---
sidebar: sidebar 
permalink: ontap-security-hardening/autosupport.html 
keywords: tr-4569, ontap hardening guide, security, proactively monitor, NetApp Digital Advisor, logs, context-sensitive data, configuration and status data, performance data, use https 
summary: 'La fonctionnalité AutoSupport de ONTAP vous permet de surveiller de manière proactive l"état de votre système.' 
---
= NetApp AutoSupport
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media


[role="lead"]
La fonction AutoSupport de ONTAP vous permet de contrôler de manière proactive l'état de votre système et d'envoyer automatiquement des messages et des détails au support technique NetApp, à l'équipe de support interne de votre entreprise ou à un partenaire de support. Par défaut, les messages AutoSupport envoyés au support technique NetApp sont activés lorsque le système de stockage est configuré pour la première fois. De plus, AutoSupport commence à envoyer des messages au support technique NetApp 24 heures après son activation. Cette période de 24 heures est configurable. Pour tirer parti de la communication avec l'équipe de support interne d'une entreprise, la configuration de l'hôte de messagerie doit être effectuée.

Seul l'administrateur du cluster peut effectuer la gestion AutoSupport (configuration). L'administrateur du SVM n'a pas accès à AutoSupport. La fonction AutoSupport peut être désactivée. Toutefois, NetApp recommande de l'activer, car AutoSupport accélère l'identification et la résolution des problèmes en cas de problème sur le système de stockage. Par défaut, le système collecte les informations AutoSupport et les stocke localement même si vous désactivez AutoSupport.

Pour plus d'informations sur les messages AutoSupport, notamment sur ce qui se trouve dans les différents messages et sur l'emplacement d'envoi des différents types de messages, reportez-vous à la link:https://activeiq.netapp.com/custom-dashboard/search["Conseiller digital NetApp"^] documentation.

Les messages AutoSupport contiennent des données sensibles, notamment, mais sans s'y limiter, les éléments suivants :

* Fichiers journaux
* Données contextuelles concernant des sous-systèmes spécifiques
* Données de configuration et d'état
* Les données de performance


AutoSupport prend en charge les protocoles de transport HTTPS, HTTP et SMTP. En raison des nature sensibles des messages AutoSupport, NetApp recommande fortement d'utiliser HTTPS comme protocole de transport par défaut pour l'envoi des messages AutoSupport au support NetApp.

De plus, vous devez utiliser `system node autosupport modify` la commande pour spécifier les cibles des données AutoSupport (par exemple, le support technique NetApp, les opérations internes d'une entreprise ou les partenaires). Cette commande vous permet également d'indiquer quelles informations AutoSupport spécifiques envoyer (par exemple, données de performances, fichiers journaux, etc.).

Pour désactiver entièrement AutoSupport, utilisez `system node autosupport modify -state disable` la commande.
