---
sidebar: sidebar 
permalink: ontap-security-hardening/certificate-status-protocol.html 
keywords: tr-4569, ontap hardening guide, security, certificate status, certificate, OCSP, advanced privilege level, security config ocsp enable -app name 
summary: 'Le protocole OCSP (Online Certificate Status Protocol) permet aux applications ONTAP qui utilisent des communications TLS ou LDAP de recevoir le statut du certificat numérique lorsque OCSP est activé.' 
---
= Protocole d'état du certificat en ligne
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le protocole OCSP (Online Certificate Status Protocol) permet aux applications ONTAP qui utilisent des communications TLS ou LDAP de recevoir le statut du certificat numérique lorsque OCSP est activé. L'application reçoit une réponse signée indiquant que le certificat demandé est valide, révoqué ou inconnu.

OCSP permet de déterminer le statut actuel d'un certificat numérique sans nécessiter de listes de révocation de certificats.

Par défaut, la vérification du statut du certificat OCSP est désactivée. Il peut être activé à l'aide de la commande `security config ocsp enable -app name`, où le nom de l'application peut être `autosupport`, `audit_log` `fabricpool` `ems`, , , , , `kmip` `ldap_ad` `ldap_nis_namemap`, , ou `all`. La commande nécessite un niveau de privilège avancé.
