---
sidebar: sidebar 
permalink: ontap-security-hardening/image-validation.html 
keywords: tr-4569, ontap hardening guide, image validation, software validation, boot time 
summary: Validation des images ONTAP 
---
= Validation des images ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP fournit des mécanismes permettant de s'assurer que l'image ONTAP est valide lors de la mise à niveau et au démarrage.



== Validation des images de mise à niveau

La signature de code permet de vérifier que les images ONTAP installées via des mises à jour d'images sans interruption ou des mises à jour d'images automatisées sans interruption, des interfaces de ligne de commande ou des API ONTAP sont produites de manière authentique par NetApp et n'ont pas été falsifiées. La validation des images de mise à niveau a été introduite dans ONTAP 9.3.

Cette fonction est une amélioration de la sécurité sans intervention de la mise à niveau ou de la restauration ONTAP. L'utilisateur ne doit rien faire différemment, sauf pour vérifier éventuellement la signature de premier niveau `image.tgz` .



== Validation de l'image de démarrage

À partir de ONTAP 9.4, le démarrage sécurisé UEFI (Unified extensible Firmware interface) est activé pour les systèmes NetApp AFF A800, AFF A220, FAS2750 et FAS2720, ainsi que pour les systèmes nouvelle génération qui utilisent le BIOS UEFI.

Lors de la mise sous tension, le chargeur d'amorçage valide la base de données de la liste blanche des clés d'amorçage sécurisées avec la signature associée à chaque module chargé. Une fois que chaque module est validé et chargé, le processus de démarrage continue avec l'initialisation ONTAP. Si la validation de la signature échoue pour un module, le système redémarre.


NOTE: Ces éléments s'appliquent aux images ONTAP et au BIOS de la plate-forme.
