---
sidebar: sidebar 
permalink: ontap-security-hardening/lif-security.html 
keywords: tr-4569, ontap hardening guide, Data LIF, Cluster LIF, Node management LIF, Cluster management LIF, Intercluster LIF, requires private IP subnet, requires secure network, default firewall policy, is the firewall customizable, under no circumstance should any LIF roles be exposed to the internet 
summary: Comprendre les caractéristiques de sécurité de chaque rôle de LIF. 
---
= Caractéristiques de sécurité des rôles LIF dans ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Une LIF est une adresse IP ou un nom de port mondial (WWPN) avec des caractéristiques associées, telles qu'un rôle, un port d'attache, un nœud d'attache, une liste de ports à basculer et une politique de pare-feu. Vous pouvez configurer les LIF sur les ports sur lesquels le cluster envoie et reçoit des communications sur le réseau. Il est essentiel de comprendre les caractéristiques de sécurité de chaque rôle de LIF.



== Rôles LIF

Les rôles LIF peuvent être les suivants :

* *Data LIF* : une LIF associée à un SVM et utilisée pour communiquer avec les clients.
* *Cluster LIF* : une LIF utilisée pour transporter le trafic intracluster entre les nœuds d'un cluster.
* *Node management LIF* : une LIF qui fournit une adresse IP dédiée pour la gestion d'un nœud particulier dans un cluster.
* *Cluster management LIF* : une LIF qui fournit une interface de gestion unique pour l'ensemble du cluster.
* *Intercluster LIF* : une LIF utilisée pour la communication, la sauvegarde et la réplication entre clusters.




== Caractéristiques de sécurité de chaque rôle de LIF

[cols="21%,13%,14%,18%,18%,16%"]
|===
|  | LIF de données | LIF Cluster | FRV de gestion des nœuds | LIF de gestion de cluster | FRV InterCluster 


| Nécessite un sous-réseau IP privé ? | Non | Oui. | Non | Non | Non 


| Nécessite un réseau sécurisé ? | Non | Oui. | Non | Non | Oui. 


| Politique de pare-feu par défaut | Très restrictif | Entièrement ouvert | Moyen | Moyen | Très restrictif 


| Le pare-feu est-il personnalisable ? | Oui. | Non | Oui. | Oui. | Oui. 
|===
[IMPORTANT]
====
* La LIF de cluster étant complètement ouverte sans règle de pare-feu configurable, elle doit se trouver sur un sous-réseau IP privé sur un réseau isolé et sécurisé.
* Les rôles LIF ne doivent jamais être exposés à Internet.


====
Pour en savoir plus sur la sécurisation des LIF, consultez le link:../networking/configure_firewall_policies_for_lifs.html["Configuration des politiques de pare-feu pour les LIF"].
