---
sidebar: sidebar 
permalink: ontap-security-hardening/ntp.html 
keywords: tr-4569, ontap hardening guide, time synchronize, NTP servers, symmetric authentication, cluster time-service ntp server create 
summary: 'Vous devez configurer les serveurs NTP (Network Time Protocol) afin de synchroniser l"heure du cluster avec au moins trois serveurs NTP externes.' 
---
= Protocole de temps réseau
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media


[role="lead"]
Bien que ONTAP vous permette de définir manuellement le fuseau horaire, la date et l'heure sur le cluster, vous devez configurer les serveurs NTP (Network Time Protocol) afin de synchroniser l'heure du cluster avec au moins trois serveurs NTP externes.

Les problèmes peuvent survenir lorsque l'heure du cluster est incorrecte. Bien que ONTAP vous permette de définir manuellement le fuseau horaire, la date et l'heure sur le cluster, vous devez configurer les serveurs NTP (Network Time Protocol) afin de synchroniser l'heure du cluster avec les serveurs NTP externes.

Depuis ONTAP 9.5, vous pouvez configurer votre serveur NTP avec une authentification symétrique.

Vous pouvez associer un maximum de 10 serveurs NTP externes à l'aide de la `cluster time-service ntp server create` commande. Pour la redondance et la qualité du service de temps, vous devez associer au moins trois serveurs NTP externes au cluster.

Pour plus de détails sur la configuration de NTP dans ONTAP, reportez-vous à la section link:../system-admin/manage-cluster-time-concept.html["Gestion de l'heure du cluster (administrateurs du cluster uniquement)"].
