---
sidebar: sidebar 
permalink: ontap-security-hardening/snapshot-copy-locking.html 
keywords: tr-4569, ontap hardening guide,security, snapshot copy locking, tamper-proof snapshot, tamperproof, tamper proof 
summary: Le verrouillage des copies Snapshot empêche la suppression des copies Snapshot grâce à la technologie SnapLock. 
---
= Verrouillage des copies Snapshot
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le verrouillage des snapshots est une fonctionnalité SnapLock dans laquelle les snapshots sont rendus indélébiles manuellement ou automatiquement avec une période de conservation définie dans la règle Snapshot du volume. Le verrouillage des snapshots permet d'empêcher les administrateurs peu scrupuleux ou non approuvés de supprimer des snapshots sur le système ONTAP principal ou secondaire.

Le verrouillage des snapshots a été introduit dans ONTAP 9.12.1. Le verrouillage des snapshots est également appelé verrouillage inviolable des snapshots. Bien qu'il nécessite la licence SnapLock et l'initialisation de l'horloge de conformité, le verrouillage des snapshots n'est pas lié à SnapLock Compliance ou SnapLock Enterprise. Il n'existe aucun administrateur de confiance dans le stockage, comme pour SnapLock Enterprise, et il ne protège pas l'infrastructure de stockage physique sous-jacente, comme pour SnapLock Compliance. Il s'agit d'une amélioration par rapport aux snapshots SnapVauting sur un système secondaire. La restauration rapide des copies Snapshot verrouillées sur les systèmes primaires peut être effectuée pour restaurer les volumes corrompus par des ransomwares.

Pour plus de détails, voir link:../snaplock/snapshot-lock-concept.html["documentation sur le verrouillage des snapshots"].
