---
sidebar: sidebar 
permalink: authentication-access-control/enable-webauthn-mfa-task.html 
keywords: mfa, multi-factor, authentication, authorization, webauthn, FIDO2, hardware key, enable, system manager 
summary: Vous pouvez activer WebAuthn MFA pour les utilisateurs de System Manager. 
---
= Activez WebAuthn MFA pour les utilisateurs ou les groupes ONTAP System Manager
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
En tant qu'administrateur ONTAP, vous pouvez activer l'authentification WebAuthn MFA pour un utilisateur ou un groupe du Gestionnaire système en ajoutant un nouvel utilisateur ou un nouveau groupe avec l'option WebAuthn MFA activée ou en activant l'option pour un utilisateur ou un groupe existant.


NOTE: Après avoir activé WebAuthn MFA comme deuxième méthode d'authentification pour un utilisateur ou un groupe, l'utilisateur (ou tous les utilisateurs de ce groupe) sera invité à enregistrer un périphérique FIDO2 matériel lors de la prochaine connexion à System Manager. Cet enregistrement est géré par le système d'exploitation local de l'utilisateur et consiste généralement à insérer la clé de sécurité, à créer une clé d'authentification et à appuyer sur la clé de sécurité (si elle est prise en charge).



== Activez WebAuthn MFA lors de la création d'un nouvel utilisateur ou d'un nouveau groupe

Vous pouvez créer un nouvel utilisateur ou un nouveau groupe avec l'authentification WebAuthn MFA activée via System Manager ou l'interface de ligne de commande ONTAP.

[role="tabbed-block"]
====
.System Manager
--
. Sélectionnez *Cluster > Paramètres*.
. Sélectionnez l'icône en forme de flèche en regard de *utilisateurs et rôles*.
. Sélectionnez *Ajouter* sous *utilisateurs*.
. Spécifiez un nom d'utilisateur ou de groupe et sélectionnez un rôle dans le menu déroulant pour *role*.
. Spécifiez une méthode de connexion et un mot de passe pour l'utilisateur ou le groupe.
+
WebAuthn MFA prend en charge les méthodes de connexion « password », « domain » ou « nsswitch » pour les utilisateurs, et « domain » ou « nsswitch » pour les groupes.

. Dans la colonne *MFA pour HTTP*, sélectionnez *Enabled*.
. Sélectionnez *Enregistrer*.


--
.CLI
--
. Créez un nouvel utilisateur ou un nouveau groupe avec WebAuthn MFA activé.
+
Dans l'exemple suivant, WebAuthn MFA est activé en choisissant "publickey" pour la deuxième méthode d'authentification :

+
[source, console]
----
security login create -user-or-group-name <user_or_group_name> \
                     -authentication-method domain \
                     -second-authentication-method publickey \
                     -application http \
                     -role admin
----


--
====


== Activez WebAuthn MFA pour un utilisateur ou un groupe existant

Vous pouvez activer WebAuthn MFA pour un utilisateur ou un groupe existant.

[role="tabbed-block"]
====
.System Manager
--
. Sélectionnez *Cluster > Paramètres*.
. Sélectionnez l'icône en forme de flèche en regard de *utilisateurs et rôles*.
. Dans la liste des utilisateurs et des groupes, sélectionnez le menu d'options de l'utilisateur ou du groupe que vous souhaitez modifier.
+
WebAuthn MFA prend en charge les méthodes de connexion « password », « domain » ou « nsswitch » pour les utilisateurs, et « domain » ou « nsswitch » pour les groupes.

. Dans la colonne *MFA pour HTTP* de cet utilisateur, sélectionnez *activé*.
. Sélectionnez *Enregistrer*.


--
.CLI
--
. Modifiez un utilisateur ou un groupe existant pour activer WebAuthn MFA pour cet utilisateur ou ce groupe.
+
Dans l'exemple suivant, WebAuthn MFA est activé en choisissant "publickey" pour la deuxième méthode d'authentification :

+
[source, console]
----
security login modify -user-or-group-name <user_or_group_name> \
                     -authentication-method domain \
                     -second-authentication-method publickey \
                     -application http \
                     -role admin
----


--
====
Pour en savoir plus sur `security login create` et `security login modify` dans le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+login["Référence de commande ONTAP"^].
