---
sidebar: sidebar 
permalink: authentication-access-control/webauthn-mfa-overview.html 
keywords: mfa, multi-factor, multifactor, authentication, authorization, webauthn, FIDO2, hardware key 
summary: À partir de ONTAP 9.16.1, vous pouvez activer WebAuthn MFA pour les utilisateurs de ONTAP. 
---
= Découvrez l'authentification multifacteur WebAuthn pour les utilisateurs d'ONTAP System Manager
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
À partir d'ONTAP 9.16.1, les administrateurs peuvent activer l'authentification multifacteur (MFA) WebAuthn pour les utilisateurs qui se connectent à System Manager. Cela permet la connexion à System Manager à l'aide d'une clé FIDO2 (telle qu'une YubiKey) comme deuxième forme d'authentification. Par défaut, la MFA WebAuthn est désactivée pour les nouveaux utilisateurs et les utilisateurs existants d'ONTAP.

[NOTE]
====
À partir d'ONTAP 9.19.1, les administrateurs doivent utiliser le paramètre  `-rp-domains` dans la commande des paramètres globaux WebAuthn. Cela permet aux administrateurs de restreindre explicitement l'ensemble des domaines Relying Party (RP) autorisés lors de l'authentification multifacteur WebAuthn (FIDO2) dans System Manager. Si vous effectuez une mise à niveau vers ONTAP 9.19.1 depuis ONTAP 9.16.1 à 9.18.1, consultez link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-Issues/CONTAP-597688["CONTAP-597688"] pour plus d'informations.

====
WebAuthn MFA est pris en charge pour les utilisateurs et les groupes qui utilisent les types d'authentification suivants pour la première méthode d'authentification :

* Utilisateurs : mot de passe, domaine ou nsswitch
* Groupes : domaine ou nsswitch


Après avoir activé WebAuthn MFA comme deuxième méthode d'authentification pour un utilisateur, l'utilisateur est invité à enregistrer un authentificateur matériel lors de sa connexion à System Manager. Après l'enregistrement, la clé privée est stockée dans l'authentificateur et la clé publique est stockée dans ONTAP.

ONTAP prend en charge une autorisation WebAuthn par utilisateur. Si un utilisateur perd un authentificateur et doit le remplacer, l'administrateur ONTAP doit supprimer les informations d'identification WebAuthn pour que l'utilisateur puisse enregistrer un nouvel authentificateur lors de la prochaine connexion.


NOTE: Les utilisateurs pour lesquels WebAuthn MFA "https://192.168.100.200"[]est activé comme deuxième méthode d'authentification doivent utiliser le FQDN (par exemple, "https://myontap.example.com"[]) au lieu de l'adresse IP (par exemple, ) pour accéder à System Manager. Pour les utilisateurs avec WebAuthn MFA activé, les tentatives de connexion à System Manager à l'aide de l'adresse IP sont rejetées.
