---
sidebar: sidebar 
permalink: ransomware-solutions/ransomware-snaplock-tamperproof-snapshots.html 
keywords: tr-4572, technical report, ransomware, protect, protection, netapp ransomware protection, netapp tr, ontap tr 
summary: La protection contre les ransomwares de NetApp inclut SnapLock, qui a fait ses preuves dans la protection contre les menaces de ransomware. 
---
= SnapLock et copies Snapshot inviolables pour la protection contre les ransomwares
:allow-uri-read: 


[role="lead"]
SnapLock, l'une des armes essentielles de l'arsenal de NetApp Snap, s'est avéré très efficace pour protéger les données contre les menaces de ransomware. En empêchant la suppression non autorisée des données, SnapLock fournit une couche de sécurité supplémentaire qui garantit l'intégrité et l'accessibilité des données critiques, même en cas d'attaques malveillantes.



== Conformité SnapLock

SnapLock Compliance (SLC) assure une protection indélébile de vos données. SLC interdit la suppression de données même lorsqu'un administrateur tente de réinitialiser la baie. Contrairement à d'autres produits concurrents, SnapLock Compliance n'est pas vulnérable aux piratages d'ingénierie sociale par l'intermédiaire des équipes de support de ces produits. Les données protégées par des volumes SnapLock Compliance peuvent être récupérables jusqu'à leur date d'expiration.

Pour activer SnapLock, une link:../system-admin/manage-licenses-concept.html["ONTAP One"] licence est requise.

.En savoir plus >>
* link:../snaplock/index.html["Documentation SnapLock"]




== Copies Snapshot inviolables

Les copies Snapshot inviolables constituent un moyen pratique et rapide de protéger vos données contre les actes malveillants. Contrairement à SnapLock Compliance, TPS est généralement utilisé sur les systèmes principaux où l'utilisateur peut protéger les données pendant un temps déterminé et les laisser localement pour des restaurations rapides ou où les données n'ont pas besoin d'être répliquées hors du système principal. TPS utilise les technologies SnapLock pour empêcher la suppression de la copie Snapshot primaire, même par un administrateur ONTAP, pendant la même période d'expiration de la conservation SnapLock. La suppression de copie Snapshot est impossible même si le volume n'est pas activé sur SnapLock, bien que les snapshots ne possèdent pas la même nature indélébile que les volumes SnapLock Compliance.

Pour que les copies Snapshot soient inviolables, une link:../system-admin/manage-licenses-concept.html["ONTAP One"] licence est requise.

.En savoir plus >>
* link:../snaplock/snapshot-lock-concept.html["Verrouillez une copie Snapshot pour vous protéger contre les attaques par ransomware"].

