---
permalink: s3-config/configure-access-ldap.html 
sidebar: sidebar 
keywords: tr-4814, generate, ldap, s3, access keys, secret keys using API 
summary: 'Les clés permettant d"accéder aux clients S3 peuvent être régénérées par les utilisateurs S3 à l"aide d"une API.' 
---
= Configurez les services d'annuaire externes pour l'accès ONTAP S3
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis ONTAP 9.14.1, les services pour les répertoires externes ont été intégrés au stockage objet ONTAP S3. Cette intégration simplifie la gestion des utilisateurs et des accès via des services d'annuaire externes.

Vous pouvez fournir des groupes d'utilisateurs appartenant à un service d'annuaire externe ayant accès à votre environnement de stockage objet ONTAP. Le protocole LDAP (Lightweight Directory Access Protocol) est une interface permettant de communiquer avec des services d'annuaire, tels qu'Active Directory, qui fournit une base de données et des services de gestion des identités et des accès (IAM). Pour y accéder, vous devez configurer les groupes LDAP dans votre environnement ONTAP S3. Une fois l'accès configuré, les membres du groupe disposent des autorisations nécessaires pour les compartiments ONTAP S3. Pour plus d'informations sur LDAP, reportez-vous à link:../nfs-config/using-ldap-concept.html["En savoir plus sur l'utilisation des services de noms LDAP sur les SVM ONTAP NFS"]la section .

Vous pouvez également configurer des groupes d'utilisateurs Active Directory en mode de liaison rapide, de sorte que les informations d'identification des utilisateurs puissent être validées et que les applications S3 tierces et open source puissent être authentifiées via des connexions LDAP.

.Avant de commencer
Avant de configurer les groupes LDAP et d'activer le mode de liaison rapide pour l'accès aux groupes, vérifiez les points suivants :

. Une VM de stockage compatible S3 contenant un serveur S3 a été créée. Voir link:../s3-config/create-svm-s3-task.html["Création d'un SVM pour S3"].
. Un compartiment a été créé dans cette VM de stockage. Voir link:../s3-config/create-bucket-task.html["Créer un compartiment"].
. DNS est configuré sur la machine virtuelle de stockage. Voir link:../networking/configure_dns_services_auto.html["Configurez les services DNS"].
. Un certificat d'autorité de certification racine (CA) auto-signé du serveur LDAP est installé sur la machine virtuelle de stockage. Voir link:../nfs-config/install-self-signed-root-ca-certificate-svm-task.html["Installer des certificats d'autorité de certification racine auto-signés sur la SVM"].
. Un client LDAP est configuré avec TLS activé sur le SVM. Voir link:../nfs-config/create-ldap-client-config-task.html["Créer des configurations de client LDAP pour l'accès NFS ONTAP"] et link:../nfs-config/enable-ldap-svms-task.html["Associez les configurations client LDAP aux SVM NFS ONTAP pour plus d'informations"].




== Configurez l'accès S3 pour LDAP

. Préciser LDAP comme _NAME service database_ du SVM pour le groupe et password pour LDAP:
+
[listing]
----
ns-switch modify -vserver <vserver-name> -database group -sources files,ldap
ns-switch modify -vserver <vserver-name> -database passwd -sources files,ldap
----
+
Pour en savoir plus sur la commande link:https://docs.NetApp.com/US-en/ONTAP-cli/vserver-services-name-service-ns-switch-modify.html[`vserver services name-service ns-switch modify`^], consultez la référence de commande ONTAP.

. Créez une instruction de stratégie de compartiment de magasin d'objets avec `principal` Sélectionnez le groupe LDAP auquel vous souhaitez accorder l'accès :
+
[listing]
----
object-store-server bucket policy statement create -bucket <bucket-name> -effect allow -principal nasgroup/<ldap-group-name> -resource <bucket-name>, <bucket-name>/*
----
+
Exemple : l'exemple suivant crée une instruction de politique de compartiment pour `buck1`. La stratégie autorise l'accès au groupe LDAP `group1` à la ressource (compartiment et ses objets) `buck1`.

+
[listing]
----
vserver object-store-server bucket policy add-statement -bucket buck1 -effect allow -action
GetObject,PutObject,DeleteObject,ListBucket,GetBucketAcl,GetObjectAcl,ListBucketMultipartUploads,ListMultipartUploadParts, ListBucketVersions,GetObjectTagging,PutObjectTagging,DeleteObjectTagging,GetBucketVersioning,PutBucketVersioning -principal nasgroup/group1 -resource buck1, buck1/*
----
. Vérifiez qu'un utilisateur du groupe LDAP `group1` Est capable d'effectuer des opérations S3 à partir du client S3.




== Utilisez le mode de liaison rapide LDAP pour l'authentification

. Préciser LDAP comme _NAME service database_ du SVM pour le groupe et password pour LDAP:
+
[listing]
----
ns-switch modify -vserver <vserver-name> -database group -sources files,ldap
ns-switch modify -vserver <vserver-name> -database passwd -sources files,ldap
----
+
Pour en savoir plus sur la commande link:https://docs.NetApp.com/US-en/ONTAP-cli/vserver-services-name-service-ns-switch-modify.html[`vserver services name-service ns-switch modify`^], consultez la référence de commande ONTAP.

. Assurez-vous qu'un utilisateur LDAP accédant au compartiment S3 dispose des autorisations définies dans les règles de compartiment. Pour plus d'informations, voir link:../s3-config/create-modify-bucket-policy-task.html["Modifier une règle de compartiment"].
. Vérifiez qu'un utilisateur du groupe LDAP peut effectuer les opérations suivantes :
+
.. Configurez la clé d'accès sur le client S3 au format suivant : exemple `"NTAPFASTBIND"` :
`"NTAPFASTBIND" + base64-encode(user-name:password)` + base64-encode(ldapuser:password), ce qui en résulte
`NTAPFASTBINDbGRhcHVzZXI6cGFzc3dvcmQ=`
+

NOTE: Le client S3 peut vous inviter à saisir une clé secrète. En l'absence d'une clé secrète, vous pouvez saisir un mot de passe d'au moins 16 caractères.

.. Effectuez des opérations S3 de base à partir du client S3 pour lequel l'utilisateur dispose des autorisations nécessaires.






=== Identifiants Base64

La configuration par défaut de ONTAP S3 exclut HTTP et utilise exclusivement HTTPS et une connexion TLS (transport Layer Security). ONTAP peut générer des certificats auto-signés, mais il est recommandé d'utiliser les certificats d'une autorité de certification tierce. Lorsque vous utilisez des certificats d'autorité de certification, vous créez une relation de confiance entre les applications clientes et le serveur de magasin d'objets ONTAP.

Sachez que les informations d'identification codées à l'aide de Base64 sont facilement décodées. L'utilisation du protocole HTTPS empêche les informations d'identification codées d'être capturées par les renifleurs de paquets MAN-in-the-middle.

N'utilisez pas le mode de liaison rapide LDAP pour l'authentification lors de la création d'URL pré-signées. L'authentification est basée exclusivement sur la clé d'accès Base64 incluse dans l'URL présignée. Le nom d'utilisateur et le mot de passe seront divulgués à toute personne qui décochera la clé d'accès Base64.



=== La méthode d'authentification est nsswitch et LDAP est activé exemple

[listing]
----
$curl -siku <user>:<user_password> -X POST https://<LIF_IP_Address>/api/protocols/s3/services/<SVM_UUID>/users -d {"comment":"<S3_user_name>", "name":<user>,"key_time_to_live":"PT6H3M"}
----

NOTE: Orienter l'API vers la LIF de cluster management, et non vers la LIF de données du SVM. Si vous souhaitez autoriser les utilisateurs à générer leurs propres clés, vous devez ajouter des autorisations HTTP à leur rôle pour utiliser curl. Cette autorisation vient en complément des autorisations de l'API S3.



== Configurer l'accès S3 pour les serveurs Active Directory ou SMB

Si le groupe nasgroup spécifié dans l'instruction de stratégie de compartiment ou si les utilisateurs qui font partie du groupe nasgroup n'ont pas d'UID et de GID définis, les recherches échouent lorsque ces attributs ne sont pas trouvés. Active Directory utilise SID et non UID. Si les entrées SID ne peuvent pas être mappées à l'UID, les données nécessaires doivent être transférées à ONTAP.

Pour ce faire, utiliser link:../authentication/enable-ad-users-groups-access-cluster-svm-task.html["vserver active-directory create"] afin que le SVM puisse s'authentifier auprès d'Active Directory et obtenir les informations nécessaires sur les utilisateurs et les groupes.

Vous pouvez également utiliser link:../authentication/enable-ad-users-groups-access-cluster-svm-task.html["création d'un vserver cifs"] pour créer un serveur SMB dans un domaine Active Directory.

Si vous utilisez des noms de domaine différents pour les serveurs de noms et les magasins d'objets, des échecs de recherche peuvent survenir. Pour éviter ces échecs, NetApp recommande d'utiliser des domaines de confiance pour l'autorisation des ressources au format UPN :  `nasgroup/group@trusted_domain.com` Les domaines de confiance sont ceux ajoutés à la liste des domaines de confiance du serveur SMB. Découvrez comment link:../smb-admin/add-remove-replace-trusted-domains-preferred-lists-task.html["ajouter, supprimer et modifier les domaines de confiance préférés"] dans la liste des serveurs SMB.



=== Générez des clés lorsque la méthode d'authentification est domaine et que les domaines de confiance sont configurés dans Active Directory

Utilisez le `s3/services/<svm_uuid>/users` noeud final avec les utilisateurs spécifiés au format UPN. Exemple :

[listing]
----
$curl -siku FQDN\\user:<user_password> -X POST https://<LIF_IP_Address>/api/protocols/s3/services/<SVM_UUID>/users -d {"comment":"<S3_user_name>", "name":<user@fqdn>,"key_time_to_live":"PT6H3M"}
----

NOTE: Orienter l'API vers la LIF de cluster management, et non vers la LIF de données du SVM. Si vous souhaitez autoriser les utilisateurs à générer leurs propres clés, vous devez ajouter des autorisations HTTP à leur rôle pour utiliser curl. Cette autorisation vient en complément des autorisations de l'API S3.



=== Générez des clés lorsque la méthode d'authentification est domaine et qu'il n'y a pas de domaines de confiance

Cette action est possible lorsque LDAP est désactivé ou lorsque des utilisateurs non POSIX n'ont pas configuré UID et GID. Exemple :

[listing]
----
$curl -siku FQDN\\user:<user_password> -X POST https://<LIF_IP_Address>/api/protocols/s3/services/<SVM_UUID>/users -d {"comment":"<S3_user_name>", "name":<user[@fqdn]>,"key_time_to_live":"PT6H3M"}
----

NOTE: Orienter l'API vers la LIF de cluster management, et non vers la LIF de données du SVM. Si vous souhaitez autoriser les utilisateurs à générer leurs propres clés, vous devez ajouter des autorisations HTTP à leur rôle pour utiliser curl. Cette autorisation vient en complément des autorisations de l'API S3. Il vous suffit d'ajouter la valeur de domaine facultative (@fqdn) à un nom d'utilisateur s'il n'y a pas de domaines de confiance.
