---
permalink: s3-config/create-bucket-task.html 
sidebar: sidebar 
keywords: s3, bucket, system manager, 
summary: 'Les objets S3 sont conservés dans _buckets_. Ils ne sont pas imbriqués en tant que fichiers dans un répertoire à l"intérieur d"autres répertoires.' 
---
= Créer un compartiment
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les objets S3 sont conservés dans _buckets_. Ils ne sont pas imbriqués en tant que fichiers dans un répertoire à l'intérieur d'autres répertoires.

.Avant de commencer
Une VM de stockage contenant un serveur S3 doit déjà exister.

.Description de la tâche
* Depuis la version ONTAP 9.14.1, le redimensionnement automatique a été activé sur les volumes FlexGroup S3 lorsque des compartiments sont créés. Cela élimine l'allocation excessive de capacité lors de la création du compartiment sur les volumes FlexGroup existants et nouveaux. Les volumes FlexGroup sont redimensionnés au minimum requis selon les instructions suivantes. La taille minimale requise correspond à la taille totale de tous les compartiments S3 d'un volume FlexGroup.
+
** À partir de ONTAP 9.14.1, si un volume FlexGroup S3 est créé dans le cadre d'une nouvelle création de compartiment, le volume FlexGroup est créé avec la taille minimale requise.
** Si un volume FlexGroup S3 a été créé avant ONTAP 9.14.1, le premier compartiment créé ou supprimé après ONTAP 9.14.1 redimensionne le volume FlexGroup à la taille minimale requise.
** Si un volume FlexGroup S3 a été créé avant ONTAP 9.14.1 et disposait déjà de la taille minimale requise, la création ou la suppression d'un compartiment après ONTAP 9.14.1 conserve la taille du volume FlexGroup S3.


* Les niveaux de service de stockage sont des groupes de règles prédéfinies de qualité de service (QoS) adaptative, avec des niveaux par défaut _Value_, _performance_ et _Extreme_. Au lieu d'un des niveaux de service de stockage par défaut, vous pouvez également définir un groupe de règles de QoS personnalisé et le appliquer à un compartiment. Pour plus d'informations sur les définitions de service de stockage, reportez-vous à la section link:storage-service-definitions-reference.html["Définitions des services de stockage"]. Pour plus d'informations sur la gestion des performances, reportez-vous à la section link:../performance-admin/index.html["Gestion des performances"].
Depuis ONTAP 9.8, lorsque vous provisionnez le stockage, la QoS est activée par défaut. Vous pouvez désactiver QoS ou choisir une règle de QoS personnalisée lors du processus de provisionnement ou ultérieurement.


* Si vous configurez la hiérarchisation de la capacité locale, vous créez des compartiments et des utilisateurs dans une VM de stockage des données, et non dans la VM de stockage du système où se trouve le serveur S3.
* Pour l'accès client à distance, vous devez configurer des compartiments dans une VM de stockage compatible S3. Si vous créez un compartiment dans une machine virtuelle de stockage non compatible S3, il sera uniquement disponible pour le Tiering local.
* À partir de ONTAP 9.14.1, vous pouvez link:create-bucket-mcc-task.html["Créez un compartiment sur un agrégat en miroir ou sans miroir dans une configuration MetroCluster"].
* Pour l'interface de ligne de commandes, lorsque vous créez un compartiment, deux options de provisionnement sont disponibles :
+
** Laissez ONTAP Select les agrégats sous-jacents et les composants FlexGroup (par défaut)
+
*** ONTAP crée et configure un volume FlexGroup pour le premier compartiment en sélectionnant automatiquement les agrégats. Il sélectionne automatiquement le niveau de service le plus élevé disponible pour votre plateforme, ou vous pouvez spécifier le niveau de service de stockage. Tout compartiment supplémentaire que vous ajoutez ultérieurement dans la VM de stockage aura le même volume FlexGroup sous-jacent.
*** Vous pouvez également indiquer si le compartiment sera utilisé pour le Tiering, dans ce cas, ONTAP tente de sélectionner un support économique avec des performances optimales pour les données hiérarchisées.


** Vous sélectionnez les agrégats sous-jacents et les composants FlexGroup (nécessite des options de commande avec privilèges avancés) : vous pouvez sélectionner manuellement les agrégats sur lesquels le compartiment et le volume FlexGroup contenant doivent être créés, puis spécifier le nombre de composants sur chaque agrégat. Lors de l'ajout de compartiments supplémentaires :
+
*** Si vous spécifiez les agrégats et les composants pour un nouveau compartiment, un nouveau FlexGroup est créé pour ce nouveau compartiment.
*** Si vous ne spécifiez pas d'agrégats ni de composants pour un nouveau compartiment, le nouveau compartiment est ajouté à un FlexGroup existant.
Voir xref:../flexgroup/index.html[Gestion des volumes FlexGroup] pour en savoir plus.
+
Lorsque vous spécifiez des agrégats et des composants lors de la création d'un compartiment, aucun groupe de règles de QoS, n'est appliqué par défaut ou personnalisé. Vous pouvez le faire plus tard avec le `vserver object-store-server bucket modify` commande.

+
Voir  pour en savoir plus.

+
*Remarque :* si vous utilisez des compartiments à partir de Cloud Volumes ONTAP, vous devez utiliser la procédure CLI. Il est fortement recommandé de sélectionner manuellement les agrégats sous-jacents pour s'assurer qu'ils n'utilisent qu'un seul nœud. L'utilisation d'agrégats des deux nœuds peut avoir un impact sur les performances, car les nœuds se trouvent dans des zones de disponibilité séparées géographiquement et sont donc sujets aux problèmes de latence.









== Créez des compartiments S3 avec l'interface de ligne de commandes de ONTAP

. Si vous prévoyez de sélectionner vous-même les agrégats et les composants FlexGroup, définissez le niveau de privilège sur Avancé (sinon, le niveau de privilège admin est suffisant) : `set -privilege advanced`
. Création d'un compartiment :
+
`vserver object-store-server bucket create -vserver _svm_name_ -bucket _bucket_name_ [-size integer[KB|MB|GB|TB|PB]] [-comment text] [additional_options]`

+
Le nom de la VM de stockage peut être soit une VM de stockage de données, soit `Cluster` (Nom de la machine virtuelle de stockage du système) si vous configurez la hiérarchisation locale.

+
Si vous n'indiquez aucune option, ONTAP crée un compartiment de 800 Go avec un niveau de service défini sur le niveau le plus élevé disponible pour votre système.

+
Si vous souhaitez que ONTAP crée un compartiment en fonction de la performance ou de l'utilisation, choisissez l'une des options suivantes :

+
** niveau de service
+
Incluez le `-storage-service-level` option avec l'une des valeurs suivantes : `value`, `performance`, ou `extreme`.

** tiering
+
Incluez le `-used-as-capacity-tier true` option.



+
Pour spécifier les agrégats sur lesquels créer le volume FlexGroup sous-jacent, utilisez les options suivantes :

+
** Le `-aggr-list` Le paramètre spécifie la liste des agrégats à utiliser pour les composants de volume FlexGroup.
+
Chaque entrée de la liste crée un composant sur l'agrégat spécifié. Vous pouvez spécifier un agrégat plusieurs fois afin d'avoir plusieurs composants créés sur l'agrégat.

+
Pour assurer des performances prévisibles sur l'ensemble du volume FlexGroup, tous les agrégats doivent utiliser les mêmes configurations de type de disque et de groupe RAID.

** Le `-aggr-list-multiplier` le paramètre spécifie le nombre de fois pour effectuer l'itération sur les agrégats répertoriés avec le `-aggr-list` Paramètre lors de la création d'un volume FlexGroup.
+
La valeur par défaut du `-aggr-list-multiplier` le paramètre est 4.



. Ajout d'une « policy group » QoS le cas échéant :
+
`vserver object-store-server bucket modify -bucket _bucket_name_ -qos-policy-group _qos_policy_group_`

. Vérification de la création de compartiment :
+
`vserver object-store-server bucket show [-instance]`



.Exemple
L'exemple suivant illustre la création d'un compartiment pour la machine virtuelle de stockage `vs1` de taille `1TB` et spécifier l'agrégat :

[listing]
----
cluster-1::*> vserver object-store-server bucket create -vserver svm1.example.com -bucket testbucket -aggr-list aggr1 -size 1TB
----


== Création de compartiments S3 avec System Manager

. Ajoutez un nouveau compartiment à une machine virtuelle de stockage compatible S3.
+
.. Cliquez sur *stockage > compartiments*, puis sur *Ajouter*.
.. Entrez un nom, sélectionnez la machine virtuelle de stockage, puis entrez une taille.
+
*** Si vous cliquez sur *Enregistrer* à ce stade, un compartiment est créé avec les paramètres par défaut suivants :
+
**** L'accès au compartiment n'est accordé à aucun utilisateur, sauf si des règles de groupes sont déjà en vigueur.
+

NOTE: Vous ne devez pas utiliser l'utilisateur root S3 pour gérer le stockage objet ONTAP et partager ses autorisations, car il dispose d'un accès illimité au magasin d'objets. Créez plutôt un utilisateur ou un groupe avec les privilèges d'administration que vous attribuez.

**** Niveau de qualité de service (performance) le plus élevé disponible pour votre système


*** Cliquez sur *Enregistrer* pour créer un compartiment avec ces valeurs par défaut.








=== Configurer des autorisations et restrictions supplémentaires

Vous pouvez cliquer sur *plus d'options* pour configurer les paramètres de verrouillage d'objet, les autorisations utilisateur et le niveau de performances lorsque vous configurez le compartiment, ou vous pouvez modifier ces paramètres ultérieurement.

Si vous prévoyez d'utiliser le stockage d'objets S3 pour le Tiering FabricPool, choisissez *use pour le Tiering* (utilisez des supports à faible coût avec des performances optimales pour les données hiérarchisées) plutôt que un niveau de service de performance.

Si vous souhaitez activer la gestion des versions de vos objets pour une récupération ultérieure, sélectionnez *Activer la gestion des versions*. La gestion des versions est activée par défaut si vous activez le verrouillage des objets sur le compartiment. Pour plus d'informations sur la gestion des versions d'objet, reportez-vous à la section https://docs.aws.amazon.com/AmazonS3/latest/userguide/Versioning.html["Gestion des versions dans des compartiments S3 pour Amazon"].

À partir de la version 9.14.1, le verrouillage des objets est pris en charge par les compartiments S3. Le verrouillage des objets S3 nécessite une licence SnapLock standard. Cette licence est incluse avec https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["ONTAP One"].
Avant ONTAP One, la licence SnapLock était incluse dans le bundle sécurité et conformité. Le bundle sécurité et conformité n'est plus proposé, mais reste valide. Bien qu'ils ne soient pas encore requis, les clients existants peuvent choisir de le faire https://docs.netapp.com/us-en/ontap/system-admin/download-nlf-task.html["Passez à ONTAP One"].
Si vous activez le verrouillage d'objet sur un compartiment, vous devez https://docs.netapp.com/us-en/ontap/system-admin/manage-license-task.html["Vérifiez qu'une licence SnapLock est installée"]. Si aucune licence SnapLock n'est installée, vous devez le faire https://docs.netapp.com/us-en/ontap/system-admin/install-license-task.html["installer"] avant de pouvoir activer le verrouillage des objets.
Une fois que vous avez vérifié que la licence SnapLock est installée, pour protéger les objets de votre compartiment contre la suppression ou l'écrasement, sélectionnez *Activer le verrouillage d'objet*. Le verrouillage peut être activé sur l'ensemble des versions d'objets ou sur des versions spécifiques, et uniquement lorsque l'horloge de conformité SnapLock est initialisée pour les nœuds de cluster. Voici la procédure à suivre :

. Si l'horloge de conformité SnapLock n'est pas initialisée sur un nœud du cluster, le bouton *initialiser horloge de conformité SnapLock* apparaît. Cliquez sur *initialiser horloge de conformité SnapLock* pour initialiser l'horloge de conformité SnapLock sur les nœuds du cluster.
. Sélectionnez le mode *Governance* pour activer un verrouillage basé sur le temps qui autorise les autorisations _Write Once, Read Many (WORM)_ sur les objets. Même en mode _Governance_, les objets peuvent être supprimés par les utilisateurs administrateurs disposant d'autorisations spécifiques.
. Sélectionnez le mode *conformité* si vous souhaitez affecter des règles plus strictes de suppression et de mise à jour des objets. Dans ce mode de verrouillage d'objet, les objets ne peuvent être expirés qu'à la fin de la période de conservation spécifiée. À moins qu'une période de conservation ne soit spécifiée, les objets restent verrouillés indéfiniment.
. Spécifiez la durée de conservation du verrou en jours ou en années si vous souhaitez que le verrouillage soit effectif pendant une certaine période.
+

NOTE: Le verrouillage s'applique aux compartiments S3 avec et sans version. Le verrouillage d'objet ne s'applique pas aux objets NAS.



Vous pouvez configurer les paramètres de protection et d'autorisation, ainsi que le niveau de service de performances du compartiment.


NOTE: Vous devez avoir déjà créé un utilisateur et des groupes avant de configurer les autorisations.

Pour plus d'informations, voir link:../s3-snapmirror/create-remote-mirror-new-bucket-task.html["Créer un miroir pour le nouveau godet"].



=== Vérifier l'accès au godet

Sur les applications client S3 (ONTAP S3 ou une application tierce externe), vous pouvez vérifier votre accès au nouveau compartiment en saisissant les informations suivantes :

* Certificat CA de serveur S3.
* La clé d'accès et la clé secrète de l'utilisateur.
* Nom de domaine complet du serveur S3 et nom de compartiment.

