---
permalink: s3-config/create-data-lifs-task.html 
sidebar: sidebar 
keywords: tr-4814, create, data, lifs 
summary: Si vous avez créé un nouveau SVM, les LIF dédiées que vous créez pour accéder à S3 doivent être des LIF de données. 
---
= Création des LIF de données pour ONTAP S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous avez créé un nouveau SVM, les LIF dédiées que vous créez pour accéder à S3 doivent être des LIF de données.

.Avant de commencer
* Le port réseau physique ou logique sous-jacent doit avoir été configuré sur le `up` statut administratif. Pour en savoir plus, `up` consultez le link:https://docs.netapp.com/us-en/ontap-cli/up.html["Référence de commande ONTAP"^].
* Si vous prévoyez d'utiliser un nom de sous-réseau pour allouer la valeur de l'adresse IP et du masque de réseau à une LIF, le sous-réseau doit déjà exister.
+
Les sous-réseaux contiennent un pool d'adresses IP qui appartiennent au même sous-réseau de couche 3. Ils sont créés à l'aide du `network subnet create` commande.

* La politique de service LIF doit déjà exister.
* Dans le cadre de la bonne pratique, les LIF utilisées pour l'accès aux données (serveur-données-s3) et les LIF utilisées pour les opérations de gestion (management-https) doivent être séparées. Les deux services ne doivent pas être activés sur la même LIF.
* Les enregistrements DNS ne doivent contenir que des adresses IP des LIFs dont le serveur-s3-données est associé. Si les adresses IP des autres LIFs sont spécifiées dans l'enregistrement DNS, les requêtes ONTAP S3 peuvent être servies par d'autres serveurs ce qui provoque des réponses inattendues ou une perte de données.


.Description de la tâche
* Vous pouvez créer des LIF IPv4 et IPv6 sur le même port réseau.
* Si vous disposez d'un grand nombre de LIF dans le cluster, vous pouvez vérifier la capacité LIF prise en charge sur le cluster à l'aide de `network interface capacity show` Et la capacité LIF prise en charge sur chaque nœud à l'aide de `network interface capacity details show` commande (au niveau de privilège avancé).
+
Pour en savoir plus sur `network interface capacity show` et `network interface capacity details show` dans le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface+capacity+show["Référence de commande ONTAP"^].

* Si vous activez la hiérarchisation distante de la capacité FabricPool (cloud), vous devez également configurer les LIF intercluster.


.Étapes
. Créer une LIF :
+
`network interface create -vserver _svm_name_ -lif _lif_name_ -service-policy _service_policy_names_ -home-node _node_name_ -home-port _port_name_ {-address _IP_address_ -netmask _IP_address_ | -subnet-name _subnet_name_} -firewall-policy data -auto-revert {true|false}`

+
** `-home-node` Est le nœud vers lequel la LIF renvoie lorsque `network interface revert` La commande est exécutée sur le LIF.
+
Pour en savoir plus, `network interface revert` consultez le link:https://docs.netapp.com/us-en/ontap-cli/network-interface-revert.html["Référence de commande ONTAP"^].

+
Vous pouvez également indiquer si la LIF doit revenir automatiquement au nœud home et au port home-port avec le `-auto-revert` option.

** `-home-port` Est le port physique ou logique vers lequel la LIF renvoie lorsque `network interface revert` La commande est exécutée sur le LIF.
** Vous pouvez spécifier une adresse IP avec le `-address` et `-netmask` ou vous activez l'allocation à partir d'un sous-réseau avec le `-subnet_name` option.
** Lors de l'utilisation d'un sous-réseau pour fournir l'adresse IP et le masque de réseau, si le sous-réseau a été défini avec une passerelle, une route par défaut vers cette passerelle est ajoutée automatiquement au SVM lorsqu'une LIF est créée à l'aide de ce sous-réseau.
** Si vous attribuez des adresses IP manuellement (sans utiliser de sous-réseau), vous devrez peut-être configurer une route par défaut vers une passerelle si des clients ou des contrôleurs de domaine se trouvent sur un autre sous-réseau IP. Pour en savoir plus sur `network route create` et créer une route statique au sein d'une SVM, consultez la link:https://docs.netapp.com/us-en/ontap-cli/network-route-create.html["Référence de commande ONTAP"^].
** Pour le `-firewall-policy` utilisez la même option par défaut `data` Comme le rôle LIF.
+
Vous pouvez créer et ajouter une stratégie de pare-feu personnalisée ultérieurement si vous le souhaitez.

+

NOTE: Depuis ONTAP 9.10.1, les politiques de pare-feu sont obsolètes et intégralement remplacées par les politiques de service de LIF. Pour plus d'informations, voir link:../networking/configure_firewall_policies_for_lifs.html["Configuration des politiques de pare-feu pour les LIF"].

** `-auto-revert` Vous permet de spécifier si une LIF de données est automatiquement rétablie sur le nœud de rattachement en cas de démarrage, de modifications du statut de la base de données de gestion ou lors de la connexion réseau. Le paramètre par défaut est `false`, mais vous pouvez le définir sur `false` selon les stratégies de gestion de réseau de votre environnement.
** Le `-service-policy` spécifie la stratégie de données et de services de gestion que vous avez créée ainsi que les autres règles dont vous avez besoin.


. Si vous souhaitez attribuer une adresse IPv6 dans `-address` option :
+
.. Utilisez le `network ndp prefix show` Commande permettant d'afficher la liste des préfixes de RA apprises sur diverses interfaces.
+
Le `network ndp prefix show` la commande est disponible au niveau de privilège avancé.

.. Utiliser le format `prefix:id` Pour construire l'adresse IPv6 manuellement.
+
`prefix` est le préfixe utilisé sur les différentes interfaces.

+
Pour calculer le `id`, choisissez un nombre hexadécimal 64 bits aléatoire.



. Vérifier que le LIF a été créé avec succès en utilisant le `network interface show` commande.
. Vérifiez que l'adresse IP configurée est accessible :
+
[cols="2*"]
|===
| Pour vérifier... | Utiliser... 


 a| 
Adresse IPv4
 a| 
`network ping`



 a| 
Adresse IPv6
 a| 
`network ping6`

|===


.Exemples
La commande suivante montre comment créer une LIF de données S3 attribuée avec le `my-S3-policy` règle de service :

[listing]
----
network interface create -vserver svm1.example.com -lif lif2 -home-node node2 -homeport e0d -service-policy my-S3-policy -subnet-name ipspace1
----
La commande suivante affiche toutes les LIFs du cluster-1. Les LIF de données datalif1 et datalif3 sont configurées avec des adresses IPv4 et le datalif4 est configuré avec une adresse IPv6 :

[listing]
----
cluster-1::> network interface show

            Logical    Status     Network          Current      Current Is
Vserver     Interface  Admin/Oper Address/Mask     Node         Port    Home
----------- ---------- ---------- ---------------- ------------ ------- ----
cluster-1
            cluster_mgmt up/up    192.0.2.3/24     node-1       e1a     true
node-1
            clus1        up/up    192.0.2.12/24    node-1       e0a     true
            clus2        up/up    192.0.2.13/24    node-1       e0b     true
            mgmt1        up/up    192.0.2.68/24    node-1       e1a     true
node-2
            clus1        up/up    192.0.2.14/24    node-2       e0a     true
            clus2        up/up    192.0.2.15/24    node-2       e0b     true
            mgmt1        up/up    192.0.2.69/24    node-2       e1a     true
vs1.example.com
            datalif1     up/down  192.0.2.145/30   node-1       e1c     true
vs3.example.com
            datalif3     up/up    192.0.2.146/30   node-2       e0c     true
            datalif4     up/up    2001::2/64       node-2       e0c     true
5 entries were displayed.
----
.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/network-ping.html["ping réseau"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["interface réseau"^]
* link:https://docs.netapp.com/us-en/ontap-cli/network-ndp-prefix-show.html["préfixe npd réseau affiché"^]

