---
permalink: s3-config/create-s3-service-data-policy-task.html 
sidebar: sidebar 
keywords: create, s3, service, data, policy 
summary: Vous pouvez créer des règles de service pour les données S3 et les services de gestion. Une règle de données de service S3 est nécessaire pour activer le trafic de données S3 sur les LIF. 
---
= Création de la stratégie de données du service ONTAP S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer des règles de service pour les données S3 et les services de gestion. Une règle de données de service S3 est nécessaire pour activer le trafic de données S3 sur les LIF.

.Description de la tâche
Une politique de données de service S3 est requise si vous utilisez des LIF de données et des LIF intercluster. Il n'est pas nécessaire d'utiliser des LIF de cluster pour la hiérarchisation locale.

Lorsqu'une politique de services est spécifiée pour une LIF, cette règle est utilisée pour construire un rôle par défaut, une politique de basculement et une liste de protocoles de données pour la LIF.

Bien que plusieurs protocoles puissent être configurés pour les SVM et les LIF, il est recommandé de configurer S3 comme le seul protocole lors du service des données d'objet.

.Étapes
. Modifiez le paramètre de privilège sur avancé :
+
`set -privilege advanced`

. Création d'une règle de données de service :
+
`network interface service-policy create -vserver _svm_name_ -policy _policy_name_ -services data-core,data-s3-server`

+
Le `data-core` et `data-s3-server` Les services sont les seuls requis pour activer ONTAP S3, bien que d'autres services puissent être inclus si nécessaire.

+
Pour en savoir plus, `network interface service-policy create` consultez le link:https://docs.netapp.com/us-en/ontap-cli/network-interface-service-policy-create.html["Référence de commande ONTAP"^].


