---
permalink: s3-config/enable-client-access-from-s3-app-task.html 
sidebar: sidebar 
keywords: enable, client, access, s3 app 
summary: 'Pour que les applications client S3 puissent accéder au serveur ONTAP S3, l"administrateur ONTAP S3 doit fournir des informations de configuration à l"utilisateur S3.' 
---
= Activation de l'accès client à partir d'une application S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour que les applications client S3 puissent accéder au serveur ONTAP S3, l'administrateur ONTAP S3 doit fournir des informations de configuration à l'utilisateur S3.

.Avant de commencer
L'application client S3 doit être capable d'authentifier auprès du serveur ONTAP S3 à l'aide des versions de signature AWS suivantes :

* Signature version 4, ONTAP 9.8 et ultérieure
* Signature version 2, ONTAP 9.11.1 et ultérieure


Les autres versions de signatures ne sont pas prises en charge par ONTAP S3.

L'administrateur ONTAP S3 doit avoir créé des utilisateurs S3 et leur accorder des autorisations d'accès, en tant qu'utilisateurs individuels ou en tant que membre de groupe, dans la stratégie de compartiment ou la stratégie de serveur de stockage objet.

L'application du client S3 doit être capable de résoudre le nom du serveur ONTAP S3, ce qui requiert que l'administrateur ONTAP S3 fournit le nom du serveur S3 (FQDN) et des adresses IP pour les LIF du serveur S3.

.Description de la tâche
Pour accéder à un compartiment ONTAP S3, un utilisateur de l'application client S3 saisit les informations fournies par l'administrateur ONTAP S3.

Depuis la version ONTAP 9.9.1, le serveur ONTAP S3 prend en charge les fonctionnalités de client AWS suivantes :

* métadonnées d'objet définies par l'utilisateur
+
Un ensemble de paires clé-valeur peut être attribué aux objets en tant que métadonnées lors de leur création à l'aide DE PUT (ou POST). Lorsqu'une opération GET/HEAD est exécutée sur l'objet, les métadonnées définies par l'utilisateur sont renvoyées avec les métadonnées du système.

* balisage d'objets
+
Un ensemble distinct de paires clé-valeur peut être attribué en tant que balises pour classer les objets. Contrairement aux métadonnées, les balises sont créées et lues avec les API REST indépendamment de l'objet. Elles sont implémentées lors de la création d'objets ou à tout moment après.

+
[NOTE]
====
Pour permettre aux clients d'obtenir et de mettre des informations de marquage, les actions `GetObjectTagging`, `PutObjectTagging`, et `DeleteObjectTagging` doivent être autorisées à l'aide des règles de compartiment ou de groupe.

====


Pour plus d'informations, consultez la documentation AWS S3.

.Étapes
. Authentifiez l'application client S3 avec le serveur ONTAP S3 en saisissant le nom du serveur S3 et le certificat de l'autorité de certification.
. Authentifier un utilisateur sur l'application client S3 en saisissant les informations suivantes :
+
** Nom du serveur S3 (FQDN) et nom du compartiment
** clé d'accès et clé secrète de l'utilisateur



