---
permalink: s3-config/enable-ontap-s3-access-remote-fabricpool-task.html 
sidebar: sidebar 
keywords: enable, ontap s3, access, remote, fabricpool tiering 
summary: 'Pour qu"ONTAP S3 puisse être utilisé comme Tier de capacité FabricPool distante (cloud), l"administrateur ONTAP S3 doit fournir des informations sur la configuration du serveur S3 à l"administrateur du cluster ONTAP distant.' 
---
= Activation de l'accès ONTAP S3 pour le Tiering FabricPool distant
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour qu'ONTAP S3 puisse être utilisé comme Tier de capacité FabricPool distante (cloud), l'administrateur ONTAP S3 doit fournir des informations sur la configuration du serveur S3 à l'administrateur du cluster ONTAP distant.

.Description de la tâche
Pour configurer des tiers cloud FabricPool, vous devez disposer des informations suivantes sur le serveur S3 :

* Nom du serveur (FQDN)
* nom du compartiment
* Certificat CA
* touche d'accès
* mot de passe (clé d'accès secrète)


En outre, la configuration réseau suivante est requise :

* Il doit y avoir une entrée pour le nom d'hôte du serveur ONTAP S3 distant dans le serveur DNS configuré pour le SVM d'administration, notamment le nom de domaine complet du serveur S3 et les adresses IP sur les LIF.
* Les LIFs intercluster doivent être configurées sur des clusters locaux et distants, bien que le peering de cluster n'est pas nécessaire.


Consultez la documentation d'FabricPool sur la configuration d'ONTAP S3 en tant que Tier cloud.

link:../fabricpool/index.html["Gestion des niveaux de stockage à l'aide de FabricPool"]
