---
permalink: s3-config/index.html 
sidebar: sidebar 
keywords: decide, s3, configuration, client, access, configure, object, bucket, svm 
summary: 'À partir de ONTAP 9.8, vous pouvez activer un serveur de stockage objet ONTAP simple Storage Service (S3) dans un cluster ONTAP.' 
---
= Présentation de la configuration S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À partir de ONTAP 9.8, vous pouvez activer un serveur de stockage objet ONTAP simple Storage Service (S3) dans un cluster ONTAP à l'aide des outils de gestion familiers tels que ONTAP System Manager pour provisionner rapidement un stockage objet haute performance pour le développement et les opérations dans ONTAP, et profiter des fonctionnalités d'efficacité du stockage et de la sécurité d'ONTAP.

Les principales utilisations de S3 dans ONTAP sont les suivantes :

* Utilisation de FabricPool pour le Tiering des données inactives vers un compartiment dans ONTAP, permettant ainsi le Tiering ONTAP vers ONTAP. Tiering dans un compartiment du link:enable-ontap-s3-access-local-fabricpool-task.html["cluster local"] ou à un tiering dans un compartiment sur un link:enable-ontap-s3-access-remote-fabricpool-task.html["cluster distant"] sont tous deux pris en charge.
Le Tiering vers ONTAP S3 vous permet d'utiliser des systèmes ONTAP moins coûteux pour les données inactives et de réaliser des économies sur la nouvelle capacité Flash sans avoir à gérer de licences FabricPool supplémentaires ou de nouvelles technologies.
* À partir de ONTAP 9.12.1, le protocole S3 peut également être activé dans
link:../s3-multiprotocol/index.html["Volumes NAS multiprotocoles"] Qui ont été préconfigurées pour utiliser les protocoles NAS. Lorsque le protocole S3 est activé dans des volumes NAS multiprotocoles, les applications client peuvent lire et écrire des données à l'aide des protocoles S3, NFS et SMB. Cela ouvre la voie à de nombreux autres cas d'utilisation.
L'une des utilisations les plus courantes est les clients NAS qui écrivent des données dans un volume et les clients S3 qui lisent les mêmes données, et qui effectuent des tâches spécialisées telles que l'analytique, la veille stratégique, le machine learning et la reconnaissance optique de caractères.



NOTE: ONTAP S3 est approprié si vous souhaitez activer les fonctionnalités S3 sur des clusters ONTAP existants sans matériel ni gestion supplémentaires. NetApp StorageGRID est la solution phare de NetApp pour le stockage objet. StorageGRID est recommandé pour les applications S3 natives qui doivent exploiter la gamme complète d'actions S3, de fonctionnalités ILM avancées ou de capacités impossibles à atteindre dans les systèmes ONTAP. Pour plus d'informations, reportez-vous à la section link:https://docs.netapp.com/us-en/storagegrid-118/index.html["Documentation StorageGRID"^].



== Configuration S3 avec System Manager et l'interface de ligne de commandes ONTAP

Vous pouvez configurer et gérer ONTAP S3 avec System Manager et l'interface de ligne de commandes d'ONTAP. Si vous activez S3 et créez des compartiments à l'aide de System Manager, ONTAP sélectionne les valeurs par défaut des meilleures pratiques pour une configuration simplifiée. Si vous devez spécifier des paramètres de configuration, vous pouvez utiliser l'interface de ligne de commandes de ONTAP.  Si vous configurez le serveur S3 et les compartiments à partir de l'interface de ligne de commandes, vous pouvez toujours les gérer avec System Manager, le cas échéant, ou vice-versa.

Lorsque vous créez un compartiment S3 avec System Manager, ONTAP configure un niveau de service de performance par défaut qui est le plus élevé disponible sur votre système. Par exemple, sur un système AFF, le paramètre par défaut est *Extreme*. Les niveaux de service de performance sont des groupes de règles prédéfinies de qualité de service (QoS) adaptative. Au lieu d'un des niveaux de service par défaut, vous pouvez définir une « policy group » QoS personnalisée ou aucun « policy group ».

Les groupes de règles de QoS adaptatifs sont les suivants :

* *Extreme* : utilisé pour les applications qui exigent la plus faible latence et les meilleures performances.
* *Performance* : utilisé pour les applications avec des besoins de performances et une latence modestes.
* *Valeur* : utilisé pour les applications pour lesquelles le débit et la capacité sont plus importants que la latence.
* *Custom* : spécifiez une politique de QoS personnalisée ou aucune politique de QoS.


Si vous sélectionnez *utiliser pour le Tiering*, aucun niveau de service de performances n'est sélectionné et le système essaie de sélectionner un support à faible coût avec des performances optimales pour les données hiérarchisées.

Voir aussi : link:../performance-admin/adaptive-qos-policy-groups-task.html["Utilisez les groupes de règles de QoS adaptatifs"].

ONTAP tente de provisionner ce compartiment sur les niveaux locaux qui comptent les disques les plus appropriés, en satisfaisant le niveau de service choisi. Toutefois, si vous devez spécifier les disques à inclure dans le compartiment, configurez le stockage objet S3 à partir de l'interface de ligne de commandes en spécifiant les niveaux locaux (agrégat). Si vous configurez le serveur S3 à partir de l'interface de ligne de commandes, vous pouvez toujours le gérer avec System Manager.

Si vous souhaitez spécifier les agrégats utilisés pour les compartiments, vous pouvez uniquement le faire via l'interface de ligne de commande.



== Configuration des compartiments S3 sur Cloud Volumes ONTAP

Pour fournir des compartiments à partir de Cloud Volumes ONTAP, il est fortement recommandé de sélectionner manuellement les agrégats sous-jacents pour vérifier qu'ils n'utilisent qu'un seul nœud. L'utilisation d'agrégats des deux nœuds peut avoir un impact sur les performances, car les nœuds se trouvent dans des zones de disponibilité séparées géographiquement et sont donc sujets aux problèmes de latence. Par conséquent, dans les environnements Cloud Volumes ONTAP, vous devriez le faire xref:create-bucket-task.html[Configuration des compartiments S3 à partir de l'interface de ligne de commandes].

Sinon, les serveurs S3 sur Cloud Volumes ONTAP sont configurés et conservés dans Cloud Volumes ONTAP et dans des environnements sur site.
