---
permalink: s3-config/ontap-s3-supported-actions-reference.html 
sidebar: sidebar 
keywords: ontap s3, supported, actions 
summary: Actions prises en charge par ONTAP S3. 
---
= Actions prises en charge par ONTAP S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Les actions ONTAP S3 sont prises en charge par les API REST S3 standard, sauf comme indiqué ci-dessous. Pour plus d'informations, reportez-vous à la link:https://docs.aws.amazon.com/AmazonS3/latest/API/Type_API_Reference.html["Référence de l'API Amazon S3"^].



== Opérations des compartiments

Les opérations suivantes sont prises en charge par les API REST ONTAP dans les versions ONTAP où la prise en charge de l'API REST AWS S3 n'est pas disponible :

* création et suppression de compartiments
* création, modification et suppression de règles de compartiment


|===
| Utilisation du godet | Prise en charge de ONTAP commençant par 


| CreateBucket | ONTAP 9.11.1 


| DeleteBucket | ONTAP 9.11.1 


| DeleteBucketPolicy | ONTAP 9.12.1 


| GetBucketAcl | ONTAP 9.8 


| GetBucketPolicy | ONTAP 9.12.1 


| Godet principal | ONTAP 9.8 


| Listseaux | ONTAP 9.8 


| PutBucket* | ONTAP 9.8 + * pris en charge avec les API REST de ONTAP uniquement 


| PutBuckePolicy | ONTAP 9.12.1 


| PutBucketLifecycleConfiguration | ONTAP 9.13.1 + * seules les actions d'expiration sont prises en charge 


| GetBucketLifecycleConfiguration | ONTAP 9.13.1 + * seules les actions d'expiration sont prises en charge 
|===


== Opérations sur l'objet

Depuis la version ONTAP 9.9.1, ONTAP S3 prend en charge le balisage et les métadonnées d'objet.

* PutObject et CreateMultipartUpload incluent désormais des paires clé-valeur utilisant `x-amz-meta-<key>.`
+
Par exemple : `x-amz-meta-project: ontap_s3`.

* GetObject. Enfin, HeadObject renvoie désormais des métadonnées définies par l'utilisateur.
* Contrairement aux métadonnées, les balises peuvent être lues indépendamment des objets à l'aide de :
+
** Marquage PutObject
** GetObjectTagging
** DeleteObjectTagging




Depuis ONTAP 9.11.1, ONTAP S3 prend en charge la gestion des versions d'objets et les actions associées avec les API ONTAP suivantes :

* GetBucketVersioning
* ListBuckeVersions
* PutBuckeVersioning


|===
| Opération d'objet | Prise en charge de ONTAP commençant par 


| AbortMultipartUpload | ONTAP 9.8 


| CompleteMultipartUpload | ONTAP 9.8 


| Objet de copie | ONTAP 9.12.1 


| CreateMultipartUpload | ONTAP 9.8 


| DeleteObject | ONTAP 9.8 


| DeleteObjects | ONTAP 9.11.1 


| DeleteObjectTagging | ONTAP 9.9.1 


| GetBucketVersioning | ONTAP 9.11.1 


| GetObject | ONTAP 9.8 


| GetObjectAcl | ONTAP 9.8 


| GetObjectTagging | ONTAP 9.9.1 


| Objet principal | ONTAP 9.8 


| ListMultipartUpload | ONTAP 9.8 


| ListObjects | ONTAP 9.8 


| ListentsV2 | ONTAP 9.8 


| ListBuckeVersions | ONTAP 9.11.1 


| ListParts | ONTAP 9.8 


| PutBuckeVersioning | ONTAP 9.11.1 


| PutObject | ONTAP 9.8 


| Marquage PutObject | ONTAP 9.9.1 


| UploadPart | ONTAP 9.8 


| UploadPartCopy | ONTAP 9.12.1 
|===


== Stratégies de groupe

Ces opérations ne sont pas spécifiques à S3 et sont généralement associées aux processus de gestion des identités et des données. ONTAP prend en charge ces commandes, mais n'utilise pas l'API REST IAM.

* Créer la règle
* Politique d'AttachGroup




== Gestion des utilisateurs

Ces opérations ne sont pas spécifiques aux protocoles S3 et sont généralement associées aux processus IAM.

* CreateUser
* Supprimer un utilisateur
* CreateGroup
* DeleteGroup

