---
permalink: s3-config/ontap-s3-supported-actions-reference.html 
sidebar: sidebar 
keywords: ontap s3, supported, actions 
summary: Actions prises en charge par ONTAP S3. 
---
= Actions prises en charge par ONTAP S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les actions ONTAP S3 sont prises en charge par les API REST S3 standard, sauf comme indiqué ci-dessous. Pour plus d'informations, reportez-vous à la link:https://docs.aws.amazon.com/AmazonS3/latest/API/Type_API_Reference.html["Référence de l'API Amazon S3"^].


NOTE: Ces actions S3 sont prises en charge spécifiquement lors de l'utilisation de compartiments S3 natifs dans ONTAP. Certaines de ces actions, telles que celles associées à la gestion des versions, aux verrous d'objets et à d'autres fonctionnalités, ne sont pas prises en charge lors de l'utilisation de link:../s3-multiprotocol/index.html["Compartiments NAS S3 (S3 dans des volumes NAS multiprotocoles)"].

Sauf indication contraire pour une opération spécifique, les en-têtes de requête courants suivants sont pris en charge à partir d' ONTAP 9.8 :

* `Authorization`
* `Connection`
* `Content-Length`
* `Content-MD5`
* `Content-Type`
* `Date`
* `Expect`
* `Host`
* `x-amz-date`




== Opérations des compartiments

Les opérations suivantes sont prises en charge dans ONTAP à l'aide des API AWS S3 :

|===
| Utilisation du godet | Prise en charge de ONTAP commençant par 


 a| 
CreateBucket

ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande, ainsi que cet en-tête supplémentaire :

* `x-amz-bucket-object-lock-enabled`

| ONTAP 9.11.1 


 a| 
DeleteBucket

ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande.
| ONTAP 9.11.1 


| DeleteBucketCors ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande. | ONTAP 9.8 


| DeleteBucketLifecycle ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande. | ONTAP 9.8 


 a| 
DeleteBucketPolicy

ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande.
| ONTAP 9.12.1 


| GetBucketAcl ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande. | ONTAP 9.8 


| GetBucketCors ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande. | ONTAP 9.8 


 a| 
GetBucketLifecycleConfiguration

ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande.
 a| 
ONTAP 9.13.1

*Seules les actions d'expiration sont prises en charge



| GetBucketLocation ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande. | ONTAP 9.10.1 


| GetBucketPolicy ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande. | ONTAP 9.12.1 


| GetBucketVersioning ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande. | ONTAP 9.11.1 


| HeadBucket ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande. | ONTAP 9.8 


| ListAllMyBuckets ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande. | ONTAP 9.8 


| ListBuckets ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande. | ONTAP 9.8 


| ListBucketVersions ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande. | ONTAP 9.11.1 


| Seau de rangement  a| 
* ONTAP 9.11.1
* ONTAP 9.8 : pris en charge uniquement avec les API REST ONTAP




| PutBucketCors ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande.  a| 
ONTAP 9.8



| PutBucketLifecycleConfiguration ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande. | ONTAP 9.13.1 * seules les actions d'expiration sont prises en charge 


| PutBucketPolicy ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande. | ONTAP 9.12.1 


| PutBucketVersioning ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande. | ONTAP 9.11.1 
|===


== Opérations sur l'objet

Depuis la version ONTAP 9.9.1, ONTAP S3 prend en charge le balisage et les métadonnées d'objet.

* PutObject et CreateMultipartUpload incluent des paires clé-valeur utilisant `x-amz-meta-<key>.`
+
Par exemple : `x-amz-meta-project: ontap_s3`.

* GetObject et HeadObject renvoient des métadonnées définies par l'utilisateur.
* Contrairement aux métadonnées, les balises peuvent être lues indépendamment des objets à l'aide de :
+
** Marquage PutObject
** GetObjectTagging
** DeleteObjectTagging




Depuis ONTAP 9.11.1, ONTAP S3 prend en charge la gestion des versions d'objets et les actions associées avec les API ONTAP suivantes :

* GetBucketVersioning
* ListBuckeVersions
* PutBuckeVersioning


Sauf indication contraire pour une opération spécifique, les paramètres de requête URI suivants sont pris en charge :

* `versionId`(comme requis pour les opérations d'objet à partir d' ONTAP 9.12.1)


|===
| Opération d'objet | Prise en charge de ONTAP commençant par 


 a| 
AbortMultipartUpload

ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette requête, ainsi que ce paramètre de requête URI supplémentaire :
`uploadId`
 a| 
ONTAP 9.8



 a| 
CompleteMultipartUpload

ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette requête, ainsi que ce paramètre de requête URI supplémentaire :
`uploadId`
 a| 
ONTAP 9.8



 a| 
Objet de copie

ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande, ainsi que ces en-têtes supplémentaires :

* `x-amz-copy-source`
* `x-amz-copy-source-if-match`
* `x-amz-copy-source-if-modified-since`
* `x-amz-copy-source-if-none-match`
* `x-amz-copy-source-if-unmodified-since`
* `x-amz-metadata-directive`
* `x-amz-object-lock-mode`
* `x-amz-object-lock-retain-until-date`
* `x-amz-tagging`
* `x-amz-tagging-directive`
* `x-amz-meta-<metadata-name>`

| ONTAP 9.12.1 


 a| 
CreateMultipartUpload

ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande, ainsi que ces en-têtes supplémentaires :

* `Cache-Control`
* `Content-Disposition`
* `Content-Encoding`
* `Content-Language`
* `Expires`
* `x-amz-tagging`
* `x-amz-object-lock-mode`
* `x-amz-object-lock-retain-until-date`
* `x-amz-meta-<metadata-name>`

| ONTAP 9.8 


 a| 
DeleteObject

ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande, ainsi que cet en-tête supplémentaire :

* `x-amz-bypass-governance-retention`

| ONTAP 9.8 


| DeleteObjects ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette requête, ainsi que cet en-tête supplémentaire : * `x-amz-bypass-governance-retention` | ONTAP 9.11.1 


 a| 
DeleteObjectTagging

ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande.
| ONTAP 9.9.1 


 a| 
GetObject

ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette requête, ainsi que ces paramètres de requête URI supplémentaires :

* `partNumber`
* `response-cache-control`
* `response-content-disposition`
* `response-content-encoding`
* `response-content-language`
* `response-content-type`
* `response-expires`


Et cet en-tête de requête supplémentaire :

* Gamme

| ONTAP 9.8 


| GetObjectAcl ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande. | ONTAP 9.8 


 a| 
Obtenir les attributs des objets

ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande, ainsi que cet en-tête supplémentaire :

* `x-amz-object-attributes`

| ONTAP 9.17.1 


| GetObjectRetention ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande. | ONTAP 9.14.1 


| GetObjectTagging ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande. | ONTAP 9.9.1 


| HeadObject ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande. | ONTAP 9.8 


 a| 
ListMultipartUpload

ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette requête, ainsi que ces paramètres URI supplémentaires :

* `delimiter`
* `key-marker`
* `max-uploads`
* `prefix`
* `upload-id-marker`

| ONTAP 9.8 


 a| 
ListObjects

ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette requête, ainsi que ces paramètres URI supplémentaires :

* `delimiter`
* `encoding-type`
* `marker`
* `max-keys`
* `prefix`

| ONTAP 9.8 


 a| 
ListentsV2

ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette requête, ainsi que ces paramètres URI supplémentaires :

* `continuation-token`
* `delimiter`
* `encoding-type`
* `fetch-owner`
* `max-keys`
* `prefix`
* `start-after`

| ONTAP 9.8 


 a| 
ListObjectVersions

ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette requête, ainsi que ces paramètres URI supplémentaires :

* `delimiter`
* `encoding-type`
* `key-marker`
* `max-keys`
* `prefix`
* `version-id-marker`

| ONTAP 9.11.1 


 a| 
ListParts

ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette requête, ainsi que ces paramètres URI supplémentaires :

* `max-parts`
* `part-number-marker`
* `uploadId`

| ONTAP 9.8 


 a| 
PutObject

ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande, ainsi que ces en-têtes supplémentaires :

* `Cache-Control`
* `Content-Disposition`
* `Content-Encoding`
* `Content-Language`
* `Expires`
* `x-amz-tagging`
* `x-amz-object-lock-mode`
* `x-amz-object-lock-retain-until-date`
* `x-amz-meta-<metadata-name>`

| ONTAP 9.8 


| PutObjectLockConfiguration ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande. | ONTAP 9.14.1 


 a| 
PutObjectRetention

ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande, ainsi que cet en-tête supplémentaire :

* `x-amz-bypass-governance-retention`

| ONTAP 9.14.1 


| PutObjectTagging ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette demande. | ONTAP 9.9.1 


| UploadPart | ONTAP 9.8 


 a| 
UploadPartCopy

ONTAP S3 prend en charge tous les paramètres et en-têtes courants pour cette requête, ainsi que ces paramètres URI supplémentaires :

* `partNumber`
* `uploadId`


Et ces en-têtes de requête supplémentaires :

* `x-amz-copy-source`
* `x-amz-copy-source-if-match`
* `x-amz-copy-source-if-modified-since`
* `x-amz-copy-source-if-none-match`
* `x-amz-copy-source-if-unmodified-since`
* `x-amz-copy-source-range`

| ONTAP 9.12.1 
|===


== Stratégies de groupe

Ces opérations ne sont pas spécifiques à S3 et sont généralement associées aux processus de gestion des identités et des données. ONTAP prend en charge ces commandes, mais n'utilise pas l'API REST IAM.

* Créer la règle
* Politique d'AttachGroup




== Gestion des utilisateurs

Ces opérations ne sont pas spécifiques aux protocoles S3 et sont généralement associées aux processus IAM.

* CreateUser
* Supprimer un utilisateur
* CreateGroup
* DeleteGroup




== Actions S3 par version

.ONTAP 9.14.1
ONTAP 9.14.1 ajoute la prise en charge du verrouillage objet S3.


NOTE: Les opérations de mise en attente légale (verrous sans durée de conservation définie) ne sont pas prises en charge.

* GetObjectLockConfiguration
* GetObjectRetention
* PutObjectLockConfiguration
* PutObjectRetention


.ONTAP 9.13.1
ONTAP 9.13.1 offre une prise en charge supplémentaire de la gestion du cycle de vie des compartiments.

* DeleteBuckeLifecycleConfiguration
* GetBucketLifecycleConfiguration
* PutBucketLifecycleConfiguration


.ONTAP 9.12.1
ONTAP 9.12.1 permet de prendre en charge les règles de compartiment et de copier les objets.

* DeleteBucketPolicy
* GetBucketPolicy
* PutBuckePolicy
* Objet de copie
* UploadPartCopy


.ONTAP 9.11.1
ONTAP 9.11.1 prend également en charge la gestion des versions, les URL présignées, les téléchargements avec groupes de commandes et la prise en charge des actions S3 courantes, telles que la création et la suppression de compartiments à l'aide des API S3.

* ONTAP S3 prend désormais en charge les téléchargements segmentés en signant les demandes à l'aide de `x-amz-content-sha256:
STREAMING-AWS4-HMAC-SHA256-PAYLOAD`
* ONTAP S3 prend désormais en charge des applications client utilisant des URL présignées pour partager des objets ou permettre à d'autres utilisateurs de télécharger des objets sans requérir d'informations d'identification utilisateur.
* CreateBucket
* DeleteBucket
* GetBucketVersioning
* ListBuckeVersions
* Seau de rangement
* PutBuckeVersioning
* DeleteObjects
* ListObjectVersions



NOTE: Comme le FlexGroup sous-jacent n'est pas créé avant que le premier compartiment ne soit, un compartiment doit d'abord être créé dans ONTAP avant qu'un client externe puisse créer un compartiment à l'aide de CreateBucket.

.ONTAP 9.10.1
ONTAP 9.10.1 ajoute la prise en charge de SnapMirror S3 et de GetBucketLocation.

* GetBuckeLocation


.ONTAP 9.9.1
ONTAP 9.9.1 ajoute la prise en charge du balisage et des métadonnées d'objet à ONTAP S3.

* PutObject et CreateMultipartUpload incluent désormais des paires clé-valeur utilisant `x-amz-meta-<key>`. Par exemple : `x-amz-meta-project: ontap_s3`.
* GetObject et HeadObject renvoient maintenant des métadonnées définies par l'utilisateur.


Les étiquettes peuvent également être utilisées avec des compartiments. Contrairement aux métadonnées, les balises peuvent être lues indépendamment des objets à l'aide de :

* Marquage PutObject
* GetObjectTagging
* DeleteObjectTagging

