---
permalink: s3-config/ontap-s3-supported-actions-reference.html 
sidebar: sidebar 
keywords: ontap s3, supported, actions 
summary: Actions prises en charge par ONTAP S3. 
---
= Actions prises en charge par ONTAP S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les actions ONTAP S3 sont prises en charge par les API REST S3 standard, sauf comme indiqué ci-dessous. Pour plus d'informations, reportez-vous à la link:https://docs.aws.amazon.com/AmazonS3/latest/API/Type_API_Reference.html["Référence de l'API Amazon S3"^].



== Opérations des compartiments

Les opérations suivantes sont prises en charge dans ONTAP à l'aide des API AWS S3 :

|===
| Utilisation du godet | Prise en charge de ONTAP commençant par 


| CreateBucket | ONTAP 9.11.1 


| DeleteBucket | ONTAP 9.11.1 


| DeleteBucketPolicy | ONTAP 9.12.1 


| GetBucketAcl | ONTAP 9.8 


| GetBucketLifecycleConfiguration | ONTAP 9.13.1 +
* seules les actions d'expiration sont prises en charge 


| GetBuckeLocation | ONTAP 9.10.1 


| GetBucketPolicy | ONTAP 9.12.1 


| Godet principal | ONTAP 9.8 


| Listseaux | ONTAP 9.8 


| ListBucketVersioning | ONTAP 9.11.1 


| ListObjectVersions | ONTAP 9.11.1 


| Seau de rangement  a| 
* ONTAP 9.11.1
* ONTAP 9.8 : pris en charge uniquement avec les API REST ONTAP




| PutBucketLifecycleConfiguration | ONTAP 9.13.1 +
* seules les actions d'expiration sont prises en charge 


| PutBuckePolicy | ONTAP 9.12.1 
|===


== Opérations sur l'objet

Depuis la version ONTAP 9.9.1, ONTAP S3 prend en charge le balisage et les métadonnées d'objet.

* PutObject et CreateMultipartUpload incluent des paires clé-valeur utilisant `x-amz-meta-<key>.`
+
Par exemple : `x-amz-meta-project: ontap_s3`.

* GetObject. Et HeadObject renvoient des métadonnées définies par l'utilisateur.
* Contrairement aux métadonnées, les balises peuvent être lues indépendamment des objets à l'aide de :
+
** Marquage PutObject
** GetObjectTagging
** DeleteObjectTagging




Depuis ONTAP 9.11.1, ONTAP S3 prend en charge la gestion des versions d'objets et les actions associées avec les API ONTAP suivantes :

* GetBucketVersioning
* ListBuckeVersions
* PutBuckeVersioning


|===
| Opération d'objet | Prise en charge de ONTAP commençant par 


| AbortMultipartUpload | ONTAP 9.8 


| CompleteMultipartUpload | ONTAP 9.8 


| Objet de copie | ONTAP 9.12.1 


| CreateMultipartUpload | ONTAP 9.8 


| DeleteObject | ONTAP 9.8 


| DeleteObjects | ONTAP 9.11.1 


| DeleteObjectTagging | ONTAP 9.9.1 


| GetBucketVersioning | ONTAP 9.11.1 


| GetObject | ONTAP 9.8 


| GetObjectAcl | ONTAP 9.8 


| GetObjectRetention | ONTAP 9.14.1 


| GetObjectTagging | ONTAP 9.9.1 


| Objet principal | ONTAP 9.8 


| ListMultipartUpload | ONTAP 9.8 


| ListObjects | ONTAP 9.8 


| ListentsV2 | ONTAP 9.8 


| ListBuckeVersions | ONTAP 9.11.1 


| ListParts | ONTAP 9.8 


| PutBuckeVersioning | ONTAP 9.11.1 


| PutObject | ONTAP 9.8 


| PutObjectLockConfiguration | ONTAP 9.14.1 


| PutObjectRetention | ONTAP 9.14.1 


| Marquage PutObject | ONTAP 9.9.1 


| UploadPart | ONTAP 9.8 


| UploadPartCopy | ONTAP 9.12.1 
|===


== Stratégies de groupe

Ces opérations ne sont pas spécifiques à S3 et sont généralement associées aux processus de gestion des identités et des données. ONTAP prend en charge ces commandes, mais n'utilise pas l'API REST IAM.

* Créer la règle
* Politique d'AttachGroup




== Gestion des utilisateurs

Ces opérations ne sont pas spécifiques aux protocoles S3 et sont généralement associées aux processus IAM.

* CreateUser
* Supprimer un utilisateur
* CreateGroup
* DeleteGroup




== Actions S3 par version

.ONTAP 9.14.1
ONTAP 9.14.1 ajoute la prise en charge du verrouillage objet S3.

* GetObjectLockConfiguration
* GetObjectRetention
* PutObjectLockConfiguration
* PutObjectRetention


.ONTAP 9.13.1
ONTAP 9.13.1 offre une prise en charge supplémentaire de la gestion du cycle de vie des compartiments.

* DeleteBuckeLifecycleConfiguration
* GetBucketLifecycleConfiguration
* PutBucketLifecycleConfiguration


.ONTAP 9.12.1
ONTAP 9.12.1 permet de prendre en charge les règles de compartiment et de copier les objets.

* DeleteBucketPolicy
* GetBucketPolicy
* PutBuckePolicy
* Objet de copie
* UploadPartCopy


.ONTAP 9.11.1
ONTAP 9.11.1 prend également en charge la gestion des versions, les URL présignées, les téléchargements avec groupes de commandes et la prise en charge des actions S3 courantes, telles que la création et la suppression de compartiments à l'aide des API S3.

* ONTAP S3 prend désormais en charge les requêtes de signature de téléchargements avec groupe de hachage à l'aide de x-amz-content-sha256 : STREAMING-AWS4-HMAC-SHA256-CHARGE
* ONTAP S3 prend désormais en charge des applications client utilisant des URL présignées pour partager des objets ou permettre à d'autres utilisateurs de télécharger des objets sans requérir d'informations d'identification utilisateur.
* CreateBucket
* DeleteBucket
* GetBucketVersioning
* ListBuckeVersions
* Seau de rangement
* PutBuckeVersioning
* DeleteObjects
* ListObjectVersions



NOTE: Comme le FlexGroup sous-jacent n'est pas créé avant que le premier compartiment ne soit, un compartiment doit d'abord être créé dans ONTAP avant qu'un client externe puisse créer un compartiment à l'aide de CreateBucket.

.ONTAP 9.10.1
ONTAP 9.10.1 ajoute la prise en charge de S3 SnapMirror et GetBucketLocation.

* GetBuckeLocation


.ONTAP 9.9.1
ONTAP 9.9.1 ajoute la prise en charge du balisage et des métadonnées d'objet à ONTAP S3.

* PutObject et CreateMultipartUpload incluent désormais des paires clé-valeur utilisant 'x-amz-meta-<key>'. Par exemple : 'x-amz-meta-project: ONTAP_s3'.
* GetObject et HeadObject renvoient maintenant des métadonnées définies par l'utilisateur.


Les étiquettes peuvent également être utilisées avec des compartiments. Contrairement aux métadonnées, les balises peuvent être lues indépendamment des objets à l'aide de :

* Marquage PutObject
* GetObjectTagging
* DeleteObjectTagging

