---
permalink: s3-config/use-cases.html 
sidebar: sidebar 
keywords: s3 use cases, ontap 9 
summary: 'Il existe trois principales utilisations pour l"accès client aux services ONTAP S3.' 
---
= Cas d'utilisation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'accès client aux services ONTAP S3 est principalement utilisé :

* Pour les systèmes ONTAP utilisant ONTAP S3 en tant que Tier de capacité FabricPool distant (cloud)
+
Le serveur et le compartiment S3 contenant le Tier de capacité (pour les données _inactives_) se trouvent sur un cluster différent du niveau de performance (pour les données _fortement sollicitées_).

* Pour les systèmes ONTAP qui utilisent ONTAP S3 en tant que Tier FabricPool local
+
Le serveur S3 et ce compartiment contenant le Tier de capacité se trouvent sur le même cluster, mais sur une paire haute disponibilité différente de celle du Tier de performance.

* Pour les applications client S3 externes
+
ONTAP S3 sert les applications client S3 s'exécutant sur des systèmes non NetApp.



Il est recommandé d'autoriser l'accès aux compartiments ONTAP S3 à l'aide de HTTPS. Lorsque HTTPS est activé, des certificats de sécurité sont nécessaires pour une intégration correcte avec SSL/TLS. Les utilisateurs du client doivent ensuite authentifier l'utilisateur avec ONTAP S3 et autoriser les autorisations d'accès des utilisateurs pour les opérations dans ONTAP S3. L'application client doit également avoir accès au certificat de l'autorité de certification racine (certificat signé du serveur ONTAP S3) pour pouvoir authentifier le serveur et créer une connexion sécurisée entre le client et le serveur.

Les utilisateurs sont créés au sein de la SVM compatible S3 et leurs autorisations d'accès peuvent être contrôlées au niveau du compartiment ou de la SVM. Il est ainsi possible de leur accorder l'accès à un ou plusieurs compartiments au sein de la SVM.

HTTPS est activé par défaut sur les serveurs ONTAP S3. Il est possible de désactiver HTTPS et d'activer HTTP pour l'accès client. Dans ce cas, l'authentification à l'aide de certificats CA n'est pas requise. Lorsque HTTP est activé et HTTPS est désactivé, toutes les communications avec le serveur ONTAP S3 sont envoyées en clair sur le réseau.

Pour plus d'informations, reportez-vous à la section https://www.netapp.com/pdf.html?item=/media/17219-tr4814pdf.pdf["Rapport technique : S3 dans les bonnes pratiques de ONTAP"]

.Informations associées
link:../flexgroup/index.html["Gestion des volumes FlexGroup"]
