---
permalink: s3-config/where-provision-storage-capacity-task.html 
sidebar: sidebar 
keywords: decide, provision, new s3, storage, capacity 
summary: Avant de créer un nouveau compartiment S3, vous devez décider de le placer dans un SVM nouveau ou existant. Cette décision détermine votre flux de travail. 
---
= Décidez où provisionner la nouvelle capacité de stockage ONTAP S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de créer un nouveau compartiment S3, vous devez décider de le placer dans un SVM nouveau ou existant. Cette décision détermine votre flux de travail.

.Choix
* Si vous souhaitez provisionner un compartiment dans un nouveau SVM ou un SVM qui n'est pas activé pour S3, effectuez les étapes suivantes.
+
link:create-svm-s3-task.html["Création d'un SVM pour S3"]

+
link:create-bucket-task.html["Création d'un compartiment pour S3"]

+
Bien que S3 puisse coexister dans un SVM avec NFS et SMB, il est possible de créer un nouveau SVM si l'un des cas suivants est vrai :

+
** Vous activez S3 pour la première fois sur un cluster.
** Un cluster contient des SVM dans lesquels vous ne souhaitez pas activer la prise en charge de S3.
** Un ou plusieurs SVM compatibles S3 sont mis en cluster et un autre serveur S3 doit avoir des caractéristiques de performance différentes.
Après l'activation du protocole S3 sur le SVM, procéder au provisionnement d'un compartiment.


* Pour provisionner le compartiment initial ou un compartiment supplémentaire sur un SVM compatible S3, effectuez la procédure ci-dessous.
+
link:create-bucket-task.html["Création d'un compartiment pour S3"]


