---
permalink: snaplock/autocommit-files-worm-task.html 
sidebar: sidebar 
keywords: snaplock, autocommit, commit, files, worm, automatically 
summary: 'La fonctionnalité d"autovalidation de SnapLock vous permet d"allouer automatiquement les fichiers en mode WORM.' 
---
= Archivage automatique des fichiers en mode WORM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La fonctionnalité d'autovalidation de SnapLock vous permet d'allouer automatiquement les fichiers en mode WORM.

.Ce dont vous avez besoin
* Les fichiers que vous souhaitez effectuer une validation automatique doivent résider sur un volume SnapLock.
* Le volume SnapLock doit être en ligne.
* Le volume SnapLock doit être un volume en lecture/écriture.


[NOTE]
====
La fonction SnapLock autocommit analyse tous les fichiers du volume et valide un fichier s'il répond à l'exigence d'autocommit. Il peut y avoir un intervalle de temps entre le moment où le fichier est prêt pour la validation automatique et celui où il est réellement engagé par le scanner SnapLock autocommit. Cependant, le fichier est toujours protégé contre les modifications et la suppression par le système de fichiers dès qu'il est éligible à l'auto-validation.

====
.Description de la tâche
Le paramètre _autocommit Period_ spécifie le temps pendant lequel les fichiers doivent rester inchangés avant leur validation automatique. La modification d'un fichier avant que la période de validation automatique ne soit écoulée entraîne le redémarrage de la période de validation automatique du fichier.

Le tableau suivant présente les valeurs possibles pour la période de validation automatique :

|===
| Valeur | Unité | Remarques 


 a| 
Aucune
 a| 
-
 a| 
La valeur par défaut.



 a| 
5 - 5256000
 a| 
quelques minutes
 a| 
-



 a| 
1 - 87600
 a| 
heures
 a| 
-



 a| 
1 - 3650
 a| 
jours
 a| 
-



 a| 
1 - 120
 a| 
mois
 a| 
-



 a| 
1 - 10
 a| 
années
 a| 
-

|===
[NOTE]
====
La valeur minimale est de 5 minutes et la valeur maximale est de 10 ans.

====
.Étapes
. Validation automatique des fichiers sur un volume SnapLock vers WORM :
+
`*volume snaplock modify -vserver _SVM_name_ -volume _volume_name_ -autocommit-period _autocommit_period_*`

+
Pour obtenir la liste complète des options, consultez la page man de la commande.

+
La commande suivante valide automatiquement les fichiers sur le volume `vol1` Du SVM vs1, tant que les fichiers restent inchangés pendant 5 heures :

+
[listing]
----
cluster1::>volume snaplock modify -vserver vs1 -volume vol1 -autocommit-period 5hours
----

