---
permalink: snaplock/commit-files-worm-state-manual-task.html 
sidebar: sidebar 
keywords: commit, file, worm, manually, nfs, cifs, read, only 
summary: 'Vous devez valider manuellement un fichier en mode WORM en le rendant en lecture seule. Vous pouvez utiliser n"importe quelle commande ou programme approprié sur NFS ou CIFS pour changer l"attribut lecture-écriture d"un fichier en lecture seule.' 
---
= Archivage manuel des fichiers en mode WORM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez valider manuellement un fichier en mode WORM en le rendant en lecture seule. Vous pouvez utiliser n'importe quelle commande ou programme approprié sur NFS ou CIFS pour changer l'attribut lecture-écriture d'un fichier en lecture seule.

.Ce dont vous avez besoin, 8217;ll
* Le fichier à valider doit résider sur un volume SnapLock.
* Le fichier doit être accessible en écriture.


L'heure de la durée de la période de conformité du volume est écrite sur le `ctime` champ du fichier lors de l'exécution de la commande ou du programme. L'heure de la fin de l'horloge détermine quand la durée de conservation du fichier a été atteinte.

.Étapes
. Utilisez une commande ou un programme approprié pour modifier l'attribut lecture-écriture d'un fichier en lecture seule.
+
Dans un shell UNIX, utilisez la commande suivante pour créer un fichier nommé `document.txt` lecture seule :

+
[listing]
----
chmod -w document.txt
----
+
Dans un shell Windows, utilisez la commande suivante pour créer un fichier nommé `document.txt` lecture seule :

+
[listing]
----
attrib +r document.txt
----

