---
permalink: snaplock/create-snaplock-volume-task.html 
sidebar: sidebar 
keywords: snaplock, volume, shanpshot, copy, create, complianceclock, file, worm, compliance, enterprise 
summary: 'Vous devez créer un volume SnapLock pour les fichiers ou les snapshots que vous souhaitez valider en état WORM. Depuis ONTAP 9.10.1, tout volume que vous créez, quel que soit le type d"agrégat, est créé par défaut en tant que volume non SnapLock. Vous devez utiliser `-snaplock-type` l"option pour créer explicitement un volume SnapLock en spécifiant soit Compliance soit Enterprise comme type SnapLock. Par défaut, le type SnapLock est défini sur `non-snaplock`.' 
---
= Créer et monter des volumes ONTAP SnapLock
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez créer un volume SnapLock pour les fichiers ou les snapshots que vous souhaitez valider en état WORM. Depuis ONTAP 9.10.1, tout volume que vous créez, quel que soit le type d'agrégat, est créé par défaut en tant que volume non SnapLock. Vous devez utiliser `-snaplock-type` l'option pour créer explicitement un volume SnapLock en spécifiant soit Compliance soit Enterprise comme type SnapLock. Par défaut, le type SnapLock est défini sur `non-snaplock`.

.Avant de commencer
* L'agrégat SnapLock doit être en ligne.
* Vous devriez link:../system-admin/manage-license-task.html["Vérifiez qu'une licence SnapLock est installée"]. Si aucune licence SnapLock n'est installée sur le nœud, vous devez link:../system-admin/install-license-task.html["installer"] la faire. Cette licence est incluse avec link:../system-admin/manage-licenses-concept.html["ONTAP One"]. Avant ONTAP One, la licence SnapLock était incluse dans le bundle sécurité et conformité. Le bundle sécurité et conformité n'est plus proposé, mais reste valide. Bien qu'il ne soit pas actuellement requis, les clients existants peuvent choisir de link:../system-admin/download-nlf-task.html["Passez à ONTAP One"].
* link:../snaplock/initialize-complianceclock-task.html["L'horloge de conformité sur le nœud doit être initialisée"].


.Description de la tâche
Avec les autorisations SnapLock appropriées, vous pouvez détruire ou renommer un volume d'entreprise à tout moment. Vous ne pouvez pas détruire un volume Compliance tant que la période de conservation n'est pas écoulée. Vous ne pouvez jamais renommer un volume Compliance.

Vous pouvez cloner des volumes SnapLock, mais vous ne pouvez pas cloner des fichiers sur un volume SnapLock. Le volume clone sera du même type SnapLock que le volume parent.

[NOTE]
====
Les LUN ne sont pas prises en charge dans les volumes SnapLock. Les LUN ne sont prises en charge dans les volumes SnapLock que dans les cas où les snapshots créés sur un volume non SnapLock sont transférés vers un volume SnapLock pour être protégés dans le cadre de la relation de copie SnapLock. Les LUN ne sont pas prises en charge dans les volumes SnapLock en lecture/écriture. Toutefois, les snapshots inviolables sont pris en charge à la fois sur les volumes source SnapMirror et sur les volumes de destination qui contiennent des LUN.

====
Effectuez cette tâche à l'aide de ONTAP System Manager ou de l'interface de ligne de commandes de ONTAP.

[role="tabbed-block"]
====
.System Manager
--
Depuis ONTAP 9.12.1, vous pouvez utiliser System Manager pour créer un volume SnapLock.

.Étapes
. Accédez à *Storage > volumes* et cliquez sur *Add*.
. Dans la fenêtre *Ajouter un volume*, cliquez sur *plus d'options*.
. Entrez les informations du nouveau volume, notamment le nom et la taille du volume.
. Sélectionnez *Activer SnapLock* et choisissez le type SnapLock, conformité ou entreprise.
. Dans la section *Auto-commit Files*, sélectionnez *Modified* et entrez la durée pendant laquelle un fichier doit rester inchangé avant qu'il ne soit automatiquement engagé. La valeur minimale est de 5 minutes et la valeur maximale est de 10 ans.
. Dans la section *Data Retention*, sélectionnez la période de rétention minimale et maximale.
. Sélectionnez la période de rétention par défaut.
. Cliquez sur *Enregistrer*.
. Sélectionnez le nouveau volume dans la page *volumes* pour vérifier les paramètres SnapLock.


--
.CLI
--
. Créer un volume SnapLock :
+
[source, cli]
----
volume create -vserver <SVM_name> -volume <volume_name> -aggregate <aggregate_name> -snaplock-type <compliance|enterprise>
----
+
Pour en savoir plus, `volume create` consultez le link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["Référence de commande ONTAP"^]. Les options suivantes ne sont pas disponibles pour les volumes SnapLock : `-nvfail` `-atime-update` , `-is-autobalance-eligible`, , `-space-mgmt-try-first` et `vmalign`.

+
La commande suivante crée une SnapLock `Compliance` volume nommé `vol1` marche `aggr1` marche `vs1`:

+
[listing]
----
cluster1::> volume create -vserver vs1 -volume vol1 -aggregate aggr1 -snaplock-type compliance
----


--
====


== Montez un volume SnapLock

Vous pouvez monter un volume SnapLock sur une Junction path dans le SVM namespace pour accéder au client NAS.

.Avant de commencer
Le volume SnapLock doit être en ligne.

.Description de la tâche
* Vous pouvez monter un volume SnapLock uniquement sous la racine de la SVM.
* Vous ne pouvez pas monter un volume normal sous un volume SnapLock.


.Étapes
. Monter un volume SnapLock :
+
`*volume mount -vserver _SVM_name_ -volume _volume_name_ -junction-path _path_*`

+
Pour en savoir plus, `volume mount` consultez le link:https://docs.netapp.com/us-en/ontap-cli/volume-mount.html["Référence de commande ONTAP"^].

+
La commande suivante monte un volume SnapLock nommé `vol1` au chemin de jonction `/sales` dans le `vs1` espace de noms :

+
[listing]
----
cluster1::> volume mount -vserver vs1 -volume vol1 -junction-path /sales
----

