---
permalink: snaplock/enable-snapshot-lock-task.html 
sidebar: sidebar 
keywords: snaplock, snapshot copy, lock, tamperproof, enable 
summary: 'Depuis ONTAP 9.12.1, vous pouvez activer le verrouillage des copies Snapshot lorsque vous créez un nouveau volume ou que vous modifiez un volume existant à l"aide du `-snapshot-locking-enabled` avec le `volume create` et `volume modify` commandes.' 
---
= Activez le verrouillage des copies Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis ONTAP 9.12.1, vous pouvez activer le verrouillage des copies Snapshot lorsque vous créez un nouveau volume ou que vous modifiez un volume existant à l'aide du `-snapshot-locking-enabled` avec le `volume create` et `volume modify` commandes.



== Activez le verrouillage des copies Snapshot lors de la création d'un volume

. Pour créer un nouveau volume et activer le verrouillage des copies Snapshot, entrez la commande suivante :
+
`volume create -vserver _vserver_name_ -volume _volume_name_ -snapshot-locking-enabled true`

+
La commande suivante permet de verrouiller les copies Snapshot sur un nouveau volume nommé vol1 :

+
[listing]
----
> volume create -volume vol1 -aggregate aggr1 -size 100m -snapshot-locking-enabled true
Warning: Snapshot copy locking is being enabled on volume “vol1” in Vserver “vs1”. It cannot be disabled until all locked Snapshot copies are past their expiry time. A volume with unexpired locked Snapshot copies cannot be deleted.
Do you want to continue: {yes|no}: y
[Job 32] Job succeeded: Successful
----




== Activez le verrouillage des copies Snapshot sur un volume existant

. Pour modifier un volume existant afin d'activer le verrouillage des copies Snapshot, entrez la commande suivante :
+
`volume modify -vserver _vserver_name_ -volume _volume_name_ -snapshot-locking-enabled true`


