---
permalink: snaplock/index.html 
sidebar: sidebar 
keywords: decide, about, archive, compliance, snaplock, unmodified, file, worm, storage, snap lock, mirror, unmirror. license, compliance clock, regulatory, governance, rules, govern, MAV, multi-admin verification, supported, unsupported 
summary: La technologie NetApp SnapLock peut être utilisée pour conserver les fichiers sous une forme non modifiée à des fins réglementaires et de gouvernance. 
---
= En savoir plus sur ONTAP SnapLock
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapLock est une solution de conformité hautes performances pour les entreprises qui utilisent le stockage WORM pour conserver les fichiers sous une forme non modifiée à des fins réglementaires et de gouvernance.

SnapLock aide à éviter la suppression, la modification ou le changement de nom des données pour répondre aux normes telles que SEC 17a-4(f), HIPAA, FINRA, CFTC et RGPD. SnapLock vous permet de créer des volumes spéciaux dans lesquels les fichiers peuvent être stockés et archivés dans un état non effaçable et non inscriptible pour une période de conservation définie ou indéfiniment. SnapLock permet cette conservation au niveau fichier via des protocoles de fichiers ouverts standard tels que CIFS et NFS. Les protocoles de fichier ouvert pris en charge pour SnapLock sont les suivants : NFS (versions 2, 3 et 4) et CIFS (SMB 1.0, 2.0 et 3.0).

Avec SnapLock, vous validez les fichiers et les snapshots dans le stockage WORM et vous définissez des périodes de conservation pour les données protégées par WORM. Le stockage WORM de SnapLock utilise la technologie Snapshot de NetApp et peut exploiter la réplication SnapMirror et les sauvegardes SnapVault comme technologie de base pour assurer la protection des sauvegardes et restaurations. En savoir plus sur le stockage WORM : link:https://www.netapp.com/pdf.html?item=/media/6158-tr4526pdf.pdf["Conformité du stockage WORM avec NetApp SnapLock - TR-4526"^].

Vous pouvez utiliser une application pour valider les fichiers en mode WORM sur NFS ou CIFS, ou utiliser la fonctionnalité d'autovalidation de SnapLock pour allouer automatiquement les fichiers en mode WORM. Vous pouvez utiliser un fichier _WORM apppliable_ pour conserver les données écrites de manière incrémentielle, comme les informations de journal. Pour plus d'informations, voir link:commit-files-worm-state-manual-task.html#create-a-worm-appendable-file["Utilisez le mode d'ajout de volumes pour créer des fichiers d'ajout WORM"].

SnapLock prend en charge les méthodes de protection des données qui doivent répondre à la plupart des exigences de conformité :

* Vous pouvez utiliser SnapLock pour SnapVault pour protéger les snapshots WORM sur le stockage secondaire. Voir link:commit-snapshot-copies-worm-concept.html["Archivage des snapshots en mode WORM"].
* Vous pouvez utiliser SnapMirror pour répliquer des fichiers WORM dans un autre emplacement géographique à des fins de reprise après incident. Voir link:mirror-worm-files-task.html["Fichiers WORM en miroir"].


SnapLock est une fonctionnalité d' ONTAP soumise à licence. Une seule licence vous autorise à utiliser SnapLock en mode Conformité stricte, pour satisfaire aux mandats externes comme la règle 17a-4(f) de la SEC, et en mode Entreprise plus souple, pour répondre aux réglementations internes en matière de protection des actifs numériques. Les licences SnapLock font partie de link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"] suite logicielle.

SnapLock est pris en charge sur tous les systèmes AFF, FAS et ONTAP Select. SnapLock n'est pas une solution exclusivement logicielle ; il s'agit d'une solution matérielle et logicielle intégrée. Cette distinction est importante pour les réglementations WORM strictes, telles que la norme SEC 17a-4(f), qui requiert une solution matérielle et logicielle intégrée. Pour plus d'informations, reportez-vous link:https://www.sec.gov/rules/interp/34-47806.htm["Conseils SEC aux courtiers-concessionnaires sur l'utilisation des supports de stockage électronique"^]à .



== Les avantages de SnapLock

Une fois SnapLock configuré, vous pouvez effectuer les tâches suivantes :

* link:commit-files-worm-state-manual-task.html["Archivage des fichiers en mode WORM"]
* link:commit-snapshot-copies-worm-concept.html["Validez les snapshots dans WORM pour le stockage secondaire"]
* link:mirror-worm-files-task.html["Mise en miroir des fichiers WORM pour la reprise après incident"]
* link:hold-tamper-proof-files-indefinite-period-task.html["Conservation des fichiers WORM en cas de litiges avec la conservation légale"]
* link:delete-worm-files-concept.html["Supprimez des fichiers WORM à l'aide de la fonction de suppression privilégiée"]
* link:set-retention-period-task.html["Définissez la période de rétention des fichiers"]
* link:move-snaplock-volume-concept.html["Déplacer un volume SnapLock"]
* link:snapshot-lock-concept.html["Verrouillez une copie Snapshot pour vous protéger contre les attaques par ransomware"]
* link:create-audit-log-task.html["Vérifiez l'utilisation de SnapLock avec le journal d'audit"]
* link:snaplock-apis-reference.html["Utilisez les API SnapLock"]




== SnapLock Compliance et Enterprise modes

Les modes SnapLock Compliance et Enterprise diffèrent principalement du niveau auquel chaque mode protège les fichiers WORM :

|===


| Mode SnapLock | Niveau de protection | Suppression du fichier WORM pendant la conservation 


 a| 
Mode de conformité
 a| 
Au niveau du disque
 a| 
Ne peut pas être supprimé



 a| 
Mode entreprise
 a| 
Au niveau fichier
 a| 
Peut être supprimé par l'administrateur de conformité à l'aide d'une procédure de « suppression privilégiée » auditée

|===
Une fois la période de rétention écoulée, vous êtes responsable de la suppression des fichiers dont vous n'avez plus besoin. Une fois qu'un fichier a été engagé en mode WORM, qu'il soit en mode conformité ou entreprise, il ne peut pas être modifié, même après l'expiration de la période de conservation.

Vous ne pouvez pas déplacer un fichier WORM pendant ou après la période de conservation. Vous pouvez copier un fichier WORM, mais la copie ne conserve pas ses caractéristiques WORM.

Le tableau suivant présente les différences de capacités prises en charge par les modes SnapLock Compliance et Enterprise :

|===


| Fonctionnalité | Conformité SnapLock | SnapLock Enterprise 


 a| 
Activer et supprimer des fichiers à l'aide de la suppression privilégiée
 a| 
Non
 a| 
Oui.



 a| 
Réinitialiser les disques
 a| 
Non
 a| 
Oui.



 a| 
Destruction des agrégats et des volumes SnapLock pendant la période de conservation
 a| 
Non
 a| 
Oui, à l'exception du volume du journal d'audit de SnapLock



 a| 
Renommer les agrégats ou les volumes
 a| 
Non
 a| 
Oui.



 a| 
Utiliser des disques non NetApp
 a| 
Non
 a| 
Non



 a| 
Utilisation du volume SnapLock pour la journalisation des audits
 a| 
Oui.
 a| 
Oui, à partir de ONTAP 9.5

|===


== Fonctionnalités prises en charge et non prises en charge avec SnapLock

Le tableau suivant présente les fonctionnalités prises en charge avec le mode SnapLock Compliance, le mode SnapLock Enterprise ou les deux :

|===


| Fonction | Prise en charge par SnapLock Compliance | Pris en charge par SnapLock Enterprise 


 a| 
Groupes de cohérence
 a| 
Non
 a| 
Non



 a| 
Volumes chiffrés
 a| 
Oui, apprenez-en plus sur xref:Encryption[Cryptage et SnapLock] .
 a| 
Oui, apprenez-en plus sur xref:Encryption[Cryptage et SnapLock] .



 a| 
FabricPool sur les agrégats SnapLock
 a| 
Non
 a| 
Oui, à partir de ONTAP 9.8. En savoir plus sur xref:FabricPool on SnapLock Enterprise aggregates[FabricPool sur les agrégats SnapLock Enterprise].



 a| 
Les agrégats Flash Pool
 a| 
Oui.
 a| 
Oui.



 a| 
FlexClone
 a| 
Vous pouvez cloner des volumes SnapLock, mais vous ne pouvez pas cloner des fichiers sur un volume SnapLock.
 a| 
Vous pouvez cloner des volumes SnapLock, mais vous ne pouvez pas cloner des fichiers sur un volume SnapLock.



 a| 
Volumes FlexGroup
 a| 
Oui, à partir de ONTAP 9.11.1. En savoir plus sur <<flexgroup>>.
 a| 
Oui, à partir de ONTAP 9.11.1. En savoir plus sur <<flexgroup>>.



 a| 
LUN
 a| 
Non En savoir plus sur xref:LUN support[Prise en charge LUN] Avec SnapLock.
 a| 
Non En savoir plus sur xref:LUN support[Prise en charge LUN] Avec SnapLock.



 a| 
Configurations MetroCluster
 a| 
Oui, à partir de ONTAP 9.3. En savoir plus sur xref:MetroCluster support[Prise en charge de MetroCluster].
 a| 
Oui, à partir de ONTAP 9.3. En savoir plus sur xref:MetroCluster support[Prise en charge de MetroCluster].



 a| 
Vérification multiadministrateur
 a| 
Oui, à partir de ONTAP 9.13.1. En savoir plus sur xref:Multi-admin verification (MAV) support[Prise en charge MAV].
 a| 
Oui, à partir de ONTAP 9.13.1. En savoir plus sur xref:Multi-admin verification (MAV) support[Prise en charge MAV].



 a| 
SAN
 a| 
Non
 a| 
Non



 a| 
SnapRestore pour un seul fichier
 a| 
Non
 a| 
Oui.



 a| 
Synchronisation active SnapMirror
 a| 
Non
 a| 
Non



 a| 
SnapRestore
 a| 
Non
 a| 
Oui.



 a| 
SMTape
 a| 
Non
 a| 
Non



 a| 
SnapMirror synchrone
 a| 
Non
 a| 
Non



 a| 
SSD
 a| 
Oui.
 a| 
Oui.



 a| 
Fonctionnalités d'efficacité du stockage
 a| 
Oui, depuis ONTAP 9.9.1. En savoir plus sur xref:Storage efficiency[prise en charge de l'efficacité du stockage].
 a| 
Oui, depuis ONTAP 9.9.1. En savoir plus sur xref:Storage efficiency[prise en charge de l'efficacité du stockage].

|===


== FabricPool sur les agrégats SnapLock Enterprise

FabricPool est pris en charge sur les agrégats SnapLock Enterprise à partir de ONTAP 9.8. Toutefois, votre équipe de compte doit ouvrir une demande de modification des produits afin de documenter que les données FabricPool hiérarchisées vers un cloud public ou privé ne sont plus protégées par SnapLock, car les administrateurs cloud peuvent les supprimer.

[NOTE]
====
Les données FabricPool placées dans un cloud public ou privé n'sont plus protégées par SnapLock, car les administrateurs cloud peuvent les supprimer.

====


== Volumes FlexGroup

SnapLock prend en charge les volumes FlexGroup depuis ONTAP 9.11.1, mais les fonctionnalités suivantes ne sont pas prises en charge :

* Obligation légale
* Conservation basée sur les événements
* SnapLock pour SnapVault (prise en charge à partir de ONTAP 9.12.1)


Vous devez également connaître les comportements suivants :

* L'horloge de conformité de volume (VCC) d'un volume FlexGroup est déterminée par le VCC du composant racine. Tous les composants non racines auront leur VCC étroitement synchronisé avec le VCC racine.
* Les propriétés de configuration de SnapLock sont définies uniquement sur la FlexGroup dans son ensemble. Les composants individuels ne peuvent pas avoir des propriétés de configuration différentes, telles que le temps de rétention par défaut et la période de validation automatique.




== Prise en charge LUN

Les LUN ne sont prises en charge dans les volumes SnapLock que dans les cas où les snapshots créés sur un volume non SnapLock sont transférés vers un volume SnapLock pour être protégés dans le cadre de la relation de copie SnapLock. Les LUN ne sont pas prises en charge dans les volumes SnapLock en lecture/écriture. Toutefois, les snapshots inviolables sont pris en charge à la fois sur les volumes source SnapMirror et sur les volumes de destination qui contiennent des LUN.



== Prise en charge de MetroCluster

La prise en charge de SnapLock dans les configurations MetroCluster diffère entre le mode SnapLock Compliance et le mode SnapLock Enterprise.

.Conformité SnapLock
* Depuis ONTAP 9.3, la conformité SnapLock est prise en charge sur les agrégats MetroCluster sans miroir.
* Depuis ONTAP 9.3, la conformité SnapLock est prise en charge sur les agrégats en miroir, mais uniquement si l'agrégat est utilisé pour héberger les volumes du journal d'audit SnapLock.
* Les configurations SnapLock spécifiques à SVM peuvent être répliquées sur les sites principal et secondaire à l'aide de MetroCluster.


.SnapLock Enterprise
* Les agrégats SnapLock Enterprise sont pris en charge.
* Depuis ONTAP 9.3, les agrégats SnapLock Enterprise avec suppression privilégiée sont pris en charge.
* Les configurations SnapLock spécifiques à SVM peuvent être répliquées vers les deux sites à l'aide de MetroCluster.


.Configurations MetroCluster et horloges de conformité
Les configurations MetroCluster utilisent deux mécanismes d'horloge de conformité, l'horloge de conformité du volume (VCC) et l'horloge de conformité du système (SCC). Les VCC et SCC sont disponibles dans toutes les configurations SnapLock. Lorsque vous créez un nouveau volume sur un noeud, son VCC est initialisé avec la valeur actuelle du SCC sur ce noeud. Une fois le volume créé, la durée de rétention du volume et du fichier est toujours suivie avec le VCC.

Lorsqu'un volume est répliqué vers un autre site, son VCC est également répliqué. Lors d'un basculement de volume, du site A vers le site B, par exemple, le VCC continue d'être mis à jour sur le site B pendant que le SCC sur le site A s'arrête lorsque le site A passe hors ligne.

Lorsque le site A est remis en ligne et que le rétablissement du volume est effectué, l'horloge du site A SCC redémarre alors que le VCC du volume continue d'être mis à jour. Étant donné que le VCC est mis à jour en permanence, indépendamment des opérations de basculement et de rétablissement, les délais de conservation des fichiers ne dépendent pas des horloges SCC et ne sont pas extensibles.



== Prise en charge de la vérification multiadministrateur

Depuis la version ONTAP 9.13.1, un administrateur de cluster peut explicitement activer la vérification multiadministrateur sur un cluster afin de demander l'approbation du quorum avant l'exécution de certaines opérations SnapLock. Lorsque MAV est activé, les propriétés du volume SnapLock telles que temps-conservation-défaut, temps-conservation-minimum, temps-conservation-maximum, mode-ajout-volume, période-allocation-auto et suppression-privilégiée requièrent l'approbation du quorum. En savoir plus sur link:../multi-admin-verify/index.html#how-multi-admin-verification-works["VAM"].



== Efficacité du stockage

Depuis la version ONTAP 9.9.1, SnapLock prend en charge les fonctionnalités d'efficacité du stockage, telles que la compaction des données, la déduplication entre les volumes et la compression adaptative pour les volumes et les agrégats SnapLock. Pour plus d'informations sur l'efficacité du stockage, voir link:../concepts/storage-efficiency-overview.html["Présentation de l'efficacité du stockage ONTAP"].



== Le cryptage

ONTAP propose des technologies de cryptage logicielles et matérielles qui permettent de garantir que les données au repos ne peuvent pas être lues si le support de stockage est requalifié, perdu ou volé.

*Avertissement :* NetApp ne peut pas garantir que les fichiers WORM protégés par SnapLock sur des disques ou volumes à autochiffrement seront récupérables en cas de perte de la clé d'authentification ou si le nombre de tentatives d'authentification échouées dépasse la limite spécifiée et entraîne le verrouillage permanent du disque. Vous êtes responsable de vous assurer contre les échecs d'authentification.

[NOTE]
====
Les volumes chiffrés sont pris en charge sur les agrégats SnapLock .

====


== Transition depuis la version 7-mode

Vous pouvez migrer des volumes SnapLock de 7-mode vers ONTAP à l'aide de la fonctionnalité de transition basée sur la copie de l'outil de transition 7-mode. Le mode SnapLock du volume de destination, conformité ou entreprise doit correspondre au mode SnapLock du volume source. Vous ne pouvez pas utiliser la transition sans copie pour migrer des volumes SnapLock.
