---
permalink: snaplock/index.html 
sidebar: sidebar 
keywords: decide, about, archive, compliance, snaplock, unmodified, file, worm, storage, snap lock, mirror, unmirror. license, compliance clock, regulatory, governance, rules, govern 
summary: La technologie NetApp SnapLock peut être utilisée pour conserver les fichiers sous une forme non modifiée à des fins réglementaires et de gouvernance. 
---
= Qu'est-ce que SnapLock
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapLock est une solution de conformité hautes performances pour les entreprises qui utilisent le stockage WORM pour conserver les fichiers sous une forme non modifiée à des fins réglementaires et de gouvernance.

SnapLock empêche la suppression, la modification ou la modification des données pour répondre aux réglementations SEC 17a-4, HIPAA, FINRA, CFTC et le RGPD. SnapLock vous permet de créer des volumes spéciaux dans lesquels les fichiers peuvent être stockés et archivés dans un état non effaçable et non inscriptible pour une période de conservation définie ou indéfiniment.

Avec SnapLock, vous archivage des fichiers et des copies Snapshot sur le stockage WORM et définissez des périodes de conservation pour les données protégées WORM.

Les protocoles de fichier ouvert pris en charge pour SnapLock sont les suivants : NFS (versions 2, 3 et 4) et CIFS (SMB 1.0, 2.0 et 3.0).

SnapLock ne nécessite pas de matériel spécifique. SnapLock est pris en charge sur tous les systèmes AFF, FAS et ONTAP Select. SnapLock n'est pas une solution exclusivement logicielle ; il s'agit d'une solution matérielle et logicielle intégrée. Cette distinction est importante pour les réglementations WORM strictes, telles que la norme SEC 17a-4, qui requièrent une solution matérielle et logicielle intégrée. Pour en savoir plus, se reporter à l'interprétation SEC : stockage électronique des dossiers des courtiers-concessionnaires.

Vous pouvez utiliser une application pour valider les fichiers en mode WORM sur NFS ou CIFS, ou utiliser la fonctionnalité d'autovalidation de SnapLock pour allouer automatiquement les fichiers en mode WORM. Vous pouvez utiliser un fichier _WORM apppliable_ pour conserver les données écrites de manière incrémentielle, comme les informations de journal. Pour plus d'informations, voir link:https://docs.netapp.com/us-en/ontap/snaplock/volume-append-mode-create-worm-appendable-files-task.html["Utilisez le mode d'ajout de volumes pour créer des fichiers d'ajout WORM"].

SnapLock prend en charge les méthodes de protection des données qui doivent répondre à la plupart des exigences de conformité :

* Vous pouvez utiliser SnapLock pour SnapVault pour protéger les copies Snapshot WORM sur le stockage secondaire. Voir link:https://docs.netapp.com/us-en/ontap/snaplock/commit-snapshot-copies-worm-concept.html["Archivage des copies Snapshot en mode WORM"].
* Vous pouvez utiliser SnapMirror pour répliquer des fichiers WORM dans un autre emplacement géographique à des fins de reprise après incident. Voir link:https://docs.netapp.com/us-en/ontap/snaplock/mirror-worm-files-task.html["Fichiers WORM en miroir"].


SnapLock est une fonctionnalité sous licence de NetApp ONTAP. Une seule licence vous donne le droit d'utiliser SnapLock en mode strict conformité, afin de répondre aux exigences externes telles que la règle SEC 17a-4 et un mode perte de l'entreprise, afin de respecter les réglementations internes régissant la protection des ressources numériques. Les licences SnapLock font partie du bundle sécurité et conformité.

L'étendue de la prise en charge d'SnapLock est même passée à ONTAP 9. Les extensions les plus importantes sont les suivantes :

Efficacité du stockage : depuis la version ONTAP 9.9.1, SnapLock prend en charge les fonctionnalités d'efficacité du stockage, telles que la compaction des données, la déduplication entre les volumes et la compression adaptative pour les volumes et les agrégats SnapLock. Pour plus d'informations sur l'efficacité du stockage, voir link:https://docs.netapp.com/us-en/ontap/volumes/index.html["Présentation de la gestion du stockage logique avec l'interface de ligne de commande"].

Volumes FlexGroup : depuis ONTAP 9.11.1, SnapLock prend en charge les volumes FlexGroup, sauf lorsque vous utilisez la conservation à des fins juridiques, la conservation basée sur des événements et SnapLock pour SnapVault. Depuis la version ONTAP 9.12.1, SnapLock pour SnapVault est pris en charge avec les volumes FlexGroup.

Le stockage WORM SnapLock utilise la technologie NetApp Snapshot™ et peut exploiter la réplication SnapMirror® et les sauvegardes SnapVault® comme technologie de base pour assurer une protection de restauration de sauvegarde des données.

[NOTE]
====
System Manager vous permet d'effectuer ces tâches SnapLock : installation des licences SnapLock, configuration de l'horloge de conformité, création d'agrégats et de volumes SnapLock et configuration de volumes SnapLock. Pour d'autres tâches SnapLock, utilisez les API SnapLock.

====


== Les avantages de SnapLock

Vous pouvez effectuer les tâches suivantes :

* Configurez SnapLock
* Gestion des fichiers WORM pour la reprise après incident
* Archivage des fichiers en mode WORM
* Archivage des copies Snapshot sur le stockage WORM pour le stockage secondaire
* Mise en miroir des fichiers WORM pour la reprise après incident
* Conservation des fichiers WORM en cas de litiges avec la conservation légale
* Supprimez des fichiers WORM à l'aide de la fonction de suppression privilégiée
* Définissez la période de rétention des fichiers
* Déplacer un volume SnapLock
* Verrouiller une copie Snapshot pour assurer la protection contre les attaques par ransomware
* Vérifiez l'utilisation de SnapLock avec le journal d'audit
* Utilisez les API SnapLock




== SnapLock Compliance et Enterprise modes

Les modes SnapLock Compliance et Enterprise diffèrent principalement du niveau auquel chaque mode protège les fichiers WORM :

|===


| Mode SnapLock | Niveau de protection | Suppression du fichier WORM pendant la conservation 


 a| 
Mode de conformité
 a| 
Au niveau fichier
 a| 
Ne peut pas être supprimé



 a| 
Mode entreprise
 a| 
Au niveau du disque
 a| 
Peut être supprimé par l'administrateur de conformité à l'aide d'une procédure auditée de "suppression privilégiée"

|===
Une fois la période de rétention écoulée, vous êtes responsable de la suppression des fichiers dont vous n'avez plus besoin. Une fois qu'un fichier a été engagé en mode WORM, qu'il soit en mode conformité ou entreprise, il ne peut pas être modifié, même après l'expiration de la période de conservation.

Vous ne pouvez pas déplacer un fichier WORM pendant ou après la période de conservation. Vous pouvez copier un fichier WORM, mais la copie ne conserve pas ses caractéristiques WORM.

Le tableau suivant présente les différences de capacités prises en charge par les modes SnapLock Compliance et Enterprise :

|===


| Fonctionnalité | Conformité SnapLock | SnapLock Enterprise 


 a| 
Activer et supprimer des fichiers à l'aide de la suppression privilégiée
 a| 
Non
 a| 
Oui.



 a| 
Réinitialiser les disques
 a| 
Non
 a| 
Oui.



 a| 
Destruction des agrégats et des volumes SnapLock pendant la période de conservation
 a| 
Non
 a| 
Oui, à l'exception du volume du journal d'audit de SnapLock



 a| 
Renommer les agrégats ou les volumes
 a| 
Non
 a| 
Oui.



 a| 
Utiliser des disques non NetApp
 a| 
Non
 a| 
Oui (avec virtualisation FlexArray)



 a| 
Utilisation du volume SnapLock pour la journalisation des audits
 a| 
Oui.
 a| 
Oui, à partir de ONTAP 9.5

|===


== Fonctionnalités prises en charge et non prises en charge avec SnapLock

Le tableau suivant présente les fonctionnalités prises en charge avec le mode SnapLock Compliance, le mode SnapLock Enterprise ou les deux :

|===


| Fonction | Prise en charge par SnapLock Compliance | Pris en charge par SnapLock Enterprise 


 a| 
Groupes de cohérence
 a| 
Non
 a| 
Non



 a| 
FabricPool sur les agrégats SnapLock
 a| 
Non
 a| 
Oui, à partir de ONTAP 9.8. Toutefois, votre équipe de compte doit ouvrir une demande de modification des produits afin de documenter que les données FabricPool hiérarchisées vers un cloud public ou privé ne sont plus protégées par SnapLock, car les administrateurs cloud peuvent les supprimer.

[NOTE]
====
Vous devez savoir que les données FabricPool placées dans un cloud public ou privé n'sont plus protégées par SnapLock, car les administrateurs cloud peuvent les supprimer.

====


 a| 
Les agrégats Flash Pool
 a| 
Oui, à partir de ONTAP 9.1.
 a| 
Oui, à partir de ONTAP 9.1.



 a| 
FlexClone
 a| 
Vous pouvez cloner des volumes SnapLock, mais vous ne pouvez pas cloner des fichiers sur un volume SnapLock.
 a| 
Vous pouvez cloner des volumes SnapLock, mais vous ne pouvez pas cloner des fichiers sur un volume SnapLock.



 a| 
Volumes FlexGroup
 a| 
Oui, depuis ONTAP 9.11.1, les fonctionnalités suivantes ne sont cependant pas prises en charge :

* Obligation légale
* Conservation basée sur les événements
* SnapLock pour SnapVault (prise en charge à partir de ONTAP 9.12.1)


Vous devez également connaître les comportements suivants :

* L'horloge de conformité de volume (VCC) d'un volume FlexGroup est déterminée par le VCC du composant racine. Tous les composants non racines auront leur VCC étroitement synchronisé avec le VCC racine.
* Les propriétés de configuration de SnapLock sont définies uniquement sur la FlexGroup dans son ensemble. Les composants individuels ne peuvent pas avoir des propriétés de configuration différentes, telles que le temps de rétention par défaut et la période de validation automatique.

 a| 
Oui, depuis ONTAP 9.11.1, les fonctionnalités suivantes ne sont cependant pas prises en charge :

* Obligation légale
* Conservation basée sur les événements
* SnapLock pour SnapVault (prise en charge à partir de ONTAP 9.12.1)


Vous devez également connaître les comportements suivants :

* L'horloge de conformité de volume (VCC) d'un volume FlexGroup est déterminée par le VCC du composant racine. Tous les composants non racines auront leur VCC étroitement synchronisé avec le VCC racine.
* Les propriétés de configuration de SnapLock sont définies uniquement sur la FlexGroup dans son ensemble. Les composants individuels ne peuvent pas avoir des propriétés de configuration différentes, telles que le temps de rétention par défaut et la période de validation automatique.




 a| 
LUN
 a| 
Non
 a| 
Non



 a| 
Configurations MetroCluster
 a| 
Oui, dans les conditions suivantes :

* Depuis ONTAP 9.3, la conformité SnapLock est prise en charge sur les agrégats MetroCluster sans miroir.
* Depuis ONTAP 9.3, la conformité SnapLock est prise en charge sur les agrégats en miroir, mais uniquement si l'agrégat est utilisé pour héberger les volumes du journal d'audit SnapLock.
* Les configurations SnapLock spécifiques à SVM peuvent être répliquées sur les sites principal et secondaire à l'aide de MetroCluster.

 a| 
Oui, dans les conditions suivantes :

* Les agrégats SnapLock Enterprise sont pris en charge depuis la version ONTAP 9.
* Depuis ONTAP 9.3, les agrégats SnapLock Enterprise avec suppression privilégiée sont pris en charge.
* Les configurations SnapLock spécifiques à SVM peuvent être répliquées vers les deux sites à l'aide de MetroCluster.




 a| 
SAN
 a| 
Non
 a| 
Non



 a| 
SnapRestore pour un seul fichier
 a| 
Non
 a| 
Oui.



 a| 
Continuité de l'activité SnapMirror
 a| 
Non
 a| 
Non



 a| 
SnapRestore
 a| 
Non
 a| 
Oui.



 a| 
SMTape
 a| 
Non
 a| 
Non



 a| 
SnapMirror synchrone
 a| 
Non
 a| 
Non



 a| 
SSD
 a| 
Oui, à partir de ONTAP 9.1.
 a| 
Oui, à partir de ONTAP 9.1.

|===


== Configurations MetroCluster et horloges de conformité

Les configurations MetroCluster utilisent deux mécanismes d'horloge de conformité, l'horloge de conformité du volume (VCC) et l'horloge de conformité du système (SCC). Les VCC et SCC sont disponibles dans toutes les configurations SnapLock. Lorsque vous créez un nouveau volume sur un noeud, son VCC est initialisé avec la valeur actuelle du SCC sur ce noeud. Une fois le volume créé, la durée de rétention du volume et du fichier est toujours suivie avec le VCC.

Lorsqu'un volume est répliqué vers un autre site, son VCC est également répliqué. Lors d'un basculement de volume, du site A vers le site B, par exemple, le VCC continue d'être mis à jour sur le site B pendant que le SCC sur le site A s'arrête lorsque le site A passe hors ligne.

Lorsque le site A est remis en ligne et que le rétablissement du volume est effectué, l'horloge du site A SCC redémarre alors que le VCC du volume continue d'être mis à jour. Étant donné que le VCC est mis à jour en permanence, indépendamment des opérations de basculement et de rétablissement, les délais de conservation des fichiers ne dépendent pas des horloges SCC et ne sont pas extensibles.



== Transition depuis la version 7-mode

Vous pouvez migrer des volumes SnapLock de 7-mode vers ONTAP à l'aide de la fonctionnalité de transition basée sur la copie de l'outil de transition 7-mode. Le mode SnapLock du volume de destination, conformité ou entreprise doit correspondre au mode SnapLock du volume source. Vous ne pouvez pas utiliser la transition sans copie pour migrer des volumes SnapLock.



== Le cryptage

ONTAP propose des technologies de cryptage logicielles et matérielles qui permettent de garantir que les données au repos ne peuvent pas être lues si le support de stockage est requalifié, perdu ou volé.

*Avertissement :* NetApp ne peut pas garantir que les fichiers WORM protégés par SnapLock sur des disques ou volumes à autochiffrement seront récupérables en cas de perte de la clé d'authentification ou si le nombre de tentatives d'authentification échouées dépasse la limite spécifiée et entraîne le verrouillage permanent du disque. Vous êtes responsable de vous assurer contre les échecs d'authentification.

[NOTE]
====
Depuis ONTAP 9.2, les volumes chiffrés sont pris en charge sur les agrégats SnapLock.

====