---
permalink: snaplock/index.html 
sidebar: sidebar 
keywords: decide, archive, compliance, snaplock, unmodified, file, worm, storage, snap lock, mirror, unmirror. license, compliance clock, regulatory, governance, rules, govern 
summary: La technologie NetApp SnapLock peut être utilisée pour conserver les fichiers sous une forme non modifiée à des fins réglementaires et de gouvernance. 
---
= Présentation de l'archivage et de la conformité
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La technologie NetApp SnapLock peut être utilisée pour conserver les fichiers sous une forme non modifiée à des fins réglementaires et de gouvernance. Elle vous montre comment allouer des fichiers et des copies Snapshot sur le stockage « WORM » (Write Once, Read Many), ainsi que comment définir des périodes de conservation pour les données protégées WORM.

Vous devez utiliser ces procédures pour travailler avec SnapLock de l'une des manières suivantes :

* Vous souhaitez utiliser l'interface de ligne de commandes ONTAP et non System Manager, ni un outil de création de scripts automatisé.
+
System Manager propose un ensemble limité, mais important de technologies SnapLock. Vous pouvez installer les licences SnapLock, définir l'horloge de conformité, créer des agrégats et des volumes SnapLock et configurer des volumes SnapLock.

* Vous souhaitez créer des agrégats Compliance ou Enterprise pour héberger les volumes des journaux d'audit SnapLock sur des configurations MetroCluster, avec les restrictions suivantes :
+
** SnapLock Enterprise est pris en charge sur les agrégats en miroir et sans miroir.
** La conformité SnapLock est prise en charge uniquement sur les agrégats sans miroir.
+
Toutes les configurations MetroCluster prennent en charge les agrégats en miroir. Voir la link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Notes de version de ONTAP"] Pour déterminer si votre configuration MetroCluster prend en charge les agrégats sans miroir.



* Vous souhaitez utiliser les agrégats SnapLock Enterprise avec FabricPool.
+
Depuis la version ONTAP 9.8, les agrégats SnapLock Enterprise sont pris en charge par link:https://docs.netapp.com/us-en/ontap/fabricpool/index.html["FabricPool"].

* Vous n'utilisez pas les LUN SAN
+
Les LUN SAN ne sont pas prises en charge sur les volumes SnapLock. S'il est possible de déplacer des LUN SAN vers un volume SnapLock avec la technologie existante, cette opération n'est pas prise en charge, ni toute autre opération impliquant des LUN SAN sur un volume SnapLock.

* Vous n'utilisez pas SMTape.
+
SMTape n'est pas pris en charge par SnapLock.

* Vous ne créez pas d'agrégats Compliance pour les LUN de baies.
+
Les agrégats SnapLock Compliance ne prennent pas en charge les LUN de baies.

* Vous ne créez pas d'agrégats de conformité avec l'option SyncMirror.
+
Les agrégats de conformité SnapLock ne prennent pas en charge les plexes SyncMirror.



[NOTE]
====
Les disques SSD et les agrégats Flash Pool sont pris en charge par SnapLock à partir de ONTAP 9.1.

====