---
permalink: snaplock/initialize-complianceclock-task.html 
sidebar: sidebar 
keywords: snaplock, complianceclock, compliance clock, initialize, worm, retention, period, node, ntp, reset, resynchronize 
summary: 'La fonctionnalité SnapLock ComplanceClock évite toute altération susceptible de modifier la période de conservation des fichiers WORM. Vous devez initialiser l"horloge de conformité du système sur chaque nœud hébergeant un agrégat SnapLock. ' 
---
= Initialiser l'horloge de conformité
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapLock utilise le _volume Compliance Clock_ pour éviter toute altération susceptible de modifier la période de conservation des fichiers WORM. Vous devez d'abord initialiser le _système CompléanceClock_ sur chaque nœud hébergeant un agrégat SnapLock.

Depuis ONTAP 9.14.1, vous pouvez initialiser ou réinitialiser l'horloge de conformité du système en l'absence de volumes SnapLock ou de volumes sur lesquels le verrouillage des copies Snapshot est activé. La possibilité de réinitialiser permet aux administrateurs système de réinitialiser l'horloge de conformité du système dans les cas où elle a été mal initialisée ou de corriger la dérive de l'horloge sur le système. Dans ONTAP 9.13.1 et les versions antérieures, une fois que vous avez initialisé l'horloge de conformité sur un nœud, vous ne pouvez pas l'initialiser à nouveau.

.Avant de commencer
Pour réinitialiser l'horloge de conformité :

* Tous les nœuds du cluster doivent être en état de santé.
* Tous les volumes doivent être en ligne.
* Aucun volume ne peut être présent dans la file d'attente de récupération.
* Aucun volume SnapLock ne peut être présent.
* Aucun volume sur lequel le verrouillage des copies Snapshot est activé ne peut être présent.


Exigences générales pour l'initialisation de l'horloge de conformité :

* Vous devez être un administrateur de cluster pour effectuer cette tâche.
* link:../system-admin/install-license-task.html["La licence SnapLock doit être installée sur le nœud"].


.Description de la tâche
L'heure de l'horloge de conformité du système est héritée par le _volume Compliance Clock_, qui contrôle la période de conservation des fichiers WORM sur le volume. L'horloge de conformité du volume est initialisée automatiquement lorsque vous créez un nouveau volume SnapLock.

[NOTE]
====
Le réglage initial de l'horloge de conformité du système est basé sur l'horloge du système matériel actuel. C'est pourquoi vous devez vérifier que l'heure et le fuseau horaire du système sont corrects avant d'initialiser l'horloge de conformité du système sur chaque nœud. Une fois que vous avez initialisé l'horloge de conformité du système sur un nœud, vous ne pouvez plus l'initialiser lorsque des volumes SnapLock ou des volumes dont le verrouillage est activé sont présents.

====
.Étapes
Vous pouvez utiliser l'interface de ligne de commande ONTAP pour initialiser l'horloge de conformité ou, à partir de ONTAP 9.12.1, vous pouvez utiliser System Manager pour initialiser l'horloge de conformité.

[role="tabbed-block"]
====
.System Manager
--
. Accédez à *Cluster > Présentation*.
. Dans la section *noeuds*, cliquez sur *Initialize SnapLock Compliance Clock*.
. Pour afficher la colonne *horloge de conformité* et vérifier que l'horloge de conformité est initialisée, dans la section *Cluster > Présentation > nœuds*, cliquez sur *Afficher/Masquer* et sélectionnez *horloge de conformité SnapLock*.


--
--
.CLI
. Initialiser l'horloge de conformité du système :
+
`*snaplock compliance-clock initialize -node _node_name_*`

+
La commande suivante initialise l'horloge de conformité du système `node1`:

+
[listing]
----
cluster1::> snaplock compliance-clock initialize -node node1
----
. Lorsque vous y êtes invité, vérifiez que l'horloge du système est correcte et que vous souhaitez initialiser l'horloge de conformité :
+
[listing]
----
Warning: You are about to initialize the secure ComplianceClock of
the node "node1" to the current value of the node's system clock.
This procedure can be performed only once on a given node, so you
should ensure that the system time is set correctly before proceeding.

The current node's system clock is: Mon Apr 25 06:04:10 GMT 2016

Do you want to continue? (y|n): y
----
. Répétez cette procédure pour chaque nœud qui héberge un agrégat SnapLock.


--
====


== Activez la resynchronisation Compliance Clock pour un système configuré en NTP

Vous pouvez activer la fonction de synchronisation de l'heure de l'horloge de conformité SnapLock lorsqu'un serveur NTP est configuré.

.Ce dont vous avez besoin
* Cette fonction est disponible uniquement au niveau de privilège avancé.
* Vous devez être un administrateur de cluster pour effectuer cette tâche.
* link:../system-admin/install-license-task.html["La licence SnapLock doit être installée sur le nœud"].
* Cette fonction est disponible uniquement sur les plates-formes Cloud Volumes ONTAP, ONTAP Select et VSIM.


.Description de la tâche
Lorsque le démon d'horloge sécurisée SnapLock détecte une inclinaison au-delà du seuil, ONTAP utilise l'heure système pour réinitialiser les horloges de conformité du système et du volume. Une période de 24 heures est définie comme seuil d'inclinaison. Cela signifie que l'horloge de conformité du système est synchronisée sur l'horloge du système uniquement si l'inclinaison a plus d'un jour.

Le démon d'horloge sécurisée SnapLock détecte une inclinaison et modifie l'horloge de conformité en l'heure système. Toute tentative de modification de l'heure du système pour forcer la synchronisation de l'horloge de conformité avec l'heure du système échoue, car l'horloge de conformité se synchronise avec l'heure du système uniquement si l'heure du système est synchronisée avec l'heure NTP.

.Étapes
. Activez la fonction de synchronisation de l'heure de l'horloge de conformité SnapLock lorsqu'un serveur NTP est configuré :
+
`*snaplock compliance-clock ntp*`

+
La commande suivante active la fonction de synchronisation de l'horloge de conformité du système :

+
[listing]
----
cluster1::*> snaplock compliance-clock ntp modify -is-sync-enabled true
----
. Lorsque vous y êtes invité, vérifiez que les serveurs NTP configurés sont approuvés et que le canal de communication est sécurisé pour activer la fonction :
. Vérifiez que la fonction est activée :
+
`*snaplock compliance-clock ntp show*`

+
La commande suivante vérifie que la fonction de synchronisation de l'horloge de conformité du système est activée :

+
[listing]
----
cluster1::*> snaplock compliance-clock ntp show

Enable clock sync to NTP system time: true
----

