---
permalink: snaplock/move-snaplock-volume-task.html 
sidebar: sidebar 
keywords: move, snaplock, volume, command, destination, aggregate 
summary: Vous pouvez utiliser la commande volume Move pour déplacer un volume SnapLock vers un agrégat de destination. 
---
= Déplacer un volume SnapLock
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `volume move` Commande de déplacement d'un volume SnapLock vers un agrégat de destination.

.Ce dont vous avez besoin, 8217;ll
* Vous devez avoir créé un journal d'audit protégé SnapLock avant d'effectuer le déplacement de volume SnapLock.
+
link:create-audit-log-task.html["Créer un journal d'audit"].

* Si vous utilisez une version de ONTAP antérieure à ONTAP 9.10.1, l'agrégat de destination doit être du même type SnapLock que le volume SnapLock que vous souhaitez déplacer : conformité à la conformité ou entreprise à la norme. Depuis ONTAP 9.10.1, cette restriction est supprimée et un agrégat peut inclure des volumes Compliance et Enterprise SnapLock, ainsi que des volumes non SnapLock.
* Vous devez être un utilisateur ayant le rôle de sécurité SnapLock.


.Étapes
. Via une connexion sécurisée, connectez-vous à la LIF de gestion du cluster ONTAP :
+
`*ssh snaplock_user@cluster_mgmt_ip*`

. Déplacer un volume SnapLock :
+
`*volume move start -vserver _SVM_name_ -volume _SnapLock_volume_name_ -destination-aggregate _destination_aggregate_name_*`

. Vérifier l'état de l'opération de déplacement de volume :
+
`*volume move show -volume _SnapLock_volume_name_ -vserver _SVM_name_ -fields volume,phase,vserver*`


