---
permalink: snaplock/set-default-retention-period-task.html 
sidebar: sidebar 
keywords: snaplock, volume, command, modify, retention, period, file, set, default 
summary: Vous pouvez utiliser la commande volume SnapLock modify pour définir la période de conservation par défaut des fichiers sur un volume SnapLock. 
---
= Définir la période de conservation par défaut
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `volume snaplock modify` Commande pour définir la période de conservation par défaut pour les fichiers d'un volume SnapLock.

Le volume SnapLock doit être en ligne.

Le tableau suivant indique les valeurs possibles pour l'option de période de conservation par défaut :

[NOTE]
====
La période de conservation par défaut doit être supérieure ou égale à (>=) la période de rétention minimale et inférieure ou égale à (\<=) la période de rétention maximale.

====
|===
| Valeur | Unité | Remarques 


 a| 
0 - 65535
 a| 
secondes
 a| 



 a| 
0 - 24
 a| 
heures
 a| 



 a| 
0 - 365
 a| 
jours
 a| 



 a| 
0 - 12
 a| 
mois
 a| 



 a| 
0 - 100
 a| 
années
 a| 
À partir d'ONTAP 9.10.1. Pour les versions antérieures de ONTAP, la valeur est comprise entre 0 et 70.



 a| 
capacité
 a| 
-
 a| 
Utilisez la période de rétention maximale.



 a| 
minimum
 a| 
-
 a| 
Utilisez la période de rétention minimale.



 a| 
illimitée
 a| 
-
 a| 
Conservez toujours les fichiers.



 a| 
non spécifié
 a| 
-
 a| 
Conservez les fichiers jusqu'à ce qu'une période de conservation absolue soit définie.

|===
Les valeurs et les plages des périodes de rétention maximale et minimale sont identiques, sauf pour `max` et `min`, qui ne sont pas applicables. Pour plus d'informations sur cette tâche, voir link:set-retention-period-task.html["Définissez l'aperçu de la durée de conservation"].

Vous pouvez utiliser le `volume snaplock show` commande pour afficher les paramètres de la période de rétention du volume. Pour plus d'informations, consultez la page man de la commande

[NOTE]
====
Une fois qu'un fichier a été engagé à l'état WORM, vous pouvez prolonger mais pas raccourcir la période de rétention.

====
.Étapes
. Définissez la période de conservation par défaut pour les fichiers d'un volume SnapLock :
+
`*volume snaplock modify -vserver _SVM_name_ -volume _volume_name_ -default-retention-period _default_retention_period_ -minimum-retention-period _min_retention_period_ -maximum-retention-period _max_retention_period_*`

+
Pour obtenir la liste complète des options, consultez la page man de la commande.

+
[NOTE]
====
Les exemples suivants supposent que les périodes de rétention minimale et maximale n'ont pas été modifiées auparavant.

====
+
La commande suivante définit la période de conservation par défaut pour un volume Compliance ou Enterprise sur 20 jours :

+
[listing]
----
cluster1::> volume snaplock modify -vserver vs1 -volume vol1 -default-retention-period 20days
----
+
La commande suivante définit la période de conservation par défaut pour un volume Compliance sur 70 ans :

+
[listing]
----
cluster1::> volume snaplock modify -vserver vs1 -volume vol1 -maximum-retention-period 70years
----
+
La commande suivante définit la période de conservation par défaut pour un volume entreprise sur 10 ans :

+
[listing]
----
cluster1::> volume snaplock modify -vserver vs1 -volume vol1 -default-retention-period max -maximum-retention-period 10years
----
+
Les commandes suivantes définissent la période de conservation par défaut pour un volume entreprise sur 10 jours :

+
[listing]
----
cluster1::> volume snaplock modify -vserver vs1 -volume vol1 -minimum-retention-period 10days
cluster1::> volume snaplock modify -vserver vs1 -volume vol1 -default-retention-period min
----
+
La commande suivante définit la période de conservation par défaut d'un volume Compliance sur infinie :

+
[listing]
----
cluster1::> volume snaplock modify -vserver vs1 -volume vol1 -default-retention-period infinite -maximum-retention-period infinite
----

