---
permalink: snaplock/snaplock-concept.html 
sidebar: sidebar 
keywords: snaplock, worm, storage, compliance, enterprise, mode, sec, rule, 17a, license 
summary: 'SnapLock est une solution de conformité hautes performances pour les entreprises qui utilisent le stockage WORM pour conserver les fichiers sous une forme non modifiée à des fins réglementaires et de gouvernance. Une seule licence vous donne le droit d"utiliser SnapLock en mode strict conformité, afin de répondre aux exigences externes telles que la règle SEC 17a-4 et un mode perte de l"entreprise, afin de respecter les réglementations internes régissant la protection des ressources numériques.' 
---
= Qu'est-ce que SnapLock
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapLock est une solution de conformité hautes performances pour les entreprises qui utilisent le stockage WORM pour conserver les fichiers sous une forme non modifiée à des fins réglementaires et de gouvernance. Une seule licence vous permet d'utiliser SnapLock en stricte _Compliance mode_, afin de répondre à des obligations externes telles que la règle SEC 17a-4 et un oser _Enterprise mode_, dans le but de respecter les réglementations internes régissant la protection des ressources numériques.



== Différences entre les modes Compliance et Enterprise

Les modes SnapLock Compliance et Enterprise diffèrent principalement du niveau auquel chaque mode protège les fichiers WORM :

* Les fichiers WORM du mode de conformité sont protégés au niveau du disque.
+
Vous ne pouvez pas réinitialiser un disque contenant des agrégats Compliance-mode.

* Les fichiers WORM Enterprise-mode sont protégés au niveau fichier.


Une différence liée implique la façon dont chaque mode gère strictement les suppressions de fichiers :

* Les fichiers WORM du mode de conformité ne peuvent pas être supprimés pendant la période de conservation.
* Les fichiers WORM Enterprise-mode peuvent être supprimés pendant la période de conservation par l'administrateur de conformité à l'aide d'une procédure auditée _Privileged delete_.


Une fois la période de rétention écoulée, vous êtes responsable de la suppression des fichiers dont vous n'avez plus besoin. Une fois qu'un fichier a été engagé en mode WORM, qu'il soit en mode conformité ou entreprise, il ne peut pas être modifié, même après l'expiration de la période de conservation.

Vous ne pouvez pas déplacer un fichier WORM pendant ou après la période de conservation. Vous pouvez copier un fichier WORM, mais la copie ne conserve pas ses caractéristiques WORM.

Le tableau suivant présente les différences entre les modes SnapLock Compliance et Enterprise :

|===


| Fonctionnalité | Conformité SnapLock | SnapLock Enterprise 


 a| 
Suppression privilégiée
 a| 
Non
 a| 
Oui.



 a| 
Réinitialiser le disque
 a| 
Non
 a| 
Oui.



 a| 
Cet agrégat et le volume SnapLock sont détruites pendant la conservation
 a| 
Non
 a| 
Oui, à l'exception du volume du journal d'audit de SnapLock



 a| 
Renommer un agrégat ou un volume
 a| 
Non
 a| 
Oui.



 a| 
Disques non NetApp
 a| 
Non
 a| 
Oui (avec virtualisation FlexArray)



 a| 
Utilisation du volume SnapLock pour la journalisation des audits
 a| 
Oui.
 a| 
Oui, à partir de ONTAP 9.5

|===


== Fonctionnalités prises en charge et non prises en charge avec SnapLock

Le tableau suivant présente les fonctionnalités prises en charge avec le mode SnapLock Compliance, le mode SnapLock Enterprise ou les deux :

|===


| Fonction | Prise en charge par SnapLock Compliance | Pris en charge par SnapLock Enterprise 


 a| 
Groupes de cohérence
 a| 
Non
 a| 
Non



 a| 
SAN
 a| 
Non
 a| 
Non



 a| 
SnapMirror synchrone
 a| 
Non
 a| 
Non



 a| 
Continuité de l'activité SnapMirror
 a| 
Non
 a| 
Non



 a| 
SnapRestore pour un seul fichier
 a| 
Non
 a| 
Oui.



 a| 
SnapRestore
 a| 
Non
 a| 
Oui.



 a| 
FlexClone
 a| 
Vous pouvez cloner des volumes SnapLock, mais vous ne pouvez pas cloner des fichiers sur un volume SnapLock.
 a| 
Vous pouvez cloner des volumes SnapLock, mais vous ne pouvez pas cloner des fichiers sur un volume SnapLock.



 a| 
LUN
 a| 
Non
 a| 
Non



 a| 
SMTape
 a| 
Non
 a| 
Non



 a| 
Configurations MetroCluster
 a| 
Oui, dans les conditions suivantes :

* Depuis ONTAP 9.3, la conformité SnapLock est prise en charge sur les agrégats MetroCluster sans miroir.
* Depuis ONTAP 9.3, la conformité SnapLock est prise en charge sur les agrégats en miroir, mais uniquement si l'agrégat est utilisé pour héberger les volumes du journal d'audit SnapLock.
* Les configurations SnapLock spécifiques à SVM peuvent être répliquées sur les sites principal et secondaire à l'aide de MetroCluster.

 a| 
Oui, dans les conditions suivantes :

* Les agrégats SnapLock Enterprise sont pris en charge depuis la version ONTAP 9.
* Depuis ONTAP 9.3, les agrégats SnapLock Enterprise avec suppression privilégiée sont pris en charge.
* Les configurations SnapLock spécifiques à SVM peuvent être répliquées vers les deux sites à l'aide de MetroCluster.




 a| 
Prise en charge de FabricPools sur des agrégats SnapLock
 a| 
Non
 a| 
Oui, à partir de ONTAP 9.8. Toutefois, votre équipe de compte doit ouvrir une demande de modification des produits afin de documenter que les données FabricPool hiérarchisées vers un cloud public ou privé ne sont plus protégées par SnapLock, car les administrateurs cloud peuvent les supprimer.

[NOTE]
====
Vous devez savoir que les données FabricPool placées dans un cloud public ou privé n'sont plus protégées par SnapLock, car les administrateurs cloud peuvent les supprimer.

====


 a| 
Volumes FlexGroup
 a| 
Oui, depuis ONTAP 9.11.1, les fonctionnalités suivantes ne sont cependant pas prises en charge :

* Obligation légale
* Conservation basée sur les événements
* SnapLock pour SnapVault (prise en charge à partir de ONTAP 9.12.1)


Vous devez également connaître les comportements suivants :

* L'horloge de conformité de volume (VCC) d'un volume FlexGroup est déterminée par le VCC du composant racine. Tous les composants non racines auront leur VCC étroitement synchronisé avec le VCC racine.
* Les propriétés de configuration de SnapLock sont définies uniquement sur la FlexGroup dans son ensemble. Les composants individuels ne peuvent pas avoir des propriétés de configuration différentes, telles que le temps de rétention par défaut et la période de validation automatique.

 a| 
Oui, depuis ONTAP 9.11.1, les fonctionnalités suivantes ne sont cependant pas prises en charge :

* Obligation légale
* Conservation basée sur les événements
* SnapLock pour SnapVault (prise en charge à partir de ONTAP 9.12.1)


Vous devez également connaître les comportements suivants :

* L'horloge de conformité de volume (VCC) d'un volume FlexGroup est déterminée par le VCC du composant racine. Tous les composants non racines auront leur VCC étroitement synchronisé avec le VCC racine.
* Les propriétés de configuration de SnapLock sont définies uniquement sur la FlexGroup dans son ensemble. Les composants individuels ne peuvent pas avoir des propriétés de configuration différentes, telles que le temps de rétention par défaut et la période de validation automatique.


|===


== Configurations MetroCluster et horloges de conformité

Les configurations MetroCluster utilisent deux mécanismes d'horloge de conformité, l'horloge de conformité du volume (VCC) et l'horloge de conformité du système (SCC). Les VCC et SCC sont disponibles dans toutes les configurations SnapLock. Lorsque vous créez un nouveau volume sur un noeud, son VCC est initialisé avec la valeur actuelle du SCC sur ce noeud. Une fois le volume créé, la durée de rétention du volume et du fichier est toujours suivie avec le VCC.

Lorsqu'un volume est répliqué vers un autre site, son VCC est également répliqué. Lors d'un basculement de volume, du site A vers le site B, par exemple, le VCC continue d'être mis à jour sur le site B pendant que le SCC sur le site A s'arrête lorsque le site A passe hors ligne.

Lorsque le site A est remis en ligne et que le rétablissement du volume est effectué, l'horloge du site A SCC redémarre alors que le VCC du volume continue d'être mis à jour. Étant donné que le VCC est mis à jour en permanence, indépendamment des opérations de basculement et de rétablissement, les délais de conservation des fichiers ne dépendent pas des horloges SCC et ne sont pas extensibles.



== Validation de fichiers sur WORM

Vous pouvez utiliser une application pour valider les fichiers en mode WORM sur NFS ou CIFS, ou utiliser la fonctionnalité d'autovalidation de SnapLock pour allouer automatiquement les fichiers en mode WORM. Vous pouvez utiliser un fichier _WORM apppliable_ pour conserver les données écrites de manière incrémentielle, comme les informations de journal.



== Protection des données

SnapLock prend en charge les méthodes de protection des données qui doivent répondre à la plupart des exigences de conformité :

* Vous pouvez utiliser SnapLock pour SnapVault pour protéger les copies Snapshot WORM sur le stockage secondaire.
* Vous pouvez utiliser SnapMirror pour répliquer des fichiers WORM dans un autre emplacement géographique à des fins de reprise après incident.




== Efficacité du stockage

Depuis la version ONTAP 9.9.1, SnapLock prend en charge les fonctionnalités d'efficacité du stockage, telles que la compaction des données, la déduplication entre les volumes et la compression adaptative pour les volumes et les agrégats SnapLock.



== Transition depuis la version 7-mode

Vous pouvez utiliser la fonction de transition basée sur la copie de l'outil de transition 7-mode pour migrer des volumes SnapLock de 7-mode vers ONTAP. Le mode SnapLock du volume de destination, conformité ou entreprise doit correspondre au mode SnapLock du volume source. Vous ne pouvez pas utiliser la transition sans copie pour migrer des volumes SnapLock.



== Le cryptage

ONTAP propose des technologies de cryptage logicielles et matérielles qui permettent de garantir que les données au repos ne peuvent pas être lues si le support de stockage est requalifié, perdu ou volé.

*Avertissement :* NetApp ne peut pas garantir que les fichiers WORM protégés par SnapLock sur des disques ou volumes à autochiffrement seront récupérables en cas de perte de la clé d'authentification ou si le nombre de tentatives d'authentification échouées dépasse la limite spécifiée et entraîne le verrouillage permanent du disque. Vous êtes responsable de vous assurer contre les échecs d'authentification.

[NOTE]
====
Depuis ONTAP 9.2, les volumes chiffrés sont pris en charge sur les agrégats SnapLock.

====