---
permalink: snaplock/snaplock-apis-reference.html 
sidebar: sidebar 
keywords: snaplock, api, zephyr, xml, scripts, workflow 
summary: 'Vous pouvez utiliser les API Zephyr pour intégrer la fonctionnalité SnapLock dans les scripts ou l"automatisation des flux de travail. Les API utilisent la messagerie XML via HTTP, HTTPS et Windows DCE/RPC.' 
---
= Les API SnapLock
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser les API Zephyr pour intégrer la fonctionnalité SnapLock dans les scripts ou l'automatisation des flux de travail. Les API utilisent la messagerie XML via HTTP, HTTPS et Windows DCE/RPC. Pour en savoir plus, consultez le link:https://docs.netapp.com/us-en/ontap-automation/["Documentation sur l'automatisation ONTAP"^].



== abandon-empreinte-fichier

Annuler une opération d'empreinte digitale de fichier.



== fichier-empreinte-dump

Affiche les informations relatives aux empreintes digitales du fichier.



== fichier-empreinte-get-iter

Affiche l'état des opérations d'empreinte des fichiers.



== démarrage de fichier-empreinte-fichier

Générez une empreinte de fichier.



== snaplock-archive-vserver-log

Archivez le fichier journal d'audit actif.



== snaplock-create-vserver-log

Créer une configuration de journal d'audit pour un SVM.



== snaplock-delete-vserver-log

Supprime une configuration du journal d'audit pour une SVM.



== snaplock-file-privileged-delete

Exécutez une opération de suppression privilégiée.



== snaplock-get-file-retention

Obtenir la période de conservation d'un fichier.



== snaplock-get-node-conformité-clock

Obtenir la date et l'heure de la fin de l'horloge du nœud.



== snaplock-get-vserver-active-log-files-iter

Affiche l'état des fichiers journaux actifs.



== snaplock-get-vserver-log-iter

Afficher la configuration du journal d'audit.



== snaplock-modify-vserver-log

Modifier la configuration du journal d'audit d'un SVM



== snaplock-set-file-conservation

Définissez la durée de conservation d'un fichier.



== snaplock-set-node-compliance-clock

Définissez la date et l'heure de la fin de l'horloge du nœud.



== snaplock-volume-set-privileged-delete

Définissez l'option Privileged-delete sur un volume SnapLock Enterprise.



== volumes-get-snaplock-attrs

Obtenir les attributs d'un volume SnapLock.



== volume-set-snaplock-attrs

Définissez les attributs d'un volume SnapLock.
