---
permalink: nfs-trunking/adapt-exports-overview.html 
sidebar: sidebar 
keywords: NFS, servers, network, NFS trunking, adapt, single-path 
summary: 'Vous pouvez adapter une exportation NFS à chemin unique existante (sans ressources partagées) pour utiliser l"agrégation.' 
---
= Présentation de l'adaptation des exportations à chemin unique
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez adapter une exportation NFSv4.1 à chemin unique existante (sans ressources partagées) pour utiliser la mise en circuit. Les clients prenant en charge l'agrégation peuvent bénéficier de performances améliorées dès que l'agrégation est activée sur le serveur, à condition que les conditions préalables du serveur et du client aient été satisfaites.

L'adaptation d'une exportation à chemin unique pour l'agrégation vous permet de maintenir les jeux de données exportés dans leurs volumes et SVM existants. Pour ce faire, vous devez activer l'agrégation sur le serveur NFS, mettre à jour la mise en réseau et la configuration d'exportation, et remonter le partage exporté sur les clients.

L'activation de l'agrégation a pour effet de redémarrer le serveur. Les clients VMware doivent ensuite remonter les datastores exportés ; les clients Linux doivent remonter les volumes exportés avec le `max_connect` option.
