---
permalink: nfs-trunking/client-mount-task.html 
sidebar: sidebar 
keywords: NFS, servers, network, NFS trunking, data shares, Linux, VMware, mounts 
summary: 'Les clients Linux et VMware qui prennent en charge l"agrégation peuvent monter des volumes ou des partages de données à partir d"un serveur ONTAP NFS activé pour l"agrégation.' 
---
= Montez des volumes ONTAP ou des partages de données pour l'agrégation NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les clients Linux et VMware qui prennent en charge l'agrégation peuvent monter des volumes ou des partages de données à partir d'un serveur ONTAP NFSv4.1 qui est activé pour l'agrégation.

Découvrez link:index.html#supported-clients["clients pris en charge"].

[role="tabbed-block"]
====
.Configuration requise pour le client Linux
--
Si vous utilisez ONTAP 9.16.1 ou une version ultérieure et Red Hat Enterprise Linux version 8.7 ou ultérieure (pour RHEL 8) ou 9.2 ou ultérieure (pour RHEL 9) comme client Linux, un seul point de montage est requis pour le groupe de ressources partagées. Monter les volumes exportés avec cette commande, en utilisant l' `trunkdiscovery`option :

[source, cli]
----
mount <lif_ip>:<volume_name> </mount_path> -o trunkdiscovery,vers=4.1
----
Dans le cas contraire, un point de montage distinct est requis pour chaque connexion dans le groupe d'agrégation. Montez le volume exporté avec des commandes similaires à celles ci-dessous, en utilisant l' `max_connect`option :

[source, cli]
----
mount <lif1_ip>:<volume_name> </mount_path1> -o vers=4.1,max_connect=16
----
[source, cli]
----
mount <lif2_ip>:<volume_name> </mount_path2> -o vers=4.1,max_connect=16
----
La version (`vers`) la valeur doit être de `4.1` ou ultérieure.

Le `max_connect` la valeur correspond au nombre de connexions dans le groupe d'agrégation.

--
.Configuration requise pour le client VMware
--
Une instruction mount est requise, qui inclut une adresse IP pour chaque connexion du groupe d'agrégation.

Montez le datastore exporté avec une commande similaire à la suivante :

`#esxcli storage nfs41 -H lif1_ip, lif2_ip -s /mnt/sh are1 -v nfs41share`

Le `-H` les valeurs correspondent aux connexions dans le groupe d'agrégation.

--
====