---
permalink: cloud/volume-move-concept.html 
sidebar: sidebar 
keywords: volume move 
summary: 'Grâce à ONTAP, vous pouvez déplacer un volume FlexVol vers un autre niveau local (agrégat) ou nœud au sein d"une même machine virtuelle de stockage (SVM) afin d"équilibrer la capacité de stockage après avoir déterminé qu"il existe un déséquilibre entre la capacité de stockage. Grâce à Cloud Volumes ONTAP, vous pouvez déplacer un ou plusieurs volumes vers un autre système Cloud Volumes ONTAP ou vers un autre agrégat pour éviter tout problème de capacité. Vous devrez peut-être le faire si le système atteint sa limite de disque.' 
---
= Déplacement de volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Grâce à ONTAP, vous pouvez déplacer un volume FlexVol vers un autre niveau local (agrégat) ou nœud au sein d'une même machine virtuelle de stockage (SVM) afin d'équilibrer la capacité de stockage après avoir déterminé qu'il existe un déséquilibre entre la capacité de stockage. Grâce à Cloud Volumes ONTAP, vous pouvez déplacer un ou plusieurs volumes vers un autre système Cloud Volumes ONTAP ou vers un autre agrégat pour éviter tout problème de capacité. Vous devrez peut-être le faire si le système atteint sa limite de disque.

.Informations associées
https://docs.netapp.com/us-en/occm/task_managing_storage.html#moving-volumes-to-another-system-to-avoid-capacity-issues["Cloud Volumes ONTAP : déplacement de volumes vers un autre système pour éviter les problèmes de capacité"]

https://docs.netapp.com/us-en/occm/task_managing_storage.html#moving-volumes-to-another-aggregate-to-avoid-capacity-issues["Cloud Volumes ONTAP : déplacement de volumes vers un autre agrégat pour éviter les problèmes de capacité"]
