---
permalink: flexcache/add-license-task.html 
sidebar: sidebar 
keywords: add, flexcache, license, flex cache, volume, limit, capacity, term 
summary: 'Si vous exécutez ONTAP 9.6 ou une version antérieure, vous devez installer une licence FlexCache, qui correspond à une licence basée sur la capacité et la durée de validité, à l"aide de System Manager.' 
---
= Ajoutez une licence FlexCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous exécutez ONTAP 9.6 ou une version antérieure, vous devez installer une licence FlexCache, qui correspond à une licence basée sur la capacité et la durée de validité, à l'aide de System Manager.

.Description de la tâche
La licence FlexCache est une licence pour l'ensemble du cluster. La licence inclut une limite d'utilisation autorisée que vous achetez pour l'utilisation des volumes FlexCache dans le cluster. L'utilisation de l'espace par les volumes FlexCache sur le cluster ne doit pas dépasser la capacité de la limite d'utilisation autorisée. Si vous devez augmenter la limite d'utilisation de la licence, contactez votre représentant commercial.

Depuis ONTAP 9.7, la licence basée sur la capacité n'est pas requise. La licence FlexCache est fournie avec le pack ONTAP.

.Étapes
. Téléchargez le fichier de licence NetApp pour la licence FlexCache sur le site de support NetApp.
+
https://mysupport.netapp.com/site/global/dashboard["Support NetApp"]

. Utilisez System Manager pour charger la licence FlexCache sur le cluster :
+
.. Cliquez sur l'onglet *configurations* > *Cluster* > *licences*.
.. Dans la fenêtre *Forfaits*, cliquez sur *Ajouter*.
.. Dans la boîte de dialogue *Add License Packages*, cliquez sur *Choose files* pour sélectionner le fichier de licence NetApp que vous avez téléchargé, puis cliquez sur *Add* pour télécharger le fichier sur le cluster.



