---
permalink: flexcache/global-file-locking-task.html 
sidebar: sidebar 
keywords: global file locking, flexcache, relationship 
summary: 'Vous pouvez activer le verrouillage global des fichiers sur les volumes FlexCache si vous souhaitez bénéficier d"une cohérence sur la disponibilité.' 
---
= Activez le verrouillage global des fichiers sur les volumes ONTAP FlexCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À partir d'ONTAP 9.10.1, vous pouvez appliquer un verrouillage global des fichiers sur FlexCache volumes pour empêcher les lectures sur tous les fichiers mis en cache associés.

.Avant de commencer
* Le verrouillage global des fichiers requiert que les clusters contenant l'origine et tous les caches associés exécutent ONTAP 9.9.1 ou une version ultérieure. Le verrouillage global des fichiers peut être activé sur les volumes FlexCache nouveaux ou existants. La commande peut être exécutée sur un seul volume et s'applique à tous les volumes FlexCache associés.
* Vous devez être au niveau de privilège avancé pour activer le verrouillage global des fichiers.
* Si vous restaurez une version de ONTAP antérieure à la version 9.9.1, le verrouillage global des fichiers doit d'abord être désactivé sur les caches d'origine et associés. Pour désactiver, à partir du volume d'origine, exécutez : `volume flexcache prepare-to-downgrade -disable-feature-set 9.10.0`
* Le processus permettant d'activer le verrouillage global des fichiers dépend de la présence ou non de caches dans l'origine :
+
** <<enable-gfl-new>>
** <<enable-gfl-existing>>






== Activation du verrouillage global des fichiers sur les nouveaux volumes FlexCache

.Étapes
. Création du volume FlexCache avec `-is-global-file-locking` défini sur vrai :
+
`volume flexcache create volume _volume_name_ -is-global-file-locking-enabled true`

+

NOTE: La valeur par défaut de `-is-global-file-locking` est « faux ». Lorsque c'est le cas `volume flexcache create` les commandes sont exécutées sur un volume, elles doivent être passées avec `-is-global-file-locking enabled` défini sur « vrai ».





== Activation du verrouillage global des fichiers sur les volumes FlexCache existants

.Étapes
. Le verrouillage global des fichiers doit être défini à partir du volume d'origine.
. L'origine ne peut avoir d'autres relations existantes (par exemple, SnapMirror). Toute relation existante doit être dissociée. Tous les caches et volumes doivent être connectés au moment de l'exécution de la commande. Pour vérifier l'état de la connexion, exécutez :
+
`volume flexcache connection-status show`

+
L'état de tous les volumes répertoriés doit s'afficher sous `connected.` Pour plus d'informations, voir link:view-connection-status-origin-task.html["Afficher l'état d'une relation FlexCache"] ou link:synchronize-properties-origin-volume-task.html["Synchronisation des propriétés d'un volume FlexCache depuis une origine"].

. Activer le verrouillage global des fichiers sur les caches :
+
`volume flexcache origin config show/modify -volume _volume_name_ -is-global-file-locking-enabled true`



.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/["Référence de commande ONTAP"^]

