---
permalink: flexcache/index.html 
sidebar: sidebar 
keywords: flexcache, volumes, faster, data, access, configure, manage, overview, origin volumes 
summary: 'Vous pouvez configurer et gérer les volumes FlexCache pour accélérer l"accès aux données.' 
---
= En savoir plus sur les volumes ONTAP FlexCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La technologie NetApp FlexCache accélère l'accès aux données, réduit la latence des réseaux WAN et diminue les coûts de bande passante WAN pour les charges de travail intensives en lecture, notamment lorsque les clients doivent accéder aux mêmes données de manière répétée. Lorsque vous créez un volume FlexCache, vous créez un cache distant d'un volume (d'origine) existant qui ne contient que les données fréquemment utilisées (données actives) du volume d'origine.

Lorsqu'un volume FlexCache reçoit une demande de lecture des données actives qu'il contient, il peut répondre plus rapidement que le volume d'origine, car il n'est pas nécessaire de se déplacer aussi loin pour atteindre le client.  Lorsqu'un volume FlexCache reçoit une demande de lecture de données rarement lues (données inactives), il récupère les données requises depuis le volume d'origine, puis les stocke avant de répondre à la demande du client. Les demandes de lecture suivantes pour ces données sont ensuite envoyées directement depuis le volume FlexCache. Après la première demande, les données n'ont plus besoin de traverser le réseau ou d'être servies à partir d'un système fortement chargé.  Supposons, par exemple, que vous rencontrez des goulots d'étranglement au sein de votre cluster au niveau d'un point d'accès unique pour les données fréquemment demandées.  Vous pouvez utiliser les volumes FlexCache au sein du cluster pour fournir plusieurs points de montage aux données actives, ce qui réduit les goulots d'étranglement et améliore les performances. Prenons un autre exemple : supposons que vous deviez réduire le trafic réseau vers un volume accessible depuis plusieurs clusters. Vous pouvez utiliser des volumes FlexCache pour distribuer les données actives du volume d'origine sur les clusters de votre réseau.  Cela réduit le trafic WAN en offrant aux utilisateurs des points d'accès plus étroits.

Vous pouvez également utiliser la technologie FlexCache pour améliorer les performances dans les environnements cloud et de cloud hybride. Un volume FlexCache vous aide à migrer vos workloads vers le cloud hybride en mettant en cache des données depuis un data Center sur site vers le cloud.  Vous pouvez également utiliser les volumes FlexCache pour supprimer les silos de clouds en mettant en cache les données d'un fournisseur cloud à un autre ou dans deux régions du même fournisseur de cloud.

Avec ONTAP 9.10.1, c'est possible link:global-file-locking-task.html["activer le verrouillage global des fichiers"] Sur tous les volumes FlexCache. Le verrouillage global des fichiers empêche un utilisateur d'accéder à un fichier déjà ouvert par un autre utilisateur.  Les mises à jour du volume d'origine sont ensuite distribuées simultanément à tous les volumes FlexCache.

Depuis ONTAP 9.9.1, les volumes FlexCache conservent une liste de fichiers introuvables.  Cela permet de réduire le trafic réseau en supprimant la nécessité d'envoyer plusieurs appels vers l'origine lorsque les clients recherchent des fichiers inexistants.

Une liste de supplémentaires link:supported-unsupported-features-concept.html["Fonctionnalités prises en charge pour les volumes FlexCache et leurs volumes d'origine"], Comprenant une liste des protocoles pris en charge par la version ONTAP, est également disponible.

Pour en savoir plus sur l'architecture de la technologie ONTAP FlexCache, consultez le link:https://www.netapp.com/pdf.html?item=/media/7336-tr4743.pdf["Tr-4743 : FlexCache dans ONTAP"^].



== Vidéos



=== Comment FlexCache peut réduire la latence des réseaux WAN et les temps de lecture des données globales

video::rbbH0l74RWc[youtube,width=848,height=480]


=== Découvrez les avantages de ONTAP FlexCache en matière de performances !

video::bWi1-8Ydkpg[youtube,width=848,height=480]