---
permalink: flexcache/prepopulate-volume-task.html 
sidebar: sidebar 
keywords: prepopulating, flexcache, volume 
summary: 'Le volume FlexCache peut être prérempli afin de réduire le temps d"accès aux données en cache.' 
---
= Préremplissage d'un volume FlexCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le volume FlexCache peut être prérempli afin de réduire le temps d'accès aux données en cache.

.Ce dont vous avez besoin
* Vous devez être un administrateur de cluster au niveau de privilège avancé
* Les chemins que vous transmettez pour la préremplissage doivent exister ou l'opération de préremplissage échoue.


.Description de la tâche
* Préremplissage lit uniquement les fichiers et parcourt les répertoires
* L'indicateur is-recursion s'applique à la liste complète des répertoires transmis à la préremplissage


.Étapes
. Préremplissage d'un volume FlexCache :
+
`volume flexcache prepopulate -cache-vserver vserver_name -cache-volume -path-list path_list -is-recursion true|false`

+
Cet exemple inclut un chemin de répertoire unique pour la prépopulation :

+
[listing]
----
cluster1::*> flexcache prepopulate start -cache-vserver vs2 -cache-volume fg_cachevol_1 -path-list /dir1
  (volume flexcache prepopulate start)
[JobId 207]: FlexCache prepopulate job queued.
----
+
Cet exemple inclut une liste de plusieurs chemins pour la prépopulation :

+
[listing]
----
cluster1::*> flexcache prepopulate start -cache-vserver vs2 -cache-volume fg_cachevol_1 -path-list /dir1,/dir2,/dir3,/dir4
  (volume flexcache prepopulate start)
[JobId 208]: FlexCache prepopulate job queued.
----
+
Cet exemple inclut un chemin non valide pour la prépopulation :

+
[listing]
----
cluster1::*> flexcache prepopulate start -cache-volume vol_cache2_vs3_c2_vol_origin1_vs1_c1 -cache-vserver vs3_c2 -path-list /dir1, dir5, dir6
  (volume flexcache prepopulate start)

Error: command failed: Path(s) "dir5, dir6" does not exist in origin volume
       "vol_origin1_vs1_c1" in Vserver "vs1_c1".
----
. Afficher le nombre de fichiers lus :
+
`job show -id job_ID -ins`


