---
permalink: flexcache/prepopulate-volume-task.html 
sidebar: sidebar 
keywords: prepopulating, flexcache, volume 
summary: 'Le volume FlexCache peut être prérempli afin de réduire le temps d"accès aux données en cache.' 
---
= Préremplir les volumes ONTAP FlexCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le volume FlexCache peut être prérempli afin de réduire le temps d'accès aux données en cache.

.Avant de commencer
* Vous devez être un administrateur de cluster au niveau de privilège avancé
* Les chemins que vous transmettez pour la préremplissage doivent exister ou l'opération de préremplissage échoue.


.Description de la tâche
* Préremplissage lit uniquement les fichiers et parcourt les répertoires
* Le `-isRecursion` indicateur s'applique à la liste complète des répertoires transmis à préremplissage


.Étapes
. Préremplissage d'un volume FlexCache :
+
`volume flexcache prepopulate -cache-vserver vserver_name -cache-volume -path-list _path_list_ -isRecursion true|false`

+
** Le `-path-list` paramètre indique le chemin du répertoire relatif que vous souhaitez préremplir à partir du répertoire racine d'origine. Par exemple, si le répertoire racine d'origine est nommé /origine et qu'il contient des répertoires /origine/dir1 et /origine/dir2, vous pouvez spécifier la liste des chemins comme suit : `-path-list dir1, dir2` ou `-path-list /dir1, /dir2`.
** La valeur par défaut du `-isRecursion` Le paramètre est vrai.
+
Cet exemple préremplit un chemin de répertoire unique :

+
[listing]
----
cluster1::*> flexcache prepopulate start -cache-vserver vs2 -cache-volume fg_cachevol_1 -path-list /dir1
  (volume flexcache prepopulate start)
[JobId 207]: FlexCache prepopulate job queued.
----
+
Cet exemple prérenseigne les fichiers de plusieurs répertoires :

+
[listing]
----
cluster1::*> flexcache prepopulate start -cache-vserver vs2 -cache-volume fg_cachevol_1 -path-list /dir1,/dir2,/dir3,/dir4
  (volume flexcache prepopulate start)
[JobId 208]: FlexCache prepopulate job queued.
----
+
Cet exemple préremplit un seul fichier :

+
[listing]
----
cluster1::*> flexcache prepopulate start -cache-vserver vs2 -cache-volume fg_cachevol_1 -path-list /dir1/file1.txt
  (volume flexcache prepopulate start)
[JobId 209]: FlexCache prepopulate job queued.
----
+
Cet exemple prérenseigne tous les fichiers de l'origine :

+
[listing]
----
cluster1::*> flexcache prepopulate start -cache-vserver vs2 -cache-volume fg_cachevol_1 -path-list / -isRecursion true
  (volume flexcache prepopulate start)
[JobId 210]: FlexCache prepopulate job queued.
----
+
Cet exemple inclut un chemin non valide pour la prépopulation :

+
[listing]
----
cluster1::*> flexcache prepopulate start -cache-volume vol_cache2_vs3_c2_vol_origin1_vs1_c1 -cache-vserver vs3_c2 -path-list /dir1, dir5, dir6
  (volume flexcache prepopulate start)

Error: command failed: Path(s) "dir5, dir6" does not exist in origin volume
       "vol_origin1_vs1_c1" in Vserver "vs1_c1".
----


. Afficher le nombre de fichiers lus :
+
`job show -id job_ID -ins`



.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/job-show.html["affichage du travail"^]

