---
permalink: flexcache/sizing-concept.html 
sidebar: sidebar 
keywords: guidelines, sizing, flexcache, volume 
summary: Avant de commencer le provisionnement des volumes, vous devez connaître les limites des volumes FlexCache. 
---
= Conseils pour le dimensionnement des volumes ONTAP FlexCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de commencer le provisionnement des volumes, vous devez connaître les limites des volumes FlexCache.

La taille limite d'un volume FlexVol s'applique à un volume d'origine. La taille d'un volume FlexCache peut être inférieure ou égale au volume d'origine. La meilleure pratique pour la taille d'un volume FlexCache consiste à correspondre à au moins 10 % de la taille du volume d'origine.

Vous devez également connaître les limites supplémentaires suivantes sur les volumes FlexCache :

[cols="55,15,15,15"]
|===


| Limite | ONTAP 9.8 et versions ultérieures | ONTAP 9.7 | ONTAP 9.6 - 9.5 


| Nombre maximal de volumes FlexCache que vous pouvez créer à partir d'un volume d'origine | 100 | 10 | 10 


| Nombre maximal recommandé de volumes d'origine par nœud | 100 | 100 | 10 


| Nombre maximal recommandé de volumes FlexCache par nœud | 100 | 100 | 10 


| Nombre maximal recommandé de composants FlexGroup dans un volume FlexCache par nœud | 800 | 800 | 40 


| Nombre maximal de composants par volume FlexCache par nœud | 32 | 32 | 32 
|===
.Informations associées
* https://mysupport.netapp.com/NOW/products/interoperability["Interopérabilité NetApp"^]

