---
permalink: volumes/assign-volume-efficiency-policy-task.html 
sidebar: sidebar 
keywords: assign, volume efficiency policy, volume 
summary: 'Vous pouvez affecter une stratégie d"efficacité à un volume pour exécuter une opération de déduplication ou de compression des données à l"aide de la commande volume Efficiency modify.' 
---
= Affecter une stratégie d'efficacité du volume à un volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez affecter une stratégie d'efficacité à un volume pour exécuter l'opération de déduplication ou de compression des données en utilisant le `volume efficiency modify` commande.

.Description de la tâche
Lorsqu'une stratégie d'efficacité est attribuée à un volume secondaire SnapVault, seul l'attribut de priorité d'efficacité du volume est pris en compte lors de l'exécution des opérations d'efficacité du volume. Les planifications de tâches sont ignorées et le processus de déduplication est exécuté lorsque des mises à jour incrémentielles sont effectuées sur le volume secondaire SnapVault.

.Étape
. Utilisez le `volume efficiency modify` commande permettant d'affecter une policy à un volume.


.Exemple
La commande suivante affecte la politique d'efficacité des volumes nommée New_policy avec le volume Vola :

`volume efficiency modify -vserver vs1 -volume VolA -policy new_policy`
