---
permalink: volumes/assign-volume-efficiency-policy-task.html 
sidebar: sidebar 
keywords: assign, volume efficiency policy, volume, efficiency policy 
summary: 'Vous pouvez attribuer une règle d"efficacité à un volume pour exécuter des opérations de déduplication ou de compression de données à l"aide de la commande volume Efficiency modify.' 
---
= Affecter une stratégie d'efficacité du volume à un volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez attribuer une règle d'efficacité à un volume pour exécuter les opérations de déduplication ou de compression des données à l'aide de la `volume efficiency modify` commande.

.Avant de commencer
Assurez-vous que vous link:create-efficiency-policy-task.html["créez la règle d'efficacité des volumes"] avant de l'affecter à un volume.

.Description de la tâche
Lorsqu'une stratégie d'efficacité est attribuée à un volume secondaire SnapVault, seul l'attribut de priorité d'efficacité du volume est pris en compte lors de l'exécution des opérations d'efficacité du volume. Les planifications de tâches sont ignorées et le processus de déduplication est exécuté lorsque des mises à jour incrémentielles sont effectuées sur le volume secondaire SnapVault.

.Étape
. Utilisez le `volume efficiency modify` commande permettant d'affecter une policy à un volume.


.Exemple
La commande suivante attribue la règle d'efficacité du volume nommée `new_policy` au volume `VolA`:

`volume efficiency modify -vserver vs1 -volume VolA -policy new_policy`

Pour en savoir plus, `volume efficiency modify` consultez le link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-modify.html["Référence de commande ONTAP"^].
