---
permalink: volumes/automatic-deduplication-schedule-aff-concept.html 
sidebar: sidebar 
keywords: manage, automatic, volume-level, background, deduplication, aff systems 
summary: 'Depuis ONTAP 9.3, il est possible de gérer la déduplication en arrière-plan au niveau des volumes pour s"exécuter automatiquement à l"aide d"une règle autoAFF prédéfinie. Aucune configuration manuelle des planifications n"est requise. La règle automatique effectue une déduplication continue en arrière-plan.' 
---
= Gérez la déduplication automatique en arrière-plan au niveau des volumes sur les systèmes AFF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis ONTAP 9.3, il est possible de gérer la déduplication en arrière-plan au niveau des volumes pour s'exécuter automatiquement à l'aide d'un volume prédéfini `auto` Politique de AFF. Aucune configuration manuelle des planifications n'est requise. Le `auto` cette règle exécute la déduplication continue en arrière-plan.

Le `auto` il est défini sur la règle pour tous les volumes nouvellement créés et pour tous les volumes mis à niveau qui n'ont pas été configurés manuellement pour la déduplication en arrière-plan. Vous pouvez modifier la règle en `default` ou toute autre stratégie de désactivation de la fonction.

Si un volume est déplacé d'un système non AFF vers un système AFF, la `auto` la règle est activée par défaut sur le nœud de destination. Si un volume est déplacé d'un nœud AFF vers un nœud non AFF, la `auto` la règle sur le nœud de destination est remplacée par le `inline-only` règle par défaut.

Sous AFF, le système contrôle tous les volumes qui ont le `auto` les règles et dépriorise le volume qui a moins d'économies ou a fréquemment remplacé. Les volumes dépriorisés ne participent plus à la déduplication automatique en arrière-plan. La journalisation des modifications sur les volumes non prioritaires est désactivée et les métadonnées sur le volume sont tronquées.

Les utilisateurs peuvent promouvoir le volume dépriorisé pour participer de nouveau à la déduplication automatique en arrière-plan à l'aide de la `volume efficiency promote` commande disponible au niveau de privilège avancé.
