---
permalink: volumes/autoshrink-snapshot-copy-deletion-concept.html 
sidebar: sidebar 
keywords: how, autoshrink functionality, interacts with, snapshot copy, deletion, automatic 
summary: 'Étant donné que la fonctionnalité de création automatique de lien réduit la taille d"une FlexVol volume, elle peut également affecter la suppression automatique des instantanés de volume.' 
---
= Fonction de suppression automatique et de capture d'écran
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Étant donné que la fonctionnalité de création automatique de lien réduit la taille d'une FlexVol volume, elle peut également affecter la suppression automatique des instantanés de volume.

La fonctionnalité Autohrink interagit avec la suppression automatique de l'instantané de volume de la manière suivante :

* Si le mode de dimensionnement automatique et la suppression automatique des snapshots sont tous deux `grow_shrink` activés, une fois la taille réduite d'un volume, une suppression automatique des snapshots peut se déclencher.
+
En effet, la réserve Snapshot est basée sur un pourcentage de la taille du volume (5 % par défaut) et ce pourcentage est désormais basé sur une taille de volume plus petite. Cela peut entraîner un débordement des snapshots hors de la réserve et leur suppression automatique.

* Si le `grow_shrink` mode de dimensionnement automatique est activé et que vous supprimez manuellement un snapshot, il est possible qu'il déclenche une réduction automatique du volume.

