---
permalink: volumes/change-maximum-number-files-allowed-concept.html 
sidebar: sidebar 
keywords: considerations, changing, maximum number of files, allowed, flexvol volume 
summary: 'Les volumes FlexVol comportent un nombre maximal de fichiers qu"ils peuvent contenir. Vous pouvez modifier le nombre maximal de fichiers pour un volume. Toutefois, avant de procéder à cette modification, vous devez comprendre son impact sur le volume.' 
---
= Considérations relatives à la modification du nombre maximal de fichiers autorisés sur un volume FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les volumes FlexVol comportent un nombre maximal de fichiers qu'ils peuvent contenir. Vous pouvez modifier le nombre maximal de fichiers pour un volume. Toutefois, avant de procéder à cette modification, vous devez comprendre son impact sur le volume.

Si vos données requièrent un grand nombre de fichiers ou de répertoires très volumineux, vous pouvez étendre la capacité des fichiers ou des répertoires ONTAP. Cependant, vous devez connaître les limites et les restrictions qui s'appliquent avant de continuer.

Le nombre de fichiers qu'un volume peut contenir est déterminé par le nombre d'inodes qu'il possède. Un _inode_ est une structure de données qui contient des informations sur les fichiers. Les volumes ont des inodes privés et publics. Les inodes publics sont utilisés pour les fichiers visibles par l'utilisateur ; les inodes privés sont utilisés pour les fichiers utilisés en interne par ONTAP. Vous pouvez modifier uniquement le nombre maximal d'inodes publics pour un volume. Vous ne pouvez pas affecter le nombre d'inodes privés.

ONTAP définit automatiquement le nombre maximal d'inodes publics pour un volume récemment créé, d'après la taille du volume : 1 inode pour 1 32 Ko de taille de volume. Lorsque la taille d'un volume augmente, soit directement par un administrateur, soit automatiquement par ONTAP via la fonctionnalité de taille automatique, ONTAP augmente également (si nécessaire) le nombre maximal d'inodes publics de façon à ce qu'il y ait au moins 1 inode par taille de volume de 32 Ko, Jusqu'à ce que le volume atteigne environ 680 Go.

Dans les versions de ONTAP antérieures à 9.13.1, l'augmentation de la taille du volume supérieure à 680 Go n'entraîne pas automatiquement plus d'inodes, car ONTAP ne crée pas automatiquement plus de 22,369,621 inodes. Si vous avez besoin de plus de fichiers que le nombre par défaut pour un volume de taille quelconque, vous pouvez utiliser la commande volume modify pour augmenter le nombre maximal d'inodes pour le volume.

À partir de ONTAP 9.13.1, le nombre maximal d'inodes continue de croître, il y a donc 1 inode par 32 Ko de volume, même si celui-ci est supérieur à 680 Go. Cette croissance se poursuit jusqu'à ce que le volume atteigne le maximum de l'inode 2,147,483,632

Vous pouvez également réduire le nombre maximal d'inodes publics. Cette opération ne modifie pas la quantité d'espace actuellement allouée aux inodes, mais elle réduit la quantité maximale d'espace que le fichier d'inode public peut consommer. Toutefois, une fois l'espace alloué aux inodes, il n'est jamais renvoyé au volume. Par conséquent, la diminution du nombre maximal d'inodes en dessous du nombre d'inodes actuellement alloués ne renvoie pas à ce volume l'espace utilisé par les inodes alloués mais inutilisés.

.Plus d'informations
* xref:display-file-inode-usage-task.html[Afficher l'utilisation du fichier ou de l'inode]

