---
permalink: volumes/change-inactive-data-threshold-task.html 
sidebar: sidebar 
keywords: storage, efficiency, temperature, change, efficient, default, threshold, inactive, compression, cold data, frequency, threshold, scan, coldness, temperature-sensitive 
summary: 'Vous pouvez modifier la fréquence d"analyse des données inactives d"ONTAP en modifiant le seuil de froid sur les volumes grâce à l"efficacité du stockage sensible à la température.' 
---
= Modifiez le seuil de compression des données inactives du volume dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier la fréquence d'analyse des données inactives d'ONTAP en modifiant le seuil de froid sur les volumes grâce à l'efficacité du stockage sensible à la température.

.Avant de commencer
Vous devez être administrateur du cluster ou du SVM et utiliser le niveau de privilège avancé de l'interface de ligne de commandes ONTAP.

.Description de la tâche
Le seuil de froid peut être de 1 à 60 jours. Le seuil par défaut est de 14 jours.

.Étapes
. Définissez le niveau de privilège :
+
`set -privilege advanced`

. Modifier la compression des données inactives sur un volume :
+
`volume efficiency inactive-data-compression modify -vserver <vserver_name> -volume <volume_name> -threshold-days <integer>`



Pour en savoir pluslink:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-inactive-data-compression-modify.html#description["modification de la compression des données inactives"], consultez le document de référence sur les commandes ONTAP.
