---
permalink: volumes/commands-activate-modify-quotas-reference.html 
sidebar: sidebar 
keywords: commands to, activate, modify, quotas, command, commands 
summary: 'Les commandes de quota de volume vous permettent de modifier l"état des quotas et de configurer la journalisation des messages des quotas.' 
---
= Commandes permettant d'activer et de modifier des quotas dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
`volume quota` les commandes vous permettent de modifier l'état des quotas et de configurer la journalisation des messages des quotas. Selon ce que vous devez faire, vous pouvez utiliser les commandes suivantes pour activer et modifier les quotas :

[cols="2*"]
|===
| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Activer les quotas (également appelés _initializing_ eux)
 a| 
`volume quota on`



 a| 
Redimensionner les quotas existants
 a| 
`volume quota resize`



 a| 
Désactivez les quotas
 a| 
`volume quota off`



 a| 
Modifiez la journalisation des messages des quotas, activez les quotas, désactivez les quotas ou redimensionnez les quotas existants
 a| 
`volume quota modify`

|===
Pour en savoir plus, `volume quota` consultez le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+quota["Référence de commande ONTAP"^].
