---
permalink: volumes/commands-move-volumes-reference.html 
sidebar: sidebar 
keywords: commands, moving, volumes, to move, move 
summary: 'L"interface de ligne de commandes ONTAP fournit des commandes spécifiques pour la gestion du déplacement de volumes.' 
---
= Commandes de déplacement de volumes dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interface de ligne de commandes ONTAP fournit des commandes spécifiques pour la gestion du déplacement de volumes. En fonction de ce que vous devez faire, utilisez les commandes suivantes pour gérer les règles de quotas et les politiques de quotas :

[cols="2*"]
|===
| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Annuler une opération de déplacement de volume active.
 a| 
`volume move abort`



 a| 
Montrer l'état d'un volume passant d'un agrégat à un autre.
 a| 
`volume move show`



 a| 
Commencez à déplacer un volume d'un agrégat à un autre.
 a| 
`volume move start`



 a| 
Gestion des agrégats cibles pour le déplacement de volumes
 a| 
`volume move target-aggr`



 a| 
Déclencher la mise en service d'une tâche de déplacement.
 a| 
`volume move trigger-cutover`



 a| 
Modifiez la durée de blocage de l'accès client si la valeur par défaut n'est pas correcte.
 a| 
`volume move start` ou `volume move modify` avec le `-cutover-window` paramètre. Le `volume move modify` commande est une commande avancée et le `-cutover-window` est un paramètre avancé.



 a| 
Déterminez ce que fait le système si l'opération de déplacement de volume ne peut pas être terminée pendant le blocage de l'accès client.
 a| 
`volume move start` ou `volume move modify` avec le `-cutover-action` paramètre. Le `volume move modify` commande est une commande avancée et le `-cutover-action` est un paramètre avancé.

|===
Pour en savoir plus, `volume move` consultez le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+move["Référence de commande ONTAP"^].
