---
permalink: volumes/commands-manage-flexvol-volumes-reference.html 
sidebar: sidebar 
keywords: commands for, managing, flexvol, volumes, manage 
summary: 'Il existe des commandes spécifiques pour gérer les volumes FlexVol à l"aide de l"interface de ligne de commandes ONTAP.' 
---
= Commandes de gestion des volumes FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il existe des commandes spécifiques pour gérer les volumes FlexVol à l'aide de l'interface de ligne de commandes ONTAP.

[cols="2*"]
|===
| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Mettre un volume en ligne
 a| 
`volume online`



 a| 
Modifier la taille d'un volume
 a| 
`volume size`



 a| 
Déterminer l'agrégat associé d'un volume
 a| 
`volume show`



 a| 
Déterminer l'agrégat associé pour tous les volumes d'une machine virtuelle de stockage (SVM)
 a| 
`volume show -vserver -fields aggregate`



 a| 
Détermination du format d'un volume
 a| 
`volume show -fields block-type`



 a| 
Montez un volume sur un autre volume à l'aide d'une jonction
 a| 
`volume mount`



 a| 
Placez un volume à l'état restreint
 a| 
`volume restrict`



 a| 
Renommer un volume
 a| 
`volume rename`



 a| 
Mettre un volume hors ligne
 a| 
`volume offline`

|===
Consultez la page man pour chaque commande pour plus d'informations.
