---
permalink: volumes/commands-display-space-usage-reference.html 
sidebar: sidebar 
keywords: commands for, displaying, space, usage, information, display 
summary: 'Vous utilisez les commandes de volume et d"agrégat de stockage pour voir comment l"espace est utilisé dans vos agrégats et volumes et leurs snapshots.' 
---
= Commandes permettant d'afficher les informations d'utilisation de l'espace
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous utilisez les `storage aggregate` commandes et `volume` pour voir comment l'espace est utilisé dans vos agrégats et volumes et leurs snapshots.

À partir de ONTAP 9.18.1, la commande  `storage aggregate show-space` modifie la façon dont la capacité logique référencée et la capacité logique non référencée sont rapportées. La capacité logique référencée comptabilise les blocs référencés dans tous les objets et les blocs non référencés dans les objets fragmentés. La capacité logique non référencée comptabilise uniquement les blocs non référencés dans les objets ayant dépassé le seuil de saturation et pouvant être supprimés ou défragmentés.

Par exemple, lorsque vous utilisez le seuil de remplissage agrégé par défaut de 40 % pour ONTAP S3 et StorageGRID, 60 % des blocs d’un objet doivent être non référencés avant que les blocs ne soient signalés comme capacité non référencée.

Dans les versions antérieures à ONTAP 9.18.1, la capacité logique référencée indique les blocs référencés dans tous les objets (complets et fragmentés). La capacité logique non référencée indique les blocs non référencés dans tous les objets.

[cols="2*"]
|===
| Pour afficher des informations sur... | Utilisez cette commande... 


 a| 
Les agrégats, y compris des informations sur les pourcentages d'espace utilisé et disponible, la taille de la réserve de snapshots et d'autres informations sur l'utilisation de l'espace
 a| 
`storage aggregate show`

`storage aggregate show-space -fields snap-size-total,used-including-snapshot-reserve`



 a| 
Mode d'utilisation des disques et des groupes RAID dans un agrégat et état RAID
 a| 
`storage aggregate show-status`



 a| 
Quantité d'espace disque qui serait récupérée si vous supprimez un snapshot spécifique
 a| 
`volume snapshot compute-reclaimable` (avancé)



 a| 
Quantité d'espace utilisée par un volume
 a| 
`volume show -fields size,used,available,percent-used`

`volume show-space`



 a| 
Quantité d'espace utilisé par un volume dans l'agrégat contenant
 a| 
`volume show-footprint`

|===
.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+aggregate+show["l'agrégat de stockage s'affiche"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-space.html["espace d'exposition de stockage agrégé"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-status.html["agrégat de stockage afficher-état"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-compute-reclaimable.html["possibilité de réclamation pour le calcul des snapshots de volume"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-show.html["volume affiché"^]

