---
permalink: volumes/configure-volume-provision-options-task.html 
sidebar: sidebar 
keywords: configure, volume, provisioning, options 
summary: Vous pouvez configurer un volume pour le provisionnement fin, le provisionnement lourd ou le provisionnement semi-lourd. 
---
= Configurer les options de provisionnement de volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer un volume pour le provisionnement fin, le provisionnement lourd ou le provisionnement semi-lourd.

Réglage du `-space-slo` option à `thick` assure les éléments suivants :

* Le volume entier est préalloué dans l'agrégat. Vous ne pouvez pas utiliser `volume create` ou `volume modify` commande pour configurer les volumes `-space-guarantee` option.
* 100 % de l'espace requis pour les écrasements est réservé. Vous ne pouvez pas utiliser `volume modify` commande pour configurer les volumes `-fractional-reserve` option


Réglage du `-space-slo` option à `semi-thick` assure les éléments suivants :

* Le volume entier est préalloué dans l'agrégat. Vous ne pouvez pas utiliser `volume create` ou `volume modify` commande pour configurer les volumes `-space-guarantee` option.
* Aucun espace n'est réservé aux écrasements. Vous pouvez utiliser le `volume modify` commande pour configurer les volumes `-fractional-reserve` option.
* La suppression automatique des copies Snapshot est activée.


.Étape
. Configurez les options de provisionnement des volumes :
+
`volume create -vserver _vserver_name_ -volume _volume_name_ -aggregate _aggregate_name_ -space-slo none|thick|semi-thick -space-guarantee none|volume`

+
Le `-space-guarantee` par défaut, l'option est `none` Pour les systèmes AFF et pour les volumes non-AFF DP. Sinon, elle est définie par défaut sur `volume`. Pour les volumes FlexVol existants, utilisez le `volume modify` commande permettant de configurer les options de provisionnement.

+
La commande suivante configure vol1 sur SVM vs1 pour le provisionnement fin :

+
[listing]
----
cluster1::> volume create –vserver vs1 -volume vol1 -space-guarantee none
----
+
La commande suivante configure vol1 sur le SVM vs1 pour le provisionnement Thick :

+
[listing]
----
cluster1::> volume create –vserver vs1 -volume vol1 -space-slo thick
----
+
La commande suivante configure vol1 sur le SVM vs1 pour le provisionnement semi-lourd :

+
[listing]
----
cluster1::> volume create –vserver vs1 -volume vol1 -space-slo semi-thick
----

