---
permalink: volumes/convert-directory-qtree-task.html 
sidebar: sidebar 
keywords: convert, directory, qtree 
summary: 'Si vous avez un répertoire à la racine d"un volume FlexVol que vous souhaitez convertir en qtree, vous devez migrer les données contenues dans le répertoire vers un nouveau qtree avec le même nom, en utilisant votre application client.' 
---
= Convertir un répertoire en présentation qtree
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous avez un répertoire à la racine d'un volume FlexVol que vous souhaitez convertir en qtree, vous devez migrer les données contenues dans le répertoire vers un nouveau qtree avec le même nom, en utilisant votre application client.

Les étapes que vous effectuez pour convertir un répertoire en qtree dépendent du client que vous utilisez. Le processus suivant décrit les tâches générales à effectuer :

.Étapes
. Renommer le répertoire à créer dans un qtree.
. Créer un qtree avec le nom du répertoire d'origine.
. Utiliser l'application client pour déplacer le contenu du répertoire dans le nouveau qtree.
. Supprimez le répertoire maintenant vide.
+
[NOTE]
====
Vous ne pouvez pas supprimer un répertoire s'il est associé à un partage CIFS existant.

====

