---
permalink: volumes/convert-directory-qtree-task.html 
sidebar: sidebar 
keywords: convert, directory, qtree 
summary: 'Si vous disposez d"un répertoire à la racine d"une FlexVol volume que vous souhaitez convertir en qtree, vous devez migrer les données contenues dans ce répertoire vers un nouveau qtree du même nom.' 
---
= Convertir un répertoire en qtree
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous disposez d'un répertoire à la racine d'un FlexVol volume que vous souhaitez convertir en qtree, vous devez migrer les données contenues dans ce répertoire vers un nouveau qtree du même nom, à l'aide de votre application client.

.Description de la tâche
Les étapes que vous effectuez pour convertir un répertoire en qtree dépendent du client que vous utilisez. Le processus suivant décrit les tâches générales à effectuer.

.Avant de commencer
Vous ne pouvez pas supprimer un répertoire s'il est associé à un partage CIFS existant.

.Étapes
. Renommer le répertoire à créer dans un qtree.
. Créer un qtree avec le nom du répertoire d'origine.
. Utiliser l'application client pour déplacer le contenu du répertoire dans le nouveau qtree.
. Supprimez le répertoire maintenant vide.

