---
permalink: volumes/convert-directory-qtree-windows-client-task.html 
sidebar: sidebar 
keywords: convert, directory to a qtree, using, windows client 
summary: 'Pour convertir un répertoire en qtree à l"aide d"un client Windows, vous renommez le répertoire, créez un qtree sur le système de stockage et déplacez le contenu du répertoire vers le qtree.' 
---
= Convertir un répertoire en qtree à l'aide d'un client Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour convertir un répertoire en qtree à l'aide d'un client Windows, vous renommez le répertoire, créez un qtree sur le système de stockage et déplacez le contenu du répertoire vers le qtree.

.Description de la tâche
Vous devez utiliser l'Explorateur Windows pour cette procédure. Vous ne pouvez pas utiliser l'interface de ligne de commande Windows ou l'environnement d'invite DOS.

.Étapes
. Ouvrez l'Explorateur Windows.
. Cliquez sur la représentation du dossier du répertoire à modifier.
+
[NOTE]
====
Le répertoire doit résider à la racine du volume qui le contient.

====
. Dans le menu *fichier*, sélectionnez *Renommer* pour donner un nom différent à ce répertoire.
. Sur le système de stockage, utilisez le `volume qtree create` commande permettant de créer un qtree avec le nom d'origine du répertoire.
. Dans l'Explorateur Windows, ouvrez le dossier du répertoire renommé et sélectionnez les fichiers qu'il contient.
. Faites glisser ces fichiers dans la représentation de dossier du nouveau qtree.
+
[NOTE]
====
Plus le nombre de sous-dossiers contenus dans le dossier que vous déplacez est important, plus l'opération de déplacement prend de temps.

====
. Dans le menu *fichier*, sélectionnez *Supprimer* pour supprimer le dossier de répertoire renommé, maintenant vide.

