---
permalink: volumes/create-flexclone-snapmirror-concept.html 
sidebar: sidebar 
keywords: considerations, creating, flexclone volume, from snapmirror, source, destination, volume, flexclone, snapmirror, future 
summary: Vous pouvez créer un volume FlexClone à partir du volume source ou de destination dans une relation SnapMirror existante, mais cela peut affecter les futures opérations de réplication SnapMirror. 
---
= Considérations relatives à la création d'un volume FlexClone à partir d'une source SnapMirror ou d'un volume de destination
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer un volume FlexClone depuis le volume source ou de destination dans une relation SnapMirror volume existante. Cela pourrait cependant empêcher les futures opérations de réplication SnapMirror de se terminer correctement.

Il est possible que la réplication ne fonctionne pas, car lorsque vous créez le volume FlexClone, vous pouvez verrouiller une copie Snapshot utilisée par SnapMirror. Dans ce cas, SnapMirror arrête la réplication sur le volume de destination jusqu'à ce que le volume FlexClone soit détruit ou séparé de son volume parent. Vous avez deux options pour résoudre ce problème :

* Si vous avez besoin que le volume FlexClone soit temporaire et que vous pouvez prendre en charge un arrêt temporaire de la réplication SnapMirror, vous pouvez créer le volume FlexClone et le supprimer ou le diviser du volume parent autant que possible.
+
La réplication SnapMirror se poursuit normalement lorsque le volume FlexClone est supprimé ou est séparé de son parent.

* Si un arrêt temporaire de la réplication SnapMirror n'est pas acceptable, vous pouvez créer une copie Snapshot dans le volume source SnapMirror, puis utiliser cette copie Snapshot pour créer le volume FlexClone. (Si vous créez le volume FlexClone à partir du volume de destination, vous devez attendre que cette copie Snapshot soit répliquée vers le volume de destination SnapMirror.)
+
Cette méthode de création d'une copie Snapshot dans le volume source SnapMirror vous permet de créer le clone sans verrouiller la copie Snapshot utilisée par SnapMirror.


