---
permalink: volumes/create-flexclone-file-flexclone-lun-task.html 
sidebar: sidebar 
keywords: create, flexclone file, flexclone lun, efficient, clone 
summary: Vous pouvez créer des clones compacts et rapides de fichiers et de LUN dans des volumes FlexVol ou FlexClone. 
---
= Créez un fichier FlexClone ou un LUN FlexClone dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer des clones rapides et compacts des fichiers et des LUN présents dans les volumes FlexVol ou des volumes FlexClone à l'aide de `volume file clone create` commande.

.Avant de commencer
* La licence FlexClone doit être installée sur le cluster. Cette licence est incluse avec link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"].
* Si plusieurs plages de blocs sont utilisées pour le clonage de sous-LUN ou le clonage de sous-fichiers, les numéros de blocs ne doivent pas se chevaucher.
* Si vous créez un sous-LUN ou un sous-fichier sur des volumes dont la compression adaptative est activée, les plages de blocs ne doivent pas être mal alignées.
+
Cela signifie que le numéro du bloc de début de la source et le numéro du bloc de début de la destination doivent être alignés de manière uniforme ou impaire.



.Description de la tâche
En fonction des privilèges attribués par l'administrateur du cluster, un administrateur du SVM peut créer des fichiers FlexClone et des LUN FlexClone.

Vous pouvez spécifier le paramètre de suppression automatique des fichiers FlexClone et des LUN FlexClone lors de la création et de la modification de clones. Par défaut, le paramètre de suppression automatique est désactivé.

Lorsque vous créez un clone, vous pouvez le remplacer par une LUN FlexClone ou un fichier FlexClone existant à l'aide du `volume file clone create` commande avec `-overwrite-destination` paramètre.

Lorsque le nœud atteint sa charge maximale de partage, il n'accepte temporairement plus les requêtes de création de fichiers FlexClone et de LUN FlexClone, et émet un `EBUSY` message d'erreur. Lorsque la charge fractionnée du nœud tombe en dessous du maximum, le nœud accepte les demandes de création des fichiers FlexClone et des LUN FlexClone de nouveau. Vous devez patienter jusqu'à ce que le nœud ait la capacité de créer les clones avant de réessayer la requête de création.

La LUN FlexClone hérite de l'attribut réservations d'espace de la LUN parent. Une LUN FlexClone à espace réservé requiert autant d'espace que la LUN parent à espace réservé. Si la LUN FlexClone n'est pas Space-Reserved, l'espace du volume doit être suffisant pour prendre en charge les modifications apportées au clone.

.Étapes
. Si vous clonez une LUN, vérifiez qu'elle n'est pas mappée ou en cours d'écriture sur.
. Créez le LUN ou le fichier FlexClone :
+
`volume file clone create -vserver _vserver_name_ -volume _volume_name_ -source-path _source_path_ -destination-path _destination_path_`

+
L'exemple suivant montre comment créer un fichier FlexClone file1_clone du fichier parent file1_source dans le volume vol1 :

+
[listing]
----
cluster1::> volume file clone create -vserver vs0 -volume vol1 -source-path /file1_source -destination-path /file1_clone
----
+
Pour en savoir plus, `volume file clone create` consultez le link:https://docs.netapp.com/us-en/ontap-cli/volume-file-clone-create.html["Référence de commande ONTAP"^].





== Créez des LUN FlexClone à partir d'un snapshot d'un volume

Vous pouvez utiliser un snapshot de votre volume pour créer des copies FlexClone de vos LUN. Les copies FlexClone des LUN sont à la fois lisibles et inscriptibles.

.Ce dont vous avez besoin
Une licence FlexClone doit être installée. Cette licence est incluse avec link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"].

.Description de la tâche
La LUN FlexClone hérite de l'attribut réservations d'espace de la LUN parent. Une LUN FlexClone à espace réservé requiert autant d'espace que la LUN parent à espace réservé. Si la LUN FlexClone n'est pas Space-Reserved, l'espace du volume doit être suffisant pour prendre en charge les modifications apportées au clone.

.Étapes
. Vérifiez que la LUN n'est pas mappée ou en cours d'écriture sur.
. Créer un snapshot du volume qui contient les LUN :
+
`volume snapshot create -vserver _vserver_name_ -volume _volume_name_ -snapshot _snapshot_name_`

+
Vous devez créer un snapshot (le snapshot de sauvegarde) de la LUN à cloner.

. Créer la LUN FlexClone à partir du snapshot :
+
`volume file clone create -vserver _vserver_name_ -volume _volume_name_ -source-path _source_path_ -snapshot-name _snapshot_name_ -destination-path _destination_path_`

+
Si le LUN FlexClone doit être disponible pour la suppression automatique, vous devez inclure `-autodelete true`. Si vous créez cette LUN FlexClone dans un volume avec provisionnement semi-lourd, vous devez activer la suppression automatique pour toutes les LUN FlexClone.

. Vérifiez que la LUN FlexClone est correcte :
+
`lun show -vserver _vserver_name_`

+
[listing]
----

Vserver Path                      State    Mapped    Type     Size
------- ----------------------    -------- --------- -------- -------
vs1     /vol/vol1/lun1_clone      online   unmapped windows   47.07MB
vs1     /vol/vol1/lun1_snap_clone online   unmapped windows   47.07MB
----

