---
permalink: volumes/deduplication-flexclone-files-luns-concept.html 
sidebar: sidebar 
keywords: how, deduplication, works, flexclone files, fexclone luns 
summary: 'Vous pouvez efficacement utiliser l"espace de stockage physique des blocs de données en créant un fichier FlexClone ou une LUN FlexClone du fichier parent et de la LUN parent dans un volume activé pour la déduplication.' 
---
= Fonctionnement de la déduplication avec les fichiers FlexClone et les LUN FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez efficacement utiliser l'espace de stockage physique des blocs de données en créant un fichier FlexClone ou une LUN FlexClone du fichier parent et de la LUN parent dans un volume activé pour la déduplication.

Le mécanisme de partage des blocs utilisé par les fichiers et les LUN FlexClone est également utilisé par la déduplication. Vous pouvez optimiser les économies d'espace réalisées sur un volume FlexVol en activant la déduplication sur le volume, puis en clonant le volume pour lequel la déduplication a été activée.

[NOTE]
====
Lors de l'exécution du `sis undo` Sur un volume activé pour la déduplication, vous ne pouvez pas créer les fichiers FlexClone et les LUN FlexClone des fichiers parent et des LUN parent qui résident sur ce volume.

====