---
permalink: volumes/default-quotas-concept.html 
sidebar: sidebar 
keywords: default quotas, quotas, quota, default 
summary: 'Vous pouvez utiliser des quotas par défaut pour appliquer un quota à toutes les instances d"un type de quota donné. Les quotas par défaut vous permettent également de modifier facilement les quotas.' 
---
= Fonctionnement des quotas par défaut
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser des quotas par défaut pour appliquer un quota à toutes les instances d'un type de quota donné. Par exemple, un quota utilisateur par défaut affecte tous les utilisateurs du système pour le volume FlexVol ou qtree spécifié. Par ailleurs, les quotas par défaut vous permettent de modifier facilement vos quotas.

Vous pouvez utiliser des quotas par défaut pour appliquer automatiquement une limite à un grand ensemble de cibles de quotas sans avoir à créer de quotas distincts pour chaque cible. Par exemple, si vous souhaitez limiter la plupart des utilisateurs à 10 Go d'espace disque, vous pouvez spécifier un quota utilisateur par défaut de 10 Go d'espace disque au lieu de créer un quota pour chaque utilisateur. Si vous avez des utilisateurs spécifiques pour lesquels vous souhaitez appliquer une limite différente, vous pouvez créer des quotas explicites pour ces utilisateurs. (Quotas explicites--quotas avec une cible ou une liste spécifique de cibles--outrepasser les quotas par défaut.)

En outre, les quotas par défaut vous permettent d'utiliser le redimensionnement plutôt que la réinitialisation lorsque vous souhaitez que les modifications de quotas prennent effet. Par exemple, si vous ajoutez un quota utilisateur explicite à un volume qui dispose déjà d'un quota utilisateur par défaut, vous pouvez activer le nouveau quota en le redimensionnant.

Les quotas par défaut peuvent être appliqués aux trois types de cibles de quota (utilisateurs, groupes et qtrees).

Les quotas par défaut n'ont pas nécessairement des limites spécifiées ; un quota par défaut peut être un quota de suivi.

Un quota est indiqué par une cible qui est soit une chaîne vide ("") soit un astérisque (*), selon le contexte :

* Lorsque vous créez un quota à l'aide de `volume quota policy rule create` commande, paramétrage du `-target` le paramètre d'une chaîne vide ("") crée un quota par défaut.
+
Pour en savoir plus, `volume quota policy rule create` consultez le link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-policy-rule-create.html["Référence de commande ONTAP"^].

* Dans le `volume quota policy rule create` commande, le `-qtree` paramètre spécifie le nom du qtree vers lequel la règle de quotas s'applique. Ce paramètre n'est pas applicable aux règles de type d'arborescence. Pour les règles de type utilisateur ou groupe au niveau du volume, ce paramètre doit contenir « ».
* Dans la sortie du `volume quota policy rule show` commande, un quota par défaut apparaît avec une chaîne vide ("") comme cible.
+
Pour en savoir plus, `volume quota policy rule show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-policy-rule-show.html["Référence de commande ONTAP"^].

* Dans la sortie du `volume quota report` Commande, un quota par défaut apparaît avec un astérisque (*) comme identifiant et indicateur de quota.
+
Pour en savoir plus, `volume quota report` consultez le link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-report.html["Référence de commande ONTAP"^].





== Exemple de quota utilisateur par défaut

La règle de quota suivante utilise un quota utilisateur par défaut pour appliquer une limite de 50 Mo à chaque utilisateur pour vol1 :

[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol1 -policy-name default -type user -target "" -qtree "" -disk-limit 50m

cluster1::> volume quota policy rule show -vserver vs0 -volume vol1

Vserver: vs0               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   ""        ""      off          50MB        -       -        -          -
----
Si un utilisateur du système entre une commande qui ferait que les données de l'utilisateur prennent plus de 50 Mo dans vol1 (par exemple, l'écriture dans un fichier à partir d'un éditeur), la commande échoue.
