---
permalink: volumes/default-user-quotas-volume-affect-qtrees-concept.html 
sidebar: sidebar 
keywords: how, default, user, quotas, flexvol volume, affect, quotas, qtrees, volume 
summary: 'Lorsqu"un quota utilisateur par défaut est défini pour un volume FlexVol, un quota utilisateur par défaut est automatiquement créé pour chaque qtree contenu par ce volume pour lequel un quota Tree explicite ou dérivé existe.' 
---
= La manière dont les quotas d'utilisateur par défaut d'un volume FlexVol affectent les quotas des qtrees de ce volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsqu'un quota utilisateur par défaut est défini pour un volume FlexVol, un quota utilisateur par défaut est automatiquement créé pour chaque qtree contenu par ce volume pour lequel un quota Tree explicite ou dérivé existe.

Si un quota utilisateur par défaut sur le qtree existe déjà, il reste inchangé lorsque le quota utilisateur par défaut sur le volume est créé.

Les quotas d'utilisateur par défaut créés automatiquement sur les qtrees ont les mêmes limites que le quota d'utilisateur par défaut que vous créez pour le volume.

Un quota utilisateur explicite pour des remplacements de qtree (remplace les limites appliquées par) le quota utilisateur par défaut créé automatiquement, de la même manière qu'il remplace un quota utilisateur par défaut sur ce qtree créé par un administrateur.
