---
permalink: volumes/delete-directories-concept.html 
sidebar: sidebar 
keywords: deleting, directories, delete, fast 
summary: 'Depuis ONTAP 9.8, vous pouvez supprimer des répertoires volumineux avec des latences inférieures. Cette méthode de suppression du répertoire améliorée peut être mise en œuvre par le biais d"une nouvelle API REST ou via l"interface de ligne de commande ONTAP.' 
---
= Vue d'ensemble de la suppression des répertoires
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis ONTAP 9.8, vous pouvez supprimer des répertoires volumineux avec des latences inférieures. Cette méthode de suppression du répertoire améliorée peut être mise en œuvre par le biais d'une nouvelle API REST ou via l'interface de ligne de commande ONTAP. Pour plus d'informations, voir xref:../flexgroup/fast-directory-delete-asynchronous-task.adoc[Supprimez rapidement des fichiers et des répertoires sur le cluster]

Depuis ONTAP 9.9.1, vous pouvez également utiliser System Manager pour supprimer rapidement le répertoire. Pour plus d'informations, voir xref:../task_nas_file_system_analytics_take_corrective_action.adoc[Prendre les mesures correctives basées sur l'analytique].
