---
permalink: volumes/differences-hard-soft-threshold-quotas-concept.html 
sidebar: sidebar 
keywords: differences, hard, soft, threshold, quotas, quota, notification, prevent 
summary: Les quotas stricts empêchent les opérations, tandis que les seuils et les quotas conditionnels déclenchent des notifications. 
---
= Différences entre les quotas conditionnels, inconditionnels et inconditionnels
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les quotas matériels empêchent les opérations tandis que les quotas conditionnels déclenchent des notifications.

Les quotas matériels imposent une limite stricte aux ressources système, toute opération qui entraînerait un dépassement de la limite. Les paramètres suivants créent des quotas matériels :

* Paramètre de limite de disque
* Paramètre de limite de fichiers


Les quotas conditionnels envoient un message d'avertissement lorsque l'utilisation des ressources atteint un certain niveau, mais n'affectent pas les opérations d'accès aux données. Vous pouvez ainsi prendre les mesures appropriées avant le dépassement du quota. Les paramètres suivants créent des quotas conditionnels :

* Seuil du paramètre limite de disque
* Paramètre limite de disque logiciel
* Paramètre de limite des fichiers logiciels


Les quotas Threshold et Soft Disk permettent aux administrateurs de recevoir plus d'une notification concernant un quota. En général, les administrateurs définissent le seuil de limite de disque sur une valeur légèrement inférieure à la limite de disque, de sorte que le seuil fournit un « avertissement final » avant que les écritures ne commencent à échouer.
