---
permalink: volumes/disable-data-compression-volume-task.html 
sidebar: sidebar 
keywords: disable data compression 
summary: 'Vous pouvez désactiver la compression des données sur un volume à l"aide de la commande volume Efficiency modify.' 
---
= Désactiver la compression des données sur un volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez désactiver la compression des données sur un volume à l'aide de la `volume efficiency modify` commande. Pour en savoir plus, `volume efficiency modify` consultez le link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-modify.html["Référence de commande ONTAP"^].

.Description de la tâche
Pour désactiver la compression post-traitement, vous devez d'abord désactiver la compression inline sur le volume.

.Étapes
. Arrêtez toutes les opérations d'efficacité du volume actuellement actives sur le volume :
+
`volume efficiency stop`

. Désactiver la compression des données :
+
`volume efficiency modify`

+
Les données compressées existantes resteront compressées sur le volume. Seules les nouvelles écritures entrant dans le volume ne sont pas compressées.



.Exemples
La commande suivante désactive la compression à la volée sur le volume Vola :

`volume efficiency modify -vserver vs1 -volume VolA -inline-compression false`

La commande suivante désactive la compression post-traitement et la compression à la volée sur volume Vola :

`volume efficiency modify -vserver vs1 -volume VolA -compression false -inline-compression false`

Pour en savoir plus, `volume efficiency stop` consultez le link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-stop.html["Référence de commande ONTAP"^].
