---
permalink: volumes/display-file-inode-usage-task.html 
sidebar: sidebar 
keywords: display, file, inode, usage 
summary: 'Les volumes FlexVol comportent un nombre maximal de fichiers qu"ils peuvent contenir. Le fait de connaître le nombre de fichiers contenus par vos volumes vous aide à déterminer si vous devez augmenter le nombre d"inodes (publics) pour vos volumes afin de les empêcher d"atteindre leur limite maximale de fichiers.' 
---
= Afficher l'utilisation du fichier ou de l'inode
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les volumes FlexVol comportent un nombre maximal de fichiers qu'ils peuvent contenir. Le fait de connaître le nombre de fichiers contenus par vos volumes vous aide à déterminer si vous devez augmenter le nombre d'inodes (publics) pour vos volumes afin de les empêcher d'atteindre leur limite maximale de fichiers.

.Description de la tâche
Les inodes publics peuvent être libres (ils ne sont pas associés à un fichier) ou utilisés (ils pointent vers un fichier). Le nombre d'inodes libres pour un volume correspond au nombre total d'inodes pour le volume moins le nombre d'inodes utilisés (le nombre de fichiers).

Si des partages au niveau des qtrees et des volumes sont présents sur le même pool FlexVol ou SCVMM, les qtrees apparaissent comme des répertoires du partage FlexVol. Par conséquent, veillez à ne pas les supprimer accidentellement.

.Étape
. Pour afficher l'utilisation d'inode pour un volume, entrez la commande suivante :
+
[source, cli]
----
volume show -vserver <SVM_name> -volume <volume_name> -fields files
----


.Exemple
[listing]
----
cluster1::*> volume show -vserver vs1 -volume vol1 -fields files
Vserver Name: vs1
Files Used (for user-visible data): 98
----