---
permalink: volumes/enable-disable-background-deduplication-aff-task.html 
sidebar: sidebar 
keywords: manage, aggregate-level, background, deduplication, aff systems 
summary: 'La déduplication au niveau de l"agrégat élimine les blocs dupliqués sur les volumes appartenant au même agrégat. Depuis ONTAP 9.3, il est possible d"effectuer la déduplication au niveau de l"agrégat en arrière-plan sur les systèmes AFF. La fonctionnalité est activée par défaut sur tous les volumes nouvellement créés et sur tous les volumes mis à niveau lorsque la déduplication en arrière-plan des volumes est activée.' 
---
= Gérez la déduplication en arrière-plan au niveau de l'agrégat sur des systèmes AFF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La déduplication au niveau de l'agrégat élimine les blocs dupliqués sur les volumes appartenant au même agrégat. Depuis ONTAP 9.3, il est possible d'effectuer la déduplication au niveau de l'agrégat en arrière-plan sur les systèmes AFF. La fonctionnalité est activée par défaut sur tous les volumes nouvellement créés et sur tous les volumes mis à niveau lorsque la déduplication en arrière-plan des volumes est activée.

.Description de la tâche
L'opération est déclenchée automatiquement lorsqu'un pourcentage suffisamment important du journal des modifications a été rempli. Aucun programme ou règle n'est associé à l'opération.

Depuis ONTAP 9.4, les utilisateurs AFF peuvent également exécuter le processus de déduplication au niveau de l'agrégat pour éliminer les doublons des données existantes sur les volumes de l'agrégat. Vous pouvez utiliser le `storage aggregate efficiency cross-volume-dedupe start` commande avec `-scan-old-data=true` option de démarrage du scanner :

[listing]
----
cluster-1::> storage aggregate efficiency cross-volume-dedupe start -aggregate aggr1 -scan-old-data true
----
L'analyse de la déduplication peut s'avérer chronophage. Vous pouvez exécuter l'opération en dehors des heures de pointe.

[NOTE]
====
La déduplication en arrière-plan au niveau de l'agrégat est parfois appelée déduplication en arrière-plan inter-volumes.

====
.Étape
. Gérez la déduplication en arrière-plan au niveau de l'agrégat sur les systèmes AFF :
+
[cols="2*"]
|===
| Les fonctions que vous recherchez... | Utilisez cette commande 


 a| 
Activer la déduplication en arrière-plan au niveau de l'agrégat
 a| 
`volume efficiency modify -vserver <vserver_name\> -volume <vol_name\> -cross-volume-background-dedupe true`



 a| 
Désactiver la déduplication en arrière-plan au niveau de l'agrégat
 a| 
`volume efficiency modify -vserver <vserver_name\> -volume <vol_name\> -cross-volume-background-dedupe false`



 a| 
Afficher l'état de la déduplication en arrière-plan au niveau de l'agrégat
 a| 
`aggregate efficiency cross-volume-dedupe show`

|===

