---
permalink: volumes/enable-inline-data-compaction-fas-systems-task.html 
sidebar: sidebar 
keywords: enable, inline, data, compaction, fas systems 
summary: 'Vous pouvez contrôler la compaction des données à la volée sur les systèmes FAS avec des agrégats Flash Pool (hybrides) ou des agrégats HDD au niveau du volume ou de l"agrégat en utilisant la commande WAFL compactage enable node shell. Par défaut, la compaction est désactivée sur les systèmes FAS.' 
---
= Utilisez la compaction des données à la volée pour les systèmes FAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez contrôler la compaction des données à la volée sur les systèmes FAS avec des agrégats Flash Pool (hybrides) ou des agrégats HDD au niveau du volume ou de l'agrégat à l'aide de `volume efficiency` commande cluster shell. Par défaut, la compaction est désactivée sur les systèmes FAS.

.Description de la tâche
Si vous activez la compaction des données au niveau des agrégats, celle-ci est activée sur tout nouveau volume créé avec la garantie d'espace du volume de `none` dans l'agrégat. L'activation de la compaction des données sur un volume dans un agrégat HDD utilise des ressources CPU supplémentaires.

.Étapes
. Passez au niveau de privilège avancé : +
`set -privilege advanced`
. Vérifier l'état de compaction des données des volumes et des agrégats pour le nœud souhaité : +
`volume efficiency show -volume _volume_name_` +
. Activer la compaction des données sur le volume : +
`volume efficiency modify -volume _volume_name_ -data-compaction true`
+
[NOTE]
====
Si la compaction est définie sur `false` pour un agrégat ou un volume, celle-ci échoue. L'activation de la compaction ne compact pas les données existantes ; seules les nouvelles écritures dans le système sont compactées. La `volume efficiency start` commande contient plus d'informations sur la façon de compacter des données existantes (dans ONTAP 9.1 et versions ultérieures). + pour plus d'informations, voir https://docs.netapp.com/us-en/ontap-cli["Référence de commande ONTAP"^].

====
. Afficher les statistiques de compactage :
`volume efficiency show -volume _volume_name_`

