---
permalink: volumes/enable-temperature-sensitive-efficiency-concept.html 
sidebar: sidebar 
keywords: enable, temperature, sensitive, storage, efficiency, sequential packing 
summary: 'Introduit dans ONTAP 9.8, l"efficacité du stockage sensible à la température est automatiquement activée sur les volumes AFF à provisionnement fin nouvellement créés. Vous pouvez activer manuellement l"efficacité du stockage sensible à la température sur les volumes AFF existants et sur les volumes non-AFF DP à provisionnement fin.' 
---
= Présentation de l'efficacité du stockage sensible à la température
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour améliorer l'efficacité du stockage selon la température, ONTAP évalue la fréquence d'accès aux données de votre volume et mappe cette fréquence sur le degré de compression appliqué à ces données. Pour les données inactives peu utilisées, les blocs de données plus volumineux sont compressés et pour les données actives, qui sont fréquemment utilisées et remplacées plus souvent, les blocs de données plus petits sont compressés, ce qui améliore l'efficacité du processus.

L'efficacité du stockage sensible à la température est introduite dans ONTAP 9.8 et activée automatiquement sur les volumes AFF à provisionnement fin nouvellement créés. Vous pouvez activer l'efficacité du stockage sensible à la température sur les volumes AFF existants et sur les volumes non-AFF DP à provisionnement fin.

À partir de ONTAP 9.10.1, deux modes d'efficacité du stockage au niveau des volumes sont introduits uniquement pour les systèmes AFF, _default_ et _Efficient_. Les deux modes permettent de choisir entre la compression de fichiers (par défaut), qui est le mode par défaut lors de la création de nouveaux volumes AFF, ou l'efficacité du stockage sensible à la température (efficace), ce qui permet d'optimiser l'efficacité du stockage en fonction de la température. Avec ONTAP 9.10.1, l'efficacité du stockage sensible à la température doit être explicitement définie pour activer la compression adaptative automatique. Cependant, d'autres fonctionnalités d'efficacité du stockage telles que la compaction des données, la déduplication automatique, la déduplication à la volée, la déduplication à la volée entre volumes et la déduplication en arrière-plan entre volumes sont activées par défaut sur les plateformes AFF pour les modes par défaut et efficaces.

Les deux modes d'efficacité du stockage (par défaut et efficace) sont pris en charge sur les agrégats compatibles avec FabricPool et avec tous les types de règles de Tiering.

Depuis la version ONTAP 9.13.1, l'efficacité du stockage sensible à la température ajoute la compaction séquentielle des blocs physiques contigus afin d'améliorer encore l'efficacité du stockage. Sur les volumes dont l'efficacité du stockage sensible à la température est activée automatiquement, la compression séquentielle est activée lorsque vous mettez à niveau des systèmes vers ONTAP 9.13.1. Une fois l'emballage séquentiel activé, vous devez le faire link:https://docs.netapp.com/us-en/ontap/volumes/run-efficiency-operations-manual-task.html["reconditionnement manuel des données existantes"].



== Mise à niveau

Lors de la mise à niveau vers ONTAP 9.10.1 et versions ultérieures, un mode d'efficacité du stockage est attribué aux volumes existants, basé sur le type de compression actuellement activé sur les volumes. Au cours d'une mise à niveau, le mode par défaut est attribué aux volumes dont la compression est activée et le mode efficace est activé pour les volumes dont l'efficacité de stockage est sensible à la température. Si la compression n'est pas activée, le mode d'efficacité du stockage reste vide.
