---
permalink: volumes/enable-deduplication-volume-task.html 
sidebar: sidebar 
keywords: enable, deduplication, volume, FlexVol, postprocess, inline 
summary: 'Activez la déduplication (post-traitement ou à la volée) sur un FlexVol volume pour optimiser l"efficacité du stockage.' 
---
= Activer la déduplication sur un volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez activer la déduplication sur un volume FlexVol afin d'optimiser l'efficacité du stockage. Vous pouvez activer la déduplication post-traitement sur tous les volumes et la déduplication à la volée sur les volumes résidant dans des agrégats AFF ou Flash Pool.

Si vous souhaitez activer la déduplication en ligne sur d’autres types de volumes, consultez lelink:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_enable_volume_inline_deduplication_on_Non-AFF_(All_Flash_FAS)_aggregates["Base de connaissances NetApp : Comment activer la déduplication en ligne des volumes sur les agrégats non AFF (All Flash FAS)"^] .

.Avant de commencer
Pour un volume FlexVol, il faut avoir vérifié qu'il existe un espace libre suffisant pour les métadonnées de la déduplication dans les volumes et les agrégats. Les métadonnées de la déduplication requièrent un espace disponible minimal dans l'agrégat. Cette quantité correspond à 3 % de la quantité totale de données physiques pour l'ensemble des volumes FlexVol dédupliqués ou des composants de données au sein de l'agrégat. Chaque volume FlexVol ou composant de données doit présenter 4 % de l'espace libre total des données physiques, pour un total de 7 %.

[NOTE]
====
La déduplication en ligne est activée par défaut sur les systèmes AFF .

====
.Choix
* Utilisez `volume efficiency on` la commande pour activer la déduplication post-traitement. Pour en savoir plus, `volume efficiency on` consultez le link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-on.html["Référence de commande ONTAP"^].
+
La commande suivante active la déduplication post-traitement sur volume Vola :

+
`volume efficiency on -vserver vs1 -volume VolA`

* Utilisez la `volume efficiency on` commande suivie de la `volume efficiency modify` commande avec `-inline-deduplication` l'option définie sur `true` pour activer la déduplication post-traitement et la déduplication à la volée. Pour en savoir plus, `volume efficiency modify` consultez le link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-modify.html["Référence de commande ONTAP"^].
+
Les commandes suivantes permettent la déduplication post-traitement et la déduplication à la volée sur le volume Vola :

+
`volume efficiency on -vserver vs1 -volume VolA`

+
`volume efficiency modify -vserver vs1 -volume VolA -inline-dedupe true`

* Utilisez le `volume efficiency on` suivi de la commande `volume efficiency modify` commande avec `-inline-deduplication` option définie sur `true` et le `-policy` option définie sur `inline-only` pour activer uniquement la déduplication à la volée.
+
Les commandes suivantes permettent uniquement la déduplication à la volée sur le volume Vola :

+
`volume efficiency on -vserver vs1 -volume VolA`

+
`volume efficiency modify -vserver vs1 -volume VolA -policy inline-only -inline-dedupe true`



.Une fois que vous avez terminé
Vérifiez que le paramètre a été modifié en consultant les paramètres d'efficacité du volume :
`volume efficiency show -instance`

Pour en savoir plus, `volume efficiency show -instance` consultez le link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-show.html["Référence de commande ONTAP"^].
