---
permalink: volumes/enable-inline-data-compaction-fas-systems-task.html 
sidebar: sidebar 
keywords: enable, inline, data compaction, fas systems, hdd aggregate, volume efficiency 
summary: 'Compaction des données à la volée sur les systèmes FAS avec des agrégats Flash Pool (hybrides) ou des agrégats HDD au niveau du volume ou de l"agrégat.' 
---
= Utilisez la compaction des données à la volée pour les systèmes FAS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez activer la compaction des données à la volée sur les systèmes FAS dotés d'agrégats Flash Pool (hybrides) ou de disques durs au niveau du volume ou de l'agrégat à l'aide de `volume efficiency` la commande cluster shell. Par défaut, la compaction est désactivée sur les systèmes FAS.

.Description de la tâche
Si vous activez la compaction des données au niveau des agrégats, celle-ci est activée sur tout nouveau volume créé avec la garantie d'espace du volume de `none` dans l'agrégat. L'activation de la compaction des données sur un volume dans un agrégat HDD utilise des ressources CPU supplémentaires.

.Étapes
. Changement au niveau de privilège avancé :
+
[source, cli]
----
set -privilege advanced
----
. Vérifier l'état de compaction des volumes et des agrégats du nœud souhaité :
+
[source, cli]
----
volume efficiency show -volume <volume_name>
----
. Activer la compaction des données sur un volume :
+
[source, cli]
----
volume efficiency modify -volume <volume_name> -data-compaction true
----
+
[NOTE]
====
Si la compaction est définie sur `false` pour un agrégat ou un volume, celle-ci échoue. L'activation de la compaction ne compact pas les données existantes ; seules les nouvelles écritures dans le système sont compactées. La `volume efficiency start` commande contient plus d'informations sur la façon de compacter des données existantes (dans ONTAP 9.1 et versions ultérieures). Pour plus d'informations, voir https://docs.netapp.com/us-en/ontap-cli["Référence de commande ONTAP"^].

====
. Afficher les statistiques de compactage :
+
[source, cli]
----
volume efficiency show -volume <volume_name>
----

