---
permalink: volumes/enforced-quotas-differ-configured-concept.html 
sidebar: sidebar 
keywords: why, enforced, quotas, differ, configured, quotas 
summary: 'Les quotas appliqués diffèrent des quotas configurés car les quotas dérivés sont appliqués sans être configurés mais les quotas configurés ne sont appliqués qu"une fois qu"ils ont été initialisés. Comprendre ces différences peut vous aider à comparer les quotas appliqués qui sont affichés dans les rapports de quotas aux quotas que vous avez configurés.' 
---
= Pourquoi les quotas appliqués diffèrent des quotas configurés
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les quotas appliqués diffèrent des quotas configurés car les quotas dérivés sont appliqués sans être configurés mais les quotas configurés ne sont appliqués qu'une fois qu'ils ont été initialisés. Comprendre ces différences peut vous aider à comparer les quotas appliqués qui sont affichés dans les rapports de quotas aux quotas que vous avez configurés.

Les quotas appliqués, qui apparaissent dans les rapports de quotas, peuvent différer des règles de quotas configurées pour les raisons suivantes :

* Les quotas dérivés sont appliqués sans être configurés comme des règles de quotas ; ONTAP crée automatiquement des quotas dérivés en réponse aux quotas par défaut.
* Il se peut que les quotas n'aient pas été réinitialisés sur un volume après la configuration des règles de quotas.
* Des erreurs peuvent se produire lors de l'initialisation de quotas sur un volume.

