---
permalink: volumes/flexclone-efficient-copies-concept.html 
sidebar: sidebar 
keywords: use, flexclone, volumes, create, efficient, copies, flexvol volumes 
summary: 'Les volumes FlexClone sont des copies inscriptibles, compactes et instantanées d"une FlexVol volume parente, qui peuvent être gérées à des fins de protection des données ou autres.' 
---
= Présentation de l'utilisation des volumes FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les volumes FlexClone sont des copies inscriptibles à un point dans le temps d'un volume FlexVol parent. Les volumes FlexClone sont compacts car ils partagent les mêmes blocs de données avec leurs volumes FlexVol parents pour les données communes. Le snapshot utilisé pour créer un volume FlexClone est également partagé avec le volume parent.

Vous pouvez cloner un volume FlexClone existant pour créer un autre volume FlexClone. Vous pouvez également créer un clone d'un volume FlexVol contenant des LUN et des clones de LUN.

Vous pouvez également séparer un volume FlexClone de son volume parent. Depuis ONTAP 9.4, pour les volumes non garantis sur les systèmes AFF, l'opération de séparation pour les volumes FlexClone partage les blocs physiques et ne copie pas les données. La division des volumes FlexClone sur les systèmes AFF est donc plus rapide que le fractionnement de FlexClone sur d'autres systèmes FAS dans ONTAP 9.4 et versions ultérieures.

Vous pouvez créer deux types de volumes FlexClone : les volumes FlexClone en lecture/écriture et les volumes FlexClone de protection des données. Vous pouvez créer un volume FlexClone en lecture/écriture d'un volume FlexVol standard, mais vous devez utiliser uniquement un volume secondaire SnapVault pour créer un volume FlexClone de protection des données.
