---
permalink: volumes/flexvol-reclaim-free-space-autodelete-concept.html 
sidebar: sidebar 
keywords: how, flexvol, volume, reclaim, free, space, autodelete, setting 
summary: 'Le paramètre de suppression automatique d"une FlexVol volume permet de supprimer automatiquement les fichiers FlexClone et les LUN FlexClone et de libérer de l"espace dans le volume.' 
---
= Les volumes FlexVol et la récupération d'espace libre grâce à la présentation de la suppression automatique
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez activer la suppression automatique d'un volume FlexVol pour supprimer automatiquement les fichiers FlexClone et les LUN FlexClone. En activant la suppression automatique, vous pouvez récupérer une quantité cible d'espace libre dans le volume lorsqu'un volume est presque plein.

Vous pouvez configurer un volume pour qu'il commence automatiquement la suppression des fichiers FlexClone et des LUN FlexClone lorsque l'espace libre du volume diminue en dessous d'un seuil particulier, et que l'espace disponible cible est récupéré lorsqu'une quantité d'espace libre dans le volume est arrêté automatiquement. Bien que vous ne puissiez pas spécifier la valeur de seuil au début de la suppression automatique de clones, vous pouvez spécifier si un clone peut être supprimé et vous pouvez spécifier la quantité cible d'espace libre d'un volume.

Un volume supprime automatiquement les fichiers FlexClone et les LUN FlexClone lorsque l'espace libre dans le volume diminue en dessous d'un seuil particulier et lorsque les _deux_ des exigences suivantes sont remplies :

* La fonctionnalité de suppression automatique est activée pour le volume qui contient les fichiers FlexClone et les LUN FlexClone.
+
Vous pouvez activer la fonction de suppression automatique d'une FlexVol volume à l'aide de la `volume snapshot autodelete modify` commande. Vous devez définir `-trigger` le paramètre sur `volume` ou `snap_reserve` pour qu'un volume supprime automatiquement les fichiers FlexClone et les LUN FlexClone. Pour en savoir plus, `volume snapshot autodelete modify` consultez le link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-autodelete-modify.html["Référence de commande ONTAP"^].

* La fonctionnalité de suppression automatique est activée pour les fichiers FlexClone et les LUN FlexClone.
+
Vous pouvez activer la suppression automatique d'un fichier FlexClone ou d'une LUN FlexClone en utilisant la `file clone create` commande associée au `-autodelete` paramètre. Par conséquent, vous pouvez préserver certains fichiers FlexClone et certaines LUN FlexClone en désactivant la suppression automatique des clones et en vous assurant que les autres paramètres de volume ne prévalent pas sur le paramètre de clonage. Pour en savoir plus, `file clone create` consultez le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=file+clone+create["Référence de commande ONTAP"^].


