---
permalink: volumes/flexclone-volumes-files-luns-concept.html 
sidebar: sidebar 
keywords: how , flexclone, volumes, work, flexclone files, flexclone luns 
summary: 'Vous pouvez créer un volume FlexClone d"un volume FlexVol doté d"un fichier FlexClone et d"un LUN FlexClone et de son fichier parent ou d"une LUN.' 
---
= Volumes FlexClone, fichiers FlexClone et LUN FlexClone associés
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer un volume FlexClone d'un volume FlexVol doté d'un fichier FlexClone et d'un LUN FlexClone et de son fichier parent ou d'une LUN.

Les fichiers FlexClone ou les LUN FlexClone ainsi que les fichiers ou LUN parents présents dans le volume FlexClone continuent de partager les blocs de la même manière que dans le volume FlexVol parent. En fait, les entités FlexClone et leurs parents partagent les mêmes blocs de données physiques sous-jacents, ce qui minimise l'utilisation de l'espace disque physique.

Si le volume FlexClone est séparé de son volume parent, les fichiers FlexClone ou les LUN FlexClone et leurs fichiers parent ou LUN cessent de partager les blocs dans le clone du volume FlexClone. Elles existent ensuite en tant que fichiers ou LUN indépendants. Le clone du volume utilise donc plus d'espace qu'avant l'opération de fractionnement.
