---
permalink: volumes/logical-space-reporting-enforcement-concept.html 
sidebar: sidebar 
keywords: logical, space, reporting, enforcement, volumes 
summary: 'Depuis la version ONTAP 9.4, vous pouvez autoriser l"espace logique utilisé dans un volume et l"espace de stockage restant à afficher. À partir de la version 9.5, vous pouvez limiter la quantité d"espace logique consommée par les utilisateurs.' 
---
= Présentation des rapports sur l'espace logique et de leur application pour les volumes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis la version ONTAP 9.4, vous pouvez autoriser l'espace logique utilisé dans un volume et l'espace de stockage restant à afficher. À partir de la version 9.5, vous pouvez limiter la quantité d'espace logique consommée par les utilisateurs.

Les fonctions de reporting et d'application de l'espace logique sont désactivées par défaut.

Les types de volumes suivants prennent en charge la création de rapports sur l'espace logique et la mise en œuvre de ces

[cols="3*"]
|===
| Type de volume | Les rapports sur l'espace sont-ils pris en charge | Les applications de l'espace sont-elles prises en charge 


 a| 
Volumes FlexVol
 a| 
Oui, à partir de ONTAP 9.4
 a| 
Oui, à partir de ONTAP 9.5



 a| 
Volumes de destination SnapMirror
 a| 
Oui, à partir de ONTAP 9.8
 a| 
Non



 a| 
Volumes FlexGroup
 a| 
Oui, à partir de ONTAP 9.9.1
 a| 
Oui, à partir de ONTAP 9.9.1

|===