---
permalink: volumes/logical-space-reporting-concept.html 
sidebar: sidebar 
keywords: what, logical, space, reporting, shows 
summary: 'Lorsque vous activez les rapports d"espace logique sur un volume, votre système affiche l"espace logique utilisé et disponible en plus de l"espace total d"un volume.' 
---
= Génération de rapports sur l'espace logique
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous activez le reporting sur l'espace logique d'un volume, votre système peut afficher la quantité d'espace logique utilisé et disponible en plus de l'espace total d'un volume. En outre, les utilisateurs des systèmes clients Linux et Windows peuvent voir l'espace utilisé et disponible logique au lieu de l'espace physique utilisé et physique disponible.

Définitions :

* L'espace physique désigne les blocs physiques de stockage disponibles ou utilisés dans le volume.
* L'espace logique désigne l'espace utilisable d'un volume.
* L'espace logique utilisé est l'espace physique utilisé, plus les économies réalisées grâce aux fonctionnalités d'efficacité du stockage (telles que la déduplication et la compression) qui ont été configurées.


Depuis ONTAP 9.5, vous pouvez activer la mise en œuvre de l'espace logique et le reporting sur l'espace.

Lorsque cette option est activée, le rapport d'espace logique affiche les paramètres suivants avec le `volume show` commande :

[cols="25%,75%"]
|===
| Paramètre | Signification 


 a| 
`-logical-used`
 a| 
Affiche des informations uniquement sur le ou les volumes dont la taille logique utilisée est spécifiée. Cette valeur inclut l'espace économisé par les fonctionnalités d'efficacité du stockage et l'espace physique utilisé. Cela n'inclut pas la réserve Snapshot, mais prend en compte la fuite Snapshot.



 a| 
`-logical-used-by-afs`
 a| 
Affiche des informations uniquement sur le ou les volumes dont la taille logique spécifiée est utilisée par le système de fichiers actif. Cette valeur diffère de la``-logical-used`` valeur par la quantité de fuite d'instantanés qui dépasse la réserve d'instantanés.



 a| 
`-logical-available`
 a| 
Lorsque seul le rapport d'espace logique est activé, seul l'espace disponible est affiché. Lorsque le reporting sur l'espace et l'application sont tous deux activés, il affiche la quantité d'espace disponible actuellement en tenant compte de l'espace économisé par les fonctions d'efficacité du stockage comme étant utilisées. Cela n'inclut pas la réserve de snapshots.



 a| 
`-logical-used-percent`
 a| 
Affiche le pourcentage de la valeur actuelle `-logical-used` avec la taille provisionnée, à l'exclusion de la réserve de snapshots du volume.

Cette valeur peut être supérieure à 100 %, car elle `-logical-used-by-afs` inclut les économies d'efficacité du volume. La `-logical-used-by-afs` valeur d'un volume n'inclut pas la fuite de snapshots comme espace utilisé. La `-physical-used` valeur d'un volume inclut la fuite Snapshot en tant qu'espace utilisé.



 a| 
`-used`
 a| 
Affiche la quantité d'espace occupé par les données utilisateur et les métadonnées du système de fichiers. Elle diffère de l' `physical-used`espace par la somme de l'espace réservé aux écritures futures et de l'espace économisé par l'efficacité du stockage de l'agrégat. Cela inclut la fuite de snapshots (quantité d'espace au-delà de la réserve de snapshots). Elle n'inclut pas la réserve Snapshot.

|===
L'activation du reporting de l'espace logique dans l'interface de ligne de commandes permet également d'afficher les valeurs de l'espace logique utilisé (%) et de l'espace logique dans System Manager

Les systèmes clients voient l'espace logique affiché comme espace « utilisé » sur les écrans suivants du système :

* Sortie * df* sur les systèmes Linux
* Détails de l'espace sous Propriétés utilisation de l'Explorateur Windows sur les systèmes Windows.


[NOTE]
====
Si la génération de rapports sur l'espace logique est activée sans application de l'espace logique, le total affiché sur les systèmes clients peut être supérieur à l'espace provisionné.

====