---
permalink: volumes/manage-aggregate-level-deduplication-aff-task.html 
sidebar: sidebar 
keywords: manage, aggregate-level, inline, deduplication, aff systems 
summary: 'Gérer la fonctionnalité de déduplication au niveau de l"agrégat qui élimine les blocs dupliqués sur les volumes appartenant au même agrégat.' 
---
= Gérez la déduplication à la volée au niveau de l'agrégat sur les systèmes AFF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La déduplication au niveau de l'agrégat élimine les blocs dupliqués sur les volumes appartenant au même agrégat. Depuis ONTAP 9.2, il est possible d'effectuer une déduplication à la volée au niveau de l'agrégat sur les systèmes AFF. La fonctionnalité est activée par défaut sur tous les volumes nouvellement créés et sur tous les volumes mis à niveau alors que la déduplication à la volée des volumes est activée.

.Description de la tâche
Le processus de déduplication élimine les blocs dupliqués avant que les données ne soient écrites sur le disque. Uniquement les volumes avec le `space guarantee` réglez sur `none` peut participer à la déduplication à la volée au niveau des agrégats. Il s'agit du paramètre par défaut sur les systèmes AFF.

[NOTE]
====
La déduplication à la volée au niveau des agrégats est parfois appelée déduplication à la volée entre les volumes.

====
.Étape
. Gérez la déduplication à la volée au niveau de l'agrégat sur les systèmes AFF :
+
[cols="2*"]
|===
| Les fonctions que vous recherchez... | Utilisez cette commande 


 a| 
Activez la déduplication à la volée au niveau des agrégats
 a| 
`volume efficiency modify -vserver vserver_name -volume vol_name -cross-volume-inline-dedupe true`



 a| 
Désactiver la déduplication à la volée au niveau des agrégats
 a| 
`volume efficiency modify -vserver vserver_name -volume vol_name -cross-volume-inline-dedupe false`



 a| 
Afficher l'état de la déduplication à la volée au niveau de l'agrégat
 a| 
`volume efficiency config -volume vol_name`

|===


.Exemples
La commande suivante affiche l'état de la déduplication à la volée au niveau de l'agrégat :

[listing]
----

wfit-8020-03-04::> volume efficiency config -volume choke0_wfit_8020_03_0
Vserver:                                      vs0
Volume:                                       choke0_wfit_8020_03_0
Schedule:                                     -
Policy:                                       choke_VE_policy
Compression:                                  true
Inline Compression:                           true
Inline Dedupe:                                true
Data Compaction:                              true
Cross Volume Inline Deduplication:            false
----