---
permalink: volumes/migration-compression-type-coexistence.html 
sidebar: sidebar 
keywords: access control lists, flexclone files, flexclone luns, inheritance, ACL, ACLs, acl, acls, flexclone 
summary: 'Les fichiers FlexClone et les LUN FlexClone héritent des listes de contrôle d"accès de leurs fichiers et LUN parents.' 
---
= Prise en charge de la coexistence des types de compression lors de la migration de volumes ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lors de la migration d'un volume entre des systèmes ONTAP, le volume source peut utiliser un type de compression de données différent de celui du volume de destination.

Les types de compression pris en charge incluent la compression secondaire, la compression adaptative 8K et le stockage sensible à la température (TSSE). Lors de la migration, ces types de compression peuvent coexister temporairement sur le volume de destination comme suit :

[cols="4"]
|===
| Type de compression de la source | Type de compression de destination | Coexistence prise en charge pour la migration | Taille de lecture/écriture des E/S d'application 


| Secondaire | TSSE | Oui. | Automatique 


| Adaptatif 8K | TSSE | Oui. | Automatique 


| Secondaire | Adaptatif 8K | Non | Non pris en charge 
|===
.Migration de la compression secondaire et adaptative 8k vers la compression TSSE
Les volumes secondaires et adaptatifs 8k sont progressivement convertis en TSSE par des processus en arrière-plan après la migration ou à mesure que les données sont réécrites sur le volume de destination pendant la migration.

Après la migration d'un volume de la compression secondaire ou adaptative 8K vers la compression TSSE, le *type de compression* affiché dans la sortie de la commande `volume efficiency show` ne change pas, même après la conversion de tous les blocs existants. Le type de compression demeure *secondaire* pour un volume secondaire converti et *adaptatif* pour un volume adaptatif 8K converti.

Les nouvelles données écrites sur des volumes convertis depuis une compression secondaire ou adaptative 8K sont compressées avec TSSE.

.Migration de la compression secondaire vers la compression adaptative 8k
La coexistence directe de la compression secondaire et adaptative 8K sur le même volume n'est pas prise en charge.

Apprenez à link:move-between-secondary-adaptive-compression-task.html["basculer entre la compression secondaire et la compression adaptative"].
