---
permalink: volumes/modify-volume-efficiency-policy-task.html 
sidebar: sidebar 
keywords: modify, volume efficiency policy, volume, efficiency, policy 
summary: 'Vous pouvez modifier une règle d"efficacité des volumes pour exécuter la déduplication et la compression des données pendant une durée différente ou modifier la planification des tâches.' 
---
= Modifier une règle d'efficacité du volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier une règle d'efficacité des volumes pour exécuter la déduplication et la compression des données pendant une durée différente ou modifier la planification des tâches à l'aide de la `volume efficiency policy modify` commande. Pour en savoir plus, `volume efficiency policy modify` consultez le link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-policy-modify.html["Référence de commande ONTAP"^].

.Étapes
. Utilisez le `volume efficiency policy modify` commande permettant de modifier une règle d'efficacité du volume.


.Exemples
La commande suivante modifie la politique d'efficacité du volume politique1 afin qu'elle s'exécute toutes les heures :

`volume efficiency policy modify -vserver vs1 -policy policy1 -schedule hourly`

La commande suivante modifie une politique d'efficacité du volume nommée pol2 pour atteindre un seuil de 30 % :

`volume efficiency policy modify -vserver vs1 -policy pol1 -type threshold -start-threshold-percent 30%`
