---
permalink: volumes/qtrees-partition-your-volumes-concept.html 
sidebar: sidebar 
keywords: use, qtrees, partition, flexvol volumes 
summary: Les qtrees vous permettent de partitionner vos volumes FlexVol en segments de plus petite taille, que vous pouvez gérer individuellement. Vous pouvez utiliser des qtrees pour gérer les quotas, le style de sécurité et les oplocks CIFS. 
---
= Qtrees et partitionnement FlexVol volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les qtrees vous permettent de partitionner vos volumes FlexVol en segments de plus petite taille, que vous pouvez gérer individuellement. Vous pouvez utiliser des qtrees pour gérer les quotas, le style de sécurité et les oplocks CIFS.

ONTAP crée un qtree par défaut, appelé _qtree0_, pour chaque volume. Si vous ne placez pas les données dans un qtree, elles résident dans qtree0.

Les noms des qtree ne doivent pas comporter plus de 64 caractères.

Les répertoires ne peuvent pas être déplacés vers des qtrees. Seuls les fichiers peuvent être déplacés entre les qtrees.

Si vous créez des partages au niveau des qtrees et des partages au niveau des volumes sur le même pool FlexVol ou SCVMM, les qtrees apparaissent comme des répertoires sur le partage FlexVol. Par conséquent, veillez à ne pas les supprimer accidentellement.
