---
permalink: volumes/quota-targets-types-concept.html 
sidebar: sidebar 
keywords: quota, targets, types 
summary: 'Les quotas ont un type : ils peuvent être soit utilisateur, groupe, soit arborescence. Les cibles de quota spécifient l"utilisateur, le groupe ou le qtree pour lequel les limites du quota sont appliquées.' 
---
= Types et cibles de quotas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les quotas ont un type : ils peuvent être soit utilisateur, groupe, soit arborescence. Les cibles de quota spécifient l'utilisateur, le groupe ou le qtree pour lequel les limites du quota sont appliquées.

Le tableau suivant répertorie les types de cibles de quota, les types de quotas associés à chaque cible de quota et la façon dont chaque cible de quota est représentée :

[cols="15,15,35,35"]
|===


| Cible de quota | Type de quota | Mode de représentation de la cible | Remarques 


 a| 
utilisateur
 a| 
quota utilisateur
 a| 
Nom d'utilisateur UNIX UID UNIX

Fichier ou répertoire dont l'UID correspond à l'utilisateur

Nom d'utilisateur Windows au format pré-Windows 2000

SID Windows

Fichier ou répertoire avec un ACL détenu par le SID de l'utilisateur
 a| 
Les quotas utilisateur peuvent être appliqués pour un volume ou qtree spécifique.



 a| 
groupe
 a| 
quota de groupe
 a| 
Nom du groupe UNIX GID UNIX

Fichier ou répertoire dont le GID correspond au groupe
 a| 
Les quotas group peuvent être appliqués pour un volume ou qtree spécifique.


NOTE: La ONTAP ne s'applique pas aux quotas de groupe basés sur les ID Windows.



 a| 
qtree
 a| 
quota d'arbre
 a| 
nom du qtree
 a| 
Les quotas d'arborescence sont appliqués à un volume en particulier et n'affectent pas les qtrees des autres volumes.



 a| 
`""`
 a| 
quota roup utilisateur

quota d'arbre
 a| 
Guillemets doubles ("")
 a| 
Une cible de quota de "" désigne un quota _default_. Pour les quotas par défaut, le type de quota est déterminé par la valeur du champ type.

|===