---
permalink: volumes/quotas-activated-concept.html 
sidebar: sidebar 
keywords: quotas, how quotas are activated, quota activation 
summary: 'Les nouveaux quotas et les modifications des quotas existants doivent être activés pour prendre effet. L"activation est effectuée au niveau du volume. Connaître le fonctionnement de l"activation des quotas peut vous aider à gérer vos quotas avec moins d"interruptions.' 
---
= Présentation de l'activation des quotas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les nouveaux quotas et les modifications des quotas existants doivent être activés pour prendre effet. L'activation est effectuée au niveau du volume. Connaître le fonctionnement de l'activation des quotas peut vous aider à gérer vos quotas avec moins d'interruptions.

Les quotas sont activés soit par _initializing_ (les activer) soit par _resizing_. Désactiver les quotas et les rallumer est appelé réinitialisation.

La durée du processus d'activation et son impact sur l'application des quotas dépendent du type d'activation :

* Le processus d'initialisation comprend deux parties : un `quota on` et une analyse de quota de l'intégralité du système de fichiers du volume. L'acquisition commence après le `quota on` le travail s'est terminé avec succès. L'analyse de quota peut prendre un certain temps ; plus il y a de fichiers, plus il prend de temps. Tant que l'analyse n'est pas terminée, l'activation du quota n'est pas terminée et les quotas ne sont pas appliqués.
* Le processus de redimensionnement n'implique qu'un `quota resize` travail. Le redimensionnement prend moins de temps qu'une initialisation des quotas, car il n'implique pas d'analyse des quotas. Lors d'un processus de redimensionnement, les quotas continuent d'être appliqués.


Par défaut, le `quota on` et `quota resize` les travaux s'exécutent en arrière-plan, ce qui vous permet d'utiliser d'autres commandes en même temps.

Les erreurs et avertissements du processus d'activation sont envoyés au système de gestion des événements. Si vous utilisez le `-foreground` paramètre avec le `volume quota on` ou `volume quota resize` commandes, la commande ne retourne pas tant que le travail n'est pas terminé ; ceci est utile si vous êtes en cours de réinitialisation à partir d'un script. Pour afficher les erreurs et les avertissements ultérieurement, vous pouvez utiliser le `volume quota show` commande avec `-instance` paramètre.

L'activation du quota persiste entre les halts et les redémarrages. Le processus d'activation des quotas n'affecte pas la disponibilité des données du système de stockage.

.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-on.html["quota de volume sur"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-resize.html["redimensionnement des quotas de volume"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-show.html["quota de volume affiché"^]

