---
permalink: volumes/quotas-concept.html 
sidebar: sidebar 
keywords: why use quotas, quota benefits 
summary: 'Vous pouvez utiliser des quotas pour gérer et surveiller l"utilisation des ressources avec les volumes FlexVol.' 
---
= Avantages de l'utilisation des quotas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser des quotas pour gérer et surveiller l'utilisation des ressources avec les volumes FlexVol.

La définition des quotas présente plusieurs avantages. Vous pouvez utiliser les quotas par défaut, explicites, dérivés et de suivi pour gérer l'utilisation des disques de la manière la plus efficace possible.

.Limitez la consommation des ressources
Vous pouvez limiter la quantité d'espace disque ou le nombre de fichiers utilisés par un utilisateur ou un groupe ou contenus dans un qtree.

.Suivre l'utilisation des ressources
La quantité d'espace disque ou le nombre de fichiers utilisés par un utilisateur, un groupe ou qtree peut être suivie sans imposer de limite.

.Avertir les utilisateurs
Des notifications peuvent être générées lorsque l'utilisation des ressources atteint des niveaux spécifiques. Ceci avertit les utilisateurs lorsque leur utilisation de disque ou de fichier est trop élevée.
