---
permalink: volumes/quota-rules-policies-enforced-quotas-concept.html 
sidebar: sidebar 
keywords: understand quotas, quota rules, quota policies 
summary: 'Les quotas sont définis dans des règles de quotas spécifiques aux volumes FlexVol. Ces règles de quotas sont collectées ensemble dans une politique de quotas pour une machine virtuelle de stockage (SVM) et activées sur chaque volume de la SVM.' 
---
= Compréhension des quotas, des règles de quotas et des politiques de quotas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les quotas sont définis dans des règles de quotas spécifiques aux volumes FlexVol. Ces règles de quotas sont collectées ensemble dans une politique de quotas pour une machine virtuelle de stockage (SVM) et activées sur chaque volume de la SVM.

Une règle de quotas est toujours spécifique à un volume. Les règles de quota n'ont aucun effet tant que des quotas ne sont pas activés sur le volume défini dans la règle de quotas.

Une politique de quotas est un ensemble de règles de quotas pour tous les volumes d'une SVM. Les règles de quotas ne sont pas partagées entre les SVM. Un SVM peut disposer jusqu'à cinq politiques de quotas, ce qui vous permet d'avoir des copies de sauvegarde de politiques de quotas. Une politique de quotas est attribuée à un SVM à tout moment donné. Lorsque vous initialisez ou redimensionnez les quotas sur un volume, vous activez les règles des quotas dans la politique de quotas qui est actuellement attribuée à la SVM.

Un quota correspond à la restriction réelle que ONTAP applique ou au suivi réel effectué par ONTAP. Une règle de quotas entraîne toujours au moins un quota et peut entraîner de nombreux quotas dérivés supplémentaires. La liste complète des quotas appliqués n'est visible que dans les rapports de quotas.

L'activation consiste à déclencher une ONTAP afin de créer des quotas appliqués à partir de l'ensemble actuel de règles de quotas dans la politique de quotas attribuée. L'activation s'effectue volume par volume. La première activation des quotas sur un volume est appelée initialisation. Les activations suivantes sont appelées soit réinitialisation, soit redimensionnement, en fonction de la portée des modifications.
