---
permalink: volumes/quota-reports-policy-rule-show-command-concept.html 
sidebar: sidebar 
keywords: when to use, volume quota policy rule show, volume quota report, commands 
summary: 'Bien que les deux commandes affichent des informations sur les quotas, la règle de quota de volume affiche rapidement les règles de quotas configurées alors que la commande volume quota report, qui consomme plus de temps et de ressources, affiche les quotas appliqués et l"utilisation des ressources.' 
---
= Quand utiliser les commandes de la règle de quota de volume show et de rapport de quota de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les deux commandes affichent des informations sur les quotas, mais la `volume quota policy rule show` affiche rapidement les règles de quota configurées pendant que l' `volume quota report` commande, qui consomme plus de temps et de ressources, affiche les quotas appliqués et l'utilisation des ressources.

Le `volume quota policy rule show` la commande est utile aux fins suivantes :

* Vérifier la configuration des règles de quota avant de les activer
+
Cette commande affiche toutes les règles de quotas configurées si les quotas ont été initialisés ou redimensionnés.

* Affichez rapidement les règles de quotas sans affecter les ressources système
+
Comme elle n'affiche pas l'utilisation des disques et des fichiers, cette commande n'est pas aussi gourmande en ressources qu'un rapport de quota.

* Afficher les règles de quota dans une politique de quota qui n'est pas assignée à la SVM.


Le `volume quota report` la commande est utile aux fins suivantes :

* Afficher les quotas appliqués, y compris les quotas dérivés
* Affichez l'espace disque et le nombre de fichiers utilisés par chaque quota en vigueur, y compris les cibles affectées par les quotas dérivés
+
(Pour les quotas par défaut, l'utilisation apparaît comme « 0 » car l'utilisation est suivie par rapport au quota dérivé résultant.)

* Déterminez les limites de quota affectent lorsqu'une écriture dans un fichier est autorisée
+
Ajoutez le `-path` paramètre au `volume quota report` commande.



[NOTE]
====
Le rapport sur les quotas est une opération à forte intensité de ressources. Si vous l'exécutez sur plusieurs volumes FlexVol du cluster, ce délai peut être long. Une manière plus efficace serait d'afficher le rapport de quotas pour un volume particulier dans un SVM.

====