---
permalink: volumes/quotas-applied-root-user-concept.html 
sidebar: sidebar 
keywords: how, quotas are applied, root user 
summary: 'L"utilisateur root (UID=0) sur les clients UNIX est soumis à des quotas d"arborescence, mais pas à des quotas d"utilisateur ou de groupe. Cela permet à l"utilisateur root de prendre des actions pour le compte d"autres utilisateurs qui seraient autrement empêchés par un quota.' 
---
= Mode d'application des quotas à l'utilisateur racine
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'utilisateur root (UID=0) sur les clients UNIX est soumis à des quotas d'arborescence, mais pas à des quotas d'utilisateur ou de groupe. Cela permet à l'utilisateur root de prendre des actions pour le compte d'autres utilisateurs qui seraient autrement empêchés par un quota.

Lorsque root effectue un changement de propriété de fichier ou de répertoire ou une autre opération (comme UNIX) `chown` Commande) au nom d'un utilisateur avec moins de privilèges, ONTAP vérifie les quotas en fonction du nouveau propriétaire, mais ne signale pas d'erreurs ni n'arrête l'opération, même si les restrictions matérielles du nouveau propriétaire sont dépassées. Cela peut être utile lorsqu'une action administrative, telle que la récupération de données perdues, entraîne un dépassement temporaire des quotas.

[NOTE]
====
Une fois le transfert de propriété effectué, un système client signale une erreur d'espace disque si l'utilisateur tente d'allouer plus d'espace disque alors que le quota est encore dépassé.

====