---
permalink: volumes/quotas-flexclone-files-luns-concept.html 
sidebar: sidebar 
keywords: how, quotas work, with, flexclone files, flexclone luns 
summary: Des limites de quota sont appliquées à la taille logique totale des fichiers FlexClone ou des LUN FlexClone. Les opérations de clonage ne échouent pas le partage des blocs, même si cela entraîne le dépassement de quotas. 
---
= Fonctionnement des quotas avec les fichiers FlexClone et les LUN FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Des limites de quota sont appliquées à la taille logique totale des fichiers FlexClone ou des LUN FlexClone. Les opérations de clonage ne échouent pas le partage des blocs, même si cela entraîne le dépassement de quotas.

Lorsque vous créez un fichier FlexClone ou une LUN FlexClone, les quotas ne reconnaissent pas les économies d'espace. Par exemple, si vous créez un fichier FlexClone d'un fichier parent de 10 Go, vous n'utilisez que 10 Go d'espace physique, mais l'utilisation du quota est enregistrée à 20 Go (10 Go pour le fichier parent et 10 Go pour le fichier FlexClone).

Si la création d'un fichier FlexClone ou d'une LUN entraîne le dépassement du quota de groupe ou d'utilisateur, l'opération de clonage réussit à condition que le volume FlexVol dispose de suffisamment d'espace pour contenir les métadonnées du clone. Cependant, le quota pour cet utilisateur ou ce groupe est sursouscrit.
