---
permalink: volumes/quotas-applied-users-multiple-ids-concept.html 
sidebar: sidebar 
keywords: how, quotas are applied, users, multiple ids 
summary: 'Un utilisateur peut être représenté par plusieurs ID. Vous pouvez définir un quota utilisateur unique pour un tel utilisateur en spécifiant une liste d"ID comme cible de quota. Un fichier appartenant à l"un de ces ID est soumis à la restriction du quota d"utilisateur.' 
---
= Mode d'application des quotas aux utilisateurs avec plusieurs ID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un utilisateur peut être représenté par plusieurs ID. Vous pouvez définir un quota utilisateur unique pour un tel utilisateur en spécifiant une liste d'ID comme cible de quota. Un fichier appartenant à l'un de ces ID est soumis à la restriction du quota d'utilisateur.

Supposons qu'un utilisateur possède l'UID UNIX 20 et les ID Windows corp\john_smith et Engineering\jsmith. Pour cet utilisateur, vous pouvez spécifier un quota où la cible de quota est une liste des ID UID et Windows. Lorsque cet utilisateur écrit sur le système de stockage, le quota spécifié s'applique, que l'écriture soit issue de l'UID 20, corp\john_smith ou Engineering\jsmith.

[NOTE]
====
Des entrées de fichier de quota distinctes sont considérées comme des cibles distinctes, même si les ID appartiennent au même utilisateur. Par exemple, pour le même utilisateur, vous pouvez spécifier un quota qui limite l'UID 20 à 1 Go d'espace disque et un autre quota qui limite corp\john_smith à 2 Go d'espace disque, même si les deux ID représentent le même utilisateur. ONTAP applique des quotas à UID 20 et corp\john_smith séparément.

Dans ce cas, aucune limite n'est appliquée à Engineering\jsmith, même si des limites sont appliquées aux autres ID utilisés par le même utilisateur.

====