---
permalink: volumes/recommended-volume-lun-config-combinations-concept.html 
sidebar: sidebar 
keywords: recommended, volume, file, lun configuration, combinations 
summary: Découvrez les avantages et les coûts de combinaisons spécifiques de configurations FlexVol volume et de fichiers ou LUN. 
---
= Présentation des combinaisons de configurations de volume et de fichier ou LUN recommandées
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il existe des combinaisons spécifiques de configurations de volumes et fichiers FlexVol ou LUN qui peuvent être utilisées, en fonction des exigences de l'application et de l'administration. En comprenant les avantages et les coûts de ces combinaisons, vous pourrez déterminer la configuration la plus adaptée à votre environnement.

Les combinaisons de configuration de volume et de LUN suivantes sont recommandées :

* Fichiers ou LUN réservés en espace avec provisionnement d'un volume lourd
* Fichiers ou LUN non réservés en espace avec le provisionnement fin du volume
* Fichiers ou LUN réservés en espace avec provisionnement de volumes semi-lourds


Vous pouvez utiliser le provisionnement fin SCSI sur vos LUN en association avec l'une de ces combinaisons de configuration.



== Fichiers ou LUN réservés en espace avec provisionnement d'un volume lourd

*Avantages :*

* Toutes les opérations d'écriture dans les fichiers réservés à l'espace sont garanties ; elles ne échoueront pas en raison de l'espace insuffisant.
* Les technologies d'efficacité du stockage et de protection des données présentes sur le volume ne sont pas soumises à restrictions.


*Coûts et limitations:*

* L'espace doit être suffisant en dehors de l'agrégat pour prendre en charge le volume bénéficiant du provisionnement.
* Un espace égal à deux fois la taille de la LUN est alloué au volume au moment de sa création.




== Fichiers ou LUN non réservés en espace avec le provisionnement fin du volume

*Avantages :*

* Les technologies d'efficacité du stockage et de protection des données présentes sur le volume ne sont pas soumises à restrictions.
* L'espace est alloué uniquement lorsqu'il est utilisé.


*Coûts et restrictions:*

* Les opérations d'écriture ne sont pas garanties ; elles peuvent échouer si le volume vient à manquer d'espace.
* Vous devez gérer efficacement l'espace libre dans l'agrégat pour empêcher ce dernier de manquer d'espace.




== Fichiers ou LUN réservés en espace avec provisionnement de volumes semi-lourds

*Avantages :*

L'espace réservé est inférieur à celui du provisionnement d'un volume non lourd et la garantie d'écriture optimale est toujours fournie.

*Coûts et restrictions:*

* Cette option permet d'échouer les opérations d'écriture.
+
Vous pouvez réduire ce risque en équilibrant correctement l'espace libre du volume par rapport à la volatilité des données.

* Vous ne pouvez pas vous fier à la conservation des objets de protection des données tels que les snapshots, les fichiers FlexClone et les LUN.
* Vous ne pouvez pas utiliser les fonctionnalités ONTAP d'efficacité du stockage de partage de blocs qui ne peuvent pas être supprimées automatiquement, notamment la déduplication, la compression et ODX/déchargement des copies.

