---
permalink: volumes/rehost-snapmirror-relationship-task.html 
sidebar: sidebar 
keywords: rehost, volumes, snapmirror, relationship 
summary: 'Vous pouvez réhéberger un volume défini dans le cadre d"une relation SnapMirror. Il y a plusieurs problèmes que vous devez prendre en compte avant de réhéberger la relation.' 
---
= Réhébergez un volume dans une relation SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez réhéberger un volume défini dans le cadre d'une relation SnapMirror. Il y a plusieurs problèmes que vous devez prendre en compte avant de réhéberger la relation.

.Description de la tâche
* Le réhébergement représente aussi une opération disruptive.
* En cas d'échec de l'opération de réhébergement, vous devrez peut-être reconfigurer les stratégies de volume et les règles associées sur le volume source.
* Une fois le réhébergement, les règles, règles et configurations de volume suivantes perdues du volume source et doivent être reconfigurées manuellement sur le volume hébergé :
+
** Règles d'exportation de volumes et de qtrees
** Politiques antivirus
** Règle d'efficacité du volume
** Règles de qualité de services
** Règles relatives aux snapshots
** Règles de quotas
** règle et règles d'exportation de la configuration des services de noms et de commutateur ns
** ID d'utilisateur et de groupe




.Avant de commencer
* Le volume doit être en ligne.
* Les opérations de gestion de volumes, telles que les déplacements de volumes ou de LUN, ne doivent pas être en cours d'exécution.
* L'accès aux données au volume qui est réhébergé doit être arrêté.
* La configuration des services de nom et de commutateur ns-switch du SVM cible doit être configurée pour prendre en charge l'accès aux données du volume de réhébergement.
* L'ID utilisateur et l'ID groupe du volume doivent être disponibles dans le SVM cible ou modifiés sur le volume d'hébergement.


.Étapes
. Enregistrez le type de relation SnapMirror :
+
`snapmirror show`

+
Ceci est une étape de précaution qui permet d'éviter de perdre des informations sur le type de relation SnapMirror en cas de défaillance du nouvel hôte du volume.

. Depuis le cluster destination, supprimer la relation SnapMirror :
+
`snapmirror delete`

+
Ne rompez pas la relation SnapMirror ; dans le cas contraire, la capacité de protection des données du volume de destination est perdue et la relation ne peut pas être rétablie après l'opération de réhébergement.

. Depuis le cluster source, supprimer les informations relatives à la relation SnapMirror :
+
`snapmirror release -relationship-info-only true`

+
La définition du `-relationship-info-only` paramètre pour `true` supprimer les informations de relation source sans supprimer les snapshots.

. Si le volume est monté, démontez-le :
+
`volume unmount -vserver <source_svm> -volume <vol_name>`

. Basculer vers le niveau de privilège avancé :
+
`set -privilege advanced`

. Réhébergement « volume » sur le SVM de destination :
+
`volume rehost -vserver <source_svm> -volume <vol_name> -destination-vserver <destination_svm>`

. Si la relation de SVM peering n'est pas présente, créer la relation de pairs SVM entre la SVM source et la SVM destination :
+
`vserver peer create`

. Créer la relation SnapMirror entre le volume source et le volume de destination :
+
`snapmirror create`

+
Vous devez exécuter le `snapmirror create` Commande du SVM qui héberge le volume DP Le volume réhébergé peut être la source ou la destination de la relation SnapMirror.

. Resynchroniser la relation SnapMirror.


.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["montrer snapmirror"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["suppression de snapmirror"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-release.html["version de snapmirror"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-unmount.html["démontage de volume"^]
* link:https://docs.netapp.com/us-en/ontap-cli/set.html["jeu"^]
* link:https://docs.netapp.com/us-en/ontap-cli/volume-rehost.html["réhébergement de volumes"^]
* link:https://docs.netapp.com/us-en/ontap-cli/vserver-peer-create.html["vserver peer create"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["création snapmirror"^]

