---
permalink: volumes/resume-efficiency-operation-checkpoint-task.html 
sidebar: sidebar 
keywords: resume, halted, efficiency, operation 
summary: 'Si une opération d"efficacité est interrompue en raison de l"arrêt d"un système, d"une interruption du système ou d"un redémarrage, vous pouvez reprendre l"opération d"efficacité à partir du même point en utilisant la commande Volume Efficiency start avec l"option de point de contrôle. Cela permet de gagner du temps et de faire des économies en n"ayant pas besoin de redémarrer l"opération d"efficacité dès le départ.' 
---
= Reprendre une opération d'efficacité interrompue
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si une opération d'efficacité est interrompue à cause de l'arrêt du système, d'une interruption du système ou d'un redémarrage, vous pouvez reprendre l'opération d'efficacité à partir du même point en utilisant le `volume efficiency start` commande avec l'option de point de contrôle. Cela permet de gagner du temps et de faire des économies en n'ayant pas besoin de redémarrer l'opération d'efficacité dès le départ.

Si vous avez activé uniquement la déduplication sur le volume, la déduplication s'exécute sur les données. Si vous avez activé la déduplication et la compression des données sur un volume, la compression des données s'exécute en premier, suivie de la déduplication.

Vous pouvez afficher les détails du point de contrôle d'un volume en utilisant le `volume efficiency show` commande.

Par défaut, les opérations d'efficacité reprennent à partir des points de contrôle. Cependant, si un point de contrôle correspondant à une opération d'efficacité précédente (la phase lorsque le `volume efficiency start``la commande -scan-old-data` est exécutée) est antérieure à 24 heures, alors l'opération d'efficacité ne reprend pas automatiquement à partir du point de contrôle précédent. Dans ce cas, l'opération d'efficacité commence dès le début. Toutefois, si vous savez que des changements significatifs n'ont pas eu lieu dans le volume depuis la dernière acquisition, vous pouvez forcer la poursuite à partir du point de contrôle précédent en utilisant le `-use-checkpoint` option.

.Étape
. Utilisez le `volume efficiency start` commande avec `-use-checkpoint` option pour reprendre une opération d'efficacité.
+
La commande suivante vous permet de reprendre une opération d'efficacité sur les nouvelles données du volume Vola :

+
`volume efficiency start -vserver vs1 -volume VolA -use-checkpoint true`

+
La commande suivante vous permet de reprendre une opération d'efficacité sur les données existantes sur le volume Vola :

+
`volume efficiency start -vserver vs1 -volume VolA -scan-old-data true -use-checkpoint true`


