---
permalink: volumes/run-efficiency-operations-scheduling-task.html 
sidebar: sidebar 
keywords: run, modify, scheduling, efficiency, operations, deduplication, data, compression 
summary: Modifier la planification des opérations de déduplication ou de compression des données sur un volume 
---
= Exécuter une opération d'efficacité à l'aide de la planification
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier la planification des opérations de déduplication ou de compression des données sur un volume. Les options de configuration d'une planification et de la règle d'efficacité des volumes s'excluent mutuellement.

.Description de la tâche
Cette opération s'effectue à l'aide de la `volume efficiency modify` commande.

.Étapes
. Utilisez le `volume efficiency modify` commande permettant de modifier la planification des opérations de déduplication ou de compression des données sur un volume.


.Exemples
La commande suivante modifie la planification des opérations d'efficacité pour Vola à 11 h, du lundi au vendredi :

`volume efficiency modify -vserver vs1 -volume VolA -schedule mon-fri@23`

.Informations associées
* link:run-efficiency-operations-depending-new-data-task.html["Exécutez les opérations d'efficacité en fonction du volume de nouvelles données écrites"]

