---
permalink: volumes/snapshot-copies-flexclone-files-luns-concept.html 
sidebar: sidebar 
keywords: how, snapshot copies, work, flexclone files, flexclone luns 
summary: Comprendre la synergie entre les snapshots et les fichiers FlexClone et les LUN FlexClone, ainsi que certaines restrictions. 
---
= Fonctionnement des snapshots avec FlexClone Files et les LUN FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il existe une synergie entre les snapshots et les fichiers FlexClone et les LUN FlexClone. Si vous travaillez avec ces technologies, vous devez être conscient de ce qui est possible ainsi que des restrictions pertinentes.

.Création de fichiers FlexClone et de LUN
Vous pouvez créer un fichier FlexClone ou une LUN FlexClone à partir d'un snapshot existant. La copie repose sur les fichiers parents et les LUN parents contenus dans une FlexVol volume.

.Suppression d'un snapshot
Vous ne pouvez pas supprimer manuellement un snapshot depuis lequel des fichiers FlexClone ou des LUN FlexClone sont en cours de création. Le snapshot reste verrouillé jusqu'à ce que le processus de partage des blocs en arrière-plan soit terminé. Si vous essayez de supprimer un instantané verrouillé, le système affiche un message vous demandant de réessayer l'opération après un certain temps. Dans ce cas, vous devez continuer à essayer de nouveau l'opération de suppression. Vous pourrez supprimer l'instantané une fois le partage de bloc terminé.
