---
permalink: volumes/space-reservation-flexclone-files-luns-concept.html 
sidebar: sidebar 
keywords: how, space reservation, works, flexclone files, flexclone luns 
summary: 'Lorsque vous utilisez des fichiers FlexClone et des LUN FlexClone, vous devez comprendre le fonctionnement de l"attribut de réservation d"espace.' 
---
= Fonctionnement de la réservation d'espace avec les fichiers FlexClone et les LUN FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous utilisez des fichiers FlexClone et des LUN FlexClone, vous devez comprendre le fonctionnement de l'attribut de réservation d'espace.

Par défaut, les fichiers FlexClone et les LUN héritent respectivement de l'attribut de réservation d'espace du fichier parent et de la LUN parent. Toutefois, vous pouvez créer des fichiers FlexClone et des LUN FlexClone avec la réservation d'espace désactivée si la FlexVol volume manque d'espace. Ceci est possible même si l'attribut dans le parent respectif est activé.

Notez que si la FlexVol volume ne contient pas assez d'espace pour créer un fichier FlexClone ou une LUN FlexClone avec la même réservation d'espace que celle du parent, l'opération de clonage échoue.
