---
permalink: volumes/space-display-quota-report-unix-client-concept.html 
sidebar: sidebar 
keywords: difference, space usage, displayed, quota report, unix client 
summary: 'La valeur de l"espace disque utilisé affichée dans un rapport de quota pour un FlexVol volume ou qtree peut être différente de la valeur affichée par un client UNIX pour le même volume ou qtree.' 
---
= Différence d'utilisation de l'espace affichée par les rapports de quotas ONTAP et les clients UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La valeur de l'espace disque utilisé affichée dans un rapport de quota pour un FlexVol volume ou qtree peut être différente de la valeur affichée par un client UNIX pour le même volume ou qtree. La différence dans ces valeurs est due aux différentes méthodes suivies par le rapport de quota et les commandes UNIX pour le calcul des blocs de données dans le volume ou qtree.

Par exemple, si un volume contient un fichier présentant des blocs de données vides (vers lesquels les données ne sont pas écrites), le rapport quota du volume ne compte pas les blocs de données vides lors de l'utilisation de l'espace. Cependant, lorsque le volume est monté sur un client UNIX et que le fichier est affiché comme sortie du `ls` commande, les blocs de données vides sont également inclus dans l'utilisation d'espace. Par conséquent, le `ls` la commande affiche une taille de fichier supérieure par rapport à l'utilisation de l'espace affichée par le rapport aux quotas.

De même, les valeurs d'utilisation de l'espace affichées dans un rapport de quota peuvent également différer des valeurs indiquées à la suite de commandes UNIX telles que `df` et `du`.



== Comment un rapport de quota tient compte de l'espace disque et de l'utilisation des fichiers

Le nombre de fichiers utilisés et la quantité d'espace disque spécifié dans un rapport de quotas pour un volume FlexVol ou un qtree dépendent du nombre de blocs de données utilisés correspondant à chaque inode du volume ou du qtree.

Le nombre de blocs inclut à la fois les blocs directs et indirects utilisés pour les fichiers normaux et les fichiers de flux. Les blocs utilisés pour les répertoires, les listes de contrôle d'accès (ACL), les répertoires de flux et les métafichiers ne sont pas pris en compte dans le rapport sur les quotas. Dans le cas de fichiers parse UNIX, des blocs de données vides ne sont pas inclus dans le rapport des quotas.

Le sous-système de quotas est conçu pour prendre en compte et inclure uniquement les aspects contrôlables par l'utilisateur du système de fichiers. Les répertoires, les listes de contrôle d'accès et l'espace des snapshots sont autant d'exemples d'espace exclu des calculs de quotas. Les quotas sont utilisés pour appliquer des limites et non des garanties, et ils fonctionnent uniquement sur le système de fichiers actif. La comptabilité des quotas ne compte pas certaines constructions du système de fichiers ni seulement pour l'efficacité du stockage (comme la compression et la déduplication).

Pour en savoir plus sur les commandes décrites dans cette procédurelink:https://docs.netapp.com/us-en/ontap-cli/["Référence de commande ONTAP"^], reportez-vous à la .



== Disparité entre la commande ls et le rapport de quota pour l'utilisation de l'espace

Lorsque vous utilisez `ls` la commande pour afficher le contenu d'un FlexVol volume monté sur un client UNIX, les tailles de fichier affichées dans le résultat peuvent différer de l'utilisation de l'espace affichée dans le rapport de quota pour le volume en fonction du type de blocs de données pour le fichier.

La sortie du `ls` commande affiche uniquement la taille d'un fichier et n'inclut pas les blocs indirects utilisés par le fichier. Tous les blocs vides du fichier sont également inclus dans la sortie de la commande.

Par conséquent, si un fichier ne contient pas de blocs vides, la taille affichée par le `ls` la commande peut être inférieure à l'utilisation du disque spécifiée par un rapport de quota en raison de l'inclusion de blocs indirects dans le rapport de quota. Inversement, si le fichier contient des blocs vides, alors la taille affichée par le `ls` la commande peut être supérieure à l'utilisation du disque spécifiée par le rapport de quota.

La sortie du `ls` commande affiche uniquement la taille d'un fichier et n'inclut pas les blocs indirects utilisés par le fichier. Tous les blocs vides du fichier sont également inclus dans la sortie de la commande.

.Exemple de différence entre l'utilisation de l'espace comptabilisée par la commande ls et un rapport de quota
[%collapsible]
====
Le rapport de quotas suivant montre la limite de 10 Mo pour un q1 qtree :

[listing]
----

                                      ----Disk----  ----Files-----   Quota
  Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
  -------  --------  ------  -------  -----  -----  ------  ------   ---------
  vol1     q1          tree    user1   10MB  10MB        1       -   q1

...
----
Un fichier présent dans le même qtree peut avoir une taille supérieure à la limite de quota lorsqu'il est visualisé à partir d'un client UNIX en utilisant le `ls` comme indiqué dans l'exemple suivant :

[listing]
----
[user1@lin-sys1 q1]$ ls -lh
-rwxr-xr-x  1 user1 nfsuser  **27M** Apr 09  2013 file1
----
====
Pour en savoir plus, `ls` consultez le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=ls["Référence de commande ONTAP"^].



== Découvrez comment la commande df prend en compte la taille des fichiers

La manière dont dans le `df` la commande signale l'utilisation de l'espace dépend de deux conditions : que les quotas soient activés ou désactivés pour le volume qui contient le qtree, et que l'utilisation des quotas au sein du qtree est suivie.

Lorsque les quotas sont activés pour le volume contenant l'utilisation du qtree et du quota au sein du qtree est suivie, l'utilisation de l'espace est signalée par le `df` commande égale la valeur spécifiée par le rapport de quota. Dans ce cas, l'utilisation des quotas exclut les blocs utilisés par les répertoires, les ACL, les répertoires de flux et les métafichiers.

Lorsque les quotas ne sont pas activés sur le volume, ou si le qtree n'a pas configuré de règle de quotas, l'utilisation de l'espace signalé inclut les blocs utilisés par les répertoires, les listes de contrôle d'accès, les répertoires de flux et les métafichiers pour tout le volume, y compris les autres qtrees du volume. Dans ce cas, l'utilisation de l'espace signalée par le `df` la commande est supérieure à la valeur attendue signalée lors du suivi des quotas.

Lorsque vous exécutez le `df` commande provenant du point de montage d'un qtree pour lequel l'utilisation du quota est suivie, la sortie de la commande affiche la même utilisation de l'espace que la valeur spécifiée par le rapport quota. Dans la plupart des cas, lorsque la règle de quota d'arborescence a une limite de disque dur, la taille totale signalée par le `df` commande égale la limite du disque et l'espace disponible équivaut à la différence entre la limite du disque de quota et l'utilisation des quotas.

Toutefois, dans certains cas, l'espace disponible indiqué par le `df` la commande peut correspondre à l'espace disponible dans le volume dans son ensemble. Cela peut se produire lorsqu'aucune limite de disque dur n'est configurée pour le qtree. Depuis la version ONTAP 9.9.1, il peut également se produire lorsque l'espace disponible dans le volume dans son ensemble est inférieur à l'espace de quota Tree restant. Lorsque l'une ou l'autre de ces conditions se produit, la taille totale signalée par le `df` Commande est un nombre synthétisé égal au quota utilisé dans le qtree plus l'espace disponible dans le volume FlexVol.

[NOTE]
====
Cette taille totale n'est ni la limite des disques qtree, ni la taille du volume configurée. Ils peuvent également varier en fonction de l'activité d'écriture dans d'autres qtrees ou de l'activité d'efficacité du stockage en arrière-plan.

====
.Exemple d'utilisation de l'espace comptabilisée par la <code>df</code> commande et un rapport de quota
[%collapsible]
====
Le rapport de quota suivant indique une limite de disque de 1 Go pour qtree alice, 2 Go pour qtree bob, et aucune limite pour le projet qtree project1 :

[listing]
----
C1_vsim1::> quota report -vserver vs0
Vserver: vs0
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol2     alice     tree    1
                                  502.0MB    1GB       2       -   alice
vol2     bob       tree    2
                                   1003MB    2GB       2       -   bob
vol2     project1  tree    3
                                  200.8MB      -       2       -   project1
vol2               tree    *           0B      -       0       -   *
4 entries were displayed.
----
Dans l'exemple suivant, la sortie du `df` Commande sur les qtrees alice et bob indiquent le même espace utilisé que le rapport de quota, et la même taille totale (en termes de blocs de 1 million) que la limite du disque. En effet, les règles de quota pour les qtrees alice et bob ont une limite de disque définie et l'espace disponible du volume (1211 Mo) est supérieur à l'espace de quota Tree restant pour qtree alice (523 Mo) et qtree bob (1045 Mo).

[listing]
----
linux-client1 [~]$ df -m /mnt/vol2/alice
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      1024   502       523  50% /mnt/vol2

linux-client1 [~]$ df -m /mnt/vol2/bob
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      2048  1004      1045  50% /mnt/vol2
----
Dans l'exemple suivant, la sortie du `df` La commande sur qtree project1 indique le même espace utilisé que le rapport de quota, mais la taille totale est synthétisée en ajoutant l'espace disponible dans le volume dans son ensemble (1211 Mo) à l'utilisation du quota de qtree project1 (201 Mo) pour donner un total de 1412 Mo. En effet, la règle de quota pour qtree project1 n'a aucune limite de disque.

[listing]
----
linux-client1 [~]$ df -m /mnt/vol2/project1
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      1412   201      1211  15% /mnt/vol2
----
L'exemple suivant montre comment la sortie de l' `df` la commande sur le volume dans son ensemble indique le même espace disponible que le project1.

[listing]
----
linux-client1 [~]$ df -m /mnt/vol2
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      2919  1709      1211  59% /mnt/vol2
----
====
Pour en savoir plus sur les commandes décrites dans cette procédurelink:https://docs.netapp.com/us-en/ontap-cli/["Référence de commande ONTAP"^], reportez-vous à la .



== Disparité entre la commande du et le rapport de quota pour l'utilisation de l'espace

Lorsque vous exécutez le `du` Commande pour vérifier l'utilisation de l'espace disque pour un volume qtree ou FlexVol monté sur un client UNIX, la valeur d'utilisation peut être supérieure à la valeur affichée par un rapport de quotas pour le qtree ou le volume.

La sortie du `du` la commande contient l'utilisation combinée de l'espace de tous les fichiers par l'intermédiaire de l'arborescence de répertoires commençant au niveau du répertoire où la commande est émise. Car la valeur d'utilisation affichée par le `du` la commande inclut également les blocs de données pour les répertoires, elle est supérieure à la valeur affichée par un rapport de quota.

.Exemple de la différence entre l'utilisation de l'espace comptabilisée par la commande du et un rapport de quota
[%collapsible]
====
Le rapport de quotas suivant montre la limite de 10 Mo pour un q1 qtree :

[listing]
----

                                      ----Disk----  ----Files-----   Quota
  Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
  -------  --------  ------  -------  -----  -----  ------  ------   ---------
  vol1     q1        tree    user1    10MB   10MB   1       -        q1

...
----
Dans l'exemple suivant, l'espace disque utilisé comme sortie du `du` la commande affiche une valeur plus élevée qui dépasse la limite du quota :

[listing]
----
[user1@lin-sys1 q1]$ du -sh
**11M**     q1
----
====
Pour en savoir plus sur les commandes décrites dans cette procédurelink:https://docs.netapp.com/us-en/ontap-cli/["Référence de commande ONTAP"^], reportez-vous à la .
