---
permalink: volumes/space-display-quota-report-unix-client-concept.html 
sidebar: sidebar 
keywords: difference, space usage, displayed, quota report, unix client 
summary: 'La valeur de l"espace disque utilisé affiché dans un rapport de quotas pour un volume FlexVol ou qtree peut être différente de la valeur affichée par un client UNIX pour le même volume ou qtree. La différence dans les valeurs d"utilisation est due à la différence des méthodes suivies par le rapport de quota et aux commandes UNIX pour le calcul des blocs de données dans le volume ou le qtree.' 
---
= Différence d'utilisation de l'espace affichée par un rapport de quota et une vue d'ensemble du client UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La valeur de l'espace disque utilisé affiché dans un rapport de quotas pour un volume FlexVol ou qtree peut être différente de la valeur affichée par un client UNIX pour le même volume ou qtree. La différence dans les valeurs d'utilisation est due à la différence des méthodes suivies par le rapport de quota et aux commandes UNIX pour le calcul des blocs de données dans le volume ou le qtree.

Par exemple, si un volume contient un fichier présentant des blocs de données vides (vers lesquels les données ne sont pas écrites), le rapport quota du volume ne compte pas les blocs de données vides lors de l'utilisation de l'espace. Cependant, lorsque le volume est monté sur un client UNIX et que le fichier est affiché comme sortie du `ls` commande, les blocs de données vides sont également inclus dans l'utilisation d'espace. Par conséquent, le `ls` la commande affiche une taille de fichier supérieure par rapport à l'utilisation de l'espace affichée par le rapport aux quotas.

De même, les valeurs d'utilisation de l'espace affichées dans un rapport de quota peuvent également différer des valeurs indiquées à la suite de commandes UNIX telles que `df` et `du`.
