---
permalink: volumes/space-reserved-luns-semi-thick-provisioning-concept.html 
sidebar: sidebar 
keywords: configuration, settings, space-reserved files, luns, semi-thick volume provisioning 
summary: 'La configuration FlexVol volume et fichier ou LUN basée sur le provisionnement de volumes semi-épais requiert moins d"espace de stockage alloué au préalable, mais elle est soumise à des restrictions.' 
---
= Paramètres de configuration pour les fichiers réservés en espace ou les LUN avec provisionnement de volumes semi-lourds
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser plusieurs combinaisons de configuration de FlexVol volume et de configurations de fichiers ou de LUN. Cette combinaison basée sur un provisionnement de volumes semi-épais requiert moins de stockage à allouer en amont que la combinaison entièrement provisionnée. Mais cela impose des restrictions sur les technologies d'efficacité que vous pouvez utiliser pour le volume. Les écrasements sont effectués par le meilleur effort pour cette combinaison de configuration.

Les paramètres suivants sont nécessaires pour configurer une LUN Space-Reserved dans un volume à l'aide du provisionnement semi-thick :

[cols="2*"]
|===
| Réglage du volume | Valeur 


 a| 
Résultats garantis
 a| 
Volumétrie



 a| 
Réserve fractionnaire
 a| 
0



 a| 
Réserve Snapshot
 a| 
0



 a| 
Suppression automatique de l'instantané
 a| 
On, avec un niveau d'engagement de destruction, une liste de destruction qui inclut tous les objets, le déclencheur défini sur volume, ainsi que toutes les LUN FlexClone et tous les fichiers FlexClone activés pour la suppression automatique.



 a| 
Croissance automatique
 a| 
Facultatif. Si cette option est activée, l'espace libre de l'agrégat doit être activement surveillé.

|===
[cols="2*"]
|===
| Paramètre fichier ou LUN | Valeur 


 a| 
Réservation d'espace
 a| 
Activé

|===


== Restrictions technologiques

Pour cette combinaison de configuration, vous ne pouvez pas utiliser les technologies suivantes d'efficacité du stockage de volumes :

* Compression
* Déduplication
* ODX et allègement de la charge des copies FlexClone
* LUN FlexClone et fichiers FlexClone non marqués pour la suppression automatique (clones actifs)
* Sous-fichiers FlexClone
* ODX/allègement de la charge des copies




== Autres considérations

Lors de l'utilisation de cette combinaison de configuration, vous devez tenir compte des éléments suivants :

* Lorsque l'espace d'espace du volume qui prend en charge cette LUN est faible, les données de protection (LUN et fichiers FlexClone, snapshots) sont détruites.
* Les opérations d'écriture peuvent entraîner un temps d'attente et l'échec lorsque l'espace disponible est insuffisant.


Par défaut, la compression est activée pour les plateformes AFF. Vous devez désactiver explicitement la compression pour tout volume pour lequel vous souhaitez utiliser un provisionnement semi-lourd sur une plateforme AFF.

.Informations associées
* link:recommended-volume-lun-config-combinations-concept.html["Présentation des combinaisons de configuration de volumes et fichiers ou LUN recommandées"]

