---
permalink: volumes/space-reserved-luns-thick-provisioned-concept.html 
sidebar: sidebar 
keywords: configuration, settings, space-reserved, files, luns with thick-provisioned volumes 
summary: 'La configuration basée sur des volumes à provisionnement lourd assure l"efficacité du stockage et ne vous oblige pas à surveiller activement l"espace libre.' 
---
= Paramètres de configuration pour les fichiers réservés en espace ou les LUN avec des volumes à provisionnement lourd
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser plusieurs combinaisons de configuration de FlexVol volume et de configurations de fichiers ou de LUN. Cette combinaison basée sur des volumes à provisionnement lourd permet d'utiliser des technologies d'efficacité du stockage et ne nécessite pas de surveiller activement l'espace disponible car un espace suffisant est alloué au préalable.

Les paramètres suivants sont nécessaires pour configurer un fichier ou une LUN réservé à l'espace dans un volume à l'aide du provisionnement Thick :

[cols="2*"]
|===
| Réglage du volume | Valeur 


 a| 
Résultats garantis
 a| 
Volumétrie



 a| 
Réserve fractionnaire
 a| 
100



 a| 
Réserve Snapshot
 a| 
Toutes



 a| 
Suppression automatique de l'instantané
 a| 
Facultatif



 a| 
Croissance automatique
 a| 
Facultatif. Si cette option est activée, l'espace libre de l'agrégat doit être activement surveillé.

|===
[cols="2*"]
|===
| Paramètre fichier ou LUN | Valeur 


 a| 
Réservation d'espace
 a| 
Activé

|===
.Informations associées
* link:recommended-volume-lun-config-combinations-concept.html["Présentation des combinaisons de configuration de volumes et fichiers ou LUN recommandées"]

