---
permalink: volumes/specify-windows-users-quotas-concept.html 
sidebar: sidebar 
keywords: how to, specify, windows users, for quotas 
summary: 'Vous pouvez spécifier un utilisateur Windows pour un quota en utilisant l"un des trois formats suivants : le nom Windows au format pré-Windows 2000, le SID, ou un fichier ou répertoire appartenant au SID de l"utilisateur.' 
---
= Comment spécifier des utilisateurs Windows pour des quotas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez spécifier un utilisateur Windows pour un quota en utilisant l'un des trois formats suivants : le nom Windows au format pré-Windows 2000, le SID, ou un fichier ou répertoire appartenant au SID de l'utilisateur.

Pour spécifier un utilisateur Windows pour un quota, vous pouvez utiliser l'un des formats suivants :

* Le nom Windows au format pré-Windows 2000.
* L'ID de sécurité (SID), tel qu'affiché par Windows sous forme de texte, tel que S-1-5-32-544.
* Nom d'un fichier ou d'un répertoire qui possède un ACL appartenant au SID de cet utilisateur.
+
[NOTE]
====
Si vous spécifiez un nom de fichier ou de répertoire, vous devez sélectionner un fichier ou un répertoire qui durera tant que le compte utilisateur reste sur le système.

Pour que ONTAP puisse obtenir le SID à partir de la liste de contrôle d’accès, la liste de contrôle d’accès doit être valide.

Si le fichier ou le répertoire existe dans un qtree de style UNIX, ou si le système de stockage utilise le mode UNIX pour l'authentification utilisateur, ONTAP applique le quota utilisateur à l'utilisateur dont *UID*, et non SID, correspond à celui du fichier ou du répertoire.

La spécification d'un nom de fichier ou de répertoire pour identifier un utilisateur pour un quota n'entraîne pas l'application par ONTAP d'un quota à ce fichier ou ce répertoire.

====

