---
permalink: volumes/specify-unix-users-quotas-concept.html 
sidebar: sidebar 
keywords: specify, unix users, for quotas 
summary: 'Vous pouvez spécifier un utilisateur UNIX pour un quota dans l"un des différents formats.' 
---
= Spécifiez les utilisateurs UNIX pour les quotas
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez spécifier un utilisateur UNIX pour un quota dans l'un des différents formats.

Les trois formats disponibles lors de la spécification d'un utilisateur UNIX pour un quota sont les suivants :

* Le nom d'utilisateur (par exemple jsmith).
+
[NOTE]
====
Vous ne pouvez pas utiliser un nom d'utilisateur UNIX pour spécifier un quota si ce nom comprend une barre oblique inverse (\) ou un signe @. Ceci est dû au fait que ONTAP traite les noms contenant ces caractères comme des noms Windows.

====
* ID utilisateur ou UID (par exemple, 20).
* Le chemin d'accès d'un fichier ou d'un répertoire appartenant à cet utilisateur, de sorte que l'UID du fichier corresponde à celui de l'utilisateur.
+
[NOTE]
====
Si vous spécifiez un nom de fichier ou de répertoire, vous devez sélectionner un fichier ou un répertoire qui durera tant que le compte utilisateur reste sur le système.

La spécification d'un nom de fichier ou de répertoire pour l'UID n'entraîne pas ONTAP l'application d'un quota à ce fichier ou répertoire.

====

