---
permalink: volumes/split-flexclone-from-parent-task.html 
sidebar: sidebar 
keywords: split, flexclone, volume, parent, volume, clone 
summary: Vous pouvez séparer un volume FlexClone de son parent pour en faire un volume FlexVol normal. 
---
= Séparer un volume FlexClone de son volume parent
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez séparer un volume FlexClone de son parent pour en faire un volume FlexVol normal.

L'opération de fractionnement de clone a lieu en arrière-plan. Les données sont accessibles sur le clone et sur le parent lors du fractionnement. À partir de la version ONTAP 9.4, l'optimisation de l'espace est préservée. Le processus de fractionnement ne met à jour que les métadonnées et requiert un nombre d'E/S minimal. Aucun bloc de données n'est copié.

.Description de la tâche
* De nouveaux snapshots du volume FlexClone ne peuvent pas être créés pendant l'opération de fractionnement.
* Un volume FlexClone ne peut pas être séparé du volume parent s'il appartient à une relation de protection des données ou s'il fait partie d'un miroir de partage de charge.
* Si vous mettez le volume FlexClone hors ligne alors que le fractionnement est en cours, l'opération est suspendue. Lorsque vous remettez le volume FlexClone en ligne, l'opération de fractionnement reprend.
* Après le fractionnement, le volume FlexVol parent et le clone nécessitent l'allocation d'espace complet déterminée par leurs garanties de volume.
* Une fois qu'un volume FlexClone est séparé de son parent, il n'est pas possible de le rejoindre à nouveau.
* Depuis ONTAP 9.4, pour les volumes non garantis sur les systèmes AFF, l'opération de séparation pour les volumes FlexClone partage les blocs physiques et ne copie pas les données. Par conséquent, le fractionnement des volumes FlexClone sur les systèmes AFF est plus rapide que le fractionnement FlexClone sur d'autres systèmes FAS dans ONTAP 9.4 et versions ultérieures. La division FlexClone optimisée sur les systèmes AFF offre plusieurs avantages :
+
** L'efficacité du stockage est préservée après le fractionnement du clone du parent.
** Les instantanés existants ne sont pas supprimés.
** L'opération est plus rapide.
** Le volume FlexClone peut être partagé en tout point de la hiérarchie des clones.




.Avant de commencer
* Vous devez être un administrateur de cluster.
* Le volume FlexClone doit être en ligne au début de l'opération de fractionnement.
* Le volume parent doit être en ligne pour que le fractionnement réussisse.


.Étapes
. Déterminez l'espace libre requis pour terminer l'opération de fractionnement :
+
`volume clone show -estimate -vserver _vserver_name_ -flexclone _clone_volume_name_ -parent-volume _parent_vol_name_`

+
L'exemple suivant fournit des informations sur l'espace libre requis pour séparer le volume FlexClone « clone1 » de son volume parent « vol1 » :

+
[listing]
----
cluster1::> volume clone show -estimate -vserver vs1 -flexclone clone1 -parent-volume volume1
                             Split
Vserver   FlexClone       Estimate
--------- ------------- ----------
vs1       clone1           40.73MB
----
. Vérifiez que l'agrégat contenant le volume FlexClone et que son parent dispose d'un espace suffisant :
+
.. Déterminez la quantité d'espace libre dans l'agrégat contenant le volume FlexClone et son parent :
+
`storage aggregate show`

.. Si l'agrégat contenant ne dispose pas d'un espace disponible suffisant, ajoutez du stockage à l'agrégat :
+
`storage aggregate add-disks`



. Démarrer l'opération de fractionnement :
+
`volume clone split start -vserver _vserver_name_ -flexclone _clone_volume_name_`

+
L'exemple suivant montre comment lancer le processus de séparation du volume FlexClone « clone1 » à partir de son volume parent « vol1 » :

+
[listing]
----
cluster1::> volume clone split start -vserver vs1 -flexclone clone1

Warning: Are you sure you want to split clone volume clone1 in Vserver vs1 ?
{y|n}: y
[Job 1617] Job is queued: Split clone1.
----
. Surveiller l'état de l'opération de séparation FlexClone :
+
`volume clone split show -vserver _vserver_name_ -flexclone _clone_volume_name_`

+
L'exemple suivant montre l'état de l'opération de séparation FlexClone sur un système AFF :

+
[listing]
----
cluster1::> volume clone split show -vserver vs1 -flexclone clone1
                                              Inodes                   Blocks
                                     ---------------------    ---------------------
Vserver   FlexClone    Processed Total    Scanned  Updated      % Inode   % Block
                                                                 Complete  Complete
vs1       clone1        0         0       411247   153600         0        37
----
. Vérifier que le volume fragmenté n'est plus un volume FlexClone :
+
`volume show -volume _volume_name_ -fields clone-volume`

+
La valeur du `clone-volume` L'option est « false » pour un volume qui n'est pas un volume FlexClone.

+
L'exemple suivant montre comment vérifier si le volume « clone1 » qui est séparé de son parent n'est pas un volume FlexClone.

+
[listing]
----
cluster1::> volume show -volume clone1 -fields clone-volume
vserver volume **clone-volume**
------- ------ **------------**
vs1     clone1 **false**
----

