---
permalink: volumes/track-quotas-concept.html 
sidebar: sidebar 
keywords: how, you, use, tracking, quotas 
summary: 'Un quota de suivi génère un rapport sur l"utilisation des disques et des fichiers, rend la modification des valeurs de quota moins perturbatrice et ne limite pas l"utilisation des ressources.' 
---
= Utiliser des quotas de suivi
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un quota de suivi génère un rapport sur l'utilisation des disques et des fichiers et ne limite pas l'utilisation des ressources. Lorsque des quotas de suivi sont utilisés, la modification des valeurs de quota est moins perturbatrice car vous pouvez redimensionner les quotas plutôt que de les désactiver puis de les activer à nouveau.

Pour créer un quota de suivi, vous omettez les paramètres limite de disque et limite de fichiers. Cela permet à ONTAP de surveiller l'utilisation des disques et des fichiers pour cette cible à ce niveau (volume ou qtree), sans imposer de limites. Les quotas de suivi sont indiqués dans la sortie de `show` commandes et le rapport de quota avec un tiret ("-") pour toutes les limites. ONTAP crée automatiquement des quotas de suivi lorsque vous utilisez l'interface utilisateur de System Manager pour créer des quotas explicites (quotas avec des cibles spécifiques). Lors de l'utilisation de l'interface de ligne de commandes, l'administrateur du stockage crée des quotas de suivi en plus des quotas explicites.

Vous pouvez également spécifier un quota de suivi par défaut_, qui s'applique à toutes les instances de la cible. Les quotas par défaut de suivi vous permettent de suivre l'utilisation de toutes les instances d'un type de quota (par exemple, tous les qtrees ou tous les utilisateurs). De plus, elles vous permettent d'utiliser le redimensionnement plutôt que la réinitialisation lorsque vous voulez que les modifications de quotas soient appliquées.

.Exemples
Le résultat d'une règle de suivi affiche les quotas de suivi en place pour un qtree, un utilisateur et un groupe, comme illustré dans l'exemple suivant pour une règle de suivi au niveau des volumes :

[listing]
----
Vserver: vs0             Policy: default             Volume: fv1

                                      Soft          Soft
                       User    Disk   Disk   Files  Files
Type  Target   Qtree   Mapping Limit  Limit  Limit  Limit  Threshold
----- -------- ------- ------- ------ ------ ------ ------ ---------
tree  ""       ""      -       -      -      -      -      -
user  ""       ""      off     -      -      -      -      -
group ""       ""      -       -      -      -      -      -
----