---
permalink: volumes/view-volume-efficiency-policy-task.html 
sidebar: sidebar 
keywords: view, volume, efficiency, policy 
summary: 'Vous pouvez afficher la règle d"efficacité des volumes, y compris le nom, la planification, la durée et la description.' 
---
= Affichez une règle d'efficacité de volume dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher la règle d'efficacité des volumes, y compris le nom, la planification, la durée et la description.

.Description de la tâche
La commande `volume efficiency policy show` permet d'afficher une règle d'efficacité des volumes. Lorsque vous exécutez la commande dans l'étendue du cluster, les politiques cluster-scoped ne sont pas affichées. Toutefois, vous pouvez afficher les policies de cluster-scoped dans le contexte du SVM. Pour en savoir plus, `volume efficiency policy show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-policy-show.html["Référence de commande ONTAP"^].

.Étapes
. Utilisez le `volume efficiency policy show` commande pour afficher les informations relatives à une règle d'efficacité du volume.
+
La sortie dépend des paramètres que vous spécifiez. Pour en savoir plus, `volume efficiency policy show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-policy-show.html["Référence de commande ONTAP"^].



.Exemples
La commande suivante affiche des informations sur les politiques créées pour le SVM vs1 :
`volume efficiency policy show -vserver vs1`

La commande suivante affiche les politiques pour lesquelles la durée est définie sur 10 heures :
`volume efficiency policy show -duration 10`
