---
permalink: encryption-at-rest/assign-authentication-keys-seds-external-task.html 
sidebar: sidebar 
keywords: assign, data, authentication, key, fips, drive, sed, external, key, management 
summary: 'Vous pouvez utiliser la commande Storage Encryption disk modify pour attribuer une clé d"authentification de données à un lecteur FIPS ou SED. Les nœuds de cluster utilisent cette clé pour verrouiller ou déverrouiller des données chiffrées sur le disque.' 
---
= Attribution d'une clé d'authentification de données à un lecteur FIPS ou SED (gestion de clés externe)
:allow-uri-read: 


[role="lead"]
Vous pouvez utiliser le `storage encryption disk modify` Commande permettant d'attribuer une clé d'authentification de données à un lecteur FIPS ou SED. Les nœuds de cluster utilisent cette clé pour verrouiller ou déverrouiller des données chiffrées sur le disque.

.Ce dont vous avez besoin
Vous devez être un administrateur de cluster pour effectuer cette tâche.

.Description de la tâche
Un disque à chiffrement automatique est protégé contre tout accès non autorisé uniquement si son ID de clé d'authentification est défini sur une valeur autre que celle par défaut. L'ID sécurisé du fabricant (MSID), qui possède l'ID de clé 0x0, est la valeur par défaut standard des lecteurs SAS. Pour les disques NVMe, la valeur standard par défaut est une clé nulle, représentée sous forme d'ID de clé vierge. Lorsque vous attribuez l'ID de clé à un disque auto-crypté, le système remplace son ID de clé d'authentification par une valeur autre que celle par défaut.

.Étapes
. Attribuez une clé d'authentification de données à un lecteur FIPS ou SED :
+
`storage encryption disk modify -disk _disk_ID_ -data-key-id _key_ID_`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
[NOTE]
====
Vous pouvez utiliser le `security key-manager query -key-type NSE-AK` Commande permettant d'afficher les ID de clés.

====
+
[listing]
----
cluster1::> storage encryption disk modify -disk 0.10.* -data-key-id F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C

Info: Starting modify on 14 disks.
      View the status of the operation by using the
      storage encryption disk show-status command.
----
. Vérifiez que les clés d'authentification ont été attribuées :
+
`storage encryption disk show`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
0.0.1   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
[...]
----

