---
permalink: encryption-at-rest/assign-authentication-keys-seds-onboard-task.html 
sidebar: sidebar 
keywords: assign, data, authentication, key, fips, drive, sed, onboard, key, management 
summary: 'Vous pouvez utiliser la commande Storage Encryption disk modify pour attribuer une clé d"authentification de données à un lecteur FIPS ou SED. Les nœuds de cluster utilisent cette clé pour accéder aux données du disque.' 
---
= Attribuez une clé d'authentification des données à un lecteur FIPS ou SED (gestion intégrée des clés) avec ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `storage encryption disk modify` Commande permettant d'attribuer une clé d'authentification de données à un lecteur FIPS ou SED. Les nœuds de cluster utilisent cette clé pour accéder aux données du disque.

.Description de la tâche
Un disque à chiffrement automatique est protégé contre tout accès non autorisé uniquement si son ID de clé d'authentification est défini sur une valeur autre que celle par défaut. L'ID sécurisé du fabricant (MSID), qui possède l'ID de clé 0x0, est la valeur par défaut standard des lecteurs SAS. Pour les disques NVMe, la valeur standard par défaut est une clé nulle, représentée sous forme d'ID de clé vierge. Lorsque vous attribuez l'ID de clé à un disque auto-crypté, le système remplace son ID de clé d'authentification par une valeur autre que celle par défaut.

.Avant de commencer
Vous devez être un administrateur de cluster pour effectuer cette tâche.

.Étapes
. Attribuez une clé d'authentification de données à un lecteur FIPS ou SED :
+
`storage encryption disk modify -disk _disk_ID_ -data-key-id _key_ID_`

+
Pour en savoir plus, `storage encryption disk modify` consultez le link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-modify.html["Référence de commande ONTAP"^].

+
[NOTE]
====
Vous pouvez utiliser le `security key-manager key query -key-type NSE-AK` Commande permettant d'afficher les ID de clés.

====
+
[listing]
----
cluster1::> storage encryption disk modify -disk 0.10.* -data-key-id <id_value>

Info: Starting modify on 14 disks.
      View the status of the operation by using the
      storage encryption disk show-status command.
----
. Vérifiez que les clés d'authentification ont été attribuées :
+
`storage encryption disk show`

+
Pour en savoir plus, `storage encryption disk show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html["Référence de commande ONTAP"^].

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data <id_value>
0.0.1   data <id_value>
[...]
----

