---
permalink: encryption-at-rest/change-key-management-passphrase-task.html 
sidebar: sidebar 
keywords: changing, onboard, key, management, passphrase 
summary: Modifiez régulièrement la phrase secrète de gestion des clés intégrées.  Stockez la nouvelle phrase secrète dans un endroit sûr en dehors du système de stockage. 
---
= Modifier la phrase secrète de gestion des clés intégrées ONTAP
:allow-uri-read: 


[role="lead"]
NetApp recommande de modifier régulièrement la phrase de passe de gestion des clés intégrées. Vous devez stocker la nouvelle phrase de passe dans un endroit sécurisé, en dehors du système de stockage.

.Avant de commencer
* Pour effectuer cette tâche, vous devez être un administrateur de cluster ou de SVM.
* Des privilèges avancés sont requis pour cette tâche.
* Dans un environnement MetroCluster , après avoir mis à jour la phrase secrète sur le cluster local, synchronisez la mise à jour de la phrase secrète sur le cluster partenaire.


.Étapes
. Changement au niveau de privilège avancé :
+
`set -privilege advanced`

. Modifiez la phrase de passe de gestion des clés intégrées. La commande à utiliser dépend de la version ONTAP que vous utilisez.
+
[role="tabbed-block"]
====
.ONTAP 9.6 et versions ultérieures
--
`security key-manager onboard update-passphrase`

--
.ONTAP 9.5 et versions antérieures
--
`security key-manager update-passphrase`

--
====
. Saisissez une phrase secrète entre 32 et 256 caractères, ou pour « `cc-mode` », une phrase secrète entre 64 et 256 caractères.
+
Si la phrase de passe « CC-mode » spécifiée est inférieure à 64 caractères, il y a un délai de cinq secondes avant que l'opération de configuration du gestionnaire de clés n'affiche à nouveau l'invite de phrase de passe.

. À l'invite de confirmation de la phrase de passe, saisissez à nouveau la phrase de passe.
. Si vous utilisez une configuration MetroCluster , synchronisez la phrase secrète mise à jour sur le cluster partenaire.
+
.. Synchronisez la phrase secrète sur le cluster partenaire en choisissant la commande appropriée pour votre version ONTAP :
+
[role="tabbed-block"]
====
.ONTAP 9.6 et versions ultérieures
--
`security key-manager onboard sync`

--
.ONTAP 9.5 et versions antérieures
--
*** Dans ONTAP 9.5, exécutez :
+
`security key-manager setup -sync-metrocluster-config`

*** Dans ONTAP 9.4 et versions antérieures, après avoir mis à jour la phrase secrète sur le cluster local, attendez 20 secondes, puis exécutez la commande suivante sur le cluster partenaire :
+
`security key-manager setup`



--
====
.. Saisissez la nouvelle phrase secrète lorsque vous y êtes invité.
+
La même phrase secrète doit être utilisée sur les deux clusters.





.Une fois que vous avez terminé
Copiez la phrase secrète de gestion des clés intégrée dans un emplacement sécurisé en dehors du système de stockage pour une utilisation ultérieure.

Sauvegardez manuellement les informations de gestion des clés chaque fois que vous modifiez la phrase de passe de gestion des clés intégrée.

.Informations associées
* link:backup-key-management-information-manual-task.html["Sauvegardez manuellement les informations intégrées de gestion des clés"]
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-update-passphrase.html["mot de passe de mise à jour intégré du gestionnaire de clés de sécurité"^]

