---
permalink: encryption-at-rest/change-key-management-passphrase-task.html 
sidebar: sidebar 
keywords: changing, onboard, key, management, passphrase 
summary: 'Il est recommandé d"appliquer régulièrement une meilleure pratique de sécurité à la modification de la phrase secrète intégrée pour la gestion des clés. Copiez la nouvelle phrase secrète intégrée pour la gestion des clés dans un emplacement sécurisé en dehors du système de stockage pour une utilisation ultérieure.' 
---
= Modifiez la phrase secrète intégrée pour la gestion des clés
:allow-uri-read: 


[role="lead"]
Il est recommandé d'appliquer régulièrement une meilleure pratique de sécurité à la modification de la phrase secrète intégrée pour la gestion des clés. Copiez la nouvelle phrase secrète intégrée pour la gestion des clés dans un emplacement sécurisé en dehors du système de stockage pour une utilisation ultérieure.

.Ce dont vous avez besoin, 8217;ll
* Pour effectuer cette tâche, vous devez être un administrateur de cluster ou de SVM.
* Des privilèges avancés sont requis pour cette tâche.


.Étapes
. Changement au niveau de privilège avancé :
+
`set -privilege advanced`

. Modifiez la phrase secrète intégrée pour la gestion des clés :
+
[cols="25,75"]
|===


| Pour cette version ONTAP... | Utilisez cette commande... 


 a| 
ONTAP 9.6 et versions ultérieures
 a| 
`security key-manager onboard update-passphrase`



 a| 
ONTAP 9.5 et versions antérieures
 a| 
`security key-manager update-passphrase`

|===
+
Pour connaître la syntaxe complète des commandes, consultez les pages de manuels.

+
La commande suivante de ONTAP 9.6 vous permet de modifier la phrase secrète de gestion intégrée des clés pour `cluster1`:

+
[listing]
----
clusterl::> security key-manager onboard update-passphrase
Warning: This command will reconfigure the cluster passphrase for onboard key management for Vserver "cluster1".
Do you want to continue? {y|n}: y
Enter current passphrase:
Enter new passphrase:
----
. Entrez `y` à l'invite, vous pouvez modifier la phrase secrète intégrée pour la gestion des clés.
. Saisissez la phrase de passe actuelle à l'invite de phrase de passe actuelle.
. À l'invite de la nouvelle phrase de passe, entrez une phrase de passe comprise entre 32 et 256 caractères, ou une phrase de passe entre 64 et 256 caractères pour « mode CC ».
+
Si la phrase de passe « CC-mode » spécifiée est inférieure à 64 caractères, il y a un délai de cinq secondes avant que l'opération de configuration du gestionnaire de clés n'affiche à nouveau l'invite de phrase de passe.

. À l'invite de confirmation de la phrase de passe, saisissez à nouveau la phrase de passe.


Dans un environnement MetroCluster, vous devez mettre à jour la phrase secrète sur le cluster partenaire :

* Dans ONTAP 9.5 et les versions antérieures, vous devez exécuter `security key-manager update-passphrase` avec la même phrase secrète sur le cluster partenaire.
* Dans ONTAP 9.6 et versions ultérieures, vous êtes invité à exécuter `security key-manager onboard sync` avec la même phrase secrète sur le cluster partenaire.


Copiez le mot de passe de gestion des clés intégré vers un emplacement sécurisé en dehors du système de stockage pour une utilisation ultérieure.

Vous devez sauvegarder manuellement les informations de gestion des clés chaque fois que vous modifiez la phrase secrète de gestion intégrée des clés.

link:backup-key-management-information-manual-task.html["Sauvegarde manuelle des informations de gestion intégrée des clés"]
