---
permalink: encryption-at-rest/change-key-management-passphrase-task.html 
sidebar: sidebar 
keywords: changing, onboard, key, management, passphrase 
summary: Modifiez régulièrement la phrase secrète de gestion des clés intégrées.  Stockez la nouvelle phrase secrète dans un endroit sûr en dehors du système de stockage. 
---
= Modifier la phrase secrète de gestion des clés intégrées ONTAP
:allow-uri-read: 


[role="lead"]
Modifiez régulièrement la phrase secrète de gestion des clés intégrées.  Stockez la nouvelle phrase secrète dans un endroit sûr en dehors du système de stockage.

.Avant de commencer
* Pour effectuer cette tâche, vous devez être un administrateur de cluster ou de SVM.
* Des privilèges avancés sont requis pour cette tâche.
* Si vous administrez un environnement ONTAP MetroCluster , vous devez mettre à jour la phrase secrète sur les deux clusters


.Étapes
. Changement au niveau de privilège avancé :
+
`set -privilege advanced`

. Modifiez la phrase secrète intégrée pour la gestion des clés :
+
[cols="25,75"]
|===


| Pour cette version ONTAP... | Utilisez cette commande... 


 a| 
ONTAP 9.6 et versions ultérieures
 a| 
`security key-manager onboard update-passphrase`



 a| 
ONTAP 9.5 et versions antérieures
 a| 
`security key-manager update-passphrase`

|===
. Saisissez une phrase secrète entre 32 et 256 caractères, ou pour « `cc-mode` », une phrase secrète entre 64 et 256 caractères.
+
Si la phrase de passe « CC-mode » spécifiée est inférieure à 64 caractères, il y a un délai de cinq secondes avant que l'opération de configuration du gestionnaire de clés n'affiche à nouveau l'invite de phrase de passe.

. À l'invite de confirmation de la phrase de passe, saisissez à nouveau la phrase de passe.


.Une fois que vous avez terminé
Copiez le mot de passe de gestion des clés intégré vers un emplacement sécurisé en dehors du système de stockage pour une utilisation ultérieure.

Vous devez sauvegarder manuellement les informations de gestion des clés chaque fois que vous modifiez la phrase secrète de gestion intégrée des clés.

.Informations associées
* link:backup-key-management-information-manual-task.html["Sauvegarde manuelle des informations de gestion intégrée des clés"]
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-update-passphrase.html["mot de passe de mise à jour intégré du gestionnaire de clés de sécurité"^]

