---
permalink: encryption-at-rest/change-encryption-key-volume-92-earlier-task.html 
sidebar: sidebar 
keywords: changing, encryption key, volume, volume move start, command 
summary: 'Il est recommandé de modifier régulièrement la clé de chiffrement d"un volume. Vous pouvez utiliser la commande volume Move start pour changer la clé de chiffrement. Le volume déplacé peut résider sur le même agrégat ou sur un autre agrégat.' 
---
= Modifier la clé de chiffrement d'un volume avec la commande ONTAP volume move start
:allow-uri-read: 


[role="lead"]
Il est recommandé de modifier régulièrement la clé de chiffrement d'un volume. Vous pouvez utiliser `volume move start` la commande pour modifier la clé de chiffrement. Le volume déplacé peut résider sur le même agrégat ou sur un autre agrégat.

.Description de la tâche
Vous ne pouvez pas utiliser `volume move start` Pour reKey un volume SnapLock ou FlexGroup.

.Avant de commencer
Vous devez être un administrateur de cluster pour effectuer cette tâche.

.Étapes
. Déplacer un volume existant et modifier la clé de chiffrement :
+
`volume move start -vserver _SVM_name_ -volume _volume_name_ -destination-aggregate _aggregate_name_ -generate-destination-key true`

+
Pour en savoir plus, `volume move start` consultez le link:https://docs.netapp.com/us-en/ontap-cli/volume-move-start.html["Référence de commande ONTAP"^].

+
La commande suivante déplace un volume existant nommé `*vol1*` vers l'agrégat de destination `*aggr2*` et modifie la clé de chiffrement :

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol1 -destination-aggregate aggr2 -generate-destination-key true
----
+
Une nouvelle clé de chiffrement est créée pour le volume. Les données du volume restent chiffrées.

. Vérifiez que le volume est activé pour le chiffrement :
+
`volume show -is-encrypted true`

+
Pour en savoir plus, `volume show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/volume-show.html["Référence de commande ONTAP"^].

+
La commande suivante affiche les volumes chiffrés sur `cluster1`:

+
[listing]
----
cluster1::> volume show -is-encrypted true

Vserver  Volume  Aggregate  State  Type  Size  Available  Used
-------  ------  ---------  -----  ----  -----  --------- ----
vs1      vol1    aggr2     online    RW  200GB    160.0GB  20%
----

