---
permalink: encryption-at-rest/configure-external-key-management-overview-concept.html 
sidebar: sidebar 
keywords: external key management, kmip, configure 
summary: 'Vous pouvez utiliser un ou plusieurs serveurs externes de gestion des clés pour sécuriser les clés que le cluster utilise pour accéder aux données chiffrées. Un serveur externe de gestion des clés est un système tiers de votre environnement de stockage qui transmet des clés aux nœuds à l"aide du protocole KMIP (Key Management Interoperability Protocol).' 
---
= En savoir plus sur la configuration de la gestion externe des clés avec ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser un ou plusieurs serveurs externes de gestion des clés pour sécuriser les clés que le cluster utilise pour accéder aux données chiffrées. Un serveur externe de gestion des clés est un système tiers de votre environnement de stockage qui transmet des clés aux nœuds à l'aide du protocole KMIP (Key Management Interoperability Protocol).


NOTE: Pour ONTAP 9.1 et les versions antérieures, les LIFs de node-management doivent être attribuées à des ports configurés avec le rôle de node-management avant de pouvoir utiliser le gestionnaire de clés externe.

NetApp Volume Encryption (NVE) prend en charge le gestionnaire de clés intégré dans ONTAP 9.1 et les versions ultérieures. À partir de la version ONTAP 9.3, NVE prend en charge la gestion externe des clés (KMIP) et le gestionnaire de clés intégré. Depuis la version ONTAP 9.10.1, vous pouvez utiliser xref:manage-keys-azure-google-task.html[Azure Key Vault ou Google Cloud Key Manager Service] pour protéger vos clés NVE. Depuis la version ONTAP 9.11.1, vous pouvez configurer plusieurs gestionnaires de clés externes dans un cluster. Voir xref:configure-cluster-key-server-task.html[Configurez les serveurs de clés en cluster.]
