---
permalink: encryption-at-rest/configure-external-key-management-overview-concept.html 
sidebar: sidebar 
keywords: external key management, kmip, configure 
summary: 'Vous pouvez utiliser un ou plusieurs serveurs externes de gestion des clés pour sécuriser les clés que le cluster utilise pour accéder aux données chiffrées. Un serveur externe de gestion des clés est un système tiers de votre environnement de stockage qui transmet des clés aux nœuds à l"aide du protocole KMIP (Key Management Interoperability Protocol).' 
---
= En savoir plus sur la configuration de la gestion des clés externes avec ONTAP NetApp Volume Encryption
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser un ou plusieurs serveurs de gestion de clés externes pour sécuriser les clés utilisées par le cluster pour accéder aux données chiffrées. Un serveur de gestion de clés externe est un système tiers de votre environnement de stockage qui fournit des clés aux nœuds via le protocole KMIP (Key Management Interoperability Protocol). Outre le gestionnaire de clés intégré, ONTAP prend en charge plusieurs serveurs de gestion de clés externes.

 Beginning with ONTAP 9.10.1, you can use xref:manage-keys-azure-google-task.html[Azure Key Vault or Google Cloud Key Manager Service] to protect your NVE keys for data SVMs. Beginning with ONTAP 9.11.1, you can configure multiple external key managers in a cluster. See xref:configure-cluster-key-server-task.html[Configure clustered key servers]. Beginning with ONTAP 9.12.0, you can use link:https://docs.aws.amazon.com/kms/latest/developerguide/overview.html[AWS' KMS^] to protect your NVE keys for data SVMs. Beginning with ONTAP 9.17.1, you can use OpenStack's xref:manage-keys-barbican-task.html[Barbican KMS] to protect your NVE keys for data SVMs.