---
permalink: encryption-at-rest/delete-encrypted-volume-task.html 
sidebar: sidebar 
keywords: deleting, encrypted, volume 
summary: Vous pouvez utiliser la commande volume delete pour supprimer un volume chiffré. 
---
= Supprime un volume chiffré dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `volume delete` commande de suppression d'un volume chiffré.

.Avant de commencer
* Vous devez être un administrateur de cluster pour effectuer cette tâche.
* Le volume doit être hors ligne.


.Étape
. Supprimez un volume chiffré :
+
`volume delete -vserver _SVM_name_ -volume _volume_name_`

+
Pour en savoir plus, `volume delete` consultez le link:https://docs.netapp.com/us-en/ontap-cli/volume-delete.html["Référence de commande ONTAP"^].

+
La commande suivante supprime un volume chiffré nommé `vol1`:

+
[listing]
----
cluster1::> volume delete -vserver vs1 -volume vol1
----
+
Entrez `yes` lorsque vous êtes invité à confirmer la suppression.

+
Le système supprime la clé de cryptage du volume au bout de 24 heures.

+
À utiliser `volume delete` avec la `-force true` possibilité de supprimer un volume et de détruire immédiatement la clé de chiffrement correspondante. Cette commande nécessite des privilèges avancés. Pour en savoir plus, `volume delete` consultez le link:https://docs.netapp.com/us-en/ontap-cli/volume-delete.html["Référence de commande ONTAP"^].



.Une fois que vous avez terminé
Vous pouvez utiliser le `volume recovery-queue` pour restaurer un volume supprimé pendant la période de rétention après l'émission du `volume delete` commande :

`volume recovery-queue _SVM_name_ -volume _volume_name_`

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_use_the_Volume_Recovery_Queue["Comment utiliser la fonction de récupération de volume"]
