---
permalink: encryption-at-rest/delegate-volume-encryption-svm-administrator-task.html 
sidebar: sidebar 
keywords: delegating, authority, run, volume move, command 
summary: 'Vous pouvez utiliser la commande volume Move pour chiffrer un volume existant, déplacer un volume chiffré ou annuler le chiffrement d"un volume. Les administrateurs de cluster peuvent exécuter la commande de déplacement de volume eux-mêmes ou déléguer l"autorité aux administrateurs du SVM.' 
---
= Autorité déléguée pour exécuter la commande volume Move dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `volume move` commande pour chiffrer un volume existant, déplacer un volume chiffré ou annuler le chiffrement d'un volume. Les administrateurs du cluster peuvent exécuter `volume move` Ils peuvent se passer eux-mêmes de la commande ou déléguer à l'autorité pour qu'elle exécute la commande aux administrateurs du SVM.

.Description de la tâche
Par défaut, les administrateurs du SVM sont affectés au système `vsadmin` rôle, qui ne comprend pas l'autorité nécessaire pour déplacer les volumes. Vous devez affecter le `vsadmin-volume` Rôle aux administrateurs SVM afin de leur permettre d'exécuter les `volume move` commande.

.Étape
. Déléguer l'autorité pour exécuter le `volume move` commande :
+
`security login modify -vserver _SVM_name_ -user-or-group-name _user_or_group_name_ -application _application_ -authmethod _authentication_method_ -role _vsadmin-volume_`

+
La commande suivante permet à l'administrateur du SVM d'exécuter le `volume move` commande.

+
[listing]
----
cluster1::>security login modify -vserver engData -user-or-group-name SVM-admin -application ssh -authmethod domain -role vsadmin-volume
----
+
Pour en savoir plus, `security login modify` consultez le link:https://docs.netapp.com/us-en/ontap-cli/security-login-modify.html["Référence de commande ONTAP"^].


