---
permalink: encryption-at-rest/delete-key-management-database-task.html 
sidebar: sidebar 
keywords: transitioning, onboard key management, external key management 
summary: 'Pour basculer vers la gestion intégrée des clés à partir d"une gestion externe des clés, vous devez supprimer la configuration de gestion externe des clés pour pouvoir activer la gestion intégrée des clés.' 
---
= Transition vers la gestion intégrée des clés à partir d'une gestion externe des clés
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour basculer vers la gestion intégrée des clés à partir d'une gestion externe des clés, vous devez supprimer la configuration de gestion externe des clés pour pouvoir activer la gestion intégrée des clés.

.Avant de commencer
* Pour le chiffrement matériel, vous devez réinitialiser les clés de données de tous les lecteurs FIPS ou SED à la valeur par défaut.
+
link:return-seds-unprotected-mode-task.html["Retour d'un lecteur FIPS ou SED en mode non protégé"]

* Vous devez avoir supprimé toutes les connexions externes du gestionnaire de clés.
+
link:remove-external-key-server-93-later-task.html["Suppression d'une connexion externe au gestionnaire de clés"]

* Vous devez être un administrateur de cluster pour effectuer cette tâche.




== Procédure

[role="tabbed-block"]
====
.ONTAP 9.6 et versions ultérieures
--
. Changement au niveau de privilège avancé :
+
`set -privilege advanced`

. Utiliser la commande :
+
`security key-manager external disable -vserver _admin_SVM_`



--
.ONTAP 9.5 et versions antérieures
--
Utiliser la commande :
`security key-manager delete-kmip-config`

--
====