---
permalink: encryption-at-rest/delete-encrypted-volume-task.html 
sidebar: sidebar 
keywords: deleting, encrypted, volume 
summary: Vous pouvez utiliser la commande volume delete pour supprimer un volume chiffré. 
---
= Supprimez un volume chiffré
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `volume delete` commande de suppression d'un volume chiffré.

.Avant de commencer
* Vous devez être un administrateur de cluster pour effectuer cette tâche. Vous pouvez également être un administrateur SVM auquel l'administrateur du cluster a délégué des pouvoirs. Pour plus d'informations, voir link:delegate-volume-encryption-svm-administrator-task.html["autorité déléguée pour exécuter la commande de déplacement de volume"].
* Le volume doit être hors ligne.


.Étape
. Supprimez un volume chiffré :
+
`volume delete -vserver _SVM_name_ -volume _volume_name_`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
La commande suivante supprime un volume chiffré nommé `vol1`:

+
[listing]
----
cluster1::> volume delete -vserver vs1 -volume vol1
----
+
Entrez `yes` lorsque vous êtes invité à confirmer la suppression.

+
Le système supprime la clé de cryptage du volume au bout de 24 heures.

+
Utiliser `volume delete` avec le `-force true` option permettant de supprimer un volume et de détruire immédiatement la clé de chiffrement correspondante. Cette commande nécessite des privilèges avancés. Pour plus d'informations, consultez la page man.



.Une fois que vous avez terminé
Vous pouvez utiliser le `volume recovery-queue` pour restaurer un volume supprimé pendant la période de rétention après l'émission du `volume delete` commande :

`volume recovery-queue _SVM_name_ -volume _volume_name_`

https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_use_the_Volume_Recovery_Queue["Comment utiliser la fonction de récupération de volume"]
