---
permalink: encryption-at-rest/destroy-nse-disks-task.html 
sidebar: sidebar 
keywords: fips, drive, sed, inaccessible, destroy, psid, physical secure ID, nrd plus, encrypt, 
summary: 'Si vous voulez rendre les données sur un lecteur FIPS ou SED définitivement inaccessibles et que vous n"avez pas besoin de réutiliser le lecteur, vous pouvez utiliser `storage encryption disk destroy` commande de destruction du disque.' 
---
= Détruisez un disque FIPS ou SED dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous voulez rendre les données sur un lecteur FIPS ou SED définitivement inaccessibles et que vous n'avez pas besoin de réutiliser le lecteur, vous pouvez utiliser `storage encryption disk destroy` commande de destruction du disque.

.Description de la tâche
Lorsque vous détruisez un lecteur FIPS ou SED, le système définit la clé de cryptage sur une valeur aléatoire inconnue et verrouille le disque de façon irréversible. Le disque devient ainsi pratiquement inutilisable et les données qu'il y a définitivement inaccessibles. Cependant, vous pouvez réinitialiser le disque à ses paramètres configurés en usine à l'aide de l'ID de sécurité physique (PSID) imprimé sur l'étiquette du disque. Pour plus d'informations, voir link:return-self-encrypting-disks-keys-not-available-task.html["Remise en service d'un lecteur FIPS ou SED en cas de perte de clés d'authentification"].


NOTE: Vous ne devez pas détruire un disque FIPS ou SED sauf si vous disposez du service NRD plus (non-Returnable Disk plus). La destruction d'un disque annule sa garantie.

.Avant de commencer
Vous devez être un administrateur de cluster pour effectuer cette tâche.

.Étapes
. Migrer toutes les données qui doivent être conservées vers un agrégat sur un autre disque.
. Supprimez l'agrégat du disque FIPS ou SED à détruire :
+
`storage aggregate delete -aggregate aggregate_name`

+
Pour en savoir plus, `storage aggregate delete` consultez le link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-delete.html["Référence de commande ONTAP"^].

+
[listing]
----
cluster1::> storage aggregate delete -aggregate aggr1
----
. Identifiez l'ID de disque pour le lecteur FIPS ou SED à détruire :
+
`storage encryption disk show`

+
Pour en savoir plus, `storage encryption disk show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html["Référence de commande ONTAP"^].

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
0.0.1   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
1.10.2  data F1CB30AFF1CB30B00101000000000000CF0EFD81EA9F6324EA97B369351C56AC
[...]
----
. Détruire le disque :
+
`storage encryption disk destroy -disk disk_id`

+
Pour en savoir plus, `storage encryption disk destroy` consultez le link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-destroy.html["Référence de commande ONTAP"^].

+
[NOTE]
====
Vous êtes invité à entrer une phrase de confirmation avant de continuer. Saisissez la phrase exactement comme indiqué à l'écran.

====
+
[listing]
----
cluster1::> storage encryption disk destroy -disk 1.10.2

Warning: This operation will cryptographically destroy 1 spare or broken
         self-encrypting disks on 1 node.
         You cannot reuse destroyed disks unless you revert
         them to their original state using the PSID value.
         To continue, enter
          destroy disk
         :destroy disk

Info: Starting destroy on 1 disk.
      View the status of the operation by using the
      "storage encryption disk show-status" command.
----

