---
permalink: encryption-at-rest/install-license-task.html 
sidebar: sidebar 
keywords: install, license, VE license, NVE, encryption, encrypt data 
summary: 'Une licence VE vous permet d"utiliser cette fonctionnalité sur tous les nœuds du cluster. Vous devez installer la licence pour pouvoir chiffrer les données avec NVE.' 
---
= Installez la licence
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une licence VE vous permet d'utiliser cette fonctionnalité sur tous les nœuds du cluster. Vous devez installer la licence pour pouvoir chiffrer les données avec NVE.

.Ce dont vous avez besoin
Vous devez être un administrateur de cluster pour effectuer cette tâche.

.Description de la tâche
Vous devriez avoir reçu la clé de licence VE de votre représentant commercial.

.Étapes
. Installez la licence VE pour un noeud :
+
`system license add -license-code license_key`

+
La commande suivante installe la licence avec la clé `AAAAAAAAAAAAAAAAAAAAAAAAAAAA`.

+
[listing]
----
cluster1::> system license add -license-code AAAAAAAAAAAAAAAAAAAAAAAAAAAA
----
. Vérifiez que la licence est installée en affichant toutes les licences sur le cluster :
+
`system license show`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
La commande suivante affiche toutes les licences sur `cluster1`:

+
[listing]
----
cluster1::> system license show
----
+
Le nom du paquet de licence VE est "VE".


