---
permalink: encryption-at-rest/modify-external-key-server-96-later-task.html 
sidebar: sidebar 
keywords: modifying, external key management, server, properties 
summary: 'Depuis ONTAP 9.6, vous pouvez utiliser la commande Security Key-Manager External modify-Server pour modifier le délai d"attente des E/S et le nom d"utilisateur d"un serveur de gestion des clés externe.' 
---
= Modifiez les propriétés du serveur de gestion externe des clés
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser ONTAP 9.6 à partir de `security key-manager external modify-server` Commande permettant de modifier le délai d'attente d'E/S et le nom d'utilisateur d'un serveur de gestion de clés externe.

.Avant de commencer
* Pour effectuer cette tâche, vous devez être un administrateur de cluster ou de SVM.
* Des privilèges avancés sont requis pour cette tâche.
* Dans un environnement MetroCluster, vous devez répéter ces étapes sur les deux clusters pour la SVM d'administration.


.Étapes
. Sur le système de stockage, passez au niveau de privilège avancé :
+
`set -privilege advanced`

. Modifiez les propriétés externes du serveur du gestionnaire de clés pour le cluster :
+
`security key-manager external modify-server -vserver admin_SVM -key-server host_name|IP_address:port,... -timeout 1...60 -username user_name`

+
[NOTE]
====
La valeur de temporisation est exprimée en secondes. Si vous modifiez le nom d'utilisateur, vous êtes invité à entrer un nouveau mot de passe. Si vous exécutez la commande à l'invite de connexion du cluster, `_admin_SVM_` Par défaut au SVM admin du cluster actuel. Vous devez être l'administrateur de cluster pour modifier les propriétés du serveur du gestionnaire de clés externe.

====
+
La commande suivante remplace la valeur de temporisation par 45 secondes pour le `cluster1` serveur de gestion externe des clés à l'écoute sur le port par défaut 5696 :

+
[listing]
----
clusterl::> security key-manager external modify-server -vserver cluster1 -key-server ks1.local -timeout 45
----
. Modifier les propriétés du serveur gestionnaire de clés externe pour un SVM (NVE uniquement) :
+
`security key-manager external modify-server -vserver SVM -key-server host_name|IP_address:port,... -timeout 1...60 -username user_name`

+
[NOTE]
====
La valeur de temporisation est exprimée en secondes. Si vous modifiez le nom d'utilisateur, vous êtes invité à entrer un nouveau mot de passe. Si vous exécutez la commande à l'invite de connexion du SVM, `_SVM_` Par défaut au SVM actuel Vous devez être l'administrateur du cluster ou de SVM pour modifier les propriétés du serveur externe Key Manager.

====
+
La commande suivante modifie le nom d'utilisateur et le mot de passe de `svm1` serveur de gestion externe des clés à l'écoute sur le port par défaut 5696 :

+
[listing]
----
svml::> security key-manager external modify-server -vserver svm11 -key-server ks1.local -username svm1user
Enter the password:
Reenter the password:
----
. Répétez la dernière étape pour tout SVM supplémentaire.

