---
permalink: encryption-at-rest/purge-data-encrypted-volume-without-snapmirror-task.html 
sidebar: sidebar 
keywords: secure, purge, scrub, data, encrypted, volume, nve, netapp, volume, encryption, snapmirror 
summary: 'À partir d" ONTAP 9.4, vous pouvez utiliser secure-purge pour nettoyer sans interruption les données sur les volumes compatibles NVE.' 
---
= Nettoyer les données d'un volume ONTAP chiffré sans relation SnapMirror
:allow-uri-read: 


[role="lead"]
Depuis ONTAP 9.4, vous pouvez utiliser la suppression sécurisée vers les données « ``cribs'' sans interruption sur les volumes NVE.

.Description de la tâche
La suppression sécurisée peut prendre de plusieurs minutes à plusieurs heures, selon la quantité de données contenues dans les fichiers supprimés. Vous pouvez utiliser le `volume encryption secure-purge show` commande permettant d'afficher le statut de l'opération. Vous pouvez utiliser le `volume encryption secure-purge abort` commande pour mettre fin à l'opération.


NOTE: Pour effectuer une purge sécurisée sur un hôte SAN, vous devez supprimer la LUN entière contenant les fichiers à purger, ou vous devez pouvoir perforer les trous dans la LUN pour les blocs appartenant aux fichiers à purger. Si vous ne pouvez pas supprimer la LUN ou si votre système d'exploitation hôte ne prend pas en charge la perforation dans la LUN, vous ne pouvez pas effectuer de purge sécurisée.

.Avant de commencer
* Vous devez être un administrateur de cluster pour effectuer cette tâche.
* Des privilèges avancés sont requis pour cette tâche.


.Étapes
. Supprimez les fichiers ou la LUN que vous souhaitez supprimer en toute sécurité.
+
** Sur un client NAS, supprimez les fichiers que vous souhaitez purger en toute sécurité.
** Sur un hôte SAN, supprimez le LUN que vous souhaitez purger ou perforer en toute sécurité les blocs appartenant aux fichiers à supprimer.


. Sur le système de stockage, passez au niveau de privilège avancé :
+
`set -privilege advanced`

. Si les fichiers que vous souhaitez purger en toute sécurité sont dans les instantanés, supprimez-les :
+
`snapshot delete -vserver _SVM_name_ -volume _volume_name_ -snapshot`

. Supprimez les fichiers supprimés de manière sécurisée :
+
`volume encryption secure-purge start -vserver _SVM_name_ -volume _volume_name_`

+
La commande suivante supprime de manière sécurisée les fichiers supprimés sur `vol1` Sur SVM``vs1``:

+
[listing]
----
cluster1::> volume encryption secure-purge start -vserver vs1 -volume vol1
----
. Vérifier l'état de l'opération de purge sécurisée :
+
`volume encryption secure-purge show`


