---
permalink: encryption-at-rest/purge-data-encrypted-asynchronous-snapmirror-task.html 
sidebar: sidebar 
keywords: securely, purging, scrub, data, encrypted, volume, nve, netapp, volume encryption, snapmirror, asynchronous 
summary: À partir de ONTAP 9.8, vous pouvez utiliser la suppression sécurisée pour « nettoyer » les données de volumes NVE avec une relation asynchrone SnapMirror, sans interruption. 
---
= Nettoyer les données d'un volume ONTAP chiffré avec une relation asynchrone SnapMirror
:allow-uri-read: 


[role="lead"]
À partir de ONTAP 9.8, vous pouvez appliquer une suppression sécurisée aux données « crub » sans interruption sur les volumes NVE avec une relation asynchrone SnapMirror.

.Avant de commencer
* Vous devez être un administrateur de cluster pour effectuer cette tâche.
* Des privilèges avancés sont requis pour cette tâche.


.Description de la tâche
La suppression sécurisée peut prendre de plusieurs minutes à plusieurs heures, selon la quantité de données contenues dans les fichiers supprimés. Vous pouvez utiliser le `volume encryption secure-purge show` commande permettant d'afficher le statut de l'opération. Vous pouvez utiliser le `volume encryption secure-purge abort` commande pour mettre fin à l'opération.


NOTE: Pour effectuer une purge sécurisée sur un hôte SAN, vous devez supprimer la LUN entière contenant les fichiers à purger, ou vous devez pouvoir perforer les trous dans la LUN pour les blocs appartenant aux fichiers à purger. Si vous ne pouvez pas supprimer la LUN ou si votre système d'exploitation hôte ne prend pas en charge la perforation dans la LUN, vous ne pouvez pas effectuer de purge sécurisée.

.Étapes
. Sur le système de stockage, basculer sur le niveau de privilège avancé :
+
`set -privilege advanced`

. Supprimez les fichiers ou la LUN que vous souhaitez supprimer en toute sécurité.
+
** Sur un client NAS, supprimez les fichiers que vous souhaitez purger en toute sécurité.
** Sur un hôte SAN, supprimez le LUN que vous souhaitez purger ou perforer en toute sécurité les blocs appartenant aux fichiers à supprimer.


. Préparez le volume de destination dans la relation asynchrone à supprimer de manière sécurisée :
+
`volume encryption secure-purge start -vserver _SVM_name_ -volume _volume_name_ -prepare true`

+
Répétez cette étape pour chaque volume de votre relation SnapMirror asynchrone.

. Si les fichiers que vous souhaitez purger en toute sécurité sont dans les instantanés, supprimez-les :
+
`snapshot delete -vserver _SVM_name_ -volume _volume_name_ -snapshot`

. Si les fichiers que vous souhaitez supprimer en toute sécurité se trouvent dans les instantanés de base, procédez comme suit :
+
.. Créer un snapshot sur le volume de destination dans la relation asynchrone SnapMirror :
+
`volume snapshot create -snapshot snapshot_name -vserver _SVM_name_ -volume _volume_name_`

.. Mettre à jour SnapMirror pour déplacer le snapshot de base vers l'avant :
+
`snapmirror update -source-snapshot _snapshot_name_ -destination-path _destination_path_`

+
Répétez cette étape pour chaque volume de la relation asynchrone SnapMirror.

.. Répéter les étapes (a) et (b) correspondant au nombre d'instantanés de base plus un.
+
Par exemple, si vous avez deux instantanés de base, vous devez répéter les étapes (a) et (b) trois fois.

.. Vérifiez que l'instantané de base est présent : +
`snapshot show -vserver _SVM_name_ -volume _volume_name_`
.. Supprimer l'instantané de base : +
`snapshot delete -vserver _svm_name_ -volume _volume_name_ -snapshot snapshot`


. Supprimez les fichiers supprimés de manière sécurisée :
+
`volume encryption secure-purge start -vserver _svm_name_ -volume _volume_name_`

+
Répétez cette étape pour chaque volume de la relation asynchrone SnapMirror.

+
La commande suivante purge de manière sécurisée les fichiers supprimés sur « 'vol1' » du SVM « vs1 » :

+
[listing]
----
cluster1::> volume encryption secure-purge start -vserver vs1 -volume vol1
----
. Vérifier l'état de l'opération de purge sécurisée :
+
`volume encryption secure-purge show`


