---
permalink: encryption-at-rest/replace-self-encrypting-disk-task.html 
sidebar: sidebar 
keywords: replacing, fips drive, sed 
summary: 'Vous pouvez remplacer un lecteur FIPS ou SED de la même façon que vous remplacez un disque ordinaire. Veillez à attribuer de nouvelles clés d"authentification des données au disque de remplacement. Pour un lecteur FIPS, vous pouvez également attribuer une nouvelle clé d"authentification FIPS 140-2.' 
---
= Remplacez un lecteur FIPS ou SED dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez remplacer un lecteur FIPS ou SED de la même façon que vous remplacez un disque ordinaire. Veillez à attribuer de nouvelles clés d'authentification des données au disque de remplacement. Pour un lecteur FIPS, vous pouvez également attribuer une nouvelle clé d'authentification FIPS 140-2.


NOTE: Si une paire haute disponibilité est utilisée link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/support-storage-encryption-concept.html["Cryptage SAS ou disques NVMe (SED, NSE, FIPS)"], vous devez suivre les instructions de la rubrique link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/return-seds-unprotected-mode-task.html["Retour d'un lecteur FIPS ou SED en mode non protégé"] Pour tous les disques de la paire HA avant d'initialiser le système (options de démarrage 4 ou 9). Si vous ne le faites pas, vous risquez de subir des pertes de données si les disques sont requalifiés.

.Avant de commencer
* Vous devez connaître l'ID de clé pour la clé d'authentification utilisée par le lecteur.
* Vous devez être un administrateur de cluster pour effectuer cette tâche.


.Étapes
. Vérifiez que le disque a été marqué défectueux :
+
`storage disk show -broken`

+
Pour en savoir plus, `storage disk show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-show.html["Référence de commande ONTAP"^].

+
[listing]
----
cluster1::> storage disk show -broken
Original Owner: cluster1-01
  Checksum Compatibility: block
                                                                 Usable Physical
    Disk   Outage Reason HA Shelf Bay Chan   Pool  Type    RPM     Size     Size
    ------ ---- ------------ ---- --- ---- ------ -----  -----  -------  -------
    0.0.0  admin  failed  0b    1   0    A  Pool0  FCAL  10000  132.8GB  133.9GB
    0.0.7  admin  removed 0b    2   6    A  Pool1  FCAL  10000  132.8GB  134.2GB
[...]
----
. Retirez le disque défectueux et remplacez-le par un nouveau lecteur FIPS ou SED, en suivant les instructions du guide matériel de votre modèle de tiroir disque.
. Attribuez la propriété du disque récemment remplacé :
+
`storage disk assign -disk disk_name -owner node`

+
Pour en savoir plus, `storage disk assign` consultez le link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-assign.html["Référence de commande ONTAP"^].

+
[listing]
----
cluster1::> storage disk assign -disk 2.1.1 -owner cluster1-01
----
. Vérifiez que le nouveau disque a été affecté :
+
`storage encryption disk show`

+
Pour en savoir plus, `storage encryption disk show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html["Référence de commande ONTAP"^].

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
0.0.1   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
1.10.0  data F1CB30AFF1CB30B00101000000000000CF0EFD81EA9F6324EA97B369351C56AC
1.10.1  data F1CB30AFF1CB30B00101000000000000CF0EFD81EA9F6324EA97B369351C56AC
2.1.1   open 0x0
[...]
----
. Attribuez les clés d'authentification des données au lecteur FIPS ou SED.
+
link:assign-authentication-keys-seds-external-task.html["Attribution d'une clé d'authentification de données à un lecteur FIPS ou SED (gestion de clés externe)"]

. Si nécessaire, attribuez une clé d'authentification FIPS 140-2 au lecteur FIPS.
+
link:assign-fips-140-2-authentication-key-task.html["Attribution d'une clé d'authentification FIPS 140-2 à un lecteur FIPS"]


