---
permalink: encryption-at-rest/rotate-authentication-keys-nse-task.html 
sidebar: sidebar 
keywords: rotating, authentication, keys, netapp, storage, encryption 
summary: 'Vous pouvez faire tourner les clés d"authentification lorsque vous utilisez NetApp Storage Encryption (NSE).' 
---
= Rotation des clés d'authentification pour NetApp Storage Encryption
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez faire tourner les clés d'authentification lorsque vous utilisez NetApp Storage Encryption (NSE).

.Description de la tâche
La rotation des clés d'authentification dans un environnement NSE est prise en charge si vous utilisez External Key Manager (KMIP).

[NOTE]
====
La rotation des clés d'authentification dans un environnement NSE n'est pas prise en charge pour Onboard Key Manager (OKM).

====
.Étapes
. Utilisez le `security key-manager create-key` commande permettant de générer de nouvelles clés d'authentification.
+
Vous devez générer de nouvelles clés d'authentification avant de pouvoir modifier les clés d'authentification.

. Utilisez le `storage encryption disk modify -disk * -data-key-id` commande pour modifier les clés d'authentification.

