---
permalink: encryption-at-rest/unencrypt-volume-data-task.html 
sidebar: sidebar 
keywords: unencrypting, volume, data 
summary: Vous pouvez utiliser la commande volume Move start pour déplacer et déchiffrer les données de volume. 
---
= Déchiffrement des données de volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `volume move start` commande pour déplacer et annuler le chiffrement des données de volume.

.Avant de commencer
Vous devez être un administrateur de cluster pour effectuer cette tâche. Vous pouvez également être un administrateur SVM auquel l'administrateur du cluster a délégué des pouvoirs. Pour plus d'informations, voir link:delegate-volume-encryption-svm-administrator-task.html["Autorité déléguée pour exécuter la commande volume Move"].

.Étapes
. Déplacer un volume chiffré existant sans chiffrer les données sur le volume :
+
`volume move start -vserver _SVM_name_ -volume volume_name -destination-aggregate _aggregate_name_ -encrypt-destination false`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
La commande suivante déplace un volume existant nommé `vol1` vers l'agrégat de destination `aggr3` et déchiffre les données sur le volume :

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol1 -destination-aggregate aggr3 -encrypt-destination false
----
+
Le système supprime la clé de cryptage du volume. Les données du volume sont non chiffrées.

. Vérifiez que le volume est désactivé pour le chiffrement :
+
`volume show -encryption`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
La commande suivante indique si les volumes sont présents `cluster1` sont chiffrées :

+
[listing]
----
cluster1::> volume show -encryption

Vserver  Volume   Aggregate   State    Encryption State
-------  ------   ---------   -----    ----------------
vs1      vol1     aggr1       online   none
----

