---
permalink: ndmp/enable-node-scoped-ndmp-cluster-task.html 
sidebar: sidebar 
keywords: enable, node, scope, ndmp, cluster 
summary: 'Vous pouvez configurer node-scoped NDMP en activant node-scoped NDMP sur le cluster et le service NDMP sur tous les nœuds du cluster. On doit également configurer l"utilisateur root pour NDMP lors de l"activation du service NDMP.' 
---
= Activez NDMP node-scoped sur le cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez sauvegarder des volumes hébergés sur un seul nœud en activant NDMP node-scoped, en activant le service NDMP et en configurant une LIF pour la connexion data et contrôle. Cela peut être effectué pour tous les nœuds du cluster.


NOTE: Le protocole NDMP avec étendue du nœud est obsolète dans ONTAP 9.

.Description de la tâche
Si vous utilisez NDMP en mode node-scope, l'authentification doit être configurée sur la base de chaque nœud. Pour plus d'informations, voir link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/NDMP/How_to_configure_NDMP_authentication_in_the_%E2%80%98node-scope%E2%80%99_mode["L'article de la base de connaissances "Comment configurer l'authentification NDMP en mode 'node-scope'""^].

.Étapes
. Activer le mode NDMP node-scoped :
+
[source, cli]
----
cluster1::> system services ndmp node-scope-mode on
----
+
NDMP node-scope-mode est activé.

. Activer le service NDMP sur tous les nœuds du cluster :
+
L'utilisation du caractère générique "`*`" permet le service NDMP sur tous les nœuds en même temps.

+
Vous devez spécifier un mot de passe pour l'authentification de la connexion NDMP par l'application de backup.

+
[source, cli]
----
cluster1::> system services ndmp on -node *
----
+
[listing]
----
Please enter password:
Confirm password:
2 entries were modified.
----
. Désactivez le `-clear-text` Option pour la communication sécurisée du mot de passe NDMP :
+
Utilisation du caractère générique "`*`" disables the `-clear-text` option sur tous les nœuds simultanément.

+
[source, cli]
----
cluster1::> system services ndmp modify -node * -clear-text false
----
. Vérifiez que le service NDMP est activé et que `-clear-text` l'option est désactivée :
+
[source, cli]
----
cluster1::> system services ndmp show
----
+
[listing]
----
Node                  Enabled   Clear text  User Id
--------------------- --------- ----------- ---------
cluster1-1            true      false        root
cluster1-2            true      false        root
2 entries were displayed.
----

