---
permalink: ndmp/enable-svm-scoped-ndmp-cluster-task.html 
sidebar: sidebar 
keywords: enable, svm, scope, ndmp, cluster 
summary: 'Si le DMA prend en charge l"extension Cluster Aware Backup (CAB), vous pouvez sauvegarder tous les volumes hébergés sur différents nœuds d"un cluster en activant SVM-scoped NDMP, en activant le service NDMP sur le cluster (admin SVM) et en configurant les LIF de données et de contrôle.' 
---
= Activer SVM-scoped NDMP sur le cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si le DMA prend en charge l'extension Cluster Aware Backup (CAB), vous pouvez sauvegarder tous les volumes hébergés sur différents nœuds d'un cluster en activant SVM-scoped NDMP, en activant le service NDMP sur le cluster (admin SVM) et en configurant les LIF de données et de contrôle.

.Ce dont vous avez besoin
L'extension CAB doit être prise en charge par le DMA.

.Description de la tâche
La désactivation du mode node-scoped NDMP permet d'activer le mode SVM-scoped NDMP sur le cluster.

.Étapes
. Activer le mode NDMP SVM-scoped :
+
[source, cli]
----
cluster1::> system services ndmp node-scope-mode off
----
+
Le mode NDMP SVM-scoped est activé.

. Activer le service NDMP sur le SVM d'admin:
+
[source, cli]
----
cluster1::> vserver services ndmp on -vserver cluster1
----
+
Le type d'authentification est défini sur `challenge` par défaut, l'authentification en texte brut est désactivée.

+
[NOTE]
====
Pour des communications sécurisées, vous devez maintenir l'authentification en texte brut désactivée.

====
. Vérifier que le service NDMP est activé :
+
[source, cli]
----
cluster1::> vserver services ndmp show
----
+
SVM type d'authentification activé
-------------- -------- --------------------
cluster 1 vrai à relever
vs1 faux à relever



[listing]
----

// 2024 Feb 23, GitIssue 1258
// 2024 Feb 09, ONTAPDOC 1629
// 2022-Oct-05, BURT 1430459
----