---
permalink: ndmp/index.html 
sidebar: sidebar 
keywords: decide, ndmp, configuration, network, data, management, protocol, backup, back up 
summary: 'Vous pouvez rapidement configurer un cluster ONTAP 9 de sorte qu"il utilise le protocole NDMP (Network Data Management Protocol) pour sauvegarder les données directement sur bande à l"aide d"une application de sauvegarde tierce.' 
---
= Présentation de la configuration NDMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez rapidement configurer un cluster ONTAP 9 de sorte qu'il utilise le protocole NDMP (Network Data Management Protocol) pour sauvegarder les données directement sur bande à l'aide d'une application de sauvegarde tierce.

Configurer NDMP dans les cas suivants :

* Le cluster exécute ONTAP 9.
* Vous disposez d'une application de sauvegarde tierce (également appelée Data Management application ou DMA).
* Vous êtes un administrateur de cluster.
* Vous souhaitez effectuer des opérations de sauvegarde au niveau du cluster (via la SVM) ou au niveau des nœuds.
* Les périphériques de bande et un serveur multimédia en option sont installés.
* Les périphériques de bande sont connectés au cluster via un commutateur Fibre Channel (FC) et ne sont pas directement connectés.
* Au moins une unité de bande a un numéro d'unité logique (LUN) de 0.


link:../tape-backup/index.html["Protection des données par sauvegarde sur bandes"].
