---
permalink: consistency-groups/clone-task.html 
sidebar: sidebar 
keywords: consistency groups, consistency group, clone 
summary: Depuis la version ONTAP 9.12.1, vous pouvez cloner un groupe de cohérence pour créer une copie de la configuration et des volumes du groupe de cohérence. 
---
= Cloner un groupe de cohérence
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis la version ONTAP 9.12.1, vous pouvez cloner un groupe de cohérence pour créer une copie du groupe de cohérence et de son contenu. Le clonage d'un groupe de cohérence crée une copie de la configuration de groupe de cohérence, de ses métadonnées telles que le type d'application, et de tous les volumes et leur contenu tels que les fichiers, les répertoires, les LUN ou les espaces de noms NVMe.

.Description de la tâche
Lors du clonage d'un groupe de cohérence, vous pouvez le cloner avec la configuration en cours, mais avec le contenu des volumes tel qu'il est ou basé sur un snapshot de groupe de cohérence existant.

Le clonage d'un groupe de cohérence est pris en charge uniquement pour l'ensemble du groupe de cohérence. Vous ne pouvez pas cloner un groupe de cohérence enfant individuel dans une relation hiérarchique : seule la configuration complète des groupes de cohérence peut être clonée.

Lorsque vous clonez un groupe de cohérence, les composants suivants ne sont pas clonés :

* IGroups
* Mappages de LUN
* Sous-systèmes NVMe
* Mappages de sous-systèmes d'espace de noms NVMe


.Avant de commencer
* Lorsque vous clonez un groupe de cohérence, ONTAP ne crée pas de partages SMB pour les volumes clonés si aucun nom de partage n'est spécifié. * Les groupes de cohérence clonés ne sont pas montés si aucun chemin de jonction n'est spécifié.
* Si vous tentez de cloner un groupe de cohérence à partir d'un snapshot qui ne reflète pas les volumes constituants actuels du groupe de cohérence, l'opération échoue.
* Une fois que vous avez cloné un groupe de cohérence, vous devez effectuer l'opération de mappage appropriée.
+
Reportez-vous à la section xref:../task_san_map_igroups_to_multiple_luns.html[Mappez les igroups sur plusieurs LUN] ou xref:../san-admin/map-nvme-namespace-subsystem-task.html[Mappez un namespace NVMe à un sous-système] pour en savoir plus.

* Le clonage d'un groupe de cohérence n'est pas pris en charge pour un groupe de cohérence dans une relation de synchronisation active SnapMirror ou avec des volumes DP associés.


[role="tabbed-block"]
====
.System Manager
--
.Étapes
. Sélectionnez *stockage > groupes de cohérence*.
. Sélectionnez le groupe de cohérence à cloner dans le menu *Groupe de cohérence*.
. En haut à droite de la page de présentation du groupe de cohérence, sélectionnez *Clone*.
. Indiquez un nom pour le nouveau groupe de cohérence cloné ou acceptez le nom par défaut.
+
.. Choisissez si vous souhaitez activer link:../concepts/thin-provisioning-concept.html["*Provisionnement fin*"^].
.. Choisissez *Split Clone* si vous souhaitez dissocier le groupe de cohérence de sa source et allouer de l'espace disque supplémentaire au groupe de cohérence cloné.


. Pour cloner le groupe de cohérence dans son état actuel, choisissez *Ajouter une nouvelle copie Snapshot*.
+
Pour cloner le groupe de cohérence en fonction d'un snapshot, choisissez *utiliser un snapshot existant*. La sélection de cette option ouvre un nouveau sous-menu. Choisissez le snapshot que vous souhaitez utiliser comme base pour l'opération de clonage.

. Sélectionnez *Clone*.
. Retournez au menu *Groupe de cohérence* pour confirmer que votre groupe de cohérence a été cloné.


--
.CLI
--
Depuis la version ONTAP 9.14.1, vous pouvez cloner un groupe de cohérence à l'aide de l'interface de ligne de commandes et des informations d'identification d'administrateur du cluster.

.Avant de commencer
* Vous devez avoir le niveau de privilège admin pour effectuer cette tâche.
* À partir d' ONTAP 9.15.1, tout utilisateur disposant de privilèges d'administrateur peut effectuer cette tâche. Dans ONTAP 9.14.1, vous devez être administrateur de cluster ou de SVM pour effectuer cette tâche.


.Cloner un groupe de cohérence
.  `consistency-group clone create`La commande clone le groupe de cohérence à l'état instantané actuel. Pour baser l'opération de clonage sur un snapshot, incluez le `-source-snapshot` paramètre.
+
`consistency-group clone create -vserver _svm_name_ -consistency-group _clone_name_ -source-consistency-group _consistency_group_name_ [-source-snapshot _snapshot_name_]`

+
Pour en savoir plus, `consistency-group clone create` consultez le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=consistency-group+clone+create["Référence de commande ONTAP"^].



--
====
.Étapes suivantes
* xref:../task_san_map_igroups_to_multiple_luns.html[Mappez les igroups sur plusieurs LUN]
* xref:../san-admin/map-nvme-namespace-subsystem-task.html[Mappez un namespace NVMe à un sous-système]

