---
sidebar: sidebar 
permalink: concept_nas_provision_overview.html 
keywords: netapp, ontap, provisioning, nas, overview, provision NAS storage, manage NAS services, NAS file service, Linux client, Windows client, NAS multiprotocol, name service, name service switch, NFS, SMB, DNS, LDAP, NIS, Kerberos security, export, share, qtree, name mapping, NAS data service 
summary: ONTAP vous permet de transmettre des données aux clients Linux et Windows de façon simple, sécurisée et efficace. 
---
= Présentation de la gestion NAS avec System Manager
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les rubriques de cette section vous expliquent comment configurer et gérer les environnements NAS avec System Manager dans ONTAP 9.7 et versions ultérieures.

Si vous utilisez System Manager classique (disponible uniquement dans ONTAP 9.7 et versions antérieures), reportez-vous aux rubriques suivantes :

* https://docs.netapp.com/us-en/ontap-sm-classic/nfs-config/index.html["Présentation de la configuration NFS"^]
* https://docs.netapp.com/us-en/ontap-sm-classic/smb-config/index.html["Présentation de la configuration SMB"^]


System Manager prend en charge les flux de production pour :

* Configuration initiale des clusters que vous prévoyez d'utiliser pour les services de fichiers NAS.
* Provisionnement de volumes supplémentaire pour répondre à l'évolution des besoins de stockage.
* Configuration et maintenance pour les installations de sécurité et d'authentification standard.


System Manager vous permet de gérer les services NAS au niveau des composants :

* Protocoles : NFS, SMB ou les deux (NAS multiprotocole)
* Services de noms : DNS, LDAP et NIS
* Nommer le commutateur de service
* Sécurité Kerberos
* Exportations et partages
* Qtrees
* Mappage des noms des utilisateurs et des groupes

