---
sidebar: sidebar 
permalink: concept_administration_overview.html 
keywords: netapp, system manager, ontap, administration, overview, cluster, node, local tier, aggregate, svm, storage vm, service level, volume, qtree, LUN, automatic aggregate selection, vserver, protocol, quota, disk, HA pair, dashboard, subnet, domain, interface, mirroring, vaulting, storage, html5 
summary: 'System Manager vous permet de gérer les systèmes et les objets de stockage et d"effectuer des tâches de gestion courantes associées aux systèmes de stockage à partir d"un navigateur Web.' 
---
= Présentation de l'administration avec System Manager
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
System Manager est une interface graphique de gestion basée sur HTML5 qui vous permet d'utiliser un navigateur Web pour gérer les systèmes et objets de stockage (tels que les disques, les volumes et les niveaux de stockage) et d'effectuer des tâches de gestion courantes liées aux systèmes de stockage.

Les procédures de cette section vous aident à gérer votre cluster avec System Manager dans ONTAP 9.7 et versions ultérieures.

[NOTE]
====
* System Manager est inclus dans le logiciel ONTAP en tant que service Web, activé par défaut et accessible via un navigateur.
* Le nom de System Manager a été modifié depuis ONTAP 9.6. Dans ONTAP 9.5 et versions antérieures, il s'appelait OnCommand System Manager. Depuis ONTAP 9.6 et versions ultérieures, il s'appelle System Manager.
* Si vous utilisez le Gestionnaire système classique (disponible uniquement dans ONTAP 9.7 et versions antérieures), reportez-vous à la section  https://docs.netapp.com/us-en/ontap-system-manager-classic/index.html["System Manager Classic (ONTAP 9.0 à 9.7)"^]


====
Grâce au tableau de bord de System Manager, vous pouvez afficher des informations d'un coup d'œil sur les alertes et notifications importantes, sur l'efficacité et la capacité des tiers et volumes de stockage, sur les nœuds disponibles dans un cluster, sur l'état des nœuds d'une paire haute disponibilité, sur les applications et objets les plus actifs, et les metrics de performance d'un cluster ou d'un nœud.

System Manager vous permet d'effectuer plusieurs tâches courantes, telles que :

* Création d'un cluster, configuration d'un réseau et configuration des détails de support du cluster.
* Configurer et gérer les objets de stockage, tels que les disques, les niveaux locaux, les volumes, les qtrees et quotas.
* Configurez des protocoles, tels que SMB et NFS, et provisionnez le partage de fichiers.
* Configurez les protocoles, tels que FC, FCoE, NVMe et iSCSI, pour l'accès au bloc.
* Créez et configurez des composants réseau, tels que des sous-réseaux, des domaines de diffusion, des interfaces de données et de gestion, et des groupes d'interfaces.
* Configuration et gestion de la mise en miroir et des relations à l'archivage.
* Exécutez les opérations de gestion des clusters, de gestion des nœuds de stockage et des machines virtuelles de stockage (VM).
* Créez et configurez des VM de stockage, gérez les objets de stockage associés aux VM de stockage et gérez les services de VM de stockage.
* Contrôle et gestion des configurations haute disponibilité (HA) dans un cluster.
* Configurez les processeurs de service pour connecter, gérer, surveiller et administrer le nœud à distance, quel que soit l'état du nœud.




== Terminologie de System Manager

System Manager utilise une terminologie différente de celle de l'interface de ligne de commandes pour certaines fonctionnalités de clés ONTAP.

* *Local Tier* – ensemble de disques SSD physiques ou de disques durs sur lequel vous stockez vos données. On peut les connaître comme des agrégats. En fait, si vous utilisez l'interface de ligne de commande ONTAP, vous verrez toujours le terme _aggrer_ utilisé pour représenter un niveau local.
* *Tier cloud* – stockage dans le cloud utilisé par ONTAP lorsque vous souhaitez placer certaines données hors site pour l'une des raisons suivantes. Si vous pensez à la partie Cloud d'un FabricPool, vous l'avez déjà défigurée. Et si vous utilisez un système StorageGRID, il est possible que votre cloud ne soit pas hors site du tout. (Une expérience sur site similaire à celle du cloud est appelée « cloud privé ».)
* *Storage VM* – machine virtuelle fonctionnant sous ONTAP qui fournit des services de stockage et de données à vos clients. Vous pouvez le connaître comme _SVM_ ou _vserver_.
* *Interface réseau* - adresse et propriétés affectées à un port réseau physique.  Vous pouvez le connaître comme une _interface logique (LIF)_.
* *Pause* - une action qui interrompt les opérations.  Avant ONTAP 9.8, vous avez peut-être fait référence à _quiesce_ dans d'autres versions de System Manager.

