---
sidebar: sidebar 
permalink: concept-svm-admin-dashboard-sm.html 
keywords: netapp, system manager, ontap, administration, overview, svm, storage vm, volume, vserver, dashboard, administrator, tenant, multi-tenancy, protocol, network interface, performance, learn 
summary: 'Les administrateurs de SVM peuvent surveiller et gérer leurs propres SVM à l"aide d"un tableau de bord System Manager dédié. Ceci est particulièrement utile dans un environnement ONTAP mutualisé, où l"administrateur du cluster peut fournir un tableau de bord SVM à chaque locataire.' 
---
= Découvrez le tableau de bord administrateur SVM d'ONTAP System Manager
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
À partir d'ONTAP 9.19.1, les administrateurs de SVM peuvent surveiller et gérer leurs SVM à l'aide d'un tableau de bord System Manager dédié et de la page Stockage > Volumes. Ceci est particulièrement utile dans un environnement ONTAP mutualisé, où l'administrateur du cluster peut fournir un tableau de bord SVM pour chaque locataire.

L'administrateur du cluster fournit les identifiants de connexion aux administrateurs SVM. Les administrateurs SVM peuvent consulter les détails et les performances sur le tableau de bord SVM et la page *Stockage > Volumes*. Le tableau de bord affiche les protocoles SVM, les interfaces réseau, les détails et les indicateurs de performance. La page Volumes fournit des informations sur les volumes SVM et, si cela est autorisé par l'administrateur du cluster, la possibilité pour l'administrateur SVM d'ajouter de nouveaux volumes.

.Et ensuite
link:task-assign-svm-admin-access-sm.html["Attribuez un accès d'administrateur SVM avec ONTAP System Manager"]
