---
settings:
  name: ONTAP 9
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  search: ontap, ontap-metrocluster, ontap-sm-classic, ontap-fli, ontap-automation,
    ontap-cli-9131
  langs: fr-fr,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,it-it
sidebar:
  entries:
  - title: Documentation ONTAP
    url: "/index.html"
  - title: Notes de version
    url: "/release-notes.html"
  - title: Intégration de System Manager à BlueXP
    url: "/sysmgr-integration-bluexp-concept.html"
  - section: introduction-concepts
  - section: setup-upgrade
  - section: cluster-admin
  - section: volume-admin
  - section: network-management
  - section: nas-management
  - section: san-management
  - section: object-storage-management
  - section: security-encryption
  - section: data-protection-disaster-recovery
  - section: event-performance-monitoring
  - title: Pages de manuel ONTAP
    url: "/concepts/manual-pages.html"
  - title: Mentions légales
    url: "/reference_legal_notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
  sidebar_label: Toute la documentation sur les produits ONTAP
