---
sidebar: sidebar 
permalink: sysmgr-integration-bluexp-concept.html 
keywords: netapp, ontap, system manager, experience, integrate, integration, bluexp, hybrid, cloud, dashboard, multicloud 
summary: 'À partir de ONTAP 9.12.1, System Manager est entièrement intégré à BlueXP.  BlueXP vous permet de gérer votre infrastructure multicloud hybride à partir d"un seul plan de contrôle tout en conservant le tableau de bord familier de System Manager.' 
---
= Intégration de System Manager à BlueXP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
À partir de ONTAP 9.12.1, System Manager est entièrement intégré à BlueXP.  BlueXP vous permet de gérer votre infrastructure multicloud hybride à partir d'un seul plan de contrôle tout en conservant le tableau de bord familier de System Manager.



== Présentation de l'intégration

Lorsque vous accédez à System Manager sur un cluster ONTAP sur site exécutant ONTAP 9.12.1 ou version ultérieure avec connectivité au service BlueXP, vous êtes invité à gérer le cluster directement à partir de BlueXP. Depuis BlueXP, vous aurez accès à l'interface System Manager à laquelle vous êtes habitué, ainsi qu'à la fonctionnalité BlueXP.

BlueXP vous permet de créer et de gérer le stockage cloud (par exemple Cloud Volumes ONTAP), d'utiliser les services de données NetApp (par exemple, Cloud Backup) et de contrôler de nombreux périphériques de stockage sur site et périphériques.



== Gérez vos clusters ONTAP à partir de BlueXP

Lorsque vous êtes prêt à gérer vos clusters ONTAP à partir de BlueXP, vous pouvez suivre le lien qui apparaît lorsque vous essayez d'accéder à System Manager ou vous pouvez vous rendre directement à BlueXP. Aller directement à BlueXP offre un avantage, si vous souhaitez utiliser les services de données de BlueXP pour sauvegarder des données, analyser et catégoriser vos données, et plus encore.



=== Utilisez le lien de System Manager

Lorsque vous vous connectez à l’interface réseau de gestion de cluster à partir de votre navigateur Web, vous serez invité à gérer le cluster avec System Manager dans BlueXP ou à utiliser System Manager directement. Pour utiliser System Manager dans BlueXP, effectuez les opérations suivantes :

.Étapes
. Ouvrez un navigateur Web et entrez l'adresse IP de l'interface réseau de gestion du cluster.
+
Si le cluster est connecté à BlueXP, une invite de connexion s'affiche.

. Cliquez sur *Continuer vers BlueXP* pour suivre le lien vers BlueXP.
. Sur la page de connexion BlueXP, sélectionnez *Connectez-vous avec vos informations d'identification du site de support NetApp* et saisissez vos identifiants.
+
Si vous avez déjà utilisé BlueXP et que vous disposez d’une connexion à l’aide d’un e-mail et d’un mot de passe, vous devez continuer à utiliser cette option de connexion.

+
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html["En savoir plus sur la connexion à BlueXP"^].

. Si vous y êtes invité, entrez un nom pour votre nouveau compte BlueXP.
+
Dans la plupart des cas, BlueXP crée automatiquement un compte pour vous en fonction des données de votre cluster.

. Saisissez les informations d'identification de l'administrateur du cluster pour le cluster.


.Résultat
System Manager s'affiche et vous pouvez désormais gérer le cluster depuis BlueXP.



=== Découvrez vos clusters directement à partir de BlueXP

BlueXP offre deux façons de découvrir et de gérer vos clusters :

* Détection directe pour la gestion via System Manager
+
Il s'agit de la même option de découverte décrite dans la section précédente avec laquelle vous suivez la redirection.

* Découverte via un connecteur
+
Ce connecteur est un logiciel installé dans votre environnement qui vous permet d'accéder aux fonctions de gestion via System Manager. Il permet également d'accéder aux services cloud BlueXP qui offrent des fonctionnalités telles que la réplication, la sauvegarde et la restauration, le classement des données, le Tiering des données, etc.



Accédez au https://docs.netapp.com/us-en/cloud-manager-family/index.html["Documentation BlueXP"^] pour en savoir plus sur ces options de découverte et de gestion.



== En savoir plus sur BlueXP

* https://docs.netapp.com/us-en/cloud-manager-family/concept-overview.html["Présentation de BlueXP"^]
* https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/index.html["Gérez vos systèmes NetApp AFF et FAS à l'aide de BlueXP"^]

