---
sidebar: sidebar 
permalink: task_admin_monitor_capacity_in_sm.html 
keywords: used storage, local tier capacity, aggregate capacity, add capacity, used capacity, available capacity, total capacity, inactive data, overprovision, overflows, snapshot copy reserves, reserves, clone, maximum capacity limit, storage VM, allocated 
summary: System Manager vous permet de surveiller la capacité de stockage utilisée et la quantité disponible pour un cluster, un niveau local ou une machine virtuelle de stockage. 
---
= Contrôle de la capacité dans System Manager
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
System Manager vous permet de surveiller la capacité de stockage utilisée et la quantité disponible pour un cluster, un niveau local ou une machine virtuelle de stockage.

À chaque version d'ONTAP, System Manager fournit des informations plus fiables sur le contrôle de la capacité :

* Depuis ONTAP 9.10.1, System Manager vous permet de consulter l'historique des données sur la capacité du cluster, ainsi que des prévisions sur la capacité qui sera utilisée ou disponible à l'avenir. Vous pouvez également surveiller la capacité des niveaux et volumes locaux.
* À partir de ONTAP 9.12.1, System Manager affiche la quantité de capacité allouée pour un niveau local.
* À partir de ONTAP 9.13.1, vous pouvez activer une limite de capacité maximale pour une machine virtuelle de stockage et définir un seuil pour déclencher des alertes lorsque le stockage utilisé atteint un certain pourcentage de la capacité maximale.



NOTE: Les mesures de la capacité utilisée s'affichent différemment en fonction de la version de ONTAP utilisée.  Pour en savoir plus, consultez link:./concepts/capacity-measurements-in-sm-concept.html["Mesures de la capacité dans System Manager"].



== Afficher la capacité d'un cluster

Vous pouvez afficher les mesures de capacité d'un cluster sur le tableau de bord dans System Manager.

.Avant de commencer
Pour afficher les données relatives à la capacité dans le cloud, vous devez disposer d'un compte Active IQ Digital Advisor et être connecté.

.Étapes
. Dans System Manager, cliquez sur *Dashboard*.
. Dans la section *capacité*, vous pouvez afficher les éléments suivants :
+
--
** Capacité totale utilisée du cluster
** Capacité totale disponible du cluster
** Pourcentages de capacité utilisée et disponible.
** Ratio de réduction des données.
** Capacité utilisée dans le cloud.
** Historique de l'utilisation de la capacité.
** Projection de l'utilisation de la capacité


--
+

NOTE: Dans System Manager, les représentations de capacité ne prennent pas en compte les capacités du niveau de stockage racine (agrégat).

. Cliquez sur le graphique pour afficher plus de détails sur la capacité du cluster.
+
Les mesures de capacité sont indiquées dans deux graphiques à barres :

+
--
** Le graphique supérieur affiche la capacité physique : la taille de l'espace physique utilisé, réservé et disponible.
** Le graphique inférieur affiche la capacité logique : la taille des données client, les copies Snapshot et les clones, ainsi que l'espace logique total utilisé.


--
+
Les mesures de réduction des données se trouvent sous les graphiques à barres :

+
--
** Taux de réduction des données pour les données clients uniquement (les copies Snapshot et les clones ne sont pas inclus).
** Ratio global de réduction des données.


--


Pour plus d'informations, voir link:./concepts/capacity-measurements-in-sm-concept.html["Mesures de la capacité dans System Manager"].



== Afficher la capacité d'un niveau local

Vous pouvez afficher des informations détaillées sur la capacité des niveaux locaux.  À partir de ONTAP 9.12.1, la vue *capacité* inclut également la quantité de capacité allouée pour un niveau local, ce qui vous permet de déterminer si vous devez ajouter de la capacité au niveau local pour prendre en charge la capacité allouée et éviter de manquer d'espace libre.

.Étapes
. Cliquez sur *stockage > niveaux*.
. Sélectionnez le nom du niveau local.
. Sur la page *Présentation*, dans la section *capacité*, la capacité est indiquée dans un graphique à barres avec trois mesures :
+
** Capacité utilisée et réservée
** Capacité disponible
** Capacité dédiée (à partir de ONTAP 9.12.1)


. Cliquez sur le tableau pour afficher des détails sur la capacité du niveau local.
+
Les mesures de capacité sont indiquées dans deux graphiques à barres :

+
--
** Le graphique à barres du haut affiche la capacité physique : la taille de l'espace physique utilisé, réservé et disponible.
** La barre du bas affiche la capacité logique : la taille des données client, des copies Snapshot et des clones, ainsi que l'espace total logique utilisé.


--
+
Les graphiques à barres ci-dessous sont des rapports de mesure pour la réduction des données :

+
--
** Taux de réduction des données pour les données clients uniquement (les copies Snapshot et les clones ne sont pas inclus).
** Ratio global de réduction des données.


--


Pour plus d'informations, voir link:./concepts/capacity-measurements-in-sm-concept.html["Mesures de la capacité dans System Manager"].

.Actions facultatives
* Si la capacité engagée est supérieure à la capacité du niveau local, vous pouvez envisager d'ajouter de la capacité au niveau local avant qu'il ne manque d'espace libre.  Voir link:./disks-aggregates/add-disks-local-tier-aggr-task.html["Ajout de capacité à un niveau local (ajout de disques à un agrégat)"].
* Vous pouvez également afficher le stockage utilisé par des volumes spécifiques dans le niveau local en sélectionnant l'onglet *volumes*.




== Affichez la capacité des volumes d'une VM de stockage

Vous pouvez afficher la quantité de stockage utilisée par les volumes d'une VM de stockage et la capacité disponible.  La mesure totale du stockage utilisé et disponible est appelée « capacité sur tous les volumes ».

.Étapes
. Sélectionnez *stockage* > *machines virtuelles de stockage*.
. Cliquez sur le nom de la machine virtuelle de stockage.
. Accédez à la section *capacité*, qui affiche un graphique à barres avec les mesures suivantes :
+
--
** *Physique utilisée* : somme du stockage physique utilisé sur tous les volumes de cette VM de stockage.
** *Disponible* : somme de la capacité disponible sur tous les volumes de cette VM de stockage.
** *Logique utilisée* : somme du stockage logique utilisé sur tous les volumes de cette machine virtuelle de stockage.


--


Pour plus de détails sur les mesures, voir link:./concepts/capacity-measurements-in-sm-concept.html["Mesures de la capacité dans System Manager"].



== Afficher la limite de capacité maximale d'une machine virtuelle de stockage

À partir de ONTAP 9.13.1, vous pouvez afficher la limite de capacité maximale d'une machine virtuelle de stockage.

.Avant de commencer
Vous devez link:manage-max-cap-limit-svm-in-sm-task.html["Limite de capacité maximale d'une machine virtuelle de stockage"] avant de pouvoir l'afficher.

.Étapes
. Sélectionnez *stockage* > *machines virtuelles de stockage*.
+
Vous pouvez afficher les mesures de capacité maximale de deux manières :

+
--
** Dans la ligne de la machine virtuelle de stockage, affichez la colonne *capacité maximale* qui contient un graphique à barres indiquant la capacité utilisée, la capacité disponible et la capacité maximale.
** Cliquez sur le nom de la VM de stockage. Dans l'onglet *vue d'ensemble*, faites défiler pour afficher les valeurs de seuil de capacité maximale, de capacité allouée et d'alerte de capacité dans la colonne de gauche.


--


.Informations associées
* link:manage-max-cap-limit-svm-in-sm-task.html#edit-max-cap-limit-svm["Modifiez la limite de capacité maximale d'une machine virtuelle de stockage"]
* link:./concepts/capacity-measurements-in-sm-concept.html["Mesures de la capacité dans System Manager"]

