---
sidebar: sidebar 
permalink: task_metrocluster_troubleshooting.html 
keywords: system manager, troubleshoot, error, event, problem, metrocluster, maintenance, fix, correction, health, check 
summary: 'Vous pouvez basculer d"un site MetroCluster à l"autre pour effectuer des opérations de maintenance et de restauration suite à un problème.' 
---
= Résolution des problèmes liés aux configurations IP MetroCluster
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Depuis ONTAP 9.8, System Manager surveille l'intégrité des configurations IP MetroCluster et vous aide à identifier et à corriger les problèmes potentiels.



== Présentation de la vérification de l'état du système MetroCluster

System Manager vérifie régulièrement l'état de santé de votre configuration IP MetroCluster.  Lorsque vous affichez la section MetroCluster du tableau de bord, le message généralement « les systèmes MetroCluster sont sains ».

Cependant, lorsqu'un problème se produit, le message indique le nombre d'événements. Vous pouvez cliquer sur ce message et afficher les résultats de la vérification de l'état des composants suivants :

* Nœud
* Interface réseau
* Niveau (stockage)
* Cluster
* Connexion
* Volumétrie
* Réplication de la configuration


La colonne *Status* identifie les composants qui présentent des problèmes et la colonne *Details* indique comment corriger le problème.



== Dépannage de MetroCluster

.Étapes
. Dans System Manager, sélectionnez *Dashboard*.
. Dans la section *MetroCluster*, notez le message.
+
.. Si le message indique que la configuration de votre MetroCluster est correcte et que les connexions entre les clusters et le médiateur ONTAP sont en bon état (avec des cases à cocher), alors vous n'avez aucun problème à corriger.
.. Si le message indique le nombre d'événements, ou si les connexions ont diminué (indiqué par un « X »), passez à l'étape suivante.


. Cliquez sur le message indiquant le nombre d'événements.
+
Le rapport d'intégrité MetroCluster s'affiche.

. Dépanner les problèmes qui apparaissent dans le rapport en utilisant les suggestions dans la colonne *Détails*.
. Lorsque tous les problèmes ont été corrigés, cliquez sur *vérifier l'état de santé du MetroCluster*.
+

NOTE: La vérification de l'état de santé MetroCluster utilise une quantité importante de ressources. Il est donc recommandé d'effectuer toutes vos tâches de dépannage avant d'exécuter la vérification.

+
La vérification de l'état de santé de MetroCluster s'exécute en arrière-plan.  Vous pouvez travailler sur d'autres tâches pendant que vous attendez la fin.


