---
sidebar: sidebar 
permalink: task_nas_monitor_nfs_active_clients.html 
keywords: netapp, ontap, nfs, active clients 
summary: System Manager indique les connexions client NFS actives lorsque NFS est sous licence sur un cluster 
---
= Surveillance des clients NFS actifs
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Depuis ONTAP 9.8, System Manager affiche les connexions client NFS actives lorsque NFS est sous licence sur un cluster.

Vous pouvez ainsi vérifier rapidement quels clients NFS sont activement connectés à une machine virtuelle de stockage, qui est connectée mais inactive et qui sont déconnectés.

Pour chaque adresse IP de client NFS, l'affichage *NFS clients* indique :
* Heure du dernier accès
* Adresse IP de l'interface réseau
* Version de connexion NFS
* Nom de la VM de stockage

En outre, une liste de clients NFS actifs au cours des 48 dernières heures est également affichée dans l'affichage *Storage> volumes* et un nombre de clients NFS est inclus dans l'affichage *Dashboard*.

.Étape
. Afficher l'activité client NFS : cliquez sur *hôtes > clients NFS*.

