---
sidebar: sidebar 
permalink: task_admin_recover_deleted_volumes.html 
keywords: netapp, ontap, administration, recover, recovering, recovery, deleted, undelete, volume, volumes, recover deleted volume, SVM, storage VM, vserver, FlexVol volume, purging volume, volume retention time, deleting a volume 
summary: Si vous avez supprimé par erreur un ou plusieurs volumes FlexVol, vous pouvez restaurer ces volumes. Vous pouvez également supprimer les volumes de manière permanente en les purgeant. 
---
= Restaurer les volumes supprimés
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Si vous avez supprimé par erreur un ou plusieurs volumes FlexVol, vous pouvez utiliser System Manager pour restaurer ces volumes. Depuis ONTAP 9.8, vous pouvez également utiliser System Manager pour restaurer des volumes FlexGroup. Vous pouvez également supprimer les volumes de manière permanente en les purgeant.

La durée de conservation des volumes peut être définie au niveau des VM de stockage. Par défaut, la durée de rétention du volume est définie sur 12 heures.



== Sélection de volumes supprimés

.Étapes
. Cliquez sur *Storage > volumes*.
. Cliquez sur *plus > Afficher les volumes supprimés*.
. Sélectionnez les volumes et cliquez sur l'action souhaitée pour récupérer ou supprimer définitivement les volumes.




== Réinitialisation des configurations de volume

La suppression d'un volume supprime les configurations associées du volume. La récupération d'un volume ne réinitialise pas toutes les configurations. Effectuez les tâches suivantes manuellement après la restauration d'un volume pour rétablir son état d'origine :

.Étapes
. Renommez le volume.
. Configurez un chemin de jonction (NAS).
. Créez des mappages pour les LUN dans le volume (SAN).
. Associer une policy Snapshot et export policy avec le volume.
. Ajouter de nouvelles règles de politique de quotas pour le volume.
. Ajoutez une règle QoS pour le volume.

