---
sidebar: sidebar 
permalink: task_metrocluster_setup.html 
keywords: system manager, metrocluster, set up, setup, start, initialize, cluster, config, nodes 
summary: Depuis ONTAP 9.8, vous pouvez utiliser System Manager pour configurer une configuration IP sur un site MetroCluster. 
---
= Configurer un site IP MetroCluster
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Depuis ONTAP 9.8, vous pouvez utiliser System Manager pour configurer une configuration IP sur un site MetroCluster.

Un site MetroCluster se compose de deux clusters. En règle générale, les clusters se trouvent dans des emplacements géographiques différents.

.Avant de commencer
* Votre système doit déjà être installé et câblé conformément au https://["Instructions d'installation et de configuration"^] fourni avec le système.
* Les interfaces réseau de clusters doivent être configurées sur chaque nœud de chaque cluster pour des communications intra-cluster.




== Attribuez une adresse IP de gestion des nœuds



=== Système Windows

Vous devez connecter votre ordinateur Windows au même sous-réseau que les contrôleurs. L'adresse IP de gestion des nœuds sera automatiquement attribuée à votre système.

.Étapes
. À partir du système Windows, ouvrez le lecteur *réseau* pour découvrir les nœuds.
. Double-cliquez sur le nœud pour lancer l'assistant de configuration du cluster.




=== Autres systèmes

Vous devez configurer l'adresse IP node-management pour l'un des nœuds du cluster. Vous pouvez utiliser cette adresse IP node-management pour lancer l'assistant de configuration des clusters.

Voir link:./software_setup/task_create_the_cluster_on_the_first_node.html["Création du cluster sur le premier node"] Pour plus d'informations sur l'attribution d'une adresse IP de gestion des nœuds.



== Initialiser et configurer le cluster

Vous initialisez le cluster en définissant un mot de passe administratif pour le cluster et en configurant les réseaux de gestion du cluster et de gestion des nœuds. Vous pouvez également configurer des services tels qu'un serveur DNS pour résoudre les noms d'hôtes et un serveur NTP pour synchroniser l'heure.

.Étapes
. Dans un navigateur Web, saisissez l'adresse IP de gestion des nœuds que vous avez configurée : "https://[]
+
System Manager détecte automatiquement les nœuds restants dans le cluster.

. Dans la fenêtre *Initialize Storage System*, effectuez les opérations suivantes :
+
.. Saisissez les données de configuration du réseau de gestion du cluster.
.. Entrez les adresses IP de gestion des nœuds pour tous les nœuds.
.. Indiquez les détails des serveurs de noms de domaine (DNS).
.. Dans la section *autre*, cochez la case *utiliser le service de temps (NTP)* pour ajouter les serveurs de temps.




Lorsque vous cliquez sur *Submit*, attendez que le cluster soit créé et configuré. Ensuite, un processus de validation a lieu.

.Et la suite ?
Une fois les deux clusters configurés, initialisés et configurés, effectuez la procédure suivante :

* link:task_metrocluster_peering.html["Configuration du peering de MetroCluster IP"]




== Configurez ONTAP sur une nouvelle vidéo de cluster

video::PiX41bospbQ[youtube,width=848,height=480]