---
sidebar: sidebar 
permalink: task-svm-admin-dashboard-sm.html 
keywords: netapp, system manager, ontap, administration, svm, storage vm, volume, vserver, dashboard, administrator, tenant, multi-tenancy, protocol, network interface, performance 
summary: 'Les administrateurs de cluster peuvent accorder à leurs administrateurs SVM l"accès nécessaire pour surveiller et gérer les SVM. Les administrateurs SVM peuvent surveiller et gérer les SVM avec le tableau de bord d"administrateur SVM dans ONTAP System Manager.' 
---
= Gérez et surveillez les SVM ONTAP avec System Manager
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
À partir d'ONTAP 9.19.1, les administrateurs SVM peuvent surveiller et gérer leurs propres SVM à l'aide d'un tableau de bord System Manager dédié.

.Avant de commencer
Votre administrateur du cluster doit vous fournir :

* Adresse IP de gestion du SVM
* Identifiants (nom d'utilisateur et mot de passe) pour le tableau de bord SVM System Manager (l'utilisateur vsadmin doit être déverrouillé)
* En option, autorisations pour ajouter des volumes sur la SVM


.Étapes
. Saisissez l'adresse IP de gestion du SVM dans un navigateur.
. Saisissez votre nom d'utilisateur et votre mot de passe pour l'administrateur SVM (vsadmin).
. Sélectionnez *Sign in*.
+
Le tableau de bord ONTAP System Manager s'ouvre.

. Vous pouvez consulter les informations suivantes concernant la SVM :
+
[cols="1,2"]
|===
| Informations sur les SVM | Description 


| Protocoles | Les protocoles activés sur la SVM. 


| Détails | Informations NIS et LDAP, langue et période de conservation après la suppression d'un volume. 


| Performance | Statistiques de performance en termes de latence, d'IOPS et de débit par heure, jour, semaine, mois ou année pour le protocole sélectionné. 
|===
. Vous pouvez également télécharger les données dans un fichier CSV (valeurs séparées par des virgules) pour une analyse plus approfondie.
. Sélectionnez *stockage > volumes*.
+
La page du tableau de bord Volumes s'ouvre.

+
L'administrateur du cluster peut vous autoriser à ajouter des volumes à la SVM. Si cette autorisation n'est pas accordée, la sélection du bouton *Ajouter* échoue et un message d'erreur s'affiche.



.Informations associées
* link:concepts/cluster-svm-administrators-concept.html["Administration des clusters et des SVM"]
* link:task_cp_dashboard_tour.html#performance["Découvrez la gestion des clusters sur les tableaux de bord ONTAP System Manager (section Performances)"]
* link:volumes/manage-volumes-task.html["Gérer les volumes ONTAP avec System Manager"]

