---
sidebar: sidebar 
permalink: task_san_configure_protection_for_business_continuity.html 
keywords: netapp, ontap, System Manager, LUNs, source cluster, protect, protection, storage VM, volume, volumes, source, destination, cluster, IOPS activity 
summary: 'La configuration de la protection pour la continuité de l"activité implique de sélectionner des LUN sur le cluster ONTAP source et de les ajouter à un groupe de cohérence. Ouvrez System Manager à partir d"un navigateur sur le cluster source pour commencer à configurer la protection des activités de continuité.' 
---
= Configuration de la protection pour la continuité de l'activité
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
La configuration de la protection pour la continuité de l'activité implique de sélectionner des LUN sur le cluster ONTAP source et de les ajouter à un groupe de cohérence. Ouvrez System Manager à partir d'un navigateur sur le cluster source pour commencer à configurer la protection des activités de continuité.

Ce flux de travail est conçu pour ONTAP 9.8 et 9.9. À partir de ONTAP 9.10.1, il est recommandé de commencer par créer un groupe de cohérence, puis d'utiliser SM-BC comme protection à distance.



== Description de la tâche

* Les LUN doivent résider sur la même machine virtuelle de stockage.
* Les LUN peuvent résider sur des volumes différents.
* Le cluster source et le cluster destination ne peuvent pas être identiques.
* L'IPspace par défaut est requis par SM-BC pour les relations cluster peer-to-peer. L'IPspace personnalisé n'est pas pris en charge.


.Étapes
. Choisissez les LUN que vous souhaitez protéger et ajoutez-les à un groupe de protection : *protection > Présentation > protéger pour la continuité de l'activité > protéger les LUN*.
. Sélectionnez une ou plusieurs LUN à protéger sur le cluster source.
. Sélectionner le cluster de destination et le SVM.
. *Initialize relation* est sélectionné par défaut. Cliquez sur *Save* pour commencer la protection.
. Accédez à *Tableau de bord > performances* pour vérifier l'activité IOPS des LUN.
. Sur le cluster de destination, utilisez System Manager pour vérifier que la protection de la relation de continuité de l'activité est en mode synchrone : *protection > relations*.

