---
sidebar: sidebar 
permalink: task_admin_add_nodes_to_cluster.html 
keywords: cluster expansion, add nodes, adding nodes, node join, expand cluster, add nodes to cluster, increase cluster size, increate cluster capabilities, cluster expansion, cluster configuration 
summary: Vous pouvez augmenter la taille et les fonctionnalités de votre cluster en ajoutant de nouveaux nœuds. 
---
= Ajout de nœuds au cluster
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Vous pouvez augmenter la taille et les fonctionnalités de votre cluster en ajoutant de nouveaux nœuds.

.Avant de commencer
Vous devriez déjà avoir câblé les nouveaux nœuds au cluster.

Il existe des processus distincts pour travailler avec System Manager dans ONTAP 9.7 ou ONTAP 9.8.

* <<add-nodes-cluster-97,Ajout de nœuds à un cluster avec System Manager (ONTAP 9.7)>>
* <<add-nodes-cluster-98,Ajout de nœuds à un cluster avec System Manager (ONTAP 9.8)>>




== Ajout de nœuds à un cluster avec System Manager (ONTAP 9.7)

.Étapes
. Cliquez sur * (revenir à la version classique)*.
. Cliquez sur *configurations > extension de cluster*.
+
System Manager détecte automatiquement les nouveaux nœuds.

. Cliquez sur *basculer vers la nouvelle expérience*.
. Cliquez sur *Cluster > Présentation* pour afficher les nouveaux nœuds.




== Ajout de nœuds à un cluster avec System Manager (ONTAP 9.8)

.Étapes
. Sélectionnez *Cluster > Présentation*.
+
Les nouveaux contrôleurs s'affichent sous forme de nœuds connectés au réseau du cluster, mais ils ne se trouvent pas dans le cluster.

. Cliquez sur *Ajouter*.
+
** Les nœuds sont ajoutés au cluster.
** Le stockage est alloué implicitement.



