---
sidebar: sidebar 
permalink: task_admin_view_submit_support_cases.html 
keywords: support, case, view, submit, active iq, telemetry, log, logging 
summary: Depuis la version ONTAP 9.9.1, vous pouvez consulter les dossiers de demande de support Active IQ associés au cluster et afficher les informations nécessaires pour ouvrir un nouveau dossier de demande de support. Depuis ONTAP 9.10.1, vous pouvez activer la journalisation de télémétrie et aider le personnel de support à résoudre les problèmes. 
---
= Consultation et envoi des dossiers de demande de support
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Depuis la version ONTAP 9.9.1, vous pouvez consulter les dossiers de support Active IQ associés au cluster. Vous pouvez également copier les informations relatives au cluster dont vous avez besoin pour créer un nouveau dossier de demande de support sur le site de support NetApp.
Depuis ONTAP 9.10.1, vous pouvez activer la journalisation de télémétrie et aider le personnel de support à résoudre les problèmes.


NOTE: Pour recevoir des alertes relatives aux mises à jour de firmwares, vous devez être enregistré auprès de Active IQ Unified Manager. Reportez-vous à la section link:https://netapp.com/support-and-training/documentation/active-iq-unified-manager["Ressources de documentation Active IQ Unified Manager"^].

.Étapes
. Dans System Manager, sélectionnez *support*.
+
La liste des dossiers de demande de support ouverts associés à ce cluster s'affiche.

. Cliquez sur les liens suivants pour effectuer les procédures :
+
** *Numéro de cas*: Voir détails sur le cas.
** *Accédez au site de support NetApp* : accédez à la page *My AutoSupport* du site de support NetApp pour consulter les articles de la base de connaissances ou ouvrir un nouveau dossier de support.
** *Afficher mes dossiers de demande de support* : accédez à la page *Mes dossiers de demande de support* sur le site de support NetApp.
** *Afficher les détails du cluster* : affichez et copiez les informations nécessaires lorsque vous soumettez un nouveau dossier.






== Activez la journalisation de télémétrie

Depuis ONTAP 9.10.1, vous pouvez utiliser System Manager pour activer la journalisation de télémétrie.  Lorsque la journalisation de télémétrie est autorisée, un identificateur de télémétrie spécifique indique le processus exact qui a déclenché le message dans les messages consignés par System Manager.  Tous les messages émis relatifs à ce processus ont le même identifiant, qui se compose du nom du workflow opérationnel et d'un nombre (par exemple « add-volume-1941290 »).

Si vous rencontrez des problèmes de performances, vous pouvez activer la journalisation de télémétrie, ce qui permet au personnel de support d'identifier plus facilement le processus spécifique pour lequel un message a été émis.  Lorsque des identifiants de télémétrie sont ajoutés aux messages, le fichier journal n'est que légèrement agrandi.

.Étapes
. Dans System Manager, sélectionnez *Cluster > Paramètres*.
. Dans la section *Paramètres d'interface utilisateur*, cochez la case *Autoriser la journalisation de télémétrie*.

