---
sidebar: sidebar 
permalink: task_admin_monitor_risks.html 
keywords: system manager, monitor, risk, risks, suggestion, suggestions, mitigate, active iq, category, categories, mitigation, impact, impacts, corrections, corrective action, corrective actions, acknowledge risk, dismiss, undismiss, restore, unacknowledge 
summary: Si vous utilisez System Manager avec ONTAP 9.10.0 ou une version ultérieure, vous pouvez surveiller les risques signalés par le conseiller digital Active IQ. 
---
= Surveiller les risques
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Depuis ONTAP 9.10.0, System Manager permet de surveiller les risques signalés par le conseiller digital Active IQ.  Depuis ONTAP 9.10.1, vous pouvez utiliser System Manager pour prendre en compte les risques.

Le conseiller digital NetApp Active IQ crée des opportunités de réduction des risques et d'amélioration des performances et de l'efficacité de votre environnement de stockage.  Avec System Manager, vous découvrez les risques signalés par Active IQ et bénéficiez d'informations exploitables pour la gestion du stockage, une disponibilité accrue, une sécurité renforcée et des performances de stockage supérieures.



== Lien vers votre compte Active IQ

Pour recevoir des informations sur les risques Active IQ, vous devez d'abord créer un lien vers votre compte Active IQ de System Manager.

.Étapes
. Dans System Manager, cliquez sur *Cluster > Paramètres*.
. Sous *Active IQ Registration*, cliquez sur *Register*.
. Saisissez vos identifiants pour Active IQ.
. Une fois vos informations d'identification authentifiées, cliquez sur *confirmer pour lier Active IQ à System Manager*.




== Afficher le nombre de risques

Depuis ONTAP 9.10.0, vous pouvez consulter le tableau de bord dans System Manager le nombre de risques signalé par Active IQ.

.Avant de commencer
Vous devez établir une connexion depuis System Manager vers votre compte Active IQ.  Reportez-vous à la section <<link_active_iq,Lien vers votre compte Active IQ>>.

.Étapes
. Dans System Manager, cliquez sur *Dashboard*.
. Dans la section *Santé*, consultez le nombre de risques signalés.
+

NOTE: Vous pouvez afficher des informations plus détaillées sur chaque risque en cliquant sur le message indiquant le nombre de risques.  Voir <<view_risk_details,Afficher les détails des risques>>.





== Afficher les détails des risques

Depuis ONTAP 9.10.0, vous pouvez visualiser dans System Manager la façon dont les risques signalés par Active IQ sont classés par zone d'impact.  Vous pouvez également consulter des informations détaillées sur chaque risque signalé, son impact potentiel sur votre système et les actions correctives que vous pouvez prendre.

.Avant de commencer
Vous devez établir une connexion depuis System Manager vers votre compte Active IQ.  Reportez-vous à la section <<link_active_iq,Lien vers votre compte Active IQ>>.

.Étapes
. Cliquez sur *Evénements > tous les événements*.
. Dans la section *Aperçu*, sous *suggestions de Active IQ*, consultez le nombre de risques dans chaque catégorie de zone d'impact.  Les catégories de risque sont les suivantes :
+
** Performances et efficacité
** Disponibilité et protection des données
** Puissance
** Configuration
** Sécurité


. Cliquez sur l'onglet *suggestions* de Active IQ pour afficher des informations sur chaque risque, notamment :
+
** Niveau d'impact sur votre système
** Catégorie du risque
** Nœuds affectés
** Type d'atténuation nécessaire
** Actions correctives possibles






== Reconnaître les risques

À partir de ONTAP 9.10.1, vous pouvez utiliser System Manager pour prendre en compte les risques ouverts.

.Étapes
. Dans System Manager, affichez la liste des risques en exécutant la procédure dans <<view_risk_details,Afficher les détails des risques>>.
. Cliquez sur le nom du risque d'un risque ouvert que vous souhaitez reconnaître.
. Entrez les informations dans les champs suivants :
+
** Rappel (date)
** Justification
** Commentaires


. Cliquez sur *Acknowledge*.
+

NOTE: Une fois que vous avez reconnu un risque, ce changement ne prend que quelques minutes et se reflète dans la liste des suggestions de Active IQ.





== Prendre en compte les risques

Depuis ONTAP 9.10.1, vous pouvez utiliser System Manager pour annuler le risque reconnu précédemment.

.Étapes
. Dans System Manager, affichez la liste des risques en exécutant la procédure dans <<view_risk_details,Afficher les détails des risques>>.
. Cliquez sur le nom du risque d'un risque reconnu que vous souhaitez annuler.
. Entrez les informations dans les champs suivants :
+
** Justification
** Commentaires


. Cliquez sur *UnAcknowledge*.
+

NOTE: Une fois que vous reconnaissez un risque, ce changement prend quelques minutes. Il faut que ce changement soit reflété dans la liste des suggestions de Active IQ.


