---
permalink: element-replication/create-relationship-element-destination-task.html 
sidebar: sidebar 
keywords: create, relationship, ontap, source, element, destination, snapshot, snap shot, lun, migrate, data, snap mirror, snapmirror, replicate, replication 
summary: 'Depuis ONTAP 9.4, vous pouvez utiliser SnapMirror pour répliquer les copies Snapshot d"un LUN créé sur une source ONTAP et les renvoyer vers une destination Element. Il est possible d"utiliser le LUN pour migrer les données d"ONTAP vers le logiciel Element.' 
---
= Création d'une relation entre une source ONTAP et une destination Element
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis ONTAP 9.4, vous pouvez utiliser SnapMirror pour répliquer les copies Snapshot d'un LUN créé sur une source ONTAP et les renvoyer vers une destination Element. Il est possible d'utiliser le LUN pour migrer les données d'ONTAP vers le logiciel Element.

.Avant de commencer
* Le nœud de destination de l'élément doit avoir été accessible à ONTAP.
* Le volume Element doit avoir été activé pour la réplication SnapMirror.


Vous devez spécifier le chemin de destination de l'élément dans le formulaire `_hostip:_/lun/_name_`, où « lun » est la chaîne réelle « lun » et `name` Est le nom du volume Element.

Les règles de réplication sont les suivantes :

* La relation de réplication doit avoir une règle de type « async-mirror ».
+
Vous pouvez utiliser une stratégie par défaut ou personnalisée.

* Seules les LUN iSCSI sont prises en charge.
* Vous ne pouvez pas répliquer plusieurs LUN depuis un volume ONTAP vers un volume Element.
* Vous ne pouvez pas répliquer un LUN depuis un volume ONTAP vers plusieurs volumes Element.


.Étape
. Créer une relation de réplication depuis une source ONTAP vers une destination Element :
+
`snapmirror create -source-path _SVM:volume_|_cluster://SVM/volume_ -destination-path _hostip:_/lun/_name_ -type XDP -schedule schedule -policy _policy_`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant illustre la création d'une relation SnapMirror DR à l'aide de la valeur par défaut `MirrorLatest` règle :

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm_1:volA_dst -destination-path 10.0.0.11:/lun/0005 -type XDP -schedule my_daily -policy MirrorLatest
----
+
L'exemple suivant illustre la création d'une relation SnapMirror DR à l'aide de la commande personnalisée `my_mirror` règle :

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm_1:volA_dst -destination-path 10.0.0.11:/lun/0005 -type XDP -schedule my_daily -policy my_mirror
----


Utilisez le `snapmirror show` Commande permettant de vérifier que la relation SnapMirror a été créée. Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.
