---
permalink: element-replication/index.html 
sidebar: sidebar 
keywords: decide, replication, netapp element software, ontap, business continuity, element, system, snapmirror, replicate, snapshot, copies, volume 
summary: 'Pour assurer la continuité de l"activité sur les systèmes Element, utilisez SnapMirror pour répliquer les copies Snapshot d"un volume Element vers une destination ONTAP.' 
---
= Réplication entre le logiciel NetApp Element et ONTAP en vue d'ensemble
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour assurer la continuité de l'activité sur les systèmes Element, utilisez SnapMirror pour répliquer les copies Snapshot d'un volume Element vers une destination ONTAP. En cas d'incident au niveau du système Element, vous pouvez délivrer les données aux clients via le système ONTAP, puis réactiver ce système une fois que le service est restauré.

Depuis ONTAP 9.4, vous pouvez répliquer les copies Snapshot d'une LUN créée sur un nœud ONTAP et les renvoyer dans un système Element. Vous pouvez avoir créé une LUN en cas de panne sur le site Element ou utiliser un LUN pour migrer les données d'un système ONTAP vers le logiciel Element.

link:https://docs.netapp.com/us-en/element-software/storage/concept_snapmirror_overview.html["Configurer la réplication du logiciel NetApp Element et de ONTAP"^].
