---
permalink: tape-backup/add-drives-libraries-concept.html 
sidebar: sidebar 
keywords: add, tape, drives, libraries, storage, system 
summary: 'Vous pouvez ajouter des lecteurs de bandes et des bibliothèques au système de stockage de façon dynamique (sans mettre le système de stockage hors ligne).' 
---
= Découvrez comment ajouter des lecteurs de bande et des bibliothèques aux systèmes de stockage ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez ajouter des lecteurs de bandes et des bibliothèques au système de stockage de façon dynamique (sans mettre le système de stockage hors ligne).

Lorsque vous ajoutez un nouveau chargeur de support, le système de stockage détecte sa présence et l'ajoute à la configuration. Si le chargeur de support est déjà référencé dans les informations d'alias, aucun nouveau nom logique n'est créé. Si la bibliothèque n'est pas référencée, le système de stockage crée un nouvel alias pour le changeur de support.

Dans une configuration de librairie de bandes, vous devez configurer un lecteur de bande ou un changeur de support sur la LUN 0 d'un port cible pour ONTAP afin de détecter tous les changeurs de support et lecteurs de bande sur ce port cible.
