---
permalink: tape-backup/assign-tape-aliases-concept.html 
sidebar: sidebar 
keywords: aliasing, ppn, physical, path, name, sn, serial, number, medium, changer, alias, name 
summary: 'Le crénelage simplifie le processus d"identification du dispositif. Le crénelage lie un nom de chemin physique (PPN) ou un numéro de série (SN) d"une bande ou d"un changeur de support à un nom d"alias persistant mais modifiable.' 
---
= Présentation de l'alias de bande
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le crénelage simplifie le processus d'identification du dispositif. Le crénelage lie un nom de chemin physique (PPN) ou un numéro de série (SN) d'une bande ou d'un changeur de support à un nom d'alias persistant mais modifiable.

Le tableau suivant décrit comment le repliement de bande vous permet de vous assurer qu'un lecteur de bande (ou une bibliothèque de bandes ou un changeur de support) est toujours associé à un nom d'alias unique :

|===
| Scénario | Réaffectation de l'alias 


 a| 
Lorsque le système redémarre
 a| 
Le lecteur de bande est automatiquement réaffecté à son alias précédent.



 a| 
Lorsqu'un périphérique de bande se déplace vers un autre port
 a| 
L'alias peut être réglé pour pointer vers la nouvelle adresse.



 a| 
Lorsque plusieurs systèmes utilisent un lecteur de bande particulier
 a| 
L'utilisateur peut définir l'alias de manière à ce qu'il soit identique pour tous les systèmes.

|===
[NOTE]
====
Lorsque vous effectuez une mise à niveau de Data ONTAP 8.1.x vers Data ONTAP 8.2.x, la fonction d'alias de bande de Data ONTAP 8.2.x modifie les noms d'alias de bande existants. Dans ce cas, vous devrez peut-être mettre à jour les noms d'alias de bande dans l'application de sauvegarde.

====
L'attribution d'alias de bande fournit une correspondance entre les noms logiques des périphériques de sauvegarde (par exemple st0 ou mc1) et un nom attribué de façon permanente à un port, un lecteur de bande ou un chargeur de support.

[NOTE]
====
st0 et st00 sont des noms logiques différents.

====
[NOTE]
====
Les noms logiques et les numéros de série sont utilisés uniquement pour accéder à un périphérique. Une fois le périphérique accédé, il renvoie tous les messages d'erreur en utilisant le nom du chemin physique.

====
Il existe deux types de noms disponibles pour le changement de dénomination : le nom du chemin physique et le numéro de série.



== En savoir plus sur les noms de chemins physiques

Les noms de chemin physique (PPN) sont les séquences d'adresses numériques que ONTAP attribue aux lecteurs de bande et aux bibliothèques de bandes en fonction de l'adaptateur ou du commutateur SCSI-2/3 (emplacement spécifique) qu'ils sont connectés au système de stockage. Les noms PPN sont également appelés noms électriques.

Les PPN des périphériques connectés directement utilisent le format suivant : `host_adapter`. `device_id_lun`

[NOTE]
====
La valeur LUN s'affiche uniquement pour les unités de bande et de changeur de support dont les valeurs LUN ne sont pas nulles, c'est-à-dire si la valeur LUN est zéro `lun` Une partie du PPN n'est pas affichée.

====
Par exemple, le PPN 8.6 indique que le numéro de l'adaptateur hôte est 8, que l'ID du périphérique est 6 et que le numéro de l'unité logique (LUN) est 0.

Les lecteurs de bande SAS sont également des périphériques à connexion directe. Par exemple, le PPN 5c.4 indique que dans un système de stockage, l'adaptateur HBA SAS est connecté à l'emplacement 5, la bande SAS est connectée au port C de l'adaptateur HBA SAS et l'ID du périphérique est 4.

Les PPN des périphériques connectés par commutateur Fibre Channel utilisent le format suivant : `switch:port_id`. `device_id_lun`

Par exemple, le PPN MY_SWITCH:5.3L2 indique que le lecteur de bande connecté au port 5 d'un commutateur appelé MY_SWITCH est défini avec l'ID de périphérique 3 et possède la LUN 2.

La LUN (numéro d'unité logique) est déterminée par le lecteur. Les bibliothèques et lecteurs de bande SCSI, Fibre Channel et les disques possèdent des PPN.

Les PPN des lecteurs de bande et des bibliothèques ne changent pas, sauf si le nom du commutateur change, que le lecteur de bande ou la bibliothèque se déplace ou que le lecteur de bande ou la bibliothèque est reconfiguré. Les PPN restent inchangés après le redémarrage. Par exemple, si un lecteur de bande nommé MY_SWITCH:5.3L2 est retiré et qu'un nouveau lecteur de bande avec le même ID de périphérique et le même LUN est connecté au port 5 du commutateur MY_SWITCH, le nouveau lecteur de bande sera accessible à l'aide DE MY_SWITCH:5.3L2.



== En savoir plus sur les numéros de série

Un numéro de série (SN) est un identifiant unique pour un lecteur de bande ou un chargeur de support. ONTAP génère des alias basés sur SN à la place du WWN.

Comme le SN est un identifiant unique pour un lecteur de bande ou un chargeur de support, l'alias reste le même quel que soit le chemin de connexion multiple vers le lecteur de bande ou le changeur de support. Les systèmes de stockage peuvent ainsi suivre le même lecteur de bande ou le même changeur de support dans une configuration de librairie de bandes.

Le numéro de série d'un lecteur de bande ou d'un changeur de support ne change pas même si vous renommez le commutateur Fibre Channel auquel le lecteur de bande ou le changeur de support est connecté. Toutefois, dans une bibliothèque de bandes, si vous remplacez un lecteur de bandes existant par un nouveau, ONTAP génère de nouveaux alias car le numéro de série du lecteur de bande change. De même, si vous déplacez un lecteur de bande existant dans un nouveau slot dans une librairie de bandes ou si vous remappage le LUN du lecteur de bande, ONTAP génère un nouvel alias pour ce lecteur de bande.

[NOTE]
====
Vous devez mettre à jour les applications de sauvegarde avec les alias nouvellement générés.

====
Le numéro de série d'un périphérique à bande utilise le format suivant : `SN[xxxxxxxxxx]L[X]`

`x` Est un caractère alphanumérique et un caractère L``X`` Est le LUN du périphérique de bande. Si le LUN est 0, le L``X`` une partie de la chaîne n'est pas affichée.

Chaque numéro de série comprend jusqu'à 32 caractères ; le format du numéro de série n'est pas sensible à la casse.
