---
permalink: tape-backup/availability-volumes-tapes-backup-restore-lif-reference.html 
sidebar: sidebar 
keywords: lif, availability, volumes, tape, devices, backup, restore, types, cab, extension, application 
summary: 'Vous pouvez configurer une application de backup pour établir une connexion de contrôle NDMP sur l"un des types LIF d"un cluster. En mode NDMP (SVM)-scoped, il est possible de déterminer la disponibilité des volumes et des dispositifs à bandes pour les opérations de backup et restore, selon ces types de LIF et le statut de l"extension CAB.' 
---
= Disponibilité de volumes et de bandes pour les sauvegardes et les restaurations sur différents types de LIF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer une application de backup pour établir une connexion de contrôle NDMP sur l'un des types LIF d'un cluster. En mode NDMP (SVM)-scoped, il est possible de déterminer la disponibilité des volumes et des dispositifs à bandes pour les opérations de backup et restore, selon ces types de LIF et le statut de l'extension CAB.

Les tableaux suivants montrent la disponibilité des volumes et des dispositifs à bande pour les types LIF de connexion de contrôle NDMP et le statut de l'extension CAB :



== Disponibilité des volumes et des dispositifs à bande lorsque l'extension CAB n'est pas prise en charge par l'application de sauvegarde

|===
| Type LIF de connexion de contrôle NDMP | Volumes disponibles pour la sauvegarde ou la restauration | Périphériques à bande disponibles pour la sauvegarde ou la restauration 


 a| 
LIF node-management
 a| 
Tous volumes hébergés par un nœud
 a| 
Dispositifs de bande connectés au nœud hébergeant la LIF de node-management



 a| 
LIF de données
 a| 
Seuls les volumes qui appartiennent au SVM hébergé par un nœud qui héberge la LIF de données
 a| 
Aucune



 a| 
LIF Cluster-management
 a| 
Tous les volumes hébergés par un nœud qui héberge la LIF de cluster-management
 a| 
Aucune



 a| 
FRV InterCluster
 a| 
Tous les volumes hébergés par un nœud qui héberge le LIF intercluster
 a| 
Périphériques de bande connectés au nœud hébergeant le LIF intercluster

|===


== Disponibilité des volumes et des dispositifs à bande lorsque l'extension CAB est prise en charge par l'application de sauvegarde

|===
| Type LIF de connexion de contrôle NDMP | Volumes disponibles pour la sauvegarde ou la restauration | Périphériques à bande disponibles pour la sauvegarde ou la restauration 


 a| 
LIF node-management
 a| 
Tous volumes hébergés par un nœud
 a| 
Dispositifs de bande connectés au nœud hébergeant la LIF de node-management



 a| 
LIF de données
 a| 
Tous les volumes qui appartiennent au SVM qui héberge la LIF de données
 a| 
Aucune



 a| 
LIF Cluster-management
 a| 
Tous les volumes du cluster
 a| 
Tous les périphériques de bande du cluster



 a| 
FRV InterCluster
 a| 
Tous les volumes du cluster
 a| 
Tous les périphériques de bande du cluster

|===