---
permalink: tape-backup/blocking-factor-concept.html 
sidebar: sidebar 
keywords: blocking, factor, tape, backup, restore, read, write, operation 
summary: 'Un bloc de bandes est de 1,024 octets de données. Lors d"une sauvegarde ou d"une restauration sur bande, vous pouvez spécifier le nombre de blocs de bandes transférés dans chaque opération de lecture/écriture. Ce nombre est appelé facteur de blocage.' 
---
= Quel est le facteur de blocage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un bloc de bandes est de 1,024 octets de données. Lors d'une sauvegarde ou d'une restauration sur bande, vous pouvez spécifier le nombre de blocs de bandes transférés dans chaque opération de lecture/écriture. Ce nombre est appelé le _facteur de blocage_.

Vous pouvez utiliser un facteur de blocage de 4 à 256. Si vous envisagez de restaurer une sauvegarde sur un système autre que celui qui a effectué la sauvegarde, le système de restauration doit prendre en charge le facteur de blocage que vous avez utilisé pour la sauvegarde. Par exemple, si vous utilisez un facteur de blocage de 128, le système sur lequel vous restaurez cette sauvegarde doit prendre en charge un facteur de blocage de 128.

Lors d'une sauvegarde NDMP, LE MOVER_RECORD_SIZE détermine le facteur de blocage. ONTAP autorise une valeur maximale de 256 Ko pour MOVER_RECORD_SIZE.
