---
permalink: tape-backup/common-ndmp-topologies-reference.html 
sidebar: sidebar 
keywords: ndmp, tape, backup, topologies, storage, system, local, data, server 
summary: 'NDMP prend en charge un certain nombre de topologies et de configurations entre les applications de sauvegarde et les systèmes de stockage ou d"autres serveurs NDMP fournissant des données (systèmes de fichiers) et des services de bande.' 
---
= Topologies de sauvegarde sur bande NDMP courantes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NDMP prend en charge un certain nombre de topologies et de configurations entre les applications de sauvegarde et les systèmes de stockage ou d'autres serveurs NDMP fournissant des données (systèmes de fichiers) et des services de bande.



== Du système de stockage sur bande locale

Dans la configuration la plus simple, une application de sauvegarde sauvegarde sauvegarde sauvegarde sauvegarde des données d'un système de stockage vers un sous-système de bande connecté au système de stockage. Il existe une connexion de contrôle NDMP sur la limite du réseau. La connexion de données NDMP qui existe dans le système de stockage entre les services de données et de bande est appelée configuration locale NDMP.



== Système de stockage à bande connecté à un autre système de stockage

Une application de sauvegarde peut également sauvegarder les données d'un système de stockage vers une librairie de bandes (un changeur de moyenne taille avec un ou plusieurs lecteurs de bande) connectée à un autre système de stockage. Dans ce cas, la connexion de données NDMP entre les services de données et de bande est fournie par une connexion réseau TCP ou TCP/IPv6. Il s'agit d'une configuration NDMP à trois voies système de stockage vers stockage.



== Bibliothèque de bandes reliée système/réseau de stockage

Les bibliothèques de bandes NDMP fournissent une variante de la configuration à trois voies. Dans ce cas, la bibliothèque de bandes se connecte directement au réseau TCP/IP et communique avec l'application de sauvegarde et le système de stockage par l'intermédiaire d'un serveur NDMP interne.



== Système de stockage à serveur de données sur bande ou serveur de données à système de stockage sur bande

NDMP prend également en charge les configurations trivoies entre système de stockage à serveur de données et serveur de données à stockage, bien que ces variantes soient moins largement déployées. Le système de stockage à serveur permet de sauvegarder les données du système de stockage dans une bibliothèque de bandes reliée à l'hôte de l'application de sauvegarde ou à un autre système de serveur de données. La configuration du système de serveur à stockage permet de sauvegarder les données du serveur dans une bibliothèque de bandes reliée au système de stockage.
