---
permalink: tape-backup/data-backup-dump-concept.html 
sidebar: sidebar 
keywords: dump, engine, flexvol, volumes, backup, recovery, snapshot, copy, tape, device 
summary: 'Dump est une solution de sauvegarde et de restauration basée sur des copies Snapshot de ONTAP qui vous permet de sauvegarder des fichiers et des répertoires d"une copie Snapshot sur un périphérique de bande et de restaurer les données sauvegardées sur un système de stockage.' 
---
= À propos du moteur de dump pour les volumes FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dump est une solution de sauvegarde et de restauration basée sur des copies Snapshot de ONTAP qui vous permet de sauvegarder des fichiers et des répertoires d'une copie Snapshot sur un périphérique de bande et de restaurer les données sauvegardées sur un système de stockage.

Vous pouvez sauvegarder les données de votre système de fichiers, telles que les répertoires, les fichiers et leurs paramètres de sécurité associés, sur un périphérique de bande à l'aide de la sauvegarde dump. Vous pouvez sauvegarder un volume entier, un qtree entier ou un sous-arbre qui n'est ni un volume entier, ni un qtree entier.

Vous pouvez effectuer une sauvegarde ou une restauration de dump à l'aide d'applications de sauvegarde conformes NDMP.

Lorsque vous effectuez une sauvegarde de dump, vous pouvez spécifier la copie Snapshot à utiliser pour une sauvegarde. Si vous ne spécifiez pas de copie Snapshot pour la sauvegarde, le moteur de dump crée une copie Snapshot pour la sauvegarde. Une fois l'opération de sauvegarde terminée, le moteur de dump supprime cette copie Snapshot.

Vous pouvez effectuer des sauvegardes de niveau 0, incrémentielles ou différentielles sur bande à l'aide du moteur de vidage.

[NOTE]
====
Après avoir revenir à une version antérieure à Data ONTAP 8.3, vous devez effectuer une opération de sauvegarde de base avant d'effectuer une opération de sauvegarde incrémentielle.

====
https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-ug-rdg/home.html["Mise à niveau, rétablissement ou mise à niveau vers une version antérieure"]
