---
permalink: tape-backup/dump-snapmirror-single-file-lun-restore-concept.html 
sidebar: sidebar 
keywords: dump, works, snapmirror, single, file, lun, restore, operation 
summary: 'Avant d"effectuer des sauvegardes de dump ou des opérations de restauration sur un volume sur lequel un fichier ou une LUN unique est restauré à l"aide de la technologie SnapMirror, vous devez comprendre le fonctionnement des opérations de dump avec une seule opération de restauration de fichiers ou de LUN.' 
---
= Fonctionnement de dump avec la restauration de fichiers ou de LUN SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'effectuer des sauvegardes de dump ou des opérations de restauration sur un volume sur lequel un fichier ou une LUN unique est restauré à l'aide de la technologie SnapMirror, vous devez comprendre le fonctionnement des opérations de dump avec une seule opération de restauration de fichiers ou de LUN.

Lors de l'opération de restauration d'un seul fichier ou de LUN SnapMirror, le nombre d'E/S client est limité sur le fichier ou la LUN en cours de restauration. Une fois l'opération de restauration de fichier ou de LUN terminée, la restriction d'E/S sur le fichier ou la LUN est supprimée. Si une sauvegarde de dump est effectuée sur un volume sur lequel un seul fichier ou LUN est restauré, alors le fichier ou la LUN qui a une restriction d'E/S client n'est pas inclus dans la sauvegarde dump. Lors d'une opération de sauvegarde ultérieure, ce fichier ou ce LUN est sauvegardé sur bande après suppression de la restriction d'E/S.

Vous ne pouvez pas effectuer simultanément une restauration de dump et une opération de restauration SnapMirror ou de LUN sur le même volume.
