---
permalink: tape-backup/dump-backup-restore-operations-mcc-config-concept.html 
sidebar: sidebar 
keywords: dump, backup, restore, opartion, metrocluster, configuration, switchback, switchover 
summary: 'Avant d"effectuer les opérations de sauvegarde et de restauration de dump dans une configuration MetroCluster, vous devez en déterminer l"impact des opérations de dump en cas d"opération de basculement ou de rétablissement.' 
---
= Comment les opérations de sauvegarde et de restauration de vidage sont affectées dans une configuration ONTAP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'effectuer les opérations de sauvegarde et de restauration de dump dans une configuration MetroCluster, vous devez en déterminer l'impact des opérations de dump en cas d'opération de basculement ou de rétablissement.



== Vidage de l'opération de sauvegarde ou de restauration suivi du basculement

Envisager deux clusters : cluster 1 et cluster 2. Lors d'une opération de sauvegarde ou de restauration sur le cluster 1, si un basculement est initié du cluster 1 au cluster 2, ce qui suit se produit :

* Si la valeur de `override-vetoes` l'option est `false`, le basculement est alors interrompu et l'opération de sauvegarde ou de restauration se poursuit.
* Si la valeur de l'option est `true`, l'opération de sauvegarde ou de restauration du vidage est alors abandonnée et le basculement se poursuit.




== Vidage de l'opération de sauvegarde ou de restauration, suivi du rétablissement

Un basculement est effectué du cluster 1 vers le cluster 2 et une opération de sauvegarde ou de restauration de « dump » est lancée sur le cluster 2. L'opération de dump sauvegarde ou restaure un volume situé sur le cluster 2. À ce stade, si un rétablissement est initié du cluster 2 au cluster 1, ce qui suit se produit :

* Si la valeur de `override-vetoes` l'option est `false`, le rétablissement est alors annulé et l'opération de sauvegarde ou de restauration se poursuit.
* Si la valeur de l'option est `true`, l'opération de sauvegarde ou de restauration est alors abandonnée et le rétablissement se poursuit.




== Vidage de l'opération de sauvegarde ou de restauration initié lors d'un basculement ou d'un rétablissement

Lors du basculement d'un cluster 1 vers un cluster 2, si une opération de sauvegarde ou de restauration de dump est initiée sur le cluster 1, l'opération de sauvegarde ou de restauration échoue et le basculement se poursuit.

Lors du rétablissement d'un cluster 2 vers le cluster 1, si une opération de sauvegarde ou de restauration de vidage est lancée depuis le cluster 2, l'opération de sauvegarde ou de restauration échoue et le rétablissement se poursuit.
