---
permalink: tape-backup/dump-events-concept.html 
sidebar: sidebar 
keywords: dump, event, field, information, parenthesis, type 
summary: 'Le champ événement d"un événement de vidage contient un type d"événement suivi d"informations spécifiques à un événement entre parenthèses.' 
---
= Quels sont les événements de vidage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le champ événement d'un événement de vidage contient un type d'événement suivi d'informations spécifiques à un événement entre parenthèses.

Le tableau suivant décrit les événements, leurs descriptions et les informations d'événement associées qui peuvent être enregistrées pour une opération de vidage :

|===
| Événement | Description | Informations sur l'événement 


 a| 
Démarrer
 a| 
Le dump NDMP est démarré
 a| 
Niveau de vidage et type de vidage



 a| 
Fin
 a| 
Vidage terminé avec succès
 a| 
Quantité de données traitées



 a| 
Abandonner
 a| 
L'opération est annulée
 a| 
Quantité de données traitées



 a| 
Options
 a| 
Les options spécifiées sont répertoriées
 a| 
Toutes les options et leurs valeurs associées, y compris les options NDMP



 a| 
Tape_open
 a| 
La bande est ouverte en lecture/écriture
 a| 
Nom du nouveau périphérique de bande



 a| 
Tape_close
 a| 
La bande est fermée pour lecture/écriture
 a| 
Nom du lecteur de bande



 a| 
Changement de phase
 a| 
Un vidage entre dans une nouvelle phase de traitement
 a| 
Nom de la nouvelle phase



 a| 
Erreur
 a| 
Un vidage a rencontré un événement inattendu
 a| 
Message d'erreur



 a| 
Snapshot
 a| 
Une copie Snapshot est créée ou située
 a| 
Nom et heure de la copie Snapshot



 a| 
Base_dump
 a| 
Une entrée de vidage de base dans le métafichier interne a été localisée
 a| 
Le niveau et le temps du vidage de la base (pour les vidages incrémentiels uniquement)

|===