---
permalink: tape-backup/dump-storage-failover-arl-operations-concept.html 
sidebar: sidebar 
keywords: dump, workd, storage, failover, arl, operations, override, aggregate, relocation, takeover, giveback, cab, extension 
summary: 'Avant d"effectuer des opérations de sauvegarde et de restauration de type dump, il est important de comprendre le fonctionnement de ces opérations avec les opérations de basculement du stockage (Takeover et giveback) ou de transfert d"agrégats (ARL). L"option -override-vetoes détermine le comportement du moteur de vidage lors d"une opération de basculement de stockage ou d"ARL.' 
---
= Fonctionnement de dump avec les opérations de basculement de stockage et d'ARL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'effectuer des opérations de sauvegarde et de restauration de type dump, il est important de comprendre le fonctionnement de ces opérations avec les opérations de basculement du stockage (Takeover et giveback) ou de transfert d'agrégats (ARL). Le `-override-vetoes` Détermine le comportement du moteur de vidage lors d'une opération de basculement du stockage ou d'ARL.

Lorsqu'une opération de sauvegarde ou de restauration est en cours d'exécution et `-override-vetoes` l'option est définie sur `false`, Un basculement de stockage ou une opération ARL initié par l'utilisateur est arrêté. Cependant, si `–override-vetoes` l'option est définie sur `true`, Le basculement du stockage ou l'opération ARL est ensuite poursuivi et l'opération de sauvegarde ou de restauration de vidage est abandonnée. Lorsqu'une opération de basculement ou d'ARL de stockage est automatiquement lancée par le système de stockage, une opération de sauvegarde ou de restauration des données de dump actif est toujours abandonnée. Vous ne pouvez pas redémarrer les opérations de sauvegarde et de restauration de vidage, même après la fin des opérations de basculement du stockage ou d'ARL.



== Opérations de vidage lorsque l'extension DE CABINE est prise en charge

Si l'application de sauvegarde prend en charge l'extension CAB, vous pouvez continuer à effectuer les opérations de sauvegarde et de restauration incrémentielles sans reconfigurer les règles de sauvegarde après un basculement de stockage ou un transfert d'agrégats.



== Les opérations de vidage lorsque l'extension DE CABINE n'est pas prise en charge

Si l'application de sauvegarde ne prend pas en charge l'extension CAB, vous pouvez continuer d'effectuer les opérations de sauvegarde et de restauration du dump incrémentiel si vous migrez la LIF configurée dans la politique de sauvegarde vers le nœud qui héberge l'agrégat de destination. Sinon, après le basculement du stockage et l'ARL, vous devez effectuer une sauvegarde de base avant d'effectuer l'opération de sauvegarde incrémentielle.

[NOTE]
====
Pour les opérations de basculement du stockage, la LIF configurée dans la stratégie de sauvegarde doit être migrée vers le nœud partenaire.

====
.Informations associées
link:../high-availability/index.html["Haute disponibilité"]
