---
permalink: tape-backup/failed-to-initialize-restore-stream-reference.html 
sidebar: sidebar 
keywords: failed, initialize, restore, stream, smtape, tape, block, factor, corrupt, damaged, wrong 
summary: 'Impossible d"initialiser le flux de restauration.' 
---
= Impossible d'initialiser le flux de restauration
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
* *Message*
+
`Failed to initialize restore stream`

* *Cause*
+
Ce message d'erreur peut s'afficher pour l'une des raisons suivantes :

+
** L'image de sauvegarde n'est pas SMTape.
** Le facteur de blocage de la bande spécifié est incorrect.
** La bande est corrompue ou endommagée.
** La mauvaise bande est chargée pour la restauration.


* * Action corrective*
+
** Si l'image de sauvegarde n'est pas SMTape, essayez de procéder à nouveau à l'opération avec une bande dotée de la sauvegarde SMTape.
** Si le facteur de blocage est incorrect, spécifiez le facteur de blocage correct et relancez l'opération.
** Si la bande est corrompue, vous ne pouvez pas effectuer l'opération de restauration.
** Si la mauvaise bande est chargée, recommencez l'opération avec la bonne bande.



