---
permalink: tape-backup/failed-to-initialize-tape-reference.html 
sidebar: sidebar 
keywords: failed, initialize, tape, smtape, blocking, factor, corrupt, damaged, restore 
summary: 'Impossible d"initialiser la bande.' 
---
= Impossible d'initialiser la bande
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
* *Message*
+
`Failed to initialize tape`

* *Cause*
+
Ce message d'erreur peut s'afficher pour l'une des raisons suivantes :

+
** L'image de sauvegarde n'est pas SMTape.
** Le facteur de blocage de la bande spécifié est incorrect.
** La bande est corrompue ou endommagée.
** La mauvaise bande est chargée pour la restauration.


* * Action corrective*
+
** Si l'image de sauvegarde n'est pas SMTape, essayez de procéder à nouveau à l'opération avec une bande dotée d'une sauvegarde SMTape.
** Si le facteur de blocage est incorrect, spécifiez le facteur de blocage correct et relancez l'opération.
** Si la bande est corrompue, vous ne pouvez pas effectuer l'opération de restauration.
** Si la mauvaise bande est chargée, recommencez l'opération avec la bonne bande.



