---
permalink: tape-backup/manage-svm-scoped-ndmp-mode-concept.html 
sidebar: sidebar 
keywords: manage, svm, scope, ndmp, flexvol, volumes, vserver, modify 
summary: 'Vous pouvez gérer NDMP par SVM en utilisant les options et commandes NDMP. Vous pouvez modifier les options NDMP en utilisant la commande vserver services ndmp modify. En mode SVM-scoped NDMP, l"authentification de l"utilisateur est intégrée au mécanisme de contrôle d"accès basé sur des rôles.' 
---
= Gérer le mode SVM-scoped NDMP pour les volumes FlexVol présentation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez gérer NDMP par SVM en utilisant les options et commandes NDMP. Vous pouvez modifier les options NDMP en utilisant le `vserver services ndmp modify` commande. En mode SVM-scoped NDMP, l'authentification de l'utilisateur est intégrée au mécanisme de contrôle d'accès basé sur des rôles.

Vous pouvez ajouter NDMP dans la liste des protocoles autorisés ou interdits en utilisant le `vserver modify` commande. Par défaut, NDMP se trouve dans la liste des protocoles autorisés. Si NDMP est ajouté à la liste des protocoles interdits, les sessions NDMP ne peuvent pas être établies.

Vous pouvez contrôler le type LIF sur lequel une connexion de données NDMP est établie en utilisant le `-preferred-interface-role` option. Au cours d'un établissement de connexion de données NDMP, NDMP choisit une adresse IP appartenant au type LIF comme spécifié par cette option. Si les adresses IP n'appartiennent à aucun de ces types LIF, la connexion de données NDMP ne peut pas être établie. Pour plus d'informations sur le `-preferred-interface-role` reportez-vous aux pages de manuel.

Pour plus d'informations sur le `vserver services ndmp modify` commandes, consultez les pages de manuels.

.Informations associées
xref:commands-manage-svm-scoped-ndmp-reference.adoc[Commandes de gestion du mode SVM-scoped NDMP]

xref:cluster-aware-backup-extension-concept.adoc[Rôle de l'extension Cluster Aware Backup]

xref:svm-scoped-ndmp-mode-concept.adoc[Le mode SVM-scoped NDMP est]

link:../system-admin/index.html["Administration du système"]
