---
permalink: tape-backup/manage-svm-scoped-ndmp-mode-concept.html 
sidebar: sidebar 
keywords: manage, svm, scope, ndmp, flexvol, volumes, vserver, modify 
summary: 'Vous pouvez gérer NDMP par SVM en utilisant les options et commandes NDMP. Vous pouvez modifier les options NDMP en utilisant la commande vserver services ndmp modify. En mode SVM-scoped NDMP, l"authentification de l"utilisateur est intégrée au mécanisme de contrôle d"accès basé sur des rôles.' 
---
= En savoir plus sur la gestion du mode NDMP à portée SVM ONTAP pour les volumes FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez gérer NDMP par SVM en utilisant les options et commandes NDMP. Vous pouvez modifier les options NDMP en utilisant le `vserver services ndmp modify` commande. En mode SVM-scoped NDMP, l'authentification de l'utilisateur est intégrée au mécanisme de contrôle d'accès basé sur des rôles.

Vous pouvez ajouter NDMP dans la liste des protocoles autorisés ou interdits en utilisant le `vserver modify` commande. Par défaut, NDMP se trouve dans la liste des protocoles autorisés. Si NDMP est ajouté à la liste des protocoles interdits, les sessions NDMP ne peuvent pas être établies.

Vous pouvez contrôler le type de LIF sur laquelle une connexion de données NDMP est établie en utilisant l' `-preferred-interface-role`option. Au cours d'un établissement de connexion de données NDMP, NDMP choisit une adresse IP appartenant au type LIF comme spécifié par cette option. Si les adresses IP n'appartiennent à aucun de ces types LIF, la connexion de données NDMP ne peut pas être établie. Pour en savoir plus, `vserver services ndmp modify` consultez le link:https://docs.netapp.com/us-en/ontap-cli/vserver-services-ndmp-modify.html["Référence de commande ONTAP"^].



== Commandes pour la gestion du mode NDMP à portée SVM ONTAP

Vous pouvez utiliser le `vserver services ndmp` Commandes permettant de gérer NDMP sur chaque machine virtuelle de stockage (SVM, précédemment appelé Vserver).

|===
| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Activez le service NDMP
 a| 
`vserver services ndmp on`

[NOTE]
====
Le service NDMP doit toujours être activé sur tous les nœuds d'un cluster. Vous pouvez activer le service NDMP sur un nœud en utilisant le `system services ndmp on` commande. Par défaut, le service NDMP est toujours activé sur un nœud.

====


 a| 
Désactiver le service NDMP
 a| 
`vserver services ndmp off`



 a| 
Affiche la configuration NDMP
 a| 
`vserver services ndmp show`



 a| 
Modifier la configuration NDMP
 a| 
`vserver services ndmp modify`



 a| 
Affiche la version NDMP par défaut
 a| 
`vserver services ndmp version`



 a| 
Affiche toutes les sessions NDMP
 a| 
`vserver services ndmp status`



 a| 
Affiche des informations détaillées sur toutes les sessions NDMP
 a| 
`vserver services ndmp probe`



 a| 
Mettre fin à une session NDMP spécifiée
 a| 
`vserver services ndmp kill`



 a| 
Mettre fin à toutes les sessions NDMP
 a| 
`vserver services ndmp kill-all`



 a| 
Générer le mot de passe NDMP
 a| 
`vserver services ndmp generate-password`



 a| 
Affiche l'état de l'extension NDMP
 a| 
`vserver services ndmp extensions show`

Cette commande est disponible au niveau de privilège avancé.



 a| 
Modifier (activer ou désactiver) l'état de l'extension NDMP
 a| 
`vserver services ndmp extensions modify`

Cette commande est disponible au niveau de privilège avancé.



 a| 
Démarrez la connexion pour la session NDMP spécifiée
 a| 
`vserver services ndmp log start`

Cette commande est disponible au niveau de privilège avancé.



 a| 
Arrêter la journalisation de la session NDMP spécifiée
 a| 
`vserver services ndmp log stop`

Cette commande est disponible au niveau de privilège avancé.

|===
Pour en savoir plus, `vserver services ndmp` consultez le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+services+ndmp["Référence de commande ONTAP"^].

.Informations associées
xref:commands-manage-svm-scoped-ndmp-reference.adoc[Commandes de gestion du mode SVM-scoped NDMP]

xref:cluster-aware-backup-extension-concept.adoc[Rôle de l'extension Cluster Aware Backup]

xref:svm-scoped-ndmp-mode-concept.adoc[Le mode SVM-scoped NDMP est]

link:../system-admin/index.html["Administration du système"]
