---
permalink: tape-backup/ndmp-management-flexgroup-concept.html 
sidebar: sidebar 
keywords: understand, ndmp, flexgroup, volume, flexvol 
summary: Depuis ONTAP 9.7, NDMP est pris en charge sur les volumes FlexGroup. 
---
= À propos de NDMP pour volumes FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis ONTAP 9.7, NDMP est pris en charge sur les volumes FlexGroup.

Depuis ONTAP 9.7, la commande ndmpcopy est prise en charge pour le transfert de données entre les volumes FlexVol et FlexGroup.

Si vous restaurez ONTAP 9.7 vers une version antérieure, les informations de transfert incrémentiel des transferts précédents ne sont pas conservées. Par conséquent, vous devez effectuer une copie de base après le rétablissement.

Les fonctionnalités NDMP suivantes sont prises en charge sur les volumes FlexGroup depuis ONTAP 9.8 :

* Le message NDMP_SNAP_RECOVER de la classe d'extension 0x2050 peut être utilisé pour récupérer des fichiers individuels dans un volume FlexGroup.
* L'extension de sauvegarde NDMP redémarrable (RBE) est prise en charge pour les volumes FlexGroup.
* Les variables d'environnement EXCLUDE et MULTI_SUBTREE_NAMES sont prises en charge pour les volumes FlexGroup.

