---
permalink: tape-backup/ndmp-modes-concept.html 
sidebar: sidebar 
keywords: ndmp, mode, operation, backup, restore, node, level, svm 
summary: 'Vous pouvez effectuer des opérations de sauvegarde sur bande et de restauration au niveau du nœud ou du SVM (Storage Virtual machine). Pour réaliser correctement ces opérations au niveau du SVM, le service NDMP doit être activé sur la SVM.' 
---
= En savoir plus sur les modes de fonctionnement ONTAP NDMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez effectuer des opérations de sauvegarde sur bande et de restauration au niveau du nœud ou du SVM (Storage Virtual machine). Pour réaliser correctement ces opérations au niveau du SVM, le service NDMP doit être activé sur la SVM.

Si vous effectuez une mise à niveau de Data ONTAP 8.2 vers Data ONTAP 8.3, le mode d'opération NDMP utilisé dans 8.2 sera conservé après la mise à niveau de 8.2 à 8.3.

Si vous installez un nouveau cluster avec Data ONTAP 8.2 ou version ultérieure, NDMP est en mode SVM-scoped NDMP par défaut. Pour effectuer des opérations de sauvegarde sur bande et de restauration en mode node-scoped NDMP, vous devez activer de façon explicite le mode node-scoped NDMP.



== En savoir plus sur le mode NDMP ONTAP à portée de nœud

En mode node-scoped NDMP, vous pouvez effectuer des opérations de backup sur bande et restore au niveau du noeud. Le mode d'opération NDMP utilisé dans Data ONTAP 8.2 reste conservé après la mise à niveau de 8.2 à 8.3.

En mode node-scoped NDMP, vous pouvez effectuer des opérations de backup sur bande et restore sur un noeud propriétaire du volume. Pour effectuer ces opérations, vous devez établir des connexions de contrôle NDMP sur une LIF hébergée sur le nœud qui détient le volume ou les lecteurs de bande.

[NOTE]
====
Ce mode est obsolète et sera supprimé dans une prochaine version majeure.

====


== En savoir plus sur le mode NDMP ONTAP à portée SVM

Vous pouvez réaliser des opérations de sauvegarde sur bande et de restauration au niveau des SVM (Storage Virtual machine) si le service NDMP est activé sur la SVM. Vous pouvez sauvegarder et restaurer tous les volumes hébergés sur différents nœuds du SVM d'un cluster si l'application de sauvegarde prend en charge l'extension CAB.

Une connexion de contrôle NDMP peut être établie sur différents types de LIF. En mode SVM-scoped NDMP, ces LIFs appartiennent au SVM de données ou au SVM admin. La connexion peut être établie sur une LIF uniquement si le service NDMP est activé sur le SVM qui possède cette LIF.

Une LIF de données appartient au SVM de données et au LIF intercluster, ainsi qu'au LIF node-management et au LIF cluster-management appartient au SVM admin.

En mode SVM-scoped NDMP, la disponibilité des volumes et des dispositifs sur bande pour les opérations de backup et restore dépend du type de LIF sur lequel la connexion NDMP control est établie et de l'état de l'extension CAB. Si votre application de sauvegarde prend en charge l'extension CAB et qu'un volume et le périphérique de bande partagent la même affinité, alors l'application de sauvegarde peut effectuer une opération de sauvegarde ou de restauration locale, au lieu d'une opération de sauvegarde ou de restauration à trois voies.

.Informations associées
xref:commands-manage-node-scoped-ndmp-reference.adoc[Commandes permettant de gérer le mode node-scoped NDMP]
