---
permalink: tape-backup/ndmp-modes-concept.html 
sidebar: sidebar 
keywords: ndmp, mode, operation, backup, restore, node, level, svm 
summary: 'Vous pouvez choisir d"effectuer des sauvegardes sur bandes et des restaurations au niveau du nœud comme vous l"avez fait jusqu"à présent ou au niveau de la machine virtuelle de stockage (SVM). Pour réaliser correctement ces opérations au niveau du SVM, le service NDMP doit être activé sur la SVM.' 
---
= À propos des modes de fonctionnement NDMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez choisir d'effectuer des sauvegardes sur bandes et des restaurations au niveau du nœud comme vous l'avez fait jusqu'à présent ou au niveau de la machine virtuelle de stockage (SVM). Pour réaliser correctement ces opérations au niveau du SVM, le service NDMP doit être activé sur la SVM.

Si vous effectuez une mise à niveau de Data ONTAP 8.2 vers Data ONTAP 8.3, le mode d'opération NDMP utilisé dans 8.2 sera conservé après la mise à niveau de 8.2 à 8.3.

Si vous installez un nouveau cluster avec Data ONTAP 8.2 ou version ultérieure, NDMP est en mode SVM-scoped NDMP par défaut. Pour effectuer des opérations de sauvegarde sur bande et de restauration en mode node-scoped NDMP, vous devez activer de façon explicite le mode node-scoped NDMP.

.Informations associées
xref:commands-manage-node-scoped-ndmp-reference.adoc[Commandes permettant de gérer le mode node-scoped NDMP]

xref:manage-node-scoped-ndmp-mode-concept.adoc[Gérer le mode NDMP node-scoped pour les volumes FlexVol]

xref:manage-svm-scoped-ndmp-mode-concept.adoc[Gérer le mode SVM-scoped NDMP pour les volumes FlexVol]
