---
permalink: tape-backup/ndmp-snaplock-volumes-concept.html 
sidebar: sidebar 
keywords: ndmp, snaplock, volumes, worm, write, once, read, many, snaplock, volume, recovery 
summary: 'La création de multiples copies de données réglementées vous fournit des scénarios de récupération redondants, et en utilisant NDMP dump and restore, il est possible de préserver les caractéristiques WORM (Write Once, Read Many) des fichiers source sur un volume SnapLock.' 
---
= En savoir plus sur NDMP avec les volumes ONTAP SnapLock
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La création de plusieurs copies de données réglementées vous permet de bénéficier de scénarios de restauration redondants. En outre, grâce à ce processus, vous pouvez conserver les caractéristiques WORM (Write Once, Read Many) des fichiers source sur un volume SnapLock.

Les attributs WORM des fichiers du volume SnapLock sont conservés lors de la sauvegarde, de la restauration et de la copie des données. Toutefois, les attributs WORM ne sont appliqués que lors de la restauration vers un volume SnapLock. Si une sauvegarde d'un volume SnapLock est restaurée dans un volume autre qu'un volume SnapLock, les attributs WORM sont conservés, mais ils sont ignorés et ne sont pas appliqués par ONTAP.
