---
permalink: tape-backup/nonqualified-tape-drives-task.html 
sidebar: sidebar 
keywords: nonqualified, tape, drive, storage, system, emulate, qualified 
summary: 'Vous pouvez utiliser un lecteur de bande non qualifié sur un système de stockage s"il peut émuler un lecteur de bande qualifié. Il est ensuite traité comme un lecteur de bande qualifié. Pour utiliser un lecteur de bande non qualifié, vous devez d"abord déterminer s"il émule un des lecteurs de bande qualifiés.' 
---
= Utilisez un lecteur de bande non qualifié
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser un lecteur de bande non qualifié sur un système de stockage s'il peut émuler un lecteur de bande qualifié. Il est ensuite traité comme un lecteur de bande qualifié. Pour utiliser un lecteur de bande non qualifié, vous devez d'abord déterminer s'il émule un des lecteurs de bande qualifiés.

Un lecteur de bande non qualifié est connecté au système de stockage, mais il n'est pas pris en charge ou reconnu par ONTAP.

.Étapes
. Affichez les lecteurs de bande non qualifiés connectés à un système de stockage à l'aide du `storage tape show-supported-status` commande.
+
La commande suivante affiche les lecteurs de bande connectés au système de stockage ainsi que l'état de support et de qualification de chaque lecteur de bande. Les lecteurs de bande non qualifiés sont également répertoriés. `tape_drive_vendor_name` Est un lecteur de bande non qualifié connecté au système de stockage, mais non pris en charge par ONTAP.

+
[listing]
----

cluster1::> storage tape show-supported-status -node Node1

          Node: Node1
                                    Is
          Tape Drive                Supported  Support Status
          --------------------      ---------  --------------
          "tape_drive_vendor_name"  false      Nonqualified tape drive
          Hewlett-Packard C1533A    true       Qualified
          Hewlett-Packard C1553A    true       Qualified
          Hewlett-Packard Ultrium 1 true       Qualified
          Sony SDX-300C             true       Qualified
          Sony SDX-500C             true       Qualified
          StorageTek T9840C         true       Dynamically Qualified
          StorageTek T9840D         true       Dynamically Qualified
          Tandberg LTO-2 HH         true       Dynamically Qualified
----
. Émuler le lecteur de bande qualifié.
+
https://mysupport.netapp.com/site/tools/tool-eula/tape-config["Téléchargements NetApp : fichiers de configuration des lecteurs de bande"^]



xref:qualified-tape-drives-concept.adoc[Lecteurs de bande qualifiés]
