---
permalink: tape-backup/restore-7-mode-clustered-ontap-concept.html 
sidebar: sidebar 
keywords: tape, backup, restore, support, data, 7 mode, storage, system 
summary: 'Vous pouvez restaurer les données sauvegardées à partir d"un système de stockage sous 7-mode ou exécutant ONTAP vers un système de stockage sous 7-mode ou exécutant ONTAP.' 
---
= Prise en charge de la sauvegarde sur bande et des restaurations entre Data ONTAP sous 7-mode et ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez restaurer les données sauvegardées à partir d'un système de stockage sous 7-mode ou exécutant ONTAP vers un système de stockage sous 7-mode ou exécutant ONTAP.

Les opérations suivantes de sauvegarde sur bande et de restauration sont prises en charge entre Data ONTAP en 7-mode et ONTAP :

* Sauvegarde d'un volume 7-mode sur un lecteur de bandes connecté à un système de stockage exécutant ONTAP
* Sauvegarde d'un volume ONTAP sur un lecteur de bandes connecté à un système 7-mode
* Restauration des données sauvegardées d'un volume 7-mode depuis un lecteur de bande connecté à un système de stockage exécutant ONTAP
* Restauration des données sauvegardées d'un volume ONTAP à partir d'un lecteur de bande connecté à un système 7-mode
* Restauration d'un volume 7-mode vers un volume ONTAP
+
[NOTE]
====
....
-   A 7-Mode LUN is restored as a LUN on an ONTAP volume.
-   You should retain the ONTAP LUN identifiers when restoring a 7-Mode LUN to an existing ONTAP LUN.
....
====
* Restauration d'un volume ONTAP sur un volume 7-mode
+
[NOTE]
====
Une LUN ONTAP est restaurée sous forme de fichier standard sur un volume 7-mode.

====

