---
permalink: tape-backup/scalability-limits-ndmp-sessions-reference.html 
sidebar: sidebar 
keywords: scalability, limits, ndmp, sessions, memory, capacities, maximum 
summary: 'Vous devez connaître le nombre maximal de sessions NDMP qui peuvent être établies simultanément sur les systèmes de stockage de différentes capacités de mémoire système. Ce nombre maximum dépend de la mémoire système d"un système de stockage.' 
---
= Limite d'évolutivité pour les sessions NDMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez connaître le nombre maximal de sessions NDMP qui peuvent être établies simultanément sur les systèmes de stockage de différentes capacités de mémoire système. Ce nombre maximum dépend de la mémoire système d'un système de stockage.

Les limites mentionnées dans le tableau suivant sont destinées au serveur NDMP. Les limites mentionnées dans la section «limites de capacités pour les sessions de sauvegarde et de restauration de vidage» sont pour la session de sauvegarde et de restauration.

xref:scalability-limits-dump-backup-restore-sessions-concept.adoc[Limite d'évolutivité pour les sessions de sauvegarde et de restauration]

|===
| Mémoire système d'un système de stockage | Nombre maximal de sessions NDMP 


 a| 
Moins de 16 Go
 a| 
8



 a| 
Supérieur ou égal à 16 Go mais inférieur à 24 Go
 a| 
20



 a| 
Supérieur ou égal à 24 Go
 a| 
36

|===
Vous pouvez obtenir la mémoire système de votre système de stockage à l'aide du `sysconfig -a` commande (disponible via le nodeshell). Pour plus d'informations sur l'utilisation de cette commande, consultez les pages de manuels.
