---
permalink: tape-backup/scalability-limits-dump-backup-restore-sessions-concept.html 
sidebar: sidebar 
keywords: scalability, limites, dump, backup, restore, sessions, maximum, memory, capacities, storage, system 
summary: 'Vous devez connaître le nombre maximal de sessions de sauvegarde et de restauration de vidage que vous pouvez effectuer simultanément sur les systèmes de stockage de différentes capacités de mémoire système. Ce nombre maximum dépend de la mémoire système d"un système de stockage.' 
---
= Limites d'évolutivité pour les sessions de sauvegarde et de restauration de dump dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez connaître le nombre maximal de sessions de sauvegarde et de restauration de vidage que vous pouvez effectuer simultanément sur les systèmes de stockage de différentes capacités de mémoire système. Ce nombre maximum dépend de la mémoire système d'un système de stockage.

Les limites mentionnées dans le tableau suivant concernent le moteur de vidage ou de restauration. Les limites mentionnées dans les limites d'évolutivité des sessions NDMP sont destinées au serveur NDMP, qui sont supérieures aux limites du moteur.

|===
| Mémoire système d'un système de stockage | Nombre total de sessions de sauvegarde et de restauration de vidage 


 a| 
Moins de 16 Go
 a| 
4



 a| 
Supérieur ou égal à 16 Go mais inférieur à 24 Go
 a| 
16



 a| 
Supérieur ou égal à 24 Go
 a| 
32

|===
[NOTE]
====
Si vous utilisez `ndmpcopy` Commande pour copier les données dans les systèmes de stockage, deux sessions NDMP sont établies, l'une pour dump backup et l'autre pour dump restore.

====
Vous pouvez obtenir la mémoire système de votre système de stockage en utilisant la `sysconfig -a` commande (disponible via le nodeshell). Pour en savoir plus, `sysconfig -a` consultez le link:https://docs.netapp.com/us-en/ontap-cli/system-node-run.html["Référence de commande ONTAP"^].

.Informations associées
xref:scalability-limits-ndmp-sessions-reference.adoc[Limite d'évolutivité pour les sessions NDMP]
