---
permalink: tape-backup/smtape-storage-failover-arl-concept.html 
sidebar: sidebar 
keywords: smtape, storage, failover, arl, operation, aggregate, relocation 
summary: 'Avant d"effectuer des opérations de sauvegarde ou de restauration SMTape, vous devez comprendre le fonctionnement de ces opérations grâce au basculement du stockage (basculement et rétablissement) ou au transfert d"agrégats (ARL). L"option -override-vetoes détermine le comportement du moteur SMTape lors d"une opération de basculement du stockage ou d"ARL.' 
---
= Fonctionnement de SMTape avec basculement du stockage et opérations d'ARL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'effectuer des opérations de sauvegarde ou de restauration SMTape, vous devez comprendre le fonctionnement de ces opérations grâce au basculement du stockage (basculement et rétablissement) ou au transfert d'agrégats (ARL). Le `-override-vetoes` Détermine le comportement du moteur SMTape lors du basculement du stockage ou du transfert d'agrégats.

Lorsqu'une opération de sauvegarde ou de restauration SMTape est en cours d'exécution sur `-override-vetoes` l'option est définie sur `false`, Un basculement de stockage initié par l'utilisateur ou une opération ARL est arrêté et l'opération de sauvegarde ou de restauration est terminée. Si l'application de sauvegarde prend en charge l'extension CAB, vous pouvez continuer à effectuer les opérations de sauvegarde et de restauration incrémentielles SMTape sans reconfigurer les règles de sauvegarde. Cependant, si `–override-vetoes` l'option est définie sur `true`, Le basculement du stockage ou l'opération ARL est ensuite poursuivi et l'opération de sauvegarde ou de restauration SMTape est abandonnée.

.Informations associées
link:../networking/networking_reference.html["Gestion du réseau"]

link:../high-availability/index.html["Haute disponibilité"]
