---
permalink: tape-backup/smtape-volume-rehost-concept.html 
sidebar: sidebar 
keywords: smtape, volume, rehost, operation, session 
summary: 'Les opérations SMTape ne peuvent pas commencer lorsqu"une opération de réhébergement de volume est en cours sur un volume. Lorsqu"un volume est impliqué dans une opération de réhébergement de volumes, les sessions SMTape ne doivent pas être lancées sur ce volume.' 
---
= Fonctionnement de SMTape avec les opérations de réhébergement de volume ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les opérations SMTape ne peuvent pas commencer lorsqu'une opération de réhébergement de volume est en cours sur un volume. Lorsqu'un volume est impliqué dans une opération de réhébergement de volumes, les sessions SMTape ne doivent pas être lancées sur ce volume.

Lorsque des opérations de réhébergement de volumes sont en cours, la sauvegarde ou la restauration SMTape échoue. Lorsqu'une sauvegarde ou une restauration SMTape est en cours, les opérations de réhébergement de volume rencontrent un message d'erreur approprié. Cette condition s'applique aux opérations de sauvegarde ou de restauration basées sur NDMP et sur l'interface de ligne de commande.
