---
permalink: tape-backup/smtape-backup-restore-operations-mcc-config-concept.html 
sidebar: sidebar 
keywords: smtape, backup, restore, operation, metrocluster, configuration, switchover, switchback 
summary: 'Avant d"effectuer les opérations de sauvegarde et de restauration SMTape sur une configuration MetroCluster, vous devez d"abord comprendre comment les opérations SMTape sont affectées lors d"une opération de basculement ou de rétablissement.' 
---
= Comment les opérations de sauvegarde et de restauration SMTape sont affectées dans les configurations ONTAP MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'effectuer les opérations de sauvegarde et de restauration SMTape sur une configuration MetroCluster, vous devez d'abord comprendre comment les opérations SMTape sont affectées lors d'une opération de basculement ou de rétablissement.



== Opération de sauvegarde ou de restauration SMTape, suivie du basculement

Envisager deux clusters : cluster 1 et cluster 2. Lors d'une opération de sauvegarde ou de restauration SMTape sur le cluster 1, si un basculement est initié du cluster 1 au cluster 2, ce qui suit se produit :

* Si la valeur de `–override-vetoes` l'option est `false`, le processus de basculement est alors interrompu et l'opération de sauvegarde ou de restauration se poursuit.
* Si la valeur de l'option est `true`, Puis l'opération de sauvegarde ou de restauration SMTape est abandonnée et le processus de basculement se poursuit.




== Opération de sauvegarde ou de restauration SMTape, suivie du rétablissement

Un basculement est effectué du cluster 1 vers le cluster 2. Une opération de sauvegarde ou de restauration SMTape est lancée sur le cluster 2. L'opération SMTape permet de sauvegarder ou de restaurer un volume situé sur le cluster 2. À ce stade, si un rétablissement est initié du cluster 2 au cluster 1, ce qui suit se produit :

* Si la valeur de `–override-vetoes` l'option est `false`, le processus de rétablissement est alors interrompu et l'opération de sauvegarde ou de restauration se poursuit.
* Si la valeur de l'option est `true`, l'opération de sauvegarde ou de restauration est alors abandonnée et le processus de rétablissement se poursuit.




== Opération de sauvegarde ou de restauration SMTape initiée lors du basculement ou du rétablissement

Lors d'un processus de basculement du cluster 1 vers le cluster 2, si une opération de sauvegarde ou de restauration SMTape est lancée sur le cluster 1, alors l'opération de sauvegarde ou de restauration échoue et le basculement se poursuit.

Lors du processus de rétablissement du cluster 2 vers le cluster 1, si une opération de sauvegarde ou de restauration SMTape est lancée depuis le cluster 2, l'opération de sauvegarde ou de restauration échoue et le rétablissement se poursuit.
