---
permalink: tape-backup/tape-seeding-concept.html 
sidebar: sidebar 
keywords: tape, seeding, smtape, functionality, destination, flexvol, data, protection, mirror 
summary: 'La fonction SMTape permet d"initialiser un volume FlexVol de destination dans une relation de miroir de protection des données.' 
---
= En quoi consiste l'amorçage des bandes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La fonction SMTape permet d'initialiser un volume FlexVol de destination dans une relation de miroir de protection des données.

Le « Tape seeding » permet d'établir une relation de miroir de protection des données entre le système source et le système de destination via une connexion à faible bande passante.

La mise en miroir incrémentielle des copies Snapshot de la source vers la destination est possible via une connexion à faible bande passante. Cependant, une mise en miroir initiale de la copie Snapshot de base prend beaucoup de temps sur une connexion à faible bande passante. Il est ainsi possible d'effectuer une sauvegarde SMTape du volume source sur bande, puis d'utiliser la bande pour transférer la copie Snapshot de la base initiale vers la destination. Vous pouvez ensuite configurer des mises à jour SnapMirror incrémentielles sur le système de destination à l'aide de la connexion à faible bande passante.
