---
permalink: tape-backup/tape-drive-management-concept.html 
sidebar: sidebar 
keywords: manage, tape, drive, library, connections, backup, resotre, operation, alias 
summary: 'Vous pouvez vérifier les connexions de la librairie de bandes et afficher les informations relatives au lecteur de bandes avant d"effectuer une sauvegarde sur bande ou une restauration. Vous pouvez utiliser un lecteur de bande non qualifié en l"émulant sur un lecteur de bande qualifié. Vous pouvez également attribuer et supprimer des alias de bande en plus d"afficher des alias existants.' 
---
= Présentation de la gestion des lecteurs de bandes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez vérifier les connexions de la librairie de bandes et afficher les informations relatives au lecteur de bandes avant d'effectuer une sauvegarde sur bande ou une restauration. Vous pouvez utiliser un lecteur de bande non qualifié en l'émulant sur un lecteur de bande qualifié. Vous pouvez également attribuer et supprimer des alias de bande en plus d'afficher des alias existants.

Lorsque vous sauvegardez des données sur bande, celles-ci sont stockées dans des fichiers sur bande. Les repères de fichier séparent les fichiers de bande et les fichiers n'ont pas de nom. Vous spécifiez un fichier de bande en fonction de sa position sur la bande. Vous écrivez un fichier de bande à l'aide d'un lecteur de bande. Lorsque vous lisez le fichier de bande, vous devez spécifier un périphérique ayant le même type de compression que celui utilisé pour écrire ce fichier de bande.
