---
permalink: tape-backup/types-data-dump-engine-backs-up-concept.html 
sidebar: sidebar 
keywords: types, data, dump, engine, backs, up, files, directory, qtree, volumes 
summary: 'Le moteur de dump vous permet de sauvegarder les données sur bande afin d"éviter les incidents ou les perturbations sur les contrôleurs. Outre la sauvegarde d"objets de données tels que des fichiers, des répertoires, des qtrees ou des volumes entiers, le moteur de dump peut sauvegarder de nombreux types d"informations sur chaque fichier. La connaissance des types de données que le moteur de dump peut sauvegarder et des restrictions à prendre en compte peut vous aider à planifier votre approche de la reprise sur incident.' 
---
= Types de données que le moteur de vidage sauvegarde
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le moteur de dump vous permet de sauvegarder les données sur bande afin d'éviter les incidents ou les perturbations sur les contrôleurs. Outre la sauvegarde d'objets de données tels que des fichiers, des répertoires, des qtrees ou des volumes entiers, le moteur de dump peut sauvegarder de nombreux types d'informations sur chaque fichier. La connaissance des types de données que le moteur de dump peut sauvegarder et des restrictions à prendre en compte peut vous aider à planifier votre approche de la reprise sur incident.

En plus de sauvegarder des données dans des fichiers, le moteur de vidage peut sauvegarder les informations suivantes sur chaque fichier, selon le cas :

* GID UNIX, UID de propriétaire et autorisations de fichier
* Heure d'accès, de création et de modification UNIX
* Type de fichier
* Taille du fichier
* Nom DOS, attributs DOS et heure de création
* Listes de contrôle d'accès (ACL) avec 1,024 entrées de contrôle d'accès (ACE)
* Informations sur les qtrees
* Chemins de liaison


Les chemins de jonction sont sauvegardés en tant que liens symboliques.

* Clones de LUN et de LUN
+
Vous pouvez sauvegarder un objet LUN entier ; cependant, vous ne pouvez pas sauvegarder un seul fichier dans cet objet. De la même manière, vous pouvez restaurer tout un objet LUN, mais pas un seul fichier au sein de ce dernier.

+
[NOTE]
====
Le moteur de dump sauvegarde les clones de LUN en tant que LUN indépendantes.

====
* Fichiers alignés sur les machines virtuelles
+
La sauvegarde des fichiers alignés sur les machines virtuelles n'est pas prise en charge dans les versions antérieures à Data ONTAP 8.1.2.



[NOTE]
====
Lorsqu'un clone de LUN avec snapshot est passé de Data ONTAP 7-mode à ONTAP, il devient LUN incohérent. Le moteur de vidage ne sauvegarde pas les LUN incohérentes.

====
Lorsque vous restaurez les données sur un volume, les E/S client sont restreintes sur les LUN en cours de restauration. La restriction de LUN est supprimée uniquement lorsque l'opération de restauration de vidage est terminée. De même, lors de l'opération de restauration de fichiers ou de LUN SnapMirror, les E/S clientes sont limitées sur les fichiers et les LUN en cours de restauration. Cette restriction est supprimée uniquement lorsque l'opération de restauration de fichier ou de LUN est terminée. Lorsqu'une sauvegarde de dump est effectuée sur un volume sur lequel une restauration de dump ou une opération de restauration de fichier unique SnapMirror ou de restauration de LUN est en cours, les fichiers ou les LUN dont les restrictions d'E/S sont présentes sur le client ne sont pas inclus dans la sauvegarde. Ces fichiers ou LUN sont inclus dans une opération de sauvegarde suivante si la restriction d'E/S du client est supprimée.

[NOTE]
====
Une LUN exécutée sur Data ONTAP 8.3 et qui est sauvegardée sur bande ne peut être restaurée qu'à partir des versions 8.3 et ultérieures, et non vers une version antérieure. Si la LUN est restaurée dans une version antérieure, la LUN est restaurée en tant que fichier.

====
Lorsque vous sauvegardez un volume secondaire SnapVault ou une destination SnapMirror volume sur bande, seules les données du volume sont sauvegardées. Les métadonnées associées ne sont pas sauvegardées. Par conséquent, lorsque vous tentez de restaurer le volume, seules les données de ce volume sont restaurées. Les informations relatives aux relations SnapMirror volume ne sont pas disponibles dans la sauvegarde et n'sont donc pas restaurées.

Si vous dump un fichier qui ne dispose que d'autorisations Windows NT et le restaurez sur un qtree ou un volume de style UNIX, le fichier obtient les autorisations UNIX par défaut pour ce qtree ou volume.

Si vous dump un fichier qui ne dispose que d'autorisations UNIX et que vous le restaurez sur un qtree ou un volume de style NTFS, le fichier obtient les autorisations Windows par défaut pour ce qtree ou ce volume.

Les autres « dumps » et les restaurations préservent les autorisations.

Vous pouvez sauvegarder des fichiers alignés sur les machines virtuelles et le `vm-align-sector` option. Pour plus d'informations sur les fichiers alignés sur les machines virtuelles, voir link:../volumes/index.html["Gestion du stockage logique"].
