---
permalink: tape-backup/user-authentication-svm-scoped-ndmp-mode-concept.html 
sidebar: sidebar 
keywords: user, authentication, svm, ndmp, node, vsadmin, backup, role, storage, virutal, machine, user 
summary: 'En mode SVM (Storage Virtual machine)-scoped NDMP, l"authentification utilisateur NDMP est intégrée au contrôle d"accès basé sur des rôles. Dans le contexte SVM, l"utilisateur NDMP doit avoir le rôle « vsadmin » ou « vsadmin-backup ». Dans un contexte de cluster, l"utilisateur NDMP doit avoir le rôle "admin" ou "backup".' 
---
= Authentification de l'utilisateur en mode SVM-scoped NDMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En mode SVM (Storage Virtual machine)-scoped NDMP, l'authentification utilisateur NDMP est intégrée au contrôle d'accès basé sur des rôles. Dans le contexte SVM, l'utilisateur NDMP doit avoir le rôle « vsadmin » ou « vsadmin-backup ». Dans un contexte de cluster, l'utilisateur NDMP doit avoir le rôle « admin » ou « backup ».

Outre ces rôles prédéfinis, un compte utilisateur associé à un rôle personnalisé peut également être utilisé pour l'authentification NDMP à condition que le rôle personnalisé ait le dossier « vserver services ndmp » dans son répertoire de commandes et que le niveau d'accès du dossier n'est pas « nul ». Dans ce mode, vous devez générer un mot de passe NDMP pour un compte utilisateur donné, créé par le biais du contrôle d'accès basé sur des rôles. Les utilisateurs de cluster en rôle d'administrateur ou de sauvegarde peuvent accéder à une LIF de node-management, à une LIF de cluster-management ou à un LIF intercluster. Les utilisateurs ayant un rôle vsadmin-backup ou vsadmin peuvent accéder uniquement à la LIF de données pour ce SVM. Par conséquent, selon le rôle d'un utilisateur, la disponibilité des volumes et des périphériques de bande pour les opérations de sauvegarde et de restauration varie.

Ce mode prend également en charge l'authentification des utilisateurs pour les utilisateurs NIS et LDAP. Ainsi, les utilisateurs NIS et LDAP peuvent accéder à plusieurs SVM avec un ID utilisateur et un mot de passe communs. Cependant, l'authentification NDMP ne prend pas en charge les utilisateurs Active Directory.

Dans ce mode, un compte utilisateur doit être associé à l'application SSH et à la méthode d'authentification « Mot de passe utilisateur ».

.Informations associées
xref:commands-manage-svm-scoped-ndmp-reference.adoc[Commandes de gestion du mode SVM-scoped NDMP]

link:../system-admin/index.html["Administration du système"]

link:../concepts/index.html["Concepts relatifs à ONTAP"]
