---
permalink: tape-backup/workflow-task.html 
sidebar: sidebar 
keywords: perform, tape, backup, restore, flexvol, volume, ndmp, backup, application 
summary: 'Vous pouvez effectuer des opérations de sauvegarde sur bande et de restauration à l"aide d"une application de sauvegarde NDMP.' 
---
= Workflow de sauvegarde et de restauration sur bande dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez effectuer des opérations de sauvegarde sur bande et de restauration à l'aide d'une application de sauvegarde NDMP.

.Description de la tâche
Le flux de production de sauvegarde et restauration sur bande présente les tâches impliquées dans les opérations de sauvegarde et de restauration sur bande. Pour plus d'informations sur l'exécution d'une opération de sauvegarde et de restauration, reportez-vous à la documentation de l'application de sauvegarde.

.Étapes
. Définissez une configuration de librairie de bandes en choisissant une topologie de bande prise en charge par NDMP.
. Activez les services NDMP sur votre système de stockage.
+
Vous pouvez activer les services NDMP au niveau des nœuds ou au niveau des machines virtuelles de stockage (SVM). Cela dépend du mode NDMP dans lequel vous choisissez d'effectuer l'opération de sauvegarde sur bande et de restauration.

. Utilisez les options NDMP pour gérer NDMP sur votre système de stockage.
+
Vous pouvez utiliser les options NDMP au niveau des nœuds ou au niveau de la SVM. Cela dépend du mode NDMP dans lequel vous choisissez d'effectuer l'opération de sauvegarde sur bande et de restauration.

+
Vous pouvez modifier les options NDMP au niveau du nœud en utilisant `system services ndmp modify` la commande et au niveau du SVM en utilisant la `vserver services ndmp modify` commande. Pour en savoir plus, `system services ndmp modify`and `vserver services ndmp modify` consultez le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=services+ndmp+modify["Référence de commande ONTAP"^].

. Effectuez une opération de sauvegarde sur bande ou de restauration à l'aide d'une application de sauvegarde NDMP.
+
ONTAP prend en charge les moteurs dump et SMTape pour la sauvegarde sur bande et la restauration.

+
Pour plus d'informations sur l'utilisation de l'application de sauvegarde (également appelée _Data Management applications_ ou _DMA_) pour effectuer des opérations de sauvegarde ou de restauration, consultez la documentation de votre application de sauvegarde.



.Informations associées
xref:common-ndmp-topologies-reference.adoc[Topologies de sauvegarde sur bande NDMP courantes]

xref:data-backup-dump-concept.adoc[Présentation du moteur de dump pour les volumes FlexVol]
