---
permalink: software_setup/concept_decide_whether_to_use_ontap_cli.html 
sidebar: sidebar 
keywords: ontap, software, setup, deciding, decide, if, whether, use, cli, cluster, System Manager, IPv6, HA, root volumes, FlexArray 
summary: 'Vous devez utiliser uniquement l"interface de ligne de commandes de ONTAP pour effectuer la configuration initiale du cluster si elle n"est pas prise en charge avec votre version de System Manager.' 
---
= Définissez si vous souhaitez utiliser System Manager ou l'interface de ligne de commandes ONTAP pour la configuration du cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer de nouveaux clusters à l'aide de l'interface de ligne de commandes ONTAP. Cependant, NetApp vous recommande d'utiliser System Manager dès que possible pour simplifier le processus de configuration du cluster. Utilisez ces procédures uniquement si votre version de System Manager ne prend pas en charge la configuration initiale du cluster pour votre déploiement ONTAP planifié.

Vous devez connaître les exigences de support suivantes de System Manager :

* La configuration du cluster est prise en charge uniquement pour les nœuds uniques et les paires haute disponibilité
* Lorsque vous configurez le logiciel de gestion des nœuds manuellement via l'interface de ligne de commandes, System Manager prend uniquement en charge IPv4 et ne prend pas en charge IPv6. Cependant, si vous lancez System Manager après avoir terminé la configuration matérielle à l'aide de DHCP avec une adresse IP auto-assignée et avec la découverte de Windows, System Manager peut configurer une adresse de gestion IPv6.
+
Dans ONTAP 9.6 et versions antérieures, System Manager ne prend pas en charge les déploiements nécessitant une mise en réseau IPv6.

* La prise en charge de l'installation MetroCluster est destinée aux configurations IP MetroCluster avec deux nœuds sur chaque site.
+
Dans ONTAP 9.7 et versions antérieures, System Manager ne prend pas en charge la nouvelle configuration du cluster pour les configurations MetroCluster.



Si vous configurez un FlexArray sur des disques non NetApp, vous devez utiliser l'interface de ligne de commande de ONTAP pour configurer les volumes root sur les LUN de la baie, puis utiliser l'assistant de configuration du cluster pour configurer le cluster. Pour plus d'informations, reportez-vous à la section link:https://docs.netapp.com/us-en/ontap-flexarray/install/concept_flexarray_virtualization_technology_overview_using_array_luns_for_storage.html["Installation et configuration requise de la virtualisation FlexArray"] documentation :

Avant d'exécuter l'une de ces procédures, vous devez avoir installé, câblé et mis sous tension votre nouveau système de stockage conformément aux instructions d'installation et de configuration de votre modèle de plate-forme. Voir la https://docs.netapp.com/us-en/ontap-systems/index.html["Documentation AFF et FAS"].
