---
sidebar: sidebar 
permalink: software_setup/setup-cluster.html 
keywords: install, installing, cluster, set up, setup, configure, disk, data ports, guided setup, local tiers, aggregate, vserver, volume, configuring ONTAP on a new cluster, configuring a new cluster, assign a node-management IP address, node, DNS server, host name, hostname, NTP server, synchronize time, create a local tier, configure protocol, SSD, provision storage, add LUN, add volume, add namespace, volume, vserver, configure ONTAP on a new cluster, configuration 
summary: 'System Manager offre un workflow simple et facile pour l"installation du cluster et la configuration du stockage.' 
---
= Créez un cluster ONTAP et rejoignez les nœuds
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp vous recommande d'utiliser System Manager pour créer de nouveaux clusters. System Manager simplifie et simplifie le flux de travail pour la configuration des clusters. Il n'est nécessaire d'utiliser l'interface de ligne de commande ONTAP que si vous exécutez ONTAP 9.7 ou une version antérieure dans une configuration MetroCluster ou si vous devez configurer un cluster IPv6 uniquement sur certaines plateformes.

.Description de la tâche
Cette procédure s'applique aux systèmes FAS, AFF et ASA. Si vous possédez un système ASA r2 (ASA A1K, ASA A90, ASA A70, ASA A50, ASA A30, ASA A20 ou ASA C30), suivez link:https://docs.netapp.com/us-en/asa-r2/install-setup/initialize-ontap-cluster.html["procédure à suivre"^] pour utiliser System Manager pour configurer un cluster ONTAP. Les systèmes ASA r2 simplifient l'expérience ONTAP propre aux clients SAN.

Depuis ONTAP 9.13.1, vous pouvez attribuer des adresses IPv6 aux LIF de gestion sur des plateformes AFF A800 et FAS8700 lors de la configuration initiale du cluster à l'aide de l'interface de ligne de commandes ONTAP. Pour les versions ONTAP antérieures à ONTAP 9.13.1, ou pour ONTAP 9.13.1 et versions ultérieures sur d'autres plateformes, vous devez utiliser System Manager pour créer votre cluster à l'aide d'adresses IPv4, puis link:convert-ipv4-to-ipv6-task.html["Convertir en IPv6"] d'adresses une fois que vous avez terminé la configuration du cluster.


NOTE: System Manager ne prend pas en charge les déploiements qui nécessitent une mise en réseau IPv6 dans ONTAP 9.6 et les versions antérieures.

.Avant de commencer
* Vous devez avoir installé, câblé et sous tension votre nouveau système de stockage conformément aux instructions d'installation et de configuration du modèle de votre plate-forme.
+
Voir la link:https://docs.netapp.com/us-en/ontap-systems/index.html["Documentation AFF et FAS"^].

* link:gather_cluster_setup_information.html["Rassemblez les informations dont vous avez besoin"] pour terminer la configuration du cluster.
* Les interfaces réseau du cluster doivent être configurées sur chaque nœud du cluster pour les communications intra-cluster.
* Si vous utilisez l'interface de ligne de commandes pour configurer IPv6, IPv6 doit être configuré sur le contrôleur de gestion de base (BMC) afin que vous puissiez utiliser SSH pour accéder au système.


.Étapes
[role="tabbed-block"]
====
.System Manager
--
. Attribuez une adresse IP de gestion des nœuds
+
** Ordinateur Windows
+
... Connectez votre ordinateur Windows au même sous-réseau que les contrôleurs.
+
Cette opération attribue automatiquement une adresse IP de gestion des nœuds à votre système.

... Ouvrez le lecteur *Network* pour découvrir les nœuds.
... Sélectionnez le nœud pour lancer l'assistant d'installation du cluster.


** Ordinateur non Windows
+
... Mettez tous les nœuds que vous ajoutez au cluster sous tension.
+
Ceci est nécessaire pour activer la détection de votre compteur de clusters.

... Se connecter à la console du premier nœud.
+
Le nœud démarre, puis l'assistant de configuration du cluster démarre sur la console.

+
[listing]
----
Welcome to the cluster setup wizard....
----
... Acceptez la déclaration AutoSupport.
+
[listing]
----
Type yes to confirm and continue {yes}: yes
----
+
AutoSupport est activé par défaut.

... Suivez les instructions à l'écran pour attribuer une adresse IP de gestion au nœud.
... Dans un navigateur Web, entrez l'adresse IP de gestion des nœuds que vous avez configurée : "https://node-management-IP"[].
+
System Manager détecte automatiquement les nœuds restants dans le cluster.





. Sous *initialiser le système de stockage*, entrez le nom du cluster et le mot de passe admin.
. Sous *réseau*, entrez l'adresse IP, le masque de sous-réseau et la passerelle de gestion du cluster.
. Si vous souhaitez utiliser le service de nom de domaine pour résoudre les noms d'hôte, sélectionnez *utiliser le service de nom de domaine (DNS)*, puis entrez les informations sur le serveur DNS.
. Si vous souhaitez utiliser le protocole NTP (Network Time Protocol) pour maintenir la synchronisation des heures dans votre cluster, sous *autres*, sélectionnez *utiliser les services de temps (NTP)*, puis entrez les informations du serveur NTP.
. Sélectionnez *soumettre*.


--
.INTERFACE DE LIGNE DE COMMANDES DE ONTAP
--
. Mettez tous les nœuds que vous ajoutez au cluster sous tension.
+
Cela est nécessaire pour activer la détection pour la configuration de votre cluster.

. Se connecter à la console du premier nœud.
+
Le nœud démarre, puis l'assistant de configuration du cluster démarre sur la console.

+
[listing]
----
Welcome to the cluster setup wizard....
----
. Acceptez la déclaration AutoSupport.
+
[listing]
----
Type yes to confirm and continue {yes}: yes
----
+
AutoSupport est activé par défaut.

. Suivez les instructions à l'écran pour attribuer une adresse IP de gestion au nœud.
+
À partir de ONTAP 9.13.1, vous pouvez attribuer des adresses IPv6 pour les LIF de gestion sur les plateformes A800 et FAS8700. Pour les versions ONTAP antérieures à 9.13.1, ou pour la version 9.13.1 et ultérieures sur d'autres plateformes, vous devez attribuer des adresses IPv4 pour les LIF de gestion, puis les convertir en IPv6 une fois que vous avez terminé la configuration du cluster.

. Appuyez sur *entrée* pour continuer.
+
[listing]
----
Do you want to create a new cluster or join an existing cluster? {create, join}:
----
. Créez un nouveau cluster :
+
.. Entrée `create`
.. Acceptez les valeurs par défaut du système ou entrez vos propres valeurs.
.. Une fois la configuration terminée, connectez-vous au cluster et vérifiez que le cluster est actif et que le premier nœud fonctionne correctement : `cluster show`
+
L'exemple suivant montre un cluster dans lequel le premier nœud (cluster 1-01) est sain et peut participer :

+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
cluster1-01           true    true
----
+
Si besoin, vous pouvez utiliser `cluster setup` la commande pour accéder à l'assistant Cluster Setup et modifier les valeurs saisies pour le SVM admin ou node.



. Joindre un nœud au cluster :
+
Vous pouvez joindre un nœud au cluster à la fois. Vous devez terminer l'opération de jointure pour chaque nœud et le nœud doit faire partie du cluster avant de pouvoir commencer à rejoindre le nœud suivant.

+
Si vous disposez d'un FAS2720 avec 24 disques NL-SAS ou moins, vérifiez que la configuration de stockage par défaut est définie sur actif/passif pour optimiser les performances. Pour plus d'informations, reportez-vous à la documentation link:../disks-aggregates/setup-active-passive-config-root-data-task.html["configuration d'une configuration actif-passif sur les nœuds à l'aide du partitionnement données-racines"]de .

+
.. Connectez-vous au nœud que vous prévoyez de joindre au cluster.
+
L'assistant de configuration du cluster démarre sur la console.

+
[listing]
----
Welcome to the cluster setup wizard....
----
.. Acceptez la déclaration AutoSupport.
+

NOTE: AutoSupport est activé par défaut.



+
[listing]
----
Type yes to confirm and continue {yes}: yes
----
+
.. Suivez les instructions à l'écran pour attribuer une adresse IP au nœud.
+
À partir de ONTAP 9.13.1, vous pouvez attribuer des adresses IPv6 pour les LIF de gestion sur les plateformes A800 et FAS8700. Pour les versions ONTAP antérieures à 9.13.1, ou pour la version 9.13.1 et ultérieures sur d'autres plateformes, vous devez attribuer des adresses IPv4 pour les LIF de gestion, puis les convertir en IPv6 une fois que vous avez terminé la configuration du cluster.

.. Appuyez sur *entrée* pour continuer.
+
[listing]
----
Do you want to create a new cluster or join an existing cluster? {create, join}:
----
.. Entrée `join`
.. Suivez les instructions à l'écran pour configurer le nœud et le joindre au cluster.
.. Une fois la configuration terminée, vérifiez que le nœud fonctionne correctement et qu'il est éligible pour participer au cluster : `cluster show`
+
L'exemple suivant montre un cluster après le rattachement du second nœud (cluster1-02) au cluster :

+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
cluster1-01           true    true
cluster1-02           true    true
----


. Répétez l'étape 7 pour joindre chaque nœud restant.


--
====
.Et la suite
* Si besoin, link:convert-ipv4-to-ipv6-task.html["Convertir d'IPv4 en IPv6"].
* link:task_check_cluster_with_config_advisor.html["Exécutez Active IQ Config Advisor pour valider votre configuration et vérifier les erreurs de configuration courantes"].

