---
permalink: software_setup/task_create_the_cluster_on_the_first_node.html 
sidebar: sidebar 
keywords: ontap, software, setup, create, cluster, first, node, autosupport, CLI 
summary: 'Vous utilisez l"assistant de configuration du cluster pour créer le cluster sur le premier nœud. L"assistant vous aide à configurer le réseau de cluster qui connecte les nœuds \(si le cluster se compose de deux ou plusieurs nœuds\), à créer le cluster admin Storage Virtual machine \(SVM\), à ajouter des clés de licence de fonctionnalité et à créer l"interface de gestion des nœuds pour le premier nœud.' 
---
= Créer le cluster sur le premier nœud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous utilisez l'assistant de configuration du cluster pour créer le cluster sur le premier nœud. L'assistant vous aide à configurer le réseau de cluster qui connecte les nœuds, à créer le SVM (Cluster admin Storage Virtual machine), à ajouter des clés de licence de fonction et à créer l'interface de gestion des nœuds pour le premier nœud.

. Mettez tous les nœuds que vous ajoutez au cluster sous tension. Cela est nécessaire pour activer la détection pour la configuration de votre cluster.
. Se connecter à la console du premier nœud.
+
Le nœud démarre, puis l'assistant de configuration du cluster démarre sur la console.

+
[listing]
----
Welcome to the cluster setup wizard....
----
. Acceptez la déclaration AutoSupport.
+
[listing]
----
Type yes to confirm and continue {yes}: yes
----
+

NOTE: AutoSupport est activé par défaut.

. Suivez les instructions à l'écran pour attribuer une adresse IP au nœud.
. Si vous utilisez l'assistant de l'interface utilisateur graphique pour effectuer la configuration, suivez les instructions pour terminer l'installation dans votre navigateur Web. Si vous utilisez l'assistant CLI pour effectuer la configuration, appuyez sur entrée pour continuer.
+
[listing]
----
Use your web browser to complete cluster setup by accessing
https://10.63.11.29

Otherwise, press Enter to complete cluster setup using the
command line interface:

Do you want to create a new cluster or join an existing cluster? {create, join}:
----
. Créez un nouveau cluster : `create`
. Acceptez les valeurs par défaut du système ou entrez vos propres valeurs.
. Une fois l'installation terminée, connectez-vous au cluster et vérifiez que le cluster est actif et que le premier nœud fonctionne correctement en entrant la commande CLI ONTAP : `cluster show`
+
L'exemple suivant montre un cluster dans lequel le premier nœud (cluster 1-01) est sain et peut participer :

+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
cluster1-01           true    true
----
+
Pour modifier les valeurs saisies pour le SVM admin ou le SVM node, il est possible d'accéder à l'assistant Cluster Setup en utilisant le `cluster setup` commande.


