---
permalink: software_setup/task_configure_important_ems_events_to_forward_notifications_to_a_syslog_server.html 
sidebar: sidebar 
keywords: ontap, software, setup, configure, important,ems, events, forward, notifications, syslog, server 
summary: 'Pour enregistrer les notifications des événements les plus graves sur un serveur syslog, vous devez configurer l"EMS pour transférer les notifications des événements qui signalent une activité importante.' 
---
= Configurez les événements EMS importants pour transférer des notifications à un serveur syslog
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour enregistrer les notifications des événements les plus graves sur un serveur syslog, vous devez configurer l'EMS pour transférer les notifications des événements qui signalent une activité importante.

Le DNS doit être configuré sur le cluster pour résoudre le nom du serveur syslog.

Si votre environnement ne contient pas encore de serveur syslog pour les notifications d'événements, vous devez d'abord en créer un. Si votre environnement contient déjà un serveur syslog pour la journalisation des événements à partir d'autres systèmes, vous pouvez l'utiliser pour les notifications d'événements importantes.

Vous pouvez effectuer cette tâche à tout moment du cluster en entrant les commandes sur la ligne de commande ONTAP.

. Créer une destination de serveur syslog pour les événements importants :
+
`event notification destination create -name syslog-ems -syslog syslog-server-address`

. Configurez les événements importants pour transférer des notifications au serveur syslog :
+
`event notification create -filter-name important-events -destinations syslog-ems`


