---
permalink: software_setup/task_synchronize_the_system_time_across_the_cluster.html 
sidebar: sidebar 
keywords: ontap, software, setup, synchronize, system, time, across, cluster 
summary: 'La synchronisation de l"heure garantit que chaque nœud du cluster est à la même heure et empêche les défaillances CIFS et Kerberos.' 
---
= Synchronisation de l'heure du système sur le cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La synchronisation de l'heure garantit que chaque nœud du cluster est à la même heure et empêche les défaillances CIFS et Kerberos.

Un serveur NTP (Network Time Protocol) doit être configuré sur votre site. Depuis ONTAP 9.5, vous pouvez configurer votre serveur NTP avec une authentification symétrique. Pour plus d'informations, voir link:https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sag/GUID-1E923D05-447D-4323-8D87-12B82F49B6F1.html?cp=4_7_6["Gestion de l'heure du cluster (administrateurs du cluster uniquement)"].

Vous synchronisez l'heure sur le cluster en associant le cluster à un ou plusieurs serveurs NTP.

. Vérifiez que le fuseau horaire et l'heure du système sont correctement définis pour chaque nœud.
+
Tous les nœuds du cluster doivent être définis sur le même fuseau horaire.

+
.. Utilisez la commande cluster date show pour afficher la date, l'heure et le fuseau horaire actuels pour chaque nœud.
+
[listing]
----
cluster1::> cluster date show
Node         Date                Time zone
------------ ------------------- -----------------
cluster1-01  01/06/2015 09:35:15 America/New_York
cluster1-02  01/06/2015 09:35:15 America/New_York
cluster1-03  01/06/2015 09:35:15 America/New_York
cluster1-04  01/06/2015 09:35:15 America/New_York
4 entries were displayed.
----
.. Utiliser la commande cluster date modify pour modifier le fuseau horaire ou la date de tous les nœuds.
+
Cet exemple modifie le fuseau horaire du cluster en GMT :

+
[listing]
----
cluster1::> cluster date modify -timezone GMT
----


. Utilisez la commande cluster Time-service NTP Server create pour associer le cluster à votre serveur NTP.
+
** Pour configurer votre serveur NTP sans authentification symétrique, entrez la commande suivante : `cluster time-service ntp server create -server server_name`
** Pour configurer votre serveur NTP avec une authentification symétrique, entrez la commande suivante : `cluster time-service ntp server create -server server_ip_address -key-id key_id`
+

NOTE: L'authentification symétrique est disponible à partir de ONTAP 9.5. Elle n'est pas disponible dans ONTAP 9.4 ou version antérieure.

+
Cet exemple suppose que le DNS a été configuré pour le cluster. Si vous n'avez pas configuré de DNS, vous devez spécifier l'adresse IP du serveur NTP :

+
[listing]
----
cluster1::> cluster time-service ntp server create -server ntp1.example.com
----


. Vérifiez que le cluster est associé à un serveur NTP : `cluster time-service ntp server show`
+
[listing]
----
cluster1::> cluster time-service ntp server show
Server               Version
-------------------- -----------
ntp1.example.com     auto
----


.Informations associées
link:../system-admin/index.html["Administration du système"]
