---
permalink: software_setup/task_decide_where_to_send_important_event_notifications.html 
sidebar: sidebar 
keywords: ontap, software, setup, decide, where, send, important, event, notifications 
summary: 'Avant de configurer les notifications importantes d"événements EMS, vous devez décider d"envoyer les notifications à une adresse e-mail, un serveur syslog ou un Traphost SNMP.' 
---
= Choisissez où envoyer les notifications d'événements importants
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de configurer les notifications importantes d'événements EMS, vous devez décider d'envoyer les notifications à une adresse e-mail, un serveur syslog ou un Traphost SNMP.

Si votre environnement contient déjà un serveur syslog permettant d'agréger les événements journaux d'autres systèmes, tels que des serveurs et des applications, il est plus facile d'utiliser ce serveur syslog également pour recevoir des notifications d'événements importantes provenant des systèmes de stockage.

Si votre environnement ne contient pas encore de serveur syslog, il est plus facile d'utiliser le courrier électronique pour les notifications d'événements importantes.

Si vous transférez déjà des notifications d'événement à un Traphost SNMP, il se peut que vous souhaitiez surveiller ce Traphost pour les événements importants.

* Configurez EMS pour envoyer des notifications d'événement.
+
[cols="2*"]
|===
| Les fonctions que vous recherchez... | Reportez-vous à ceci... 


 a| 
L'EMS doit envoyer des notifications d'événements importantes à une adresse e-mail
 a| 
xref:task_configure_important_ems_events_to_send_email_notifications.html[Configuration des événements EMS importants pour envoyer des notifications par e-mail]



 a| 
L'EMS doit transmettre des notifications d'événements importantes à un serveur syslog
 a| 
xref:task_configure_important_ems_events_to_forward_notifications_to_a_syslog_server.html[Configuration des événements EMS importants pour transférer des notifications à un serveur syslog]



 a| 
Si vous souhaitez que l'EMS envoie des notifications d'événement à un Traphost SNMP
 a| 
xref:task_configure_snmp_traphosts_to_receive_event_notifications.html[Configuration des Traphosts SNMP pour recevoir des notifications d'événement]

|===

