---
permalink: asa/overview.html 
sidebar: sidebar 
keywords: all flash san array, asa, san, array, software, configuration, configure, configuring, setup, set up, limitations, restrictions, nvme, mcc ip, persistent ports, host, settings, utilities, ways to identify 
summary: 'Les baies SAN 100 % Flash NetApp sont disponibles à partir de ONTAP 9.7.  Les systèmes ASAS sont des solutions SAN 100 % Flash basées sur les plateformes NetApp éprouvées de AFF.' 
---
= Présentation de la configuration logicielle des baies SAN 100 % Flash
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Les baies SAN 100 % Flash NetApp sont disponibles à partir de ONTAP 9.7.  Les systèmes ASAS sont des solutions SAN 100 % Flash basées sur les plateformes NetApp éprouvées de AFF.

Les plateformes ASA utilisent une symétrie actif-actif pour les chemins d'accès multiples. Tous les chemins sont optimisés/en mode actif. Ainsi, en cas de basculement de stockage, l'hôte n'a pas besoin d'attendre la transition ALUA des chemins de basculement pour reprendre les E/S. Le délai de basculement est ainsi réduit.



== Configurer un ASA

Les baies SAN 100 % Flash (ASA) suivent la même procédure de configuration que les systèmes non ASA.

System Manager vous guide tout au long des procédures nécessaires pour initialiser votre cluster, créer un niveau local, configurer les protocoles et provisionner le stockage de votre ASA.

xref:../software_setup/concept_decide_whether_to_use_ontap_cli.html[Commencez avec la configuration de clusters ONTAP].



== Utilitaires et paramètres d'hôte ASA

Les paramètres d'hôte pour la configuration des baies SAN 100 % Flash (ASA) sont les mêmes que pour tous les autres hôtes SAN.

Vous pouvez télécharger le link:https://mysupport.netapp.com/NOW/cgi-bin/software["Logiciel NetApp Host Utilities"^] pour vos hôtes spécifiques sur le site de support.



== Méthodes d'identification d'un système ASA

Vous pouvez identifier un système ASA via System Manager ou l'interface de ligne de commandes de ONTAP.

* *Dans le tableau de bord System Manager* : cliquez sur *Cluster > Présentation*, puis sélectionnez le nœud système.
+
La *PERSONNALITÉ* s'affiche sous la forme *Baie SAN 100 % Flash*.

* *À partir de l'interface CLI* : entrez le `san config show` commande.
+
La valeur « Baie SAN 100 % Flash » est renvoyée pour les systèmes ASA.



.Informations associées
* link:https://www.netapp.com/pdf.html?item=/media/85671-tr-4968.pdf["Rapport technique 4968 : disponibilité et intégrité des données des baies SAN 100 % Flash de NetApp"^]
* link:http://www.netapp.com/us/media/tr-4080.pdf["Rapport technique 4080 : meilleures pratiques pour un SAN évolutif ONTAP 9"^]

