---
permalink: asa/support-limitations.html 
sidebar: sidebar 
keywords: all san array, asa, san, array, software, configuration, configure, configuring, setup, set up, limitations, restrictions, nvme, mcc ip, persistent ports, host, settings, utilities, ways to identify 
summary: 'Utilisez les procédures suivantes pour configurer une matrice SAN à l"aide de System Manager.' 
---
= Prise en charge de toutes les limites de configuration et de toutes les baies SAN
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Les limites de configuration et la prise en charge de ASA varient en fonction de la version de ONTAP.

Les détails les plus récents sur les limites de configuration prises en charge sont disponibles dans link:https://hwu.netapp.com/["NetApp Hardware Universe"^].



== Protocoles et nœuds SAN par cluster

La prise en charge ASA des protocoles SAN et des nœuds par cluster est la suivante :

[cols="3*"]
|===


| Depuis ONTAP... | Protocoles pris en charge | Nombre max. De nœuds par cluster 


| 9.12.1  a| 
* NVMe (pris en charge sur les configurations IP MetroCluster à 4 nœuds et les configurations IP non MetroCluster)
* FC
* ISCSI

| 12 


| 9.9.1  a| 
* NVMe (pris en charge sur les configurations IP non-MetroCluster)
* FC
* ISCSI

 a| 
* 12 nœuds (pour les configurations IP non MetroCluser)
* 8 nœuds (pour les configurations MetroCluster IP)




| 9.7  a| 
* FC
* ISCSI

| 4 
|===


== Prise en charge des ports persistants

Depuis ONTAP 9.8, les ports persistants sont activés par défaut sur toutes les baies SAN (ASAS) configurées pour utiliser le protocole FC. Les ports persistants sont uniquement disponibles pour FC et requièrent l'appartenance de zone identifiée par WWPN (World Wide Port Name).

Les ports persistants réduisent l'impact des conversions en créant une LIF « shadow » sur le port physique correspondant du partenaire de haute disponibilité. Lorsqu'un nœud est repris, la LIF shadow sur le nœud partenaire assume l'identité du LIF d'origine, y compris le WWPNe. Avant que le chemin d'accès au nœud mis en service ne soit modifié en défectueux, le shadow LIF apparaît sous la forme d'un chemin actif-optimisé vers la pile MPIO hôte, ainsi que de transferts d'E/S. Cela réduit les perturbations d'E/S car l'hôte voit toujours le même nombre de chemins vers la cible, même lors des opérations de basculement de stockage.

Pour les ports persistants, les caractéristiques de port FCP suivantes doivent être identiques dans la paire haute disponibilité :

* Nombre de ports FCP
* Noms des ports FCP
* Vitesses du port FCP
* Segmentation basée sur le WWPN FCP LIF


Si l'une de ces caractéristiques n'est pas identique au sein de la paire HA, le message EMS suivant est généré :

`EMS : scsiblade.lif.persistent.ports.fcp.init.error`

Pour plus d'informations sur les ports persistants, voir link:http://www.netapp.com/us/media/tr-4080.pdf["Rapport technique de NetApp 4080 : meilleures pratiques pour les environnements SAN évolutifs ONTAP 9"^].
