---
sidebar: sidebar 
permalink: high-availability/ha-pair-encryption.html 
keywords: cluster network, encryption, TLS, data-in-flight 
summary: Configurer la communication chiffrée entre les nœuds de la paire HA 
---
= Configurer le chiffrement du trafic ONTAP HA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À partir d' ONTAP 9.18.1, vous pouvez configurer le chiffrement du trafic réseau entre les nœuds de paires à haute disponibilité (HA).  Ce chiffrement protège les données client et les métadonnées transmises entre les nœuds d'une paire HA.

.Description de la tâche
* Le chiffrement du trafic HA est désactivé par défaut.
* L'activation ou la désactivation du chiffrement du trafic HA affecte toutes les paires HA du cluster.  Vous ne pouvez pas activer ou désactiver le chiffrement pour des nœuds individuels.
* Lorsque vous activez le chiffrement du trafic HA, toutes les données client et les métadonnées transmises entre les nœuds de la paire HA sont chiffrées.  Certains flux de données HA, tels que les métadonnées du système de fichiers et les messages de pulsation, ne sont pas chiffrés.
* Lorsque le chiffrement du trafic HA est activé et que de nouvelles paires HA sont ajoutées au cluster, vous devez activer manuellement le chiffrement du trafic HA pour les nouveaux nœuds en réexécutant la commande. `security ha-network modify -enabled true` commande.


.Avant de commencer
* Vous devez être administrateur ONTAP au niveau `admin` niveau de privilège requis pour effectuer la procédure suivante.
* Avant d'activer le chiffrement du trafic HA, vous devezlink:../encryption-at-rest/configure-external-key-management-concept.html["Configurez la gestion externe des clés"] .
* Tous les nœuds du cluster doivent exécuter ONTAP 9.18.1 ou une version ultérieure pour activer le chiffrement du trafic HA.


.Étapes
. Consultez l'état actuel du chiffrement pour le trafic HA :
+
[source, cli]
----
security ha-network show
----
+
Cette commande affiche l'état actuel du chiffrement du trafic HA pour chaque nœud :

+
[source]
----
security ha-network show
Node                  Enabled
--------------------- --------------------
node1                 true
node2                 true
node3                 true
node4                 true
4 entries were displayed.
----
. Activer ou désactiver le chiffrement pour le trafic HA :


[source, cli]
----
security ha-network modify -enabled <true|false>
----
Cette commande active ou désactive le trafic HA chiffré pour tous les nœuds du cluster.  Lorsque de nouvelles paires HA sont ajoutées au cluster, vous devrez réexécuter cette commande pour activer le chiffrement du trafic HA pour les nouveaux nœuds.
