---
sidebar: sidebar 
permalink: high-availability/halt-reboot-node-wo-takeover-task.html 
keywords: high availability pair, hair, inhibit-takeover, reboot, epsilon, HA 
summary: 'Vous arrêtez ou redémarrez un nœud dans un cluster à deux nœuds sans passer par le basculement lorsque vous effectuez certaines opérations de maintenance matérielle sur un nœud ou un tiroir. Vous pouvez également limiter les temps d"indisponibilité en maintenant le nœud partenaire en fonctionnement, en cas de problème empêchant un basculement manuel, vous devez également maintenir les agrégats du nœud partenaire et assurer le service des données. De plus, si le support technique vous aide à résoudre les problèmes, il se peut que vous deviez effectuer cette procédure dans le cadre de ces efforts.' 
---
= Arrêter ou redémarrer les nœuds ONTAP sans lancer de prise de contrôle dans les clusters à deux nœuds
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous arrêtez ou redémarrez un nœud dans un cluster à deux nœuds sans passer par le basculement lorsque vous effectuez certaines opérations de maintenance matérielle sur un nœud ou un tiroir. Vous pouvez également limiter les temps d'indisponibilité en maintenant le nœud partenaire en fonctionnement, en cas de problème empêchant un basculement manuel, vous devez également maintenir les agrégats du nœud partenaire et assurer le service des données. De plus, si le support technique vous aide à résoudre les problèmes, il se peut que vous deviez effectuer cette procédure dans le cadre de ces efforts.

.Description de la tâche
* Avant de désactiver le basculement (à l'aide du `-inhibit-takeover true` Paramètre), vous désactivez le cluster HA.


[CAUTION]
====
* Dans un cluster à deux nœuds, la haute disponibilité du cluster permet de s'assurer que la défaillance d'un nœud ne désactive pas le cluster. Toutefois, si vous ne désactivez pas la haute disponibilité du cluster avant d'utiliser  `-inhibit-takeover true` paramètre, le service des données n'est plus servi sur les deux nœuds.
* Si vous tentez d'arrêter ou de redémarrer un nœud avant de désactiver la haute disponibilité du cluster, ONTAP émet un avertissement et vous indique de désactiver la haute disponibilité du cluster.


====
* Vous migrez les LIF (interfaces logiques) vers le nœud partenaire que vous souhaitez conserver en ligne.
* Si sur le nœud que vous arrête ou redémarrez, des agrégats doivent être conservés, vous les déplacez vers le nœud que vous souhaitez conserver en ligne.


.Étapes
. Vérifiez que les deux nœuds sont en bon état :
+
[source, cli]
----
cluster show
----
+
Pour les deux nœuds, `true` s'affiche dans le `Health` colonne.

+
[listing]
----
cluster::> cluster show
Node         Health  Eligibility
------------ ------- ------------
node1        true     true
node2        true     true
----
+
Pour en savoir plus, `cluster show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/cluster-show.html["Référence de commande ONTAP"^].

. Migrez toutes les LIF du nœud que vous allez arrêter ou redémarrer vers le nœud partenaire :
+
[source, cli]
----
network interface migrate-all -node <node_name>
----
+
Pour en savoir plus, `network interface migrate-all` consultez le link:https://docs.netapp.com/us-en/ontap-cli/network-interface-migrate-all.html["Référence de commande ONTAP"^].

. Si le nœud comporte des agrégats que vous allez arrêter ou redémarrer et que vous souhaitez maintenir en ligne lorsque le nœud est hors service, déplacez-les vers le nœud partenaire.
+
.. Afficher les agrégats sur le nœud que vous allez arrêter ou redémarrer :
+
[source, cli]
----
storage aggregates show -node <node_name>
----
+
Par exemple, le nœud 1 est le nœud qui sera arrêté ou redémarré :

+
[listing]
----
cluster::> storage aggregates show -node node1
Aggregate  Size  Available  Used%  State  #Vols   Nodes   RAID  Status
---------  ----  ---------  -----  -----  -----   -----   ----  ------
aggr0_node_1_0
           744.9GB   32.68GB   96% online       2 node1    raid_dp,
                                                                normal
aggr1       2.91TB    2.62TB   10% online       8 node1    raid_dp,
                                                                normal
aggr2
            4.36TB    3.74TB   14% online      12 node1    raid_dp,
                                                                normal
test2_aggr  2.18TB    2.18TB    0% online       7 node1    raid_dp,
                                                                normal
4 entries were displayed.
----
.. Déplacez les agrégats vers le nœud partenaire :
+
[source, cli]
----
storage aggregate relocation start -node <node_name> -destination <node_name> -aggregate-list <aggregate_name>
----
+
Par exemple, les agrégats aggr1, aggr2 et test2_aggr sont déplacés du nœud 1 vers le nœud 2 :

+
`storage aggregate relocation start -node _node1_ -destination _node2_ -aggregate-list _aggr1_,_aggr2_,_test2_aggr_`



. Désactiver la haute disponibilité du cluster :
+
[source, cli]
----
cluster ha modify -configured false
----
+
Lorsque la haute disponibilité du cluster est désactivée, epsilon est automatiquement déplacé vers le nœud 1. La sortie de retour confirme que la haute disponibilité est désactivée : `Notice: HA is disabled`

+

NOTE: Cette opération ne désactive pas le basculement du stockage.

. Si le nœud à arrêter ou à redémarrer est le nœud 1, déplacez epsilon vers le nœud 2 :
+
.. Définissez le niveau de privilège sur avancé :
+
[source, cli]
----
set -privilege advanced
----
.. Vérifiez que le nœud 2 est sain et éligible pour epsilon:
+
[source, cli]
----
cluster show
----
.. Supprimez epsilon du nœud 1 :
+
[source, cli]
----
cluster modify -node <node1_name> -epsilon false
----
.. Attribuez epsilon au nœud 2 :
+
[source, cli]
----
cluster modify -node <node2_name> -epsilon true
----
.. Vérifiez que epsilon se trouve sur le nœud 2:
+
[source, cli]
----
cluster show
----


. Arrêtez ou redémarrez et empêchez la prise de contrôle du nœud cible :
+
[cols="1h,1h"]
|===


 a| 
Arrêtez le nœud sans initier de prise de contrôle :
 a| 
[source, cli]
----
system node halt -node _node_name_ -inhibit-takeover true
----


 a| 
Redémarrez le nœud sans lancer de prise de contrôle :
 a| 
[source, cli]
----
system node reboot -node _node_name_ -inhibit-takeover true
----
|===
+

NOTE: Dans le résultat de la commande, un avertissement s'affiche vous demandant si vous souhaitez continuer, entrez `y`.

. Vérifiez que le nœud qui reste en ligne est en bon état (pendant que le partenaire est hors service) :
+
[source, cli]
----
cluster show
----
+
Pour le nœud en ligne, `true` s'affiche dans le `Health` colonne.

+

NOTE: Dans le résultat de la commande, vous verrez un avertissement indiquant que le cluster HA n'est pas configuré. Vous pouvez ignorer l'avertissement.

. Exécutez les actions qui vous permettent d'arrêter ou de redémarrer le nœud.
. Démarrez le nœud hors ligne à partir de l'invite LOADER :
+
[source, cli]
----
boot_ontap
----
. Vérifiez que les deux nœuds sont en bon état :
+
[source, cli]
----
cluster show
----
+
Pour les deux nœuds, `true` s'affiche dans le `Health` colonne.

+

NOTE: Dans le résultat de la commande, un avertissement s'affiche indiquant que le cluster HA n'est pas configuré. Vous pouvez ignorer l'avertissement pour le moment.

. Réactivez la haute disponibilité du cluster :
+
[source, cli]
----
cluster ha modify -configured true
----
. Si, plus tôt dans cette procédure, vous avez déplacé des agrégats vers le nœud partenaire, replacez-les sur leur nœud d'origine.
+
[source, cli]
----
storage aggregate relocation start -node <node_name> -destination <node_name> -aggregate-list <aggregate_name>
----
+
Par exemple, les agrégats aggr1, aggr2 et test2_aggr sont déplacés du nœud node2 vers le nœud node1 :
`storage aggregate relocation start -node _node2_ -destination _node1_ -aggregate-list _aggr1_,_aggr2_,_test2_aggr_`

. Rerestaurez les LIF sur leurs home ports :
+
.. Afficher les LIF qui ne sont pas à domicile :
+
[source, cli]
----
network interface show -is-home false
----
+
Pour en savoir plus, `network interface show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["Référence de commande ONTAP"^].

.. Si certaines LIF ne se trouvent pas chez soi et n'ont pas été migrées depuis le nœud défaillant, vérifiez qu'il est sûr de les déplacer avant le rétablissement.
.. Si cela ne présente aucun danger, ramenez tous les LIF à leur emplacement d'origine.
+
[source, cli]
----
 network interface revert *
----
+
Pour en savoir plus, `network interface revert` consultez le link:https://docs.netapp.com/us-en/ontap-cli/network-interface-revert.html["Référence de commande ONTAP"^].





.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/cluster-ha-modify.html["modification de la haute disponibilité du cluster"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-relocation-start.html["début de la relocalisation des agrégats de stockage"^]

