---
permalink: nas-audit/connect-external-fpolicy-servers-task.html 
sidebar: sidebar 
keywords: connect, external fpolicy servers 
summary: 'Pour activer le traitement de fichiers, vous devrez peut-être vous connecter manuellement à un serveur FPolicy externe si la connexion a déjà été interrompue. Une connexion est interrompue une fois le délai d"expiration du serveur atteint ou en raison d"une erreur. L"administrateur peut également mettre fin manuellement à une connexion.' 
---
= Connectez-vous à des serveurs FPolicy externes dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour activer le traitement de fichiers, vous devrez peut-être vous connecter manuellement à un serveur FPolicy externe si la connexion a déjà été interrompue. Une connexion est interrompue une fois le délai d'expiration du serveur atteint ou en raison d'une erreur. L'administrateur peut également mettre fin manuellement à une connexion.

.Description de la tâche
En cas d'erreur fatale, la connexion au serveur FPolicy peut être interrompue. Après avoir résolu le problème à l'origine de l'erreur fatale, vous devez vous reconnecter manuellement au serveur FPolicy.

.Étapes
. Connectez-vous au serveur FPolicy externe à l'aide de `vserver fpolicy engine-connect` commande.
+
Pour en savoir plus, `vserver fpolicy engine-connect` consultez le link:https://docs.netapp.com/us-en/ontap-cli/vserver-fpolicy-engine-connect.html["Référence de commande ONTAP"^].

. Vérifiez que le serveur FPolicy externe est connecté à l'aide du `vserver fpolicy show-engine` commande.
+
Pour en savoir plus, `vserver fpolicy show-engine` consultez le link:https://docs.netapp.com/us-en/ontap-cli/vserver-fpolicy-show-engine.html["Référence de commande ONTAP"^].


