---
permalink: nas-audit/create-fpolicy-event-task.html 
sidebar: sidebar 
keywords: creating, fpolicy event 
summary: 'Dans le cadre de la configuration de règles FPolicy, vous devez créer un événement FPolicy. Lors de sa création, vous associez l"événement à la politique FPolicy. Un événement définit le protocole à surveiller et les événements d"accès aux fichiers à surveiller et à filtrer.' 
---
= Créez l'événement FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dans le cadre de la configuration de règles FPolicy, vous devez créer un événement FPolicy. Lors de sa création, vous associez l'événement à la politique FPolicy. Un événement définit le protocole à surveiller et les événements d'accès aux fichiers à surveiller et à filtrer.

.Avant de commencer
Vous devez terminer l'événement FPolicy link:../nas-audit/fpolicy-event-config-worksheet-reference.html["feuille de calcul"].



== Créez l'événement FPolicy

. Créez l'événement FPolicy à l'aide de `vserver fpolicy policy event create` commande.
+
`vserver fpolicy policy event create -vserver vs1.example.com -event-name event1 -protocol cifs -file-operations open,close,read,write`

. Vérifiez la configuration d'événement FPolicy à l'aide de `vserver fpolicy policy event show` commande.
+
`vserver fpolicy policy event show -vserver vs1.example.com`

+
[listing]
----

                  Event               File                    Is Volume
Vserver           Name      Protocols Operations    Filters   Operation
---------------   --------- --------- ------------- --------- ------------
vs1.example.com   event1    cifs      open, close,  -         false
                                      read, write
----




== Créez les événements de refus d'accès FPolicy

À partir de ONTAP 9.13.1, les utilisateurs peuvent recevoir des notifications en cas d'échec des opérations sur les fichiers en raison d'un manque d'autorisations. Ces notifications sont précieuses pour la sécurité, la protection contre les ransomware et la gouvernance.

. Créez l'événement FPolicy à l'aide de `vserver fpolicy policy event create` commande.
+
`vserver fpolicy policy event create -vserver vs1.example.com -event-name event1 -protocol cifs -monitor-fileop-failure true -file-operations open`


