---
permalink: nas-audit/create-security-traces-concept.html 
sidebar: sidebar 
keywords: considerations, create, security traces 
summary: 'Lorsque vous créez des traces de sécurité sur des machines virtuelles de stockage (SVM), tenez compte de plusieurs points à prendre en compte. Par exemple, vous devez savoir quels protocoles vous pouvez créer une trace, quels styles de sécurité sont pris en charge et quel est le nombre maximum de traces actives.' 
---
= Considérations lors de la création de traces de sécurité sur les SVM ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous créez des traces de sécurité sur des machines virtuelles de stockage (SVM), tenez compte de plusieurs points à prendre en compte. Par exemple, vous devez savoir quels protocoles vous pouvez créer une trace, quels styles de sécurité sont pris en charge et quel est le nombre maximum de traces actives.

* Vous ne pouvez créer que des traces de sécurité sur des SVM.
* Chaque entrée de filtre de trace de sécurité est spécifique au SVM.
+
On doit spécifier le SVM sur lequel vous souhaitez exécuter le tracé.

* Vous pouvez ajouter des filtres de suivi des permissions pour les requêtes SMB et NFS.
* On doit configurer le serveur SMB ou NFS sur le SVM sur lequel vous souhaitez créer des filtres de trace.
* Vous pouvez créer des traces de sécurité pour les fichiers et les dossiers résidant sur NTFS, UNIX, ainsi que sur des volumes et des qtrees de type sécurité mixtes.
* Vous pouvez ajouter un maximum de 10 filtres de suivi des permissions par SVM.
* Vous devez spécifier un numéro d'index de filtre lors de la création ou de la modification d'un filtre.
+
Les filtres sont pris en compte dans l'ordre du numéro d'index. Les critères d'un filtre avec un numéro d'index plus élevé sont pris en compte avant les critères avec un nombre d'index plus faible. Si la demande suivie correspond aux critères de plusieurs filtres activés, seul le filtre dont le numéro d'index est le plus élevé est déclenché.

* Une fois que vous avez créé et activé un filtre de trace de sécurité, vous devez exécuter des demandes de fichier ou de dossier sur un système client pour générer l'activité que le filtre de trace peut capturer et ouvrir une session dans le journal des résultats de trace.
* Vous devez ajouter des filtres de suivi des autorisations pour la vérification de l'accès aux fichiers ou le dépannage uniquement.
+
L'ajout de filtres de suivi des autorisations a un effet mineur sur les performances du contrôleur.

+
Lorsque vous avez terminé l'activité de vérification ou de dépannage, vous devez désactiver ou supprimer tous les filtres de suivi des autorisations. En outre, les critères de filtrage que vous sélectionnez doivent être aussi spécifiques que possible pour que ONTAP n'envoie pas un grand nombre de résultats de trace au journal.


