---
permalink: nas-audit/delete-security-trace-filters-task.html 
sidebar: sidebar 
keywords: delete, security trace filters 
summary: 'Lorsque vous n"avez plus besoin d"une entrée de filtre de trace de sécurité, vous pouvez la supprimer. Étant donné que vous pouvez disposer d"un maximum de 10 filtres de suivi de sécurité par machine virtuelle de stockage (SVM), la suppression des filtres inutiles vous permet de créer de nouveaux filtres si vous avez atteint le maximum.' 
---
= Supprimer les filtres de trace de sécurité
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous n'avez plus besoin d'une entrée de filtre de trace de sécurité, vous pouvez la supprimer. Étant donné que vous pouvez disposer d'un maximum de 10 filtres de suivi de sécurité par machine virtuelle de stockage (SVM), la suppression des filtres inutiles vous permet de créer de nouveaux filtres si vous avez atteint le maximum.

Pour identifier de manière unique le filtre de trace de sécurité que vous souhaitez supprimer, vous devez spécifier les éléments suivants :

* Nom du SVM auquel le filtre de trace est appliqué
* Numéro d'index du filtre de trace


.Étapes
. Identifiez le numéro d'index de filtre de l'entrée de filtre de trace de sécurité que vous souhaitez supprimer :
+
`vserver security trace filter show -vserver vserver_name`

+
`vserver security trace filter show -vserver vs1`

+
[listing]
----

Vserver  Index   Client-IP            Path            Trace-Allow  Windows-Name
-------- -----  -----------  ----------------------   -----------  -------------
vs1        1    -            /dir1/dir2/file.txt          yes      -
vs1        2    -            /dir3/dir4/                  no       mydomain\joe
----
. À l'aide des informations de numéro d'index de filtre de l'étape précédente, supprimez l'entrée de filtre :
+
`vserver security trace filter delete -vserver vserver_name -index index_number`

+
`vserver security trace filter delete -vserver vs1 -index 1`

. Vérifiez que l'entrée du filtre de trace de sécurité est supprimée :
+
`vserver security trace filter show -vserver vserver_name`

+
`vserver security trace filter show -vserver vs1`

+
[listing]
----

Vserver  Index   Client-IP            Path            Trace-Allow   Windows-Name
-------- -----  -----------  ----------------------   -----------   -------------
vs1        2    -            /dir3/dir4/                  no        mydomain\joe
----

