---
permalink: nas-audit/disconnect-from-external-fpolicy-servers-task.html 
sidebar: sidebar 
keywords: disconnect, external fpolicy servers 
summary: 'Vous devrez peut-être vous déconnecter manuellement d"un serveur FPolicy externe. Cette opération peut être utile si le serveur FPolicy présente des problèmes avec le traitement des demandes de notification ou si vous devez effectuer une maintenance sur le serveur FPolicy.' 
---
= Déconnectez-vous des serveurs FPolicy externes dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devrez peut-être vous déconnecter manuellement d'un serveur FPolicy externe. Cette opération peut être utile si le serveur FPolicy présente des problèmes avec le traitement des demandes de notification ou si vous devez effectuer une maintenance sur le serveur FPolicy.

.Étapes
. Déconnectez-vous du serveur FPolicy externe à l'aide de `vserver fpolicy engine-disconnect` commande.
+
Pour en savoir plus, `vserver fpolicy engine-disconnect` consultez le link:https://docs.netapp.com/us-en/ontap-cli/vserver-fpolicy-engine-disconnect.html["Référence de commande ONTAP"^].

. Vérifiez que le serveur FPolicy externe est déconnecté à l'aide de `vserver fpolicy show-engine` commande.
+
Pour en savoir plus, `vserver fpolicy show-engine` consultez le link:https://docs.netapp.com/us-en/ontap-cli/vserver-fpolicy-show-engine.html["Référence de commande ONTAP"^].


