---
permalink: nas-audit/display-enabled-fpolicy-policies-task.html 
sidebar: sidebar 
keywords: display, information, enabled fpolicy policies 
summary: Vous pouvez afficher des informations sur les règles FPolicy activées pour déterminer le moteur externe FPolicy à utiliser, la priorité de la règle et le SVM associé à la règle FPolicy. 
---
= Affiche des informations sur les règles FPolicy activées
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher des informations sur les règles FPolicy activées pour déterminer le moteur externe FPolicy à utiliser, la priorité de la règle et le SVM associé à la règle FPolicy.

Si vous ne spécifiez aucun paramètre, la commande affiche les informations suivantes :

* Nom du SVM
* Nom de la règle
* Priorité de la stratégie


Vous pouvez utiliser les paramètres de la commande pour filtrer la sortie de la commande par critères spécifiés.

.Étape
. Afficher des informations sur les règles FPolicy activées à l'aide de la commande appropriée :
+
[cols="35,65"]
|===


| Si vous souhaitez afficher des informations sur les stratégies activées... | Entrez la commande... 


 a| 
Sur le cluster
 a| 
`vserver fpolicy show-enabled`



 a| 
Sur un SVM spécifié
 a| 
`vserver fpolicy show-enabled -vserver vserver_name`



 a| 
Avec le nom de la règle spécifiée
 a| 
`vserver fpolicy show-enabled -policy-name policy_name`



 a| 
Avec le numéro de séquence spécifié
 a| 
`vserver fpolicy show-enabled -priority integer`

|===


Les exemples suivants affichent les informations sur les règles FPolicy activées sur le cluster :

[listing]
----
cluster1::> vserver fpolicy show-enabled
Vserver                 Policy Name               Priority

----------------------- ------------------------- ----------
vs1.example.com         pol_native                native
vs1.example.com         pol_native2               native
vs1.example.com         pol1                      2
vs1.example.com         pol2                      4
----