---
permalink: nas-audit/display-fpolicy-passthrough-read-connection-task.html 
sidebar: sidebar 
keywords: display, information, fpolicy, passthrough-read, connection status 
summary: 'Vous pouvez afficher des informations sur l"état de la connexion de passage en lecture FPolicy à des serveurs FPolicy externes pour le cluster ou à un SVM spécifié. Ces informations peuvent vous aider à identifier les serveurs FPolicy dotés de connexions de données de type « passthrough read » et pour lesquels les serveurs FPolicy sont déconnectés.' 
---
= Affiche des informations sur l'état de la connexion de passerelle FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher des informations sur l'état de la connexion de passage en lecture FPolicy à des serveurs FPolicy externes pour le cluster ou à un SVM spécifié. Ces informations peuvent vous aider à identifier les serveurs FPolicy dotés de connexions de données de type « passthrough read » et pour lesquels les serveurs FPolicy sont déconnectés.

.Description de la tâche
Si vous ne spécifiez aucun paramètre, la commande affiche les informations suivantes :

* Nom du SVM
* Nom de la règle FPolicy
* Nom du nœud
* Adresse IP du serveur FPolicy
* État de la connexion de lecture intermédiaire FPolicy


En plus d'afficher les informations relatives aux connexions FPolicy sur le cluster ou un SVM spécifique, vous pouvez utiliser les paramètres de la commande pour filtrer les résultats de la commande par d'autres critères.

Vous pouvez spécifier le `-instance` paramètre pour afficher des informations détaillées sur les règles répertoriées. Vous pouvez également utiliser le `-fields` paramètre pour afficher uniquement les champs indiqués dans la sortie de la commande. Vous pouvez entrer `?` après le `-fields` paramètre pour déterminer les champs que vous pouvez utiliser.

.Étape
. Afficher des informations filtrées sur l'état de connexion entre le nœud et le serveur FPolicy à l'aide de la commande appropriée :
+
[cols="35,65"]
|===


| Pour afficher les informations sur l'état de la connexion... | Entrez la commande... 


 a| 
État de la connexion de lecture « pashrough FPolicy » pour le cluster
 a| 
`vserver fpolicy show-passthrough-read-connection`



 a| 
État de connexion de passerelle FPolicy pour un SVM spécifié
 a| 
`vserver fpolicy show-passthrough-read-connection -vserver vserver_name`



 a| 
État de la connexion de lecture intermédiaire FPolicy pour une règle spécifiée
 a| 
`vserver fpolicy show-passthrough-read-connection -policy-name policy_name`



 a| 
État détaillé de la connexion de lecture intermédiaire FPolicy pour une règle spécifiée
 a| 
`vserver fpolicy show-passthrough-read-connection -policy-name policy_name -instance`



 a| 
État de la connexion de lecture intermédiaire FPolicy pour l'état que vous spécifiez
 a| 
`vserver fpolicy show-passthrough-read-connection -policy-name policy_name -server-status status`     La liste ci-dessous répertorie les différents États du serveur :

** `connected`
** `disconnected`


|===


.Exemple
La commande suivante affiche des informations relatives aux connexions de lecture passerelle de tous les serveurs FPolicy du cluster :

[listing]
----
cluster1::> vserver fpolicy show-passthrough-read-connection
                                            FPolicy           Server
Vserver          Policy Name   Node         Server            Status
---------------  ------------- ------------ ----------------- --------------
vs2.example.com  pol_cifs_2    FPolicy-01   2.2.2.2           disconnected
vs1.example.com  pol_cifs_1    FPolicy-01   1.1.1.1           connected
----
La commande suivante affiche des informations détaillées sur les connexions en lecture pasde serveurs FPolicy configurées dans la politique « Pol_cifs_1 » :

[listing]
----
cluster1::> vserver fpolicy show-passthrough-read-connection -policy-name pol_cifs_1 -instance

                                             Node: FPolicy-01
                                          Vserver: vs1.example.com
                                           Policy: pol_cifs_1
                                           Server: 1.1.1.1
                Session ID of the Control Channel: 8cef052e-2502-11e3-88d4-123478563412
                                    Server Status: connected
      Time Passthrough Read Channel was Connected: 9/24/2013 10:17:45
   Time Passthrough Read Channel was Disconnected: -
Reason for Passthrough Read Channel Disconnection: none
----