---
permalink: nas-audit/display-audit-config-task.html 
sidebar: sidebar 
keywords: display, information, audit configurations 
summary: 'Vous pouvez afficher des informations sur les configurations d"audit. Les informations peuvent vous aider à déterminer si la configuration est celle que vous souhaitez mettre en place pour chaque SVM. Les informations affichées vous permettent également de vérifier si une configuration d"audit est activée.' 
---
= Affiche des informations sur les configurations d'audit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher des informations sur les configurations d'audit. Les informations peuvent vous aider à déterminer si la configuration est celle que vous souhaitez mettre en place pour chaque SVM. Les informations affichées vous permettent également de vérifier si une configuration d'audit est activée.

Vous pouvez afficher des informations détaillées sur les configurations d'audit sur tous les SVM. Vous pouvez également personnaliser les informations affichées dans le résultat en spécifiant des paramètres facultatifs. Si vous ne spécifiez aucun des paramètres facultatifs, les éléments suivants s'affichent :

* Nom du SVM auquel s'applique la configuration d'audit
* État d'audit, qui peut être `true` ou `false`
+
Si l'état d'audit est `true`, l'audit est activé. Si l'état d'audit est `false`, l'audit est désactivé.

* Catégories d'événements à vérifier
* Format du journal d'audit
* Répertoire cible dans lequel le sous-système d'audit stocke les journaux d'audit consolidés et convertis


.Étape
. Affiche des informations sur la configuration d'audit à l'aide du `vserver audit show` commande.
+
Pour plus d'informations sur l'utilisation de la commande, consultez les pages de manuels.



L'exemple suivant affiche un résumé de la configuration d'audit de tous les SVM :

[listing]
----
cluster1::> vserver audit show

 Vserver     State  Event Types Log Format Target Directory
 ----------- ------ ----------- ---------- --------------------
 vs1         false  file-ops    evtx       /audit_log
----
L'exemple suivant affiche, sous forme de liste, toutes les informations de configuration d'audit de tous les SVM :

[listing]
----
cluster1::> vserver audit show -instance

                             Vserver: vs1
                      Auditing state: true
                Log Destination Path: /audit_log
       Categories of Events to Audit: file-ops
                          Log Format: evtx
                 Log File Size Limit: 100MB
        Log Rotation Schedule: Month: -
  Log Rotation Schedule: Day of Week: -
          Log Rotation Schedule: Day: -
         Log Rotation Schedule: Hour: -
       Log Rotation Schedule: Minute: -
                  Rotation Schedules: -
            Log Files Rotation Limit: 0
----