---
permalink: nas-audit/enable-disable-fpolicy-policies-task.html 
sidebar: sidebar 
keywords: enable, disable, fpolicy policies 
summary: 'Vous pouvez activer les règles FPolicy une fois la configuration terminée. L"activation de la stratégie définit sa priorité et lance la surveillance de l"accès aux fichiers pour la stratégie. Vous pouvez désactiver les règles FPolicy pour arrêter la surveillance des accès aux fichiers correspondant à cette règle.' 
---
= Activez ou désactivez les règles FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez activer les règles FPolicy une fois la configuration terminée. L'activation de la stratégie définit sa priorité et lance la surveillance de l'accès aux fichiers pour la stratégie. Vous pouvez désactiver les règles FPolicy pour arrêter la surveillance des accès aux fichiers correspondant à cette règle.

.Avant de commencer
La configuration FPolicy doit être réalisée avant l'activation des règles FPolicy.

.Description de la tâche
* La priorité est utilisée lorsque plusieurs règles sont activées sur la machine virtuelle de stockage (SVM) et qu'une seule règle a souscrit au même événement d'accès aux fichiers.
* Les règles qui utilisent la configuration du moteur natif ont une priorité plus élevée que les règles pour tout autre moteur, quel que soit le numéro de séquence qui leur est attribué lors de l'activation de la stratégie.
* Pour modifier la priorité d'une règle FPolicy, vous devez la désactiver puis la réactiver à l'aide du nouveau numéro de séquence.


.Étape
. Effectuez l'action appropriée :
+
[cols="35,65"]
|===


| Les fonctions que vous recherchez... | Saisissez la commande suivante... 


 a| 
Activez une règle FPolicy
 a| 
`vserver fpolicy enable -vserver-name vserver_name -policy-name policy_name -sequence-number integer`



 a| 
Désactiver une règle FPolicy
 a| 
`vserver fpolicy disable -vserver-name vserver_name -policy-name policy_name`

|===

