---
permalink: nas-audit/enable-disable-auditing-svms-task.html 
sidebar: sidebar 
keywords: enable, disable, audit, svms 
summary: 'Vous pouvez activer ou désactiver l"audit sur les serveurs virtuels de stockage (SVM). Vous pouvez désactiver l"audit des fichiers et des répertoires temporairement. Vous pouvez activer l"audit à tout moment (si une configuration d"audit existe).' 
---
= Activation et désactivation de l'audit sur les SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez activer ou désactiver l'audit sur les serveurs virtuels de stockage (SVM). Vous pouvez désactiver l'audit des fichiers et des répertoires temporairement. Vous pouvez activer l'audit à tout moment (si une configuration d'audit existe).

Avant de pouvoir activer l'audit sur le SVM, la configuration d'audit du SVM doit déjà exister.

La désactivation de l'audit ne supprime pas la configuration d'audit.

.Étapes
. Exécutez la commande appropriée :
+
[cols="35,65"]
|===


| Si vous voulez que l'audit soit... | Entrez la commande... 


 a| 
Activé
 a| 
`vserver audit enable -vserver vserver_name`



 a| 
Désactivé
 a| 
`vserver audit disable -vserver vserver_name`

|===
. Vérifiez que l'audit est dans l'état souhaité :
+
`vserver audit show -vserver vserver_name`



L'exemple suivant permet l'audit du SVM vs1 :

[listing]
----
cluster1::> vserver audit enable -vserver vs1

cluster1::> vserver audit show -vserver vs1

                             Vserver: vs1
                      Auditing state: true
                Log Destination Path: /audit_log
       Categories of Events to Audit: file-ops, cifs-logon-logoff
                          Log Format: evtx
                 Log File Size Limit: 100MB
        Log Rotation Schedule: Month: -
  Log Rotation Schedule: Day of Week: -
          Log Rotation Schedule: Day: -
         Log Rotation Schedule: Hour: -
       Log Rotation Schedule: Minute: -
                  Rotation Schedules: -
            Log Files Rotation Limit: 10
----
L'exemple suivant désactive l'audit pour SVM vs1 :

[listing]
----
cluster1::> vserver audit disable -vserver vs1

                             Vserver: vs1
                      Auditing state: false
                Log Destination Path: /audit_log
       Categories of Events to Audit: file-ops, cifs-logon-logoff
                          Log Format: evtx
                 Log File Size Limit: 100MB
        Log Rotation Schedule: Month: -
  Log Rotation Schedule: Day of Week: -
          Log Rotation Schedule: Day: -
         Log Rotation Schedule: Hour: -
       Log Rotation Schedule: Minute: -
                  Rotation Schedules: -
            Log Files Rotation Limit: 10
----