---
permalink: nas-audit/enable-audit-svm-task.html 
sidebar: sidebar 
keywords: enable, audit, svm 
summary: 'Une fois la configuration d"audit terminée, vous devez activer l"audit sur la machine virtuelle de stockage \(SVM\).' 
---
= Activation de l'audit sur le SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois la configuration d'audit terminée, vous devez activer l'audit sur la machine virtuelle de stockage (SVM).

La configuration d'audit SVM doit déjà exister.

Lorsqu'une configuration SVM Disaster Recovery ID rebuter est démarrée en premier (une fois l'initialisation de SnapMirror terminée) et que le SVM dispose d'une configuration d'audit, ONTAP désactive automatiquement la configuration d'audit. L'audit est désactivé sur le SVM en lecture seule pour empêcher le remplissage des volumes de transit. Vous pouvez activer l'audit uniquement après la rupture de la relation SnapMirror et la SVM est read-write.

.Étape
. Activer l'audit sur le SVM :
+
`vserver audit enable -vserver vserver_name`

+
`vserver audit enable -vserver vs1`


