---
permalink: nas-audit/fpolicy-external-engine-config-worksheet-reference.html 
sidebar: sidebar 
keywords: complete, fpolicy, external engine, configuration, worksheet 
summary: Vous pouvez utiliser cette fiche technique pour enregistrer les valeurs nécessaires lors du processus de configuration du moteur externe FPolicy. Si une valeur de paramètre est requise, vous devez déterminer la valeur à utiliser pour ces paramètres avant de configurer le moteur externe. 
---
= Fiches de configuration complètes du moteur externe ONTAP FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser cette fiche technique pour enregistrer les valeurs nécessaires lors du processus de configuration du moteur externe FPolicy. Si une valeur de paramètre est requise, vous devez déterminer la valeur à utiliser pour ces paramètres avant de configurer le moteur externe.



== Informations concernant la configuration de base d'un moteur externe

Vous devez indiquer si vous souhaitez inclure chaque paramètre dans la configuration du moteur externe, puis enregistrer la valeur des paramètres que vous souhaitez inclure.

[cols="40,20,20,20"]
|===


| Type d'information | Obligatoire | Inclure | Vos valeurs 


 a| 
Nom de la machine virtuelle de stockage (SVM)
 a| 
Oui.
 a| 
Oui.
 a| 



 a| 
Nom du moteur
 a| 
Oui.
 a| 
Oui.
 a| 



 a| 
Serveurs FPolicy principaux
 a| 
Oui.
 a| 
Oui.
 a| 



 a| 
Numéro de port
 a| 
Oui.
 a| 
Oui.
 a| 



 a| 
Serveurs FPolicy secondaires
 a| 
Non
 a| 
 a| 



 a| 
Type de moteur externe
 a| 
Non
 a| 
 a| 



 a| 
Option SSL pour la communication avec le serveur FPolicy externe
 a| 
Oui.
 a| 
Oui.
 a| 



 a| 
Nom de domaine complet du certificat ou nom commun personnalisé
 a| 
Non
 a| 
 a| 



 a| 
Numéro de série du certificat
 a| 
Non
 a| 
 a| 



 a| 
Autorité de certification
 a| 
Non
 a| 
 a| 

|===


== Informations relatives aux paramètres avancés du moteur externe

Pour configurer un moteur externe avec des paramètres avancés, vous devez saisir la commande de configuration en mode Advanced Privilege.

[cols="40,20,20,20"]
|===


| Type d'information | Obligatoire | Inclure | Vos valeurs 


 a| 
Délai d'annulation d'une demande
 a| 
Non
 a| 
 a| 



 a| 
Délai d'abandon d'une demande
 a| 
Non
 a| 
 a| 



 a| 
Intervalle d'envoi des demandes d'état
 a| 
Non
 a| 
 a| 



 a| 
Nombre maximal de requêtes en attente sur le serveur FPolicy
 a| 
Non
 a| 
 a| 



 a| 
Délai de déconnexion d'un serveur FPolicy non réactif
 a| 
Non
 a| 
 a| 



 a| 
Intervalle d'envoi de messages de sauvegarde au serveur FPolicy
 a| 
Non
 a| 
 a| 



 a| 
Nombre maximal de tentatives de reconnexion
 a| 
Non
 a| 
 a| 



 a| 
Taille de la mémoire tampon de réception
 a| 
Non
 a| 
 a| 



 a| 
Taille de la mémoire tampon d'envoi
 a| 
Non
 a| 
 a| 



 a| 
Délai de purge d'un ID de session pendant la reconnexion
 a| 
Non
 a| 
 a| 

|===