---
permalink: nas-audit/fpolicy-scope-worksheet-reference.html 
sidebar: sidebar 
keywords: complete, fpolicy, scope, worksheet 
summary: 'Vous pouvez utiliser cette fiche pour enregistrer les valeurs nécessaires lors du processus de configuration du périmètre FPolicy. Si une valeur de paramètre est requise, vous devez déterminer la valeur à utiliser pour ces paramètres avant de configurer l"étendue FPolicy.' 
---
= Feuilles de travail complètes sur la portée de la politique ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser cette fiche pour enregistrer les valeurs nécessaires lors du processus de configuration du périmètre FPolicy. Si une valeur de paramètre est requise, vous devez déterminer la valeur à utiliser pour ces paramètres avant de configurer l'étendue FPolicy.

Vous devez indiquer si vous souhaitez inclure chaque paramètre dans la configuration de l'étendue FPolicy, puis noter la valeur des paramètres que vous souhaitez inclure.

[cols="40,20,20,20"]
|===


| Type d'information | Obligatoire | Inclure | Vos valeurs 


 a| 
Nom de la machine virtuelle de stockage (SVM)
 a| 
Oui.
 a| 
Oui.
 a| 



 a| 
Nom de la règle
 a| 
Oui.
 a| 
Oui.
 a| 



 a| 
Partages à inclure
 a| 
Non
 a| 
 a| 



 a| 
Partages à exclure
 a| 
Non
 a| 
 a| 



 a| 
Volumes à inclure
 a| 
Non
 a| 
 a| 



 a| 
Volumes à exclure
 a| 
Non
 a| 
 a| 



 a| 
Export-policy à inclure
 a| 
Non
 a| 
 a| 



 a| 
Exporter les règles à exclure
 a| 
Non
 a| 
 a| 



 a| 
Extensions de fichier à inclure
 a| 
Non
 a| 
 a| 



 a| 
Extension de fichier à exclure
 a| 
Non
 a| 
 a| 



 a| 
La vérification de l'extension de fichier sur le répertoire est-elle activée ?
 a| 
Non
 a| 
 a| 

|===