---
permalink: nas-audit/fpolicy-credentials-privileged-data-access-concept.html 
sidebar: sidebar 
keywords: fpolicy, connection, credentials, privileged data access channels 
summary: 'Le serveur FPolicy établit des connexions privilégiées aux données avec les nœuds du cluster grâce à des informations d"identification Windows spécifiques enregistrées avec la configuration FPolicy. SMB est le seul protocole pris en charge pour établir une connexion de canal avec accès aux données privilégié.' 
---
= Comment les identifiants de connexion FPolicy sont utilisés avec les canaux d'accès aux données privilégiés
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le serveur FPolicy établit des connexions privilégiées aux données avec les nœuds du cluster grâce à des informations d'identification Windows spécifiques enregistrées avec la configuration FPolicy. SMB est le seul protocole pris en charge pour établir une connexion de canal avec accès aux données privilégié.

Si le serveur FPolicy nécessite un accès privilégié aux données, les conditions suivantes doivent être remplies :

* Une licence SMB doit être activée sur le cluster.
* Le serveur FPolicy doit fonctionner avec les identifiants configurés dans la configuration FPolicy.


Lors de la connexion à un canal de données, FPolicy utilise les informations d'identification du nom d'utilisateur Windows spécifié. Les données sont accessibles via le partage ONTAP_ADMIN$ par l'administrateur.
