---
permalink: nas-audit/fpolicy-external-fpolicy-servers-concept.html 
sidebar: sidebar 
keywords: fpolicy, works, external fpolicy servers 
summary: 'Une fois FPolicy configuré et activé sur le SVM, FPolicy s"exécute sur chaque nœud auquel le SVM participe. FPolicy est chargé de l"établissement et de la maintenance des connexions avec des serveurs FPolicy externes (serveurs FPolicy), pour le traitement des notifications, ainsi que pour la gestion des messages de notification vers et depuis des serveurs FPolicy.' 
---
= Fonctionnement de FPolicy avec les serveurs FPolicy externes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois FPolicy configuré et activé sur le SVM, FPolicy s'exécute sur chaque nœud auquel le SVM participe. FPolicy est chargé de l'établissement et de la maintenance des connexions avec des serveurs FPolicy externes (serveurs FPolicy), pour le traitement des notifications, ainsi que pour la gestion des messages de notification vers et depuis des serveurs FPolicy.

Dans le cadre de la gestion des connexions, FPolicy possède également les responsabilités suivantes :

* Garantit que la notification des fichiers circule via le LIF correct vers le serveur FPolicy.
* Garantit que lorsque plusieurs serveurs FPolicy sont associés à une règle, l'équilibrage de la charge est réalisé lors de l'envoi de notifications aux serveurs FPolicy.
* Tentatives de rétablissement de la connexion en cas de panne de la connexion à un serveur FPolicy.
* Envoie les notifications aux serveurs FPolicy par le biais d'une session authentifiée.
* Gère la connexion de données de type passthrough établie par le serveur FPolicy pour le traitement des requêtes client lorsque la lecture-passe est activée.

