---
permalink: nas-audit/index.html 
sidebar: sidebar 
keywords: file, access, auditing, audit, smb, cifs, nfs, fpolicy, udit, nas, events, svms 
summary: 'Grâce à ONTAP, vous pouvez utiliser les fonctions d"audit de l"accès aux fichiers disponibles pour les protocoles SMB et NFS, comme l"audit natif et la gestion des règles de fichiers via FPolicy.' 
---
= Audit et suivi de sécurité SMB et NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Grâce à ONTAP, vous pouvez utiliser les fonctions d'audit de l'accès aux fichiers disponibles pour les protocoles SMB et NFS, comme l'audit natif et la gestion des règles de fichiers via FPolicy.

Vous devez concevoir et implémenter l'audit des événements d'accès aux fichiers SMB et NFS dans les circonstances suivantes :

* L'accès de base aux fichiers des protocoles SMB et NFS a été configuré.
* Vous souhaitez créer et gérer une configuration d'audit à l'aide de l'une des méthodes suivantes :
+
** Fonctionnalité ONTAP native
** Serveurs FPolicy externes






== Audit des événements NAS sur les SVM

L'audit des événements NAS est une mesure de sécurité qui vous permet de suivre et de consigner certains événements SMB et NFS sur des serveurs virtuels de stockage (SVM). Cela vous permet de suivre les problèmes de sécurité potentiels et de prouver toute violation de la sécurité. Vous pouvez également définir et auditer les stratégies d'accès central Active Directory pour voir quel serait le résultat de leur mise en œuvre.



=== Événements SMB

Vous pouvez auditer les événements suivants :

* Événements d'accès aux fichiers et aux dossiers SMB
+
Vous pouvez auditer les événements d'accès aux fichiers et aux dossiers SMB sur des objets stockés sur des volumes FlexVol appartenant aux SVM activés à l'audit.

* Événements de connexion et de déconnexion SMB
+
Vous pouvez auditer les événements de connexion et de déconnexion SMB des serveurs SMB sur les SVM.

* Événements d'activation de stratégie d'accès central
+
Vous pouvez auditer l'accès effectif des objets sur les serveurs SMB à l'aide des autorisations appliquées à l'aide des règles d'accès centrales proposées. L'audit par la mise en place de stratégies d'accès central vous permet de voir quels sont les effets des stratégies d'accès central avant leur déploiement.

+
L'audit du staging des règles d'accès central est configuré à l'aide des GPO Active Directory. Cependant, la configuration d'audit du SVM doit être configurée pour auditer les événements de staging des règles d'accès central.

+
Bien que vous puissiez activer le staging de stratégie d'accès central dans la configuration d'audit sans activer le contrôle d'accès dynamique sur le serveur SMB, les événements de staging de stratégie d'accès central ne sont générés que si le contrôle d'accès dynamique est activé. Le contrôle d'accès dynamique est activé par le biais d'une option de serveur SMB. Elle n'est pas activée par défaut.





=== Événements NFS

Vous pouvez auditer les événements de fichier et de répertoire à l'aide des ACL NFSv4 sur des objets stockés sur les SVM.
