---
permalink: nas-audit/manage-audit-policy-change-event-concept.html 
sidebar: sidebar 
keywords: manage, audit-policy-change, event 
summary: 'Lorsqu"un événement d"audit-policy-change est configuré pour une machine virtuelle de stockage (SVM) et qu"un audit est activé, des événements d"audit sont générés. Les événements audit-policy-change sont générés lorsqu"une policy d"audit est modifiée à l"aide de commandes liées à l"audit vserver.' 
---
= Gestion des événements ONTAP audit-modification de règles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsqu'un événement d'audit-policy-change est configuré pour une machine virtuelle de stockage (SVM) et qu'un audit est activé, des événements d'audit sont générés. Les événements audit-règle-modification sont générés lorsqu'une règle d'audit est modifiée à l'aide de `vserver audit` commandes associées

L'événement audit-policy-change avec l'ID-événement 4719 est généré chaque fois qu'une stratégie d'audit est désactivée, activée ou modifiée et aide à identifier quand un utilisateur tente de désactiver l'audit pour couvrir les pistes. Il est configuré par défaut et requiert un privilège de diagnostic pour être désactivé.

L'exemple suivant montre un événement de modification de règle d'audit avec l'ID 4719 généré lorsqu'un audit est désactivé :

[listing]
----
netapp-clus1::*> vserver audit disable -vserver vserver_1
- System
  - Provider
   [ Name]  NetApp-Security-Auditing
   [ Guid]  {3CB2A168-FE19-4A4E-BDAD-DCF422F13473}
   EventID 4719
   EventName Audit Disabled
   ...
   ...
  SubjectUserName admin
  SubjectUserSid 65533-1001
  SubjectDomainName ~
  SubjectIP console
  SubjectPort
----