---
permalink: nas-audit/manage-authorization-policy-change-event-concept.html 
sidebar: sidebar 
keywords: manage, authorization-policy-change, event 
summary: 'Lorsque l"événement autorisation-policy-change est configuré pour une machine virtuelle de stockage (SVM) et qu"un audit est activé, des événements d"audit sont générés.' 
---
= Gestion des événements ONTAP autorisation-règle-changement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque l'événement autorisation-policy-change est configuré pour une machine virtuelle de stockage (SVM) et qu'un audit est activé, des événements d'audit sont générés.

Les événements autorisation-policy-change avec les id-événements 4704 et 4705 sont générés chaque fois que les droits d'autorisation sont accordés ou révoqués pour un utilisateur SMB et un groupe SMB. Les événements autorisation-stratégie-modification sont générés lorsque les droits d'autorisation sont affectés ou révoqués à l'aide de `vserver cifs users-and-groups privilege` commandes associées

L'exemple suivant affiche un événement de stratégie d'autorisation avec l'ID 4704 généré lorsque les droits d'autorisation d'un groupe d'utilisateurs SMB sont affectés :

[listing]
----
netapp-clus1::*> vserver cifs users-and-groups privilege add-privilege -user-or-group-name testcifslocalgroup -privileges *
- System
  - Provider
   [ Name]  NetApp-Security-Auditing
   [ Guid]  {3CB2A168-FE19-4A4E-BDAD-DCF422F13473}
   EventID 4704
   EventName User Right Assigned
   ...
   ...
  TargetUserOrGroupName testcifslocalgroup
  TargetUserOrGroupDomainName NETAPP-CLUS1
  TargetUserOrGroupSid S-1-5-21-2447422786-1297661003-4197201688-1004;
  PrivilegeList SeTcbPrivilege;SeBackupPrivilege;SeRestorePrivilege;SeTakeOwnershipPrivilege;SeSecurityPrivilege;SeChangeNotifyPrivilege;
  TargetType CIFS
----