---
permalink: nas-audit/manual-rotate-audit-event-logs-task.html 
sidebar: sidebar 
keywords: manually, rotate, audit event logs 
summary: 'Avant de pouvoir afficher les journaux d"événements d"audit, ils doivent être convertis en formats lisibles par l"utilisateur. Si vous souhaitez afficher les journaux des événements d"une machine virtuelle de stockage (SVM) spécifique avant que ONTAP ne fasse automatiquement pivoter le journal, vous pouvez faire tourner manuellement les journaux des événements d"audit sur un SVM.' 
---
= Rotation manuelle des journaux d'événements d'audit
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de pouvoir afficher les journaux d'événements d'audit, ils doivent être convertis en formats lisibles par l'utilisateur. Si vous souhaitez afficher les journaux des événements d'une machine virtuelle de stockage (SVM) spécifique avant que ONTAP ne fasse automatiquement pivoter le journal, vous pouvez faire tourner manuellement les journaux des événements d'audit sur un SVM.

.Étape
. Faites pivoter les journaux d'événements d'audit à l'aide de `vserver audit rotate-log` commande.
+
`vserver audit rotate-log -vserver vs1`

+
Le journal des événements d'audit est enregistré dans le répertoire du journal des événements d'audit SVM au format spécifié par la configuration d'audit (`XML` ou `EVTX`), et peut être consulté à l'aide de l'application appropriée.


