---
permalink: nas-audit/modify-security-trace-filters-task.html 
sidebar: sidebar 
keywords: modify, security trace filters 
summary: 'Si vous souhaitez modifier les paramètres de filtre facultatifs utilisés pour déterminer les événements d"accès qui sont tracés, vous pouvez modifier les filtres de trace de sécurité existants.' 
---
= Modifier les filtres de trace de sécurité
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous souhaitez modifier les paramètres de filtre facultatifs utilisés pour déterminer les événements d'accès qui sont tracés, vous pouvez modifier les filtres de trace de sécurité existants.

Vous devez identifier le filtre de trace de sécurité à modifier en précisant le nom de la machine virtuelle de stockage (SVM) sur laquelle le filtre est appliqué et le numéro d'index du filtre. Vous pouvez modifier tous les paramètres de filtre facultatifs.

.Étapes
. Modifier un filtre de trace de sécurité :
+
`vserver security trace filter modify -vserver vserver_name -index index_numberfilter_parameters`

+
** `vserver_name` Est le nom du SVM sur lequel vous souhaitez appliquer un filtre de trace de sécurité.
** `index_number` est le numéro d'index que vous souhaitez appliquer au filtre. Les valeurs autorisées pour ce paramètre sont de 1 à 10.
** `filter_parameters` est une liste des paramètres de filtre facultatifs.


. Vérifiez l'entrée du filtre de trace de sécurité :
+
`vserver security trace filter show -vserver vserver_name -index index_number`



La commande suivante modifie le filtre de trace de sécurité avec l'index numéro 1. Le filtre trace les événements pour tout utilisateur accédant à un fichier avec un chemin de partage `\\server\share1\dir1\dir2\file.txt` À partir de n'importe quelle adresse IP. Le filtre utilise un chemin complet pour le `-path` option. Les traces de filtre autorisent et refusent les événements :

[listing]
----
cluster1::> vserver security trace filter modify -vserver vs1 -index 1 -path /dir1/dir2/file.txt -trace-allow yes

cluster1::> vserver security trace filter show -vserver vs1 -index 1
                                 Vserver: vs1
                            Filter Index: 1
              Client IP Address to Match: -
                                    Path: /dir1/dir2/file.txt
                       Windows User Name: -
                          UNIX User Name: -
                      Trace Allow Events: yes
                          Filter Enabled: enabled
               Minutes Filter is Enabled: 60
----