---
permalink: nas-audit/persistent-stores.html 
sidebar: sidebar 
keywords: overview, persistent store, fpolicy 
summary: 'À partir de ONTAP 9.14.1, FPolicy permet de configurer un magasin persistant pour capturer les événements d"accès aux fichiers pour des règles asynchrones non obligatoires dans la SVM. Les magasins persistants peuvent aider à découpler le traitement des E/S client du traitement des notifications FPolicy afin de réduire la latence du client. Les configurations obligatoires synchrones et asynchrones ne sont pas prises en charge.' 
---
= Les magasins persistants FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les magasins persistants peuvent aider à découpler le traitement des E/S client du traitement des notifications FPolicy afin de réduire la latence du client. Depuis la version ONTAP 9.14.1, vous pouvez configurer un magasin persistant FPolicy pour capturer les événements d'accès aux fichiers pour des règles asynchrones non obligatoires dans la SVM. Les configurations obligatoires synchrones (obligatoires ou non) et asynchrones ne sont pas prises en charge.

Cette fonctionnalité est uniquement disponible en mode externe FPolicy. L'application partenaire que vous utilisez doit prendre en charge cette fonctionnalité. Vous devez collaborer avec votre partenaire pour vous assurer que cette configuration FPolicy est prise en charge.

À partir de ONTAP 9.15.1, la configuration du stockage persistant FPolicy est simplifiée. Le `persistent-store create` Automatise la création de volume pour la SVM et configure le volume avec les bonnes pratiques de stockage persistant.

Pour plus d'informations sur les meilleures pratiques en matière de stockage persistant, reportez-vous à la section link:requirements-best-practices-fpolicy-concept.html["D'exigences, de considérations et de meilleures pratiques pour la configuration de FPolicy"].

Pour plus d'informations sur l'ajout de magasins persistants, reportez-vous à la section link:create-persistent-stores.html["Créez des magasins persistants"].
