---
permalink: nas-audit/roles-cluster-components-fpolicy-concept.html 
sidebar: sidebar 
keywords: roles, cluster components, play, fpolicy implementation 
summary: 'Le cluster, les SVM contenant les machines virtuelles de stockage et les LIF de données jouent tous un rôle dans l"implémentation d"une FPolicy.' 
---
= Rôles des composants du cluster dans la mise en œuvre d'ONTAP FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le cluster, les SVM contenant les machines virtuelles de stockage et les LIF de données jouent tous un rôle dans l'implémentation d'une FPolicy.

* *cluster*
+
Le cluster contient le framework de gestion FPolicy. Il gère et gère les informations relatives à toutes les configurations FPolicy du cluster.

* *SVM*
+
Une configuration FPolicy est définie au niveau de la SVM. L'étendue de la configuration est le SVM, et ne fonctionne que sur les ressources SVM. Une configuration SVM ne peut pas surveiller et envoyer de notifications pour les demandes d'accès aux fichiers effectuées pour les données résidant sur une autre SVM.

+
Les configurations FPolicy peuvent être définies sur le SVM d'administration. Une fois les configurations définies sur le SVM d'administration, elles peuvent être consultées et utilisées dans tous les SVM.

* *LIF de données*
+
Les connexions aux serveurs FPolicy sont effectuées via les LIF de données appartenant au SVM avec la configuration FPolicy. Les LIF de données utilisées pour ces connexions peuvent basculer de la même manière que les LIF de données utilisées pour un accès client normal.


