---
permalink: nas-audit/security-traces-work-concept.html 
sidebar: sidebar 
keywords: security traces, work 
summary: 'Les traces de sécurité vous permettent de configurer un filtre qui détecte les opérations client sur SMB et NFS sur la machine virtuelle de stockage (SVM), et trace tous les contrôles d"accès correspondant à ce filtre. Vous pouvez alors afficher les résultats de la trace, ce qui fournit un résumé pratique de la raison pour laquelle l"accès a été autorisé ou refusé.' 
---
= En savoir plus sur les traces de sécurité ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez ajouter des filtres de suivi des autorisations pour demander à ONTAP de consigner des informations sur la raison pour laquelle les serveurs SMB et NFS d'une machine virtuelle de stockage (SVM) autorise ou refuse la demande d'un client ou d'un utilisateur d'effectuer une opération. Cela peut être utile lorsque vous voulez vérifier que votre schéma de sécurité d'accès aux fichiers est approprié ou lorsque vous souhaitez résoudre les problèmes d'accès aux fichiers.

Les traces de sécurité vous permettent de configurer un filtre qui détecte les opérations client sur SMB et NFS sur le SVM et trace tous les contrôles d'accès correspondant à ce filtre. Vous pouvez alors afficher les résultats de la trace, ce qui fournit un résumé pratique de la raison pour laquelle l'accès a été autorisé ou refusé.

Lorsque vous voulez vérifier les paramètres de sécurité de l'accès SMB ou NFS sur des fichiers et dossiers de votre SVM ou si vous êtes confronté à un problème d'accès, vous pouvez rapidement ajouter un filtre pour activer le suivi des autorisations.

La liste suivante présente des faits importants sur le fonctionnement des traces de sécurité :

* ONTAP applique des traces de sécurité au niveau du SVM.
* Chaque requête entrante est criblée pour voir si elle correspond aux critères de filtrage des traces de sécurité activées.
* Des traces sont effectuées pour les demandes d'accès aux fichiers et aux dossiers.
* Les traces peuvent être filtrées en fonction des critères suivants :
+
** Adresse IP du client
** Chemin SMB ou NFS
** Nom Windows
** Nom UNIX


* Les demandes sont examinées pour les résultats des réponses _autorisé_ et _refusé_.
* Chaque demande correspondant aux critères de filtrage des tracés activés est enregistrée dans le journal des résultats de suivi.
* L'administrateur du stockage peut configurer une temporisation sur un filtre pour la désactiver automatiquement.
* Si une demande correspond à plusieurs filtres, les résultats du filtre dont le numéro d'index est le plus élevé sont enregistrés.
* L'administrateur du stockage peut imprimer les résultats à partir du journal des résultats de suivi pour déterminer pourquoi une demande d'accès a été autorisée ou refusée.

