---
permalink: nas-audit/smb-events-audit-concept.html 
sidebar: sidebar 
keywords: smb events, audited 
summary: 'ONTAP peut auditer certains événements SMB, notamment certains événements d"accès aux fichiers et aux dossiers, certains événements de connexion et de déconnexion, et des événements d"activation des règles d"accès central. Savoir quels événements d"accès peuvent être audités est utile pour interpréter les résultats des journaux d"événements.' 
---
= Découvrez les événements SMB pouvant faire l'objet d'un audit par ONTAP pour interpréter les résultats
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP peut auditer certains événements SMB, notamment certains événements d'accès aux fichiers et aux dossiers, certains événements de connexion et de déconnexion, et des événements d'activation des règles d'accès central. Savoir quels événements d'accès peuvent être audités est utile pour interpréter les résultats des journaux d'événements.

Les événements SMB supplémentaires suivants peuvent être audités dans ONTAP 9.2 et versions ultérieures :

[cols="20,25,35,20"]
|===


| ID D'ÉVÉNEMENT (EVT/EVTX) | Événement | Description | Catégorie 


 a| 
4670
 a| 
Les autorisations d'objet ont été modifiées
 a| 
ACCÈS AUX OBJETS : autorisations modifiées.
 a| 
Accès aux fichiers



 a| 
4907
 a| 
Les paramètres d'audit d'objet ont été modifiés
 a| 
ACCÈS À L'OBJET : paramètres d'audit modifiés.
 a| 
Accès aux fichiers



 a| 
4913
 a| 
La stratégie d'accès à Object Central a été modifiée
 a| 
ACCÈS À L'OBJET : BOUCHON MODIFIÉ.
 a| 
Accès aux fichiers

|===
Les événements SMB suivants peuvent être audités dans ONTAP 9.0 et versions ultérieures :

[cols="20,25,35,20"]
|===


| ID D'ÉVÉNEMENT (EVT/EVTX) | Événement | Description | Catégorie 


 a| 
540/4624
 a| 
Un compte a été connecté avec succès
 a| 
CONNEXION/DÉCONNEXION : connexion réseau (SMB).
 a| 
Connexion et déconnexion



 a| 
529/4625
 a| 
Impossible de se connecter à un compte
 a| 
CONNEXION/DÉCONNEXION : nom d'utilisateur inconnu ou mot de passe incorrect.
 a| 
Connexion et déconnexion



 a| 
530/4625
 a| 
Impossible de se connecter à un compte
 a| 
OUVERTURE/FERMETURE de SESSION : restriction de l'heure de connexion au compte.
 a| 
Connexion et déconnexion



 a| 
531/4625
 a| 
Impossible de se connecter à un compte
 a| 
CONNEXION/DÉCONNEXION : compte actuellement désactivé.
 a| 
Connexion et déconnexion



 a| 
532/4625
 a| 
Impossible de se connecter à un compte
 a| 
OUVERTURE/FERMETURE DE SESSION : le compte utilisateur a expiré.
 a| 
Connexion et déconnexion



 a| 
533/4625
 a| 
Impossible de se connecter à un compte
 a| 
OUVERTURE/FERMETURE DE SESSION : l'utilisateur ne peut pas se connecter à cet ordinateur.
 a| 
Connexion et déconnexion



 a| 
534/4625
 a| 
Impossible de se connecter à un compte
 a| 
OUVERTURE DE SESSION/DÉCONNEXION : l'utilisateur n'a pas accordé de type de connexion ici.
 a| 
Connexion et déconnexion



 a| 
535/4625
 a| 
Impossible de se connecter à un compte
 a| 
OUVERTURE/FERMETURE DE SESSION : le mot de passe de l'utilisateur a expiré.
 a| 
Connexion et déconnexion



 a| 
537/4625
 a| 
Impossible de se connecter à un compte
 a| 
OUVERTURE/FERMETURE de SESSION : la connexion a échoué pour des raisons autres que ci-dessus.
 a| 
Connexion et déconnexion



 a| 
539/4625
 a| 
Impossible de se connecter à un compte
 a| 
OUVERTURE DE SESSION/DÉCONNEXION : compte verrouillé.
 a| 
Connexion et déconnexion



 a| 
538/4634
 a| 
Un compte a été déconnecté
 a| 
OUVERTURE/FERMETURE DE SESSION : déconnexion de l'utilisateur local ou réseau.
 a| 
Connexion et déconnexion



 a| 
560/4656
 a| 
Ouvrir objet/Créer objet
 a| 
ACCÈS EN MODE OBJET : objet (fichier ou répertoire) ouvert.
 a| 
Accès aux fichiers



 a| 
563/4659
 a| 
Ouvrez l'objet avec l'intention de supprimer
 a| 
ACCÈS AUX OBJETS : un descripteur d'objet (fichier ou répertoire) a été demandé avec l'intention de supprimer.
 a| 
Accès aux fichiers



 a| 
564/4660
 a| 
Supprimer l'objet
 a| 
ACCÈS OBJET : supprimer l'objet (fichier ou répertoire). ONTAP génère cet événement lorsqu'un client Windows tente de supprimer l'objet (fichier ou répertoire).
 a| 
Accès aux fichiers



 a| 
567/4663
 a| 
Lire objet/Ecrire objet/obtenir attributs d'objet/définir attributs d'objet
 a| 
ACCÈS AUX OBJETS : tentative d'accès aux objets (lecture, écriture, obtenir l'attribut, définir l'attribut).

*Remarque :* pour cet événement, ONTAP vérifie uniquement la première opération de lecture SMB et la première opération d'écriture SMB (succès ou échec) sur un objet. Cela empêche ONTAP de créer un nombre excessif d'entrées de journal lorsqu'un seul client ouvre un objet et effectue de nombreuses opérations de lecture ou d'écriture successives sur le même objet.
 a| 
Accès aux fichiers



 a| 
NA/4664
 a| 
Lien dur
 a| 
ACCÈS À L'OBJET : tentative de création d'un lien dur.
 a| 
Accès aux fichiers



 a| 
NA/4818
 a| 
La politique d'accès central proposée n'accorde pas les mêmes autorisations d'accès que la politique d'accès central actuelle
 a| 
ACCÈS AUX OBJETS : transfert de la stratégie d'accès central.
 a| 
Accès aux fichiers



 a| 
Na/NA - ID d'événement Data ONTAP 9999
 a| 
Renommer l'objet
 a| 
ACCÈS OBJET : objet renommé. Il s'agit d'un événement ONTAP. Windows ne prend actuellement pas en charge cet événement en tant qu'événement unique.
 a| 
Accès aux fichiers



 a| 
Na/NA Data ONTAP ID d'événement 9998
 a| 
Dissocier l'objet
 a| 
ACCÈS AUX OBJETS : objet non lié. Il s'agit d'un événement ONTAP. Windows ne prend actuellement pas en charge cet événement en tant qu'événement unique.
 a| 
Accès aux fichiers

|===


== Informations supplémentaires sur l'événement 4656

Le `HandleID` dans l'audit `XML` event contient le descripteur de l'objet (fichier ou répertoire) accédé. Le `HandleID` La balise de l'événement EVTX 4656 contient des informations différentes selon que l'événement ouvert permet de créer un nouvel objet ou d'ouvrir un objet existant :

* Si l'événement ouvert est une demande ouverte pour créer un nouvel objet (fichier ou répertoire), le `HandleID` La balise dans l'événement XML d'audit affiche un vide `HandleID` (par exemple : `<Data Name="HandleID">00000000000000;00;00000000;00000000</Data>` ).
+
Le `HandleID` Est vide car la demande OUVERTE (pour la création d'un nouvel objet) est auditée avant la création réelle de l'objet et avant qu'un descripteur n'existe. Les événements audités suivants pour le même objet ont le bon descripteur d'objet dans le `HandleID` balise :

* Si l'événement ouvert est une demande ouverte d'ouverture d'un objet existant, l'événement d'audit aura le descripteur affecté à cet objet dans le `HandleID` balise (par exemple : `<Data Name="HandleID">00000000000401;00;000000ea;00123ed4</Data>` ).

