---
permalink: nas-audit/supported-file-operation-filter-fpolicy-nfsv4-concept.html 
sidebar: sidebar 
keywords: ontap 9, supported file operation, filter combinations, fpolicy, monitor, nfsv4 
summary: 'Lorsque vous configurez votre événement FPolicy, vous devez savoir que seules certaines combinaisons d"opérations et de filtres sont prises en charge pour surveiller les opérations d"accès aux fichiers NFSv4.' 
---
= Opérations de fichiers et combinaisons de filtres prises en charge que FPolicy peut surveiller pour NFSv4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous configurez votre événement FPolicy, vous devez savoir que seules certaines combinaisons d'opérations et de filtres sont prises en charge pour surveiller les opérations d'accès aux fichiers NFSv4.

Le tableau suivant fournit la liste des combinaisons d'opérations de fichiers et de filtres prises en charge pour la surveillance FPolicy des événements d'accès aux fichiers NFSv4 :

[cols="30,70"]
|===


| Opérations de fichiers prises en charge | Filtres pris en charge 


 a| 
fermer
 a| 
bit hors ligne, répertoire d'exclusion



 a| 
création
 a| 
bit hors ligne



 a| 
dir_de_création
 a| 
Aucun filtre n'est actuellement pris en charge pour cette opération de fichier.



 a| 
supprimer
 a| 
bit hors ligne



 a| 
dir_de_suppression
 a| 
Aucun filtre n'est actuellement pris en charge pour cette opération de fichier.



 a| 
getattr
 a| 
bit hors ligne, répertoire d'exclusion



 a| 
lien
 a| 
bit hors ligne



 a| 
recherche
 a| 
bit hors ligne, répertoire d'exclusion



 a| 
la transparence
 a| 
bit hors ligne, répertoire d'exclusion



 a| 
lecture
 a| 
bit hors ligne, première lecture



 a| 
écriture
 a| 
bit hors ligne, première écriture, écriture avec changement de taille



 a| 
renommer
 a| 
bit hors ligne



 a| 
rename_dir
 a| 
Aucun filtre n'est actuellement pris en charge pour cette opération de fichier.



 a| 
définir
 a| 
offline-bit, setattr_with_owner_change, setattr_with_group_change, setattr_with_mode_change, setattr_with_sacl_change, setattr_with_dacl_change, setattr_with_modify_time_change, setattr_with_access_time_change, setattr_with_size_change, exclude_directory



 a| 
symlink
 a| 
bit hors ligne

|===