---
permalink: nas-audit/supported-file-operation-filter-fpolicy-nfsv3-concept.html 
sidebar: sidebar 
keywords: ontap 9, supported file operation, filter combinations, fpolicy, monitor, nfsv3 
summary: 'Lorsque vous configurez votre événement FPolicy, vous devez savoir que seules certaines combinaisons d"opérations sur les fichiers et de filtres sont prises en charge pour surveiller les opérations d"accès aux fichiers NFSv3.' 
---
= Opérations de fichiers et combinaisons de filtres prises en charge pouvant être moniteurs par FPolicy pour NFSv3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous configurez votre événement FPolicy, vous devez savoir que seules certaines combinaisons d'opérations sur les fichiers et de filtres sont prises en charge pour surveiller les opérations d'accès aux fichiers NFSv3.

Le tableau suivant répertorie les opérations de fichiers et les combinaisons de filtres prises en charge pour la surveillance FPolicy des événements d'accès aux fichiers NFSv3 :

[cols="30,70"]
|===


| Opérations de fichiers prises en charge | Filtres pris en charge 


 a| 
création
 a| 
bit hors ligne



 a| 
dir_de_création
 a| 
Aucun filtre n'est actuellement pris en charge pour cette opération de fichier.



 a| 
supprimer
 a| 
bit hors ligne



 a| 
dir_de_suppression
 a| 
Aucun filtre n'est actuellement pris en charge pour cette opération de fichier.



 a| 
lien
 a| 
bit hors ligne



 a| 
recherche
 a| 
offline-bit, exclude-dir



 a| 
lecture
 a| 
bit hors ligne, première lecture



 a| 
écriture
 a| 
bit hors ligne, première écriture, écriture avec changement de taille



 a| 
renommer
 a| 
bit hors ligne



 a| 
rename_dir
 a| 
Aucun filtre n'est actuellement pris en charge pour cette opération de fichier.



 a| 
définir
 a| 
offline-bit, setattr_with_owner_change, setattr_with_group_change, setattr_with_mode_change, setattr_with_modif_time_change, setattr_with_access_time_change, setattr_with_size_change, exclude_directory



 a| 
symlink
 a| 
bit hors ligne

|===
À partir de ONTAP 9.13.1, les utilisateurs peuvent recevoir des notifications en cas d'échec des opérations sur les fichiers en raison d'un manque d'autorisations. Le tableau suivant répertorie les combinaisons de filtres et d'opérations de fichiers refusés d'accès prises en charge pour la surveillance FPolicy des événements d'accès aux fichiers NFSv3 :

[cols="30,70"]
|===


| Opération de fichier d'accès refusé prise en charge | Filtres pris en charge 


 a| 
l'accès
 a| 
NA



 a| 
création
 a| 
NA



 a| 
dir_de_création
 a| 
NA



 a| 
supprimer
 a| 
NA



 a| 
dir_de_suppression
 a| 
NA



 a| 
lien
 a| 
NA



 a| 
lecture
 a| 
NA



 a| 
renommer
 a| 
NA



 a| 
rename_dir
 a| 
NA



 a| 
définir
 a| 
NA



 a| 
écriture
 a| 
NA

|===