---
permalink: nas-audit/supported-file-operation-filter-fpolicy-smb-concept.html 
sidebar: sidebar 
keywords: list, supported file operation, filter combinations, fpolicy, monitor, smb 
summary: 'Lorsque vous configurez votre événement FPolicy, vous devez savoir que seules certaines combinaisons d"opérations et de filtres sont prises en charge pour la surveillance des opérations d"accès aux fichiers SMB.' 
---
= Opérations de fichiers et combinaisons de filtres prises en charge que FPolicy peut surveiller pour SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous configurez votre événement FPolicy, vous devez savoir que seules certaines combinaisons d'opérations et de filtres sont prises en charge pour la surveillance des opérations d'accès aux fichiers SMB.

Le tableau suivant fournit la liste des combinaisons d'opérations de fichiers et de filtres prises en charge pour la surveillance FPolicy des événements d'accès aux fichiers SMB :

[cols="30,70"]
|===


| Opérations de fichiers prises en charge | Filtres pris en charge 


 a| 
fermer
 a| 
surveillance-ads, hors ligne-bit, fermeture-avec-modification, fermeture-sans-modification, gros-avec-lecture, exclure-répertoire



 a| 
création
 a| 
surveillance-ads, hors ligne-bit



 a| 
dir_de_création
 a| 
Aucun filtre n'est actuellement pris en charge pour cette opération de fichier.



 a| 
supprimer
 a| 
surveillance-ads, hors ligne-bit



 a| 
dir_de_suppression
 a| 
Aucun filtre n'est actuellement pris en charge pour cette opération de fichier.



 a| 
getattr
 a| 
offline-bit, exclude-dir



 a| 
la transparence
 a| 
monitor-ads, offline-bit, open-with-delete-intentionnel, open-with-write-intentions, exclude-dir



 a| 
lecture
 a| 
surveillance-ads, hors-ligne-bit, première lecture



 a| 
écriture
 a| 
surveillance-ads, hors-ligne-bit, première-écriture, écriture-avec-changement de taille



 a| 
renommer
 a| 
surveillance-ads, hors ligne-bit



 a| 
rename_dir
 a| 
Aucun filtre n'est actuellement pris en charge pour cette opération de fichier.



 a| 
définir
 a| 
monitor-ads, offline-bit, setattr_with_owner_change, setattr_with_group_change, setattr_with_mode_change, setattr_with_sacl_change, setattr_with_dacl_change, setattr_with_modify_time_change, setattr_with_access_time_change, setattr_with_creation_time_change, setattr_with_size_change, setattr_with_allocation_size_change, exclude_directory

|===
À partir de ONTAP 9.13.1, les utilisateurs peuvent recevoir des notifications en cas d'échec des opérations sur les fichiers en raison d'un manque d'autorisations. Le tableau suivant répertorie les combinaisons de filtres et d'opérations de fichiers refusés d'accès pris en charge pour la surveillance FPolicy des événements d'accès aux fichiers SMB :

[cols="30,70"]
|===


| Opération de fichier d'accès refusé prise en charge | Filtres pris en charge 


 a| 
la transparence
 a| 
NA

|===