---
permalink: nas-audit/two-parts-fpolicy-solution-concept.html 
sidebar: sidebar 
keywords: two parts, fpolicy, solution 
summary: Une solution FPolicy possède deux parties. La structure ONTAP FPolicy gère les activités du cluster et envoie des notifications à des serveurs FPolicy externes. Les serveurs FPolicy externes traitent les notifications envoyées par ONTAP FPolicy. 
---
= De quoi sont les deux parties de la solution FPolicy
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FPolicy est un framework de notification d'accès aux fichiers utilisé pour surveiller et gérer les événements d'accès aux fichiers sur les machines virtuelles de stockage (SVM).

Une solution FPolicy possède deux parties. La structure ONTAP FPolicy gère les activités du cluster et envoie des notifications à des serveurs FPolicy externes. Les serveurs FPolicy externes traitent les notifications envoyées par ONTAP FPolicy.

Le framework ONTAP crée et gère la configuration FPolicy, surveille les événements de fichier et envoie des notifications aux serveurs FPolicy externes. ONTAP FPolicy fournit l'infrastructure qui permet la communication entre les serveurs FPolicy externes et les nœuds de machine virtuelle de stockage (SVM).

La structure FPolicy se connecte aux serveurs FPolicy externes et envoie des notifications pour certains événements du système de fichiers aux serveurs FPolicy lorsque ces événements se produisent suite à l'accès client. Les serveurs FPolicy externes traitent les notifications et réenvoient les réponses au nœud. Ce qui se produit à la suite du traitement des notifications dépend de l'application et si la communication entre le nœud et les serveurs externes est asynchrone ou synchrone.
