---
permalink: san-config/change-fc-adapter-speed-task.html 
sidebar: sidebar 
keywords: change, fc adapter, speed 
summary: 'Vous devez définir la vitesse du port cible de votre adaptateur afin qu"elle corresponde à la vitesse du périphérique auquel il se connecte, au lieu d"utiliser la négociation automatique. Un port défini pour la négociation automatique peut prendre plus de temps pour se reconnecter après un basculement/rétablissement ou une autre interruption.' 
---
= Modifier la vitesse de l'adaptateur FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez définir la vitesse du port cible de votre adaptateur afin qu'elle corresponde à la vitesse du périphérique auquel il se connecte, au lieu d'utiliser la négociation automatique. Un port défini pour la négociation automatique peut prendre plus de temps pour se reconnecter après un basculement/rétablissement ou une autre interruption.

Toutes les LIFs qui utilisent cet adaptateur comme port de home port doivent être hors ligne.

Cette tâche englobant tous les SVM (Storage Virtual machine) et toutes les LIFs d'un cluster, vous devez utiliser le `-home-port` et `-home-lif` paramètres pour limiter la portée de cette opération. Si vous n'utilisez pas ces paramètres, l'opération s'applique à toutes les LIFs du cluster, ce qui peut ne pas être souhaitable.

.Étapes
. Mettre hors ligne toutes les LIFs sur cet adaptateur :
+
`network interface modify -vserver * -lif * { -home-node node1 -home-port 0c } -status-admin down`

. Mettez l'adaptateur hors ligne :
+
`network fcp adapter modify -node node1 -adapter 0c -state down`

+
Si l'adaptateur ne passe pas hors ligne, vous pouvez également retirer le câble du port d'adaptateur approprié du système.

. Déterminez la vitesse maximale de l'adaptateur de port :
+
`fcp adapter show -instance`

+
Vous ne pouvez pas modifier la vitesse de l'adaptateur au-delà de la vitesse maximale.

. Modifier la vitesse de l'adaptateur :
+
`network fcp adapter modify -node node1 -adapter 0c -speed 16`

. Mettez la carte en ligne :
+
`network fcp adapter modify -node node1 -adapter 0c -state up`

. Mettre en ligne toutes les LIFs sur l'adaptateur :
+
`network interface modify -vserver * -lif * { -home-node node1 -home-port 0c } -status-admin up`


