---
permalink: san-config/determine-supported-nodes-task.html 
sidebar: sidebar 
keywords: determine, number, supported, nodes, san configurations 
summary: Le nombre de nœuds par cluster pris en charge par ONTAP varie en fonction de la version de ONTAP, des modèles de contrôleur de stockage dans le cluster et du protocole de vos nœuds de cluster. 
---
= Identification du nombre de nœuds pris en charge dans les configurations SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le nombre de nœuds par cluster pris en charge par ONTAP varie en fonction de la version de ONTAP, des modèles de contrôleur de stockage dans le cluster et du protocole de vos nœuds de cluster.

.Description de la tâche
Si un nœud du cluster est configuré pour les protocoles FC, FC-NVMe, FCoE ou iSCSI, ce cluster est limité aux limites du nœud SAN. Les limites de nœuds basées sur les contrôleurs de votre cluster sont répertoriées dans le _Hardware Universe_.

.Étapes
. Accédez à https://hwu.netapp.com["NetApp Hardware Universe"^].
. Cliquez sur *plates-formes* dans le coin supérieur gauche (en regard du bouton *Home*) et sélectionnez le type de plate-forme.
. Cochez la case en regard de votre version de ONTAP.
+
Une nouvelle colonne s'affiche pour vous permettre de choisir vos plates-formes.

. Cochez les cases en regard des plateformes utilisées dans votre solution.
. Désélectionnez la case *Sélectionner tout* dans la colonne *Choisissez vos spécifications*.
. Cochez la case *Max Nodes per Cluster (NAS/SAN)*.
. Cliquez sur *Afficher les résultats*.


.Informations associées
https://hwu.netapp.com["NetApp Hardware Universe"^]
