---
permalink: san-config/determine-supported-hosts-iscsi-config-task.html 
sidebar: sidebar 
keywords: determine, supported, number, hosts, iscsi, configurations 
summary: 'Le nombre maximal d"hôtes SAN pouvant être connectés dans des configurations iSCSI varie considérablement en fonction de votre combinaison spécifique de plusieurs attributs de cluster, tels que le nombre d"hôtes connectés à chaque nœud de cluster, les initiateurs par hôte, les connexions par hôte et les nœuds du cluster.' 
---
= Identification du nombre d'hôtes pris en charge dans les configurations iSCSI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le nombre maximal d'hôtes SAN pouvant être connectés dans des configurations iSCSI varie considérablement en fonction de votre combinaison spécifique de plusieurs attributs de cluster, tels que le nombre d'hôtes connectés à chaque nœud de cluster, les initiateurs par hôte, les connexions par hôte et les nœuds du cluster.

.Description de la tâche
Le nombre d'hôtes pouvant être connectés directement à un nœud ou qui peuvent être connectés via un ou plusieurs commutateurs dépend du nombre de ports Ethernet disponibles. Le nombre de ports Ethernet disponibles est déterminé par le modèle du contrôleur et par le nombre et le type d'adaptateurs installés dans le contrôleur. Le nombre de ports Ethernet pris en charge pour les contrôleurs et les adaptateurs est disponible dans _Hardware Universe_.

Pour toutes les configurations de clusters à plusieurs nœuds, vous devez déterminer le nombre de sessions iSCSI par nœud pour savoir si vous pouvez ajouter d'autres hôtes à votre cluster. Tant que le cluster est inférieur au nombre maximal de sessions iSCSI par nœud, vous pouvez continuer à ajouter des hôtes au cluster. Le nombre maximal de sessions iSCSI par nœud varie en fonction des types de contrôleurs du cluster.

.Étapes
. Identifiez tous les groupes de portails cible sur le nœud.
. Vérifier le nombre de sessions iSCSI pour chaque groupe de portails cible sur le nœud :
+
`iscsi session show -tpgroup _tpgroup_`

+
Le nombre d'entrées affichées au bas de la sortie de la commande représente le nombre de sessions iSCSI pour ce groupe de portails cible.

. Notez le nombre de sessions iSCSI affichées pour chaque groupe de portails cible.
. Ajoutez le nombre de sessions iSCSI pour chaque groupe de portails cible sur le nœud.
+
Le total représente le nombre de sessions iSCSI sur votre nœud.


