---
permalink: san-config/fc-switch-config-limits-reference.html 
sidebar: sidebar 
keywords: fc, switch, configuration, limits 
summary: Les commutateurs Fibre Channel ont des limites de configuration maximales, y compris le nombre de connexions prises en charge par port, groupe de ports, lame et commutateur. Les fournisseurs des commutateurs documentent leurs limites prises en charge. 
---
= Limites de configuration des commutateurs FC utilisés avec les systèmes ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les commutateurs Fibre Channel ont des limites de configuration maximales, y compris le nombre de connexions prises en charge par port, groupe de ports, lame et commutateur. Les fournisseurs des commutateurs documentent leurs limites prises en charge.

Chaque interface logique FC (LIF) se connecte à un port de commutateur FC. Le nombre total de connexions à partir d'une seule cible sur le nœud est égal au nombre de LIF plus une connexion pour le port physique sous-jacent. Ne dépassez pas les limites de configuration du fournisseur du commutateur pour les connexions ou d'autres valeurs de configuration. Cela est également vrai pour les initiateurs utilisés côté hôte dans les environnements virtualisés avec NPIV activé. Ne dépassez pas les limites de configuration du fournisseur pour les connexions pour la cible ou les initiateurs utilisés dans la solution.



== Limites des commutateurs Brocade

Les limites de configuration des commutateurs Brocade sont indiquées dans les _directives d'évolutivité Brocade_.



== Limites du commutateur Cisco Systems

Les limites de configuration des commutateurs Cisco sont disponibles dans le http://www.cisco.com/en/US/products/ps5989/products_installation_and_configuration_guides_list.html["Limites de configuration Cisco"^] Guide de la version du logiciel du commutateur Cisco.
