---
permalink: san-config/fc-switch-config-best-practices-concept.html 
sidebar: sidebar 
keywords: fc, switch, configuration, best, practices 
summary: Pour obtenir des performances optimales, vous devez tenir compte de certaines des meilleures pratiques lors de la configuration du commutateur FC. 
---
= Meilleures pratiques en matière de configuration des commutateurs FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour obtenir des performances optimales, vous devez tenir compte de certaines des meilleures pratiques lors de la configuration du commutateur FC.

Un paramètre de vitesse de liaison fixe est la meilleure pratique pour les configurations de commutateurs FC, en particulier pour les structures importantes, car il offre les meilleures performances pour les reconstructions de structures et peut gagner beaucoup de temps. Bien que la négociation automatique offre la plus grande flexibilité, la configuration des commutateurs FC ne fonctionne pas toujours comme prévu, et elle ajoute du temps à la séquence globale de création de la structure.

Tous les commutateurs connectés à la structure doivent prendre en charge la virtualisation NPIV (N_Port ID Virtualization) et doivent avoir NPIV activé. ONTAP utilise NPIV pour présenter les cibles FC à une structure.

Pour plus d'informations sur les environnements pris en charge, reportez-vous au https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^].

Pour connaître les meilleures pratiques en matière de FC et d'iSCSI, reportez-vous à https://www.netapp.com/pdf.html?item=/media/10680-tr4080pdf.pdf["Rapport technique de NetApp 4080 : meilleures pratiques pour le SAN moderne"^]la section.
