---
permalink: san-config/fc-target-port-config-recommendations-concept.html 
sidebar: sidebar 
keywords: fc, target, port, configuration, recommendations 
summary: Pour des performances optimales et une disponibilité optimale, vous devez utiliser la configuration de port cible FC recommandée. 
---
= Recommandations pour la configuration des ports FC cibles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour des performances optimales et une disponibilité optimale, vous devez utiliser la configuration de port cible FC recommandée.

Le tableau suivant indique l'ordre d'utilisation des ports préféré pour les ports intégrés FC et FC-NVMe cibles. Pour les adaptateurs d'extension, les ports FC doivent être répartis de manière à ne pas utiliser le même ASIC pour la connectivité. L'ordre de slot préféré est indiqué dans le https://hwu.netapp.com["NetApp Hardware Universe"^] Pour la version du logiciel ONTAP utilisée par votre contrôleur.

La connectivité FC-NVMe est prise en charge sur les modèles suivants :

* AFF A300
+
[NOTE]
====
Les ports intégrés des systèmes AFF A300 ne prennent pas en charge FC-NVMe.

====
* AFF A700
* AFF A700s
* AFF A800


[NOTE]
====
Les systèmes FAS2520 ne disposent pas de ports FC intégrés et ne prennent pas en charge les adaptateurs add-on.

====
[cols="3*"]
|===
| Contrôleur | Paires de ports avec ASIC partagé | Nombre de ports cibles : ports préférés 


 a| 
FAS9000, AFF A700, AFF A700S ET AFF A800
 a| 
Aucune
 a| 
Tous les ports de données se trouvent sur des adaptateurs d'extension. Voir https://hwu.netapp.com["NetApp Hardware Universe"^] pour en savoir plus.



 a| 
8080, 8060 et 8040
 a| 
0e+0f

0g+0h
 a| 
1 : 0e

2 : 0e, 0g

3 : 0e, 0g, 0h

4 : 0e, 0g, 0f, 0h



 a| 
FAS8200 ET AFF A300
 a| 
0g+0h
 a| 
1: 0g

2: 0g, 0h



 a| 
8020
 a| 
0c+0d
 a| 
1 : 0c

2 : 0c, 0d



 a| 
62xx
 a| 
0a+0b

0c+0d
 a| 
1 : 0a

2 : 0a, 0c

3 : 0a, 0c, 0b

4 : 0a, 0c, 0b, 0d



 a| 
32xx
 a| 
0c+0d
 a| 
1 : 0c

2 : 0c, 0d



 a| 
FAS2554, FAS2552, FAS2600 SERIES, FAS2720, FAS2750, AFF A200 ET AFF A220
 a| 
0c+0d

0e+0f
 a| 
1 : 0c

2 : 0c, 0e

3 : 0c, 0e, 0d

4 : 0c, 0e, 0d, 0f

|===