---
permalink: san-config/fc-target-port-supported-speeds-reference.html 
sidebar: sidebar 
keywords: fc, target, port, supported, speeds 
summary: 'Les ports cibles FC peuvent être configurés pour s"exécuter à différentes vitesses. Vous devez définir la vitesse du port cible en fonction de la vitesse du périphérique auquel il se connecte. Tous les ports cibles utilisés par un hôte donné doivent être définis sur la même vitesse.' 
---
= Vitesses prises en charge par le port FC cible
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les ports cibles FC peuvent être configurés pour s'exécuter à différentes vitesses. Vous devez définir la vitesse du port cible en fonction de la vitesse du périphérique auquel il se connecte. Tous les ports cibles utilisés par un hôte donné doivent être définis sur la même vitesse.

Les ports cibles FC peuvent être utilisés pour les configurations FC-NVMe de la même manière qu'ils sont utilisés pour les configurations FC.

Vous devez définir la vitesse du port cible afin qu'elle corresponde à la vitesse du périphérique auquel il se connecte au lieu d'utiliser la négociation automatique. Un port défini pour la négociation automatique peut prendre plus de temps pour se reconnecter après un basculement/rétablissement ou une autre interruption.

Vous pouvez configurer les ports intégrés et les adaptateurs d'extension pour qu'ils s'exécutent à la vitesse suivante. Chaque contrôleur et port d'adaptateur d'extension peuvent être configurés individuellement pour différentes vitesses, selon les besoins.

[cols="4*"]
|===
| Ports 4 Go | Ports 8 Go | Ports 16 Go | Ports 32 Go 


 a| 
* 4 Go
* 2 Go
* 1 Go

 a| 
* 8 Go
* 4 Go
* 2 Go

 a| 
* 16 Go
* 8 Go
* 4 Go

 a| 
* 32 Go
* 16 Go
* 8 Go


|===
[NOTE]
====
Les ports UTA2 peuvent utiliser un adaptateur SFP+ de 8 Gb pour prendre en charge les vitesses de 8, 4 et 2 Go, si nécessaire.

====