---
permalink: san-config/fc-target-port-config-recommendations-concept.html 
sidebar: sidebar 
keywords: fc, target, port, configuration, recommendations 
summary: Pour des performances optimales et une disponibilité optimale, vous devez utiliser la configuration de port cible FC recommandée. 
---
= Vitesses et configuration recommandées des ports FC target pour les systèmes ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les ports cibles FC peuvent être configurés et utilisés pour le protocole FC-NVMe de la même manière qu'ils sont configurés et utilisés pour le protocole FC. La prise en charge du protocole FC-NVMe varie en fonction de votre plateforme et de votre version de ONTAP. Utilisez NetApp Hardware Universe pour vérifier le support.

Pour des performances optimales et une disponibilité optimale, vous devez utiliser la configuration de port cible recommandée indiquée dans le https://hwu.netapp.com["NetApp Hardware Universe"^] pour votre plate-forme spécifique.



== Configuration des ports FC target avec ASIC partagés

Les plates-formes suivantes ont des paires de ports avec des circuits intégrés (ASIC) partagés propres aux applications. Si vous utilisez un adaptateur d'extension avec ces plates-formes, vous devez configurer vos ports FC de sorte qu'ils n'utilisent pas le même ASIC pour la connectivité.

[cols="3*"]
|===
| Contrôleur | Paires de ports avec ASIC partagé | Nombre de ports cibles : ports recommandés 


 a| 
* FAS8200
* AFF A300

 a| 
0g+0h
 a| 
1 : 0g 2 : 0g, 0h



 a| 
* FAS2720
* FAS2750
* AVEC AFF A220

 a| 
0c+0d 0e+0f
 a| 
1 : 0c 2 : 0c, 0e 3 : 0c, 0e, 0d 4 : 0c, 0e, 0d, 0f

|===


== Vitesses prises en charge par le port FC cible

Les ports cibles FC peuvent être configurés pour s'exécuter à différentes vitesses. Tous les ports cibles utilisés par un hôte donné doivent être définis sur la même vitesse. Vous devez définir la vitesse du port cible en fonction de la vitesse du périphérique auquel il se connecte. N'utilisez pas la négociation automatique pour la vitesse de votre port. Un port défini pour la négociation automatique peut prendre plus de temps pour se reconnecter après un basculement/rétablissement ou une autre interruption.

Vous pouvez configurer les ports intégrés et les adaptateurs d'extension pour qu'ils s'exécutent à la vitesse suivante. Chaque contrôleur et port d'adaptateur d'extension peuvent être configurés individuellement pour différentes vitesses, selon les besoins.

[cols="4*"]
|===
| Ports 4 Go | Ports 8 Gb | Ports 16 Gb | Ports 32 Gb 


 a| 
* 4 Go
* 2 Go
* 1 Go

 a| 
* 8 Go
* 4 Go
* 2 Go

 a| 
* 16 Go
* 8 Go
* 4 Go

 a| 
* 32 Go
* 16 Go
* 8 Go


|===
Pour obtenir la liste complète des cartes prises en charge et de leurs vitesses prises en charge, consultez le NetApp Hardware Universe à l'adresse https://hwu.netapp.com["NetApp Hardware Universe"^].
