---
permalink: san-config/fcoe-supported-hop-count-reference.html 
sidebar: sidebar 
keywords: fcoe, supported, hop, count 
summary: 'Le nombre maximal de sauts Fibre Channel over Ethernet (FCoE) pris en charge entre un hôte et un système de stockage dépend du fournisseur du commutateur et de la prise en charge du système de stockage pour les configurations FCoE.' 
---
= Nombre de sauts pris en charge par FCoE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le nombre maximal de sauts Fibre Channel over Ethernet (FCoE) pris en charge entre un hôte et un système de stockage dépend du fournisseur du commutateur et de la prise en charge du système de stockage pour les configurations FCoE.

Le nombre de sauts est défini comme le nombre de commutateurs dans le chemin entre l'initiateur (hôte) et la cible (système de stockage). La documentation de Cisco Systems fait également référence à cette valeur comme le _diamètre de la structure SAN_.

Pour le protocole FCoE, vous pouvez avoir connecté les commutateurs FCoE aux commutateurs FC.

Pour les connexions FCoE de bout en bout, les commutateurs FCoE doivent exécuter une version de firmware qui prend en charge les liaisons ISL (Ethernet Inter-switch Links).

Le tableau suivant répertorie le nombre maximal de sauts pris en charge :

[cols="2*"]
|===
| Changer de fournisseur | Nombre de sauts pris en charge 


 a| 
Brocade
 a| 
7 pour FC

5 pour la FCoE



 a| 
Cisco
 a| 
7

Il est possible d'utiliser jusqu'à 3 commutateurs FCoE.

|===