---
permalink: san-config/fibre-channel-fcoe-zoning-concept.html 
sidebar: sidebar 
keywords: fibre, channel, fcoe zoning 
summary: 'Une zone FC, FC-NVMe ou FCoE est un regroupement logique d"un ou de plusieurs ports au sein d"une structure. Pour que les périphériques puissent se voir, se connecter, créer des sessions entre eux et communiquer, les deux ports doivent avoir une zone commune. La segmentation à un seul initiateur est recommandée.' 
---
= Présentation de la segmentation Fibre Channel et FCoE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une zone FC, FC-NVMe ou FCoE est un regroupement logique d'un ou de plusieurs ports au sein d'une structure. Pour que les périphériques puissent se voir, se connecter, créer des sessions entre eux et communiquer, les deux ports doivent avoir une zone commune. La segmentation à un seul initiateur est recommandée.



== Motifs de la segmentation

* La segmentation réduit ou élimine la _diaphonie_ entre les HBA initiateurs.
+
Cela se produit même dans les petits environnements et est l'un des meilleurs arguments pour la mise en œuvre du zonage. Les sous-ensembles logiques de structure créés par la segmentation éliminent les problèmes de diaphonie.

* La segmentation réduit le nombre de chemins disponibles vers un port FC, FC-NVMe ou FCoE spécifique. Elle diminue le nombre de chemins entre un hôte et une LUN précise visible.
+
Par exemple, certaines solutions de chemins d'accès multiples du système d'exploitation hôte ont une limite sur le nombre de chemins qu'elles peuvent gérer. La segmentation peut réduire le nombre de chemins qu'un pilote de chemins d'accès multiples du système d'exploitation voit. Si une solution de chemins d'accès multiples n'est pas installée sur un hôte, vérifiez qu'un seul chemin d'accès à une LUN est visible en utilisant le zoning dans la structure ou une combinaison de mappage de LUN sélectif (SLM) et de jeux de ports dans le SVM.

* Le zonage renforce la sécurité en limitant l'accès et la connectivité aux points de terminaison qui partagent une zone commune.
+
Les ports qui n'ont pas de zones en commun ne peuvent pas communiquer entre eux.

* La segmentation améliore la fiabilité du SAN en isolant les problèmes et réduit le temps de résolution des problèmes en limitant l'espace disponible.




== Recommandations pour la segmentation

* Vous devez implémenter le zoning à tout moment si quatre hôtes ou plus sont connectés à un SAN ou si SLM n'est pas implémenté sur les nœuds vers un SAN.
* Bien que la segmentation WWNN (World Wide Node Name) soit possible avec certains fournisseurs de commutateurs, la segmentation WWPN (World Wide Port Name) est nécessaire pour définir correctement un port spécifique et pour utiliser NPIV efficacement.
* La taille de la zone doit être limitée tout en maintenant la facilité de gestion.
+
Pour limiter la taille, vous pouvez faire se chevaucher plusieurs zones. En principe, une zone est définie pour chaque hôte ou cluster hôte.

* Vous devez utiliser la segmentation à un seul initiateur pour éliminer la diaphonie entre les HBA initiateurs.

