---
permalink: san-config/iscsi-config-concept.html 
sidebar: sidebar 
keywords: considerations, iscsi, configurations 
summary: Lors de la configuration de votre configuration iSCSI, plusieurs éléments sont à prendre en compte. 
---
= Présentation des configurations iSCSI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lors de la configuration de votre configuration iSCSI, plusieurs éléments sont à prendre en compte.

* Vous pouvez configurer votre configuration iSCSI avec des nœuds uniques ou avec des paires haute disponibilité.
+
La connexion directe ou l'utilisation de commutateurs Ethernet sont prises en charge pour la connectivité. Vous devez créer des LIF pour ces deux types de connectivité

* Il est recommandé de configurer une LIF de gestion pour chaque SVM prenant en charge SAN.
* Le mappage sélectif de LUN (SLM) limite les chemins utilisés pour accéder aux LUN détenus par une paire haute disponibilité.
+
Il s'agit du comportement par défaut des LUN créées avec les versions de ONTAP.

* Les paires HAUTE DISPONIBILITÉ sont définies comme les nœuds de reporting pour les chemins actif-optimisé et actif-non optimisés qui seront utilisés par l'hôte pour accéder aux LUN via ALUA.
* Il est recommandé que tous les SVM des configurations ISCSI aient au moins deux LIF par nœud dans des réseaux Ethernet séparés pour la redondance et le MPIO sur plusieurs chemins.
* Vous devez créer un ou plusieurs chemins iSCSI depuis chaque nœud d'une paire haute disponibilité à l'aide des interfaces logiques (LIF) pour permettre l'accès aux LUN qui sont gérés par la paire haute disponibilité.
+
Si un nœud tombe en panne, les LIFs ne migrent pas et ne partent pas des adresses IP du nœud partenaire défaillant. À la place, le logiciel MPIO, avec ALUA sur l'hôte, est chargé de sélectionner les chemins d'accès appropriés pour les LUN via les LIF.

* Les VLAN offrent des avantages spécifiques, comme une sécurité accrue et une fiabilité réseau améliorée que l'iSCSI peut souhaiter exploiter.

