---
permalink: san-config/support-shared-san-config-concept.html 
sidebar: sidebar 
keywords: requirements, shared, san, configurations 
summary: 'Les configurations SAN partagées sont des hôtes reliés aux systèmes de stockage ONTAP et aux systèmes de stockage d"autres fournisseurs. L"accès à des systèmes de stockage ONTAP et aux systèmes de stockage d"autres fournisseurs à partir d"un hôte unique est pris en charge dans la mesure où plusieurs conditions sont respectées.' 
---
= Configuration requise pour les hôtes SAN connectés à des systèmes ONTAP et non NetApp
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les configurations SAN partagées sont des hôtes connectés à la fois aux systèmes de stockage ONTAP et aux systèmes de stockage d'autres fournisseurs. L'accès aux systèmes de stockage ONTAP et aux systèmes de stockage d'autres fournisseurs à partir d'un hôte unique est pris en charge, dans la mesure où plusieurs conditions sont respectées.

Pour tous les systèmes d'exploitation hôtes, il est recommandé d'utiliser des adaptateurs distincts pour la connexion aux systèmes de stockage de chaque fournisseur. L'utilisation de cartes séparées réduit les risques de conflits entre les pilotes et les paramètres. Pour les connexions à un système de stockage ONTAP, le modèle d'adaptateur, le BIOS, le firmware et le pilote doivent être répertoriés comme pris en charge dans l'outil de matrice d'interopérabilité NetApp.

Vous devez définir les valeurs de temporisation requises ou recommandées et d'autres paramètres de stockage pour l'hôte. Vous devez toujours installer le logiciel NetApp ou appliquer les paramètres NetApp en dernier.

* Pour AIX, vous devez appliquer les valeurs de la version AIX Host Utilities répertoriée dans l'outil Interoperability Matrix Tool pour votre configuration.
* Pour ESX, vous devez appliquer les paramètres de l'hôte à l'aide de Virtual Storage Console pour VMware vSphere.
* Pour HP-UX, vous devez utiliser les paramètres de stockage par défaut HP-UX.
* Pour Linux, vous devez appliquer les valeurs de la version Linux Host Utilities répertoriée dans la matrice d'interopérabilité pour votre configuration.
* Pour Solaris, vous devez appliquer les valeurs de la version Solaris Host Utilities répertoriée dans la matrice d'interopérabilité pour votre configuration.
* Pour Windows, vous devez installer la version des utilitaires d'hôtes Windows répertoriée dans la matrice d'interopérabilité pour votre configuration.


.Informations associées
https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^]
