---
permalink: san-config/supported-number-fc-hop-counts-reference.html 
sidebar: sidebar 
keywords: supported, number, fc, hop counts 
summary: Le nombre maximal de sauts FC pris en charge entre un hôte et un système de stockage dépend du fournisseur du commutateur et de la prise en charge du système de stockage pour les configurations FC. 
---
= Nombre de sauts FC pris en charge
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le nombre maximal de sauts FC pris en charge entre un hôte et un système de stockage dépend du fournisseur du commutateur et de la prise en charge du système de stockage pour les configurations FC.

Le nombre de sauts est défini comme le nombre de commutateurs dans le chemin entre l'initiateur (hôte) et la cible (système de stockage). Cisco désigne également cette valeur par l'expression _diamètre de la structure SAN_.

[cols="2*"]
|===
| Changer de fournisseur | Nombre de sauts pris en charge 


 a| 
Brocade
 a| 
7 pour FC5 pour FCoE



 a| 
Cisco
 a| 
7 pour les FC il est possible d'obtenir jusqu'à 3 des commutateurs FCoE.

|===
.Informations associées
http://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Brocade/san_download.shtml#scale["Téléchargements NetApp : documents Brocade relatifs à la matrice d'évolutivité"]

http://mysupport.netapp.com/NOW/download/software/sanswitch/fcp/Cisco/download.shtml#scale["Téléchargements NetApp : documents Cisco scalabilité Matrix"]
