---
permalink: san-config/zoning-restrictions-cisco-fc-fcoe-switches-reference.html 
sidebar: sidebar 
keywords: zoning, restrictions, for cisco, fc, fcoe, switches 
summary: 'Si vous utilisez des commutateurs Cisco FC et FCoE, une seule zone de structure ne doit pas contenir plus d"une LIF cible pour le même port physique. Si plusieurs LIF présentes sur le même port se trouvent dans la même zone, les ports LIF peuvent ne pas effectuer de restauration suite à une perte de connexion.' 
---
= Restrictions de segmentation pour les commutateurs Cisco FC et FCoE
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous utilisez des commutateurs Cisco FC et FCoE, une seule zone de structure ne doit pas contenir plus d'une LIF cible pour le même port physique. Si plusieurs LIF présentes sur le même port se trouvent dans la même zone, les ports LIF peuvent ne pas effectuer de restauration suite à une perte de connexion.

Le protocole FC-NVMe utilise régulièrement des switchs FC de la même manière qu'ils sont utilisés pour le protocole FC.

* Plusieurs LIF pour les protocoles FC et FCoE peuvent partager des ports physiques sur un nœud tant qu'ils se trouvent dans des zones différentes.
* FC-NVMe et FCoE ne peuvent pas partager le même port physique.
* Les protocoles FC et FC-NVMe peuvent partager le même port physique de 32 Go.
* Les commutateurs FC et FCoE Cisco exigent que chaque LIF d'un port donné se trouve dans une zone distincte des autres LIF du port en question.
* Une seule zone peut avoir à la fois des LIF FC et FCoE. Une zone peut contenir une LIF à partir de chaque port cible du cluster, mais veillez à ne pas dépasser les limites de chemin de l'hôte et à vérifier la configuration SLM.
* Les LIF présentes sur différents ports physiques peuvent se trouver dans la même zone.
* Les commutateurs Cisco exigent la séparation des LIF.
+
Bien qu'elles ne soient pas requises, la séparation des LIF est recommandée pour tous les commutateurs


