---
permalink: upgrade/choose-target-version.html 
sidebar: sidebar 
keywords: upgrade, ontap, choose target release, target release 
summary: Choisissez la version de mise à niveau ONTAP cible en fonction des recommandations de NetApp, de vos besoins en matière de fonctionnalités ou de la version minimale recommandée pour les performances. 
---
= Choisissez votre version ONTAP cible pour une mise à niveau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous utilisez Upgrade Advisor pour générer un plan de mise à niveau pour votre cluster, le plan inclut une version ONTAP cible recommandée pour la mise à niveau.  La recommandation fournie par Upgrade Advisor est basée sur votre configuration actuelle et votre version actuelle de ONTAP.

Si vous n'utilisez pas l'outil Upgrade Advisor, vous devez choisir la version de mise à niveau ONTAP cible en fonction des recommandations de NetApp, de vos besoins en matière de fonctionnalités ou de votre version minimale afin de répondre à vos besoins en termes de performances.

* Mise à niveau vers la dernière version disponible (recommandé)
+
NetApp vous recommande de mettre à niveau votre logiciel ONTAP vers la dernière version de correctif de la dernière version numérotée de ONTAP.  Si cela n'est pas possible parce que la dernière version numérotée n'est pas prise en charge par les systèmes de stockage de votre cluster, vous devez effectuer une mise à niveau vers la dernière version numérotée prise en charge.

* Disponibilité des fonctions
+
Si vous souhaitez effectuer une mise à niveau vers la version minimale de ONTAP requise pour prendre en charge une fonctionnalité spécifique, reportez-vous au link:https://www.netapp.com/media/15984-ontap-release-recommendation-guide.pdf["Recommandations sur les versions de ONTAP"^] Pour déterminer la version de ONTAP, vous devez effectuer la mise à niveau vers.

* Version minimale recommandée
+
Si vous souhaitez limiter votre mise à niveau à la version minimale recommandée pour votre cluster, reportez-vous à la section link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU2["Versions minimales recommandées de ONTAP"^] Pour déterminer la version de ONTAP, vous devez effectuer la mise à niveau vers.


