---
permalink: upgrade/concept_upgrade_requirements_for_snapmirror.html 
sidebar: sidebar 
keywords: ontap, upgrade, requirements, snapmirror 
summary: Vous devez effectuer certaines tâches pour mettre à niveau un cluster qui exécute SnapMirror. 
---
= Conditions de mise à niveau requises pour SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez effectuer certaines tâches pour mettre à niveau un cluster qui exécute SnapMirror.

* Si vous mettez à niveau des clusters avec des relations DP SnapMirror, vous devez mettre à niveau le cluster/les nœuds de destination avant de mettre à niveau le cluster/les nœuds source.
* Avant de mettre à niveau un cluster exécutant SnapMirror, les opérations SnapMirror doivent être suspendues pour chaque nœud qui contient des volumes de destination, et chaque SVM peering doit avoir un nom unique sur l'ensemble des clusters.
+
Pour éviter toute défaillance des transferts SnapMirror, vous devez suspendre les opérations SnapMirror. Vous pouvez également suspendre les transferts SnapMirror sur un volume de destination particulier et mettre à niveau le nœud de destination propriétaire avant de mettre à niveau les nœuds source. Les transferts SnapMirror pour tous les autres volumes de destination peuvent ainsi continuer. Le tableau ci-dessous décrit les deux options permettant de suspendre les opérations SnapMirror.

+
[cols="3*"]
|===
| Option | Description | Mettre à niveau les nœuds de destination avant les nœuds source ? 


 a| 
Suspendre les opérations SnapMirror pendant toute la durée de la mise à niveau sans interruption.
 a| 
La méthode la plus simple pour la mise à niveau dans un environnement SnapMirror consiste à interrompre toutes les opérations SnapMirror, à effectuer la mise à niveau, puis à reprendre les opérations SnapMirror. Cependant, aucun transfert SnapMirror n'aura lieu pendant l'ensemble de la mise à niveau sans interruption. Vous devez utiliser cette méthode si votre cluster contient des nœuds qui sont des volumes en miroir les uns sur les autres.
 a| 
Non, les nœuds peuvent être mis à niveau dans n'importe quel ordre.



 a| 
Suspendre les opérations SnapMirror pour un volume de destination à la fois.
 a| 
Vous pouvez interrompre les transferts SnapMirror pour un volume de destination spécifique, mettre à niveau le nœud (ou une paire HA) contenant le volume de destination, mettre à niveau le nœud (ou une paire HA) contenant le volume source, puis reprendre les transferts SnapMirror pour le volume de destination. Cette méthode permet de continuer les transferts SnapMirror pour tous les autres volumes de destination pendant la mise à niveau des nœuds contenant les volumes de destination et source d'origine.
 a| 
Oui.

|===


SVM peering nécessite que les noms de SVM soient uniques sur tous les clusters. Il est recommandé de nommer les SVM avec un nom de domaine complet unique (FQDN), par exemple, « dataVerser.HQ » ou « irrirorVserver.Offsite ». L'utilisation du style de nom FQDN facilite grandement la tâche de garantir l'unicité.

.Informations associées
link:../concepts/index.html["Concepts relatifs à ONTAP"]
