---
permalink: upgrade/concept_mixed_version_requirements.html 
sidebar: sidebar 
keywords: ontap, upgrade, mixed, version, clusters, mixed-version nodes, requirements 
summary: Un cluster ONTAP à version mixte se compose de nœuds exécutant deux versions principales de ONTAP différentes, telles que ONTAP 9.8 et 9.12.1. Les clusters ONTAP à versions mixtes ne sont pris en charge que dans des scénarios spécifiques. 
---
= Vérifiez la compatibilité des versions ONTAP avec les clusters à versions mixtes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dans un cluster ONTAP à version mixte, les nœuds exécutent deux versions principales de ONTAP différentes pendant un court instant. Par exemple, un cluster avec des nœuds exécutant ONTAP 9.8 et 9.12.1 ou ONTAP 9.9.1 et 9.13.1 est un cluster à version mixte. Les clusters avec des nœuds exécutant différents niveaux de patch dans la même version, comme ONTAP 9.9.1P1 et 9.9.1P5, ne sont pas des clusters à versions mixtes.


NOTE: Cloud Volumes ONTAP ne prend pas en charge les clusters à versions mixtes.

NetApp prend en charge les clusters ONTAP à versions mixtes pendant une période limitée et dans des scénarios spécifiques.

Les scénarios suivants sont les plus courants dans lesquels un cluster ONTAP sera dans un état de version mixte :

* Mises à niveau logicielles ONTAP dans les clusters de grande taille
+
La mise à niveau de tous les nœuds d'un cluster de grande taille peut prendre plusieurs jours, voire plusieurs semaines. Le cluster entre et reste dans un état de version mixte jusqu'à la mise à niveau de tous les nœuds.

* Des mises à niveau logicielles ONTAP sont nécessaires lorsque vous prévoyez d'ajouter de nouveaux nœuds à un cluster
+
Vous pouvez ajouter de nouveaux nœuds à votre cluster pour augmenter sa capacité, ou vous pouvez ajouter de nouveaux nœuds lors du processus de remplacement complet de vos contrôleurs. Dans les deux cas, vous devrez peut-être saisir un état de version mixte pour pouvoir migrer vos données depuis des contrôleurs existants vers les nouveaux nœuds de votre nouveau système.



Pour un fonctionnement optimal du cluster, la durée pendant laquelle celui-ci se trouve dans un état à version mixte doit être aussi courte que possible. La durée maximale pendant laquelle un cluster peut prendre en charge dans un état de version mixte dépend de la version ONTAP la plus faible du cluster.

[cols="2"]
|===
| Si la version la plus basse de ONTAP s'exécutant dans le cluster de version mixte est... | Vous pouvez alors rester dans un état de version mixte pendant un maximum de... 


| ONTAP 9.8 ou version ultérieure | 90 jours 


| ONTAP 9.7 ou version antérieure | 7 jours 
|===
Le cluster étant à l'état de version mixte, vous ne devez pas saisir de commandes pour modifier le fonctionnement ou la configuration du cluster, à l'exception de celles requises pour le processus de mise à niveau ou de migration des données. Par exemple, les activités telles que la migration de LIF, les opérations planifiées de basculement du stockage ou la création ou suppression d'objets à grande échelle ne doivent pas être effectuées avant la fin de la mise à niveau et de la migration des données.



== Prise en charge de clusters à version mixte pour les mises à niveau du logiciel ONTAP

Vous pouvez entrer un état de version mixte avec n'importe quelle version de ONTAP prise en charge pour une mise à niveau directe à partir de votre version la plus basse. Par exemple, si vous exécutez ONTAP 9.11.1, vous pouvez entrer un état de version mixte avec les nœuds exécutant ONTAP 9.15.1. Vous ne pouvez pas entrer un état de version mixte avec des nœuds exécutant ONTAP 9.11.1 et ONTAP 9.16.1. ONTAP 9.16.1 n'est pas pris en charge pour la mise à niveau directe à partir de ONTAP 9.11.1.


NOTE: Les versions de correctifs ONTAP (P) n'ont aucun impact sur la compatibilité des clusters mixtes. Par exemple, si vous utilisez ONTAP 9.11.1P6, votre version ONTAP actuelle pour la compatibilité des clusters mixtes est ONTAP 9.11.1. Si vous utilisez ONTAP 9.12.1 et souhaitez effectuer une mise à niveau vers ONTAP 9.15.1P2, votre ONTAP cible pour la compatibilité des clusters mixtes est ONTAP 9.15.1.

Pour effectuer une mise à niveau vers une version ONTAP qui n'est pas prise en charge pour une mise à niveau directe à partir de votre version actuelle, vous devez effectuer une mise à niveau en plusieurs étapes. Dans une mise à niveau en plusieurs étapes, vous entrez d'abord un état de version mixte avec la version la plus élevée prise en charge pour une mise à niveau directe à partir de votre version actuelle. Vous avez terminé cette mise à niveau, puis vous effectuez une mise à niveau séparée vers votre version cible. Par exemple, si la version la plus récente est ONTAP 9.10.1 et que vous souhaitez effectuer une mise à niveau vers ONTAP 9.16.1, vous devez d'abord saisir un état de version mixte pour mettre à niveau tous vos nœuds vers ONTAP 9.14.1. Ensuite, vous effectuez une mise à niveau séparée de ONTAP 9.14.1 vers ONTAP 9.16.1. En savoir plus sur link:concept_upgrade_paths.html#types-of-upgrade-paths["mises à niveau en plusieurs étapes"] et link:concept_upgrade_paths.html#supported-upgrade-paths["chemins de mise à niveau pris en charge"].

Un cluster à versions mixtes ne peut contenir que deux versions majeures de ONTAP. Par exemple, vous pouvez avoir un cluster à version mixte avec des nœuds exécutant ONTAP 9.13.1 et 9.15.1 ou avec des nœuds exécutant ONTAP 9.13.1 et 9.16.1. Vous ne pouvez pas avoir de cluster à version mixte avec des nœuds exécutant ONTAP 9.13.1, 9.15.1 et 9.16.1.

[cols="25,25,50"]
|===
| Si votre version actuelle de ONTAP est… | Et votre version ONTAP cible est… | L'état de version mixte pour la mise à niveau est… 


| 9.17.1 | 9.18.1 | Pris en charge 


.2+| 9.16.1 | 9.18.1 | Pris en charge 


| 9.17.1 | Pris en charge 


.3+| 9.15.1 | 9.18.1 | Pris en charge 


| 9.17.1 | Pris en charge 


| 9.16.1 | Pris en charge 


.4+| 9.14.1 | 9.18.1 | Pris en charge 


| 9.17.1 | Pris en charge 


| 9.16.1 | Pris en charge 


| 9.15.1 | Pris en charge 


.5+| 9.13.1 | 9.18.1 | Non pris en charge 


| 9.17.1 | Pris en charge 


| 9.16.1 | Pris en charge 


| 9.15.1 | Pris en charge 


| 9.14.1 | Pris en charge 


.5+| 9.12.1 | 9.17.1 ou version ultérieure | Non pris en charge 


| 9.16.1 | Pris en charge 


| 9.15.1 | Pris en charge 


| 9.14.1 | Pris en charge 


| 9.13.1 | Pris en charge 


.5+| 9.11.1 | 9.16.1 ou ultérieure  a| 
Non pris en charge



| 9.15.1 | Pris en charge 


| 9.14.1 | Pris en charge 


| 9.13.1 | Pris en charge 


| 9.12.1 | Pris en charge 


.5+| 9.10.1 | 9.15.1 ou ultérieure  a| 
Non pris en charge



| 9.14.1 | Pris en charge 


| 9.13.1 | Pris en charge 


| 9.12.1 | Pris en charge 


| 9.11.1 | Pris en charge 


.5+| 9.9.1 | 9.14.1 ou version ultérieure  a| 
Non pris en charge



| 9.13.1 | Pris en charge 


| 9.12.1 | Pris en charge 


| 9.11.1 | Pris en charge 


| 9.10.1 | Pris en charge 


.5+| 9.8 | 9.13.1 ou version ultérieure  a| 
Non pris en charge



| 9.12.1 | Pris en charge 


| 9.11.1 | Pris en charge 


| 9.10.1  a| 
Pris en charge



| 9.9.1 | Pris en charge 
|===


== Ajout de nouveaux nœuds à un cluster ONTAP

Si vous prévoyez d'ajouter de nouveaux nœuds au cluster et que ces nœuds nécessitent une version minimale de ONTAP ultérieure à la version actuellement en cours d'exécution, vous devez effectuer toutes les mises à niveau logicielles prises en charge sur les nœuds existants du cluster avant d'ajouter de nouveaux nœuds. Dans l'idéal, vous devez mettre à niveau tous les nœuds existants vers la version minimale de ONTAP requise par les nœuds que vous prévoyez d'ajouter au cluster. Toutefois, si cela n'est pas possible parce que certains de vos nœuds ne prennent pas en charge la version ultérieure de ONTAP, vous devrez entrer un état de version mixte pendant une durée limitée dans le cadre de votre processus de mise à niveau.

.Étapes
. link:concept_upgrade_methods.html["Mise à niveau"] Les nœuds qui ne prennent pas en charge la version ONTAP minimale requise par vos nouveaux contrôleurs seront mis à niveau vers la version ONTAP la plus élevée qu'ils prennent en charge.
+
Par exemple, si vous avez un FAS8080 exécutant ONTAP 9.5 et que vous ajoutez une nouvelle plateforme C-Series exécutant ONTAP 9.12.1, vous devez mettre à niveau votre FAS8080 vers ONTAP 9.8 (qui est la version ONTAP la plus élevée qu'il prend en charge).

. link:../system-admin/add-nodes-cluster-concept.html["Ajoutez les nouveaux nœuds à votre cluster"^].
. link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-create-aggregate-move-volumes.html["Migration des données"^] des nœuds en cours de suppression du cluster vers les nouveaux nœuds ajoutés.
. link:../system-admin/remove-nodes-cluster-concept.html["Supprimez les nœuds non pris en charge du cluster"^].
. link:concept_upgrade_methods.html["Mise à niveau"] le cluster à la même version ONTAP et au même niveau de correctif exécuté sur les nouveaux nœuds ou au link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU2["dernière version de correctif recommandée"^] pour la version ONTAP exécutée sur les nouveaux nœuds.
. Vérifiez que tous les nœuds exécutent la même version ONTAP .
+
.. Afficher la version ONTAP exécutée sur le cluster :
+
[source, cli]
----
version
----
.. Afficher la version ONTAP exécutée sur chaque nœud du cluster :
+
[source, cli]
----
version *
----


+
S'il existe une différence entre la version ONTAP signalée dans la sortie pour le `version *` (groupe) et `version` (commandes de nœuds individuels), mettez à jour tous les nœuds avec la même version ONTAP et du correctif en exécutant une link:concept_upgrade_methods.html["mise à jour de l'image du cluster"].



Pour plus d'informations sur la migration des données, voir :

* link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-create-aggregate-move-volumes.html["Création d'un agrégat et déplacement des volumes vers les nouveaux nœuds"^]
* link:https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_linux_iscsi_hosts_from_mcc_fc_to_mcc_ip_nodes.html#setting-up-new-iscsi-connections["Configuration de nouvelles connexions iSCSI pour les déplacements de volumes SAN"^]
* link:../encryption-at-rest/encrypt-existing-volume-task.html["Déplacement de volumes avec chiffrement"^]

