---
permalink: upgrade/concept_upgrade_methods.html 
sidebar: sidebar 
keywords: upgrade, methods, andu, ndu, automated, automatic, system manager, cli, nondisruptive, disruptive 
summary: 'La méthode utilisée pour la mise à niveau dépend de votre configuration.  Le cas échéant, la mise à niveau automatisée sans interruption (ANDU) utilisant System Manager est la méthode recommandée.' 
---
= Méthodes de mise à niveau du logiciel ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez effectuer une mise à niveau automatisée de votre logiciel ONTAP à l'aide de la fonction gestion du système. Vous pouvez également effectuer une mise à niveau automatique ou manuelle à l'aide de l'interface de ligne de commande ONTAP. La méthode utilisée pour mettre à niveau ONTAP dépend de votre configuration, de votre version actuelle de ONTAP et du nombre de nœuds dans votre cluster. NetApp recommande d'utiliser System Manager pour effectuer des mises à niveau automatisées, sauf si la configuration requiert une approche différente. Par exemple, si vous disposez d'une configuration MetroCluster avec 4 nœuds exécutant ONTAP 9.3 ou version ultérieure, vous devez utiliser System Manager pour effectuer une mise à niveau automatisée (parfois appelée mise à niveau automatisée sans interruption ou ANDU). Si vous avez une configuration MetroCluster avec 8 nœuds exécutant ONTAP 9.2 ou une version antérieure, vous devez utiliser l'interface de ligne de commande pour effectuer une mise à niveau manuelle.

Une mise à niveau peut être exécutée à l'aide du processus de mise à niveau par déploiement ou par lots. Ces deux solutions ne perturbent pas l'activité.

.Mises à niveau du déploiement ONTAP
Lors du processus de mise à niveau par déploiement, un nœud est mis hors ligne et mis à niveau alors que son partenaire prend le relais. Une fois la mise à niveau du nœud terminée, le nœud partenaire contrôle à nouveau le nœud propriétaire d'origine et le processus est répété sur le nœud partenaire. Chaque paire haute disponibilité supplémentaire est mise à niveau séquencement jusqu'à ce que toutes les paires haute disponibilité exécutent la version cible. Le processus de mise à niveau par déploiement est le processus par défaut pour les clusters de moins de 8 nœuds.

.Mises à niveau par lots ONTAP
Lors du processus de mise à niveau par lots, le cluster est divisé en plusieurs lots, chacun contenant plusieurs paires haute disponibilité. Dans le premier lot, la moitié des nœuds est mise à niveau, suivie par ses partenaires dans le domaine de la haute disponibilité. Le processus est ensuite répété séquentiellement pour les lots restants. Le processus de mise à niveau par lot est le processus par défaut pour les clusters de 8 nœuds ou plus.

Pour les mises à niveau automatisées, ONTAP installe automatiquement l'image ONTAP cible sur chaque nœud, valide les composants du cluster pour s'assurer qu'il peut être mis à niveau sans interruption, puis exécute une mise à niveau par lot ou par déploiement en arrière-plan en fonction du nombre de nœuds. Dans le cas des mises à niveau manuelles, l'administrateur vérifie que chaque nœud du cluster est prêt pour la mise à niveau, puis effectue la procédure d'exécution d'une mise à niveau par déploiement.



== Méthodes de mise à niveau recommandées pour ONTAP en fonction de la configuration

Les méthodes de mise à niveau prises en charge par votre configuration sont répertoriées par ordre d'utilisation recommandée.

[cols="4"]
|===
| Configuration | Version ONTAP | Nombre de nœuds | Méthode de mise à niveau recommandée 


| Standard | 9.0 ou ultérieure | 2 ou plus  a| 
* xref:task_upgrade_andu_sm.html[Continuité de l'activité automatisée grâce à System Manager]
* xref:task_upgrade_andu_cli.html[Automatisation de la continuité de l'activité à l'aide de l'interface]




| Standard | 9.0 ou ultérieure | Unique | xref:task_upgrade_disruptive_automated_cli.html[Interruption automatisée] 


| MetroCluster | 9.3 ou ultérieure | 8  a| 
* xref:task_upgrade_andu_cli.html[Automatisation de la continuité de l'activité à l'aide de l'interface]
* xref:task_updating_a_four_or_eight_node_mcc.html[Continuité manuelle de l'activité pour les MetroCluster à 4 ou 8 nœuds via l'interface de ligne de commande]




| MetroCluster | 9.3 ou ultérieure | 2,4  a| 
* xref:task_upgrade_andu_sm.html[Continuité de l'activité automatisée grâce à System Manager]
* xref:task_upgrade_andu_cli.html[Automatisation de la continuité de l'activité à l'aide de l'interface]




| MetroCluster | 9.2 ou antérieure | 4, 8 | xref:task_updating_a_four_or_eight_node_mcc.html[Continuité manuelle de l'activité pour les MetroCluster à 4 ou 8 nœuds via l'interface de ligne de commande] 


| MetroCluster | 9.2 ou antérieure | 2 | xref:task_updating_a_two_node_metrocluster_configuration_in_ontap_9_2_and_earlier.html[Continuité manuelle de l'activité pour le MetroCluster à 2 nœuds via l'interface de ligne de commande] 
|===
ANDU l'utilisation de System Manager est la méthode de mise à niveau recommandée pour toutes les mises à niveau de correctifs, quelle que soit la configuration.


NOTE: A xref:task_updating_an_ontap_cluster_disruptively.html[mise à niveau manuelle sans interruption] peut être effectué sur n'importe quelle configuration.  Cependant, vous ne devez pas effectuer une mise à niveau perturbation sauf si vous pouvez mettre le cluster hors ligne pendant la durée de la mise à niveau. Si vous travaillez dans un environnement SAN, vous devez être prêt à arrêter ou à suspendre tous les clients SAN avant d'effectuer une mise à niveau entraînant des perturbations. Les interruptions sont réalisées à l'aide de l'interface de ligne de commandes ONTAP.
