---
permalink: upgrade/concept_upgrade_requirements_for_metrocluster_configurations.html 
sidebar: sidebar 
keywords: ontap, upgrade, update, requirements, metrocluster, mcc, general, normal, operations, switchover 
summary: Si vous devez mettre à niveau une configuration MetroCluster, vous devez tenir compte de certaines exigences importantes. 
---
= Configuration requise pour la mise à niveau des configurations MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous devez mettre à niveau une configuration MetroCluster, vous devez tenir compte de certaines exigences importantes.



== Méthodes requises pour effectuer des mises à niveau majeures et mineures des configurations MetroCluster

Les mises à niveau de correctifs des configurations MetroCluster peuvent être réalisées avec une procédure de mise à niveau sans interruption automatique.

Depuis ONTAP 9.3, les principales mises à niveau des configurations MetroCluster peuvent être réalisées par une procédure de mise à niveau sans interruption automatique. Pour les systèmes exécutant ONTAP 9.2 ou une version antérieure, les mises à niveau majeures vers les configurations MetroCluster doivent être réalisées avec la procédure de mise à niveau sans interruption propre aux configurations MetroCluster.



== Exigences générales

* La même version de ONTAP doit être exécutée sur les deux clusters.
+
Vous pouvez vérifier la version de ONTAP à l'aide de la commande version.

* La configuration MetroCluster doit être en mode normal ou basculement.
+

NOTE: La mise à niveau en mode basculement n'est prise en charge que dans les mises à niveau de correctifs mineurs.

* Dans toutes les configurations, à l'exception des clusters à deux nœuds, vous pouvez mettre à niveau les deux clusters à la fois sans interruption.
+
Pour assurer la mise à niveau sans interruption dans des clusters à deux nœuds, les clusters doivent être mis à niveau à un nœud à la fois.

* L'état RAID ne doit pas être resynchronisés dans les deux clusters.
+
Au cours de la correction MetroCluster, les agrégats mis en miroir sont resynchronisés. Vous pouvez vérifier si la configuration MetroCluster est dans cet état en utilisant le `storage aggregate plex show -in-progress true` commande. Si des agrégats sont synchronisés, vous ne devez pas effectuer de mise à niveau tant que la resynchronisation n'est pas terminée.

* Les opérations de basculement négociées échouent alors que la mise à niveau est en cours.
+
Pour éviter tout problème de mise à niveau ou de restauration des opérations, évitez tout basculement non planifié lors d'une opération de mise à niveau ou de restauration, sauf si tous les nœuds des deux clusters exécutent la même version d'ONTAP.





== Configuration requise pour un fonctionnement normal

* Les LIFs du SVM source doivent être up et situées sur leurs home nœuds.
+
Les LIF de données du SVM de destination ne sont pas nécessairement stockées sur leurs nœuds de base.

* Tous les agrégats du site local doivent être en ligne.
* Tous les volumes root et de données possédés par les SVM du cluster local doivent être en ligne.




== Configuration requise pour le basculement

* Toutes les LIFs doivent être up et situées sur leur home node.
* Tous les agrégats doivent être en ligne, à l'exception des agrégats root du site de DR.
+
Les agrégats racine du site de reprise après incident sont hors ligne pendant certaines phases de basculement.

* Tous les volumes doivent être en ligne.


.Informations associées
link:task_verifying_the_networking_and_storage_status_for_metrocluster_cluster_is_ready.html["Vérification de l'état du réseau et du stockage pour les configurations MetroCluster"]
