---
permalink: upgrade/concept_upgrade_requirements_for_metrocluster_configurations.html 
sidebar: sidebar 
keywords: ontap, upgrade, update, requirements, metrocluster, configuration, mcc, general, normal, operations, switchover 
summary: Avant de mettre à niveau le logiciel ONTAP sur une configuration MetroCluster, vos clusters doivent répondre à certaines exigences. 
---
= Vérifier les conditions de mise à niveau de ONTAP pour les configurations MetroCluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de mettre à niveau le logiciel ONTAP sur une configuration MetroCluster, vos clusters doivent répondre à certaines exigences.

* La même version de ONTAP doit être exécutée sur les deux clusters.
+
Vous pouvez vérifier la version de ONTAP à l'aide de la commande version.

* Si vous effectuez une mise à niveau majeure de ONTAP, la configuration MetroCluster doit être en mode normal.
* Si vous effectuez une mise à niveau de patch ONTAP, la configuration MetroCluster peut être en mode normal ou en mode de basculement.
* Dans toutes les configurations, à l'exception des clusters à deux nœuds, vous pouvez mettre à niveau les deux clusters à la fois sans interruption.
+
Pour assurer la mise à niveau sans interruption dans des clusters à deux nœuds, les clusters doivent être mis à niveau à un nœud à la fois.

* L'état RAID ne doit pas être resynchronisés dans les deux clusters.
+
Au cours de la correction MetroCluster, les agrégats mis en miroir sont resynchronisés. Vous pouvez vérifier si la configuration MetroCluster est dans cet état en utilisant le `storage aggregate plex show -in-progress true` commande. Si des agrégats sont synchronisés, vous ne devez pas effectuer de mise à niveau tant que la resynchronisation n'est pas terminée.

* Les opérations de basculement négociées échouent alors que la mise à niveau est en cours.
+
Pour éviter tout problème de mise à niveau ou de restauration des opérations, évitez tout basculement non planifié lors d'une opération de mise à niveau ou de restauration, sauf si tous les nœuds des deux clusters exécutent la même version d'ONTAP.





== Configuration requise pour le fonctionnement normal de MetroCluster

* Les LIFs du SVM source doivent être up et situées sur leurs home nœuds.
+
Les LIF de données du SVM de destination ne sont pas nécessairement stockées sur leurs nœuds de base.

* Tous les agrégats du site local doivent être en ligne.
* Tous les volumes root et de données possédés par les SVM du cluster local doivent être en ligne.




== Configuration requise pour le basculement MetroCluster

* Toutes les LIFs doivent être up et situées sur leur home node.
* Tous les agrégats doivent être en ligne, à l'exception des agrégats root du site de DR.
+
Les agrégats racine du site de reprise après incident sont hors ligne pendant certaines phases de basculement.

* Tous les volumes doivent être en ligne.


.Informations associées
link:task_verifying_the_networking_and_storage_status_for_metrocluster_cluster_is_ready.html["Vérification de l'état du réseau et du stockage pour les configurations MetroCluster"]
