---
permalink: upgrade/concept_verify_svm_routing.html 
sidebar: sidebar 
keywords: ontap, upgrade, verify, verifying, svm, routing 
summary: 'La table de routage d"un SVM détermine le chemin réseau utilisé par la SVM pour communiquer avec une destination. Il est important de comprendre le fonctionnement des tables de routage afin d"éviter les problèmes de réseau avant qu"ils ne surviennent.' 
---
= Vérifier la configuration du routage SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il est recommandé de configurer une route par défaut pour un SVM. Pour éviter toute interruption, avant de mettre à niveau ONTAP, vous devez vous assurer que la route par défaut est capable d'atteindre toute adresse réseau inaccessible par une route plus spécifique. Pour plus d'informations, voir link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU134["SU134 : l'accès au réseau peut être interrompu par une configuration de routage incorrecte dans ONTAP"^].

La table de routage d'un SVM détermine le chemin réseau utilisé par la SVM pour communiquer avec une destination. Il est important de comprendre comment fonctionnent les tables de routage afin d'éviter les problèmes de réseau avant qu'ils ne surviennent.

Les règles de routage sont les suivantes :

* ONTAP achemine le trafic sur l'itinéraire le plus spécifique disponible.
* ONTAP achemine le trafic sur une route de passerelle par défaut (ayant 0 bits de masque de réseau) comme dernier recours, lorsque des routes plus spécifiques ne sont pas disponibles.


Dans le cas de routes avec la même destination, le même masque de réseau et la même mesure, il n'est pas garanti que le système utilisera la même route après un redémarrage ou après une mise à niveau. Cela peut être particulièrement problématique si vous avez configuré plusieurs routes par défaut.
