---
permalink: upgrade/concept_considerations_for_session_oriented_protocols.html 
sidebar: sidebar 
keywords: ontap, upgrade, update, considerations, session-oriented, protocols, impact, io, client, session, disruption, disrupted, smb, hyper-v, sql, server, ndo, nondisruptive, continuous availability, nfsv4.x, ndmp, backup, restores 
summary: 'Les clusters et les protocoles orientés session peuvent avoir des effets néfastes sur les clients et les applications dans certains domaines, tels que le service d"E/S pendant les mises à niveau.' 
---
= Découvrez les effets indésirables des protocoles orientés session lors des mises à niveau d'ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les clusters et les protocoles orientés session peuvent avoir des effets néfastes sur les clients et les applications dans certains domaines, tels que le service d'E/S pendant les mises à niveau.

Si vous utilisez des protocoles orientés session, prenez en compte les points suivants :

* PME
+
Si vous utilisez des partages disponibles en continu (CA) avec SMBv3, vous pouvez utiliser le système automatisé
Méthode de mise à niveau sans interruption (avec System Manager ou l'interface de ligne de commandes), et sans interruption
expérimenté par le client.

+
Si vous accédez à des partages avec SMBv1 ou SMBv2, ou des partages non-CA avec SMBv3, les sessions client sont interrompues lors des opérations de basculement et de redémarrage de mise à niveau. Invitez les utilisateurs à arrêter leurs sessions avant de procéder à la mise à niveau.

+
Hyper-V et SQL Server sur SMB prennent en charge la continuité de l'activité. Si vous avez configuré une solution Hyper-V ou SQL Server over SMB, les serveurs d'applications et les machines virtuelles ou bases de données qui y sont contenues restent en ligne et garantissent une disponibilité continue lors de la mise à niveau de ONTAP.

* NFSv4.x
+
Les clients NFSv4.x récupèrent automatiquement des pertes de connexion lors de la mise à niveau en suivant les procédures de restauration NFSv4.x standard. Les applications peuvent rencontrer un retard temporaire des E/S au cours de ce processus.

* NDMP
+
L'état est perdu et l'utilisateur client doit recommencer l'opération.

* Les sauvegardes et les restaurations
+
L'état est perdu et l'utilisateur client doit recommencer l'opération.

+

IMPORTANT: Ne lancez pas de sauvegarde ou de restauration pendant ou immédiatement avant une mise à niveau. Cela peut entraîner une perte de données.

* Applications (par exemple, Oracle ou Exchange)
+
Les effets dépendent des applications. Dans le cas des applications basées sur le délai d'expiration, il est possible que vous puissiez modifier le paramètre de délai d'expiration sur une durée supérieure au délai de redémarrage de ONTAP afin de minimiser les effets indésirables.


