---
permalink: upgrade/concept_mixed_version_requirements.html 
sidebar: sidebar 
keywords: ontap, upgrade, mixed, version, clusters, mixed-version nodes, requirements 
summary: Un cluster ONTAP à version mixte se compose de nœuds exécutant deux versions principales de ONTAP différentes, telles que ONTAP 9.8 et 9.12.1. Les clusters ONTAP à versions mixtes sont uniquement pris en charge par NetApp dans des scénarios spécifiques. 
---
= Clusters ONTAP à version mixte
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un cluster ONTAP à version mixte se compose de nœuds exécutant deux versions principales de ONTAP différentes pendant une durée limitée.  Par exemple, si un cluster se compose de nœuds exécutant ONTAP 9.8 et 9.12.1, il s'agit d'un cluster à version mixte.  De même, un cluster dans lequel les nœuds exécutent ONTAP 9.9.1 et 9.13.1 est un cluster à version mixte.  NetApp prend en charge les clusters ONTAP à versions mixtes pendant une période limitée et dans des scénarios spécifiques.

Les scénarios suivants sont les plus courants dans lesquels un cluster ONTAP sera dans un état de version mixte :

* Mises à niveau logicielles ONTAP dans les clusters de grande taille
* Des mises à niveau logicielles ONTAP sont nécessaires lorsque vous prévoyez d'ajouter de nouveaux nœuds à un cluster


Ces informations s'appliquent aux versions ONTAP qui prennent en charge les systèmes de plateformes NetApp, tels que les systèmes AFF A-Series et C-Series, ASA, FAS et C-Series. Ces informations ne s'appliquent pas aux versions cloud de ONTAP (9.x.0) telles que 9.12.0.



== Conditions requises pour les clusters ONTAP à versions mixtes

Si votre cluster doit avoir un état de version mixte de ONTAP, vous devez connaître les exigences et restrictions importantes.

* Un cluster ne peut pas contenir plus de deux versions principales de ONTAP différentes. Les clusters dont les nœuds fonctionnent avec différents niveaux de patch P ou D de la même version ONTAP, tels que ONTAP 9.9.1P1 et 9.9.1P5, ne sont pas considérés comme des clusters ONTAP de version mixte.
* Le cluster étant à l'état de version mixte, vous ne devez pas saisir de commandes pour modifier le fonctionnement ou la configuration du cluster, à l'exception de celles requises pour le processus de mise à niveau ou de migration des données.  Par exemple, les activités telles que la migration de LIF, les opérations planifiées de basculement du stockage ou la création ou la destruction d'objets à grande échelle ne doivent pas être effectuées avant la fin de la mise à niveau et de la migration des données.
* Pour un fonctionnement optimal du cluster, la durée pendant laquelle celui-ci se trouve dans un état à version mixte doit être aussi courte que possible.  La durée maximale pendant laquelle un cluster peut rester dans un état de version mixte dépend de la version ONTAP la plus faible du cluster.
+
[cols="2*"]
|===
| Si la version la plus basse de ONTAP s'exécutant dans le cluster de version mixte est : | Vous pouvez alors rester dans un état de version mixte pendant un maximum de 


| ONTAP 9.8 ou supérieur | 90 jours 


| ONTAP 9.7 ou inférieur | 7 jours 
|===
* À partir de ONTAP 9.8, un cluster ONTAP à version mixte peut couvrir un maximum de 4 versions majeures. Par exemple, un cluster ONTAP à version mixte peut avoir des nœuds exécutant ONTAP 9.8 et 9.12.1, ou des nœuds exécutant ONTAP 9.9.1 et 9.13.1. Un cluster ONTAP à versions mixtes avec des nœuds exécutant ONTAP 9.8 et 9.13.1 ne serait pas pris en charge, car ce cluster à versions mixtes couvre 5 versions principales.




== Mise à jour de la version ONTAP d'un grand cluster

Pour la saisie d'un état de cluster à version mixte, vous devez notamment mettre à niveau la version ONTAP d'un cluster à plusieurs nœuds afin de bénéficier des fonctionnalités disponibles dans les versions ultérieures de ONTAP 9. Lorsque vous devez mettre à niveau la version ONTAP d'un cluster de plus grande taille, vous entrez une version mixte de l'état du cluster pendant un certain temps au fur et à mesure de la mise à niveau de chaque nœud du cluster.



== Ajout de nouveaux nœuds à votre cluster

Un autre scénario de saisie d'un état de cluster de version mixte implique l'ajout de nouveaux nœuds à votre cluster. Vous pouvez ajouter de nouveaux nœuds à votre cluster pour augmenter sa capacité, ou vous pouvez ajouter de nouveaux nœuds lors du processus de remplacement complet de vos contrôleurs. Dans les deux cas, vous devez activer la migration de vos données à partir de contrôleurs existants vers les nouveaux nœuds de votre nouveau système.

Si vous prévoyez d'ajouter de nouveaux nœuds au cluster et que ces nœuds nécessitent une version minimale de ONTAP supérieure à la version actuellement en cours d'exécution, vous devez effectuer toutes les mises à niveau logicielles prises en charge sur les nœuds existants du cluster avant d'ajouter de nouveaux nœuds.

Dans l'idéal, vous devez mettre à niveau tous les nœuds existants vers la version minimale de ONTAP requise par les nœuds que vous prévoyez d'ajouter au cluster. Toutefois, si cela n'est pas possible parce que certains de vos nœuds ne prennent pas en charge la version ultérieure de ONTAP, vous devrez entrer un état de version mixte pendant une durée limitée dans le cadre de votre processus de mise à niveau. Si certains nœuds ne prennent pas en charge la version ONTAP minimale requise par vos nouveaux contrôleurs, effectuez les opérations suivantes :

. link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_methods.html["Mise à niveau"] Tous les nœuds du cluster qui prennent en charge la version minimale de ONTAP requise par vos nouveaux contrôleurs.
. Ajoutez les nouveaux nœuds à votre cluster.
+
Utilisez le cluster de commandes ONTAP `add-node -allow-mixed-version-join` au niveau de privilège avancé pour rejoindre les nouveaux nœuds.

. Migrez les données à partir de nœuds qui ne peuvent pas être mis à niveau vers un nœud exécutant la version ONTAP supérieure.
. link:https://docs.netapp.com/us-en/ontap/system-admin/remov-nodes-cluster-concept.html["Supprimez les nœuds non pris en charge du cluster"^].
+
Utilisez le cluster de commandes ONTAP `remove-node -skip-last-low-version-node-check` pour supprimer ces nœuds. (Dans ONTAP 9.3 et versions antérieures, utilisez le `cluster unjoin -skip-last-low-version-node-check` commande.)



Pour plus d'informations sur la migration des données, voir :

* link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-create-aggregate-move-volumes.html["Création d'un agrégat et déplacement des volumes vers les nouveaux nœuds"^]
* link:https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_linux_iscsi_hosts_from_mcc_fc_to_mcc_ip_nodes.html#setting-up-new-iscsi-connections["Configuration de nouvelles connexions iSCSI pour les déplacements de volumes SAN"^]
* link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/encrypt-existing-volume-task.html["Déplacement de volumes avec chiffrement"^]

