---
permalink: upgrade/considerations-authenticate-ssh-public-key-fips-concept.html 
sidebar: sidebar 
keywords: ontap, upgrade, update, considerations, ssl, fips mode, host key algorithm 
summary: 'Si le mode SSL FIPS est activé sur un cluster où les comptes d"administrateur s"authentifient avec une clé publique SSH, vous devez vous assurer que l"algorithme de clé hôte est pris en charge sur la version cible avant de mettre à niveau ONTAP.' 
---
= Vérifiez la prise en charge de l'algorithme de clé hôte SSH avant la mise à niveau de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de mettre à niveau ONTAP, si le mode SSL FIPS est activé sur un cluster où les comptes d'administrateur s'authentifient avec une clé publique SSH, vous devez vous assurer que l'algorithme de clé d'hôte est pris en charge sur la version cible.

Le tableau suivant indique les algorithmes de type de clé hôte pris en charge pour les connexions ONTAP SSH.  Ces types de clés ne s'appliquent pas à la configuration de l'authentification publique SSH.

[cols="30,30,30"]
|===


| Version de ONTAP | Types de clés pris en charge en mode FIPS | Types de clés pris en charge en mode non FIPS 


 a| 
9.11.1 et versions ultérieures
 a| 
ecdsa-sha2-nistp256
 a| 
ecdsa-sha2-nistp256 +
rsa-sha2-512 +
rsa-sha2-256 +
ssh-ed25519 +
ssh-dss +
ssh-rsa



 a| 
9.10.1 et versions antérieures
 a| 
ecdsa-sha2-nistp256 +
ssh-ed25519
 a| 
ecdsa-sha2-nistp256 +
ssh-ed25519 +
ssh-dss +
ssh-rsa

|===

NOTE: La prise en charge de l'algorithme de clé hôte ssh-ed25519 a été supprimée à partir de ONTAP 9.11.1.

Pour plus d'informations, voir link:../networking/configure_network_security_using_federal_information_processing_standards_@fips@.html["Configurez la sécurité réseau à l'aide de FIPS"].

Les comptes de clés publiques SSH existants sans les algorithmes de clé pris en charge doivent être reconfigurés avec un type de clé pris en charge avant l'activation de la mise à niveau, ou l'authentification de l'administrateur échoue.

link:../authentication/enable-ssh-public-key-accounts-task.html["En savoir plus sur l'activation des comptes de clé publique SSH."]
