---
permalink: upgrade/considerations-authenticate-ssh-public-key-fips-concept.html 
sidebar: sidebar 
keywords: ontap, upgrade, update, considerations, ssl, fips mode, host key algorithm 
summary: 'Si le mode SSL FIPS est activé sur un cluster où les comptes d"administrateur s"authentifient avec une clé publique SSH, vous devez vous assurer que l"algorithme de clé hôte est pris en charge sur la version cible avant de mettre à niveau ONTAP.' 
---
= Considérations relatives aux protocoles orientés session
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si le mode SSL FIPS est activé sur un cluster où les comptes d'administrateur s'authentifient avec une clé publique SSH, vous devez vous assurer que l'algorithme de clé hôte est pris en charge sur la version cible avant de mettre à niveau ONTAP.

*Remarque :* la prise en charge de l'algorithme de clé hôte a changé dans ONTAP 9.11.1 et versions ultérieures.

[cols="30,30,30"]
|===


| Version de ONTAP | Types de clés pris en charge | Types de clés non pris en charge 


 a| 
9.11.1 et versions ultérieures
 a| 
ecdsa-sha2-nistp256
 a| 
rsa-sha2-512 + rsa-sha2-256 + ssh-ed25519 + ssh-dss + ssh-rsa



 a| 
9.10.1 et versions antérieures
 a| 
ecdsa-sha2-nistp256 + ssh-ed25519
 a| 
ssh-dss + ssh-rsa

|===
Les comptes de clés publiques SSH existants sans les algorithmes de clé pris en charge doivent être reconfigurés avec un type de clé pris en charge avant l'activation de la mise à niveau, ou l'authentification de l'administrateur échoue.

link:../authentication/enable-ssh-public-key-accounts-task.html["En savoir plus sur l'activation des comptes de clé publique SSH."]
