---
permalink: upgrade/create-upgrade-plan.html 
sidebar: sidebar 
keywords: ontap, upgrade, plan, planning, upgrade advisor, advisor, active iq, create an upgrade plan, estimate upgrade, 
summary: Le service Upgrade Advisor de Active IQ Digital Advisor vous aide à planifier votre mise à niveau et réduit les incertitudes et les risques. 
---
= Planifier votre mise à niveau avec Upgrade Advisor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous avez un actif link:https://www.netapp.com/us/services/support-edge.aspx["Services SupportEdge"^] contrat pour link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["Conseiller digital Active IQ"^], Il est recommandé d'utiliser Upgrade Advisor pour générer un plan de mise à niveau.

Le service Upgrade Advisor de Active IQ Digital Advisor vous aide à planifier votre mise à niveau et réduit les incertitudes et les risques.

Active IQ identifie les problèmes qui peuvent être résolus dans votre environnement en passant à une version plus récente de ONTAP. Ce service vous aide à planifier une mise à niveau réussie et génère un rapport sur les problèmes vers la version ONTAP vers laquelle vous effectuez la mise à niveau.

Si vous ne disposez pas d'un contrat support Edge Services actif pour Active IQ Digital Advisor, vous devez link:prepare.html["Préparez votre mise à niveau sans Upgrade Advisor"].

.Étapes
. https://aiq.netapp.com/["Lancez Active IQ"^]
. Dans Active IQ link:https://docs.netapp.com/us-en/active-iq/task_view_risk_and_take_action.html["affichez les risques associés à votre cluster et prenez manuellement des actions correctives"^].
+
Les risques inclus dans les catégories *SW Config change*, *HW Config change* et *HW Replacement* doivent être résolus avant d'effectuer une mise à niveau ONTAP.

. Vérifiez le chemin de mise à niveau recommandé et link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["générez votre plan de mise à niveau"^].


.Et la suite
* Vous devez consulter le link:../release-notes/index.html["Notes de version de ONTAP"] Pour la version ONTAP cible recommandée pour votre cluster par Upgrade Advisor, vous devez suivre le plan généré par Upgrade Advisor pour la mise à niveau du cluster.
* Vous devriez link:reboot-sp-bmc.html["Redémarrez le processeur de service ou le contrôleur BMC"] avant le début de la mise à niveau.

