---
permalink: upgrade/download-software-image.html 
sidebar: sidebar 
keywords: ontap, software, image, download, downloading, upgrade 
summary: 'Avant de mettre à niveau ONTAP, vous devez d"abord télécharger le logiciel ONTAP à partir du site de support NetApp.' 
---
= Téléchargez l'image du logiciel ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de mettre à niveau ONTAP, vous devez d'abord télécharger l'image du logiciel ONTAP cible depuis le site du support NetApp. Selon la version de votre ONTAP, vous pouvez télécharger le logiciel ONTAP sur un serveur HTTPS, HTTP ou FTP de votre réseau, ou dans un dossier local.

[cols="2"]
|===
| Si vous exécutez... | Vous pouvez télécharger l'image à cet emplacement... 


| ONTAP 9.6 et versions ultérieures  a| 
* Un serveur HTTPS +
Le certificat CA du serveur doit être installé sur le système local.
* Un dossier local
* Un serveur HTTP ou FTP




| ONTAP 9.4 et versions ultérieures  a| 
* Un dossier local
* Un serveur HTTP ou FTP




| ONTAP 9.0 et versions ultérieures | Un serveur HTTP ou FTP 
|===
.Description de la tâche
* Si vous effectuez une mise à niveau automatisée sans interruption à l'aide d'un link:concept_upgrade_paths.html#types-of-upgrade-paths["chemin de mise à niveau multi-sauts direct"], Vous devez télécharger le progiciel pour la version intermédiaire de ONTAP et la version cible de ONTAP requise pour votre mise à niveau.  Par exemple, si vous effectuez une mise à niveau de ONTAP 9.8 vers ONTAP 9.13.1, vous devez télécharger le progiciel pour ONTAP 9.12.1 et le progiciel pour ONTAP 9.13.1.  Voir link:concept_upgrade_paths.html#supported-upgrade-paths-for-on-premises-ontap-and-ontap-select["chemins de mise à niveau pris en charge"] pour déterminer si votre mise à niveau spécifique nécessite le téléchargement d'un progiciel intermédiaire.
* Si vous mettez à niveau un système avec NetApp Volume Encryption vers ONTAP 9.5 ou une version ultérieure, vous devez télécharger l'image logicielle de ONTAP pour les pays non soumis à des restrictions, notamment NetApp Volume Encryption.
+
Si vous utilisez l'image logicielle ONTAP pour des pays limités pour mettre à niveau un système avec NetApp Volume Encryption, le système fonctionne de façon incohérente et l'accès aux volumes est perdu.

* Il n'est pas nécessaire de télécharger un pack logiciel distinct pour votre micrologiciel. La mise à jour de firmware de votre cluster est incluse dans le pack de mise à niveau logicielle ONTAP et est copiée sur le périphérique de démarrage de chaque nœud. Le nouveau micrologiciel est ensuite installé dans le cadre du processus de mise à niveau.


.Étapes
. Recherchez le logiciel ONTAP cible dans le link:https://mysupport.netapp.com/site/products/all/details/ontap9/downloads-tab["Téléchargements de logiciels"] Domaine du site de support NetApp.
+
Pour une mise à niveau ONTAP Select, sélectionnez *mise à niveau de noeud ONTAP Select*.

. Copiez l'image logicielle (par exemple, 97_q_image.tgz) à l'emplacement approprié.
+
En fonction de votre version ONTAP, l'emplacement sera un répertoire, un serveur HTTP, HTTPS ou FTP à partir duquel l'image sera desservie par le système local, ou un dossier local sur le système de stockage.


