---
permalink: upgrade/index.html 
sidebar: sidebar 
keywords: upgrade overview, upgrade, digital advisor, summary, upgrade ontap, upgrading ontap, upgrade, upgrading, ontap, software, on-premise, prepare, preparation, major upgrade, minor upgrade, patch upgrade, upgrade assistance, upgrade help, upgrade technical support 
summary: Une mise à niveau ONTAP vous permet de bénéficier de nouvelles fonctionnalités et de fonctionnalités améliorées. Suivez les étapes recommandées pour préparer votre mise à niveau avant de commencer. 
---
= En savoir plus sur la mise à niveau ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La mise à niveau de votre logiciel ONTAP vous permet de bénéficier des nouvelles fonctionnalités améliorées de ONTAP qui contribuent à réduire les coûts, accélérer les workloads stratégiques, améliorer la sécurité et étendre la portée de la protection des données disponible pour votre entreprise.

Une mise à niveau majeure d'ONTAP consiste à passer d'une version ONTAP inférieure à une version ONTAP supérieure. Un exemple serait une mise à niveau de votre cluster de ONTAP 9.14.1 à ONTAP 9.18.1. Une mise à niveau mineure (ou patch) consiste à passer d'une version ONTAP inférieure à une version ONTAP supérieure au sein de la même version numérotée. Un exemple serait une mise à niveau de votre cluster de ONTAP 9.17.1P1 à 9.17.1P4.

Pour commencer, vous pouvez utiliser l'une des méthodes suivantes pour préparer la mise à niveau.

* Conseiller de mise à niveau
+
Si vous disposez d'un contrat SupportEdge actif pour Active IQ Digital Advisor (également appelé Digital Advisor), vous devriez link:create-upgrade-plan.html["Préparez la mise à niveau avec Upgrade Advisor"]. Upgrade Advisor fournit une intelligence qui vous aide à minimiser l'incertitude et les risques en évaluant votre cluster et en créant un plan de mise à niveau spécifique à votre configuration.

+
Upgrade Advisor convient aux utilisateurs avec un environnement plus restreint qui préfèrent une expérience basée sur le cloud et centrée sur l'interface utilisateur.

+
En savoir plus sur link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["Conseiller de mise à niveau"^].

* Mise à niveau Health Checker
+
Vous pouvez également link:create-upgrade-plan.html["Préparez-vous à la mise à niveau avec Upgrade Health Checker"]. Upgrade Health Checker est un outil de conseil en matière de mise à niveau qui effectue des vérifications complètes sur site afin d’identifier les blocages et les avertissements liés à la mise à niveau. Un contrat SupportEdge n’est pas requis pour utiliser Upgrade Health Checker.

+
Upgrade Health Checker convient aux utilisateurs qui disposent d'un environnement vaste ou complexe, d'un accès limité à Internet, ou d'un cadre d'automatisation et d'orchestration existant.

+
En savoir plus sur link:https://docs.netapp.com/us-en/upgrade-health-checker/learn-about-upgrade-health-checker.html["Mise à niveau Health Checker"^].

* Préparation manuelle
+
Si vous n'utilisez pas Upgrade Advisor ou l'outil Upgrade Health Checker, vous devez link:prepare.html["préparez-vous à effectuer une mise à niveau manuelle"]. La préparation manuelle nécessite l'accomplissement de plusieurs tâches pour vérifier la présence de problèmes ou de blocages connus et garantir que votre cluster répond aux exigences nécessaires à la mise à niveau.

+
En savoir plus sur link:prepare.html["préparation de la mise à niveau manuelle"^].



Après avoir préparé votre mise à niveau, il est recommandé d'effectuer les mises à niveau à l'aide de link:task_upgrade_andu_sm.html["Mise à niveau automatisée sans interruption (ANDU) depuis System Manager"]. ANDU exploite la technologie de basculement haute disponibilité de ONTAP pour assurer le service des données sans interruption au cours de la mise à niveau.


NOTE: À partir d' ONTAP 9.12.1, System Manager est entièrement intégré à la console NetApp .  Si la console est configurée sur votre système, vous pouvez effectuer la mise à niveau via la page Systèmes.

Si vous avez besoin d'aide pour mettre à niveau votre logiciel ONTAP, les services professionnels NetApp proposent une link:https://www.netapp.com/pdf.html?item=/media/8144-sd-managed-upgrade-service.pdf["Service géré de mise à niveau"^]. Si vous souhaitez utiliser ce service, contactez votre ingénieur commercial NetApp ou link:https://www.netapp.com/forms/sales-contact/["Envoyez le formulaire de demande de renseignements NetApp"^]. Le service géré de mise à niveau ainsi que d'autres types d'assistance de mise à niveau sont disponibles pour les clients disposant de link:https://www.netapp.com/pdf.html?item=/media/8845-supportedge-expert-service.pdf["Services SupportEdge Expert"^] sans frais supplémentaires.

.Informations associées
* link:concept_upgrade_paths.html["Chemins de mise à niveau pris en charge"]

