---
permalink: upgrade/index.html 
sidebar: sidebar 
keywords: upgrade overview, upgrade, summary, upgrade ontap, upgrading ontap, upgrade, upgrading, ontap, software, on-premise, prepare, preparation, major upgrade, minor upgrade, patch upgrade, upgrade assistance, upgrade help, upgrade technical support 
summary: Une mise à niveau ONTAP vous permet de bénéficier de nouvelles fonctionnalités et de fonctionnalités améliorées. Suivez les étapes recommandées pour préparer votre mise à niveau avant de commencer. 
---
= Présentation de la mise à niveau ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La mise à niveau de votre logiciel ONTAP vous permet de bénéficier des nouvelles fonctionnalités améliorées de ONTAP qui contribuent à réduire les coûts, accélérer les workloads stratégiques, améliorer la sécurité et étendre la portée de la protection des données disponible pour votre entreprise.

Une mise à niveau majeure de ONTAP consiste à passer d'une version portant un numéro ONTAP inférieur à supérieur. Par exemple, une mise à niveau de votre cluster de ONTAP 9.8 vers ONTAP 9.12.1 est possible.  Une mise à niveau mineure (ou correctif) consiste à passer d'une version ONTAP inférieure à une version ONTAP supérieure dans la même version numérotée. Par exemple, une mise à niveau de votre cluster de ONTAP 9.12.1P1 à 9.12.1P4.

Pour commencer, vous devez link:prepare.html["préparer la mise à niveau"]. Si vous avez un contrat SupportEdge actif pour le conseiller digital Active IQ, vous devriez link:create-upgrade-plan.html#plan-your-upgrade-with-upgrade-advisor["Planifiez votre mise à niveau avec Upgrade Advisor"]. Upgrade Advisor fournit des informations intelligentes qui vous aident à minimiser l'incertitude et les risques en évaluant votre cluster et en créant un plan de mise à niveau propre à votre configuration.

Une fois que vous avez préparé la mise à niveau, il est recommandé d'effectuer les mises à niveau à l'aide de link:task_upgrade_andu_sm.html["Mise à niveau automatisée sans interruption (ANDU) depuis System Manager"].  ANDU exploite la technologie de basculement haute disponibilité d'ONTAP pour assurer le service des données sans interruption lors de la mise à niveau.


NOTE: À partir de ONTAP 9.12.1, System Manager est entièrement intégré à BlueXP. Si BlueXP est configuré sur votre système, vous pouvez effectuer une mise à niveau via l'environnement de travail BlueXP.

Si vous avez besoin d'aide pour mettre à niveau votre logiciel ONTAP, les services professionnels NetApp proposent une link:https://www.netapp.com/pdf.html?item=/media/8144-sd-managed-upgrade-service.pdf["Service géré de mise à niveau"^]. Si vous souhaitez utiliser ce service, contactez votre ingénieur commercial NetApp ou link:https://www.netapp.com/forms/sales-contact/["Envoyez le formulaire de demande de renseignements NetApp"^]. Le service géré de mise à niveau ainsi que d'autres types d'assistance de mise à niveau sont disponibles pour les clients disposant de link:https://www.netapp.com/services/support/supportedge/["Services SupportEdge"^] sans frais supplémentaires.
