---
permalink: upgrade/install-software-manual-upgrade.html 
sidebar: sidebar 
keywords: ontap, software, image, download, downloading, install, installing. manual, manually 
summary: 'Après avoir téléchargé le pack logiciel ONTAP pour une mise à niveau manuelle, vous devez l"installer localement avant de commencer la mise à niveau' 
---
= Installez le progiciel ONTAP pour les mises à niveau manuelles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir téléchargé le pack logiciel ONTAP pour une mise à niveau manuelle, vous devez l'installer localement avant de commencer la mise à niveau.

.Étapes
. Définissez le niveau de privilège sur avancé, en entrant *y* lorsque vous êtes invité à continuer : `set -privilege advanced`
+
L'invite avancée (`*>`) s'affiche.

. Installez l'image.
+
[cols="2"]
|===
| Si vous disposez de la configuration suivante... | Utilisez cette commande... 


 a| 
** Non MetroCluster
** MetroCluster à 2 nœuds

 a| 
[source, cli]
----
system node image update -node * -package <location> -replace-package true -setdefault true -background true
----
`<location>` Il peut s'agir d'un serveur Web ou d'un dossier local, selon la version de ONTAP. Pour en savoir plus, `system node image update` consultez le link:https://docs.netapp.com/us-en/ontap-cli/system-node-image-update.html["Référence de commande ONTAP"^].

Cette commande installe l'image logicielle sur tous les nœuds simultanément. Pour installer l'image sur chaque nœud un par un, ne spécifiez pas le `-background` paramètre.



 a| 
** MetroCluster à 4 nœuds
** Configuration MetroCluster à 8 nœuds

 a| 
[source, cli]
----
system node image update -node * -package <location> -replace-package true -background true -setdefault false
----
Vous devez exécuter cette commande sur les deux clusters.

Cette commande utilise une requête étendue pour modifier l'image du logiciel cible, qui est installée comme image alternative sur chaque nœud.

|===
. Entrez `y` pour continuer lorsque vous y êtes invité.
. Vérifiez que l'image logicielle est installée sur chaque nœud.
+
[source, cli]
----
system node image show-update-progress -node *
----
+
Cette commande affiche l'état actuel de l'installation de l'image logicielle. Vous devez continuer à exécuter cette commande jusqu'à ce que tous les nœuds signalent un *Run Status* de *unch* et un *Exit Status* de *Success*.

+
La commande de mise à jour de l'image du nœud système peut échouer et afficher des messages d'erreur ou d'avertissement. Après avoir résolu les erreurs ou les avertissements, vous pouvez relancer la commande.

+
Cet exemple montre un cluster à deux nœuds dans lequel l'image logicielle est installée avec succès sur les deux nœuds :

+
[listing]
----
cluster1::*> system node image show-update-progress -node *
There is no update/install in progress
Status of most recent operation:
        Run Status:     Exited
        Exit Status:    Success
        Phase:          Run Script
        Exit Message:   After a clean shutdown, image2 will be set as the default boot image on node0.
There is no update/install in progress
Status of most recent operation:
        Run Status:     Exited
        Exit Status:    Success
        Phase:          Run Script
        Exit Message:   After a clean shutdown, image2 will be set as the default boot image on node1.
2 entries were acted on.
----

