---
permalink: upgrade/prepare.html 
sidebar: sidebar 
keywords: upgrade, ontap, prepare, digital advisor, preparation, before you upgrade, plan, upgrade overview, upgrade summary, upgrade health checker 
summary: 'La préparation d"une mise à niveau ONTAP vous permet d"identifier et de limiter les risques ou les bloqueurs de mise à niveau, et de tenir compte de considérations spéciales applicables à votre configuration.' 
---
= Préparez manuellement une mise à niveau du logiciel ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous choisissez de préparer votre mise à niveau manuellement, vous devez effectuer plusieurs tâches pour vérifier s'il existe des problèmes ou blocages connus et vous assurer que votre cluster répond aux exigences nécessaires pour la mise à niveau. Par exemple, si le mode SSL FIPS est activé sur votre cluster et que les comptes administrateur utilisent des clés publiques SSH pour l'authentification, vous devez vérifier que l'algorithme de clé hôte est pris en charge dans votre version cible d'ONTAP.


NOTE: Aucune préparation manuelle n'est nécessaire lorsque vous utilisez Upgrade Advisor dans Active IQ Digital Advisor ou Upgrade Health Checker. Les deux outils fournissent une intelligence qui vous aide à planifier votre mise à niveau, à identifier les blocages et les avertissements, et à minimiser l'incertitude et le risque. En savoir plus sur link:create-upgrade-plan.html["préparation d'une mise à niveau avec Upgrade Advisor ou Upgrade Health Checker"].

.Étapes
. link:choose-target-version.html["Choisissez votre version ONTAP cible"].
. Consultez les sections _mises en garde de mise à niveau_ et _problèmes et limitations connus_ de la link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Notes de mise à jour de ONTAP 9"] pour votre version cible.
+
_Mises en garde de mise à niveau_ Décrivez les problèmes potentiels que vous devez connaître avant de procéder à la mise à niveau. _Problèmes et limitations connus_ Décrivez le comportement potentiellement inattendu du système que vous pourriez rencontrer après la mise à niveau.

+
Vous devez vous connecter avec votre compte NetApp ou créer un compte pour accéder aux notes de version.

. link:confirm-configuration.html["Confirmez le support ONTAP pour votre configuration matérielle"].
+
La plateforme matérielle, les commutateurs de gestion de cluster et les commutateurs MetroCluster IP doivent prendre en charge la version cible.  Si votre cluster est configuré pour SAN, la configuration SAN doit être entièrement prise en charge.

. link:task_check_for_common_configuration_errors_using_config_advisor.html["Utilisez Active IQ Config Advisor pour vérifier que vous n'avez pas d'erreurs de configuration courantes."]
. Consultez le ONTAP pris en charge link:concept_upgrade_paths.html#supported-upgrade-paths["chemins de mise à niveau"] pour déterminer si vous pouvez effectuer une mise à niveau directe ou si vous devez effectuer la mise à niveau par étapes.
. link:task_verifying_the_lif_failover_configuration.html["Vérifier la configuration du basculement de LIF"].
+
Avant d'effectuer une mise à niveau, vous devez vérifier que les stratégies de basculement et les groupes de basculement du cluster sont correctement configurés.

. link:concept_verify_svm_routing.html["Vérifier la configuration de routage du SVM"].
. link:special-considerations.html["Vérifier les considérations spéciales"] de votre cluster.
+
Si certaines configurations existent sur le cluster, certaines actions spécifiques doivent être effectuées avant de procéder à une mise à niveau du logiciel ONTAP.

. link:reboot-sp-bmc.html["Redémarrez le processeur de service ou le contrôleur BMC"].

