---
permalink: upgrade/reboot-sp-bmc.html 
sidebar: sidebar 
keywords: ontap, upgrade, how, firmware, updated, during 
summary: 'Vous n"avez pas besoin de mettre à jour votre micrologiciel avant une mise à niveau ONTAP.  Le firmware de votre cluster est inclus avec le pack de mise à niveau ONTAP et installé dans le cadre du processus de mise à niveau.' 
---
= Redémarrez le processeur de service ou le contrôleur BMC pour préparer la mise à jour du firmware lors d'une mise à niveau de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous n'avez pas besoin de mettre à jour manuellement votre micrologiciel avant d'effectuer une mise à niveau ONTAP.  Le firmware de votre cluster est inclus dans le pack de mise à niveau ONTAP et copié sur le périphérique de démarrage de chaque nœud.  Le nouveau micrologiciel est ensuite installé dans le cadre du processus de mise à niveau.

Le firmware des composants suivants est mis à jour automatiquement si la version de votre cluster est antérieure au firmware inclus dans le pack de mise à niveau ONTAP :

* BIOS/CHARGEUR
* Processeur de service (SP) ou contrôleur BMC (Baseboard Management Controller)
* Tiroir de stockage
* Disque
* Flash cache


Pour préparer une mise à jour en douceur, redémarrez le SP ou le BMC avant le début de la mise à niveau.

.Étape
. Redémarrez le SP ou le BMC avant la mise à niveau :
+
[source, cli]
----
system service-processor reboot-sp -node node_name
----
+
Redémarrez uniquement un SP ou un BMC à la fois.  Attendez que le processeur de stockage ou le contrôleur BMC redémarré se recycle complètement avant de redémarrer le prochain.



Vous pouvez également link:../update/firmware-task.html["mettre à jour le micrologiciel manuellement"] Entre les mises à niveau ONTAP.  Si vous avez Active IQ, c'est possible link:https://activeiq.netapp.com/system-firmware/["Affichez la liste des versions de micrologiciel actuellement incluses dans votre image ONTAP"^].

Les mises à jour du micrologiciel sont disponibles comme suit :

* link:https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics["Micrologiciel système (BIOS, BMC, SP)"^]
* link:https://mysupport.netapp.com/site/downloads/firmware/disk-shelf-firmware["Micrologiciel du tiroir"^]
* link:https://mysupport.netapp.com/site/downloads/firmware/disk-drive-firmware["Firmwares des disques et de Flash cache"^]

