---
permalink: upgrade/remove-ems-lif-service-task.html 
sidebar: sidebar 
keywords: ontap, upgrade, after, post, ems, event, management, system, lifs, messages, not, delivered 
summary: Le service Upgrade Advisor de Active IQ Digital Advisor vous aide à planifier votre mise à niveau et réduit les incertitudes et les risques. 
---
= Supprimez le service LIF EMS des stratégies de service réseau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous disposez de messages EMS (Event Management System) configurés avant la mise à niveau de ONTAP 9.7 ou version antérieure à ONTAP 9.8 ou version ultérieure , après la mise à niveau, il se peut que les messages EMS ne soient pas envoyés.

Au cours de la mise à niveau, management-ems, qui est le service EMS LIF, est ajouté à toutes les stratégies de service existantes. Cela permet d'envoyer des messages EMS depuis n'importe laquelle des LIFs associées à l'une des stratégies de service. Si la LIF sélectionnée n'a pas l'accessibilité à la destination de notification d'événement, le message n'est pas transmis.

Pour éviter cela, après la mise à niveau, vous devez supprimer le service EMS LIF des stratégies de service réseau qui ne permettent pas de reachabilité à la destination.

.Étapes
. Identifier les LIFs et les stratégies de service réseau associées via lesquelles les messages EMS peuvent être envoyés :
+
`network interface show -fields service-policy -services management-ems`

+
[listing]
----
vserver        lif            service-policy
-------------- ------------ ------------------
cluster-1      cluster_mgmt
                                      default-management
cluster-1      node1-mgmt
                                      default-management
cluster-1      node2-mgmt
                                      default-management
cluster-1      inter_cluster
                                      default-intercluster
4 entries were displayed.
----
. Vérifier la connectivité de chaque LIF à la destination EMS :
+
`network ping -lif lif_name -vserver svm_name -destination destination_address`

+
Effectuez cette opération sur chaque nœud.

+
.Exemples
[listing]
----
cluster-1::> network ping -lif node1-mgmt -vserver cluster-1 -destination 10.10.10.10
10.10.10.10 is alive

cluster-1::> network ping -lif inter_cluster -vserver cluster-1 -destination 10.10.10.10
no answer from 10.10.10.10
----
. Entrer le niveau de privilège avancé :
+
`set advanced`

. Pour les LIF qui n'ont pas de accessibilité, supprimer le service LIF management-ems des politiques de service correspondantes :
+
`network interface service-policy remove-service -vserver svm_name -policy service_policy_name -service management-ems`

. Vérifier que la LIF management-ems est désormais uniquement associée aux LIFs qui fournissent une accessibilité à la destination EMS :
+
`network interface show -fields service-policy -services management-ems`



.Liens connexes
link:https://docs.netapp.com/us-en/ontap/networking/lifs_and_service_policies96.html#service-policies-for-system-svms.["LIF et politiques de service dans ONTAP 9.6 et versions ultérieures"]
