---
permalink: upgrade/snapmirror-cascade-relationship-blocked.html 
sidebar: sidebar 
keywords: ontap, upgrade, 9.9.1. 9.10.1, update, cascade, LTR, long term retention, snapshots, considerations, secondary storage 
summary: Si vous avez configuré une relation en cascade SnapMirror sur votre cluster, vous devrez peut-être désactiver la conservation des snapshots à long terme avant la mise à niveau. 
---
= Désactivez les snapshots de conservation à long terme avant la mise à niveau de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dans une relation de volumes en cascade, les instantanés de conservation à long terme ne sont pris en charge que sur le volume de destination SnapMirror final de la cascade dans toutes les versions d' ONTAP 9. L'activation des instantanés de conservation à long terme sur n'importe quel volume intermédiaire de la cascade entraîne la perte de sauvegardes et d'instantanés.

En savoir plus surlink:../data-protection/long-term-retention-snapshots-concept.html["instantanés de rétention à long terme"] .

Si vous disposez d'une configuration non prise en charge dans laquelle les snapshots de conservation à long terme sont activés sur un volume intermédiaire d'une cascade, contactez le support technique et consultez le lien suivanthttps://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/Cascading_a_volume_with_Long-Term_Retention_ retention)_snapshots_enabled_is_not_supported [Base de connaissances NetApp : La mise en cascade d'un volume avec des snapshots de conservation à long terme (LTR) activés n'est pas prise en charge^] pour obtenir de l'aide.

Les versions ONTAP suivantes ne vous permettent pas d'activer les instantanés de conservation à long terme sur un volume quelconque dans une cascade, à l'exception du volume de destination final SnapMirror .

* 9.15.1 et versions ultérieures
* 9.14.1P2 et P4 à P14
* 9.13.1P9 à P17
* 9.12.1 P12 à P19
* 9.11.1P15 à P20
* 9.10.1P18 à P20
* 9.9.1P20


Avant de passer d'une version ONTAP qui vous permet d'activer les instantanés de conservation à long terme sur les volumes intermédiaires d'une cascade à une version ONTAP qui les bloque, vous devez désactiver les instantanés de conservation à long terme pour éviter les sauvegardes et les instantanés manqués.

Vous devez prendre des mesures dans les scénarios suivants :

* Les snapshots de conservation à long terme sont configurés sur le volume « B » dans une cascade SnapMirror « A > B > C » ou sur un autre volume de destination SnapMirror intermédiaire dans votre cascade plus large.
* Les instantanés de conservation à long terme sont définis par une planification appliquée à une règle de stratégie SnapMirror . Cette règle ne réplique pas les instantanés du volume source, mais les crée directement sur le volume de destination.
+

NOTE: Pour plus d'informations sur les horaires et les politiques SnapMirror , consultez lelink:https://kb.netapp.com/on-prem/ontap/DP/SnapMirror/SnapMirror-KBs/How_does_the_schedule_parameter_in_an_ONTAP_9_SnapMirror_policy_rule_work["Base de connaissances NetApp : Comment fonctionne le paramètre « schedule » dans une règle de stratégie ONTAP 9 SnapMirror ?"^] .



.Étapes
. Supprimez la règle de conservation à long terme de la stratégie SnapMirror sur le volume intermédiaire de la cascade :
+
[listing]
----
Secondary::> snapmirror policy remove-rule -vserver <> -policy <> -snapmirror-label <>
----
+
En savoir plus sur  `snapmirror policy remove-rule` dans le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-remove-rule.html["Référence de commande ONTAP"^] .

. Ajoutez à nouveau la règle pour l'étiquette SnapMirror sans la période de conservation à long terme :
+
[listing]
----
Secondary::> snapmirror policy add-rule -vserver <> -policy <> -snapmirror-label <> -keep <>
----
+

NOTE: Supprimer les instantanés de conservation à long terme des règles de stratégie SnapMirror signifie que SnapMirror extraira les instantanés portant l'étiquette spécifiée du volume source. Vous devrez peut-être également ajouter ou modifier une planification dans la stratégie de snapshots du volume source afin de créer des snapshots correctement étiquetés.

+
Pour en savoir plus, `snapmirror policy add-rule` consultez le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-add-rule.html["Référence de commande ONTAP"^].

. Si nécessaire, modifier (ou créer) une planification sur la règle Snapshot du volume source pour permettre la création de snapshots avec une étiquette SnapMirror :
+
[listing]
----
Primary::> volume snapshot policy modify-schedule -vserver <> -policy <> -schedule <> -snapmirror-label <>
----
+
[listing]
----
Primary::> volume snapshot policy add-schedule -vserver <> -policy <> -schedule <> -snapmirror-label <> -count <>
----



NOTE: Les instantanés de conservation à long terme peuvent toujours être activés sur le volume de destination final SnapMirror dans une configuration en cascade SnapMirror .
