---
permalink: upgrade/task_plan_with_upgrade_advisor.html 
sidebar: sidebar 
keywords: ontap, upgrade, plan, planning, upgrade advisor, advisor, active iq 
summary: Le service Upgrade Advisor de Active IQ Digital Advisor vous aide à planifier votre mise à niveau et réduit les incertitudes et les risques. 
---
= Planifier votre mise à niveau avec Upgrade Advisor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le service Upgrade Advisor de link:https://aiq.netapp.com/["Conseiller digital Active IQ"] fournit des informations intelligentes qui vous aident à planifier votre mise à niveau et réduisent les incertitudes et les risques.

Active IQ identifie les problèmes qui peuvent être résolus dans votre environnement en passant à une version plus récente de ONTAP. Ce service vous aide à planifier une mise à niveau réussie et génère un rapport sur les problèmes vers la version ONTAP vers laquelle vous effectuez la mise à niveau.


NOTE: Un contrat SupportEdge actif est requis pour Active IQ.

. https://aiq.netapp.com/["Lancez Active IQ"]
. Vérifiez le récapitulatif de l'état de santé des systèmes Active IQ pour vous aider à évaluer l'état de santé de votre cluster.
. Vérifiez le chemin de mise à niveau recommandé et link:https://docs.netapp.com/us-en/active-iq/task_view_upgrade.html["générez votre plan de mise à niveau"^].


.Informations associées
https://www.netapp.com/us/services/support-edge.aspx["Services SupportEdge"]
