---
permalink: upgrade/task_verifying_that_the_netgroup_file_is_present_on_all_nodes.html 
sidebar: sidebar 
keywords: ontap, upgrade, verifying, verify, netgroup file, present, nodes 
summary: 'Si vous avez chargé des groupes réseau dans des machines virtuelles de stockage \(SVM\), avant de procéder à une mise à niveau ou à une restauration, vous devez vérifier que le fichier netgroup est présent sur chaque nœud. Un fichier de groupe réseau manquant sur un nœud peut entraîner l"échec d"une mise à niveau ou d"une restauration.' 
---
= Vérification de la présence du fichier netgroup sur tous les noeuds
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous avez chargé des groupes réseau sur des machines virtuelles de stockage (SVM), avant de procéder à une mise à niveau ou à une restauration, vous devez vérifier que le fichier netgroup est présent sur chaque nœud. Un fichier de groupe réseau manquant sur un nœud peut entraîner l'échec d'une mise à niveau ou d'une restauration.

link:../nfs-admin/index.html["Gestion NFS"] Contient plus d'informations sur les netgroups et leur chargement à partir d'un URI.

. Définissez le niveau de privilège sur avancé : `set -privilege advanced`
. Afficher le statut netgroup pour chaque SVM : `vserver services netgroup status`
. Vérifier que pour chaque SVM, chaque nœud affiche la même valeur de hachage de fichier netgroup : `vserver services name-service netgroup status`
+
Si c'est le cas, vous pouvez passer à l'étape suivante et poursuivre la mise à niveau ou la restauration. Sinon, passez à l'étape suivante.

. Sur un nœud du cluster, chargez manuellement le fichier netgroup : `vserver services netgroup load -vserver vserver_name -source uri`
+
Cette commande télécharge le fichier netgroup sur tous les nœuds. Si un fichier de groupe réseau existe déjà sur un noeud, il est écrasé.


