---
permalink: upgrade/task_resuming_snapmirror_operations.html 
sidebar: sidebar 
keywords: ontap, upgrade, resuming, resume, snapmirror 
summary: Après avoir effectué une mise à niveau sans interruption, vous devez reprendre toutes les relations SnapMirror suspendues. 
---
= Reprise des opérations SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir effectué une mise à niveau sans interruption, vous devez reprendre toutes les relations SnapMirror suspendues.

Les relations SnapMirror existantes doivent avoir été suspendues à l'aide de la commande snapmirror quiesce, et le cluster doit avoir été mis à niveau sans interruption.

. Reprendre les transferts pour chaque relation SnapMirror précédemment suspendues : `snapmirror resume *`
+
Cette commande relance les transferts pour toutes les relations SnapMirror suspendues.

. Vérifier que les opérations SnapMirror ont repris : `snapmirror show`
+
[listing]
----
cluster1::> snapmirror show

Source            Destination  Mirror  Relationship  Total             Last
Path        Type  Path         State   Status        Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
cluster1-vs1:dp_src1
            DP   cluster1-vs2:dp_dst1
                              Snapmirrored
                                      Idle           -         true    -
cluster1-vs1:xdp_src1
            XDP  cluster1-vs2:xdp_dst1
                              Snapmirrored
                                      Idle           -         true    -
cluster1://cluster1-vs1/ls_src1
            LS   cluster1://cluster1-vs1/ls_mr1
                              Snapmirrored
                                      Idle           -         true    -
                 cluster1://cluster1-vs1/ls_mr2
                              Snapmirrored
                                      Idle           -         true    -
4 entries were displayed.
----
+
Pour chaque relation SnapMirror, vérifiez que l'état de la relation est *Idle*. Si l'état est *Transferring*, attendez la fin du transfert SnapMirror, puis entrez à nouveau la commande pour vérifier que l'état est passé à *Idle*.



Pour chaque relation SnapMirror configurée pour s'exécuter selon une planification, il est important de vérifier que le premier transfert SnapMirror planifié se termine correctement.
