---
permalink: upgrade/task_requesting_notification_of_issues_encountered_in_nondisruptive_upgrades.html 
sidebar: sidebar 
keywords: ontap, upgrade, requesting, notification, issues, encountered, ndu, andu, nondisruptive, upgrades 
summary: 'Si vous n"envisagez pas de surveiller la progression du processus de mise à niveau, il est conseillé de demander des notifications EMS sur les erreurs pouvant nécessiter une intervention manuelle. Vous pouvez également configurer un message AutoSupport pour l"envoyer à votre service de support interne.' 
---
= Demande de notification des problèmes rencontrés lors des mises à niveau sans interruption
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous n'envisagez pas de surveiller la progression du processus de mise à niveau, il est conseillé de demander des notifications EMS sur les erreurs pouvant nécessiter une intervention manuelle. Vous pouvez également configurer un message AutoSupport pour l'envoyer à votre service de support interne.

Vous devez être un administrateur de cluster pour effectuer cette tâche.

Il est utile de configurer des notifications de sorte qu'elles soient envoyées en cas de problème lors du processus de mise à niveau. En particulier, le message callhome.andu.pauseederr contient des informations utiles pour le dépannage.

Si le paramètre AutoSupport noteto est configuré avec des adresses e-mail, elles sont automatiquement copiées dans les destinations de notification EMS lors de la mise à niveau vers ONTAP 9 ou 9.1. Une nouvelle notification EMS est également créée pour mapper le filtre événements importants à ces adresses. Par conséquent, vous recevrez deux notifications par e-mail pour chaque événement callhome jusqu'à ce que vous supprimiez les adresses e-mail du paramètre AutoSupport notto. Vous recevrez également des notifications par e-mail concernant d'autres événements importants configurés à l'origine.


NOTE: Si votre cluster n'est pas configuré pour envoyer des messages AutoSupport, une copie de la notification est enregistrée localement.

. Demande de notification de problèmes rencontrés lors de la mise à niveau sans interruption.
+
link:../error-messages/index.html["Configuration EMS"]

. Avant de lancer une mise à niveau sans interruption, si AutoSupport est activé sur ce cluster, supprimez la création automatique de dossiers en invoquant un message AutoSupport. Si AutoSupport n'est pas activé sur ce cluster, ignorez cette étape : `system node autosupport invoke -node * -type all -message MAINT=xh`
+
x représente la durée de la fenêtre de maintenance en heures.

+

NOTE: Le message informe le support technique de cette tâche de maintenance de sorte que la création automatique de dossier soit supprimée pendant la fenêtre de maintenance.

+
Cette commande supprime la création automatique de dossiers pendant deux heures :

+
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=2h
----
. Après la mise à niveau sans interruption, reactivez la création automatique de dossiers en invoquant un message AutoSupport : `system node autosupport invoke -node * -type all -message MAINT=END`
+
La commande reactive la création automatique de dossiers :

+
[listing]
----
cluster::*> system node autosupport invoke -node * -type all -message MAINT=END
----


http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Commandes de ONTAP 9"^]

link:../error-messages/index.html["Configuration EMS"]
