---
permalink: upgrade/task_verifying_the_san_configuration_after_an_upgrade.html 
sidebar: sidebar 
keywords: ontap, upgrade, post, after, san, verify 
summary: Après une mise à niveau de ONTAP, dans un environnement SAN, vérifier que chaque initiateur qui était connecté à une LIF avant que la mise à niveau ne se reconnecte à la LIF 
---
= Vérifiez la configuration SAN après une mise à niveau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après une mise à niveau de ONTAP, dans un environnement SAN, vérifier que chaque initiateur ayant été connecté à une LIF avant que la mise à niveau ne se reconnecte à la LIF.

. Vérifiez que chaque initiateur est connecté au LIF correct.
+
Vous devez comparer la liste des initiateurs à la liste que vous avez faite lors de la préparation de la mise à niveau. Si vous exécutez ONTAP 9.11.1 ou une version ultérieure, utilisez System Manager pour afficher l'état de la connexion, car l'affichage est plus clair que celui de l'interface de ligne de commande.

+
[role="tabbed-block"]
====
.System Manager
--
.. Dans System Manager, cliquez sur *hôtes > groupes initiateurs SAN*.
+
La page affiche la liste des groupes initiateurs. Si la liste est grande, vous pouvez afficher des pages supplémentaires de la liste en cliquant sur les numéros de page dans le coin inférieur droit de la page.

+
Les colonnes affichent diverses informations sur les igroups. Depuis 9.11.1, l'état de connexion du groupe initiateur est également affiché. Passez le curseur sur les alertes d'état pour afficher les détails.



--
.CLI
--
** Lister les initiateurs iSCSI :
+
[source, cli]
----
iscsi initiator show -fields igroup,initiator-name,tpgroup
----
** Lister les initiateurs FC :
+
[source, cli]
----
fcp initiator show -fields igroup,wwpn,lif
----


--
====

