---
permalink: upgrade/task_updating_an_ontap_cluster_disruptively.html 
sidebar: sidebar 
keywords: ontap, upgrade, disruptively 
summary: 'Si vous pouvez mettre votre cluster hors ligne pour effectuer la mise à niveau vers une nouvelle version de ONTAP, vous pouvez utiliser la méthode de mise à niveau perturbation. Cette méthode se procédure en plusieurs étapes : désactivation du basculement du stockage pour chaque paire haute disponibilité, redémarrage de chaque nœud du cluster, puis réactivation du basculement du stockage.' 
---
= Mise à niveau manuelle sans interruption via l'interface de ligne de commandes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous pouvez mettre votre cluster hors ligne pour effectuer la mise à niveau vers une nouvelle version de ONTAP, vous pouvez utiliser la méthode de mise à niveau perturbation. Cette méthode se procédure en plusieurs étapes : désactivation du basculement du stockage pour chaque paire haute disponibilité, redémarrage de chaque nœud du cluster, puis réactivation du basculement du stockage.

* Vous devez avoir satisfait aux exigences de préparation.
+
En particulier, vous devez télécharger et installer l'image logicielle en suivant la procédure link:task_download_and_install_ontap_software_image.html#for-manual-upgrades["pour les mises à niveau manuelles"].

* Si vous travaillez dans un environnement SAN, tous les clients SAN doivent être arrêtés ou suspendus jusqu'à la fin de la mise à niveau.
+
Si les clients SAN ne sont pas arrêtés ou suspendus avant une mise à niveau perturbatrice , les systèmes de fichiers clients et les applications reçoivent des erreurs qui peuvent nécessiter une récupération manuelle après la fin de la mise à niveau.



Lors d'une mise à niveau sans interruption, un basculement du stockage est désactivé pour chaque paire haute disponibilité et chaque nœud est mis à jour. Lorsque le basculement de stockage est désactivé, chaque nœud se comporte comme un cluster à un seul nœud ; c'est-à-dire que les services système associés au nœud sont interrompus tant que le système doit redémarrer.

. Définissez le niveau de privilège de admin sur avancé, en entrant *y* lorsque vous êtes invité à continuer : `set -privilege advanced`
+
L'invite avancée (`*>`) s'affiche.

. Définissez la nouvelle image du logiciel ONTAP comme image par défaut : `system image modify {-node * -iscurrent false} -isdefault true`
+
Cette commande utilise une requête étendue pour modifier l'image logicielle ONTAP cible (qui est installée comme image secondaire) en tant qu'image par défaut pour chaque nœud.

. Vérifiez que la nouvelle image du logiciel ONTAP est définie comme image par défaut : `system image show`
+
Dans l'exemple suivant, l'image 2 est la nouvelle version de ONTAP et est définie en tant qu'image par défaut sur les deux nœuds :

+
[listing]
----
cluster1::*> system image show
                 Is      Is                Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------- -------------------
node0
         image1  false   true    X.X.X     MM/DD/YYYY TIME
         image2  true    false   Y.Y.Y     MM/DD/YYYY TIME
node1
         image1  false   true    X.X.X     MM/DD/YYYY TIME
         image2  true    false   Y.Y.Y     MM/DD/YYYY TIME
4 entries were displayed.
----
. Effectuez l'une des opérations suivantes :
+
[cols="2*"]
|===
| Si le cluster est constitué de... | Procédez comme ça... 


 a| 
Un nœud
 a| 
Passez à l'étape suivante.



 a| 
Deux nœuds
 a| 
.. Désactiver la haute disponibilité du cluster : `cluster ha modify -configured false`
+
Entrez `y` pour continuer lorsque vous y êtes invité.

.. Désactivation du basculement du stockage pour la paire haute disponibilité : `storage failover modify -node * -enabled false`




 a| 
Plus de deux nœuds
 a| 
Désactiver le basculement du stockage pour chaque paire haute disponibilité du cluster : `storage failover modify -node * -enabled false`

|===
. Reboot d'un noeud sur le cluster: `system node reboot -node nodename -ignore-quorum-warnings`
+

IMPORTANT: Ne redémarrez pas plus d'un nœud à la fois.

+
Le nœud démarre la nouvelle image ONTAP. L'invite de connexion ONTAP apparaît, indiquant que le processus de redémarrage est terminé.

. Après le redémarrage du nœud ou de l'ensemble de nœuds avec la nouvelle image ONTAP, définissez le niveau de privilège sur Advanced : `set -privilege advanced`
+
Entrez *y* lorsque vous êtes invité à continuer

. Vérifiez que le nouveau logiciel est en cours d'exécution : `system node image show`
+
Dans l'exemple suivant, image1 est la nouvelle version de ONTAP et est définie comme la version actuelle sur le noeud 0 :

+
[listing]
----
cluster1::*> system node image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    X.X.X       MM/DD/YYYY TIME
         image2  false   false   Y.Y.Y      MM/DD/YYYY TIME
node1
         image1  true    false   X.X.X      MM/DD/YYYY TIME
         image2  false   true    Y.Y.Y      MM/DD/YYYY TIME
4 entries were displayed.
----
. Vérifiez que la mise à niveau est effectuée correctement :
+
.. Définissez le niveau de privilège sur avancé : `set -privilege advanced`
.. Vérifiez que la mise à niveau est terminée pour chaque nœud : `system node upgrade-revert show -node nodename`
+
L'état doit être indiqué comme étant terminé.

+
Si le statut n'est pas terminé, link:http://mysupport.netapp.com/["Contactez le support NetApp"] immédiatement.

.. Retour au niveau de privilège admin : `set -privilege admin`


. Répétez les étapes 2 à 7 pour chaque nœud supplémentaire.
. Si le cluster comprend deux nœuds ou plus, activez le basculement du stockage pour chaque paire haute disponibilité du cluster : `storage failover modify -node * -enabled true`
. Si le cluster ne comprend que deux nœuds, activez la haute disponibilité du cluster : `cluster ha modify -configured true`

