---
permalink: upgrade/task_reconfiguring_kmip_servers_connections_after_upgrading_to_ontap_9_3_or_later.html 
sidebar: sidebar 
keywords: ontap, upgrade, reconfigure, reconfiguring, kmip, server, connections, 9.3, later 
summary: 'Après une mise à niveau vers ONTAP 9.3 ou version ultérieure, vous devez reconfigurer vos connexions au serveur de gestion externe des clés (KMIP).' 
---
= Reconfigurez les connexions de serveur KMIP après une mise à niveau à partir de ONTAP 9.2 ou d'une version antérieure
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après la mise à niveau de ONTAP 9.2 ou d'une version antérieure vers ONTAP 9.3 ou version ultérieure, vous devez reconfigurer les connexions au serveur de gestion externe des clés (KMIP).

.Étapes
. Configurez la connectivité du gestionnaire de clés :
+
[source, cli]
----
security key-manager setup
----
. Ajoutez vos serveurs KMIP :
+
[source, cli]
----
security key-manager add -address <key_management_server_ip_address>
----
. Vérifiez que les serveurs KMIP sont connectés :
+
[source, cli]
----
security key-manager show -status
----
. Interroger les serveurs de clés :
+
[source, cli]
----
security key-manager query
----
. Créez une nouvelle clé d'authentification et une nouvelle phrase secrète :
+
[source, cli]
----
security key-manager create-key -prompt-for-key true
----
+
Définissez une phrase secrète avec au moins 32 caractères.

. Interroger la nouvelle clé d'authentification :
+
[source, cli]
----
security key-manager query
----
. Attribuez la nouvelle clé d'authentification à vos disques à autochiffrement (SED) :
+
[source, cli]
----
storage encryption disk modify -disk <disk_ID> -data-key-id <key_ID>
----
+

NOTE: Utilisez la nouvelle clé d’authentification de votre requête.

. Si nécessaire, attribuez une clé FIPS aux disques SED :
+
[source, cli]
----
storage encryption disk modify -disk <disk_id> -fips-key-id <fips_authentication_key_id>
----
+
Si votre configuration de sécurité nécessite l’utilisation de clés différentes pour l’authentification des données et l’authentification FIPS 140-2, vous devez créer une clé distincte pour chacune.  Sinon, utilisez la même clé d’authentification pour les deux.



.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli-9161/security-key-manager-setup.html["configuration du gestionnaire de clés de sécurité"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-modify.html["modification du disque de cryptage de stockage"^]

