---
permalink: upgrade/task_setting_the_desired_nt_acl_permissions_display_level_for_nfs_clients.html 
sidebar: sidebar 
keywords: ontap, upgrade, setting, set, desired, nt, acl, permissions, display, level, nfs, clients 
summary: 'Après la mise à niveau depuis ONTAP 8.3.0, la gestion par défaut de l"affichage des autorisations d"accès aux ACL NT sur les clients NFS a été modifiée. Vous devez vérifier le paramètre et le modifier si nécessaire pour votre environnement. Cette tâche ne s"applique pas si vous effectuez une mise à niveau depuis ONTAP 8.3.1 ou une version ultérieure.' 
---
= Définissez le niveau d'affichage des autorisations de la liste de contrôle d'accès NT souhaité pour les clients NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après la mise à niveau depuis ONTAP 8.3.0, la gestion par défaut de l'affichage des autorisations d'accès aux ACL NT sur les clients NFS a été modifiée. Vous devez vérifier le paramètre et le modifier si nécessaire pour votre environnement. Cette tâche ne s'applique pas si vous effectuez une mise à niveau depuis ONTAP 8.3.1 ou une version ultérieure.

Dans les environnements multiprotocoles, ONTAP affiche aux clients NFS les autorisations des fichiers et répertoires de style de sécurité NTFS en fonction de l'accès accordé par l'ACL NT à n'importe quel utilisateur. Dans ONTAP 8.3.0, ONTAP affiche par défaut aux clients NFS l’autorisation basée sur l’accès maximal autorisé par l’ACL NT. Après la mise à niveau, le paramètre par défaut change pour afficher les autorisations en fonction de l'accès minimal accordé par la liste de contrôle d'accès NT. Cette modification s'applique aux serveurs virtuels de stockage (SVM) nouveaux et existants.

. Définissez le niveau de privilège sur avancé : `set -privilege advanced`
. Vérifiez le paramètre d'affichage des autorisations ACL NT pour les clients NFS : `vserver nfs show -vserver vserver_name -fields ntacl-display-permissive-perms`
+
Après la mise à niveau de 8.3.0, la valeur de ce nouveau paramètre est désactivée, ce qui signifie que ONTAP affiche les autorisations minimales.

. Si vous préférez afficher les autorisations maximales, modifiez le paramètre individuellement pour chaque SVM comme vous le souhaitez : `vserver nfs modify -vserver vserver_name -ntacl-display-permissive-perms enabled`
. Vérifiez que la modification a pris effet : `vserver nfs show -vserver vserver_name -fields ntacl-display-permissive-perms`
. Retour au niveau de privilège admin : `set -privilege admin`

