---
permalink: upgrade/task_preparing_all_load_sharing_mirrors_for_a_major_upgrade.html 
sidebar: sidebar 
keywords: ontap, upgrade, prepare, preparing, load-sharing, load, sharing, mirrors 
summary: 'Avant d"effectuer une mise à niveau majeure à partir de ONTAP 8.3, il est conseillé de déplacer tous les volumes source du miroir de partage de charge vers un agrégat du nœud que vous allez mettre à niveau en dernier. Cela permet de s"assurer que les volumes de destination des miroirs de partage de charge appartiennent à la même version ou à une version ultérieure de ONTAP.' 
---
= Préparer tous les miroirs de partage de charge avant la mise à niveau depuis ONTAP 8.3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de procéder à une mise à niveau à partir de ONTAP 8.3, vous devez déplacer tous les volumes source du miroir de partage de charge vers un agrégat sur le nœud que vous allez mettre à niveau en dernier. Cela permet de s'assurer que les volumes de destination des miroirs de partage de charge appartiennent à la même version ou à une version ultérieure de ONTAP.


NOTE: Cette procédure ne doit être effectuée que lors de la mise à niveau à partir de ONTAP 8.3.

.Étapes
. Enregistrez l'emplacement de tous les volumes source des miroirs de partage de charge.
+
Savoir où sont issus les volumes source des miroirs de partage de charge facilite leur retour à leur emplacement d'origine après la mise à niveau majeure.

. Déterminez le nœud et l'agrégat vers lesquels vous déplaerez les volumes source du miroir de partage de charge.
. Déplacez les volumes source miroir de partage de charge vers le nœud et l'agrégat à l'aide de la commande volume Move start.

