---
permalink: performance-admin/active-iq-digital-advisor-view-performance-concept.html 
sidebar: sidebar 
keywords: use, active iq digital advisor, view, system, performance 
summary: Tous les systèmes ONTAP qui envoient la télémétrie AutoSupport à NetApp peuvent afficher des données étendues sur les performances et la capacité.Active IQ affiche les performances du système sur une période plus longue que ce que vous pouvez voir dans System Manager. 
---
= Utilisez le conseiller numérique Active IQ pour consulter les performances du système
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour tous les systèmes ONTAP qui envoient la télémétrie AutoSupport à NetApp, vous pouvez afficher des données étendues de performances et de capacité. Active IQ affiche les performances du système sur une période plus longue que ce que vous pouvez voir dans System Manager.

Vous pouvez afficher les graphiques de l'utilisation du CPU, de la latence, des opérations d'entrée/sortie par seconde, des opérations d'entrée/sortie par protocole et du débit du réseau. Vous pouvez également télécharger ces données au format .csv pour les analyser avec d'autres outils.

Outre ces données de performances, Active IQ affiche l'efficacité du stockage par charge de travail et compare cette efficacité à celle attendue pour ce type de charge de travail. Vous pouvez consulter les tendances en matière de capacité et obtenir une estimation de la quantité de stockage supplémentaire à ajouter dans une période donnée.

[NOTE]
====
* L'efficacité du stockage est disponible au niveau du client, du cluster et des nœuds, à gauche du tableau de bord principal.
* La performance est disponible au niveau du cluster et du nœud sur la gauche du tableau de bord principal.


====
.Informations associées
* https://["Documentation du conseiller digital Active IQ"]
* https://["Liste de lecture vidéo conseiller numérique Active IQ"]
* https://["Portail Web Active IQ"]

