---
permalink: performance-admin/enable-disable-throughput-floors-v2-task.html 
sidebar: sidebar 
keywords: enable, disable, throughput, floors v2 
summary: 'Vous pouvez activer ou désactiver le débit planchers v2 sur AFF. La valeur par défaut est activée. Lorsque la technologie planchers v2 est activée, le débit au sol peut être atteint lorsque les contrôleurs sont utilisés de façon intensive, au détriment d"une latence plus élevée sur d"autres charges de travail. Au niveau de la QoS et de la QoS adaptative.' 
---
= Activer ou désactiver le débit planchers v2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez activer ou désactiver le débit planchers v2 sur AFF. La valeur par défaut est activée. Lorsque la technologie planchers v2 est activée, le débit au sol peut être atteint lorsque les contrôleurs sont utilisés de façon intensive, au détriment d'une latence plus élevée sur d'autres charges de travail. Au niveau de la QoS et de la QoS adaptative.

.Étapes
. Changement au niveau de privilège avancé :
+
`set -privilege advanced`

. Entrez l'une des commandes suivantes :
+
|===
| Les fonctions que vous recherchez... | Utilisez cette commande : 


 a| 
Désactiver les étages v2
 a| 
`qos settings throughput-floors-v2 -enable false`



 a| 
Activation de la version 2
 a| 
`qos settings throughput-floors-v2 -enable true`

|===
+
[NOTE]
====
Pour désactiver le débit planchers v2 dans un cluster MetroCluster, vous devez exécuter le

`qos settings throughput-floors-v2 -enable false`

contrôlez à la fois les clusters source et de destination.

====
+
[listing]
----
cluster1::*> qos settings throughput-floors-v2 -enable false
----

