---
permalink: performance-admin/identify-remaining-performance-capacity-task.html 
sidebar: sidebar 
keywords: identify, remaining, performance, capacity 
summary: La capacité de performance ou la marge mesure le volume de travail que vous pouvez placer sur un nœud ou un agrégat avant que les performances des charges de travail sur la ressource ne commencent à être affectées par la latence. Connaître la capacité en termes de performances disponible sur le cluster vous aide à provisionner et à équilibrer les charges de travail. 
---
= Identifiez la capacité de performance restante dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La capacité de performance, ou _headroom_, mesure le volume de travail que vous pouvez placer sur un nœud ou un agrégat avant que les performances des charges de travail sur la ressource ne commencent à être affectées par la latence. Connaître la capacité en termes de performances disponible sur le cluster vous aide à provisionner et à équilibrer les charges de travail.

.Avant de commencer
Des commandes de niveau de privilège avancé sont requises pour cette tâche.

.Description de la tâche
Vous pouvez utiliser les valeurs suivantes pour l' `-object` option pour collecter et afficher les statistiques de marge :

* Pour les CPU, `resource_headroom_cpu`.
* Pour les agrégats, `resource_headroom_aggr`.


Vous pouvez également effectuer cette tâche à l'aide de System Manager et de Active IQ Unified Manager.

.Étapes
. Changement au niveau de privilège avancé :
+
`set -privilege advanced`

. Démarrer la collecte de statistiques de marge en temps réel :
+
`statistics start –object resource_headroom_cpu|aggr`

+
Pour en savoir plus, `statistics start` consultez le link:https://docs.netapp.com/us-en/ontap-cli/statistics-start.html["Référence de commande ONTAP"^].

. Afficher les informations statistiques relatives à la marge en temps réel :
+
`statistics show -object resource_headroom_cpu|aggr`

. Revenir au privilège administratif :
+
`set -privilege admin`



.Exemple
L'exemple suivant affiche les statistiques moyennes sur la marge horaire des nœuds du cluster.

Vous pouvez calculer la capacité de performances disponible d'un nœud en soustrayant la `current_utilization` compteur du `optimal_point_utilization` compteur. Dans cet exemple, la capacité d'utilisation pour `CPU_sti2520-213` Est de -14% (72%-86%), ce qui suggère que le CPU a été surexploité en moyenne au cours de la dernière heure.

Vous avez peut-être spécifié `ewma_daily`, `ewma_weekly`, ou `ewma_monthly` pour obtenir la moyenne des mêmes informations sur des périodes plus longues.

[listing]
----
sti2520-2131454963690::*> statistics show -object resource_headroom_cpu -raw -counter ewma_hourly
  (statistics show)

Object: resource_headroom_cpu
Instance: CPU_sti2520-213
Start-time: 2/9/2016 16:06:27
End-time: 2/9/2016 16:06:27
Scope: sti2520-213

    Counter                                                     Value
    -------------------------------- --------------------------------
    ewma_hourly                                                     -
                         current_ops                             4376
                     current_latency                            37719
                 current_utilization                               86
                   optimal_point_ops                             2573
               optimal_point_latency                             3589
           optimal_point_utilization                               72
     optimal_point_confidence_factor                                1

Object: resource_headroom_cpu
Instance: CPU_sti2520-214
Start-time: 2/9/2016 16:06:27
End-time: 2/9/2016 16:06:27
Scope: sti2520-214

    Counter                                                     Value
    -------------------------------- --------------------------------
    ewma_hourly                                                     -
                         current_ops                                0
                     current_latency                                0
                 current_utilization                                0
                   optimal_point_ops                                0
               optimal_point_latency                                0
           optimal_point_utilization                               71
     optimal_point_confidence_factor                                1
2 entries were displayed.
----
Pour en savoir plus, `statistics show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/statistics-show.html["Référence de commande ONTAP"^].
