---
permalink: performance-admin/index.html 
sidebar: sidebar 
keywords: decide, performance, management 
summary: Vous pouvez définir des tâches de base de gestion des performances, et identifier et résoudre des problèmes courants de performances. 
---
= Présentation de la gestion des performances
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez définir des tâches de base de gestion des performances pour identifier et résoudre des problèmes courants de performance.

Vous pouvez utiliser ces procédures pour surveiller les performances du cluster si les hypothèses suivantes s'appliquent à votre situation :

* Vous voulez appliquer les bonnes pratiques, pas explorer toutes les options disponibles.
* Vous ne voulez pas lire beaucoup de contexte conceptuel.
* Vous pouvez afficher l'état du système et les alertes, surveiller les performances du cluster et effectuer une analyse de la source des problèmes à l'aide de Active IQ Unified Manager (anciennement OnCommand Unified Manager) en plus de l'interface de ligne de commandes de ONTAP.
* Vous utilisez l'interface de ligne de commandes ONTAP pour configurer la qualité de service (QoS) du stockage.
+
La QoS est également disponible dans System Manager, NSLM, WFA, VSC (plug-in VMware) et les API.

* Vous souhaitez installer Unified Manager à l'aide d'une appliance virtuelle au lieu d'une installation Linux ou Windows.
* Vous êtes prêt à utiliser une configuration statique plutôt que DHCP pour installer le logiciel.
* Vous pouvez accéder aux commandes ONTAP au niveau de privilège avancé.
* Vous êtes un administrateur de cluster ayant le rôle « admin ».


Si ces hypothèses ne sont pas correctes pour votre situation, vous devez consulter les ressources suivantes :

* http://docs.netapp.com/ocum-98/topic/com.netapp.doc.onc-um-isg/home.html["Installation de Active IQ Unified Manager 9.8"]
* link:../system-admin/index.html["Administration du système"]
* link:../performance-config/index.html["Configuration du contrôle des performances"]

