---
permalink: performance-admin/set-throughput-ceiling-qos-task.html 
sidebar: sidebar 
keywords: setting, throughput, ceiling, qos 
summary: 'Un plafond de QoS ou de débit garantit que le débit d"une charge de travail ne dépasse pas un nombre maximal d"IOPS ou de Mo/s, ou d"IOPS et de Mo/s, quelles que soient les charges de travail concurrentes. Définissez un plafond de débit pour éviter que les charges de travail moins critiques ne consomment des ressources de performance excessives et ne dégradent les performances des charges de travail plus critiques.' 
---
= Définissez un plafond de débit avec les groupes de stratégies QoS ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un plafond ou une limite de qualité de service (QoS) garantit que le débit d'une charge de travail ne dépasse pas un nombre maximal d'IOPS ou de Mo/s, ou un nombre maximal d'IOPS et de Mo/s indépendamment des charges de travail concurrentes. Définissez un plafond de débit pour éviter que les charges de travail moins critiques ne consomment des ressources de performance excessives et ne dégradent les performances des charges de travail plus critiques.

Vous pouvez spécifier le plafond de débit lors de la création d'un groupe de stratégies QoS ou attendre de surveiller vos charges de travail pour le spécifier.

link:guarantee-throughput-qos-task.html["Apprenez-en davantage sur les plafonds de débit"].

.Avant de commencer
* Vous devez être administrateur du cluster pour créer un groupe de stratégies et l'appliquer à une SVM.


.Description de la tâche
* Les groupes de stratégies QoS adaptatifs et non adaptatifs sont activés automatiquement pour augmenter temporairement le plafond de débit d’une charge de travail de 50 % pendant une seconde afin de répondre par défaut aux demandes ponctuelles de performances accrues. À partir d’ONTAP 9.19.1, vous pouvez modifier ces paramètres par défaut. Dans ONTAP 9.18.1 et les versions antérieures, ces paramètres ne peuvent pas être modifiés.
+
Utilisez les options suivantes pour modifier les paramètres par défaut :

+
[cols="3"]
|===
| Option | Description | Paramètre par défaut 


 a| 
`burst-percent`
| Augmentation du débit en pourcentage | 50% 


 a| 
`burst duration`
| Durée de l'augmentation du débit en secondes | 1 seconde 


 a| 
`burst-iops`
| Nombre maximal d'IOPS au-dessus du plafond de débit pour la durée de rafale spécifiée | 0 
|===
* Vous pouvez utiliser un groupe de stratégies QoS _non partagé_ pour spécifier que le plafond de débit défini s'applique individuellement à chaque charge de travail membre. Sinon, le groupe de stratégies est _partagé_ : le débit total des charges de travail qui lui sont affectées ne peut pas dépasser le plafond spécifié.
+
Réglez `-is-shared=false` pour le `qos policy-group create` commande permettant de spécifier une « policy group » non partagée.

* Vous pouvez spécifier la limite de débit pour le plafond en IOPS, Mo/s ou IOPS, Mo/s. Si vous spécifiez les IOPS et Mo/s, la première limite atteinte est appliquée.
+
[NOTE]
====
Si vous définissez une limite et un sol pour la même charge de travail, vous pouvez spécifier la limite de débit pour le plafond des IOPS uniquement.

====
* Un objet de stockage faisant l'objet d'une limite QoS doit être contenu par le SVM auquel appartient le groupe de règles. Plusieurs « policy group » peuvent appartenir à la même SVM.
* Vous ne pouvez pas affecter un objet de stockage à un groupe de règles si son objet contenant ou ses objets enfants appartiennent à ce groupe.
* Il s'agit d'une meilleure pratique de QoS pour appliquer un groupe de règles au même type d'objets de stockage.


.Étapes
. Création d'une « policy group » :
+
[source, cli]
----
qos policy-group create -policy-group <policy_group> -vserver <SVM> -max-throughput <number_of_iops_|Mb/S|iops,Mb/S> -is-shared <true|false>
----
+
Pour en savoir plus, `qos policy-group create` consultez le link:https://docs.netapp.com/us-en/ontap-cli/qos-policy-group-create.html["Référence de commande ONTAP"^].

+
Vous pouvez utiliser `qos policy-group modify` la commande pour ajuster les plafonds de débit.

+
L'exemple suivant crée le groupe de stratégies partagées `pg-vs1` avec un débit maximal de 5 000 IOPS :

+
[listing]
----
cluster1::> qos policy-group create -policy-group pg-vs1 -vserver vs1 -max-throughput 5000iops -is-shared true
----
+
L'exemple suivant crée le groupe de stratégies non partagé `pg-vs3` avec un débit maximal de 100 IOPS et 400 Kb/s :

+
[listing]
----
cluster1::> qos policy-group create -policy-group pg-vs3 -vserver vs3 -max-throughput 100iops,400KB/s -is-shared false
----
+
L'exemple suivant crée le groupe de stratégies non partagé `pg-vs4` sans limite de débit :

+
[listing]
----
cluster1::> qos policy-group create -policy-group pg-vs4 -vserver vs4 -is-shared false
----
+
Pour en savoir plus, `qos policy-group modify` consultez le link:https://docs.netapp.com/us-en/ontap-cli/qos-policy-group-modify.html["Référence de commande ONTAP"^].

. Appliquer une « policy group » à un SVM, fichier, volume ou LUN :
+
[source, cli]
----
vserver create -vserver <SVM> -qos-policy-group <policy_group>
----
+
L'exemple suivant applique le groupe de stratégies `pg-vs1` à la SVM `vs1` :

+
[listing]
----
cluster1::> vserver create -vserver vs1 -qos-policy-group pg-vs1
----
+
Les exemples suivants appliquent le groupe de politiques `pg-app` aux volumes `app1` et `app2` :

+
[listing]
----
cluster1::> volume create -vserver vs2 -volume app1 -aggregate aggr1 -qos-policy-group pg-app
----
+
[listing]
----
cluster1::> volume create -vserver vs2 -volume app2 -aggregate aggr1 -qos-policy-group pg-app
----
. Surveillance des performances des groupes de règles :
+
[source, cli]
----
qos statistics performance show
----
+
Pour en savoir plus, `qos statistics performance show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/qos-statistics-performance-show.html["Référence de commande ONTAP"^].

+
[NOTE]
====
Contrôle des performances depuis le cluster. N'utilisez pas d'outil sur l'hôte pour surveiller les performances.

====
+
L'exemple suivant montre les performances d'un groupe de politiques :

+
[listing]
----
cluster1::> qos statistics performance show
Policy Group           IOPS      Throughput   Latency
-------------------- -------- --------------- ----------
-total-                 12316       47.76MB/s  1264.00us
pg_vs1                   5008       19.56MB/s     2.45ms
_System-Best-Effort        62       13.36KB/s     4.13ms
_System-Background         30           0KB/s        0ms
----
. Contrôle de la performance des charges de travail :
+
[source, cli]
----
qos statistics workload performance show
----
+
[NOTE]
====
Contrôle des performances depuis le cluster. N'utilisez pas d'outil sur l'hôte pour surveiller les performances.

====
+
L'exemple suivant montre les performances de la charge de travail :

+
[listing]
----
cluster1::> qos statistics workload performance show
Workload          ID     IOPS      Throughput    Latency
--------------- ------ -------- ---------------- ----------
-total-              -    12320        47.84MB/s  1215.00us
app1-wid7967      7967     7219        28.20MB/s   319.00us
vs1-wid12279     12279     5026        19.63MB/s     2.52ms
_USERSPACE_APPS     14       55        10.92KB/s   236.00us
_Scan_Backgro..   5688       20            0KB/s        0ms
----
+
Voici un exemple de sortie pour une charge de travail avec max-throughput défini à 2000 IOPS et burst-percent défini à 25 pour une durée de rafale de 5 secondes.

+
[listing]
----
cluster1::> qos statistics workload performance show -workload test_vol_nfs_pct25-wid54260

Workload	                ID	    IOPS
--------------------------- -----   ----
test_vol_nfs_pct25-wid54260	54260	2564
-total-	-	                        3704
test_vol_nfs_pct25-wid54260	54260	2527
-total-	-	                        3105
test_vol_nfs_pct25-wid54260	54260	2550
-total-	-	                        3445
test_vol_nfs_pct25-wid54260	54260	2476
-total-	-	                        3460
test_vol_nfs_pct25-wid54260	54260	2479
-total-	-	                        3511
test_vol_nfs_pct25-wid54260	54260	1996
-total-	-	                        2197
test_vol_nfs_pct25-wid54260	54260	2068
-total-	-	                        2057
test_vol_nfs_pct25-wid54260	54260	2087
-total-	-	                        3119

----
+
Pour en savoir plus, `qos statistics workload performance show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/qos-statistics-workload-performance-show.html["Référence de commande ONTAP"^].

+
Vous pouvez utiliser la commande  `qos statistics workload latency show` pour afficher des statistiques de latence détaillées pour les charges de travail QoS.

+
En savoir plus sur  `qos statistics workload latency show` dans la link:https://docs.netapp.com/us-en/ontap-cli/qos-statistics-workload-latency-show.html["Référence de commande ONTAP"^].


