---
permalink: performance-admin/weekly-monthly-performance-trends-identify-issues-task.html 
sidebar: sidebar 
keywords: Use, weekly, monthly, performance, trends, identify, issues 
summary: 'L"identification des tendances de performances permet de déterminer si le cluster est sur-utilisé ou sous-utilisé en analysant la latence du volume. Vous pouvez utiliser des étapes similaires pour identifier les goulets d"étranglement du processeur, du réseau ou d"autres systèmes.' 
---
= Utilisez les tendances de performances hebdomadaires et mensuelles ONTAP Active IQ Unified Manager pour identifier les problèmes de performances
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'identification des tendances de performances permet de déterminer si le cluster est sur-utilisé ou sous-utilisé en analysant la latence du volume. Vous pouvez utiliser des étapes similaires pour identifier les goulets d'étranglement du processeur, du réseau ou d'autres systèmes.

.Étapes
. Identifiez le volume que vous pensez être sous-utilisé ou sur-utilisé.
. Dans l'onglet *Détails du volume*, cliquez sur *30 d* pour afficher les données historiques.
. Dans le menu déroulant « données de pause par », sélectionnez *latence*, puis cliquez sur *Envoyer*.
. Désélectionnez *agrégat* dans le tableau comparatif des composants du cluster, puis comparez la latence du cluster avec celle du tableau de latence du volume.
. Sélectionnez *agrégat* et désélectionnez tous les autres composants dans le tableau comparatif des composants du cluster, puis comparez la latence globale avec celle du graphique de latence du volume.
. Comparez le graphique de latence de lecture/écriture sur le tableau de latence du volume.
. Identifiez si les charges d'application client ont provoqué des conflits au niveau de la charge de travail et rééquilibrez les charges de travail en fonction des besoins.
. Déterminez si l'agrégat est sur-utilisé et source de conflits, et rééquilibrez les charges de travail si nécessaire.

