---
permalink: performance-admin/worksheet-reference.html 
sidebar: sidebar 
keywords: active iq unified manager, worksheet 
summary: 'Avant d"installer, de configurer et de connecter Active IQ Unified Manager, vous devez disposer facilement d"informations spécifiques sur votre environnement. Vous pouvez enregistrer les informations dans la fiche.' 
---
= Fiche technique Active IQ Unified Manager
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'installer, de configurer et de connecter Active IQ Unified Manager, vous devez disposer facilement d'informations spécifiques sur votre environnement. Vous pouvez enregistrer les informations dans la fiche.



== Informations sur l'installation de Unified Manager

|===


| Machine virtuelle sur laquelle le logiciel est déployé | Votre valeur 


 a| 
Adresse IP du serveur ESXi
 a| 



 a| 
Nom de domaine complet de l'hôte
 a| 



 a| 
Adresse IP de l'hôte
 a| 



 a| 
Masque de réseau
 a| 



 a| 
Adresse IP de la passerelle
 a| 



 a| 
Adresse DNS principale
 a| 



 a| 
Adresse DNS secondaire
 a| 



 a| 
Domaines de recherche
 a| 



 a| 
Nom d'utilisateur de maintenance
 a| 



 a| 
Mot de passe utilisateur de maintenance
 a| 

|===


== Informations sur la configuration de Unified Manager

|===


| Réglage | Votre valeur 


 a| 
Adresse e-mail de l'utilisateur de maintenance
 a| 



 a| 
Serveur NTP
 a| 



 a| 
Nom d'hôte ou adresse IP du serveur SMTP
 a| 



 a| 
Nom d'utilisateur SMTP
 a| 



 a| 
Mot de passe SMTP
 a| 



 a| 
Port SMTP par défaut
 a| 
25 (valeur par défaut)



 a| 
E-mail à partir duquel les notifications d'alerte sont envoyées
 a| 



 a| 
Nom distinctif de la liaison LDAP
 a| 



 a| 
Mot de passe de liaison LDAP
 a| 



 a| 
Nom d'administrateur Active Directory
 a| 



 a| 
Mot de passe Active Directory
 a| 



 a| 
Nom distinctif de la base du serveur d'authentification
 a| 



 a| 
Nom d'hôte ou adresse IP du serveur d'authentification
 a| 

|===


== Informations sur le cluster

Capturer les informations suivantes pour chaque cluster sur Unified Manager.

|===


| Cluster 1 de N | Votre valeur 


 a| 
Nom d'hôte ou adresse IP de gestion du cluster
 a| 



 a| 
Nom d'utilisateur de l'administrateur ONTAP

[NOTE]
====
L'administrateur doit avoir reçu le rôle « admin ».

==== a| 



 a| 
Mot de passe administrateur ONTAP
 a| 



 a| 
Protocole (HTTP ou HTTPS)
 a| 

|===
link:../authentication/index.html["Authentification de l'administrateur et RBAC"]
