---
permalink: performance-config/verify-environment-supported-task.html 
sidebar: sidebar 
keywords: verify, vnware, environment, supported 
summary: Pour une installation réussie de Active IQ Unified Manager, vous devez vérifier que votre environnement VMware répond aux exigences requises. 
---
= Vérifiez que votre environnement VMware est pris en charge
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour une installation réussie de Active IQ Unified Manager, vous devez vérifier que votre environnement VMware répond aux exigences requises.

.Étapes
. Vérifiez que votre infrastructure VMware répond aux exigences de dimensionnement pour l'installation de Unified Manager.
. Accédez à la matrice d'interopérabilité pour vérifier que vous disposez d'une combinaison de composants prise en charge :
+
** Version ONTAP
** Version du système d'exploitation ESXi
** Version de VMware vCenter Server
** Version des outils VMware
** Type et version du navigateur


+
[NOTE]
====
Le http://mysupport.netapp.com/matrix["Matrice d'interopérabilité"] Le répertorie les configurations prises en charge pour Unified Manager.

====
. Cliquez sur le nom de la configuration sélectionnée.
+
Les détails de cette configuration s'affichent dans la fenêtre Détails de la configuration.

. Vérifiez les informations dans les onglets suivants :
+
** Remarques
+
Le répertorie les alertes et informations importantes spécifiques à votre configuration.

** Politiques et lignes directrices
+
Présente des recommandations d'ordre général pour toutes les configurations.




