---
permalink: peering/additional-information-reference.html 
sidebar: sidebar 
keywords: SnapMirror, ONTAP CLI, System Manager, diaster prep, recover 
summary: Vous pouvez en savoir plus sur les tâches liées à un cluster et à SVM peering dans la vaste bibliothèque de documentation de NetApp. 
---
= Où trouver des informations complémentaires
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez en savoir plus sur les tâches liées à un cluster et à SVM peering dans la vaste bibliothèque de documentation de NetApp.

* link:../concepts/index.html["Concepts relatifs à ONTAP"]
+
Décrit les concepts qui contribuent à l'utilisation du logiciel de gestion des données ONTAP, notamment la protection et le transfert des données.

* link:../data-protection/index.html["Protection des données"]
+
Décrit l'utilisation de l'interface de ligne de commandes ONTAP pour effectuer la réplication SnapMirror.

* https://docs.netapp.com/us-en/ontap-sm-classic/volume-disaster-prep/index.html["Préparation de la reprise après incident de volume"]
+
Décrit comment utiliser System Manager pour configurer rapidement un volume de destination pour la reprise après incident.

* https://docs.netapp.com/us-en/ontap-sm-classic/volume-disaster-prep/index.html["Préparation de la reprise après incident de volume"]
+
Décrit l'utilisation de System Manager pour restaurer rapidement un volume de destination après un incident.

* https://docs.netapp.com/us-en/ontap-sm-classic/volume-backup-snapvault/index.html["Sauvegarde de volume avec SnapVault"]
+
Décrit l'utilisation de System Manager pour configurer rapidement une relation SnapVault entre les volumes.

* https://docs.netapp.com/us-en/ontap-sm-classic/volume-restore-snapvault/index.html["Gestion des restaurations de volumes avec SnapVault"]
+
Décrit comment utiliser System Manager pour restaurer rapidement des fichiers à partir d'un volume de destination dans une relation SnapVault.

* link:../snaplock/index.html["Archivage et conformité grâce à la technologie SnapLock"]
+
Décrit la réplication de fichiers WORM dans un volume SnapLock.


