---
permalink: peering/index.html 
sidebar: sidebar 
keywords: decide, cluster, svm, peering, peer, relationships, source, destination, svm, storage, virtual, machines 
summary: Il est possible de créer des relations entre les clusters source et de destination et entre les machines virtuelles de stockage source et de destination. 
---
= En savoir plus sur le cluster ONTAP et le peering de SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il est possible de créer des relations entre les clusters source et de destination et entre les machines virtuelles de stockage source et de destination. Vous devez créer des relations de pairs entre ces entités avant de pouvoir répliquer des snapshots à l'aide de SnapMirror.

ONTAP 9.3 apporte des améliorations qui simplifient la configuration des relations entre les clusters et les SVM. Les procédures de peering de clusters et de SVM sont disponibles pour toutes les versions de ONTAP 9. Utilisez la procédure appropriée pour votre version de ONTAP.

Vous effectuez les procédures à l'aide de l'interface de ligne de commandes, et non de System Manager ou d'un outil de script automatisé.
