---
permalink: peering/peering-basics-concept.html 
sidebar: sidebar 
keywords: peer, basics 
summary: 'Les clusters et les SVM dans des relations entre pairs communiquent sur le réseau intercluster à l"aide des interfaces logiques intercluster. Une LIF intercluster est une LIF qui prend en charge le service d"interface réseau « intercluster-core » et est généralement créée à l"aide de la politique de service d"interface réseau « par défaut-intercluster ». On doit créer des LIF intercluster sur chaque nœud des clusters en cours de peering.' 
---
= Principes de base du peering ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez créer des _relations peer_ entre les clusters source et de destination et entre les SVM source et de destination avant de pouvoir répliquer des snapshots à l'aide de SnapMirror. Une relation de type peer-to-peer définit les connexions réseau qui permettent aux clusters et aux SVM d'échanger les données de manière sécurisée.

Les clusters et les SVM dans des relations entre pairs communiquent sur le réseau intercluster à l'aide de _interfaces logiques (LIF) intercluster._ une LIF intercluster est une LIF qui prend en charge le service d'interface réseau « intercluster-core » et qui est généralement créée en utilisant la politique de service d'interface réseau « default-intercluster ». On doit créer des LIF intercluster sur chaque nœud des clusters en cours de peering.

Les LIFs intercluster utilisent des routes qui appartiennent au SVM système auquel elles sont assignées. ONTAP crée automatiquement un SVM système pour les communications au niveau du cluster au sein d'un IPspace.

Les topologies en mode « Fan-Out » et en cascade sont toutes deux prises en charge. Dans une topologie en cascade, il suffit de créer des réseaux intercluster entre les clusters principal et secondaire, et entre les clusters secondaire et tertiaire. Il n'est pas nécessaire de créer un réseau intercluster entre le cluster principal et le cluster tertiaire.

[NOTE]
====
Il est possible (mais pas conseillé) à un administrateur de supprimer le service intercluster de la politique de service default-intercluster. Dans ce cas, les LIFs créées à l'aide de « Default-intercluster » ne seront en fait pas des LIFs intercluster. Pour vérifier que la politique de service par défaut-intercluster contient le service intercluster-core, utiliser la commande suivante :

`network interface service-policy show -policy default-intercluster`

Pour en savoir plus, `network interface service-policy show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/network-interface-service-policy-show.html["Référence de commande ONTAP"^].

====