---
permalink: peering/remove-snapmirror-encryption-existing-relationship-task.html 
sidebar: sidebar 
keywords: remove, cluster, peering, encryption, existing, peer, relationship 
summary: Par défaut, le cryptage de peering de cluster est activé sur toutes les relations entre pairs créées dans ONTAP 9.6 ou version ultérieure. Si vous ne souhaitez pas utiliser le cryptage pour les communications de peering intercluster, vous pouvez le désactiver. 
---
= Supprimez le chiffrement de peering de cluster ONTAP des relations entre pairs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Par défaut, le cryptage de peering de cluster est activé sur toutes les relations entre pairs créées dans ONTAP 9.6 ou version ultérieure. Si vous ne souhaitez pas utiliser le cryptage pour les communications de peering intercluster, vous pouvez le désactiver.

.Étapes
. Sur le cluster de destination, modifiez les communications avec le cluster source pour interrompre l'utilisation du chiffrement de peering de cluster :
+
** Pour supprimer le cryptage mais maintenir l'authentification, entrez :
+
[source, cli]
----
cluster peer modify <source_cluster> -auth-status-admin use-authentication -encryption-protocol-proposed none
----
** Pour supprimer le cryptage et l'authentification :
+
... Modifiez la stratégie de peering de cluster pour autoriser l'accès non authentifié :
+
[source, cli]
----
cluster peer policy modify -is-unauthenticated-access-permitted true
----
... Modifier le cryptage et l'accès d'authentification :
+
[source, cli]
----
cluster peer modify <source_cluster> -auth-status no-authentication
----




. Lorsque vous y êtes invité, saisissez la phrase de passe.
. Confirmez la phrase de passe en la saisissant à nouveau.
. Sur le cluster source, désactiver le cryptage pour la communication avec le cluster destination :
+
** Pour supprimer le cryptage mais maintenir l'authentification, entrez :
+
[source, cli]
----
cluster peer modify <destination_cluster> -auth-status-admin use-authentication -encryption-protocol-proposed none
----
** Pour supprimer le cryptage et l'authentification :
+
... Modifiez la stratégie de peering de cluster pour autoriser l'accès non authentifié :
+
[source, cli]
----
cluster peer policy modify -is-unauthenticated-access-permitted true
----
... Modifier le cryptage et l'accès d'authentification :
+
[source, cli]
----
cluster peer modify <destination_cluster> -auth-status no-authentication
----




. Lorsque vous y êtes invité, entrez et saisissez à nouveau la phrase de passe que vous avez utilisée sur le cluster de destination.

