---
permalink: san-admin/additional-information-reference.html 
sidebar: sidebar 
keywords: where, find, additional, information 
summary: Pour en savoir plus sur les tâches et les concepts décrits dans ce guide, consultez la vaste bibliothèque de documentation de NetApp. 
---
= Où trouver des informations complémentaires
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour en savoir plus sur les tâches et les concepts décrits dans ce guide, consultez la vaste bibliothèque de documentation de NetApp.

La documentation suivante est disponible :

* link:../san-config/index.html["Configuration SAN"]
+
Décrit les topologies FC, iSCSI et FCoE prises en charge pour la connexion des ordinateurs hôtes aux contrôleurs de stockage dans les clusters.

* https://docs.netapp.com/us-en/ontap-sanhost/index.html["Configuration de l'hôte SAN ONTAP"]
+
Décrit comment installer et configurer le logiciel Host Utilities.

* http://www.netapp.com/us/media/tr-4684.pdf["Rapport technique NetApp 4684 : implémentation et configuration des SAN modernes avec NVMe/FC"]
+
Décrit l'implémentation et la configuration de SAN avec NVMe/FC.

* http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Commandes de ONTAP 9"^]
+
Décrit les commandes ONTAP au format de référence.

* https://hwu.netapp.com["NetApp Hardware Universe"^]
+
Décrit les limites de configuration des contrôleurs et des hôtes SAN.


