---
permalink: san-admin/address-issues-when-luns-go-offline-concept.html 
sidebar: sidebar 
keywords: ways, address, issues, when, luns, go, offline 
summary: 'Lorsqu"aucun espace n"est disponible pour les écritures, les LUN sont mises hors ligne pour préserver l"intégrité des données. Les LUN peuvent manquer d"espace et les mettre hors ligne pour diverses raisons, et il existe plusieurs façons de résoudre le problème.' 
---
= Méthodes pour résoudre les problèmes lorsque les LUN sont mises hors ligne
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsqu'aucun espace n'est disponible pour les écritures, les LUN sont mises hors ligne pour préserver l'intégrité des données. Les LUN peuvent manquer d'espace et les mettre hors ligne pour diverses raisons, et il existe plusieurs façons de résoudre le problème.

[cols="2*"]
|===
| Si... | Vous pouvez... 


 a| 
L'agrégat est plein
 a| 
* Ajouter des disques.
* Utilisez le `volume modify` commande pour réduire un volume qui dispose d'un espace disponible.
* Si vous disposez de volumes Space-Guarantee qui disposent d'espace disponible, définissez la garantie d'espace de volume sur `none` avec le `volume modify` commande.




 a| 
Le volume est plein, mais l'agrégat contenant est disponible
 a| 
* Pour les volumes garantis par espace, utilisez `volume modify` commande pour augmenter la taille du volume.
* Pour les volumes à provisionnement fin, utilisez le `volume modify` commande pour augmenter la taille maximale du volume.
+
Si la croissance automatique de volume n'est pas activée, utiliser `volume modify -autogrow-mode` pour l'activer.

* Supprimez manuellement les copies Snapshot avec le `volume snapshot delete` ou utilisez la commande `volume snapshot autodelete modify` Commande permettant de supprimer automatiquement les copies Snapshot.


|===
.Informations associées
link:../disks-aggregates/index.html["Gestion des disques et des agrégats"]

link:../volumes/index.html["Gestion du stockage logique"]
