---
permalink: san-admin/change-uta2-port-cna-mode-fc-task.html 
sidebar: sidebar 
keywords: change, uta2, port, cna mode, fc mode 
summary: 'Vous devez modifier le port UTA2 entre le mode CNA (Converged Network adapter) et le mode FC (Fibre Channel) pour prendre en charge l"initiateur FC et le mode cible FC. Vous devez modifier la personnalité du mode CNA en mode FC lorsque vous devez modifier le support physique qui connecte le port à son réseau.' 
---
= Remplacez le port UTA2 du mode CNA par le mode FC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez modifier le port UTA2 entre le mode CNA (Converged Network adapter) et le mode FC (Fibre Channel) pour prendre en charge l'initiateur FC et le mode cible FC. Vous devez modifier la personnalité du mode CNA en mode FC lorsque vous devez modifier le support physique qui connecte le port à son réseau.

.Étapes
. Mettez l'adaptateur hors ligne :
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -status-admin down`

. Modifiez le mode des ports :
+
`ucadmin modify -node _node_name_ -adapter _adapter_name_ -mode fcp`

. Redémarrez le nœud, puis mettez l'adaptateur en ligne :
+
`network fcp adapter modify -node _node_name_ -adapter _adapter_name_ -status-admin up`

. Informez votre administrateur ou votre gestionnaire vif de supprimer ou de supprimer le port, le cas échéant :
+
** Si le port est utilisé en tant que port d'origine d'une LIF, est membre d'un groupe d'interface (ifgrp), ou des VLAN hôtes, un administrateur doit faire ce qui suit :
+
... Déplacez les LIF, retirez le port du ifgrp ou supprimez les VLAN.
... Supprimez manuellement le port en exécutant le `network port delete` commande.
+
Si le `network port delete` échec de la commande, l'administrateur doit corriger les erreurs, puis exécuter de nouveau la commande.

+
Pour en savoir plus, `network port delete` consultez le link:https://docs.netapp.com/us-en/ontap-cli/network-port-delete.html["Référence de commande ONTAP"^].



** Si le port n'est pas utilisé comme port de base d'une LIF, n'est pas membre d'un ifgrp. Il ne héberge pas les VLAN, alors le vif Manager doit supprimer le port de ses enregistrements au moment du redémarrage.
+
Si le vif Manager ne supprime pas le port, l'administrateur doit le supprimer manuellement après le redémarrage à l'aide du `network port delete` commande.

+
[listing]
----
net-f8040-34::> network port show

    Node: net-f8040-34-01
                                                      Speed(Mbps) Health
    Port      IPspace      Broadcast Domain Link MTU  Admin/Oper  Status
    --------- ------------ ---------------- ---- ---- ----------- --------
    ...
    e0i       Default      Default          down 1500  auto/10    -
    e0f       Default      Default          down 1500  auto/10    -
    ...

    net-f8040-34::> ucadmin show
                              Current  Current    Pending  Pending    Admin
    Node            Adapter   Mode     Type       Mode     Type       Status
    ------------    -------   -------  ---------  -------  ---------  -----------
    net-f8040-34-01   0e       cna      target     -        -          offline
    net-f8040-34-01   0f       cna      target     -        -          offline
    ...

    net-f8040-34::> network interface create -vs net-f8040-34 -lif m -role
node-mgmt-home-node net-f8040-34-01 -home-port e0e -address 10.1.1.1
-netmask 255.255.255.0


    net-f8040-34::> network interface show -fields home-port, curr-port

    vserver lif                   home-port curr-port
    ------- --------------------- --------- ---------
    Cluster net-f8040-34-01_clus1 e0a       e0a
    Cluster net-f8040-34-01_clus2 e0b       e0b
    Cluster net-f8040-34-01_clus3 e0c       e0c
    Cluster net-f8040-34-01_clus4 e0d       e0d
    net-f8040-34
            cluster_mgmt          e0M       e0M
    net-f8040-34
            m                     e0e       e0i
    net-f8040-34
            net-f8040-34-01_mgmt1 e0M       e0M
    7 entries were displayed.

    net-f8040-34::> ucadmin modify local 0e fc

    Warning: Mode on adapter 0e and also adapter 0f will be changed to fc.
    Do you want to continue? {y|n}: y
    Any changes will take effect after rebooting the system. Use the
"system node reboot" command to reboot.

    net-f8040-34::> reboot local
      (system node reboot)

    Warning: Are you sure you want to reboot node "net-f8040-34-01"?
    {y|n}: y
----


+
Pour en savoir plus, `network port show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/network-port-show.html["Référence de commande ONTAP"^].

. Vérifiez que le SFP+ est installé correctement :
+
`network fcp adapter show -instance -node -adapter`

+
Pour le CNA, vous devez utiliser un SFP Ethernet 10 Gbit. Pour ce faire, vous devez utiliser un SFP 8 Gbit ou un SFP 16 Gbit avant de modifier la configuration sur le nœud.

+
Pour en savoir plus, `network fcp adapter show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/network-fcp-adapter-show.html["Référence de commande ONTAP"^].



.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["interface réseau"^]

