---
permalink: san-admin/configure-network-best-performance-task.html 
sidebar: sidebar 
keywords: configure, your, network, best, performance 
summary: Les performances des réseaux Ethernet varient considérablement. Vous pouvez optimiser les performances du réseau utilisé pour iSCSI en sélectionnant des valeurs de configuration spécifiques. 
---
= Configurez votre réseau pour des performances optimales
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les performances des réseaux Ethernet varient considérablement. Vous pouvez optimiser les performances du réseau utilisé pour iSCSI en sélectionnant des valeurs de configuration spécifiques.

.Étapes
. Connectez l'hôte et les ports de stockage au même réseau.
+
Il est préférable de se connecter aux mêmes commutateurs. Le routage ne doit jamais être utilisé.

. Sélectionnez les ports à vitesse la plus élevée disponibles et dédier-les à iSCSI.
+
Les 10 ports GbE sont optimaux. Le nombre minimal de ports 1 GbE est égal à 1.

. Désactiver le contrôle de flux Ethernet pour tous les ports.
+
Vous devriez voir link:../networking/networking_reference.html["Gestion du réseau"] Pour configurer le contrôle de flux du port Ethernet à l'aide de l'interface de ligne de commande.

. Activez les trames Jumbo (généralement MTU de 9 9000).
+
Tous les périphériques du chemin d'accès aux données, y compris les initiateurs, les cibles et les commutateurs, doivent prendre en charge les trames Jumbo. Dans le cas contraire, l'activation des trames Jumbo réduit considérablement les performances du réseau.


