---
permalink: san-admin/configure-backup-vaults-san-environment-concept.html 
sidebar: sidebar 
keywords: configure, using, snapvault, backups, san, environment 
summary: 'La configuration et l"utilisation de SnapVault dans un environnement SAN sont très similaires à celles utilisées dans un environnement NAS. Toutefois, la restauration des LUN dans un environnement SAN nécessite des procédures spéciales.' 
---
= Configuration et utilisation des sauvegardes SnapVault dans un environnement SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La configuration et l'utilisation de SnapVault dans un environnement SAN sont très similaires à celles utilisées dans un environnement NAS. Toutefois, la restauration des LUN dans un environnement SAN nécessite des procédures spéciales.

Les sauvegardes SnapVault contiennent un ensemble de copies en lecture seule d'un volume source. Dans un environnement SAN, vous devez toujours sauvegarder des volumes entiers sur le volume secondaire SnapVault, et non sur des LUN individuelles.

La procédure de création et d'initialisation de la relation SnapVault entre un volume primaire contenant des LUN et un volume secondaire agissant comme sauvegarde SnapVault est identique à la procédure utilisée avec les volumes FlexVol utilisés pour les protocoles de fichiers. Cette procédure est décrite en détail dans link:../data-protection/index.html["La protection des données"].

Il est important de s'assurer que les LUN en cours de sauvegarde sont dans un état cohérent avant la création et la copie des snapshots sur le volume secondaire SnapVault. Grâce à l'automatisation de la création de snapshots avec SnapCenter, les LUN sauvegardées sont complètes et utilisables par l'application d'origine.

Il existe trois options de base pour la restauration des LUN à partir d'un volume secondaire SnapVault :

* Vous pouvez mapper une LUN directement à partir du volume secondaire SnapVault et connecter un hôte au LUN pour accéder au contenu de la LUN.
+
La LUN est en lecture seule et vous ne pouvez effectuer un mappage qu'à partir du snapshot le plus récent de la sauvegarde SnapVault. Les réservations et autres métadonnées LUN sont perdues. Si vous le souhaitez, vous pouvez utiliser un programme de copie sur l'hôte pour copier le contenu de la LUN vers la LUN d'origine si celle-ci est toujours accessible.

+
Le numéro de série de la LUN source est différent de celui de la LUN source.

* Vous pouvez cloner n'importe quel snapshot du volume secondaire SnapVault vers un nouveau volume en lecture-écriture.
+
Vous pouvez ensuite mapper l'une des LUN du volume et connecter un hôte au LUN pour accéder au contenu de la LUN. Si vous le souhaitez, vous pouvez utiliser un programme de copie sur l'hôte pour copier le contenu de la LUN vers la LUN d'origine si celle-ci est toujours accessible.

* Vous pouvez restaurer la totalité du volume contenant la LUN à partir de n'importe quel snapshot du volume secondaire SnapVault.
+
La restauration du volume entier remplace toutes les LUN, ainsi que tous les fichiers, dans le volume. Toute nouvelle LUN créée depuis la création du Snapshot est perdue.

+
Les LUN conservent leur mappage, leur numéro de série, leurs UUID et leurs réservations permanentes.


