---
permalink: san-admin/control-monitor-io-performance-luns-qos-task.html 
sidebar: sidebar 
keywords: control, monitor, i/o, performance, luns, using, storage qos 
summary: 'Vous pouvez contrôler les performances des entrées/sorties (E/S) des LUN en affectant des LUN aux groupes de règles de QoS de stockage. Vous pouvez contrôler les performances d"E/S pour permettre aux workloads d"atteindre des objectifs de performance spécifiques ou de limiter les workloads qui ont un impact négatif sur d"autres workloads.' 
---
= Contrôlez et surveillez les performances d'E/S des LUN grâce à la QoS de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez contrôler les performances des entrées/sorties (E/S) des LUN en affectant des LUN aux groupes de règles de QoS de stockage. Vous pouvez contrôler les performances d'E/S pour permettre aux workloads d'atteindre des objectifs de performance spécifiques ou de limiter les workloads qui ont un impact négatif sur d'autres workloads.

.Description de la tâche
Les groupes de règles appliquent une limite de débit maximal (par exemple, 100 Mo/s). Vous pouvez créer un groupe de règles sans spécifier un débit maximal, ce qui vous permet de contrôler les performances avant de contrôler le workload.

Vous pouvez également attribuer des SVM (Storage Virtual machines) avec des volumes FlexVol et des LUN à des groupes de règles.

Prenez en compte les exigences suivantes concernant l'assignation d'une LUN à un « policy group » :

* La LUN doit être contenue par le SVM auquel appartient le « policy group ».
+
Vous spécifiez la SVM lors de la création de la « policy group ».

* Si vous attribuez une LUN à une « policy group » alors vous ne pouvez pas attribuer le volume ou SVM contenant la LUN à une « policy group ».


Pour plus d'informations sur l'utilisation de la QoS du stockage, consultez le link:../system-admin/index.html["Référence d'administration du système"].

.Étapes
. Utilisez le `qos policy-group create` commande pour créer une « policy group ».
. Utilisez le `lun create` commande ou le `lun modify` commande avec `-qos-policy-group` Paramètre permettant d'affecter une LUN à une « policy group ».
. Utilisez le `qos statistics` commandes pour afficher les données de performances.
. Si nécessaire, utiliser l' `qos policy-group modify` commande pour ajuster la limite de débit maximale du groupe de règles.

