---
permalink: san-admin/data-protection-methods-reference.html 
sidebar: sidebar 
keywords: data, protection, methods, san, environments, snapmirror business continuity, smbc, snapshot copy, mirror, update, flexclone luns, license required, snapvault, backups, snapdrive, windows, unix 
summary: 'Vous pouvez protéger vos données en les faisant des copies afin qu"elles soient disponibles à des fins de restauration en cas de suppression accidentelle, de panne d"application, de corruption des données ou d"incident. Selon vos besoins en termes de protection et de sauvegarde des données, ONTAP propose plusieurs méthodes pour protéger vos données.' 
---
= Présentation des méthodes de protection des données dans les environnements SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez protéger vos données en les faisant des copies afin qu'elles soient disponibles à des fins de restauration en cas de suppression accidentelle, de panne d'application, de corruption des données ou d'incident. Selon vos besoins en termes de protection et de sauvegarde des données, ONTAP propose plusieurs méthodes pour protéger vos données.



== Continuité de l'activité SnapMirror (SM-BC)

Depuis la disponibilité générale de ONTAP 9.9.1, assure un délai de restauration nul ou un basculement transparent des applications (TAF) pour permettre le basculement automatique des applications stratégiques dans les environnements SAN. SM-BC requiert l'installation du Mediator 1.2 ONTAP dans une configuration avec deux clusters AFF ou deux clusters ASA (All SAN Array).

https://docs.netapp.com/us-en/ontap/smbc["Documentation NetApp : continuité de l'activité SnapMirror"^]



== La copie Snapshot

Vous permet de créer, de planifier et de gérer plusieurs sauvegardes de vos LUN manuellement ou automatiquement. Les copies Snapshot n'utilisent qu'une quantité minimale d'espace supplémentaire sur le volume et ne présentent pas de coûts de performances. Si vos données de la LUN sont accidentellement modifiées ou supprimées, elles peuvent être restaurées facilement et rapidement à partir de l'une des dernières copies Snapshot.



== LUN FlexClone (licence FlexClone requise)

Réalisation de copies inscriptibles instantanées d'une autre LUN dans un volume actif ou dans une copie Snapshot Un clone et son parent peuvent être modifiés de façon indépendante sans affecter les autres



== SnapRestore (licence requise)

Permet de restaurer rapidement des données à la demande, sans utiliser d'espace et avec des copies Snapshot sur un volume entier. Vous pouvez utiliser SnapRestore pour restaurer une LUN à un état conservé antérieur sans redémarrer le système de stockage.



== Copies miroir de protection des données (licence SnapMirror requise)

Offre une reprise après incident asynchrone en vous permettant de créer régulièrement des copies Snapshot des données sur votre volume, de les copier sur un réseau local ou étendu vers un volume partenaire, généralement sur un autre cluster, et de conserver ces copies Snapshot. La copie miroir du volume partenaire assure une disponibilité et une restauration rapides des données à partir de la dernière copie Snapshot, en cas de corruption ou de perte des données du volume source.



== Sauvegardes SnapVault (licence SnapMirror requise)

Permet un stockage efficace et une conservation à long terme des sauvegardes. Les relations SnapVault vous permettent de sauvegarder des copies Snapshot de volumes sélectionnées sur un volume de destination et de conserver les sauvegardes.

Si vous réalisez des sauvegardes sur bande et des opérations d'archivage, vous pouvez les effectuer sur les données déjà sauvegardées sur le volume secondaire de SnapVault.



== SnapDrive pour Windows ou UNIX (licence SnapDrive requise)

Configure l'accès aux LUN, gère les LUN et gère les copies Snapshot du système de stockage directement à partir d'hôtes Windows ou UNIX.



== Sauvegarde et restauration natives sur bande

La prise en charge de la plupart des lecteurs de bandes existants est incluse dans ONTAP, ainsi qu'une méthode permettant aux fournisseurs de bandes d'ajouter dynamiquement la prise en charge des nouveaux périphériques. ONTAP prend également en charge le protocole RMT (Remote Magnetic Tape), permettant ainsi une sauvegarde et une restauration vers tout système capable.

.Informations associées
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30050["Documentation NetApp : SnapDrive pour UNIX"^]

http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30049["Documentation NetApp : SnapDrive pour Windows (versions actuelles)"^]

link:../tape-backup/index.html["Protection des données par sauvegarde sur bandes"]
