---
permalink: san-admin/define-authentication-method-initiator-task.html 
sidebar: sidebar 
keywords: define, security, policy, method, initiator 
summary: 'Vous pouvez définir une liste d"initiateurs et leurs méthodes d"authentification. Vous pouvez également modifier la méthode d"authentification par défaut qui s"applique aux initiateurs qui n"ont pas de méthode d"authentification définie par l"utilisateur.' 
---
= Définir une méthode de stratégie de sécurité pour un initiateur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez définir une liste d'initiateurs et leurs méthodes d'authentification. Vous pouvez également modifier la méthode d'authentification par défaut qui s'applique aux initiateurs qui n'ont pas de méthode d'authentification définie par l'utilisateur.

Vous pouvez générer des mots de passe uniques à l'aide d'algorithmes de règles de sécurité dans le produit ou vous pouvez spécifier manuellement les mots de passe que vous souhaitez utiliser.

[NOTE]
====
Tous les initiateurs ne prennent pas en charge les mots de passe secrets CHAP hexadécimaux.

====
.Étapes
. Utilisez le `vserver iscsi security create` commande permettant de créer une méthode de stratégie de sécurité pour un initiateur.
+
`vserver iscsi security create -vserver vs2 -initiator iqn.1991-05.com.microsoft:host1 -auth-type CHAP -user-name bob1 -outbound-user-name bob2`

. Suivez les commandes à l'écran pour ajouter les mots de passe.
+
Crée une méthode de stratégie de sécurité pour l'initiateur iqn.1991-05.com.microsoft:host1 avec des noms d'utilisateur et des mots de passe CHAP entrants et sortants.



.Informations associées
* xref:iscsi-authentication-concept.adoc[Fonctionnement de l'authentification iSCSI]
* xref:using-chap-authentication-concept.adoc[Consignes d'utilisation de l'authentification CHAP]
* xref:chap-authentication-concept.adoc[Qu'est-ce que l'authentification CHAP]

