---
permalink: san-admin/delete-iscsi-service-svm-task.html 
sidebar: sidebar 
keywords: delete, iscsi, service, svm 
summary: 'Vous pouvez supprimer un service iSCSI pour une machine virtuelle de stockage (SVM) s"il n"est plus nécessaire.' 
---
= Suppression d'un service iSCSI pour une SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez supprimer un service iSCSI pour une machine virtuelle de stockage (SVM) s'il n'est plus nécessaire.

.Avant de commencer
L'état d'administration du service iSCSI doit être à l'état "`down`" avant de pouvoir supprimer un service iSCSI. Vous pouvez déplacer l'état d'administration vers le bas à l'aide de `vserver iscsi modify` commande.

.Étapes
. Utilisez le `vserver iscsi modify` Commande permettant d'arrêter les E/S vers la LUN.
+
`vserver iscsi modify -vserver vs1 -status-admin down`

. Utilisez le `vserver iscsi delete` Commande permettant de supprimer le service iscsi du SVM.
+
`vserver iscsi delete -vserver vs_1`

. Utilisez le `vserver iscsi show command` Pour vérifier que vous avez supprimé le service iSCSI de la SVM.
+
`vserver iscsi show -vserver vs1`


