---
permalink: san-admin/edit-lun-qos-policy-task.html 
sidebar: sidebar 
keywords: system manager, san, lun, qos, group, policy, quality, service, edit, editing, update, updating, change, changing 
summary: Depuis ONTAP 9.10.1, vous pouvez utiliser System Manager pour attribuer ou supprimer des règles de QoS sur plusieurs LUN en même temps. 
---
= Modifiez la « policy group » QoS de la LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Depuis ONTAP 9.10.1, vous pouvez utiliser System Manager pour attribuer ou supprimer des règles de QoS sur plusieurs LUN en même temps.


NOTE: Si la politique de QoS est attribuée au niveau du volume, elle doit être modifiée au niveau du volume. Vous pouvez modifier la règle de qualité de services au niveau des LUN uniquement s'il a été initialement attribué au niveau des LUN.

.Étapes
. Dans System Manager, cliquez sur *stockage > LUN*.
. Sélectionnez la ou les LUN à modifier.
+
Si vous modifiez plusieurs LUN à la fois, les LUN doivent appartenir au même SVM (Storage Virtual machine). Si vous sélectionnez des LUN qui n'appartiennent pas au même SVM, l'option de modification du QoS Policy Group n'est pas affichée.

. Cliquez sur *plus* et sélectionnez *Modifier groupe de stratégies QoS*.

