---
permalink: san-admin/enable-space-allocation-scsi-thin-provisioned-luns-task.html 
sidebar: sidebar 
keywords: enable, space, allocation, scsi, thinly, provisioned luns 
summary: 'Si vous définissez l"option d"allocation d"espace sur activé, ONTAP notifie l"hôte lorsque l"espace du volume est insuffisant et la LUN du volume ne peut pas accepter les écritures. Cette option permet également à ONTAP de récupérer automatiquement de l"espace lorsque votre hôte supprime des données.' 
---
= Activez l'allocation d'espace pour les LUN SCSI à provisionnement fin
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous définissez le `space-allocation` option à `enabled`, ONTAP informe l'hôte lorsque l'espace du volume est insuffisant et que la LUN du volume ne peut pas accepter les écritures. Cette option permet également à ONTAP de récupérer automatiquement de l'espace lorsque votre hôte supprime des données.

.Description de la tâche
Le `space-allocation` l'option est définie sur `disabled` Par défaut, et vous devez mettre la LUN hors ligne pour permettre l'allocation d'espace. Après avoir activé l'allocation d'espace, vous devez effectuer une détection sur l'hôte pour que l'hôte reconnaisse que l'allocation d'espace a été activée.

.Étapes
. Mettez la LUN hors ligne.
+
[source, cli]
----
lun modify -vserver vserver_name -volume volume_name -lun lun_name -state offline
----
. Activer l'allocation d'espace :
+
[source, cli]
----
lun modify -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -space-allocation enabled
----
. Vérifiez que l'allocation d'espace est activée :
+
[source, cli]
----
lun show -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -fields space-allocation
----
. Mettre la LUN en ligne :
+
[source, cli]
----
lun modify -vserver _vserver_name_ -volume _volume_name_ -lun _lun_name_ -state online
----
. Sur l'hôte, relancez l'analyse de tous les disques pour vous assurer que la modification apportée à l' `-space-allocation` l'option est correctement découverte.

