---
permalink: san-admin/example-how-igroups-give-lun-access-reference.html 
sidebar: sidebar 
keywords: ontap 9.2, example, how, igroups, give, lun, access 
summary: 'Vous pouvez créer plusieurs igroups pour définir quels LUN sont disponibles pour vos hôtes. Par exemple, si vous disposez d"un cluster hôte, vous pouvez utiliser des igroups pour s"assurer que des LUN spécifiques ne sont visibles que pour un seul hôte du cluster ou pour tous les hôtes du cluster.' 
---
= Exemple de mode d'accès des groupes initiateurs aux LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer plusieurs igroups pour définir quels LUN sont disponibles pour vos hôtes. Par exemple, si vous disposez d'un cluster hôte, vous pouvez utiliser des igroups pour s'assurer que des LUN spécifiques ne sont visibles que pour un seul hôte du cluster ou pour tous les hôtes du cluster.

Le tableau suivant montre comment quatre groupes initiateurs accèdent aux LUN pour quatre hôtes différents qui accèdent au système de stockage. Les hôtes en cluster (Host3 et Host4) sont tous deux membres du même groupe initiateur (groupe3) et peuvent accéder aux LUN mappées à ce groupe initiateur. Le groupe initiateur nommé groupe4 contient les WWPN de Host4 pour stocker les informations locales qui ne sont pas destinées à être vues par son partenaire.

[cols="4*"]
|===
| Hôtes avec WWPN HBA, IQN ou EUI | igroups | WWPN, IQN et EUI ajoutés aux igroups | LUN mappées aux igroups 


 a| 
Host1, chemin unique (initiateur de logiciel iSCSI)

iqn.1991-05.com.microsoft:host1
 a| 
groupe 1
 a| 
iqn.1991-05.com.microsoft:host1
 a| 
`/vol/vol2/lun1`



 a| 
Host2, multipath (deux HBA)

10:00:00:00:c9:2b:6b:3c

10:00:00:00:c9:2b:02:3c
 a| 
groupe 2
 a| 
10:00:00:00:c9:2b:6b:3c

10:00:00:00:c9:2b:02:3c
 a| 
`/vol/vol2/lun2`



 a| 
Host3, multipath, cluster avec l'hôte 4

10:00:00:00:c9:2b:32:1b

10:00:00:00:c9:2b:41:02
 a| 
groupe 3
 a| 
10:00:00:00:c9:2b:32:1b

10:00:00:00:c9:2b:41:02

10:00:00:00:c9:2b:51:2c

10:00:00:00:c9:2b:47:a2
 a| 
`/vol/vol2/qtree1/lun3`



 a| 
Host4, multichemin, cluster (non visible sur Host3)

10:00:00:00:c9:2b:51:2c

10:00:00:00:c9:2b:47:a2
 a| 
groupe4
 a| 
10:00:00:00:c9:2b:51:2c

10:00:00:00:c9:2b:47:a2
 a| 
`/vol/vol2/qtree2/lun4` `/vol/vol2/qtree1/lun5`

|===