---
permalink: san-admin/get-details-iscsi-session-error-recoveries-task.html 
sidebar: sidebar 
keywords: get, more, details, iscsi, session, error, recoveries 
summary: 'L"augmentation du niveau de récupération des erreurs de session iSCSI vous permet de recevoir des informations plus détaillées sur les restaurations d"erreurs iSCSI. L"utilisation d"un niveau de récupération d"erreur plus élevé peut entraîner une réduction mineure des performances de la session iSCSI.' 
---
= Obtenez plus de détails dans les restaurations d'erreurs de session iSCSI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'augmentation du niveau de récupération des erreurs de session iSCSI vous permet de recevoir des informations plus détaillées sur les restaurations d'erreurs iSCSI. L'utilisation d'un niveau de récupération d'erreur plus élevé peut entraîner une réduction mineure des performances de la session iSCSI.

.Description de la tâche
Par défaut, ONTAP est configuré pour utiliser le niveau de récupération d'erreur 0 pour les sessions iSCSI. Si vous utilisez un initiateur qui a été qualifié pour la récupération d'erreur de niveau 1 ou 2, vous pouvez choisir d'augmenter le niveau de récupération d'erreur. Le niveau de récupération d'erreur de session modifié n'affecte que les sessions nouvellement créées et n'affecte pas les sessions existantes.

À partir de ONTAP 9.4, le `max-error-recovery-level` cette option n'est pas prise en charge dans le `iscsi show` et `iscsi modify` commandes.

.Étapes
. Entrer en mode avancé :
+
`set -privilege advanced`

. Vérifiez le paramètre actuel à l'aide du `iscsi show` commande.
+
`iscsi show -vserver vs3 -fields max-error-recovery-level`

+
[listing]
----
vserver max-error-recovery-level
------- ------------------------
vs3     0
----
. Modifiez le niveau de récupération d'erreur à l'aide de `iscsi modify` commande.
+
`iscsi modify -vserver vs3 -max-error-recovery-level 2`


