---
permalink: san-admin/host-side-management-concept.html 
sidebar: sidebar 
keywords: understand, host-side, space, management 
summary: 'Dans un environnement à provisionnement fin, la gestion de l"espace côté hôte complète le processus de gestion de l"espace depuis le système de stockage qui a été libéré dans le système de fichiers hôte.' 
---
= Gestion de l'espace côté hôte SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dans un environnement à provisionnement fin, la gestion de l'espace côté hôte complète le processus de gestion de l'espace depuis le système de stockage qui a été libéré dans le système de fichiers hôte.

Un système de fichiers hôte contient des métadonnées pour suivre les blocs disponibles pour stocker de nouvelles données et les blocs contenant des données valides qui ne doivent pas être écrasés. Ces métadonnées sont stockées au sein de la LUN. Lorsqu'un fichier est supprimé dans le système de fichiers hôte, les métadonnées du système de fichiers sont mises à jour pour marquer les blocs de ce fichier comme espace libre. L'espace total disponible du système de fichiers est ensuite recalculé pour inclure les blocs récemment libérés. Sur le système de stockage, ces mises à jour de métadonnées n'apparaissent aucune différence entre les autres écritures effectuées par l'hôte. Par conséquent, le système de stockage n'a pas conscience que des suppressions se sont produits.

Cela crée un écart entre la quantité d'espace libre signalée par l'hôte et la quantité d'espace libre signalée par le système de stockage sous-jacent. Supposons par exemple que vous avez affecté un nouveau LUN de 200 Go provisionné à l'hôte par votre système de stockage. L'hôte et le système de stockage indiquent 200 Go d'espace libre. L'hôte écrit alors 100 Go de données. À ce stade, l'hôte et le système de stockage indiquent 100 Go d'espace utilisé et 100 Go d'espace inutilisé.

Vous supprimez ensuite 50 Go de données de votre hôte. À ce stade, votre hôte indique 50 Go d'espace utilisé et 150 Go d'espace inutilisé. Toutefois, votre système de stockage indique 100 Go d'espace utilisé et 100 Go d'espace inutilisé.

La gestion de l'espace côté hôte utilise différentes méthodes pour concilier la différence d'espace entre l'hôte et le système de stockage.



== Gestion simplifiée de l'hôte avec SnapCenter

Le logiciel SnapCenter permet de simplifier certaines des tâches de gestion et de protection des données associées aux solutions de stockage iSCSI et FC. SnapCenter est un package de gestion facultatif pour les hôtes Windows et UNIX.

Le logiciel SnapCenter peut être utilisé pour créer facilement des disques virtuels à partir de pools de stockage qui peuvent être distribués sur plusieurs systèmes de stockage, ainsi que pour automatiser des tâches de provisionnement du stockage et simplifier le processus de création de copies Snapshot et de clones à partir de copies Snapshot cohérentes avec les données hôtes.

Consultez la documentation des produits NetApp pour plus d'informations sur https://docs.netapp.com/us-en/snapcenter/index.html["SnapCenter"].

.Liens connexes
link:enable-space-allocation-scsi-thin-provisioned-luns-task.html["Activez l'allocation d'espace pour les LUN SCSI à provisionnement fin"]
