---
permalink: san-admin/igroups-concept.html 
sidebar: sidebar 
keywords: understand, igroups 
summary: 'Les groupes initiateurs sont des tableaux des WWPN des hôtes du protocole FC ou des noms des nœuds hôtes iSCSI. Vous pouvez définir des groupes initiateurs et les mapper sur des LUN pour contrôler l"accès des initiateurs aux LUN.' 
---
= À propos des igroups
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les groupes initiateurs sont des tableaux des WWPN des hôtes du protocole FC ou des noms des nœuds hôtes iSCSI. Vous pouvez définir des groupes initiateurs et les mapper sur des LUN pour contrôler l'accès des initiateurs aux LUN.

Généralement, vous souhaitez que tous les ports initiateurs ou initiateurs logiciels de l'hôte puissent accéder à une LUN. Si vous utilisez un logiciel de chemins d'accès multiples ou que vous disposez d'hôtes en cluster, chaque port d'initiateur ou initiateur logiciel de chaque hôte en cluster a besoin de chemins redondants vers la même LUN.

Vous pouvez créer des groupes initiateurs spécifiant les initiateurs auxquels les initiateurs ont accès aux LUN avant ou après leur création. Vous devez toutefois créer des groupes initiateurs avant de pouvoir mapper une LUN sur un groupe initiateur.

Plusieurs groupes initiateurs peuvent avoir plusieurs initiateurs. Vous pouvez également avoir le même initiateur. Toutefois, vous ne pouvez pas mapper une LUN sur plusieurs groupes initiateurs qui ont le même initiateur. Un initiateur ne peut pas être membre des igroups de différents otypes.
