---
permalink: san-admin/iscsi-endpoint-isolation-concept.html 
sidebar: sidebar 
keywords: iscsi, endpoint, isolation, add, remove, initiator, address, range 
summary: 'À partir de ONTAP 9.1, les commandes de sécurité iSCSI existantes ont été améliorées pour accepter une plage d"adresses IP, ou plusieurs adresses IP.' 
---
= Isolation du terminal iSCSI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À partir de ONTAP 9.1, les commandes de sécurité iSCSI existantes ont été améliorées pour accepter une plage d'adresses IP, ou plusieurs adresses IP.

Tous les initiateurs iSCSI doivent fournir des adresses IP d'origine lors de l'établissement d'une session ou d'une connexion avec une cible. Cette nouvelle fonctionnalité empêche un initiateur de se connecter au cluster si l'adresse IP d'origine n'est pas prise en charge ou inconnue, fournissant un schéma d'identification unique. Tout initiateur provenant d'une adresse IP non prise en charge ou inconnue aura son login rejeté au niveau de la couche de session iSCSI, empêchant l'initiateur d'accéder à n'importe quelle LUN ou volume du cluster.

Mettez en œuvre cette nouvelle fonctionnalité à l'aide de deux nouvelles commandes pour faciliter la gestion des entrées préexistantes.



== Ajouter une plage d'adresses initiateur

Améliorez la gestion de la sécurité de l'initiateur iSCSI en ajoutant une plage d'adresses IP ou plusieurs adresses IP avec le `vserver iscsi security add-initiator-address-range` commande.

`cluster1::> vserver iscsi security add-initiator-address-range`



== Supprimer la plage d'adresses initiateurs

Supprimez une ou plusieurs adresses IP avec le `vserver iscsi security remove-initiator-address-range` commande.

`cluster1::> vserver iscsi security remove-initiator-address-range`
