---
permalink: san-admin/lif-movement-concept.html 
sidebar: sidebar 
keywords: considerations, san, lif, movement 
summary: 'Vous n"avez besoin d"effectuer un déplacement de LIF que si vous modifiez le contenu du cluster, par exemple : ajout de nœuds au cluster ou suppression de nœuds. Si vous effectuez un déplacement LIF, vous n"avez pas besoin de remettre votre structure FC ou de créer de nouvelles sessions iSCSI entre les hôtes connectés de votre cluster et la nouvelle interface cible.' 
---
= Que savoir avant de déplacer une LIF SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous n'avez besoin d'effectuer un déplacement de LIF que si vous modifiez le contenu du cluster, par exemple : ajout de nœuds au cluster ou suppression de nœuds. Si vous effectuez un déplacement LIF, vous n'avez pas besoin de remettre votre structure FC ou de créer de nouvelles sessions iSCSI entre les hôtes connectés de votre cluster et la nouvelle interface cible.

Vous ne pouvez pas déplacer une LIF SAN à l'aide de `network interface move` commande. Le déplacement de la LIF SAN doit être effectué en mettant la LIF hors ligne, en la déplaçant vers un autre nœud ou port de rattachement, puis en la remettant en ligne sur son nouvel emplacement. L'ALUA (Asymmetric Logical Unit Access) offre des chemins redondants et une sélection de chemin automatique dans le cadre de n'importe quelle solution SAN de ONTAP. Par conséquent, il n'y a pas d'interruption d'E/S lorsque la LIF est mise hors ligne pour le déplacement. L'hôte tente simplement de retraiter et déplace les E/S vers un autre LIF.

Grâce au déplacement de LIF, vous pouvez effectuer les opérations suivantes sans interruption :

* Remplacez une paire haute disponibilité d'un cluster par une paire haute disponibilité mise à niveau de manière transparente pour les hôtes qui accèdent aux données de la LUN
* Mettre à niveau une carte d'interface cible
* Transfert des ressources d'un serveur virtuel de stockage (SVM) d'un ensemble de nœuds d'un cluster vers un autre ensemble de nœuds du cluster

