---
permalink: san-admin/manage-lifs-all-san-protocols-concept.html 
sidebar: sidebar 
keywords: manage, lifs, san protocols 
summary: 'Les LIF sont connectées aux hôtes SAN. Elles peuvent être retirées des ensembles de ports, déplacées vers différents nœuds au sein d"une machine virtuelle de stockage et supprimées.' 
---
= En savoir plus sur les LIF ONTAP pour les environnements SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les LUN et les espaces de noms dans votre système ONTAP sont contenus dans des machines virtuelles de stockage (SVM). Les interfaces réseau (LIF) permettent à vos clients SAN de se connecter à une SVM et d'accéder aux données dans les LUN et les espaces de noms qu'elle contient.

* Vous devez configurer une interface logique de gestion (LIF) pour chaque machine virtuelle de stockage (SVM) prenant en charge le SAN.
* Vous pouvez configurer deux LIF par nœud, une pour chaque structure utilisée avec FC et pour séparer les réseaux Ethernet pour iSCSI.
* La connectivité peut s'effectuer par connexion directe ou via des commutateurs Ethernet. Vous devez configurer les LIF pour les deux types de connectivité.


Apprendre àlink:../networking/create_a_lif.html["Créer une LIF"]

.Informations associées
* link:../networking/configure_lifs_cluster_administrators_only_overview.html["Apprenez-en davantage sur la configuration LIF"]
* link:multipath-automatic-lif-failover-support.html["Découvrez la prise en charge du basculement automatique LIF SAN"].

