---
permalink: san-admin/manage-lifs-all-san-protocols-concept.html 
sidebar: sidebar 
keywords: manage, lifs, san protocols 
summary: 'Les LIF sont connectées aux hôtes SAN. Ils peuvent être supprimés des ensembles de ports, déplacés vers différents nœuds au sein d"une machine virtuelle de stockage (SVM) et supprimés.' 
---
= Gérez les LIF de tous les protocoles SAN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les initiateurs doivent utiliser les options MPIO (Multi Path I/O) et ALUA (Asymmetric Logical Unit Access) pour la capacité de basculement des clusters dans un environnement SAN. Si un nœud tombe en panne, les LIFs ne migrent pas et ne partent pas des adresses IP du nœud partenaire défaillant. À la place, le logiciel MPIO, avec ALUA sur l'hôte, est chargé de sélectionner les chemins d'accès appropriés pour les LUN via les LIF.

Vous devez créer un ou plusieurs chemins iSCSI depuis chaque nœud d'une paire haute disponibilité à l'aide des interfaces logiques (LIF) pour permettre l'accès aux LUN qui sont gérés par la paire haute disponibilité.  Il est recommandé de configurer une LIF de gestion pour chaque SVM prenant en charge SAN.

La connexion directe ou l'utilisation de commutateurs Ethernet sont prises en charge pour la connectivité. Vous devez créer des LIF pour les deux types de connectivité.

* Il est recommandé de configurer une LIF de gestion pour chaque SVM prenant en charge SAN.
Vous pouvez configurer deux LIF par nœud, un pour chaque structure utilisée avec FC et plusieurs réseaux Ethernet pour iSCSI.


Une fois les LIF créées, elles peuvent être supprimées des jeux de ports, déplacées vers différents nœuds d'une machine virtuelle de stockage (SVM), et supprimées.

.Informations associées
* link:../networking/configure_lifs_cluster_administrators_only_overview.html#lif-failover-and-giveback["Configurer la présentation des LIFs"]
* link:../networking/create_a_lif.html["Créer une LIF"]

