---
permalink: san-admin/manage-nvme-concept.html 
sidebar: sidebar 
keywords: manage, nvme, overview, license 
summary: 'La technologie NVMe/FC est prise en charge à partir de la version ONTAP 9.4. Une licence est requise pour la prise en charge de NVMe à partir de ONTAP 9.5. Si NVMe est activé dans ONTAP 9.4, une période de grâce de 90 jours est accordée pour l"acquisition de la licence après la mise à niveau vers ONTAP 9.5.' 
---
= Présentation de NVMe
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis la version ONTAP 9.4, NVMe/FC est pris en charge sur les configurations AFF non MetroCluster. Depuis la version ONTAP 9.9.1 NVMe/FC est également pris en charge sur toutes les configurations ASA (All SAN Array) non MetroCluster.

Vous pouvez utiliser le protocole NVMe (non-volatile Memory Express) pour fournir du stockage dans un environnement SAN. Le protocole NVMe est optimisé pour les performances du stockage Solid state.

Pour NVMe, les cibles de stockage sont appelées espaces de noms. Un namespace NVMe est une quantité de stockage non volatile pouvant être formatée dans des blocs logiques et présentée à un hôte comme un périphérique de bloc standard. Vous créez des espaces de noms et des sous-systèmes, puis mappez les espaces de noms aux sous-systèmes, de la même manière que les LUN sont provisionnées et mappées aux igroups pour FC et iSCSI.

Les cibles NVMe sont connectées au réseau via une infrastructure FC standard en utilisant des switchs FC ou une infrastructure TCP standard à l'aide de switchs Ethernet et d'adaptateurs côté hôte.



== Qu'est-ce que NVMe

Le protocole NVMe (Nonvolatile Memory Express) est un protocole de transport utilisé pour l'accès aux supports de stockage non volatiles.

NVMe over Fabrics (NVMeoF) est une extension définie par la spécification vers NVMe qui permet une communication basée sur NVMe avec des connexions autres que PCIe. Cette interface permet de connecter des armoires de stockage externes à un serveur.

Conçue pour fournir un accès efficace aux dispositifs de stockage conçus avec une mémoire non volatile, de la technologie Flash aux technologies de mémoire persistante plus performantes. En tant que telle, elle ne présente pas les mêmes limites que les protocoles de stockage conçus pour les disques durs. Les périphériques Flash et Solid State Devices (SSD) sont un type de mémoire non volatile (NVM). NVM est un type de mémoire qui conserve son contenu pendant une coupure de courant. C'est une méthode qui vous permet d'accéder à cette mémoire.

La vitesse, la productivité, le débit et la capacité accrues sont autant d'avantages pour le transfert de données. Caractéristiques spécifiques :

* NVMe est conçu pour accueillir jusqu'à 64 000 files d'attente.
+
Chaque file d'attente peut à son tour comporter jusqu'à 64 000 commandes simultanées.

* La technologie NVMe est prise en charge par plusieurs fournisseurs matériels et logiciels
* NMVe est plus productif grâce aux technologies Flash, qui accélèrent les temps de réponse
* NVMe autorise plusieurs requêtes de données pour chaque « demande » envoyée vers le SSD.
+
NVMe apporte moins de temps à décoder une « recherche » et n'exige pas de verrouillage des threads dans un programme multithread.

* NVMe prend en charge des fonctionnalités qui empêchent les goulots d'étranglement au niveau du CPU et assure une évolutivité massive au fur et à mesure que les systèmes augmentent.




== À propos des espaces de noms NVMe

Un namespace NVMe est une quantité de mémoire non volatile (NVM) pouvant être formatée dans des blocs logiques. Les espaces de noms sont utilisés lorsqu'un serveur virtuel de stockage est configuré avec le protocole NVMe et équivalent de LUN pour les protocoles FC et iSCSI.

Un ou plusieurs espaces de noms sont provisionnés et connectés à un hôte NVMe. Chaque espace de noms peut prendre en charge plusieurs tailles de blocs.

Le protocole NVMe donne accès aux espaces de noms via plusieurs contrôleurs. À l'aide des pilotes NVMe, pris en charge sur la plupart des systèmes d'exploitation, les espaces de noms des disques SSD apparaissent comme des périphériques de bloc standard sur lesquels les systèmes de fichiers et les applications peuvent être déployés sans aucune modification.

Un ID d'espace de noms (NSID) est un identifiant utilisé par un contrôleur pour fournir l'accès à un espace de noms. Lors de la définition du NSID pour un hôte ou un groupe d'hôtes, vous configurez également l'accessibilité à un volume par un hôte. Un bloc logique ne peut être mappé qu'à un seul groupe d'hôtes à la fois et un groupe d'hôtes donné ne possède pas de NSID en double.



== À propos des sous-systèmes NVMe

Un sous-système NVMe comprend un ou plusieurs contrôleurs NVMe, des espaces de noms, des ports de sous-système NVM, un support de stockage NVM et une interface entre le contrôleur et le support de stockage NVM. Par défaut, lorsque vous créez un namespace NVMe, ce dernier n'est pas mappé sur un sous-système. Vous pouvez également choisir de mapper un sous-système nouveau ou existant.

.Informations associées
* link:../task_nvme_provision_suse_linux.html["Provisionnement du stockage NVMe pour SUSE Linux"]
* link:../create-nvme-namespace-subsystem-task.html["De stockage NVMe de provisionnoin pour les autres hôtes"]
* link:san-admin/map-nvme-namespace-subsystem-task.html["Mappez un namespace NVMe à un sous-système"]

