---
permalink: san-admin/map-nvme-namespace-subsystem-task.html 
sidebar: sidebar 
keywords: map, nvme, namespace, subsystem 
summary: 'Lors de l"utilisation de NVMe, vous devez mapper un namespace sur un sous-système.' 
---
= Mappez un namespace NVMe à un sous-système
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le mappage d'un namespace NVMe sur un sous-système permet l'accès aux données depuis votre hôte.  Vous pouvez mapper un namespace NVMe à un sous-système lors du provisionnement du stockage ou le faire une fois celui-ci provisionné.

À partir d' ONTAP 9.17.1, si vous utilisez une configuration SnapMirror Active Sync, vous pouvez ajouter une SVM à un hôte en tant que serveur virtuel proximal lors de l'ajout de l'hôte à un sous-système NVMe. Les chemins optimisés pour un espace de noms dans un sous-système NVMe sont publiés sur un hôte uniquement à partir de la SVM configurée comme serveur virtuel proximal.

À partir de ONTAP 9.14.1, vous pouvez hiérarchiser l'allocation des ressources pour des hôtes spécifiques. Par défaut, lorsqu'un hôte est ajouté au sous-système NVMe, sa priorité est donnée. Vous pouvez utiliser l'interface de ligne de commandes ONTAP pour modifier manuellement la priorité par défaut, de normal à élevée.  Les hôtes affectés à une priorité élevée reçoivent un nombre de files d'attente d'E/S et des profondeurs de files d'attente plus importants.


NOTE: Si vous souhaitez donner une priorité élevée à un hôte ajouté à un sous-système dans ONTAP 9.13.1 ou une version antérieure, vous pouvez le faire xref:../nvme/change-host-priority-nvme-task.html[modifiez la priorité de l'hôte].

.Avant de commencer
Votre espace de noms et votre sous-système doivent déjà être créés. Si vous devez créer un espace de noms et un sous-système, reportez-vous à la section link:create-nvme-namespace-subsystem-task.html["Provisionner le stockage NVMe"].



== Cartographier un espace de noms NVMe

.Étapes
. Obtenez le NQN de l'hôte.
. Ajoutez le NQN hôte au sous-système :
+
[source, cli]
----
vserver nvme subsystem host add -vserver <SVM_name> -subsystem <subsystem_name> -host-nqn <Host_NQN_:subsystem._subsystem_name>
----
+
Si vous souhaitez modifier la priorité par défaut de l'hôte de normal à élevé, utilisez l' `-priority high`option. Cette option est disponible à partir de ONTAP 9.14.1. Pour en savoir plus, `vserver nvme subsystem host add` consultez le link:https://docs.netapp.com/us-en/ontap-cli/vserver-nvme-subsystem-host-add.html["Référence de commande ONTAP"^].

+
Si vous souhaitez ajouter un SVM en tant que  `proximal-vserver` à un hôte lors de l'ajout de l'hôte à un sous-système NVMe dans une configuration de synchronisation active SnapMirror , vous pouvez utiliser le  `-proximal-vservers` Option. Cette option est disponible à partir d' ONTAP 9.17.1. Vous pouvez ajouter la SVM source ou de destination, ou les deux. La SVM dans laquelle vous exécutez cette commande est celle par défaut.

. Mapper l'espace de noms au sous-système :
+
[source, cli]
----
vserver nvme subsystem map add -vserver <SVM_name> -subsystem <subsystem_name> -path <path>
----
+
Un espace de noms ne peut être mappé qu'à un seul sous-système. Pour en savoir plus, `vserver nvme subsystem map add` consultez le link:https://docs.netapp.com/us-en/ontap-cli/vserver-nvme-subsystem-map-add.html["Référence de commande ONTAP"^].

. Vérifiez que l'espace de noms est mappé sur le sous-système :
+
[source, cli]
----
vserver nvme namespace show -vserver <SVM_name> -instance
----
+
Le sous-système doit être répertorié comme `Attached subsystem` . Pour en savoir plus, `vserver nvme namespace show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/vserver-nvme-namespace-show.html["Référence de commande ONTAP"^].


