---
permalink: san-admin/map-nvme-namespace-subsystem-task.html 
sidebar: sidebar 
keywords: map, nvme, namespace, subsystem 
summary: 'Lors de l"utilisation de NVMe, vous devez mapper un namespace sur un sous-système.' 
---
= Mappez un namespace NVMe à un sous-système
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette procédure mappe un namespace NVMe existant sur un sous-système NVMe existant à l'aide de l'interface de ligne de commande ONTAP.

Votre espace de noms et votre sous-système doivent déjà être créés. Si vous devez créer un espace de noms et un sous-système, reportez-vous à la section link:create-nvme-namespace-subsystem-task.html["Provisionner le stockage NVMe"].

.Étapes
. Obtenez le NQN de l'hôte.
. Ajoutez le NQN hôte au sous-système :
+
`vserver nvme subsystem host add -vserver _SVM_name_ -subsystem _subsystem_name_ -host-nqn _Host_NQN_:subsystem._subsystem_name_`

. Mapper l'espace de noms au sous-système :
+
`vserver nvme subsystem map add -vserver _SVM_name_ -subsystem _subsystem_name_ -path _path_`

+
Un espace de noms ne peut être mappé qu'à un seul sous-système.

. Vérifiez que l'espace de noms est mappé sur le sous-système :
+
`vserver nvme namespace show -vserver _SVM_name_ -instance`

+
Le sous-système doit être répertorié comme `Attached subsystem`.


