---
permalink: san-admin/move-san-lifs-task.html 
sidebar: sidebar 
keywords: move, san, lifs 
summary: Si un nœud doit être mis hors ligne, vous pouvez déplacer une SAN LIF afin de préserver ses informations de configuration, telles que son WWPN, et éviter le rezonage de la matrice de commutation. 
---
= Déplacer une LIF SAN ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si un nœud doit être mis hors ligne, vous pouvez déplacer une LIF SAN afin de préserver ses informations de configuration, telles que son WWPN. Le déplacement d'une LIF ne nécessite pas de re-zonage de votre fabric FC ni la création de nouvelles sessions iSCSI entre les hôtes du cluster et l'interface cible. Vous pouvez déplacer les LIF SAN vers n'importe quel nœud du cluster, mais pas entre storage virtual machines (SVM).

Vous pouvez déplacer un LIF pour effectuer les opérations suivantes sans interruption de service :

* Remplacer une paire haute disponibilité d'un cluster par une paire haute disponibilité mise à niveau de manière transparente pour les hôtes accédant aux données LUN ou d'espace de noms
* Mettre à niveau une carte d'interface cible
* Transfert des ressources d'un serveur virtuel de stockage (SVM) d'un ensemble de nœuds d'un cluster vers un autre ensemble de nœuds du cluster


Vous ne pouvez pas déplacer une LIF SAN à l'aide de la  `network interface move` commande. Pour déplacer une LIF SAN, vous devez la mettre hors ligne, la déplacer vers un nouveau nœud ou port d'attache, puis la remettre en ligne. Parce qu'une LIF SAN doit être mise hors ligne avant d'être déplacée, le trafic hôte doit s'appuyer sur un logiciel de multipathing hôte pour fournir un accès aux données sans interruption à la LUN afin qu'il n'y ait aucune interruption d'E/S.

.Avant de commencer
Si le LIF est membre d'un port set, il faut que la LIF ait été supprimée du port set avant de pouvoir déplacer la LIF vers un autre nœud.

.Description de la tâche
Le nœud de destination et le port physique d'une LIF que vous souhaitez déplacer doivent se trouver sur la même structure FC ou sur un même réseau Ethernet. Si vous déplacez une LIF vers une autre structure qui n'a pas été correctement zonée ou si vous déplacez la LIF vers un réseau Ethernet qui n'a pas de connectivité entre l'initiateur iSCSI et la cible, la LUN sera inaccessible lorsque vous la remettez en ligne.

.Étapes
. Afficher le statut administratif et opérationnel de la LIF :
+
[source, cli]
----
network interface show -vserver <SVM_name>
----
+
Pour en savoir plus, `network interface show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["Référence de commande ONTAP"^].

. Modifiez le statut de la LIF en `down` (hors ligne) :
+
[source, cli]
----
network interface modify -vserver <SVM_name> -lif <LIF_name> -status-admin down
----
+
Pour en savoir plus, `network interface modify` consultez le link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html["Référence de commande ONTAP"^].

. Assigner le LIF à un nouveau nœud et port :
+
[source, cli]
----
network interface modify -vserver <SVM_name> -lif <LIF_name> -home-node <node_name> -home-port <port_name>
----
. Modifiez le statut de la LIF en `up` (en ligne) :
+
[source, cli]
----
network interface modify -vserver <SVM_name> -lif <LIF_name> -status-admin up
----
. Vérifiez les modifications :
+
[source, cli]
----
network interface show -vserver <SVM_name>
----

