---
permalink: san-admin/prerequisites-setup-luns-concept.html 
sidebar: sidebar 
keywords: prerequisites, setting up, luns 
summary: 'La configuration des LUN implique la création d"une LUN, la création d"un groupe initiateur et le mappage de celle-ci sur le groupe initiateur. Votre système doit respecter certaines conditions préalables avant de pouvoir configurer vos LUN.' 
---
= Configuration minimale requise
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La configuration des LUN implique la création d'une LUN, la création d'un groupe initiateur et le mappage de celle-ci sur le groupe initiateur. Votre système doit respecter certaines conditions préalables avant de pouvoir configurer vos LUN.

* La matrice d'interopérabilité doit répertorier votre configuration SAN prise en charge.
* Votre environnement SAN doit être conforme aux limites de configuration d'hôtes et de contrôleurs SAN spécifiées dans la https://["NetApp Hardware Universe"^] Pour votre version du logiciel ONTAP.
* Une version prise en charge des utilitaires hôtes doit être installée.
+
La documentation Host Utilities fournit des informations supplémentaires.

* Vous devez disposer de LIF SAN sur le nœud propriétaire et sur le partenaire HA du nœud propriétaire.


.Informations associées
https://["Matrice d'interopérabilité NetApp"^]

https://["Configuration de l'hôte SAN ONTAP"]

http://["Rapport technique de NetApp 4017 : meilleures pratiques liées au SAN Fibre Channel"]
