---
sidebar: sidebar 
permalink: san-admin/provision-storage.html 
keywords: netapp, ontap, san, provisioning, linux, servers, provision, storage, create lun, fc, iscsi, zone switches, scsi disk, iscsi 
summary: 'Créez des LUN pour fournir du stockage à votre hôte à l"aide du protocole SAN FC ou iSCSI. Les LUN apparaissent comme des disques pour votre hôte.' 
---
= Provisionnement du stockage SAN
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cette procédure crée de nouvelles LUN sur une machine virtuelle de stockage existante sur laquelle le protocole FC ou iSCSI est déjà configuré.

Si vous devez créer une nouvelle machine virtuelle de stockage et configurer le protocole FC ou iSCSI, reportez-vous à la section link:configure-svm-fc-task.html["Configuration d'un SVM pour FC"] ou link:configure-svm-iscsi-task.html["Configuration d'un SVM pour iSCSI"].

Si la licence FC n'est pas activée, les LIFs et les SVM semblent être en ligne, mais le statut opérationnel est arrêté.

Les LUN apparaissent sur votre hôte en tant que périphériques de disque.


NOTE: L'accès ALUA (Asymmetric Logical Unit Access) est toujours activé au cours de la création de LUN. Vous ne pouvez pas modifier le paramètre ALUA.

Vous devez utiliser un zoning unique pour toutes les LIFs FC du SVM pour héberger les initiateurs.

Depuis ONTAP 9.8, lorsque vous provisionnez le stockage, la QoS est activée par défaut. Vous pouvez désactiver QoS ou choisir une règle de QoS personnalisée lors du processus de provisionnement ou ultérieurement.

.Étapes
[role="tabbed-block"]
====
.System Manager
--
Créer des LUN pour fournir du stockage à un hôte SAN à l'aide du protocole FC ou iSCSI avec ONTAP System Manager (9.7 et versions ultérieures).

Pour effectuer cette tâche à l'aide de System Manager Classic (disponible avec les versions 9.7 et antérieures), reportez-vous à la section https://docs.netapp.com/us-en/ontap-system-manager-classic/iscsi-config-rhel/index.html["Configuration iSCSI pour Red Hat Enterprise Linux"^]

.Étapes
. Installez le approprié link:https://docs.netapp.com/us-en/ontap-sanhost/["Utilitaires d'hôte SAN"] sur votre hôte.
. Dans System Manager, cliquez sur *stockage > LUN*, puis sur *Ajouter*.
. Indiquez les informations requises pour la création de la LUN.
. Vous pouvez cliquer sur *plus d'options* pour effectuer l'une des opérations suivantes, selon votre version de ONTAP.
+
[cols="80,20"]
|===


| Option | Disponible à partir de 


 a| 
** Attribuez la politique de QoS aux LUN au lieu du volume parent
+
*** *Plus d'options > stockage et optimisation*
*** Sélectionnez *Performance Service Level*.
*** Pour appliquer la stratégie QoS à des LUN individuelles au lieu du volume entier, sélectionnez *appliquer ces seuils de performances à chaque LUN*.
+
Par défaut, des limites de performances sont appliquées au niveau du volume.




| ONTAP 9.10.1 


 a| 
** Créez un nouveau groupe initiateur à l'aide des groupes initiateurs existants
+
*** *Plus d'options > INFORMATIONS SUR L'HÔTE*
*** Sélectionnez *Nouveau groupe initiateur utilisant des groupes initiateurs* existants.
+

NOTE: Le type de système d'exploitation d'un groupe initiateur contenant d'autres groupes initiateurs ne peut pas être modifié après sa création.




| ONTAP 9.9.1 


 a| 
** Ajoutez une description à votre groupe initiateur ou à votre initiateur hôte
+
La description sert d'alias pour le groupe initiateur ou l'initiateur hôte.

+
*** *Plus d'options > INFORMATIONS SUR L'HÔTE*



| ONTAP 9.9.1 


 a| 
** Créez votre LUN sur un volume existant
+
Par défaut une nouvelle LUN est créée dans un nouveau volume.

+
*** *Plus d'options > Ajouter des LUN*
*** Sélectionnez *groupes de LUN connexes*.



| ONTAP 9.9.1 


 a| 
** Désactivez la QoS ou choisissez une règle de QoS personnalisée
+
*** *Plus d'options > stockage et optimisation*
*** Sélectionnez *Performance Service Level*.
+

NOTE: Dans ONTAP 9.9.1 et versions ultérieures, si vous sélectionnez une stratégie de QoS personnalisée, vous pouvez également sélectionner le placement manuel sur un niveau local spécifié.




| ONTAP 9.8 
|===


. Pour FC, désegmentation des commutateurs FC par WWPN. Utilisez une zone par initiateur et incluez tous les ports cibles dans chaque zone.
. Découvrez les LUN sur votre hôte
+
Pour VMware vSphere, utilisez Virtual Storage Console (VSC) pour détecter et initialiser vos LUN.

. Initialisez les LUN et, éventuellement, créez des systèmes de fichiers.
. Vérifiez que l'hôte peut écrire et lire les données sur la LUN.


--
.CLI
--
Créer des LUN afin de fournir le stockage d'un hôte SAN utilisant le protocole FC ou iSCSI avec l'interface de ligne de commande de ONTAP.

. Vérifiez que vous disposez d'une licence pour FC ou iSCSI.
+
[source, cli]
----
system license show
----
+
[listing]
----

Package           Type    Description           Expiration
 ----------------- ------- --------------------- --------------------
 Base              site    Cluster Base License  -
 NFS               site    NFS License           -
 CIFS              site    CIFS License          -
 iSCSI             site    iSCSI License         -
 FCP               site    FCP License           -
----
. Si vous ne disposez pas de licence pour FC ou iSCSI, utilisez le `license add` commande.
+
[source, cli]
----
license add -license-code <your_license_code>
----
. Activer votre service de protocole sur le SVM :
+
*Pour iSCSI:*

+
[source, cli]
----
vserver iscsi create -vserver <svm_name> -target-alias <svm_name>
----
+
*Pour FC:*

+
[source, cli]
----
vserver fcp create -vserver <svm_name> -status-admin up
----
. Créez deux LIF pour les SVM sur chaque nœud :
+
[source, cli]
----
network interface create -vserver <svm_name> -lif <lif_name> -role data -data-protocol <iscsi|fc> -home-node <node_name> -home-port <port_name> -address <ip_address> -netmask <netmask>
----
+
NetApp prend en charge au moins une LIF iSCSI ou FC par nœud pour chaque SVM assurant le service des données. Cependant, deux LIF par nœud sont nécessaires pour assurer la redondance. Pour iSCSI, il est recommandé de configurer au moins deux LIF par nœud dans des réseaux Ethernet distincts.

. Vérifiez que vos LIF ont été créées et que leur statut opérationnel est `online`:
+
[source, cli]
----
network interface show -vserver <svm_name> <lif_name>
----
. Création de vos LUN :
+
[source, cli]
----
lun create -vserver <svm_name> -volume <volume_name> -lun <lun_name> -size <lun_size> -ostype linux -space-reserve <enabled|disabled>
----
+
Le nom de LUN ne doit pas dépasser 255 caractères et ne peut pas contenir d'espaces.

+

NOTE: L'option NVFAIL est automatiquement activée lorsqu'une LUN est créée dans un volume.

. Création de vos igroups :
+
[source, cli]
----
igroup create -vserver <svm_name> -igroup <igroup_name> -protocol <fcp|iscsi|mixed> -ostype linux -initiator <initiator_name>
----
. Mappage de vos LUN sur des igroups :
+
[source, cli]
----
lun mapping create -vserver <svm_name> -volume <volume_name> -lun <lun_name> -igroup <igroup_name>
----
. Vérifiez que vos LUN sont configurées correctement :
+
[source, cli]
----
lun show -vserver <svm_name>
----
. En option, link:create-port-sets-binding-igroups-task.html["Créez un port défini et associez-le à un groupe initiateur"].
. Suivez les étapes de la documentation de votre hôte pour activer l'accès aux blocs sur vos hôtes spécifiques.
. Utilisez les utilitaires hôtes pour terminer le mappage FC ou iSCSI et détecter vos LUN sur l'hôte.


--
====
.Informations associées
* link:index.html["Présentation de L'administration SAN"]
* https://docs.netapp.com/us-en/ontap-sanhost/index.html["Configuration de l'hôte SAN ONTAP"]
* https://docs.netapp.com/us-en/ontap/san-admin/manage-san-initiators-task.html["Afficher et gérer les groupes initiateurs SAN dans System Manager"]
* https://www.netapp.com/pdf.html?item=/media/19680-tr-4017.pdf["Rapport technique de NetApp 4017 : meilleures pratiques liées au SAN Fibre Channel"^]

