---
permalink: san-admin/reasons-cloning-luns-concept.html 
sidebar: sidebar 
keywords: reasons, using, flexclone, luns 
summary: 'Vous pouvez utiliser des LUN FlexClone pour créer plusieurs copies en lecture/écriture d"une LUN.' 
---
= Motifs d'utilisation des LUN FlexClone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser des LUN FlexClone pour créer plusieurs copies en lecture/écriture d'une LUN.

Vous pouvez vouloir le faire pour les raisons suivantes :

* Vous devez créer une copie temporaire d'une LUN afin d'y effectuer des tests.
* Vous devez mettre une copie de vos données à la disposition d'autres utilisateurs sans pour autant avoir accès aux données de production.
* Vous souhaitez créer un clone de base de données pour les opérations de manipulation et de projection, tout en préservant les données d'origine sous une forme non modifiée.
* Vous souhaitez accéder à un sous-ensemble spécifique des données d'une LUN (un volume logique ou un système de fichiers spécifique dans un groupe de volumes, Ou un fichier spécifique ou un ensemble de fichiers dans un système de fichiers) et copiez-le dans la LUN d'origine, sans restaurer le reste des données de la LUN d'origine. Ce fonctionnement fonctionne sur les systèmes d'exploitation qui prennent en charge le montage simultané d'une LUN et d'un clone de la LUN. SnapDrive pour UNIX en est capable avec le `snap connect` commande.
* Vous avez besoin de plusieurs hôtes de démarrage SAN avec le même système d'exploitation.

