---
permalink: san-admin/remove-lif-from-portset-task.html 
sidebar: sidebar 
keywords: remove, san, lif, port, set 
summary: Si la LIF que vous souhaitez supprimer ou déplacer se trouve dans un port set, vous devez supprimer la LIF du port set avant de pouvoir supprimer ou déplacer la LIF. 
---
= Supprimer une LIF SAN d'un port set
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si la LIF que vous souhaitez supprimer ou déplacer se trouve dans un port set, vous devez supprimer la LIF du port set avant de pouvoir supprimer ou déplacer la LIF.

.Description de la tâche
Vous n'avez à effectuer l'étape 1 que si une LIF est dans le port set. Vous ne pouvez pas supprimer la dernière LIF d'un port défini si l'ensemble de ports est lié à un groupe initiateur. Sinon, vous pouvez commencer par l'étape 2 si plusieurs LIF se trouvent dans le port défini.

.Étapes
. Si un seul LIF est dans le port set, utilisez le `lun igroup unbind` commande permettant de dissocier le port défini sur le groupe initiateur.
+
[NOTE]
====
Lorsque vous annulez la liaison d'un groupe initiateur à un ensemble de ports, tous les initiateurs du groupe initiateur ont accès à toutes les LUN cibles mappées sur le groupe initiateur sur toutes les interfaces réseau.

====
+
`cluster1::>lun igroup unbind -vserver vs1 -igroup ig1`

. Utilisez le `lun portset remove` Commande de supprimer le LIF du port set.
+
`cluster1::> port set remove -vserver vs1 -portset ps1 -port-name lif1`


