---
permalink: san-admin/resolve-iscsi-error-messages-reference.html 
sidebar: sidebar 
keywords: resolve, iscsi, error messages, storage system 
summary: 'Il existe un certain nombre de messages d"erreur iSCSI courants que vous pouvez afficher avec la commande event log show. Vous devez savoir ce que signifient ces messages et ce que vous pouvez faire pour résoudre les problèmes qu"ils identifient.' 
---
= Résolution des messages d'erreur iSCSI sur le système de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher un certain nombre de messages d'erreur iSCSI courants avec le `event log show` commande. Vous devez savoir ce que signifient ces messages et ce que vous pouvez faire pour résoudre les problèmes qu'ils identifient.

Le tableau suivant contient les messages d'erreur les plus courants et des instructions pour les résoudre :

[cols="3*"]
|===
| Messagerie | Explication | Que faire 


 a| 
`ISCSI: network interface identifier disabled for use; incoming connection discarded`
 a| 
Le service iSCSI n'est pas activé sur l'interface.
 a| 
Vous pouvez utiliser le `iscsi interface enable` Pour activer le service iSCSI sur l'interface. Par exemple :

`iscsi interface enable -vserver vs1 -lif lif1`



 a| 
`ISCSI: Authentication failed for initiator nodename`
 a| 
CHAP n'est pas configuré correctement pour l'initiateur spécifié.
 a| 
Vous devez vérifier les paramètres CHAP ; vous ne pouvez pas utiliser le même nom d'utilisateur et mot de passe pour les paramètres entrant et sortant sur le système de stockage :

* Les identifiants entrants du système de stockage doivent correspondre aux informations d'identification sortantes de l'initiateur.
* Les identifiants sortants du système de stockage doivent correspondre aux informations d'identification entrantes de l'initiateur.


|===
Pour en savoir plus, `event log show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/event-log-show.html["Référence de commande ONTAP"^].
