---
permalink: san-admin/san-host-provisioning-concept.html 
sidebar: sidebar 
keywords: understand, san host, provisioning 
summary: 'Dans les environnements SAN, les systèmes de stockage sont des cibles qui disposent de périphériques de stockage cibles. Pour iSCSI et FC, les périphériques cibles de stockage sont appelés LUN (unités logiques). Pour NVMe (non-volatile Memory Express) sur Fibre Channel, les périphériques de stockage cibles sont appelés « namespaces ».' 
---
= Provisionnement DE SAN avec iSCSI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dans les environnements SAN, les systèmes de stockage sont des cibles qui disposent de périphériques de stockage cibles. Pour iSCSI et FC, les périphériques cibles de stockage sont appelés LUN (unités logiques). Pour NVMe (non-volatile Memory Express) sur Fibre Channel, les périphériques de stockage cibles sont appelés « namespaces ».

Vous configurez le stockage en créant des LUN pour iSCSI et FC, ou en créant des espaces de noms pour NVMe. Les LUN ou les espaces de noms sont ensuite accessibles par les hôtes via les réseaux de protocole Internet Small Computer Systems interface (iSCSI) ou Fibre Channel (FC).

Pour se connecter aux réseaux iSCSI, les hôtes peuvent utiliser des cartes réseau Ethernet (NIC) standard, des cartes TOE (TCP Offload Engine) avec des initiateurs logiciels, des adaptateurs réseau convergés (CNA) ou des adaptateurs de bus hôte iSCSI dédiés.

Pour la connexion aux réseaux FC, les hôtes nécessitent des HBA FC ou des CNA.

Les protocoles FC pris en charge sont les suivants :

* FC
* FCoE
* NVMe




== Noms et connexions réseau du nœud cible iSCSI

Les nœuds cibles iSCSI peuvent se connecter au réseau de plusieurs façons :

* Plus de interfaces Ethernet utilisent un logiciel intégré à ONTAP.
* Via plusieurs interfaces système, avec une interface utilisée pour iSCSI qui transmet également le trafic pour d'autres protocoles, tels que les protocoles SMB et NFS.
* Utilisation d'un adaptateur cible unifié (UTA) ou d'un adaptateur réseau convergé (CNA).


Chaque nœud iSCSI doit avoir un nom de nœud.

Les deux formats, ou les indicateurs de type, pour les noms de nœud iSCSI sont _iqn_ et _eui_. La cible iSCSI du SVM utilise toujours l'indicateur de type iqn. L'initiateur peut utiliser l'indicateur de type iqn ou eui.



== Nom de nœud du système de stockage

Chaque SVM exécutant iSCSI possède un nom de nœud par défaut basé sur un nom de domaine inverse et un numéro de codage unique.

Le nom du nœud est affiché au format suivant :

iqn.1992-08.com.netapp:sn.`_unique-encoding-number_`

L'exemple suivant montre le nom de nœud par défaut d'un système de stockage avec un numéro d'encodage unique :

iqn.1992-08.com.netapp:sn.812921059e6c11e097b3123478563412:vs.6



== Port TCP pour iSCSI

Le protocole iSCSI est configuré dans ONTAP pour utiliser le port TCP numéro 3260.

ONTAP ne prend pas en charge la modification du numéro de port pour iSCSI. Le numéro de port 3260 est enregistré dans le cadre de la spécification iSCSI et ne peut être utilisé par aucune autre application ou service.

https://docs.netapp.com/us-en/ontap-sanhost/["Documentation NetApp : configuration de l'hôte SAN ONTAP"]
