---
permalink: san-admin/selective-lun-map-concept.html 
sidebar: sidebar 
keywords: select, lun, map 
summary: 'Le mappage de LUN sélectif (SLM) réduit le nombre de chemins entre l"hôte et la LUN. Avec SLM, lorsqu"un nouveau mappage de LUN est créé, le LUN est accessible uniquement via des chemins sur le nœud propriétaire de la LUN et son partenaire HA.' 
---
= Présentation du mappage de LUN sélectif
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le mappage de LUN sélectif (SLM) réduit le nombre de chemins entre l'hôte et la LUN. Avec SLM, lorsqu'un nouveau mappage de LUN est créé, le LUN est accessible uniquement via des chemins sur le nœud propriétaire de la LUN et son partenaire HA.

SLM permet de gérer un groupe initiateur unique par hôte et prend également en charge les opérations de déplacement de LUN sans interruption qui ne nécessitent pas de manipulation de l'ensemble de ports ou de remappage des LUN.

Les ensembles de ports peuvent être utilisés avec SLM comme dans les versions précédentes de ONTAP pour restreindre davantage l'accès de certaines cibles à certains initiateurs. Lors de l'utilisation de SLM avec des ensembles de ports, les LUN sont accessibles sur l'ensemble des LIF du portset sur le nœud propriétaire de la LUN et sur le partenaire HA de ce nœud.

SLM est activé par défaut sur tous les nouveaux mappages de LUN.
