---
permalink: san-admin/simplified-host-management-snapcenter-concept.html 
sidebar: sidebar 
keywords: snapcenter, host management, simplified 
summary: Le logiciel SnapCenter permet de simplifier certaines des tâches de gestion et de protection des données associées aux solutions de stockage iSCSI et FC. SnapCenter est un package de gestion facultatif pour les hôtes Windows et UNIX. 
---
= Gestion simplifiée de l'hôte avec SnapCenter
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le logiciel SnapCenter permet de simplifier certaines des tâches de gestion et de protection des données associées aux solutions de stockage iSCSI et FC. SnapCenter est un package de gestion facultatif pour les hôtes Windows et UNIX.

Le logiciel SnapCenter peut être utilisé pour créer facilement des disques virtuels à partir de pools de stockage qui peuvent être distribués sur plusieurs systèmes de stockage, ainsi que pour automatiser des tâches de provisionnement du stockage et simplifier le processus de création de copies Snapshot et de clones à partir de copies Snapshot cohérentes avec les données hôtes.

Consultez la documentation des produits NetApp pour plus d'informations sur https://docs.netapp.com/us-en/snapcenter/index.html["SnapCenter"].
