---
permalink: smb-config/assess-networking-requirements-task.html 
sidebar: sidebar 
keywords: provide, smb, storage, client, verify, network, configure, provision, requirement, assess, assess networking requirements 
summary: Avant de fournir un stockage SMB aux clients, vous devez vérifier que la mise en réseau est correctement configurée pour répondre aux exigences de provisionnement SMB. 
---
= Évaluer les exigences de mise en réseau
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de fournir un stockage SMB aux clients, vous devez vérifier que la mise en réseau est correctement configurée pour répondre aux exigences de provisionnement SMB.

Les objets de réseau de cluster suivants doivent être configurés :

* Ports physiques et logiques
* Les domaines de diffusion
* Sous-réseaux (le cas échéant)
* IPspaces (selon les besoins, en plus de l'IPspace par défaut)
* Failover Groups (si nécessaire, en plus du groupe de basculement par défaut pour chaque broadcast domain)
* Pare-feu externes


.Étapes
. Afficher les ports physiques et virtuels disponibles : `network port show`
+
** Dans la mesure du possible, vous devez utiliser le port avec la vitesse la plus élevée pour le réseau de données.
** Tous les composants du réseau de données doivent avoir le même paramètre MTU pour optimiser les performances.


. Si vous prévoyez d'utiliser un nom de sous-réseau pour allouer la valeur de l'adresse IP et du masque de réseau à une LIF, vérifiez que le sous-réseau existe et dispose des adresses suffisantes : `network subnet show`
+
Les sous-réseaux contiennent un pool d'adresses IP qui appartiennent au même sous-réseau de couche 3. Les sous-réseaux sont créés à l'aide du `network subnet create` commande.

. Affichez les IPspaces disponibles : `network ipspace show`
+
Vous pouvez utiliser l'IPspace par défaut ou un IPspace personnalisé.

. Si vous souhaitez utiliser des adresses IPv6, vérifiez que l'IPv6 est activé sur le cluster : `network options ipv6 show`
+
Si nécessaire, vous pouvez activer IPv6 en utilisant le `network options ipv6 modify` commande.


