---
permalink: smb-config/create-qtree-task.html 
sidebar: sidebar 
keywords: create, qtree, contain, data, specify, properties, property, volume, command, create a qtree 
summary: 'Vous pouvez créer un qtree pour contenir vos données et spécifier ses propriétés à l"aide de la commande volume qtree create.' 
---
= Création de qtrees ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer un qtree pour contenir vos données et spécifier ses propriétés en utilisant le `volume qtree create` commande.

.Avant de commencer
* La SVM et le volume qui contiendra le nouveau qtree doivent déjà exister.
* Le style de sécurité du SVM doit être NTFS et SMB doit être configuré et en cours d'exécution.


.Étapes
. Créer le qtree : `volume qtree create -vserver vserver_name { -volume volume_name -qtree qtree_name | -qtree-path qtree path } -security-style ntfs`
+
Vous pouvez spécifier le volume et qtree en tant qu'arguments distincts ou spécifier l'argument du chemin qtree au format `/vol/volume_name/_qtree_name`.

. Vérifier que le qtree a été créé avec le chemin de jonction souhaité : `volume qtree show -vserver vserver_name { -volume volume_name -qtree qtree_name | -qtree-path qtree path }`


.Exemple
L'exemple suivant crée un qtree nommé qt01 situé sur le SVM vs1.example.com qui dispose d'un chemin de jonction `/vol/data1`:

[listing]
----
cluster1::> volume qtree create -vserver vs1.example.com -qtree-path /vol/data1/qt01 -security-style ntfs
[Job 1642] Job succeeded: Successful

cluster1::> volume qtree show -vserver vs1.example.com -qtree-path /vol/data1/qt01

                      Vserver Name: vs1.example.com
                       Volume Name: data1
                        Qtree Name: qt01
  Actual (Non-Junction) Qtree Path: /vol/data1/qt01
                    Security Style: ntfs
                       Oplock Mode: enable
                  Unix Permissions: ---rwxr-xr-x
                          Qtree Id: 2
                      Qtree Status: normal
                     Export Policy: default
        Is Export Policy Inherited: true
----