---
permalink: smb-config/map-dns-server-task.html 
sidebar: sidebar 
keywords: site, dns, server, entry, point, smb, name, netbios, alias, ip, address, lif, windows, map the smb server on the dns server 
summary: 'Le serveur DNS de votre site doit avoir une entrée pointant le nom du serveur SMB, et tout alias NetBIOS, vers l"adresse IP de la LIF de données afin que les utilisateurs Windows puissent mapper un lecteur au nom du serveur SMB.' 
---
= Mappez le serveur SMB sur le serveur DNS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le serveur DNS de votre site doit avoir une entrée pointant sur le nom du serveur SMB, et tous les alias NetBIOS, à l'adresse IP de la LIF de données afin que les utilisateurs Windows puissent mapper un disque au nom du serveur SMB.

.Avant de commencer
Vous devez avoir un accès administratif au serveur DNS de votre site. Si vous ne disposez pas d'un accès administratif, vous devez demander à l'administrateur DNS d'effectuer cette tâche.

.Description de la tâche
Si vous utilisez des alias NetBIOS pour le nom du serveur SMB, il est recommandé de créer des points d'entrée de serveur DNS pour chaque alias.

.Étapes
. Connectez-vous au serveur DNS.
. Créer des entrées de recherche de type a - Address record (enregistrement d'adresse A) et inverse (PTR - enregistrement du pointeur) pour mapper le nom du serveur SMB à l'adresse IP de la LIF de données.
. Si vous utilisez des alias NetBIOS, créez une entrée de recherche alias nom canonique (enregistrement de ressource CNAME) pour mapper chaque alias à l'adresse IP de la LIF de données du serveur SMB.


.Résultats
Une fois le mappage propagé sur le réseau, les utilisateurs Windows peuvent mapper un lecteur au nom du serveur SMB ou à ses alias NetBIOS.
