---
permalink: smb-config/verify-client-access-task.html 
sidebar: sidebar 
keywords: verify, configure, smb, correct, access, writing, write, data, share, server, name, netbios, alias, verify smb client access 
summary: 'Vérifiez que SMB est correctement configuré en accédant au partage et en écrivant les données. Vous devez tester l"accès à l"aide du nom du serveur SMB et de tout alias NetBIOS.' 
---
= Vérifiez l'accès du client SMB ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vérifiez que SMB est correctement configuré en accédant au partage et en écrivant les données. Vous devez tester l'accès à l'aide du nom du serveur SMB et de tout alias NetBIOS.

.Étapes
. Connectez-vous à un client Windows.
. Testez l'accès à l'aide du nom du serveur SMB :
+
.. Dans l'Explorateur Windows, mappez un lecteur sur le partage au format suivant : `\⁠\\SMB_Server_Name\Share_Name`
+
Si le mappage ne réussit pas, il est possible que le mappage DNS ne se soit pas encore propagé sur l'ensemble du réseau. Vous devez tester l'accès par la suite à l'aide du nom de serveur SMB.

+
Si le serveur SMB est nommé vs1.example.com et que le partage est nommé SHARE1, vous devez entrer ce qui suit : `\⁠\vs0.example.com\SHARE1`

.. Sur le lecteur nouvellement créé, créez un fichier test, puis supprimez le fichier.


+
Vous avez vérifié l'accès en écriture au partage à l'aide du nom du serveur SMB.

. Répétez l'étape 2 pour tous les alias NetBIOS.

