---
permalink: smb-config/where-provision-storage-capacity-task.html 
sidebar: sidebar 
keywords: create, smb, volume, qtree, exist, configuration, svm, decision, workflow, decide where to provision new SMB storage capacity 
summary: Avant de créer un nouveau volume SMB ou qtree, vous devez décider de le placer dans un SVM nouveau ou existant, et de la configuration requise par la SVM. Cette décision détermine votre flux de travail. 
---
= Choisissez où provisionner la capacité de stockage SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de créer un nouveau volume SMB ou qtree, vous devez décider de le placer dans un SVM nouveau ou existant, et de la configuration requise par la SVM. Cette décision détermine votre flux de travail.

.Choix
* Si vous souhaitez provisionner un volume ou qtree sur un nouveau SVM, ou sur un SVM existant sur lequel SMB est activé mais non configuré, suivez les étapes des sections « Configuration de l'accès SMB à un SVM » et « Ajout de capacité de stockage à un SVM SMB ».
+
xref:configure-access-svm-task.adoc[Configuration de l'accès SMB à un SVM]

+
xref:configure-client-access-shared-storage-concept.adoc[Configuration de l'accès client SMB au stockage partagé]

+
Vous pouvez choisir de créer un nouveau SVM si l'un des cas suivants est vrai :

+
** Vous activez SMB sur un cluster pour la première fois.
** Un cluster contient des SVM existants dans lequel vous ne souhaitez pas activer la prise en charge SMB.
** Au sein d'un cluster, un ou plusieurs SVM compatibles SMB doivent être connectés :
+
*** Vers une autre forêt ou groupe de travail Active Directory.
*** Vers un serveur SMB dans un espace de noms isolé (scénario de colocation). Vous devez également choisir cette option pour provisionner le stockage sur un SVM existant pour lequel SMB est activé, mais pas configuré. Ce peut être le cas si vous avez créé le SVM pour l'accès SAN ou si aucun protocole n'a été activé au moment de la création de la SVM.




+
Après l'activation de SMB sur le SVM, procéder au provisionnement d'un volume ou qtree.

* Si vous souhaitez provisionner un volume ou qtree sur un SVM existant entièrement configuré pour l'accès SMB, suivez les étapes de la section « Ajout de capacité de stockage à un SVM compatible SMB ».
+
xref:configure-client-access-shared-storage-concept.adoc[Configuration de l'accès client SMB au stockage partagé]


