---
permalink: disks-aggregates/add-local-tier-overview-task.html 
sidebar: sidebar 
keywords: local tier, aggregate, add, create 
summary: 'Pour ajouter un niveau local (créer un agrégat), il faut suivre un workflow spécifique.' 
---
= Ajout d'un niveau local (création d'un agrégat)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour ajouter un niveau local (créer un agrégat), il faut suivre un workflow spécifique.

Déterminez le nombre de disques ou de partitions de disque requis pour le niveau local et choisissez la méthode à utiliser pour créer le niveau local. Vous pouvez ajouter des niveaux locaux automatiquement en laissant à ONTAP l'attribuer ou vous pouvez spécifier manuellement la configuration.

* link:aggregate-expansion-workflow-concept.html["Flux de production pour l'ajout d'un niveau local (agrégat)"]
* link:determine-number-disks-partitions-concept.html["Détermination du nombre de disques ou de partitions de disque requis pour un niveau local (agrégat)"]
* link:decide-aggregate-creation-method-concept.html["Choisissez la méthode de création du niveau local (agrégat) à utiliser"]
* link:create-aggregates-auto-provision-task.html["Ajout automatique de niveaux locaux (agrégats)"]
* link:create-aggregates-manual-task.html["Ajoutez manuellement des niveaux locaux (agrégats)"]

