---
permalink: disks-aggregates/assign-aggregates-svms-task.html 
sidebar: sidebar 
keywords: assign, aggregate, local tier, svm, storage vm, vserver 
summary: 'Si vous attribuez un ou plusieurs niveaux locaux (agrégats) à une machine virtuelle de stockage (Storage VM ou SVM, anciennement appelée Vserver), vous pouvez uniquement utiliser les niveaux locaux pour contenir des volumes pour ce SVM. A' 
---
= Assignation de niveaux locaux (agrégats) à des VM de stockage (SVM)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous attribuez un ou plusieurs niveaux locaux (agrégats) à une machine virtuelle de stockage (Storage VM ou SVM, anciennement appelée Vserver), vous pouvez uniquement utiliser les niveaux locaux pour contenir des volumes pour cette machine virtuelle de stockage (SVM).

La machine virtuelle de stockage et les niveaux locaux que vous souhaitez attribuer à cette machine virtuelle de stockage doivent déjà exister.

En attribuant des niveaux locaux à vos VM de stockage, il est important d'isoler les VM de stockage les uns des autres. C'est particulièrement important dans un environnement en colocation.

.Étapes
. Vérifier la liste des niveaux locaux (agrégats) déjà affectés à la SVM :
+
`vserver show -fields aggr-list`

+
Les agrégats actuellement affectés au SVM sont affichés. Si aucun agrégat n'est attribué, "`-`" s'affiche.

. Ajoutez ou supprimez des agrégats affectés, selon vos besoins :
+
|===


| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Attribuez des agrégats supplémentaires
 a| 
`vserver add-aggregates`



 a| 
Annuler l'attribution des agrégats
 a| 
`vserver remove-aggregates`

|===
+
Les agrégats répertoriés sont affectés ou supprimés du SVM. Si le SVM possède déjà des volumes qui utilisent un agrégat qui n'est pas affecté à la SVM, un message d'avertissement est affiché, mais la commande se termine avec succès. Tous les agrégats qui ont déjà été affectés au SVM et qui n'ont pas été nommés dans la commande ne sont pas affectés.



Dans l'exemple suivant, les agrégats aggr1 et aggr2 sont affectés à SVM svm1 :

`vserver add-aggregates -vserver svm1 -aggregates aggr1,aggr2`
