---
permalink: disks-aggregates/commands-display-storage-shelves-reference.html 
sidebar: sidebar 
keywords: commands, display, information, storage, shelves 
summary: 'Utilisez la commande Storage shelf show pour afficher les informations de configuration et d"erreur de vos tiroirs disques.' 
---
= Commandes ONTAP pour l'affichage des informations sur les tiroirs de stockage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous utilisez le `storage shelf show` commande permettant d'afficher les informations de configuration et d'erreur de vos tiroirs disques.

|===
| Si vous voulez afficher... | Utilisez cette commande... 


 a| 
Informations générales sur la configuration des tiroirs et l'état du matériel
 a| 
`storage shelf show`



 a| 
Informations détaillées pour un tiroir spécifique, y compris l'ID de la pile
 a| 
`storage shelf show -shelf`



 a| 
Non résolu, exploitables par le client, erreurs par tiroir
 a| 
`storage shelf show -errors`



 a| 
Informations sur les baies
 a| 
`storage shelf show -bay`



 a| 
Informations sur la connectivité
 a| 
`storage shelf show -connectivity`



 a| 
Informations de refroidissement, y compris les capteurs de température et les ventilateurs
 a| 
`storage shelf show -cooling`



 a| 
Informations sur les modules d'E/S.
 a| 
`storage shelf show -module`



 a| 
Informations sur les ports
 a| 
`storage shelf show -port`



 a| 
Informations d'alimentation, y compris les blocs d'alimentation, les capteurs de courant et les capteurs de tension
 a| 
`storage shelf show -power`

|===
.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/storage-shelf-show.html["exposition d'étagères de rangement"^]

