---
permalink: disks-aggregates/convert-raid-dp-tec-task.html 
sidebar: sidebar 
keywords: convert, raid-dp, raid-tec, raid policy 
summary: Si vous souhaitez bénéficier de la protection supplémentaire de la triple parité, vous pouvez passer de RAID-DP à RAID-TEC. RAID-TEC est recommandé si la taille des disques utilisés dans votre niveau local est supérieure à 4 Tio. 
---
= Conversion de ONTAP RAID-DP en RAID-TEC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous souhaitez bénéficier de la protection supplémentaire de la triple parité, vous pouvez passer de RAID-DP à RAID-TEC. RAID-TEC est recommandé si la taille des disques utilisés dans votre niveau local est supérieure à 4 Tio.


NOTE: Avant ONTAP 9.7, System Manager utilise le terme _aggregate_ pour décrire un niveau _local_. Quelle que soit votre version de ONTAP, l'interface de ligne de commandes de ONTAP utilise le terme _aggregate_. Pour en savoir plus sur les niveaux locaux, voir link:../disks-aggregates/index.html["Disques et niveaux locaux"].

.Avant de commencer
Le niveau local à convertir doit avoir au moins sept disques.

.Description de la tâche
* Les niveaux locaux de disque dur peuvent être convertis de RAID-DP à RAID-TEC. Cela inclut les niveaux de disques durs dans les niveaux locaux de Flash Pool.
* Pour en savoir plus, `storage aggregate modify` consultez la link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-modify.html#parameter["Référence de commande ONTAP"^]


.Étapes
. Vérifiez que le niveau local est en ligne et qu'il dispose d'au moins six disques :
+
`storage aggregate show-status -aggregate _aggregate_name_`

. Conversion du niveau local de RAID-DP en RAID-TEC :
+
`storage aggregate modify -aggregate _aggregate_name_ -raidtype raid_tec`

. Vérifiez que la stratégie RAID de niveau local est RAID-TEC :
+
`storage aggregate show _aggregate_name_`


