---
permalink: disks-aggregates/decide-aggregate-creation-method-concept.html 
sidebar: sidebar 
keywords: decide, aggregate, create, add, method, local tier 
summary: 'Même si ONTAP fournit des recommandations sur les meilleures pratiques pour la création automatique (agrégats) de niveaux locaux (avec provisionnement automatique), vous devez déterminer si les configurations recommandées sont prises en charge dans votre environnement. Si ce n"est pas le cas, vous devez prendre des décisions sur la stratégie RAID et la configuration du disque, puis créer les niveaux locaux manuellement.' 
---
= Choisir la méthode à utiliser pour créer des tiers locaux (agrégats)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bien que ONTAP recommande l'ajout automatique de niveaux locaux (création d'agrégats avec provisionnement automatique) conformément aux meilleures pratiques, vous devez déterminer si les configurations recommandées sont prises en charge dans votre environnement. Si ce n'est pas le cas, vous devez prendre des décisions sur la stratégie RAID et la configuration du disque, puis créer les niveaux locaux manuellement.

Lors de la création automatique d'un niveau local, ONTAP analyse les disques de spare du cluster et génère une recommandation sur la façon d'utiliser les disques disponibles pour ajouter des tiers locaux conformément aux meilleures pratiques. ONTAP affiche les configurations recommandées. Vous pouvez accepter les recommandations ou ajouter les tiers locaux manuellement.



== Avant d'accepter les recommandations ONTAP

Si l'une des conditions de disque suivantes est présente, elles doivent être résolues avant d'accepter les recommandations de ONTAP :

* Disques manquants
* Fluctuation des numéros de disque disponibles
* Disques non assignés
* Pièces de rechange non remises à zéro
* Les disques sont soumis à un test de maintenance


Le `storage aggregate auto-provision` la page man contient plus d'informations sur ces exigences.



== Lorsque vous devez utiliser la méthode manuelle

Dans de nombreux cas, l'organisation recommandée du niveau local sera optimale pour votre environnement. Cependant, si votre cluster exécute ONTAP 9.1 ou une version antérieure, ou si votre environnement inclut les configurations suivantes, vous devez créer le niveau local à l'aide de la méthode manuelle.


NOTE: Depuis ONTAP 9.11.1, vous pouvez ajouter manuellement des niveaux locaux avec System Manager.

* Agrégats utilisant des LUN de baies tierces
* Disques virtuels avec Cloud Volumes ONTAP ou ONTAP Select
* Système MetroCluster
* SyncMirror
* Disques MSATA
* Niveaux Flash Pool (agrégats)
* Plusieurs types ou tailles de disques sont connectés au nœud




== Sélectionnez la méthode de création des niveaux locaux (agrégats).

Choisissez la méthode que vous souhaitez utiliser :

* link:create-aggregates-auto-provision-task.html["Ajoutez (créez) automatiquement des niveaux locaux (agrégats)"]
* link:create-aggregates-manual-task.html["Ajoutez (créez) des niveaux locaux (agrégats) manuellement"]


.Informations associées
http://["Commandes ONTAP 9"^]
