---
permalink: disks-aggregates/determine-space-usage-aggregate-concept.html 
sidebar: sidebar 
keywords: space, usage, aggregate, local tier, volume 
summary: 'Vous pouvez afficher la quantité d"espace utilisée par tous les volumes d"un ou plusieurs niveaux locaux afin de pouvoir prendre des mesures pour libérer de l"espace.' 
---
= Déterminez l'utilisation de l'espace dans un niveau local ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher la quantité d'espace utilisée par tous les volumes d'un ou plusieurs niveaux locaux afin de pouvoir prendre des mesures pour libérer de l'espace.


NOTE: Avant ONTAP 9.7, System Manager utilise le terme _aggregate_ pour décrire un niveau _local_. Quelle que soit votre version de ONTAP, l'interface de ligne de commandes de ONTAP utilise le terme _aggregate_. Pour en savoir plus sur les niveaux locaux, voir link:../disks-aggregates/index.html["Disques et niveaux locaux"].

WAFL réserve un pourcentage de l'espace disque total pour les métadonnées et les performances de niveau local. L'espace utilisé pour maintenir les volumes du niveau local sort de la réserve WAFL et ne peut pas être modifié.

Pour les tiers locaux de moins de 30 To, WAFL réserve 10 % de l'espace disque total pour les métadonnées et les performances au niveau du niveau local.

À partir de ONTAP 9.12.1, dans les tiers locaux de 30 To ou plus, la quantité d'espace disque réservé pour les métadonnées de niveau local et les performances sont réduites, ce qui se traduit par une augmentation de 5 % de l'espace utilisable dans les tiers locaux. La disponibilité de ces économies d'espace varie en fonction de votre plateforme et de votre version d'ONTAP.

[cols="30,30,40"]
|===
| Espace disque réservé par ONTAP dans les niveaux locaux de 30 To ou plus | S'applique aux plates-formes | Dans les versions ONTAP 


| 5 % | Toutes les plateformes AFF et FAS | ONTAP 9.14.1 et versions ultérieures 


| 5 % | Plateformes AFF et FAS500f | ONTAP 9.12.1 et versions ultérieures 


| 10 % | Toutes les plateformes | ONTAP 9.11.1 et versions ultérieures 
|===
Vous pouvez afficher l'utilisation de l'espace par tous les volumes d'un ou plusieurs niveaux locaux à l'aide de la `aggregate show-space` commande. Cela vous permet de voir quels volumes consomment le plus d'espace dans leurs niveaux locaux contenant, de sorte que vous pouvez prendre des mesures pour libérer de l'espace.

L'espace utilisé dans un niveau local est directement affecté par l'espace utilisé dans les volumes FlexVol qu'il contient. Les mesures que vous prenez pour augmenter l'espace dans un volume affectent également l'espace dans le niveau local.


NOTE: À partir de ONTAP 9.15.1, deux nouveaux compteurs de métadonnées sont disponibles. En plus des modifications apportées à plusieurs compteurs existants, vous pouvez obtenir une vue plus claire de la quantité de données utilisateur allouées. Voir link:../volumes/determine-space-usage-volume-aggregate-concept.html["Déterminez l'utilisation de l'espace dans un volume ou un niveau local"] pour plus d'informations.

Les lignes suivantes sont incluses dans le `aggregate show-space` sortie de la commande :

* *Empreintes de volume*
+
Total de toutes les empreintes de volume dans le niveau local. Il inclut l'intégralité de l'espace utilisé ou réservé par toutes les données et métadonnées de tous les volumes du niveau local contenant.

* *Métadonnées agrégées*
+
Total des métadonnées du système de fichiers requises par le niveau local, telles que les bitmaps d'allocation et les fichiers inode.

* *Réserve snapshot*
+
Quantité d'espace réservé pour les snapshots de niveau local, en fonction de la taille du volume. Elle est considérée comme un espace utilisé et n'est pas disponible pour le volume, les données de niveau local ou les métadonnées.

* *Réserve snapshot inutilisable*
+
Quantité d'espace initialement allouée pour la réserve de snapshots de niveau local non disponible pour les snapshots de niveau local car elle est utilisée par les volumes associés au niveau local. Peut se produire uniquement pour les niveaux locaux avec une réserve de snapshots de niveau local non nulle.

* *Total utilisé*
+
Somme de tout l'espace utilisé ou réservé au niveau local par les volumes, les métadonnées ou les snapshots.

* *Physique totale utilisée*
+
Quantité d'espace utilisée pour les données actuellement (au lieu d'être exclusivement réservée à une utilisation ultérieure). Inclut l'espace utilisé par les snapshots de niveau local.



L'exemple suivant montre la `aggregate show-space` sortie de la commande pour un niveau local dont la réserve Snapshot est de 5 %. Si la réserve d'instantanés était 0, la ligne ne s'affiche pas.

....
cluster1::> storage aggregate show-space

						Aggregate : wqa_gx106_aggr1

      Feature                                   Used      Used%
      --------------------------------    ----------     ------
      Volume Footprints                      101.0MB         0%
      Aggregate Metadata                       300KB         0%
      Snapshot Reserve                        5.98GB         5%

      Total Used                              6.07GB         5%
      Total Physical Used                    34.82KB         0%
....
.Informations associées
* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Space_Usage["Article de la base de connaissances : utilisation de l'espace"^]
* link:https://www.netapp.com/blog/free-up-storage-capacity-upgrade-ontap/["Libérez jusqu'à 5 % de capacité en passant à ONTAP 9.12.1"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-space.html["espace d'exposition de stockage agrégé"^]

