---
permalink: disks-aggregates/determine-space-usage-aggregate-concept.html 
sidebar: sidebar 
keywords: space, usage, aggregate, local tier, volume 
summary: 'Vous pouvez afficher la quantité d"espace utilisée par tous les volumes d"un ou plusieurs niveaux locaux (agrégats) afin de libérer de l"espace.' 
---
= Déterminer l'utilisation de l'espace au niveau local (agrégat)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher la quantité d'espace utilisée par tous les volumes d'un ou plusieurs niveaux locaux (agrégats) afin de libérer de l'espace.

WAFL réserve un pourcentage de l'espace disque total pour les métadonnées et les performances au niveau de l'agrégat.  L'espace utilisé pour la maintenance des volumes de l'agrégat vient de la réserve WAFL et ne peut pas être modifié.

Dans les agrégats de moins de 30 To, WAFL réserve 10 % de l'espace disque total pour les métadonnées et les performances au niveau de l'agrégat.

À partir de ONTAP 9.12.1, dans des agrégats de 30 To ou plus, la quantité d'espace disque réservé pour les métadonnées et les performances au niveau de l'agrégat diminue. L'espace utilisable des agrégats est donc 5 % plus important. La disponibilité de ces économies d'espace varie en fonction de votre plateforme et de votre version d'ONTAP.

[cols="30,30,40"]
|===
| Espace disque réservé par ONTAP dans les agrégats de 30 To ou plus | S'applique aux plates-formes | Dans les versions ONTAP 


| 5 % | Toutes les plateformes AFF et FAS | ONTAP 9.14.1 et versions ultérieures 


| 5 % | Plateformes AFF et FAS500f | ONTAP 9.12.1 et versions ultérieures 


| 10 % | Toutes les plateformes | ONTAP 9.11.1 et versions ultérieures 
|===
Vous pouvez afficher l'utilisation de l'espace par tous les volumes d'un ou plusieurs agrégats avec `aggregate show-space` commande. Cela vous permet de déterminer quels volumes consomment le plus d'espace de leurs agrégats contenant afin de pouvoir mettre en œuvre des actions pour libérer plus d'espace.

L'espace utilisé d'un agrégat est directement affecté par l'espace utilisé sur les volumes FlexVol qu'il contient. Les mesures que vous prenez pour augmenter l'espace d'un volume affectent également l'espace de l'agrégat.


NOTE: À partir de ONTAP 9.15.1, deux nouveaux compteurs de métadonnées sont disponibles. En plus des modifications apportées à plusieurs compteurs existants, vous pouvez obtenir une vue plus claire de la quantité de données utilisateur allouées. Voir link:../volumes/determine-space-usage-volume-aggregate-concept.html["Détermination de l'utilisation de l'espace dans un volume ou un agrégat"] pour en savoir plus.

Les lignes suivantes sont incluses dans le `aggregate show-space` sortie de la commande :

* *Empreintes de volume*
+
Total de l'ensemble des empreintes des volumes de l'agrégat. Il inclut tout l'espace utilisé ou réservé par toutes les données et métadonnées de tous les volumes de l'agrégat contenant.

* *Métadonnées agrégées*
+
L'ensemble des métadonnées du système de fichiers requises par l'agrégat, telles que les bitmaps d'allocation et les fichiers d'inodes.

* *Réserve snapshot*
+
Quantité d'espace réservé pour les copies Snapshot de l'agrégat, sur la base de la taille du volume. Elle est considérée comme un espace utilisé et n'est pas disponible pour le volume, l'agrégat des données ou des métadonnées.

* *Réserve snapshot inutilisable*
+
Quantité d'espace initialement allouée à la réserve Snapshot de l'agrégat non disponible pour les copies Snapshot de l'agrégat, car elle est utilisée par les volumes associés à l'agrégat. Ne peut avoir lieu que pour les agrégats avec une réserve Snapshot d'agrégat non nulle.

* *Total utilisé*
+
Somme de l'espace utilisé ou réservé dans l'agrégat par volumes, métadonnées ou copies Snapshot.

* *Physique totale utilisée*
+
Quantité d'espace utilisée pour les données actuellement (au lieu d'être exclusivement réservée à une utilisation ultérieure). Inclut l'espace utilisé par les copies Snapshot de l'agrégat.



L'exemple suivant montre le `aggregate show-space` Sortie de la commande d'un agrégat dont la réserve Snapshot est de 5 %. Si la réserve Snapshot était 0, la ligne ne s'affiche pas.

....
cluster1::> storage aggregate show-space

						Aggregate : wqa_gx106_aggr1

      Feature                                   Used      Used%
      --------------------------------    ----------     ------
      Volume Footprints                      101.0MB         0%
      Aggregate Metadata                       300KB         0%
      Snapshot Reserve                        5.98GB         5%

      Total Used                              6.07GB         5%
      Total Physical Used                    34.82KB         0%
....
.Informations associées
* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Space_Usage["Article de la base de connaissances : utilisation de l'espace"^]
* link:https://www.netapp.com/blog/free-up-storage-capacity-upgrade-ontap/["Libérez jusqu'à 5 % de capacité en passant à ONTAP 9.12.1"^]

