---
permalink: disks-aggregates/disk-partition-ownership-overview-concept.html 
sidebar: sidebar 
keywords: disk, partition, ownership, overview 
summary: Vous pouvez gérer la propriété des disques et des partitions. 
---
= Propriété du disque et de la partition
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


Vous pouvez gérer la propriété des disques et des partitions.

Vous pouvez effectuer les tâches suivantes :

* *link:display-partition-ownership-task.html["Afficher la propriété du disque et de la partition"]*
+
Vous pouvez afficher la propriété des disques pour déterminer quel nœud contrôle le stockage. Vous pouvez également afficher la propriété de la partition sur les systèmes qui utilisent des disques partagés.

* *link:manual-assign-ownership-partitioned-disks-task.html["Assignation manuelle de propriétaires de disques partitionnés"]*
+
Vous pouvez définir la propriété du disque de conteneur ou des partitions manuellement ou en utilisant l'affectation automatique, comme pour les disques non partitionnés.

* *link:configure-auto-assignment-disk-ownership-task.html["Configurez l'assignation automatique de la propriété de disque"]*
+
Vous pouvez configurer ONTAP de manière à attribuer automatiquement la propriété des disques en fonction de la pile, du tiroir ou de la baie d'un disque.

* *link:remove-failed-disk-task.html["Retirez un disque défectueux"]*
+
Un disque défectueux n'est plus considéré par ONTAP comme un disque utilisable, et vous pouvez immédiatement déconnecter le disque du shelf.

* *link:remove-ownership-disk-task.html["Supprimer la propriété d'un disque"]*
+
ONTAP écrit les informations de propriété du disque sur le disque. Avant de retirer un disque de spare ou son tiroir d'un nœud, vous devez supprimer ses informations de propriété de sorte qu'elles puissent être correctement intégrées à un autre nœud.


