---
permalink: disks-aggregates/disk-autoassignment-policy-concept.html 
sidebar: sidebar 
keywords: disk, auto-assign, spare, policy, automatic, assignment, disk ownership 
summary: 'L"assignation automatique des disques qui n"appartiennent pas est activée par défaut. Les assignations de propriété automatique de disque surviennent 10 minutes après l"initialisation du système et toutes les cinq minutes pendant le fonctionnement normal du système.' 
---
= À propos de l'assignation automatique de Disk Ownership
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'assignation automatique des disques qui n'appartiennent pas est activée par défaut. Les assignations de propriété automatique de disque surviennent 10 minutes après l'initialisation du système et toutes les cinq minutes pendant le fonctionnement normal du système.

Lorsque vous ajoutez de nouveaux disques à un système, par exemple lors du remplacement de disques défectueux, de la réponse à un message de disques de secours faible ou de l'ajout de capacité, la règle d'affectation automatique par défaut attribue la propriété du disque à un nœud comme disque de secours. Vous pouvez désactiver l'affectation automatique ou sélectionner une autre règle d'affectation automatique à l'aide du `storage disk option modify` commande.

La règle d'auto-assignation par défaut se base sur des caractéristiques spécifiques à la plate-forme, mais elle utilise l'une des méthodes suivantes pour assigner la propriété disque :

|===


| Méthode d'affectation | Effet sur les affectations de nœuds | Plateformes 


 a| 
baie
 a| 
Les baies à numéro pair sont attribuées au nœud A et aux baies à numéro impair au nœud B.
 a| 
Systèmes d'entrée de gamme configurés dans une configuration haute disponibilité avec un seul tiroir partagé.



 a| 
tiroir
 a| 
Tous les disques du tiroir sont affectés au nœud A.
 a| 
Systèmes d'entrée de gamme configurés en configuration haute disponibilité avec une seule pile de deux tiroirs ou plus et configurations MetroCluster avec une pile par nœud, deux ou plusieurs tiroirs.



 a| 
séparer la tablette
 a| 
Les disques du côté gauche du shelf sont affectés au nœud A et du côté droit au nœud B. Les tiroirs partiels des nouveaux systèmes sont expédiés depuis l'usine avec des disques remplis du bord du tiroir vers le centre.
 a| 
Systèmes AFF C190 et certaines configurations MetroCluster.



 a| 
pile
 a| 
Tous les disques de la pile sont affectés au nœud A.
 a| 
Systèmes d'entrée de gamme autonomes et toutes les autres configurations.

|===
Si la méthode d'affectation par défaut n'est pas souhaitable dans votre environnement, vous pouvez spécifier la méthode d'affectation de la baie, de la étagère ou de la pile à l'aide de l' `-autoassign-policy` paramètre au `storage disk option modify` commande. Notez les règles suivantes :

* Si vous essayez d'utiliser le `bay autoassign-policy` dans le cas d'une plate-forme non d'entrée de gamme, elle échouera.
* Il n'existe pas de règle non par défaut correspondante pour spécifier la méthode split-shelf.


Vous pouvez également gérer manuellement l'affectation des disques à l'aide du `storage disk assign` commande.

* Si vous désactivez l'assignation automatique, les nouveaux disques ne sont pas disponibles en tant que pièces de rechange tant qu'ils ne sont pas affectés à un nœud avec le `storage disk assign` commande.
* Si vous souhaitez attribuer automatiquement des disques et que vous disposez de plusieurs piles ou tiroirs qui doivent avoir un droit de propriété différent, un disque doit avoir été manuellement affecté à chaque pile ou tiroir afin que l'affectation automatique de la propriété fonctionne sur chaque pile ou tiroir.
* Si l'affectation automatique est activée et que vous affectez manuellement un lecteur à un nœud non spécifié dans la stratégie active, l'affectation automatique cesse de fonctionner et un message EMS s'affiche.


En savoir plus sur link:manual-assign-ownership-partitioned-disks-task.html["attribution manuelle de la propriété du disque"].

Vous pouvez afficher les paramètres d'affectation automatique actuels à l'aide du `storage disk option show` commande.
