---
permalink: disks-aggregates/fast-zeroing-drives-concept.html 
sidebar: sidebar 
keywords: fast, zero, drives 
summary: Sur les systèmes récemment installés avec ONTAP 9.4 ou version ultérieure et les systèmes réinitialisés avec ONTAP 9.4 ou version ultérieure, _FAST remise à zéro_ est utilisé pour zéro disque. 
---
= Remise à zéro rapide des disques
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sur les systèmes récemment installés avec ONTAP 9.4 ou version ultérieure et les systèmes réinitialisés avec ONTAP 9.4 ou version ultérieure, _FAST remise à zéro_ est utilisé pour zéro disque.

Avec _FAST remise à zéro_, les entraînements sont remis à zéro en secondes. Cette opération est effectuée automatiquement avant le provisionnement et réduit considérablement le temps nécessaire pour initialiser le système, créer des agrégats ou développer des agrégats lors de l'ajout de disques de rechange.

_Fast Rremise à zéro_ est pris en charge à la fois sur les disques SSD et les disques durs.


NOTE: _Fast remise à zéro_ n'est pas pris en charge sur les systèmes mis à niveau à partir de ONTAP 9.3 ou version antérieure. ONTAP 9.4 ou version ultérieure doit être récemment installé ou le système doit être réinitialisé. Dans ONTAP 9.3 et versions antérieures, le processus de mise à zéro des disques est également automatique par ONTAP, mais ce processus prend plus de temps.

Si vous devez mettre manuellement à zéro un lecteur, vous pouvez utiliser l'une des méthodes suivantes. Dans ONTAP 9.4 et versions ultérieures, la remise à zéro manuelle d'un disque ne prend également que quelques secondes.

[role="tabbed-block"]
====
.Commande CLI
--
*Utilisez une commande CLI pour les disques rapides à zéro*

.Description de la tâche
Des privilèges d'administrateur sont requis pour utiliser cette commande.

.Étapes
. Entrez la commande CLI :
+
`storage disk zerospares`



--
.Options du menu de démarrage
--
*Sélectionnez les options du menu de démarrage sur disques rapides à zéro*

.Description de la tâche
* L'amélioration de la remise à zéro rapide ne prend pas en charge les systèmes mis à niveau depuis une version antérieure à ONTAP 9.4.
* Si un nœud du cluster contient un niveau local (agrégat) avec des disques à remise à zéro rapide, vous ne pouvez pas rétablir le cluster à la version ONTAP 9.2 ou antérieure.


.Étapes
. Dans le menu de démarrage, sélectionnez l'une des options suivantes :
+
** (4) nettoyer la configuration et initialiser tous les disques
** (9a) départition de tous les disques et suppression de leurs informations de propriété
** (9b) nettoyer la configuration et initialiser le nœud avec des disques entiers




--
====