---
permalink: disks-aggregates/flash-pool-aggregate-caching-policies-concept.html 
sidebar: sidebar 
keywords: cache, flash pool, policy, local tier, aggregate 
summary: Les règles de mise en cache sont appliquées aux volumes résidant dans les niveaux locaux Flash Pool. Vous devez comprendre le fonctionnement des stratégies de mise en cache avant de les modifier. 
---
= Règles de mise en cache de niveau local Flash Pool dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les règles de mise en cache des volumes d'un niveau local Flash Pool vous permettent de déployer la technologie Flash en tant que cache hautes performances pour vos jeux de données de travail, tout en utilisant des disques durs à moindre coût pour les données moins fréquemment utilisées. Si vous fournissons un cache à deux niveaux locaux Flash Pool ou plus, vous devez utiliser le partitionnement SSD Flash Pool pour partager les disques SSD entre les niveaux locaux de Flash Pool.

Les règles de mise en cache sont appliquées aux volumes résidant dans les niveaux locaux Flash Pool. Vous devez comprendre le fonctionnement des stratégies de mise en cache avant de les modifier.

Dans la plupart des cas, la règle de mise en cache par défaut de `auto` est la meilleure règle de mise en cache à utiliser. La règle de mise en cache ne doit être modifiée que si une autre règle améliore les performances de votre charge de travail. La configuration d'une règle de mise en cache incorrecte peut fortement dégrader les performances des volumes. La dégradation des performances peut augmenter progressivement au fil du temps.

Les règles de mise en cache combinent une règle de mise en cache de lecture et une règle de mise en cache d'écriture. Le nom de la règle concatène les noms de la règle de mise en cache des lectures et de la règle de mise en cache des écritures, séparés par un tiret. S'il n'y a pas de tiret dans le nom de la stratégie, la stratégie de mise en cache d'écriture est `none`, à l'exception de la `auto` stratégie.

Les règles de mise en cache de lecture optimisent l'utilisation pour les performances de lecture futures en plaçant des copies des données dans le cache en plus des données stockées sur des disques durs. Pour les règles de mise en cache de lecture qui insèrent des données dans le cache pour les opérations d'écriture, le cache fonctionne comme un _cache-transfert_.

Les données insérées dans le cache en utilisant la règle de mise en cache d'écriture n'existent que dans le cache ; il n'y a pas de copie dans les disques durs. Le cache Flash Pool est protégé par RAID. L'activation de la mise en cache d'écriture permet aux données d'effectuer immédiatement des opérations d'écriture à partir du cache, puis de reporter l'écriture des données sur les disques durs jusqu'à ce qu'elles deviennent hors du cache.

Si vous déplacez un volume d'un niveau local Flash Pool vers un niveau local à un niveau local à un niveau, sa stratégie de mise en cache est perdue ; si vous la redéplacez ultérieurement vers un niveau local Flash Pool, la stratégie de mise en cache par défaut se voit affecter la `auto` . Si vous déplacez un volume entre deux niveaux locaux Flash Pool, la règle de mise en cache est conservée.



== Modifier une règle de mise en cache

Vous pouvez utiliser l'interface de ligne de commandes pour modifier la règle de mise en cache d'un volume résidant sur un niveau local Flash Pool à l'aide de `-caching-policy` paramètre avec le `volume create` commande.

Lorsque vous créez un volume sur un niveau local Flash Pool, par défaut, la `auto` règle de mise en cache est attribuée au volume.
