---
permalink: disks-aggregates/manage-local-tiers-overview-concept.html 
sidebar: sidebar 
keywords: local tier, aggregate, prepare, add, create, disks, RAID, delete, manage local tier, manage aggregate 
summary: 'Vous pouvez ajouter des niveaux locaux, gérer leur utilisation et leur ajouter de la capacité (disques) via System Manager ou l"interface de ligne de commande.' 
---
= En savoir plus sur la gestion locale des niveaux ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser System Manager ou l'interface de ligne de commandes de ONTAP pour ajouter des tiers locaux, gérer leur utilisation et leur ajouter de la capacité (disques).


NOTE: Avant ONTAP 9.7, System Manager utilise le terme _aggregate_ pour décrire un niveau _local_. Quelle que soit votre version de ONTAP, l'interface de ligne de commandes de ONTAP utilise le terme _aggregate_. Pour en savoir plus sur les niveaux locaux, voir link:../disks-aggregates/index.html["Disques et niveaux locaux"].

Vous pouvez effectuer les tâches suivantes :

* link:add-local-tier-overview-task.html["Ajouter (créer) un niveau local"]
+
Pour ajouter un niveau local, suivez un flux de travail spécifique. Déterminez le nombre de disques ou de partitions de disque requis pour le niveau local et choisissez la méthode à utiliser pour créer le niveau local. Vous pouvez ajouter des niveaux locaux automatiquement en laissant à ONTAP l'attribuer ou vous pouvez spécifier manuellement la configuration.

* link:manage-use-local-tiers-overview-task.html["Gérer l'utilisation des niveaux locaux"]
+
Pour les niveaux locaux existants, vous pouvez les renommer, définir les coûts des supports ou déterminer leurs informations de disque et de groupe RAID. Vous pouvez modifier la configuration RAID d'un niveau local et attribuer des niveaux locaux aux SVM (Storage VM).
Vous pouvez modifier la configuration RAID d'un niveau local et attribuer des niveaux locaux aux SVM (Storage VM). Vous pouvez déterminer quels volumes résident sur un niveau local, ainsi que la quantité d'espace qu'ils utilisent sur un niveau local. Vous pouvez contrôler la quantité d'espace que les volumes peuvent utiliser. Vous pouvez transférer la propriété des niveaux locaux avec une paire haute disponibilité.  Vous pouvez également supprimer un niveau local.

* link:add-capacity-local-tier-overview-task.html["Ajout de capacité (disques) à un niveau local"]
+
En utilisant différentes méthodes, vous suivez un flux de travail spécifique pour ajouter de la capacité.
Vous pouvez ajouter des disques à un niveau local et ajouter des disques à un nœud ou à un tiroir.
Si nécessaire, vous pouvez corriger les partitions de rechange mal alignées.


