---
permalink: disks-aggregates/manual-assign-disks-ownership-prep-task.html 
sidebar: sidebar 
keywords: manual, assign, disk, ownership 
summary: 'Les disques doivent être au sein d"un nœud avant de pouvoir être utilisés dans un niveau local (agrégat). Si votre cluster n"est pas configuré pour utiliser l"affectation automatique de propriété de disque, vous devez attribuer la propriété manuellement. Vous ne pouvez pas réaffecter la propriété d"un disque en cours d"utilisation dans un niveau local.' 
---
= Attribuer manuellement la propriété des disques
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les disques doivent être au sein d'un nœud avant de pouvoir être utilisés dans un niveau local (agrégat).

Si votre cluster n'est pas configuré pour utiliser l'affectation automatique de propriété de disque, vous devez attribuer la propriété manuellement.

Vous ne pouvez pas réaffecter la propriété d'un disque en cours d'utilisation dans un niveau local.

.Étapes
. À l'aide de l'interface de ligne de commande, afficher tous les disques non possédés :
+
`storage disk show -container-type unassigned`

. Affectez chaque disque :
+
`storage disk assign -disk _disk_name_ -owner _owner_name_`

+
Vous pouvez utiliser le caractère générique pour attribuer plusieurs disques à la fois. Si vous réassignez un disque de réserve qui appartient déjà à un nœud différent, vous devez utiliser l'option "`-force`".


