---
permalink: disks-aggregates/modify-caching-policies-flash-pool-aggregates-task.html 
sidebar: sidebar 
keywords: modify, cache, policy, flash pool, aggregate, local tier 
summary: 'Vous devez modifier la stratégie de mise en cache d"un volume uniquement si une règle de mise en cache différente est censée améliorer les performances. Vous pouvez modifier la politique de mise en cache d"un volume sur un niveau local Flash Pool.' 
---
= Modifiez les règles de mise en cache des niveaux locaux Flash Pool dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez modifier la stratégie de mise en cache d'un volume uniquement si une règle de mise en cache différente est censée améliorer les performances. Vous pouvez modifier la politique de mise en cache d'un volume sur un niveau local Flash Pool.

.Avant de commencer
Vous devez déterminer si vous souhaitez modifier votre stratégie de mise en cache.

.Description de la tâche
Dans la plupart des cas, la règle de mise en cache par défaut de `auto` est la meilleure règle de mise en cache que vous pouvez utiliser. La règle de mise en cache ne doit être modifiée que si une autre règle améliore les performances de votre charge de travail. La configuration d'une règle de mise en cache incorrecte peut fortement dégrader les performances des volumes. La dégradation des performances peut augmenter progressivement au fil du temps. Vous devez être prudent lorsque vous modifiez les règles de mise en cache. Si vous rencontrez des problèmes de performances avec un volume pour lequel la stratégie de mise en cache a été modifiée, vous devez renvoyer la stratégie de mise en cache à `auto`.

.Étape
. Utiliser l'interface de ligne de commande pour modifier la règle de mise en cache du volume :
+
`volume modify -volume _volume_name_ -caching-policy _policy_name_`



.Exemple
L'exemple suivant modifie la politique de mise en cache d'un volume nommé `vol2` à la policy `none`:

`volume modify -volume vol2 -caching-policy none`
