---
permalink: disks-aggregates/sanitization-interrupted-concept.html 
sidebar: sidebar 
keywords: disks, interrupted disk sanitization, power outage, disk sanitization, power failure 
summary: 'Si le nettoyage des disques est interrompu par l"intervention de l"utilisateur ou un événement inattendu tel qu"une panne de courant, ONTAP prend les mesures nécessaires pour rétablir les disques aseptisés dans un état connu. Cependant, vous devez également prendre les mesures nécessaires pour que le processus de nettoyage puisse se terminer.' 
---
= Que se passe-t-il si le nettoyage du disque est interrompu
:allow-uri-read: 


[role="lead"]
Si le nettoyage des disques est interrompu par l'intervention de l'utilisateur ou un événement inattendu tel qu'une panne de courant, ONTAP prend les mesures nécessaires pour rétablir les disques aseptisés dans un état connu. Cependant, vous devez également prendre les mesures nécessaires pour que le processus de nettoyage puisse se terminer.

Le nettoyage de disque est une opération longue durée. Si le processus de nettoyage est interrompu par une panne de courant, une intervention panique du système ou manuelle, le processus de nettoyage doit être répété depuis le début. Le disque n'est pas désigné comme désinfecté.

Si la phase de formatage du nettoyage du disque est interrompue, ONTAP doit restaurer tout disque endommagé par l'interruption. Après un redémarrage du système et une fois toutes les heures, ONTAP vérifie s'il existe un disque cible de nettoyage qui n'a pas terminé la phase de formatage de son nettoyage. Si des disques de ce type sont trouvés, ONTAP les récupère. La méthode de restauration dépend du type de disque. Une fois qu'un disque a été restauré, vous pouvez réexécuter le processus de nettoyage sur ce disque. Pour les disques durs, vous pouvez utiliser le `-s` option permettant de spécifier que la phase de formatage n'est pas répétée à nouveau.
