---
permalink: disks-aggregates/sanitization-tips-concept.html 
sidebar: sidebar 
keywords: disk, disk sanitization, local tier, aggregate, sensitive data, sanitize 
summary: 'Si vous créez ou sauvegardez des tiers locaux (agrégats) afin de contenir des données qui peuvent être désinfectées, la procédure suivante permet de limiter le temps nécessaire à la suppression de vos données.' 
---
= Conseils pour créer et sauvegarder des tiers locaux (agrégats) contenant des données à désinfecter
:allow-uri-read: 


[role="lead"]
Si vous créez ou sauvegardez des tiers locaux (agrégats) afin de contenir des données qui peuvent être désinfectées, la procédure suivante permet de limiter le temps nécessaire à la suppression de vos données.

* Veillez à ce que vos tiers locaux contenant des données sensibles ne soient pas plus volumineux qu'ils ne le souhaitent.
+
Si elles sont plus importantes que nécessaire, le nettoyage nécessite plus de temps, d'espace disque et de bande passante.

* Lorsque vous sauvegardez des tiers locaux contenant des données sensibles, évitez de les sauvegarder sur un niveau local contenant également d'importantes quantités de données non sensibles.
+
Cette opération réduit les ressources requises pour déplacer des données non sensibles avant le nettoyage des données sensibles.


