---
permalink: disks-aggregates/sizing-raid-groups-concept.html 
sidebar: sidebar 
keywords: consideration, size, raid groups 
summary: 'Pour configurer une taille de groupe RAID optimale, il faut faire une reprise des facteurs. Vous devez déterminer les facteurs suivants : vitesse de reconstruction RAID, assurance contre le risque de perte de données due à une panne disque, optimisation des performances d"E/S et optimisation de l"espace de stockage. Ils sont les plus importants pour le niveau local (agrégat) que vous configurez.' 
---
= Considérations relatives au dimensionnement des groupes RAID ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour configurer une taille de groupe RAID optimale, il faut faire une reprise des facteurs. Vous devez décider des facteurs (vitesse de reconstruction RAID, assurance contre le risque de perte de données en raison de défaillances de disque, optimisation des performances d'E/S et optimisation de l'espace de stockage) qui sont les plus importants pour l'agrégat (niveau local) que vous configurez.

Lorsque vous créez de plus grands groupes RAID, vous optimisez l'espace disponible pour le stockage des données pour la même quantité de stockage utilisée pour la parité (également appelée « taxe de parité »). Par ailleurs, lorsqu'un disque tombe en panne au sein d'un groupe RAID plus important, le temps de reconstruction augmente et les performances sont affectées pendant une période plus longue. En outre, le fait d'avoir plus de disques dans un groupe RAID augmente la probabilité d'une défaillance de plusieurs disques au sein d'un même groupe RAID.



== Groupes RAID de disques durs ou de LUN de baies

Lors du dimensionnement de vos groupes RAID composés de disques durs ou de LUN de baies, veillez à respecter les consignes suivantes :

* Tous les RAID groupes d'un niveau local (agrégat) doivent avoir le même nombre de disques.
+
Même si le nombre de disques des différents groupes raid peut être inférieur ou égal à 50 % sur un niveau local, cela peut entraîner des goulets d'étranglement des performances dans certains cas, ce qui évite généralement d'avoir à utiliser cette méthode.

* La plage recommandée pour les disques des groupes RAID est comprise entre 12 et 20.
+
La fiabilité des disques hautes performances peut prendre en charge une taille de groupe RAID allant jusqu'à 28, si nécessaire.

* Si les deux premières directives sont conformes à plusieurs numéros de disques de groupe RAID, vous devez choisir le plus grand nombre de disques.




== Groupes RAID SSD dans les niveaux locaux de Flash Pool (agrégats)

La taille du groupe RAID SSD peut être différente de la taille du groupe RAID pour les groupes RAID de disques durs dans un niveau local Flash Pool (agrégat). En règle générale, vous devez vous assurer que vous ne disposez que d'un seul groupe SSD RAID pour un niveau local Flash Pool, afin de réduire le nombre de disques SSD requis pour la parité.



== Groupes RAID SSD dans niveaux locaux SSD (agrégats)

Lors du dimensionnement de vos groupes RAID composés de disques SSD, veillez à respecter les consignes suivantes :

* Tous les RAID groupes d'un niveau local (agrégat) doivent disposer d'un nombre similaire de disques.
+
Il n'est pas nécessaire que les groupes RAID soient de la même taille, mais ne doivent pas avoir de groupe RAID de moins de la moitié de la taille des autres groupes RAID du même niveau local lorsque cela est possible.

* Pour RAID-DP, la plage recommandée pour la taille de groupe RAID est comprise entre 20 et 28.

