---
permalink: disks-aggregates/update-disk-qualification-package-concept.html 
sidebar: sidebar 
keywords: update, desk, qualification, package 
summary: 'Le boîtier de qualification des disques (DQP) ajoute un support complet pour les disques nouvellement qualifiés. Avant de mettre à jour le firmware des disques ou d"ajouter de nouveaux types ou tailles de disques à un cluster, vous devez mettre à jour le DQP. Il est également recommandé de mettre à jour régulièrement le DQP, par exemple tous les trimestres ou tous les deux ans.' 
---
= Lorsque vous devez mettre à jour le progiciel de qualification des disques
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le boîtier de qualification des disques (DQP) ajoute un support complet pour les disques nouvellement qualifiés. Avant de mettre à jour le firmware des disques ou d'ajouter de nouveaux types ou tailles de disques à un cluster, vous devez mettre à jour le DQP. Il est également recommandé de mettre à jour régulièrement le DQP, par exemple tous les trimestres ou tous les deux ans.

Vous devez télécharger et installer le DQP dans les situations suivantes :

* Chaque fois que vous ajoutez un nouveau type ou une nouvelle taille de disque au nœud
+
Par exemple, si vous avez déjà des disques de 1 To et que vous ajoutez des disques de 2 To, vous devez vérifier la dernière mise à jour du DQP.

* Chaque fois que vous mettez à jour le micrologiciel du disque
* Chaque fois que les fichiers de firmware ou de DQP sont plus récents
* Chaque fois que vous effectuez une mise à niveau vers une nouvelle version de ONTAP.
+
Le DQP n'a pas été mis à jour dans le cadre d'une mise à niveau ONTAP.



.Informations associées
https://["Téléchargements NetApp : pack de qualification des disques"^]

https://["Téléchargements NetApp : firmware de disque"^]
