---
permalink: flexgroup/convert-flexvol-volume-task.html 
sidebar: sidebar 
keywords: convert, flexvol, volume, flexgroup, conversion, flex vol, flex group, transitioned, 
summary: 'Depuis ONTAP 9.7, vous pouvez effectuer une conversion sans déplacement des données d"un volume FlexVol en volume FlexGroup sans nécessiter de copie des données ni d"espace disque supplémentaire.' 
---
= Conversion d'un volume FlexVol en volume FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis ONTAP 9.7, vous pouvez effectuer une conversion sans déplacement des données d'un volume FlexVol en volume FlexGroup sans nécessiter de copie des données ni d'espace disque supplémentaire.

.Ce dont vous avez besoin
* Les volumes transférés peuvent être convertis en volumes FlexGroup à partir de ONTAP 9.8. Si vous convertissez un volume transféré en FlexGroup, consultez l'article de la base de connaissances link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_To_Convert_a_Transitioned_FlexVol_to_FlexGroup["Comment convertir un FlexVol converti en FlexGroup"] pour en savoir plus.
* Le volume FlexVol en cours de conversion doit être en ligne.
* Les opérations et les configurations du volume FlexVol doivent être compatibles avec le processus de conversion.
+
Un message d'erreur est généré si le volume FlexVol présente une incompatibilité et que la conversion de volume est abandonnée. Vous pouvez effectuer des actions correctives et recommencer la conversion.

* Si un volume FlexVol est très grand (par exemple, 80 à 100 To) et très plein (80 à 100 %), vous devez copier les données plutôt que de les convertir.
+
[NOTE]
====
La conversion d'un très grand volume FlexGroup entraîne l'saturation du composant du volume FlexGroup, ce qui engendre des problèmes de performances. Pour plus d'informations, reportez-vous à la section intitulée « quand ne pas créer de volume FlexGroup » dans le rapport technique TR link:https://www.netapp.com/media/12385-tr4571.pdf["Volumes FlexGroup - Guide des meilleures pratiques et de mise en œuvre"].

====


.Étapes
. Vérifiez que le volume FlexVol est en ligne : `volume show vol_name -volume-style-extended,state`
+
[listing]
----
cluster-1::> volume show my_volume -fields volume-style-extended,state
vserver volume    state  volume-style-extended
------- --------- ------ ---------------------
vs0     my_volume online flexvol
----
. Vérifiez si le volume FlexVol peut être converti sans problème :
+
.. Connectez-vous au mode de privilège avancé : `set -privilege advanced`
.. Vérifiez le processus de conversion : `volume conversion start -vserver vs1 -volume flexvol -check-only true`
+
Vous devez corriger toutes les erreurs avant de convertir le volume.

+
[NOTE]
====
Vous ne pouvez pas reconvertir un volume FlexGroup en volume FlexVol.

====


. Lancer la conversion : `volume conversion start -vserver svm_name -volume vol_name`
+
[listing]
----
cluster-1::*> volume conversion start -vserver vs0 -volume my_volume

Warning: Converting flexible volume "my_volume" in Vserver "vs0" to a FlexGroup
         will cause the state of all Snapshot copies from the volume to be set
         to "pre-conversion". Pre-conversion Snapshot copies cannot be
         restored.
Do you want to continue? {y|n}: y
[Job 57] Job succeeded: success
----
. Vérifiez que la conversion est réussie : `volume show vol_name -fields -volume-style-extended,state`
+
[listing]
----
cluster-1::*> volume show my_volume -fields volume-style-extended,state
vserver volume    state  volume-style-extended
------- --------- ------ ---------------------
vs0     my_volume online flexgroup
----


.Résultats
Le volume FlexVol est converti en volume FlexGroup à un seul membre.

.Une fois que vous avez terminé
Il est possible de développer le volume FlexGroup, si nécessaire.
