---
permalink: flexgroup/create-unified-data-protection-relationship-task.html 
sidebar: sidebar 
keywords: create, unified, data, protection, relationship, flexgroup, volume, snap shot, snapshot, policy, policies, mirrorandvault, mirror-vault, mirrorallsnapshot, back up, backup, snapvault, snap vault 
summary: 'Depuis ONTAP 9.3, vous pouvez créer et configurer des relations de protection des données unifiées SnapMirror pour configurer la reprise après incident et l"archivage sur le même volume de destination.' 
---
= Créez des relations de protection unifiée des données pour les volumes ONTAP FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis ONTAP 9.3, vous pouvez créer et configurer des relations de protection des données unifiées SnapMirror pour configurer la reprise après incident et l'archivage sur le même volume de destination.

.Avant de commencer
Il est à prendre en compte les considérations relatives à la création de relations unifiées de protection des données pour les volumes FlexGroup.

link:snapvault-backup-concept.html["Considérations relatives à la création d'une relation de sauvegarde SnapVault et d'une relation unifiée de protection des données pour les volumes FlexGroup"]

.Étapes
. Créer un volume FlexGroup de type destination `DP` Avec le même nombre de composants que celui du volume FlexGroup source :
+
.. Depuis le cluster source, déterminer le nombre de composants du volume FlexGroup source : `volume show -volume volume_name* -is-constituent true`
+
[listing]
----
cluster1::> volume show  -volume srcFG* -is-constituent true
Vserver   Volume         Aggregate    State      Type       Size  Available  Used%
--------- ------------   ------------ ---------- ---- ----------  ---------- -----
vss       srcFG          -            online     RW         400TB   172.86GB  56%
vss       srcFG__0001    Aggr_cmode   online     RW         25GB    10.86TB   56%
vss       srcFG__0002    aggr1        online     RW         25TB    10.86TB   56%
vss       srcFG__0003    Aggr_cmode   online     RW         25TB    10.72TB   57%
vss       srcFG__0004    aggr1        online     RW         25TB    10.73TB   57%
vss       srcFG__0005    Aggr_cmode   online     RW         25TB    10.67TB   57%
vss       srcFG__0006    aggr1        online     RW         25TB    10.64TB   57%
vss       srcFG__0007    Aggr_cmode   online     RW         25TB    10.63TB   57%
...
----
.. Depuis le cluster de destination, créez un volume FlexGroup de type destination `DP` Avec le même nombre de composants que celui du volume FlexGroup source.
+
[listing]
----
cluster2::> volume create -vserver vsd -aggr-list aggr1,aggr2 -aggr-list-multiplier 8 -size 400TB -type DP dstFG

Warning: The FlexGroup volume "dstFG" will be created with the following number of constituents of size 25TB: 16.
Do you want to continue? {y|n}: y
[Job 766] Job succeeded: Successful
----
.. Depuis le cluster de destination, vérifiez le nombre de composants du volume FlexGroup de destination : `volume show -volume volume_name* -is-constituent true`
+
[listing]
----
cluster2::> volume show  -volume dstFG* -is-constituent true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vsd       dstFG          -            online     RW         400TB   172.86GB  56%
vsd       dstFG__0001    Aggr_cmode   online     RW         25GB    10.86TB   56%
vsd       dstFG__0002    aggr1        online     RW         25TB    10.86TB   56%
vsd       dstFG__0003    Aggr_cmode   online     RW         25TB    10.72TB   57%
vsd       dstFG__0004    aggr1        online     RW         25TB    10.73TB   57%
vsd       dstFG__0005    Aggr_cmode   online     RW         25TB    10.67TB   57%
vsd       dstFG__0006    aggr1        online     RW         25TB    10.64TB   57%
vsd       dstFG__0007    Aggr_cmode   online     RW         25TB    10.63TB   57%
...
----


. Création d'un programme de travail : `job schedule cron create -name job_name -month month -dayofweek day_of_week -day day_of_month -hour hour -minute minute`
+
Pour le `-month`, `-dayofweek`, et `-hour` vous pouvez spécifier des options `all` pour exécuter le travail tous les mois, tous les jours de la semaine et toutes les heures, respectivement.

+
L'exemple suivant crée un programme de travail nommé `my_weekly` Le samedi à 3:00 :

+
[listing]
----
cluster1::> job schedule cron create -name my_weekly -dayofweek "Saturday" -hour 3 -minute 0
----
. Création d'une règle de type personnalisée `mirror-vault`, puis définissez une règle pour la stratégie de miroir et de coffre-fort:
+
.. Création d'une règle de type personnalisée `mirror-vault` pour la relation unifiée de protection des données : `snapmirror policy create -vserver svm_name -policy policy_name -type mirror-vault`
.. Définissez une règle pour la règle de mise en miroir et de coffre-fort qui détermine quels snapshots sont transférés au cours des opérations d'initialisation et de mise à jour : `snapmirror policy add-rule -vserver svm_name -policy policy_for_rule - snapmirror-label snapmirror-label -keep retention_count -schedule schedule`


+
Si vous ne spécifiez pas de stratégie personnalisée, le `MirrorAndVault` il est utilisé pour les relations de protection des données unifiées,

. Créer une relation unifiée de protection des données : `snapmirror create -source-path src_svm:src_flexgroup -destination-path dest_svm:dest_flexgroup -type XDP -schedule schedule_name -policy MirrorAndVault`
+
Dans ONTAP 9.4 et versions antérieures, si la politique n'est pas spécifiée avec le `snapmirror create` commande, le `MirrorAllSnapshots` la règle est utilisée par défaut. Dans ONTAP 9.5, si la politique n'est pas spécifiée avec le `snapmirror create` commande, le `MirrorAndVault` la règle est utilisée par défaut.

+
[listing]
----
cluster2::> snapmirror create -source-path vss:srcFG -destination-path vsd:dstFG -type XDP -schedule Daily -policy MirrorAndVault
----
. Depuis le cluster destination, initialiser la relation de protection des données unifiée en effectuant un transfert de base : `snapmirror initialize -destination-path dest_svm:dest_flexgroup`
+
[listing]
----
cluster2::> snapmirror initialize -destination-path vsd:dstFG
Operation is queued: snapmirror initialize of destination "vsd:dstFG".
----

