---
permalink: flexgroup/expand-snapmirror-relationship-task.html 
sidebar: sidebar 
keywords: expand, flexgroup, volume, snapmirror, relationship, snap mirror, flex group, manual, automatic, automatically, disaster 
summary: Depuis ONTAP 9.3, vous pouvez développer le volume FlexGroup source et le volume FlexGroup de destination dans une relation SnapMirror en ajoutant de nouveaux composants aux volumes. Vous pouvez développer les volumes de destination manuellement ou automatiquement. 
---
= Développement de volumes FlexGroup dans une relation SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis ONTAP 9.3, vous pouvez développer le volume FlexGroup source et le volume FlexGroup de destination dans une relation SnapMirror en ajoutant de nouveaux composants aux volumes. Vous pouvez développer les volumes de destination manuellement ou automatiquement.

.Description de la tâche
* Après l'extension, le nombre de composants dans le volume FlexGroup source et le volume FlexGroup de destination d'une relation SnapMirror doit correspondre.
+
Si le nombre de composants des volumes ne correspond pas, les transferts SnapMirror échouent.

* Vous ne devez pas effectuer d'opération SnapMirror lorsque le processus d'extension est en cours.
* Si un incident survient avant la fin du processus d'extension, vous devez interrompre la relation SnapMirror et attendre la réussite de l'opération.
+
[NOTE]
====
Vous devez interrompre la relation SnapMirror lorsque le processus d'extension est en cours uniquement en cas d'incident. Dans le cas d'un incident, cette opération peut prendre un certain temps. Vous devez attendre que l'opération de pause soit terminée avec succès avant d'effectuer une resynchronisation. En cas d'échec de l'opération de pause, vous devez recommencer l'opération. En cas d'échec de l'opération de pause, certains des nouveaux composants peuvent rester dans le volume FlexGroup de destination après l'opération de pause. Il est préférable de supprimer ces composants manuellement avant de poursuivre.

====

