---
permalink: flexgroup/index.html 
sidebar: sidebar 
keywords: decide, scalability, performance, flexgroup, volumes, scalability, performance 
summary: 'Vous pouvez configurer, gérer et protéger les volumes FlexGroup pour garantir l"évolutivité et les performances. Les volumes FlexGroup sont des volumes scale-out qui fournissent des performances élevées et une répartition automatique de la charge.' 
---
= Présentation de la gestion des volumes FlexGroup avec l'interface de ligne de commandes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer, gérer et protéger les volumes FlexGroup pour garantir l'évolutivité et les performances. Les volumes FlexGroup sont des volumes scale-out qui fournissent des performances élevées et une répartition automatique de la charge.

Vous pouvez configurer des volumes FlexGroup si les conditions suivantes sont vraies :

* Vous exécutez ONTAP 9.1 ou version ultérieure.
* Vous pouvez utiliser NFSv4.x, NFSv3, SMB 2.0 ou SMB 2.1.
* Vous souhaitez utiliser l'interface de ligne de commandes ONTAP et non System Manager, ni un outil de création de scripts automatisé.
+
Vous trouverez des informations détaillées sur la syntaxe des commandes dans l'aide de l'interface de ligne de commande et dans les pages de manuel ONTAP.

+
System Manager propose un sous-ensemble important de la fonctionnalité FlexGroup.

* Vous voulez appliquer les bonnes pratiques, pas explorer toutes les options disponibles.
* Vous disposez des privilèges d'administrateur de cluster et non des privilèges d'administrateur de SVM.



NOTE: FlexGroups remplace Infinite volumes, qui ne sont pas pris en charge dans les nouvelles versions de ONTAP.

Les informations conceptuelles sur les volumes FlexVol sont applicables aux volumes FlexGroup. Pour plus d'informations sur les volumes FlexVol et la technologie ONTAP, consultez la bibliothèque de référence ONTAP et les rapports techniques (TR).
