---
permalink: flexgroup/index.html 
sidebar: sidebar 
keywords: decide, scalability, performance, flexgroup, volumes, scalability, performance 
summary: 'Vous pouvez configurer, gérer et protéger les volumes FlexGroup pour garantir l"évolutivité et les performances. Les volumes FlexGroup sont des volumes scale-out qui fournissent des performances élevées et une répartition automatique de la charge.' 
---
= En savoir plus sur la gestion des volumes ONTAP FlexGroup avec l'interface de ligne de commande
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer, gérer et protéger les volumes FlexGroup pour garantir l'évolutivité et les performances. Les volumes FlexGroup sont des volumes scale-out qui fournissent des performances élevées et une répartition automatique de la charge.

Vous pouvez configurer des volumes FlexGroup si les conditions suivantes sont vraies :

* Vous voulez appliquer les bonnes pratiques, pas explorer toutes les options disponibles.
* Vous disposez des privilèges d'administrateur de cluster et non des privilèges d'administrateur de SVM.



NOTE: Depuis ONTAP 9.5, les volumes FlexGroup remplacent les Infinite volumes, qui ne sont pas pris en charge dans ONTAP 9.5 ou les versions ultérieures.

Voir la link:supported-unsupported-config-concept.html["Configurations prises en charge et non prises en charge pour les volumes FlexGroup"] pour en savoir plus.

.Informations associées
Les informations conceptuelles sur les volumes FlexVol sont applicables aux volumes FlexGroup. Pour plus d'informations sur les volumes FlexVol et la technologie ONTAP, consultez la bibliothèque de référence ONTAP et les rapports techniques (TR).
