---
permalink: flexgroup/move-constituents-task.html 
sidebar: sidebar 
keywords: constituents, flexgroup, volume, flex group, balancing, balance, traffic, free, space, aggregate, snapmirror, snap mirror, 
summary: 'Vous pouvez déplacer les composants d"un volume FlexGroup d"un agrégat à un autre afin d"équilibrer la charge lorsque certains composants connaissent plus le trafic. Le déplacement des composants permet également de libérer de l"espace sur un agrégat pour le redimensionnement des composants existants.' 
---
= Déplacer les composants d'un volume FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez déplacer les composants d'un volume FlexGroup d'un agrégat à un autre afin d'équilibrer la charge lorsque certains composants connaissent plus le trafic. Le déplacement des composants permet également de libérer de l'espace sur un agrégat pour le redimensionnement des composants existants.

.Ce dont vous avez besoin
Pour déplacer un composant de volume FlexGroup dans une relation SnapMirror, vous devez avoir initialisé la relation SnapMirror.

.Description de la tâche
Vous ne pouvez pas effectuer de déplacement de volumes pendant l'extension des composants du volume FlexGroup.

.Étapes
. Identifiez les composants du volume FlexGroup que vous souhaitez déplacer : `volume show -vserver svm_name -is-constituent *`
+
[listing]
----
cluster1::> volume show -vserver vs2 -is-constituent *
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vs2       fg1          -            online     RW        400TB    15.12TB   62%
vs2       fg1__0001    aggr1        online     RW         25TB     8.12MB   59%
vs2       fg1__0002    aggr2        online     RW         25TB     2.50TB   90%
...
----
. Identifiez un agrégat dans lequel vous pouvez déplacer le composant de volume FlexGroup : `volume move target-aggr show -vserver svm_name -volume vol_constituent_name`
+
L'espace disponible dans l'agrégat que vous sélectionnez doit être supérieur à la taille du composant de volume FlexGroup que vous déplacez.

+
[listing]
----
cluster1::> volume move target-aggr show -vserver vs2 -volume fg1_0002
Aggregate Name   Available Size   Storage Type
--------------   --------------   ------------
aggr2            467.9TB          hdd
node12a_aggr3    100.34TB         hdd
node12a_aggr2    100.36TB         hdd
node12a_aggr1    100.36TB         hdd
node12a_aggr4    100.36TB         hdd
5 entries were displayed.
----
. Vérifier que le composant de volume FlexGroup peut être déplacé vers l'agrégat prévu : `volume move start -vserver svm_name -volume vol_constituent_name -perform-validation-only true`
+
[listing]
----
cluster1::> volume move start -vserver vs2 -volume fg1_0002 -destination-aggregate node12a_aggr3 -perform-validation-only true
Validation succeeded.
----
. Déplacez le composant de volume FlexGroup : `volume move start -vserver svm_name -volume vol_constituent_name -destination-aggregate aggr_name [-allow-mixed-aggr-types {true|false}]`
+
L'opération de déplacement de volume s'exécute en arrière-plan.

+
Depuis ONTAP 9.5, il est possible de déplacer des composants de volumes FlexGroup d'un FabricPool vers un pool non Fabric, ou inversement en paramétrant le `-allow-mixed-aggr-types` paramètre à `true`. Par défaut, le `-allow-mixed-aggr-types` l'option est définie sur `false`.

+
[NOTE]
====
Vous ne pouvez pas utiliser `volume move` Commande pour activer le chiffrement sur les volumes FlexGroup.

====
+
[listing]
----
cluster1::> volume move start -vserver vs2 -volume fg1_002 -destination-aggregate node12a_aggr3
----
+
[NOTE]
====
Si l'opération de déplacement de volume échoue en raison d'une opération SnapMirror active, vous devez abandonner l'opération SnapMirror à l'aide du `snapmirror abort -h` commande. Dans certains cas, l'opération d'abandon de SnapMirror peut également échouer. Dans ce cas, vous devez abandonner l'opération de déplacement de volume et réessayer ultérieurement.

====
. Vérifiez l'état de l'opération de déplacement de volume : `volume move show -volume vol_constituent_name`
+
L'exemple suivant montre l'état d'un volume composant FlexGroup qui a terminé la phase de réplication et est en phase de mise en service de l'opération de déplacement de volume :

+
[listing]
----
cluster1::> volume move show -volume fg1_002
Vserver   Volume     State    Move Phase  Percent-Complete Time-To-Complete
--------- ---------- -------- ----------  ---------------- ----------------
vs2       fg1_002    healthy  cutover     -                -
----

