---
permalink: flexgroup/provision-automatically-task.html 
sidebar: sidebar 
keywords: provision, flexgroup, volume, automatic, create, flex group, aggregate, space 
summary: 'Lorsque vous créez un volume FlexGroup, vous pouvez choisir de faire provisionner le volume FlexGroup par ONTAP en sélectionnant automatiquement les tiers locaux (agrégats). Les niveaux locaux sont sélectionnés en fonction des meilleures pratiques pour des performances optimales.' 
---
= Provisionnez automatiquement un volume ONTAP FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous créez un volume FlexGroup, vous pouvez choisir de faire en sorte que ONTAP provisionne automatiquement le volume FlexGroup en sélectionnant les tiers locaux sous-jacents (agrégats). Les niveaux locaux sont sélectionnés en fonction des meilleures pratiques pour des performances et une capacité optimales.

.Avant de commencer
Chaque nœud du cluster doit avoir au moins un niveau local.

[NOTE]
====
Lors de la création d'un volume FlexGroup qui hiérarchise les données inactives, chaque nœud doit avoir au moins un Tier local avec FabricPool activé.

====
.Description de la tâche
Pour créer le volume FlexGroup, ONTAP sélectionne deux tiers locaux avec la plus grande quantité d'espace utilisable sur chaque nœud. Si deux tiers locaux ne sont pas disponibles, ONTAP sélectionne un Tier local par nœud pour créer le volume FlexGroup.

À partir de ONTAP 9.15.1, lorsque vous provisionnez automatiquement un volume FlexGroup, ONTAP utilise le placement équilibré (BP) pour choisir la disposition des niveaux locaux et des volumes membres FlexGroup (constituants). L'un des aspects de BP est la manière dont elle limite le sur-provisionnement des niveaux locaux lors de la création de volumes FlexGroup « aucun » garantis (à provisionnement fin). La taille du volume FlexGroup global est limitée par la quantité d'espace libre sur le Tier local, bien que la limite soit supérieure à celle des volumes FlexGroup garantis (à provisionnement lourd) par « volume ». La création d'un volume FlexGroup à l'aide d'API REST ou `auto-provision-as` de l'interface de ligne de commandes ONTAP peut entraîner l'échec du provisionnement en raison d'un espace insuffisant pour cause de cette limite. Vous pouvez éviter cela en créant des volumes FlexGroup plus petits ou en link:create-task.html["Création d'un volume FlexGroup et sélection manuelle des niveaux locaux"] utilisant le `aggr-list` paramètre.

.Étapes
. Provisionnez le volume FlexGroup :
+
`volume create -vserver svm_name -volume fg_vol_name –auto-provision-as flexgroup -size fg_size [–encrypt true] [-qos-policy-group qos_policy_group_name] [-support-tiering true] [-granular-data advanced]`

+
À partir de ONTAP 9.16.1, vous pouvez activer link:../enable-adv-capacity-flexgroup-task.html["équilibrage avancé de la capacité"] (`-granular-data advanced` dans l'interface de ligne de commandes) pour écrire des données sur plusieurs volumes de membres FlexGroup lorsque les fichiers dépassent 10 Go.

+
À partir de ONTAP 9.5, vous pouvez créer des volumes FlexGroup sur des niveaux locaux avec FabricPool activé. Pour provisionner automatiquement un volume FlexGroup sur des niveaux locaux avec FabricPool activé, vous devez définir le `-support-tiering` paramètre sur `true`. La garantie de volume doit toujours être définie sur `none` pour FabricPool. Vous pouvez également spécifier la règle de Tiering ainsi que la période de refroidissement minimale de Tiering du volume FlexGroup.

+
link:../disks-aggregates/index.html["Gestion des disques et des agrégats"]

+
Vous pouvez spécifier un plafond de débit (QoS max) pour les volumes FlexGroup. Cela limite les ressources de performance que le volume FlexGroup peut consommer. À partir de la version ONTAP 9.4, vous pouvez spécifier les niveaux de débit (QoS min) et la QoS adaptative pour les volumes FlexGroup.

+
link:../performance-admin/index.html["Gestion des performances"]

+
Vous pouvez définir `-encrypt` le paramètre sur `true` si vous souhaitez activer le chiffrement sur le volume FlexGroup. Pour créer un volume chiffré, vous devez avoir installé la licence de chiffrement de volume et le gestionnaire de clés.

+

NOTE: Vous devez activer le chiffrement sur les volumes FlexGroup au moment de la création. Vous ne pouvez pas activer le chiffrement sur les volumes FlexGroup existants.

+
link:../encryption-at-rest/index.html["Cryptage des données au repos"]

+
Le `size` Paramètre spécifie la taille du volume FlexGroup en Ko, Mo, Go, To ou po.

+
L'exemple suivant montre comment provisionner un volume FlexGroup de 400 To :

+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
L'exemple suivant montre comment créer une « policy group » QoS pour le plafond de débit et comment l'appliquer à un volume FlexGroup :

+
[listing]
----
cluster1::> qos policy-group create -policy group pg-vs1 -vserver vs1 -max-throughput 5000iops
----
+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -qos-policy-group pg-vs1
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
L'exemple suivant montre comment provisionner un volume FlexGroup de 400 To sur des niveaux locaux avec FabricPool activé :

+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -support-tiering true -tiering-policy auto
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
Le volume FlexGroup est créé avec huit volumes membres sur chaque nœud du cluster. Les volumes membres sont répartis de manière égale entre les deux niveaux locaux les plus grands de chaque nœud.

+
Par défaut, le volume FlexGroup est créé avec le `volume` Paramètre de garantie d'espace disponible sauf sur les systèmes AFF. Pour les systèmes AFF, le volume FlexGroup est créé par défaut avec le `none` garantie d'espace.

. Montez le volume FlexGroup avec une Junction path :
+
`volume mount -vserver vserver_name -volume vol_name -junction-path junction_path`

+
[listing]
----
cluster1::> volume mount -vserver vs0 -volume fg2 -junction-path /fg2
----


.Une fois que vous avez terminé
Vous devez monter le volume FlexGroup à partir du client.

Si vous exécutez ONTAP 9.6 ou version antérieure et si la machine virtuelle de stockage (SVM) a configuré NFSv3 et NFSv4, le montage du volume FlexGroup du client peut échouer. Dans ce cas, vous devez spécifier de manière explicite la version NFS lors du montage du volume FlexGroup à partir du client.

[listing]
----
# mount -t nfs -o vers=3 192.53.19.64:/fg2 /mnt/fg2
# ls /mnt/fg2
file1  file2
----