---
permalink: flexgroup/reactivate-original-source-after-disaster-task.html 
sidebar: sidebar 
keywords: reactivate, original, source, flexgroup, volume, disaster 
summary: 'Lorsque le volume FlexGroup source est disponible, vous pouvez resynchroniser les volumes FlexGroup source et de destination d"origine. Toutes les nouvelles données présentes sur le volume FlexGroup de destination sont perdues.' 
---
= Réactiver le volume FlexGroup source d'origine après un incident
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque le volume FlexGroup source est disponible, vous pouvez resynchroniser les volumes FlexGroup source et de destination d'origine. Toutes les nouvelles données présentes sur le volume FlexGroup de destination sont perdues.

Toutes les règles de quota actives sur le volume de destination sont désactivées et les règles de quota sont supprimées avant d'effectuer une resynchronisation.

Vous pouvez utiliser le `volume quota policy rule create` et `volume quota modify` commandes permettant de créer et de réactiver des règles de quota une fois l'opération de resynchronisation terminée.

.Étapes
. Depuis le cluster de destination, faire une resynchronisation de la relation de FlexGroup volume SnapMirror : `snapmirror resync -destination-path dst_svm:dest_flexgroup`
. Afficher l'état de la relation SnapMirror : `snapmirror show -expand`
+
[listing]
----
cluster2::> snapmirror show -expand
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vss:s       XDP  vsd:dst        Snapmirrored
                                      Idle           -         true    -
vss:s__0001 XDP  vsd:dst__0001  Snapmirrored
                                      Idle           -         true    -
vss:s__0002 XDP  vsd:dst__0002  Snapmirrored
                                      Idle           -         true    -
vss:s__0003 XDP  vsd:dst__0003  Snapmirrored
                                      Idle           -         true    -
vss:s__0004 XDP  vsd:dst__0004  Snapmirrored
                                      Idle           -         true    -
vss:s__0005 XDP  vsd:dst__0005  Snapmirrored
                                      Idle           -         true    -
vss:s__0006 XDP  vsd:dst__0006  Snapmirrored
                                      Idle           -         true    -
vss:s__0007 XDP  vsd:dst__0007  Snapmirrored
                                      Idle           -         true    -
vss:s__0008 XDP  vsd:dst__0008  Snapmirrored
                                      Idle           -         true    -
...
----
+
L'état de la relation SnapMirror de chaque composant est `Snapmirrored`.


