---
permalink: flexgroup/restore-snapvault-backup-task.html 
sidebar: sidebar 
keywords: restore, flexgroup, volume, snapvault, backup 
summary: 'Vous pouvez effectuer une opération de restauration de volume complet des volumes FlexGroup à partir d"une copie Snapshot sur le volume secondaire SnapVault. Vous pouvez restaurer le volume FlexGroup sur le volume source d"origine ou sur un nouveau volume FlexGroup.' 
---
= Restaurez un volume FlexGroup à partir d'une sauvegarde SnapVault
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez effectuer une opération de restauration de volume complet des volumes FlexGroup à partir d'une copie Snapshot sur le volume secondaire SnapVault. Vous pouvez restaurer le volume FlexGroup sur le volume source d'origine ou sur un nouveau volume FlexGroup.

.Avant de commencer
Vous devez prendre en compte certaines considérations relatives à la restauration à partir des sauvegardes SnapVault pour les volumes FlexGroup.

* Seule la restauration de base est prise en charge avec des copies Snapshot partielles à partir d'une sauvegarde SnapVault.
Le nombre de composants du volume de destination doit correspondre au nombre de composants du volume source lors de la copie Snapshot effectuée.
* Si une opération de restauration échoue, aucune autre opération n'est autorisée tant que l'opération de restauration n'est pas terminée.
Vous pouvez soit relancer l'opération de restauration, soit exécuter l'opération de restauration avec `cleanup` paramètre.
* Un volume FlexGroup peut être le volume source d'une seule relation de sauvegarde ou de restauration.
Un volume FlexGroup ne peut pas être à l'origine de deux relations SnapVault, de deux relations de restauration, ou d'une relation SnapVault et de restauration.
* Les opérations de sauvegarde et de restauration de SnapVault ne peuvent pas être exécutées en parallèle.
Lorsqu'une opération de restauration de base ou une opération de restauration incrémentielle est en cours, vous devez arrêter les opérations de sauvegarde.
* Vous devez annuler l'opération de restauration d'une copie Snapshot partielle du volume FlexGroup de destination.
Vous ne pouvez pas abandonner l'opération de restauration d'une copie Snapshot partielle du volume source.
* Si vous abandonnez une opération de restauration, vous devez redémarrer l'opération avec la même copie Snapshot utilisée pour la précédente opération de restauration.


.Description de la tâche
Toutes les règles de quota actives sur le volume FlexGroup de destination sont désactivées avant l'exécution de la restauration.

Vous pouvez utiliser le `volume quota modify` commande permettant de réactiver les règles de quota une fois l'opération de restauration terminée.

.Étapes
. Restaurez le volume FlexGroup : `snapmirror restore -source-path _src_svm:src_flexgroup_ -destination-path _dest_svm:dest_flexgroup_ -snapshot _snapshot_name_`
`snapshot_name` Est la copie Snapshot à restaurer depuis le volume source vers le volume de destination. Si la copie Snapshot n'est pas spécifiée, le volume de destination est restauré à partir de la dernière copie Snapshot.
+
[listing]
----
vserverA::> snapmirror restore -source-path vserverB:dstFG -destination-path vserverA:newFG -snapshot daily.2016-07-15_0010
Warning: This is a disruptive operation and the volume vserverA:newFG will be read-only until the operation completes
Do you want to continue? {y|n}: y
----

