---
permalink: flexgroup/snapvault-backup-concept.html 
sidebar: sidebar 
keywords: consider, create, snapvault, backup, relation, unified, data, protection, flexgroup, volume 
summary: 'Il est à prendre en compte les considérations relatives à la création d"une relation de sauvegarde SnapVault et d"une relation de protection unifiée des données pour les volumes FlexGroup.' 
---
= Considérations relatives à la création d'une relation de sauvegarde SnapVault et d'une relation unifiée de protection des données pour les volumes FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il est à prendre en compte les considérations relatives à la création d'une relation de sauvegarde SnapVault et d'une relation de protection unifiée des données pour les volumes FlexGroup.

* Vous pouvez resynchroniser une relation de sauvegarde SnapVault et une relation de protection des données unifiée en utilisant l' `-preserve`option qui permet de conserver les copies Snapshot sur le volume de destination qui sont plus récentes que le dernier snapshot commun.
* La conservation à long terme n'est pas prise en charge par les volumes FlexGroup.
+
La conservation à long terme permet de créer des snapshots directement sur le volume de destination sans devoir les stocker sur le volume source.

* Le `snapshot` commande `expiry-time` Option non prise en charge pour les volumes FlexGroup.
* L'efficacité du stockage ne peut pas être configurée sur le volume FlexGroup de destination d'une relation de sauvegarde SnapVault et d'une relation de protection unifiée des données.
* Vous ne pouvez pas renommer les snapshots d'une relation de sauvegarde SnapVault et d'une relation de protection unifiée des données pour les volumes FlexGroup.
* Un volume FlexGroup peut être le volume source d'une seule relation de sauvegarde ou de restauration.
+
Un volume FlexGroup ne peut pas être à l'origine de deux relations SnapVault, de deux relations de restauration, ou d'une relation de sauvegarde SnapVault et de restauration.

* Si vous supprimez un snapshot sur le volume FlexGroup source et que vous recréez un snapshot portant le même nom, le transfert de mise à jour suivant vers le volume FlexGroup de destination échoue si le volume de destination possède un snapshot du même nom.
+
En effet, les snapshots ne peuvent pas être renommés pour les volumes FlexGroup.


