---
permalink: flexgroup/supported-unsupported-config-concept.html 
sidebar: sidebar 
keywords: support, unsupported, configuration, flexgroup, volumes 
summary: Notez les fonctionnalités de ONTAP prises en charge par les volumes FlexGroup dans ONTAP 9. 
---
= Configurations prises en charge et non prises en charge pour les volumes FlexGroup
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Notez les fonctionnalités de ONTAP prises en charge par les volumes FlexGroup dans ONTAP 9.



== Fonctionnalités prises en charge à partir d'ONTAP 9.12.1

* Rééquilibrage FlexGroup
* SnapLock pour SnapVault




== Fonctionnalités prises en charge à partir d'ONTAP 9.11.1

* Volumes SnapLock
+
SnapLock ne prend pas en charge les fonctionnalités suivantes avec les volumes FlexGroup :

+
** Obligation légale
** Conservation basée sur les événements
** SnapLock pour SnapVault




Vous configurez SnapLock au niveau de FlexGroup. Vous ne pouvez pas configurer SnapLock au niveau du composant.

xref:../snaplock/snaplock-concept.adoc[Qu'est-ce que SnapLock]

* Suppression du répertoire asynchrone du client
+
xref:manage-client-async-dir-delete-task.adoc[Gérer les droits des clients pour supprimer rapidement des répertoires]





== Fonctionnalités prises en charge à partir d'ONTAP 9.10.1

* Conversion de volumes FlexVol en volumes FlexGroup au sein d'une source SVM-DR
+
xref:convert-flexvol-svm-dr-relationship-task.adoc[Conversion d'un volume FlexVol en volume FlexGroup au sein d'une relation SVM-DR]

* Prise en charge SVM-DR FlexClone pour les volumes FlexGroup
+
xref:../volumes/create-flexclone-task.adoc[En savoir plus sur la création de volumes FlexClone.]





== Fonctionnalités prises en charge à partir d'ONTAP 9.9.1

* Reprise d'activité de SVM
+
Le clonage d'un volume FlexGroup faisant partie d'une relation SVM-DR n'est pas pris en charge.

* SnapMirror gère 2 relations ou plus (A à B, A à C), avec un maximum de 8 pieds en éventail.
+
xref:create-snapmirror-cascade-fanout-reference.adoc[Considérations relatives à la création de relations SnapMirror en cascade et avec fanout pour FlexGroups]

* Relations SnapMirror en cascade (de A à B à C) jusqu'à deux niveaux
+
xref:create-snapmirror-cascade-fanout-reference.adoc[Considérations relatives à la création de relations SnapMirror en cascade et avec fanout pour FlexGroups]





== Fonctionnalités prises en charge à partir d'ONTAP 9.8

* Restauration d'un seul fichier à partir d'un coffre-fort FlexGroup SnapMirror ou d'une destination UDP
+
** La restauration peut être d'un volume FlexGroup de n'importe quelle géométrie vers un volume FlexGroup de n'importe quelle géométrie
** Un seul fichier par opération de restauration est pris en charge


* La conversion des volumes a été effectué à partir de systèmes 7-mode vers des volumes FlexGroup
+
Pour plus d'informations, consultez l'article de la base de connaissances link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_To_Convert_a_Transitioned_FlexVol_to_FlexGroup["Comment convertir un FlexVol converti en FlexGroup"].

* NFSv4.2
* Suppression asynchrone de fichiers et de répertoires
* Analyse du système de fichiers (FSA)
* FlexGroup en tant que datastore VMware vSphere
* Prise en charge supplémentaire de la sauvegarde sur bande et de la restauration via NDMP, notamment :
+
** Extension de sauvegarde redémarrable NDMP (RBE) et extension de gestion Snapshot (SSME)
** Les variables d'environnement EXCLUDE et MULTI_SUBTREE_NAMES prennent en charge les sauvegardes FlexGroup
** Introduction de la variable d'environnement IGNORE_CTIME_MTIME pour les sauvegardes FlexGroup
** La restauration de fichiers individuels dans un FlexGroup à l'aide du message NDMP_SNAP_RECOVER, qui fait partie de l'extension 0x2050 Dump and restore sessions, est abandonnée pendant une mise à niveau ou une restauration.






== Fonctionnalités prises en charge à partir d'ONTAP 9.7

* Volume FlexClone
* NFSv4 et NFSv4.1
* PNFS
* Sauvegarde sur bande et restauration à l'aide de NDMP
+
Pour la prise en charge de NDMP sur les volumes FlexGroup, vous devez connaître les points suivants :

+
** Le message NDMP_SNAP_RECOVER de la classe d'extension 0x2050 ne peut être utilisé que pour restaurer un volume FlexGroup entier.
+
Les fichiers individuels d'un volume FlexGroup ne peuvent pas être restaurés.

** L'extension de sauvegarde NDMP redémarrable (RBE) n'est pas prise en charge pour les volumes FlexGroup.
** Les variables d'environnement EXCLUDE et MULTI_SUBTREE_NAMES ne sont pas prises en charge pour les volumes FlexGroup.
** Le `ndmpcopy` La commande est prise en charge pour le transfert de données entre les volumes FlexVol et FlexGroup.
+
Si vous restaurez Data ONTAP 9.7 vers une version antérieure, les informations de transfert incrémentiel des transferts précédents ne sont pas conservées. Par conséquent, vous devez effectuer une copie de base après le rétablissement.



* VMware vStorage APIs for Array Integration (VAAI)
* Conversion d'un volume FlexVol en volume FlexGroup
* Volumes FlexGroup en tant que volumes d'origine FlexCache




== Fonctionnalités prises en charge à partir d'ONTAP 9.6

* Partages SMB disponibles en permanence
* Configurations MetroCluster
* Modification du nom d'un volume FlexGroup (`volume rename` commande)
* Réduction ou réduction de la taille d'un volume FlexGroup (`volume size` commande)
* Dimensionnement élastique
* Chiffrement d'agrégat NetApp (NAE)
* Cloud Volumes ONTAP




== Fonctionnalités prises en charge à partir d'ONTAP 9.5

* Allègement de la charge des copies (ODX
* Protection d'accès au niveau du stockage
* Améliorations apportées aux notifications de modification pour les partages SMB
+
Des notifications de modification sont envoyées pour les modifications apportées au répertoire parent sur lequel l' `changenotify` la propriété est définie et pour les modifications apportées à tous les sous-répertoires de ce répertoire parent.

* FabricPool
* Application des quotas
* Statistiques qtree
* QoS adaptative pour les fichiers dans les volumes FlexGroup
* FlexCache (cache uniquement ; FlexGroup en tant qu'origine pris en charge dans ONTAP 9.7)




== Fonctionnalités prises en charge à partir d'ONTAP 9.4

* FPolicy
* Audit de fichiers
* Débit au sol (QoS min) et QoS adaptative pour les volumes FlexGroup
* Débit maximal (QoS Max) et débit au sol (QoS min) pour les fichiers dans les volumes FlexGroup
+
Vous utilisez le `volume file modify` Commande pour gérer la « QoS policy group » associée à un fichier.

* Limites SnapMirror détendues
* Multicanal SMB 3.x




== Fonctionnalités prises en charge à partir d'ONTAP 9.3

* Configuration antivirus
* Notifications de modification pour les partages SMB
+
Les notifications sont envoyées uniquement pour les modifications apportées au répertoire parent sur lequel l' `changenotify` la propriété est définie. Les notifications de modification ne sont pas envoyées pour les modifications apportées aux sous-répertoires du répertoire parent.

* Qtrees
* Plafond de débit (QoS max)
* Étendre le volume FlexGroup source et le volume FlexGroup de destination dans une relation SnapMirror
* La sauvegarde et la restauration de SnapVault
* Relations unifiées de protection des données
* Option croissance automatique et option Autohrink
* Le nombre d'inodes a été prévu pour l'ingestion




== Fonctionnalité prise en charge depuis ONTAP 9.2

* Chiffrement de volume
* Déduplication à la volée dans l'agrégat (déduplication entre plusieurs volumes)
* Chiffrement de volume NetApp (NVE)




== Fonctionnalités prises en charge à partir d'ONTAP 9.1

Les volumes FlexGroup ont été introduits avec la prise en charge de plusieurs fonctionnalités d'ONTAP dans ONTAP 9.1.

* Technologie SnapMirror
* Copies Snapshot
* Active IQ
* Compression adaptative à la volée
* Déduplication à la volée
* Compaction des données à la volée
* AFF
* Création de rapports sur les quotas
* Technologie Snapshot de NetApp
* Logiciel SnapRestore (niveau FlexGroup)
* Agrégats hybrides
* Déplacement du volume du composant ou du membre
* Déduplication post-traitement
* Technologie NetApp RAID-TEC
* Point de cohérence par agrégat
* Partage d'FlexGroup avec un volume FlexVol sur le même SVM




== Configurations non prises en charge dans ONTAP 9

|===


| Protocoles non pris en charge | Fonctionnalités de protection des données non prises en charge | Autres fonctionnalités ONTAP non prises en charge 


 a| 
* PNFS (ONTAP 9.0 à 9.6)
* SMB 1.0
* Basculement transparent SMB (ONTAP 9.0 à 9.5)
* SAN

 a| 
* Volumes SnapLock (ONTAP 9.10.1 et versions antérieures)
* SMTape

 a| 
Service VSS (Remote Volume Shadow Copy Service)

|===
https://docs.netapp.com/ontap-9/index.jsp["Centre de documentation ONTAP 9"]
