---
permalink: flexcache-writeback/flexcache-write-back-prerequisites.html 
sidebar: sidebar 
keywords: tr-4743, flexcache writeback, flexcache write-back, prerequisites, technical report, netapp tr, ontap tr 
summary: Avant de déployer FlexCache en mode écriture différée, assurez-vous que vous répondez aux exigences en matière de logiciel, de licence et de configuration du système. 
---
= Conditions préalables à la réécriture de ONTAP FlexCache
:allow-uri-read: 


[role="lead"]
Avant de déployer FlexCache en mode écriture différée, assurez-vous que vous répondez aux exigences de performances, de logiciels, de licences et de configuration du système.



[[cpu-and-memory]]
== Processeur et mémoire

Il est __**fortement recommandé**__ que chaque nœud de cluster d'origine dispose d'au moins 128 Go de RAM et de 20 processeurs pour absorber les messages d'écriture différée initiés par les caches activés pour l'écriture différée. C'est l'équivalent d'un modèle A400 ou supérieur. Si le cluster d'origine sert d'origine à plusieurs modules FlexCas à écriture différée, il faudra davantage de CPU et de RAM.


CAUTION: L'utilisation d'une source de taille insuffisante pour votre charge de travail peut avoir un impact important sur les performances au niveau du cache avec écriture différée ou de l'origine.



[[ontap-version]]
== Version ONTAP

* L'origine *_doit_* fonctionner sous ONTAP 9.15.1 ou une version ultérieure ; cependant, ONTAP 9.15.1 ne dispose pas de tous les correctifs et améliorations nécessaires pour la fonction de write-back FlexCache, et n'est pas recommandé pour les charges de travail en production. Des améliorations significatives pour le write-back FlexCache ont été introduites dans ONTAP 9.17.1P1. Il est *_fortement_* conseillé d’exécuter la version recommandée actuelle postérieure à la 9.17.1P1, à la fois sur le cluster d’origine et sur les clusters de cache. Si vous ne pouvez pas exécuter ONTAP 9.17.1, la dernière version P de la 9.16.1 est la version suivante recommandée.
+

NOTE: Il est *_vivement_* recommandé que vous consultiez le link:flexcache-write-back-guidelines.html["Instructions de réécriture de code FlexCache"] avant de mettre en œuvre la fonctionnalité de réécriture FlexCache dans votre environnement.

* Tout cluster de cache devant fonctionner en mode de réécriture *_must_* exécute ONTAP 9.15.1 ou une version ultérieure.
* Tout cluster de mise en cache qui n'a pas besoin de fonctionner en mode write-back peut exécuter n'importe quelle version ONTAP prenant en charge les volumes FlexCache.




[[licensing]]
== Licences

FlexCache, y compris le mode d'opération de réécriture, est inclus avec votre achat de ONTAP. Aucune licence supplémentaire n'est requise.



[[peering]]
== Peering

* Les clusters d'origine et de cache doivent être link:../flexcache-writeback/flexcache-writeback-enable-task.html["peering de cluster"]
* Les serveurs virtuels (SVM) sur le cluster d'origine et cache doivent link:../flexcache-writeback/flexcache-writeback-enable-task.html["peering de vservers"] utiliser l'option FlexCache.



NOTE: Vous n'avez pas besoin de transférer un cluster de cache vers un autre cluster de cache. Il n'est pas non plus nécessaire de placer un SVM en cache sur une autre SVM en cache.
