---
permalink: flexcache-writeback/flexcache-write-back-guidelines.html 
sidebar: sidebar 
keywords: tr-4743, flexcache writeback, flexcache write-back, flexcache, write-back, write back, guidelines, best practices, performance, ontap tr, netapp tr 
summary: 'Suivez ces instructions pour garantir des performances optimales lors de l"utilisation de l"écriture différée FlexCache.' 
---
= Instructions de réécriture de code ONTAP FlexCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'écriture différée de FlexCache implique de nombreuses interactions complexes entre l'origine et les caches. Pour des performances optimales, vous devez vous assurer que votre environnement respecte ces directives. Ces instructions sont basées sur la dernière version majeure de ONTAP (ONTAP 9.15.1) disponible au moment de la création du contenu.

Il est recommandé de tester votre charge de travail de production dans un environnement de non-production. Cela est encore plus important si vous implémentez la réécriture FlexCache en dehors de ces instructions.

Les directives suivantes sont testées en interne par NetApp. Il est *_fortement_* recommandé que vous restiez à l'intérieur d'eux. Si ce n'est pas le cas, un comportement inattendu pourrait se produire.

* Des améliorations importantes ont été apportées à la réécriture FlexCache dans ONTAP 9.15.1P5. Il est recommandé d'exécuter la version recommandée après 9.15.1P5 sur les clusters d'origine et de cache.
* Dans l'itération actuelle, les caches d'écriture différée FlexCache doivent être configurés avec un seul composant pour l'ensemble du volume FlexCache. Des FlexCaches multi-composants peuvent entraîner des suppressions indésirables des données du cache.
* Des tests ont été réalisés pour des fichiers inférieurs à 100 Go et des temps d'aller-retour WAN entre le cache et l'origine n'excédant pas 100 ms. Toute charge de travail en dehors de ces limites peut entraîner des caractéristiques de performances inattendues.
* L'écriture dans les autres flux de données SMB entraîne la suppression du fichier principal du cache. Toutes les données corrompues du fichier principal doivent être vidées à l'origine avant que d'autres opérations puissent avoir lieu sur ce fichier. Le flux de données alternatif est également transmis à l'origine.
* Le fait de renommer un fichier entraîne la suppression du fichier du cache. Toutes les données corrompues du fichier doivent être vidées à l'origine avant que d'autres opérations puissent avoir lieu sur ce fichier.
* Pour le moment, les seuls attributs qui peuvent être modifiés ou définis sur un fichier du volume FlexCache avec écriture différée sont les suivants :
+
** Horodatages
** Bits de mode
** Listes de contrôle d'accès NT
** Propriétaire
** Groupe
** Taille
+
Tous les autres attributs modifiés ou définis sont transférés vers l'origine, ce qui peut entraîner l'éviction du fichier du cache. Si vous avez besoin de modifier ou de définir d'autres attributs dans le cache, demandez à votre équipe de gestion de compte d'ouvrir un PVR.



* Les snapshots pris à l'origine entraînent le rappel de toutes les données corrompues en attente de chaque cache activé pour l'écriture différée associé à ce volume d'origine. Ceci peut nécessiter plusieurs tentatives de l'opération si une activité de réécriture importante est en cours, car les suppressions de ces fichiers sales peuvent prendre un certain temps.
* L'origine doit rester pleine à moins de 80 %. Les volumes de cache ne disposent pas de délégations de verrouillage exclusives si au moins 20 % d'espace n'est pas disponible dans le volume d'origine. Dans ce cas, les appels vers un cache avec réinscription sont transférés vers l'origine. Cela permet d'éviter de manquer d'espace à l'origine, ce qui entraînerait la création de données corrompues orphelines dans un cache réinscriptible.

