---
permalink: flexcache-writeback/flexcache-write-back-prerequisites.html 
sidebar: sidebar 
keywords: tr-4743, flexcache writeback, flexcache write-back, prerequisites, technical report, netapp tr, ontap tr 
summary: Avant de déployer FlexCache en mode écriture différée, assurez-vous que vous répondez aux exigences en matière de logiciel, de licence et de configuration du système. 
---
= Conditions préalables à la réécriture de FlexCache
:allow-uri-read: 


[role="lead"]
Avant de déployer FlexCache en mode écriture différée, assurez-vous que vous avez satisfait aux conditions requises pour le logiciel, la licence et la configuration du système.



== Version ONTAP

* L'origine *_must_* exécute ONTAP 9.15.1 ou une version ultérieure.
* Tout cluster de cache devant fonctionner en mode de réécriture *_must_* exécute ONTAP 9.15.1 ou une version ultérieure.
* Tout cluster de cache qui n'a pas besoin d'opérer en mode de réécriture peut exécuter n'importe quelle version de ONTAP prise en charge.




== Licences

FlexCache, y compris le mode d'opération de réécriture, est inclus avec votre achat de ONTAP. Aucune licence supplémentaire n'est requise.



== Peering

* Les clusters d'origine et de cache doivent être link:../flexcache-writeback/flexcache-writeback-enable-task.html["peering de cluster"]
* Les serveurs virtuels (SVM) sur le cluster d'origine et cache doivent link:../flexcache-writeback/flexcache-writeback-enable-task.html["peering de vservers"] utiliser l'option FlexCache.



NOTE: Vous n'avez pas besoin de transférer un cluster de cache vers un autre cluster de cache. Il n'est pas non plus nécessaire de placer un SVM en cache sur une autre SVM en cache.
