---
permalink: smbc/resume-protection-fan-out-configuration.html 
sidebar: sidebar 
keywords: fan out, asynchronous, restore, third site, MirrorAllSnapshots, MirrorAndVault 
summary: SM-BC prend en charge les configurations « Fan-Out ». Suite à un basculement sur le noeud final SM-BC, vous devez reprendre la connexion avec le noeud final asynchrone Fan-Out. 
---
= Reprendre la protection dans une configuration de « Fan-Out » avec SM-BC
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Supports SM-BC xref:../data-protection/supported-deployment-config-concept.html[configurations « fan-out »]. Votre volume source peut être mis en miroir sur un terminal de destination SM-BC et sur une ou plusieurs relations SnapMirror asynchrones.

Les configurations « fan-out » sont prises en charge par le système `MirrorAllSnapshots` Et, à partir de ONTAP 9.11.1, le `MirrorAndVault` politique. Depuis ONTAP 9.11.1, les configurations de « Fan-Out » dans SM-BC ne sont pas prises en charge avec le `XDPDefault` politique.

Si vous constatez un basculement sur la destination SM-BC, la destination SnapMirror asynchrone deviendra défectueuse et vous devez restaurer manuellement la protection en supprimant et en recréant la relation avec le terminal SnapMirror asynchrone.

.Reprendre la protection dans une configuration « Fan-Out »
. Vérifiez que le basculement s'est terminé correctement :
`snapmirror failover show`
. Sur le terminal SnapMirror asynchrone, supprimez le terminal « Fan-Out » :
`snapmirror delete -destination-path _destination_path_`
. Sur le troisième site, créer des relations SnapMirror asynchrones entre le nouveau volume primaire SM-BC et le volume de destination asynchrone Fan-Out :
`snapmirror create -source-path _source_path_ -destination-path _destination_path_ -policy MirrorAllSnapshots -schedule _schedule_`
. Resynchroniser la relation :
`SnapMirror resync -destination-path _destination_path_`
. Vérifiez l'état et l'état de la relation :
`snapmirror show`

