---
sidebar: sidebar 
permalink: smbc/smbc_troubleshoot_sm_delete_fails_in_takeover_state.html 
keywords: troubleshooting, SM-BC, SMBC, SnapMirror, delete, takeover, consistency group 
summary: 'Lorsque ONTAP 9.9.1 est installé sur un cluster, exécutant le `snapmirror delete` La commande échoue lorsqu"une relation de groupe de cohérence SM-BC est à l"état basculement.' 
---
= L'opération de suppression de SnapMirror a échoué lors du basculement
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


.Problème :
[role="lead"]
Lorsque ONTAP 9.9.1 est installé sur un cluster, exécutant le `snapmirror delete` La commande échoue lorsqu'une relation de groupe de cohérence SM-BC est à l'état basculement.

....
C2_cluster::> snapmirror delete  vs1:/cg/dd

Error: command failed: RPC: Couldn't make connection
....
.Solution
Lorsque les nœuds d'une relation SM-BC sont en état de basculement, exécutez l'opération de suppression et de libération de SnapMirror avec l'option « force » définie sur vrai.

....
C2_cluster::> snapmirror delete  vs1:/cg/dd -force true

Warning: The relationship between source "vs0:/cg/ss" and destination
         "vs1:/cg/dd" will be deleted, however the items of the destination
         Consistency Group might not be made writable, deletable, or modifiable
         after the operation. Manual recovery might be required.
Do you want to continue? {y|n}: y
Operation succeeded: snapmirror delete for the relationship with destination "vs1:/cg/dd".
....