---
sidebar: sidebar 
permalink: smbc/smbc_intro_terminology.html 
keywords: SM-BC, SMBC, Mediator, terminology 
summary: 'Lorsque vous commencez à explorer le logiciel ONTAP SnapMirror de continuité de l"activité et de planification d"un déploiement, vous pouvez vous familiariser avec la terminologie et les concepts clés.' 
---
= Concepts clés
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Lorsque vous commencez à explorer le logiciel ONTAP SnapMirror de continuité de l'activité et de planification d'un déploiement, vous pouvez vous familiariser avec la terminologie et les concepts clés.

Acronyme de la solution SnapMirror Business Continuity (SM-BC) disponible avec ONTAP 9.8 et versions ultérieures.

Depuis ONTAP 9.10.1, les groupes de cohérence sont devenus une unité de gestion de premier ordre. Pour en savoir plus sur les groupes de cohérence, reportez-vous à la section link:../consistency-groups/index.html["Présentation des groupes de cohérence"].

Un groupe de cohérence est une collection de volumes FlexVol qui offre une garantie de cohérence de l'ordre d'écriture pour la charge de travail applicative qui doit être protégée pour la continuité de l'activité. Un groupe de cohérence permet d'effectuer simultanément des copies Snapshot cohérentes après panne d'un ensemble de volumes à un moment donné. Dans un déploiement régulier, le groupe de volumes sélectionnés pour faire partie d'un groupe de cohérence est mappé à une instance d'application. Les relations SnapMirror, également appelées relations de groupe de cohérence, sont établies entre un groupe de cohérence source et un groupe de cohérence de destination. Les groupes de cohérence source et de destination doivent contenir le même nombre et le même type de volumes.

Les volumes FlexVol individuels qui font partie d'un groupe de cohérence.

ONTAP Mediator fournit un autre chemin d'état de santé au cluster peer, avec les LIFs intercluster fournissant l'autre chemin d'état. Grâce aux informations de santé du médiateur, les clusters peuvent différencier une panne de LIF intercluster et une défaillance de site. Lorsque le site tombe en panne, Mediator transmet les informations de santé au groupe de pairs à la demande, ce qui facilite le basculement du groupe de pairs. Avec les informations fournies par le médiateur et les informations de vérification de l'état du LIF intercluster, ONTAP détermine s'il faut effectuer un basculement automatique, s'il s'agit d'un basculement impossible, continuer ou s'arrêter.

Le médiateur est l'une des trois parties du quorum SM-BC, travaillant avec le groupe principal et le groupe secondaire pour parvenir à un consensus. Un consensus exige qu'au moins deux parties au quorum conviennent d'une opération.

Les E/S de l'application ne sont pas répliquées sur le système de stockage secondaire. Le volume de destination n'est pas synchronisé avec le volume source, car la réplication SnapMirror n'est pas survenue. Si l'état du miroir est Snapmirrored, cela indique un échec de transfert ou un échec dû à une opération non prise en charge.

Objectif de point de restauration nul. Vous pouvez éviter toute perte de données liée à une interruption.

Le basculement de chemin d'accès logiciel MPIO (Multi-Path E/S) au niveau des hôtes assure un objectif de délai de restauration nul ou un basculement transparent des applications sur incident.

Opération manuelle pour modifier les rôles des copies dans une relation SM-BC. Le primaire devient le secondaire et le secondaire devient le primaire. Les rapports ALUA sont également modifiés.

Opération automatique pour effectuer un basculement vers la copie miroir. L'opération nécessite l'aide du médiateur pour détecter que la copie principale n'est pas disponible.
