---
sidebar: sidebar 
permalink: smbc/smbc_admin_performing_a_planned_failover.html 
keywords: SM-BC, testing failover, planned failover, maintenance, quorum, , snapmirror active sync 
summary: Vous pouvez effectuer un basculement planifié pour tester votre configuration de reprise sur incident ou réaliser des opérations de maintenance sur le cluster principal. 
---
= Effectuer un basculement planifié
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Lors d'un basculement planifié, vous changez les rôles des clusters principal et secondaire, de sorte que le cluster secondaire prenne le relais du cluster principal. Lors d'un basculement, ce qui est généralement le cluster secondaire traite les demandes d'entrée et de sortie localement sans interrompre les opérations client.

Vous pouvez effectuer un basculement planifié pour tester l'état de santé de votre configuration de reprise sur incident ou pour effectuer des opérations de maintenance sur le cluster principal.

.Description de la tâche
Un basculement planifié est initié par l'administrateur du cluster secondaire. L'opération nécessite le basculement des rôles principal et secondaire afin que le cluster secondaire prenne le relais du cluster principal. Le nouveau cluster principal peut alors commencer à traiter les demandes d'entrée et de sortie localement, sans interrompre les opérations client.

.Avant de commencer
* La relation SM-BC doit être synchronisée.
* Vous ne pouvez pas lancer de basculement planifié lorsqu'une opération sans interruption est en cours. La continuité de l'activité inclut les déplacements de volumes, les transferts d'agrégats et les basculements de stockage.
* Le médiateur ONTAP doit être configuré, connecté et en quorum.


.Étapes
Vous pouvez effectuer un basculement planifié via l'interface de ligne de commande ONTAP ou System Manager.

[role="tabbed-block"]
====
.System Manager
--
. Dans System Manager, sélectionnez **protection > vue d'ensemble > relations**.
. Identifiez la relation SM-BC à basculer. En regard de son nom, sélectionnez le `...` À côté du nom de la relation, puis sélectionnez **basculement**.
. Pour surveiller l'état du basculement, utilisez `snapmirror failover show` Dans l'interface de ligne de commandes ONTAP.


--
.CLI
--
. Depuis le cluster de destination, lancer l'opération de basculement :
+
`destination::>snapmirror failover start -destination-path   vs1_dst:/cg/cg_dst`

. Surveiller la progression du basculement :
+
`destination::>snapmirror failover show`

. À la fin de l'opération de basculement, vous pouvez surveiller l'état de la relation de protection SnapMirror synchrone depuis la destination :
+
`destination::>snapmirror show`



--
====