---
sidebar: sidebar 
permalink: smbc/smbc_install_mapping_luns_to_the_application_hosts.html 
keywords: SM-BC, SMBC, igroup, LUN, initiator, application host, cluster configure 
summary: 'Vous devez créer un groupe initiateur sur chaque cluster afin de pouvoir mapper des LUN sur l"initiateur sur l"hôte de l"application.' 
---
= Mappage des LUN sur les hôtes de l'application
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous devez créer un groupe initiateur sur chaque cluster afin de pouvoir mapper des LUN sur l'initiateur sur l'hôte de l'application.

.Description de la tâche
Vous devez effectuer cette configuration à la fois sur les clusters source et de destination.

.Étapes
. Créez un groupe initiateur sur chaque cluster :
+
`lun igroup create -igroup name -protocol fcp|iscsi -ostype os   -initiator initiator_name`

+
*Exemple*

+
....
lun igroup create -igroup ig1 -protocol iscsi -ostype linux -initiator -initiator iqn.2001-04.com.example:abc123
....
. Mapper les LUN sur le groupe initiateur :
+
`lun map -path path_name -igroup igroup_name`

+
*Exemple:*

+
....
lun map -path /vol/src1/11 -group ig1
....
. Vérifiez que les LUN sont mappées :
+
`lun show`

. Découvrez les nouveaux LUN sur l'hôte applicatif.

