---
sidebar: sidebar 
permalink: smbc/smbc_admin_upgrade_and_revert_considerations.html 
keywords: upgrade, revert, snapmirror active sync 
summary: La mise à niveau ou le rétablissement de ONTAP a des implications sur votre relation SM-BC, en particulier lorsque vous passez à ONTAP 9.8 ou version ultérieure ou à la version 9.7 ou antérieure. 
---
= Mettez à niveau et restaurez ONTAP avec SM-BC
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror Business Continuity (SM-BC) est pris en charge à partir de la version 9.8 de ONTAP. La mise à niveau et la restauration de votre cluster ONTAP ont des implications sur vos relations SM-BC selon la version de ONTAP vers laquelle vous effectuez la mise à niveau ou la restauration.



== Mettez à niveau ONTAP

Avant de pouvoir configurer et utiliser SM-BC, vous devez mettre à niveau tous les nœuds des clusters source et de destination vers ONTAP 9.8 ou version ultérieure.
link:link:../upgrade/index.html["Mettez à niveau le logiciel sur les clusters ONTAP"]


NOTE: Le `snapmirror quiesce` et `snampirror resume` Les commandes ne sont pas prises en charge par SM-BC.

Lorsque vous mettez à niveau des clusters de la version 9.8 ou 9.9.1 vers la version 9.10.1, ONTAP crée de nouveaux groupes de cohérence sur la source et la destination pour les relations SM-BC. Ils peuvent être gérés dans System Manager sous l'option **groupes de cohérence** ou en utilisant l'API REST ONTAP avec le noeud final des groupes de cohérence.



== Restaurez ONTAP 9.9.1 à partir de ONTAP 9.10.1

Pour rétablir des relations de 9.10.1 à 9.9.1, les relations SM-BC doivent être supprimées, suivies de l'instance de groupe de cohérence 9.10.1. Impossible de supprimer les groupes de cohérence avec une relation SM-BC active. Tout volume FlexVol mis à niveau vers la version 9.10.1 précédemment associé à une autre application de conteneur intelligent ou d'entreprise en 9.9.1 ou version antérieure ne sera plus associé à la restauration. La suppression des groupes de cohérence ne supprime pas les volumes constitutifs ou les snapshots granulaires volume. Reportez-vous à la section link:../consistency-groups/delete-task.html["Supprimez un groupe de cohérence"] Pour plus d'informations sur cette tâche dans ONTAP 9.10.1 et versions ultérieures.



== Restaurez ONTAP 9.7 à partir de ONTAP 9.8


NOTE: SM-BC n'est pas pris en charge avec les clusters mixtes ONTAP 9.7 et ONTAP 9.8.

Lorsque vous restaurez ONTAP 9.8 vers ONTAP 9.7, vous devez tenir compte des éléments suivants :

* Si le cluster héberge une destination SM-BC, le retour à ONTAP 9.7 n'est pas autorisé tant que la relation n'est pas rompue et supprimée.
* Si le cluster héberge une source SM-BC, le retour à ONTAP 9.7 n'est pas autorisé tant que la relation n'est pas validée.
* Toutes les politiques SnapMirror personnalisées SM-BC créées par l'utilisateur doivent être supprimées avant de revenir à ONTAP 9.7.


Pour répondre à ces exigences, reportez-vous à la section link:smbc_admin_removing_an_smbc_configuration.html["Supprimer une configuration SM-BC"].

.Étapes
. Effectuer une vérification de restauration à partir de l'un des clusters de la relation SM-BC :
+
`cluster::*> system node revert-to -version 9.7 -check-only`

+
Exemple :

+
....
cluster::*> system node revert-to -version 9.7 -check-only
Error: command failed: The revert check phase failed. The following issues must be resolved before revert can be completed. Bring the data LIFs down on running vservers. Command to list the running vservers: vserver show -admin-state running Command to list the data LIFs that are up: network interface show -role data -status-admin up Command to bring all data LIFs down: network interface modify {-role data} -status-admin down
Disable snapshot policies.
    Command to list snapshot policies: "snapshot policy show".
    Command to disable snapshot policies: "snapshot policy modify -vserver
   * -enabled false"

   Break off the initialized online data-protection (DP) volumes and delete
   Uninitialized online data-protection (DP) volumes present on the local
   node.
    Command to list all online data-protection volumes on the local node:
   volume show -type DP -state online -node <local-node-name>
    Before breaking off the initialized online data-protection volumes,
   quiesce and abort transfers on associated SnapMirror relationships and
   wait for the Relationship Status to be Quiesced.
    Command to quiesce a SnapMirror relationship: snapmirror quiesce
    Command to abort transfers on a SnapMirror relationship: snapmirror
   abort
    Command to see if the Relationship Status of a SnapMirror relationship
   is Quiesced: snapmirror show
    Command to break off a data-protection volume: snapmirror break
    Command to break off a data-protection volume which is the destination
   of a SnapMirror relationship with a policy of type "vault": snapmirror
   break -delete-snapshots
    Uninitialized data-protection volumes are reported by the "snapmirror
   break" command when applied on a DP volume.
    Command to delete volume: volume delete

   Delete current version snapshots in advanced privilege level.
    Command to list snapshots: "snapshot show -fs-version 9.8"
    Command to delete snapshots: "snapshot prepare-for-revert -node
   <nodename>"

   Delete all user-created policies of the type active-strict-sync-mirror
   and active-sync-mirror.
   The command to see all active-strict-sync-mirror and active-sync-mirror
   type policies is:
    snapmirror policy show -type
   active-strict-sync-mirror,active-sync-mirror
   The command to delete a policy is :
    snapmirror policy delete -vserver <SVM-name> -policy <policy-name>
....


Pour plus d'informations sur le rétablissement des clusters, reportez-vous à la section link:../revert/index.html["Restaurez la ONTAP"].
