---
sidebar: sidebar 
permalink: smbc/smbc_install_creating_a_consistency_group_relationship.html 
keywords: SM-BC, SMBC, consistency group, create, constituent 
summary: Vous devez créer un groupe de cohérence SnapMirror qui établit également la relation de groupe de cohérence synchrone. 
---
= Créer une relation de groupe de cohérence
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous devez créer un groupe de cohérence SM-BC qui établit également la relation de groupe de cohérence synchrone.


NOTE: Ce flux de travail s'applique aux utilisateurs sous ONTAP 9.8 et 9.9.1. Si vous utilisez ces commandes de l'interface de ligne de commandes de ONTAP depuis ONTAP 9.10.1, elles continueront à fonctionner avec la création d'un groupe de cohérence, cependant, il est recommandé de gérer les groupes de cohérence avec System Manager ou l'API REST de ONTAP.

.Avant de commencer
Les conditions préalables et restrictions suivantes s'appliquent :

* Vous devez être un administrateur de cluster ou de machines virtuelles de stockage
* Vous devez disposer d'une licence SnapMirror synchrone
* Les volumes de destination doivent être de type DP
* La machine virtuelle de stockage primaire et secondaire doit être en relation peering
* Tous les volumes composant d'un groupe de cohérence doivent se trouver sur une seule machine virtuelle de stockage
* Vous ne pouvez pas établir de relations de groupe de cohérence SM-BC entre les clusters ASA et les clusters non ASA
* Le nom du groupe de cohérence doit être unique


.Description de la tâche
Vous devez créer la relation de groupe de cohérence à partir du cluster de destination. Vous pouvez mapper jusqu'à 12 composants à l'aide du `cg-item-mappings` sur le `snapmirror create` commande.

.Étapes
. Créer une relation de groupe de cohérence et de composant Cet exemple crée deux groupes de cohérence : cg_src avec les volumes constitutifs vol1 et vol2, et cg_dist avec les volumes constitutifs vol1_dr et vol2_dr.
+
`destination::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol_src1:@vol_dst1,vol_src2:@vol_dst2 -policy AutomatedFailOver`


