---
sidebar: sidebar 
permalink: smbc/smbc_plan_prerequisites.html 
keywords: SM-BC, SMBC, prerequisites, planning, software, hardware, licensing, protocols, network 
summary: 'Lorsque vous planifiez le déploiement d"une solution de continuité de l"activité SnapMirror, vous devez prendre en compte plusieurs critères.' 
---
= Prérequis
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Lors de la planification du déploiement de la continuité de l'activité SnapMirror, assurez-vous de répondre aux différentes exigences en matière de configuration du système, du matériel et des logiciels.



== Sous-jacent

* Seuls les clusters haute disponibilité à deux nœuds sont pris en charge
* Les deux clusters doivent être soit AFF (y compris AFF C-Series), soit ASA (pas de combinaison)




== Logiciel

* ONTAP 9.8 ou version ultérieure
* ONTAP Mediator 1.2 ou version ultérieure
* Un serveur Linux ou une machine virtuelle pour le médiateur ONTAP exécutant l'un des éléments suivants :


[cols="30,70"]
|===


| Version du médiateur ONTAP | Versions Linux prises en charge 


 a| 
1.6
 a| 
* Red Hat Enterprise Linux : 8.4, 8.5, 8.6, 8.7, 8.8, 9.0, 9.1, 9.2
* Rocky Linux 8 et 9




 a| 
1.5
 a| 
* Red Hat Enterprise Linux : 7.6, 7.7, 7.8, 7.9, 8.1 8.2 février 8.3, 8.4, 8.5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.4
 a| 
* Red Hat Enterprise Linux : 7.6, 7.7, 7.8, 7.9, 8.1 8.2 février 8.3, 8.4, 8.5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.3
 a| 
* Red Hat Enterprise Linux : 7.6, 7.7, 7.8, 7.9, 8.1 8.2 février 8.3
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.2
 a| 
* Red Hat Enterprise Linux : 7.6, 7.7, 7.8, 8.1
* CentOS: 7.6, 7.7, 7.8


|===


== Licences

* La licence synchrone SnapMirror (SM-S) doit être appliquée aux deux clusters
* La licence SnapMirror doit être appliquée aux deux clusters
+

NOTE: Si vous avez acheté vos systèmes de stockage ONTAP avant juin 2019, consultez la page link:https://mysupport.netapp.com/site/systems/master-license-keys["Clés de licence principales pour ONTAP NetApp"^] Pour obtenir la licence SM-S requise.





== Environnement de mise en réseau

* Le temps de réponse aller-retour de latence entre clusters doit être inférieur à 10 millisecondes.
* Les réservations persistantes SCSI-3 sont **non** prises en charge par SM-BC .




== Protocoles pris en charge

* Seuls les protocoles SAN sont pris en charge (pas NFS/SMB).
* Seuls les protocoles Fibre Channel et iSCSI sont pris en charge.
* L'IPspace par défaut est requis par SM-BC pour les relations cluster peer-to-peer. L'IPspace personnalisé n'est pas pris en charge.




== Style de sécurité NTFS

Le style de sécurité NTFS est *non* pris en charge sur les volumes SM-BC.



== Médiateur de ONTAP

* Le Mediator ONTAP peut être provisionné en externe et connecté à ONTAP pour un basculement transparent des applications.
* Pour fonctionner entièrement et permettre un basculement non planifié automatique, le médiateur ONTAP externe doit être provisionné et configuré avec des clusters ONTAP.
* Le médiateur ONTAP doit être installé dans un troisième domaine de défaillance, distinct des deux clusters ONTAP.
* Lors de l'installation du médiateur ONTAP, vous devez remplacer le certificat auto-signé par un certificat valide signé par une autorité de certification grand public fiable.
* Pour plus d'informations sur le médiateur ONTAP, reportez-vous à la section link:../mediator/index.html["Préparez-vous à installer le service ONTAP Mediator"].




== Volumes de destination en lecture/écriture

* Les relations SM-BC ne sont pas prises en charge sur les volumes de destination en lecture/écriture. Avant de pouvoir utiliser un volume en lecture-écriture, vous devez le convertir en volume DP en créant une relation SnapMirror au niveau du volume, puis en supprimant la relation. Pour plus de détails, voir link:smbc_admin_converting_existing_relationships_to_smbc.html["Conversion de relations existantes en relations SM-BC"]




== Des LUN de grande taille et de grands volumes

La prise en charge de LUN et de volumes importants (supérieurs à 100 To) dépend de la version de ONTAP que vous utilisez et de votre plateforme.

[role="tabbed-block"]
====
.ONTAP 9.12.1P2 et versions ultérieures
--
* Pour ONTAP 9.12.1 P2 et versions ultérieures, SMBC prend en charge les grandes LUN et les volumes de plus de 100 To sur ASA et AFF (y compris C-Series).



NOTE: Pour les versions ONTAP 9.12.1P2 et ultérieures, vous devez vous assurer que les clusters principal et secondaire sont tous deux des baies SAN ou 100 % Flash, et qu'ONTAP 9.12.1 P2 ou version ultérieure est installé sur les deux. Si le cluster secondaire exécute une version antérieure à ONTAP 9.12.1P2 ou si le type de baie n'est pas le même que le cluster principal, la relation synchrone peut être désynchronisée si le volume primaire dépasse 100 To.

--
.ONTAP 9.8 - 9.12.1P1
--
* Pour les versions ONTAP comprises entre ONTAP 9.8 et 9.12.1 P1 (inclus), les LUN de grande taille et les volumes de grande taille supérieurs à 100 To ne sont pris en charge que sur toutes les baies SAN.



NOTE: Pour les versions ONTAP comprises entre ONTAP 9.8 et 9.12.1 P2, vous devez vous assurer que les clusters principal et secondaire sont tous deux des baies SAN, et que ONTAP 9.8 ou version ultérieure est installé sur les deux. Si le cluster secondaire exécute une version antérieure à ONTAP 9.8 ou, s'il ne s'agit pas d'une baie SAN uniquement, la relation synchrone peut manquer de synchronisation si le volume primaire augmente de plus de 100 To.

--
====


== Plus d'informations

* link:https://hwu.netapp.com/["Hardware Universe"^]
* link:../mediator/mediator-overview-concept.html["Présentation du médiateur ONTAP"^]

