---
sidebar: sidebar 
permalink: smbc/smbc_plan_ontap_access_options.html 
keywords: SM-BC, SMBC, access options, CLI, command line interface, System Manager, REST API 
summary: 'Plusieurs options d"accès sont disponibles lors de la configuration des nœuds ONTAP participant à un déploiement SM- BC.' 
---
= Options d'accès ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Plusieurs options d'accès sont disponibles lors de la configuration des nœuds ONTAP participant à un déploiement SM- BC. Vous devez sélectionner l'option qui correspond le mieux à votre environnement et à vos objectifs de déploiement.


NOTE: Dans tous les cas, vous devez vous connecter à l'aide du compte administrateur avec un mot de passe valide.

Interface de ligne de commandes:: L'interface de ligne de commande texte est disponible via le shell de gestion ONTAP. Vous pouvez accéder à l'interface de ligne de commande à l'aide du shell sécurisé (SSH).
System Manager:: Vous pouvez vous connecter à System Manager à l'aide d'un navigateur Web moderne. L'interface Web fournit une interface intuitive et facile d'utilisation lors de l'accès à la fonctionnalité de continuité de l'activité SnapMirror. Pour plus d'informations sur l'utilisation de System Manager, reportez-vous à la section https://docs.netapp.com/us-en/ontap/["Documentation de System Manager"^].
API REST:: L'API REST ONTAP exposée aux clients externes fournit une autre option lors de la connexion à ONTAP. Vous pouvez accéder à l'API à l'aide de n'importe quel langage ou outil de programmation standard prenant en charge les services Web REST. Parmi les choix les plus populaires :
+
--
* Python (y compris la bibliothèque client Python ONTAP)
* Java
* Gondolage


--


L'utilisation d'un langage de programmation ou de script permet d'automatiser le déploiement et la gestion d'un déploiement de continuité de l'activité SnapMirror. Pour plus d'informations, consultez la page de documentation en ligne de ONTAP sur votre système de stockage ONTAP.
