---
permalink: s3-audit/modify-config-task.html 
sidebar: sidebar 
keywords: s3 audit, modify 
summary: 'Vous pouvez modifier les paramètres d"audit de compartiments individuels ou la configuration d"audit de toutes les compartiments sélectionnés pour l"audit dans la SVM.' 
---
= Modifiez la configuration d'audit ONTAP S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier les paramètres d'audit de compartiments individuels ou la configuration d'audit de toutes les compartiments sélectionnés pour l'audit dans la SVM.

[cols="2,4"]
|===
| Si vous souhaitez modifier la configuration d'audit pour... | Entrer... 


| Seaux individuels | `vserver object-store-server audit event-selector modify -vserver _svm_name_ [-bucket _bucket_name_] [_parameters to modify_]` 


| Tous les compartiments du SVM  a| 
`vserver object-store-server audit modify -vserver _svm_name_ [_parameters to modify_]`

|===
.Exemples
L'exemple suivant modifie la configuration d'audit de compartiment individuel pour auditer uniquement les événements d'accès en écriture :

[listing]
----
cluster1::> vserver object-store-server audit event-selector modify -vserver vs1 -bucket test-bucket -access write-only
----
L'exemple suivant modifie la configuration d'audit de tous les buckets du SVM de manière à définir la taille limite des logs à 10 Mo et à conserver 3 fichiers journaux avant de faire pivoter.

[listing]
----
cluster1::> vserver object-store-server audit modify -vserver vs1 -rotate-size 10MB -rotate-limit 3
----