---
permalink: s3-audit/select-buckets-task.html 
sidebar: sidebar 
keywords: s3 audit, select, buckets 
summary: 'Vous devez spécifier les compartiments à auditer dans une SVM activée par l"audit.' 
---
= Sélectionnez des compartiments pour l'audit S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez spécifier les compartiments à auditer dans une SVM activée par l'audit.

.Ce dont vous avez besoin
* SVM activé pour l'audit S3.


.Description de la tâche
Les configurations d'audit S3 sont activées par SVM, mais vous devez sélectionner les compartiments des SVM activés pour l'audit. Si vous ajoutez des compartiments au SVM et que vous souhaitez auditer les nouveaux compartiments, vous devez les sélectionner avec cette procédure. Vous pouvez également disposer de compartiments non audités dans une SVM activée pour l'audit de S3.

Les configurations d'audit restent conservées pour les compartiments jusqu'à ce qu'elles soient supprimées par le `vserver object-store-server audit object-select delete` commande.

.Procédure
Sélectionner un compartiment pour l'audit S3 :

`vserver object-store-server audit event-selector create -vserver _svm_name_ -bucket _bucket_name_ [[-access] {read-only|write-only|all}] [[-permission] {allow-only|deny-only|all}]`

* `-access` - spécifie le type d'accès aux événements à auditer : `read-only`, `write-only` ou `all` (la valeur par défaut est `all`).
* `-permission` - spécifie le type d'autorisation d'événement à auditer : `allow-only`, `deny-only` ou `all` (la valeur par défaut est `all`).


.Exemple
L'exemple suivant crée une configuration d'audit de compartiment qui connecte uniquement les événements autorisés avec un accès en lecture seule :

`cluster1::> vserver object-store-server audit event-selector create -vserver vs1 -bucket test-bucket -access read-only -permission allow-only`
