---
permalink: s3-audit/show-config-task.html 
sidebar: sidebar 
keywords: s3 audit, show, display 
summary: 'Dans cette tâche, vous apprendrez à afficher des informations sur les audits s3 avec l"interface de ligne de commandes.' 
---
= Affiche les configurations d'audit S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois la configuration d'audit terminée, vous pouvez vérifier que l'audit est correctement configuré et activé. Vous pouvez également afficher des informations sur toutes les configurations d'audit du magasin d'objets du cluster.

.Description de la tâche
Vous pouvez afficher des informations sur les configurations d'audit de compartiment et SVM.

* Godets : utilisez le `vserver object-store-server audit event-selector show` commande
+
Sans aucun paramètre, la commande affiche les informations suivantes sur les compartiments de tous les SVM du cluster avec des configurations d'audit de magasin d'objets :

+
** Nom du SVM
** Nom du compartiment
** Valeurs d'accès et d'autorisation


* SVM : utilisez le `vserver object-store-server audit show` commande
+
Sans aucun paramètre, la commande affiche les informations suivantes sur tous les SVM du cluster avec des configurations d'audit du magasin d'objets :

+
** Nom du SVM
** État d'audit
** Répertoire cible




Vous pouvez spécifier le `-fields` paramètre pour spécifier les informations de configuration d'audit à afficher.

.Procédure
Afficher des informations sur les configurations d'audit S3 :

[cols="2,4"]
|===
| Si vous souhaitez modifier la configuration pour... | Entrer... 


| Seaux | `vserver object-store-server audit event-selector show [-vserver _svm_name_] [_parameters_]` 


| SVM  a| 
`vserver object-store-server audit show [-vserver _svm_name_] [_parameters_]`

|===
.Exemples
L'exemple suivant affiche les informations pour un seul compartiment :

[listing]
----
cluster1::> vserver object-store-server audit event-selector show -vserver vs1 -bucket test-bucket
     Vserver     Bucket     Access          Permission
     ----------- ---------- --------------- ----------
     vs1         bucket1    read-only       allow-only
----
L'exemple suivant affiche les informations pour toutes les compartiments d'un SVM :

[listing]
----
cluster1::> vserver object-store-server audit event-selector show -vserver vs1

     Vserver           :vs1
     Bucket            :test-bucket
     Access            :all
     Permission        :all
----
L'exemple suivant affiche le nom, l'état d'audit, les types d'événements, le format du journal et le répertoire cible de tous les SVM.

[listing]
----
cluster1::> vserver object-store-server audit show

Vserver     State  Event Types Log Format Target Directory
----------- ------ ----------- ---------- --------------------
vs1         false  data        json       /audit_log
----
L'exemple suivant affiche les noms des SVM et des détails sur le journal d'audit de tous les SVM.

[listing]
----
cluster1::> vserver object-store-server audit show -log-save-details

                  Rotation                           Rotation
      Vserver     File Size Rotation Schedule        Limit
      ----------- --------- ------------------------ --------
      vs1         100MB     -                        0
----
L'exemple suivant s'affiche sous forme de liste toutes les informations de configuration d'audit relatives à tous les SVM.

[listing]
----
cluster1::> vserver object-store-server audit show -instance

                             Vserver: vs1
                      Auditing state: true
                Log Destination Path: /audit_log
       Categories of Events to Audit: data
                          Log Format: json
                 Log File Size Limit: 100MB
        Log Rotation Schedule: Month: -
  Log Rotation Schedule: Day of Week: -
          Log Rotation Schedule: Day: -
         Log Rotation Schedule: Hour: -
       Log Rotation Schedule: Minute: -
                  Rotation Schedules: -
            Log Files Rotation Limit: 0
                  Log Retention Time: 0s
----