---
sidebar: sidebar 
permalink: s3-snapmirror/requirements-cloud-targets-concept.html 
keywords: requirements for cloud target relationships 
summary: Vérifiez que vos environnements source et cible répondent aux exigences de protection des sauvegardes S3 SnapMirror vers les cibles dans le cloud. 
---
= Exigences relatives aux relations cibles cloud
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/
:toc-position: content


[role="lead"]
Vérifiez que vos environnements source et cible répondent aux exigences de protection des sauvegardes S3 SnapMirror vers les cibles dans le cloud.

Pour accéder au compartiment de données, vous devez disposer d'identifiants de compte valides auprès du fournisseur de magasin d'objets.

Les interfaces réseau intercluster et un IPspace doivent être configurées sur le cluster avant que le cluster ne puisse se connecter à un magasin d'objets cloud. Vous devez créer des interfaces réseau du cluster sur chaque nœud pour transférer les données de manière transparente du stockage local vers le magasin d'objets cloud.

Pour les cibles StorageGRID, vous devez connaître les informations suivantes :

* Nom du serveur, exprimé sous forme de nom de domaine complet (FQDN) ou d'adresse IP
* nom de compartiment : ce compartiment doit déjà exister
* touche d'accès
* clé secrète


En outre, le certificat d'autorité de certification utilisé pour signer le certificat de serveur StorageGRID doit être installé sur la machine virtuelle de stockage d'administration du cluster ONTAP S3 à l'aide de `security certificate install command`. Pour plus d'informations, voir link:../fabricpool/install-ca-certificate-storagegrid-task.html["Installation d'un certificat CA"]  Si vous utilisez StorageGRID.

Pour les cibles AWS S3, vous devez connaître les informations suivantes :

* Nom du serveur, exprimé sous forme de nom de domaine complet (FQDN) ou d'adresse IP
* nom de compartiment : ce compartiment doit déjà exister
* touche d'accès
* clé secrète


Le serveur DNS de la machine virtuelle de stockage admin du cluster ONTAP doit être capable de résoudre les FQDN (si utilisé) aux adresses IP.
