---
sidebar: sidebar 
permalink: s3-snapmirror/requirements-cloud-targets-concept.html 
keywords: requirements for cloud target relationships, ontap s3, snapmirror, s3, cloud target 
summary: Assurez-vous que vos environnements source et cible respectent les exigences de protection de sauvegarde SnapMirror S3 sur des cibles cloud. 
---
= Conditions requises pour les relations ONTAP SnapMirror S3 Cloud cible
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Assurez-vous que vos environnements source et cible respectent les exigences de protection de sauvegarde SnapMirror S3 sur des cibles cloud.

Pour accéder au compartiment de données, vous devez disposer d'identifiants de compte valides auprès du fournisseur de magasin d'objets.

Les LIF intercluster et un IPspace doivent être configurés sur le cluster avant que le cluster ne puisse se connecter à un magasin d'objets cloud. Vous devez créer des LIF intercluster sur chaque nœud afin de transférer de manière transparente les données du stockage local vers le référentiel de stockage en mode objet cloud.

Pour les cibles StorageGRID, vous devez connaître les informations suivantes :

* Nom du serveur, exprimé sous forme de nom de domaine complet (FQDN) ou d'adresse IP
* nom de compartiment : ce compartiment doit déjà exister
* touche d'accès
* clé secrète


De plus, le certificat CA utilisé pour signer le certificat du serveur StorageGRID doit être installé sur la machine virtuelle de stockage d'administration du cluster ONTAP S3 à l'aide de  `security certificate install` commande. Pour plus d'informations, reportez-vous à link:../fabricpool/install-ca-certificate-storagegrid-task.html["Installation d'un certificat CA"] la section  si vous utilisez StorageGRID.

Pour les cibles AWS S3, vous devez connaître les informations suivantes :

* Nom du serveur, exprimé sous forme de nom de domaine complet (FQDN) ou d'adresse IP
* nom de compartiment : ce compartiment doit déjà exister
* touche d'accès
* clé secrète


Le serveur DNS de la machine virtuelle de stockage admin du cluster ONTAP doit pouvoir résoudre les noms de domaine complets (s'ils sont utilisés) en adresses IP.

.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-install.html["installation du certificat de sécurité"^]

