---
permalink: nvme/convert-namespace-to-lun-task.html 
sidebar: sidebar 
keywords: nvme, convert, namespace, lun 
summary: 'Depuis la version ONTAP 9.11.1, vous pouvez utiliser l"interface de ligne de commandes ONTAP pour convertir un espace de noms NVMe existant en LUN sans déplacement.' 
---
= Convertir un namespace en LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis la version ONTAP 9.11.1, vous pouvez utiliser l'interface de ligne de commandes ONTAP pour convertir un espace de noms NVMe existant en LUN sans déplacement.



== Avant de commencer

* L'espace de noms NVMe spécifié ne doit pas disposer d'aucun mappage existant à un sous-système.
* L'espace de noms ne doit pas faire partie d'un snapshot ou du côté destination de la relation SnapMirror comme un espace de noms en lecture seule.
* Les espaces de noms NVMe ne sont pris en charge qu'avec des plates-formes spécifiques et des cartes réseau, cette fonctionnalité ne fonctionne qu'avec du matériel spécifique.


.Étapes
. Entrez la commande suivante pour convertir un namespace NVMe en LUN :
+
`lun convert-from-namespace -vserver -namespace-path`


