---
permalink: nvme/disable-secure-authentication-nvme-tcp-task.html 
sidebar: sidebar 
keywords: manage, nvme, secure, authentication, tcp, dh-hmac-hcap, chap, disable 
summary: 'Depuis la version ONTAP 9.12.1, l"authentification bidirectionnelle et sécurisée entre un hôte et un contrôleur NVMe est prise en charge par le protocole d"authentification DH-HMAC-CHAP.   ' 
---
= Désactivez l'authentification sécurisée sur NVMe/TCP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous exécutez le protocole NVMe/TCP et que vous avez établi une authentification sécurisée à l'aide de DH-HMAC-CHAP, vous pouvez choisir de la désactiver à tout moment.

Cependant, si vous restaurez ONTAP 9.12.1 ou version ultérieure vers ONTAP 9.12.0 ou version antérieure, vous devez désactiver l'authentification sécurisée avant de procéder à une restauration.  Si l'authentification sécurisée à l'aide de DH-HMAC-CHAP n'est pas désactivée, la restauration échoue.

.Étapes
. Supprimez l'hôte du sous-système pour désactiver l'authentification DH-HMAC-CHAP :
+
`vserver nvme subsystem host remove –vserver _svm_name_ -subsystem _subsystem_ -host-nqn _host_nqn_`

. Vérifiez que le protocole d'authentification DH-HMAC-CHAP est supprimé de l'hôte :
+
`vserver nvme subsystem host show`

. Ajoutez l'hôte au sous-système sans authentification :
+
`vserver nvme subsystem host add –vserver _svm_name_ -subsystem _subsystem_ -host-nqn _host_nqn_`


