---
permalink: nvme/set-up-tls-secure-channel-nvme-task.html 
sidebar: sidebar 
keywords: manage, nvme, secure, encryption, in-flight, tls secure channel, tcp, tls, encrypt, enable, set up 
summary: À partir de ONTAP 9.16.1, vous pouvez activer et désactiver le canal sécurisé TLS pour les connexions NVMe/TCP. 
---
= Configuration du canal sécurisé TLS pour NVMe/TCP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À partir de ONTAP 9.16.1, vous pouvez configurer le canal sécurisé TLS pour les connexions NVMe/TCP. Vous pouvez utiliser System Manager ou l'interface de ligne de commandes de ONTAP pour ajouter un nouveau sous-système NVMe avec TLS activé ou activer TLS pour un sous-système NVMe existant.

[role="tabbed-block"]
====
.System Manager
--
Depuis la version ONTAP 9.16.1, vous pouvez utiliser System Manager pour configurer TLS pour les connexions NVMe/TCP lors de la création ou de la mise à jour d'un sous-système NVMe, de la création ou du clonage d'espaces de noms NVMe, ou de l'ajout de groupes de cohérence avec de nouveaux espaces de noms NVMe.

.Étapes
. Dans System Manager, cliquez sur *hosts > NVMe Subsystem*, puis sur *Add*.
. Ajoutez le nom du sous-système NVMe, puis sélectionnez la VM de stockage et le système d'exploitation hôte.
. Saisissez le NQN hôte.
. Sélectionnez *exiger le protocole TLS (transport Layer Security)* en regard du NQN hôte.
. Fournissez la clé pré-partagée (PSK).
. Cliquez sur *Enregistrer*.
. Pour vérifier que le canal sécurisé TLS est activé, sélectionnez *System Manager > hosts > NVMe Subsystem > Grid > Peek View*.


--
.CLI
--
.Étapes
. Ajoutez un hôte de sous-système NVMe qui prend en charge le canal sécurisé TLS. Vous pouvez fournir une clé pré-partagée (PSK) en utilisant le  `tls-configured-psk` argument:
+
[source, cli]
----
vserver nvme subsystem host add -vserver <svm_name> -subsystem <subsystem> -host-nqn <host_nqn> -tls-configured-psk <key_text>
----
. Vérifiez que l'hôte du sous-système NVMe est configuré pour le canal sécurisé TLS. Vous pouvez éventuellement utiliser l' `tls-key-type`argument pour afficher uniquement les hôtes qui utilisent ce type de clé :
+
[source, cli]
----
vserver nvme subsystem host show -vserver <svm_name> -subsystem <subsystem> -host-nqn <host_nqn> -tls-key-type {none|configured}
----
. Vérifiez que le contrôleur hôte du sous-système NVMe est configuré pour le canal sécurisé TLS. Vous pouvez éventuellement utiliser l'un des `tls-key-type` arguments , `tls-identity` ou `tls-cipher` pour afficher uniquement les contrôleurs ayant ces attributs TLS :
+
[source, cli]
----
vserver nvme subsystem controller show -vserver <svm_name> -subsystem <subsystem> -host-nqn <host_nqn> -tls-key-type {none|configured} -tls-identity <text> -tls-cipher {none|TLS_AES_128_GCM_SHA256|TLS_AES_256_GCM_SHA384}
----


--
====
.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+nvme+subsystem["sous-système nvme vserver"^]

