= 
:allow-uri-read: 


[role="lead"]
Vous pouvez utiliser un ou plusieurs serveurs KMIP pour sécuriser les clés que le cluster utilise pour accéder aux données chiffrées. Vous pouvez connecter jusqu'à quatre serveurs KMIP à un nœud. Un minimum de deux serveurs est recommandé pour la redondance et la reprise après sinistre.

.Ce dont vous avez besoin, 8217;ll
* Les certificats client SSL KMIP et serveur doivent avoir été installés.
* Vous devez être un administrateur de cluster pour effectuer cette tâche.
* Vous devez configurer l'environnement MetroCluster avant de configurer un gestionnaire de clés externe.


ONTAP configure la connectivité du serveur KMIP pour tous les nœuds du cluster.

.Étapes
. Configurer la connectivité du gestionnaire de clés pour les nœuds du cluster :
+
`security key-manager setup`

+
La configuration du gestionnaire de clés démarre.

. Entrez la réponse appropriée à chaque invite.
. Ajoutez un serveur KMIP :
+
`security key-manager add -address key_management_server_ipaddress`

+
[listing]
----
clusterl::> security key-manager add -address 20.1.1.1
----
. Ajoutez un serveur KMIP supplémentaire pour la redondance :
+
`security key-manager add -address key_management_server_ipaddress`

+
[listing]
----
clusterl::> security key-manager add -address 20.1.1.2
----
. Vérifiez que tous les serveurs KMIP configurés sont connectés :
+
`security key-manager show -status`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
[listing]
----
cluster1::> security key-manager show -status

Node            Port      Registered Key Manager  Status
--------------  ----      ----------------------  ---------------
cluster1-01     5696      20.1.1.1                available
cluster1-01     5696      20.1.1.2                available
cluster1-02     5696      20.1.1.1                available
cluster1-02     5696      20.1.1.2                available
----

