---
sidebar: sidebar 
permalink: networking/change_the_mtu_value_for_ports_in_a_broadcast_domain.html 
keywords: modify, modifying, mtu, mtu_value, change, changing, broadcast, domain, ports, port, change the mtu value for ports in a broadcast domain 
summary: 'Modifiez la valeur MTU d"un domaine de diffusion pour modifier cette valeur pour tous les ports du domaine de diffusion' 
---
= Modifiez la valeur MTU des ports d'un domaine de diffusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez modifier la valeur MTU d'un domaine de diffusion pour modifier la valeur MTU de tous les ports de ce domaine de diffusion. Cela peut être fait pour prendre en charge les modifications de topologie effectuées sur le réseau.

.Avant de commencer
La valeur MTU doit correspondre à tous les périphériques connectés à ce réseau de couche 2, à l'exception du trafic de gestion du port e0M.

.Description de la tâche
La modification de la valeur MTU entraîne une brève interruption du trafic sur les ports affectés. Le système affiche une invite vous demandant de répondre par y pour effectuer la modification de la MTU.

.Étape
Modifier la valeur MTU pour tous les ports d'un domaine de diffusion :

....
network port broadcast-domain modify -broadcast-domain <broadcast_domain_name> -mtu <mtu_value> [-ipspace <ipspace_name>]
....
* `broadcast_domain` est le nom du domaine de diffusion.
* `mtu` Est la taille de MTU des paquets IP ; 1500 et 9000 sont des valeurs types.
* `ipspace` Est le nom de l'IPspace dans lequel réside ce domaine de diffusion. L'IPspace par défaut est utilisé sauf si vous spécifiez une valeur pour cette option. La commande suivante remplace la MTU sur 9000 pour tous les ports du broadcast domain bcast1 :


....
network port broadcast-domain modify -broadcast-domain <Default-1> -mtu < 9000 >
Warning: Changing broadcast domain settings will cause a momentary data-serving interruption.
Do you want to continue? {y|n}: <y>
....