---
sidebar: sidebar 
permalink: networking/commands_for_managing_snmp.html 
keywords: snmp, traps, traphosts, trap, traphost, manage, managing, users, user, configure, configuring, modify, modifying, set, setting, event, command, system snmp, security, options -option-name snmp.enable -option-value on, options -option-name snmp.enable -option-value off, commands for managing snmp, commands for managing snmp v1, v2c, and v3 users, commands for providing contact and location information, commands for managing SNMP communities, command for displaying snmp option values, commands for managing snmp traps and traphosts, commands for managing events related to snmp traps, system snmp, security login create, security snmpusers and security login show -application snmp, security login create, security login delete, security snmpusers and security login show -application snmp, security login modify, system snmp contact, system snmp location, system snmp community add, system snmp community delete, system snmp community show, system snmp show 
summary: 'Gérez les SNMP, les utilisateurs SNMP, les interruptions, les événements d"interruption et les Traphosts' 
---
= Commandes pour la gestion de SNMP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser le `system snmp` Commandes permettant de gérer SNMP, les traps et les Traphosts. Vous pouvez utiliser le `security` Commandes permettant de gérer les utilisateurs SNMP par SVM. Vous pouvez utiliser le `event` Commandes pour gérer les événements liés aux traps SNMP.



== Commandes permettant de configurer SNMP

|===


| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Activez SNMP sur le cluster
 a| 
`options -option-name snmp.enable -option-value on`

Le service SNMP doit être autorisé conformément à la politique de pare-feu de gestion. Vous pouvez vérifier si le protocole SNMP est autorisé via la commande system services firewall policy show.



 a| 
Désactiver le protocole SNMP sur le cluster
 a| 
`options -option-name snmp.enable -option-value off`

|===


== Commandes pour la gestion des utilisateurs SNMP v1, v2c et v3

|===


| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Configurez les utilisateurs SNMP
 a| 
`security login create`



 a| 
Afficher les utilisateurs SNMP
 a| 
`security snmpusers and security login show -application snmp`



 a| 
Supprimer les utilisateurs SNMP
 a| 
`security login delete`



 a| 
Modifier le nom du rôle de contrôle d'accès d'une méthode de connexion pour les utilisateurs SNMP
 a| 
`security login modify`

|===


== Commandes permettant de fournir des informations de contact et d'emplacement

|===


| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Afficher ou modifier les détails du contact du cluster
 a| 
`system snmp contact`



 a| 
Afficher ou modifier les détails d'emplacement du cluster
 a| 
`system snmp location`

|===


== Commandes pour la gestion des communautés SNMP

|===


| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Ajoutez une communauté en lecture seule (ro) pour un SVM ou pour tous les SVM du cluster
 a| 
`system snmp community add`



 a| 
Supprimer une communauté ou toutes les communautés
 a| 
`system snmp community delete`



 a| 
Afficher la liste de toutes les communautés
 a| 
`system snmp community show`

|===
Les SVM ne faisant pas partie de la norme SNMP, les requêtes relatives aux LIF de données doivent inclure l'OID racine NetApp (1.3.6.1.4.1.789), par exemple. `snmpwalk -v 2c -c snmpNFS 10.238.19.14 1.3.6.1.4.1.789`.



== Commande pour l'affichage des valeurs d'option SNMP

|===


| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Afficher les valeurs actuelles de toutes les options SNMP, y compris le contact de cluster, l'emplacement de contact, si le cluster est configuré pour envoyer des traps, la liste des Traphosts, la liste des communautés et le type de contrôle d'accès
 a| 
`system snmp show`

|===


== Commandes pour la gestion des interruptions SNMP et des Traphosts

|===


| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Activer les traps SNMP envoyés depuis le cluster
 a| 
`system snmp init -init 1`



 a| 
Désactiver les traps SNMP envoyés depuis le cluster
 a| 
`system snmp init -init 0`



 a| 
Ajoutez un Traphost qui reçoit des notifications SNMP pour des événements spécifiques dans le cluster
 a| 
`system snmp traphost add`



 a| 
Supprimer un Traphost
 a| 
`system snmp traphost delete`



 a| 
Affiche la liste des Traphosts
 a| 
`system snmp traphost show`

|===


== Commandes pour la gestion des événements liés aux traps SNMP

|===


| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Afficher les événements pour lesquels des interruptions SNMP (intégrées) sont générées
 a| 
`event route show`

Utilisez le `-snmp-support true` Paramètre pour afficher uniquement les événements SNMP.

Utilisez le `instance -messagename <message>` paramètre permettant d'afficher une description détaillée de la raison d'un événement et de toute action corrective.

Le routage des événements de déroutement SNMP individuels vers des destinations de traphost spécifiques n'est pas pris en charge. Tous les événements de déroutement SNMP sont envoyés à toutes les destinations de Traphost.



 a| 
Affiche la liste des enregistrements de l'historique des interruptions SNMP, qui sont des notifications d'événements envoyées à des interruptions SNMP
 a| 
`event snmphistory show`



 a| 
Supprimer un enregistrement de l'historique des interruptions SNMP
 a| 
`event snmphistory delete`

|===
Pour plus d'informations sur le `system snmp`, `security`, et `event` reportez-vous à la section link:http://docs.netapp.com/us-en/ontap-cli["Référence de commande ONTAP 9"^].
