---
sidebar: sidebar 
permalink: networking/commands_for_managing_failover_groups_and_policies.html 
keywords: manage, managing, failover, fail, over, group, policy, policies, groups, commands for managing failover groups and policies, network interface failover-groups, network interface modify, network interface failover-groups add-targets, network interface failover-groups remove-targets, network interface failover-groups modify, network interface modify -failover-group -failover-policy, network interface failover-groups show, rename, delete 
summary: Gérer les groupes de basculement 
---
= Commandes pour la gestion des groupes et des règles de basculement dans ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `network interface failover-groups` commandes permettant de gérer les groupes de basculement. Vous utilisez le `network interface modify` Commande permettant de gérer les groupes de basculement et les règles de basculement appliquées à une LIF.

|===


| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Ajout de ports réseau à un groupe de basculement
 a| 
`network interface failover-groups add-targets`



 a| 
Supprime les ports réseau d'un groupe de basculement
 a| 
`network interface failover-groups remove-targets`



 a| 
Modifier les ports réseau d'un failover group
 a| 
`network interface failover-groups modify`



 a| 
Afficher les groupes de basculement actuels
 a| 
`network interface failover-groups show`



 a| 
Configurer le basculement sur un LIF
 a| 
`network interface modify -failover-group -failover-policy`



 a| 
Afficher le failover group et la policy de failover utilisés par chaque LIF
 a| 
`network interface show -fields failover-group, failover-policy`



 a| 
Renommer un groupe de basculement
 a| 
`network interface failover-groups rename`



 a| 
Supprime un groupe de basculement
 a| 
`network interface failover-groups delete`

|===

NOTE: La modification d'un groupe de basculement de manière à ce qu'il n'assure pas une cible de basculement valide pour une LIF du cluster peut entraîner une panne lorsqu'une LIF tente de basculer.

Pour en savoir plus sur `network interface failover-groups` et `network interface modify` dans le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["Référence de commande ONTAP"^].
