---
sidebar: sidebar 
permalink: networking/commands_for_managing_firewall_service_and_policies.html 
keywords: manage, managing, firewall, fire, wall, service, policy, policies, commands for managing firewall service and policies, system services firewall, system services firewall policy, network interface modify, system services firewall modify, system services firewall show, system services firewall policy create, network interface modify -lif lifname -firewall-policy, system services firewall policy modify, system services firewall policy show, system services firewall policy clone, system services firewall policy delete 
summary: Gérer le service de pare-feu 
---
= Commandes permettant de gérer le service et les politiques de pare-feu
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez utiliser le `system services firewall` commandes permettant de gérer le service de pare-feu, le `system services firewall policy` commandes pour gérer les politiques de pare-feu et `network interface modify` Commande permettant de gérer les paramètres de pare-feu des LIF.

|===


| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Activez ou désactivez le service de pare-feu
 a| 
`system services firewall modify`



 a| 
Affiche la configuration actuelle du service de pare-feu
 a| 
`system services firewall show`



 a| 
Créez une politique de pare-feu ou ajoutez un service à une politique de pare-feu existante
 a| 
`system services firewall policy create`



 a| 
Appliquer une politique de pare-feu à une LIF
 a| 
`network interface modify -lif lifname -firewall-policy`



 a| 
Modifiez les adresses IP et les masques de réseau associés à une politique de pare-feu
 a| 
`system services firewall policy modify`



 a| 
Affiche des informations sur les politiques de pare-feu
 a| 
`system services firewall policy show`



 a| 
Créez une nouvelle politique de pare-feu qui est une copie exacte d'une politique existante
 a| 
`system services firewall policy clone`



 a| 
Supprimez une politique de pare-feu qui n'est pas utilisée par une LIF
 a| 
`system services firewall policy delete`

|===
Pour plus d'informations, consultez les pages de manuel du `system services firewall`, `system services firewall policy`, et `network interface modify` commandes dans link:http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Commandes ONTAP 9"^].
