---
sidebar: sidebar 
permalink: networking/configure_failover_groups_and_policies_for_lifs_overview.html 
keywords: lif, failover, fail, over, target, automatic, automatically, port, link, failure, group, broadcast, domain, lif failover is the automatic migration of a lif to a different network port in response to a link failure, configure failover groups and policies for lifs overview, network interface show -failover 
summary: 'Le basculement de LIF est la migration automatique d"une LIF vers un autre port réseau en réponse à une défaillance de liaison' 
---
= Présentation du basculement de LIF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Le basculement de LIF désigne la migration automatique d'une LIF vers un autre port réseau en réponse à une défaillance de liaison sur le port actuel de la LIF. Ce composant clé assure la haute disponibilité des connexions aux SVM. La configuration du basculement de LIF implique la création d'un groupe de basculement, la modification de la LIF afin d'utiliser le groupe de basculement et la spécification d'une règle de basculement.

Un failover group contient un ensemble de ports réseau (ports physiques, VLAN et groupes d'interfaces) à partir d'un ou de plusieurs nœuds d'un cluster. Les ports réseau présents dans le failover group définissent les cibles de failover disponibles pour le LIF. Un groupe de basculement peut disposer des LIF de données intercluster, node management, et NAS qui y sont attribuées.


IMPORTANT: Lorsqu'une LIF est configurée sans une cible de basculement valide, une panne se produit lorsque la LIF tente de basculer. Vous pouvez utiliser la commande « network interface show -Failover » pour vérifier la configuration du basculement.

Lorsque vous créez un broadcast domain, un failover group du même nom est créé automatiquement contenant les mêmes ports réseau. Ce failover group est automatiquement géré par le système, ce qui signifie qu'à mesure que des ports sont ajoutés ou supprimés du broadcast domain, ils sont automatiquement ajoutés ou supprimés de ce failover group. Cela est fourni comme une efficacité pour les administrateurs qui ne souhaitent pas gérer leurs propres groupes de basculement.
