---
sidebar: sidebar 
permalink: networking/configure_ipspaces_@cluster_administrators_only@_overview.html 
keywords: ipspace, ipspaces, introduction, introducing, overview, ipv4, ipv6, routing, route, domain, configure ipspaces overview 
summary: 'Un IPspace définit un espace d"adresse IP distinct dans lequel les SVM (Storage Virtual machines) résident' 
---
= Présentation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les IPspaces permettent de configurer un cluster ONTAP unique afin d'y accéder aux clients à partir de plusieurs domaines réseau distincts d'un point de vue administratif, même si ces clients utilisent la même plage de sous-réseau d'adresses IP. Cela permet de séparer le trafic client pour des raisons de confidentialité et de sécurité.

Un IPspace définit un espace d'adresse IP distinct dans lequel les SVM (Storage Virtual machines) résident. Les ports et les adresses IP définis pour un IPspace ne sont applicables qu'au sein de cet IPspace. Une table de routage distincte est conservée pour chaque SVM au sein d'un IPspace. Par conséquent, aucun routage de trafic cross-SVM ou cross-IPspace n'a lieu.


NOTE: Les IPspaces prennent en charge les adresses IPv4 et IPv6 sur leurs domaines de routage.

Si vous gérez le stockage pour une seule organisation, vous n'avez pas besoin de configurer les IPspaces. Si vous gérez le stockage de plusieurs entreprises sur un même cluster ONTAP, et qu'aucun de vos clients n'a de configurations réseau contradictoires, vous n'avez également besoin d'utiliser les IPspaces. Dans de nombreux cas, l'utilisation de machines virtuelles de stockage (SVM), avec leurs propres tables de routage IP distinctes, peut être utilisée pour isoler les configurations réseau uniques au lieu d'utiliser les IPspaces.
