---
sidebar: sidebar 
permalink: networking/configure_broadcast_domains_@cluster_administrators_only@_overview.html 
keywords: broadcast, domain, overview, introduction, introducing, configure broadcast domains overview for ontap 9.8 and later, broadcast domains group network ports that belong to the same layer 2 network 
summary: Les domaines de diffusion regroupent des ports réseau qui appartiennent au même réseau de couche 2 
---
= À propos des domaines de diffusion pour ONTAP 9.8 et versions ultérieures
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les domaines de diffusion sont destinés à regrouper les ports réseau qui appartiennent au même réseau de couche 2. Les ports du groupe peuvent ensuite être utilisés par une machine virtuelle de stockage (SVM) pour le trafic de données ou de gestion.

Un domaine de diffusion réside dans un IPspace. Lors de l'initialisation du cluster, le système crée deux broadcast domain :

* Le broadcast domain « Default » contient les ports qui sont dans le « Default » IPspace.
+
Ces ports servent principalement à transmettre des données. Les ports de management des clusters et de management des nœuds sont également présents dans ce broadcast domain.

* Le broadcast domain « Cluster » contient les ports qui sont dans le « Cluster » IPspace.
+
Ces ports sont utilisés pour la communication de cluster et incluent tous les ports de cluster de tous les nœuds du cluster.

+
Le système crée des domaines de diffusion supplémentaires dans l'IPspace par défaut si nécessaire. Le broadcast domain « Default » contient le home-port de la LIF de gestion, ainsi que tous les autres ports qui ont une accessibilité de couche 2 à ce port. Les domaines de diffusion supplémentaires sont nommés « default-1 », « default-2 », etc.


