---
sidebar: sidebar 
permalink: networking/configure_failover_settings_on_a_lif.html 
keywords: configure, configuring, configuration, setup, set, up, failover, fail, over, group, policy, lif, configure failover settings on a lif, broadcast-domain-wide, system-defined, local-only, sfo-partner-only, disabled, network interface modify -vserver <vserver_name> -lif <lif_name> -failover-policy <failover_policy> -failover-group <failover_group>, examples of configuring failover settings and disabling failover 
summary: Configurer une LIF pour basculer vers un groupe spécifique de ports réseau 
---
= Configurer les paramètres de basculement sur une LIF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer une LIF afin de basculer vers un groupe spécifique de ports réseau en appliquant une politique de basculement et un failover group à la LIF. Vous pouvez également désactiver le basculement d'une LIF vers un autre port.

.Description de la tâche
* Lors de la création d'une LIF, le basculement LIF est activé par défaut et la liste des ports cibles disponibles est déterminée par le groupe de basculement par défaut et la règle de basculement basée sur le type et la stratégie de service LIF.
+
Depuis 9.5, vous pouvez spécifier une policy de services pour le LIF qui définit les services réseau pouvant utiliser le LIF. Certains services réseau imposent des restrictions de basculement sur une LIF.

+

NOTE: Si la politique de service d'une LIF est modifiée de façon à limiter davantage le basculement, la politique de basculement de la LIF est automatiquement mise à jour par le système.

* Vous pouvez modifier le comportement de basculement des LIFs en spécifiant des valeurs des paramètres -failover-group et -failover-policy dans la commande network interface modify.
* La modification d'une LIF entraînant l'absence de cible de basculement valide entraîne un message d'avertissement.
+
Si une LIF ne disposant pas de tentatives de basculement cible valides, une panne peut se produire.

* À partir de ONTAP 9.11.1, sur les plateformes de baie SAN 100 % Flash (ASA), le basculement de LIF iSCSI est automatiquement activé sur les LIF iSCSI nouvellement créées sur les machines virtuelles de stockage nouvellement créées.
+
En outre, c'est possible link:../san-admin/asa-iscsi-lif-fo-task.html["Activez manuellement le basculement de LIF iSCSI sur des LIF iSCSI préexistantes"], C'est-à-dire les LIF créées avant la mise à niveau vers ONTAP 9.11.1 ou version ultérieure.

* La liste suivante décrit la manière dont le paramètre -failover-policy affecte les ports cibles sélectionnés dans le failover group :



NOTE: Pour le basculement LIF iSCSI, seules les règles de basculement `local-only`, `sfo-partner-only` et `disabled` sont pris en charge.

* `broadcast-domain-wide` s'applique à tous les ports de tous les nœuds du failover group.
* `system-defined` S'applique uniquement aux ports du nœud de rattachement de la LIF et à un autre nœud du cluster, généralement un partenaire non- SFO, le cas échéant.
* `local-only` S'applique uniquement aux ports du nœud de rattachement du LIF.
* `sfo-partner-only` S'applique uniquement aux ports du nœud de rattachement du LIF et à son partenaire SFO.
* `disabled` Indique que le LIF n'est pas configuré pour le basculement.


.Étapes
Configurez les paramètres de basculement pour une interface existante :

....
network interface modify -vserver <vserver_name> -lif <lif_name> -failover-policy <failover_policy> -failover-group <failover_group>
....


== Exemples de configuration des paramètres de basculement et de désactivation du basculement

La commande suivante définit la règle de basculement sur broadcast-domain-large et utilise les ports du failover group fg3 comme cibles de basculement pour LIF data1 sur SVM vs3 :

....
network interface modify -vserver vs3 -lif data1 -failover-policy broadcast-domain-wide -failover-group fg3

network interface show -vserver vs3 -lif * -fields failover-group,failover-policy

vserver lif             failover-policy       failover-group
------- -------------- ---------------        --------------
vs3     data1          broadcast-domain-wide  fg3
....
La commande suivante désactive le basculement pour LIF data1 sur le SVM vs3 :

....
network interface modify -vserver vs3 -lif data1 -failover-policy disabled
....