---
sidebar: sidebar 
permalink: networking/decide_whether_to_use_this_network_management_guide-manual.html 
keywords: ONTAP 9.0 - 9.7, CLI, decide, deciding, find, finding, decide whether to use this network management content, find the right network management, information 
summary: Cette procédure décrit le flux de travail de basculement du chemin NAS pour les versions ONTAP 9.0 à 9.7. 
---
= Décider d'utiliser ces informations de gestion de réseau
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cette procédure décrit le flux de travail de basculement du chemin NAS pour les versions ONTAP 9.0 à 9.7.

Vous devez suivre cette procédure dans les cas suivants :

* Vous souhaitez appliquer les bonnes pratiques de basculement de chemin NAS dans un workflow qui simplifie la configuration du réseau.
* Vous souhaitez utiliser l'interface de ligne de commandes, pas System Manager.
* Vous configurez la mise en réseau sur un nouveau système exécutant ONTAP 9.8 ou version ultérieure.


Si vous exécutez une version ONTAP ultérieure à 9.7, vous devez vous reporter à :

* link:https://docs.netapp.com/us-en/ontap/networking/set_up_nas_path_failover_98_and_later_cli.html["Flux de travail de basculement de chemin NAS ONTAP 9.8 et versions ultérieures"^]


Si vous souhaitez obtenir des détails sur la gestion de réseau, reportez-vous aux sections suivantes :

* link:https://docs.netapp.com/us-en/ontap/networking-reference/index.html["Référence en matière de gestion du réseau ONTAP 9"^]


Si vous souhaitez utiliser System Manager pour configurer le réseau pour ONTAP 9.7 et versions ultérieures, vous devez choisir la documentation suivante :

* link:https://docs.netapp.com/us-en/ontap/["Documentation sur System Manager"^]


Si vous avez besoin d'informations supplémentaires sur la configuration ou les concepts, vous devez choisir parmi les documents suivants :

* Arrière-plan conceptuel pour la configuration du réseau
+
** link:../concepts/index.html["Concepts relatifs à ONTAP"^]


* Un accès aux fichiers NAS
+
** link:../nfs-admin/index.html["Gestion NFS"^]
** link:../smb-admin/index.html["Gestion SMB"^]


* Provisionnement d'hôtes SAN
+
** link:../san-admin/index.html["Administration SAN"^]


* Référence de commande
+
** http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Commandes ONTAP 9"^]


* Rapports techniques (TR), qui incluent des informations supplémentaires sur la technologie ONTAP et l'interaction avec des services externes
+
** http://www.netapp.com/us/media/tr-4182.pdf["Rapport technique NetApp 4182 : considérations relatives à la conception du stockage Ethernet et meilleures pratiques pour les configurations clustered Data ONTAP"^]



