---
sidebar: sidebar 
permalink: networking/decide_whether_to_use_this_network_management_guide_reference.html 
keywords: ONTAP 9, CLI, decide, deciding, find, finding, decide whether to use this network management guide, find the right network management guide 
summary: Trouvez le guide de gestion de réseau qui vous convient 
---
= Décider d'utiliser ces informations de gestion de réseau
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez effectuer l'administration du réseau de stockage de base, comme configurer des ports réseau physiques et virtuels (VLAN et groupes d'interface), créer des LIF à l'aide d'IPv4 et d'IPv6, gérer les services de routage et de résolution d'hôte dans les clusters, équilibrer les charges pour optimiser le trafic réseau et surveiller un cluster à l'aide de SNMP.

Vous devez utiliser ces informations dans les circonstances suivantes :

* Vous voulez connaître la gamme de fonctionnalités de gestion de réseau ONTAP.
* Vous souhaitez utiliser l'interface de ligne de commandes, pas System Manager.
* Vous configurez la mise en réseau sur un système nouveau ou mis à niveau exécutant ONTAP 9.


Si vous souhaitez suivre les bonnes pratiques de basculement des chemins NAS et que vous exécutez une version d'ONTAP 9.8 ou ultérieure, vous devez utiliser la documentation suivante :

* link:https://docs.netapp.com/us-en/ontap/networking/set_up_nas_path_failover_98_and_later_cli.html["Flux de travail de basculement de chemin NAS ONTAP 9.8 et versions ultérieures"^]


Si vous souhaitez suivre les meilleures pratiques en matière de basculement des chemins NAS et que vous exécutez une version de ONTAP 9.0 à 9.7, vous devez utiliser la documentation suivante :

* link:https://docs.netapp.com/us-en/ontap/networking/worksheet_for_nas_path_failover_configuration_manual.html["ONTAP 9.0 - 9.7 flux de travail de basculement de chemin NAS"^]


Si vous souhaitez utiliser System Manager pour configurer le réseau pour ONTAP 9.7 et versions ultérieures, vous devez choisir la documentation suivante :

* link:https://docs.netapp.com/us-en/ontap/["Documentation sur System Manager"^]


Si vous avez besoin d'informations supplémentaires sur la configuration ou les concepts, vous devez choisir parmi les documents suivants :

* Arrière-plan conceptuel pour la configuration du réseau
+
** link:../concepts/index.html["Concepts relatifs à ONTAP"^]


* Un accès aux fichiers NAS
+
** link:../nfs-admin/index.html["Gestion NFS"^]
** link:../smb-admin/index.html["Gestion SMB"^]


* Provisionnement d'hôtes SAN
+
** link:../san-admin/index.html["Administration SAN"^]


* Référence de commande
+
** http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Commandes ONTAP 9"^]


* Rapports techniques (TR), qui incluent des informations supplémentaires sur la technologie ONTAP et l'interaction avec des services externes
+
** http://www.netapp.com/us/media/tr-4182.pdf["Rapport technique NetApp 4182 : considérations relatives à la conception du stockage Ethernet et meilleures pratiques pour les configurations clustered Data ONTAP"^]



