---
sidebar: sidebar 
permalink: networking/delete_a_lif.html 
keywords: 'remove a lif, destroy a lif, delete, deleting, remove, removing, logical, interface, lif, delete a lif, delete a network interface (lif) that is no longer required, network interface delete' 
summary: 'Supprimez une interface réseau (LIF) qui n"est plus requise' 
---
= Supprimer une LIF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez supprimer une interface réseau (LIF) qui n'est plus requise.

Les LIFs à supprimer ne doivent pas être en cours d'utilisation.

.Étapes
. Marquez les LIFs que vous souhaitez supprimer comme administrativement arrêtées à l'aide de la commande suivante :
+
....
network interface modify -vserver vserver_name -lif lif_name -status-admin down
....
. Utilisez le `network interface delete` Commande de suppression d'une ou de l'ensemble des LIFs :
+
[cols="30,70"]
|===


| Si vous souhaitez supprimer... | Entrez la commande ... 


 a| 
Une LIF spécifique
 a| 
`network interface delete -vserver vserver_name -lif lif_name`



 a| 
Toutes les LIF
 a| 
`network interface delete -vserver vserver_name -lif *`

|===
+
La commande suivante supprime le LIF mgmtlif2 :

+
....
network interface delete -vserver vs1 -lif mgmtlif2
....
. Utilisez le `network interface show` Commande pour confirmer que la LIF est supprimée.

