---
sidebar: sidebar 
permalink: networking/display_routing_information.html 
keywords: display, view, show, route, svm, storage, virtual, machine, display routing information, view information about the routing configuration for each svm on your cluster, network route show, network route show-lifs, network route active-entry show 
summary: Afficher des informations sur la configuration de routage pour chaque SVM de votre cluster 
---
= Afficher les informations de routage ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher des informations sur la configuration de routage pour chaque SVM sur le cluster. Cela peut vous aider à diagnostiquer les problèmes de routage impliquant des problèmes de connectivité entre les applications ou les services client et un LIF sur un nœud du cluster.

.Étapes
. Utilisez le `network route show` Commande permettant d'afficher les routes au sein d'un ou plusieurs SVM. L'exemple suivant montre une route configurée sur le SVM vs0 :
+
....
network route show
  (network route show)
Vserver             Destination     Gateway         Metric
------------------- --------------- --------------- ------
vs0
                    0.0.0.0/0       172.17.178.1    20
....
. Utilisez le `network route show-lifs` Commande pour afficher l'association des routes et LIFs au sein d'un ou plusieurs SVM.
+
L'exemple suivant montre les LIFs avec des routes détenues par le SVM vs0 :

+
....
network route show-lifs
  (network route show-lifs)

Vserver: vs0
Destination             Gateway                 Logical Interfaces
----------------------  --------------          --------------------
0.0.0.0/0               172.17.178.1            cluster_mgmt,
                                                LIF-b-01_mgmt1,
                                                LIF-b-02_mgmt1
....
+
Pour en savoir plus sur `network route show` et `network route show-lifs` dans le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+route+show["Référence de commande ONTAP"^].

. Utilisez le `network route active-entry show` Commande permettant d'afficher les routes installées sur un ou plusieurs nœuds, SVM, sous-réseaux ou routes avec des destinations spécifiées.
+
L'exemple suivant montre toutes les routes installées sur un SVM spécifique :

+
....
network route active-entry show -vserver Data0

Vserver: Data0
Node: node-1
Subnet Group: 0.0.0.0/0
Destination             Gateway              Interface   Metric  Flags
----------------------  -------------------  ---------   ------  -----
127.0.0.1               127.0.0.1            lo              10  UHS
127.0.10.1              127.0.20.1           losk            10  UHS
127.0.20.1              127.0.20.1           losk            10  UHS

Vserver: Data0
Node: node-1
Subnet Group: fd20:8b1e:b255:814e::/64
Destination             Gateway              Interface   Metric  Flags
----------------------  -------------------  ---------   ------  -----
default                 fd20:8b1e:b255:814e::1
                                             e0d             20  UGS
fd20:8b1e:b255:814e::/64
                        link#4               e0d              0  UC

Vserver: Data0
Node: node-2
Subnet Group: 0.0.0.0/0
Destination             Gateway              Interface   Metric  Flags
----------------------  -------------------  ---------   ------  -----
127.0.0.1               127.0.0.1            lo              10  UHS

Vserver: Data0
Node: node-2
Subnet Group: 0.0.0.0/0
Destination             Gateway              Interface   Metric  Flags
----------------------  -------------------  ---------   ------  -----
127.0.10.1              127.0.20.1           losk            10  UHS
127.0.20.1              127.0.20.1           losk            10  UHS

Vserver: Data0
Node: node-2
Subnet Group: fd20:8b1e:b255:814e::/64
Destination             Gateway              Interface   Metric  Flags
----------------------  -------------------  ---------   ------  -----
default                 fd20:8b1e:b255:814e::1
                                             e0d             20  UGS
fd20:8b1e:b255:814e::/64
                        link#4               e0d              0  UC
fd20:8b1e:b255:814e::1  link#4               e0d              0  UHL
11 entries were displayed.
....
+
Pour en savoir plus, `network route active-entry show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/network-route-active-entry-show.html["Référence de commande ONTAP"^].


