---
sidebar: sidebar 
permalink: networking/display_broadcast_domains.html 
keywords: display, view, show, broadcast, domain, display broadcast domains, view a list of broadcast domains within each ipspace in a cluster 
summary: Afficher la liste des domaines de broadcast au sein de chaque IPspace dans un cluster 
---
= Afficher les domaines de diffusion ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher la liste des domaines de broadcast au sein de chaque IPspace dans un cluster. La sortie affiche également la liste des ports et la valeur MTU pour chaque domaine de diffusion.


NOTE: La procédure d'affichage des domaines de diffusion est différente dans ONTAP 9.7 et les versions antérieures. Si vous devez afficher des domaines de diffusion sur un réseau exécutant ONTAP 9.7 et des versions antérieures, reportez-vous link:https://docs.netapp.com/us-en/ontap-system-manager-classic/networking-bd/display_broadcast_domains97.html["Afficher les domaines de diffusion (ONTAP 9.7 ou version antérieure)"^]à la section .

.Étape
Afficher les broadcast domain et les ports associés dans le cluster :

....
network port broadcast-domain show
....
La commande suivante affiche tous les broadcast domain et les ports associés du cluster :

....
network port broadcast-domain show
IPspace Broadcast                                Update
Name    Domain Name  MTU   Port List             Status Details
------- ----------- -----  --------------------- --------------
Cluster Cluster      9000
                           cluster-1-01:e0a       complete
                           cluster-1-01:e0b       complete
                           cluster-1-02:e0a       complete
                           cluster-1-02:e0b       complete
Default Default      1500
                           cluster-1-01:e0c       complete
                           cluster-1-01:e0d       complete
                           cluster-1-02:e0c       complete
                           cluster-1-02:e0d       complete
        Default-1    1500
                           cluster-1-01:e0e       complete
                           cluster-1-01:e0f       complete
                           cluster-1-01:e0g       complete
                           cluster-1-02:e0e       complete
                           cluster-1-02:e0f       complete
                           cluster-1-02:e0g       complete
....
La commande suivante affiche les ports du broadcast domain default-1 qui ont un statut de mise à jour de l'erreur, ce qui indique que le port n'a pas pu être mis à jour correctement :

....
network port broadcast-domain show -broadcast-domain Default-1 -port-update-status error

IPspace Broadcast                                Update
Name    Domain Name  MTU   Port List             Status Details
------- ----------- -----  --------------------- --------------
Default Default-1   1500
                           cluster-1-02:e0g       error
....
.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/network-port-broadcast-domain-show.html["broadcast-domain-domain port réseau show"^]

