---
sidebar: sidebar 
permalink: networking/display_network_connectivity_with_neighbor_discovery_protocols.html 
keywords: display, view, show, network, connectivity, neighbor, discovery, protocol, ndp, cdp, cisco, link, layer, lldp, display network connectivity with neighbor discovery protocols, use neighbor discovery protocols to view network connectivity between a pair of physical or virtual systems and their network interfaces, use cdp to detect network connectivity, considerations for using cdp, enable or disable cdp, view cdp neighbor information, example of showing and clearing statistics, use lldp to detect network connectivity, enable or disable lldp, view lldp neighbor information, adjust the interval for transmitting lldp advertisements 
summary: Utilisez les protocoles de découverte voisins pour afficher la connectivité réseau entre une paire de systèmes physiques ou virtuels et leurs interfaces réseau 
---
= Affichez la connectivité réseau ONTAP avec les protocoles de détection de voisins
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Dans un data Center, vous pouvez utiliser des protocoles de découverte voisins pour afficher la connectivité réseau entre une paire de systèmes physiques ou virtuels et leurs interfaces réseau. ONTAP prend en charge deux protocoles de découverte de voisins : le Cisco Discovery Protocol (CDP) et le Link Layer Discovery Protocol (LLDP).

Les protocoles de détection de voisins vous permettent de détecter et d'afficher automatiquement des informations sur les périphériques compatibles avec des protocoles directement connectés sur un réseau. Chaque appareil transmet des informations d'identification, de fonctionnalités et de connectivité. Ces informations sont transmises en trames Ethernet à une adresse MAC multicast et sont reçues par tous les périphériques compatibles avec les protocoles voisins.

Pour que deux périphériques deviennent voisins, un protocole doit être activé et correctement configuré. La fonctionnalité du protocole de découverte est limitée aux réseaux directement connectés. Les voisins peuvent inclure des périphériques compatibles avec les protocoles, tels que des commutateurs, des routeurs, des ponts, etc. ONTAP prend en charge deux protocoles de détection de voisins, qui peuvent être utilisés individuellement ou conjointement.

*Cisco Discovery Protocol (CDP)*

CDP est un protocole propriétaire de couche de liaison développé par Cisco Systems. Il est activé par défaut dans ONTAP pour les ports de cluster, mais il doit être activé explicitement pour les ports de données.

*Protocole LLDP (Link Layer Discovery Protocol)*

LLDP est un protocole indépendant du fournisseur spécifié dans le document de normes IEEE 802.1AB. Elle doit être activée explicitement pour tous les ports.
