---
sidebar: sidebar 
permalink: networking/display_ipspaces.html 
keywords: display, view, show, ipspace, display ipspaces, list the ipspaces and view ipspace information for the cluster 
summary: 'Lister les IPspaces et afficher les informations d"IPspace pour le cluster' 
---
= Afficher les IPspaces sur le réseau ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher la liste des IPspaces qui existent dans un cluster et afficher les serveurs de stockage virtuels (SVM), les domaines de diffusion et les ports affectés à chaque IPspace.

.Étape
Affichage des IPspaces et des SVM dans un cluster :

....
network ipspace show [-ipspace ipspace_name]
....
La commande suivante affiche tous les IPspaces, le SVM et les domaines de diffusion dans le cluster :

....
network ipspace show
IPspace        Vserver List             Broadcast Domains
-------------  -----------------------  -------------------
Cluster
               Cluster                  Cluster
Default
               vs1, cluster-1            Default
ipspace1
               vs3, vs4, ipspace1       bcast1
....
La commande suivante affiche les nœuds et les ports faisant partie de l'IPspace ipspace1 :

....
network ipspace show -ipspace ipspace1
IPspace name: ipspace1
Ports: cluster-1-01:e0c, cluster-1-01:e0d, cluster-1-01:e0e, cluster-1-02:e0c, cluster-1-02:e0d, cluster-1-02:e0e
Broadcast Domains: Default-1
Vservers: vs3, vs4, ipspace1
....