---
sidebar: sidebar 
permalink: networking/display_routing_information_01.html 
keywords: display, view, show, route, svm, storage, virtual, machine, display routing information, view information about routes within an svm 
summary: 'Afficher les informations sur les routes au sein d"un SVM' 
---
= Afficher les informations de routage pour le réseau ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher les informations relatives aux routes au sein d'une SVM.

.Étape
Selon le type d'informations de routage que vous souhaitez afficher, entrez la commande applicable :

[cols="40,60"]
|===


| Pour afficher des informations sur... | Entrer... 


 a| 
Routes statiques, par SVM
 a| 
`network route show`



 a| 
LIF sur chaque route, par SVM
 a| 
`network route show-lifs`

|===
Vous pouvez afficher des informations détaillées pour chaque itinéraire en spécifiant le `-instance` paramètre. La commande suivante affiche les routes statiques au sein des SVM en cluster- 1 :

....
network route show
Vserver             Destination     Gateway         Metric
------------------- --------------- --------------- ------
Cluster
                    0.0.0.0/0       10.63.0.1       10
cluster-1
                    0.0.0.0/0       198.51.9.1      10
vs1
                    0.0.0.0/0       192.0.2.1       20
vs3
                    0.0.0.0/0       192.0.2.1       20
....
La commande suivante affiche l'association de routes statiques et d'interfaces logiques (LIF) au sein de tous les SVM au sein du cluster-1 :

....
network route show-lifs
Vserver: Cluster
Destination             Gateway                 Logical Interfaces
----------------------  ----------------------  -------------------
0.0.0.0/0               10.63.0.1               -

Vserver: cluster-1
Destination             Gateway                 Logical Interfaces
----------------------  ----------------------  -------------------
0.0.0.0/0               198.51.9.1              cluster_mgmt,
                                                cluster-1_mgmt1,

Vserver: vs1
Destination             Gateway                 Logical Interfaces
----------------------  ----------------------  -------------------
0.0.0.0/0               192.0.2.1               data1_1, data1_2

Vserver: vs3
Destination             Gateway                 Logical Interfaces
----------------------  ----------------------  -------------------
0.0.0.0/0               192.0.2.1               data2_1, data2_2
....