---
sidebar: sidebar 
permalink: networking/how_dns_load_balancing_works.html 
keywords: introducing, introduction, overview, dns, naming, name, service, load, balance, balancing, performance, how dns load balancing works, introducing dns load balancing 
summary: 'Introduction à l"équilibrage de charge DNS' 
---
= Fonctionnement de l'équilibrage de charge DNS
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les clients montent un SVM en spécifiant une adresse IP (associée à une LIF) ou un nom d'hôte (associé à plusieurs adresses IP). Par défaut, les LIFs sont sélectionnées par le serveur DNS à l'échelle du site de manière round-Robin, qui équilibre la charge de travail sur tous les LIFs.

L'équilibrage de charge round-Robin peut entraîner la surcharge de certaines LIF. Vous avez donc la possibilité d'utiliser une zone d'équilibrage de charge DNS qui gère la résolution host-name dans un SVM. L'utilisation d'une zone d'équilibrage de charge DNS permet de mieux équilibrer les nouvelles connexions client sur les ressources disponibles, ce qui améliore les performances du cluster.

Une zone d'équilibrage de charge DNS est un serveur DNS au sein du cluster qui évalue dynamiquement la charge sur toutes les LIFs et renvoie un LIF chargé correctement. Dans une zone d'équilibrage de la charge, DNS attribue un poids (métrique), en fonction de la charge, à chaque LIF.

Un poids est attribué à chaque LIF en fonction de la charge des ports et de l'utilisation du CPU de son nœud de rattachement. Les LIF qui font partie de ports moins chargés ont plus de chances d'être renvoyées dans une requête DNS. Les poids peuvent également être attribués manuellement.
