---
sidebar: sidebar 
permalink: networking/index.html 
keywords: ontap, 9, network, management, documentation, guide, ontap 9 network management documentation, welcome to the ontap 9 network management documentation portal 
summary: Bienvenue sur le portail de documentation de gestion de réseau ONTAP 9 
---
= Documentation de gestion du réseau ONTAP 9
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
System Manager permet une visualisation avancée du réseau et permet de télécharger des données consolidées sur votre réseau. Pour en savoir plus, consultez les rubriques suivantes :

* link:https://docs.netapp.com/us-en/ontap/concept_admin_viewing_managing_network.html["Afficher et gérer votre réseau"]
* link:https://docs.netapp.com/us-en/ontap/concept_admin_downloading_data_report.html["Téléchargez les données réseau pour le reporting"]


Vous pouvez également configurer et gérer votre réseau à l'aide de l'interface de ligne de commande ONTAP. La documentation de gestion de réseau sur l'interface de ligne de commande ONTAP 9 comporte trois domaines principaux :

link:set_up_nas_path_failover_98_and_later_cli.html["Configurez le basculement de chemin NAS pour ONTAP 9.8 et versions ultérieures"]

Découvrez comment configurer le basculement de chemin NAS en suivant les meilleures pratiques établies dans ONTAP 9.8 et versions ultérieures

link:set_up_nas_path_failover_9_to_97_cli.html["Configurez le basculement de chemin NAS pour ONTAP 9.7 et versions antérieures"]

Découvrez comment configurer le basculement de chemin NAS en appliquant les meilleures pratiques établies dans ONTAP 9.7 et versions antérieures.

link:networking_reference.html["Référence de mise en réseau"]

La documentation de référence réseau décrit comment configurer et gérer les ports réseau physiques et virtuels (VLAN et groupes d'interfaces), les LIF utilisant IPv4 et IPv6, le routage et les services de résolution hôte dans les clusters, optimiser le trafic réseau par équilibrage de charge et surveiller le cluster à l'aide de SNMP. Sauf indication contraire, ces informations s'appliquent à toutes les versions de ONTAP 9.
