---
sidebar: sidebar 
permalink: networking/manage_the_hosts_table_@cluster_administrators_only@.html 
keywords: 'manage, managing, snmp, monitor, monitoring, troubleshooting, error detection, traps, hosts, host, table, add, modify, change, create, delete, remove, view, show, display, manage the hosts table (cluster administrators only, manage the host name entries in the hosts table of the admin svm, commands for managing local host-name entries, vserver services name-service dns hosts' 
summary: 'Gérer les entrées de nom d"hôte dans le tableau hosts du SVM admin' 
---
= Gestion de la table hosts (administrateurs du cluster uniquement)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Un administrateur de cluster peut ajouter, modifier, supprimer et afficher les entrées de nom d'hôte dans le tableau hosts de la machine virtuelle de stockage (SVM) admin. Un administrateur SVM peut configurer les entrées de nom d'hôte uniquement pour la SVM attribuée.



== Commandes permettant de gérer les entrées locales de nom d'hôte

Vous pouvez utiliser le `vserver services name-service dns hosts` Commande pour créer, modifier ou supprimer des entrées de table hôte DNS.

Lorsque vous créez ou modifiez les entrées de nom d'hôte DNS, vous pouvez spécifier plusieurs adresses d'alias séparées par des virgules.

[cols="30,70"]
|===


| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Créez une entrée de nom d'hôte DNS
 a| 
`vserver services name-service dns hosts create`



 a| 
Modifier une entrée de nom d'hôte DNS
 a| 
`vserver services name-service dns hosts modify`



 a| 
Supprimer une entrée de nom d'hôte DNS
 a| 
`vserver services name-service dns hosts delete`

|===
Pour plus d'informations, reportez-vous à la section http://["Commandes ONTAP 9"^] pour le `vserver services name-service dns hosts` commandes.
