---
sidebar: sidebar 
permalink: networking/manage_snmp_on_the_cluster_@cluster_administrators_only@_overview.html 
keywords: manage, managing, snmp, monitor, monitoring, troubleshooting, error detection, traps, overview, configure snmp to monitor svms in your cluster 
summary: Configurez SNMP pour surveiller les SVM au sein de votre cluster 
---
= Présentation
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez configurer le protocole SNMP pour surveiller les SVM au sein de votre cluster afin d'éviter les problèmes avant qu'ils ne se produisent et de répondre aux problèmes en cas de survenue. La gestion de SNMP implique la configuration des utilisateurs SNMP et la configuration des destinations de Traphost SNMP (stations de travail de gestion) pour tous les événements SNMP. SNMP est désactivé par défaut sur les LIFs de données.

Vous pouvez créer et gérer des utilisateurs SNMP en lecture seule dans la SVM de données. Les LIFs data doivent être configurées de sorte à recevoir des requêtes SNMP sur le SVM.

Les postes de travail SNMP de gestion de réseau, ou gestionnaires, peuvent interroger l'agent SNMP du SVM pour obtenir des informations. L'agent SNMP recueille des informations et les transmet aux gestionnaires SNMP. L'agent SNMP génère également des notifications d'interruption lorsque des événements spécifiques se produisent. L'agent SNMP du SVM possède des privilèges en lecture seule ; il ne peut pas être utilisé pour des opérations définies ou pour effectuer une action corrective en réponse à un trap. ONTAP fournit un agent SNMP compatible avec les versions SNMP v1, v2c et v3. SNMPv3 offre une sécurité avancée en utilisant des phrases de passe et le cryptage.

Pour plus d'informations sur la prise en charge SNMP dans les systèmes ONTAP, voir https://www.netapp.com/pdf.html?item=/media/16417-tr-4220pdf.pdf["Tr-4220 : prise en charge SNMP dans Data ONTAP"^].
