---
sidebar: sidebar 
permalink: networking/merge_broadcast_domains97.html 
keywords: merge, combine, broadcast, domain, reachability, merge broadcast domains, merge the ports from one broadcast domain into an existing broadcast domain 
summary: 'Fusionner les ports d"un domaine de diffusion dans un domaine de diffusion existant' 
---
= Fusionner les domaines de diffusion
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Vous pouvez déplacer tous les ports d'un domaine de diffusion vers un domaine de diffusion existant à l'aide de la commande Merge.

Cette opération réduit les étapes requises si vous deviez supprimer tous les ports d'un broadcast domain, puis ajouter les ports à un broadcast domain existant.

Fusionner les ports d'un domaine de diffusion dans un domaine de diffusion existant :

....
network port broadcast-domain merge -ipspace <ipspace_name> -broadcast-domain <broadcast_domain_name> -into-broadcast-domain <broadcast_domain_name>
....
* `ipspace_name` Est le nom de l'IPspace où les domaines de diffusion résident.
* `-broadcast-domain` est le nom du domaine de diffusion qui sera fusionné.
* `-into-broadcast-domain` est le nom du domaine de diffusion qui recevra des ports supplémentaires.


L'exemple suivant fusionne le domaine de broadcast bd-data1 dans le domaine de broadcast bd-data2 :

`network port -ipspace Default broadcast-domain bd-data1 into-broadcast-domain bd-data2`
