---
sidebar: sidebar 
permalink: networking/modify_network_port_attributes.html 
keywords: change, changing, modify, modifying, network, port, attributes, modify network port attributes, change the autonegotiation, duplex, flow control, speed, and health settings of a physical network port 
summary: 'Modifiez les paramètres de négociation automatique, duplex, contrôle de flux, vitesse et état d"un port réseau physique' 
---
= Modifiez les attributs des ports réseau ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier les paramètres de négociation automatique, duplex, contrôle du flux, vitesse et état d'un port réseau physique.

.Avant de commencer
Le port que vous souhaitez modifier ne doit pas héberger les LIFs.

.Description de la tâche
* Il n'est pas recommandé de modifier les paramètres d'administration des interfaces réseau 100 GbE, 40 GbE, 10 GbE ou 1 GbE.
+
Les valeurs que vous définissez pour le mode duplex et la vitesse du port sont appelées paramètres administratifs. En fonction des limites du réseau, les paramètres d'administration peuvent différer des paramètres opérationnels (c'est-à-dire le mode duplex et la vitesse utilisés par le port).

* Il n'est pas recommandé de modifier les paramètres d'administration des ports physiques sous-jacents dans un groupe d'interfaces.
+
Le `-up-admin` paramètre (disponible au niveau des privilèges avancés) modifie les paramètres administratifs du port.

* Il n'est pas recommandé de régler le `-up-admin` Paramètre administratif sur false pour tous les ports d'un nœud, ou pour le port qui héberge la dernière LIF de cluster opérationnelle sur un nœud.
* Il n'est pas recommandé de modifier la taille MTU du port de gestion, `e0M`.
* La taille MTU d'un port dans un domaine de diffusion ne peut pas être modifiée à partir de la valeur MTU définie pour le domaine de diffusion.
* La taille MTU d'un VLAN ne peut pas dépasser la valeur de la taille MTU de son port de base.


.Étapes
. Modifier les attributs d'un port réseau :
+
`network port modify`

. Vous pouvez définir le `-ignore-health-status` champ à true pour spécifier que le système peut ignorer l'état de santé du port réseau d'un port spécifié.
+
Le statut de l'état de santé des ports réseau est automatiquement modifié et passe de dégradé à sain, et ce port peut désormais être utilisé pour héberger les LIFs. Vous devez définir le contrôle de flux des ports du cluster sur `none`. Par défaut, le contrôle de flux est défini sur `full`.



La commande suivante désactive le contrôle de flux sur le port e0b en définissant le contrôle de flux sur aucun :

....
network port modify -node cluster-1-01 -port e0b -flowcontrol-admin none
....