---
sidebar: sidebar 
permalink: networking/recover_from_an_incorrectly_configured_cluster_lif.html 
keywords: misconfigured, misconfigurations, incorrect, incorrectly, switch, switches, switched, cable, physical, wiring, wired, reachability, port, cluster, ontap 9.8 and later, recover from an incorrectly configured cluster lif, how to identify and correct a cluster that has been misconfigured, cluster create, network port, reachability show -detail, reset the home port 
summary: Comment identifier et corriger un cluster mal configuré 
---
= Restaurer une LIF ONTAP mal configurée
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Un cluster ne peut pas être créé lorsque le réseau de cluster est câblé à un commutateur, mais tous les ports configurés dans le Cluster IPspace peuvent atteindre les autres ports configurés dans le Cluster IPspace.

.Description de la tâche
Dans un cluster commuté, si une interface réseau de cluster (LIF) est configurée sur le port inapproprié ou si un port de cluster est câblé dans le mauvais réseau, le `cluster create` la commande peut échouer avec l'erreur suivante :

....
Not all local cluster ports have reachability to one another.
Use the "network port reachability show -detail" command for more details.
....
Pour en savoir plus, `cluster create` consultez le link:https://docs.netapp.com/us-en/ontap-cli/cluster-create.html["Référence de commande ONTAP"^].

Les résultats de la `network port show` commande peuvent afficher que plusieurs ports sont ajoutés au Cluster IPspace car ils sont connectés à un port configuré avec une LIF de cluster. Cependant, les résultats de la  `network port reachability show -detail` la commande révèle quels ports n'ont pas de connectivité entre eux.

Pour en savoir plus, `network port show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/network-port-show.html["Référence de commande ONTAP"^].

Pour restaurer une LIF de cluster configurée sur un port qui n'est pas accessible aux autres ports configurés avec des LIFs de cluster, effectuez les opérations suivantes :

.Étapes
. Réinitialiser le home port de la LIF de cluster sur le port correct :
+
....
network port modify -home-port
....
+
Pour en savoir plus, `network port modify` consultez le link:https://docs.netapp.com/us-en/ontap-cli/network-port-modify.html["Référence de commande ONTAP"^].

. Retirer les ports qui ne disposent pas de LIFs de cluster configurées sur eux du cluster broadcast domain :
+
....
network port broadcast-domain remove-ports
....
+
Pour en savoir plus, `network port broadcast-domain remove-ports` consultez le link:https://docs.netapp.com/us-en/ontap-cli/network-port-broadcast-domain-remove-ports.html["Référence de commande ONTAP"^].

. Création du cluster :
+
....
cluster create
....


.Résultat
Une fois le cluster créé, le système détecte la configuration correcte et place les ports dans les domaines de diffusion appropriés.

.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/network-port-reachability-show.html["affichage de l'accessibilité des ports réseau"^]

