---
sidebar: sidebar 
permalink: networking/split_broadcast_domains.html 
keywords: split, broadcast, domain, separate, splitting, separating, reachability, port, split a broadcast domain to synchronize the ontap configuration with the physical network topology, unreachable ports, broadcast-domain split, split broadcast domains 
summary: Diviser un domaine de diffusion pour synchroniser la configuration ONTAP 9.8 et supérieure avec la topologie de réseau physique 
---
= Domaines de diffusion divisés (ONTAP 9.8 et versions ultérieures)
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Si l'accessibilité des ports réseau a changé, via la connectivité réseau physique ou la configuration du commutateur, De plus, un groupe de ports réseau précédemment configurés dans un domaine de diffusion unique est désormais partitionné en deux ensembles de capacité d'accès différents, vous pouvez fractionner un domaine de diffusion pour synchroniser la configuration ONTAP avec la topologie de réseau physique.

Pour déterminer si un domaine de diffusion de port réseau est partitionné en plusieurs ensembles de capacité d'accès, utilisez le `network port reachability show -details` Commande et attention à quels ports ne sont pas connectabilité les uns aux autres (« ports inaccessibles »). En général, la liste des ports inaccessibles définit l'ensemble des ports qui doivent être répartis dans un autre broadcast domain, après avoir vérifié que la configuration physique et celle du switch est exacte.

.Étape
Diviser un domaine de diffusion en deux domaines de diffusion :

....
network port broadcast-domain split -ipspace <ipspace_name> -broadcast-domain <broadcast_domain_name> -new-broadcast-domain <broadcast_domain_name> -ports <node:port,node:port>
....
* `ipspace_name` est le nom de l'ipspace où réside le domaine de diffusion.
* -`broadcast-domain` est le nom du domaine de diffusion qui sera partagé.
* -`new-broadcast-domain` est le nom du nouveau domaine de diffusion qui sera créé.
* -`ports` est le nom du nœud et le port à ajouter au nouveau broadcast domain.

