---
sidebar: sidebar 
permalink: networking/standard_properties_of_ipspaces.html 
keywords: standard, property, properties, ipspace, special, ipspaces, svm, cluster, default, understanding, cluster, initialization, initialized, introducing, introduction, overview, standard properties of ipspaces, introducing the default and cluster ipspaces created during cluster initialization, default ipspace, cluster ipspace, system svm 
summary: 'Présentation des IPspaces par défaut et des clusters créés lors de l"initialisation du cluster' 
---
= Propriétés standard des IPspaces
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Les IPspaces spéciaux sont créés par défaut lors de la première création du cluster. De plus, des machines virtuelles de stockage spéciales sont créées pour chaque IPspace.

Deux IPspaces sont créés automatiquement lors de l'initialisation du cluster :

* IPspace par défaut
+
Cet IPspace est un conteneur pour les ports, les sous-réseaux et les SVM qui servent de données. Si votre configuration n'a pas besoin d'IPspaces distinctes pour les clients, tous les SVM peuvent être créés dans cet IPspace. Cet IPspace contient également les ports de gestion du cluster et des nœuds.

* IPspace « cluster »
+
Cet IPspace contient tous les ports de cluster de tous les nœuds du cluster. Il est créé automatiquement lors de la création du cluster. Il assure la connectivité au réseau interne privé du cluster. À mesure que les nœuds supplémentaires rejoint le cluster, les ports de cluster à partir de ces nœuds sont ajoutés à l'IPspace « Cluster ».



Un SVM « système » existe pour chaque IPspace. Lorsque vous créez un IPspace, un SVM système par défaut du même nom est créé :

* Le SVM système pour le « Cluster » IPspace transmet le trafic du cluster entre les nœuds d'un cluster sur le réseau interne de cluster privé.
+
Il est géré par l'administrateur du cluster, et il porte le nom « Cluster ».

* Le SVM système pour l'IPspace « par défaut » transmet le trafic de gestion du cluster et des nœuds, y compris le trafic intercluster entre les clusters.
+
Il est géré par l'administrateur du cluster, et il utilise le même nom que le cluster.

* Le SVM système pour un IPspace personnalisé que vous créez implique le trafic de gestion pour ce SVM.
+
Il est géré par l'administrateur du cluster, et il utilise le même nom que l'IPspace.



Un ou plusieurs SVM pour les clients peuvent exister dans un IPspace. Chaque SVM client dispose de ses propres volumes et configurations de données, et il est administré indépendamment des autres SVM.
