---
sidebar: sidebar 
permalink: networking/task_testing_snmp_polling.html 
keywords: configure, snmp, verify, poll, cluster, test, test snmp poll 
summary: Une fois le protocole SNMP configuré, vous devez vérifier que vous pouvez interroger le cluster. 
---
= Tester l'interrogation SNMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois le protocole SNMP configuré, vous devez vérifier que vous pouvez interroger le cluster.

.Description de la tâche
Pour interroger un cluster, vous devez utiliser une commande tierce par exemple `snmpwalk`.

.Étapes
. Envoyer une commande SNMP pour interroger le cluster depuis un autre cluster.
+
Pour les systèmes exécutant SNMPv1, utilisez la commande CLI `snmpwalk -v version -c community_stringip_address_or_host_name system` Pour découvrir le contenu de la base MIB (Management information base).

+
Dans cet exemple, l'adresse IP de la LIF de gestion du cluster dont vous disposez est 10.11.12.123. La commande affiche les informations demandées à partir de la MIB :

+
[listing]
----
C:\Windows\System32>snmpwalk -v 1 -c public 10.11.12.123 system

SNMPv1-MIB::sysDescr.0 = STRING: NetApp Release 8.3.0
            Cluster-Mode: Tue Apr 22 16:24:48 EDT 2014
SNMPv1-MIB::sysObjectID.0 = OID: SNMPv1-SMI::enterprises.789.2.5
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (162644448) 18 days, 19:47:24.48
SNMPv1-MIB::sysContact.0 = STRING:
SNMPv1-MIB::sysName.0 = STRING: systemname.testlabs.com
SNMPv1-MIB::sysLocation.0 = STRING: Floor 2 Row B Cab 2
SNMPv1-MIB::sysServices.0 = INTEGER: 72
----
+
Pour les systèmes exécutant SNMPv2c, utilisez la commande CLI `snmpwalk -v version -c community_stringip_address_or_host_name system` Pour découvrir le contenu de la base MIB (Management information base).

+
Dans cet exemple, l'adresse IP de la LIF de gestion du cluster dont vous disposez est 10.11.12.123. La commande affiche les informations demandées à partir de la MIB :

+
[listing]
----
C:\Windows\System32>snmpwalk -v 2c -c public 10.11.12.123 system

SNMPv2-MIB::sysDescr.0 = STRING: NetApp Release 8.3.0
            Cluster-Mode: Tue Apr 22 16:24:48 EDT 2014
SNMPv2-MIB::sysObjectID.0 = OID: SNMPv2-SMI::enterprises.789.2.5
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (162635772) 18 days, 19:45:57.72
SNMPv2-MIB::sysContact.0 = STRING:
SNMPv2-MIB::sysName.0 = STRING: systemname.testlabs.com
SNMPv2-MIB::sysLocation.0 = STRING: Floor 2 Row B Cab 2
SNMPv2-MIB::sysServices.0 = INTEGER: 72
----
+
Pour les systèmes exécutant SNMPv3, utilisez la commande CLI `snmpwalk -v 3 -a MD5 or SHA -l authnopriv -u username -A passwordip_address_or_host_name system` Pour découvrir le contenu de la base MIB (Management information base).

+
Dans cet exemple, l'adresse IP de la LIF de gestion du cluster dont vous disposez est 10.11.12.123. La commande affiche les informations demandées à partir de la MIB :

+
[listing]
----
C:\Windows\System32>snmpwalk -v 3 -a MD5 -l authnopriv -u snmpv3
       -A password123 10.11.12.123 system

SNMPv3-MIB::sysDescr.0 = STRING: NetApp Release 8.3.0
       Cluster-Mode: Tue Apr 22 16:24:48 EDT 2014
SNMPv3-MIB::sysObjectID.0 = OID: SNMPv3-SMI::enterprises.789.2.5
DISMAN-EVENT-MIB::sysUpTimeInstance = Timeticks: (162666569) 18 days, 19:51:05.69
SNMPv3-MIB::sysContact.0 = STRING:
SNMPv3-MIB::sysName.0 = STRING: systemname.testlabs.com
SNMPv3-MIB::sysLocation.0 = STRING: Floor 2 Row B Cab 2
SNMPv3-MIB::sysServices.0 = INTEGER: 72
----

