---
permalink: concepts/aggregates-raid-groups-concept.html 
sidebar: sidebar 
keywords: aggregate, local tier, raid group, raid-dp, parity disk 
summary: 'Les technologies RAID modernes protègent contre les pannes de disque en reconstruisant les données d"un disque défaillant sur un disque de secours. Le système compare les informations d"index sur un "disque de parité" avec les données sur les disques en bon état restants pour reconstruire les données manquantes, le tout sans temps d"arrêt ni coût de performance significatif.' 
---
= Niveaux locaux (agrégats) et groupes RAID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les technologies RAID modernes protègent contre les défaillances de disque en reconstruisant les données d'un disque défaillant sur un disque de secours. Le système compare les informations d'index sur un « disque de parité » avec les données des disques restants en bonne santé pour reconstruire les données manquantes, le tout sans temps d'arrêt ni coûts de performances significatifs.

Un niveau local (agrégat) se compose d'un ou plusieurs _RAID Groups_. Le _RAID type_ du niveau local détermine le nombre de disques de parité du groupe RAID et le nombre de pannes de disque simultanées que la configuration RAID protège contre.

Le type RAID par défaut, RAID-DP (RAID-double parité), requiert deux disques de parité par groupe RAID et protège contre les pertes de données en cas de défaillance simultanée de deux disques. Pour le RAID-DP, la taille de groupe RAID recommandée est comprise entre 12 et 20 disques durs et entre 20 et 28 disques SSD.

Vous pouvez répartir le coût supplémentaire des disques de parité en créant des groupes RAID à la partie supérieure des recommandations de dimensionnement. Ceci est particulièrement vrai pour les disques SSD, qui sont bien plus fiables que les disques haute capacité. Pour les niveaux locaux utilisant des disques durs, il est conseillé de choisir entre l'optimisation du stockage sur disque et les facteurs compensatoires, comme le délai de reconstruction plus long requis pour les groupes RAID plus volumineux.
