---
permalink: concepts/autosupport-active-iq-digital-advisor-concept.html 
sidebar: sidebar 
keywords: autosupport, active iq, digital advisor, upgrade advisor 
summary: 'ONTAP propose un contrôle et un reporting basés sur l"intelligence artificielle via un portail Web et une application mobile. Le composant AutoSupport de ONTAP envoie une télémétrie analysée par le conseiller numérique.' 
---
= AutoSupport et Digital Advisor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP propose un contrôle et un reporting basés sur l'intelligence artificielle via un portail Web et une application mobile. Le composant AutoSupport de ONTAP envoie une télémétrie analysée par le conseiller numérique Active IQ (également appelé conseiller numérique).

Grâce à Digital Advisor, vous pouvez optimiser votre infrastructure de données dans l'ensemble de votre cloud hybride grâce à un portail cloud et à une application mobile qui fournit des analyses prédictives et un support proactif. Les informations et recommandations issues de Digital Advisor sont disponibles pour tous les clients NetApp ayant un contrat SupportEdge actif (les fonctionnalités varient selon le produit et le niveau de support).

Voici quelques-unes des fonctionnalités que vous pouvez faire avec Digital Advisor :

* Planification des mises à niveau. Digital Advisor identifie les problèmes de votre environnement qui peuvent être résolus en effectuant une mise à niveau vers une version plus récente de ONTAP. Le composant Upgrade Advisor vous aide à planifier une mise à niveau réussie.
* Voir le bien-être du système. Votre tableau de bord Digital Advisor signale les problèmes liés à leur intégrité et vous aide à les corriger. Surveillez la capacité du système pour vous assurer que votre espace de stockage est insuffisant.
* Gestion des performances. Digital Advisor affiche les performances du système sur une période plus longue que ce que vous pouvez voir dans System Manager. Identifiez les problèmes de configuration et de système qui ont un impact sur les performances.
* Optimisez l'efficacité. Affichez les mesures de l'efficacité du stockage et identifiez des moyens de stocker plus de données dans moins d'espace.
* Voir l'inventaire et la configuration. Digital Advisor affiche l'inventaire complet ainsi que des informations sur la configuration des logiciels et du matériel. Voyez quand les contrats de service arrivent à expiration pour vous assurer de rester couverts.


.Informations associées
https://docs.netapp.com/us-en/active-iq/["Documentation NetApp : conseiller digital"]

https://aiq.netapp.com/custom-dashboard/search["Lancez Digital Advisor"]

https://www.netapp.com/us/services/support-edge.aspx["Services SupportEdge"]
