---
permalink: concepts/builtin-storage-efficiency-concept.html 
sidebar: sidebar 
keywords: storage efficiency, built-in, platform, controller, offload, aff a1k, aff a90, aff a70, fas90, fas70, aff a50, aff a30 
summary: 'L"efficacité du stockage du processeur de déchargement dédié est activée par défaut sur certaines plates-formes AFF et FAS . Ces plates-formes n’utilisent pas d’efficacité de stockage sensible à la température.  La compression commence sans attendre que les données soient froides et est effectuée à l"aide d"un processeur de déchargement dédié.' 
---
= En savoir plus sur l'efficacité du stockage du processeur de déchargement dédié ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'efficacité du stockage du processeur de déchargement dédié effectue un conditionnement séquentiel de blocs physiques contigus et utilise un processeur de déchargement dédié pour la compression de données 32 K.  Avec une compression 32k, les économies d'espace sont réalisées au niveau agrégé, contrairement aux plateformes utilisant une compression adaptative 8k, où les économies d'espace sont réalisées au niveau du volume.  Les plates-formes qui utilisent l'efficacité de stockage du processeur de déchargement dédié n'utilisent pas l'efficacité de stockage sensible à la température (TSSE), ce qui signifie que la compression n'est pas basée sur des données chaudes ou froides.  Il en résulte un gain de place immédiat sans impact sur les performances.

L'efficacité du stockage du processeur de déchargement dédié est activée par défaut sur les plates-formes et versions ONTAP suivantes.


NOTE: La plate-forme AFF A20 ne prend pas en charge l'efficacité du stockage du processeur de déchargement dédié.  Pour les plates-formes AFF A20, les données migrées à l'aide de la technologie SnapMirror sont automatiquement converties en compression en ligne 32 K à l'aide du processeur principal.

[cols="2"]
|===
| Plateforme | Version ONTAP 


 a| 
* AFF A1K
* AFF A90
* AFF A70
* FAS90
* FAS70

| 9.15.1 ou ultérieure 


 a| 
* AFF C80
* AFF C60
* AFF C30
* AFF A50
* AFF A30

| 9.16.1 ou ultérieure 
|===
Pour les plates-formes suivantes, l’efficacité du stockage est activée automatiquement et ne nécessite aucune configuration.  Cela s'applique à tous les volumes nouvellement créés et aux données existantes, y compris les volumes déplacés depuis d'autres plates-formes.  La déduplication est activée quel que soit le paramètre de garantie d'espace.  La compression et le compactage des données nécessitent tous deux que la garantie d'espace soit définie sur aucune.  Les données migrées à l'aide de la technologie de déplacement de volume ou de SnapMirror sont automatiquement converties en compression en ligne 32 K.

* AFF C80
* AFF C60
* AFF C30
* AFF A1K
* AFF A90
* AFF A70
* AFF A50
* AFF A30


Pour les plates-formes suivantes, l'efficacité du stockage est activée par défaut uniquement sur les volumes à provisionnement dynamique existants sur lesquels l'efficacité du stockage était activée avant la mise à niveau vers ONTAP 9.15.1 ou une version ultérieure.  Vous pouvez activer l’efficacité du stockage sur les volumes nouvellement créés à l’aide de la méthode CLI ou REST API.  Les données migrées à l'aide de la technologie de déplacement de volume ou de SnapMirror sont converties en compression en ligne 32 K uniquement si la compression a été activée sur la plate-forme d'origine.

* FAS90
* FAS70


Pour plus d'informations sur la mise à niveau d'un contrôleur vers l'une des plates-formes prises en charge, consultez le https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["Documentation sur la mise à niveau du matériel ONTAP"^] .
