---
sidebar: sidebar 
permalink: concepts/capacity-measurements-in-sm-concept.html 
keywords: capacity, measurement, physical, logical, storage, used storage, local tier capacity, aggregate capacity, block, capacity concern, add capacity, volume, used capacity, available capacity, total capacity, inactive capacity, static insights, dynamic insights, snapshot copy, snapshot copies, inactive data, overprovision, overflows, snapshot copy policy, snapshot copy reserves, reserves, policy, top volumes 
summary: La capacité du système peut être mesurée en espace physique ou en espace logique. Les versions récentes de System Manager utilisent des mesures de la capacité physique et logique. 
---
= Mesures de la capacité dans System Manager
:allow-uri-read: 


[role="lead"]
La capacité du système peut être mesurée en espace physique ou en espace logique. Les versions récentes de System Manager utilisent des mesures de la capacité physique et logique.

Les différences entre les deux mesures sont expliquées dans les descriptions suivantes :

* *Capacité physique* : l'espace physique désigne les blocs physiques de stockage utilisés dans le volume ou le niveau local. La valeur de la capacité physique utilisée est généralement inférieure à la valeur de la capacité logique utilisée grâce à la réduction des données provenant des fonctionnalités d'efficacité du stockage (telles que la déduplication et la compression).
* *Capacité logique*: Espace logique fait référence à l'espace utilisable (blocs logiques) dans un volume ou un niveau local. L'espace logique désigne la manière dont l'espace théorique peut être utilisé, sans tenir compte des résultats obtenus grâce à la déduplication ou à la compression. La valeur de l'espace logique utilisé est issue de la quantité d'espace physique utilisé, plus les économies réalisées grâce aux fonctionnalités d'efficacité du stockage (telles que la déduplication et la compression) qui ont été configurées. Cette mesure est souvent supérieure à la capacité physique utilisée, car elle inclut des copies Snapshot, des clones et d'autres composants, et ne reflète pas la compression des données et autres réductions de l'espace physique. La capacité logique totale peut donc être supérieure à l'espace provisionné.



NOTE: Dans System Manager, les représentations de capacité ne prennent pas en compte les capacités du niveau de stockage racine (agrégat).

<<measurements-used-cap>>
<<cap-measurement-terms>>
<<cap-measurement-units>>

.Informations supplémentaires
Vous pouvez surveiller la capacité d'un cluster, ainsi que ses niveaux locaux et ses volumes dans System Manager. Reportez-vous à la section link:./task_admin_monitor_capacity_in_sm.html["Contrôle de la capacité dans System Manager"].



== Mesures de la capacité utilisée

Les mesures de la capacité utilisée s'affichent différemment en fonction de la version de System Manager que vous utilisez, comme expliqué dans le tableau ci-dessous :

[cols="30,30,40"]
|===


| Version de System Manager | Terme utilisé pour la capacité | Type de capacité visé 


 a| 
9.5 et 9.6 (vue classique)
 a| 
Utilisé
 a| 
Espace physique utilisé



 a| 
9.7 et 9.8
 a| 
Utilisé
 a| 
Espace logique utilisé (si les paramètres d'efficacité du stockage ont été activés)



 a| 
9.9.1 et versions ultérieures
 a| 
Utilisation logique
 a| 
Espace logique utilisé (si les paramètres d'efficacité du stockage ont été activés)

|===


== Termes de mesure de la capacité

Les termes suivants sont utilisés pour décrire la capacité :

* *Disponible* : quantité d'espace physique disponible dans un niveau local qui peut être utilisé pour provisionner des volumes.
* *Données client* : espace utilisé par les données client (physique ou logique).
* *Validé* : le montant de la capacité engagée pour un niveau local.
* *Réduction des données* :
+
** *Général* : ratio de tout l'espace logique utilisé par rapport à l'espace physique utilisé.
** *Sans copies et clones Snapshot* : rapport entre l'espace logique utilisé uniquement par les données client et l'espace physique utilisé uniquement par les données client.


* *Logical Used* : quantité d'espace utilisé sans tenir compte de l'espace économisé par les fonctions d'efficacité du stockage.
* *Logical Used %* : pourcentage de la capacité logique utilisée actuelle par rapport à la taille provisionnée, à l'exclusion des réserves snapshot. Cette valeur peut être supérieure à 100 %, grâce aux économies en termes d'efficacité réalisées dans le volume.
* *Physical Used*: La capacité utilisée dans les blocs physiques d'un volume ou d'un niveau local.
* *Physical Used %* : pourcentage de capacité utilisée dans les blocs physiques d'un volume par rapport à la taille provisionnée.
* *Réservé* : espace réservé pour les volumes déjà provisionnés dans un niveau local.
* *Utilisé et réservé* : somme de l'espace physique utilisé et réservé.




== Unités de mesure de la capacité

System Manager calcule la capacité de stockage en fonction des unités binaires de 1024 (2^10^) octets. Dans ONTAP 9.10.0 et versions antérieures, ces unités étaient affichées dans System Manager sous la forme Ko, Mo, Go, To et po. Depuis la version ONTAP 9.10.1, ces options s'affichent dans System Manager comme Kio, Mio, Gio, Tio et Pio.


NOTE: Les unités utilisées dans System Manager pour le débit continuent à être les Ko/s, Mo/s, Go/s, To/s et po/s pour toutes les versions des systèmes ONTAP.

[cols="20,20,30,30"]
|===


| Unité de capacité affichée dans System Manager pour ONTAP 9.10.0 et versions antérieures | Unité de capacité affichée dans System Manager pour ONTAP 9.10.1 et versions ultérieures | Calcul | Valeur en octets 


 a| 
KO
 a| 
Kio
 a| 
1024
 a| 
1024 octets



 a| 
MO
 a| 
Mio
 a| 
1024 * 1024
 a| 
1,048,576 octets



 a| 
GO
 a| 
Gio
 a| 
1024 * 1024 * 1024
 a| 
1,073,741,824 octets



 a| 
TO
 a| 
Tio
 a| 
1024 * 1024 * 1024 * 1024
 a| 
1,099,511,627,776 octets



 a| 
PO
 a| 
Pio
 a| 
1024 * 1024 * 1024 * 1024 * 1024
 a| 
1,125,898,010,834,824 octets

|===
.Informations supplémentaires :
link:./volumes/logical-space-reporting-enforcement-concept.html["Création de rapports sur l'espace logique et application des volumes"]
