---
permalink: concepts/cloud-backup-support-traditional-backups-concept.html 
sidebar: sidebar 
keywords: cloud backup, support, traditional backups 
summary: 'Outre les relations de protection des données SnapMirror et SnapVault, qui n"étaient auparavant qu"un disque à disque, plusieurs solutions de sauvegarde offrent aujourd"hui une alternative moins coûteuse pour la conservation à long terme des données.' 
---
= Sauvegarde dans le cloud et prise en charge des sauvegardes classiques
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Outre les relations de protection des données SnapMirror et SnapVault, qui n'étaient auparavant qu'un disque à disque, plusieurs solutions de sauvegarde offrent aujourd'hui une alternative moins coûteuse pour la conservation à long terme des données.

De nombreuses applications tierces de protection des données proposent des sauvegardes classiques pour les données gérées par ONTAP. Veeam, Veritas et CommVault entre autres proposent une sauvegarde intégrée pour les systèmes ONTAP.

Depuis ONTAP 9.8, SnapMirror Cloud permet la réplication asynchrone des copies Snapshot à partir d'instances ONTAP vers les terminaux de stockage objet. La réplication SnapMirror Cloud requiert une application sous licence pour l'orchestration et la gestion des workflows de protection des données. Les relations SnapMirror avec le cloud sont prises en charge par les systèmes ONTAP afin de sélectionner des cibles de stockage objet sur site et dans le cloud public, notamment AWS S3, Google Cloud Storage Platform ou Microsoft Azure Blob Storage, qui améliorent l'efficacité avec les logiciels de sauvegarde des fournisseurs. Contactez votre conseiller NetApp pour obtenir une liste des fournisseurs d'applications certifiées et de stockage objet pris en charge.

Si la protection des données native du cloud vous intéresse, BlueXP peut être utilisé pour configurer les relations SnapMirror ou SnapVault entre les volumes sur site et les instances Cloud Volumes ONTAP dans le cloud public.

BlueXP fournit également des sauvegardes d'instances Cloud Volumes ONTAP à l'aide d'un modèle SaaS. Les utilisateurs peuvent sauvegarder leurs instances Cloud Volumes ONTAP dans le stockage objet de cloud public compatible S3 et S3 à l'aide de Cloud Backup disponible sur NetApp Cloud Central.

https://www.netapp.com/cloud-services/cloud-manager/documentation/["Ressources de documentation Cloud Volumes ONTAP et BlueXP"]

https://cloud.netapp.com["NetApp Cloud Central"]
