---
permalink: concepts/cloud-backup-support-traditional-backups-concept.html 
sidebar: sidebar 
keywords: cloud backup, support, traditional backups 
summary: Outre les relations de protection des données SnapMirror et SnapVault, qui étaient disque à disque uniquement pour ONTAP 9.7 et les versions antérieures, plusieurs solutions de sauvegarde offrent une alternative moins onéreuse pour la conservation à long terme des données. 
---
= Sauvegarde dans le cloud et prise en charge des sauvegardes classiques
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Outre les relations de protection des données SnapMirror et SnapVault, qui étaient disque à disque uniquement pour ONTAP 9.7 et les versions antérieures, plusieurs solutions de sauvegarde offrent une alternative moins onéreuse pour la conservation à long terme des données.

De nombreuses applications tierces de protection des données proposent des sauvegardes classiques pour les données gérées par ONTAP. Veeam, Veritas et CommVault entre autres proposent une sauvegarde intégrée pour les systèmes ONTAP.

À partir de ONTAP 9.8, le cloud SnapMirror offre une réplication asynchrone des copies Snapshot entre des instances ONTAP et des terminaux de stockage objet. La réplication cloud SnapMirror nécessite une application sous licence pour l'orchestration et la gestion des workflows de protection des données. Les relations cloud SnapMirror sont prises en charge par les systèmes ONTAP pour sélectionner des cibles de stockage objet sur site et dans le cloud public, y compris AWS S3, Google Cloud Storage Platform ou Microsoft Azure Blob Storage, pour une efficacité améliorée avec les logiciels de sauvegarde des fournisseurs. Contactez votre conseiller NetApp pour obtenir une liste des fournisseurs d'applications certifiées et de stockage objet pris en charge.

Si la protection des données native du cloud vous intéresse, BlueXP peut être utilisé pour configurer les relations SnapMirror ou SnapVault entre les volumes sur site et les instances Cloud Volumes ONTAP dans le cloud public.

BlueXP fournit également des sauvegardes d'instances Cloud Volumes ONTAP à l'aide d'un modèle SaaS. Les utilisateurs peuvent sauvegarder leurs instances Cloud Volumes ONTAP dans un stockage objet de cloud public compatible S3 et S3 à l'aide de la sauvegarde et de la restauration BlueXP .

link:https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/index.html["Documentation Cloud Volumes ONTAP"^]

link:https://docs.netapp.com/us-en/bluexp-family/index.html["Documentation BlueXP"^]

link:https://bluexp.netapp.com/["NetApp BlueXP"^]
