---
permalink: concepts/cluster-svm-administrators-concept.html 
sidebar: sidebar 
keywords: cluster, svm administration 
summary: 'Un administrateur de cluster accède au SVM d"admin pour le cluster. Le SVM admin et un administrateur du cluster avec le nom réservé admin sont créés automatiquement lors de la configuration du cluster.' 
---
= Administration des clusters et des SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un _cluster Administrator_ accède au SVM d'admin pour le cluster. La SVM d'admin et un administrateur du cluster avec le nom réservé `admin` sont automatiquement créées lorsque le cluster est configuré.

Un administrateur de cluster avec la valeur par défaut `admin` le rôle peut administrer l'ensemble du cluster et ses ressources. L'administrateur du cluster peut créer d'autres administrateurs de cluster disposant de différents rôles selon les besoins.

Un _administrateur SVM_ accède à un SVM de données. L'administrateur du cluster crée des SVM de données et des administrateurs SVM si nécessaire.

Les administrateurs du SVM sont affectés à `vsadmin` rôle par défaut. L'administrateur du cluster peut attribuer différents rôles aux administrateurs du SVM si nécessaire.

|===


 a| 
*_contrôle d'accès basé sur les rôles (RBAC)_*

Le _role_ attribué à un administrateur détermine les commandes auxquelles l'administrateur a accès. Vous attribuez le rôle lorsque vous créez le compte pour l'administrateur. Vous pouvez attribuer un autre rôle ou définir des rôles personnalisés selon vos besoins.

|===