---
permalink: concepts/fabricpool-concept.html 
sidebar: sidebar 
keywords: storagegrid, storage grid, fabricpool, cloud tier, local tier, aggregate 
summary: 'De nombreux clients de NetApp disposent d"une quantité importante de données stockées rarement utilisées. Nous appelons les données inactives. Les clients disposent également de données fréquemment utilisées, que nous appelons les données fortement sollicitées. Dans l"idéal, vous souhaitez maintenir vos données actives dans votre système de stockage le plus rapide pour obtenir des performances optimales. Les données inactives peuvent être déplacées vers un stockage plus lent tant qu"elles sont immédiatement disponibles si nécessaire. Mais comment savoir quelles parties de vos données sont actives et lesquelles sont inactives ?' 
---
= FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
De nombreux clients de NetApp disposent d'une quantité importante de données stockées rarement utilisées. On appelle les données _COLD_. Les clients disposent également de données fréquemment utilisées, que nous appelons les données _hot_. Dans l'idéal, vous souhaitez maintenir vos données actives dans votre système de stockage le plus rapide pour obtenir des performances optimales. Les données inactives peuvent être déplacées vers un stockage plus lent tant qu'elles sont immédiatement disponibles si nécessaire. Mais comment savoir quelles parties de vos données sont actives et lesquelles sont inactives ?

FabricPool est une fonctionnalité ONTAP qui déplace automatiquement les données entre un Tier local haute performance et un Tier cloud basé sur des modèles d'accès. Le Tiering libère du stockage local coûteux pour les données actives, tout en maintenant les données inactives disponibles immédiatement à partir d'un stockage objet à faible coût dans le cloud. FabricPool surveille en permanence l'accès aux données et les déplace entre les différents niveaux pour des performances optimales et des économies maximales.

L'utilisation de FabricPool pour déplacer les données inactives vers le cloud est l'un des moyens les plus simples d'obtenir des services efficaces dans le cloud et de créer une configuration de cloud hybride. FabricPool fonctionne au niveau du bloc de stockage et fonctionne donc aussi bien avec les données de fichiers que de LUN.

Toutefois, FabricPool n'est pas réservé au Tiering des données sur site vers le cloud. De nombreux clients utilisent FabricPool dans Cloud Volumes ONTAP pour transférer les données inactives d'un stockage cloud plus onéreux vers un stockage objet moins coûteux au sein du fournisseur cloud. À partir de ONTAP 9.8, vous pouvez capturer des analyses sur des volumes compatibles FabricPool avec link:../concept_nas_file_system_analytics_overview.html["Analytique du système de fichiers"] ou link:../volumes/enable-temperature-sensitive-efficiency-concept.html["efficacité du stockage sensible à la température"].

Les applications qui utilisent les données n'ont pas connaissance du Tier de stockage. Aucune modification n'est donc nécessaire. Le Tiering est entièrement automatique. Aucune administration n'est donc nécessaire.

Vous pouvez stocker les données inactives dans le stockage objet à partir de l'un des principaux fournisseurs cloud. Vous pouvez également choisir NetApp StorageGRID pour conserver vos données inactives dans votre propre cloud privé et bénéficier d'une performance optimale et d'un contrôle total sur vos données.

.Informations associées
https://docs.netapp.com/us-en/ontap/concept_cloud_overview.html["Document FabricPool System Manager"^]

https://docs.netapp.com/us-en/bluexp-tiering/index.html["Tiering BlueXP"^]

https://www.youtube.com/playlist?list=PLdXI3bZJEw7mcD3RnEcdqZckqKkttoUpS["Liste de lecture FabricPool sur NetApp TechComm TV"^]
