---
permalink: concepts/index.html 
sidebar: sidebar 
keywords: decide, concepts, ontap, overview, data, management, cluster storage, high-availability, virtualization, protection, storage, efficiency, security 
summary: 'Les concepts suivants contribuent au logiciel de gestion des données ONTAP, notamment le stockage en cluster, la haute disponibilité, la virtualisation et la protection des données l"efficacité du stockage et la sécurité.' 
---
= Présentation des concepts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les concepts suivants contribuent au logiciel de gestion des données ONTAP, notamment le stockage en cluster, la haute disponibilité, la virtualisation et la protection des données l'efficacité du stockage et la sécurité. Avant de configurer votre solution de stockage, vous devez connaître l'ensemble des fonctionnalités et avantages de ONTAP.

Si vous avez besoin d'informations de référence et de configuration sur les fonctionnalités ONTAP, consultez les documents suivants :

* Configuration haute disponibilité (HA)
+
link:../high-availability/index.html["Haute disponibilité"]

* Administration des clusters et des SVM
+
link:../system-admin/index.html["Administration du système"]

* Gestion du réseau et des LIF
+
link:../networking/index.html["Gestion du réseau"]

* Disques et agrégats
+
link:../disks-aggregates/index.html["Gestion des disques et des agrégats"]

* Les volumes FlexVol, la technologie FlexClone et les fonctionnalités d'efficacité du stockage
+
link:../volumes/index.html["Gestion du stockage logique"]

* Provisionnement d'hôtes SAN
+
link:../san-admin/index.html["Administration SAN"]

* Un accès aux fichiers NAS
+
** link:../nfs-admin/index.html["Gestion NFS"]
** link:../smb-admin/index.html["Gestion SMB"]


* Reprise après incident et archivage
+
link:../data-protection/index.html["Protection des données"]


