---
permalink: concepts/manual-pages.html 
sidebar: sidebar 
keywords: CLI commands, manual pages, volume create, volume modify, volume show, volume move, snapmirror show, snapmirror create, vserver create, network interface show, storage disk show, volume delete, man pages, cli comparison tool, cli diff 
summary: 'Les pages du manuel ONTAP expliquent comment utiliser les commandes CLI d"ONTAP. Recherchez la référence de commande pour la version de ONTAP que vous utilisez.' 
---
= Référence de commande ONTAP
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour chaque version majeure de ONTAP, les commandes CLI les plus courantes (pages de manuel ONTAP ou pages de manuel) sont regroupées dans un link:https://docs.netapp.com/us-en/ontap-cli/["_référence de commande_"^]. Ces références de commandes expliquent comment utiliser les commandes CLI dans chaque version de ONTAP. Les pages man sont également disponibles sur la ligne de commande ONTAP avec la `man` commande. Pour en savoir plus, `man` consultez le link:https://docs.netapp.com/us-en/ontap-cli/man.html["Référence de commande ONTAP"^].



== Références des commandes pour les versions de support limitées de ONTAP (PDF uniquement)

* link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2843631["ONTAP 9.4"^]




== Outil de comparaison CLI

Pour en savoir plus sur les modifications apportées aux commandes de l'interface de ligne de commandes entre les versions de ONTAP, consultez le link:https://mysupport.netapp.com/site/info/cli-comparison["Outil de comparaison CLI"^] Sur le site de support NetApp.

.Informations associées
* xref:../system-admin/command-line-interface-concept.html[Utilisez l'interface de ligne de commande ONTAP]
* xref:../system-admin/methods-navigating-cli-command-directories-concept.html[Méthodes de navigation dans les répertoires de commandes CLI]

