---
permalink: concepts/rdma-concept.html 
sidebar: sidebar 
keywords: Remote Direct Memory Access, NFS over RDMA, RoCE, intercluster 
summary: 'NFS sur RDMA et l"interconnexion des clusters RDMA exploitent RDMA pour améliorer les performances des charges de travail à large bande passante.' 
---
= Présentation de RDMA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous disposez de charges de travail sensibles à la latence ou à large bande passante, vous pouvez tirer parti des offres RDMA d'ONTAP. RDMA permet de copier directement les données entre la mémoire du système de stockage et la mémoire du système hôte, ce qui évite les interruptions du processeur et la surcharge.



== NFS sur RDMA

Vous pouvez le configurer avec ONTAP 9.10.1 link:../nfs-rdma/index.html["NFS sur RDMA"] Pour permettre l'utilisation du stockage NVIDIA GPUDirect pour les workloads avec accélération par processeur graphique sur des hôtes équipés de processeurs graphiques NVIDIA pris en charge.



== Interconnexion de cluster RDMA

Depuis ONTAP 9.10.1, ONTAP prend en charge l'interconnexion de cluster RDMA pour les utilisateurs ONTAP avec un système de stockage A400 ou ASA400 avec des cartes réseau de cluster Pensando. L'interconnexion de cluster RDMA réduit la latence, réduit les temps de basculement et accélère la communication entre les nœuds d'un cluster. Aucune configuration supplémentaire n'est nécessaire compte tenu de la configuration adéquate du système de stockage.

.Plus d'informations
* xref:../nfs-rdma/index.html[NFS sur RDMA]
* link:https://docs.netapp.com/us-en/e-series/config-linux/nvme-roce-configure-storage-connections-task.html["Configuration des connexions NVMe over RoCE de la baie de stockage"^]

