---
permalink: concepts/rdma-concept.html 
sidebar: sidebar 
keywords: Remote Direct Memory Access, NFS over RDMA, RoCE, intercluster 
summary: 'Les offres RDMA (Remote Direct Memory Access) d"ONTAP prennent en charge les charges de travail à large bande passante et sensibles à la latence. RDMA permet de copier directement les données entre la mémoire du système de stockage et la mémoire du système hôte, évitant ainsi les interruptions et la surcharge du processeur' 
---
= Présentation de RDMA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les offres RDMA (Remote Direct Memory Access) d'ONTAP prennent en charge les charges de travail à large bande passante et sensibles à la latence. RDMA permet de copier directement les données entre la mémoire du système de stockage et la mémoire du système hôte, ce qui évite les interruptions du processeur et la surcharge.



== NFS sur RDMA

Vous pouvez le configurer avec ONTAP 9.10.1 link:../nfs-rdma/index.html["NFS sur RDMA"] Pour permettre l'utilisation du stockage NVIDIA GPUDirect pour les workloads avec accélération par processeur graphique sur des hôtes équipés de processeurs graphiques NVIDIA pris en charge.



== Interconnexion de cluster RDMA

Le protocole RDMA d'interconnexion de cluster réduit la latence, réduit les temps de basculement et accélère la communication entre les nœuds d'un cluster.

À partir de ONTAP 9.10.1, le protocole RDMA d'interconnexion de cluster est pris en charge pour certains systèmes matériels lorsqu'il est utilisé avec des cartes réseau de cluster X1151A. À partir de ONTAP 9.13.1, les cartes réseau X91153A prennent également en charge le protocole RDMA d'interconnexion de cluster. Consultez le tableau pour connaître les systèmes pris en charge dans les différentes versions de ONTAP.

|===
| Systèmes | Versions de ONTAP prises en charge 


 a| 
* AFF A50
* AFF A30
* AFF A20
* AFF C80
* AFF C60
* AFF C30
* ASA A50
* ASA A30
* ASA A20

| ONTAP 9.16.1 et versions ultérieures 


 a| 
* AFF A1K
* AFF A90
* AFF A70
* ASA A1K
* ASA A90
* ASA A70
* FAS90
* FAS70

| ONTAP 9.15.1 et versions ultérieures 


 a| 
* AFF A400
* ASA A400

| ONTAP 9.10.1 et versions ultérieures 


 a| 
* AFF A900
* ASA A900
* FAS9500

| ONTAP 9.13.1 et versions ultérieures 
|===
Étant donné la configuration appropriée du système de stockage, aucune configuration supplémentaire n'est nécessaire pour utiliser le protocole RDMA d'interconnexion de cluster.
