---
sidebar: sidebar 
permalink: concepts/sysmgr-integration-bluexp-concept.html 
keywords: netapp, ontap, system manager, experience, integrate, integration, bluexp, hybrid, cloud, dashboard, multicloud 
summary: 'À partir de ONTAP 9.12.1, System Manager est entièrement intégré à BlueXP.  BlueXP vous permet de gérer votre infrastructure multicloud hybride à partir d"un seul plan de contrôle tout en conservant le tableau de bord familier de System Manager.' 
---
= Intégration de System Manager à BlueXP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
À partir de ONTAP 9.12.1, System Manager est entièrement intégré à BlueXP.  BlueXP vous permet de gérer votre infrastructure multicloud hybride à partir d'un seul plan de contrôle tout en conservant le tableau de bord familier de System Manager.

BlueXP vous permet de créer et de gérer le stockage cloud (par exemple Cloud Volumes ONTAP), d'utiliser les services de données NetApp (par exemple, Cloud Backup) et de contrôler de nombreux périphériques de stockage sur site et périphériques.

Pour utiliser System Manager dans BlueXP, effectuez les opérations suivantes :

.Étapes
. Ouvrez un navigateur Web et entrez l'adresse IP de l'interface réseau de gestion du cluster.
+
Si le cluster est connecté à BlueXP, une invite de connexion s'affiche.

. Cliquez sur *Continuer vers BlueXP* pour suivre le lien vers BlueXP.
+

NOTE: Si vos paramètres système ont bloqué des réseaux externes, vous ne pourrez pas accéder à BlueXP.  Pour accéder à System Manager à l'aide de BlueXP, vous devez vous assurer que l'adresse « cloudmanager.cloud.netapp.com`" est accessible par votre système.  Sinon, à l'invite, vous pouvez choisir d'utiliser la version de System Manager installée avec votre système ONTAP.

. Sur la page de connexion BlueXP, sélectionnez *Connectez-vous avec vos informations d'identification du site de support NetApp* et saisissez vos identifiants.
+
Si vous avez déjà utilisé BlueXP et que vous disposez d’une connexion à l’aide d’un e-mail et d’un mot de passe, vous devez continuer à utiliser cette option de connexion.

+
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html["En savoir plus sur la connexion à BlueXP"^].

. Si vous y êtes invité, entrez un nom pour votre nouveau compte BlueXP.
+
Dans la plupart des cas, BlueXP crée automatiquement un compte pour vous en fonction des données de votre cluster.

. Saisissez les informations d'identification de l'administrateur du cluster pour le cluster.


.Résultat
System Manager s'affiche et vous pouvez désormais gérer le cluster depuis BlueXP.



== Découvrez vos clusters directement à partir de BlueXP

BlueXP offre deux façons de découvrir et de gérer vos clusters :

* Détection directe pour la gestion via System Manager
+
Il s'agit de la même option de découverte décrite dans la section précédente avec laquelle vous suivez la redirection.

* Découverte via un connecteur
+
Ce connecteur est un logiciel installé dans votre environnement qui vous permet d'accéder aux fonctions de gestion via System Manager. Il permet également d'accéder aux services cloud BlueXP qui offrent des fonctionnalités telles que la réplication, la sauvegarde et la restauration, le classement des données, le Tiering des données, etc.



Accédez au https://docs.netapp.com/us-en/cloud-manager-family/index.html["Documentation BlueXP"^] pour en savoir plus sur ces options de découverte et de gestion.



== En savoir plus sur BlueXP

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["Présentation de BlueXP"^]
* https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/index.html["Gérez vos systèmes NetApp AFF et FAS à l'aide de BlueXP"^]

