---
sidebar: sidebar 
permalink: concepts/sysmgr-integration-bluexp-concept.html 
keywords: netapp, ontap, system manager, experience, integrate, integration, bluexp, hybrid, cloud, dashboard, multicloud 
summary: 'Vous pouvez gérer ONTAP 9.10.1 et les versions ultérieures avec System Manager dans BlueXP. Cette intégration vous permet de superviser efficacement votre infrastructure multicloud hybride grâce à un plan de contrôle unifié, tout en conservant l"interface utilisateur familière de System Manager.' 
---
= Intégrer ONTAP System Manager avec BlueXP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez gérer ONTAP 9.10.1 et les versions ultérieures avec System Manager dans BlueXP. Cette intégration vous permet de superviser efficacement votre infrastructure multicloud hybride grâce à un plan de contrôle unifié, tout en conservant l'interface utilisateur familière de System Manager.

BlueXP vous permet de créer et d'administrer le stockage cloud (par exemple, Cloud Volumes ONTAP), d'utiliser les services de données NetApp (par exemple, Cloud Backup) et de contrôler de nombreux périphériques de stockage sur site et en périphérie.

BlueXP offre deux façons de découvrir et de gérer vos clusters :

* Découverte directe pour la gestion via System Manager (ONTAP 9.12.1 et versions ultérieures)
* Découverte via un connecteur


Le connecteur est un logiciel installé dans votre environnement. Il vous permet d'accéder aux fonctions de gestion via le Gestionnaire système et aux services cloud BlueXP, qui offrent des fonctionnalités telles que la réplication, la sauvegarde et la restauration des données, la classification et la hiérarchisation des données, etc.

En savoir plus sur link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html["Gestion des clusters ONTAP sur site à l'aide de BlueXP"^].

.Étapes
. Connectez-vous à BlueXP.
+
.. Si vous disposez d'un identifiant BlueXP, utilisez-le.
.. S'il s'agit de votre première fois, sélectionnez Se connecter avec vos informations d'identification du site de support NetApp et saisissez vos informations d'identification sur la page de connexion BlueXP.


. Découvrez votre cluster sur site dans BlueXP à l'aide d'un connecteur ou d'une découverte directe. Pour en savoir plus, consultez le lien : https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html [découverte des clusters ONTAP sur site^].
+
.. Découvrez comment link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-direct.html["gérer les clusters qui ont été découverts directement"^].
.. Découvrez comment link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-connector.html["gérer les clusters découverts avec un connecteur"^].


. Gérez votre cluster sur site avec le Gestionnaire système. Dans la section « Mes environnements de travail », sélectionnez le cluster, puis cliquez sur « Gestionnaire système » dans la liste des services.
+
.. En savoir plus sur link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-direct.html["gérer les clusters découverts directement"^].
.. Découvrez comment link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-connector.html["gérer les clusters découverts avec un connecteur"^].






== BlueXP et ONTAP 9.12.1

Remarque : si vous utilisez ONTAP 9.12.1, un message s’affiche pour vous inviter à essayer BlueXP.

+ Si le cluster dispose d'une connectivité à BlueXP, une invite de connexion s'affiche.

. Cliquez sur *Continuer vers BlueXP* pour suivre le lien vers BlueXP.
+

NOTE: Si vos paramètres système ont bloqué des réseaux externes, vous ne pourrez pas accéder à BlueXP.  Pour accéder à System Manager à l'aide de BlueXP, vous devez vous assurer que l'adresse « cloudmanager.cloud.netapp.com`" est accessible par votre système.  Sinon, à l'invite, vous pouvez choisir d'utiliser la version de System Manager installée avec votre système ONTAP.

. Sur la page de connexion BlueXP, sélectionnez *Connectez-vous avec vos informations d'identification du site de support NetApp* et saisissez vos identifiants.
+
Si vous avez déjà utilisé BlueXP et que vous disposez d'une connexion utilisant un e-mail et un mot de passe, vous devrez continuer à utiliser cette option de connexion à la place.

+
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html["En savoir plus sur la connexion à BlueXP"^].

. Si vous y êtes invité, entrez un nom pour votre nouveau compte BlueXP.
+
Dans la plupart des cas, BlueXP crée automatiquement un compte pour vous en fonction des données de votre cluster.

. Saisissez les informations d'identification de l'administrateur du cluster pour le cluster.


.Résultat
System Manager s'affiche et vous pouvez désormais gérer le cluster depuis BlueXP.



== En savoir plus sur BlueXP

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["Présentation de BlueXP"^]
* https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/index.html["Gérez vos systèmes NetApp AFF et FAS à l'aide de BlueXP"^]

