---
sidebar: sidebar 
permalink: concepts/sysmgr-integration-console-concept.html 
keywords: netapp, ontap, system manager, experience, integrate, integration, bluexp, netapp console, console, hybrid, cloud, dashboard, multicloud 
summary: 'Vous pouvez gérer ONTAP 9.10.1 et les versions ultérieures à l"aide du Gestionnaire système dans la console NetApp .  Cette intégration vous permet de superviser efficacement votre infrastructure multicloud hybride à l"aide d"un plan de contrôle unifié, tout en conservant l"interface utilisateur familière de System Manager.' 
---
= Intégrer ONTAP System Manager à la console NetApp
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Vous pouvez gérer ONTAP 9.10.1 et les versions ultérieures à l'aide du Gestionnaire système dans la console NetApp .  Cette intégration vous permet de superviser efficacement votre infrastructure multicloud hybride à l'aide d'un plan de contrôle unifié, tout en conservant l'interface utilisateur familière de System Manager.

La console vous permet de créer et d'administrer le stockage cloud (par exemple, Cloud Volumes ONTAP), d'utiliser les services de données NetApp (par exemple, Cloud Backup) et de contrôler de nombreux périphériques de stockage sur site et en périphérie.

La console propose deux manières de découvrir et de gérer vos clusters :

* Découverte directe pour la gestion via System Manager (ONTAP 9.12.1 et versions ultérieures)
* Découverte via un agent Console.


L'agent de console est un logiciel installé dans votre environnement.  Cela vous permet d'accéder aux fonctions de gestion via System Manager et d'accéder aux services cloud NetApp qui fournissent des fonctionnalités telles que la réplication des données, la sauvegarde et la récupération, la classification des données, la hiérarchisation des données, etc.

En savoir plus sur link:https://docs.netapp.com/us-en/storage-management-ontap-onprem/index.html["Gestion des clusters ONTAP sur site à l'aide de la console NetApp"^] .

.Étapes
. Connectez-vous à la console NetApp .
+
.. Si vous disposez d'un identifiant de console, utilisez-le.
.. S'il s'agit de votre première fois, sélectionnez Se connecter avec vos informations d'identification du site de support NetApp et saisissez vos informations d'identification sur la page de connexion de la console.


. Découvrez votre cluster sur site dans la console à l’aide d’un agent de console ou d’une découverte directe. En savoir plus sur le lien : https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html [découverte des clusters ONTAP sur site^].
+
.. Découvrez comment link:https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-manage-ontap-direct.html["gérer les clusters qui ont été découverts directement"^] .
.. Découvrez comment link:https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-manage-ontap-connector.html["gérer les clusters découverts avec un agent de console"^] .


. Gérez votre cluster sur site à l’aide de System Manager.  Sur la page Systèmes de mes environnements de travail, sélectionnez le cluster et cliquez sur Gestionnaire système dans la liste Services.
+
.. En savoir plus sur link:https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-manage-ontap-direct.html["gérer les clusters découverts directement"^] .
.. Découvrez comment link:https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-manage-ontap-connector.html["gérer les clusters découverts avec un agent de console"^] .






== Console NetApp et ONTAP 9.12.1

Remarque : si vous utilisez ONTAP 9.12.1, un message s’affiche pour vous inviter à essayer la console NetApp .

+ Si le cluster dispose d’une connectivité à la console NetApp , une invite de connexion s’affiche.

. Cliquez sur *Continuer vers la console NetApp * pour suivre le lien vers la console.
+

NOTE: Si les paramètres de votre système ont bloqué les réseaux externes, vous ne pourrez pas accéder à la console.  Pour accéder au Gestionnaire système à l'aide de la console, vous devez vous assurer que l'adresse « cloudmanager.cloud.netapp.com » est accessible par votre système.  Sinon, à l'invite, vous pouvez choisir d'utiliser la version de System Manager installée avec votre système ONTAP .

. Sur la page de connexion de la console, sélectionnez *Se connecter avec vos informations d'identification du site de support NetApp * et saisissez vos informations d'identification.
+
Si vous avez déjà utilisé la console et que vous disposez d'une connexion utilisant un e-mail et un mot de passe, vous devrez continuer à utiliser cette option de connexion à la place.

+
https://docs.netapp.com/us-en/console-setup-admin/task-logging-in.html["En savoir plus sur la connexion à la console NetApp"^] .

. Si vous y êtes invité, entrez un nom pour votre nouveau compte NetApp Console.
+
Dans la plupart des cas, la console crée automatiquement un compte pour vous en fonction des données de votre cluster.

. Saisissez les informations d'identification de l'administrateur du cluster pour le cluster.


.Résultat
Le Gestionnaire système s'affiche et vous pouvez désormais gérer le cluster depuis la console.



== En savoir plus sur la console NetApp

* https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html["Présentation de la console NetApp"^]
* https://docs.netapp.com/us-en/storage-management-ontap-onprem/index.html["Gérez vos systèmes NetApp AFF et FAS via la console NetApp"^]

