---
permalink: concepts/thin-provisioning-concept.html 
sidebar: sidebar 
keywords: thin provision 
summary: 'Une LUN ou un volume à provisionnement fin est un volume pour lequel le stockage n"est pas réservé à l"avance. Au contraire, le stockage est alloué de manière dynamique, selon les besoins. L"espace libre est relibéré dans le système de stockage lorsque les données du volume ou de la LUN sont supprimées.' 
---
= Provisionnement fin
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP propose un large éventail de technologies d'efficacité du stockage, en plus des copies Snapshot. Les technologies clés sont le provisionnement fin, la déduplication, la compression, ainsi que les volumes FlexClone, les fichiers Et des LUN. À l'instar des copies Snapshot, elles reposent sur le WAFL (Write Anywhere File Layout) d'ONTAP.

Un _volume_ provisionné_ ou une LUN est un volume pour lequel le stockage n'est pas réservé à l'avance. Au contraire, le stockage est alloué de manière dynamique, selon les besoins. L'espace libre est relibéré dans le système de stockage lorsque les données du volume ou de la LUN sont supprimées.

Imaginez que votre entreprise doit fournir à 5,000 utilisateurs du stockage pour les répertoires locaux. Vous estimez que les principaux répertoires locaux consommeront 1 Go d'espace.

Dans ce cas, vous pouvez acheter 5 To de stockage physique. Pour chaque volume qui stocke un home Directory, vous pouvez réserver suffisamment d'espace pour répondre aux besoins des plus grands consommateurs.

En pratique, cependant, vous savez aussi que les besoins en capacité des répertoires d'accueil varient considérablement d'un bout à l'autre de votre communauté. Pour chaque grand utilisateur du stockage, dix ne consomment que peu ou pas d'espace.

Le provisionnement fin vous permet de répondre aux besoins des grands consommateurs de stockage sans acheter de stockage que vous n'utiliserez probablement pas. L'espace de stockage n'étant pas alloué tant qu'il n'est pas consommé, vous pouvez « surallouer » un agrégat de 2 To en attribuant théoriquement une taille de 1 Go à chacun des 5,000 volumes que l'agrégat contient.

Tant que vous avez raison de ratios de lumière 10:1 pour les utilisateurs intensifs et tant que vous jouez un rôle actif dans la surveillance de l'espace libre de l'agrégat, vous pouvez compter sur le fait que les écritures de volume ne échouent pas en raison du manque d'espace.
