---
permalink: nfs-rdma/configure-nics-task.html 
sidebar: sidebar 
keywords: networking, NICs, NFS over RDMA, NVIDIA, NFS, system manager, ports, ethernet ports 
summary: 'Cet article explique comment les processus de configuration du système client et de la plateforme de stockage, ainsi que les exigences des cartes réseau pour qu"elles utilisent NFS sur RDMA dans ONTAP.' 
---
= Configurer les cartes réseau pour NFS sur RDMA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS sur RDMA requiert une configuration de carte réseau pour le système client et la plateforme de stockage.



== Configuration de la plateforme de stockage

Pour plus d'informations sur la prise en charge de RNIC cible, reportez-vous au https://hwu.netapp.com/["NetApp Hardware Universe"^].

Si vous utilisez une configuration haute disponibilité, les deux nœuds doivent utiliser le même RNIC pour prendre en charge le basculement RDMA. La carte réseau doit être compatible RoCE.

* Depuis ONTAP 9.10.1, vous pouvez afficher la liste des protocoles de déchargement RDMA avec la commande :
+
[source, cli]
----
network port show -rdma-protocols roce
----
+
Pour en savoir plus, `network port show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/network-port-show.html["Référence de commande ONTAP"^].

* A partir de ONTAP 9.16.1, il est recommandé d'utiliser le contrôle de débit prioritaire (PFC). Configurer le PFC à l'aide de la `network port modify` commande :
+
[source, cli]
----
network port modify -node <nodename> -port <portname> -flowcontrol-admin pfc -pfc-queues-admin 3
----
* Avant ONTAP 9.16.1, il est recommandé d'utiliser le contrôle de flux global par défaut (GFC). Si le paramètre de contrôle de flux a été modifié, configurez GFC à l'aide de la `network port modify` commande :
+
[source, cli]
----
network port modify -node <nodename> -port <portname> -flowcontrol-admin full
----
+
Pour en savoir plus, `network port modify` consultez le link:https://docs.netapp.com/us-en/ontap-cli/network-port-modify.html["Référence de commande ONTAP"^].





== Configuration du système client

Pour plus d'informations sur les systèmes d'exploitation clients pris en charge pour NFS sur RDMA, reportez-vous au https://imt.netapp.com/matrix/["Matrice d'interopérabilité NetApp (IMT)"^] . Pour les RNIC RoCE v2 pris en charge, reportez-vous à la documentation du fournisseur RNIC correspondant.

Bien que le client et le serveur puissent être directement connectés, l'utilisation de commutateurs est recommandée pour améliorer les performances de basculement.

Le client, le serveur, tous les commutateurs et tous les ports des commutateurs doivent être configurés à l'aide de trames Jumbo. La configuration de contrôle de flux sur les clients et les commutateurs doit correspondre à la configuration de contrôle de flux de ONTAP. À partir de ONTAP 9.16.1, il est recommandé d'activer et de configurer le contrôle de flux par priorité sur ONTAP, les commutateurs et les clients. Avant ONTAP 9.16.1, il est recommandé d'utiliser le contrôle de flux global.

Une fois cette configuration confirmée, vous pouvez monter l'exportation NFS à l'aide de RDMA.

[role="tabbed-block"]
====
.System Manager
--
Vous devez utiliser ONTAP 9.12.1 ou version ultérieure pour configurer les interfaces réseau avec NFS sur RDMA à l'aide de System Manager.

.Étapes
. Vérifier si le protocole RDMA est pris en charge. Accédez à *réseau > ports Ethernet* et sélectionnez le nœud approprié dans la vue de groupe. Lorsque vous développez le nœud, examinez le champ *protocoles RDMA* pour un port donné : la valeur *RoCE* indique que RDMA est pris en charge ; un tiret (*-*) indique qu'il n'est pas pris en charge.
. Pour ajouter un VLAN, sélectionnez *+ VLAN*. Sélectionnez le nœud approprié. Dans le menu déroulant *Port*, les ports disponibles affichent le texte *RoCE Enabled* s'ils prennent en charge RDMA. Aucun texte ne s'affiche s'ils ne prennent pas en charge RDMA.
. Suivez le flux de travail dans xref:../task_nas_enable_linux_nfs.html[Activez le stockage NAS pour les serveurs Linux à l'aide de NFS] Pour configurer un nouveau serveur NFS.
+
Lorsque vous ajoutez des interfaces réseau, vous avez la possibilité de sélectionner *utiliser les ports RoCE*. Sélectionnez cette option pour les interfaces réseau que vous souhaitez utiliser NFS sur RDMA.



--
.CLI
--
. Vérifier si l'accès RDMA est activé sur le serveur NFS avec la commande :
+
`vserver nfs show-vserver <SVM_name>`

+
Par défaut, `-rdma` doit être activé. Si ce n'est pas le cas, activer l'accès RDMA sur le serveur NFS :

+
`vserver nfs modify -vserver <SVM_name> -rdma enabled`

. Monter le client via NFSv4.0 sur RDMA :
+
.. L'entrée du paramètre proto dépend de la version du protocole IP du serveur. S'il s'agit d'IPv4, utilisez `proto=rdma`. S'il s'agit du protocole IPv6, utilisez-le `proto=rdma6`.
.. Spécifiez le port cible NFS en tant que `port=20049` au lieu du port standard 2049 :
+
`mount -o vers=4,minorversion=0,proto=rdma,port=20049 <Server_IP_address>:/<volume_path> <mount_point>`



. *FACULTATIF* : si vous devez démonter le client, exécutez la commande `unmount <mount_path>`


--
====
.Plus d'informations
* xref:../nfs-config/create-server-task.html[Créer des serveurs ONTAP NFS]
* xref:../task_nas_enable_linux_nfs.html[Activez le stockage NAS pour les serveurs Linux à l'aide de NFS]

