---
permalink: error-messages/configure-snmp-traphosts-event-notifications-task.html 
sidebar: sidebar 
keywords: configuring, snmp, traphosts, receive, event notifications 
summary: 'Pour recevoir des notifications d"événements sur un Traphost SNMP, vous devez configurer un Traphost.' 
---
= Configurez les Traphosts SNMP pour recevoir des notifications d'événement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour recevoir des notifications d'événements sur un Traphost SNMP, vous devez configurer un Traphost.

.Avant de commencer
* Les traps SNMP doivent être activés sur le cluster.
+
[NOTE]
====
Les interruptions SNMP et SNMP sont activées par défaut.

====
* Le DNS doit être configuré sur le cluster pour résoudre les noms de Traphost.


.Description de la tâche
Si aucun Traphost SNMP n'est déjà configuré pour recevoir des notifications d'événements (traps SNMP), vous devez en ajouter un.

Vous pouvez effectuer cette tâche à tout moment du cluster en entrant les commandes sur la ligne de commande ONTAP.

.Étape
. Si votre environnement ne dispose pas déjà d'un Traphost SNMP configuré pour recevoir des notifications d'événement, ajoutez-en un :
+
`system snmp traphost add -peer-address _snmp_traphost_name_`

+
Toutes les notifications d'événements prises en charge par SNMP par défaut sont transmises au Traphost SNMP.


