---
permalink: error-messages/configure-ems-events-send-email-task.html 
sidebar: sidebar 
keywords: configuring, important, ems, events, send, email, notifications 
summary: 'Pour recevoir des notifications par e-mail des événements les plus importants, vous devez configurer l"EMS pour qu"il envoie des e-mails pour les événements qui signalent une activité importante.' 
---
= Configurez les événements EMS ONTAP importants pour envoyer des notifications par e-mail
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour recevoir des notifications par e-mail des événements les plus importants, vous devez configurer l'EMS pour qu'il envoie des e-mails pour les événements qui signalent une activité importante.

.Avant de commencer
Le DNS doit être configuré sur le cluster pour résoudre les adresses e-mail.

.Description de la tâche
Vous pouvez effectuer cette tâche à tout moment du cluster en entrant les commandes sur la ligne de commande ONTAP.

.Étapes
. Configurez les paramètres du serveur de messagerie SMTP d'événement :
+
`event config modify -mail-server mailhost.your_domain -mail-from cluster_admin@your_domain`

. Créer une destination e-mail pour les notifications d'événements :
+
`event notification destination create -name storage-admins -email your_email@your_domain`

. Configurez les événements importants pour envoyer des notifications par e-mail :
+
`event notification create -filter-name important-events -destinations storage-admins`


