---
permalink: nfs-admin/access-ntfs-volumes-qtrees-unknown-users-task.html 
sidebar: sidebar 
keywords: handle, nfs, access, ntfs, volumes, qtrees, unknown, unix, users 
summary: 'Si ONTAP ne peut pas identifier les utilisateurs UNIX qui tentent de se connecter à des volumes ou des qtrees avec le style de sécurité NTFS, il ne peut donc pas mapper l"utilisateur de façon explicite à un utilisateur Windows. Vous pouvez configurer ONTAP de manière à refuser l"accès à ces utilisateurs pour une sécurité plus stricte ou les mapper à un utilisateur Windows par défaut afin d"assurer un niveau d"accès minimum pour tous les utilisateurs.' 
---
= Gérer l'accès NFS aux volumes ONTAP NTFS ou aux qtrees pour les utilisateurs UNIX inconnus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si ONTAP ne peut pas identifier les utilisateurs UNIX qui tentent de se connecter à des volumes ou des qtrees avec le style de sécurité NTFS, il ne peut donc pas mapper l'utilisateur de façon explicite à un utilisateur Windows. Vous pouvez configurer ONTAP de manière à refuser l'accès à ces utilisateurs pour une sécurité plus stricte ou les mapper à un utilisateur Windows par défaut afin d'assurer un niveau d'accès minimum pour tous les utilisateurs.

.Avant de commencer
Un utilisateur Windows par défaut doit être configuré si vous souhaitez activer cette option.

.Description de la tâche
Si un utilisateur UNIX tente d'accéder aux volumes ou aux qtrees avec un style de sécurité NTFS, l'utilisateur UNIX doit d'abord être mappé à un utilisateur Windows afin que ONTAP puisse correctement évaluer les autorisations NTFS. Cependant, si ONTAP ne peut pas rechercher le nom de l'utilisateur UNIX dans les sources de service de nom d'informations utilisateur configurées, il ne peut pas explicitement mapper l'utilisateur UNIX à un utilisateur Windows spécifique. Vous pouvez décider comment gérer ces utilisateurs UNIX inconnus de la manière suivante :

* Refuser l'accès aux utilisateurs UNIX inconnus.
+
Ceci met en œuvre une sécurité plus stricte en nécessitant un mappage explicite pour tous les utilisateurs UNIX afin d'accéder aux volumes ou aux qtrees NTFS.

* Mapper des utilisateurs UNIX inconnus à un utilisateur Windows par défaut.
+
Cette fonctionnalité offre moins de sécurité et davantage de commodité, en veillant à ce que tous les utilisateurs aient un niveau d'accès minimal aux volumes NTFS ou aux qtrees par l'intermédiaire d'un utilisateur Windows par défaut.



.Étapes
. Définissez le niveau de privilège sur avancé :
+
`set -privilege advanced`

. Effectuez l'une des opérations suivantes :
+
[cols="35,65"]
|===


| Si vous voulez que l'utilisateur Windows par défaut pour les utilisateurs UNIX inconnus... | Entrez la commande... 


 a| 
Activé
 a| 
`vserver nfs modify -vserver vserver_name -map-unknown-uid-to-default-windows-user enabled`



 a| 
Désactivé
 a| 
`vserver nfs modify -vserver vserver_name -map-unknown-uid-to-default-windows-user disabled`

|===
. Retour au niveau de privilège admin :
+
`set -privilege admin`


