---
permalink: nfs-admin/break-locks-task.html 
sidebar: sidebar 
keywords: breaking, locks 
summary: 'Lorsque des verrous de fichier empêchent l"accès client aux fichiers, vous pouvez afficher des informations sur les verrous actuellement mis en attente, puis interrompre des verrous spécifiques. Les applications de débogage sont des exemples de scénarios dans lesquels vous devrez peut-être interrompre les verrous.' 
---
= Serrures de sécurité
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque des verrous de fichier empêchent l'accès client aux fichiers, vous pouvez afficher des informations sur les verrous actuellement mis en attente, puis interrompre des verrous spécifiques. Les applications de débogage sont des exemples de scénarios dans lesquels vous devrez peut-être interrompre les verrous.

Le `vserver locks break` la commande n'est disponible que au niveau de privilège avancé et supérieur. La page man de la commande contient des informations détaillées.

.Étapes
. Pour trouver les informations dont vous avez besoin pour interrompre un verrouillage, utilisez le `vserver locks show` commande.
+
La page man de la commande contient des informations détaillées.

. Définissez le niveau de privilège sur avancé :
+
`set -privilege advanced`

. Effectuez l'une des opérations suivantes :
+
[cols="35,65"]
|===


| Si vous voulez rompre un verrou en spécifiant... | Entrez la commande... 


 a| 
Le nom du SVM, le nom du volume, le nom de la LIF et le chemin de fichier
 a| 
`vserver locks break -vserver vserver_name -volume volume_name -path path -lif lif`



 a| 
L'ID de verrouillage
 a| 
`vserver locks break -lockid UUID`

|===
. Retour au niveau de privilège admin :
+
`set -privilege admin`


