---
permalink: nfs-admin/commands-manage-name-service-switch-entries-reference.html 
sidebar: sidebar 
keywords: command, manage, name, service, switch, entry 
summary: Vous pouvez gérer les entrées de commutateur de service de noms en les créant, en les affichant, en les modifiant et en les supprimant. 
---
= Commandes de gestion des entrées de commutateur de service de noms dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez gérer les entrées de commutateur de service de noms en les créant, en les affichant, en les modifiant et en les supprimant.

[cols="35,65"]
|===


| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Créer une entrée de commutateur de service de nom
 a| 
`vserver services name-service ns-switch create`



 a| 
Afficher les entrées du commutateur d'entretien du nom
 a| 
`vserver services name-service ns-switch show`



 a| 
Modifier une entrée de commutateur de service de nom
 a| 
`vserver services name-service ns-switch modify`



 a| 
Supprimer une entrée de commutateur de service de nom
 a| 
`vserver services name-service ns-switch delete`

|===
Pour en savoir plus, `vserver services name-service ns-switch` consultez le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+services+name-service+ns-switch["Référence de commande ONTAP"^].

.Informations associées
https://www.netapp.com/pdf.html?item=/media/16328-tr-4668pdf.pdf["Rapport technique de NetApp 4668 : name Services Best Practices Guide (Guide des meilleures pratiques des services de noms)"^]
