---
permalink: nfs-admin/commands-manage-export-rules-reference.html 
sidebar: sidebar 
keywords: command, manage, export, rule 
summary: 'Il existe des commandes ONTAP spécifiques pour gérer les règles d"exportation.' 
---
= Commandes pour la gestion des règles d'export dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il existe des commandes ONTAP spécifiques pour gérer les règles d'exportation.

[cols="35,65"]
|===


| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Créer une règle d'exportation
 a| 
`vserver export-policy rule create`



 a| 
Affiche des informations sur les règles d'exportation
 a| 
`vserver export-policy rule show`



 a| 
Modifier une règle d'exportation
 a| 
`vserver export-policy rule modify`



 a| 
Supprimer une règle d'exportation
 a| 
`vserver export-policy rule delete`

|===
[NOTE]
====
Si vous avez configuré plusieurs règles d'exportation identiques correspondant à différents clients, veillez à les garder synchronisées lors de la gestion des règles d'exportation.

====
Pour en savoir plus, `vserver export-policy` consultez le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+export-policy["Référence de commande ONTAP"^].
