---
permalink: nfs-admin/commands-manage-nis-domain-config-reference.html 
sidebar: sidebar 
keywords: command, manage, nis, domain, configuration 
summary: Il existe des commandes ONTAP spécifiques pour gérer les configurations de domaine NIS. 
---
= Commandes pour la gestion des configurations de domaine NIS dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il existe des commandes ONTAP spécifiques pour gérer les configurations de domaine NIS.

[cols="35,65"]
|===


| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Créez une configuration de domaine NIS
 a| 
`vserver services name-service nis-domain create`



 a| 
Affiche les configurations de domaine NIS
 a| 
`vserver services name-service nis-domain show`



 a| 
Affiche l'état de liaison d'une configuration de domaine NIS
 a| 
`vserver services name-service nis-domain show-bound`



 a| 
Affiche les statistiques NIS
 a| 
`vserver services name-service nis-domain show-statistics` Disponible au niveau de privilège avancé et au niveau supérieur.



 a| 
Effacer les statistiques NIS
 a| 
`vserver services name-service nis-domain clear-statistics` Disponible au niveau de privilège avancé et au niveau supérieur.



 a| 
Modifier une configuration de domaine NIS
 a| 
`vserver services name-service nis-domain modify`



 a| 
Supprimer une configuration de domaine NIS
 a| 
`vserver services name-service nis-domain delete`



 a| 
Activer la mise en cache pour les recherches netgroup-par-hôte
 a| 
`vserver services name-service nis-domain netgroup-database config modify` Disponible au niveau de privilège avancé et au niveau supérieur.

|===
Pour en savoir plus, `vserver services name-service nis-domain` consultez le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+services+name-service+nis-domain["Référence de commande ONTAP"^].
