---
permalink: nfs-admin/commands-manage-ldap-client-config-reference.html 
sidebar: sidebar 
keywords: command, manage, ldap, client, configuration 
summary: Il existe des commandes ONTAP spécifiques pour gérer les configurations du client LDAP. 
---
= Commandes permettant de gérer les configurations du client LDAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il existe des commandes ONTAP spécifiques pour gérer les configurations du client LDAP.

[NOTE]
====
Les administrateurs du SVM ne peuvent ni modifier ni supprimer les configurations du client LDAP créées par les administrateurs du cluster.

====
[cols="35,65"]
|===


| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Créez une configuration client LDAP
 a| 
`vserver services name-service ldap client create`



 a| 
Affiche les configurations du client LDAP
 a| 
`vserver services name-service ldap client show`



 a| 
Modifier une configuration client LDAP
 a| 
`vserver services name-service ldap client modify`



 a| 
Modifiez le mot de passe DE LIAISON du client LDAP
 a| 
`vserver services name-service ldap client modify-bind-password`



 a| 
Supprimez une configuration client LDAP
 a| 
`vserver services name-service ldap client delete`

|===
Consultez la page man pour chaque commande pour plus d'informations.
