---
permalink: nfs-admin/commands-manage-local-unix-groups-reference.html 
sidebar: sidebar 
keywords: command, manage, local, unix, group 
summary: Il existe des commandes ONTAP spécifiques pour gérer les groupes UNIX locaux. 
---
= Commandes permettant de gérer les groupes UNIX locaux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il existe des commandes ONTAP spécifiques pour gérer les groupes UNIX locaux.

[cols="35,65"]
|===


| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Créer un groupe UNIX local
 a| 
`vserver services name-service unix-group create`



 a| 
Ajouter un utilisateur à un groupe UNIX local
 a| 
`vserver services name-service unix-group adduser`



 a| 
Chargement des groupes UNIX locaux à partir d'un URI
 a| 
`vserver services name-service unix-group load-from-uri`



 a| 
Afficher les groupes UNIX locaux
 a| 
`vserver services name-service unix-group show`



 a| 
Modifier un groupe UNIX local
 a| 
`vserver services name-service unix-group modify`



 a| 
Supprimer un utilisateur d'un groupe UNIX local
 a| 
`vserver services name-service unix-group deluser`



 a| 
Supprimer un groupe UNIX local
 a| 
`vserver services name-service unix-group delete`

|===
Consultez la page man pour chaque commande pour plus d'informations.
