---
permalink: nfs-admin/commands-manage-name-mappings-reference.html 
sidebar: sidebar 
keywords: command, mapping, name 
summary: Il existe des commandes ONTAP spécifiques permettant de gérer les mappages de noms. 
---
= Commandes permettant de gérer les mappages de noms
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il existe des commandes ONTAP spécifiques permettant de gérer les mappages de noms.

[cols="35,65"]
|===


| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Créer un mappage de nom
 a| 
`vserver name-mapping create`



 a| 
Insérez un mappage de nom à une position spécifique
 a| 
`vserver name-mapping insert`



 a| 
Afficher les mappages de noms
 a| 
`vserver name-mapping show`



 a| 
Échange de la position de deux mappages de noms REMARQUE : un échange n'est pas autorisé lorsque le mappage-noms est configuré avec une entrée de qualificatif-ip.
 a| 
`vserver name-mapping swap`



 a| 
Modifier un mappage de noms
 a| 
`vserver name-mapping modify`



 a| 
Supprime un mappage de noms
 a| 
`vserver name-mapping delete`



 a| 
Valider le mappage de nom correct
 a| 
`vserver security file-directory show-effective-permissions -vserver vs1 -win-user-name user1 -path / -share-name sh1`

|===
Consultez la page man pour chaque commande pour plus d'informations.
