---
permalink: nfs-admin/configure-time-to-live-cached-user-credentials-task.html 
sidebar: sidebar 
keywords: configure, time, live, cache, nfs, user, credential 
summary: 'Vous pouvez configurer la durée pendant laquelle ONTAP stocke les identifiants des utilisateurs NFS dans son cache interne (TTL ou délai avant activation) en modifiant le serveur NFS de la machine virtuelle de stockage (SVM). Vous pourrez ainsi remédier à certains problèmes liés à une charge élevée sur les serveurs de noms ou à des modifications d"identifiants qui affectent l"accès des utilisateurs NFS.' 
---
= Configurer le délai de mise en service des informations d'identification utilisateur NFS mises en cache dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer la durée pendant laquelle ONTAP stocke les identifiants des utilisateurs NFS dans son cache interne (TTL ou délai avant activation) en modifiant le serveur NFS de la machine virtuelle de stockage (SVM). Vous pourrez ainsi remédier à certains problèmes liés à une charge élevée sur les serveurs de noms ou à des modifications d'identifiants qui affectent l'accès des utilisateurs NFS.

.Description de la tâche
Ces paramètres sont disponibles au niveau de privilège avancé.

.Étapes
. Définissez le niveau de privilège sur avancé :
+
`set -privilege advanced`

. Effectuez l'action souhaitée :
+
[cols="35,65"]
|===


| Si vous souhaitez modifier le TTL pour le cache... | Utilisez la commande... 


 a| 
Références positives
 a| 
`vserver nfs modify -vserver vserver_name -cached-cred-positive-ttl time_to_live`

Le TTL est mesuré en millisecondes. À partir de ONTAP 9.10.1 et versions ultérieures, la valeur par défaut est 1 heure (3,600,000 millisecondes). Dans ONTAP 9.9.1 et les versions antérieures, la valeur par défaut est de 24 heures (86,400,000 millisecondes). La plage autorisée pour cette valeur est de 1 minute (60000 millisecondes) à 7 jours (604,800,000 millisecondes).



 a| 
Références négatives
 a| 
`vserver nfs modify -vserver vserver_name -cached-cred-negative-ttl time_to_live`

Le TTL est mesuré en millisecondes. La valeur par défaut est 2 heures (7,200,000 millisecondes). La plage autorisée pour cette valeur est de 1 minute (60000 millisecondes) à 7 jours (604,800,000 millisecondes).

|===
. Retour au niveau de privilège admin :
+
`set -privilege admin`


