---
permalink: nfs-admin/control-root-user-access-ntfs-security-data-task.html 
sidebar: sidebar 
keywords: control, root, user, access, ntfs, security, style, data 
summary: 'Vous pouvez configurer ONTAP de manière à permettre aux clients NFS d"accéder aux données de type sécurité NTFS et aux clients NTFS pour accéder aux données de type sécurité NFS. Lorsque vous utilisez le style de sécurité NTFS dans un magasin de données NFS, vous devez décider comment traiter l"accès par l"utilisateur root et configurer la machine virtuelle de stockage (SVM) en conséquence.' 
---
= Contrôler l'accès utilisateur root aux données de style de sécurité NTFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer ONTAP de manière à permettre aux clients NFS d'accéder aux données de type sécurité NTFS et aux clients NTFS pour accéder aux données de type sécurité NFS. Lorsque vous utilisez le style de sécurité NTFS dans un magasin de données NFS, vous devez décider comment traiter l'accès par l'utilisateur root et configurer la machine virtuelle de stockage (SVM) en conséquence.

.Description de la tâche
Lorsqu'un utilisateur root accède aux données de style de sécurité NTFS, vous disposez de deux options :

* Mappez l'utilisateur root à un utilisateur Windows comme tout autre utilisateur NFS et gérez l'accès en fonction des listes de contrôle d'accès NTFS.
* Ignorez les listes de contrôle d'accès NTFS et offrez un accès complet à la racine.


.Étapes
. Définissez le niveau de privilège sur avancé :
+
`set -privilege advanced`

. Effectuez l'action souhaitée :
+
[cols="35,65"]
|===


| Si vous voulez que l'utilisateur root... | Entrez la commande... 


 a| 
Être mappé à un utilisateur Windows
 a| 
`vserver nfs modify -vserver vserver_name -ignore-nt-acl-for-root disabled`



 a| 
Ignorer la vérification de la liste de contrôle d’accès NT
 a| 
`vserver nfs modify -vserver vserver_name -ignore-nt-acl-for-root enabled`

|===
+
Par défaut, ce paramètre est désactivé.

+
Si ce paramètre est activé mais qu'il n'y a pas de mappage de noms pour l'utilisateur root, ONTAP utilise les informations d'identification d'administrateur SMB par défaut pour l'audit.

. Retour au niveau de privilège admin :
+
`set -privilege admin`


