---
permalink: nfs-admin/display-nis-statistics-task.html 
sidebar: sidebar 
keywords: display, nis, statistics 
summary: 'Pour surveiller les performances et diagnostiquer les problèmes, vous pouvez afficher les statistiques NIS des machines virtuelles de stockage (SVM) sur le système de stockage.' 
---
= Afficher les statistiques NIS pour les SVM ONTAP NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour surveiller les performances et diagnostiquer les problèmes, vous pouvez afficher les statistiques NIS des machines virtuelles de stockage (SVM) sur le système de stockage.

.Étapes
. Utilisez le `statistics catalog object show` Pour identifier les objets NIS à partir desquels vous pouvez afficher des données.
+
`statistics catalog object show -object external_service_op*`

. Utilisez le `statistics start` et `statistics stop` commandes permettant de collecter un échantillon de données à partir d'un ou de plusieurs objets.
. Utilisez le `statistics show` commande pour afficher les exemples de données.




== Surveillance des statistiques NIS

Les exemples suivants affichent des données de performances pour les requêtes NIS. Les commandes suivantes permettent de lancer la collecte de données pour un nouvel échantillon :

[listing]
----
vs1::*> statistics start -object external_service_op -sample-id nis_sample1
vs1::*> statistics start -object external_service_op_error -sample-id nis_sample2
----
La commande suivante affiche les données de l'échantillon en spécifiant des compteurs indiquant le nombre de requêtes NIS envoyées par rapport au nombre de requêtes NIS reçues, en échec ou en expiration :

[listing]
----
vs1::*> statistics show -sample-id nis_sample1 -counter instance|num_requests_sent|num_responses_received|num_successful_responses|num_timeouts|num_request_failures|num_not_found_responses

Object: external_service_op
Instance: vs1:NIS:Query:10.227.13.221
Start-time: 3/8/2016 11:27:39
End-time: 3/8/2016 11:27:56
Elapsed-time: 17s
Scope: vs1

    Counter                                                     Value
    -------------------------------- --------------------------------
    num_not_found_responses                                         0
    num_request_failures                                            1
    num_requests_sent                                               2
    num_responses_received                                          1
    num_successful_responses                                        1
    num_timeouts                                                    0
6 entries were displayed.
----
La commande suivante affiche les données de l'échantillon en spécifiant des compteurs indiquant le nombre de fois où une erreur spécifique a été reçue pour une requête NIS sur le serveur particulier :

[listing]
----
vs1::*> statistics show -sample-id nis_sample2 -counter server_ip_address|error_string|count

Object: external_service_op_error
Instance: vs1:NIS:Query:YP_NOTFOUND:10.227.13.221
Start-time: 3/8/2016 11:33:05
End-time: 3/8/2016 11:33:10
Elapsed-time: 5s
Scope: vs1

    Counter                                                     Value
    -------------------------------- --------------------------------
    count                                                           1
    error_string                                          YP_NOTFOUND
    server_ip_address                                   10.227.13.221
3 entries were displayed.
----
.Informations associées
link:../performance-config/index.html["Configuration du contrôle des performances"]
