---
permalink: nfs-admin/display-export-policy-netgroup-queue-cache-task.html 
sidebar: sidebar 
keywords: display, export, policy, netgroup, queue, cache 
summary: 'ONTAP utilise la file d"attente du groupe réseau lors de l"importation et de la résolution des groupes réseau et utilise le cache du groupe réseau pour stocker les informations obtenues. Lors du dépannage des problèmes liés à l"export policy netgroup, vous pouvez utiliser les commandes vserver export-policy netgroup queue show et vserver export-policy netgroup cache show pour afficher le statut de la file d"attente netgroup et le contenu du cache netgroup.' 
---
= Affiche la file d'attente et le cache de groupe réseau de la politique d'export
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP utilise la file d'attente du groupe réseau lors de l'importation et de la résolution des groupes réseau et utilise le cache du groupe réseau pour stocker les informations obtenues. Lors de la résolution des problèmes liés à la stratégie d'exportation netgroup, vous pouvez utiliser le `vserver export-policy netgroup queue show` et `vserver export-policy netgroup cache show` commandes permettant d'afficher l'état de la file d'attente netgroup et le contenu du cache netgroup.

.Étape
. Effectuez l'une des opérations suivantes :
+
[cols="20,80"]
|===


| Pour afficher le groupe réseau de la export policy... | Entrez la commande... 


 a| 
File d'attente
 a| 
`vserver export-policy netgroup queue show`



 a| 
Cache
 a| 
`vserver export-policy netgroup cache show -vserver vserver_name`

|===
+
Consultez la page man pour chaque commande pour plus d'informations.


