---
permalink: nfs-admin/display-ldap-statistics-task.html 
sidebar: sidebar 
keywords: display, ldap, statistics 
summary: 'Depuis ONTAP 9.2, vous pouvez afficher les statistiques LDAP des serveurs virtuels de stockage (SVM) sur un système de stockage pour surveiller les performances et diagnostiquer les problèmes.' 
---
= Affiche les statistiques LDAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis ONTAP 9.2, vous pouvez afficher les statistiques LDAP des serveurs virtuels de stockage (SVM) sur un système de stockage pour surveiller les performances et diagnostiquer les problèmes.

.Ce dont vous avez besoin, 8217;ll
* Vous devez avoir configuré un client LDAP sur la SVM.
* Vous devez avoir identifié des objets LDAP à partir desquels vous pouvez afficher des données.


.Étape
. Afficher les données de performance des objets compteur :
+
`statistics show`



L'exemple suivant montre les données de performances de l'objet `secd_external_service_op`:

[listing]
----
cluster::*> statistics show -vserver vserverName -object secd_external_service_op -instance “vserverName:LDAP (NIS & Name Mapping):GetUserInfoFromName:1.1.1.1”

Object: secd_external_service_op
Instance: vserverName:LDAP (NIS & Name Mapping):GetUserInfoFromName:1.1.1.1
Start-time: 4/13/2016 22:15:38
End-time: 4/13/2016 22:15:38
Scope: vserverName
Counter                            Value
-------------------------------- --------------------------------
instance_name                      vserverName:LDAP (NIS & Name
                                   Mapping):GetUserInfoFromName:
                                   1.1.1.1
last_modified_time                 1460610787
node_name                          nodeName
num_not_found_responses            1
num_request_failures               1
num_requests_sent                  1
num_responses_received             1
num_successful_responses           0
num_timeouts                       0
operation                          GetUserInfoFromName
process_name                       secd
request_latency                    52131us
----