---
permalink: nfs-admin/enable-disable-rquota-support-task.html 
sidebar: sidebar 
keywords: enable, disable, rquota, support 
summary: 'ONTAP supporte le protocole de quota distant version 1 (rquota v1). Le protocole rquota permet aux clients NFS d"obtenir des informations de quotas pour les utilisateurs à partir d"une machine distante. Vous pouvez activer rquota sur des SVM (Storage Virtual machines) à l"aide de la commande vserver nfs modify.' 
---
= Activer ou désactiver la prise en charge de rquota
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP supporte le protocole de quota distant version 1 (rquota v1). Le protocole rquota permet aux clients NFS d'obtenir des informations de quotas pour les utilisateurs à partir d'une machine distante. Vous pouvez activer rquota sur des machines virtuelles de stockage (SVM) à l'aide du `vserver nfs modify` commande.

.Description de la tâche
Par défaut, rquota est désactivé.

.Étape
. Effectuez l'une des opérations suivantes :
+
[cols="2*"]
|===
| Les fonctions que vous recherchez... | Saisissez la commande suivante... 


 a| 
Activer la prise en charge de rquota pour les SVM
 a| 
`vserver nfs modify -vserver vserver_name -rquota enable`



 a| 
Désactiver la prise en charge de rquota pour les SVM
 a| 
`vserver nfs modify -vserver vserver_name -rquota disable`

|===
+
Pour plus d'informations sur les quotas, reportez-vous à la section link:../volumes/index.html["Gestion du stockage logique"].


