---
permalink: nfs-admin/enable-access-windows-nfs-clients-task.html 
sidebar: sidebar 
keywords: enable, access, windows, nfs, clients 
summary: 'ONTAP prend en charge l"accès aux fichiers à partir de clients Windows NFSv3. Cela signifie que les clients exécutant des systèmes d"exploitation Windows avec prise en charge de NFSv3 peuvent accéder aux fichiers lors des exports NFSv3 sur le cluster. Pour utiliser correctement cette fonctionnalité, vous devez configurer correctement le serveur virtuel de stockage (SVM) et connaître certaines exigences et limites.' 
---
= Activez l'accès aux clients Windows NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP prend en charge l'accès aux fichiers à partir de clients Windows NFSv3. Cela signifie que les clients exécutant des systèmes d'exploitation Windows avec prise en charge de NFSv3 peuvent accéder aux fichiers lors des exports NFSv3 sur le cluster. Pour utiliser correctement cette fonctionnalité, vous devez configurer correctement le serveur virtuel de stockage (SVM) et connaître certaines exigences et limites.

.Description de la tâche
Par défaut, la prise en charge du client Windows NFSv3 est désactivée.

.Avant de commencer
NFSv3 doit être activé sur le SVM.

.Étapes
. Activer la prise en charge des clients Windows NFSv3 :
+
`vserver nfs modify -vserver _svm_name_ -v3-ms-dos-client enabled`

. Sur tous les SVM qui prennent en charge les clients Windows NFSv3, désactivez le `-enable-ejukebox` et `-v3-connection-drop` paramètres :
+
`vserver nfs modify -vserver vserver_name -enable-ejukebox false -v3-connection-drop disabled`

+
Les clients Windows NFSv3 peuvent désormais monter des exportations sur le système de stockage.

. Assurez-vous que chaque client Windows NFSv3 utilise des montages durs en spécifiant le `-o mtype=hard` option.
+
Ceci est nécessaire pour garantir la fiabilité des supports.

+
`mount -o mtype=hard \\10.53.33.10\vol\vol1 z:\`


