---
permalink: nfs-admin/enable-disable-nfsv4-read-file-delegations-task.html 
sidebar: sidebar 
keywords: enable, disable, nfsv4, read, file, delegation 
summary: 'Pour activer ou désactiver les délégations de fichiers en lecture NFSv4, vous pouvez modifier l"option -v4.0-read-délégation ou -v4.1-read-délégation. En activant les délégations de fichiers de lecture, vous pouvez éliminer une grande partie de la surcharge de messages associée à l"ouverture et à la fermeture des fichiers.' 
---
= Activer ou désactiver les délégations de fichiers de lecture NFSv4 pour les SVM ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour activer ou désactiver les délégations de fichiers en lecture NFSv4, vous pouvez modifier ``-v4.0-read-delegation``ou option. En activant les délégations de fichiers de lecture, vous pouvez éliminer une grande partie de la surcharge de messages associée à l'ouverture et à la fermeture des fichiers.

.Description de la tâche
Par défaut, les délégations des fichiers lus sont désactivées.

L'inconvénient de l'activation des délégations de fichiers en lecture est que le serveur et ses clients doivent restaurer des délégations après le redémarrage ou le redémarrage du serveur, qu'un client redémarre ou qu'une partition réseau se produit.

.Étape
. Effectuez l'une des opérations suivantes :
+
[cols="35,65"]
|===


| Les fonctions que vous recherchez... | Alors... 


 a| 
Activer les délégations des fichiers lus NFSv4
 a| 
Saisissez la commande suivante :

`vserver nfs modify -vserver vserver_name -v4.0-read-delegation enabled`



 a| 
Activer les délégations des fichiers de lecture NFSv4.1
 a| 
Saisissez la commande suivante :

+
`vserver nfs modify -vserver vserver_name -v4.1-read-delegation enabled`



 a| 
Désactiver les délégations des fichiers de lecture NFSv4
 a| 
Saisissez la commande suivante :

`vserver nfs modify -vserver vserver_name -v4.0-read-delegation disabled`



 a| 
Désactiver les délégations de fichiers de lecture NFSv4.1
 a| 
Saisissez la commande suivante :

`vserver nfs modify -vserver vserver_name -v4.1-read-delegation disabled`

|===


.Résultat
Les options de délégation de fichiers prennent effet dès qu'elles sont modifiées. Il n'est pas nécessaire de redémarrer ou de redémarrer NFS.
