---
permalink: nfs-admin/enable-disable-modification-nfsv4-acls-task.html 
sidebar: sidebar 
keywords: enable, disable, modification, nfsv4, acl 
summary: Lorsque ONTAP reçoit une commande chmod pour un fichier ou un répertoire avec une liste de contrôle d’accès, la liste de contrôle d’accès est par défaut conservée et modifiée pour refléter le changement de bit de mode. Vous pouvez désactiver le paramètre -v4-acl-preserve pour modifier le comportement si vous souhaitez que la liste de contrôle d’accès soit supprimée. 
---
= Activer ou désactiver la modification des listes de contrôle d'accès NFSv4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque ONTAP reçoit un `chmod` Commande pour un fichier ou un répertoire avec une liste de contrôle d’accès, la liste de contrôle d’accès est par défaut conservée et modifiée pour refléter le changement de bit de mode. Vous pouvez désactiver le `-v4-acl-preserve` Paramètre pour modifier le comportement si vous souhaitez que la liste de contrôle d’accès soit supprimée.

Lors de l'utilisation d'un style de sécurité unifié, ce paramètre indique également si les autorisations de fichier NTFS sont conservées ou supprimées lorsqu'un client envoie une commande chmod, chgroup ou chown pour un fichier ou un répertoire.

La valeur par défaut de ce paramètre est activée.

.Étapes
. Définissez le niveau de privilège sur avancé :
+
`set -privilege advanced`

. Effectuez l'une des opérations suivantes :
+
[cols="35,65"]
|===


| Les fonctions que vous recherchez... | Saisissez la commande suivante... 


 a| 
Activer la conservation et la modification des listes de contrôle d'accès NFSv4 existantes (par défaut)
 a| 
`vserver nfs modify -vserver vserver_name -v4-acl-preserve enabled`



 a| 
Désactivez la conservation et déposez les ACL NFSv4 lors du changement de bits de mode
 a| 
`vserver nfs modify -vserver vserver_name -v4-acl-preserve disabled`

|===
. Retour au niveau de privilège admin :
+
`set -privilege admin`


