---
permalink: nfs-admin/enable-or-disable-nfs-over-tls-cli.html 
sidebar: sidebar 
keywords: enable, tls, data, lif 
summary: 'Vous pouvez utiliser l"interface de ligne de commandes de ONTAP pour activer TLS sur une LIF de données pour les clients NFS. Cela permet au SVM d"utiliser les services de sécurité TLS pour NFS.' 
---
= Activez ou désactivez TLS pour les clients NFS dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez améliorer la sécurité des connexions NFS en configurant NFS sur TLS de manière à chiffrer toutes les données envoyées sur le réseau entre le client NFS et ONTAP. Cela augmente la sécurité des connexions NFS. Vous pouvez le configurer sur une machine virtuelle de stockage existante activée pour NFS.


NOTE: NFS over TLS est disponible dans ONTAP 9.15.1 en tant que préversion publique. À titre de préversion, NFS over TLS n'est pas pris en charge pour les workloads de production dans ONTAP 9.15.1.



== Activez TLS

Vous pouvez activer le chiffrement TLS pour les clients NFS afin d'augmenter la sécurité des données en transit.

.Avant de commencer
* Reportez-vous à la link:tls-nfs-strong-security-concept.html["de formation"] Pour NFS sur TLS avant de commencer.
* Reportez-vous aux pages de manuel ONTAP pour plus d'informations sur la commande dans cette procédure.
* Pour en savoir plus sur la commande link:https://docs.NetApp.com/US-en/ONTAP-cli/vserver-nfs-tls-interface-enable.html[`vserver nfs tls interface show`^], consultez la référence de commande ONTAP.


.Étapes
. Il convient de choisir une machine virtuelle de stockage et une interface logique (LIF) sur laquelle activer TLS.
. Activez TLS pour les connexions NFS sur cette machine virtuelle et cette interface de stockage.
+
[source, console]
----
vserver nfs tls interface enable -vserver <STORAGE_VM> -lif <LIF_NAME> -certificate-name <CERTIFICATE_NAME>
----
. Utilisez le `vserver nfs tls interface show` pour afficher les résultats :
+
[source, console]
----
vserver nfs tls interface show
----


.Exemple
La commande suivante active NFS sur TLS sur le `data1` LIF du `vs1` VM de stockage :

[source, console]
----
vserver nfs tls interface enable -vserver vs1 -lif data1 -certificate-name cert_vs1
----
[source, console]
----
vserver nfs tls interface show
----
....
               Logical
Vserver        Interface     Address         TLS Status TLS Certificate Name
-------------- ------------- --------------- ---------- -----------------------
vs1            data1         10.0.1.1        enabled    cert_vs1
vs2            data2         10.0.1.2        disabled   -
2 entries were displayed.
....


== Désactiver TLS

Vous pouvez désactiver TLS pour les clients NFS si vous n'avez plus besoin de la sécurité améliorée pour les données en transit.

.Avant de commencer
Pour en savoir plus sur la commande link:https://docs.NetApp.com/US-en/ONTAP-cli/vserver-nfs-tls-interface-disable.html[`vserver nfs tls interface disable`^], consultez la référence de commande ONTAP.

.Étapes
. Choisissez une VM de stockage et une interface logique (LIF) sur laquelle désactiver TLS.
. Désactivez TLS pour les connexions NFS sur cette VM et cette interface de stockage.
+
[source, console]
----
vserver nfs tls interface disable -vserver <STORAGE_VM> -lif <LIF_NAME>
----
. Utilisez le `vserver nfs tls interface show` pour afficher les résultats :
+
[source, console]
----
vserver nfs tls interface show
----


.Exemple
La commande suivante désactive NFS sur TLS sur le `data1` LIF du `vs1` VM de stockage :

[source, console]
----
vserver nfs tls interface disable -vserver vs1 -lif data1
----
[source, console]
----
vserver nfs tls interface show
----
....
               Logical
Vserver        Interface     Address         TLS Status TLS Certificate Name
-------------- ------------- --------------- ---------- -----------------------
vs1            data1         10.0.1.1        disabled   -
vs2            data2         10.0.1.2        disabled   -
2 entries were displayed.
....


== Modifier une configuration TLS

Vous pouvez modifier les paramètres d'une configuration NFS sur TLS existante. Par exemple, vous pouvez utiliser cette procédure pour mettre à jour le certificat TLS.

.Avant de commencer
Pour en savoir plus sur la commande link:https://docs.NetApp.com/US-en/ONTAP-cli/vserver-nfs-tls-interface-modify.html[`vserver nfs tls interface modify`^], consultez la référence de commande ONTAP.

.Étapes
. Choisir une VM de stockage et une interface logique (LIF) sur laquelle modifier la configuration TLS pour les clients NFS.
. Modifier la configuration. Si vous spécifiez un `status` de `enable`, vous devez également spécifier le `certificate-name` paramètre. Remplacez les valeurs entre parenthèses <> par les informations de votre environnement :
+
[source, console]
----
vserver nfs tls interface modify -vserver <STORAGE_VM> -lif <LIF_NAME> -status <STATUS> -certificate-name <CERTIFICATE_NAME>
----
. Utilisez le `vserver nfs tls interface show` pour afficher les résultats :
+
[source, console]
----
vserver nfs tls interface show
----


.Exemple
La commande suivante modifie la configuration NFS sur TLS sur le `data2` LIF du `vs2` VM de stockage :

[source, console]
----
vserver nfs tls interface modify -vserver vs2 -lif data2 -status enable -certificate-name new_cert
----
[source, console]
----
vserver nfs tls interface show
----
....
               Logical
Vserver        Interface     Address         TLS Status TLS Certificate Name
-------------- ------------- --------------- ---------- -----------------------
vs1            data1         10.0.1.1        disabled   -
vs2            data2         10.0.1.2        enabled    new_cert
2 entries were displayed.
....
.Informations associées
link:../task_nas_enable_linux_nfs.html["Activez le stockage NAS pour les serveurs Linux à l'aide de NFS"].
