---
permalink: nfs-admin/enable-nfsv42-security-labels-task.html 
sidebar: sidebar 
keywords: enable, nfs, v4.2, security, label 
summary: Depuis ONTAP 9.9.1, les étiquettes de sécurité NFS peuvent être activées. Ils sont désactivés par défaut. 
---
= Activez les étiquettes de sécurité NFS v4.2
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis ONTAP 9.9.1, les étiquettes de sécurité NFS peuvent être activées. Ils sont désactivés par défaut.

.Description de la tâche
Avec les étiquettes de sécurité NFS v4.2, les serveurs NFS ONTAP prennent en charge le contrôle d'accès obligatoire (MAC), en stockant et en récupérant les attributs sec_label envoyés par les clients.

Pour plus d'informations, voir https://tools.ietf.org/html/rfc7204["RFC7240"]

[NOTE]
====
Les étiquettes de sécurité NFS v4.2 ne sont actuellement pas prises en charge pour les opérations de dump NDMP. Si des étiquettes de sécurité sont présentes sur des fichiers ou des répertoires, le vidage échoue.

====
.Étapes
. Modifiez le paramètre de privilège sur avancé :
+
``set -privilege advanced``

. Activer les étiquettes de sécurité :
+
``vserver nfs modify -vserver svm_name -v4.2-seclabel enabled``


