---
permalink: nfs-admin/enable-disable-pnfs-task.html 
sidebar: sidebar 
keywords: enable, disable, pnfs 
summary: 'PNFS améliore les performances en permettant aux clients NFS d"effectuer des opérations de lecture/écriture sur les périphériques de stockage directement et en parallèle, en contournant le serveur NFS comme un goulot d"étranglement potentiel. Pour activer ou désactiver pNFS (Parallel NFS), vous pouvez modifier l"option -v4.1-pnfs.' 
---
= Activer ou désactiver pNFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
PNFS améliore les performances en permettant aux clients NFS d'effectuer des opérations de lecture/écriture sur les périphériques de stockage directement et en parallèle, en contournant le serveur NFS comme un goulot d'étranglement potentiel. Pour activer ou désactiver pNFS (Parallel NFS), vous pouvez modifier le `-v4.1-pnfs` option.

[cols="50,50"]
|===
| Si la version de ONTAP est... | La norme pNFS par défaut est... 


| 9.8 ou ultérieure | désactivé 


| 9.7 ou antérieure | activé 
|===
.Ce dont vous avez besoin
La prise en charge de NFSv4.1 est requise pour pouvoir utiliser pNFS.

Si vous souhaitez activer pNFS, vous devez d'abord désactiver les référencements NFS. Les deux ne peuvent pas être activées en même temps.

Si vous utilisez pNFS avec Kerberos sur des SVM, il faut activer Kerberos sur chaque LIF de la SVM.

.Étape
. Effectuez l'une des opérations suivantes :
+
[cols="2*"]
|===
| Les fonctions que vous recherchez... | Entrez la commande... 


 a| 
Activez pNFS
 a| 
`vserver nfs modify -vserver vserver_name -v4.1-pnfs enabled`



 a| 
Désactiver pNFS
 a| 
`vserver nfs modify -vserver vserver_name -v4.1-pnfs disabled`

|===


.Informations associées
* xref:../nfs-trunking/index.html[Présentation de l'agrégation NFS]

