---
permalink: nfs-admin/export-policies-client-access-volumes-concept.html 
sidebar: sidebar 
keywords: export, policies, control, client, access, volume, qtrees 
summary: 'Les export-policy contiennent une ou plusieurs règles d"exportation qui traitent chaque requête d"accès client. Le résultat du processus détermine si le client est refusé ou accordé et quel niveau d"accès. Un export policy avec règles d"export doit exister sur la machine virtuelle de stockage (SVM) afin que les clients puissent accéder aux données.' 
---
= Comment les politiques d'exportation contrôlent l'accès des clients aux volumes NFS ou qtrees ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les règles d'exportation contiennent une ou plusieurs _export rules_ qui traitent chaque demande d'accès client. Le résultat du processus détermine si le client est refusé ou accordé et quel niveau d'accès. Un export policy avec règles d'export doit exister sur la machine virtuelle de stockage (SVM) afin que les clients puissent accéder aux données.

Vous associez exactement une export policy à chaque volume ou qtree pour configurer l'accès client au volume ou qtree. Le SVM peut contenir plusieurs export policy. Vous pouvez ainsi effectuer les opérations suivantes pour les SVM avec plusieurs volumes ou qtrees :

* Assigner différentes export policy à chaque volume ou qtree du SVM pour le contrôle d'accès client individuel à chaque volume ou qtree du SVM.
* Assigner la même export policy à plusieurs volumes ou qtree du SVM pour un contrôle d'accès client identique sans avoir à créer une nouvelle export policy pour chaque volume ou qtree.


Si un client effectue une demande d'accès qui n'est pas autorisée par la stratégie d'exportation applicable, la requête échoue et un message d'autorisation est refusé. Si un client ne correspond à aucune règle de l'export policy, l'accès est refusé. Si une export policy est vide, alors tous les accès sont implicitement refusés.

Vous pouvez modifier une export-policy de manière dynamique sur un système exécutant ONTAP.
