---
permalink: nfs-admin/how-ontap-creates-file-directory-names-concept.html 
sidebar: sidebar 
keywords: ontap, create, file, directory, name 
summary: 'ONTAP crée et conserve deux noms pour les fichiers ou les répertoires de tout répertoire ayant accès à partir d"un client SMB : le nom long et le nom d"origine au format 8.3.' 
---
= Comment ONTAP crée des noms de fichiers et de répertoires
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP crée et conserve deux noms pour les fichiers ou les répertoires de tout répertoire ayant accès à partir d'un client SMB : le nom long et le nom d'origine au format 8.3.

Pour les noms de fichier ou de répertoire dépassant le nom de huit caractères ou la limite d'extension de trois caractères (pour les fichiers), ONTAP génère un nom de format 8.3 comme suit :

* Il tronque le nom de fichier ou de répertoire d'origine à six caractères, si le nom dépasse six caractères.
* Il ajoute un tilde (~) et un nombre, un à cinq, aux noms de fichier ou de répertoire qui ne sont plus uniques après être tronqués.
+
S'il manque des nombres parce qu'il y a plus de cinq noms similaires, il crée un nom unique qui n'a aucune relation avec le nom original.

* Dans le cas des fichiers, il tronque l'extension du nom de fichier à trois caractères.


Par exemple, si un client NFS crée un fichier nommé `specifications.html`, Le nom de fichier au format 8.3 créé par ONTAP est `specif~1.htm`. Si ce nom existe déjà, ONTAP utilise un numéro différent à la fin du nom du fichier. Par exemple, si un client NFS crée un autre fichier nommé `specifications_new.html`, le format 8.3 de `specifications_new.html` est `specif~2.htm`.
