---
permalink: nfs-admin/modify-nfsv3-nfsv4-tcp-maximum-transfer-size-task.html 
sidebar: sidebar 
keywords:  
summary: 'Vous pouvez modifier l"option -tcp-max-xfer-size pour configurer les tailles de transfert maximales pour toutes les connexions TCP en utilisant les protocoles NFSv3 et NFSv4.x.' 
---
= Modifier la taille maximale du transfert TCP NFSv3 et NFSv4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier le `-tcp-max-xfer-size` Option permettant de configurer les tailles de transfert maximales pour toutes les connexions TCP en utilisant les protocoles NFSv3 et NFSv4.x.

.Description de la tâche
Vous pouvez modifier ces options individuellement pour chaque serveur virtuel de stockage (SVM).

À partir de ONTAP 9, le `v3-tcp-max-read-size` et `v3-tcp-max-write-size` les options sont obsolètes. Vous devez utiliser le `-tcp-max-xfer-size` à la place.

.Étapes
. Définissez le niveau de privilège sur avancé :
+
`set -privilege advanced`

. Effectuez l'une des opérations suivantes :
+
[cols="2*"]
|===
| Les fonctions que vous recherchez... | Entrez la commande... 


 a| 
Modifier la taille maximale du transfert TCP NFSv3 ou NFSv4
 a| 
`vserver nfs modify -vserver vserver_name -tcp-max-xfer-size integer_max_xfer_size`

|===
+
[cols="3*"]
|===
| Option | Gamme | Valeur par défaut 


 a| 
`-tcp-max-xfer-size`
 a| 
8192 à 1048576 octets
 a| 
65536 octets

|===
+
[NOTE]
====
La taille de transfert maximale que vous saisissez doit être un multiple de 4 Ko (4096 octets). Les demandes qui ne sont pas correctement alignées ont un impact négatif sur les performances.

====
. Utilisez le `vserver nfs show -fields tcp-max-xfer-size` pour vérifier les modifications.
. Si des clients utilisent des montages statiques, démontez et remontez la nouvelle taille de paramètre pour prendre effet.


.Exemple
La commande suivante définit la taille maximale du transfert NFSv3 et NFSv4.x TCP à 1048576 octets sur le SVM nommé vs1 :

[listing]
----
vs1::> vserver nfs modify -vserver vs1 -tcp-max-xfer-size 1048576
----