---
permalink: nfs-admin/name-mapping-concept.html 
sidebar: sidebar 
keywords: mapping, work 
summary: 'Lorsque ONTAP doit mapper les informations d"identification d"un utilisateur, il recherche tout d"abord un mappage existant dans la base de données de mappage de noms locaux et le serveur LDAP. Qu"elle vérifie un ou les deux et dans quel ordre est déterminé par la configuration du service de nom du SVM.' 
---
= En savoir plus sur les mappages de noms pour les SVM NAS ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque ONTAP doit mapper les informations d'identification d'un utilisateur, il recherche tout d'abord un mappage existant dans la base de données de mappage de noms locaux et le serveur LDAP. Qu'elle vérifie un ou les deux et dans quel ordre est déterminé par la configuration du service de nom du SVM.

* Pour le mappage Windows à UNIX
+
Si aucun mappage n'est trouvé, ONTAP vérifie si le nom d'utilisateur Windows minuscule est un nom d'utilisateur valide dans le domaine UNIX. Si cela ne fonctionne pas, il utilise l'utilisateur UNIX par défaut à condition qu'il soit configuré. Si l'utilisateur UNIX par défaut n'est pas configuré et que ONTAP ne peut pas obtenir de mappage de cette façon, le mappage échoue et une erreur est renvoyée.

* Pour le mappage d'UNIX à Windows
+
Si aucun mappage n'est trouvé, ONTAP tente de trouver un compte Windows correspondant au nom UNIX dans le domaine SMB. Si cela ne fonctionne pas, il utilise l'utilisateur SMB par défaut, à condition qu'il soit configuré. Si l'utilisateur SMB par défaut n'est pas configuré et que ONTAP ne peut pas obtenir de mappage de cette façon, le mappage échoue et une erreur est renvoyée.



Par défaut, les comptes machine sont mappés à l'utilisateur UNIX par défaut spécifié. Si aucun utilisateur UNIX par défaut n'est spécifié, les mappages de compte machine échouent.

* À partir de ONTAP 9.5, vous pouvez mapper des comptes machine à des utilisateurs autres que l'utilisateur UNIX par défaut.
* Dans ONTAP 9.4 et versions antérieures, vous ne pouvez pas mapper les comptes machine à d'autres utilisateurs.
+
Même si des mappages de noms pour des comptes machine sont définis, les mappages sont ignorés.


