---
permalink: nfs-admin/nfs-credential-cache-concept.html 
sidebar: sidebar 
keywords: nfs, credential, cache 
summary: 'Lorsqu"un utilisateur NFS demande l"accès aux exports NFS sur le système de stockage, ONTAP doit récupérer les identifiants de l"utilisateur à partir de serveurs de noms externes ou de fichiers locaux afin de l"authentifier. ONTAP stocke ensuite ces informations d"identification dans un cache d"informations d"identification interne pour référence ultérieure. Il est donc essentiel de comprendre le fonctionnement des caches d"identifiants NFS pour gérer les problèmes de performance et d"accès qui peuvent survenir.' 
---
= Comment fonctionne le cache d'informations d'identification NFS ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsqu'un utilisateur NFS demande l'accès aux exports NFS sur le système de stockage, ONTAP doit récupérer les identifiants de l'utilisateur à partir de serveurs de noms externes ou de fichiers locaux afin de l'authentifier. ONTAP stocke ensuite ces informations d'identification dans un cache d'informations d'identification interne pour référence ultérieure. Il est donc essentiel de comprendre le fonctionnement des caches d'identifiants NFS pour gérer les problèmes de performance et d'accès qui peuvent survenir.

Sans le cache des informations d'identification, ONTAP devra interroger les services de noms chaque fois qu'un utilisateur NFS a demandé l'accès. Sur un système de stockage surchargé auquel de nombreux utilisateurs accèdent, cela peut rapidement entraîner des problèmes de performance graves, entraînant des retards non désirés ou même des dénis de l'accès client NFS.

Avec le cache des informations d'identification, ONTAP récupère les informations d'identification de l'utilisateur, puis les stocke pendant un délai prédéterminé pour un accès rapide et facile en cas d'envoi d'une autre demande par le client NFS. Cette méthode offre les avantages suivants :

* Il facilite la charge du système de stockage en gérant moins de requêtes vers des serveurs de noms externes (par exemple NIS ou LDAP).
* Il facilite la charge sur les serveurs de noms externes en leur envoyant moins de demandes.
* Il accélère l'accès des utilisateurs en éliminant le temps d'attente pour obtenir des informations d'identification de sources externes avant que l'utilisateur puisse être authentifié.


ONTAP stocke les informations d'identification positives et négatives dans le cache des informations d'identification. Des informations d'identification positives signifient que l'utilisateur a été authentifié et a accordé l'accès. Les identifiants négatifs signifient que l'utilisateur n'a pas été authentifié et a refusé l'accès.

Par défaut, ONTAP stocke des identifiants positifs pendant 24 heures. Ainsi, après l'authentification initiale d'un utilisateur, ONTAP utilise les identifiants mis en cache pour toutes les demandes d'accès de cet utilisateur pendant 24 heures. Si l'utilisateur demande l'accès après 24 heures, le cycle commence : ONTAP supprime les informations d'identification mises en cache et obtient à nouveau les informations d'identification à partir de la source de service de noms appropriée. Si les informations d'identification ont été modifiées sur le serveur de noms au cours des 24 dernières heures, ONTAP met en cache les informations d'identification mises à jour pour les 24 prochaines heures.

Par défaut, ONTAP stocke les informations d'identification négatives pendant deux heures. Ainsi, après avoir initialement refusé l'accès à un utilisateur, ONTAP continue à refuser toute demande d'accès à cet utilisateur pendant deux heures. Si l'utilisateur demande l'accès au bout de 2 heures, le cycle commence : ONTAP obtient à nouveau les informations d'identification à partir de la source de service de noms appropriée. Si les informations d'identification ont été modifiées sur le serveur de noms au cours des deux heures précédentes, ONTAP met en cache les informations d'identification mises à jour pour les deux heures suivantes.
