---
permalink: nfs-admin/nfsv3-nfsv4-performance-tcp-transfer-size-concept.html 
sidebar: sidebar 
keywords: nfsv3, nfsv4, performance, improvement, modify, tcp, transfer, size 
summary: Vous pouvez améliorer les performances des clients NFSv3 et NFSv4 qui se connectent aux systèmes de stockage sur un réseau à latence élevée en modifiant la taille maximale du transfert TCP. 
---
= Découvrez les améliorations des performances NFSv3 et NFSv4 et la taille de transfert TCP pour les SVM ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez améliorer les performances des clients NFSv3 et NFSv4 qui se connectent aux systèmes de stockage sur un réseau à latence élevée en modifiant la taille maximale du transfert TCP.

Lorsque les clients accèdent aux systèmes de stockage sur un réseau à latence élevée, tel qu'un réseau WAN (Wide Area Network) ou un réseau MAN (Metro Area Network) avec une latence supérieure à 10 millisecondes, vous pouvez améliorer les performances de connexion en modifiant la taille maximale du transfert TCP. Les clients qui accèdent aux systèmes de stockage dans un réseau à faible latence, tel qu'un réseau local (LAN), ne peuvent guère bénéficier de la modification de ces paramètres. Si l'amélioration du débit ne l'emporte pas sur l'impact sur la latence, vous ne devez pas utiliser ces paramètres.

Pour déterminer si votre environnement de stockage peut tirer parti de la modification de ces paramètres, vous devez d'abord effectuer une évaluation complète des performances d'un client NFS peu performant. Vérifiez si les faibles performances sont à cause d'une latence aller-retour excessive et d'une petite demande sur le client. Dans ces conditions, le client et le serveur ne peuvent pas utiliser pleinement la bande passante disponible parce qu'ils passent la majorité de leurs cycles de service en attente de petites demandes et réponses à transmettre par le biais de la connexion.

En augmentant la taille des requêtes NFSv3 et NFSv4, le client et le serveur peuvent utiliser la bande passante disponible plus efficacement pour déplacer plus de données par unité de temps, ce qui accroît l'efficacité globale de la connexion.

N'oubliez pas que la configuration entre le système de stockage et le client peut varier. Le système de stockage et le client prennent en charge une taille maximale de 1 Mo pour les opérations de transfert. Cependant, si vous configurez le système de stockage pour prendre en charge une taille de transfert maximale de 1 Mo mais que le client ne prend en charge que 64 Ko, la taille de transfert de montage est limitée à 64 Ko ou moins.

Avant de modifier ces paramètres, notez qu'il entraîne une consommation de mémoire supplémentaire sur le système de stockage pendant la durée nécessaire à l'assemblage et à la transmission d'une réponse importante. Plus les connexions à latence élevée sont nombreuses, plus la consommation de mémoire supplémentaire augmente. Les systèmes de stockage dont la capacité de mémoire est élevée ne subissent que très peu d'effet. Les systèmes de stockage dont la capacité de mémoire est faible peuvent constater une dégradation notable des performances.

La réussite de l'utilisation de ces paramètres repose sur la capacité à récupérer les données provenant de plusieurs nœuds d'un cluster. La latence inhérente au réseau du cluster peut augmenter la latence globale de la réponse. La latence globale a tendance à augmenter lors de l'utilisation de ces paramètres. Ainsi, les charges de travail sensibles à la latence peuvent avoir un impact négatif.
