---
permalink: nfs-admin/nfsv4-acls-concept.html 
sidebar: sidebar 
keywords: nfsv4, acls, work 
summary: 'Un client utilisant des listes de contrôle d"accès NFSv4 peut définir et afficher des listes de contrôle d"accès sur les fichiers et les répertoires du système. Lorsqu"un nouveau fichier ou sous-répertoire est créé dans un répertoire contenant une liste de contrôle d"accès, le nouveau fichier ou sous-répertoire hérite de toutes les entrées de contrôle d"accès (ACE) de la liste de contrôle d"accès qui ont été marquées avec les indicateurs d"héritage appropriés.' 
---
= Fonctionnement des listes de contrôle d'accès NFSv4
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un client utilisant des listes de contrôle d'accès NFSv4 peut définir et afficher des listes de contrôle d'accès sur les fichiers et les répertoires du système. Lorsqu'un nouveau fichier ou sous-répertoire est créé dans un répertoire contenant une liste de contrôle d'accès, le nouveau fichier ou sous-répertoire hérite de toutes les entrées de contrôle d'accès (ACE) de la liste de contrôle d'accès qui ont été marquées avec les indicateurs d'héritage appropriés.

Lorsqu'un fichier ou un répertoire est créé à la suite d'une requête NFSv4, l'ACL du fichier ou répertoire résultant dépend du fait que la demande de création de fichier inclut une ACL ou uniquement les autorisations d'accès aux fichiers UNIX standard, et si le répertoire parent possède une ACL :

* Si la requête inclut une liste de contrôle d’accès, cette liste de contrôle d’accès est utilisée.
* Si la demande comprend uniquement des autorisations d'accès aux fichiers UNIX standard mais que le répertoire parent possède une ACL, les ACE de l'ACL du répertoire parent sont hérités par le nouveau fichier ou répertoire tant que les ACE ont été balisés avec les indicateurs d'héritage appropriés.
+
[NOTE]
====
Une ACL parent est héritée même si `-v4.0-acl` est défini sur `off`.

====
* Si la requête inclut uniquement les autorisations d'accès aux fichiers UNIX standard et que le répertoire parent ne dispose pas d'ACL, le mode fichier client est utilisé pour définir les autorisations d'accès aux fichiers UNIX standard.
* Si la requête inclut uniquement les autorisations d'accès aux fichiers UNIX standard et que le répertoire parent dispose d'une ACL non héritable, le nouvel objet est créé uniquement avec des bits de mode.


[NOTE]
====
Si le `-chown-mode` le paramètre a été défini sur `restricted` à l'aide des commandes dans `vserver nfs` ou `vserver export-policy rule` Familles, la propriété des fichiers ne peut être modifiée que par le superutilisateur, même si les autorisations sur disque définies avec les ACL NFSv4 permettent à un utilisateur non-root de modifier la propriété des fichiers. Pour plus d'informations, consultez les pages de manuel correspondantes.

====