---
permalink: nfs-admin/supported-versions-clients-reference.html 
sidebar: sidebar 
keywords: support, nfs, version, client 
summary: 'Avant d"utiliser NFS dans votre réseau, vous devez connaître les versions NFS et les clients pris en charge par ONTAP.' 
---
= En savoir plus sur les versions et les clients ONTAP NFS pris en charge
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'utiliser NFS dans votre réseau, vous devez connaître les versions NFS et les clients pris en charge par ONTAP.

Ce tableau indique lorsque des versions majeures et mineures des protocoles NFS sont prises en charge par défaut dans ONTAP. Par défaut, la prise en charge n'indique pas qu'il s'agit de la version la plus ancienne de ONTAP prenant en charge ce protocole NFS.

[cols="3*"]
|===
| Version | Pris en charge | Introduction 


 a| 
NFSv3
 a| 
Oui.
 a| 
Toutes les versions de ONTAP



 a| 
NFSv4.0
 a| 
Oui.
 a| 
ONTAP 8



 a| 
NFSv4.1
 a| 
Oui.
 a| 
ONTAP 8,1



 a| 
NFSv4.2
 a| 
Oui.
 a| 
ONTAP 9.8



 a| 
PNFS
 a| 
Oui.
 a| 
ONTAP 8,1

|===
Pour obtenir les dernières informations sur les clients NFS pris en charge par ONTAP, consultez la matrice d'interopérabilité.

https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^]
