---
permalink: nfs-admin/support-vmware-vstorage-over-nfs-concept.html 
sidebar: sidebar 
keywords: support, vmware, vStorage, nfs 
summary: 'ONTAP prend en charge certaines fonctionnalités VMware vStorage APIs for Array Integration (VAAI) dans un environnement NFS.' 
---
= Prise en charge de VMware vStorage over NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP prend en charge certaines fonctionnalités VMware vStorage APIs for Array Integration (VAAI) dans un environnement NFS.



== Fonctionnalités prises en charge

Les fonctionnalités suivantes sont prises en charge :

* Copie auxiliaire
+
Permet à un hôte ESXi de copier des machines virtuelles ou des disques de machines virtuelles directement entre les emplacements de datastore source et de destination sans impliquer l'hôte. Cela permet d'économiser les cycles du processeur de l'hôte ESXi et la bande passante du réseau. Le déchargement des copies préserve l'efficacité de l'espace si le volume source est faible.

* Réservation d'espace
+
Garantit l'espace de stockage d'un fichier VMDK en réservant de l'espace pour celui-ci.





== Limites

VMware vStorage over NFS présente les limites suivantes :

* Les opérations de déchargement des copies peuvent échouer dans les scénarios suivants :
+
** Lors de l'exécution de waffer sur le volume source ou de destination, car il met temporairement le volume hors ligne
** Pendant le déplacement du volume source ou de destination
** Lors du déplacement de LIF source ou de destination
** Lors des opérations de basculement ou de rétablissement
** Lors des opérations de basculement ou de rétablissement


* La copie côté serveur peut échouer en raison des différences de format de descripteur de fichier dans le scénario suivant :
+
Tentative de copie des données à partir des SVM dont les qtrees n'ont pas encore été exportés vers des SVM, ou qui ont déjà été exportés. Pour contourner cette limitation, vous pouvez exporter au moins un qtree sur le SVM de destination.



https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/What_VAAI_offloaded_operations_are_supported_by_Data_ONTAP%3F["Quelles opérations VAAI Offloaded sont prises en charge par Data ONTAP ?"]
