---
sidebar: sidebar 
permalink: anti-ransomware/enable-task.html 
keywords: anti-ransomware overview, ransomware, security, introduce, autotonomous, protection, arp, detection, threat, attack, suspect, what ontap anti-ransomware detects, entropy, abnormal volume activity, extension conformity, how to recover data in after a ransomware attack, ransomware protection strategy 
summary: 'La protection autonome contre les ransomwares (ARP) peut être activée sur les volumes nouveaux ou existants. Vous activez tout d"abord ARP en mode d"apprentissage, dans lequel le système analyse la charge de travail pour caractériser le comportement normal, puis vous passez en mode actif, dans lequel une activité anormale est signalée pour votre évaluation.' 
---
= Activation de la protection autonome contre les ransomwares
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Depuis ONTAP 9.10.1, la protection autonome contre les ransomwares (ARP) peut être activée sur les volumes nouveaux ou existants. Vous commencez par activer ARP en mode d'apprentissage, dans lequel le système analyse la charge de travail pour caractériser le comportement normal. Vous pouvez activer ARP sur un volume existant ou créer un nouveau volume et activer ARP depuis le début.

.Description de la tâche
Vous devez toujours activer le protocole ARP initialement dans l'état DRY-RUN (mode d'apprentissage). En commençant par l'état actif, vous pouvez générer un nombre excessif de faux positifs.

Il est recommandé de laisser ARP fonctionner en mode d'apprentissage pendant au moins 30 jours. À partir de ONTAP 9.13.1, ARP détermine automatiquement la période d'apprentissage optimale et automatise le commutateur, qui peut se produire avant 30 jours.

Pour plus d'informations, voir link:index.html#learning-and-active-modes["Modes d'apprentissage et actifs"].


NOTE: Dans les volumes existants, les modes d'apprentissage et actif s'appliquent uniquement aux données récemment écrites, et non aux données déjà existantes du volume. Les données existantes ne sont pas analysées et analysées, car les caractéristiques du trafic de données normal antérieur sont présumées basées sur les nouvelles données une fois que le volume est activé pour ARP.

.Avant de commencer
* Une VM de stockage doit être activée pour NFS ou SMB (ou les deux).
* Le xref:index.html[licence correcte] Doit être installé pour votre version ONTAP.
* Vous devez avoir une charge de travail NAS avec des clients configurés.
* Le volume sur lequel vous souhaitez définir ARP doit être protégé doit avoir un actif link:../concepts/namespaces-junction-points-concept.html["chemin de jonction"^].
* Il est recommandé de configurer le système EMS pour envoyer des notifications par e-mail, qui incluront des notifications d'activité ARP. Pour plus d'informations, voir link:../error-messages/configure-ems-events-send-email-task.html["Configurez les événements EMS pour envoyer des notifications par e-mail"].
* À partir de la version ONTAP 9.13.1, il est recommandé d'activer la vérification multiadministrateur afin que deux administrateurs d'utilisateurs authentifiés ou plus soient requis pour la configuration ARP (Autonomous ransomware protection). Pour plus d'informations, voir link:../multi-admin-verify/enable-disable-task.html["Activez la vérification multiadministrateur"^].


.Étapes
[role="tabbed-block"]
====
.System Manager
--
. Sélectionnez *stockage > volumes*, puis sélectionnez le volume à protéger.
. Dans l'onglet *sécurité* de la vue d'ensemble *volumes*, sélectionnez *État* pour passer de Désactivé à activé en mode apprentissage dans la zone *anti-ransomware*.
. Lorsque la période d'apprentissage est terminée, passez ARP en mode actif.
+

NOTE: À partir de ONTAP 9.13.1, ARP détermine automatiquement la période d'apprentissage optimale et automatise le commutateur. C'est possible link:../anti-ransomware/enable-default-task.html["Désactivez ce paramètre sur la machine virtuelle de stockage associée"] si vous souhaitez contrôler manuellement le mode d'apprentissage en mode actif.

+
.. Sélectionnez *stockage > volumes*, puis sélectionnez le volume prêt pour le mode actif.
.. Dans l'onglet *sécurité* de la vue d'ensemble *volumes*, sélectionnez *basculer* en mode actif dans la zone anti-ransomware.


. Vous pouvez vérifier l'état ARP du volume dans la zone *anti-ransomware*.
+
Pour afficher l'état ARP de tous les volumes : dans le volet *volumes*, sélectionnez *Afficher/Masquer*, puis assurez-vous que l'état *anti-ransomware* est vérifié.



--
.CLI
--
.Activez ARP sur un volume existant
. Modifiez un volume existant pour activer la protection par ransomware en mode d'apprentissage :
+
`security anti-ransomware volume dry-run -volume _vol_name_ -vserver _svm_name_`

+
Vous pouvez également activer la protection contre les ransomware à l'aide du `volume modify` commande :

+
`volume modify -volume _vol_name_ -vserver _svm_name_ -anti-ransomware-state dry-run`

+
Si vous avez mis à niveau vers ONTAP 9.13.1 ou une version ultérieure, l'apprentissage adaptatif est activé de sorte que le changement d'état actif s'effectue automatiquement. Si vous ne souhaitez pas que ce comportement soit automatiquement activé, modifier le paramètre au niveau du SVM sur tous les volumes associés :

+
`vserver modify _svm_name_ -anti-ransomware-auto-switch-from-learning-to-enabled false`

. Lorsque la période d'apprentissage est terminée, modifiez le volume protégé pour passer en mode actif si ce n'est pas déjà fait automatiquement :
+
`security anti-ransomware volume enable -volume _vol_name_ -vserver _svm_name_`

+
Vous pouvez également passer en mode actif à l'aide de la commande modifier le volume :

+
`volume modify -volume _vol_name_ -vserver _svm_name_ -anti-ransomware-state active`

. Vérifiez l'état ARP du volume.
+
`security anti-ransomware volume show`



.Activez ARP sur un nouveau volume
. Créez un volume avec la protection anti-ransomware activée avant le provisionnement des données.
+
`volume create -volume _vol_name_ -vserver _svm_name_  -aggregate _aggr_name_ -size _nn_ -anti-ransomware-state dry-run -junction-path /_path_name_`

+
Si vous avez mis à niveau vers ONTAP 9.13.1 ou une version ultérieure, l'apprentissage adaptatif est activé de sorte que le changement d'état actif s'effectue automatiquement. Si vous ne souhaitez pas que ce comportement soit automatiquement activé, modifier le paramètre au niveau du SVM sur tous les volumes associés :

+
`vserver modify _svm_name_ -anti-ransomware-auto-switch-from-learning-to-enabled false`

. Lorsque la période d'apprentissage est terminée, modifiez le volume protégé pour passer en mode actif si ce n'est pas déjà fait automatiquement :
+
`security anti-ransomware volume enable -volume _vol_name_ -vserver _svm_name_`

+
Vous pouvez également passer en mode actif à l'aide de la commande modifier le volume :

+
`volume modify -volume _vol_name_ -vserver _svm_name_ -anti-ransomware-state active`

. Vérifiez l'état ARP du volume.
+
`security anti-ransomware volume show`



--
====