---
sidebar: sidebar 
permalink: anti-ransomware/index.html 
keywords: ransomware, arp, autonomous protection, ai, arp ai, security, detect, detection, threat, attack, suspect, anti-ransomware, entropy, abnormal volume activity, antiransomware, extension conformity, ransomware protection strategy 
summary: 'La protection autonome contre les ransomwares exploite l"analyse des workloads dans les environnements NAS pour détecter et avertir en cas d"activité anormale qui pourrait être une attaque par ransomware.' 
---
= Découvrez la protection anti-ransomware autonome de ONTAP
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Depuis ONTAP 9.10.1, la fonctionnalité ARP (autonome ransomware protection) utilise l'analyse des workloads dans les environnements NAS (NFS et SMB) pour détecter et avertir de manière proactive les activités anormales qui pourraient indiquer une attaque par ransomware. Lorsqu'une attaque est suspectée, ARP crée également de nouveaux snapshots en plus de la protection existante fournie par les snapshots programmés.



== Protection anti-ransomware autonome avec l'intelligence artificielle (ARP/IA)

Depuis la version ONTAP 9.16.1, ARP améliore la cyberrésilience en adoptant un modèle de machine learning pour l'analytique anti-ransomware qui détecte les formes de ransomware en constante évolution avec un taux de précision de 99 %. Le modèle de machine learning d'ARP est pré-entraîné sur un dataset volumineux de fichiers, à la fois avant et après une simulation d'attaque par ransomware. Cette formation intensive en ressources est réalisée en dehors de ONTAP, mais l'apprentissage de cette formation est utilisé pour le modèle au sein de ONTAP.

.Transition immédiate vers la protection active pour ARP/ai avec les volumes FlexVol
Avec les volumes ARP/ai et FlexVol, il n'y a pas de <<Modes d'apprentissage et actifs,période d'apprentissage>>. ARP/ai est activé et actif immédiatement après l'installation ou la mise à niveau vers 9.16. Après la mise à niveau de votre cluster vers ONTAP 9.16.1, ARP/ai sera automatiquement activé pour les volumes FlexVol existants et nouveaux si ARP est déjà activé pour ces volumes.

link:enable-arp-ai-with-au.html["En savoir plus sur l'activation d'ARP/ai"]

.Mises à jour automatiques ARP/ai
Pour vous protéger efficacement contre les menaces les plus récentes de ransomware, le protocole ARP/ai propose des mises à jour automatiques fréquentes qui ne sont pas cadrées entre les mises à niveau et les versions ONTAP. Si c'est le caslink:../update/enable-automatic-updates-task.html["mises à jour automatiques activées"], vous pourrez également commencer à recevoir des mises à jour de sécurité automatiques vers ARP/ai après avoir sélectionné des mises à jour automatiques pour les fichiers de sécurité. Vous pouvez également choisir d'effectuer ces mises à jour manuellement et de contrôler le moment où elles se produisent.

Depuis ONTAP 9.16.1, les mises à jour de sécurité pour ARP/ai sont disponibles via System Manager en plus des mises à jour du système et du micrologiciel.


IMPORTANT: La fonction ARP/ai ne prend actuellement en charge que le NAS. Bien que la fonctionnalité de mise à jour automatique affiche la disponibilité des nouveaux fichiers de sécurité pour le déploiement dans System Manager, ces mises à jour ne s'appliquent qu'à la protection des charges de travail NAS.

link:arp-ai-automatic-updates.html["En savoir plus sur les mises à jour ARP/ai"]



== Licences et activation

Le support ARP est inclus avec link:https://kb.netapp.com/onprem/ontap/os/ONTAP_9.10.1_and_later_licensing_overview["Licence ONTAP ONE"^]. Si vous ne disposez pas de la licence ONTAP One, d'autres licences sont disponibles pour utiliser le protocole ARP qui varie en fonction de votre version de ONTAP.

[cols="2*"]
|===
| Versions d'ONTAP | Licence 


 a| 
ONTAP 9.11.1 et versions ultérieures
 a| 
Protection contre les ransomwares



 a| 
ONTAP 9.10.1
 a| 
MT_EK_MGMT (gestion des clés mutualisée)

|===
* Si vous effectuez une mise à niveau de ONTAP 9.10.1 vers ONTAP 9.11.1 ou une version ultérieure et que ARP est déjà configuré sur votre système, vous n'avez pas besoin d'installer la nouvelle licence anti-ransomware. Pour les nouvelles configurations ARP, la nouvelle licence est requise.
* Si vous effectuez une restauration depuis ONTAP 9.11.1 ou une version ultérieure vers ONTAP 9.10.1 et que vous avez activé ARP avec la licence anti-ransomware, un message d'avertissement s'affiche et vous devrez peut-être reconfigurer ARP.


link:../revert/anti-ransomware-license-task.html["Découvrez le rétablissement ARP"].



== Stratégie ONTAP de protection contre les ransomwares

Une stratégie efficace de détection des ransomwares doit inclure plus d'une couche de protection unique

On pourrait comparer les caractéristiques de sécurité d'un véhicule. Vous ne vous fiez pas à une seule fonction, telle qu'une ceinture de sécurité, pour vous protéger complètement en cas d'accident. Les sacs gonflables, les freins antiblocage et l'avertissement de collision avant sont tous des dispositifs de sécurité supplémentaires qui permettront d'obtenir un meilleur résultat. La protection contre les ransomwares doit être vue de la même manière.

Alors que ONTAP inclut des fonctionnalités comme FPolicy, snapshots, SnapLock et Active IQ Digital Advisor (également appelé Digital Advisor) pour vous protéger contre les attaques par ransomware, les informations suivantes se concentrent sur la fonctionnalité intégrée ARP avec des fonctionnalités de machine learning.

Pour en savoir plus sur les autres fonctionnalités de ONTAP contre les ransomware, consultez link:../ransomware-solutions/ransomware-overview.html["Ransomware et le portefeuille de solutions de protection de NetApp"].



== Ce que le protocole ARP détecte

Le protocole ARP est conçu pour vous protéger contre les attaques par déni de service où l'attaquant conserve ses données jusqu'au paiement d'une rançon. ARP propose une détection en temps réel des ransomware basée sur :

* Identification des données entrantes comme cryptées ou en texte clair.
* Une analytique qui détecte :
+
** **Entropy**: Une évaluation du caractère aléatoire des données dans un fichier
** **Types d'extension de fichier** : extension non conforme au type d'extension normal
** **File IOPS** : une augmentation de l'activité de volume anormale avec le chiffrement des données (à partir de ONTAP 9.11.1)




ARP peut détecter la propagation de la plupart des attaques par ransomware après le chiffrement d'un petit nombre de fichiers uniquement, l'action automatique pour protéger les données et vous avertir qu'une attaque suspectée a lieu.


NOTE: Aucun système de détection ou de prévention par ransomware ne peut garantir la sécurité en cas d'attaque par ransomware. Bien qu'il soit possible qu'une attaque ne soit pas détectée, ARP agit comme une couche supplémentaire importante de défense si un logiciel antivirus ne parvient pas à détecter une intrusion.



== Modes d'apprentissage et actifs

Pour tous les ARP fonctionnant avec ONTAP 9.10.1 à 9.15.1 et ARP utilisés pour les volumes FlexGroup avec ONTAP 9.16.1, ARP a deux modes :

* *Mode d'apprentissage* (ou mode de fonctionnement à sec)
* *Mode actif* (ou mode « activé »)



NOTE: Avec ARP/ai débutant dans ONTAP 9.16.1, il n'y a pas de période d'apprentissage lorsque ARP est utilisé avec des volumes FlexVol. ARP/ai sur les volumes FlexVol est activé et actif immédiatement après l'installation ou la mise à niveau vers la version 9.16.1. Si vous utilisez ONTAP 9.16.1 et ARP avec des volumes FlexGroup, une période d'apprentissage est toujours nécessaire avant de passer en mode actif.

.Mode d'apprentissage
Pour tous les ARP fonctionnant avec ONTAP 9.10.1 à 9.15.1 et ARP utilisés pour les volumes FlexGroup avec ONTAP 9.16.1, lorsque vous activez ARP, il s'exécute en _mode d'apprentissage_. En mode apprentissage, le système ONTAP développe un profil d'alerte basé sur les zones analytiques : entropie, types d'extension de fichier et IOPS de fichier. Après avoir exécuté ARP en mode d'apprentissage pendant suffisamment de temps pour évaluer les caractéristiques de la charge de travail, vous pouvez passer en mode actif et commencer à protéger vos données.

Il est recommandé de laisser ARP en mode d'apprentissage pendant 30 jours. À partir de ONTAP 9.13.1, ARP détermine automatiquement l'intervalle d'apprentissage optimal et automatise le commutateur, qui peut se produire avant 30 jours.


TIP: La commande `security anti-ransomware volume workload-behavior show` affiche les extensions de fichier qui ont été détectées dans le volume. Si vous exécutez cette commande très tôt en mode d'apprentissage et qu'elle affiche une représentation précise des types de fichiers, vous ne devez pas utiliser ces données comme base pour passer en mode actif, car ONTAP collecte toujours d'autres metrics. Pour en savoir plus, `security anti-ransomware volume workload-behavior show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/security-anti-ransomware-volume-workload-behavior-show.html["Référence de commande ONTAP"^].

.Mode actif
Pour le protocole ARP fonctionnant avec ONTAP 9.10.1 à 9.15.1, le protocole ARP passe en _active mode_ une fois la période d'apprentissage optimale terminée. Une fois que le protocole ARP est passé en mode actif, ONTAP crée des instantanés ARP pour protéger les données en cas de détection d'une menace.

En mode actif, si une extension de fichier est marquée comme anormale, vous devez évaluer l'alerte. Vous pouvez agir sur l'alerte pour protéger vos données ou marquer l'alerte comme un faux positif. Le fait de marquer une alerte comme un faux positif met à jour le profil d'alerte. Par exemple, si l'alerte est déclenchée par une nouvelle extension de fichier et que vous marquez l'alerte comme un faux positif, vous ne recevrez pas d'alerte la prochaine fois que l'extension de fichier sera observée.


NOTE: A partir de ONTAP 9.11.1, vous pouvez personnaliser les paramètres de détection pour ARP. Pour plus d'informations, voir xref:manage-parameters-task.html[Gérer les paramètres de détection d'attaque ARP].



== Évaluation des menaces et instantanés ARP

Lorsqu'il est actif et non en mode d'apprentissage, le protocole ARP évalue la probabilité de menace en se basant sur les données entrantes mesurées par rapport aux analyses apprises. Une mesure est attribuée lorsque ARP détecte une menace :

* *Faible* : première détection d'une anomalie dans le volume (par exemple, une nouvelle extension de fichier est observée dans le volume). Ce niveau de détection n'est disponible que dans les versions antérieures à ONTAP 9.16.1 qui n'ont pas ARP/ai.
* *Modéré* : plusieurs fichiers avec la même extension de fichier jamais vu-avant sont observés.
+
** Dans ONTAP 9.10.1, le seuil de remontée à modéré est de 100 fichiers ou plus.
** À partir de ONTAP 9.11.1, la quantité du fichier peut être modifiée ; sa valeur par défaut est 20.




En cas de menace faible, ONTAP détecte une anomalie et crée un snapshot du volume pour créer le meilleur point de restauration. ONTAP ajoute le nom de l'instantané ARP `Anti-ransomware-backup` pour le rendre facilement identifiable ; par exemple, `Anti_ransomware_backup.2022-12-20_1248`.

La menace passe au niveau modéré après l'exécution d'un rapport d'analytique par ONTAP qui détermine si l'anomalie correspond à un profil de ransomware. Lorsque la probabilité d'attaque est modérée, ONTAP génère une notification EMS vous invitant à évaluer la menace. ONTAP n'envoie pas d'alertes concernant les menaces faibles, mais, à partir de ONTAP 9.14.1, vous pouvez xref:manage-parameters-task.html#modify-alerts[modifier les paramètres des alertes]. Pour plus d'informations, voir xref:respond-abnormal-task.html[Réagir à une activité anormale].

Vous pouvez afficher des informations sur les menaces modérées dans la section *Events* de System Manager ou à l'aide de `security anti-ransomware volume show` la commande. Les événements à faible menace peuvent également être affichés à l'aide de `security anti-ransomware volume show` la commande dans les versions antérieures à ONTAP 9.16.1 qui n'ont pas ARP/ai. Pour en savoir plus, `security anti-ransomware volume show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/security-anti-ransomware-volume-show.html["Référence de commande ONTAP"^].

Les instantanés ARP individuels sont conservés pendant deux jours. S'il existe plusieurs instantanés ARP, ils sont conservés pendant cinq jours par défaut. À partir de ONTAP 9.11.1, vous pouvez modifier les paramètres de rétention. Pour plus d'informations, voir xref:modify-automatic-shapshot-options-task.html[Modifier les options pour les instantanés].



== Comment récupérer des données dans ONTAP après une attaque par ransomware

En cas de suspicion d'attaque, le système utilise une copie Snapshot du volume à ce stade et verrouille cette copie. Si l'attaque est confirmée ultérieurement, le volume peut être restauré à l'aide de l'instantané ARP.

Les snapshots verrouillés ne peuvent pas être supprimés par des moyens normaux. Cependant, si vous décidez plus tard de marquer l'attaque comme un faux positif, la copie verrouillée sera supprimée.

En connaissant les fichiers affectés et l'heure de l'attaque, il est possible de restaurer de manière sélective les fichiers affectés à partir de différents snapshots plutôt que de simplement restaurer l'ensemble du volume sur l'un des snapshots.

ARP s'appuie donc sur la technologie de protection des données et de reprise après incident ONTAP éprouvée pour répondre aux attaques par ransomware. Pour plus d'informations sur la récupération de données, reportez-vous aux rubriques suivantes.

* link:../data-protection/restore-contents-volume-snapshot-task.html["Restaurer à partir de snapshots"]
* link:https://www.netapp.com/blog/smart-ransomware-recovery["Restauration intelligente par ransomware"^]




== Protection de vérification multiadministrateur pour ARP

Depuis la version ONTAP 9.13.1, il est recommandé d'activer la vérification multiadministrateur afin que deux administrateurs d'utilisateurs authentifiés ou plus soient requis pour la configuration ARP (Autonomous ransomware protection). Pour plus d'informations, voir link:../multi-admin-verify/enable-disable-task.html["Activez la vérification multiadministrateur"].

.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/["Référence de commande ONTAP"^]

