---
sidebar: sidebar 
permalink: anti-ransomware/manage-parameters-task.html 
keywords: anti-ransomware overview, ransomware, security, modify, security anti-ransomware attack, parameters 
summary: À partir de la version ONTAP 9.11.1, les paramètres de détection de la protection anti-ransomware autonome peuvent être modifiés en fonction du workload. 
---
= Gérer les paramètres de détection d'attaque ARP
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
À partir de la version ONTAP 9.11.1, vous pouvez modifier les paramètres de détection des ransomwares sur un volume spécifique optimisé par la protection anti-ransomware autonome et signaler une augmentation connue sous le nom d'activité de fichier normale. Le réglage des paramètres de détection permet d'améliorer la précision des rapports en fonction de votre charge de travail de volume spécifique.



== Fonctionnement de la détection des attaques

Lorsque la protection anti-ransomware autonome (ARP) est en mode d'apprentissage, elle développe des valeurs de base pour les comportements de volume. Il s'agit d'entropie, d'extensions de fichiers et, à partir de ONTAP 9.11.1, d'IOPS. Ces données de base sont utilisées pour évaluer les menaces de ransomware. Pour plus d'informations sur ces critères, reportez-vous à la section xref:index.html#what-arp-detects[Ce que le protocole ARP détecte].

Dans ONTAP 9.10.1, ARP émet un avertissement s'il détecte les deux conditions suivantes :

* plus de 20 fichiers avec des extensions de fichier qui n'ont pas été précédemment observés dans le volume
* données d'entropie élevées


À partir de ONTAP 9.11.1, ARP émet un avertissement de menace si _seule_ une condition est remplie. Par exemple, si plus de 20 fichiers avec des extensions de fichier qui n'ont pas été observées précédemment dans le volume sont observés dans une période de 24 heures, ARP catégorise ceci comme une menace _indépendamment_ de l'entropie observée. (Les valeurs de fichier 24 heures et 20 sont des valeurs par défaut, qui peuvent être modifiées.)

Certains volumes et charges de travail requièrent des paramètres de détection différents. Par exemple, votre volume ARP peut héberger de nombreux types d'extensions de fichiers. Dans ce cas, vous pouvez modifier le nombre de seuils pour les extensions de fichiers jamais vues à un nombre supérieur à la valeur par défaut de 20 ou désactiver les avertissements basés sur des extensions de fichiers jamais vues. À partir de ONTAP 9.11.1, vous pouvez modifier les paramètres de détection des attaques afin qu'ils s'adaptent mieux à vos workloads spécifiques.



== Modifier les paramètres de détection d'attaque

Selon les comportements attendus de votre volume ARP, vous pouvez modifier les paramètres de détection d'attaque.

.Étapes
. Afficher les paramètres de détection d'attaque existants :
+
`security anti-ransomware volume attack-detection-parameters show -vserver _svm_name_ -volume _volume_name_`

+
....
security anti-ransomware volume attack-detection-parameters show -vserver vs1 -volume vol1
                                             Vserver Name : vs1
                                              Volume Name : vol1
            Is Detection Based on High Entropy Data Rate? : true
  Is Detection Based on Never Seen before File Extension? : true
                  Is Detection Based on File Create Rate? : true
                  Is Detection Based on File Rename Rate? : true
                  Is Detection Based on File Delete Rate? : true
           Is Detection Relaxing Popular File Extensions? : true
                High Entropy Data Surge Notify Percentage : 100
                 File Create Rate Surge Notify Percentage : 100
                 File Rename Rate Surge Notify Percentage : 100
                 File Delete Rate Surge Notify Percentage : 100
 Never Seen before File Extensions Count Notify Threshold : 20
       Never Seen before File Extensions Duration in Hour : 24
....
. Tous les champs affichés avec le peuvent être modifiés avec des valeurs booléennes ou entières. Pour modifier un champ, utilisez `security anti-ransomware volume attack-detection-parameters modify` commande.
+
Pour obtenir la liste complète des paramètres, reportez-vous à la section link:https://docs.netapp.com/us-en/ontap-cli-9131/security-anti-ransomware-volume-attack-detection-parameters-modify.html["Référence de commande ONTAP"^].





== Signaler les surtensions connues

ARP continue de modifier les valeurs de base pour les paramètres de détection, même en mode actif. Si vous connaissez des surtensions dans votre activité de volume--des surtensions ou une surtension qui est caractéristique d'une nouvelle normale--vous devriez la signaler comme sûre. La déclaration manuelle de ces surtensions comme étant sûres contribue à améliorer la précision des évaluations des menaces d'ARP.

.Surtensions
. Si une surtension ponctuelle se produit dans des circonstances connues et que vous souhaitez que ARP signale une surtension similaire dans des circonstances futures, éliminez la poussée du comportement de la charge de travail :
+
`security anti-ransomware volume workload-behavior clear-surge -vserver _svm_name_ -volume _volume_name_`



.Modifier la surtension de la ligne de base
. Si une surtension signalée doit être considérée comme un comportement normal de l'application, signalez-la en tant que telle pour modifier la valeur de surtension de la ligne de base.
+
`security anti-ransomware volume workload-behavior update-baseline-from-surge -vserver _svm_name_ -volume _volume_name_`



.Plus d'informations
* link:https://kb.netapp.com/onprem/ontap/da/NAS/Understanding_Autonomous_Ransomware_Protection_attacks_and_the_Autonomous_Ransomware_Protection_snapshot["Apprenez à comprendre les attaques de protection anti-ransomware autonomes et le snapshot de protection anti-ransomware autonome"^]

