---
sidebar: sidebar 
permalink: anti-ransomware/modify-automatic-shapshot-options-task.html 
keywords: anti-ransomware, automatic Snapshot copy, suspected attack, vserver options command, autonomous, ransomware, protection, arp 
summary: 'Depuis ONTAP 9.11.1, vous pouvez contrôler le nombre et la période de conservation des copies Snapshot ARP (autonome ransomware protection) générées automatiquement en réponse aux attaques de ransomware suspectées.' 
---
= Modifiez les options des copies Snapshot automatiques
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Depuis ONTAP 9.11.1, vous pouvez utiliser l'interface de ligne de commandes pour contrôler le nombre et la période de conservation des copies Snapshot ARP (autonome ransomware protection) générées automatiquement en réponse aux attaques de ransomware suspectées.

*Note*: Le `vserver options` commande est une commande masquée. Pour afficher la page man, entrez `man vserver options` Sur l'interface de ligne de commandes de ONTAP.

Les options suivantes pour les copies Snapshot automatiques peuvent être modifiées :

compte arw.snap.max:: Spécifie le nombre maximal de copies snapshot ARP pouvant exister dans un volume à tout moment. Les anciennes copies sont supprimées pour garantir que le nombre total de copies snapshot ARP se situe dans cette limite spécifiée.
arw.snap.create.interval.hours:: Spécifie l'intervalle (en heures) entre les copies snapshot ARP. Une nouvelle copie Snapshot est créée lorsqu'une attaque est suspectée et que la copie créée précédemment est plus ancienne que cet intervalle spécifié.
arw.snap.normal.retain.interval.hours:: Spécifie la durée (en heures) pendant laquelle une copie Snapshot ARP est conservée. Lorsqu'une copie snapshot ARP devient cet ancien, toute autre copie Snapshot ARP créée avant la dernière copie pour atteindre cet âge est supprimée. Aucune copie snapshot ARP ne peut être antérieure à cette durée.
arw.snap.max.retain.interval.days:: Spécifie la durée maximale (en jours) pendant laquelle une copie Snapshot ARP peut être conservée. Toute copie snapshot ARP antérieure à cette durée sera supprimée si aucune attaque n'a été signalée sur le volume.
arw.snap.create.interval.hours.post.max.count:: Spécifie l'intervalle (en heures) entre les copies Snapshot ARP lorsque le volume contient déjà le nombre maximal de copies Snapshot ARP. Lorsque le nombre maximum est atteint, une copie snapshot ARP est supprimée pour faire place à une nouvelle copie. La nouvelle vitesse de création de copie Snapshot ARP peut être réduite pour conserver l'ancienne copie à l'aide de cette option. Si le volume contient déjà un nombre maximal de copies snapshot ARP, cet intervalle spécifié dans cette option est utilisé pour la création de la copie Snapshot ARP suivante, au lieu de arw.snap.create.interval.hours.
arw.surge.snap.interval.days:: Spécifie l'intervalle (en jours) entre les copies Snapshot de surtension ARP. Une nouvelle copie de surtension ARP Snapshot est créée en cas de forte augmentation du trafic d'E/S et si la dernière copie Snapshot ARP créée est plus ancienne que cet intervalle spécifié. Cette option indique également la durée (en jours) pendant laquelle une copie Snapshot de surtension ARP est conservée.


Pour afficher tous les paramètres de copie snapshot ARP actuels, entrez :
`vserver options -vserver _svm_name_ arw*`

Pour afficher les paramètres de copie snapshot ARP actuels sélectionnés, entrez :
`vserver options -vserver _svm_name_ -option-name _arw_setting_name_`

Pour modifier les paramètres de copie snapshot ARP, entrez :
`vserver options -vserver _svm_name_ -option-name _arw_setting_name_ -option-value _arw_setting_value_`
