---
sidebar: sidebar 
permalink: anti-ransomware/pause-task.html 
keywords: anti-ransomware, ransomware, pause, autonomous, protection, arp 
summary: 'Si vous attendez des événements inhabituels des charges de travail, vous pouvez suspendre et reprendre temporairement l"analyse ARP (autonome ransomware protection) à tout moment.' 
---
= Mettez en pause la protection autonome contre les ransomwares pour exclure les événements des charges de travail de l'analyse
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
Si vous attendez des événements inhabituels des charges de travail, vous pouvez suspendre et reprendre temporairement l'analyse ARP (autonome ransomware protection) à tout moment.

.Ce dont vous aurez besoin
* ARP s'exécute en mode apprentissage ou actif.


Lors d'une pause ARP, aucun événement n'est enregistré et aucune action n'est en cours pour les nouvelles écritures. Toutefois, le processus d'analytique continue pour les journaux précédents en arrière-plan.


NOTE: N'utilisez pas la fonction de désactivation anti-ransomware pour interrompre l'analytique. Ceci désactive ARP sur le volume et toutes les informations existantes concernant le comportement de la charge de travail apprise sont perdues. Cela nécessiterait un redémarrage de la période d'apprentissage.

.Étapes
[role="tabbed-block"]
====
.System Manager
--
. Cliquez sur *Storage > volumes*, puis sélectionnez le volume sur lequel vous souhaitez mettre ARP en pause.
. Dans l'onglet sécurité de la vue d'ensemble des volumes, cliquez sur *Pause anti-ransomware* dans la zone *anti-ransomware*.


--
.CLI
--
Suspendre ARP sur un volume :

`security anti-ransomware volume pause -vserver _svm_name_ -volume _vol_name_`

Pour reprendre le traitement, utilisez `resume` paramètre.

`security anti-ransomware volume resume -vserver _svm_name_ -volume _vol_name_`

--
====