---
sidebar: sidebar 
permalink: snapmirror-active-sync/cloud-mediator-requirements-concept.html 
keywords: SM-BC, SMBC, ONTAP, Cloud Mediator, prerequisites, requirements, configuration, firewall, latency, proxy, certificate, snapmirror active sync 
summary: Vous devez répondre à certaines exigences avant d’installer ONTAP Cloud Mediator. 
---
= Préparez-vous à configurer ONTAP Cloud Mediator
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Avant toi link:cloud-mediator-config-task.html["configurer ONTAP Cloud Mediator"] , vous devez vous assurer que les conditions préalables sont remplies.



[[firewall-requirements]]
== Exigences relatives au pare-feu

Le paramètre de pare-feu sur le contrôleur de domaine doit autoriser le trafic HTTPS  `api.bluexp.netapp.com` des deux groupes.



[[proxy-server-requirements]]
== Exigences du serveur proxy

Si vous utilisez des serveurs proxy pour la synchronisation active de SnapMirror , assurez-vous que les serveurs proxy sont créés et que vous disposez des informations de serveur proxy suivantes :

* IP proxy HTTPS
* Port
* Nom d'utilisateur
* Mot de passe




[[latency]]
== Latence

La latence de ping recommandée entre le serveur cloud de la console NetApp et les homologues du cluster de synchronisation active SnapMirror est inférieure à 200 ms.



[[root-ca-certificates]]
== Certificats d'autorité de certification racine

.Vérifiez le cluster pour les certificats
ONTAP est livré avec des certificats CA racine bien connus préinstallés. Dans la plupart des cas, vous n'avez donc pas besoin d'installer le certificat CA racine du serveur de la console NetApp . Avant de commencer la configuration ONTAP Cloud Mediator, vous pouvez vérifier l'existence des certificats dans le cluster :

Exemple :

[listing]
----
C1_cluster% openssl s_client -showcerts -connect api.bluexp.netapp.com:443 -servername api.bluexp.netapp.com | egrep "s:|i:"

depth=4 C=GB, ST=Greater Manchester, L=Salford, O=Comodo CA Limited, CN=AAA Certificate Services
verify error:num=19:self-signed certificate in certificate chain
verify return:1
depth=4 C=GB, ST=Greater Manchester, L=Salford, O=Comodo CA Limited, CN=AAA Certificate Services
verify return:1
depth=3 C=US, ST=New Jersey, L=Jersey City, O=The USERTRUST Network, CN=USERTrust RSA Certification Authority
verify return:1
depth=2 C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication Root R46
verify return:1
depth=1 C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication CA OV R36
verify return:1
depth=0 C=US, ST=California, O=NetApp, Inc., CN=cloud.netapp.com
verify return:1
 0 s:C=US, ST=California, O=NetApp, Inc., CN=cloud.netapp.com
   i:C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication CA OV R36
 1 s:C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication CA OV R36
   i:C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication Root R46
 2 s:C=GB, O=Sectigo Limited, CN=Sectigo Public Server Authentication Root R46
   i:C=US, ST=New Jersey, L=Jersey City, O=The USERTRUST Network, CN=USERTrust RSA Certification Authority
 3 s:C=US, ST=New Jersey, L=Jersey City, O=The USERTRUST Network, CN=USERTrust RSA Certification Authority
   i:C=GB, ST=Greater Manchester, L=Salford, O=Comodo CA Limited, CN=AAA Certificate Services
 4 s:C=GB, ST=Greater Manchester, L=Salford, O=Comodo CA Limited, CN=AAA Certificate Services
   i:C=GB, ST=Greater Manchester, L=Salford, O=Comodo CA Limited, CN=AAA Certificate Services

C1_cluster::> security certificate show -common-name Sectigo*|USERTrust*|AAA*
Vserver    Serial Number   Certificate Name                       Type
---------- --------------- -------------------------------------- ------------
C1_sti245-vsim-ocvs024k_1775534714 42F2CCDA1B6937445F15FE752810B8F4 SectigoPublicServerAuthenticationRootE46 server-ca
    Certificate Authority: Sectigo Public Server Authentication Root E46
          Expiration Date: Wed Mar 21 19:59:59 2046

C1_sti245-vsim-ocvs024k_1775534714 758DFD8BAE7C0700FAA925A7E1C7AD14 SectigoPublicServerAuthenticationRootR46 server-ca
    Certificate Authority: Sectigo Public Server Authentication Root R46
          Expiration Date: Wed Mar 21 19:59:59 2046

C1_sti245-vsim-ocvs024k_1775534714 5C8B99C55A94C5D27156DECD8980CC26 USERTrustECCCertificationAuthority server-ca
    Certificate Authority: USERTrust ECC Certification Authority
          Expiration Date: Mon Jan 18 18:59:59 2038

C1_sti245-vsim-ocvs024k_1775534714 01FD6D30FCA3CA51A81BBC640E35032D USERTrustRSACertificationAuthority server-ca
    Certificate Authority: USERTrust RSA Certification Authority
          Expiration Date: Mon Jan 18 18:59:59 2038

----
.Vérifiez le serveur proxy pour les certificats installés
Si vous utilisez un proxy pour vous connecter au service ONTAP Cloud Mediator dans la console NetApp , assurez-vous que les certificats d'autorité de certification racine du serveur proxy sont installés dans ONTAP:

Exemple :

[listing]
----
C1_cluster% openssl s_client -showcerts -proxy <ip:port> -connect api.bluexp.netapp.com:443 -servername api.bluexp.netapp.com |egrep "s:|i:"
----
.Télécharger le certificat CA :
Si nécessaire, vous pouvez télécharger les certificats root-CA à partir du site Web de l'autorité de certification et les installer sur les clusters.

Exemple :

[listing]
----
C1_cluster::> security certificate install -type server-ca -vserver C1_cluster

C2_cluster::> security certificate install -type server-ca -vserver C2_cluster
----