---
sidebar: sidebar 
permalink: snapmirror-active-sync/cloud-mediator-slow-troubleshoot-task.html 
keywords: troubleshooting, SM-BC, SMBC, Cloud Mediator, network, latency, snapmirror active sync 
summary: 'L"ajout d" ONTAP Cloud Meditor échoue avec une erreur indiquant que la latence du ping est supérieure à la latence recommandée.' 
---
= ONTAP Cloud Mediator est accessible mais répond lentement
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Utilisez les informations suivantes si ONTAP Cloud Meditor échoue avec une erreur indiquant que la latence du ping est supérieure à la latence recommandée.

.Problème :
Gestionnaire système : Le service Cloud Mediator est accessible mais il répond lentement.

CLI : Le  `mediator add` la commande échoue avec l'erreur : 
`Error: command failed: The ping latency of the BlueXP cloud server is <x> ms which is higher than twice the recommended latency of 200 ms.`

.Cause :
Il se peut que les clusters ne soient pas situés à proximité du cloud de la console NetApp ou qu'il existe des goulots d'étranglement au niveau du chemin réseau.

.Solution :
* Vérifiez l’emplacement géographique et la proximité du cloud NetApp Console (US East).
* Optimisez le chemin réseau ou résolvez les goulots d’étranglement.
* Mesurez le temps d'aller-retour (RTT) à l'aide d'outils réseau et réduisez la latence dans les limites recommandées.
* Utilisez un proxy HTTP pour améliorer les performances.


Voir link:cloud-mediator-config-task.html["Configurer ONTAP Cloud Mediator et les clusters pour la synchronisation active SnapMirror"] .
