---
sidebar: sidebar 
permalink: snapmirror-active-sync/cluster-config-task.html 
keywords: SM-BC, SMBC, cluster, peering, ONTAP, Mediator, ONTAP Cloud Mediator, initialize, snapmirror active sync 
summary: Lorsque vous utilisez ONTAP Mediator ou ONTAP Cloud Mediator avec SnapMirror Active Sync, vous devez d’abord vous assurer que le cluster est correctement configuré. 
---
= Configurer les clusters ONTAP pour la synchronisation active SnapMirror
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror Active Sync utilise des clusters appairés pour protéger vos données en cas de basculement. Avant de configurer ONTAP Mediator ou ONTAP Cloud Mediator pour SnapMirror Active Sync, vous devez d'abord vous assurer que le cluster est correctement configuré.

.Avant de commencer
Avant de configurer ONTAP Mediator ou ONTAP Cloud Mediator, vous devez confirmer les points suivants :

. Une relation d'appairage de cluster existe entre les clusters.
+

NOTE: L'IPspace par défaut est requis par SnapMirror Active Sync pour les relations entre clusters. Un IPspace personnalisé n'est pas pris en charge.

+
link:../peering/create-cluster-relationship-93-later-task.html["Création d'une relation entre clusters"]

. Les SVM sont créés sur chaque cluster.
+
link:../smb-config/create-svms-data-access-task.html["Création d'un SVM"]

. Une relation d’homologue existe entre les SVM de chaque cluster.
+
link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["Création d'une relation de SVM peering"]

. Les volumes existent pour vos LUN.
+
link:../smb-config/create-volume-task.html["Création d'un volume"]

. Au moins un SAN LIF (FC ou iSCSI selon le cas) est créé sur chaque nœud dans les deux clusters.
+
link:../san-admin/manage-lifs-all-san-protocols-concept.html["Considérations relatives aux LIF dans un environnement SAN de cluster"]

+
link:../networking/create_a_lif.html["Création d'une LIF"]

. Les LUN nécessaires sont créés et mappés à un igroup, qui est utilisé pour mapper les LUN à l'initiateur sur l'hôte d'application.
+
link:../san-admin/provision-storage.html["Créer des LUN et mapper des igroups"]

. L'hôte de l'application est réanalysé pour découvrir de nouveaux LUN.

