---
sidebar: sidebar 
permalink: snapmirror-active-sync/delete-fails-takeover-task.html 
keywords: troubleshooting, SM-BC, SMBC, SnapMirror, delete, takeover, consistency group, snapmirror active sync 
summary: 'Lorsque ONTAP 9.9.1 est installé sur un cluster, l"exécution de la commande  `snapmirror delete` la commande échoue lorsqu"une relation de groupe de cohérence de synchronisation active SnapMirror est en état de prise de contrôle.' 
---
= L'opération de suppression de SnapMirror ONTAP échoue dans l'état de reprise
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Utilisez les informations suivantes si le  `snapmirror delete` la commande échoue lorsqu'une relation de groupe de cohérence de synchronisation active SnapMirror est en état de prise de contrôle.

.Problème :
Lorsque ONTAP 9.9.1 est installé sur un cluster, l'exécution de la commande  `snapmirror delete` la commande échoue lorsqu'une relation de groupe de cohérence de synchronisation active SnapMirror est en état de prise de contrôle.

....
C2_cluster::> snapmirror delete  vs1:/cg/dd

Error: command failed: RPC: Couldn't make connection
....
.Solution
Lorsque les nœuds d'une relation de synchronisation active SnapMirror sont en état de prise de contrôle, effectuez l'opération de suppression et de libération de SnapMirror avec l'option « -force » définie sur true.

....
C2_cluster::> snapmirror delete  vs1:/cg/dd -force true

Warning: The relationship between source "vs0:/cg/ss" and destination
         "vs1:/cg/dd" will be deleted, however the items of the destination
         Consistency Group might not be made writable, deletable, or modifiable
         after the operation. Manual recovery might be required.
Do you want to continue? {y|n}: y
Operation succeeded: snapmirror delete for the relationship with destination "vs1:/cg/dd".
....
.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["suppression de snapmirror"^]

