---
sidebar: sidebar 
permalink: snapmirror-active-sync/index.html 
keywords: SM-BC, SMBC, failover, terms, benefits, snapmirror active sync, TR-4878 
summary: 'Utilisez la synchronisation active SnapMirror pour protéger les applications avec les LUN. Les applications peuvent ainsi basculer en toute transparence et assurer la continuité de l"activité en cas d"incident.' 
---
= En savoir plus sur la synchronisation active ONTAP SnapMirror
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La synchronisation active SnapMirror (également appelée SnapMirror Business Continuity _[SM-BC]_) permet aux services de l'entreprise de continuer à fonctionner même en cas de défaillance complète du site. Les applications peuvent ainsi basculer en toute transparence grâce à une copie secondaire. Aucune intervention manuelle ni script personnalisé n'est nécessaire pour déclencher un basculement avec la synchronisation active SnapMirror.

La prise en charge de la synchronisation active SnapMirror varie en fonction de votre version d' ONTAP:

[cols="4*"]
|===


| Version ONTAP | Clusters pris en charge | Protocoles pris en charge | Configurations compatibles 


| 9.17.1 et versions ultérieures  a| 
* AFF
* ASA
* Série C.
* ASA r2

 a| 
* ISCSI
* FC
* NVMe

 a| 
* Asymétrique actif/actif



NOTE: L'asymétrique actif/actif ne prend pas en charge ASA r2 et NVMe. Pour plus d'informations sur la prise en charge de NVMe, consultez link:../nvme/support-limitations.html["Configuration, prise en charge et limitations de NVMe"] .

* Symétrie actif-actif




| 9.15.1 et versions ultérieures  a| 
* AFF
* ASA
* Série C.

 a| 
* ISCSI
* FC

 a| 
* Asymétrique actif/actif
* Les configurations symétriques actives/actives prennent en charge les clusters à 2 nœuds dans ONTAP 9.15.1. Les clusters à 4 nœuds sont pris en charge dans ONTAP 9.16.1 et versions ultérieures.




| 9.9.1 et versions ultérieures  a| 
* AFF
* ASA
* Série C *

 a| 
* ISCSI
* FC

 a| 
Asymétrique actif/actif

|===
Les clusters primaires et secondaires doivent être du même type : soit link:../san-admin/learn-about-asa.html["ASA"] , link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA r2"^] , ou AFF.


NOTE: Depuis juillet 2024, le contenu des rapports techniques publiés au format PDF a été intégré à la documentation produit de ONTAP. La documentation relative à la synchronisation active de SnapMirror ONTAP inclut désormais du contenu de _TR-4878: SnapMirror active sync_.



== Avantages

La synchronisation active SnapMirror offre les avantages suivants :

* Disponibilité sans interruption pour les applications stratégiques.
* Possibilité d'héberger alternativement des applications critiques à partir de sites principaux et secondaires.
* Gestion simplifiée des applications grâce à l'utilisation de groupes de cohérence pour assurer la cohérence des ordres d'écriture dépendants.
* Capacité à tester le basculement pour chaque application.
* Création instantanée de clones en miroir sans impact sur la disponibilité des applications.
* La possibilité de déployer des charges de travail protégées et non protégées dans le même cluster ONTAP.
* L'identité du LUN, de l'espace de noms NVMe, du sous-système NVMe ou de l'unité de stockage reste la même, de sorte que l'application les considère comme un périphérique virtuel partagé.
* Possibilité de réutiliser des clusters secondaires avec flexibilité pour créer des clones instantanés pour l'utilisation des applications à des fins de développement et de test UAT ou de création de rapports, sans impact sur la disponibilité ou les performances des applications.


La synchronisation active SnapMirror vous permet de protéger vos LUN de données ou vos espaces de noms NVMe, ce qui permet aux applications de basculer de manière transparente pour assurer la continuité de l'activité en cas de sinistre. Pour plus d'informations, consultez la page link:use-cases-concept.html["Cas d'utilisation"] .



== Concepts clés

SnapMirror Active Sync utilise des groupes de cohérence et ONTAP Mediator ou, à partir d' ONTAP 9.17.1, ONTAP Cloud Mediator pour garantir la réplication et la diffusion de vos données, même en cas de sinistre. Lors de la planification de votre déploiement de SnapMirror Active Sync, il est important de comprendre les concepts essentiels de SnapMirror Active Sync et de son architecture.

.Asymétrie et symétrie
Dans les configurations symétriques actif/actif, les deux sites peuvent accéder au stockage local pour les E/S actives. La configuration symétrique actif/actif est optimisée pour les applications en cluster, notamment VMware vMSC, Windows Failover Cluster avec SQL et Oracle RAC.

Dans les configurations actives/actives asymétriques, les données du site secondaire sont transmises par proxy à un LUN, un espace de noms ou une unité de stockage.

Pour plus d'informations, voir xref:architecture-concept.html[Architecture de synchronisation active SnapMirror].

.Groupe de cohérence
Pour les systèmes AFF et ASA, un link:../consistency-groups/index.html["groupe de cohérence"] Il s'agit d'un ensemble de volumes FlexVol garantissant la cohérence de la charge de travail applicative devant être protégée pour la continuité des activités. Dans les systèmes ASA r2, un groupe de cohérence est un ensemble d'unités de stockage.

L'objectif d'un groupe de cohérence est de prendre des instantanés simultanés d'un ensemble de volumes ou d'unités de stockage, garantissant ainsi des copies cohérentes en cas de panne à un instant T. Un groupe de cohérence garantit que tous les volumes d'un ensemble de données sont suspendus, puis réinitialisés exactement au même instant. Cela fournit un point de restauration cohérent pour les données des volumes ou unités de stockage prenant en charge l'ensemble de données. Un groupe de cohérence maintient ainsi la cohérence des ordres d'écriture dépendants. Si vous décidez de protéger des applications pour la continuité d'activité, le groupe de volumes ou d'unités de stockage correspondant à cette application doit être ajouté à un groupe de cohérence afin d'établir une relation de protection des données entre les groupes de cohérence source et destination. Les groupes de cohérence source et destination doivent contenir le même nombre et le même type de volumes.

.Composant
Un volume individuel, un LUN ou un espace de noms NVMe (commençant par ONTAP 9.17.1) qui fait partie du groupe de cohérence protégé dans la relation de synchronisation active SnapMirror .

.Médiateur de ONTAP
Le link:../mediator/index.html["Médiateur de ONTAP"] Reçoit des informations sur l'état de santé des clusters et nœuds ONTAP appairés, coordonne les échanges entre eux et détermine si chaque nœud/cluster est en bon état et opérationnel. ONTAP Mediator fournit des informations sur l'état de santé des nœuds et nœuds suivants :

* Clusters Peer ONTAP
* Nœuds de cluster Peer ONTAP
* Groupes de cohérence (qui définissent les unités de basculement dans une relation de synchronisation active SnapMirror) ; les informations suivantes sont fournies pour chaque groupe de cohérence :
+
** État de la réplication : non initialisé, en synchronisation ou désynchronisé
** Quel cluster héberge la copie principale
** Contexte d'opération (utilisé pour le basculement planifié)




Grâce à ces informations sur l'état de santé du médiateur ONTAP, les clusters peuvent différencier différents types de défaillances et déterminer s'il faut effectuer un basculement automatique. Le médiateur ONTAP est l'un des trois intervenants du quorum de synchronisation active SnapMirror avec les deux clusters ONTAP (principal et secondaire). Pour parvenir à un consensus, au moins deux parties au quorum doivent accepter une certaine opération.


NOTE: Depuis ONTAP 9.15.1, System Manager affiche l'état de votre relation de synchronisation active SnapMirror depuis l'un ou l'autre cluster. Vous pouvez également surveiller l'état du médiateur ONTAP depuis l'un des clusters dans System Manager. Dans les versions précédentes de ONTAP, System Manager affiche l'état des relations de synchronisation active SnapMirror depuis le cluster source.

.Médiateur cloud ONTAP
ONTAP Cloud Mediator est disponible à partir d' ONTAP 9.17.1. ONTAP Cloud Mediator fournit les mêmes services ONTAP Mediator, sauf qu'il est hébergé dans le cloud à l'aide de BlueXP.

.Basculement planifié
Opération manuelle pour modifier le rôle des copies dans une relation de synchronisation active SnapMirror. Les sites principaux deviennent les sites secondaires, et le site secondaire devient le site principal.

.Polarisation primaire en premier et primaire
La synchronisation active SnapMirror utilise un principe prioritaire qui donne la préférence à la copie principale pour traiter les E/S en cas de partition réseau.

Le principal biais est une implémentation spéciale de quorum qui améliore la disponibilité d'un dataset protégé par synchronisation active SnapMirror. Si la copie principale est disponible, le biais principal entre en vigueur lorsque le médiateur ONTAP n'est pas accessible depuis les deux clusters.

Le principal et le principal biais sont pris en charge dans la synchronisation active SnapMirror à partir de ONTAP 9.15.1. Les copies primaires sont désignées dans System Manager et sortent avec l'API REST et l'interface de ligne de commandes.

.Basculement automatique non planifié (AUFO)
Opération automatique pour effectuer un basculement vers la copie miroir. L'opération nécessite l'aide du médiateur ONTAP pour détecter que la copie principale n'est pas disponible.

.Non synchronisé (OOS)
Lorsque les E/S de l'application ne sont pas répliquées sur le système de stockage secondaire, elles sont signalées comme **hors synchronisation**. L'état « non synchronisé » signifie que les volumes secondaires ne sont pas synchronisés avec le volume primaire (source) et que la réplication SnapMirror n'est pas en cours.

Si l'état du miroir est `Snapmirrored`, indique un échec ou un échec de transfert dû à une opération non prise en charge.

La synchronisation active SnapMirror prend en charge la resynchronisation automatique qui permet le retour des copies à un état insync.

À partir de la version ONTAP 9.15.1, SnapMirror active Sync est pris en charge link:interoperability-reference.html#fan-out-configurations["reconfiguration automatique dans les configurations « fan-out »"].

.Configuration uniforme et non uniforme
* **Accès hôte uniforme** signifie que les hôtes des deux sites sont connectés à tous les chemins vers les clusters de stockage sur les deux sites. Les chemins d'accès intersites sont étendus sur plusieurs distances.
* **Accès hôte non uniforme** signifie que les hôtes de chaque site sont connectés uniquement au cluster du même site. Les chemins intersites et les chemins étendus ne sont pas connectés.



NOTE: Un accès uniforme à l'hôte est pris en charge pour tout déploiement SnapMirror à synchronisation active. L'accès non uniforme à l'hôte n'est pris en charge que pour les déploiements actif-actif symétriques.

.RPO nul
L'objectif RPO correspond à l'objectif de point de récupération, qui correspond à la quantité de perte de données jugée acceptable au cours d'une période donnée. La valeur RPO de zéro signifie qu'aucune perte de données n'est acceptable.

.Le RTO nul
L'objectif RTO désigne l'objectif de délai de restauration, qui correspond au temps jugé acceptable pour une application de reprendre son activité normale sans interruption suite à une panne, une défaillance ou tout autre événement de perte de données. La valeur zéro RTO indique qu'aucune interruption n'est acceptable.
