---
sidebar: sidebar 
permalink: snapmirror-active-sync/limits-reference.html 
keywords: SM-BC, SMBC, restrictions, consistency group, endpoint limits, solaris, aix, hp-ux, fanout, snapmirror active sync 
summary: 'Il existe plusieurs restrictions et restrictions supplémentaires lors de l"utilisation de la synchronisation active SnapMirror.' 
---
= Limites d'objet pour la synchronisation active SnapMirror
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Lorsque vous vous préparez à utiliser la synchronisation active SnapMirror, tenez compte des limites d'objet suivantes.



== Groupes de cohérence dans un cluster

Les limites de groupe de cohérence d'un cluster avec SnapMirror actif Sync sont calculées en fonction des relations et dépendent de la version de ONTAP utilisée. Les limites sont indépendantes de la plateforme.

|===
| Version ONTAP | Nombre maximal de relations 


| ONTAP 9.11.1 et versions ultérieures | 50 


| ONTAP 9.10.1 | 20 


| ONTAP 9.9.1 | 5 
|===


== Volumes par groupe de cohérence

Le nombre maximal de volumes par groupe de cohérence avec la synchronisation active SnapMirror est indépendant de la plateforme.

|===
| Version ONTAP | Nombre maximal de volumes pris en charge dans une relation de groupe de cohérence 


| ONTAP 9.15.1 et versions ultérieures | 80 


| ONTAP 9.10.1-9.14.1 | 16 


| ONTAP 9.9.1 | 12 
|===


== Volumes

Dans SnapMirror, les limites de volume de la synchronisation active sont calculées sur la base du nombre de terminaux, et non du nombre de relations. Un groupe de cohérence de 12 volumes contribue à hauteur de 12 terminaux sur le cluster principal et le cluster secondaire. La synchronisation active SnapMirror et les relations synchrone SnapMirror contribuent toutes deux au nombre total de terminaux.

Le nombre maximum de terminaux par plateforme est inclus dans le tableau suivant.

|===
| S. Non | Plateforme 3+| Terminaux par haute disponibilité pour la synchronisation active SnapMirror 3+| Terminaux de synchronisation actifs SnapMirror et de synchronisation globaux pour chaque haute disponibilité 


|  |  | ONTAP 9.11.1 et versions ultérieures | ONTAP 9.10.1 | ONTAP 9.9.1 | ONTAP 9.11.1 et versions ultérieures | ONTAP 9.10.1 | ONTAP 9.9.1 


| 1 | AFF | 400 | 200 | 60 | 400 | 200 | 80 


| 2 | ASA | 400 | 200 | 60 | 80 | 200 | 400 
|===


== Limites D'objets SAN

Les limites des objets SAN sont incluses dans le tableau suivant. Les limites s'appliquent quelle que soit la plate-forme.

|===
| Objet dans une relation de synchronisation active SnapMirror | Nombre 


| LUN par volume | 256 


| Mappages de LUN par nœud  a| 
* 4096 (ONTAP 9.10 et versions ultérieures)
* 2048 (ONTAP 9.9.1 et versions antérieures)




| Mappages de LUN par cluster  a| 
* 8192 (ONTAP 9.10 et versions ultérieures)
* 4096 (ONTAP 9.9.1 et versions antérieures)




| LIFs par SVM (avec au moins un volume dans une relation SnapMirror active Sync) | 256 


| LIF inter-cluster par nœud | 4 


| LIF inter-cluster par cluster | 8 
|===
.Informations associées
* link:https://hwu.netapp.com/["Hardware Universe"^]
* link:../consistency-groups/limits.html["Limites des groupes de cohérence"^]

