---
sidebar: sidebar 
permalink: snapmirror-active-sync/planned-failover-unsuccessful-task.html 
keywords: troubleshooting, SM-BC, SMBC, SnapMirror, failover, planned failover, common Snapshot copy, snapmirror active sync 
summary: 'Après avoir exécuté le `snapmirror failover start` commande, sortie de `snapmirror failover show` commande affiche un message indique qu"une opération sans interruption est en cours.' 
---
= Échec du basculement planifié
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Utilisez les informations suivantes si l’opération de basculement planifiée échoue.

.Problème :
Après avoir exécuté le `snapmirror failover start` commande, sortie de `snapmirror failover show` commande affiche un message indique qu'une opération sans interruption est en cours.

....
Cluster1::> snapmirror failover show
Source Destination Error
Path Path Type Status start-time end-time Reason
-------- ----------- -------- --------- ---------- ---------- ----------
vs1:/cg/cg vs0:/cg/cg planned failed 10/1/2020 10/1/2020 SnapMirror Failover cannot start because a volume move is running. Retry the command once volume move has finished.
                                                          08:35:04 08:35:04
....
.Cause :
Un basculement planifié ne peut pas commencer lorsqu'une opération sans interruption est en cours, notamment le déplacement de volumes, le déplacement d'agrégats et le basculement du stockage.

.Solution :
Attendez la fin de l'opération sans interruption et réessayez l'opération de basculement.

.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-failover-show.html["affichage du basculement de SnapMirror"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-failover-start.html["démarrage du basculement de SnapMirror"^]

