---
sidebar: sidebar 
permalink: snapmirror-active-sync/prerequisites-reference.html 
keywords: SM-BC, SMBC, prerequisites, planning, software, hardware, licensing, protocols, network, snapmirror active sync 
summary: 'Plusieurs conditions préalables doivent être prises en compte lors de la planification du déploiement d"une solution de synchronisation active SnapMirror.' 
---
= Conditions préalables pour la synchronisation active ONTAP SnapMirror
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Lors de la planification de votre déploiement de synchronisation active SnapMirror, assurez-vous de répondre aux différentes exigences en matière de matériel, de logiciels et de configuration système.



== Sous-jacent

Le tableau suivant présente les configurations de cluster NetApp prises en charge.

[cols="25,25,25,25"]
|===


| Type de cluster | Modèles pris en charge | Fonctionnalités prises en charge | Nombre maximal de nœuds de cluster pris en charge 


 a| 
AFF
 a| 
A-Series, C-Series
 a| 
Basculement automatisé en duplex (symétrique actif/actif), basculement automatisé (asymétrique actif/actif)
 a| 
* 2 (ONTAP 9.9.1 ou version ultérieure)
* 4 (ONTAP 9.16.1 avec configurations symétriques actives/actives)




 a| 
ASA
 a| 
A-Series, C-Series
 a| 
Basculement automatisé en duplex (symétrique actif/actif), basculement automatisé (asymétrique actif/actif)
 a| 
* 2 (ONTAP 9.9.1 ou version ultérieure
* 4 (ONTAP 9.16.1 avec configurations symétriques actives/actives)




 a| 
ASA r2
 a| 
Tout
 a| 
Basculement automatique en duplex (actif symétrique/actif)
 a| 
2

|===
Le tableau ci-dessous présente la fonctionnalité de réplication entre types de cluster.

[cols="33,33,33"]
|===


| Type de cluster 1 | Type de cluster 2 | Réplication prise en charge ? 


 a| 
Série A AFF
 a| 
AFF série C.
 a| 
Oui.



 a| 
ASA r2 Série A
 a| 
ASA r2 Série C
 a| 
Oui.



 a| 
AFF
 a| 
ASA
 a| 
Non



 a| 
ASA
 a| 
ASA r2
 a| 
Non



 a| 
ASA r2
 a| 
ASA r2
 a| 
Oui.

|===


== Logiciel

* ONTAP 9.9.1 ou version ultérieure
* ONTAP Mediator 1.2 ou version ultérieure
* Un serveur Linux ou une machine virtuelle pour ONTAP Mediator exécutant l'un des éléments suivants :


[cols="30,70"]
|===


| Version du médiateur ONTAP | Versions Linux prises en charge 


 a| 
1,10
 a| 
* Red Hat Enterprise Linux
+
** Compatible : 9.5 ^1^
** Recommandé : 8.10, 9.4, 9.6 et 10


* Rocky Linux 8.10, 9.6 et 10




 a| 
1.9.1
 a| 
* Red Hat Enterprise Linux
+
** Compatible : 8.4, 8.5, 8.6, 8.7, 8.9, 9.1 et 9.3 ^1^
** Recommandations : 8.8, 8.10, 9.0, 9.2, 9.4 et 9.5


* Rocky Linux 8,10 et 9,5




 a| 
1,9
 a| 
* Red Hat Enterprise Linux
+
** Compatible : 8.4, 8.5, 8.6, 8.7, 8.9, 9.1 et 9.3 ^1^
** Recommandations : 8.8, 8.10, 9.0, 9.2, 9.4 et 9.5


* Rocky Linux 8,10 et 9,5




 a| 
1.8
 a| 
* Red Hat Enterprise Linux : 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 8.10, 9.0, 9.1, 9.2, 9.3 et 9.4
* Rocky Linux 8,10 et 9,4




 a| 
1.7
 a| 
* Red Hat Enterprise Linux : 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9.0, 9.1, 9.2 et 9.3
* Rocky Linux 8,9 et 9,3




 a| 
1.6
 a| 
* Red Hat Enterprise Linux : 8.4, 8.5, 8.6, 8.7, 8.8, 9.0, 9.1, 9.2
* Rocky Linux 8,8 et 9,2




 a| 
1.5
 a| 
* Red Hat Enterprise Linux : 7.6, 7.7, 7.8, 7.9, 8.0, 8.1, 8.2, 8.3, 8.4, 8.5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.4
 a| 
* Red Hat Enterprise Linux : 7.6, 7.7, 7.8, 7.9, 8.0, 8.1, 8.2, 8.3, 8.4, 8.5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.3
 a| 
* Red Hat Enterprise Linux : 7.6, 7.7, 7.8, 7.9, 8.0, 8.1, 8.2, 8.3
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.2
 a| 
* Red Hat Enterprise Linux : 7.6, 7.7, 7.8, 7.9, 8.0, 8.1
* CentOS: 7.6, 7.7, 7.8, 7.9


|===
. Compatible signifie que RHEL ne prend plus en charge cette version mais que ONTAP Mediator peut toujours être installé.




== Licences

* Une licence synchrone SnapMirror doit être appliquée aux deux clusters.
* Une licence SnapMirror doit être appliquée aux deux clusters.
+

NOTE: Si vous avez acheté vos systèmes de stockage ONTAP avant juin 2019, consultez la page link:https://mysupport.netapp.com/site/systems/master-license-keys["Clés de licence principales pour ONTAP NetApp"^] Pour obtenir la licence synchrone SnapMirror requise.





== Environnement de mise en réseau

* Le temps de réponse aller-retour de latence entre clusters doit être inférieur à 10 millisecondes.
* À partir de ONTAP 9.14.1, link:https://kb.netapp.com/onprem/ontap/da/SAN/What_are_SCSI_Reservations_and_SCSI_Persistent_Reservations["Réservations persistantes SCSI-3"] Sont pris en charge avec la synchronisation active SnapMirror.




== Protocoles pris en charge

SnapMirror Active Sync prend en charge les protocoles SAN.

* Les protocoles FC et iSCSI sont pris en charge à partir d' ONTAP 9.9.1.
* Le protocole NVMe est pris en charge avec les charges de travail VMware à partir d' ONTAP 9.17.1.
+

NOTE: NVMe/TCP avec VMware dépend de la résolution de l'ID de bogue VMware : TR1049746.

+
La synchronisation active de SnapMirror ne prend pas en charge les éléments suivants avec le protocole NVMe :

+
** Configurations actives/actives symétriques à 4 nœuds
** Modifications de la taille du groupe de cohérence
+
Vous ne pouvez pas étendre ou réduire un groupe de cohérence lorsque vous utilisez le protocole NVMe avec la synchronisation active SnapMirror .

** La coexistence de LUN et d'espaces de noms dans le même groupe de cohérence n'est pas prise en charge.






== IPspace

L'IPspace par défaut est requis par SnapMirror Active Sync pour les relations entre clusters. L'IPspace personnalisé n'est pas pris en charge.



== Style de sécurité NTFS

La sécurité NTFS est *non* prise en charge sur les volumes SnapMirror actif sync.



== Médiateur de ONTAP

* ONTAP Mediator doit être provisionné en externe et attaché à ONTAP pour un basculement d'application transparent.
* Pour être entièrement fonctionnel et permettre un basculement automatique non planifié, le médiateur ONTAP externe doit être provisionné et configuré avec des clusters ONTAP.
* ONTAP Mediator doit être installé dans un troisième domaine de défaillance, distinct des deux clusters ONTAP.
* Lors de l'installation d'ONTAP Mediator, vous devez remplacer le certificat auto-signé par un certificat valide signé par une autorité de certification fiable et standard.
* Pour plus d'informations sur ONTAP Mediator, consultez link:../mediator/index.html["Préparez-vous à installer ONTAP Mediator"] .




== Autres conditions préalables

* Les relations de synchronisation active SnapMirror ne sont pas prises en charge sur les volumes de destination en lecture-écriture. Avant de pouvoir utiliser un volume en lecture-écriture, vous devez le convertir en volume DP en créant une relation SnapMirror au niveau du volume, puis en supprimant la relation. Pour plus de détails, voir link:convert-active-sync-task.html["Convertir une relation SnapMirror existante en synchronisation active SnapMirror"].
* Les machines virtuelles de stockage utilisant la synchronisation active SnapMirror ne peuvent pas être jointes à Active Directory en tant que client calculé.




== Plus d'informations

* link:https://hwu.netapp.com/["Hardware Universe"^]
* link:../mediator/mediator-overview-concept.html["Présentation du médiateur ONTAP"^]

