---
sidebar: sidebar 
permalink: snapmirror-active-sync/protect-task.html 
keywords: SM-BC, snapmirror business continuity, consistency group, remote protection, destination, scsi, nvme 
summary: 'La configuration de la protection pour la continuité de l"activité implique de sélectionner des LUN sur le cluster ONTAP source et de les ajouter à un groupe de cohérence.' 
---
= Protégez avec la synchronisation active ONTAP SnapMirror
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
La synchronisation active SnapMirror offre une protection asymétrique et, à partir de ONTAP 9.15.1, une protection actif-actif symétrique.



== Configurer la protection asymétrique

Configurer la protection asymétrique à l'aide de SnapMirror Active Sync implique de sélectionner des LUN sur le cluster source ONTAP et de les ajouter à un groupe de cohérence.

.Avant de commencer
* Vous devez disposer d'une licence SnapMirror synchrone.
* Vous devez être un administrateur de cluster ou de machines virtuelles de stockage.
* Tous les volumes constitutifs d'un groupe de cohérence doivent se trouver dans une seule VM de stockage (SVM).
+
** Les LUN peuvent résider sur des volumes différents.


* Le cluster source et le cluster destination ne peuvent pas être identiques.
* Vous ne pouvez pas établir de relations de groupe de cohérence avec la synchronisation active SnapMirror entre les clusters ASA et les clusters non-ASA.
* L'IPspace par défaut est requis par SnapMirror Active Sync pour les relations entre clusters. L'IPspace personnalisé n'est pas pris en charge.
* Le nom du groupe de cohérence doit être unique.
* Les volumes du cluster secondaire (destination) doivent être de type DP.
* Les SVM primaire et secondaire doivent être en relation de peering.


.Étapes
Vous pouvez configurer un groupe de cohérence via l'interface de ligne de commandes ONTAP ou System Manager.

À partir d' ONTAP 9.10.1, ONTAP propose un point de terminaison et un menu de groupe de cohérence dans System Manager, offrant des utilitaires de gestion supplémentaires. Si vous utilisez ONTAP 9.10.1 ou une version ultérieure, consultez la section link:../consistency-groups/configure-task.html["Configurer un groupe de cohérence"] alors link:../consistency-groups/protect-task.html["configurer la protection"] pour créer une relation de synchronisation active SnapMirror .


IMPORTANT: De ONTAP 9.14.1 à 9.8, la synchronisation active SnapMirror est appelée SnapMirror Business Continuity (SM-BC).

[role="tabbed-block"]
====
.System Manager
--
. Sur le cluster principal, accédez à *protection > Présentation > protéger pour la continuité de l'activité > protéger les LUN*.
. Sélectionnez les LUN que vous souhaitez protéger et ajoutez-les à un groupe de protection.
. Sélectionner le cluster de destination et le SVM.
. *Initialize relation* est sélectionné par défaut. Cliquez sur *Save* pour commencer la protection.
. Accédez à *Tableau de bord > performances* pour vérifier l'activité IOPS des LUN.
. Sur le cluster de destination, utilisez System Manager pour vérifier que la protection de la relation de continuité de l'activité est en mode synchrone : *protection > relations*.


--
.CLI
--
. Créez une relation de groupe de cohérence à partir du cluster destination.
`destination::> snapmirror create -source-path _source-path_ -destination-path _destination-path_ -cg-item-mappings _volume-paths_ -policy _policy-name_`
+
Vous pouvez mapper jusqu'à 12 volumes constitutifs à l'aide du `cg-item-mappings` sur le `snapmirror create` commande.

+
La création de deux groupes de cohérence dans l'exemple suivant : `cg_src_ on the source with `vol1` et `vol2` et un groupe de cohérence de destination en miroir, `cg_dst`.

+
`destination::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol_src1:@vol_dst1,vol_src2:@vol_dst2 -policy AutomatedFailOver`

. Depuis le cluster de destination, initialisez le groupe de cohérence.
+
`destination::>snapmirror initialize -destination-path _destination-consistency-group_`

. Confirmer que l'opération d'initialisation a réussi. Le statut doit être de `InSync`.
+
`snapmirror show`

. Sur chaque cluster, créez un groupe initiateur afin de mapper les LUN sur l'initiateur de l'hôte d'application.
`lun igroup create -igroup _name_ -protocol _fcp|iscsi_ -ostype _os_ -initiator _initiator_name_`
+
Pour en savoir plus, `lun igroup create` consultez le link:https://docs.netapp.com/us-en/ontap-cli/lun-igroup-create.html["Référence de commande ONTAP"^].

. Sur chaque cluster, mappez les LUN sur le groupe initiateur :
+
`lun map -path _path_name_ -igroup _igroup_name_`

. Vérifiez que le mappage de LUN a réussi avec le `lun map` commande. Vous pouvez ensuite détecter les nouveaux LUN sur l'hôte d'application.


--
====


== Configurer la protection actif-actif symétrique

Vous pouvez établir une protection symétrique à l'aide de System Manager ou de l'interface de ligne de commande de ONTAP. Dans les deux interfaces, il existe différentes étapes pour xref:index.html#key-concepts[configurations uniformes et non uniformes].

.Avant de commencer
* Les deux clusters doivent exécuter ONTAP 9.15.1 ou une version ultérieure.
* Les configurations actif-actif symétriques nécessitent le `AutomatedFailoverDuplex` règles de protection. Sinon, vous pouvez xref:../data-protection/create-custom-replication-policy-concept.html[Créez une règle SnapMirror personnalisée] a condition que le `-type` est `automated-failover-duplex`.
* Dans ONTAP 9.15.1, le mode actif-actif symétrique n'est pris en charge que sur les clusters à 2 nœuds.
* Depuis la version ONTAP 9.16.1 GA, la synchronisation active SnapMirror prend en charge les configurations actif-actif symétriques sur les clusters à quatre nœuds.
+
** Pour utiliser la synchronisation active SnapMirror sur un cluster à quatre nœuds, vous devez exécuter ONTAP 9.16.1 GA ou une version ultérieure.
** Avant de déployer une configuration à quatre nœuds, vous devez xref:../peering/create-cluster-relationship-93-later-task.adoc[créez une relation entre clusters].
** Vérifiez les xref:limits-reference.adoc[limites] pour les clusters à quatre nœuds.
** Si vous revenez à un cluster à deux nœuds, vous devez supprimer les relations de synchronisation active SnapMirror du cluster avant le rétablissement.
** Vous pouvez utiliser la configuration à quatre nœuds pour mettre à niveau les contrôleurs et le stockage. Ce processus n'engendre aucune interruption et étend le cluster tout en déplaçant les volumes vers les nouveaux nœuds. Pour plus d'informations, voir link:upgrade-revert-task.html#refresh-a-cluster["actualiser un cluster"].


* À partir d' ONTAP 9.17.1, vous pouvez configurer une protection symétrique active/active sur les espaces de noms NVMe uniquement lorsque les deux clusters exécutent ONTAP 9.17.1 ou une version ultérieure.




== Configurer une protection symétrique active/active à l'aide d'une configuration de synchronisation active SCSI SnapMirror

.Étapes
Vous pouvez utiliser System Manager ou l'interface de ligne de commande ONTAP pour configurer la protection symétrique active/active à l'aide des mappages d'hôtes du protocole SCSI.

[role="tabbed-block"]
====
.System Manager
--
.Étapes pour une configuration uniforme
. Sur le site principal, link:../consistency-groups/configure-task.html#create-a-consistency-group-with-new-luns-or-volumes["Créez un groupe de cohérence à l'aide des nouvelles LUN."^]
+
.. Lors de la création du groupe de cohérence, spécifiez les initiateurs hôtes à créer des igroups.
.. Cochez la case **Activer SnapMirror** puis choisissez le `AutomatedFailoverDuplex` politique.
.. Dans la boîte de dialogue qui s'affiche, cochez la case **répliquer les groupes initiateurs** pour répliquer les groupes initiateurs. Dans **Modifier les paramètres de proximité**, définissez les SVM proximales pour vos hôtes.
.. Sélectionnez **Enregistrer**.




.Étapes d'une configuration non uniforme
. Sur le site principal, link:../consistency-groups/configure-task.html#create-a-consistency-group-with-new-luns-or-volumes["Créez un groupe de cohérence à l'aide des nouvelles LUN."^]
+
.. Lors de la création du groupe de cohérence, spécifiez les initiateurs hôtes à créer des igroups.
.. Cochez la case **Activer SnapMirror** puis choisissez le `AutomatedFailoverDuplex` politique.
.. Sélectionnez **Save** pour créer les LUN, le groupe de cohérence, le groupe initiateur, la relation SnapMirror et le mappage des groupes initiateur.


. Sur le site secondaire, créez un groupe initiateur et mappez les LUN.
+
.. Accédez à **hosts** > **SAN Initiator Groups**.
.. Sélectionnez **+Ajouter** pour créer un nouveau groupe initiateur.
.. Indiquez un **Nom**, sélectionnez le **système d'exploitation hôte**, puis choisissez **membres du groupe initiateur**.
.. Sélectionnez **Enregistrer** pour initialiser la relation.


. Mappez le nouveau groupe initiateur sur les LUN de destination.
+
.. Accédez à **stockage** > **LUN**.
.. Sélectionnez toutes les LUN à mapper sur le groupe initiateur.
.. Sélectionnez **plus** puis **Mapper sur les groupes initiateurs**.




--
.CLI
--
.Étapes pour une configuration uniforme
. Créez une nouvelle relation SnapMirror regroupant tous les volumes de l'application. Assurez-vous de désigner le `AutomatedFailOverDuplex` règle d'établissement de la réplication synchrone bidirectionnelle.
+
`snapmirror create -source-path <source_path> -destination-path <destination_path> -cg-item-mappings <source_volume:@destination_volume> -policy AutomatedFailOverDuplex`

+
Exemple : l’exemple suivant crée deux groupes de cohérence : cg_src sur la source avec vol1 et vol2, et un groupe de cohérence en miroir sur la destination, cg_dst.

+
[listing]
----
destination::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol_src1:@vol_dst1,vol_src2:@vol_dst2 -policy AutomatedFailOver
----
. Initialiser la relation SnapMirror :
`snapmirror initialize -destination-path <destination-consistency-group>`
. Confirmer que l'opération a réussi en attendant le `Mirrored State` pour afficher sous `SnapMirrored` et le `Relationship Status` comme `Insync`.
+
`snapmirror show -destination-path <destination_path>`

. Sur votre hôte, configurez la connectivité hôte avec l'accès à chaque cluster en fonction de vos besoins.
. Établissement de la configuration du groupe initiateur. Définissez les chemins d'accès préférés des initiateurs sur le cluster local. Spécifiez l'option permettant de répliquer la configuration sur le cluster homologue pour l'affinité inverse.
+
`SiteA::> igroup create -vserver <svm_name> -ostype <os_type> -igroup <igroup_name> -replication-peer <peer_svm_name> -initiator <host>`

+

NOTE: Depuis ONTAP 9.16.1, utilisez le `-proximal-vserver local` paramètre dans cette commande.

+
`SiteA::> igroup add -vserver <svm_name> -igroup <igroup_name> -ostype <os_type> -initiator <host>`

+

NOTE: Depuis ONTAP 9.16.1, utilisez le `-proximal-vserver peer` paramètre dans cette commande.

. Depuis l'hôte, détectez les chemins et vérifiez que les hôtes disposent d'un chemin actif/optimisé vers la LUN de stockage à partir du cluster préféré.
. Déployez l'application et distribuez les charges de travail des machines virtuelles entre les clusters pour atteindre l'équilibrage de charge requis.


.Étapes d'une configuration non uniforme
. Créez une nouvelle relation SnapMirror regroupant tous les volumes de l'application. Assurez-vous de désigner le `AutomatedFailOverDuplex` règle d'établissement de la réplication synchrone bidirectionnelle.
+
`snapmirror create -source-path <source_path> -destination-path <destination_path> -cg-item-mappings <source_volume:@destination_volume> -policy AutomatedFailOverDuplex`

+
Exemple : l’exemple suivant crée deux groupes de cohérence : cg_src sur la source avec vol1 et vol2, et un groupe de cohérence en miroir sur la destination, cg_dst.

+
[listing]
----
destination::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol_src1:@vol_dst1,vol_src2:@vol_dst2 -policy AutomatedFailOver
----
. Initialiser la relation SnapMirror :
`snapmirror initialize -destination-path <destination-consistency-group>`
. Confirmer que l'opération a réussi en attendant le `Mirrored State` pour afficher sous `SnapMirrored` et le `Relationship Status` comme `Insync`.
+
`snapmirror show -destination-path <destination_path>`

. Sur votre hôte, configurez la connectivité hôte avec l'accès à chaque cluster en fonction de vos besoins.
. Établissement des configurations de groupe initiateur sur le cluster source et le cluster destination
+
`# primary site
SiteA::> igroup create -vserver <svm_name> -igroup <igroup_name> -initiator <host_1_name_>`

+
`# secondary site
SiteB::> igroup create -vserver <svm_name> -igroup <igroup_name> -initiator <host_2_name>`

. Depuis l'hôte, détectez les chemins et vérifiez que les hôtes disposent d'un chemin actif/optimisé vers la LUN de stockage à partir du cluster préféré.
. Déployez l'application et distribuez les charges de travail des machines virtuelles entre les clusters pour atteindre l'équilibrage de charge requis.


--
====


== Configurer une protection symétrique active/active à l'aide d'une configuration de synchronisation active NVMe SnapMirror

.Avant de commencer
Outre les exigences de configuration de la protection symétrique active/active, vous devez connaître les configurations prises en charge et non prises en charge lors de l'utilisation du protocole NVMe.

* Les groupes de cohérence peuvent avoir un ou plusieurs sous-systèmes.
* Les volumes au sein du groupe de cohérence peuvent avoir des cartes d’espace de noms provenant de plusieurs sous-systèmes.
* Les sous-systèmes ne peuvent pas avoir de cartes d’espace de noms appartenant à plusieurs groupes de cohérence.
* Les sous-systèmes ne peuvent pas avoir des cartes d’espace de noms appartenant à un groupe de cohérence et des cartes d’espace de noms n’appartenant pas à un groupe de cohérence.
* Les sous-systèmes doivent avoir des cartes d’espace de noms qui font partie du même groupe de cohérence.


.Étapes
À partir d' ONTAP 9.17.1, vous pouvez utiliser System Manager ou l'interface de ligne de commande ONTAP pour créer un groupe de cohérence et configurer une protection active/active symétrique à l'aide de mappages d'hôtes de protocole NVMe.

[role="tabbed-block"]
====
.System Manager
--
. Sur le site principal, link:../consistency-groups/configure-task.html#create-a-consistency-group-with-new-luns-or-volumes["créer un groupe de cohérence à l'aide de nouveaux volumes ou d'espaces de noms NVMe."^]
. sélectionnez *+Ajouter* et choisissez *Utiliser les nouveaux espaces de noms NVMe*.
. Entrez le nom du groupe de cohérence.
. Sélectionnez *Plus*.
. Dans la section *Protection*, sélectionnez *Activer SnapMirror* puis choisissez l'option  `AutomatedFailoverDuplex` politique.
. Dans la section *Mappage d'hôte*, choisissez *Sous-système NVMe existant* ou *Nouveau sous-système NVMe*.
. Sélectionnez « À proximité de » pour modifier la SVM proximale. La SVM source est sélectionnée par défaut.
. Si nécessaire, ajoutez un autre sous-système NVMe.


--
.CLI
--
. Créez une nouvelle relation SnapMirror regroupant tous les volumes contenant tous les espaces de noms NVMe utilisés par l'application. Assurez-vous de désigner le  `AutomatedFailOverDuplex` politique visant à établir une réplication de synchronisation bidirectionnelle.
+
`snapmirror create -source-path <source_path> -destination-path <destination_path> -cg-item-mappings <source_volume:@destination_volume> -policy AutomatedFailOverDuplex`

+
Exemple :

+
[listing]
----
DST::> snapmirror create -source-path vs_src:/cg/cg_src_1 -destination-path vs_dst:/cg/cg_dst_1 -cg-item-mappings vs_src_vol1:@vs_dst_vol1,vs_src_vol2:@vs_dst_vol2 -policy AutomatedFailOverDuplex
----
. Initialiser la relation SnapMirror :
`snapmirror initialize -destination-path <destination-consistency-group>`
+
Exemple :

+
[listing]
----
DST::> snapmirror initialize -destination-path vs1:/cg/cg_dst_1
----
. Confirmer que l'opération a réussi en attendant le `Mirrored State` pour afficher sous `SnapMirrored` et le `Relationship Status` comme `Insync`.
+
`snapmirror show -destination-path <destination_path>`

+
Les sous-systèmes NVMe associés aux espaces de noms NVMe dans les volumes principaux sont automatiquement répliqués sur le cluster secondaire.

. Sur votre hôte, configurez la connectivité hôte avec l'accès à chaque cluster en fonction de vos besoins.
. Spécifiez la SVM la plus proche de chacun de vos hôtes. Cela permet à l'hôte d'accéder à l'espace de noms NVMe via un chemin d'accès depuis le cluster préféré. Il peut s'agir de la SVM du cluster principal ou de celle du cluster de reprise après sinistre.
+
La commande suivante indique que la SVM VS_A est proche de l'hôte H1 et définit VS_A comme SVM proximale :

+
`SiteA::> vserver nvme subsystem host add -subsystem ss1 -host-nqn <H1_NQN> -proximal-vservers <VS_A>`

+
La commande suivante indique que la SVM VS_B est proche de l'hôte H2 et définit VS_B comme la SVM proximale :

+
`SiteB::> vserver nvme subsystem host add -subsystem ss1 -host-nqn <H2_NQN> -proximal-vservers <VS_B>`

. Depuis l'hôte, découvrez les chemins et vérifiez que les hôtes disposent d'un chemin actif/optimisé vers le stockage à partir du cluster préféré.
. Déployez l'application et distribuez les charges de travail des machines virtuelles entre les clusters pour atteindre l'équilibrage de charge requis.


--
====
.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["création snapmirror"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["initialisation snapmirror"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["spectacle snapmirror"^]

