---
sidebar: sidebar 
permalink: snapmirror-active-sync/remove-mediator-task.html 
keywords: SM-BC, SMBC, removing, uninstalling, Mediator, Cloud Mediator, snapmirror active sync 
summary: 'Si vous souhaitez supprimer une configuration ONTAP Mediator ou ONTAP Cloud Mediator existante de vos clusters ONTAP , vous pouvez le faire à l"aide de la commande snapmirror mediator remove.' 
---
= Supprimer ONTAP Mediator ou ONTAP Cloud Mediator
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Si vous souhaitez supprimer une configuration ONTAP Mediator ou ONTAP Cloud Mediator existante de vos clusters ONTAP , vous pouvez le faire à l'aide de l'  `snapmirror mediator remove` commande. Par exemple, vous ne pouvez utiliser qu'un seul type de médiateur à la fois ; vous devez donc supprimer une instance avant d'installer l'autre.

.Étapes
Vous pouvez supprimer ONTAP Mediator ou ONTAP Cloud Mediator en effectuant l’une des étapes suivantes.

[role="tabbed-block"]
====
.Médiateur de ONTAP
--
. Supprimer un médiateur ONTAP :
+
`snapmirror mediator remove -mediator-address <address> -peer-cluster <peerClusterName>`

+
Exemple :

+
[listing]
----
snapmirror mediator remove -mediator-address 12.345.678.90 -peer-cluster cluster_xyz
----


--
.Médiateur cloud ONTAP
--
. Supprimer ONTAP Cloud Mediator :
+
`snapmirror mediator remove -peer-cluster <peerClusterName> -type cloud`

+
Exemple :

+
[listing]
----
snapmirror mediator remove -peer-cluster cluster_xyz -type cloud
----


--
====
.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-mediator-remove.html["supprimer le médiateur SnapMirror"^]

