---
sidebar: sidebar 
permalink: snapmirror-active-sync/volume-move-stuck-task.html 
keywords: SM-BC, SMBC, volume move, troubleshooting, primary down, snapmirror active sync 
summary: Vous pouvez supprimer la protection synchrone de SnapMirror avec objectif RTO nul et supprimer la configuration de la relation de synchronisation active SnapMirror. 
---
= Opération de déplacement de volume bloquée lorsque le volume principal est en baisse
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Utilisez les informations suivantes si une opération de déplacement de volume est bloquée indéfiniment dans un état de basculement différé lorsque le site principal est en panne dans une relation de synchronisation active SnapMirror .

.Problème :
Une opération de déplacement de volume est bloquée indéfiniment dans un état de mise en service différée lorsque le site principal est en panne dans une relation de synchronisation active SnapMirror.
Lorsque le site principal est en panne, le site secondaire effectue un basculement automatique non planifié (AUFO). Lorsqu'une opération de déplacement de volume est en cours lorsque l'AUFO est déclenché, le déplacement de volume devient bloqué.

.Solution :
Interrompez l'instance de déplacement de volume bloquée et redémarrez l'opération de déplacement de volume.
