---
permalink: smb-hyper-v-sql/determine-statistics-objects-counters-task.html 
sidebar: sidebar 
keywords: determine, statistics, objects, counters, cifs, smb, audit, branchcache, hash, monitor, performance 
summary: 'Avant d"obtenir des informations sur les statistiques de hachage CIFS, SMB, d"audit et de BranchCache, ainsi que sur les performances, vous devez connaître les objets et compteurs disponibles, à partir desquels vous pouvez obtenir des données.' 
---
= Déterminez les objets statistiques et les compteurs disponibles dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'obtenir des informations sur les statistiques de hachage CIFS, SMB, d'audit et de BranchCache, ainsi que sur les performances, vous devez connaître les objets et compteurs disponibles, à partir desquels vous pouvez obtenir des données.

.Étapes
. Définissez le niveau de privilège sur avancé :
+
`set -privilege advanced`

. Effectuez l'une des opérations suivantes :
+
|===
| Si vous voulez déterminer... | Entrer... 


 a| 
Les objets disponibles
 a| 
`statistics catalog object show`



 a| 
Objets spécifiques disponibles
 a| 
`statistics catalog object show -object _object_name_`



 a| 
Quels compteurs sont disponibles
 a| 
`statistics catalog counter show -object _object_name_`

|===
+
En savoir plus sur  `statistics catalog object show` et  `statistics catalog counter show` dans le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=statistics+catalog["Référence de commande ONTAP"^] .

. Retour au niveau de privilège admin :
+
`set -privilege admin`



.Exemples
La commande suivante affiche la description des objets statistiques sélectionnés relatifs à l'accès CIFS et SMB au cluster, comme s'il s'affiche au niveau de privilège avancé :

[listing]
----
cluster1::> set -privilege advanced

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by support personnel.
Do you want to continue? {y|n}: y

cluster1::*> statistics catalog object show -object audit
    audit_ng                    CM object for exporting audit_ng performance counters

cluster1::*> statistics catalog object show -object cifs
    cifs                        The CIFS object reports activity of the
                                Common Internet File System protocol
                                ...

cluster1::*> statistics catalog object show -object nblade_cifs
    nblade_cifs                 The Common Internet File System (CIFS)
                                protocol is an implementation of the Server
                                ...

cluster1::*> statistics catalog object show -object smb1
    smb1                        These counters report activity from the SMB
                                revision of the protocol. For information
                                ...

cluster1::*> statistics catalog object show -object smb2
    smb2                        These counters report activity from the
                                SMB2/SMB3 revision of the protocol. For
                                ...

cluster1::*> statistics catalog object show -object hashd
    hashd                       The hashd object provides counters to measure
                                the performance of the BranchCache hash daemon.
cluster1::*> set -privilege admin
----
La commande suivante affiche des informations sur certains compteurs de `cifs` objet tel qu'il apparaît au niveau de privilège avancé :

[NOTE]
====
Cet exemple n'affiche pas tous les compteurs disponibles pour le `cifs` objet ; la sortie est tronquée.

====
[listing]
----
cluster1::> set -privilege advanced

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by support personnel.
Do you want to continue? {y|n}: y

cluster1::*> statistics catalog counter show -object cifs

Object: cifs
    Counter                     Description
    --------------------------- ----------------------------------------------
    active_searches             Number of active searches over SMB and SMB2
    auth_reject_too_many        Authentication refused after too many
                                requests were made in rapid succession
    avg_directory_depth         Average number of directories crossed by SMB
                                and SMB2 path-based commands
    ...                         ...

cluster2::> statistics start -object client -sample-id
Object: client
    Counter                                                     Value
    -------------------------------- --------------------------------
    cifs_ops                                                        0
    cifs_read_ops                                                   0
    cifs_read_recv_ops                                              0
    cifs_read_recv_size                                            0B
    cifs_read_size                                                 0B
    cifs_write_ops                                                  0
    cifs_write_recv_ops                                             0
    cifs_write_recv_size                                           0B
    cifs_write_size                                                0B
    instance_name                             vserver_1:10.72.205.179
    instance_uuid                                     2:10.72.205.179
    local_ops                                                       0
    mount_ops                                                       0


[...]
----
Pour en savoir plus, `statistics start` consultez le link:https://docs.netapp.com/us-en/ontap-cli/statistics-start.html["Référence de commande ONTAP"^].
