---
permalink: smb-hyper-v-sql/nondisruptive-operations-glossary-concept.html 
sidebar: sidebar 
keywords: key, concepts, nondisruptive, operation, hyper, v, sql, server, smb, configure 
summary: 'Avant de configurer la solution Hyper-V ou SQL Server sur SMB, certains concepts relatifs à la continuité de l"activité doivent être abordés.' 
---
= Concepts clés de la continuité de l'activité pour Hyper-V et SQL Server sur SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de configurer la solution Hyper-V ou SQL Server sur SMB, certains concepts relatifs à la continuité de l'activité doivent être abordés.

* *Partage disponible en continu*
+
Partage SMB 3.0 avec la propriété de partage disponible en continu. Les clients qui se connectent via des partages disponibles en permanence peuvent survivre aux événements perturbateur tels que le basculement, le rétablissement et le transfert d'agrégats.

* *Nœud*
+
Un contrôleur unique membre d'un cluster. Pour faire la distinction entre les deux nœuds d'une paire SFO, un nœud est parfois appelé _local node_ et l'autre nœud est parfois appelé _Partner node_ ou _remote node_. Le propriétaire principal du stockage est le nœud local. Le propriétaire secondaire, qui prend le contrôle du stockage en cas de défaillance du propriétaire principal, est le nœud partenaire. Chaque nœud est le principal propriétaire de son stockage et du secondaire pour le stockage de son partenaire.

* *Transfert d'agrégats sans interruption*
+
Capacité à déplacer un agrégat entre les nœuds partenaires au sein d'une paire SFO dans un cluster sans interrompre les applications client.

* *Basculement sans interruption*
+
Voir _Takeover_.

* *Migration de LIF sans interruption*
+
La possibilité d'effectuer une migration de LIF sans interrompre les applications client qui sont connectées au cluster via cette LIF. Pour les connexions SMB, cette opération est uniquement possible pour les clients qui se connectent via SMB 2.0 ou version ultérieure.

* * Continuité de l'activité*
+
La possibilité d'effectuer les principales opérations de gestion et de mise à niveau ONTAP, et de résister aux défaillances de nœud sans interrompre les applications client. Ce terme fait référence à la collecte de fonctionnalités de basculement sans interruption, de mise à niveau sans interruption et de migration dans son ensemble.

* * Mise à niveau sans interruption*
+
Capacité à mettre à niveau le matériel ou les logiciels des nœuds sans perturber les applications.

* *Déplacement de volume sans interruption*
+
La capacité de déplacer librement un volume au sein du cluster sans interrompre les applications qui utilisent ce volume. Pour les connexions SMB, toutes les versions de SMB prennent en charge le déplacement de volumes sans interruption.

* *Poignées permanentes*
+
Propriété de SMB 3.0 qui permet aux connexions disponibles en continu de se reconnecter de façon transparente au serveur CIFS en cas de déconnexion. Tout comme les poignées durables, les poignées permanentes sont conservées par le serveur CIFS pendant un certain temps après la perte de la communication avec le client connecté. Toutefois, les pointeurs permanents bénéficient d'une résilience supérieure à celle des poignées durables. En plus de donner au client la possibilité de récupérer la poignée dans une fenêtre de 60 secondes après reconnexion, le serveur CIFS refuse l'accès à tout autre client demandant l'accès au fichier pendant cette fenêtre de 60 secondes.

+
Des informations relatives aux pointeurs permanents sont mises en miroir sur le stockage persistant du partenaire SFO, qui permet aux clients disposant de pointeurs permanents déconnectés de récupérer les pointeurs durables après un événement où le partenaire SFO est propriétaire du stockage du nœud. En plus d'assurer la continuité de l'activité en cas de déplacement de LIF (dont la prise en charge est durable), des pointeurs permanents assurent la continuité de l'activité pendant le basculement, le rétablissement et le transfert d'agrégats.

* *OFS-retour*
+
Retour d'agrégats à leurs locaux lors d'une récupération après un événement de basculement.

* *Paire SFO*
+
Si l'un des deux nœuds cesse de fonctionner, une paire de nœuds dont les contrôleurs sont configurés pour transmettre des données les uns aux autres. Selon le modèle du système, les deux contrôleurs peuvent se trouver dans un seul châssis ou les contrôleurs peuvent se trouver dans un châssis distinct. Appelé paire HA dans un cluster à deux nœuds.

* * Prise de contrôle*
+
Processus par lequel le partenaire prend le contrôle du stockage en cas de défaillance du propriétaire principal de ce stockage. Dans le cadre du SFO, le basculement et le basculement sont synonymes.


