---
permalink: smb-hyper-v-sql/remote-vss-concepts-concept.html 
sidebar: sidebar 
keywords: remove, vss, concepts, volume, shadow, copy, service, hyper, v, smb, configuration 
summary: 'Vous devez connaître certains concepts requis pour comprendre l"utilisation de VSS distant (Volume Shadow Copy Service) par les services de sauvegarde avec des configurations Hyper-V sur SMB.' 
---
= Concepts de VSS distant
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez connaître certains concepts requis pour comprendre l'utilisation de VSS distant (Volume Shadow Copy Service) par les services de sauvegarde avec des configurations Hyper-V sur SMB.

* *VSS (Volume Shadow Copy Service)*
+
Technologie Microsoft utilisée pour effectuer des copies de sauvegarde ou des snapshots de données sur un volume spécifique à un point dans le temps spécifique. VSS coordonne entre les serveurs de données, les applications de sauvegarde et les logiciels de gestion du stockage afin d'assurer la création et la gestion de sauvegardes cohérentes.

* *VSS distant (Remote Volume Shadow Copy Service)*
+
Technologie Microsoft utilisée pour créer des copies de sauvegarde basées sur les partages de données qui sont cohérentes avec les données à un point spécifique dans le temps où les données sont accessibles via les partages SMB 3.0. Également connu sous le nom _Volume Shadow Copy Service_.

* *Copie fantôme*
+
Un jeu de données dupliqué contenu dans le partage à un instant bien défini dans le temps. Des clichés instantanés sont utilisés pour créer des sauvegardes ponctuelles cohérentes des données, permettant ainsi au système ou aux applications de continuer à mettre à jour les données sur les volumes d'origine.

* *Ensemble de copies ombré*
+
Collection d'une ou plusieurs clichés instantanés, chaque copie fantôme correspondant à un partage. Les clichés instantanés dans un jeu de clichés instantanés représentent tous les partages qui doivent être sauvegardés dans la même opération. Le client VSS de l'application VSS-enabled identifie les clichés instantanés à inclure dans l'ensemble.

* *Shadow Copy set Automatic Recovery*
+
La partie du processus de sauvegarde pour les applications de sauvegarde VSS distantes dans lesquelles le répertoire de réplica contenant les clichés instantanés est cohérent à un point dans le temps. Au début de la sauvegarde, le client VSS de l'application déclenche l'application pour qu'elle prenne des points de contrôle logiciels sur les données planifiées pour la sauvegarde (les fichiers de la machine virtuelle dans le cas d'Hyper-V). Le client VSS autorise alors les applications à continuer. Une fois le jeu de clichés instantanés créé, Remote VSS rend le jeu de clichés instantanés inscriptible et expose la copie inscriptible aux applications. L'application prépare le jeu de clichés instantanés pour la sauvegarde en effectuant une restauration automatique à l'aide du point de contrôle du logiciel précédemment effectué. La récupération automatique place les clichés instantanés dans un état cohérent en détournant les modifications apportées aux fichiers et répertoires depuis la création du point de contrôle. La restauration automatique est une étape facultative pour les sauvegardes VSS.

* *ID de copie fantôme*
+
GUID qui identifie de manière unique une copie en double.

* *ID jeu de copies ombré*
+
GUID qui identifie de manière unique une collection d'ID de copie en double sur le même serveur.

* *SnapManager pour Hyper-V*
+
Logiciel qui automatise et simplifie les opérations de sauvegarde et de restauration pour Microsoft Windows Server 2012 Hyper-V. SnapManager for Hyper-V utilise VSS distant avec restauration automatique pour sauvegarder des fichiers Hyper-V sur des partages SMB.



xref:nondisruptive-operations-glossary-concept.adoc[Concepts clés de la continuité de l'activité pour Hyper-V et SQL Server sur SMB]

xref:share-based-backups-remote-vss-concept.adoc[Partage de sauvegardes avec VSS distant]
