---
permalink: smb-hyper-v-sql/share-based-backups-remote-vss-concept.html 
sidebar: sidebar 
keywords: share, based, backups, remote, vss, cif, server, hyper, v, virtual, machine, file 
summary: Vous pouvez utiliser VSS distant pour effectuer des sauvegardes basées sur les partages des fichiers de machines virtuelles Hyper-V stockés sur un serveur CIFS. 
---
= Présentation de VSS distant pour les sauvegardes basées sur le partage
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser VSS distant pour effectuer des sauvegardes basées sur les partages des fichiers de machines virtuelles Hyper-V stockés sur un serveur CIFS.

Microsoft Remote VSS (Volume Shadow Copy Services) est une extension de l'infrastructure Microsoft VSS existante. Avec Remote VSS, Microsoft a étendu l'infrastructure VSS pour prendre en charge la copie Shadow des partages SMB. Les applications serveur telles qu'Hyper-V stockent des fichiers VHD sur des partages de fichiers SMB. Avec ces extensions, il est possible d'effectuer des clichés instantanés cohérents avec les applications pour les machines virtuelles qui stockent des données et des fichiers de configuration sur des partages.
