---
permalink: smb-hyper-v-sql/verify-domain-accounts-map-default-unix-user-task.html 
sidebar: sidebar 
keywords: verfiy, domain, account, default, unix, server, smb, share, user 
summary: 'Hyper-V et SQL Server nécessitent que les comptes d"ordinateurs de domaine soient mappés à un utilisateur UNIX pour l"accès SMB. Il est plus simple de les mapper à l"utilisateur UNIX par défaut.' 
---
= Vérifiez que les comptes de domaine correspondent à l'utilisateur UNIX par défaut dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Hyper-V et SQL Server utilisent des comptes de domaine pour créer des connexions SMB à des partages disponibles en continu. Pour réussir la création de la connexion, le compte d'ordinateur doit être mappé avec un utilisateur UNIX. Le moyen le plus pratique pour y parvenir est de mapper le compte d'ordinateur à l'utilisateur UNIX par défaut.

.Description de la tâche
Hyper-V et SQL Server utilisent les comptes d'ordinateur de domaine pour créer des connexions SMB. En outre, SQL Server utilise un compte d'utilisateur de domaine comme compte de service qui établit également des connexions SMB.

Lorsque vous créez une machine virtuelle de stockage (SVM), ONTAP crée automatiquement l'utilisateur par défaut nommé  `pcuser` (avec un UID de  `65534` ) et le groupe nommé  `pcuser` (avec un GID de  `65534` ), et ajoute l'utilisateur par défaut au  `pcuser` groupe. Si vous configurez une solution Hyper-V sur SMB sur un SVM existant avant de mettre à niveau le cluster vers Data ONTAP 8.2, l'utilisateur et le groupe par défaut risquent de ne pas exister. Dans le cas contraire, vous devez les créer avant de configurer l'utilisateur UNIX par défaut du serveur CIFS.

.Étapes
. Déterminez s'il existe un utilisateur UNIX par défaut :
+
[source, cli]
----
vserver cifs options show -vserver <vserver_name>
----
. Si l'option utilisateur par défaut n'est pas définie, déterminez si un utilisateur UNIX peut être désigné comme utilisateur UNIX par défaut :
+
[source, cli]
----
vserver services unix-user show -vserver <vserver_name>
----
. Si l'option utilisateur par défaut n'est pas définie et qu'aucun utilisateur UNIX ne peut être désigné comme utilisateur UNIX par défaut, créez le groupe par défaut et l'utilisateur UNIX par défaut, puis ajoutez l'utilisateur par défaut au groupe.
+
. Le groupe par défaut reçoit généralement le nom de groupe « pcuser » Le GID attribué au groupe doit être `65534`.

+
.. Créez le groupe par défaut :
+
[source, cli]
----
vserver services unix-group create -vserver <vserver_name> -name pcuser -id 65534
----
.. Créez l'utilisateur par défaut et ajoutez l'utilisateur par défaut au groupe par défaut :
+
[source, cli]
----
vserver services unix-user create -vserver <vserver_name> -user pcuser -id 65534 -primary-gid 65534
----
.. Vérifiez que l'utilisateur par défaut et le groupe par défaut sont correctement configurés :
+
[source, cli]
----
vserver services unix-user show -vserver <vserver_name>
----
+
[source, cli]
----
vserver services unix-group show -vserver <vserver_name> -members
----


. Si l'utilisateur par défaut du serveur CIFS n'est pas configuré, effectuez les opérations suivantes :
+
.. Configurez l'utilisateur par défaut :
+
[source, cli]
----
vserver cifs options modify -vserver <vserver_name> -default-unix-user pcuser
----
.. Vérifiez que l'utilisateur UNIX par défaut est configuré correctement :
+
[source, cli]
----
vserver cifs options show -vserver <vserver_name>
----


. Pour vérifier que le compte de l'ordinateur du serveur d'application correspond correctement à l'utilisateur par défaut, mappez un disque sur un partage résidant sur le SVM et confirmez que l'utilisateur Windows correspond au mappage utilisateur UNIX à l'aide de `vserver cifs session show` commande.
+
Pour en savoir plus, `vserver cifs options` consultez le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs+options["Référence de commande ONTAP"^].



.Exemple
Les commandes suivantes déterminent que l'utilisateur par défaut du serveur CIFS n'est pas défini, mais déterminent que le  `pcuser` utilisateur et  `pcuser` groupe existe. Le  `pcuser` l'utilisateur est affecté comme utilisateur par défaut du serveur CIFS sur SVM vs1.

[listing]
----
cluster1::> vserver cifs options show

Vserver: vs1

  Client Session Timeout : 900
  Default Unix Group     : -
  Default Unix User      : -
  Guest Unix User        : -
  Read Grants Exec       : disabled
  Read Only Delete       : disabled
  WINS Servers           : -



cluster1::> vserver services unix-user show
          User            User   Group  Full
Vserver   Name            ID     ID     Name
--------- --------------- ------ ------ ----------------
vs1       nobody          65535  65535  -
vs1       pcuser          65534  65534  -
vs1       root            0      1      -

cluster1::> vserver services unix-group show -members
Vserver        Name                ID
vs1            daemon              1
       Users: -
vs1            nobody              65535
       Users: -
vs1            pcuser              65534
       Users: -
vs1            root                0
       Users: -

cluster1::> vserver cifs options modify -vserver vs1 -default-unix-user pcuser

cluster1::> vserver cifs options show

Vserver: vs1

  Client Session Timeout : 900
  Default Unix Group     : -
  Default Unix User      : pcuser
  Guest Unix User        : -
  Read Grants Exec       : disabled
  Read Only Delete       : disabled
  WINS Servers           : -
----