---
sidebar: sidebar 
permalink: file-system-analytics/considerations-concept.html 
keywords: file system analytics, performance, SVM 
summary: 'L"analytique du système de fichiers est conçue pour fournir une visibilité sur les volumes contenant des données NAS actives. Son utilisation est soumise à des restrictions.' 
---
= Considérations relatives à l'analytique des systèmes de fichiers
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez connaître les limites d'utilisation et les impacts potentiels sur les performances associés à l'implémentation de File System Analytics.



== Relations protégées par un SVM

Si vous avez activé File System Analytics sur les volumes dont le SVM contient fait partie d'une relation de protection, les données d'analytique ne sont pas répliquées vers le SVM de destination. Si le SVM source doit être resynchronisé dans une opération de restauration, vous devez de nouveau activer manuellement l'analytique sur les volumes souhaités après sa restauration.



== Performances

Dans certains cas, l'activation d'une analytique système de fichiers peut avoir un impact négatif sur les performances lors de la collecte de métadonnées initiale. Cela est généralement le plus fréquemment observé sur les systèmes qui atteignent une utilisation maximale. Pour éviter l'activation de l'analytique sur ces systèmes, vous pouvez utiliser les outils de contrôle des performances de ONTAP System Manager.

Si vous constatez une augmentation notable de la latence, consultez l'article de la base de connaissances link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/High_or_fluctuating_latency_after_turning_on_NetApp_ONTAP_File_System_Analytics["Latence élevée ou variable après l'activation de l'analytique système de fichiers ONTAP de NetApp"^].
