---
sidebar: sidebar 
permalink: file-system-analytics/considerations-concept.html 
keywords: file system analytics, performance, SVM 
summary: 'L"analytique du système de fichiers est conçue pour fournir une visibilité sur les volumes contenant des données NAS actives. Son utilisation est soumise à des restrictions.' 
---
= Considérations relatives à l'analytique des systèmes de fichiers dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez connaître les limites d'utilisation et les impacts potentiels sur les performances associés à l'implémentation de File System Analytics.



== Relations protégées par un SVM

Si vous avez activé File System Analytics sur les volumes dont le SVM contient fait partie d'une relation de protection, les données d'analytique ne sont pas répliquées vers le SVM de destination. Si le SVM source doit être resynchronisé dans une opération de restauration, vous devez de nouveau activer manuellement l'analytique sur les volumes souhaités après sa restauration.



== Performances

Dans certains cas, l'activation d'une analytique système de fichiers peut avoir un impact négatif sur les performances lors de la collecte de métadonnées initiale. Cela est généralement le plus fréquemment observé sur les systèmes qui atteignent une utilisation maximale. Pour éviter l'activation de l'analytique sur ces systèmes, vous pouvez utiliser les outils de contrôle des performances de ONTAP System Manager.

Si vous constatez une augmentation notable de la latence, consultez l'article de la base de connaissances link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/High_or_fluctuating_latency_after_turning_on_NetApp_ONTAP_File_System_Analytics["Latence élevée ou variable après l'activation de l'analytique système de fichiers ONTAP de NetApp"^].



== Considérations relatives à l'analyse

Lorsque vous activez l'analyse de la capacité, ONTAP effectue une analyse d'initialisation pour l'analyse de la capacité. L'analyse accède aux métadonnées de tous les fichiers des volumes pour lesquels l'analyse de capacité est activée. Aucune donnée de fichier n'est lue pendant l'acquisition. Depuis ONTAP 9.14.1, vous pouvez suivre la progression de l'analyse avec l'API REST, dans l'onglet **Explorer** du Gestionnaire système ou avec la `volume analytics show` commande CLI. En cas d'événement d'accélération, ONTAP envoie une notification.

Lorsque vous activez l'analyse du système de fichiers sur un volume, assurez-vous qu'au moins 5 à 8 % de l'espace disponible du volume est libre. Si la taille automatique est activée sur le volume, calculez la taille disponible en fonction de la taille maximale de la croissance automatique. Depuis ONTAP 9.15.1, ONTAP affiche un message d'erreur si l'espace disponible est insuffisant lorsque vous activez l'analyse du système de fichiers sur un volume.

Une fois l'analyse terminée, l'analyse du système de fichiers est continuellement mise à jour en temps réel à mesure que le système de fichiers change.

Le temps requis pour l'analyse est proportionnel au nombre de répertoires et de fichiers sur le volume. Étant donné que l'analyse collecte des métadonnées, la taille du fichier n'a pas d'incidence sur le temps d'analyse.

Pour plus d'informations sur l'acquisition d'initialisation, reportez-vous à la section link:https://www.netapp.com/pdf.html?item=/media/20707-tr-4867.pdf["Tr-4867 : recommandations sur les bonnes pratiques pour l'analytique de système de fichiers"^].



=== Et des meilleures pratiques

Vous devez démarrer l'analyse sur des volumes qui ne partagent pas d'agrégats. Vous pouvez voir quels agrégats hébergent actuellement les volumes à l'aide de la commande :

`volume show -volume _comma-separated-list_of_volumes_ -fields aggr-list`

Pendant l'analyse, les volumes continuent de transmettre le trafic client. Il est recommandé de démarrer l'analyse pendant les périodes où vous prévoyez un trafic client plus faible.

Si le trafic client augmente, il consomme les ressources système et allonge l'analyse.

Depuis ONTAP 9.12.1, vous pouvez interrompre la collecte de données dans System Manager et via l'interface de ligne de commandes ONTAP.

* Si vous utilisez l'interface de ligne de commandes ONTAP :
+
** Vous pouvez interrompre la collecte de données à l'aide de la commande : `volume analytics initialization pause -vserver _svm_name_ -volume _volume_name_`
** Une fois le trafic client ralenti, vous pouvez reprendre la collecte de données à l'aide de la commande : `volume analytics initialization resume -vserver _svm_name_ -volume _volume_name_`


* Si vous utilisez System Manager, dans la vue *Explorer* du menu volume, vous utilisez les boutons *Pause collecte de données* et *reprendre collecte de données* pour gérer l'acquisition.

