---
permalink: antivirus/commands-manage-on-access-policies-reference.html 
sidebar: sidebar 
keywords: commands, manage, on-access, policies 
summary: Vous pouvez modifier, désactiver ou supprimer une stratégie On-Access. Vous pouvez afficher un résumé et les détails de la règle. 
---
= Commandes ONTAP Vscan pour la gestion des politiques d'accès
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier, désactiver ou supprimer une stratégie On-Access. Vous pouvez afficher un résumé et les détails de la règle.

|===


| Les fonctions que vous recherchez... | Saisissez la commande suivante... 


 a| 
Création d'une règle on-Access
 a| 
`vserver vscan on-access-policy create`



 a| 
Modifier une stratégie d'accès
 a| 
`vserver vscan on-access-policy modify`



 a| 
Activez une stratégie on-Access
 a| 
`vserver vscan on-access-policy enable`



 a| 
Désactivez une stratégie on-Access
 a| 
`vserver vscan on-access-policy disable`



 a| 
Supprimez une on-Access policy
 a| 
`vserver vscan on-access-policy delete`



 a| 
Afficher un récapitulatif et des détails d'une stratégie d'accès
 a| 
`vserver vscan on-access-policy show`



 a| 
Ajouter à la liste des chemins à exclure
 a| 
`vserver vscan on-access-policy paths-to-exclude add`



 a| 
Supprimer de la liste des chemins à exclure
 a| 
`vserver vscan on-access-policy paths-to-exclude remove`



 a| 
Afficher la liste des chemins à exclure
 a| 
`vserver vscan on-access-policy paths-to-exclude show`



 a| 
Ajouter à la liste des extensions de fichier à exclure
 a| 
`vserver vscan on-access-policy file-ext-to-exclude add`



 a| 
Supprimer de la liste des extensions de fichier à exclure
 a| 
`vserver vscan on-access-policy file-ext-to-exclude remove`



 a| 
Afficher la liste des extensions de fichier à exclure
 a| 
`vserver vscan on-access-policy file-ext-to-exclude show`



 a| 
Ajouter à la liste des extensions de fichier à inclure
 a| 
`vserver vscan on-access-policy file-ext-to-include add`



 a| 
Supprimer de la liste des extensions de fichier à inclure
 a| 
`vserver vscan on-access-policy file-ext-to-include remove`



 a| 
Afficher la liste des extensions de fichier à inclure
 a| 
`vserver vscan on-access-policy file-ext-to-include show`

|===
Pour en savoir plus sur les commandes décrites dans cette procédurelink:https://docs.netapp.com/us-en/ontap-cli/["Référence de commande ONTAP"^], reportez-vous à la .
