---
permalink: antivirus/commands-manage-on-demand-tasks-reference.html 
sidebar: sidebar 
keywords: commands, manage, on-demand, tasks 
summary: 'Vous pouvez modifier, supprimer ou annuler la planification d"une tâche à la demande. Vous pouvez afficher un résumé et des détails de la tâche et gérer les rapports de la tâche.' 
---
= Commandes permettant de gérer des tâches à la demande
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier, supprimer ou annuler la planification d'une tâche à la demande. Vous pouvez afficher un résumé et des détails de la tâche et gérer les rapports de la tâche.

|===


| Les fonctions que vous recherchez... | Saisissez la commande suivante... 


 a| 
Créer une tâche à la demande
 a| 
`vserver vscan on-demand-task create`



 a| 
Modifier une tâche à la demande
 a| 
`vserver vscan on-demand-task modify`



 a| 
Supprimer une tâche à la demande
 a| 
`vserver vscan on-demand-task delete`



 a| 
Exécutez une tâche à la demande
 a| 
`vserver vscan on-demand-task run`



 a| 
Planifiez une tâche à la demande
 a| 
`vserver vscan on-demand-task schedule`



 a| 
Annulez la planification d'une tâche à la demande
 a| 
`vserver vscan on-demand-task unschedule`



 a| 
Consultez le récapitulatif des tâches à la demande et les détails correspondant
 a| 
`vserver vscan on-demand-task show`



 a| 
Consultez les rapports à la demande
 a| 
`vserver vscan on-demand-task report show`



 a| 
Supprimer des rapports à la demande
 a| 
`vserver vscan on-demand-task report delete`

|===
Pour en savoir plus sur les commandes décrites dans cette procédurelink:https://docs.netapp.com/us-en/ontap-cli/["Référence de commande ONTAP"^], reportez-vous à la .
