---
permalink: antivirus/create-on-access-policy-task.html 
sidebar: sidebar 
keywords: create, on-access, policy, wildcards 
summary: 'Une règle On-Access définit l"étendue d"une analyse on-Access. On peut créer une on-Access policy pour un SVM individuel ou pour tous les SVM d"un cluster. Si vous avez créé une on-Access policy pour tous les SVM d"un cluster, vous devez activer la politique sur chaque SVM individuellement.' 
---
= Créer des politiques d'accès ONTAP Vscan
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une règle On-Access définit l'étendue d'une analyse on-Access. On peut créer une on-Access policy pour un SVM individuel ou pour tous les SVM d'un cluster. Si vous avez créé une on-Access policy pour tous les SVM d'un cluster, vous devez activer la politique sur chaque SVM individuellement.

.Description de la tâche
* Vous pouvez spécifier la taille maximale du fichier à numériser, les extensions de fichier et les chemins à inclure dans la numérisation, ainsi que les extensions de fichier et les chemins à exclure de la numérisation.
* Vous pouvez définir le `scan-mandatory` Option désactivée pour spécifier que l'accès aux fichiers est autorisé lorsqu'aucun serveur Vscan n'est disponible pour l'analyse antivirus.
* Par défaut, ONTAP crée une on-Access policy nommée « default_CIFS » et l'active pour tous les SVM d'un cluster.
* Tout fichier admissible à l'exclusion de numérisation en fonction du `paths-to-exclude`, `file-ext-to-exclude`, ou `max-file-size` les paramètres ne sont pas pris en compte pour l'acquisition, même si l' `scan-mandatory` l'option est activée. (Cochez cette case link:vscan-server-connection-concept.html["dépannage"] pour les problèmes de connectivité liés au `scan-mandatory` option.)
* Par défaut, seuls les volumes en lecture-écriture sont analysés. Vous pouvez spécifier des filtres qui permettent la numérisation de volumes en lecture seule ou qui limitent la numérisation aux fichiers ouverts avec l'accès d'exécution.
* L'analyse antivirus n'est pas effectuée sur un partage SMB pour lequel le paramètre disponible en continu est défini sur Oui.
* Voir la link:architecture-concept.html["Architecture antivirus"] Pour plus d'informations sur le profil _Vscan file-Operations_.
* Vous pouvez créer un maximum de dix (10) règles d'accès par SVM. Toutefois, vous ne pouvez activer qu'une seule stratégie d'accès à la fois.
+
** Vous pouvez exclure un maximum de cent (100) chemins et extensions de fichiers de l'analyse antivirus dans une stratégie d'accès.


* Quelques recommandations d'exclusion de fichiers :
+
** Pensez à exclure les fichiers volumineux (la taille de fichier peut être spécifiée) de l'analyse antivirus car ils peuvent entraîner un temps de réponse lent ou des délais de requête d'analyse pour les utilisateurs CIFS. La taille de fichier par défaut pour l'exclusion est de 2 Go.
** Pensez à exclure les extensions de fichier telles que `.vhd` et `.tmp` car les fichiers avec ces extensions peuvent ne pas être appropriés pour la numérisation.
** Pensez à exclure les chemins de fichiers tels que le répertoire de quarantaine ou les chemins dans lesquels seuls les disques durs virtuels ou les bases de données sont stockés.
** Vérifiez que toutes les exclusions sont spécifiées dans la même stratégie, car une seule stratégie peut être activée à la fois. NetApp recommande vivement de disposer du même ensemble d'exclusions que celui spécifié dans le moteur antivirus.
** À partir de ONTAP 9.14.1, vous pouvez utiliser des caractères génériques pour spécifier les chemins d'accès à la demande et les extensions de fichiers à exclure.


* Une stratégie d'accès est requise pour un xref:create-on-demand-task-task.html[analyse à la demande]. Pour éviter la numérisation à l'accès, vous devez définir `-scan-files-with-no-ext` pour faux et `-file-ext-to-exclude` à * pour exclure tous les postes.


.Étapes
. Création d'une règle on-Access :
+
`vserver vscan on-access-policy create -vserver _data_SVM|cluster_admin_SVM_ -policy-name _policy_name_ -protocol CIFS -max-file-size _max_size_of_files_to_scan_ –filters [scan-ro-volume,][scan-execute-access] -file-ext-to-include _extensions_of_files_to_include_ -file-ext-to-exclude _extensions_of_files_to_exclude_ -scan-files-with-no-ext true|false -paths-to-exclude _paths_of_files_to_exclude_ -scan-mandatory on|off`

+
** Spécifier un SVM de données pour une politique définie pour un SVM individuel, un SVM d'administration du cluster pour une politique définie pour tous les SVM d'un cluster.
** Le `-file-ext-to-exclude` le réglage remplace le `-file-ext-to-include` réglage.
** Réglez `-scan-files-with-no-ext` à vrai pour numériser des fichiers sans extensions.
La commande suivante crée une on-Access policy nommée `Policy1` sur le `vs1` SVM :


+
[listing]
----
cluster1::> vserver vscan on-access-policy create -vserver vs1 -policy-name Policy1 -protocol CIFS -filters scan-ro-volume -max-file-size 3GB -file-ext-to-include "mp*","tx*" -file-ext-to-exclude "mp3","txt" -scan-files-with-no-ext false -paths-to-exclude "\vol\a b\","\vol\a,b\"
----
. Vérifiez que la stratégie on-Access a été créée : `vserver vscan on-access-policy show -instance _data_SVM|cluster_admin_SVM_ -policy-name _name_`
+
Pour en savoir plus, `vserver vscan on-access-policy` consultez le link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-on-access-policy-show.html["Référence de commande ONTAP"^].

+
La commande suivante affiche les détails de `Policy1` règle :

+
[listing]
----
cluster1::> vserver vscan on-access-policy show -instance vs1 -policy-name Policy1

                           Vserver: vs1
                            Policy: Policy1
                     Policy Status: off
               Policy Config Owner: vserver
              File-Access Protocol: CIFS
                           Filters: scan-ro-volume
                    Mandatory Scan: on
Max File Size Allowed for Scanning: 3GB
            File Paths Not to Scan: \vol\a b\, \vol\a,b\
       File Extensions Not to Scan: mp3, txt
           File Extensions to Scan: mp*, tx*
      Scan Files with No Extension: false
----

