---
permalink: antivirus/enable-virus-scan-svm-task.html 
sidebar: sidebar 
keywords: enable, virus scan, svm 
summary: 'Vous devez activer l"analyse antivirus sur un SVM avant de pouvoir exécuter une analyse à la demande ou à l"accès.' 
---
= Activer l'analyse antivirus sur SVM ONTAP Vscan
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez activer l'analyse antivirus sur un SVM avant de pouvoir exécuter une analyse à la demande ou à l'accès.

.Étapes
. Activer l'analyse antivirus sur un SVM :
+
`vserver vscan enable -vserver data_SVM`

+
Pour en savoir plus, `vserver vscan enable` consultez le link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-enable.html["Référence de commande ONTAP"^].

+
[NOTE]
====
Vous pouvez, si nécessaire, désactiver l'analyse antivirus à l'aide de `vserver vscan disable` la commande. Pour en savoir plus, `vserver vscan disable` consultez le link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-disable.html["Référence de commande ONTAP"^].

====
+
La commande suivante active l'analyse antivirus sur le `vs1` SVM :

+
[listing]
----
cluster1::> vserver vscan enable -vserver vs1
----
. Vérifier que l'analyse antivirus est activée sur le SVM :
+
`vserver vscan show -vserver data_SVM`

+
Pour en savoir plus, `vserver vscan show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-show.html["Référence de commande ONTAP"^].

+
La commande suivante affiche le statut Vscan du `vs1` SVM :

+
[listing]
----
cluster1::> vserver vscan show -vserver vs1

                           Vserver: vs1
                      Vscan Status: on
----

