---
permalink: antivirus/modify-vscan-file-profile-smb-share-task.html 
sidebar: sidebar 
keywords: modify, vscan, file-operations, profile, cifs share 
summary: 'Le profil Vscan des opérations-fichier d"un partage SMB définit les opérations sur le partage qui peuvent déclencher l"analyse. Par défaut, le paramètre est défini sur standard. Vous pouvez régler le paramètre si nécessaire lors de la création ou de la modification d"un partage SMB.' 
---
= Modifier le profil des opérations-fichiers Vscan pour un partage SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le profil Vscan des opérations-fichier d'un partage SMB définit les opérations sur le partage qui peuvent déclencher l'analyse. Par défaut, le paramètre est défini sur `standard`. Vous pouvez régler le paramètre si nécessaire lors de la création ou de la modification d'un partage SMB.

Pour plus d'informations sur les valeurs disponibles pour un profil d'opérations de fichiers Vscan, reportez-vous à la section « profil d'opérations de fichiers Vscan ».

link:architecture-concept.html["Profil des opérations de fichiers Vscan (analyse accessible uniquement)"]

[NOTE]
====
L'analyse antivirus n'est pas réalisée sur un partage SMB pour lequel `continuously-available` le paramètre est défini sur `Yes`.

====
.Étape
. Modifier la valeur du profil des fichiers-opérations Vscan pour un partage SMB : `vserver cifs share modify -vserver _data_SVM_ -share-name _share_ -path _share_path_ -vscan-fileop-profile no-scan|standard|strict|writes-only`
+
Pour obtenir la liste complète des options, consultez la page man de la commande.

+
La commande suivante modifie le profil des opérations de fichier Vscan pour un partage SMB à `strict`:

+
[listing]
----
cluster1::> vserver cifs share modify -vserver vs1 -share-name SALES_SHARE -path /sales -vscan-fileop-profile strict
----

