---
permalink: antivirus/reset-status-scanned-files-task.html 
sidebar: sidebar 
keywords: reset, status, scanned files 
summary: 'Il peut arriver que vous souhaitiez réinitialiser l"état de scan des fichiers ayant réussi sur un SVM en utilisant la commande vserver vscan reset afin d"ignorer les informations mises en cache pour les fichiers. Vous pouvez utiliser cette commande pour redémarrer le traitement de l"analyse antivirus en cas de mauvaise configuration d"une analyse, par exemple.' 
---
= Réinitialiser l'état des fichiers numérisés par ONTAP Vscan
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il peut parfois être utile de réinitialiser l'état de scan des fichiers scannés avec succès sur un SVM en utilisant la `vserver vscan reset` commande pour supprimer les informations mises en cache pour les fichiers. Vous pouvez utiliser cette commande pour redémarrer le traitement de l'analyse antivirus en cas de mauvaise configuration d'une analyse, par exemple. Pour en savoir plus, `vserver vscan reset` consultez le link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-reset.html["Référence de commande ONTAP"^].

.Description de la tâche
Après avoir exécuté le `vserver vscan reset` commande, tous les fichiers admissibles seront numérisés la prochaine fois qu'ils seront consultés.

[NOTE]
====
Cette commande peut avoir un impact négatif sur les performances, en fonction du nombre et de la taille des fichiers à réanalyser.

====
.Avant de commencer
Des privilèges avancés sont requis pour cette tâche.

.Étapes
. Changement au niveau de privilège avancé :
+
`set -privilege advanced`

+
Pour en savoir plus, `set -privilege advanced` consultez le link:https://docs.netapp.com/us-en/ontap-cli/set.html["Référence de commande ONTAP"^].

. Réinitialiser l'état des fichiers numérisés :
+
`vserver vscan reset -vserver data_SVM`

+
La commande suivante réinitialise l'état des fichiers numérisés sur le `vs1` SVM :

+
[listing]
----
cluster1::> vserver vscan reset -vserver vs1
----

