---
permalink: antivirus/schedule-on-demand-task-task.html 
sidebar: sidebar 
keywords: schedule, on-demand, task 
summary: 'Vous pouvez créer une tâche sans affecter de planification et utiliser le `vserver vscan on-demand-task schedule` pour attribuer un planning ou pour ajouter un planning lors de la création de la tâche.' 
---
= Planifiez une tâche à la demande avec ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer une tâche sans affecter de planification et utiliser le `vserver vscan on-demand-task schedule` pour attribuer un planning ou pour ajouter un planning lors de la création de la tâche.

.Description de la tâche
Planification affectée avec `vserver vscan on-demand-task schedule` la commande remplace un planning déjà affecté par le `vserver vscan on-demand-task create` commande.

.Étapes
. Planifier une tâche à la demande :
+
`vserver vscan on-demand-task schedule -vserver _data_SVM_ -task-name _task_name_ -schedule cron_schedule`

+
La commande suivante planifie une tâche à accès nommée `Task2` sur le `vs2` SVM :

+
[listing]
----
cluster1::> vserver vscan on-demand-task schedule -vserver vs2 -task-name Task2 -schedule daily
[Job 142]: Vscan On-Demand job is queued. Use the "job show -id 142" command to view the status.
----
+
Pour en savoir plus, `vserver vscan on-demand-task schedule` consultez le link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-on-demand-task-schedule.html["Référence de commande ONTAP"^].

+

NOTE: Pour afficher l'état du travail, utilisez la `job show` commande. Les `job pause` commandes et `job resume`, respectivement, interrompent et redémarrent le travail ; la `job stop` commande termine le travail. Pour en savoir plus, `job` consultez le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=job["Référence de commande ONTAP"^].

. Vérifiez que la tâche à la demande a été planifiée :
+
`vserver vscan on-demand-task show -instance _data_SVM_ -task-name _task_name_`

+
Pour en savoir plus, `vserver vscan on-demand-task show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-on-demand-task-show.html["Référence de commande ONTAP"^].

+
La commande suivante affiche les détails de `Task 2` tâche :

+
[listing]
----
cluster1::> vserver vscan on-demand-task show -instance vs2 -task-name Task2

                           Vserver: vs2
                         Task Name: Task2
                List of Scan Paths: /vol1/, /vol2/cifs/
             Report Directory Path: /report
                      Job Schedule: daily
Max File Size Allowed for Scanning: 5GB
            File Paths Not to Scan: /vol1/cold-files/
       File Extensions Not to Scan: mp3, mp4
           File Extensions to Scan: vmdk, mp*
      Scan Files with No Extension: false
           Request Service Timeout: 5m
                    Cross Junction: true
               Directory Recursion: true
                     Scan Priority: low
                  Report Log Level: info
----


.Une fois que vous avez terminé
Vous devez activer l'analyse sur la SVM avant que la tâche ne soit planifiée.
