---
permalink: antivirus/troubleshoot-common-virus-scanning-issues-reference.html 
sidebar: sidebar 
keywords: troubleshooting, troubleshoot, virus scanning, vscan, monitoring, connection, connectivity 
summary: 'Un tableau répertoriant les problèmes courants d"analyse de virus, leurs causes possibles et les moyens de les résoudre.' 
---
= Résolution des problèmes liés à l'analyse antivirus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour les problèmes courants d'analyse antivirus, il existe des causes possibles et des moyens de les résoudre. L'analyse antivirus est également appelée Vscan.

|===


| Problème | Comment le résoudre 


 a| 
Les serveurs Vscan ne peuvent pas se connecter à
Système de stockage clustered ONTAP.
 a| 
Vérifiez si la configuration du scanner pool spécifie le
Adresse IP du serveur Vscan. Vérifiez également si le est autorisé
les utilisateurs privilégiés de la liste des scanner-pool sont actifs. Pour vérifier le scanner pool, exécutez le `vserver vscan scanner-pool show` dans l'invite de commande du système de stockage.
Si les serveurs Vscan ne peuvent toujours pas se connecter, il peut y avoir un problème au niveau du réseau.



 a| 
Les clients observent une latence élevée
 a| 
Il est probablement temps d'ajouter d'autres serveurs Vscan au
scanner pool.



 a| 
Trop d'acquisitions sont déclenchées
 a| 
Modifier la valeur du `vscan-fileop-profile`
paramètre permettant de limiter le nombre d'opérations sur les fichiers
surveillé pour l'analyse antivirus



 a| 
Certains fichiers ne sont pas numérisés.
 a| 
Vérifiez la stratégie d'accès. Il est possible que le chemin pour
ces fichiers ont été ajoutés à la liste d'exclusion de chemin d'accès ou à celle-ci
leur taille dépasse la valeur configurée pour les exclusions. À
vérifiez la stratégie d'accès, exécutez le `vserver vscan
on-access-policy show` sur le stockage
invite de commande système.



 a| 
Accès au fichier refusé.
 a| 
Vérifiez si le paramètre de numérisation obligatoire est spécifié
dans la configuration de la règle. Ce paramètre refuse l'accès aux données
Si aucun serveur Vscan n'est connecté Modifiez le paramètre comme
approprié.

|===