---
permalink: revert/anti-ransomware-license-task.html 
sidebar: sidebar 
keywords: revert, reverting, reversion, anti-ransomware, autonomous, protection, arp, license, licensing 
summary: 'Si vous avez configuré la protection contre les ransomwares et que vous restaurez de ONTAP 9.11.1 ou version ultérieure vers ONTAP 9.10.1, vous pouvez rencontrer des messages d"avertissement et une fonctionnalité anti-ransomwares limitée.' 
---
= Vérifiez les licences autonomes de protection contre les ransomwares avant de restaurer depuis ONTAP 9.11.1 ou version ultérieure
:allow-uri-read: 


[role="lead"]
Si vous avez configuré la protection autonome contre les attaques par ransomware (ARP) et que vous restaurez de ONTAP 9.11.1 ou version ultérieure à ONTAP 9.10.1 ou version antérieure, vous risquez de rencontrer des messages d'avertissement et une fonctionnalité ARP limitée.

Dans ONTAP 9.11.1, la licence anti-ransomware a remplacé la licence MTKM (Multi-tenant Key Management). Si votre système dispose de la licence anti-ransomware mais qu'aucune licence MT_EK_MGMT n'est disponible, un avertissement s'affiche lors de la restauration indiquant que ARP ne peut pas être activé sur les nouveaux volumes lors de la restauration.

Les volumes bénéficiant d'une protection existante continuent de fonctionner normalement après restauration, et le statut ARP peut être affiché à l'aide de l'interface de ligne de commande de ONTAP. System Manager ne peut pas afficher l'état ARP sans la licence MTKM.

Par conséquent, si vous souhaitez que ARP continue après le retour à ONTAP 9.10.1, assurez-vous que la licence MTKM est installée avant le rétablissement. link:../anti-ransomware/index.html["En savoir plus sur les licences ARP."]
