---
permalink: revert/anti-ransomware-disable-san.html 
sidebar: sidebar 
keywords: revert, reverting, reversion, anti-ransomware, san, autonomous, protection, arp 
summary: Désactivez ARP sur les volumes SAN avant de revenir à ONTAP 9.16.1 ou une version antérieure pour éviter une consommation inutile de CPU et d’espace disque. 
---
= Désactiver la protection autonome contre les ransomwares sur les volumes SAN avant de revenir à ONTAP 9.17.1
:allow-uri-read: 


[role="lead"]
La fonctionnalité ARP ONTAP pour les volumes SAN n'est pas prise en charge dans ONTAP 9.16.1 et les versions antérieures. Il est recommandé de désactiver ARP sur les volumes SAN avant de revenir à ONTAP 9.16.1 ou une version antérieure afin d'éviter que la fonctionnalité reste active et utilise les ressources CPU et disque sans effectuer de détection réelle sur la version restaurée.

.Étapes
[role="tabbed-block"]
====
.System Manager
--
. Sélectionnez *Stockage > Volumes*, puis sélectionnez le nom du volume.
. Dans l'onglet *Sécurité* de l'aperçu *Volumes*, sélectionnez *État* pour passer de Activé à Désactivé.


--
.CLI
--
. Désactiver la protection contre les ransomwares sur un volume :
+
[source, cli]
----
security anti-ransomware volume disable -volume <vol_name> -vserver <svm_name>
----


--
====