---
permalink: revert/concept_reversion_requirements_for_snapmirror_and_snapvault_relationships.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, requirements, snapmirror, snapvault, relationships 
summary: La commande system node revert-to vous informe de toute relation SnapMirror et SnapVault qui doit être supprimée ou reconfigurée pour que le processus de restauration soit terminé. Cependant, vous devez connaître ces exigences avant de commencer la nouvelle version. 
---
= Conditions de restauration de ONTAP pour les relations SnapMirror et SnapVault
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La `system node revert-to` commande vous informe de toute relation SnapMirror et SnapVault qui doit être supprimée ou reconfigurée pour que le processus de restauration soit terminé. Cependant, vous devez connaître ces exigences avant de commencer la nouvelle version.

* Toutes les relations de SnapVault et de miroir de protection des données doivent être suspendues, puis cassées.
+
Une fois la restauration terminée, vous pouvez resynchroniser et reprendre ces relations si un snapshot commun existe.

* Les relations SnapVault ne doivent pas contenir les types de règles SnapMirror suivants :
+
** mise en miroir asynchrone
+
Vous devez supprimer toute relation utilisant ce type de stratégie.

** MirrorAndVault
+
Si l'une de ces relations existe, vous devez modifier la règle SnapMirror en miroir-vault.



* Tous les clones de charge et volumes de destination doivent être supprimés.
* Les relations SnapMirror avec des volumes de destination FlexClone doivent être supprimées.
* La compression réseau doit être désactivée pour chaque règle SnapMirror.
* La règle All_source_snapshot doit être supprimée de toute règle SnapMirror de type async-mirror.
+

NOTE: Les opérations SFSR (Single File Snapshot Restore) et PFSR (Partial File Snapshot Restore) sont obsolètes au niveau du volume racine.

* Toutes les opérations de restauration de fichiers et de snapshots uniques en cours d'exécution doivent être terminées avant que la restauration ne puisse continuer.
+
Vous pouvez soit attendre la fin de l'opération de restauration, soit l'abandonner.

* Toute opération de restauration incomplète de fichier unique et d'instantané doit être supprimée à l'aide de la `snapmirror restore` commande.
+
Pour en savoir plus, `snapmirror restore` consultez le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-restore.html["Référence de commande ONTAP"^].


