---
permalink: revert/concept_when_to_call_technical_support.html 
sidebar: sidebar 
keywords: ontap, downgrade, revert, paths 
summary: Vous pouvez revenir aux clusters de test ou aux nouveaux clusters sans assistance. Contactez le support technique pour rétablir les clusters de production. 
---
= Ai-je besoin d'une assistance technique pour rétablir le service ?
:allow-uri-read: 


[role="lead"]
Vous pouvez revenir aux clusters de test ou aux nouveaux clusters sans assistance. Contactez le support technique pour rétablir les clusters de production. Si vous rencontrez l'un des problèmes suivants, appelez le support technique :

* Vous êtes dans un environnement de production et la restauration échoue, ou vous rencontrez des problèmes avant ou après la restauration :
+
** Le processus de restauration a échoué et ne peut pas se terminer.
** Le processus de restauration est terminé, mais le cluster est inutilisable dans un environnement de production.
** Le processus de restauration se termine et le cluster passe en production, mais vous n'êtes pas satisfait de son comportement.


* Vous avez créé des volumes dans ONTAP 9.5 ou version ultérieure et vous devez restaurer une version antérieure. Les volumes qui utilisent la compression adaptative doivent être décompressés avant le rétablissement.

