---
permalink: revert/concept_when_to_call_technical_support.html 
sidebar: sidebar 
keywords: ontap, downgrade, revert, paths 
summary: Sur les clusters nouveaux ou de test, vous pouvez effectuer une restauration sans assistance. Pour les clusters de production, vous devez contacter le support technique. 
---
= Ai-je besoin d'un support technique pour rétablir un cluster ONTAP ?
:allow-uri-read: 


[role="lead"]
Vous devez contacter le support technique avant de tenter de rétablir un cluster ONTAP dans les situations suivantes :

* Un environnement de production
+
N'essayez pas de rétablir un cluster de production sans l'aide du support technique.

* Vous avez créé des volumes dans ONTAP 9.5 ou version ultérieure et vous devez restaurer une version antérieure.
+
Les volumes qui utilisent la compression adaptative doivent être décompressés avant le rétablissement.



Vous pouvez restaurer de nouveaux clusters ou tester ces clusters sans assistance. Si vous tentez de rétablir vous-même un cluster et rencontrez l'un des problèmes suivants, contactez le support technique :

* La restauration échoue ou ne peut pas se terminer.
* La restauration se termine, mais le cluster est inutilisable dans un environnement de production.
* La restauration se termine et le cluster passe en production, mais vous n'êtes pas satisfait de son comportement.

