---
permalink: revert/concept_support_of_sp_firmware_automatic_revert.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, considerations, manual, manually, update, updating, sp, firmware 
summary: Si la fonctionnalité de mise à jour automatique du processeur de service est activée, la rétrogradation ou le rétablissement vers ONTAP 8.3.x ne nécessite pas de mise à jour manuelle du micrologiciel du processeur de service. Le micrologiciel du processeur de service est automatiquement mis à jour vers la dernière version compatible prise en charge par la version ONTAP que vous avez rétablie ou rétrogradée. 
---
= Facteurs à prendre en compte pour la mise à jour manuelle du firmware du processeur de service
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si la fonctionnalité de mise à jour automatique du processeur de service est activée (par défaut), la rétrogradation ou le rétablissement de ONTAP 8.3.x ne nécessite pas de mise à jour manuelle du micrologiciel du processeur de service. Le micrologiciel du processeur de service est automatiquement mis à jour vers la dernière version compatible prise en charge par la version ONTAP que vous avez rétablie ou rétrogradée.

Si la fonctionnalité de mise à jour automatique du processeur de service est désactivée (non recommandée), après ONTAP la fin du processus de restauration ou de mise à niveau vers une version antérieure du micrologiciel du processeur de service, vous devez mettre à jour manuellement la version prise en charge pour la version de ONTAP à laquelle vous avez rétabli ou déclassé.

http://mysupport.netapp.com/NOW/download/tools/serviceimage/support/["Matrice de prise en charge NetApp BIOS/ONTAP"]

https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics["Téléchargements NetApp : firmware système et diagnostics"]
