---
permalink: revert/concept_consideration_for_reverting_systems_with_snapmirror_synchronous_relationships.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, considerations, snapmirror, synchronous, relationships 
summary: Vous devez tenir compte des considérations relatives aux relations SnapMirror synchrone avant de restaurer la version ONTAP 9.6 à ONTAP 9.5. 
---
= Considérations relatives à l'rétablissement de systèmes avec des relations SnapMirror synchrone
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez tenir compte des considérations relatives aux relations SnapMirror synchrone avant de restaurer la version ONTAP 9.6 à ONTAP 9.5.

Avant de restaurer les données, vous devez effectuer les étapes suivantes si vous avez des relations SnapMirror synchrone :

* Vous devez supprimer toute relation SnapMirror synchrone dans laquelle le volume source transmet des données via NFSv4 ou SMB.
+
ONTAP 9.5 ne prend pas en charge NFSv4 et SMB.

* Vous devez supprimer toutes les relations SnapMirror synchrone dans un déploiement en cascade de miroir.
+
Un déploiement en cascade en miroir n'est pas pris en charge pour les relations SnapMirror synchrone dans ONTAP 9.5.

* Si les copies Snapshot courantes de ONTAP 9.5 ne sont pas disponibles lors de la restauration, vous devez initialiser la relation SnapMirror synchrone après le rétablissement.
+
Après deux heures de mise à niveau vers ONTAP 9.6, les copies Snapshot courantes de ONTAP 9.5 sont automatiquement remplacées par les copies Snapshot communes de ONTAP 9.6. Par conséquent, vous ne pouvez pas resynchroniser la relation SnapMirror synchrone après le rétablissement si les copies Snapshot communes de ONTAP 9.5 ne sont pas disponibles.


