---
permalink: revert/delete-active-active-svms.html 
sidebar: sidebar 
keywords: delete, active-active, SVMs, storage virtual machines, revert 
summary: 'Si vous avez activé l"agrégation pour les connexions client et que vous revenez à une version antérieure à ONTAP 9.12.1, vous devez désactiver l"agrégation sur tous les serveurs NFSv4.1 avant le rétablissement.' 
---
= Supprimez les SVM actifs-actifs avant de revenir de ONTAP 9.19.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le multipathing actif-actif SAN n'est pas pris en charge dans ONTAP 9.18.1 et les versions antérieures. Avant de revenir de ONTAP 9.19.1, vous devez supprimer toutes les machines virtuelles de stockage (SVM) avec des configurations actif-actif.

.Étapes
. Identifiez les SVM dont l'option san-multipathing est configurée pour actif-actif ou actif-actif-scsi-only :
+
[source, cli]
----
vserver show
----
. Supprimez tous les SVM configurés pour le multipathing actif-actif ou actif-actif-scsi uniquement :
+
[source, cli]
----
vserver delete -vserver <SVM>
----
. Vérifiez que les SVM sont supprimés :
+
[source, cli]
----
vserver show
----


.Informations associées
Apprenez-en davantage sur link:../san-admin/multipath-automatic-lif-failover-support.html["Prise en charge du multipathing actif-actif SAN"] dans ONTAP 9.19.1 et versions ultérieures.
