---
permalink: revert/identify-user-sha2-hash-user-accounts.html 
sidebar: sidebar 
keywords: revert, reverting, reversion, password, hash, function, supported, encryption, type 
summary: Si vous restaurez une version antérieure à une version de ONTAP 9, les utilisateurs de compte SHA-2 ne peuvent plus être authentifiés avec leurs mots de passe. 
---
= Identifiez les comptes utilisateur qui utilisent la fonction de hachage SHA-2
:allow-uri-read: 


[role="lead"]
Si vous êtes en train de revenir de ONTAP 9.1 ou ONTAP 9.0 à ONTAP 8.3.x, les utilisateurs de comptes SHA-2 ne peuvent plus être authentifiés avec leurs mots de passe. Avant de revenir à la version précédente, vous devez identifier les comptes utilisateur qui utilisent la fonction de hachage SHA-2, de sorte qu'après le rétablissement, vous pouvez les faire réinitialiser pour utiliser le type de cryptage (MD5) pris en charge par la version à laquelle vous restaurez.

. Passez au paramètre de privilège sur avancé : `set -privilege advanced`
. Identifiez les comptes d'utilisateur qui utilisent le SHA-2 ont une fonction : `security login show -vserver * -username * -application * -authentication-method password -hash-function !md5`
. Conservez le résultat de la commande à utiliser après la restauration.



NOTE: Pendant la restauration, vous êtes invité à exécuter la commande avancée `security login password-prepare-to-downgrade` Pour réinitialiser votre propre mot de passe pour utiliser la fonction de hachage MD5. Si votre mot de passe n'est pas chiffré avec MD5, la commande vous invite à saisir un nouveau mot de passe et le crypte avec MD5, ce qui permet à vos informations d'identification d'être authentifiées après la restauration.
