---
permalink: revert/remove-nas-bucket-task.html 
sidebar: sidebar 
keywords: s3, svm, bucket, object, server, filesystems, nas, directories, revert 
summary: 'Si vous avez configuré l"accès client S3 pour les données NAS et que vous restaurez la ONTAP version 9.12.1 ou ultérieure à ONTAP 9.11.1 ou version antérieure, vous devez supprimer la configuration du compartiment NAS. Vous devez également supprimer tous les utilisateurs S3 des mappages de noms d"utilisateur Windows/Unix avant de restaurer.' 
---
= Supprimez la configuration du compartiment NAS S3 avant de revenir à ONTAP 9.12.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous avez configuré l'accès client S3 pour les données NAS, vous devez utiliser l'interface de ligne de commande ONTAP pour supprimer la configuration du compartiment NAS et supprimer tout mappage de nom (utilisateurs S3 vers utilisateurs Windows ou Unix) avant de revenir de ONTAP 9.12.1.

.Description de la tâche
Les tâches suivantes sont effectuées en arrière-plan pendant le processus de restauration.

* Supprimez toutes les créations d'objets singleton partiellement terminées (c'est-à-dire toutes les entrées des répertoires masqués).
* Supprimez tous les répertoires masqués : il peut y en avoir un pour chaque volume accessible à partir de la racine de l'exportation mappée depuis le compartiment NAS S3.
* Supprimez la table de chargement.
* Supprimez toutes les valeurs par défaut utilisateur-unix et utilisateur-Windows-par défaut de tous les serveurs S3 configurés.


.Étapes
. Supprimer la configuration de compartiment NAS S3 :
+
[source, cli]
----
vserver object-store-server bucket delete -vserver <svm_name> -bucket <s3_nas_bucket_name>
----
+
Pour en savoir plus, `vserver object-store-server bucket delete` consultez le link:https://docs.netapp.com/us-en/ontap-cli/vserver-object-store-server-bucket-delete.html["Référence de commande ONTAP"^].

. Supprimer les mappages de noms pour UNIX :
+
[source, cli]
----
vserver name-mapping delete -vserver <svm_name> -direction s3-unix
----
+
Pour en savoir plus, `vserver name-mapping delete` consultez le link:https://docs.netapp.com/us-en/ontap-cli/vserver-name-mapping-delete.html["Référence de commande ONTAP"^].

. Supprimer les mappages de noms pour Windows :
+
[source, cli]
----
vserver name-mapping delete -vserver <svm_name> -direction s3-win
----
. Retirer les protocoles S3 du SVM :
+
[source, cli]
----
vserver remove-protocols -vserver <svm_name> -protocols s3
----
+
Pour en savoir plus, `vserver remove-protocols` consultez le link:https://docs.netapp.com/us-en/ontap-cli/vserver-remove-protocols.html["Référence de commande ONTAP"^].


