---
permalink: revert/task-disable-tls-nvme-host.html 
sidebar: sidebar 
keywords: ontap, revert, reversion, reverting, tls, nvme, host, controller, subsystem, tls secure channel 
summary: Avant de revenir à une version précédente de ONTAP qui ne prend pas en charge TLS pour les hôtes NVMe, vous devez désactiver TLS sur les hôtes NVMe. 
---
= Désactivez le canal sécurisé TLS sur un hôte NVMe avant le rétablissement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À partir de ONTAP 9.16.1, vous pouvez configurer le canal sécurisé TLS pour les connexions NVMe/TCP. Si vous avez configuré le canal sécurisé TLS pour les connexions NVMe/TCP dans ONTAP 9.16.1 ou les versions ultérieures, vous devez désactiver la configuration TLS sur les hôtes NVMe avant de rétablir ONTAP dans une version qui ne prend pas en charge le canal sécurisé TLS pour NVMe/TCP.

.Étapes
. Supprimez la configuration de canal sécurisé TLS de l'hôte :
+
[source, cli]
----
vserver nvme subsystem host unconfigure-tls-for-revert -vserver <svm_name> -subsystem <subsystem> -host-nqn <host_nqn>
----
+
Cette commande supprime l'hôte du sous-système, puis recrée l'hôte dans le sous-système sans la configuration TLS.

. Vérifiez que le canal sécurisé TLS est supprimé de l'hôte :
+
[source, cli]
----
vserver nvme subsystem host show
----


.En savoir plus >>
Consultez les pages de manuel ONTAP pour obtenir les commandes suivantes :

* https://docs.netapp.com/us-en/ontap-cli/vserver-nvme-subsystem-host-unconfigure-tls-for-revert.html["vserver nvme sous-système host unconfigure-tls-for-revert"^]
* https://docs.netapp.com/us-en/ontap-cli/vserver-nvme-subsystem-host-show.html["vserver nvme sous-système host show"^]

