---
permalink: revert/task_reverting_an_ontap_cluster.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, cluster 
summary: Pour mettre le cluster hors ligne afin de revenir à une version antérieure de ONTAP, vous devez désactiver le basculement du stockage et les LIF de données, mettre en place des conditions préalables à la reversion, rétablir les configurations du cluster et du système de fichiers sur un nœud, puis répéter le processus pour chaque nœud supplémentaire du cluster. 
---
= Ne restaurez pas un cluster ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour mettre le cluster hors ligne afin de revenir à une version antérieure de ONTAP, vous devez désactiver le basculement du stockage et les LIF de données, mettre en place des conditions préalables à la reversion, rétablir les configurations du cluster et du système de fichiers sur un nœud, puis répéter le processus pour chaque nœud supplémentaire du cluster.

Vous devez avoir terminé la restauration link:task_things_to_verify_before_revert.html["vérifications"] et link:concept_pre_revert_checks.html["pré-contrôles"].

Pour restaurer un cluster, vous devez mettre le cluster hors ligne pendant la durée de la nouvelle version.

. Définissez le niveau de privilège sur avancé : `set -privilege advanced`
+
Entrez *y* lorsque vous êtes invité à continuer.

. Vérifier que le logiciel ONTAP cible est installé : `system image show`
+
L'exemple suivant montre que la version 9.1 est installée comme image alternative sur les deux nœuds :

+
[listing]
----
cluster1::*> system image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    9.2        MM/DD/YYYY TIME
         image2  false   false   9.1        MM/DD/YYYY TIME
node1
         image1  true    true    9.2        MM/DD/YYYY TIME
         image2  false   false   9.1        MM/DD/YYYY TIME
4 entries were displayed.
----
. Désactiver toutes les LIFs de données du cluster : `network interface modify {-role data} -status-admin down`
. Déterminez si vous avez des relations FlexCache entre clusters : `flexcache origin show-caches -relationship-type inter-cluster`
. Si des flexcar inter-cluster sont présents, désactiver les lifs de données sur le cluster de cache : `network interface modify -vserver vserver_name -lif lif_name -status-admin down`
. Si le cluster ne comprend que deux nœuds, désactiver cluster HA : `cluster ha modify -configured false`
. [[STEP-5]]désactivez le basculement du stockage pour les nœuds de la paire haute disponibilité à partir de l'un des deux nœuds : `storage failover modify -node nodename -enabled false`
+
Il n'est nécessaire de désactiver qu'une seule fois le basculement du stockage pour la paire haute disponibilité. Lorsque vous désactivez le basculement du stockage pour un nœud, le basculement du stockage est également désactivé sur le partenaire du nœud.

. [[STEP-6]]Connectez-vous au nœud que vous souhaitez restaurer.
+
Pour restaurer un nœud, vous devez être connecté au cluster par l'intermédiaire du LIF de node management.

. Définissez l'image du logiciel ONTAP cible du nœud sur l'image par défaut : `system image modify -node nodename -image target_image -isdefault true`
. Vérifiez que l'image logicielle ONTAP cible est définie en tant qu'image par défaut du nœud que vous rétablissement : `system image show`
+
L'exemple suivant montre que la version 9.1 est définie comme image par défaut sur le noeud 0 :

+
[listing]
----
cluster1::*> system image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  false   true    9.2        MM/DD/YYYY TIME
         image2  true    false   9.1        MM/DD/YYYY TIME
node1
         image1  true    true    9.2        MM/DD/YYYY TIME
         image2  false   false   9.1        MM/DD/YYYY TIME
4 entries were displayed.
----
. Si le cluster ne comprend que deux nœuds, vérifier que le nœud ne contient pas epsilon :
+
.. Vérifier si le nœud contient actuellement epsilon : `cluster show -node nodename`
+
L'exemple suivant montre que le nœud contient epsilon :

+
[listing]
----
cluster1::*> cluster show -node node1

          Node: node1
          UUID: 026efc12-ac1a-11e0-80ed-0f7eba8fc313
       Epsilon: true
   Eligibility: true
        Health: true
----
.. Si le nœud contient epsilon, marquer l'epsilon comme false sur le nœud afin que l'epsilon peut être transféré au partenaire du nœud : `cluster modify -node nodenameA -epsilon false`
.. Transfert d'epsilon vers le partenaire du nœud par le marquage epsilon true sur le nœud partenaire : `cluster modify -node nodenameB -epsilon true`


. Vérifiez que le nœud est prêt pour la nouvelle version : `system node revert-to -node nodename -check-only true -version 9.x`
+
Le paramètre de vérification seule identifie les conditions préalables qui doivent être abordées avant le rétablissement, comme les exemples suivants :

+
** Désactivation du basculement du stockage
** Désactivation de la règle Snapshot
** Suppression des copies Snapshot qui ont été créées après la mise à niveau vers la version ultérieure d'ONTAP


. Vérifiez que toutes les conditions préalables ont été traitées : `system node revert-to -node nodename -check-only true -version 9.x`
. Ne rétablit pas la configuration de cluster du nœud: `system node revert-to -node nodename -version 9.x`
+
L'option -version fait référence à la version cible. Par exemple, si le logiciel que vous avez installé et vérifié est ONTAP 9.1, la valeur correcte de l'option -version est 9.1.

+
La configuration du cluster est rétablie, puis vous êtes déconnecté du clustershell.

. Reconnectez-vous au clustershell, puis basculez vers le nodeshell : `run -node nodename`
+
Après une nouvelle connexion au clustershell, quelques minutes suffisent avant qu'il soit prêt à accepter la commande nodeshell. Si la commande échoue, attendez quelques minutes et réessayez.

. Ne rétablit pas la configuration du système de fichiers du nœud: `revert_to 9.x`
+
Cette commande vérifie que la configuration du système de fichiers du nœud est prête à être rétablie, puis la restaure. Si des conditions préalables sont identifiées, vous devez les résoudre et exécuter à nouveau la commande revert_to.

+

NOTE: L'utilisation d'une console système pour surveiller le processus de restauration affiche des détails supérieurs à ceux affichés dans le nodeshell.

+
Si AUTOBOOT est vrai, lorsque la commande est terminée, le nœud redémarre en ONTAP.

+
Si AUTOBOOT est faux, lorsque la commande termine l'invite DU CHARGEUR s'affiche. Entrez `yes` pour revenir en arrière, utilisez ensuite `boot_ontap` pour redémarrer manuellement le nœud.

. Une fois le nœud redémarré, vérifiez que le nouveau logiciel exécute : `system node image show`
+
Dans l'exemple suivant, image1 est la nouvelle version de ONTAP et est définie comme la version actuelle sur le noeud 0 :

+
[listing]
----
cluster1::*> system node image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    X.X.X       MM/DD/YYYY TIME
         image2  false   false   Y.Y.Y      MM/DD/YYYY TIME
node1
         image1  true    false   X.X.X      MM/DD/YYYY TIME
         image2  false   true    Y.Y.Y      MM/DD/YYYY TIME
4 entries were displayed.
----
. [[étape-16]]Vérifiez que l'état de restauration est complet pour chaque nœud : `system node upgrade-revert show -node nodename`
+
L'état doit être indiqué comme « complet », « non requis » ou « aucune entrée de table n'est renvoyée ».

. Recommencez <<step-6>> à <<step-16>> Sur l'autre nœud de la paire HA.
. Si le cluster ne comprend que deux nœuds, réactivez le cluster HA : `cluster ha modify -configured true`
. [[STEP-19]]réactivez le basculement du stockage sur les deux nœuds s'il était auparavant désactivé : `storage failover modify -node nodename -enabled true`
. Recommencez <<step-5>> à <<step-19>> Pour chaque paire haute disponibilité supplémentaire et les deux clusters dans la configuration MetroCluster.

