---
permalink: revert/task_reverting_an_ontap_cluster.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, cluster 
summary: Pour mettre le cluster hors ligne afin de revenir à une version antérieure de ONTAP, vous devez désactiver le basculement du stockage et les LIF de données, mettre en place des conditions préalables à la reversion, rétablir les configurations du cluster et du système de fichiers sur un nœud, puis répéter le processus pour chaque nœud supplémentaire du cluster. 
---
= Ne restaurez pas un cluster ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le rétablissement d'un cluster ONTAP est perturbateur. Vous devez mettre le cluster hors ligne pendant la durée de la restauration. Vous ne devez pas restaurer un cluster de production sans l'aide du support technique.

Pour rétablir un nouveau cluster ou un cluster test, vous devez désactiver le basculement du stockage, les LIFs de données et les conditions de retour ; vous devez ensuite rétablir la configuration du cluster et du système de fichiers sur chaque nœud du cluster.

.Avant de commencer.
* Vous devez avoir terminé le link:task_things_to_verify_before_revert.html["vérifications avant restauration"].
* Vous devez avoir rempli le champ requis link:concept_pre_revert_checks.html["Pré-vérifie votre version ONTAP spécifique"].
* Tu aurais dû link:task_download_and_install_ontap_software_image.html["téléchargé et installé l'image du logiciel ONTAP cible"] .




== Étape 1 : préparer le cluster pour la restauration

Avant de rétablir l'un de vos nœuds de cluster, vérifiez que votre image ONTAP cible est installée et vous devez désactiver toutes les LIFs de données dans le cluster.

.Étapes
. Définissez le niveau de privilège sur avancé :
+
[source, cli]
----
set -privilege advanced
----
+
Entrez *y* lorsque vous êtes invité à continuer.

. Vérifier que le logiciel ONTAP cible est installé :
+
[source, cli]
----
system image show
----
+
L'exemple suivant montre que la version 9.13.1 est installée comme image alternative sur les deux nœuds :

+
[listing]
----
cluster1::*> system image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    9.14.1      MM/DD/YYYY TIME
         image2  false   false   9.13.1      MM/DD/YYYY TIME
node1
         image1  true    true    9.14.1      MM/DD/YYYY TIME
         image2  false   false   9.13.1      MM/DD/YYYY TIME
4 entries were displayed.
----
. Désactiver toutes les LIFs de données du cluster :
+
[source, cli]
----
network interface modify {-role data} -status-admin down
----
. Déterminez si vous avez des relations FlexCache entre clusters :
+
[source, cli]
----
flexcache origin show-caches -relationship-type inter-cluster
----
. Si des flexcar inter-cluster sont présents, désactiver les lifs de données sur le cluster de cache :
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -status-admin down
----




== Étape 2 : restaurez les nœuds du cluster

Pour rétablir votre cluster, vous devez restaurer le premier nœud d'une paire haute disponibilité, puis restaurer le nœud partenaire. Vous répétez ensuite ce processus pour chaque paire haute disponibilité de votre cluster jusqu'à ce que tous les nœuds soient restaurés. Si vous disposez d'une configuration MetroCluster, vous devez répéter ces étapes pour les deux clusters de la configuration.

[role="tabbed-block"]
====
.4 nœuds ou plus
--
.Étapes
. Connectez-vous au nœud que vous souhaitez restaurer.
+
Pour restaurer un nœud, vous devez être connecté au cluster par l'intermédiaire du LIF de node management.

. Désactiver le basculement du stockage pour les nœuds de la paire haute disponibilité :
+
[source, cli]
----
storage failover modify -node <nodename> -enabled false
----
+
Il n'est nécessaire de désactiver qu'une seule fois le basculement du stockage pour la paire haute disponibilité. Lorsque vous désactivez le basculement du stockage pour un nœud, le basculement du stockage est également désactivé sur le partenaire du nœud.

. Définissez l'image du logiciel ONTAP cible du nœud sur l'image par défaut :
+
[source, cli]
----
system image modify -node <nodename> -image <target_image> -isdefault true
----
. Vérifiez que l'image logicielle ONTAP cible est définie en tant qu'image par défaut du nœud que vous rétablissement :
+
[source, cli]
----
system image show
----
+
L'exemple suivant montre que la version 9.13.1 est définie comme image par défaut sur le nœud 0 :

+
[listing]
----
cluster1::*> system image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  false   true    9.14.1      MM/DD/YYYY TIME
         image2  true    false   9.13.1      MM/DD/YYYY TIME
node1
         image1  true    true    9.14.1      MM/DD/YYYY TIME
         image2  false   false   9.13.1      MM/DD/YYYY TIME
4 entries were displayed.
----
. Vérifiez que le nœud est prêt pour la nouvelle version :
+
[source, cli]
----
system node revert-to -node <nodename> -check-only true -version 9.x
----
+
Le `check-only` paramètre identifie les conditions préalables qui doivent être résolues avant le rétablissement, telles que la désactivation de la règle de snapshot ou la suppression des snapshots créés après la mise à niveau vers la version ultérieure de ONTAP.

+
L' `-version`option fait référence à la version ONTAP vers laquelle vous revenez. Par exemple, si vous revenez de 9.14.1 à 9.13.1, la valeur correcte de l' `-version`option est 9.13.1.

. Ne rétablit pas la configuration de cluster du nœud:
+
[source, cli]
----
system node revert-to -node <nodename> -version 9.x
----
+
La configuration du cluster est rétablie, puis vous êtes déconnecté du clustershell.

. Attendez l'invite de connexion, puis entrez *non* lorsque vous êtes invité à vous connecter au systemshell.
+
L'affichage de l'invite de connexion peut prendre jusqu'à 30 minutes ou plus.

. Connectez-vous au cluster shell avec admin.
. Passez au nodeshell :
+
[source, cli]
----
run -node <nodename>
----
+
Après une nouvelle connexion au clustershell, quelques minutes suffisent avant qu'il soit prêt à accepter la commande nodeshell. Si la commande échoue, attendez quelques minutes et réessayez.

. Ne rétablit pas la configuration du système de fichiers du nœud:
+
[source, cli]
----
revert_to 9.x
----
+
Cette commande vérifie que la configuration du système de fichiers du nœud est prête à être rétablie, puis la restaure. Si des conditions préalables sont identifiées, vous devez les résoudre puis relancer la `revert_to` commande.

+

NOTE: L'utilisation d'une console système pour surveiller le processus de restauration affiche des détails supérieurs à ceux affichés dans le nodeshell.

+
Si AUTOBOOT est vrai, lorsque la commande est terminée, le nœud redémarre en ONTAP.

+
Si AUTOBOOT est FALSE, lorsque la commande est terminée, l'invite Loader s'affiche. Entrez `yes` pour revenir à la version précédente, puis utilisez `boot_ontap` pour redémarrer manuellement le nœud.

. Une fois le nœud redémarré, vérifiez que le nouveau logiciel exécute :
+
[source, cli]
----
system node image show
----
+
Dans l'exemple suivant, image1 est la nouvelle version de ONTAP et est définie comme la version actuelle sur le noeud 0 :

+
[listing]
----
cluster1::*> system node image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    X.X.X       MM/DD/YYYY TIME
         image2  false   false   Y.Y.Y      MM/DD/YYYY TIME
node1
         image1  true    false   X.X.X      MM/DD/YYYY TIME
         image2  false   true    Y.Y.Y      MM/DD/YYYY TIME
4 entries were displayed.
----
. Vérifiez que l'état de restauration du nœud est terminé :
+
[source, cli]
----
system node upgrade-revert show -node <nodename>
----
+
L'état doit être indiqué comme « complet », « non requis » ou « aucune entrée de table n'est renvoyée ».

. Répétez ces étapes pour l'autre nœud de la paire haute disponibilité, puis pour chaque paire haute disponibilité supplémentaire.
+
Si vous disposez d'une configuration MetroCluster, vous devez répéter ces étapes sur les deux clusters de la configuration

. Une fois tous les nœuds rétablis, réactivez la haute disponibilité pour le cluster :
+
[source, cli]
----
storage failover modify -node* -enabled true
----


--
.cluster à 2 nœuds
--
. Connectez-vous au nœud que vous souhaitez restaurer.
+
Pour restaurer un nœud, vous devez être connecté au cluster par l'intermédiaire du LIF de node management.

. Désactivation de la haute disponibilité (HA) du cluster :
+
[source, cli]
----
cluster ha modify -configured false
----
. Désactiver le basculement du stockage :
+
[source, cli]
----
storage failover modify -node <nodename> -enabled false
----
+
Il n'est nécessaire de désactiver qu'une seule fois le basculement du stockage pour la paire haute disponibilité. Lorsque vous désactivez le basculement du stockage pour un nœud, le basculement du stockage est également désactivé sur le partenaire du nœud.

. Définissez l'image du logiciel ONTAP cible du nœud sur l'image par défaut :
+
[source, cli]
----
system image modify -node <nodename> -image <target_image> -isdefault true
----
. Vérifiez que l'image logicielle ONTAP cible est définie en tant qu'image par défaut du nœud que vous rétablissement :
+
[source, cli]
----
system image show
----
+
L'exemple suivant montre que la version 9.13.1 est définie comme image par défaut sur le nœud 0 :

+
[listing]
----
cluster1::*> system image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  false   true    9.14.1      MM/DD/YYYY TIME
         image2  true    false   9.13.1      MM/DD/YYYY TIME
node1
         image1  true    true    9.14.1      MM/DD/YYYY TIME
         image2  false   false   9.13.1      MM/DD/YYYY TIME
4 entries were displayed.
----
. Vérifier si le nœud contient actuellement epsilon :
+
[source, cli]
----
cluster show -node <nodename>
----
+
L'exemple suivant montre que le nœud contient epsilon :

+
[listing]
----
cluster1::*> cluster show -node node1

          Node: node1
          UUID: 026efc12-ac1a-11e0-80ed-0f7eba8fc313
       Epsilon: true
   Eligibility: true
        Health: true
----
+
.. Si le nœud contient epsilon, marquer l'epsilon comme false sur le nœud afin que l'epsilon peut être transféré au partenaire du nœud :
+
[source, cli]
----
cluster modify -node <nodename> -epsilon false
----
.. Transfert d'epsilon vers le partenaire du nœud par le marquage epsilon true sur le nœud partenaire :
+
[source, cli]
----
cluster modify -node <node_partner_name> -epsilon true
----


. Vérifiez que le nœud est prêt pour la nouvelle version :
+
[source, cli]
----
system node revert-to -node <nodename> -check-only true -version 9.x
----
+
Le `check-only` paramètre identifie toutes les conditions qui doivent être résolues avant le rétablissement, telles que la désactivation de la règle de snapshot ou la suppression des snapshots créés après la mise à niveau vers la version ultérieure de ONTAP.

+
Le `-version` Cette option fait référence à la version ONTAP vers laquelle vous revenez. Seules les deux premières valeurs de la version ONTAP sont requises. Par exemple, si vous revenez de la version 9.14.1 à la version 9.13.1, la valeur correcte de `-version` L'option est 9.13.

+
La configuration du cluster est rétablie, puis vous êtes déconnecté du clustershell.

. Ne rétablit pas la configuration de cluster du nœud:
+
[source, cli]
----
system node revert-to -node <nodename> -version 9.x
----
. Attendez l'invite de connexion, puis entrez `No` lorsque vous êtes invité à vous connecter au systemshell.
+
L'affichage de l'invite de connexion peut prendre jusqu'à 30 minutes ou plus.

. Connectez-vous au cluster shell avec admin.
. Passez au nodeshell :
+
[source, cli]
----
run -node <nodename>
----
+
Après une nouvelle connexion au clustershell, quelques minutes suffisent avant qu'il soit prêt à accepter la commande nodeshell. Si la commande échoue, attendez quelques minutes et réessayez.

. Ne rétablit pas la configuration du système de fichiers du nœud:
+
[source, cli]
----
revert_to 9.x
----
+
Cette commande vérifie que la configuration du système de fichiers du nœud est prête à être rétablie, puis la restaure. Si des conditions préalables sont identifiées, vous devez les résoudre puis relancer la `revert_to` commande.

+

NOTE: L'utilisation d'une console système pour surveiller le processus de restauration affiche des détails supérieurs à ceux affichés dans le nodeshell.

+
Si AUTOBOOT est vrai, lorsque la commande est terminée, le nœud redémarre en ONTAP.

+
Si AUTOBOOT est faux, lorsque la commande termine l'invite DU CHARGEUR s'affiche. Entrez `yes` pour revenir en arrière, utilisez ensuite `boot_ontap` pour redémarrer manuellement le nœud.

. Une fois le nœud redémarré, vérifiez que le nouveau logiciel exécute :
+
[source, cli]
----
system node image show
----
+
Dans l'exemple suivant, image1 est la nouvelle version de ONTAP et est définie comme la version actuelle sur le noeud 0 :

+
[listing]
----
cluster1::*> system node image show
                 Is      Is                 Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------   -------------------
node0
         image1  true    true    X.X.X       MM/DD/YYYY TIME
         image2  false   false   Y.Y.Y      MM/DD/YYYY TIME
node1
         image1  true    false   X.X.X      MM/DD/YYYY TIME
         image2  false   true    Y.Y.Y      MM/DD/YYYY TIME
4 entries were displayed.
----
. Vérifiez que l'état de restauration est complet pour le nœud :
+
[source, cli]
----
system node upgrade-revert show -node <nodename>
----
+
L'état doit être indiqué comme « complet », « non requis » ou « aucune entrée de table n'est renvoyée ».

. Répétez ces étapes sur l'autre nœud de la paire HA.
. Une fois les deux nœuds rétablis, réactivez la haute disponibilité pour le cluster :
+
[source, cli]
----
cluster ha modify -configured true
----
. Réactiver le basculement du stockage sur les deux nœuds :
+
[source, cli]
----
storage failover modify -node <nodename> -enabled true
----


--
====
.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/storage-failover-modify.html["modification du basculement du stockage"^]

