---
permalink: revert/task_things_to_verify_before_revert.html 
sidebar: sidebar 
keywords: ontap, revert, reversion, reverting, downgrade, downgrading, preparation, pre-revert, checks, verification, cluster health, storage health, system time, jobs 
summary: 'Avant de rétablir ONTAP, vous devez vérifier l"état de santé du cluster, l"état du stockage et l"heure système. Vérifiez également qu"aucune tâche n"est en cours d"exécution sur le cluster.' 
---
= Vérifications système à effectuer avant la restauration d'un cluster ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de rétablir un cluster ONTAP, vous devez vérifier l'état de santé, l'état du stockage et l'heure système de votre cluster. Vérifiez également qu'aucune tâche n'est en cours d'exécution sur le cluster.



== Vérification de l'état du cluster

Avant de rétablir un cluster ONTAP, vérifiez que les nœuds sont sains et admissibles à participer au cluster et que le cluster a le quorum.

.Étapes
. Vérifiez que les nœuds du cluster sont en ligne et peuvent participer au cluster :
+
[source, cli]
----
cluster show
----
+
Dans cet exemple, tous les nœuds sont sains et peuvent participer au cluster.

+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
node0                 true    true
node1                 true    true
----
+
Si l'un des nœuds est défectueux ou non éligible, vérifiez la présence d'erreurs dans les journaux EMS et effectuez des actions correctives.

. Définissez le niveau de privilège sur avancé :
+
[source, cli]
----
set -privilege advanced
----
+
Entrez `y` pour continuer.

. Vérifier les détails de configuration pour chaque processus RDB
+
** L'époque de la base de données relationnelle et les séries de tests de base de données doivent correspondre pour chaque nœud.
** Le maître de quorum par anneau doit être le même pour tous les nœuds.
+
Notez que chaque anneau peut avoir un maître de quorum différent.

+
[cols="2*"]
|===
| Pour afficher ce processus RDB... | Entrez cette commande... 


 a| 
Application de gestion
 a| 
[source, cli]
----
cluster ring show -unitname mgmt
----


 a| 
Base de données d'emplacement de volume
 a| 
[source, cli]
----
cluster ring show -unitname vldb
----


 a| 
Gestionnaire d'interface virtuelle
 a| 
[source, cli]
----
cluster ring show -unitname vifmgr
----


 a| 
Démon de gestion DU SAN
 a| 
[source, cli]
----
cluster ring show -unitname bcomd
----
|===
+
Cet exemple représente le processus de la base de données d'emplacements de volumes :

+
[listing]
----
cluster1::*> cluster ring show -unitname vldb
Node      UnitName Epoch    DB Epoch DB Trnxs Master    Online
--------- -------- -------- -------- -------- --------- ---------
node0     vldb     154      154      14847    node0     master
node1     vldb     154      154      14847    node0     secondary
node2     vldb     154      154      14847    node0     secondary
node3     vldb     154      154      14847    node0     secondary
4 entries were displayed.
----


. Retour au niveau de privilège admin :
+
[source, cli]
----
set -privilege admin
----
. Si vous travaillez dans un environnement SAN, vérifiez que chaque nœud se trouve dans un quorum SAN :
+
[source, cli]
----
event log show  -severity informational -message-name scsiblade.*
----
+
Le message d'événement scsiBlade le plus récent pour chaque nœud doit indiquer que le SCSI-Blade est quorum.

+
[listing]
----
cluster1::*> event log show  -severity informational -message-name scsiblade.*
Time             Node       Severity       Event
---------------  ---------- -------------- ---------------------------
MM/DD/YYYY TIME  node0      INFORMATIONAL  scsiblade.in.quorum: The scsi-blade ...
MM/DD/YYYY TIME  node1      INFORMATIONAL  scsiblade.in.quorum: The scsi-blade ...
----


.Informations associées
link:../system-admin/index.html["Administration du système"]



== Vérification de l'état du stockage

Avant de rétablir un cluster ONTAP, vous devez vérifier l'état de vos disques, agrégats et volumes.

.Étapes
. Vérification de l'état du disque :
+
[cols="2*"]
|===
| Pour vérifier... | Procédez comme ça... 


 a| 
Disques cassés
 a| 
.. Afficher les éventuels disques défectueux :
+
[source, cli]
----
storage disk show -state broken
----
.. Retirez ou remplacez tout disque endommagé.




 a| 
Disques soumis à des opérations de maintenance ou de reconstruction
 a| 
.. Afficher tous les disques en état de maintenance, en attente ou reconstruction :
+
[source, cli]
----
storage disk show -state maintenance|pending|reconstructing
----
.. Attendez la fin de l'opération de maintenance ou de reconstruction avant de poursuivre.


|===
. Vérifiez que tous les agrégats sont en ligne en affichant l'état du stockage physique et logique, y compris les agrégats de stockage : +
+
[source, cli]
----
storage aggregate show -state !online
----
+
Cette commande affiche les agrégats qui sont _not_ online. Tous les agrégats doivent être en ligne avant et après avoir effectué une mise à niveau ou une nouvelle version majeure.

+
[listing]
----
cluster1::> storage aggregate show -state !online
There are no entries matching your query.
----
. Vérifiez que tous les volumes sont en ligne en affichant les volumes _NOT_ online :
+
[source, cli]
----
volume show -state !online
----
+
Tous les volumes doivent être en ligne avant et après avoir effectué une mise à niveau ou une nouvelle version majeure.

+
[listing]
----
cluster1::> volume show -state !online
There are no entries matching your query.
----
. Vérifiez qu'il n'y a pas de volumes incohérents :
+
[source, cli]
----
volume show -is-inconsistent true
----
+
Consultez l'article de la base de connaissances link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Volume_Showing_WAFL_Inconsistent["Volume affichant des WAFL incohérentes"] sur la manière de traiter les volumes incohérents.



.Informations associées
link:../disks-aggregates/index.html["Gestion des disques et des agrégats"]



== Vérifiez l'heure du système

Avant de rétablir un cluster ONTAP, vérifiez que le protocole NTP est configuré et que l'heure est synchronisée sur l'ensemble du cluster.

.Étapes
. Vérifiez que le cluster est associé à un serveur NTP :
+
[source, cli]
----
cluster time-service ntp server show
----
. Vérifiez que chaque nœud a la même date et l'heure :
+
[source, cli]
----
cluster date show
----
+
[listing]
----
cluster1::> cluster date show
Node      Date                Timezone
--------- ------------------- -------------------------
node0     4/6/2013 20:54:38   GMT
node1     4/6/2013 20:54:38   GMT
node2     4/6/2013 20:54:38   GMT
node3     4/6/2013 20:54:38   GMT
4 entries were displayed.
----




== Vérifiez qu'aucune tâche n'est en cours d'exécution

Avant de rétablir un cluster ONTAP, vous devez vérifier l'état des tâches de cluster. Si des tâches d'agrégat, de volume, de NDMP (vidage ou restauration) ou de snapshot (telles que créer, supprimer, déplacer, modifier, répliquer et monter) sont en cours d'exécution ou en file d'attente, vous devez autoriser les travaux à se terminer avec succès ou arrêter les entrées en file d'attente.

.Étapes
. Consultez la liste des tâches d'agrégat, de volume ou de snapshot en cours d'exécution ou en file d'attente :
+
[source, cli]
----
job show
----
+
Dans cet exemple, deux travaux sont mis en file d'attente :

+
[listing]
----
cluster1::> job show
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
8629   Vol Reaper           cluster1   -              Queued
       Description: Vol Reaper Job
8630   Certificate Expiry Check
                            cluster1   -              Queued
       Description: Certificate Expiry Check
----
. Supprimez tout agrégat, volume ou snapshot en cours d'exécution ou en file d'attente :
+
[source, cli]
----
job delete -id <job_id>
----
. Vérifiez qu'aucune tâche d'agrégat, de volume ou de snapshot n'est en cours d'exécution ou mise en file d'attente :
+
[source, cli]
----
job show
----
+
Dans cet exemple, tous les travaux en cours d'exécution et en file d'attente ont été supprimés :

+
[listing]
----
cluster1::> job show
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
9944   SnapMirrorDaemon_7_2147484678
                            cluster1   node1          Dormant
       Description: Snapmirror Daemon for 7_2147484678
18377  SnapMirror Service Job
                            cluster1   node0          Dormant
       Description: SnapMirror Service Job
2 entries were displayed
----


.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-show.html["affichage du disque de stockage"^]

