---
permalink: smb-admin/add-remove-replace-trusted-domains-preferred-lists-task.html 
sidebar: sidebar 
keywords: add, remove, trust, domain, prefer, cifs, server, modify, list, configure, bidirectional, multidomain, name, mapping, search, add remove or replace trusted domains in preferred trusted domain list, replace 
summary: 'Vous pouvez ajouter ou supprimer des domaines approuvés de la liste des domaines approuvés préférés pour le serveur CIFS ou modifier la liste actuelle. Si vous configurez une liste de domaines de confiance privilégiés, cette liste est utilisée à la place des domaines de confiance bidirectionnels découverts lors de l"exécution de recherches sur le mappage de noms multidomaines.' 
---
= Ajoutez, supprimez ou remplacez des domaines de confiance dans les listes de domaines de confiance préférées
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez ajouter ou supprimer des domaines approuvés de la liste des domaines approuvés préférés pour le serveur SMB ou modifier la liste actuelle. Si vous configurez une liste de domaines de confiance privilégiés, cette liste est utilisée à la place des domaines de confiance bidirectionnels découverts lors de l'exécution de recherches sur le mappage de noms multidomaines.

.Description de la tâche
* Si vous ajoutez des domaines approuvés à une liste existante, la nouvelle liste est fusionnée avec la liste existante et les nouvelles entrées sont placées à la fin Les domaines de confiance sont recherchés dans l'ordre dans lequel ils apparaissent dans la liste des domaines de confiance.
* Si vous supprimez des domaines de confiance de la liste existante et ne spécifiez pas de liste, la liste de domaines de confiance complète pour la machine virtuelle de stockage (SVM) spécifiée est supprimée.
* Si vous modifiez la liste existante des domaines approuvés, la nouvelle liste remplace la liste existante.


[NOTE]
====
Vous devez entrer uniquement les domaines de confiance bidirectionnels dans la liste des domaines de confiance préférés. Même si vous pouvez entrer des domaines de confiance sortants ou entrants dans la liste de domaines préférés, ils ne sont pas utilisés lors de recherches de mappage de noms de domaines multiples. ONTAP ignore l'entrée du domaine unidirectionnel et passe au domaine de confiance bidirectionnel suivant dans la liste.

====
.Étape
. Effectuez l'une des opérations suivantes :
+
|===
| Si vous souhaitez effectuer les opérations suivantes avec la liste des domaines de confiance préférés... | Utilisez la commande... 


 a| 
Ajouter des domaines de confiance à la liste
 a| 
`+vserver cifs domain name-mapping-search add -vserver _vserver_name_ -trusted-domains FQDN, ...+`



 a| 
Supprimer des domaines de confiance de la liste
 a| 
`+vserver cifs domain name-mapping-search remove -vserver _vserver_name_ [-trusted-domains FQDN, ...]+`



 a| 
Modifier la liste existante
 a| 
`+vserver cifs domain name-mapping-search modify -vserver _vserver_name_ -trusted-domains FQDN, ...+`

|===


.Exemples
La commande suivante ajoute deux domaines de confiance (cifs1.example.com et cifs2.example.com) à la liste de domaines de confiance privilégiée utilisée par le SVM vs1 :

[listing]
----
cluster1::> vserver cifs domain name-mapping-search add -vserver vs1 -trusted-domains cifs1.example.com, cifs2.example.com
----
La commande suivante supprime deux domaines de confiance de la liste utilisée par le SVM vs1 :

[listing]
----
cluster1::> vserver cifs domain name-mapping-search remove -vserver vs1 -trusted-domains cifs1.example.com, cifs2.example.com
----
La commande suivante modifie la liste de domaines approuvés utilisée par le SVM vs1. La nouvelle liste remplace la liste d'origine :

[listing]
----
cluster1::> vserver cifs domain name-mapping-search modify -vserver vs1 -trusted-domains cifs3.example.com
----
.Informations associées
xref:display-preferred-trusted-domain-list-task.adoc[Affichage d'informations sur la liste de domaines de confiance préférée]
