---
permalink: smb-admin/add-preferred-domain-controllers-task.html 
sidebar: sidebar 
keywords: ontap, discover, domain, controller, dns, list, add preferred domain controllers 
summary: ONTAP détecte automatiquement les contrôleurs de domaine via DNS. Vous pouvez éventuellement ajouter un ou plusieurs contrôleurs de domaine à la liste des contrôleurs de domaine privilégiés pour un domaine spécifique. 
---
= Ajouter des contrôleurs de domaine préférés
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP détecte automatiquement les contrôleurs de domaine via DNS. Vous pouvez éventuellement ajouter un ou plusieurs contrôleurs de domaine à la liste des contrôleurs de domaine privilégiés pour un domaine spécifique.

Si une liste de contrôleurs de domaine privilégiés existe déjà pour le domaine spécifié, la nouvelle liste est fusionnée avec la liste existante.

.Étape
. Pour ajouter à la liste des contrôleurs de domaine privilégiés, entrez la commande suivante : +
`vserver cifs domain preferred-dc add -vserver _vserver_name_ -domain _domain_name_ -preferred-dc IP_address, ...+`
+
`-vserver _vserver_name_` Spécifie le nom de la machine virtuelle de stockage (SVM).

+
`-domain _domain_name_` Spécifie le nom Active Directory complet du domaine auquel appartiennent les contrôleurs de domaine spécifiés.

+
`-preferred-dc _IP_address_`,... indique une ou plusieurs adresses IP des contrôleurs de domaine préférés, en tant que liste délimitée par des virgules, par ordre de préférence.



La commande suivante ajoute des contrôleurs de domaine 172.17.102.25 et 172.17.102.24 à la liste des contrôleurs de domaine préférés que le serveur SMB du SVM vs1 utilise pour gérer l'accès externe au domaine cifs.lab.example.com.

[listing]
----
cluster1::> vserver cifs domain preferred-dc add -vserver vs1 -domain cifs.lab.example.com -preferred-dc 172.17.102.25,172.17.102.24
----
xref:commands-manage-preferred-domain-controllers-reference.adoc[Commandes pour la gestion des contrôleurs de domaine privilégiés]
