---
permalink: smb-admin/additional-information-concept.html 
sidebar: sidebar 
keywords: additional, resource, configure, dynamic, access, control, central, policies, policy, where to find additional information about configuring and using dynamic access control and central policies 
summary: 'Des ressources supplémentaires sont disponibles pour vous aider à configurer et utiliser le contrôle d"accès dynamique et les stratégies d"accès central.' 
---
= Où trouver des informations supplémentaires sur la configuration et l'utilisation du contrôle d'accès dynamique et des stratégies d'accès central
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Des ressources supplémentaires sont disponibles pour vous aider à configurer et utiliser le contrôle d'accès dynamique et les stratégies d'accès central.

Vous trouverez des informations sur la configuration des stratégies de contrôle d'accès dynamique et d'accès central dans Active Directory dans la bibliothèque Microsoft TechNet.

http://["Microsoft TechNet : présentation des scénarios de contrôle d'accès dynamique"]

http://["Microsoft TechNet : scénario de stratégie d'accès centralisé"]

Les références suivantes peuvent vous aider à configurer le serveur SMB afin qu'il utilise et prend en charge les stratégies de contrôle d'accès dynamique et d'accès central :

* *Utilisation de stratégies de groupe sur le serveur SMB*
+
xref:applying-group-policy-objects-concept.adoc[Application d'objets de stratégie de groupe aux serveurs SMB]

* *Configuration de l'audit NAS sur le serveur SMB*
+
link:../nas-audit/index.html["Audit et suivi de sécurité SMB et NFS"]


