---
permalink: smb-admin/assign-privileges-concept.html 
sidebar: sidebar 
keywords: assign, privilege, direct, local, user, domain, group, capabiltiies, capability, how to assign privileges 
summary: Vous pouvez attribuer des privilèges directement aux utilisateurs locaux ou aux utilisateurs du domaine. Vous pouvez également affecter des utilisateurs à des groupes locaux dont les privilèges attribués correspondent aux fonctions que vous souhaitez que ces utilisateurs disposent. 
---
= En savoir plus sur l'attribution des privilèges SMB ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez attribuer des privilèges directement aux utilisateurs locaux ou aux utilisateurs du domaine. Vous pouvez également affecter des utilisateurs à des groupes locaux dont les privilèges attribués correspondent aux fonctions que vous souhaitez que ces utilisateurs disposent.

* Vous pouvez attribuer un ensemble de privilèges à un groupe que vous créez.
+
Vous ajoutez ensuite un utilisateur au groupe disposant des privilèges que vous souhaitez que cet utilisateur dispose.

* Vous pouvez également attribuer des utilisateurs locaux et des utilisateurs de domaine à des groupes prédéfinis dont les privilèges par défaut correspondent aux privilèges que vous souhaitez accorder à ces utilisateurs.


.Informations associées
* xref:add-privileges-local-domain-users-groups-task.adoc[Ajout de privilèges aux utilisateurs ou groupes locaux ou de domaine]
* xref:remove-privileges-local-domain-users-groups-task.adoc[Suppression des privilèges des utilisateurs ou groupes locaux ou de domaine]
* xref:reset-privileges-local-domain-users-groups-task.adoc[Réinitialisation des privilèges pour les utilisateurs et groupes locaux ou de domaine]
* xref:configure-bypass-traverse-checking-concept.adoc[Configuration de la vérification de la traverse de dérivation]

