---
permalink: smb-admin/automatic-node-referrals-client-concept.html 
sidebar: sidebar 
keywords: referral, client, perspective, windows, dfstuil, exe, utility, monitor, client-side, smb, automatic, how to monitor client-side smb automatic node referral information using a windows client 
summary: 'Pour déterminer les références faites du point de vue du client, vous pouvez utiliser l"utilitaire Windows dfsutil.exe.' 
---
= Surveiller les informations de renvoi automatique de nœud SMB côté client à l'aide d'un client Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour déterminer les références faites du point de vue du client, vous pouvez utiliser Windows `dfsutil.exe` informatique.

Le kit Remote Server Administration Tools (RSAT) disponible avec les clients Windows 7 et versions ultérieures contient le `dfsutil.exe` informatique. Cet utilitaire vous permet d'afficher des informations sur le contenu du cache de référence ainsi que des informations sur chaque référence que le client utilise actuellement. Vous pouvez également utiliser l'utilitaire pour effacer le cache de référence du client. Pour plus d'informations, consultez la bibliothèque Microsoft TechNet.

.Informations associées
http://["Bibliothèque Microsoft TechNet : technet.microsoft.com/en-us/library/"]
