---
permalink: smb-admin/branchcache-when-reverting-concept.html 
sidebar: sidebar 
keywords: revert, ontap, release, support, branchcache, what happens to branchcache when reverting 
summary: Il est important de comprendre ce qui se passe lorsque vous restaurez ONTAP vers une version qui ne prend pas en charge BranchCache. 
---
= Utilisation de BranchCache lors du rétablissement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il est important de comprendre ce qui se passe lorsque vous restaurez ONTAP vers une version qui ne prend pas en charge BranchCache.

* Lorsque vous restaurez vers une version d'ONTAP qui ne prend pas en charge BranchCache, les partages SMB n'publient pas de fonctionnalités de BranchCache pour les clients compatibles avec BranchCache. Ainsi, les clients ne demandent pas d'informations de hachage.
+
À la place, ils demandent le véritable contenu à l'aide de demandes de lecture SMB normales. En réponse à la demande de contenu, le serveur SMB envoie le contenu réel stocké sur la machine virtuelle de stockage (SVM).

* Lorsqu'un nœud qui héberge un magasin de hachage est rétabli dans une version qui ne prend pas en charge BranchCache, l'administrateur du stockage doit restaurer manuellement la configuration de BranchCache à l'aide d'une commande imprimée pendant la restauration.
+
Cette commande supprime la configuration de BranchCache et des hachages.

+
Une fois la restauration terminée, l'administrateur du stockage peut supprimer manuellement le répertoire qui contient le magasin de hachage si nécessaire.



xref:delete-branchcache-config-task.html[Suppression de la configuration de BranchCache sur les SVM]
