---
permalink: smb-admin/commands-oplocks-volumes-qtrees-reference.html 
sidebar: sidebar 
keywords: oplock, client, lock, file, cache, performance, operation, qtree, command, enabling, enable, disabling, disable, volume, commands for enabling or disabling oplocks on volumes and qtrees 
summary: 'Les oplocks permettent aux clients de verrouiller des fichiers et de mettre du contenu en cache localement, ce qui peut augmenter les performances des opérations sur les fichiers. Vous devez connaître les commandes permettant d"activer ou de désactiver les oplocks sur des volumes ou des qtrees. Vous devez également savoir quand vous pouvez activer ou désactiver les oplocks sur des volumes et des qtrees.' 
---
= Commandes pour l'activation ou la désactivation des oplocks sur des volumes et des qtrees
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les oplocks permettent aux clients de verrouiller des fichiers et de mettre du contenu en cache localement, ce qui peut augmenter les performances des opérations sur les fichiers. Vous devez connaître les commandes permettant d'activer ou de désactiver les oplocks sur des volumes ou des qtrees. Vous devez également savoir quand vous pouvez activer ou désactiver les oplocks sur des volumes et des qtrees.

* Les oplocks sont activés par défaut sur les volumes.
* Vous ne pouvez pas désactiver les oplocks lorsque vous créez un volume.
* Vous pouvez à tout moment activer ou désactiver les oplocks sur des volumes existants pour des SVM.
* Vous pouvez activer les oplocks sur des qtrees pour les SVM.
+
Le paramètre du mode oplock est une propriété de l'ID qtree 0, le qtree par défaut que tous les volumes ont. Si vous ne spécifiez pas de paramètre oplock lors de la création d'un qtree, le qtree hérite du paramètre oplock du volume parent, qui est activé par défaut. Cependant, si vous spécifiez un paramètre oplock sur le nouveau qtree, il est prioritaire sur le paramètre oplock sur le volume.



|===
| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Activez les oplocks sur des volumes ou des qtrees
 a| 
`volume qtree oplocks` avec le `-oplock-mode` paramètre défini sur `enable`



 a| 
Désactiver les oplocks sur des volumes ou des qtrees
 a| 
`volume qtree oplocks` avec le `-oplock-mode` paramètre défini sur `disable`

|===
xref:monitor-oplock-status-task.adoc[Surveillance de l'état du oplock]
