---
permalink: smb-admin/commands-manage-security-policy-jobs-reference.html 
sidebar: sidebar 
keywords: ontap, command, pausing, pause, resuming, resume, stop, display, information, security, policy, job, commands for managing security policy jobs 
summary: 'Des commandes ONTAP permettent d"interrompre, de reprendre, d"arrêter et d"afficher des informations sur les tâches de stratégie de sécurité.' 
---
= Commandes pour la gestion des tâches de stratégie de sécurité dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Des commandes ONTAP permettent d'interrompre, de reprendre, d'arrêter et d'afficher des informations sur les tâches de stratégie de sécurité.

|===
| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Interrompre les tâches de stratégie de sécurité
 a| 
`vserver security file-directory job pause ‑vserver vserver_name -id integer`



 a| 
Reprendre les tâches de stratégie de sécurité
 a| 
`vserver security file-directory job resume ‑vserver vserver_name -id integer`



 a| 
Affiche des informations sur les tâches de stratégie de sécurité
 a| 
`vserver security file-directory job show ‑vserver vserver_name` Vous pouvez déterminer l'ID d'un travail à l'aide de cette commande.



 a| 
Arrêtez les tâches de stratégie de sécurité
 a| 
`vserver security file-directory job stop ‑vserver vserver_name -id integer`

|===
Pour en savoir plus, `vserver security file-directory job` consultez le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+job["Référence de commande ONTAP"^].
