---
permalink: smb-admin/commands-manage-ntfs-security-descriptors-reference.html 
sidebar: sidebar 
keywords: ontap, comand, managing, manage, security, descriptor, create, modify, delete, display, information, commands for managing ntfs security descriptors 
summary: Il existe des commandes ONTAP spécifiques pour gérer les descripteurs de sécurité. Vous pouvez créer, modifier, supprimer et afficher des informations sur les descripteurs de sécurité. 
---
= Commandes ONTAP pour la gestion des descripteurs de sécurité NTFS sur les serveurs SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il existe des commandes ONTAP spécifiques pour gérer les descripteurs de sécurité. Vous pouvez créer, modifier, supprimer et afficher des informations sur les descripteurs de sécurité.

|===
| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Créer des descripteurs de sécurité NTFS
 a| 
`vserver security file-directory ntfs create`



 a| 
Modifiez les descripteurs de sécurité NTFS existants
 a| 
`vserver security file-directory ntfs modify`



 a| 
Affiche des informations sur les descripteurs de sécurité NTFS existants
 a| 
`vserver security file-directory ntfs show`



 a| 
Supprimez les descripteurs de sécurité NTFS
 a| 
`vserver security file-directory ntfs delete`

|===
Pour en savoir plus, `vserver security file-directory ntfs` consultez le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+ntfs["Référence de commande ONTAP"^].
