---
permalink: smb-admin/configure-branchcache-enabled-shares-concept.html 
sidebar: sidebar 
keywords: configure, branchcache, smb server, office, enable, smb, share, content, client, configure branchache-enabled smb shares 
summary: Une fois que vous avez configuré BranchCache sur le serveur SMB et dans la succursale, vous pouvez activer BranchCache sur des partages SMB contenant du contenu que vous souhaitez autoriser les clients des succursales à mettre en cache. 
---
= Configurer les partages SMB compatibles avec BranchCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois que vous avez configuré BranchCache sur le serveur SMB et dans la succursale, vous pouvez activer BranchCache sur des partages SMB contenant du contenu que vous souhaitez autoriser les clients des succursales à mettre en cache.

La mise en cache de BranchCache peut être activée sur tous les partages SMB sur le serveur SMB ou sur la base du partage par partage.

* Si vous activez BranchCache sur le partage à partage, vous pouvez activer BranchCache pendant la création du partage ou en modifiant les partages existants.
+
Si vous activez la mise en cache sur un partage SMB existant, ONTAP commence des hachages de calcul et envoie des métadonnées aux clients demandant du contenu dès que vous activez BranchCache sur ce partage.

* Les clients qui disposent d'une connexion SMB existante vers un partage n'bénéficient pas de la prise en charge de BranchCache si ce partage est ensuite activé.
+
ONTAP annonce la prise en charge de BranchCache pour un partage au moment de la configuration de la session SMB. Les clients qui ont déjà établi des sessions lorsque BranchCache est activé doivent se déconnecter, puis se reconnecter pour utiliser le contenu mis en cache pour ce partage.



[NOTE]
====
Si BranchCache sur un partage SMB est ensuite désactivé, ONTAP arrête d'envoyer les métadonnées au client demandeur. Un client qui a besoin de données l'extrait directement du serveur de contenu (serveur SMB).

====