---
permalink: smb-admin/configure-apply-audit-policies-ntfs-files-folders-task.html 
sidebar: sidebar 
keywords: perform, apply, policies, policy, ntfs, file, folder, ontap, cli, security, descriptor, sacl, descriptor, create, storage, virtual, machine, svm, configure and apply audit policies to ntfs files and folders using the cli 
summary: 'Lorsque vous utilisez l"interface de ligne de commande ONTAP, vous devez effectuer plusieurs étapes pour appliquer des règles d"audit aux fichiers et dossiers NTFS. Tout d"abord, vous créez un descripteur de sécurité NTFS et ajoutez des CLS au descripteur de sécurité. Ensuite, vous créez une stratégie de sécurité et ajoutez des tâches de stratégie. Vous appliquez ensuite la politique de sécurité sur une machine virtuelle de stockage (SVM).' 
---
= Commandes ONTAP pour configurer et appliquer des stratégies d'audit SMB aux fichiers et dossiers NTFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous utilisez l'interface de ligne de commande ONTAP, vous devez effectuer plusieurs étapes pour appliquer des règles d'audit aux fichiers et dossiers NTFS. Tout d'abord, vous créez un descripteur de sécurité NTFS et ajoutez des CLS au descripteur de sécurité. Ensuite, vous créez une stratégie de sécurité et ajoutez des tâches de stratégie. Vous appliquez ensuite la politique de sécurité sur une machine virtuelle de stockage (SVM).

.Description de la tâche
Après avoir appliqué la stratégie de sécurité, vous pouvez surveiller la tâche de stratégie de sécurité, puis vérifier les paramètres de la stratégie d'audit appliquée.


NOTE: Lorsqu'une stratégie d'audit et des CLS associées sont appliquées, les CLS existantes sont écrasées. Il est recommandé de passer en revue les stratégies de sécurité existantes avant d'en créer et d'en appliquer de nouvelles.

.Informations associées
* xref:secure-file-access-storage-level-access-guard-concept.adoc[Découvrez l'accès sécurisé aux fichiers à l'aide de Storage-Level Access Guard]
* xref:limits-when-cli-set-file-folder-security-concept.adoc[Découvrez les limites lors de l'utilisation de commandes pour définir la sécurité des fichiers et des dossiers SMB]
* xref:security-descriptors-apply-file-folder-security-concept.adoc[Utilisez des descripteurs de sécurité pour appliquer la sécurité des fichiers et des dossiers]
* link:../nas-audit/index.html["Audit et suivi de sécurité SMB et NFS"]
* xref:create-ntfs-security-descriptor-file-task.adoc[Créer des descripteurs de sécurité NTFS sur les serveurs]

