---
permalink: smb-admin/configure-ntfs-windows-security-tab-task.html 
sidebar: sidebar 
keywords: configure, standard, ntfs, file, permission, file, folder, windows, security, tab, windows, properties, configure advanced ntfs file permission using the windows security tab 
summary: 'Vous pouvez configurer les autorisations de fichiers NTFS standard sur des fichiers et des dossiers à l"aide de l"onglet sécurité de Windows de la fenêtre Propriétés de Windows.' 
---
= Configurer les autorisations de fichiers NTFS avancées à l'aide de l'onglet Sécurité Windows pour les SVM SMB ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez configurer les autorisations de fichier NTFS standard sur les fichiers et les dossiers en utilisant l'onglet *sécurité Windows* de la fenêtre Propriétés Windows.

.Avant de commencer
L'administrateur effectuant cette tâche doit disposer d'autorisations NTFS suffisantes pour modifier les autorisations sur les objets sélectionnés.

.Description de la tâche
La configuration des autorisations de fichiers NTFS se fait sur un hôte Windows en ajoutant des entrées aux listes de contrôle d'accès discrétionnaire NTFS (DACL) associées à un descripteur de sécurité NTFS. Le descripteur de sécurité est ensuite appliqué aux fichiers et répertoires NTFS. Ces tâches sont traitées automatiquement par l'interface graphique de Windows.

.Étapes
. Dans le menu *Tools* de l'Explorateur Windows, sélectionnez *Map network drive*.
. Renseignez la boîte de dialogue *Map Network Drive* :
+
.. Sélectionnez une lettre *lecteur*.
.. Dans la zone *Folder*, saisissez le nom du serveur CIFS contenant le partage contenant les données auxquelles vous souhaitez appliquer les autorisations et le nom du partage.
+
Si le nom de votre serveur CIFS est ""CIFS_SERVER"" et que votre partage est nommé "`hare1"", vous devez taper `\\CIFS_SERVER\share1`.

+

NOTE: Vous pouvez spécifier l'adresse IP de l'interface de données du serveur CIFS au lieu du nom du serveur CIFS.

.. Cliquez sur *Terminer*.


+
Le lecteur sélectionné est monté et prêt avec la fenêtre de l'Explorateur Windows affichant les fichiers et dossiers contenus dans le partage.

. Sélectionnez le fichier ou le répertoire pour lequel vous souhaitez définir les autorisations de fichier NTFS.
. Cliquez avec le bouton droit de la souris sur le fichier ou le répertoire, puis sélectionnez *Propriétés*.
. Sélectionnez l'onglet *sécurité*.
+
L'onglet *sécurité* affiche la liste des utilisateurs et des groupes pour lesquels les autorisations NTFS sont définies. La zone *autorisations pour* affiche une liste des autorisations Autoriser et refuser en vigueur pour chaque utilisateur ou groupe sélectionné.

. Cliquez sur *Avancé*.
+
La fenêtre Propriétés de Windows affiche des informations sur les autorisations de fichier existantes attribuées aux utilisateurs et aux groupes.

. Cliquez sur *Modifier les autorisations*.
+
La fenêtre autorisations s'ouvre.

. Effectuez les opérations souhaitées :
+
|===
| Les fonctions que vous recherchez... | Procédez comme suit... 


 a| 
Configurez des autorisations NTFS avancées pour un nouvel utilisateur ou un nouveau groupe
 a| 
.. Cliquez sur *Ajouter*.
.. Dans la zone *Entrez le nom de l'objet à sélectionner*, saisissez le nom de l'utilisateur ou du groupe que vous souhaitez ajouter.
.. Cliquez sur *OK*.




 a| 
Modifiez les autorisations NTFS avancées d'un utilisateur ou d'un groupe
 a| 
.. Dans la zone *permissions Entries:*, sélectionnez l'utilisateur ou le groupe dont vous souhaitez modifier les autorisations avancées.
.. Cliquez sur *Modifier*.




 a| 
Supprimez les autorisations NTFS avancées pour un utilisateur ou un groupe
 a| 
.. Dans la zone *permissions Entries:*, sélectionnez l'utilisateur ou le groupe à supprimer.
.. Cliquez sur *Supprimer*.
.. Passez à l'étape 13.


|===
+
Si vous ajoutez des autorisations NTFS avancées sur un nouvel utilisateur ou un nouveau groupe ou si vous modifiez les autorisations avancées NTFS sur un utilisateur ou un groupe existant, la zone entrée d'autorisation de <objet> s'ouvre.

. Dans la zone *appliquer à*, sélectionnez la façon dont vous souhaitez appliquer cette entrée d'autorisation de fichier NTFS.
+
Si vous configurez des autorisations de fichier NTFS sur un seul fichier, la case *appliquer à* n'est pas active. Le paramètre *appliquer à* est défini par défaut sur *cet objet uniquement*.

. Dans la zone *permissions*, sélectionnez les cases *Autoriser* ou *refuser* pour les autorisations avancées que vous souhaitez définir sur cet objet.
+
** Pour autoriser l'accès spécifié, cochez la case *Autoriser*.
** Pour ne pas autoriser l'accès spécifié, cochez la case *Deny*.
Vous pouvez définir des autorisations sur les droits avancés suivants :
** *Contrôle total*
+
Si vous choisissez ce droit avancé, tous les autres droits avancés sont automatiquement choisis (autoriser ou refuser des droits).

** *Dossier traverse / fichier d'exécution*
** *Liste de dossiers / lecture de données*
** *Lire les attributs*
** *Lire les attributs étendus*
** *Créer des fichiers / écrire des données*
** *Créer des dossiers / ajouter des données*
** *Ecrire des attributs*
** *Ecrire des attributs étendus*
** *Supprimer des sous-dossiers et des fichiers*
** *Supprimer*
** *Autorisations de lecture*
** *Modifier les autorisations*
** * Prendre possession*


+

NOTE: Si l'une des zones d'autorisation avancée n'est pas sélectionnable, c'est parce que les autorisations sont héritées de l'objet parent.

. Si vous souhaitez que les sous-dossiers et les fichiers de cet objet héritent de ces autorisations, cochez la case *appliquer ces autorisations aux objets et/ou aux conteneurs dans ce conteneur uniquement*.
. Cliquez sur *OK*.
. Une fois que vous avez terminé d'ajouter, de supprimer ou de modifier des autorisations NTFS, spécifiez le paramètre d'héritage de cet objet :
+
** Sélectionnez la case *inclure les autorisations héritables dans la boîte parent* de cet objet.
+
Il s'agit de la valeur par défaut.

** Sélectionnez la case *remplacer toutes les autorisations d'objet enfant par des autorisations héritables de cet objet*.
+
Ce paramètre n'est pas présent dans la zone autorisations si vous définissez des autorisations de fichier NTFS sur un seul fichier.

+

NOTE: Soyez prudent lorsque vous sélectionnez ce paramètre. Ce paramètre supprime toutes les autorisations existantes sur tous les objets enfants et les remplace par les paramètres d'autorisation de cet objet. Vous pourriez supprimer par inadvertance les autorisations que vous ne souhaitez pas supprimer. Il est particulièrement important lorsque vous définissez des autorisations dans un volume mixte de style de sécurité ou qtree. Si les objets enfant ont un style de sécurité UNIX effectif, la propagation des autorisations NTFS à ces objets enfant entraîne le ONTAP changement de style de sécurité UNIX au style de sécurité NTFS, et toutes les autorisations UNIX sur ces objets enfants sont remplacées par des autorisations NTFS.

** Sélectionnez les deux cases.
** Sélectionnez aucune case.


. Cliquez sur *OK* pour fermer la case *permissions*.
. Cliquez sur *OK* pour fermer la case *Paramètres de sécurité avancés pour <objet>*.
+
Pour plus d'informations sur la définition des autorisations NTFS avancées, consultez votre documentation Windows.



.Informations associées
xref:create-ntfs-security-descriptor-file-task.adoc[Configurez et appliquez la sécurité des fichiers sur les fichiers et dossiers NTFS à l'aide de l'interface de ligne de commande]

xref:display-file-security-ntfs-style-volumes-task.adoc[Affichage d'informations sur la sécurité des fichiers sur les volumes de style de sécurité NTFS]

xref:display-file-security-mixed-style-volumes-task.adoc[Affichage d'informations sur la sécurité des fichiers sur des volumes de style de sécurité mixtes]

xref:display-file-security-unix-style-volumes-task.adoc[Affichage d'informations sur la sécurité des fichiers sur des volumes de style de sécurité UNIX]
