---
permalink: smb-admin/configure-access-restrictions-anonymous-users-task.html 
sidebar: sidebar 
keywords: anonymous, unauthenticated, user, information, network, cifs, server, option, configure, access, restriction, user, configure access restrictions for anonymous users 
summary: 'Par défaut, un utilisateur anonyme et non authentifié (également appelé utilisateur nul) peut accéder à certaines informations sur le réseau. Vous pouvez utiliser une option de serveur SMB pour configurer les restrictions d"accès pour l"utilisateur anonyme.' 
---
= Configurez les restrictions d'accès SMB ONTAP pour les utilisateurs anonymes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Par défaut, un utilisateur anonyme et non authentifié (également appelé _null user_) peut accéder à certaines informations sur le réseau. Vous pouvez utiliser une option de serveur SMB pour configurer les restrictions d'accès pour l'utilisateur anonyme.

.Description de la tâche
Le `-restrict-anonymous` L'option de serveur SMB correspond au `RestrictAnonymous` Entrée de registre dans Windows.

Les utilisateurs anonymes peuvent lister ou énumérer certains types d'informations système provenant des hôtes Windows sur le réseau, y compris les noms d'utilisateur et les détails, les stratégies de compte et les noms de partage. Vous pouvez contrôler l'accès de l'utilisateur anonyme en spécifiant l'un des trois paramètres de restriction d'accès suivants :

|===
| Valeur | Description 


 a| 
`no-restriction` (valeur par défaut)
 a| 
Spécifie aucune restriction d'accès pour les utilisateurs anonymes.



 a| 
`no-enumeration`
 a| 
Spécifie que seule l'énumération est restreinte pour les utilisateurs anonymes.



 a| 
`no-access`
 a| 
Spécifie que l'accès est restreint pour les utilisateurs anonymes.

|===
.Étapes
. Définissez le niveau de privilège sur avancé : `set -privilege advanced`
. Configurez le paramètre restreindre l'anonymat : `vserver cifs options modify -vserver _vserver_name_ -restrict-anonymous {no-restriction|no-enumeration|no-access}`
. Vérifiez que l'option est réglée sur la valeur souhaitée : `vserver cifs options show -vserver _vserver_name_`
. Retour au niveau de privilège admin : `set -privilege admin`


.Informations associées
xref:server-options-reference.adoc[Options de serveur disponibles]
