---
permalink: smb-admin/configure-offline-files-computer-management-mmc-task.html 
sidebar: sidebar 
keywords: permit, user, cache, file, local, offline, configure, computer management, mmc, microsoft, management, console, configure offline files support on smb shares by using the computer management mmc 
summary: 'Si vous souhaitez autoriser les utilisateurs à mettre en cache des fichiers localement pour une utilisation hors ligne, vous pouvez configurer la prise en charge des fichiers hors ligne à l"aide de la console MMC gestion de l"ordinateur (Microsoft Management Console).' 
---
= Configurer la prise en charge des fichiers hors ligne sur les partages SMB ONTAP à l'aide de la console MMC de gestion de l'ordinateur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous souhaitez autoriser les utilisateurs à mettre en cache des fichiers localement pour une utilisation hors ligne, vous pouvez configurer la prise en charge des fichiers hors ligne à l'aide de la console MMC gestion de l'ordinateur (Microsoft Management Console).

.Étapes
. Pour ouvrir la console MMC sur votre serveur Windows, dans l'Explorateur Windows, cliquez avec le bouton droit de la souris sur l'icône de l'ordinateur local, puis sélectionnez *gérer*.
. Dans le panneau de gauche, sélectionnez *Computer Management*.
. Sélectionnez *action* > *connexion à un autre ordinateur*.
+
La boîte de dialogue Sélectionner un ordinateur s'affiche.

. Tapez le nom du serveur CIFS ou cliquez sur *Browse* pour localiser le serveur CIFS.
+
Si le nom du serveur CIFS est identique au nom d'hôte SVM (Storage Virtual machine), tapez le nom du SVM. Si le nom du serveur CIFS est différent du nom d'hôte du SVM, tapez le nom du serveur CIFS.

. Cliquez sur *OK*.
. Dans l'arborescence de la console, cliquez sur *Outils système* > *dossiers partagés*.
. Cliquez sur *partages*.
. Dans le volet des résultats, cliquez avec le bouton droit de la souris sur le partage.
. Cliquez sur *Propriétés*.
+
Les propriétés du partage sélectionné s'affichent.

. Dans l'onglet *général*, cliquez sur *Paramètres hors ligne*.
+
La boîte de dialogue Paramètres hors ligne s'affiche.

. Configurez les options de disponibilité hors ligne selon les besoins.
. Cliquez sur *OK*.

