---
permalink: smb-admin/configure-security-styles-task.html 
sidebar: sidebar 
keywords: configure, flexvol, volume, security, style, type, permission, data, storage, virtual, machine, svm, configure security styles on flexvol volumes 
summary: 'Configurez le style de sécurité des volumes FlexVol afin de déterminer le type d"autorisations utilisées pour les données sur des volumes FlexVol de la machine virtuelle de stockage (SVM).' 
---
= Configurer des styles de sécurité sur les volumes FlexVol
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Configurez le style de sécurité des volumes FlexVol afin de déterminer le type d'autorisations utilisées pour les données sur des volumes FlexVol de la machine virtuelle de stockage (SVM).

.Étapes
. Effectuez l'une des opérations suivantes :
+
|===


| Si le volume FlexVol... | Utilisez la commande... 


 a| 
N'existe pas encore
 a| 
`volume create` et inclure le `-security-style` paramètre pour spécifier le style de sécurité.



 a| 
Existe déjà
 a| 
`volume modify` et inclure le `-security-style` paramètre pour spécifier le style de sécurité.

|===
+
Les options possibles pour le style de sécurité du volume FlexVol sont `unix`, `ntfs`, ou `mixed`.

+
Si vous ne spécifiez pas de style de sécurité lors de la création d'un volume FlexVol, le volume hérite du style de sécurité du volume racine.

+
Pour plus d'informations sur le `volume create` ou `volume modify` commandes, voir link:../volumes/index.html["Gestion du stockage logique"].

. Pour afficher la configuration, en incluant le style de sécurité du volume FlexVol que vous avez créé, entrez la commande suivante :
+
`volume show -volume volume_name -instance`


