---
permalink: smb-admin/create-ntfs-security-descriptor-audit-task.html 
sidebar: sidebar 
keywords: create, creating, ntfs, security, descriptor, audit, policy, configure, configuring, apply, access, control, list, acl, file, residing, reside, svm, associate, folder, policy, task, create an ntfs security descriptor 
summary: 'La création d"une règle d"audit NTFS est la première étape de la configuration et de l"application des listes de contrôle d"accès (ACL) NTFS aux fichiers et dossiers qui résident au sein des SVM. Vous associerez le descripteur de sécurité au chemin du fichier ou du dossier dans une tâche de stratégie.' 
---
= Créez un descripteur de sécurité NTFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La création d'une règle d'audit NTFS est la première étape de la configuration et de l'application des listes de contrôle d'accès (ACL) NTFS aux fichiers et dossiers qui résident au sein des SVM. Vous associerez le descripteur de sécurité au chemin du fichier ou du dossier dans une tâche de stratégie.

Vous pouvez créer des descripteurs de sécurité NTFS pour les fichiers et les dossiers résidant dans des volumes de style de sécurité NTFS ou pour les fichiers et dossiers résidant sur des volumes de type sécurité mixtes.

Par défaut, lorsqu'un descripteur de sécurité est créé, quatre entrées de contrôle d'accès (ACE) de liste de contrôle d'accès discrétionnaire (DACL) sont ajoutées à ce descripteur de sécurité. Les quatre ACE par défaut sont les suivants :

|===
| Objet | Type d'accès | Droits d'accès | Où appliquer les autorisations 


 a| 
INTÉGRÉ\administrateurs
 a| 
Autoriser
 a| 
Contrôle total
 a| 
ce dossier, sous-dossiers, fichiers



 a| 
INTÉGRÉ\utilisateurs
 a| 
Autoriser
 a| 
Contrôle total
 a| 
ce dossier, sous-dossiers, fichiers



 a| 
PROPRIÉTAIRE DU CRÉATEUR
 a| 
Autoriser
 a| 
Contrôle total
 a| 
ce dossier, sous-dossiers, fichiers



 a| 
AUTORITÉ NT\SYSTÈME
 a| 
Autoriser
 a| 
Contrôle total
 a| 
ce dossier, sous-dossiers, fichiers

|===
Vous pouvez personnaliser la configuration du descripteur de sécurité à l'aide des paramètres facultatifs suivants :

* Propriétaire du Security Descriptor
* Groupe principal du propriétaire
* Indicateurs de contrôle bruts


La valeur de n'importe quel paramètre facultatif est ignorée pour Storage-Level Access Guard. Consultez les pages de manuels pour plus d'informations.

.Étapes
. Si vous souhaitez utiliser les paramètres avancés, définissez le niveau de privilège sur avancé : `set -privilege advanced`
. Créez un Security Descriptor: `vserver security file-directory ntfs create -vserver vserver_name -ntfs-sd SD_nameoptional_parameters`
+
`vserver security file-directory ntfs create -ntfs-sd sd1 -vserver vs1 -owner DOMAIN\joe`

. Vérifiez que la configuration du descripteur de sécurité est correcte : `vserver security file-directory ntfs show -vserver vserver_name -ntfs-sd SD_name`
+
[listing]
----
vserver security file-directory ntfs show -vserver vs1 -ntfs-sd sd1
----
+
[listing]
----
                                     Vserver: vs1
                           Security Descriptor Name: sd1
                   Owner of the Security Descriptor: DOMAIN\joe
----
. Si vous êtes au niveau de privilège avancé, revenez au niveau de privilège admin : `set -privilege admin`

