---
permalink: smb-admin/create-security-policies-file-task.html 
sidebar: sidebar 
keywords: create, creating, file, security, policy, svm, configuring, configure, apply, acl, folder, act, container, entry, applied, create security policies 
summary: 'La création d"une politique de sécurité des fichiers pour les SVM représente la troisième étape de la configuration et de l"application de ces ACL à un fichier ou dossier. Une règle agit comme un conteneur pour différentes tâches, où chaque tâche est une entrée unique qui peut être appliquée à des fichiers ou des dossiers. Vous pouvez ajouter des tâches à la stratégie de sécurité ultérieurement.' 
---
= Créer des stratégies de sécurité
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La création d'une politique de sécurité des fichiers pour les SVM représente la troisième étape de la configuration et de l'application de ces ACL à un fichier ou dossier. Une règle agit comme un conteneur pour différentes tâches, où chaque tâche est une entrée unique qui peut être appliquée à des fichiers ou des dossiers. Vous pouvez ajouter des tâches à la stratégie de sécurité ultérieurement.

.Description de la tâche
Les tâches que vous ajoutez à une stratégie de sécurité contiennent des associations entre le descripteur de sécurité NTFS et les chemins de fichier ou de dossier. Vous devez donc associer la politique de sécurité à chaque SVM (qui contient des volumes de style de sécurité NTFS ou des volumes de type sécurité mixtes).

.Étapes
. Création d'une stratégie de sécurité : `vserver security file-directory policy create -vserver vserver_name -policy-name policy_name`
+
`vserver security file-directory policy create -policy-name policy1 -vserver vs1`

. Vérifiez la stratégie de sécurité : `vserver security file-directory policy show`
+
[listing]
----

            vserver security file-directory policy show
               Vserver          Policy Name
             ------------     --------------
                 vs1              policy1
----

