---
permalink: smb-admin/create-snapshot-config-previous-versions-access-task.html 
sidebar: sidebar 
keywords: previous, version, functionality, available, client, access, snapshot, copies, copy, enable, snapshot, exist, configuration, requirement, create a snapshot configuration to enable previous versions access 
summary: 'Les versions précédentes sont toujours disponibles dans la mesure où l"accès du client aux copies Snapshot est activé et à condition que des copies Snapshot existent. Si votre configuration de copie Snapshot ne répond pas à ces exigences, vous pouvez créer une configuration de copie Snapshot qui le fait.' 
---
= Créez une configuration de snapshot pour activer l'accès aux versions précédentes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les versions précédentes sont toujours disponibles dans la mesure où l'accès du client aux copies Snapshot est activé et à condition que des copies Snapshot existent. Si votre configuration de copie Snapshot ne répond pas à ces exigences, vous pouvez créer une configuration de copie Snapshot qui le fait.

.Étapes
. Si le volume contenant le partage auquel vous souhaitez autoriser l'accès aux versions précédentes n'est pas associé à une stratégie Snapshot, associez une politique Snapshot au volume et activez-la à l'aide du `volume modify` commande.
+
Pour plus d'informations sur l'utilisation du `volume modify` commandes, consultez les pages de manuels.

. Accès aux copies Snapshot à l'aide du `volume modify` pour définir le `-snap-dir` option à `true`.
+
Pour plus d'informations sur l'utilisation du `volume modify` commandes, consultez les pages de manuels.

. Vérifiez que les règles Snapshot sont activées et que l'accès aux répertoires Snapshot est activé à l'aide du `volume show` et `volume snapshot policy show` commandes.
+
Pour plus d'informations sur l'utilisation du `volume show` et `volume snapshot policy show` commandes, consultez les pages de manuels.

+
Pour plus d'informations sur la configuration et la gestion des règles Snapshot et des planifications Snapshot, reportez-vous à la section link:../data-protection/index.html["La protection des données"].



.Informations associées
link:../data-protection/index.html["Protection des données"]
