---
permalink: smb-admin/default-administrative-shares-concept.html 
sidebar: sidebar 
keywords: create, cifs, server, storage, virtual, machine, svm, default, administrative, share, automatic, what the default administrative shares are 
summary: 'Lorsque vous créez un serveur CIFS sur votre SVM (Storage Virtual machine), les partages administratifs par défaut sont automatiquement créés. Vous devez comprendre ce que sont ces partages par défaut et comment ils sont utilisés.' 
---
= En savoir plus sur les partages SMB d'administration par défaut de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous créez un serveur CIFS sur votre SVM (Storage Virtual machine), les partages administratifs par défaut sont automatiquement créés. Vous devez comprendre ce que sont ces partages par défaut et comment ils sont utilisés.

Lors de la création du serveur CIFS, ONTAP crée les partages administratifs par défaut suivants :


NOTE: Depuis ONTAP 9.8, le partage admin$ n'est plus créé par défaut.

* ipc$
* admin$ (ONTAP 9.7 et versions antérieures uniquement)
* c$


Les partages qui se terminent par le caractère $ étant des partages masqués, les partages administratifs par défaut ne sont pas visibles depuis mon ordinateur, mais vous pouvez les afficher à l'aide de dossiers partagés.



== Utilisation des partages IPC$ et admin$ par défaut

Les partages ipc$ et admin$ sont utilisés par ONTAP et ne peuvent pas être utilisés par les administrateurs Windows pour accéder aux données résidant sur la SVM.

* part ipc$
+
La part ipc$ est une ressource qui partage les canaux nommés qui sont essentiels à la communication entre les programmes. Le partage ipc$ est utilisé lors de l'administration à distance d'un ordinateur et lors de l'affichage des ressources partagées d'un ordinateur. Vous ne pouvez pas modifier les paramètres de partage, les propriétés de partage ou les listes de contrôle d’accès du partage ipc$. Vous ne pouvez pas non plus renommer ou supprimer le partage ipc$.

* Partage admin$ (ONTAP 9.7 et versions antérieures uniquement)
+

NOTE: Depuis ONTAP 9.8, le partage admin$ n'est plus créé par défaut.

+
Le partage admin$ est utilisé pendant l'administration à distance du SVM. Le chemin de cette ressource est toujours le chemin vers la racine SVM. Vous ne pouvez pas modifier les paramètres de partage, les propriétés de partage ou les listes de contrôle d'accès pour le partage admin$. Vous ne pouvez pas non plus renommer ou supprimer le partage admin$.





== Utilisation du partage par défaut c$

Le partage c$ est un partage administratif que l'administrateur du cluster ou du SVM peut utiliser pour accéder au volume root du SVM et le gérer.

Voici les caractéristiques de la part c$ :

* Le chemin pour ce partage est toujours le chemin vers le volume root du SVM et ne peut pas être modifié.
* La liste de contrôle d'accès par défaut pour le partage c$ est Administrator / Full Control.
+
Cet utilisateur est le BULILTIN\Administrator. Par défaut, BUILTIN\Administrator peut mapper sur le partage et l'affichage, créer, modifier ou supprimer des fichiers et dossiers dans le répertoire racine mappé. Soyez prudent lorsque vous gérez des fichiers et des dossiers dans ce répertoire.

* Vous pouvez modifier l'ACL du partage c$.
* Vous pouvez modifier les paramètres de partage c$ et les propriétés de partage.
* Vous ne pouvez pas supprimer le partage c$.
* L'administrateur du SVM peut accéder au reste de l'espace de noms du SVM à partir du partage c$ mappé en croisant les jonctions de l'espace de noms.
* Le partage c$ est accessible à l'aide de la console de gestion Microsoft.


.Informations associées
xref:configure-ntfs-windows-security-tab-task.adoc[Configurer les autorisations de fichiers avancées à l'aide de l'onglet Sécurité Windows]
