---
permalink: smb-admin/delete-local-group-task.html 
sidebar: sidebar 
keywords: delete, local, group, storage, virtual, machine, svm, determine, determining, access, right, data, associate, assign, user, privilege, member, delete a local group 
summary: 'Vous pouvez supprimer un groupe local de la machine virtuelle de stockage (SVM) s"il n"est plus nécessaire pour déterminer les droits d"accès aux données associées à ce SVM ou s"il n"est plus nécessaire d"attribuer des droits d"utilisateur de SVM (privilèges) aux membres du groupe.' 
---
= Supprimer un groupe local
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez supprimer un groupe local de la machine virtuelle de stockage (SVM) s'il n'est plus nécessaire pour déterminer les droits d'accès aux données associées à ce SVM ou s'il n'est plus nécessaire d'attribuer des droits d'utilisateur de SVM (privilèges) aux membres du groupe.

Lors de la suppression de groupes locaux, tenez compte des points suivants :

* Le système de fichiers n'est pas modifié.
+
Les descripteurs de sécurité Windows sur les fichiers et les répertoires faisant référence à ce groupe ne sont pas ajustés.

* Si le groupe n'existe pas, une erreur est renvoyée.
* Le groupe _Everyone_ spécial ne peut pas être supprimé.
* Les groupes intégrés tels que _BUILTIN\Administrators_ _BUILTIN\Users_ ne peuvent pas être supprimés.


.Étapes
. Déterminer le nom du groupe local que vous souhaitez supprimer en affichant la liste des groupes locaux sur la SVM : `vserver cifs users-and-groups local-group show -vserver vserver_name`
. Supprimez le groupe local : `vserver cifs users-and-groups local-group delete -vserver _vserver_name_ ‑group-name _group_name_`
. Vérifiez que le groupe est supprimé : `vserver cifs users-and-groups local-user show -vserver _vserver_name_`


L'exemple suivant supprime le groupe local « CIFS_SERVER\sales » associé à la SVM vs1 :

[listing]
----
cluster1::> vserver cifs users-and-groups local-group show -vserver vs1
Vserver   Group Name                   Description
--------- ---------------------------- ----------------------------
vs1       BUILTIN\Administrators       Built-in Administrators group
vs1       BUILTIN\Backup Operators     Backup Operators group
vs1       BUILTIN\Power Users          Restricted administrative privileges
vs1       BUILTIN\Users                All users
vs1       CIFS_SERVER\engineering
vs1       CIFS_SERVER\sales

cluster1::> vserver cifs users-and-groups local-group delete -vserver vs1 -group-name CIFS_SERVER\sales

cluster1::> vserver cifs users-and-groups local-group show -vserver vs1
Vserver   Group Name                   Description
--------- ---------------------------- ----------------------------
vs1       BUILTIN\Administrators       Built-in Administrators group
vs1       BUILTIN\Backup Operators     Backup Operators group
vs1       BUILTIN\Power Users          Restricted administrative privileges
vs1       BUILTIN\Users                All users
vs1       CIFS_SERVER\engineering
----