---
permalink: smb-admin/deploy-offline-files-concept.html 
sidebar: sidebar 
keywords: important, guideline, understand, deploy, offline, file, home, directory, share, showsnapshot, property, set, home, directories, directory, guidelines for deploying offline files 
summary: Il existe certaines directives importantes que vous devez comprendre lorsque vous déployez des fichiers hors ligne sur des partages de répertoires locaux dont la propriété de partage showsnapshot est définie sur des répertoires locaux. 
---
= Instructions pour le déploiement de fichiers hors ligne
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Il existe certaines directives importantes que vous devez comprendre lorsque vous déployez des fichiers hors ligne sur des partages de répertoire personnel qui possèdent le `showsnapshot` propriété de partage définie sur les répertoires d'accueil.

Si le `showsnapshot` La propriété Share est définie sur un partage de répertoire personnel sur lequel les fichiers hors ligne sont configurés. Les clients Windows mettent en cache toutes les copies Snapshot sous `~snapshot` dans le répertoire de base de l'utilisateur.

Les clients Windows mettent en cache toutes les copies Snapshot sous le home Directory si l'un des nombreux éléments suivants est vrai :

* L'utilisateur rend le répertoire personnel disponible hors ligne à partir du client.
+
Le contenu du `~snapshot` le dossier du répertoire personnel est inclus et rendu disponible hors ligne.

* L'utilisateur configure la redirection de dossier pour rediriger un dossier tel que `My Documents` À la racine d'un répertoire local résidant sur le partage CIFS Server.
+
Certains clients Windows peuvent rendre automatiquement le dossier redirigé hors ligne. Si le dossier est redirigé vers la racine du répertoire de base, le `~snapshot` le dossier est inclus dans le contenu hors ligne mis en cache.



[NOTE]
====
Déploiement de fichiers hors ligne où `~snapshot` le dossier est inclus dans les fichiers hors ligne doit être évité. Copies Snapshot dans le `~snapshot` Le dossier contient toutes les données du volume au point où ONTAP a créé la copie Snapshot. Par conséquent, la création d'une copie hors ligne du `~snapshot` la consommation d'un stockage local important dans le dossier du client consomme de la bande passante réseau lors de la synchronisation des fichiers hors ligne, et augmente le temps nécessaire à la synchronisation des fichiers hors ligne.

====