---
permalink: smb-admin/disable-branchcache-shares-concept.html 
sidebar: sidebar 
keywords: branchcache, caching, cache, service, smb, disable, share, share-by-share, basis, configure, temporarily, automatic, disable branchcache on smb shares 
summary: 'Si vous ne souhaitez pas fournir de services de mise en cache de BranchCache sur certains partages SMB, mais que vous pouvez ensuite fournir des services de mise en cache, vous pouvez désactiver BranchCache sur le partage à partager. Si BranchCache est configuré pour assurer la mise en cache sur tous les partages, mais que vous souhaitez désactiver temporairement tous les services de mise en cache, vous pouvez modifier la configuration de BranchCache afin d"arrêter la mise en cache automatique sur tous les partages.' 
---
= Désactivez BranchCache sur les partages SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous ne souhaitez pas fournir de services de mise en cache de BranchCache sur certains partages SMB, mais que vous pouvez ensuite fournir des services de mise en cache, vous pouvez désactiver BranchCache sur le partage à partager. Si BranchCache est configuré pour assurer la mise en cache sur tous les partages, mais que vous souhaitez désactiver temporairement tous les services de mise en cache, vous pouvez modifier la configuration de BranchCache afin d'arrêter la mise en cache automatique sur tous les partages.

Si BranchCache sur un partage SMB est ensuite désactivé après son activation, ONTAP arrête d'envoyer les métadonnées au client qui demande. Client qui a besoin de données la récupère directement depuis le serveur de contenu (serveur CIFS sur la machine virtuelle de stockage (SVM)).

xref:configure-branchcache-enabled-shares-concept.adoc[Configuration de partages SMB compatibles avec BranchCache]
