---
permalink: smb-admin/disable-enable-branchcache-task.html 
sidebar: sidebar 
keywords: disable, branchcache, storage, virtual, machine, svm, changing, change, operating, mode, disable, operate, per-share, automatic, disable or enable branchcache 
summary: 'Vous pouvez désactiver BranchCache sur le serveur virtuel de stockage (SVM) en désactivant le mode d"exploitation BranchCache. Vous pouvez activer BranchCache à tout moment en modifiant le mode d"exploitation afin d"offrir soit des services de BranchCache par partage, soit automatiquement pour tous les partages.' 
---
= Désactiver ou activer BranchCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez désactiver BranchCache sur le serveur virtuel de stockage (SVM) en changeant le mode d'exploitation BranchCache en `disabled`. Vous pouvez activer BranchCache à tout moment en modifiant le mode d'exploitation afin d'offrir soit des services de BranchCache par partage, soit automatiquement pour tous les partages.

.Étapes
. Exécutez la commande appropriée :
+
|===
| Les fonctions que vous recherchez... | Puis entrez les informations suivantes... 


 a| 
Désactivez BranchCache
 a| 
`vserver cifs branchcache modify -vserver vserver_name -operating-mode disable`



 a| 
Activez BranchCache par partage
 a| 
`vserver cifs branchcache modify -vserver vserver_name -operating-mode per-share`



 a| 
Activez BranchCache pour tous les partages
 a| 
`vserver cifs branchcache modify -vserver vserver_name -operating-mode all-shares`

|===
. Vérifiez que le mode de fonctionnement de BranchCache est configuré avec le paramètre souhaité : `vserver cifs branchcache show -vserver vserver_name`


L'exemple suivant désactive BranchCache sur le SVM vs1 :

[listing]
----
cluster1::> vserver cifs branchcache modify -vserver vs1 -operating-mode disable

cluster1::> vserver cifs branchcache show -vserver vs1

                                 Vserver: vs1
          Supported BranchCache Versions: enable_all
                      Path to Hash Store: /hash_data
          Maximum Size of the Hash Store: 20GB
Encryption Key Used to Secure the Hashes: -
        CIFS BranchCache Operating Modes: disable
----