---
permalink: smb-admin/display-group-memberships-local-users-task.html 
sidebar: sidebar 
keywords: display, information, local, group, user, belong, folder, determine, access, file, useful, troubleshoot, display information about group memberships for local users 
summary: 'Vous pouvez afficher des informations sur les groupes locaux auxquels un utilisateur local appartient. Vous pouvez utiliser ces informations pour déterminer l"accès que l"utilisateur doit avoir aux fichiers et dossiers. Ces informations peuvent être utiles pour déterminer les droits d"accès que l"utilisateur doit posséder aux fichiers et dossiers ou pour résoudre les problèmes d"accès aux fichiers.' 
---
= Affiche des informations sur les membres de groupe pour les utilisateurs locaux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher des informations sur les groupes locaux auxquels un utilisateur local appartient. Vous pouvez utiliser ces informations pour déterminer l'accès que l'utilisateur doit avoir aux fichiers et dossiers. Ces informations peuvent être utiles pour déterminer les droits d'accès que l'utilisateur doit posséder aux fichiers et dossiers ou pour résoudre les problèmes d'accès aux fichiers.

Vous pouvez personnaliser la commande pour afficher uniquement les informations que vous souhaitez afficher.

.Étape
. Effectuez l'une des opérations suivantes :
+
|===
| Les fonctions que vous recherchez... | Entrez la commande... 


 a| 
Afficher les informations d'appartenance des utilisateurs locaux pour un utilisateur local spécifié
 a| 
`vserver cifs users-and-groups local-user show-membership -user-name _user_name_`



 a| 
Affiche les informations d'appartenance de l'utilisateur local pour le groupe local dont cet utilisateur local est membre
 a| 
`vserver cifs users-and-groups local-user show-membership -membership _group_name_`



 a| 
Afficher les informations d'appartenance des utilisateurs aux utilisateurs locaux associés à une machine virtuelle de stockage (SVM) spécifiée
 a| 
`vserver cifs users-and-groups local-user show-membership -vserver _vserver_name_`



 a| 
Affiche des informations détaillées pour tous les utilisateurs locaux sur un SVM spécifié
 a| 
`vserver cifs users-and-groups local-user show-membership -instance ‑vserver _vserver_name_`

|===


L'exemple suivant affiche les informations d'appartenance de tous les utilisateurs locaux sur le SVM vs1 ; l'utilisateur « CIFS_SERVER\Administrator » est membre du groupe « BUILTIN\Administrators » et « CIFS_SERVER\sue » est membre du groupe « CIFS_SERVER\g1 » :

[listing]
----
cluster1::> vserver cifs users-and-groups local-user show-membership -vserver vs1
Vserver    User Name                    Membership
---------- ---------------------------- ------------------------
vs1        CIFS_SERVER\Administrator    BUILTIN\Administrators
           CIFS_SERVER\sue              CIFS_SERVER\g1
----