---
permalink: smb-admin/display-branchcache-group-policy-objects-task.html 
sidebar: sidebar 
keywords: display, information, cifs, server, group, policy, object, gpo, configuration, branchcache, define, domain, server, display information about branchcache group policy objects 
summary: 'Vous pouvez afficher des informations sur la configuration GPO (Group Policy Object) du serveur CIFS pour déterminer si des GPO de BranchCache sont définis pour le domaine auquel le serveur CIFS appartient et, le cas échéant, quels sont les paramètres autorisés. Vous pouvez également déterminer si les paramètres GPO de BranchCache sont appliqués au serveur CIFS.' 
---
= Afficher des informations sur les objets de stratégie de groupe ONTAP SMB BranchCache
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher des informations sur la configuration GPO (Group Policy Object) du serveur CIFS pour déterminer si des GPO de BranchCache sont définis pour le domaine auquel le serveur CIFS appartient et, le cas échéant, quels sont les paramètres autorisés. Vous pouvez également déterminer si les paramètres GPO de BranchCache sont appliqués au serveur CIFS.

.Description de la tâche
Bien qu'un paramètre GPO soit défini au sein du domaine auquel le serveur CIFS appartient, il n'est pas nécessairement appliqué à l'unité organisationnelle contenant la machine virtuelle de stockage (SVM) compatible CIFS. Le paramètre GPO appliqué est le sous-ensemble de tous les GPO définis qui sont appliqués à la SVM compatible CIFS. Les paramètres BranchCache appliqués via les GPO remplacent les paramètres appliqués via l'interface CLI.

.Étapes
. Affichez le paramètre GPO de BranchCache défini pour le domaine Active Directory à l'aide du `vserver cifs group-policy show-defined` commande.
+
[NOTE]
====
Cet exemple n'affiche pas tous les champs de sortie disponibles pour la commande. La sortie est tronquée.

====
+
[listing]
----
cluster1::> vserver cifs group-policy show-defined -vserver vs1

Vserver: vs1
-----------------------------
       GPO Name: Default Domain Policy
       Level: Domain
      Status: enabled
  Advanced Audit Settings:
      Object Access:
          Central Access Policy Staging: failure
  Registry Settings:
      Refresh Time Interval: 22
      Refresh Random Offset: 8
      Hash Publication Mode for BranchCache: per-share
      Hash Version Support for BranchCache: version1
  [...]

    GPO Name: Resultant Set of Policy
      Status: enabled
  Advanced Audit Settings:
      Object Access:
          Central Access Policy Staging: failure
  Registry Settings:
      Refresh Time Interval: 22
      Refresh Random Offset: 8
      Hash Publication for Mode BranchCache: per-share
      Hash Version Support for BranchCache: version1
  [...]
----
. Affichez le paramètre GPO de BranchCache appliqué au serveur CIFS à l'aide de `vserver cifs group-policy show-applied` commande. ``
+
[NOTE]
====
Cet exemple n'affiche pas tous les champs de sortie disponibles pour la commande. La sortie est tronquée.

====
+
[listing]
----
cluster1::> vserver cifs group-policy show-applied -vserver vs1

Vserver: vs1
-----------------------------
     GPO Name: Default Domain Policy
       Level: Domain
      Status: enabled
  Advanced Audit Settings:
      Object Access:
          Central Access Policy Staging: failure
  Registry Settings:
      Refresh Time Interval: 22
      Refresh Random Offset: 8
      Hash Publication Mode for BranchCache: per-share
      Hash Version Support for BranchCache: version1
  [...]

    GPO Name: Resultant Set of Policy
       Level: RSOP
  Advanced Audit Settings:
      Object Access:
          Central Access Policy Staging: failure
  Registry Settings:
      Refresh Time Interval: 22
      Refresh Random Offset: 8
      Hash Publication Mode for BranchCache: per-share
      Hash Version Support for BranchCache: version1
 [...]
----


.Informations associées
* xref:enable-disable-gpo-support-task.adoc[Activation ou désactivation de la prise en charge de GPO sur un serveur CIFS]
* link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-group-policy-show-defined.html["vserver cifs group-policy show-defined"^]
* link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-group-policy-show-applied.html["vserver cifs group-policy show-applied"^]

