---
permalink: smb-admin/display-restricted-group-gpos-task.html 
sidebar: sidebar 
keywords: display, detail, information, restrict, group, define, group, policy, object, gpo, active, directory, applied, apply, cifs, server, display detailed information about restricted group gpos 
summary: 'Vous pouvez afficher des informations détaillées sur les groupes restreints qui sont définis comme objets de stratégie de groupe (GPO, Group Policy Objects) dans Active Directory et qui sont appliqués au serveur CIFS.' 
---
= Affiche des informations détaillées sur les GPO de groupe restreints
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher des informations détaillées sur les groupes restreints qui sont définis comme objets de stratégie de groupe (GPO, Group Policy Objects) dans Active Directory et qui sont appliqués au serveur CIFS.

Par défaut, les informations suivantes sont affichées :

* Nom de la stratégie de groupe
* Version de la stratégie de groupe
* Lien
+
Spécifie le niveau dans lequel la stratégie de groupe est configurée. Les valeurs de sortie possibles sont les suivantes :

+
** `Local` Lorsque la stratégie de groupe est configurée dans ONTAP
** `Site` lorsque la stratégie de groupe est configurée au niveau du site dans le contrôleur de domaine
** `Domain` lorsque la stratégie de groupe est configurée au niveau du domaine dans le contrôleur de domaine
** `OrganizationalUnit` Lorsque la stratégie de groupe est configurée au niveau de l'unité organisationnelle (ou) dans le contrôleur de domaine
** `RSOP` pour l'ensemble résultant de règles dérivées de toutes les stratégies de groupe définies à différents niveaux


* Nom de groupe restreint
* Utilisateurs et groupes qui appartiennent à et qui n'appartiennent pas au groupe restreint
* Liste des groupes auxquels le groupe restreint est ajouté
+
Un groupe peut être membre de groupes autres que ceux répertoriés ici.



.Étape
. Afficher des informations sur tous les GPO de groupe restreints en effectuant l'une des actions suivantes :
+
|===
| Si vous souhaitez afficher des informations sur tous les GPO de groupe restreints... | Entrez la commande... 


 a| 
Défini dans Active Directory
 a| 
`vserver cifs group-policy restricted-group show-defined -vserver vserver_name`



 a| 
Appliqué à un serveur CIFS
 a| 
`vserver cifs group-policy restricted-group show-applied -vserver vserver_name`

|===


L'exemple suivant affiche les informations relatives aux stratégies de groupe restreintes définies dans le domaine Active Directory auquel appartient la SVM compatible CIFS nommée vs1 :

[listing]
----
cluster1::> vserver cifs group-policy restricted-group show-defined -vserver vs1

Vserver: vs1
-------------

     Group Policy Name: gpo1
               Version: 16
                  Link: OrganizationalUnit
            Group Name: group1
               Members: user1
              MemberOf: EXAMPLE\group9

     Group Policy Name: Resultant Set of Policy
               Version: 0
                  Link: RSOP
            Group Name: group1
               Members: user1
              MemberOf: EXAMPLE\group9
----
L'exemple suivant affiche les informations relatives aux groupes restreints GPO appliqués au SVM vs1 activé pour CIFS :

[listing]
----
cluster1::> vserver cifs group-policy restricted-group show-applied -vserver vs1

Vserver: vs1
-------------

     Group Policy Name: gpo1
               Version: 16
                  Link: OrganizationalUnit
            Group Name: group1
               Members: user1
              MemberOf: EXAMPLE\group9

     Group Policy Name: Resultant Set of Policy
               Version: 0
                  Link: RSOP
            Group Name: group1
               Members: user1
              MemberOf: EXAMPLE\group9
----
xref:display-gpo-config-task.adoc[Affichage des informations sur les configurations GPO]
