---
permalink: smb-admin/display-dynamic-access-control-security-task.html 
sidebar: sidebar 
keywords: display, information, dynamic, access, control, dac, security, ntfs, volume, data, effective, security, mix, security-stle, volume, conditional, ace, resource, central, access, policy, display information about dynamic access control security 
summary: 'Vous pouvez afficher des informations sur la sécurité DAC (Dynamic Access Control) sur des volumes NTFS et sur des données avec la sécurité efficace NTFS sur des volumes de type sécurité mixtes. Cela comprend de l"information sur les ACE conditionnels, les ACE de ressources et les ACE de politique d"accès central. Les résultats vous permettent de valider votre configuration de sécurité ou de résoudre les problèmes d"accès aux fichiers.' 
---
= Afficher des informations sur la sécurité DAC pour les serveurs SMB ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher des informations sur la sécurité DAC (Dynamic Access Control) sur des volumes NTFS et sur des données avec la sécurité efficace NTFS sur des volumes de type sécurité mixtes. Cela comprend de l'information sur les ACE conditionnels, les ACE de ressources et les ACE de politique d'accès central. Les résultats vous permettent de valider votre configuration de sécurité ou de résoudre les problèmes d'accès aux fichiers.

.Description de la tâche
Vous devez fournir le nom de la machine virtuelle de stockage (SVM) et le chemin d'accès aux données dont vous souhaitez afficher les informations de sécurité des fichiers ou des dossiers. Vous pouvez afficher les valeurs de sortie sous forme de récapitulatif ou sous forme de liste détaillée.

.Étape
. Afficher les paramètres de sécurité des fichiers et des répertoires avec le niveau de détail souhaité :
+
|===
| Pour afficher les informations... | Saisissez la commande suivante... 


 a| 
Sous forme récapitulative
 a| 
`vserver security file-directory show -vserver vserver_name -path path`



 a| 
Avec détails étendus
 a| 
`vserver security file-directory show -vserver vserver_name -path path -expand-mask true`



 a| 
Où la sortie est affichée avec les SID de groupe et d'utilisateur
 a| 
`vserver security file-directory show -vserver vserver_name -path path -lookup-names false`



 a| 
A propos de la sécurité des fichiers et des répertoires pour les fichiers et les répertoires où le masque binaire hexadécimal est traduit en format texte
 a| 
`vserver security file-directory show -vserver vserver_name -path path -textual-mask true`

|===


.Exemples
L'exemple suivant affiche les informations de sécurité du contrôle d'accès dynamique sur le chemin `/vol1` Au SVM vs1 :

[listing]
----
cluster1::> vserver security file-directory show -vserver vs1 -path /vol1
                           Vserver: vs1
                         File Path: /vol1
                 File Inode Number: 112
                    Security Style: mixed
                   Effective Style: ntfs
                    DOS Attributes: 10
            DOS Attributes in Text: ----D---
            Expanded Dos Attribute: -
                      Unix User Id: 0
                     Unix Group Id: 1
                    Unix Mode Bits: 777
            Unix Mode Bits in Text: rwxrwxrwx
                              ACLs: NTFS Security Descriptor
                                    Control:0xbf14
                                    Owner:CIFS1\Administrator
                                    Group:CIFS1\Domain Admins
                                    SACL - ACEs
                                       ALL-Everyone-0xf01ff-OI|CI|SA|FA
                                       RESOURCE ATTRIBUTE-Everyone-0x0
                                         ("Department_MS",TS,0x10020,"Finance")
                                       POLICY ID-All resources - No Write-0x0-OI|CI
                                    DACL - ACEs
                                       ALLOW-CIFS1\Administrator-0x1f01ff-OI|CI
                                       ALLOW-Everyone-0x1f01ff-OI|CI
                                       ALLOW CALLBACK-DAC\user1-0x1200a9-OI|CI
                                         ((@User.department==@Resource.Department_MS&&@Resource.Impact_MS>1000)&&@Device.department==@Resource.Department_MS)
----
.Informations associées
xref:display-gpo-config-task.adoc[Affichage des informations sur les configurations GPO]

xref:display-central-access-policies-task.adoc[Affichage d'informations sur les règles d'accès central]

xref:display-central-access-policy-rules-task.adoc[Affichage d'informations sur les règles de stratégie d'accès central]
