---
permalink: smb-admin/display-list-netbios-aliases-task.html 
sidebar: sidebar 
keywords: display, list, netbios, alias, useful, determine, name, smb, client, connection, cifs, server, display the list of netbios aliases on cifs servers 
summary: Vous pouvez afficher la liste des alias NetBIOS. Cela peut être utile lorsque vous voulez déterminer la liste des noms sur lesquels les clients SMB peuvent établir des connexions au serveur CIFS. 
---
= Afficher la liste des alias NetBIOS sur les serveurs CIFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher la liste des alias NetBIOS. Cela peut être utile lorsque vous voulez déterminer la liste des noms sur lesquels les clients SMB peuvent établir des connexions au serveur CIFS.

.Étape
. Effectuez l'une des opérations suivantes :
+
|===
| Pour afficher des informations sur... | Entrer... 


 a| 
Alias NetBIOS d'un serveur CIFS
 a| 
`vserver cifs show -display-netbios-aliases`



 a| 
La liste des alias NetBIOS dans le cadre des informations détaillées du serveur CIFS
 a| 
`vserver cifs show -instance`

|===
+
L'exemple suivant affiche des informations sur les alias NetBIOS d'un serveur CIFS :

+
`vserver cifs show -display-netbios-aliases`

+
[listing]
----
Vserver: vs1

         Server Name: CIFS_SERVER
         NetBIOS Aliases: ALIAS_1, ALIAS_2, ALIAS_3
----
+
L'exemple suivant affiche la liste des alias NetBIOS dans le cadre des informations détaillées du serveur CIFS :

+
`vserver cifs show -instance`

+
[listing]
----

                                          Vserver: vs1
                         CIFS Server NetBIOS Name: CIFS_SERVER
                    NetBIOS Domain/Workgroup Name: EXAMPLE
                      Fully Qualified Domain Name: EXAMPLE.COM
Default Site Used by LIFs Without Site Membership:
                             Authentication Style: domain
                CIFS Server Administrative Status: up
                          CIFS Server Description:
                          List of NetBIOS Aliases: ALIAS_1, ALIAS_2, ALIAS_3
----
+
Consultez la page man pour les commandes pour plus d'informations.



xref:add-list-netbios-aliases-server-task.adoc[Ajout d'une liste d'alias NetBIOS au serveur CIFS]

xref:commands-manage-servers-reference.adoc[Commandes pour la gestion des serveurs CIFS]
