---
permalink: smb-admin/display-preferred-trusted-domain-list-task.html 
sidebar: sidebar 
keywords: display, information, trust, domain, perfer, list, order, multidomain, name, map, search, enable, configure, alternative, display information about the preferred trusted domain list 
summary: 'Vous pouvez afficher des informations sur les domaines de confiance dans la liste des domaines de confiance préférés et l"ordre dans lequel ils sont recherchés si les recherches de mappage de noms de domaines multiples sont activées. Vous pouvez configurer une liste de domaines de confiance préférée comme alternative à l"utilisation de la liste de domaines de confiance automatiquement découverts.' 
---
= Affiche des informations sur la liste de domaines de confiance préférée
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher des informations sur les domaines de confiance dans la liste des domaines de confiance préférés et l'ordre dans lequel ils sont recherchés si les recherches de mappage de noms de domaines multiples sont activées. Vous pouvez configurer une liste de domaines de confiance préférée comme alternative à l'utilisation de la liste de domaines de confiance automatiquement découverts.

.Étapes
. Effectuez l'une des opérations suivantes :
+
|===
| Pour afficher des informations sur les éléments suivants... | Utilisez la commande... 


 a| 
Tous les domaines de confiance privilégiés dans le cluster regroupés par SVM (Storage Virtual machine)
 a| 
`vserver cifs domain name-mapping-search show`



 a| 
Tous les domaines fiables préférés pour un SVM spécifié
 a| 
`vserver cifs domain name-mapping-search show -vserver _vserver_name_`

|===
+
La commande suivante affiche des informations sur tous les domaines de confiance privilégiés sur le cluster :

+
[listing]
----
cluster1::> vserver cifs domain name-mapping-search show
Vserver         Trusted Domains
--------------  ----------------------------------
vs1             CIFS1.EXAMPLE.COM
----


xref:add-remove-replace-trusted-domains-preferred-lists-task.adoc[Ajout, suppression ou remplacement de domaines de confiance dans les listes de domaines de confiance préférées]
