---
permalink: smb-admin/display-privilege-overrides-task.html 
sidebar: sidebar 
keywords: display, information, custom, privilege, assign, domain, local, user, account, group, desire, right, applied, apply, display information about privilege overrides 
summary: 'Vous pouvez afficher des informations sur les privilèges personnalisés attribués à des comptes ou groupes d"utilisateurs locaux ou de domaine. Ces informations vous aident à déterminer si les droits d"utilisateur souhaités sont appliqués.' 
---
= Affiche des informations sur les remplacements de privilèges
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher des informations sur les privilèges personnalisés attribués à des comptes ou groupes d'utilisateurs locaux ou de domaine. Ces informations vous aident à déterminer si les droits d'utilisateur souhaités sont appliqués.

.Étape
. Effectuez l'une des opérations suivantes :
+
|===
| Pour afficher des informations sur... | Entrez cette commande... 


 a| 
Privilèges personnalisés pour tous les utilisateurs et groupes locaux et du domaine sur la machine virtuelle de stockage (SVM)
 a| 
`vserver cifs users-and-groups privilege show -vserver _vserver_name_`



 a| 
Privilèges personnalisés pour un domaine spécifique ou un utilisateur et groupe local sur le SVM
 a| 
`vserver cifs users-and-groups privilege show -vserver _vserver_name_ -user-or-group-name _name_`

|===
+
D'autres paramètres facultatifs peuvent être choisis lors de l'exécution de cette commande. Consultez la page man pour plus d'informations



.Exemple
La commande suivante affiche tous les privilèges explicitement associés aux utilisateurs et groupes locaux ou de domaine pour le SVM vs1 :

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver    User or Group Name     Privileges
--------- ---------------------   ---------------
vs1       BUILTIN\Administrators  SeTakeOwnershipPrivilege
                                  SeRestorePrivilege
vs1       CIFS_SERVER\sue         SeTcbPrivilege
                                  SeTakeOwnershipPrivilege
----