---
permalink: smb-admin/display-discovered-trusted-domains-task.html 
sidebar: sidebar 
keywords: display, information, discover, trust, domain, cifs, server, home, contain, computer, trusted-domain, list, display information about discover trusted domains 
summary: Vous pouvez afficher des informations sur les domaines approuvés découverts pour le domaine personnel du serveur CIFS, qui est le domaine contenant le compte ordinateur du serveur CIFS. Cela peut être utile lorsque vous voulez savoir quels domaines de confiance sont découverts et comment ils sont ordonnés dans la liste domaine de confiance découvert. 
---
= Affiche des informations sur les domaines SMB ONTAP fiables découverts
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher des informations sur les domaines approuvés découverts pour le domaine personnel du serveur CIFS, qui est le domaine contenant le compte d'ordinateur du serveur CIFS. Cela peut être utile lorsque vous voulez savoir quels domaines de confiance sont découverts et comment ils sont ordonnés dans la liste domaine de confiance découvert.

.Description de la tâche
Seuls les domaines avec des approbations bidirectionnelles avec le domaine de départ sont découverts. Étant donné que le contrôleur de domaine (DC) du domaine d'origine renvoie la liste des domaines de confiance dans un ordre déterminé par le DC, l'ordre des domaines dans la liste ne peut pas être prédit. En affichant la liste des domaines de confiance, vous pouvez déterminer l'ordre de recherche des recherches de mappage de noms de domaines multiples.

Les informations des domaines de confiance affichés sont regroupées par nœud et par SVM (Storage Virtual machine).

.Étape
. Affiche des informations sur les domaines de confiance découverts à l'aide du `vserver cifs domain trusts show` commande.
+
`vserver cifs domain trusts show -vserver vs1`

+
[listing]
----
   Node: node1
Vserver: vs1

Home Domain            Trusted Domain
---------------------  -----------------------------------
EXAMPLE.COM            CIFS1.EXAMPLE.COM,
                       CIFS2.EXAMPLE.COM
                       EXAMPLE.COM

   Node: node2
Vserver: vs1

Home Domain            Trusted Domain
---------------------  -----------------------------------
EXAMPLE.COM            CIFS1.EXAMPLE.COM,
                       CIFS2.EXAMPLE.COM
                       EXAMPLE.COM
----


.Informations associées
xref:reset-rediscover-trusted-domains-task.adoc[Réinitialisation et redécouverte des domaines de confiance]
