---
permalink: smb-admin/display-statistics-task.html 
sidebar: sidebar 
keywords: display, various, statistic, cifs, smb, audit, branchcache, has, monitor, performance, diagnose, issue 
summary: 'Vous pouvez afficher plusieurs statistiques, notamment des statistiques sur CIFS et SMB, l"audit et des hachages de BranchCache, pour surveiller les performances et diagnostiquer les problèmes.' 
---
= Afficher les statistiques ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez afficher plusieurs statistiques, notamment des statistiques sur CIFS et SMB, l'audit et des hachages de BranchCache, pour surveiller les performances et diagnostiquer les problèmes.

.Avant de commencer
Vous devez avoir collecté des échantillons de données à l'aide du `statistics start` et `statistics stop` commandes avant de pouvoir afficher les informations relatives aux objets.

.Étapes
. Définissez le niveau de privilège sur avancé : `set -privilege advanced`
. Effectuez l'une des opérations suivantes :
+
|===
| Pour afficher les statistiques de... | Entrer... 


 a| 
Toutes les versions de SMB
 a| 
`statistics show -object cifs`



 a| 
SMB 1.0
 a| 
`statistics show -object smb1`



 a| 
SMB 2.x et SMB 3.0
 a| 
`statistics show -object smb2`



 a| 
Sous-système CIFS du nœud
 a| 
`statistics show -object nblade_cifs`



 a| 
Audit multiprotocole
 a| 
`statistics show -object audit_ng`



 a| 
Service de hachage BranchCache
 a| 
`statistics show -object hashd`



 a| 
DNS dynamique
 a| 
`statistics show -object ddns_update`

|===
+
Pour en savoir plus, `statistics show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/statistics-show.html["Référence de commande ONTAP"^].

. Retour au niveau de privilège admin : `set -privilege admin`


.Informations associées
* xref:determine-statistics-objects-counters-available-task.adoc[Déterminer quelles statistiques, quels objets et quels compteurs sont disponibles sur les serveurs]
* xref:monitor-signed-session-statistics-task.adoc[Contrôle des statistiques de session signées SMB]
* xref:display-branchcache-statistics-task.adoc[Afficher les statistiques de BranchCache]
* xref:statistics-monitor-automatic-node-referral-task.adoc[Utilisez les statistiques pour surveiller l'activité de renvoi automatique des nœuds]
* link:../smb-hyper-v-sql/index.html["Configuration SMB pour Microsoft Hyper-V et SQL Server"]
* link:../performance-config/index.html["Configuration du contrôle des performances"]

