---
permalink: smb-admin/enable-disable-odx-task.html 
sidebar: sidebar 
keywords: enable, disable, odx, storage, virtual, machine, svm, default, support, copy, offload, smb, enable, enable or disable odx 
summary: 'Vous pouvez activer ou désactiver ODX sur des SVM. Par défaut, est d"activer la prise en charge de l"allègement de la charge des copies (ODX) si SMB 3.0 est également activé.' 
---
= Activer ou désactiver ODX sur les serveurs ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez activer ou désactiver ODX sur des SVM. Par défaut, est d'activer la prise en charge de l'allègement de la charge des copies (ODX) si SMB 3.0 est également activé.

.Avant de commencer
SMB 3.0 doit être activé.

.Description de la tâche
Si vous désactivez SMB 3.0, ONTAP désactive également SMB ODX. Si vous réactivez SMB 3.0, vous devez réactiver manuellement SMB ODX.

.Étapes
. Définissez le niveau de privilège sur avancé : `set -privilege advanced`
. Effectuez l'une des opérations suivantes :
+
|===
| Si vous voulez que l'allègement de la charge des copies ODX soit... | Entrez la commande... 


 a| 
Activé
 a| 
`vserver cifs options modify -vserver vserver_name -copy-offload-enabled true`



 a| 
Désactivé
 a| 
`vserver cifs options modify -vserver vserver_name -copy-offload-enabled false`

|===
. Retour au niveau de privilège admin : `set -privilege admin`


.Exemple
L'exemple suivant active la décharge de la copie ODX sur le SVM vs1 :

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options modify -vserver vs1 -copy-offload-enabled true

cluster1::*> set -privilege admin
----
.Informations associées
xref:server-options-reference.adoc[Options de serveur SMB disponibles]
