---
permalink: smb-admin/enable-ldap-signing-sealing-task.html 
sidebar: sidebar 
keywords: cifs, server, sign, seal, secure, communication, active, directory, ldap, modify, security, setting, sign, seal, enable, enable ldap signing and sealing on the cifs server 
summary: Avant que votre serveur CIFS puisse utiliser la signature et le chiffrement pour sécuriser la communication avec un serveur LDAP Active Directory, vous devez modifier les paramètres de sécurité du serveur CIFS pour activer la signature et le chiffrement LDAP. 
---
= Activez le chiffrement et la signature LDAP sur le serveur CIFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant que votre serveur CIFS puisse utiliser la signature et le chiffrement pour sécuriser la communication avec un serveur LDAP Active Directory, vous devez modifier les paramètres de sécurité du serveur CIFS pour activer la signature et le chiffrement LDAP.

Vous devez consulter votre administrateur de serveur AD pour déterminer les valeurs de configuration de sécurité appropriées.

.Étapes
. Configurez le paramètre de sécurité du serveur CIFS qui autorise le trafic signé et scellé avec les serveurs LDAP Active Directory : `vserver cifs security modify -vserver _vserver_name_ -session-security-for-ad-ldap {none|sign|seal}`
+
Vous pouvez activer la signature (`sign`, intégrité des données), signature et scellage (`seal`, intégrité et chiffrement des données), ou ni l'un ni l'autre  `none`, pas de signature ou d'étanchéité). La valeur par défaut est `none`.

. Vérifiez que le paramètre de sécurité de signature et de chiffrement LDAP est défini correctement : `vserver cifs security show -vserver _vserver_name_`
+
[NOTE]
====
Si le SVM utilise le même serveur LDAP pour effectuer des requêtes name-mapping ou d'autres informations UNIX, comme les utilisateurs, les groupes et les netgroups, alors vous devez activer le paramètre correspondant avec le `-session-security` de la `vserver services name-service ldap client modify` commande.

====

