---
permalink: smb-admin/enable-disable-oplocks-when-creating-shares-task.html 
sidebar: sidebar 
keywords: oplock, client, lock, file, cache, content, local, performance, operation, storage, virtual, machine, svm, circumstance, disable, share-by-share, basis, enable, disable, enable or disable oplocks when creating smb shares 
summary: 'Les oplocks permettent aux clients de verrouiller des fichiers et de mettre du contenu en cache localement, ce qui peut augmenter les performances des opérations sur les fichiers. Les oplocks sont activés sur des partages SMB résidant sur des SVM (Storage Virtual machine). Dans certaines circonstances, vous pouvez désactiver les oplocks. Vous pouvez activer ou désactiver les oplocks sur une base de partage par partage.' 
---
= Activez ou désactivez les oplocks lors de la création de partages SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les oplocks permettent aux clients de verrouiller des fichiers et de mettre du contenu en cache localement, ce qui peut augmenter les performances des opérations sur les fichiers. Les oplocks sont activés sur des partages SMB résidant sur des SVM (Storage Virtual machine). Dans certaines circonstances, vous pouvez désactiver les oplocks. Vous pouvez activer ou désactiver les oplocks sur une base de partage par partage.

Si les oplocks sont activés sur le volume contenant un partage mais que la propriété de partage oplock pour ce partage est désactivée, les oplocks sont désactivés pour ce partage. La désactivation des oplocks sur un partage a priorité sur le paramètre oplock de volume. La désactivation des oplocks sur le partage désactive à la fois les oplocks opportunistes et les oplocks de location.

Vous pouvez spécifier d'autres propriétés de partage en plus de spécifier la propriété de partage oplock à l'aide d'une liste délimitée par des virgules. Vous pouvez également spécifier d'autres paramètres de partage.

.Étapes
. Effectuez l'action appropriée :
+
|===
| Les fonctions que vous recherchez... | Alors... 


 a| 
Activez les oplocks sur un partage lors de la création du partage
 a| 
Saisissez la commande suivante : `+vserver cifs share create -vserver _vserver_name_ -share-name share_name -path path_to_share -share-properties [oplocks,...]+`

[NOTE]
====
Si vous souhaitez que le partage n'ait que les propriétés de partage par défaut, c'est-à-dire `oplocks`, `browsable`, et `changenotify` activé, vous n'avez pas besoin de spécifier le `-share-properties` Paramètre lors de la création d'un partage SMB. Si vous souhaitez utiliser une combinaison de propriétés de partage autre que la valeur par défaut, vous devez spécifier l' `-share-properties` paramètre avec la liste des propriétés de partage à utiliser pour ce partage.

====


 a| 
Désactiver les oplocks sur un partage lors de la création du partage
 a| 
Saisissez la commande suivante : `+vserver cifs share create -vserver _vserver_name_ -share-name _share_name_ -path _path_to_share_ -share-properties [other_share_property,...]+`

[NOTE]
====
Lors de la désactivation des oplocks, vous devez spécifier une liste de propriétés de partage lors de la création du partage, mais vous ne devez pas spécifier le `oplocks` propriété.

====
|===


xref:enable-disable-oplocks-existing-shares-task.adoc[Activation ou désactivation des oplocks sur des partages SMB existants]

xref:monitor-oplock-status-task.adoc[Surveillance de l'état du oplock]
