---
permalink: smb-admin/enable-disable-multidomain-name-mapping-searches-task.html 
sidebar: sidebar 
keywords: multidomain, name, mapping, search, wild, card, domain, portion, windows, configure, configuring, unix, user, bidirectional, enable, disable, enable or disable multidomain name mapping searches 
summary: 'Avec les recherches de mappage de noms multidomaine, vous pouvez utiliser un caractère générique (*) dans la partie domaine d"un nom Windows lors de la configuration du mappage de noms d"utilisateur UNIX vers Windows. L"utilisation d"un caractère générique (*) dans la partie domaine du nom permet à ONTAP de rechercher tous les domaines ayant une confiance bidirectionnelle avec le domaine qui contient le compte ordinateur du serveur CIFS.' 
---
= Activez ou désactivez les recherches de mappage de noms multidomaine
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avec les recherches de mappage de noms multidomaine, vous pouvez utiliser un caractère générique (\*) dans la partie domaine d'un nom Windows lors de la configuration du mappage de noms d'utilisateurs UNIX vers Windows. L'utilisation d'un caractère générique (*) dans la partie domaine du nom permet à ONTAP de rechercher tous les domaines ayant une confiance bidirectionnelle avec le domaine qui contient le compte ordinateur du serveur CIFS.

.Description de la tâche
Comme alternative à la recherche de tous les domaines de confiance bidirectionnels, vous pouvez configurer une liste de domaines de confiance préférés. Lorsqu'une liste de domaines de confiance privilégiés est configurée, ONTAP utilise la liste de domaines de confiance préférée au lieu des domaines de confiance bidirectionnels découverts pour effectuer des recherches de mappage de noms multiples domaines.

* Les recherches de mappage de noms de domaines multiples sont activées par défaut.
* Cette option est disponible au niveau de privilège avancé.


.Étapes
. Définissez le niveau de privilège sur avancé : `set -privilege advanced`
. Effectuez l'une des opérations suivantes :
+
|===
| Pour effectuer des recherches sur le mappage de noms de domaines multiples... | Entrez la commande... 


 a| 
Activé
 a| 
`vserver cifs options modify -vserver _vserver_name_ -is-trusted-domain-enum-search-enabled true`



 a| 
Désactivé
 a| 
`vserver cifs options modify -vserver _vserver_name_ -is-trusted-domain-enum-search-enabled false`

|===
. Retour au niveau de privilège admin : `set -privilege admin`


.Informations associées
xref:server-options-reference.adoc[Options de serveur SMB disponibles]
