---
permalink: smb-admin/enable-disable-ntfs-acls-unix-security-task.html 
sidebar: sidebar 
keywords: enable, disable, presentation, ntfs, acl, smb, client, unix, security-style, data, volume, enable or disable the presentation of ntfs acls for unix security-style data 
summary: 'Vous pouvez activer ou désactiver la présentation des listes de contrôle d"accès NTFS aux clients SMB pour les données de style de sécurité UNIX (volumes de style sécurité UNIX et volumes de type sécurité mixte avec sécurité effective UNIX).' 
---
= Configurez la présentation des ACL NTFS aux clients SMB ONTAP pour les données de type sécurité UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez activer ou désactiver la présentation des listes de contrôle d'accès NTFS aux clients SMB pour les données de style de sécurité UNIX (volumes de style sécurité UNIX et volumes de type sécurité mixte avec sécurité effective UNIX).

.Description de la tâche
Si vous activez cette option, ONTAP présente les fichiers et les dossiers sur les volumes avec un style de sécurité UNIX efficace aux clients SMB comme ayant des listes de contrôle d'accès NTFS. Si vous désactivez cette option, les volumes sont présentés en tant que volumes FAT aux clients SMB. Par défaut, cette valeur doit présenter des listes de contrôle d'accès NTFS aux clients SMB.

.Étapes
. Définissez le niveau de privilège sur avancé : `set -privilege advanced`
. Configurez le paramètre d'option ACL NTFS UNIX : `vserver cifs options modify -vserver _vserver_name_ -is-unix-nt-acl-enabled {true|false}`
. Vérifiez que l'option est réglée sur la valeur souhaitée : `vserver cifs options show -vserver _vserver_name_`
. Retour au niveau de privilège admin : `set -privilege admin`

