---
permalink: smb-admin/enable-metadata-cache-task.html 
sidebar: sidebar 
keywords: smb, performance, client, enabling, enable, metadata, cache, disable, enable the smb metadata cache 
summary: Vous pouvez améliorer les performances SMB des clients SMB 1.0 en activant le cache de métadonnées SMB. Par défaut, la mise en cache des métadonnées SMB est désactivée. 
---
= Activer le cache de métadonnées ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez améliorer les performances SMB des clients SMB 1.0 en activant le cache de métadonnées SMB. Par défaut, la mise en cache des métadonnées SMB est désactivée.

.Étape
. Effectuez l'action souhaitée :
+
|===
| Les fonctions que vous recherchez... | Entrez la commande... 


 a| 
Activez la mise en cache des métadonnées SMB lorsque vous créez un partage
 a| 
`vserver cifs share create -vserver _vserver_name_ -share-name _share_name_ -path _path_ -share-properties attributecache`



 a| 
Activez la mise en cache des métadonnées SMB sur un partage existant
 a| 
`vserver cifs share properties add -vserver _vserver_name_ -share-name _share_name_ -share-properties attributecache`

|===


.Informations associées
* xref:configure-lifetime-metadata-cache-entries-task.adoc[Configurer la durée de vie des entrées du cache de métadonnées]
* xref:add-remove-share-properties-existing-share-task.adoc[Ajouter ou supprimer des propriétés de partage sur des partages existants]

