---
permalink: smb-admin/enable-disable-oplocks-existing-shares-task.html 
sidebar: sidebar 
keywords: oplock, enable, smb, share, storage, virtual, machine, svm, default, circumstance, disable, alternative, enable or disable oplocks on existing smb shares 
summary: 'Les oplocks sont activés par défaut sur des partages SMB sur des SVM (Storage Virtual machines). Dans certaines circonstances, vous pouvez désactiver les oplocks. Si vous avez précédemment désactivé les oplocks sur un partage, vous pouvez également réactiver les oplocks.' 
---
= Activer ou désactiver les oplocks sur les partages SMB ONTAP existants
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les oplocks sont activés par défaut sur des partages SMB sur des SVM (Storage Virtual machines). Dans certaines circonstances, vous pouvez désactiver les oplocks. Si vous avez précédemment désactivé les oplocks sur un partage, vous pouvez également réactiver les oplocks.

.Description de la tâche
Si les oplocks sont activés sur le volume contenant un partage, mais que la propriété de partage oplock pour ce partage est désactivée, les oplocks sont désactivés pour ce partage. La désactivation des oplocks sur un partage a priorité sur l'activation des oplocks sur le volume. La désactivation des oplocks sur la part désactive les oplocks opportunistes et ceux de location. Vous pouvez à tout moment activer ou désactiver les oplocks sur des partages existants.

.Étape
. Effectuez l'action appropriée :
+
|===
| Les fonctions que vous recherchez... | Alors... 


 a| 
Activez les oplocks sur un partage en modifiant un partage existant
 a| 
Saisissez la commande suivante : `vserver cifs share properties add -vserver _vserver_name_ -share-name share_name -share-properties oplocks`

[NOTE]
====
Vous pouvez spécifier des propriétés de partage supplémentaires à ajouter à l'aide d'une liste délimitée par des virgules.

====
Les nouvelles propriétés ajoutées sont ajoutées à la liste existante des propriétés de partage. Toutes les propriétés de partage que vous avez précédemment spécifiées restent en vigueur.



 a| 
Désactivez les oplocks sur un partage en modifiant un partage existant
 a| 
Saisissez la commande suivante : `vserver cifs share properties remove -vserver _vserver_name_ -share-name _share_name_ -share-properties oplocks`

[NOTE]
====
Vous pouvez spécifier des propriétés de partage supplémentaires à supprimer à l'aide d'une liste délimitée par des virgules.

====
Les propriétés de partage que vous supprimez sont supprimées de la liste existante de propriétés de partage. Cependant, les propriétés de partage configurées précédemment que vous ne supprimez pas restent en vigueur.

|===


.Exemples
La commande suivante active les oplocks pour le partage nommé « Ingénierie » sur une machine virtuelle de stockage (SVM, précédemment connue sous le nom de Vserver) vs1 :

[listing]
----
cluster1::> vserver cifs share properties add -vserver vs1 -share-name Engineering -share-properties oplocks

cluster1::> vserver cifs share properties show
Vserver          Share            Properties
---------------- ---------------- -----------------
vs1              Engineering      oplocks
                                  browsable
                                  changenotify
                                  showsnapshot
----
La commande suivante désactive les oplocks pour l'action nommée « Engineering » sur le SVM vs1 :

[listing]
----
cluster1::> vserver cifs share properties remove -vserver vs1 -share-name Engineering -share-properties oplocks

cluster1::> vserver cifs share properties show
Vserver          Share            Properties
---------------- ---------------- -----------------
vs1              Engineering      browsable
                                  changenotify
                                  showsnapshot
----
.Informations associées
* xref:enable-disable-oplocks-when-creating-shares-task.adoc[Activez ou désactivez les oplocks lors de la création de partages SMB]
* xref:monitor-oplock-status-task.adoc[Surveiller l'état du oplock]
* xref:add-remove-share-properties-existing-share-task.adoc[Ajouter ou supprimer des propriétés de partage sur des partages existants]

