---
permalink: smb-admin/enable-disable-export-policies-task.html 
sidebar: sidebar 
keywords: enable, disable, export, policies, policy, smb, access, storage, virtual, machine, svm, control, resource, enable or disable export policies for smb access 
summary: 'Vous pouvez activer ou désactiver les export policy pour l"accès SMB sur les SVM (Storage Virtual machines). L"utilisation des règles d"exportation pour contrôler l"accès SMB aux ressources est facultative.' 
---
= Activez ou désactivez les export policy pour l'accès SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez activer ou désactiver les export policy pour l'accès SMB sur les SVM (Storage Virtual machines). L'utilisation des règles d'exportation pour contrôler l'accès SMB aux ressources est facultative.

.Avant de commencer
Les conditions suivantes sont requises pour l'activation des export policy pour SMB :

* Le client doit avoir un enregistrement "PTR" dans DNS avant de créer les règles d'exportation pour ce client.
* Un ensemble supplémentaire d'enregistrements « A » et « PTR » pour les noms d'hôtes est nécessaire si le SVM fournit l'accès aux clients NFS et si le nom d'hôte que vous souhaitez utiliser pour l'accès NFS est différent du nom du serveur CIFS.


.Description de la tâche
Lors de la configuration d'un nouveau serveur CIFS sur votre SVM, l'utilisation des export policies pour l'accès SMB est désactivée par défaut. Vous pouvez activer des export policy pour l'accès SMB si vous souhaitez contrôler l'accès en fonction du protocole d'authentification, des adresses IP clientes ou des noms d'hôte. Vous pouvez activer ou désactiver des export policy pour l'accès SMB à tout moment.


NOTE: L'activation des export policy pour CIFS/SMB dans un SVM compatible NFS permet à un client Linux d'utiliser `showmount -e` la commande sur le SVM afin de visualiser les Junction path de tous les volumes SMB avec les export policy rules associées.

.Étapes
. Définissez le niveau de privilège sur avancé : `set -privilege advanced`
. Activer ou désactiver les export-policies :
+
** Activer les export-policies : `vserver cifs options modify -vserver _vserver_name_ -is-exportpolicy-enabled true`
** Désactiver les export-policies : `vserver cifs options modify -vserver _vserver_name_ -is-exportpolicy-enabled false`


. Retour au niveau de privilège admin : `set -privilege admin`


.Exemple
L'exemple suivant permet d'utiliser les export policy pour contrôler l'accès des clients SMB aux ressources sur le SVM vs1 :

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options modify -vserver vs1 -is-exportpolicy-enabled true

cluster1::*> set -privilege admin
----