---
permalink: smb-admin/enable-disable-gpo-support-task.html 
sidebar: sidebar 
keywords: enable, disable, group, policy, object, gpo, support, cifs, server, applicable, define, policy, organizational, unit, ou, enable or disable gpo support on a cifs server 
summary: 'Vous pouvez activer ou désactiver la prise en charge des objets de stratégie de groupe (GPO, Group Policy Object) sur un serveur CIFS. Si vous activez la prise en charge GPO sur un serveur CIFS, les GPO applicables définis sur la stratégie de groupe (la stratégie appliquée à l"unité organisationnelle (ou) qui contient l"objet ordinateur de serveur CIFS) sont appliqués au serveur CIFS.' 
---
= Activer ou désactiver la prise en charge de GPO sur un serveur CIFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez activer ou désactiver la prise en charge des objets de stratégie de groupe (GPO, Group Policy Object) sur un serveur CIFS. Si vous activez la prise en charge GPO sur un serveur CIFS, les GPO applicables définis sur la stratégie de groupe--la stratégie appliquée à l'unité organisationnelle (ou) qui contient l'objet ordinateur de serveur CIFS--sont appliqués au serveur CIFS.

[NOTE]
.Description de la tâche
====
Les GPO ne peuvent pas être activés sur les serveurs CIFS en mode Workgroup.

====
.Étapes
. Effectuez l'une des opérations suivantes :
+
|===
| Les fonctions que vous recherchez... | Entrez la commande... 


 a| 
Activer les stratégies de groupe
 a| 
`vserver cifs group-policy modify -vserver _vserver_name_ -status enabled`



 a| 
Désactiver les stratégies de groupe
 a| 
`vserver cifs group-policy modify -vserver _vserver_name_ -status disabled`

|===
. Vérifiez que la prise en charge des stratégies de groupe est dans l'état souhaité : `vserver cifs group-policy show -vserver +vserver_name_`
+
L'état de la stratégie de groupe pour les serveurs CIFS en mode groupe de travail s'affiche en tant que « désactivé ».



.Exemple
L'exemple suivant illustre la prise en charge de GPO sur SVM (Storage Virtual machine) vs1 :

[listing]
----
cluster1::> vserver cifs group-policy modify -vserver vs1 -status enabled

cluster1::> vserver cifs group-policy show -vserver vs1

            Vserver: vs1
Group Policy Status: enabled
----
.Informations associées
xref:supported-gpos-concept.adoc[Stratégies de groupe prises en charge]

xref:requirements-gpos-concept.adoc[Configuration requise pour l'utilisation des objets de stratégie de groupe avec votre serveur CIFS]

xref:gpos-updated-server-concept.adoc[Mise à jour des stratégies de groupe sur le serveur CIFS]

xref:manual-update-gpo-settings-task.adoc[Mise à jour manuelle des paramètres GPO sur le serveur CIFS]

xref:display-gpo-config-task.adoc[Affichage des informations sur les configurations GPO]
