---
permalink: smb-admin/gpo-updates-failing-reference.html 
sidebar: sidebar 
keywords: circumstance, group, policy, object, gpo, update, windows, domain, controller, fail, visible, central, access, policy, setting, section, output, verserver, cifs, group-policy, show-defined, command, correct, what to do if gpo updates are failing 
summary: 'Dans certains cas, les mises à jour de l"objet de stratégie de groupe (GPO) des contrôleurs de domaine Windows 2012 peuvent échouer, ce qui n"affiche rien sous la section Central Access Policy Settings de la sortie de la commande vserver cifs group-policy show-defined. Vous devez savoir comment corriger ce problème s"il se produit.' 
---
= Que faire si les mises à jour de GPO échouent
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dans certaines circonstances, les mises à jour des objets de stratégie de groupe (GPO) des contrôleurs de domaine Windows 2012 peuvent échouer, ce qui n'a rien à voir sous `Central Access Policy Settings` section de la sortie pour le `vserver cifs group-policy show-defined` commande. Vous devez savoir comment corriger ce problème s'il se produit.

|===
| Cause sous-jacente | Solution 


 a| 
Lorsque ONTAP tente de se connecter au contrôleur de domaine Windows 2012 pour effectuer la mise à jour GPO, la connexion peut échouer avec l'erreur `error 0xc00000bd (NT STATUS_DUPLICATE_NAME)`.

Cette erreur se produit lorsque le nom du serveur utilisé pour établir la connexion est différent du nom NetBIOS du serveur CIFS. Il y a plusieurs raisons que cela pourrait se produire, y compris l'utilisation des alias. De plus, ONTAP applique le nom NetBIOS utilisé lors de la connexion au contrôleur de domaine pour que la longueur du nom soit égale à 15 caractères. Cela peut faire apparaître que le nom du serveur CIFS et le nom NetBIOS sont différents.
 a| 
. Désactivez la vérification du nom NetBIOS sur le serveur Windows en ajoutant la clé de Registre suivante avec la valeur définie sur `1`:
+
`"HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\LanmanServer\Parameters\DisableStrictNameChecking"`

+
Pour en savoir plus sur cette clé de Registre, contactez le support technique de Microsoft.

+
http://["Support Microsoft"]

. Redémarrez le contrôleur de domaine.


|===