---
permalink: smb-admin/how-ontap-preserves-unix-permissions-concept.html 
sidebar: sidebar 
keywords: file, flexvol, volume, unix, permission, edit, windows, application, preserve, ontap, how ontap preserves unix permissions 
summary: 'Lorsque les fichiers d"un volume FlexVol qui disposent actuellement d"autorisations UNIX sont modifiés et enregistrés par des applications Windows, ONTAP peut préserver les autorisations UNIX.' 
---
= Comment ONTAP préserve les autorisations UNIX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque les fichiers d'un volume FlexVol qui disposent actuellement d'autorisations UNIX sont modifiés et enregistrés par des applications Windows, ONTAP peut préserver les autorisations UNIX.

Lorsque des applications sur des clients Windows modifient et enregistrent des fichiers, elles lisent les propriétés de sécurité du fichier, créent un nouveau fichier temporaire, appliquent ces propriétés au fichier temporaire, puis donnent au fichier temporaire le nom du fichier d'origine.

Lorsque les clients Windows effectuent une requête pour les propriétés de sécurité, ils reçoivent une ACL construite qui représente exactement les autorisations UNIX. Le seul but de cette liste de contrôle d'accès construite est de préserver les autorisations UNIX du fichier lorsque les fichiers sont mis à jour par les applications Windows pour s'assurer que les fichiers résultants ont les mêmes autorisations UNIX. ONTAP ne définit pas d'ACL NTFS à l'aide de la liste de contrôle d'accès construite.
