---
permalink: smb-admin/how-name-mappings-are-used-concept.html 
sidebar: sidebar 
keywords: ontap, name, map, cifs, identify, identifies, unix, information, connect, credentials, client, configure name mappings 
summary: 'ONTAP fait appel au mappage de noms pour mapper les identités CIFS aux identités UNIX, les identités Kerberos aux identités UNIX et les identités UNIX aux identités CIFS. Il a besoin de ces informations pour obtenir les informations d"identification des utilisateurs et fournir un accès approprié aux fichiers, qu"ils se connectent à partir d"un client NFS ou d"un client CIFS.' 
---
= En savoir plus sur la configuration des mappages de noms SMB de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP fait appel au mappage de noms pour mapper les identités CIFS aux identités UNIX, les identités Kerberos aux identités UNIX et les identités UNIX aux identités CIFS. Il a besoin de ces informations pour obtenir les informations d'identification des utilisateurs et fournir un accès approprié aux fichiers, qu'ils se connectent à partir d'un client NFS ou d'un client CIFS.

Il existe deux exceptions lorsque vous n'avez pas besoin d'utiliser le mappage de noms :

* Vous configurez un environnement UNIX pur et ne prévoyez pas d'utiliser l'accès CIFS ou le style de sécurité NTFS sur les volumes.
* Vous configurez l'utilisateur par défaut à utiliser à la place.
+
Dans ce scénario, le mappage de noms n'est pas nécessaire car au lieu de mapper chaque identifiant client individuel, toutes les informations d'identification client sont mappées au même utilisateur par défaut.



Notez que vous pouvez utiliser le mappage de noms uniquement pour les utilisateurs, pas pour les groupes.

Toutefois, vous pouvez mapper un groupe d'utilisateurs individuels à un utilisateur spécifique. Par exemple, vous pouvez mapper tous les utilisateurs AD qui commencent ou se terminent par le mot VENTES à un utilisateur UNIX spécifique et à l'UID de l'utilisateur.
