---
permalink: smb-admin/index.html 
sidebar: sidebar 
keywords: smb, cifs, protocol, file, access, overview 
summary: 'Les fonctionnalités d"accès aux fichiers ONTAP disponibles pour le protocole SMB, telles que l"activation d"un serveur CIFS, la création de partages et l"activation des services Microsoft.' 
---
= Présentation de SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les fonctionnalités d'accès aux fichiers ONTAP sont disponibles pour le protocole SMB. Vous pouvez activer un serveur CIFS, créer des partages et activer les services Microsoft.

[NOTE]
====
_SMB_ (Server message Block) désigne les dialectes modernes du protocole CIFS (Common Internet File System). Vous verrez toujours _CIFS_ dans l'interface de ligne de commande (CLI) ONTAP et dans les outils de gestion OnCommand.

====
Vous devez utiliser ces procédures dans les circonstances suivantes :

* Vous souhaitez connaître la plage de fonctionnalités du protocole SMB de ONTAP.
* Vous souhaitez effectuer des tâches de configuration et de maintenance moins courantes, et non pas une configuration SMB de base.
* Vous souhaitez utiliser l'interface de ligne de commande et non System Manager, ni un outil de création de scripts automatisé.

