---
permalink: smb-admin/limits-configuring-unix-symbolic-links-concept.html 
sidebar: sidebar 
keywords: limit, configuring, configure, unix, symbolic, link, smb, access, limits when configuring unix symbolic links for smb access 
summary: 'Vous devez connaître certaines limites lors de la configuration de liens symboliques UNIX pour l"accès SMB.' 
---
= Limites lors de la configuration de liens symboliques UNIX pour l'accès SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez connaître certaines limites lors de la configuration de liens symboliques UNIX pour l'accès SMB.

|===
| Limite | Description 


 a| 
45
 a| 
Longueur maximale du nom de serveur CIFS que vous pouvez spécifier lors de l'utilisation d'un FQDN pour le nom du serveur CIFS.

[NOTE]
====
Vous pouvez également spécifier le nom du serveur CIFS sous la forme d'un nom NetBIOS, limité à 15 caractères.

====


 a| 
80
 a| 
Longueur maximale du nom de partage.



 a| 
256
 a| 
Longueur maximale du chemin UNIX que vous pouvez spécifier lors de la création d'un lien symbolique ou lors de la modification du chemin UNIX d'un lien symbolique existant.le chemin UNIX doit commencer par un ""/`" (slash) and end with a "`/». Les barres obliques de début et de fin font partie de la limite de 256 caractères.



 a| 
256
 a| 
Longueur maximale du chemin CIFS que vous pouvez spécifier lors de la création d'un lien symbolique ou lors de la modification du chemin CIFS d'un lien symbolique existant.le chemin CIFS doit commencer par « »/`" (slash) and end with a "`/». Les barres obliques de début et de fin font partie de la limite de 256 caractères.

|===
.Informations associées
xref:create-symbolic-link-mappings-task.adoc[Création de mappages de liens symboliques pour les partages SMB]
