---
permalink: smb-admin/list-supported-privileges-reference.html 
sidebar: sidebar 
keywords: ontap, predefined, support, privilege, local, group, add, user, exist, domain, list of supported privileges 
summary: 'ONTAP dispose d"un ensemble prédéfini de privilèges pris en charge. Certains groupes locaux prédéfinis ont certains de ces privilèges ajoutés par défaut. Vous pouvez également ajouter ou supprimer des privilèges des groupes prédéfinis ou créer de nouveaux utilisateurs ou groupes locaux et ajouter des privilèges aux groupes que vous avez créés ou aux utilisateurs et groupes de domaine existants.' 
---
= Liste des privilèges SMB ONTAP pris en charge
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP dispose d'un ensemble prédéfini de privilèges pris en charge. Certains groupes locaux prédéfinis ont certains de ces privilèges ajoutés par défaut. Vous pouvez également ajouter ou supprimer des privilèges des groupes prédéfinis ou créer de nouveaux utilisateurs ou groupes locaux et ajouter des privilèges aux groupes que vous avez créés ou aux utilisateurs et groupes de domaine existants.

Le tableau ci-dessous répertorie les privilèges pris en charge sur la machine virtuelle de stockage (SVM) et fournit la liste des groupes BUILTIN avec des privilèges attribués :

|===
| Nom de privilège | Paramètre de sécurité par défaut | Description 


 a| 
`SeTcbPrivilege`
 a| 
Aucune
 a| 
Faire partie du système d'exploitation



 a| 
`SeBackupPrivilege`
 a| 
`BUILTIN\Administrators`, `BUILTIN\Backup Operators`
 a| 
Sauvegardez des fichiers et des répertoires, en remplaçant les listes de contrôle d'accès



 a| 
`SeRestorePrivilege`
 a| 
`BUILTIN\Administrators`, `BUILTIN\Backup Operators`
 a| 
Restaurez les fichiers et les répertoires, en remplaçant les listes de contrôle d'accès, définissez tout ID utilisateur ou groupe valide comme propriétaire du fichier



 a| 
`SeTakeOwnershipPrivilege`
 a| 
`BUILTIN\Administrators`
 a| 
Prendre possession de fichiers ou d'autres objets



 a| 
`SeSecurityPrivilege`
 a| 
`BUILTIN\Administrators`
 a| 
Gérer les audits

Cela inclut l'affichage, le vidage et l'effacement du journal de sécurité.



 a| 
`SeChangeNotifyPrivilege`
 a| 
`BUILTIN\Administrators`, `BUILTIN\Backup Operators`, `BUILTIN\Power Users`, `BUILTIN\Users`, `Everyone`
 a| 
Vérification de la traverse de dérivation

Les utilisateurs disposant de ce privilège ne sont pas tenus d'avoir des autorisations traverse (x) pour traverser des dossiers, des liens symboliques ou des jonctions.

|===
.Informations associées
* xref:assign-privileges-concept.adoc[En savoir plus sur l'attribution de privilèges]
* xref:configure-bypass-traverse-checking-concept.adoc[En savoir plus sur la configuration de la vérification de contournement]

