---
permalink: smb-admin/manage-local-group-membership-task.html 
sidebar: sidebar 
keywords: manage, local, group, membership, add, removing, remove, local, domain, user, domain, group, control, access, place, privilege, associate, manage local group membership 
summary: 'Vous pouvez gérer l"appartenance à un groupe local en ajoutant et en supprimant des utilisateurs locaux ou de domaine, ou en ajoutant et supprimant des groupes de domaines. Ceci est utile si vous souhaitez contrôler l"accès aux données en fonction des contrôles d"accès placés sur le groupe ou si vous souhaitez que les utilisateurs disposent de privilèges associés à ce groupe.' 
---
= Gérer l'appartenance à un groupe local
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez gérer l'appartenance à un groupe local en ajoutant et en supprimant des utilisateurs locaux ou de domaine, ou en ajoutant et supprimant des groupes de domaines. Ceci est utile si vous souhaitez contrôler l'accès aux données en fonction des contrôles d'accès placés sur le groupe ou si vous souhaitez que les utilisateurs disposent de privilèges associés à ce groupe.

Directives pour l'ajout de membres à un groupe local :

* Vous ne pouvez pas ajouter d'utilisateurs au groupe spécial _Everyone_.
* Le groupe local doit exister avant de pouvoir y ajouter un utilisateur.
* L'utilisateur doit exister avant de pouvoir ajouter l'utilisateur à un groupe local.
* Vous ne pouvez pas ajouter un groupe local à un autre groupe local.
* Pour ajouter un utilisateur ou un groupe de domaine à un groupe local, Data ONTAP doit pouvoir résoudre le nom en SID.


Directives pour le retrait de membres d'un groupe local :

* Vous ne pouvez pas supprimer des membres du groupe spécial _Everyone_.
* Le groupe dont vous souhaitez supprimer un membre doit exister.
* ONTAP doit pouvoir résoudre les noms des membres que vous souhaitez supprimer du groupe vers un SID correspondant.


.Étape
. Ajouter ou supprimer un membre d'un groupe.
+
|===
| Les fonctions que vous recherchez... | Utilisez ensuite la commande... 


 a| 
Ajouter un membre à un groupe
 a| 
`+vserver cifs users-and-groups local-group add-members -vserver _vserver_name_ -group-name _group_name_ -member-names name[,...]+` Vous pouvez spécifier une liste délimitée par des virgules d'utilisateurs locaux, d'utilisateurs de domaine ou de groupes de domaine à ajouter au groupe local spécifié.



 a| 
Supprimer un membre d'un groupe
 a| 
`+vserver cifs users-and-groups local-group remove-members -vserver _vserver_name_ -group-name _group_name_ -member-names name[,...]+` Vous pouvez spécifier une liste délimitée par des virgules d'utilisateurs locaux, d'utilisateurs de domaine ou de groupes de domaine à supprimer du groupe local spécifié.

|===
+
L'exemple suivant ajoute un utilisateur local « `SMB_SERVER\sue` » et un groupe de domaine « AD_DOM\dom_eng »au groupe local « `SMB_SERVER\engineering' » sur la SVM vs1 :

+
[listing]
----
cluster1::> vserver cifs users-and-groups local-group add-members -vserver vs1 -group-name SMB_SERVER\engineering -member-names SMB_SERVER\sue,AD_DOMAIN\dom_eng
----
+
L'exemple suivant supprime les utilisateurs locaux « `SMB_SERVER\sue` » et « `SMB_SERVER\james` du groupe local « `SMB_SERVER\engineering' » sur la SVM vs1 :

+
[listing]
----
cluster1::> vserver cifs users-and-groups local-group remove-members -vserver vs1 -group-name SMB_SERVER\engineering -member-names SMB_SERVER\sue,SMB_SERVER\james
----


xref:display-members-local-groups-task.adoc[Affichage des informations relatives aux membres des groupes locaux]
