---
permalink: smb-admin/manage-local-user-accounts.html 
sidebar: sidebar 
keywords: modify, local, user, account, change, exist, name, description, enable, disable, rename, compromise, administrative, modify local user accounts 
summary: 'Vous pouvez activer un compte utilisateur local pour autoriser l"accès aux données SVM via SMB, ou le désactiver pour empêcher l"accès. Vous pouvez également modifier le compte pour mettre à jour le nom complet de l"utilisateur, sa description ou son statut activé. Si nécessaire, vous pouvez renommer le compte pour des raisons administratives, comme un nom d"utilisateur compromis. Vous pouvez également consulter les groupes locaux auxquels appartient un utilisateur, ce qui aide à déterminer l"accès aux fichiers et dossiers et à résoudre les problèmes d"accès.' 
---
= Gérer les comptes d'utilisateurs SMB locaux ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez activer un compte utilisateur local pour autoriser l'accès aux données SVM via SMB, ou le désactiver pour empêcher l'accès. Vous pouvez également modifier le compte pour mettre à jour le nom complet de l'utilisateur, sa description ou son statut activé. Si nécessaire, vous pouvez renommer le compte pour des raisons administratives, comme un nom d'utilisateur compromis. Vous pouvez également consulter les groupes locaux auxquels appartient un utilisateur, ce qui aide à déterminer l'accès aux fichiers et dossiers et à résoudre les problèmes d'accès.

|===
| Les fonctions que vous recherchez... | Entrez la commande... 


 a| 
Modifier le mot de passe de l'utilisateur local
 a| 
`vserver cifs users-and-groups local-user set-password -vserver <SVM_name> -user-name <user_name>`



 a| 
Activez ou désactivez le compte utilisateur local
 a| 
`vserver cifs users-and-groups local-user modify -vserver <SVM_name> -user-name <user_name> -is-account-disabled {true|false}`



 a| 
Affiche des informations détaillées sur le compte d'un utilisateur
 a| 
`vserver cifs users-and-groups local-user show -instance -vserver <SVM_name> -user-name <user_name>`



 a| 
Afficher les informations d'appartenance des utilisateurs locaux pour un utilisateur local spécifié
 a| 
`vserver cifs users-and-groups local-user show-membership -user-name <user_name>`



 a| 
Affiche les informations d'appartenance de l'utilisateur local pour le groupe local dont cet utilisateur local est membre
 a| 
`vserver cifs users-and-groups local-user show-membership -membership _group_name_`



 a| 
Afficher les informations d'appartenance des utilisateurs aux utilisateurs locaux associés à une machine virtuelle de stockage (SVM) spécifiée
 a| 
`vserver cifs users-and-groups local-user show-membership -vserver <SVM_name>`



 a| 
Affiche des informations détaillées pour tous les utilisateurs locaux sur un SVM spécifié
 a| 
`vserver cifs users-and-groups local-user show-membership -instance -vserver <SVM_name>`



 a| 
Affichage des informations relatives à tous les utilisateurs sur la machine virtuelle de stockage (SVM)
 a| 
`vserver cifs users-and-groups local-user show -vserver <SVM_name>`



 a| 
Modifier la description de l'utilisateur local
 a| 
`vserver cifs users-and-groups local-user modify -vserver <SVM_name> -user-name <user_name> -description text`

Si la description contient un espace, alors elle doit être placée entre guillemets doubles.



 a| 
Modifier le nom complet de l'utilisateur local
 a| 
`vserver cifs users-and-groups local-user modify -vserver <SVM_name> -user-name <user_name> -full-name text`

Si le nom complet contient un espace, il doit être placé entre guillemets doubles.



 a| 
Renommez le compte d'utilisateur local
 a| 
`vserver cifs users-and-groups local-user rename -vserver <SVM_name> -user-name <user_name> -new-user-name <new_user_name>`

Lors du renommage d'un utilisateur local, le nouveau nom d'utilisateur doit rester associé au même serveur CIFS que l'ancien nom d'utilisateur.

|===
.Exemple
L'exemple suivant renomme l'utilisateur local « CIFS_SERVER\sue » en « CIFS_SERVER\sue_New » sur la machine virtuelle de stockage (SVM, précédemment appelé vServer) vs1 :

[listing]
----
cluster1::> vserver cifs users-and-groups local-user rename -user-name CIFS_SERVER\sue -new-user-name CIFS_SERVER\sue_new -vserver vs1
----
.Exemple
L'exemple suivant affiche les informations relatives à tous les utilisateurs locaux sur le SVM vs1 :

[listing]
----
cluster1::> vserver cifs users-and-groups local-user show -vserver vs1
Vserver  User Name                   Full Name     Description
-------- --------------------------- ------------- -------------
vs1      CIFS_SERVER\Administrator   James Smith   Built-in administrator account
vs1      CIFS_SERVER\sue             Sue   Jones
----
.Exemple
L'exemple suivant définit le mot de passe pour l'utilisateur local « CIFS_SERVER\sue » associé à une machine virtuelle de stockage (SVM, anciennement Vserver) vs1 :

[listing]
----
cluster1::> vserver cifs users-and-groups local-user set-password -user-name CIFS_SERVER\sue -vserver vs1

Enter the new password:
Confirm the new password:
----
.Exemple
L'exemple suivant affiche les informations d'appartenance de tous les utilisateurs locaux sur le SVM vs1 ; l'utilisateur « CIFS_SERVER\Administrator » est membre du groupe « BUILTIN\Administrators » et « CIFS_SERVER\sue » est membre du groupe « CIFS_SERVER\g1 » :

[listing]
----
cluster1::> vserver cifs users-and-groups local-user show-membership -vserver vs1
Vserver    User Name                    Membership
---------- ---------------------------- ------------------------
vs1        CIFS_SERVER\Administrator    BUILTIN\Administrators
           CIFS_SERVER\sue              CIFS_SERVER\g1
----
.Informations associées
* Pour en savoir plus, `vserver cifs` consultez le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs["Référence de commande ONTAP"^].
* xref:enable-disable-password-complexity-local-users-task.adoc[Configurer la complexité du mot de passe pour les utilisateurs locaux]
* xref:display-server-security-settings-task.adoc[Afficher des informations sur les paramètres de sécurité du serveur]




== Supprimer les comptes utilisateurs SMB ONTAP locaux

Vous pouvez supprimer des comptes utilisateurs locaux de votre machine virtuelle de stockage (SVM) s'ils ne sont plus nécessaires pour l'authentification SMB locale sur le serveur CIFS ou pour déterminer les droits d'accès aux données contenues dans votre SVM.

.Description de la tâche
Tenez compte des points suivants lors de la suppression d'utilisateurs locaux :

* Le système de fichiers n'est pas modifié.
+
Les descripteurs de sécurité Windows sur les fichiers et les répertoires qui font référence à cet utilisateur ne sont pas ajustés.

* Toutes les références aux utilisateurs locaux sont supprimées des bases de données d'appartenance et de privilèges.
* Les utilisateurs standard bien connus tels que Administrateur ne peuvent pas être supprimés.


.Étapes
. Déterminez le nom du compte d'utilisateur local que vous souhaitez supprimer :
+
[source, cli]
----
vserver cifs users-and-groups local-user show -vserver <SVM_name>
----
. Supprimer l'utilisateur local :
+
[source, cli]
----
vserver cifs users-and-groups local-user delete -vserver <SVM_name> -user-name <user_name>
----
. Vérifiez que le compte utilisateur est supprimé :
+
[source, cli]
----
vserver cifs users-and-groups local-user show -vserver <SVM_name>
----


L'exemple suivant supprime l'utilisateur local « CIFS_SERVER\sue » associé à la SVM vs1 :

[listing]
----
cluster1::> vserver cifs users-and-groups local-user show -vserver vs1
Vserver  User Name                   Full Name      Description
-------- --------------------------- -------------- -------------
vs1      CIFS_SERVER\Administrator   James Smith    Built-in administrator account
vs1      CIFS_SERVER\sue             Sue   Jones


cluster1::> vserver cifs users-and-groups local-user delete -vserver vs1 -user-name CIFS_SERVER\sue

cluster1::> vserver cifs users-and-groups local-user show -vserver vs1
Vserver      User Name                   Full Name      Description
-------- --------------------------- -------------- -------------
vs1      CIFS_SERVER\Administrator   James Smith    Built-in administrator account
----