---
permalink: smb-admin/manage-acls-dynamic-access-control-aces-task.html 
sidebar: sidebar 
keywords: resource, acl, applied, apply, dynamic, access, control, ace, disable, dynamic, storage, virtual, machine, svm, remove, non-dynamic, manage acls that contain dynamic access control aces when dynamic access control is disabled 
summary: 'Si vous disposez de ressources dont les listes de contrôle d"accès sont appliquées avec les ACE de contrôle d"accès dynamique et que vous désactivez le contrôle d"accès dynamique sur la machine virtuelle de stockage (SVM), vous devez supprimer les ACE de contrôle d"accès dynamique avant de pouvoir gérer les ACE de contrôle d"accès non dynamique sur cette ressource.' 
---
= Gérer les listes de contrôle d'accès qui contiennent des ACE de contrôle d'accès dynamique lorsque le contrôle d'accès dynamique est désactivé
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous disposez de ressources dont les listes de contrôle d'accès sont appliquées avec les ACE de contrôle d'accès dynamique et que vous désactivez le contrôle d'accès dynamique sur la machine virtuelle de stockage (SVM), vous devez supprimer les ACE de contrôle d'accès dynamique avant de pouvoir gérer les ACE de contrôle d'accès non dynamique sur cette ressource.

Une fois le contrôle d'accès dynamique désactivé, vous ne pouvez pas supprimer les ACE existants de contrôle d'accès non dynamique ou ajouter de nouveaux ACE de contrôle d'accès non dynamique tant que vous n'avez pas supprimé les ACE de contrôle d'accès dynamique existants.

Vous pouvez utiliser n'importe quel outil que vous utilisez normalement pour gérer les listes de contrôle d'accès pour effectuer ces étapes.

.Étapes
. Déterminez quels ACE de contrôle d'accès dynamique sont appliqués à la ressource.
. Supprimez les ACE de contrôle d'accès dynamique de la ressource.
. Ajoutez ou supprimez des ACE de contrôle d'accès non dynamiques comme vous le souhaitez de la ressource.

