---
permalink: smb-admin/modify-dynamic-dns-domain-before-moving-server-task.html 
sidebar: sidebar 
keywords: active, directory-integrated, dns, server, dynamic, register, smb, server, record, modify, ddns, storage, virtual, machine, svm, modify the dynamic dns domain on the svm before moving the smb server 
summary: 'Si vous souhaitez que le serveur DNS intégré à Active Directory enregistre de manière dynamique les enregistrements DNS du serveur SMB dans DNS lorsque vous déplacez le serveur SMB vers un autre domaine, vous devez modifier DNS dynamique (DDNS) sur la machine virtuelle de stockage (SVM) avant de déplacer le serveur SMB.' 
---
= Modifier le domaine DNS dynamique sur le SVM avant de déplacer le serveur SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous souhaitez que le serveur DNS intégré à Active Directory enregistre de manière dynamique les enregistrements DNS du serveur SMB dans DNS lorsque vous déplacez le serveur SMB vers un autre domaine, vous devez modifier DNS dynamique (DDNS) sur la machine virtuelle de stockage (SVM) avant de déplacer le serveur SMB.

.Avant de commencer
Les services de nom DNS doivent être modifiés sur le SVM afin d'utiliser le domaine DNS qui contient les enregistrements d'emplacement de service pour le nouveau domaine qui contiendra le compte ordinateur du serveur SMB. Si vous utilisez Secure DDNS, vous devez utiliser des serveurs de noms DNS intégrés à Active Directory.

.Description de la tâche
Bien que DDNS (si configuré sur la SVM) ajoute automatiquement les enregistrements DNS des LIFs de données au nouveau domaine, les enregistrements DNS du domaine d'origine ne sont pas automatiquement supprimés du serveur DNS d'origine. Vous devez les supprimer manuellement.

Pour effectuer les modifications DDNS avant de déplacer le serveur SMB, reportez-vous à la rubrique suivante :

link:../networking/configure_dynamic_dns_services.html["Configuration des services DNS dynamiques"]
