---
permalink: smb-admin/modify-local-groups-reference.html 
sidebar: sidebar 
keywords: modify, exist, local, group, description, exist, local, group, renaming, rename, modify local groups 
summary: 'Vous pouvez modifier les groupes locaux existants en modifiant la description d"un groupe local existant ou en renommant ce groupe.' 
---
= Modifier les groupes SMB ONTAP locaux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier les groupes locaux existants en modifiant la description d'un groupe local existant ou en renommant ce groupe.

|===
| Les fonctions que vous recherchez... | Utilisez la commande... 


 a| 
Modifier la description du groupe local
 a| 
`vserver cifs users-and-groups local-group modify -vserver _vserver_name_ -group-name _group_name_ -description text` Si la description contient un espace, elle doit être placée entre guillemets.



 a| 
Renommer le groupe local
 a| 
`vserver cifs users-and-groups local-group rename -vserver _vserver_name_ -group-name _group_name_ -new-group-name _new_group_name_`

|===
.Exemples
L'exemple suivant renomme le groupe local « CIFS_SERVER\engineering » en « CIFS_SERVER\engineering_New » :

[listing]
----
cluster1::> vserver cifs users-and-groups local-group rename -vserver vs1 -group-name CIFS_SERVER\engineering -new-group-name CIFS_SERVER\engineering_new
----
L'exemple suivant modifie la description du groupe local « CIFS_SERVER\engineering » :

[listing]
----
cluster1::> vserver cifs users-and-groups local-group modify -vserver vs1 -group-name CIFS_SERVER\engineering -description "New Description"
----