---
permalink: smb-admin/modify-server-kerberos-security-settings-task.html 
sidebar: sidebar 
keywords: modify, cifs, server, kerberos, security, setting, clock, skew, time, ticket, lifetime, renewal, modify the cifs server kerberos security ticket settings 
summary: 'Vous pouvez modifier certains paramètres de sécurité Kerberos pour le serveur CIFS, notamment le temps d"inclinaison maximal autorisé de l"horloge Kerberos, la durée de vie du ticket Kerberos et le nombre maximum de jours de renouvellement de ticket.' 
---
= Modifiez les paramètres de sécurité Kerberos du serveur CIFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier certains paramètres de sécurité Kerberos pour le serveur CIFS, notamment le temps d'inclinaison maximal autorisé de l'horloge Kerberos, la durée de vie du ticket Kerberos et le nombre maximum de jours de renouvellement de ticket.

.Description de la tâche
Modification des paramètres Kerberos du serveur CIFS à l'aide de `vserver cifs security modify` La commande modifie les paramètres uniquement sur la machine virtuelle de stockage (SVM) que vous spécifiez avec le `-vserver` paramètre. Vous pouvez gérer de manière centralisée les paramètres de sécurité Kerberos pour tous les SVM du cluster appartenant au même domaine Active Directory à l'aide des objets de stratégie de groupe Active Directory.

.Étapes
. Effectuez une ou plusieurs des opérations suivantes :
+
|===


| Les fonctions que vous recherchez... | Entrer... 


 a| 
Spécifiez le temps d'inclinaison maximal autorisé de l'horloge Kerberos en minutes.
 a| 
`vserver cifs security modify -vserver _vserver_name_ -kerberos-clock-skew _integer_in_minutes_`

La valeur par défaut est 5 minutes.



 a| 
Spécifiez la durée de vie du ticket Kerberos en heures.
 a| 
`vserver cifs security modify -vserver _vserver_name_ -kerberos-ticket-age integer_in_hours`

Le paramètre par défaut est 10 heures.



 a| 
Spécifiez le nombre maximum de jours de renouvellement de billet.
 a| 
`vserver cifs security modify -vserver _vserver_name_ -kerberos-renew-age _integer_in_days_`

Le paramètre par défaut est 7 jours.



 a| 
Spécifiez le délai d'expiration des sockets sur les KDC après lequel tous les KDC sont marqués comme inaccessibles.
 a| 
`vserver cifs security modify -vserver _vserver_name_ -kerberos-kdc-timeout _integer_in_seconds_`

Le réglage par défaut est de 3 secondes.

|===
. Vérifiez les paramètres de sécurité Kerberos :
+
`vserver cifs security show -vserver _vserver_name_`



.Exemple
L'exemple suivant apporte les modifications suivantes à la sécurité Kerberos : « Kerberos Clock Skew » est défini sur 3 minutes et « Kerberos Ticket Age » est défini sur 8 heures pour le SVM vs1 :

[listing]
----
cluster1::> vserver cifs security modify -vserver vs1 -kerberos-clock-skew 3 -kerberos-ticket-age 8

cluster1::> vserver cifs security show -vserver vs1

Vserver: vs1

                    Kerberos Clock Skew:                   3 minutes
                    Kerberos Ticket Age:                   8 hours
                   Kerberos Renewal Age:                   7 days
                   Kerberos KDC Timeout:                   3 seconds
                    Is Signing Required:               false
        Is Password Complexity Required:                true
   Use start_tls For AD LDAP connection:               false
              Is AES Encryption Enabled:               false
                 LM Compatibility Level:  lm-ntlm-ntlmv2-krb
             Is SMB Encryption Required:               false
----
.Informations associées
link:display-server-security-settings-task.html["Affichage d'informations sur les paramètres de sécurité du serveur CIFS"]

link:supported-gpos-concept.html["Stratégies de groupe prises en charge"]

link:applying-group-policy-objects-concept.html["Application d'objets de stratégie de groupe aux serveurs CIFS"]
