---
permalink: smb-admin/modify-local-user-accounts-reference.html 
sidebar: sidebar 
keywords: modify, local, user, account, change, exist, name, description, enable, disable, rename, compromise, administrative, modify local user accounts 
summary: 'Vous pouvez modifier un compte d"utilisateur local si vous souhaitez modifier le nom complet ou la description d"un utilisateur existant et si vous souhaitez activer ou désactiver le compte d"utilisateur. Vous pouvez également renommer un compte d’utilisateur local si le nom de l’utilisateur est compromis ou si un changement de nom est nécessaire à des fins administratives.' 
---
= Modifier les comptes utilisateurs SMB ONTAP locaux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez modifier un compte d'utilisateur local si vous souhaitez modifier le nom complet ou la description d'un utilisateur existant et si vous souhaitez activer ou désactiver le compte d'utilisateur. Vous pouvez également renommer un compte d'utilisateur local si le nom de l'utilisateur est compromis ou si un changement de nom est nécessaire à des fins administratives.

|===
| Les fonctions que vous recherchez... | Entrez la commande... 


 a| 
Modifier le nom complet de l'utilisateur local
 a| 
`vserver cifs users-and-groups local-user modify -vserver _vserver_name_ -user-name _user_name_ ‑full-name text` Si le nom complet contient un espace, il doit être placé entre guillemets.



 a| 
Modifier la description de l'utilisateur local
 a| 
`vserver cifs users-and-groups local-user modify -vserver _vserver_name_ -user-name _user_name_ ‑description text` Si la description contient un espace, elle doit être placée entre guillemets.



 a| 
Activez ou désactivez le compte utilisateur local
 a| 
`vserver cifs users-and-groups local-user modify -vserver _vserver_name_ -user-name _user_name_ -is-account-disabled {true|false}`



 a| 
Renommez le compte d'utilisateur local
 a| 
`vserver cifs users-and-groups local-user rename -vserver _vserver_name_ -user-name _user_name_ -new-user-name _new_user_name_` Lors du changement de nom d'un utilisateur local, le nouveau nom d'utilisateur doit rester associé au même serveur CIFS que l'ancien nom d'utilisateur.

|===
.Exemple
L'exemple suivant renomme l'utilisateur local « CIFS_SERVER\sue » en « CIFS_SERVER\sue_New » sur la machine virtuelle de stockage (SVM, précédemment appelé vServer) vs1 :

[listing]
----
cluster1::> vserver cifs users-and-groups local-user rename -user-name CIFS_SERVER\sue -new-user-name CIFS_SERVER\sue_new -vserver vs1
----