---
permalink: smb-admin/offline-files-allow-caching-concept.html 
sidebar: sidebar 
keywords: ontap, support, microsoft, offline, file, feature, client-side, caching, cache, file, local, host, offline, disconnect, network, use offline files to allow caching of files for offline use 
summary: 'ONTAP prend en charge la fonctionnalité Microsoft Offline Files ou la mise en cache côté client, qui permet la mise en cache des fichiers sur l"hôte local pour une utilisation hors ligne. Les utilisateurs peuvent utiliser la fonctionnalité fichiers hors ligne pour continuer à travailler sur des fichiers même lorsqu"ils sont déconnectés du réseau.' 
---
= Utilisez les fichiers hors ligne pour permettre la mise en cache des fichiers pour une utilisation hors ligne
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP prend en charge la fonctionnalité de fichiers hors ligne Microsoft, ou _mise en cache côté client_, qui permet de mettre les fichiers en cache sur l'hôte local pour une utilisation hors ligne. Les utilisateurs peuvent utiliser la fonctionnalité fichiers hors ligne pour continuer à travailler sur des fichiers même lorsqu'ils sont déconnectés du réseau.

Vous pouvez spécifier si les documents et programmes utilisateur Windows sont automatiquement mis en cache sur un partage ou si les fichiers doivent être sélectionnés manuellement pour la mise en cache. La mise en cache manuelle est activée par défaut pour les nouveaux partages. Les fichiers mis hors ligne sont synchronisés avec le disque local du client Windows. La synchronisation a lieu lorsque la connectivité réseau à un partage de système de stockage spécifique est restaurée.

Étant donné que les fichiers et dossiers hors ligne conservent les mêmes autorisations d'accès que la version des fichiers et dossiers enregistrés sur le serveur CIFS, l'utilisateur doit disposer des autorisations suffisantes sur les fichiers et dossiers enregistrés sur le serveur CIFS pour effectuer des actions sur les fichiers et dossiers hors ligne.

Lorsque l'utilisateur et une autre personne du réseau modifient le même fichier, l'utilisateur peut enregistrer la version locale du fichier sur le réseau, conserver l'autre version ou enregistrer les deux. Si l'utilisateur conserve les deux versions, un nouveau fichier avec les modifications de l'utilisateur local est enregistré localement et le fichier mis en cache est écrasé par des modifications de la version du fichier enregistré sur le serveur CIFS.

Vous pouvez configurer des fichiers hors ligne par partage à l'aide des paramètres de configuration du partage. Vous pouvez choisir l'une des quatre configurations de dossiers hors ligne lorsque vous créez ou modifiez des partages :

* Pas de mise en cache
+
Désactive la mise en cache côté client pour le partage. Les fichiers et les dossiers ne sont pas automatiquement mis en cache localement sur les clients et les utilisateurs ne peuvent pas choisir de mettre en cache des fichiers ou des dossiers localement.

* Mise en cache manuelle
+
Permet la sélection manuelle des fichiers à mettre en cache sur le partage. Il s'agit du paramètre par défaut. Par défaut, aucun fichier ni dossier n'est mis en cache sur le client local. Les utilisateurs peuvent choisir les fichiers et dossiers qu'ils souhaitent mettre en cache localement pour une utilisation hors ligne.

* Mise en cache automatique des documents
+
Permet de mettre automatiquement en cache les documents utilisateur sur le partage. Seuls les fichiers et les dossiers accessibles sont mis en cache localement.

* Mise en cache automatique des programmes
+
Permet de mettre automatiquement en cache les programmes et les documents utilisateur sur le partage. Seuls les fichiers, les dossiers et les programmes accessibles sont mis en cache localement. De plus, ce paramètre permet au client d'exécuter des exécutables mis en cache localement, même lorsqu'il est connecté au réseau.



Pour plus d'informations sur la configuration des fichiers hors ligne sur les serveurs et les clients Windows, consultez la bibliothèque Microsoft TechNet.

xref:roaming-profiles-store-user-profiles-concept.adoc[Utilisation de profils itinérants pour stocker les profils utilisateurs de façon centralisée sur un serveur CIFS associé à la SVM]

xref:folder-redirection-store-data-concept.adoc[Utilisation de la redirection de dossiers pour stocker des données sur un serveur CIFS]

xref:branchcache-cache-share-content-branch-office-concept.adoc[Utilisation de BranchCache pour mettre en cache le contenu de partage SMB dans une succursale]

http://technet.microsoft.com/en-us/library/["Bibliothèque Microsoft TechNet : technet.microsoft.com/en-us/library/"]
