---
permalink: smb-admin/provide-security-access-based-enumeration-task.html 
sidebar: sidebar 
keywords: access-based, enumeration, abe, enable, smb, share, user, folder, file, contain, within, share, individual, permission, restriction, resource, environment, provide folder security on shares with access-based enumeration 
summary: 'Lorsque l"énumération basée sur l"accès (ABE) est activée sur un partage SMB, les utilisateurs qui n"ont pas l"autorisation d"accéder à un dossier ou un fichier contenu dans le partage (que ce soit par le biais de restrictions d"autorisation individuelles ou de groupe) ne voient pas cette ressource partagée affichée dans leur environnement.' 
---
= Assurez la sécurité des dossiers sur les partages dotés d'une vue d'ensemble de l'énumération basée sur l'accès
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque l'énumération basée sur l'accès (ABE) est activée sur un partage SMB, les utilisateurs qui n'ont pas l'autorisation d'accéder à un dossier ou un fichier contenu dans le partage (que ce soit par le biais de restrictions d'autorisation individuelles ou de groupe) ne voient pas cette ressource partagée affichée dans leur environnement, bien que le partage lui-même reste visible.

Les propriétés de partage conventionnelles vous permettent de spécifier quels utilisateurs (individuellement ou en groupes) ont l'autorisation d'afficher ou de modifier les fichiers ou dossiers contenus dans le partage. Cependant, elles ne vous permettent pas de contrôler si les dossiers ou les fichiers contenus dans le partage sont visibles pour les utilisateurs qui ne disposent pas de l'autorisation d'y accéder. Cela peut poser des problèmes si les noms de ces dossiers ou fichiers dans le partage décrivent des informations sensibles, telles que les noms des clients ou des produits en cours de développement.

L'énumération basée sur l'accès (ABE) étend les propriétés de partage pour inclure l'énumération des fichiers et dossiers dans le partage. ABE vous permet donc de filtrer l'affichage des fichiers et dossiers dans le partage en fonction des droits d'accès des utilisateurs. C'est-à-dire que le partage lui-même est visible pour tous les utilisateurs, mais les fichiers et les dossiers du partage peuvent être affichés ou masqués par les utilisateurs désignés. En plus de protéger les informations sensibles sur votre lieu de travail, ABE vous permet de simplifier l'affichage de grandes structures de répertoires pour le bénéfice des utilisateurs qui n'ont pas besoin d'accéder à toute votre gamme de contenus. Par exemple, le partage lui-même est visible pour tous les utilisateurs, mais les fichiers et dossiers du partage peuvent être affichés ou masqués.

Découvrez link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Performance_impact_when_using_CIFS_Access_Based_Enumeration["Impact sur les performances lors de l'utilisation d'une énumération basée sur SMB/CIFS"^].
