---
permalink: smb-admin/recover-files-folders-previous-versions-concept.html 
sidebar: sidebar 
keywords: ability, microsoft, previous, version, applicable, file, system, support, snapshot, copies, copy, form, enable, technolofy, integral, ontap, recover, file, recover files and folders using previous versions 
summary: 'La possibilité d"utiliser les versions précédentes de Microsoft s"applique aux systèmes de fichiers qui prennent en charge les instantanés sous une forme ou une autre et qui les ont activés. La technologie Snapshot fait partie intégrante de ONTAP. Les utilisateurs peuvent récupérer des fichiers et des dossiers à partir de snapshots à partir de leur client Windows en utilisant la fonction versions précédentes de Microsoft.' 
---
= Restaurer des fichiers et des dossiers à l'aide de la présentation des versions précédentes
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La possibilité d'utiliser les versions précédentes de Microsoft s'applique aux systèmes de fichiers qui prennent en charge les instantanés sous une forme ou une autre et qui les ont activés. La technologie Snapshot fait partie intégrante de ONTAP. Les utilisateurs peuvent récupérer des fichiers et des dossiers à partir de snapshots à partir de leur client Windows en utilisant la fonction versions précédentes de Microsoft.

La fonctionnalité versions précédentes permet aux utilisateurs de parcourir les snapshots ou de restaurer des données à partir d'un snapshot sans l'intervention d'un administrateur de stockage. Les versions précédentes ne peuvent pas être configurées. Elle est toujours activée. Si l'administrateur du stockage a rendu des instantanés disponibles sur un partage, l'utilisateur peut utiliser les versions précédentes pour effectuer les tâches suivantes :

* Restaurer les fichiers supprimés par inadvertance.
* Récupération après écrasement accidentel d'un fichier.
* Comparer les versions du fichier pendant le fonctionnement.


Les données stockées dans les snapshots sont en lecture seule. Les utilisateurs doivent enregistrer une copie d'un fichier à un autre emplacement pour apporter des modifications au fichier. Les snapshots sont régulièrement supprimés. Par conséquent, les utilisateurs doivent créer des copies des fichiers contenus dans les versions précédentes s'ils souhaitent conserver indéfiniment une version précédente d'un fichier.
