---
permalink: smb-admin/remove-privileges-local-domain-users-groups-task.html 
sidebar: sidebar 
keywords: manage, user, right, local, domain, group, removing, remove, privilege, enhance, security, allow, customize, maximum, remove privileges from local or domain users or groups 
summary: 'Vous pouvez gérer les droits d"utilisateur pour les utilisateurs ou groupes locaux ou de domaine en supprimant les privilèges. Cela vous permet de renforcer la sécurité en vous permettant de personnaliser le nombre maximal de privilèges dont disposent les utilisateurs et les groupes.' 
---
= Supprimez les privilèges des utilisateurs ou groupes locaux ou de domaine
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez gérer les droits d'utilisateur pour les utilisateurs ou groupes locaux ou de domaine en supprimant les privilèges. Cela vous permet de renforcer la sécurité en vous permettant de personnaliser le nombre maximal de privilèges dont disposent les utilisateurs et les groupes.

.Avant de commencer
L'utilisateur ou le groupe local ou de domaine dont les privilèges seront supprimés doit déjà exister.

.Description de la tâche
Vous devez garder à l'esprit les éléments suivants lorsque vous supprimez des privilèges des utilisateurs ou groupes locaux ou de domaine :

* Vous pouvez supprimer un ou plusieurs privilèges.
* Lors de la suppression de privilèges d'un utilisateur ou d'un groupe de domaines, ONTAP peut valider l'utilisateur ou le groupe de domaines en contactant le contrôleur de domaine.
+
La commande peut échouer si ONTAP n'est pas en mesure de contacter le contrôleur de domaine.



.Étapes
. Supprimer un ou plusieurs privilèges d'un utilisateur ou groupe local ou de domaine : `+vserver cifs users-and-groups privilege remove-privilege -vserver _vserver_name_ -user-or-group-name _name_ -privileges _privilege_[,...]+`
. Vérifiez que les privilèges souhaités ont été supprimés de l'objet : `vserver cifs users-and-groups privilege show -vserver _vserver_name_ ‑user-or-group-name _name_`


.Exemple
L'exemple suivant supprime les privilèges « `Enregistrer TcbPrivilege' » et « `Saba OwnershipPrivilege » de l'utilisateur « CIFS_SERVER\sue » sur la machine virtuelle de stockage (SVM, précédemment connue sous le nom de Vserver) vs1 :

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- ---------------
vs1       CIFS_SERVER\sue       SeTcbPrivilege
                                SeTakeOwnershipPrivilege

cluster1::> vserver cifs users-and-groups privilege remove-privilege -vserver vs1 -user-or-group-name CIFS_SERVER\sue -privileges SeTcbPrivilege,SeTakeOwnershipPrivilege

cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- -------------------
vs1       CIFS_SERVER\sue       -
----