---
permalink: smb-admin/remove-netbios-aliases-from-list-task.html 
sidebar: sidebar 
keywords: netbios, alias, cifs, server, remove, list, remove netbios aliases from the netbios alias list 
summary: 'Si vous n"avez pas besoin d"alias NetBIOS spécifiques pour un serveur CIFS, vous pouvez supprimer ces alias NetBIOS de la liste. Vous pouvez également supprimer tous les alias NetBIOS de la liste.' 
---
= Supprimez les alias NetBIOS de la liste d'alias NetBIOS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous n'avez pas besoin d'alias NetBIOS spécifiques pour un serveur CIFS, vous pouvez supprimer ces alias NetBIOS de la liste. Vous pouvez également supprimer tous les alias NetBIOS de la liste.

.Description de la tâche
Vous pouvez supprimer plusieurs alias NetBIOS à l'aide d'une liste délimitée par des virgules. Vous pouvez supprimer tous les alias NetBIOS d'un serveur CIFS en spécifiant `-` comme valeur pour le `-netbios-aliases` paramètre.

.Étapes
. Effectuez l'une des opérations suivantes :
+
|===
| Si vous souhaitez supprimer... | Entrer... 


 a| 
Alias NetBIOS spécifiques dans la liste
 a| 
`+vserver cifs remove-netbios-aliases -vserver _vserver_name_ -netbios-aliases _NetBIOS_alias_,...+`



 a| 
Tous les alias NetBIOS de la liste
 a| 
`vserver cifs remove-netbios-aliases -vserver _vserver_name_ -netbios-aliases -`

|===
+
`vserver cifs remove-netbios-aliases -vserver vs1 -netbios-aliases alias_1`

. Vérifiez que les alias NetBIOS spécifiés ont été supprimés : `vserver cifs show -vserver _vserver_name_ -display-netbios-aliases`
+
`vserver cifs show -vserver vs1 -display-netbios-aliases`

+
[listing]
----
Vserver: vs1

         Server Name: CIFS_SERVER
         NetBIOS Aliases: ALIAS_2, ALIAS_3
----

