---
permalink: smb-admin/requirements-odx-concept.html 
sidebar: sidebar 
keywords: odx, copy, offload, storage, virtual, machine, svm, requirement, requirements for using odx, odx 
summary: 'Avant de pouvoir utiliser ODX pour la réduction des déchargements de copies avec votre machine virtuelle de stockage (SVM), vous devez prendre en compte certaines exigences.' 
---
= Conditions requises pour l'utilisation d'ODX sur les serveurs ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de pouvoir utiliser ODX pour la réduction des déchargements de copies avec votre machine virtuelle de stockage (SVM), vous devez prendre en compte certaines exigences.



== Configuration requise pour la version ONTAP

Les versions d'ONTAP prennent en charge ODX pour la réduction des copies.



== Conditions requises pour la version SMB

* ONTAP prend en charge ODX avec SMB 3.0 et versions ultérieures.
* SMB 3.0 doit être activé sur le serveur CIFS pour que ODX puisse être activé :
+
** L'activation d'ODX active également SMB 3.0, si elle n'est pas déjà activée.
** La désactivation de SMB 3.0 désactive également ODX.






== Configuration requise pour le serveur et le client Windows

Avant de pouvoir utiliser ODX pour la réduction des tâches de copie, le client Windows doit prendre en charge cette fonctionnalité.

Le link:https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^]Contient les informations les plus récentes sur les clients Windows pris en charge.



== Besoins en termes de volume

* Les volumes source doivent être d'au moins 1.25 Go.
* Si vous utilisez des volumes compressés, le type de compression doit être adaptatif et seule la taille de groupe de compression de 8 Ko est prise en charge.
+
Le type de compression secondaire n'est pas pris en charge.


