---
permalink: smb-admin/requirements-microsoft-previous-versions-concept.html 
sidebar: sidebar 
keywords: version, cifs, server, ontap, smb, windows, client, support, snapshot, setting, requirement 
summary: Avant de pouvoir utiliser les versions précédentes avec votre serveur CIFS, vous devez savoir quelles versions de ONTAP et SMB et quels clients Windows le prennent en charge. Vous devez également connaître les exigences relatives aux paramètres de snapshot. 
---
= Conditions requises pour l'utilisation des versions précédentes de Microsoft
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de pouvoir utiliser les versions précédentes avec votre serveur CIFS, vous devez savoir quelles versions de ONTAP et SMB et quels clients Windows le prennent en charge. Vous devez également connaître les exigences relatives aux paramètres de snapshot.



== Configuration requise pour la version ONTAP

Prend en charge les versions précédentes.



== Version requise du protocole SMB

Pour les machines virtuelles de stockage (SVM), ONTAP prend en charge les versions précédentes sur toutes les versions de SMB.



== Configuration requise pour le client Windows

Avant qu'un utilisateur puisse utiliser les versions précédentes pour accéder aux données dans les instantanés, le client Windows doit prendre en charge cette fonctionnalité.

Pour obtenir les dernières informations sur les clients Windows prenant en charge les versions précédentes, consultez la matrice d'interopérabilité.

https://mysupport.netapp.com/matrix["Matrice d'interopérabilité NetApp"^]



== Configuration requise pour les paramètres de snapshot

Pour utiliser les versions précédentes afin d'accéder aux données des instantanés, une stratégie d'instantanés activée doit être associée au volume contenant les données, les clients doivent pouvoir accéder aux données d'instantanés et des instantanés doivent exister.
