---
permalink: smb-admin/reset-rediscovering-servers-task.html 
sidebar: sidebar 
keywords: reset, discover, rediscover, server, cifs, server, discard, store, information, ldap, domain, controller, information, external, respond, reset and rediscover servers 
summary: 'La réinitialisation et la redécouverte des serveurs sur votre serveur CIFS permet au serveur CIFS de supprimer les informations stockées sur les serveurs LDAP et les contrôleurs de domaine. Après l"abandon des informations sur le serveur, le serveur CIFS acquiert de nouveau les informations actuelles sur ces serveurs externes. Cela peut être utile lorsque les serveurs connectés ne répondent pas correctement.' 
---
= Réinitialiser et redécouvrir les serveurs
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La réinitialisation et la redécouverte des serveurs sur votre serveur CIFS permet au serveur CIFS de supprimer les informations stockées sur les serveurs LDAP et les contrôleurs de domaine. Après l'abandon des informations sur le serveur, le serveur CIFS acquiert de nouveau les informations actuelles sur ces serveurs externes. Cela peut être utile lorsque les serveurs connectés ne répondent pas correctement.

.Étapes
. Saisissez la commande suivante : `vserver cifs domain discovered-servers reset-servers -vserver _vserver_name_`
. Afficher les informations sur les nouveaux serveurs découverts : `vserver cifs domain discovered-servers show -vserver _vserver_name_`


L'exemple suivant illustre la réinitialisation et la redécouverte des serveurs pour la machine virtuelle de stockage (SVM, anciennement Vserver) vs1 :

[listing]
----
cluster1::> vserver cifs domain discovered-servers reset-servers -vserver vs1

cluster1::> vserver cifs domain discovered-servers show

Node: node1
Vserver: vs1

Domain Name     Type     Preference DC-Name     DC-Address    Status
--------------- -------- ---------- ----------- ------------- -------
example.com     MS-LDAP  adequate   DC-1        1.1.3.4       OK
example.com     MS-LDAP  adequate   DC-2        1.1.3.5       OK
example.com     MS-DC    adequate   DC-1        1.1.3.4       OK
example.com     MS-DC    adequate   DC-2        1.1.3.5       OK
----
xref:display-discovered-servers-task.adoc[Affichage des informations sur les serveurs découverts]

xref:stop-start-server-task.adoc[Arrêt ou démarrage du serveur CIFS]
