---
permalink: smb-admin/secure-file-access-dynamic-access-control-concept.html 
sidebar: sidebar 
keywords: secure, access, dynamic, control, creating, create, central, policies, policy, active, directory, apply, file, folder, group, policy, object, gpo, staging, stage, change, secure file access by using dynamic access control, dac 
summary: 'Vous pouvez sécuriser l"accès à l"aide du contrôle d"accès dynamique et en créant des stratégies d"accès centrales dans Active Directory et en les appliquant aux fichiers et dossiers sur les SVM via des objets de stratégie de groupe appliqués (GPO, Applied Group Policy Objects). Vous pouvez configurer l"audit de manière à utiliser les événements d"activation de stratégie d"accès central pour voir les effets des modifications apportées aux stratégies d"accès central avant de les appliquer.' 
---
= Sécuriser l'accès aux fichiers à l'aide de la présentation du contrôle d'accès dynamique (DAC)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez sécuriser l'accès à l'aide du contrôle d'accès dynamique et en créant des stratégies d'accès centrales dans Active Directory et en les appliquant aux fichiers et dossiers sur les SVM via des objets de stratégie de groupe appliqués (GPO, Applied Group Policy Objects). Vous pouvez configurer l'audit de manière à utiliser les événements d'activation de stratégie d'accès central pour voir les effets des modifications apportées aux stratégies d'accès central avant de les appliquer.



== Ajouts aux informations d'identification CIFS

Avant le contrôle d'accès dynamique, un identifiant CIFS incluait une identité de sécurité (de l'utilisateur) et une appartenance au groupe Windows. Avec le contrôle d'accès dynamique, trois autres types d'informations sont ajoutés à l'identité du périphérique, aux réclamations du périphérique et aux réclamations de l'utilisateur :

* Identité du périphérique
+
Analogique des informations d'identité de l'utilisateur, à l'exception de l'identité et de l'appartenance au groupe de l'appareil à partir de lequel l'utilisateur se connecte.

* Réclamations de l'appareil
+
Assertions sur un principal de sécurité de périphérique. Par exemple, un sinistre de périphérique peut être qu'il est membre d'une UO spécifique.

* Réclamations de l'utilisateur
+
Assertions sur un principal de sécurité utilisateur. Par exemple, une réclamation d'utilisateur peut être que son compte AD est membre d'une unité d'organisation spécifique.





== Politiques d'accès centralisé

Les stratégies d'accès centrales aux fichiers permettent aux organisations de déployer et de gérer de manière centralisée des stratégies d'autorisation qui incluent des expressions conditionnelles à l'aide de groupes d'utilisateurs, de revendications d'utilisateurs, de revendications de périphériques et de propriétés de ressources.

Par exemple, pour accéder aux données à fort impact sur l'entreprise, un utilisateur doit être un employé à plein temps et n'a accès qu'aux données à partir d'un périphérique géré. Les stratégies d'accès central sont définies dans Active Directory et distribuées aux serveurs de fichiers via le mécanisme GPO.



== Mise en place centralisée des stratégies d'accès avec audit avancé

Les politiques d'accès central peuvent être « mises en service », auquel cas elles sont évaluées de manière « par quoi » lors des contrôles d'accès aux fichiers. Les résultats de ce qui se serait passé si la stratégie était en vigueur et la différence par rapport à ce qui est actuellement configuré sont consignés en tant qu'événement d'audit. De cette façon, les administrateurs peuvent utiliser les journaux d'événements d'audit pour étudier l'impact d'une modification de stratégie d'accès avant de mettre la stratégie en jeu. Après avoir évalué l'impact d'une modification de règle d'accès, la règle peut être déployée via des GPO sur les SVM souhaités.

.Informations associées
xref:supported-gpos-concept.adoc[Stratégies de groupe prises en charge]

xref:applying-group-policy-objects-concept.adoc[Application d'objets de stratégie de groupe aux serveurs SMB]

xref:enable-disable-gpo-support-task.adoc[Activation ou désactivation de la prise en charge de GPO sur un serveur CIFS]

xref:display-gpo-config-task.adoc[Affichage des informations sur les configurations GPO]

xref:display-central-access-policies-task.adoc[Affichage d'informations sur les règles d'accès central]

xref:display-central-access-policy-rules-task.adoc[Affichage d'informations sur les règles de stratégie d'accès central]

xref:configure-central-access-policies-secure-data-task.adoc[Configuration des règles d'accès centrales pour sécuriser les données sur les serveurs CIFS]

xref:display-dynamic-access-control-security-task.adoc[Affichage d'informations sur la sécurité du contrôle d'accès dynamique]

link:../nas-audit/index.html["Audit et suivi de sécurité SMB et NFS"]
