---
permalink: smb-admin/server-security-settings-svm-disaster-recovery-concept.html 
sidebar: sidebar 
keywords: create, creating, svm, configure, disaster, recovery, destination, identity, preserve, snapmirror, configuration, smb, guideline, guidelines for smb server security settings in an svm disaster recovery configuration 
summary: 'Avant de créer un SVM configuré en tant que destination de reprise d"activité où l"identité n"est pas préservée (l"option -Identity-preserve est définie sur false dans la configuration SnapMirror), vous devez savoir comment les paramètres de sécurité du serveur SMB sont gérés sur la SVM de destination.' 
---
= En savoir plus sur les paramètres de sécurité du serveur SMB pour la configuration de la reprise d'activité du SVM ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de créer un SVM configuré en tant que destination de reprise d'activité pour laquelle l'identité n'est pas conservée (le `-identity-preserve` l'option est définie sur `false` En configuration SnapMirror), il est important de savoir comment les paramètres de sécurité des serveurs SMB sont gérés sur la SVM de destination.

* Les paramètres de sécurité du serveur SMB non par défaut ne sont pas répliqués sur la destination.
+
Lorsque vous créez un serveur SMB sur le SVM de destination, tous les paramètres de sécurité du serveur SMB sont définis sur les valeurs par défaut. Lors de l'initialisation, de la destination de reprise après incident du SVM, de la mise à jour ou de la resynchronisation, les paramètres de sécurité du serveur SMB sur la source ne sont pas répliqués sur la destination.

* Vous devez configurer manuellement les paramètres de sécurité du serveur SMB non par défaut.
+
Si vous avez configuré sur la SVM source des paramètres de sécurité du serveur SMB non par défaut, vous devez configurer manuellement ces mêmes paramètres sur le SVM de destination après que la destination devienne read-write (après une interruption de la relation SnapMirror).


