---
permalink: smb-admin/share-properties-concept.html 
sidebar: sidebar 
keywords: customize, properties, property, smb, share, how to use smb share properties 
summary: Vous pouvez personnaliser les propriétés des partages SMB. 
---
= Découvrez comment utiliser les propriétés de partage SMB de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez personnaliser les propriétés des partages SMB.

Les propriétés de partage disponibles sont les suivantes :

|===
| Propriétés du partage | Description 


 a| 
`oplocks`
 a| 
Cette propriété indique que le partage utilise des verrous opportunistes, également appelés mise en cache côté client.



 a| 
`browsable`
 a| 
Cette propriété permet aux clients Windows de parcourir le partage.



 a| 
`showsnapshot`
 a| 
Cette propriété indique que les instantanés peuvent être affichés et parcourus par les clients.



 a| 
`changenotify`
 a| 
Cette propriété indique que le partage prend en charge les demandes de notification des modifications. Pour les partages sur un SVM, il s'agit d'une propriété initiale par défaut.



 a| 
`attributecache`
 a| 
Cette propriété permet la mise en cache des attributs de fichier sur le partage SMB afin d'accélérer l'accès aux attributs. La valeur par défaut est de désactiver la mise en cache des attributs. Cette propriété ne doit être activée que si des clients se connectent à des partages sur SMB 1.0. Cette propriété de partage n'est pas applicable si les clients se connectent à des partages via SMB 2.x ou SMB 3.0.



 a| 
`continuously-available`
 a| 
Cette propriété permet aux clients SMB qui la prennent en charge d'ouvrir des fichiers de façon persistante. Les fichiers ouverts de cette façon sont protégés contre les événements perturbateurs, tels que le basculement et le rétablissement.



 a| 
`branchcache`
 a| 
Cette propriété spécifie que le partage permet aux clients de demander des hachages de BranchCache sur les fichiers de ce partage. Cette option n'est utile que si vous spécifiez « par partage » en mode de fonctionnement dans la configuration de BranchCache CIFS.



 a| 
`access-based-enumeration`
 a| 
Cette propriété spécifie que _accès basé sur Enumeration_ (ABE) est activé sur ce partage. Les dossiers partagés filtrés PAR ABE sont visibles par un utilisateur en fonction des droits d'accès de cet utilisateur, empêchant l'affichage des dossiers ou d'autres ressources partagées que l'utilisateur ne dispose pas des droits d'accès.



 a| 
`namespace-caching`
 a| 
Cette propriété spécifie que les clients SMB qui se connectent à ce partage peuvent mettre en cache les résultats d'énumération de répertoire renvoyés par les serveurs CIFS, ce qui peut fournir de meilleures performances. Par défaut, les clients SMB 1 ne mettent pas en cache les résultats d'énumération des répertoires. Étant donné que les clients SMB 2 et SMB 3 mettent en cache les résultats d'énumération de répertoires par défaut, la spécification de cette propriété de partage n'offre des avantages en termes de performances que pour les connexions clients SMB 1.



 a| 
`encrypt-data`
 a| 
Cette propriété spécifie que le chiffrement SMB doit être utilisé lors de l'accès à ce partage. Les clients SMB qui ne prennent pas en charge le chiffrement lors de l'accès aux données SMB ne pourront pas accéder à ce partage.

|===