---
permalink: smb-admin/share-naming-requirements-concept.html 
sidebar: sidebar 
keywords: ontap, share, naming, name, requirement, mind, creating, create, smb, server, smb share naming requirements 
summary: Lors de la création de partages SMB sur votre serveur SMB, veillez à respecter les exigences de dénomination des partages ONTAP. 
---
= Exigences de nommage des partages SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lors de la création de partages SMB sur votre serveur SMB, veillez à respecter les exigences de dénomination des partages ONTAP.

Les conventions de nom des partages pour ONTAP sont identiques à celles de Windows et doivent être respectées dans ce cas :

* Le nom de chaque partage doit être unique pour le serveur SMB.
* Les noms de partage ne sont pas sensibles à la casse.
* La longueur maximale du nom de partage est de 80 caractères.
* Les noms de partage Unicode sont pris en charge.
* Les noms de partage se terminant par le caractère $ sont des partages masqués.
* Les partages administratifs ADMIN$, IPC$ et c$ sont automatiquement créés sur chaque serveur CIFS et sont réservés.
* Lors de la création d'un partage, vous ne pouvez pas utiliser le nom de partage ONTAP_ADMIN$.
* Les noms de partage contenant des espaces sont pris en charge :
+
** Vous ne pouvez pas utiliser un espace comme premier caractère ou comme dernier caractère dans un nom de partage.
** Vous devez inclure des noms de partage contenant un espace entre guillemets.
+
[NOTE]
====
Les guillemets simples sont considérés comme faisant partie du nom du partage et ne peuvent pas être utilisés à la place des guillemets.

====


* Les caractères spéciaux suivants sont pris en charge lorsque vous nommez des partages SMB :
+
! @ # $ % et ' _ - . ~ ( ) { }

* Les caractères spéciaux suivants ne sont pas pris en charge lorsque vous nommez des partages SMB :
+
** " / \ : ; | < > , ? * =



