---
permalink: smb-admin/snapmirror-svms-local-groups-concept.html 
sidebar: sidebar 
keywords: aware, guideline, configure, snapmirror, volume, svm, contain, local, group, guidelines for using snapmirror on svms that contain local groups 
summary: Notez les instructions lorsque vous configurez SnapMirror sur des volumes appartenant aux SVM contenant des groupes locaux. 
---
= Consignes relatives à l'utilisation de SnapMirror sur des SVM contenant des groupes locaux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Notez les instructions lorsque vous configurez SnapMirror sur des volumes appartenant aux SVM contenant des groupes locaux.

Vous ne pouvez pas utiliser des groupes locaux dans des ACE appliqués à des fichiers, des répertoires ou des partages qui sont répliqués par SnapMirror vers une autre SVM. Si vous utilisez la fonctionnalité SnapMirror pour créer un miroir de reprise sur incident sur un volume situé sur un autre SVM et que le volume dispose d'une version ACE pour un groupe local, l'ACE n'est pas valide pour le miroir. Si les données sont répliquées sur un autre SVM, celles-ci se croisent efficacement et un autre domaine local. Les autorisations accordées aux utilisateurs et groupes locaux ne sont valides qu'au sein du périmètre de la SVM sur lequel ils ont été créés.
