---
permalink: smb-admin/support-automatic-node-referrals-concept.html 
sidebar: sidebar 
keywords: enable, smb, automatic, node, referral, aware, ontap, functionality, support, support for smb automatic node referrals 
summary: 'Avant d"activer les référencements automatiques des nœuds SMB, sachez que certaines fonctionnalités ONTAP ne prennent pas en charge les référencements.' 
---
= Prise en charge des références automatiques de nœuds ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant d'activer les référencements automatiques des nœuds SMB, sachez que certaines fonctionnalités ONTAP ne prennent pas en charge les référencements.

* Les types de volumes suivants ne prennent pas en charge les référencements automatiques des nœuds SMB :
+
** Membres en lecture seule d'un miroir de partage de charge
** Volume de destination d'un miroir de protection des données


* Les référencements des nœuds ne bougent pas parallèlement à un déplacement LIF.
+
Lorsqu'un client utilise une connexion référencée sur une connexion SMB 2.x ou SMB 3.0 et qu'une LIF de données se déplace sans interruption, le client continue d'utiliser la même connexion référencée, même si la LIF n'est plus locale des données.

* Les référencements de nœuds ne se déplacent pas parallèlement à un déplacement des volumes.
+
Lorsqu'un client utilise une connexion référencée sur une connexion SMB et qu'un déplacement de volume se produit, le client continue à utiliser la même connexion référencée, même si le volume n'est plus situé sur le même nœud que la LIF de données.


