---
permalink: smb-admin/supported-versions-functionality-concept.html 
sidebar: sidebar 
keywords: server, message, block, smb, remote, file-sharing, protocol, microsoft, windows, client, server, ontap, functionality, environment, supported smb versions and functionality 
summary: 'Server message Block (SMB) est un protocole de partage de fichiers distant utilisé par les clients et les serveurs Microsoft Windows. Dans ONTAP 9, toutes les versions SMB sont prises en charge, mais la prise en charge par défaut de SMB 1.0 dépend de votre version ONTAP. Vérifiez que le serveur ONTAP SMB prend en charge les clients et les fonctionnalités requis dans votre environnement.' 
---
= Fonctionnalités et versions SMB prises en charge
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Server message Block (SMB) est un protocole de partage de fichiers distant utilisé par les clients et les serveurs Microsoft Windows. Dans ONTAP 9, toutes les versions SMB sont prises en charge, mais la prise en charge par défaut de SMB 1.0 dépend de votre version ONTAP. Vérifiez que le serveur ONTAP SMB prend en charge les clients et les fonctionnalités requis dans votre environnement.

Les dernières informations sur les clients SMB et les contrôleurs de domaine pris en charge par ONTAP sont disponibles dans l'outil _Interoperability Matrix Tool_.

SMB 2.0 et les versions ultérieures sont activées par défaut pour les serveurs SMB ONTAP 9 et peuvent être activées ou désactivées selon les besoins. Le tableau suivant présente le support SMB 1.0 et la configuration par défaut.

|===
| Fonctionnalité SMB 1.0 : 4+| Dans ces versions ONTAP 9 : 


 a| 
 a| 
9.0
 a| 
9.1
 a| 
9.2
 a| 
9.3 et versions ultérieures



 a| 
Est activé par défaut
 a| 
Oui.
 a| 
Oui.
 a| 
Oui.
 a| 
Non



 a| 
Peut être activé ou désactivé
 a| 
Non
 a| 
Oui*9.1 P8 ou ultérieur requis.
 a| 
Oui.
 a| 
Oui.

|===
[NOTE]
====
Les paramètres par défaut des connexions SMB 1.0 et 2.0 aux contrôleurs de domaine dépendent également de la version de ONTAP. Pour plus d'informations, consultez le `vserver cifs security modify` page de manuel. Pour les environnements avec des serveurs CIFS existants exécutant SMB 1.0, vous devez migrer vers une version SMB ultérieure dès que possible pour préparer des améliorations en matière de sécurité et de conformité. Contactez votre représentant NetApp pour plus d'informations.

====
Le tableau suivant indique les fonctionnalités SMB prises en charge dans chaque version de SMB. Certaines fonctionnalités SMB sont activées par défaut et d'autres requièrent une configuration supplémentaire.

|===
| *Cette fonctionnalité:* | *Nécessite une activation:* 5+| *Est pris en charge dans ONTAP 9 pour ces versions SMB:* 


 a| 
 a| 
 a| 
1.0
 a| 
2.0
 a| 
2.1
 a| 
3.0
 a| 
3.1.1



 a| 
Fonctionnalité SMB 1.0 héritée
 a| 
 a| 
X
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
Poignées durables
 a| 
 a| 
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
Opérations cumulées
 a| 
 a| 
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
Opérations asynchrones
 a| 
 a| 
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
Tailles de tampon de lecture et d'écriture améliorées
 a| 
 a| 
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
Évolutivité optimisée
 a| 
 a| 
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
Signature SMB
 a| 
X
 a| 
X
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
Autre format de fichier ADS (Data Stream)
 a| 
X
 a| 
X
 a| 
X
 a| 
X
 a| 
X
 a| 
X



 a| 
MTU important (activé par défaut à partir de ONTAP 9.7)
 a| 
X
 a| 
 a| 
 a| 
X
 a| 
X
 a| 
X



 a| 
Oplocks de location
 a| 
 a| 
 a| 
 a| 
X
 a| 
X
 a| 
X



 a| 
Partages disponibles en permanence
 a| 
X
 a| 
 a| 
 a| 
 a| 
X
 a| 
X



 a| 
Pointeurs permanents
 a| 
 a| 
 a| 
 a| 
 a| 
X
 a| 
X



 a| 
Témoin
 a| 
 a| 
 a| 
 a| 
 a| 
X
 a| 
X



 a| 
CHIFFREMENT SMB : AES-128-CCM
 a| 
X
 a| 
 a| 
 a| 
 a| 
X
 a| 
X



 a| 
Évolutivité horizontale (requise par les partages de CA)
 a| 
 a| 
 a| 
 a| 
 a| 
X
 a| 
X



 a| 
Basculement transparent
 a| 
 a| 
 a| 
 a| 
 a| 
X
 a| 
X



 a| 
Multicanal SMB (à partir de ONTAP 9.4)
 a| 
X
 a| 
 a| 
 a| 
 a| 
X
 a| 
X



 a| 
Intégrité de la pré-authentification
 a| 
 a| 
 a| 
 a| 
 a| 
 a| 
X



 a| 
Basculement client cluster v.2 (CCFv2)
 a| 
 a| 
 a| 
 a| 
 a| 
 a| 
X



 a| 
Chiffrement SMB : AES-128-GCM (à partir de ONTAP 9.1)
 a| 
X
 a| 
 a| 
 a| 
 a| 
 a| 
X

|===
.Informations associées
xref:signing-enhance-network-security-concept.adoc[Utilisation de la signature SMB pour améliorer la sécurité du réseau]

xref:set-server-minimum-authentication-security-level-task.adoc[Définition du niveau de sécurité d'authentification minimum du serveur SMB]

xref:configure-required-encryption-concept.adoc[Configuration du chiffrement SMB requis sur les serveurs SMB pour les transferts de données sur SMB]

http://www.netapp.com/us/media/tr-4543.pdf["Rapport technique de NetApp 4543 : meilleures pratiques relatives au protocole SMB"]

https://mysupport.netapp.com/NOW/products/interoperability["Interopérabilité NetApp"^]
