---
permalink: smb-admin/unix-file-permissions-provide-access-control-concept.html 
sidebar: sidebar 
keywords: flexvol, volume, security, style, ntfs, unix, mixed, access, data, smb, regardless, access, effective, how unix file permissions provide access control when accessing files over smb 
summary: 'Un volume FlexVol peut avoir l"un des trois types de style de sécurité suivants : NTFS, UNIX ou mixte. Vous pouvez accéder aux données via SMB quel que soit le style de sécurité. Cependant, des autorisations appropriées sur les fichiers UNIX sont nécessaires pour accéder aux données à l"aide de la sécurité effective d"UNIX.' 
---
= Comment les autorisations d'accès aux fichiers UNIX permettent de contrôler l'accès aux fichiers sur SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un volume FlexVol peut avoir l'un des trois types de style de sécurité suivants : NTFS, UNIX ou mixte. Vous pouvez accéder aux données via SMB quel que soit le style de sécurité. Cependant, des autorisations appropriées sur les fichiers UNIX sont nécessaires pour accéder aux données à l'aide de la sécurité effective d'UNIX.

Lorsque vous accédez aux données via SMB, plusieurs contrôles d'accès sont utilisés pour déterminer si un utilisateur est autorisé à effectuer une action demandée :

* Droits d'exportation
+
La configuration des autorisations d'exportation pour l'accès SMB est facultative.

* Partager les autorisations
* Autorisations liées aux fichiers
+
Les types d'autorisations de fichier suivants peuvent être appliqués aux données sur lesquelles l'utilisateur souhaite effectuer une action :

+
** NTFS
** ACL UNIX NFSv4
** Bits mode UNIX




Pour les données avec des ACL NFSv4 ou des bits de mode UNIX définis, les autorisations de style UNIX sont utilisées afin de déterminer les droits d'accès aux fichiers aux données. L'administrateur du SVM doit définir l'autorisation appropriée pour garantir que les utilisateurs disposent des droits nécessaires pour effectuer l'action souhaitée.

[NOTE]
====
Les données d'un volume de type sécurité mixte peuvent avoir un style de sécurité NTFS ou UNIX. Si les données ont un style de sécurité UNIX effectif, les autorisations NFSv4 ou les bits du mode UNIX sont utilisés pour déterminer les droits d'accès aux fichiers aux données.

====