---
permalink: smb-admin/use-cases-odx-concept.html 
sidebar: sidebar 
keywords: use, case, odx, svm, determine, circumstance, odx, performance, benefit, use cases for odx 
summary: 'Vous devez tenir compte des cas d"utilisation d"ODX sur des SVM afin de pouvoir déterminer dans quelles circonstances ODX vous fournit des avantages en matière de performances.' 
---
= Cas d'utilisation d'ODX sur les serveurs ONTAP SMB
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez tenir compte des cas d'utilisation d'ODX sur des SVM afin de pouvoir déterminer dans quelles circonstances ODX vous fournit des avantages en matière de performances.

Par défaut, les serveurs et clients Windows qui prennent en charge ODX utilisent la fonction d'allègement de la charge des copies pour copier des données sur des serveurs distants. Si le serveur ou le client Windows ne prend pas en charge ODX, ou si l'allègement de la charge des copies ODX échoue à tout moment, l'opération de copie ou de déplacement retourne aux lectures et écritures classiques pour la copie ou le déplacement.

Les cas d'utilisation suivants prennent en charge l'utilisation de copies et de déplacements d'ODX :

* Intra-volume
+
Les fichiers ou LUN source et de destination se trouvent dans le même volume.

* Inter-volume, même nœud, même SVM
+
Les fichiers ou LUN source et de destination se trouvent sur des volumes différents situés sur le même nœud. Les données sont détenues par le même SVM.

* Inter-volumes, nœuds différents, même SVM
+
Les fichiers ou LUN source et de destination se trouvent sur des volumes différents situés sur des nœuds différents. Les données sont détenues par le même SVM.

* Inter-SVM, même nœud
+
Les fichiers source et de destination ou les LUN se trouvent sur des volumes différents situés sur le même nœud. Les données sont détenues par différents SVM.

* Inter-SVM, nœuds différents
+
Les fichiers ou LUN source et de destination se trouvent sur des volumes différents situés sur des nœuds différents. Les données sont détenues par différents SVM.

* Inter-cluster
+
Les LUN source et de destination se trouvent sur des volumes différents, sur différents nœuds, sur l'ensemble des clusters. Ceci n'est pris en charge que pour SAN et ne fonctionne pas pour CIFS.



Il existe d'autres cas d'utilisation spéciaux :

* Dans l'implémentation de ONTAP ODX, vous pouvez utiliser ODX pour copier des fichiers entre des partages SMB et des disques virtuels connectés FC ou iSCSI.
+
Vous pouvez utiliser Windows Explorer, l'interface de ligne de commande Windows ou PowerShell, Hyper-V ou d'autres applications prenant en charge ODX pour copier ou déplacer des fichiers de manière transparente à l'aide de l'allègement de la charge des copies ODX entre les partages SMB et les LUN connectés, à condition que les partages SMB et les LUN soient sur le même cluster.

* Hyper-V fournit des cas d'utilisation supplémentaires pour la décharge de copies ODX :
+
** Vous pouvez utiliser le pass-through ODX qui décharge les copies et Hyper-V pour copier des données dans ou sur des fichiers de disque dur virtuel (VHD), ou pour copier des données entre les partages SMB mappés et les LUN iSCSI connectés au sein du même cluster.
+
Ainsi, des copies des systèmes d'exploitation invités peuvent être transmis au stockage sous-jacent.

** Lors de la création de VHD de taille fixe, ODX permet d'initialiser le disque avec des zéros, à l'aide d'un jeton bien connu mis à zéro.
** L'allègement de la charge des copies d'ODX est utilisé pour la migration du stockage de machines virtuelles si le stockage source et cible est situé sur le même cluster.


+
[NOTE]
====
Pour tirer parti des cas d'utilisation liés au délestage des copies ODX par Hyper-V, le système d'exploitation invité doit prendre en charge ODX. Les disques du système d'exploitation invité doivent être des disques SCSI pris en charge par le stockage (SMB ou SAN) prenant en charge ODX. Les disques IDE du système d'exploitation invité ne prennent pas en charge le pass-through ODX.

====

