---
permalink: smb-admin/using-odx-concept.html 
sidebar: sidebar 
keywords: odx, copy, offload, aware, guideline, volume, intra-cluster, inter-cluster, consideration, guidelines for using odx 
summary: 'Avant de pouvoir utiliser ODX pour l"allègement de la charge des copies, vous devez prendre connaissance des instructions. Par exemple, vous devez connaître les types de volumes que vous pouvez utiliser ODX, et connaître les considérations d"ODX au sein du cluster et entre clusters.' 
---
= Instructions d'utilisation d'ODX
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de pouvoir utiliser ODX pour l'allègement de la charge des copies, vous devez prendre connaissance des instructions. Par exemple, vous devez connaître les types de volumes que vous pouvez utiliser ODX, et connaître les considérations d'ODX au sein du cluster et entre clusters.



== Règles relatives aux volumes

* ODX ne peut pas être utilisé pour l'allègement de la charge des copies avec les configurations de volume suivantes :
+
** La taille du volume source est inférieure à 1.25 Go
+
La taille du volume doit être supérieure ou égale à 1.25 Go pour utiliser ODX.

** Volumes en lecture seule
+
ODX n'est pas utilisé pour les fichiers et les dossiers résidant dans des miroirs de partage de charge ou dans des volumes de destination SnapMirror ou SnapVault.

** Si le volume source n'est pas dédupliqué


* Les copies ODX sont prises en charge uniquement pour les copies intra-cluster.
+
Vous ne pouvez pas utiliser ODX pour copier des fichiers ou des dossiers vers un volume d'un autre cluster.





== Autres lignes directrices

* Dans les environnements SMB, pour utiliser ODX pour l'allègement de la charge des copies, les fichiers doivent être d'une taille supérieure ou égale à 256 Ko.
+
Les fichiers plus petits sont transférés à l'aide d'une opération de copie traditionnelle.

* La fonctionnalité de déchargement des copies d'ODX utilise la déduplication dans le cadre du processus de copie.
+
Si vous ne souhaitez pas que la déduplication s'exécute sur les volumes SVM lors de la copie ou du déplacement de données, vous devez désactiver la décharge des copies ODX sur ce SVM.

* L'application qui effectue le transfert de données doit être écrite pour prendre en charge ODX.
+
Les opérations applicatives prenant en charge ODX sont les suivantes :

+
** Les opérations de gestion Hyper-V, telles que la création et la conversion de disques durs virtuels (VHD), la gestion des copies Snapshot et la copie de fichiers entre les machines virtuelles
** Opérations de l'Explorateur Windows
** Commandes de copie Windows PowerShell
** Commandes de copie de l'invite de commande Windows
+
Robocopy à l'invite de commandes Windows prend en charge ODX.

+
[NOTE]
====
Les applications doivent être exécutées sur des serveurs Windows ou des clients prenant en charge ODX.

====
+
Pour plus d'informations sur les applications ODX prises en charge sur les serveurs et clients Windows, consultez la bibliothèque Microsoft TechNet.





.Informations associées
http://["Bibliothèque Microsoft TechNet : technet.microsoft.com/en-us/library/"]
