---
permalink: svm-migrate/cancel-task.html 
sidebar: sidebar 
keywords: svm, migrate, cancel, abort 
summary: 'Si vous devez annuler une migration SVM avant qu"elle ne soit terminée, vous pouvez annuler une migration SVM uniquement lorsque l"opération est à l"état suspendu ou échoué.' 
---
= Annuler une migration SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous devez annuler une migration SVM avant qu'elle ne soit terminée, vous pouvez utiliser le `vserver migrate abort` commande. Vous pouvez annuler une migration SVM uniquement lorsque l’opération est en pause ou en échec. Vous ne pouvez pas annuler une migration SVM lorsque le statut est « basculement démarré » ou une fois le basculement terminé. Vous ne pouvez pas utiliser le `abort` option lorsqu'une migration SVM est en cours.

.Étapes
. Vérifier l'état de la migration :
+
`dest_cluster> vserver migrate show -vserver <vserver name>`

. Annuler la migration :
+
`dest_cluster> vserver migrate abort -vserver <vserver name>`

. Vérifier la progression de l'opération d'annulation :
+
`dest_cluster> vserver migrate show`

+
L'état de la migration indique l'abandon de la migration lorsque l'opération d'annulation est en cours. Lorsque l'opération d'annulation est terminée, l'état de la migration n'indique rien.


