---
permalink: svm-migrate/migrate-svm-task.html 
sidebar: sidebar 
keywords: svm, migrate, defaults, cutover, cleanup 
summary: Une fois la migration SVM terminée, les clients sont automatiquement mis en service sur le cluster de destination et le SVM inutile est retiré du cluster source. La mise en service automatique et le nettoyage automatique des sources sont activés par défaut. Si nécessaire, vous pouvez désactiver la mise en service automatique des clients pour suspendre la migration avant la mise en service et désactiver le nettoyage automatique des SVM source. 
---
= Migrer un SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois la migration SVM terminée, les clients sont automatiquement mis en service sur le cluster de destination et le SVM inutile est retiré du cluster source. La mise en service automatique et le nettoyage automatique des sources sont activés par défaut. Si nécessaire, vous pouvez désactiver la mise en service automatique des clients pour suspendre la migration avant la mise en service et désactiver le nettoyage automatique des SVM source.

* Vous pouvez utiliser le `-auto-cutover false` option permettant de suspendre la migration lors de la mise en service client automatique, puis d'effectuer la mise en service manuellement ultérieurement.
+
xref:manual-client-cutover-task.adoc[Mise en service manuelle des clients après la migration de SVM]

* Vous pouvez utiliser le privilège d'avance `-auto-source-cleanup false` Option permettant de désactiver la suppression du SVM source après la mise en service, puis de déclencher le nettoyage source manuellement ultérieurement, après la mise en service.
+
xref:manual-source-removal-task.adoc[Supprimer manuellement le SVM source après la mise en service]





== Migrer un SVM avec la mise en service automatique activée

Par défaut, les clients sont automatiquement mis en service sur le cluster de destination une fois la migration terminée et le SVM inutile est retiré du cluster source.

.Étapes
. Depuis le cluster destination, exécutez les contrôles préalables de migration :
+
`dest_cluster> vserver migrate start -vserver _SVM_name_ -source-cluster _cluster_name_ -check-only true`

. Depuis le cluster destination, démarrer la migration SVM :
+
`dest_cluster> vserver migrate start -vserver _SVM_name_ -source-cluster _cluster_name_`

. Vérifier l'état de la migration :
+
`dest_cluster> vserver migrate show`

+
L'état affiche « migrate-Complete » lorsque la migration de SVM est terminée.





== Migrer un SVM avec la mise en service client automatique désactivée

Vous pouvez utiliser l'option –auto-mise en service false pour suspendre la migration lors de la mise en service automatique du client, puis effectuer la mise en service manuellement ultérieurement. Voir xref:manual-client-cutover-task.adoc[Mise en service manuelle des clients après la migration de SVM].

.Étapes
. Depuis le cluster destination, exécutez les contrôles préalables de migration :
+
`dest_cluster> vserver migrate start -vserver _SVM_name_ -source-cluster _cluster_name_ -check-only true`

. Depuis le cluster destination, démarrer la migration SVM :
+
`dest_cluster> vserver migrate start -vserver _SVM_name_ -source-cluster _cluster_name_ -auto-cutover false`

. Vérifier l'état de la migration :
+
`dest_cluster> vserver migrate show`
L'état affiche « prêt à la mise en service » lorsque la migration des SVM termine les transferts de données asynchrones et est prête pour la mise en service.





== Migrer un SVM avec le nettoyage source désactivé

Vous pouvez utiliser l'option faux privilèges -auto-source-cleanup pour désactiver la suppression du SVM source après la mise en service, puis déclencher le nettoyage source manuellement après la mise en service. Voir xref:manual-source-removal-task.adoc[Supprimer manuellement la SVM source].

.Étapes
. Depuis le cluster destination, exécutez les contrôles préalables de migration :
+
`dest_cluster*> vserver migrate start -vserver _SVM_name_ -source-cluster _cluster_name_ -check-only true`

. Depuis le cluster destination, démarrer la migration SVM :
+
`dest_cluster*> vserver migrate start -vserver _SVM_name_ -source-cluster _cluster_name_ -auto-source-cleanup false`

. Vérifier l'état de la migration :
+
`dest_cluster*> vserver migrate show`

+
L'état affiche Ready-for-source-cleanup lorsque la mise en service de la migration des SVM est terminée, et est prêt à supprimer le SVM sur le cluster source.


