---
permalink: svm-migrate/pause-task.html 
sidebar: sidebar 
keywords: svm, migrate, pause, resume, restart 
summary: 'Vous pouvez interrompre une migration SVM avant le démarrage de la mise en service. Vous pouvez interrompre une migration SVM à l"aide de `vserver migrate pause` commande.' 
---
= Mettre en pause et reprendre la migration du SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez interrompre une migration SVM avant le démarrage de la mise en service. Vous pouvez interrompre une migration SVM à l'aide de `vserver migrate pause` commande.



== Interrompre la migration

Vous pouvez interrompre une migration SVM avant le démarrage de la mise en service client à l'aide de `vserver migrate pause` commande.

Certaines modifications de configuration sont restreintes lorsqu'une opération de migration est en cours ; cependant, à partir de ONTAP 9.12.1, vous pouvez interrompre une migration pour corriger certaines configurations restreintes et pour certains États défaillants afin de résoudre les problèmes de configuration susceptibles d'avoir causé la défaillance. Voici quelques-uns des États défaillants que vous pouvez corriger lorsque vous interrompez la migration des SVM :

* `setup-configuration-failed`
* `migrate-failed`


.Étapes
. Depuis le cluster destination, suspendre la migration :
+
[source, cli]
----
vserver migrate pause -vserver <vserver name>
----




== Reprendre les migrations

Lorsque vous êtes prêt à reprendre une migration SVM en pause ou en cas d'échec d'une migration SVM, vous pouvez utiliser `vserver migrate resume` la commande.

.Étapes
. Effectuez les opérations suivantes sur le cluster de destination :
+
.. Reprise de la migration SVM :
+
[source, cli]
----
vserver migrate resume
----
.. Vérifier que la migration SVM a repris et contrôler la progression :
+
[source, cli]
----
vserver migrate show
----



