---
permalink: mediator/host-maintenance-task.html 
sidebar: sidebar 
keywords: mediator, maintain, host, maintenance, package update, kernel upgrade, change hostname, change IP, self-signed certificate, self signed certificate 
summary: Maintenez régulièrement le système d’exploitation hôte pour ONTAP Mediator pour des performances optimales. 
---
= Maintenir le système d'exploitation hôte pour le médiateur ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Maintenez régulièrement le système d’exploitation hôte pour ONTAP Mediator pour des performances optimales.



== Redémarrez l'hôte

Redémarrez l’hôte uniquement lorsque les clusters sont sains.  Les clusters ne peuvent pas répondre aux échecs lorsque ONTAP Mediator est hors ligne.  Planifiez une fenêtre de service avant le redémarrage.

ONTAP Mediator reprend automatiquement lors d'un redémarrage et réintègre les relations précédemment configurées avec les clusters ONTAP .



== Mises à jour du package hôte

Mettre à jour n'importe quelle bibliothèque ou package yum à l'exception du noyau.  Redémarrez l'hôte si nécessaire pour que les modifications prennent effet.  Planifiez une fenêtre de service avant de redémarrer l'hôte.

Si vous installez le `yum-utils` utiliser le `needs-restarting` commande permettant de détecter si des modifications de pack nécessitent un redémarrage.

Redémarrez après la mise à jour des dépendances du médiateur ONTAP , car les modifications ne prennent pas effet immédiatement.



== Mises à niveau mineures du noyau du système d'exploitation hôte

SCST doit être compilé pour le noyau utilisé.  Pour mettre à jour le système d'exploitation, une fenêtre de maintenance est requise.

.Étapes
Procédez comme suit pour mettre à niveau le noyau du système d'exploitation hôte.


NOTE: Avant de mettre à niveau le noyau, vérifiez que le système d'exploitation et la version d' ONTAP Mediator sont compatibles.  Pour les versions prises en charge, voir lelink:whats-new-concept.html#os-support-matrix["Matrice de prise en charge du se"] .

. Arrêtez le médiateur ONTAP.
. Désinstaller le package SCST, voir<<Effectuer la maintenance de l'hôte>> .  (SCST ne fournit pas de mécanisme de mise à niveau.)
. Mettez à niveau le système d'exploitation, puis redémarrez.
. Réinstallez le progiciel SCST.
. Réactiver ONTAP Mediator.




== Effectuer la maintenance de l'hôte

La mise à niveau du noyau de la machine virtuelle peut entraîner des problèmes de compatibilité avec les modules SCST.  Désinstaller et réinstaller manuellement SCST.



=== Étape 1 : Désinstaller SCST

Pour désinstaller SCST, utilisez le bundle tar correspondant à votre version d' ONTAP Mediator.

.Étapes
. Téléchargez le bundle SCST approprié (comme indiqué dans le tableau suivant) et extrayez-le.
+
[cols="50,50"]
|===


| Pour cette version ... | Utiliser ce paquet tar... 


 a| 
Médiateur ONTAP 1.10
 a| 
scst-3.9.tar.gz



 a| 
Médiateur ONTAP 1.9.1
 a| 
scst-3.8.0.tar.bz2



 a| 
Médiateur ONTAP 1.9
 a| 
scst-3.8.0.tar.bz2



 a| 
Médiateur ONTAP 1.8
 a| 
scst-3.8.0.tar.bz2



 a| 
Médiateur ONTAP 1.7
 a| 
scst-3.7.0.tar.bz2



 a| 
Médiateur ONTAP 1.6
 a| 
scst-3.7.0.tar.bz2



 a| 
Médiateur ONTAP 1.5
 a| 
scst-3.6.0.tar.bz2



 a| 
Médiateur ONTAP 1.4
 a| 
scst-3.6.0.tar.bz2



 a| 
Médiateur ONTAP 1.3
 a| 
scst-3.5.0.tar.bz2



 a| 
Médiateur ONTAP 1.1
 a| 
scst-3.4.0.tar.bz2



 a| 
Médiateur ONTAP 1.0
 a| 
scst-3.3.0.tar.bz2

|===
+
.. Accédez au package open source à partir dulink:https://scst.sourceforge.net/downloads.html["Téléchargements de SCST SourceForge"^] .
.. Sélectionnez *Télécharger les versions publiées*.
.. Extrayez le bundle sur votre VM.


. Exécutez les commandes de désinstallation suivantes dans le `scst` annuaire:
+
.. `systemctl stop mediator-scst`
.. `make scstadm_uninstall`
.. `make iscsi_uninstall`
.. `make usr_uninstall`
.. `make scst_uninstall`
.. `depmod`






=== Étape 2 : installer SCST

Pour installer manuellement SCST, vous avez besoin du bundle tar SCST utilisé pour la version installée d' ONTAP Mediator (voir le<<scst-bundle-table,Tableau SCST>> ).


NOTE: Effectuez cette étape avant d’installer ONTAP Mediator.  Si la version SCST que vous utilisez est plus récente que la version fournie avec le programme d'installation ONTAP Mediator, le programme d'installation ignore cette étape.

. Exécutez les commandes d'installation suivantes dans le `scst` annuaire:
+
.. `make 2release`
.. `make scst_install`
.. `make usr_install`
.. `make iscsi_install`
.. `make scstadm_install`
.. `depmod`
+
[NOTE]
====
Si vous effectuez une première installation et souhaitez préinstaller ONTAP Mediator, exécutez la commande suivante avant de passer à l'étape suivante :

`mkdir -p /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys`

====
.. `cp scst/src/certs/scst_module_key.der /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/`
.. `patch /etc/init.d/scst < /opt/netapp/lib/ontap_mediator/systemd/scst.patch`
+

NOTE: Si vous préinstallez SCST avant ONTAP Mediator lors d'une première installation, ignorez cette étape.  Le programme d'installation applique les correctifs SCST pertinents.



. Si vous le souhaitez, si le démarrage sécurisé est activé, effectuez les opérations suivantes avant de redémarrer :
+
.. Déterminez chaque nom de fichier pour le `scst_vdisk` , `scst` , et `iscsi_scst` modules:
+
....
[root@localhost ~]# modinfo -n scst_vdisk
[root@localhost ~]# modinfo -n scst
[root@localhost ~]# modinfo -n iscsi_scst
....
.. Déterminez la version du noyau :
+
....
[root@localhost ~]# uname -r
....
.. Signez chaque fichier de module avec le noyau :
+
....
[root@localhost ~]# /usr/src/kernels/<KERNEL-RELEASE>/scripts/sign-file \sha256 \
/opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/scst_module_key.priv \
/opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/scst_module_key.der \
_module-filename_
....
.. Installez la clé UEFI avec le firmware.
+
Les instructions d'installation de la clé UEFI se trouvent à l'adresse suivante :

+
`/opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/README.module-signing`

+
La clé UEFI générée se trouve à l'emplacement suivant :

+
`/opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/scst_module_key.der`



. Redémarrer le système :
+
`reboot`





== L'hôte modifie le nom d'hôte ou l'adresse IP

.Description de la tâche
* Effectuez cette tâche sur l’hôte Linux sur lequel vous avez installé ONTAP Mediator.
* Effectuez cette tâche uniquement si les certificats auto-signés sont obsolètes car le nom d’hôte ou l’adresse IP a changé après l’installation ONTAP Mediator.
* Une fois le certificat auto-signé temporaire remplacé par un certificat tiers de confiance, vous n'utilisez pas cette tâche pour régénérer un certificat.  Si vous ne disposez pas d’un certificat auto-signé, vous ne pouvez pas utiliser cette procédure.


.Étape
Créez un certificat auto-signé temporaire pour l’hôte actuel :

. Redémarrer ONTAP Mediator :
+
`./make_self_signed_certs.sh overwrite`

+
[listing]
----
[root@xyz000123456 ~]# cd /opt/netapp/lib/ontap_mediator/ontap_mediator/server_config
[root@xyz000123456 server_config]# ./make_self_signed_certs.sh overwrite

Adding Subject Alternative Names to the self-signed server certificate
#
# OpenSSL example configuration file.
Generating self-signed certificates
Generating RSA private key, 4096 bit long modulus (2 primes)
..................................................................................................................................................................++++
........................................................++++
e is 65537 (0x010001)
Generating a RSA private key
................................................++++
.............................................................................................................................................++++
writing new private key to 'ontap_mediator_server.key'
-----
Signature ok
subject=C = US, ST = California, L = San Jose, O = "NetApp, Inc.", OU = ONTAP Core Software, CN = ONTAP Mediator, emailAddress = support@netapp.com
Getting CA Private Key

[root@xyz000123456 server_config]# systemctl restart ontap_mediator
----

