---
permalink: mediator/index.html 
sidebar: sidebar 
keywords: ontap mediator service, install requirements, mediator requirements 
summary: 'Pour installer le service Mediator ONTAP, vous devez vous assurer que toutes les conditions préalables sont remplies, obtenir le package d"installation et exécuter le programme d"installation sur l"hôte.' 
---
= Préparez l'installation ou la mise à niveau du service Mediator ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour installer le service ONTAP Mediator, vous devez vous assurer que toutes les conditions préalables sont remplies, récupérer le package d'installation et exécuter le programme d'installation sur l'hôte. Cette procédure est utilisée pour une installation ou une mise à niveau d'une installation existante.

* À partir de ONTAP 9.7, vous pouvez utiliser n'importe quelle version du Mediator ONTAP pour contrôler une configuration IP MetroCluster.
* Depuis ONTAP 9.8, vous pouvez utiliser n'importe quelle version du médiateur ONTAP pour surveiller une relation de synchronisation active SnapMirror.




== Considérations sur l'installation et la mise à niveau

Consultez les considérations suivantes avant de mettre à niveau ou d'installer le Mediator ONTAP.


CAUTION: ONTAP Mediator 1.8 et versions antérieures n'est pas compatible avec le mode Red Hat Enterprise Linux FIPS et l'empêche de s'installer correctement. Vous pouvez vérifier si le mode FIPS est activé à l'aide de la `fips-mode-setup --check` commande. Vous pouvez désactiver le mode FIPS à l'aide de la `fips-modesetup --disable` commande. Redémarrez le système après avoir désactivé le mode FIPS pour installer correctement ONTAP Mediator 1.8 ou une version antérieure.

* Vous devez mettre à niveau le Mediator ONTAP vers la dernière version disponible. Les versions précédentes de ONTAP Mediator restent rétrocompatibles avec toutes les versions de ONTAP, mais les versions récentes incluent des correctifs de sécurité pour tous les éléments tiers.
* Lorsque vous effectuez une mise à niveau vers une nouvelle version de ONTAP Mediator, le programme d'installation se met automatiquement à niveau vers la version recommandée de SCST, sauf si une version supérieure est disponible. Pour obtenir des instructions sur l'installation manuelle d'une version SCST supérieure, reportez-vous à link:manage-task.html["Gérer le service Mediator"]la section . Pour connaître les versions prises en charge, consultez le link:whats-new-concept.html#scst-support-matrix["Matrice de prise en charge SCST"].
+

CAUTION: En cas d'échec de l'installation, vous devrez peut-être effectuer une mise à niveau vers une version plus récente de ONTAP Mediator.

* Si vous installez le `yum-utils` vous pouvez utiliser le `needs-restarting` commande.




=== Configuration requise pour le système d'exploitation

Votre système d'exploitation doit répondre aux exigences suivantes :

* installation physique 64 bits ou machine virtuelle
* 8 GO DE RAM
* 1 Go d'espace disque (utilisé pour l'installation des applications, les journaux du serveur et la base de données)
* Utilisateur : accès racine


Le tableau suivant présente les systèmes d'exploitation pris en charge pour chaque version de ONTAP Mediator.

[cols="30,70"]
|===


| Version du médiateur ONTAP | Versions Linux prises en charge 


 a| 
1,9
 a| 
* Red Hat Enterprise Linux
+
** Compatible : 8.4, 8.5, 8.6, 8.7, 8.9, 9.1 et 9.3 ^1^
** Recommandations : 8.8, 8.10, 9.0, 9.2 et 9.4


* Rocky Linux 8 et 9




 a| 
1.8
 a| 
* Red Hat Enterprise Linux : 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 8.10, 9.0, 9.1, 9.2, 9.3 et 9.4
* Rocky Linux 8 et 9




 a| 
1.7
 a| 
* Red Hat Enterprise Linux : 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9.0, 9.1, 9.2 et 9.3
* Rocky Linux 8 et 9




 a| 
1.6
 a| 
* Red Hat Enterprise Linux : 8.4, 8.5, 8.6, 8.7, 8.8, 9.0, 9.1, 9.2
* Rocky Linux 8 et 9




 a| 
1.5
 a| 
* Red Hat Enterprise Linux : 7.6, 7.7, 7.8, 7.9, 8.0, 8.1, 8.2, 8.3, 8.4, 8.5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.4
 a| 
* Red Hat Enterprise Linux : 7.6, 7.7, 7.8, 7.9, 8.0, 8.1, 8.2, 8.3, 8.4, 8.5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.3
 a| 
* Red Hat Enterprise Linux : 7.6, 7.7, 7.8, 7.9, 8.0, 8.1, 8.2, 8.3
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.2
 a| 
* Red Hat Enterprise Linux : 7.6, 7.7, 7.8, 7.9, 8.0, 8.1
* CentOS: 7.6, 7.7, 7.8, 7.9


|===
. Compatible signifie que RHEL ne prend plus en charge cette version mais que ONTAP Mediator peut toujours être installé.




=== Considérations sur la mise à niveau du système d'exploitation et la compatibilité du noyau

* Tous les packages de bibliothèque, à l'exception du noyau, peuvent être mis à jour en toute sécurité, mais ils peuvent nécessiter un redémarrage pour appliquer les modifications dans l'application ONTAP Mediator. Une fenêtre de service est recommandée lorsqu'un redémarrage est nécessaire.
* Vous devez maintenir le noyau du système d'exploitation à jour. Le noyau du noyau peut être mis à niveau vers une version répertoriée comme prise en charge dans le link:whats-new-concept.html#scst-support-matrix["Matrice de version du médiateur ONTAP"]. Le redémarrage est obligatoire. Vous devez donc prévoir une fenêtre de maintenance pour l'interruption de service.
+
** Vous devez désinstaller le module du noyau SCST avant de redémarrer, puis de le réinstaller après.
** Vous devez disposer d'une version prise en charge du SCST prête à être réinstallé avant de démarrer la mise à niveau du système d'exploitation du noyau.




[NOTE]
====
* La version du noyau doit correspondre à la version du système d'exploitation.
* La mise à niveau vers un noyau au-delà de la version du système d'exploitation prise en charge pour la version spécifique du Mediator ONTAP n'est pas prise en charge. (Cela indique probablement que le module SCST testé ne se compile pas).


====


== Enregistrez une clé de sécurité lorsque le démarrage sécurisé UEFI est activé

Pour installer le médiateur ONTAP avec le démarrage sécurisé UEFI activé, vous devez enregistrer une clé de sécurité avant de pouvoir démarrer le service. La clé est générée lors de l'étape de compilation de l'installation SCST et enregistrée en tant que paire de clés privée-publique sur votre machine. Utilisez `mokutil` l'utilitaire pour ajouter la clé publique en tant que clé propriétaire de l'ordinateur (MOK) à votre micrologiciel UEFI, ce qui permet au système d'approuver et de charger le module signé. Enregistrez la `mokutil` phrase de passe dans un emplacement sécurisé car cela est requis lors du redémarrage de votre système pour activer le MOK.

Pour déterminer si le système est activé pour UEFI et si l'amorçage sécurisé est activé, effectuez les opérations suivantes :

.Étapes
. Si `mokutil` n'est pas installé, exécutez la commande suivante :
+
`yum install mokutil`

. Vérifiez si le démarrage sécurisé UEFI est activé sur votre système :
+
`mokutil --sb-state`

+
Les résultats indiquent si le démarrage sécurisé UEFI est activé sur ce système.

+
[NOTE]
====
** Vous êtes invité à créer une phrase de passe que vous devez stocker dans un emplacement sécurisé. Vous aurez besoin de cette phrase de passe pour activer la clé dans le Gestionnaire d'amorçage UEFI.
** ONTAP Mediator 1.2.0 et les versions antérieures ne prennent pas en charge ce mode.


====
. Ajoutez la clé publique à la liste MOK :
+
`mokutil --import /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/scst_module_key.der`

+

NOTE: Vous pouvez laisser la clé privée à son emplacement par défaut ou la déplacer à un emplacement sécurisé. Cependant, la clé publique doit être conservée à son emplacement existant pour être utilisée par Boot Manager. Pour plus d'informations, reportez-vous au fichier README.module-Signing suivant :

+
`[root@hostname ~]# ls /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/
README.module-signing  scst_module_key.der  scst_module_key.priv`

. Redémarrez l'hôte et utilisez le gestionnaire d'amorçage UEFI de votre périphérique pour approuver le nouveau PROTOCOLE D'accès. Vous aurez besoin de la phrase de passe fournie pour le `mokutil` à l'étape 2.




== Désactivez le démarrage sécurisé UEFI

Vous pouvez également choisir de désactiver le démarrage sécurisé UEFI avant d'installer le médiateur ONTAP.

.Étapes
. Dans les paramètres du BIOS de la machine physique, désactivez l'option « démarrage sécurisé UEFI ».
. Dans les paramètres VMware de la machine virtuelle, désactivez l'option « démarrage sécurisé » pour vSphere 6.x ou l'option « démarrage sécurisé » pour vSphere 7.x.

