---
permalink: mediator/index.html 
sidebar: sidebar 
keywords: ontap mediator, install requirements, mediator requirements 
summary: 'Pour installer ONTAP Mediator, vous devez vous assurer que toutes les conditions préalables sont remplies, obtenir le package d"installation et exécuter le programme d"installation sur l"hôte.' 
---
= Préparez-vous à installer ou à mettre à niveau ONTAP Mediator
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour installer ONTAP Mediator, vous devez vous assurer que toutes les conditions préalables sont remplies, récupérer le package d'installation et exécuter le programme d'installation sur l'hôte. Cette procédure est utilisée pour une installation ou une mise à niveau d'une installation existante.

* À partir de ONTAP 9.7, vous pouvez utiliser n'importe quelle version du Mediator ONTAP pour contrôler une configuration IP MetroCluster.
* Depuis ONTAP 9.8, vous pouvez utiliser n'importe quelle version du médiateur ONTAP pour surveiller une relation de synchronisation active SnapMirror.




== Considérations sur l'installation et la mise à niveau

Passez en revue les considérations suivantes avant de mettre à niveau ou d’installer ONTAP Mediator.


NOTE: ONTAP Mediator 1.8 et versions antérieures n'est pas compatible avec le mode Red Hat Enterprise Linux FIPS et l'empêche de s'installer correctement. Vous pouvez vérifier si le mode FIPS est activé à l'aide de la `fips-mode-setup --check` commande. Vous pouvez désactiver le mode FIPS à l'aide de la `fips-modesetup --disable` commande. Redémarrez le système après avoir désactivé le mode FIPS pour installer correctement ONTAP Mediator 1.8 ou une version antérieure.

* Vous devez mettre à niveau ONTAP Mediator vers la dernière version disponible. Les versions précédentes de ONTAP Mediator restent rétrocompatibles avec toutes les versions de ONTAP, mais les versions récentes incluent des correctifs de sécurité pour tous les éléments tiers.
* Lorsque vous effectuez une mise à niveau vers une nouvelle version de ONTAP Mediator, le programme d'installation se met automatiquement à niveau vers la version recommandée de SCST, sauf si une version supérieure est disponible. Pour obtenir des instructions sur l'installation manuelle d'une version SCST supérieure, reportez-vous à link:manage-task.html["Gérer le médiateur ONTAP"]la section . Pour connaître les versions prises en charge, consultez le link:whats-new-concept.html#scst-support-matrix["Matrice de prise en charge SCST"].


[NOTE]
====
* En cas d'échec de l'installation, vous devrez peut-être effectuer une mise à niveau vers une version plus récente de ONTAP Mediator.
* À compter du 15 juin 2025, vous ne pourrez plus installer ni mettre à niveau ONTAP Mediator 1.8 et 1.9, car leurs certificats de signature de code ont expiré. En cas d'échec de l'installation ou de la mise à niveau, utilisez plutôt la version corrective ONTAP Mediator 1.9.1.


====
* Si vous installez le `yum-utils` vous pouvez utiliser le `needs-restarting` commande.




=== Configuration requise pour l'hôte

Suivez ces exigences lors de l'installation de Red Hat Enterprise Linux (RHEL) ou de Rocky Linux et de la configuration des référentiels associés.

[NOTE]
====
Si vous modifiez le processus d'installation ou de configuration, vous devrez peut-être effectuer des étapes supplémentaires.

====
.Conditions requises pour la distribution Linux
* Installez RHEL ou Rocky Linux conformément aux meilleures pratiques de Red Hat. Puisque CentOS 8.x est arrivé en fin de vie, les versions compatibles de CentOS 8.x ne sont pas recommandées.
* Lors de l'installation d'ONTAP Mediator, assurez-vous que le système a accès au référentiel requis afin que le programme d'installation puisse récupérer et installer toutes les dépendances logicielles requises.
* Pour permettre au programme d'installation yum de trouver des logiciels dépendants dans les référentiels RHEL, enregistrez le système lors de l'installation ou après en utilisant un abonnement Red Hat valide.
+
[NOTE]
====
Pour plus d'informations, reportez-vous à la documentation de Red Hat Subscription Manager.

====


.Configuration réseau requise
Assurez-vous que les ports suivants sont disponibles et inutilisés pour le Mediator ONTAP :

|===


| Port/services | Source | Direction | Destination | Objectif 


 a| 
22/tcp
 a| 
Hôte de gestion
 a| 
Entrant
 a| 
Médiateur de ONTAP
 a| 
(Facultatif) gestion du médiateur SSH/ONTAP



 a| 
31784/tcp
 a| 
LIF Cluster-management
 a| 
Entrant
 a| 
Serveur web du médiateur ONTAP
 a| 
(OBLIGATOIRE) API REST (HTTPS)



 a| 
3260/tcp ^1^
 a| 
LIF Node Data ou Node Management
 a| 
Bidirectionnel
 a| 
Cibles iSCSI du médiateur ONTAP
 a| 
(Requis pour MCCIP) connexion de données iSCSI pour les boîtes aux lettres

|===
. Pour les clients SMBC, ONTAP ne nécessite pas l'activation ou la connexion du port 3260.
+
** Si vous utilisez un pare-feu tiers, reportez-vous à la link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_mediator_requirements.html#firewall-requirements-for-ontap-mediator["Exigences relatives au pare-feu pour le médiateur ONTAP"^]section .
** Pour les hôtes Linux sans accès à Internet, assurez-vous que les packages requis sont disponibles dans un référentiel local.
+
Si vous utilisez le protocole LACP (Link Aggregation Control Protocol) dans un environnement Linux, configurez le noyau et définissez le `sysctl net.ipv4.conf.all.arp_ignore` sur `2`.





.Configuration requise pour le système d'exploitation
Votre système d'exploitation doit répondre aux exigences suivantes :

* installation physique 64 bits ou machine virtuelle
* 8 GO DE RAM
* 1 Go d'espace disque (utilisé pour l'installation des applications, les journaux du serveur et la base de données)
* Utilisateur : accès racine


Le tableau suivant présente les systèmes d'exploitation pris en charge pour chaque version du Media ONTAP.

[cols="30,70"]
|===


| Version du médiateur ONTAP | Versions Linux prises en charge 


 a| 
1,9
 a| 
* Red Hat Enterprise Linux
+
** Compatible : 8.4, 8.5, 8.6, 8.7, 8.9, 9.1 et 9.3 ^1^
** Recommandations : 8.8, 8.10, 9.0, 9.2, 9.4 et 9.5


* Rocky Linux 8 et 9




 a| 
1.8
 a| 
* Red Hat Enterprise Linux : 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 8.10, 9.0, 9.1, 9.2, 9.3 et 9.4
* Rocky Linux 8 et 9




 a| 
1.7
 a| 
* Red Hat Enterprise Linux : 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9.0, 9.1, 9.2 et 9.3
* Rocky Linux 8 et 9




 a| 
1.6
 a| 
* Red Hat Enterprise Linux : 8.4, 8.5, 8.6, 8.7, 8.8, 9.0, 9.1, 9.2
* Rocky Linux 8 et 9




 a| 
1.5
 a| 
* Red Hat Enterprise Linux : 7.6, 7.7, 7.8, 7.9, 8.0, 8.1, 8.2, 8.3, 8.4, 8.5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.4
 a| 
* Red Hat Enterprise Linux : 7.6, 7.7, 7.8, 7.9, 8.0, 8.1, 8.2, 8.3, 8.4, 8.5
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.3
 a| 
* Red Hat Enterprise Linux : 7.6, 7.7, 7.8, 7.9, 8.0, 8.1, 8.2, 8.3
* CentOS: 7.6, 7.7, 7.8, 7.9




 a| 
1.2
 a| 
* Red Hat Enterprise Linux : 7.6, 7.7, 7.8, 7.9, 8.0, 8.1
* CentOS: 7.6, 7.7, 7.8, 7.9


|===
. Compatible signifie que RHEL ne prend plus en charge cette version mais que ONTAP Mediator peut toujours être installé.


.Packs OS requis
Les packages suivants sont requis par ONTAP Mediator :


NOTE: Les packages sont préinstallés ou automatiquement installés par le programme d'installation du Mediator ONTAP.

[cols="34,33,33"]
|===


| Toutes les versions de RHEL/CentOS | Packages supplémentaires pour RHEL 8.x / Rocky Linux 8 | Packages supplémentaires pour RHEL 9.x / Rocky Linux 9 


 a| 
* openssl
* openssl-devel
* kernel-devel-$ (nom_uname -r)
* gcc
* marque
* libselinux-utils
* correctif
* bzip2
* perl-Data-Dumper
* perl-ExtUtils-MakeMaker
* efibootmgr
* mokutil

 a| 
* python3-pip
* elfutils-libelf-devel
* politiqueutils-python-utils
* red hat-lsb-core
* python39
* python39-devel

 a| 
* python3-pip
* elfutils-libelf-devel
* politiqueutils-python-utils
* python3
* python3-devel


|===
Le package d'installation Mediator est un fichier tar compressé auto-extractible qui comprend :

* Un fichier RPM contenant toutes les dépendances qui ne peuvent pas être obtenues du référentiel de la version prise en charge.
* Un script d'installation.


Une certification SSL valide est recommandée.



=== Considérations sur la mise à niveau du système d'exploitation et la compatibilité du noyau

* Tous les packages de bibliothèque, à l'exception du noyau, peuvent être mis à jour en toute sécurité, mais ils peuvent nécessiter un redémarrage pour appliquer les modifications dans l'application ONTAP Mediator. Une fenêtre de service est recommandée lorsqu'un redémarrage est nécessaire.
* Vous devez maintenir le noyau du système d'exploitation à jour. Le noyau du noyau peut être mis à niveau vers une version répertoriée comme prise en charge dans le link:whats-new-concept.html#scst-support-matrix["Matrice de version du médiateur ONTAP"]. Le redémarrage est obligatoire. Vous devez donc prévoir une fenêtre de maintenance pour l'interruption de service.
+
** Vous devez désinstaller le module du noyau SCST avant de redémarrer, puis de le réinstaller après.
** Vous devez disposer d'une version prise en charge du SCST prête à être réinstallé avant de démarrer la mise à niveau du système d'exploitation du noyau.




[NOTE]
====
* La version du noyau doit correspondre à la version du système d'exploitation.
* La mise à niveau vers un noyau au-delà de la version du système d'exploitation prise en charge pour la version spécifique du Mediator ONTAP n'est pas prise en charge. (Cela indique probablement que le module SCST testé ne se compile pas).


====


== Installez le médiateur ONTAP lorsque le démarrage sécurisé UEFI est activé

ONTAP Mediator peut être installé sur un système avec ou sans démarrage sécurisé UEFI activé.

.Description de la tâche
Vous pouvez choisir de désactiver le démarrage sécurisé UEFI avant d'installer le médiateur ONTAP s'il n'est pas nécessaire ou si vous dépannez des problèmes d'installation du médiateur ONTAP. Désactivez l'option UEFI Secure Boot dans les paramètres de votre ordinateur.

[NOTE]
====
Pour obtenir des instructions détaillées sur la désactivation de l'amorçage sécurisé UEFI, reportez-vous à la documentation de votre système d'exploitation hôte.

====
Pour installer ONTAP Mediator avec UEFI Secure Boot activé, vous devez enregistrer une clé de sécurité avant que le service puisse démarrer. La clé est générée lors de l'étape de compilation de l'installation SCST et enregistrée en tant que paire de clés privée-publique sur votre machine. Utilisez `mokutil` l'utilitaire pour ajouter la clé publique en tant que clé propriétaire de l'ordinateur (MOK) à votre micrologiciel UEFI, ce qui permet au système d'approuver et de charger le module signé. Enregistrez la `mokutil` phrase de passe dans un emplacement sécurisé car cela est requis lors du redémarrage de votre système pour activer le MOK.

.Étapes
. [[STEP_1_uefi]]Vérifiez si le démarrage sécurisé UEFI est activé sur votre système :
+
`mokutil --sb-state`

+
Les résultats indiquent si le démarrage sécurisé UEFI est activé sur ce système.

+
[cols="40,60"]
|===


| Si... | Aller à... 


 a| 
Le démarrage sécurisé UEFI est activé
 a| 




 a| 
Le démarrage sécurisé UEFI est désactivé
 a| 
link:upgrade-host-os-mediator-task.html["Mettez à niveau le système d'exploitation hôte, puis ONTAP Mediator"]

|===
+
[NOTE]
====
** Vous êtes invité à créer une phrase de passe que vous devez stocker dans un emplacement sécurisé. Vous aurez besoin de cette phrase de passe pour activer la clé dans le Gestionnaire d'amorçage UEFI.
** ONTAP Mediator 1.2.0 et les versions antérieures ne prennent pas en charge ce mode.


====
. [[STEP_2_uefi]]si l' `mokutil`utilitaire n'est pas installé, exécutez la commande suivante :
+
`yum install mokutil`

. Ajoutez la clé publique à la liste MOK :
+
`mokutil --import /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/scst_module_key.der`

+

NOTE: Vous pouvez laisser la clé privée à son emplacement par défaut ou la déplacer à un emplacement sécurisé. Cependant, la clé publique doit être conservée à son emplacement existant pour être utilisée par Boot Manager. Pour plus d'informations, reportez-vous au fichier README.module-Signing suivant :

+
`[root@hostname ~]# ls /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/
README.module-signing  scst_module_key.der  scst_module_key.priv`

. Redémarrez l'hôte et utilisez le gestionnaire d'amorçage UEFI de votre périphérique pour approuver le nouveau PROTOCOLE D'accès. Vous aurez besoin de la phrase de passe fournie pour `mokutil` l'utilitaire dans <<step_1_uefi,Étape permettant de vérifier si le démarrage sécurisé UEFI est activé sur votre système>>.

