---
permalink: mediator/manage-task.html 
sidebar: sidebar 
keywords: mediator, service, username, user name, password, change, uninstall, self-signed certificate, self signed certificate, regenerate, stop mediator service, uninstall scst 
summary: 'Une fois le service ONTAP Mediator installé, vous pouvez modifier le nom d"utilisateur ou le mot de passe. Vous pouvez également désinstaller le service ONTAP Mediator.' 
---
= Gérez le service ONTAP médiateur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois le service ONTAP Mediator installé, vous pouvez modifier le nom d'utilisateur ou le mot de passe. Vous pouvez également désinstaller le service ONTAP Mediator.



== Modifier le nom d'utilisateur

.À propos de ces tâches
Cette tâche est exécutée sur l'hôte Linux sur lequel le service ONTAP Mediator est installé.

Si vous ne pouvez pas atteindre cette commande, il vous faudra peut-être exécuter la commande en utilisant le chemin d'accès complet, comme illustré dans l'exemple suivant :

`/usr/local/bin/mediator_username`

.Procédure
Modifiez le nom d'utilisateur en choisissant l'une des options suivantes :

* Exécutez la commande mediator_change_user et répondez aux invites comme indiqué dans l'exemple suivant :
+
....
 [root@mediator-host ~]# mediator_change_user
 Modify the Mediator API username by entering the following values:
     Mediator API User Name: mediatoradmin
                   Password:
 New Mediator API User Name: mediator
 The account username has been modified successfully.
 [root@mediator-host ~]#
....
* Exécutez la commande suivante :
+
`MEDIATOR_USERNAME=mediator MEDIATOR_PASSWORD=mediator2 MEDIATOR_NEW_USERNAME=mediatoradmin mediator_change_user`

+
....
 [root@mediator-host ~]# MEDIATOR_USERNAME= mediator MEDIATOR_PASSWORD='mediator2' MEDIATOR_NEW_USERNAME= mediatoradmin mediator_change_user
 The account username has been modified successfully.
 [root@mediator-host ~]#
....




== Changer le mot de passe

.Description de la tâche
Cette tâche est effectuée sur l'hôte Linux sur lequel le service ONTAP Mediator est installé.

Si vous ne pouvez pas atteindre cette commande, il vous faudra peut-être exécuter la commande en utilisant le chemin d'accès complet, comme illustré dans l'exemple suivant :

`/usr/local/bin/mediator_change_password`

.Procédure
Modifiez le mot de passe en choisissant l'une des options suivantes :

* Exécutez le `mediator_change_password` commande et répond aux invites, comme illustré dans l'exemple suivant :
+
....
 [root@mediator-host ~]# mediator_change_password
 Change the Mediator API password by entering the following values:
    Mediator API User Name: mediatoradmin
              Old Password:
              New Password:
          Confirm Password:
 The password has been updated successfully.
 [root@mediator-host ~]#
....
* Exécutez la commande suivante :
+
`MEDIATOR_USERNAME= mediatoradmin MEDIATOR_PASSWORD=mediator1 MEDIATOR_NEW_PASSWORD=mediator2 mediator_change_password`

+
L'exemple montre que le mot de passe passe passe de "mediator1" à "mediator2".

+
....
 [root@mediator-host ~]# MEDIATOR_USERNAME=mediatoradmin MEDIATOR_PASSWORD=mediator1 MEDIATOR_NEW_PASSWORD=mediator2 mediator_change_password
 The password has been updated successfully.
 [root@mediator-host ~]#
....




== Arrêtez le service ONTAP Mediator

Pour arrêter le service du médiateur ONTAP, effectuez les opérations suivantes :

.Étapes
. Arrêtez le médiateur ONTAP.
+
`systemctl stop ontap_mediator`

. Arrêter SCST.
+
`systemctl stop mediator-scst`

. Désactivez le Mediator ONTAP et le SCST.
+
`systemctl diable ontap_mediator mediator-scst`





== Réactiver le service ONTAP Mediator

Pour réactiver le service ONTAP Mediator, effectuez les opérations suivantes :

.Étapes
. Activez le Mediator ONTAP et le SCST.
+
`systemctl enable ontap_mediator mediator-scst`

. Démarrez SCST.
+
`systemctl start mediator-scst`

. Démarrez ONTAP Mediator.
+
`systemctl start ontap_mediator`





== Vérifiez que le médiateur ONTAP fonctionne correctement

Une fois le médiateur ONTAP installé, vous devez vérifier que les services du médiateur ONTAP sont en cours d'exécution.

.Étapes
. Afficher l'état des services du médiateur ONTAP :
+
.. `systemctl status ontap_mediator`
+
[listing]
----
[root@scspr1915530002 ~]# systemctl status ontap_mediator

 ontap_mediator.service - ONTAP Mediator
Loaded: loaded (/etc/systemd/system/ontap_mediator.service; enabled; vendor preset: disabled)
Active: active (running) since Mon 2022-04-18 10:41:49 EDT; 1 weeks 0 days ago
Process: 286710 ExecStop=/bin/kill -s INT $MAINPID (code=exited, status=0/SUCCESS)
Main PID: 286712 (uwsgi)
Status: "uWSGI is ready"
Tasks: 3 (limit: 49473)
Memory: 139.2M
CGroup: /system.slice/ontap_mediator.service
      ├─286712 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini
      ├─286716 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini
      └─286717 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini

[root@scspr1915530002 ~]#
----
.. `systemctl status mediator-scst`
+
[listing]
----
[root@scspr1915530002 ~]# systemctl status mediator-scst
   Loaded: loaded (/etc/systemd/system/mediator-scst.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2022-04-18 10:41:47 EDT; 1 weeks 0 days ago
  Process: 286595 ExecStart=/etc/init.d/scst start (code=exited, status=0/SUCCESS)
 Main PID: 286662 (iscsi-scstd)
    Tasks: 1 (limit: 49473)
   Memory: 1.2M
   CGroup: /system.slice/mediator-scst.service
           └─286662 /usr/local/sbin/iscsi-scstd

[root@scspr1915530002 ~]#
----


. Vérifiez les ports utilisés par le service ONTAP Mediator :
+
`netstat`

+
[listing]
----
[root@scspr1905507001 ~]# netstat -anlt | grep -E '3260|31784'

         tcp   0   0 0.0.0.0:31784   0.0.0.0:*      LISTEN

         tcp   0   0 0.0.0.0:3260    0.0.0.0:*      LISTEN

         tcp6  0   0 :::3260         :::*           LISTEN
----




== Désinstallez manuellement SCST pour effectuer la maintenance de l'hôte

Pour désinstaller SCST, vous avez besoin du paquet tar SCST utilisé pour la version installée de ONTAP Mediator.

.Étapes
. Téléchargez l'ensemble SCST approprié (comme indiqué dans le tableau suivant) et décompressez-le.
+
[cols="50,50"]
|===


| Pour cette version ... | Utiliser ce paquet tar... 


 a| 
Médiateur ONTAP 1.7
 a| 
scst-3.7.0.tar.bz2



 a| 
Médiateur ONTAP 1.6
 a| 
scst-3.7.0.tar.bz2



 a| 
Médiateur ONTAP 1.5
 a| 
scst-3.6.0.tar.bz2



 a| 
Médiateur ONTAP 1.4
 a| 
scst-3.6.0.tar.bz2



 a| 
Médiateur ONTAP 1.3
 a| 
scst-3.5.0.tar.bz2



 a| 
Médiateur ONTAP 1.1
 a| 
scst-3.4.0.tar.bz2



 a| 
Médiateur ONTAP 1.0
 a| 
scst-3.3.0.tar.bz2

|===
. Exécutez les commandes suivantes dans le répertoire « scst » :
+
.. `systemctl stop mediator-scst`
.. `make scstadm_uninstall`
.. `make iscsi_uninstall`
.. `make usr_uninstall`
.. `make scst_uninstall`
.. `depmod`






== Installez manuellement SCST pour effectuer la maintenance de l'hôte

Pour installer manuellement le SCST, vous devez disposer du paquet tar SCST utilisé pour la version installée du Mediator ONTAP (voir le <<scst-bundle-table,tableau ci-dessus>>).

. Exécutez les commandes suivantes dans le répertoire « scst » :
+
.. `make 2release`
.. `make scst_install`
.. `make usr_install`
.. `make iscsi_install`
.. `make scstadm_install`
.. `depmod`
.. `cp scst/src/certs/scst_module_key.der /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/.`
.. `cp scst/src/certs/scst_module_key.der /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/.`
.. `patch /etc/init.d/scst < /opt/netapp/lib/ontap_mediator/systemd/scst.patch`


. (Facultatif) si le démarrage sécurisé est activé, effectuez les opérations suivantes avant de redémarrer :
+
.. Déterminez chaque nom de fichier pour les modules "scst_vdisk", "scst" et "iscsi_scst".
+
....
[root@localhost ~]# modinfo -n scst_vdisk
[root@localhost ~]# modinfo -n scst
[root@localhost ~]# modinfo -n iscst_scst
....
.. Déterminez la version du noyau.
+
....
[root@localhost ~]# uname -r
....
.. Signez chaque fichier avec le noyau.
+
....
[root@localhost ~]# /usr/src/kernels/<KERNEL-RELEASE>/scripts/sign-file \sha256 \
/opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/scst_module_key.priv \
/opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/scst_module_key.der \
_module-filename_
....
.. Installez la clé correcte avec le micrologiciel UEFI.
+
Les instructions d'installation de la clé UEFI se trouvent à l'adresse suivante :

+
`/opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/README.module-signing`

+
La clé UEFI générée se trouve à l'emplacement suivant :

+
`/opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/scst_module_key.der`



. Redémarrer.
+
`reboot`





== Désinstallez le service ONTAP Mediator

.Avant de commencer
Si nécessaire, vous pouvez supprimer le service ONTAP Mediator. Le médiateur doit être déconnecté de ONTAP avant de supprimer le service médiateur.

.Description de la tâche
Cette tâche est effectuée sur l'hôte Linux sur lequel le service ONTAP Mediator est installé.

Si vous ne pouvez pas atteindre cette commande, il vous faudra peut-être exécuter la commande en utilisant le chemin d'accès complet, comme illustré dans l'exemple suivant :

`/usr/local/bin/uninstall_ontap_mediator`

.Étape
. Désinstallez le service ONTAP Mediator :
+
`uninstall_ontap_mediator`

+
....
 [root@mediator-host ~]# uninstall_ontap_mediator

 ONTAP Mediator: Self Extracting Uninstaller

 + Removing ONTAP Mediator. (Log: /tmp/ontap_mediator.GmRGdA/uninstall_ontap_mediator/remove.log)
 + Remove successful.
 [root@mediator-host ~]#
....




== Régénérez un certificat auto-signé temporaire

.Description de la tâche
* Vous effectuez cette tâche sur l'hôte Linux sur lequel le service ONTAP Mediator est installé.
* Vous pouvez effectuer cette tâche uniquement si les certificats auto-signés générés sont devenus obsolètes en raison de modifications apportées au nom d'hôte ou à l'adresse IP de l'hôte après l'installation du médiateur ONTAP.
* Une fois que le certificat auto-signé temporaire a été remplacé par un certificat tiers approuvé, vous devez _ne_ pas_ utiliser cette tâche pour régénérer un certificat.  L'absence d'un certificat auto-signé entraînera l'échec de cette procédure.


.Étape
Pour régénérer un nouveau certificat auto-signé temporaire pour l'hôte actuel, effectuez l'étape suivante :

. Redémarrez le médiateur ONTAP :
+
`./make_self_signed_certs.sh overwrite`

+
[listing]
----
[root@xyz000123456 ~]# cd /opt/netapp/lib/ontap_mediator/ontap_mediator/server_config
[root@xyz000123456 server_config]# ./make_self_signed_certs.sh overwrite

Adding Subject Alternative Names to the self-signed server certificate
#
# OpenSSL example configuration file.
Generating self-signed certificates
Generating RSA private key, 4096 bit long modulus (2 primes)
..................................................................................................................................................................++++
........................................................++++
e is 65537 (0x010001)
Generating a RSA private key
................................................++++
.............................................................................................................................................++++
writing new private key to 'ontap_mediator_server.key'
-----
Signature ok
subject=C = US, ST = California, L = San Jose, O = "NetApp, Inc.", OU = ONTAP Core Software, CN = ONTAP Mediator, emailAddress = support@netapp.com
Getting CA Private Key
----

