---
permalink: mediator/upgrade-host-os-mediator-task.html 
sidebar: sidebar 
keywords: mediator, new, release, update, install, 
summary: 'Dans le cadre du processus d"installation, vous mettez à niveau le système d"exploitation hôte, puis le médiateur ONTAP.' 
---
= Mettez à niveau le système d'exploitation hôte, puis le médiateur ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour mettre à niveau le système d'exploitation hôte pour ONTAP Mediator vers une version ultérieure, vous devez d'abord désinstaller ONTAP Mediator.

.Avant de commencer
Les meilleures pratiques d'installation de Red Hat Enterprise Linux ou Rocky Linux et des référentiels associés sur votre système sont répertoriées ci-dessous. Les systèmes installés ou configurés différemment peuvent nécessiter des étapes supplémentaires.

* Vous devez installer Red Hat Enterprise Linux ou Rocky Linux conformément aux meilleures pratiques de Red Hat. En raison de la fin de vie des versions CentOS 8.x, les versions compatibles de CentOS 8.x ne sont pas recommandées.
* Lors de l'installation du service ONTAP Mediator sur Red Hat Enterprise Linux ou Rocky Linux, le système doit avoir accès au référentiel approprié pour que le programme d'installation puisse accéder à toutes les dépendances logicielles requises et les installer.
* Pour que le programme d'installation de yum trouve des logiciels dépendants dans les référentiels Red Hat Enterprise Linux, vous devez avoir enregistré le système pendant l'installation de Red Hat Enterprise Linux ou ultérieurement en utilisant un abonnement Red Hat valide.
+
Pour plus d'informations sur le Gestionnaire d'abonnement Red Hat, reportez-vous à la documentation Red Hat.

* Les ports suivants doivent être inutilisés et disponibles pour le médiateur :
+
** 31784
** 3260


* Si vous utilisez un pare-feu tiers : reportez-vous à la link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_mediator_requirements.html#firewall-requirements-for-ontap-mediator["Exigences relatives au pare-feu pour le médiateur ONTAP"^]
* Si l'hôte Linux se trouve dans un emplacement sans accès à Internet, vous devez vous assurer que les packages requis sont disponibles dans un référentiel local.
+
Si vous utilisez le protocole LACP (Link Aggregation Control Protocol) dans un environnement Linux, vous devez configurer correctement le noyau et vous assurer que le `sysctl net.ipv4.conf.all.arp_ignore` est réglé sur « 2 ».



.Ce dont vous avez besoin
Les packages suivants sont requis par le service ONTAP Mediator :

[cols="34,33,33"]
|===


| Toutes les versions de RHEL/CentOS | Packages supplémentaires pour RHEL 8.x / Rocky Linux 8 | Packages supplémentaires pour RHEL 9.x / Rocky Linux 9 


 a| 
* openssl
* openssl-devel
* kernel-devel-$ (nom_uname -r)
* gcc
* marque
* libselinux-utils
* correctif
* bzip2
* perl-Data-Dumper
* perl-ExtUtils-MakeMaker
* efibootmgr
* mokutil

 a| 
* python3-pip
* elfutils-libelf-devel
* politiqueutils-python-utils
* red hat-lsb-core
* python39
* python39-devel

 a| 
* python3-pip
* elfutils-libelf-devel
* politiqueutils-python-utils
* python3
* python3-devel


|===
Le package d'installation Mediator est un fichier tar compressé auto-extractible qui comprend :

* Un fichier RPM contenant toutes les dépendances qui ne peuvent pas être obtenues du référentiel de la version prise en charge.
* Un script d'installation.


Une certification SSL valide est recommandée.

.Description de la tâche
Lorsque vous mettez à niveau le système d'exploitation hôte pour ONTAP Mediator vers une version majeure ultérieure (par exemple, de 7.x à 8.x) à l'aide de l'outil de mise à niveau leapp, Vous devez désinstaller ONTAP Mediator car l'outil tente de détecter les nouvelles versions de tous les RPM installés dans les référentiels enregistrés avec le système.

Comme un fichier .rpm a été installé dans le cadre du programme d'installation de ONTAP Mediator, il est inclus dans cette recherche. Cependant, comme ce fichier .rpm a été décompressé dans le cadre du programme d'installation et n'a pas été téléchargé à partir d'un référentiel enregistré, une mise à niveau est introuvable. Dans ce cas, l'outil de mise à niveau leapp désinstalle le package.

Afin de conserver les fichiers journaux, qui seront utilisés pour trier les dossiers de support, vous devez sauvegarder les fichiers avant de procéder à une mise à niveau du système d'exploitation et les restaurer après une réinstallation du progiciel ONTAP Mediator. Étant donné que le médiateur ONTAP est en cours de réinstallation, tous les clusters ONTAP qui y sont connectés devront être reconnectés après la nouvelle installation.


NOTE: Les étapes suivantes doivent être effectuées dans l'ordre.  Immédiatement après la réinstallation du médiateur ONTAP, vous devez arrêter le service ontap_médiateur, remplacer les fichiers journaux et redémarrer le service. Cela permet de s'assurer que les journaux ne seront pas perdus.

.Étapes
. Sauvegardez les fichiers journaux.
+
....
[rootmediator-host ~]# tar -czf ontap_mediator_file_backup.tgz -C /opt/netapp/lib/ontap_mediator ./log ./ontap_mediator/server_config/ontap_mediator.user_config.yaml
[rootmediator-host ~]# tar -tf ontap_mediator_file_backup.tgz
./log/
./log/ontap_mediator.log
./log/scstadmin.log
./log/ontap_mediator_stdout.log
./log/ontap_mediator_requests.log
./log/install_20230419134611.log
./log/scst.log
./log/ontap_mediator_syslog.log
./ontap_mediator/server_config/ontap_mediator.user_config.yaml
[rootmediator-host ~]#
....
. Effectuez une mise à niveau avec l'outil de mise à niveau leapp.
+
....
[rootmediator-host ~]# leapp preupgrade --target 8.4
  ..<snip upgrade checks>..
  ..<fix issues found>..
[rootmediator-host ~]# leapp upgrade --target 8.4
  ..<snip upgrade>..
[rootmediator-host ~]# cat /etc/os-release | head -2
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
[rootmediator-host ~]#
....
. Réinstallez le médiateur ONTAP.
+

NOTE: Effectuez le reste des étapes immédiatement après la réinstallation du médiateur ONTAP pour éviter la perte des fichiers journaux.

+
....
[rootmediator-host ~]# ontap-mediator-1.6.0/ontap-mediator-1.6.0

ONTAP Mediator: Self Extracting Installer

  ..<snip installation>..
[rootmediator-host ~]#
....
. Arrêtez le service ontap_médiateur.
+
....
[rootmediator-host ~]# systemctl stop ontap_mediator
[rootmediator-host ~]#
....
. Remplacez les fichiers journaux.
+
....
[rootmediator-host ~]# tar -xf ontap_mediator_log_backup.tgz -C /opt/netapp/lib/ontap_mediator
[rootmediator-host ~]#
....
. Démarrez le service ontap_médiateur.
+
....
[rootmediator-host ~]# systemctl start ontap_mediator
[rootmediator-host ~]#
....
. Reconnectez tous les clusters ONTAP au médiateur ONTAP mis à niveau
+
.Procédure pour MetroCluster sur IP
[%collapsible]
====
....
siteA::> metrocluster configuration-settings mediator show
Mediator IP     Port    Node                    Configuration Connection
                                                Status        Status
--------------- ------- ----------------------- ------------- -----------
172.31.40.122
                31784   siteA-node2             true          false
                        siteA-node1             true          false
                        siteB-node2             true          false
                        siteB-node2             true          false
siteA::> metrocluster configuration-settings mediator remove
Removing the mediator and disabling Automatic Unplanned Switchover. It may take a few minutes to complete.
Please enter the username for the mediator: mediatoradmin
Please enter the password for the mediator:
Confirm the mediator password:
Automatic Unplanned Switchover is disabled for all nodes...
Removing mediator mailboxes...
Successfully removed the mediator.

siteA::> metrocluster configuration-settings mediator add -mediator-address 172.31.40.122
Adding the mediator and enabling Automatic Unplanned Switchover. It may take a few minutes to complete.
Please enter the username for the mediator: mediatoradmin
Please enter the password for the mediator:
Confirm the mediator password:
Successfully added the mediator.

siteA::> metrocluster configuration-settings mediator show
Mediator IP     Port    Node                    Configuration Connection
                                                Status        Status
--------------- ------- ----------------------- ------------- -----------
172.31.40.122
                31784   siteA-node2             true          true
                        siteA-node1             true          true
                        siteB-node2             true          true
                        siteB-node2             true          true
siteA::>
....
====


.Procédure de synchronisation active SnapMirror
[%collapsible]
====
Pour la synchronisation active SnapMirror, si vous avez installé votre certificat TLS en dehors du répertoire /opt/netapp, vous n'avez pas besoin de le réinstaller. Si vous utilisiez le certificat auto-signé généré par défaut ou si vous placez votre certificat personnalisé dans le répertoire /opt/netapp, vous devez le sauvegarder et le restaurer.

....
peer1::> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
172.31.49.237    peer2            unreachable       true

peer1::> snapmirror mediator remove -mediator-address 172.31.49.237 -peer-cluster peer2

Info: [Job 39] 'mediator remove' job queued

peer1::> job show -id 39
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
39     mediator remove      peer1      peer1-node1    Success
     Description: Removing entry in mediator

peer1::> security certificate show -common-name ONTAPMediatorCA
Vserver    Serial Number   Certificate Name                       Type
---------- --------------- -------------------------------------- ------------
peer1
        4A790360081F41145E14C5D7CE721DC6C210007F
                        ONTAPMediatorCA                        server-ca
    Certificate Authority: ONTAP Mediator CA
        Expiration Date: Mon Apr 17 10:27:54 2073

peer1::> security certificate delete -common-name ONTAPMediatorCA *
1 entry was deleted.

 peer1::> security certificate install -type server-ca -vserver peer1

Please enter Certificate: Press <Enter> when done
  ..<snip ONTAP Mediator CA public key>..

You should keep a copy of the CA-signed digital certificate for future reference.

The installed certificate's CA and serial number for reference:
CA: ONTAP Mediator CA
serial: 44786524464C5113D5EC966779D3002135EA4254

The certificate's generated name for reference: ONTAPMediatorCA

peer2::> security certificate delete -common-name ONTAPMediatorCA *
1 entry was deleted.

peer2::> security certificate install -type server-ca -vserver peer2

 Please enter Certificate: Press <Enter> when done
..<snip ONTAP Mediator CA public key>..


You should keep a copy of the CA-signed digital certificate for future reference.

The installed certificate's CA and serial number for reference:
CA: ONTAP Mediator CA
serial: 44786524464C5113D5EC966779D3002135EA4254

The certificate's generated name for reference: ONTAPMediatorCA

peer1::> snapmirror mediator add -mediator-address 172.31.49.237 -peer-cluster peer2 -username mediatoradmin

Notice: Enter the mediator password.

Enter the password:
Enter the password again:

Info: [Job: 43] 'mediator add' job queued

peer1::> job show -id 43
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
43     mediator add         peer1      peer1-node2    Success
    Description: Creating a mediator entry

peer1::> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
172.31.49.237    peer2            connected         true

peer1::>

....
====