---
permalink: update/enable-automatic-updates-task.html 
sidebar: sidebar 
keywords: ontap, enable, upgrade, update, automatic, automated, firmware, bmc, sp, system, timezone database, timezone 
summary: 'L"activation des mises à jour automatiques permet à ONTAP de télécharger et d"installer les mises à jour du micrologiciel et de la base de données de fuseaux horaires sans votre intervention.' 
---
= Activer les mises à jour automatiques
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis ONTAP 9.10.1, vous pouvez activer les mises à jour automatiques pour permettre à ONTAP de télécharger et d'installer des mises à jour de micrologiciel sans votre intervention.

Depuis ONTAP 9.13.1, ces mises à jour automatiques incluent également des mises à jour automatiques de la base de données de fuseaux horaires.

.Avant de commencer
Vous devez disposer d'un support en cours. Ceci peut être validé sur le link:https://mysupport.netapp.com/site/["Site de support NetApp"] Dans la page *Détails du système*.

.Description de la tâche
Pour activer les mises à jour automatiques, vous devez d'abord activer AutoSupport avec HTTPS. Si AutoSupport n'est pas activé sur votre cluster ou si AutoSupport est activé sur votre cluster avec un autre protocole de transport, vous aurez la possibilité de l'activer avec HTTPS au cours de cette procédure.

.Étapes
. Dans System Manager, cliquez sur *Events*.
. Dans la section *Présentation*, en regard de *Activer la mise à jour automatique*, cliquez sur *actions>Activer*.
. Si AutoSupport avec HTTPS n'est pas activé, sélectionnez pour l'activer.
. Acceptez les conditions générales et sélectionnez *Enregistrer*.


.Informations associées
https://docs.netapp.com/us-en/ontap/system-admin/troubleshoot-autosupport-http-https-task.html["Dépanner la distribution des messages AutoSupport via HTTP ou HTTPS"]
