---
permalink: update/index.html 
sidebar: sidebar 
keywords: ontap, upgrade, update, automatic, automated, firmware, bmc, sp, system, timezone database, timezone, security, arp 
summary: Selon votre version de ONTAP, vous pouvez activer les mises à jour automatiques du micrologiciel, du système et de la sécurité. 
---
= Présentation des mises à jour de firmware, de système et de sécurité
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Selon votre version de ONTAP, vous pouvez activer les mises à jour automatiques du micrologiciel, du système et de la sécurité.

[cols="25,75"]
|===
| Version ONTAP | Ce qui est inclus dans les mises à jour automatiques 


| 9.16.1 et versions ultérieures  a| 
* Protection anti-ransomware autonome avec l'intelligence artificielle (ARP/IA)
* Base de données fuseau horaire ONTAP
* Micrologiciel de stockage pour les périphériques de stockage, les disques et les tiroirs disques
* Micrologiciel SP/BMC pour les processeurs de service et les modules BMC




| 9.13.1 et versions ultérieures  a| 
* Base de données fuseau horaire ONTAP
* Micrologiciel de stockage pour les périphériques de stockage, les disques et les tiroirs disques
* Micrologiciel SP/BMC pour les processeurs de service et les modules BMC




| 9.10.1 et versions ultérieures  a| 
* Micrologiciel de stockage pour les périphériques de stockage, les disques et les tiroirs disques
* Micrologiciel SP/BMC pour les processeurs de service et les modules BMC




| 9.9.1 et versions antérieures | Non pris en charge 
|===
Si aucune mise à jour automatique n'est disponible pour votre version de ONTAP ou si vous n'avez pas activé les mises à jour automatiques, vous pouvez effectuer les mises à jour de micrologiciel, de base de données de fuseau horaire et de sécurité manuellement.

.Liens connexes
* link:firmware-task.html["Apprenez à effectuer des mises à jour de firmware manuellement"]
* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_update_time_zone_information_in_ONTAP_9["Article de la base de connaissances, Comment mettre à jour les informations de fuseau horaire dans ONTAP 9"^]
* link:../anti-ransomware/enable-arp-ai-with-au.html["Apprenez à effectuer des mises à jour de sécurité manuellement"]




== Vidéo : fonction de mise à jour automatique du micrologiciel

Jetez un coup d'œil à la fonction de mise à jour automatique du micrologiciel disponible à partir de ONTAP 9.10.1.

video::GoABILT85hQ[youtube,width=848,height=480]