---
permalink: update/index.html 
sidebar: sidebar 
keywords: ontap, upgrade, update, automatic, automated, firmware, bmc, sp, system, timezone database, timezone 
summary: Selon votre version de ONTAP, vous pouvez activer les mises à jour automatiques du micrologiciel et du système. 
---
= Présentation des mises à jour du firmware et du système
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Selon votre version de ONTAP, vous pouvez activer les mises à jour automatiques du micrologiciel et du système.

[cols="25,75"]
|===
| Version ONTAP | Ce qui est inclus dans les mises à jour automatiques 


| 9.13.1 et versions ultérieures  a| 
* Base de données fuseau horaire ONTAP
* Micrologiciel de stockage pour les périphériques de stockage, les disques et les tiroirs disques
* Micrologiciel SP/BMC pour les processeurs de service et les modules BMC




| 9.10.1 et versions ultérieures  a| 
* Micrologiciel de stockage pour les périphériques de stockage, les disques et les tiroirs disques
* Micrologiciel SP/BMC pour les processeurs de service et les modules BMC




| 9.9.1 et versions antérieures | Non pris en charge 
|===
Si vous utilisez ONTAP 9.9.1 ou une version antérieure, ou si vous ne l'avez pas link:enable-automatic-updates-task.html["mises à jour automatiques du système"] activé, c'est possible link:firmware-task.html["effectuez les mises à jour de micrologiciel manuellement"].

Si vous utilisez ONTAP 9.12.1 ou une version antérieure, ou si vous ne l'avez pas link:enable-automatic-updates-task.html["mises à jour automatiques du système"] Activé, vous pouvez mettre à jour manuellement la base de données des fuseaux horaires.  Consultez l'article de la base de connaissances, link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_update_time_zone_information_in_ONTAP_9["Comment mettre à jour les informations de fuseau horaire dans ONTAP 9"^], pour plus de détails.



== Vidéo : fonction de mise à jour automatique du micrologiciel

Jetez un coup d'œil à la fonction de mise à jour automatique du micrologiciel disponible à partir de ONTAP 9.10.1.

video::GoABILT85hQ[youtube,width=848,height=480]