---
permalink: data-protection/configure-custom-snapshot-policies-concept.html 
sidebar: sidebar 
keywords: configure, custom, snapshot, policy 
summary: 'Une règle Snapshot définit la façon dont le système crée des snapshots. La règle indique quand créer des snapshots, combien de copies conserver et comment les nommer. Par exemple, un système peut créer un snapshot chaque jour à 12:10, conserver les deux copies les plus récentes et nommer les copies « Daily.timestamp ».' 
---
= Présentation de la configuration des règles de snapshot personnalisées
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une _règle de snapshot_ définit la façon dont le système crée des snapshots. La règle indique quand créer des snapshots, combien de copies conserver et comment les nommer. Par exemple, un système peut créer un snapshot chaque jour à 12:10, conserver les deux copies les plus récentes et nommer les copies « quotidiennes ».`_timestamp_`.

La règle par défaut d'un volume crée automatiquement des snapshots selon le planning suivant, avec les snapshots les plus anciens supprimés pour faire de la place pour les nouvelles copies :

* Six snapshots par heure au maximum ont pris cinq minutes au-delà de l'heure.
* Un maximum de deux clichés quotidiens pris du lundi au samedi à 10 minutes après minuit.
* Un maximum de deux instantanés hebdomadaires pris chaque dimanche à 15 minutes après minuit.


À moins que vous ne spécifiiez une politique de snapshot lors de la création d'un volume, le volume hérite de la politique de snapshot associée à sa machine virtuelle de stockage (SVM).
