---
permalink: data-protection/configure-destination-volume-data-access-concept.html 
sidebar: sidebar 
keywords: configure, destination, volume, data, access 
summary: 'Une fois le volume de destination inscriptible, vous devez configurer le volume pour l"accès aux données. Les clients NAS, le sous-système NVMe et les hôtes SAN peuvent accéder aux données à partir du volume de destination jusqu"à ce que le volume source soit réactivé.' 
---
= Configurer le volume de destination pour l'accès aux données
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois le volume de destination inscriptible, vous devez configurer le volume pour l'accès aux données. Les clients NAS, le sous-système NVMe etles hôtes SAN peuvent accéder aux données à partir du volume de destination jusqu'à ce que le volume source soit réactivé.

Environnement NAS :

. Monter le volume NAS sur l'espace de noms en utilisant la même Junction path que le volume source a été monté sur dans le SVM source.
. Appliquez les ACL appropriés sur les partages SMB au volume de destination.
. Attribuez les export-policies NFS au volume de destination.
. Appliquer les règles de quota au volume de destination
. Redirection des clients vers le volume de destination.
. Remontez les partages NFS et SMB sur les clients.


Environnement SAN :

. Mappez les LUN du volume sur le groupe initiateur approprié.
. Pour iSCSI, créez des sessions iSCSI des initiateurs hôtes SAN vers les LIF SAN.
. Sur le client SAN, effectuez une nouvelle analyse de stockage pour détecter les LUN connectés.


Pour plus d'informations sur l'environnement NVMe, reportez-vous à la section link:../san-admin/index.html["Administration SAN"].
