---
permalink: data-protection/configure-custom-snapshot-policies-concept.html 
sidebar: sidebar 
keywords: configure, custom, snapshot, policy 
summary: Une règle Snapshot définit la façon dont le système crée les copies Snapshot. La règle indique quand créer des copies Snapshot, le nombre de copies à conserver et comment les nommer. Par exemple, un système peut créer une copie Snapshot tous les jours à 12 h 10, conserver les deux copies les plus récentes et nommer les copies « Daily.timestamp ». 
---
= Présentation de la configuration de règles Snapshot personnalisées
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une règle _Snapshot_ définit la façon dont le système crée des copies Snapshot. La règle indique quand créer des copies Snapshot, le nombre de copies à conserver et comment les nommer. Par exemple, un système peut créer une copie Snapshot tous les jours à 12 h 10, conserver les deux copies les plus récentes et nommer les copies « otidienne.`_timestamp_`.»

La règle par défaut d'un volume crée automatiquement des copies Snapshot selon le calendrier suivant, avec les plus anciennes copies Snapshot supprimées pour laisser de l'espace disponible pour les copies les plus récentes :

* Six copies Snapshot toutes les heures ont été effectuées au maximum cinq minutes au-delà de l'heure.
* Deux copies Snapshot quotidiennes maximum sont effectuées du lundi au samedi 10 minutes après minuit.
* Deux copies Snapshot hebdomadaires maximum sont réalisées tous les dimanches à 15 minutes après minuit.


Sauf si vous spécifiez une règle Snapshot lorsque vous créez un volume, le volume hérite des règles de Snapshot associées à sa machine virtuelle de stockage (SVM).
