---
permalink: data-protection/convert-mode-snapmirror-synchronous-task.html 
sidebar: sidebar 
keywords: convert, mode, snapmirror, synchronous, relationship 
summary: 'Depuis ONTAP 9.5, les relations SnapMirror synchrones sont prises en charge. Vous pouvez convertir le mode d"une relation synchrone SnapMirror de StrictSync en Sync ou vice versa.' 
---
= Convertir le mode d'une relation synchrone SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis ONTAP 9.5, les relations SnapMirror synchrones sont prises en charge. Vous pouvez convertir le mode d'une relation synchrone SnapMirror de StrictSync en Sync ou vice versa.

.Description de la tâche
Vous ne pouvez pas modifier la règle d'une relation synchrone SnapMirror pour convertir son mode.

.Étapes
. Depuis le cluster de destination, arrêter la relation synchrone SnapMirror existante :
+
`snapmirror quiesce -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster2::> snapmirror quiesce -destination-path vs1_dr:vol1
----
. Depuis le cluster de destination, supprimer la relation synchrone SnapMirror existante :
+
`snapmirror delete -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster2::> snapmirror delete -destination-path vs1_dr:vol1
----
. Depuis le cluster source, libérer la relation SnapMirror sans supprimer les copies Snapshot courantes :
+
`snapmirror release -relationship-info-only true -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster1::> snapmirror release -relationship-info-only true -destination-path vs1_dr:vol1
----
. Depuis le cluster de destination, créer une relation synchrone SnapMirror en spécifiant le mode de conversion de la relation synchrone SnapMirror :
+
`snapmirror create -source-path vs1:vol1 -destination-path <destination_SVM>:<destination_volume> -policy Sync|StrictSync`

+
[listing]
----
cluster2::> snapmirror create -source-path vs1:vol1 -destination-path vs1_dr:vol1 -policy Sync
----
. Depuis le cluster de destination, resynchroniser la relation SnapMirror :
+
`snapmirror resync -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster2::> snapmirror resync -destination-path vs1_dr:vol1
----

