---
permalink: data-protection/create-snapshot-job-schedule-task.html 
sidebar: sidebar 
keywords: create, snapshot, job, schedule 
summary: 'Une règle Snapshot requiert une planification d"au moins une tâche de copie Snapshot. Vous pouvez utiliser la commande cron create de planification de travaux pour créer une planification de travaux.' 
---
= Créer un planning de travail instantané
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une règle Snapshot requiert une planification d'au moins une tâche de copie Snapshot. Vous pouvez utiliser le `job schedule cron create` commande permettant de créer un programme de travail.

.Description de la tâche
Par défaut, ONTAP forme les noms des copies Snapshot en ajoutant un horodatage au nom du calendrier des travaux.

Si vous spécifiez des valeurs pour le jour du mois et le jour de la semaine, elles sont considérées indépendamment. Par exemple, une planification cron avec la spécification de jour `Friday` et le jour du mois `13` S'étend tous les vendredis et le 13ème jour de chaque mois, pas seulement tous les vendredis du 13ème.

.Étape
. Création d'un programme de travail :
+
`job schedule cron create -name _job_name_ -month month -dayofweek _day_of_week_ -day _day_of_month_ -hour _hour_ -minute _minute_`

+
Pour `-month`, `-dayofweek`, et `-hour`, vous pouvez spécifier `all` pour exécuter le travail chaque mois, jour de la semaine et heure, respectivement.

+
Depuis ONTAP 9.10.1, vous pouvez inclure le vServer dans votre calendrier des tâches :

+
`job schedule cron create -name _job_name_ -vserver _Vserver_name_ -month _month_ -dayofweek _day_of_week_ -day _day_of_month_ -hour _hour_ -minute _minute_`

+
L'exemple suivant crée un programme de travail nommé `myweekly` Le samedi à 3:00 :

+
[listing]
----
cluster1::> job schedule cron create -name myweekly -dayofweek "Saturday" -hour 3 -minute 0
----
+
L'exemple suivant crée un programme nommé `myweeklymulti` ce délai est spécifié pour plusieurs jours, heures et minutes :

+
[listing]
----
job schedule cron create -name myweeklymulti -dayofweek "Monday,Wednesday,Sunday" -hour 3,9,12 -minute 0,20,50
----

