---
permalink: data-protection/custom-vs-default-snapshot-policy-concept.html 
sidebar: sidebar 
keywords: configure, custom, snapshot, policy 
summary: 'Si la politique Snapshot par défaut n"est pas adaptée à un volume, vous pouvez configurer une règle personnalisée modifiant la fréquence, la conservation et le nom des copies Snapshot. Le planning sera dicté principalement par le taux de changement du système de fichiers actif.' 
---
= A quel moment configurer une règle Snapshot personnalisée
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si la politique Snapshot par défaut n'est pas adaptée à un volume, vous pouvez configurer une règle personnalisée modifiant la fréquence, la conservation et le nom des copies Snapshot. Le planning sera dicté principalement par le taux de changement du système de fichiers actif.

Vous pouvez sauvegarder toutes les heures un système de fichiers très utilisé, comme une base de données, et sauvegarder les fichiers rarement utilisés une fois par jour. Même pour une base de données, vous exécutez généralement une sauvegarde complète une ou deux fois par jour, tout en sauvegardant les journaux de transactions toutes les heures.

Les autres facteurs sont l'importance des fichiers pour votre entreprise, votre contrat de niveau de service (SLA), votre objectif de point de récupération (RPO) et votre objectif de délai de restauration (RTO). De manière générale, vous devez conserver autant de copies Snapshot que nécessaire.
