---
permalink: data-protection/delete-svm-replication-relationship-task.html 
sidebar: sidebar 
keywords: delete, svm, replication, relationship 
summary: Vous pouvez utiliser les commandes snapmirror delete et snapmirror release pour supprimer une relation de réplication SVM. Vous pouvez ensuite supprimer manuellement les volumes de destination inutiles. 
---
= Supprimer une relation de réplication de SVM ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser les `snapmirror delete` commandes et `snapmirror release` pour supprimer une relation de réplication d'un SVM. Vous pouvez ensuite supprimer manuellement les volumes de destination inutiles. Pour en savoir plus sur les commandes décrites dans cette procédurelink:https://docs.netapp.com/us-en/ontap-cli/["Référence de commande ONTAP"^], reportez-vous à la .

.Description de la tâche
La `snapmirror release` commande supprime tous les snapshots créés par SnapMirror de la source. Vous pouvez utiliser `-relationship-info-only` l'option pour conserver les instantanés.

.Étapes
. Lancer la commande suivante depuis le SVM de destination ou le cluster de destination pour faire un break de la relation de réplication :
+
`snapmirror break -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
Vous devez entrer deux-points (:) après le nom de SVM dans la `-source-path` et `-destination-path` options. Voir l'exemple ci-dessous.

====
+
L'exemple suivant rompt la relation entre la SVM source `svm1` Et le SVM de destination `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm1: -destination-path svm_backup:
----
+
Pour en savoir plus, `snapmirror break` consultez le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-break.html["Référence de commande ONTAP"^].

. Lancer la commande suivante depuis le SVM de destination ou le cluster de destination pour supprimer la relation de réplication :
+
`snapmirror delete -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
Vous devez entrer deux-points (:) après le nom de SVM dans la `-source-path` et `-destination-path` options. Voir l'exemple ci-dessous.

====
+
L'exemple suivant supprime la relation entre la SVM source `svm1` Et le SVM de destination `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror delete -source-path svm1: -destination-path svm_backup:
----
+
Pour en savoir plus, `snapmirror delete` consultez le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["Référence de commande ONTAP"^].

. Lancer la commande suivante depuis le cluster source ou le SVM source pour libérer les informations relatives aux relations de réplication du SVM source :
+
`snapmirror release -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
Vous devez entrer deux-points (:) après le nom de SVM dans la `-source-path` et `-destination-path` options. Voir l'exemple ci-dessous.

====
+
L'exemple suivant publie des informations pour la relation de réplication spécifiée à partir du SVM source `svm1`:

+
[listing]
----
cluster_src::> snapmirror release -source-path svm1: -destination-path svm_backup:
----
+
Pour en savoir plus, `snapmirror release` consultez le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-release.html["Référence de commande ONTAP"^].


