---
permalink: data-protection/delete-volume-replication-relationship-task.html 
sidebar: sidebar 
keywords: delete, volume, replication, relationship, replicate, synchronous, snapmirror, quiese, pause 
summary: Vous pouvez utiliser les commandes snapmirror delete et snapmirror release pour supprimer une relation de réplication de volume. Vous pouvez ensuite supprimer manuellement les volumes de destination inutiles. 
---
= Supprime une relation de réplication de volume ONTAP SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser les `snapmirror delete` commandes et `snapmirror release` pour supprimer une relation de réplication de volume. Vous pouvez ensuite supprimer manuellement les volumes de destination inutiles.

.Description de la tâche
La `snapmirror release` commande supprime tous les snapshots créés par SnapMirror de la source. Vous pouvez utiliser `-relationship-info-only` l'option pour conserver les instantanés.

.Étapes
. Arrêter la relation de réplication :
+
`snapmirror quiesce -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
[listing]
----
cluster_dst::> snapmirror quiesce -destination-path svm_backup:volA_dst
----
+
Pour en savoir plus, `snapmirror quiesce` consultez le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["Référence de commande ONTAP"^].

. (Facultatif) si vous souhaitez que le volume de destination soit un volume de lecture/écriture, romprez la relation de réplication. Vous pouvez ignorer cette étape si vous prévoyez de supprimer le volume de destination ou si vous n'avez pas besoin d'un volume en lecture/écriture :
+
`snapmirror break -source-path <SVM:volume>|<cluster://SVM/volume>, …​ -destination-path <SVM:volume>|<cluster://SVM/volume>, …​`

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm1:volA -destination-path svm_backup:volA_dst
----
+
Pour en savoir plus, `snapmirror break` consultez le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-break.html["Référence de commande ONTAP"^].

. Supprimez la relation de réplication :
+
`snapmirror delete -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ...`

+
[NOTE]
====
On doit exécuter cette commande depuis le cluster de destination ou le SVM de destination.

====
+
L'exemple suivant supprime la relation entre le volume source `volA` marche `svm1` et le volume de destination `volA_dst` marche `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror delete -source-path svm1:volA -destination-path svm_backup:volA_dst
----
+
Pour en savoir plus, `snapmirror delete` consultez le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["Référence de commande ONTAP"^].

. Libérer les informations de relation de réplication depuis le SVM source :
+
`snapmirror release -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ...`

+
[NOTE]
====
Vous devez exécuter cette commande à partir du cluster source ou du SVM source.

====
+
L'exemple suivant publie des informations pour la relation de réplication spécifiée à partir du SVM source `svm1`:

+
[listing]
----
cluster_src::> snapmirror release -source-path svm1:volA -destination-path svm_backup:volA_dst
----
+
Pour en savoir plus, `snapmirror release` consultez le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-release.html["Référence de commande ONTAP"^].


