---
permalink: data-protection/initialize-replication-relationship-task.html 
sidebar: sidebar 
keywords: initialize, replication, relationship, snapmirror, snap mirror, synchronous, transfer, snapshot copy, 
summary: 'Pour tous les types de relation, l"initialisation effectue un transfert de base : elle crée un snapshot du volume source, puis transfère cette copie et tous les blocs de données qu"elle référence au volume de destination. Dans le cas contraire, le contenu du transfert dépend de la police.' 
---
= Initialiser une relation de réplication avec ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour tous les types de relation, l'initialisation effectue un _transfert de base_ : elle crée un instantané du volume source, puis transfère cette copie et tous les blocs de données qu'elle référence au volume de destination. Dans le cas contraire, le contenu du transfert dépend de la police.

.Ce dont vous avez besoin
Les clusters source et de destination et les SVM doivent être associés.

link:../peering/index.html["Cluster et SVM peering"]

.Description de la tâche
L'initialisation peut prendre beaucoup de temps. Vous pouvez exécuter le transfert de base en dehors des heures creuses.

Depuis ONTAP 9.5, les relations SnapMirror synchrones sont prises en charge.

.Étape
. Initialiser une relation de réplication :
+
`snapmirror initialize -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ...`

+
Pour en savoir plus, `snapmirror initialize` consultez le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["Référence de commande ONTAP"^].

+
[NOTE]
====
On doit exécuter cette commande depuis le SVM de destination ou le cluster destination.

====
+
L'exemple suivant initialise la relation entre le volume source `volA` marche `svm1` et le volume de destination `volA_dst` marche `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror initialize -source-path svm1:volA -destination-path svm_backup:volA_dst
----

