---
permalink: data-protection/limitations-mirror-relationships-concept.html 
sidebar: sidebar 
keywords: snapmirror, limitations 
summary: Avant de créer une relation de protection des données, il est recommandé de connaître les limites élémentaires de SnapMirror. 
---
= SnapMirror limitations
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de créer une relation de protection des données, il est recommandé de connaître les limites élémentaires de SnapMirror.

* Un volume de destination ne peut avoir qu'un seul volume source.
+
[NOTE]
====
Un volume source peut avoir plusieurs volumes de destination. Le volume de destination peut être le volume source pour tout type de relation de réplication SnapMirror.

====
* Vous pouvez ventiler jusqu'à huit volumes de destination depuis un volume source unique.
* Vous ne pouvez pas restaurer de fichiers vers la destination d'une relation SnapMirror DR.
* Les volumes SnapVault source ou de destination ne peuvent pas être de 32 bits.
* Le volume source d'une relation SnapVault ne doit pas être un volume FlexClone.
+
[NOTE]
====
La relation fonctionnera, mais l'efficacité offerte par les volumes FlexClone ne sera pas préservée.

====

