---
permalink: data-protection/make-destination-volume-writeable-task.html 
sidebar: sidebar 
keywords: destination, volume, writeable, write, serve data, snapmirror, quiesce, pause, abort, transfers 
summary: Vous devez rendre le volume de destination inscriptible avant de pouvoir transmettre les données du volume à des clients. Vous pouvez utiliser la commande snapmirror quiesce pour arrêter les transferts planifiés vers la destination, la commande snapmirror abort pour arrêter les transferts en cours et la commande snapmirror break pour rendre la destination inscriptible. 
---
= Rendre le volume de destination inscriptible
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez rendre le volume de destination inscriptible avant de pouvoir transmettre les données du volume à des clients. Vous pouvez utiliser le `snapmirror quiesce` commande pour arrêter les transferts programmés vers la destination, le `snapmirror abort` pour arrêter les transferts en cours, et le `snapmirror break` commande permettant de rendre la destination inscriptible.

Cette tâche doit être effectuée depuis le SVM de destination ou le cluster de destination.

.Étapes
. Arrêter les transferts programmés vers la destination :
+
`snapmirror quiesce -source-path _SVM:volume|cluster://SVM/volume_, ... -destination-path _SVM:volume|cluster://SVM/volume_, ...`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant arrête les transferts programmés entre le volume source `volA` marche `svm1` et le volume de destination `volA_dst` marche `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror quiesce -source-path svm1:volA -destination-path svm_backup:volA_dst
----
. Arrêter les transferts en cours vers la destination :
+
`snapmirror abort -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
[NOTE]
====
Cette étape n'est pas requise pour les relations SnapMirror synchrone (prise en charge à partir de ONTAP 9.5).

====
+
L'exemple suivant arrête les transferts en cours entre le volume source `volA` marche `svm1` et le volume de destination `volA_dst` marche `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror abort -source-path svm1:volA -destination-path svm_backup:volA_dst
----
. Interrompre la relation SnapMirror DR :
+
`snapmirror break -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant rompt la relation entre le volume source `volA` marche `svm1` et le volume de destination `volA_dst` marche `svm_backup` et le volume de destination `volA_dst` marche `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm1:volA -destination-path svm_backup:volA_dst
----




== D'autres façons de le faire dans ONTAP

[cols="2"]
|===
| Pour effectuer ces tâches avec... | Voir ce contenu... 


| System Manager redessiné (disponible avec ONTAP 9.7 et versions ultérieures) | link:https://docs.netapp.com/us-en/ontap/task_dp_serve_data_from_destination.html["Service des données à partir d'une destination SnapMirror"^] 


| System Manager Classic (disponible avec ONTAP 9.7 et versions antérieures) | link:https://docs.netapp.com/us-en/ontap-sm-classic/volume-disaster-recovery/index.html["Présentation de la reprise après incident de volume"^] 
|===