---
permalink: data-protection/manage-local-snapshot-copies-concept.html 
sidebar: sidebar 
keywords: manage, local, snapshot, copy, storage, performance overhead, copies, image, restore, flexvol, flexgroup 
summary: 'Un snapshot est une image instantanée en lecture seule d"un volume. L"image consomme un espace de stockage minimal et présente un impact négligeable sur les performances, car elle n"enregistre que les modifications apportées aux fichiers depuis le dernier snapshot.' 
---
= En savoir plus sur la gestion des snapshots ONTAP locaux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un _snapshot_ est une image instantanée en lecture seule d'un volume. L'image consomme un espace de stockage minimal et présente un impact négligeable sur les performances, car elle n'enregistre que les modifications apportées aux fichiers depuis le dernier snapshot.

Vous pouvez utiliser un snapshot pour restaurer l'intégralité du contenu d'un volume, ou pour restaurer des fichiers individuels ou des LUN. Les snapshots sont stockés dans le répertoire du volume. `.snapshot`

Dans ONTAP 9.4 et versions ultérieures, un FlexVol volume peut contenir jusqu'à 1 023 instantanés.  Dans ONTAP 9.3 et versions antérieures, un volume peut contenir jusqu'à 255 snapshots.

[NOTE]
====
À partir de ONTAP 9.8, les volumes FlexGroup peuvent contenir 1023 snapshots. Pour plus d'informations, voir link:../flexgroup/protect-snapshot-copies-task.html["Protection des volumes FlexGroup à l'aide de copies Snapshot"].

====
Il existe plusieurs types courants d'instantanés ONTAP :

* `sched_created`: Instantanés générés automatiquement par une politique d'instantanés ONTAP, basée sur des calendriers prédéfinis (par exemple, horaires, quotidiens, hebdomadaires ou mensuels).
* `sm_created`: Instantanés créés automatiquement à la suite de transferts de réplication SnapMirror (opérations de mise à jour ou d'initialisation).
* `application_created`: Instantanés générés par un logiciel d'intégration au niveau de l'hôte ou de la base de données comme SnapCenter ou SnapDrive.
* `user_created`: Instantanés déclenchés manuellement par un administrateur à l'aide de l'interface de ligne de commande ONTAP ou de System Manager.
* `sv_created`: Instantanés créés automatiquement lors des opérations de cluster, telles que Storage Virtual Machine (SVM) DR ou des flux de travail de protection spécifiques.
* `luns_created`: Instantanés créés pour sauvegarder ou capturer l'état des clones de LUN ou d'espace de noms NVMe.

