---
permalink: data-protection/manage-snapmirror-root-volume-replication-concept.html 
sidebar: sidebar 
keywords: manage, snapmirror, root volume , replication 
summary: 'Chaque SVM d"un environnement NAS possède un espace de noms unique. Le volume root du SVM, contenant le système d"exploitation et les informations associées, est le point d"entrée de la hiérarchie de l"espace de noms. Pour garantir que les données restent accessibles aux clients en cas de panne ou de basculement d"un nœud, vous devez créer une copie miroir de partage de la charge du volume racine du SVM.' 
---
= En savoir plus sur la réplication de volume racine ONTAP SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Chaque SVM d'un environnement NAS possède un espace de noms unique. Le SVM _root volume,_ contenant le système d'exploitation et les informations associées, est le point d'entrée de la hiérarchie de l'espace de noms. Pour garantir que les données restent accessibles aux clients en cas de panne ou de basculement d'un nœud, vous devez créer une copie miroir de partage de la charge du volume racine du SVM.

L'objectif principal des miroirs de partage de charge pour les volumes root des SVM n'est plus de permettre le partage de charge ; ils ont plutôt pour objectif la reprise sur incident.

* Si le volume racine est temporairement indisponible, le miroir de partage de charge permet un accès en lecture seule aux données du volume racine.
* Si le volume racine n'est définitivement pas disponible, vous pouvez promouvoir l'un des volumes de partage de charge pour fournir un accès en écriture aux données du volume racine.

