---
permalink: data-protection/manage-snapmirror-root-volume-replication-concept.html 
sidebar: sidebar 
keywords: manage, snapmirror, root volume , replication 
summary: 'Dans un environnement NAS, chaque SVM possède un espace de noms unique. Le volume racine de la SVM constitue le point d"entrée de cette hiérarchie d"espace de noms. Pour les clusters composés d"au moins deux paires haute disponibilité, vous devriez envisager des miroirs à répartition de charge (LSM) du volume racine de la SVM afin de garantir que l"espace de noms reste accessible aux clients dans le cas où les deux nœuds d"une paire haute disponibilité échouent.' 
---
= En savoir plus sur la réplication de volume racine ONTAP SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dans un environnement NAS, chaque SVM possède un espace de noms unique. Le volume racine de la SVM constitue le point d'entrée de cette hiérarchie d'espace de noms. Pour les clusters composés de deux paires haute disponibilité ou plus, vous devriez envisager des miroirs à répartition de charge (LSM) du volume racine de la SVM afin de garantir que l'espace de noms reste accessible aux clients dans le cas où les deux nœuds d'une paire haute disponibilité échouent. Les miroirs à répartition de charge ne conviennent pas aux clusters composés d'une seule paire haute disponibilité et ne conviennent pas à un environnement MetroCluster.

* À partir de ONTAP 9.1, les miroirs à partage de charge sont obsolètes pour les volumes de données et ne sont pris en charge que pour les volumes racine SVM.
* SnapMirror load-sharing mirrors ne prennent en charge que les clients NAS (CIFS/NFSv3). Les miroirs à répartition de charge ne prennent pas en charge les clients NFSv4 ni les connexions aux protocoles clients SAN (FC, FCoE ou iSCSI). Cependant, NFSv4 et les miroirs à répartition de charge peuvent coexister dans le même environnement.

