---
permalink: data-protection/path-name-pattern-matching-concept.html 
sidebar: sidebar 
keywords: path, pattern, matching 
summary: Vous pouvez utiliser la correspondance de modèles pour spécifier les chemins source et de destination dans les commandes snapmirror. 
---
= En savoir plus sur la correspondance des motifs de nom de chemin dans les commandes ONTAP SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser la correspondance de motif pour spécifier les chemins source et de destination dans `snapmirror` commandes.

 `snapmirror` les commandes utilisent des noms de chemin complets au format suivant : `vserver:volume`. Vous pouvez abréger le nom du chemin en n'entrant pas le nom de la SVM. Si vous le faites, le `snapmirror` Commande suppose le contexte SVM local de l'utilisateur.

En supposant que la SVM est appelée « vserver1 » et que le volume est appelé « vol1 », le chemin d'accès complet est `vserver1:vol1`.

Vous pouvez utiliser l'astérisque (*) dans les chemins comme caractère générique pour sélectionner des noms de chemin complets et correspondants. Le tableau suivant fournit des exemples d'utilisation du caractère générique pour sélectionner une plage de volumes.

[cols="2*"]
|===


 a| 
`*`
 a| 
Correspond à tous les chemins.



 a| 
`vs*`
 a| 
Correspondance de tous les SVM et volumes avec des noms de SVM commençant par `vs`.



 a| 
`*:*src*`
 a| 
Correspond à tous les SVM avec des noms de volume contenant le `src` texte.



 a| 
`*:vol*`
 a| 
Correspond à tous les SVM avec des noms de volume commençant par `vol`.

|===
[listing]
----
vs1::> snapmirror show -destination-path *:*dest*
                                                                                Progress
Source              Destination  Mirror        Relationship  Total              Last
Path          Type  Path         State         Status        Progress   Healthy Updated
------------- ---- ------------ ------------- -------------- ---------- ------- --------
vs1:sm_src2
              DP   vs2:sm_dest1
                                Snapmirrored  Idle           -          true    -
----
Pour en savoir plus sur les commandes décrites dans cette procédurelink:https://docs.netapp.com/us-en/ontap-cli/["Référence de commande ONTAP"^], reportez-vous à la .
