---
permalink: data-protection/preserve-snapshot-copy-primary-source-volume-task.html 
sidebar: sidebar 
keywords: ensure, snapshot, copy, mirror-vault, deployment 
summary: 'Vous pouvez utiliser la commande snapmirror snapshot-owner create pour conserver une copie Snapshot nommée sur le système secondaire, dans un déploiement miroir-vault. Cela garantit qu"il existe une copie Snapshot commune pour la mise à jour de la relation de coffre-fort.' 
---
= Nous garantissons une copie Snapshot commune dans un déploiement de copie miroir-coffre avec ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `snapmirror snapshot-owner create` Commande permettant de conserver une copie Snapshot étiquetée sur le système secondaire dans un déploiement mis en miroir-vault. Cela garantit qu'il existe une copie Snapshot commune pour la mise à jour de la relation de coffre-fort.

.Description de la tâche
Si vous utilisez une combinaison de mirror-vault Fan-Out ou de cascade, sachez que les mises à jour échoueront si une copie Snapshot commune n'existe pas sur les volumes source et de destination.

Ce problème ne se pose jamais pour la relation de miroir dans un déploiement de type « fan-out » (fan-out) à base de miroir ou en cascade, car SnapMirror crée toujours une copie Snapshot du volume source avant d'effectuer la mise à jour.

Il peut en revanche s'agir d'un problème pour la relation de copie à distance, puisque SnapMirror ne crée pas de copie Snapshot du volume source lors de la mise à jour d'une relation de copie à distance. Vous devez utiliser le `snapmirror snapshot-owner create` Pour s'assurer qu'il existe au moins une copie Snapshot commune à la fois sur la source et la destination de la relation de coffre-fort.

.Étapes
. Sur le volume source, attribuez un propriétaire à la copie Snapshot nommée que vous souhaitez conserver :
+
`snapmirror snapshot-owner create -vserver <SVM> -volume <volume> -snapshot <snapshot> -owner <owner>`

+
L'exemple suivant affecte `ApplicationA` en tant que propriétaire du `snap1` Copie Snapshot :

+
[listing]
----
clust1::> snapmirror snapshot-owner create -vserver vs1 -volume vol1
-snapshot snap1 -owner ApplicationA
----
. Mettez à jour la relation de miroir, comme décrit dans link:update-replication-relationship-manual-task.html["Mise à jour manuelle d'une relation de réplication"].
+
Vous pouvez également attendre la mise à jour planifiée de la relation miroir.

. Transférer la copie Snapshot étiquetée vers la destination du coffre-fort :
+
`snapmirror update -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ... -source-snapshot snapshot`

+
Pour en savoir plus, `snapmirror update` consultez le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["Référence de commande ONTAP"^].

+
L'exemple suivant transfère le `snap1` La copie Snapshot::
+
--
[listing]
----
clust1::> snapmirror update -vserver vs1 -volume vol1
-source-snapshot snap1
----
La copie Snapshot nommée sera conservée lors de la mise à jour de la relation de coffre-fort.

--


. Sur le volume source, supprimez le propriétaire de la copie Snapshot nommée :
+
`snapmirror snapshot-owner delete -vserver _SVM_ -volume _volume_ -snapshot _snapshot_ -owner _owner_`

+
Les exemples suivants sont supprimés `ApplicationA` en tant que propriétaire du `snap1` Copie Snapshot :

+
[listing]
----
clust1::> snapmirror snapshot-owner delete -vserver vs1 -volume vol1
-snapshot snap1 -owner ApplicationA
----

