---
permalink: data-protection/preserve-snapshot-copy-primary-source-volume-task.html 
sidebar: sidebar 
keywords: ensure, snapshot, copy, mirror-vault, deployment 
summary: 'Vous pouvez utiliser la commande SnapMirror snapshot-owner create pour conserver un snapshot étiqueté sur le secondaire dans un déploiement de coffre-fort en miroir. Cela permet de s"assurer qu"un snapshot commun existe pour la mise à jour de la relation de coffre-fort.' 
---
= Garantir un snapshot commun dans un déploiement de miroir-coffre ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser `snapmirror snapshot-owner create` la commande pour conserver un snapshot étiqueté sur le secondaire dans un déploiement de coffre-fort en miroir. Cela permet de s'assurer qu'un snapshot commun existe pour la mise à jour de la relation de coffre-fort. Pour en savoir plus, `snapmirror snapshot-owner create` consultez le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-snapshot-owner-create.html["Référence de commande ONTAP"^].

.Description de la tâche
Si vous utilisez une combinaison de fan-out de miroir-coffre-fort ou de déploiement en cascade, gardez à l'esprit que les mises à jour échoueront si un snapshot commun n'existe pas sur les volumes source et de destination.

Il ne s'agit jamais d'un problème pour la relation de miroir dans un déploiement en cascade ou avec « fan-out » de miroir-coffre-fort, puisque SnapMirror crée toujours un snapshot du volume source avant d'effectuer la mise à jour.

Il peut cependant s'agir d'un problème pour la relation de copie en coffre-fort, car SnapMirror ne crée pas de snapshot du volume source lors de la mise à jour d'une relation de copie en coffre-fort. Vous devez utiliser `snapmirror snapshot-owner create` pour vous assurer qu'il existe au moins un snapshot commun sur la source et la destination de la relation de coffre-fort. link:supported-deployment-config-concept.html["En savoir plus sur les déploiements « Fan-Out » et « Cascade » de la protection des données"].

.Étapes
. Sur le volume source, attribuez un propriétaire à l'instantané étiqueté que vous souhaitez conserver :
+
`snapmirror snapshot-owner create -vserver <SVM> -volume <volume> -snapshot <snapshot> -owner <owner>`

+
L'exemple suivant illustre `ApplicationA` le rôle de propriétaire du `snap1` snapshot :

+
[listing]
----
clust1::> snapmirror snapshot-owner create -vserver vs1 -volume vol1
-snapshot snap1 -owner ApplicationA
----
. Mettez à jour la relation de miroir, comme décrit dans link:update-replication-relationship-manual-task.html["Mise à jour manuelle d'une relation de réplication"].
+
Vous pouvez également attendre la mise à jour planifiée de la relation miroir.

. Transférer l'instantané étiqueté vers la destination du coffre-fort :
+
`snapmirror update -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ... -source-snapshot snapshot`

+
Pour en savoir plus, `snapmirror update` consultez le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["Référence de commande ONTAP"^].

+
L'exemple suivant transfère le `snap1` snapshot::
+
--
[listing]
----
clust1::> snapmirror update -vserver vs1 -volume vol1
-source-snapshot snap1
----
L'instantané marqué sera conservé lorsque la relation de coffre-fort sera mise à jour.

--


. Sur le volume source, supprimez le propriétaire de l'instantané marqué :
+
`snapmirror snapshot-owner delete -vserver _SVM_ -volume _volume_ -snapshot _snapshot_ -owner _owner_`

+
Les exemples suivants sont supprimés `ApplicationA` en tant que propriétaire de l' `snap1`instantané :

+
[listing]
----
clust1::> snapmirror snapshot-owner delete -vserver vs1 -volume vol1
-snapshot snap1 -owner ApplicationA
----
+
Pour en savoir plus, `snapmirror snapshot-owner delete` consultez le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-snapshot-owner-delete.html["Référence de commande ONTAP"^].


