---
permalink: data-protection/reactivate-original-source-volume-task.html 
sidebar: sidebar 
keywords: reactivate, original, source, volume 
summary: 'Vous pouvez rétablir la relation initiale de protection des données entre les volumes source et destination lorsque vous n"avez plus besoin de transmettre des données depuis la destination.' 
---
= Réactivez le volume source d'origine avec ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez rétablir la relation initiale de protection des données entre les volumes source et destination lorsque vous n'avez plus besoin de transmettre des données depuis la destination.

.Description de la tâche
* La procédure ci-dessous suppose que la ligne de base du volume source d'origine est intacte. Si la base n'est pas intacte, vous devez créer et initialiser la relation entre le volume dont vous accédez aux données et le volume source d'origine avant d'effectuer la procédure.
* La préparation en arrière-plan et la phase d'entreposage des données d'une relation SnapMirror XDP peuvent prendre un certain temps. Il n'est pas rare de voir la relation SnapMirror indiquant l'état « préparation » pour une période prolongée.


.Étapes
. Inverser la relation de protection des données d'origine :
+
`snapmirror resync -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
Pour en savoir plus, `snapmirror resync` consultez le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["Référence de commande ONTAP"^].

+
[NOTE]
====
Vous devez exécuter cette commande à partir du SVM source d'origine ou du cluster source d'origine. Bien que la resynchronisation ne nécessite pas de transfert de base, elle peut prendre du temps. Vous pouvez exécuter la resynchronisation en dehors des heures de pointe. Échec de la commande si une copie Snapshot commune n'existe pas sur la source et la destination. Utiliser `snapmirror initialize` pour réinitialiser la relation.

====
+
L'exemple suivant inverse la relation entre le volume source d'origine, `volA` marche `svm1`et le volume que vous servant de données, `volA_dst` marche `svm_backup`:

+
[listing]
----
cluster_src::> snapmirror resync -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. Lorsque vous êtes prêt à rétablir l'accès aux données à la source d'origine, l'accès au volume de destination d'origine est interrompu. L'une des façons de faire est d'arrêter le SVM de destination d'origine :
+
`vserver stop -vserver _SVM_`

+
Pour en savoir plus, `vserver stop` consultez le link:https://docs.netapp.com/us-en/ontap-cli/vserver-stop.html["Référence de commande ONTAP"^].

+
[NOTE]
====
Vous devez exécuter cette commande à partir du SVM destination d'origine ou du cluster destination d'origine. Cette commande arrête l'accès de l'utilisateur à l'ensemble du SVM de destination d'origine. Vous pouvez arrêter l'accès au volume de destination d'origine à l'aide d'autres méthodes.

====
+
L'exemple suivant arrête le SVM destination original :

+
[listing]
----
cluster_dst::> vserver stop svm_backup
----
. Mettre à jour la relation inversée :
+
`snapmirror update -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
Pour en savoir plus, `snapmirror update` consultez le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["Référence de commande ONTAP"^].

+
[NOTE]
====
Vous devez exécuter cette commande à partir du SVM source d'origine ou du cluster source d'origine.

====
+
L'exemple suivant met à jour la relation entre le volume que vous servant des données, `volA_dst` marche `svm_backup`, et le volume source d'origine, `volA` marche `svm1`:

+
[listing]
----
cluster_src::> snapmirror update -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. Depuis le SVM source d'origine ou le cluster source d'origine, arrêter les transferts programmés pour la relation inversée :
+
`snapmirror quiesce -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
Pour en savoir plus, `snapmirror quiesce` consultez le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["Référence de commande ONTAP"^].

+
[NOTE]
====
Vous devez exécuter cette commande à partir du SVM source d'origine ou du cluster source d'origine.

====
+
L'exemple suivant illustre la fin des transferts programmés entre le volume de destination d'origine. `volA_dst` marche `svm_backup`, et le volume source d'origine, `volA` marche `svm1`:

+
[listing]
----
cluster_src::> snapmirror quiesce -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. Lorsque la mise à jour finale est terminée et que la relation indique « suspendu » pour l'état de la relation, exécutez la commande suivante à partir du SVM source d'origine ou du cluster source d'origine pour interrompre la relation inversée :
+
`snapmirror break -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
Pour en savoir plus, `snapmirror break` consultez le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-break.html["Référence de commande ONTAP"^].

+
[NOTE]
====
Vous devez exécuter cette commande à partir du SVM source d'origine ou du cluster source.

====
+
L'exemple suivant rompt la relation entre le volume de destination d'origine, `volA_dst` marche `svm_backup`, et le volume source d'origine, `volA` marche `svm1`:

+
[listing]
----
cluster_scr::> snapmirror break -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. Depuis le SVM source d'origine ou le cluster source d'origine, supprimer la relation de protection des données inversée :
+
`snapmirror delete -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
Pour en savoir plus, `snapmirror delete` consultez le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["Référence de commande ONTAP"^].

+
[NOTE]
====
Vous devez exécuter cette commande à partir du SVM source d'origine ou du cluster source d'origine.

====
+
L'exemple suivant supprime la relation inversée entre le volume source d'origine, `volA` marche `svm1`et le volume que vous servant de données, `volA_dst` marche `svm_backup`:

+
[listing]
----
cluster_src::> snapmirror delete -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. Libérer la relation inverse de la SVM destination d'origine ou du cluster destination d'origine.
+
`snapmirror release -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
[NOTE]
====
Vous devez exécuter cette commande à partir du SVM destination d'origine ou du cluster destination d'origine.

====
+
L'exemple suivant libère la relation inversée entre le volume de destination d'origine, `volA_dst` marche `svm_backup`, et le volume source d'origine, `volA` marche `svm1`:

+
[listing]
----
cluster_dst::> snapmirror release -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. Rétablir la relation de protection des données d'origine à partir de la destination d'origine :
+
`snapmirror resync -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
Pour en savoir plus, `snapmirror resync` consultez le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["Référence de commande ONTAP"^].

+
L'exemple suivant rétablit la relation entre le volume source d'origine, `volA` marche `svm1`, et le volume de destination d'origine, `volA_dst` marche `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1:volA -destination-path svm_backup:volA_dst
----
. Si besoin démarrer le SVM de destination d'origine :
+
`vserver start -vserver _SVM_`

+
Pour en savoir plus, `vserver start` consultez le link:https://docs.netapp.com/us-en/ontap-cli/vserver-start.html["Référence de commande ONTAP"^].

+
L'exemple suivant démarre le SVM de destination d'origine :

+
[listing]
----
cluster_dst::> vserver start svm_backup
----


.Une fois que vous avez terminé
Utiliser `snapmirror show` la commande pour vérifier que la relation SnapMirror a été créée. Pour en savoir plus, `snapmirror show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["Référence de commande ONTAP"^].
