---
permalink: data-protection/reactivate-original-source-volume-task.html 
sidebar: sidebar 
keywords: reactivate, original, source, volume 
summary: 'Vous pouvez rétablir la relation initiale de protection des données entre les volumes source et destination lorsque vous n"avez plus besoin de transmettre des données depuis la destination.' 
---
= Réactiver le volume source d'origine
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez rétablir la relation initiale de protection des données entre les volumes source et destination lorsque vous n'avez plus besoin de transmettre des données depuis la destination.

.Description de la tâche
* La procédure ci-dessous suppose que la ligne de base du volume source d'origine est intacte. Si la base n'est pas intacte, vous devez créer et initialiser la relation entre le volume dont vous accédez aux données et le volume source d'origine avant d'effectuer la procédure.
* La préparation en arrière-plan et la phase d'entreposage des données d'une relation SnapMirror XDP peuvent prendre un certain temps. Il n'est pas rare de voir la relation SnapMirror indiquant l'état « préparation » pour une période prolongée.


.Étapes
. Supprimez la relation de protection des données d'origine :
+
`snapmirror delete -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
On doit exécuter cette commande depuis le SVM de destination ou le cluster destination.

+
L'exemple suivant supprime la relation entre le volume source d'origine, `volA` marche `svm1`et le volume que vous servant de données, `volA_dst` marche `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror delete -source-path svm1:volA -destination-path svm_backup:volA_dst
----
. Inverser la relation de protection des données d'origine :
+
`snapmirror resync -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
On doit exécuter cette commande depuis le SVM de destination ou le cluster destination. Bien que la resynchronisation ne nécessite pas de transfert de base, elle peut prendre du temps. Vous pouvez exécuter la resynchronisation en dehors des heures de pointe.

+
L'exemple suivant inverse la relation entre le volume source d'origine, `volA` marche `svm1`et le volume que vous servant de données, `volA_dst` marche `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. Arrêter le SVM source pour la relation inversée :
+
`vserver stop -vserver _SVM_`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant arrête le SVM source pour la relation inversée :

+
[listing]
----
cluster_src::> vserver stop svm_backup
----
. Mettre à jour la relation inversée :
+
`snapmirror update -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
[NOTE]
====
Vous devez exécuter cette commande à partir du SVM de destination ou du cluster de destination.la commande échoue si une copie Snapshot commune n'existe pas sur la source et la destination. Utiliser `snapmirror initialize` pour réinitialiser la relation.

====
+
L'exemple suivant met à jour la relation entre le volume que vous servant des données, `volA_dst` marche `svm_backup`, et le volume source d'origine, `volA` marche `svm1`:

+
[listing]
----
cluster_dst::> snapmirror update -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. Arrêter les transferts programmés pour la relation inversée :
+
`snapmirror quiesce -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
[NOTE]
====
On doit exécuter cette commande depuis le SVM de destination ou le cluster destination.

====
+
L'exemple suivant arrête les transferts programmés entre le volume à partir de où vous accédez les données, `volA_dst` marche `svm_backup`, et le volume source d'origine, `volA` marche `svm1`:

+
[listing]
----
cluster_dst::> snapmirror quiesce -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. Arrêter les transferts en cours pour la relation inversée :
+
`snapmirror abort -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
[NOTE]
====
On doit exécuter cette commande depuis le SVM de destination ou le cluster destination.

====
+
L'exemple suivant arrête les transferts en cours entre le volume dont vous accédez à des données, `volA_dst` marche `svm_backup`, et le volume source d'origine, `volA` marche `svm1`:

+
[listing]
----
cluster_dst::> snapmirror abort -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. Rompez la relation inversée :
+
`snapmirror break -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
[NOTE]
====
On doit exécuter cette commande depuis le SVM de destination ou le cluster destination.

====
+
L'exemple suivant rompt la relation entre le volume dont vous servant des données, `volA_dst` marche `svm_backup`, et le volume source d'origine, `volA` marche `svm1`:

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. Démarrer le SVM source d'origine :
+
`vserver start -vserver _SVM_`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant démarre le SVM source d'origine :

+
[listing]
----
cluster_dst::> vserver start svm1
----
. Supprimez la relation de protection des données inversée :
+
`snapmirror delete -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
On doit exécuter cette commande depuis le SVM source ou le cluster source pour la relation inversée.

+
L'exemple suivant supprime la relation inversée entre le volume source d'origine, `volA` marche `svm1`et le volume que vous servant de données, `volA_dst` marche `svm_backup`:

+
[listing]
----
cluster_src::> snapmirror delete -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. Rétablir la relation initiale de protection des données :
+
`snapmirror resync -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant rétablit la relation entre le volume source d'origine, `volA` marche `svm1`, et le volume de destination d'origine, `volA_dst` marche `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1:volA -destination-path svm_backup:volA_dst
----


.Une fois que vous avez terminé
Utilisez le `snapmirror show` Commande permettant de vérifier que la relation SnapMirror a été créée. Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.
