---
permalink: data-protection/restore-single-file-snapshot-task.html 
sidebar: sidebar 
keywords: restore, single file, snapshot copy 
summary: 'Vous pouvez utiliser la commande volume snapshot restore-file pour restaurer un fichier ou une LUN unique à partir d"un snapshot. Vous pouvez restaurer le fichier à un autre emplacement dans le volume en lecture-écriture parent si vous ne souhaitez pas remplacer un fichier existant.' 
---
= Restaurez un fichier unique à partir d'un snapshot ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser `volume snapshot restore-file` la commande pour restaurer un fichier ou une LUN unique à partir d'un snapshot. Vous pouvez restaurer le fichier à un autre emplacement dans le volume en lecture-écriture parent si vous ne souhaitez pas remplacer un fichier existant.

.Description de la tâche
Si vous restaurez une LUN existante, un clone de LUN est créé et sauvegardé sous forme de snapshot. Pendant l'opération de restauration, vous pouvez lire et écrire sur la LUN.

Par défaut, les fichiers contenant des flux sont restaurés.

.Étapes
. Lister les snapshots dans un volume :
+
`volume snapshot show -vserver _SVM_ -volume _volume_`

+
Pour en savoir plus, `volume snapshot show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-show.html["Référence de commande ONTAP"^].

+
L'exemple suivant montre les snapshots dans `vol1`:

+
[listing]
----

clus1::> volume snapshot show -vserver vs1 -volume vol1

Vserver Volume Snapshot                State    Size  Total% Used%
------- ------ ---------- ----------- ------   -----  ------ -----
vs1	    vol1   hourly.2013-01-25_0005  valid   224KB     0%    0%
               daily.2013-01-25_0010   valid   92KB      0%    0%
               hourly.2013-01-25_0105  valid   228KB     0%    0%
               hourly.2013-01-25_0205  valid   236KB     0%    0%
               hourly.2013-01-25_0305  valid   244KB     0%    0%
               hourly.2013-01-25_0405  valid   244KB     0%    0%
               hourly.2013-01-25_0505  valid   244KB     0%    0%

7 entries were displayed.
----
. Restaurer un fichier à partir d'un snapshot :
+
`volume snapshot restore-file -vserver _SVM_ -volume _volume_ -snapshot _snapshot_ -path _file_path_ -restore-path _destination_path_`

+
Pour en savoir plus, `volume snapshot restore-file` consultez le link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-restore-file.html["Référence de commande ONTAP"^].

+
L'exemple suivant restaure le fichier `myfile.txt`:

+
[listing]
----
cluster1::> volume snapshot restore-file -vserver vs0 -volume vol1 -snapshot daily.2013-01-25_0010 -path /myfile.txt
----

