---
permalink: data-protection/restore-single-file-snapshot-task.html 
sidebar: sidebar 
keywords: restore, single file, snapshot copy 
summary: 'Vous pouvez utiliser la commande volume snapshot restore-file pour restaurer un fichier ou une LUN unique à partir d"une copie Snapshot. Vous pouvez restaurer le fichier à un autre emplacement dans le volume en lecture-écriture parent si vous ne souhaitez pas remplacer un fichier existant.' 
---
= Restaurez un seul fichier à partir d'une copie Snapshot
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `volume snapshot restore-file` Commande permettant de restaurer un fichier ou une LUN à partir d'une copie Snapshot. Vous pouvez restaurer le fichier à un autre emplacement dans le volume en lecture-écriture parent si vous ne souhaitez pas remplacer un fichier existant.

.Description de la tâche
Si vous restaurez une LUN existante, un clone de LUN est créé et sauvegardé sous le format d'une copie Snapshot. Durant l'opération de restauration, vous pouvez lire et écrire à partir de la LUN.

Par défaut, les fichiers contenant des flux sont restaurés.

.Étapes
. Lister les copies Snapshot dans un volume :
+
`volume snapshot show -vserver _SVM_ -volume _volume_`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant montre les copies Snapshot dans `vol1`:

+
[listing]
----

clus1::> volume snapshot show -vserver vs1 -volume vol1

Vserver Volume Snapshot                State    Size  Total% Used%
------- ------ ---------- ----------- ------   -----  ------ -----
vs1	 vol1   hourly.2013-01-25_0005  valid   224KB     0%    0%
               daily.2013-01-25_0010   valid   92KB      0%    0%
               hourly.2013-01-25_0105  valid   228KB     0%    0%
               hourly.2013-01-25_0205  valid   236KB     0%    0%
               hourly.2013-01-25_0305  valid   244KB     0%    0%
               hourly.2013-01-25_0405  valid   244KB     0%    0%
               hourly.2013-01-25_0505  valid   244KB     0%    0%

7 entries were displayed.
----
. Restaurer un fichier à partir d'une copie Snapshot :
+
`volume snapshot restore-file -vserver _SVM_ -volume _volume_ -snapshot _snapshot_ -path _file_path_ -restore-path _destination_path_`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
L'exemple suivant restaure le fichier `myfile.txt`:

+
[listing]
----
cluster1::> volume snapshot restore-file -vserver vs0 -volume vol1 -snapshot daily.2013-01-25_0010 -path /myfile.txt
----

