---
permalink: data-protection/resynchronize-relationship-task.html 
sidebar: sidebar 
keywords: resynchronize, replication, relationship 
summary: 'Vous devez resynchroniser une relation de réplication après avoir créé un volume de destination inscriptible, après une mise à jour échoue, car une copie Snapshot commune n"existe pas sur les volumes source et de destination, ou si vous souhaitez modifier la règle de réplication pour la relation.' 
---
= Resynchroniser une relation de réplication
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez resynchroniser une relation de réplication après avoir créé un volume de destination inscriptible, après une mise à jour échoue, car une copie Snapshot commune n'existe pas sur les volumes source et de destination, ou si vous souhaitez modifier la règle de réplication pour la relation.

.Description de la tâche
* Bien que la resynchronisation ne nécessite pas de transfert de base, elle peut prendre du temps. Vous pouvez exécuter la resynchronisation en dehors des heures de pointe.
* La resynchronisation des volumes qui font partie d'une configuration « fan-out » ou en cascade peut prendre plus de temps. Il n'est pas rare de voir la relation SnapMirror indiquant l'état « préparation » pour une période prolongée.


.Étape
. Resynchronisation des volumes source et de destination :
+
`snapmirror resync -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ... -type DP|XDP -policy _policy_`

+
Pour connaître la syntaxe complète de la commande, reportez-vous à la page man.

+
[NOTE]
====
On doit exécuter cette commande depuis le SVM de destination ou le cluster destination.

====
+
L'exemple suivant resynchronque la relation entre le volume source `volA` marche `svm1` et le volume de destination `volA_dst` marche `svm_backup`:

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1:volA -destination-path svm_backup:volA_dst
----

