---
permalink: data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html 
sidebar: sidebar 
keywords: snapmirror, synchronous, disaster, recovery 
summary: 'Depuis la version ONTAP 9.5, la technologie SnapMirror synchrone (SM-S) est prise en charge sur toutes les plateformes FAS et AFF disposant d"au moins 16 Go de mémoire et sur toutes les plateformes ONTAP Select. La technologie SnapMirror synchrone est une fonctionnalité sous licence par nœud qui permet la réplication synchrone des données au niveau du volume.' 
---
= Principes de base de la reprise après incident synchrone de SnapMirror
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis la version ONTAP 9.5, la technologie SnapMirror synchrone (SM-S) est prise en charge sur toutes les plateformes FAS et AFF disposant d'au moins 16 Go de mémoire et sur toutes les plateformes ONTAP Select. La technologie SnapMirror synchrone est une fonctionnalité sous licence par nœud qui permet la réplication synchrone des données au niveau du volume.

Cette fonctionnalité répond aux exigences réglementaires et nationales en matière de réplication synchrone dans les secteurs financiers, de la santé et autres secteurs réglementés où aucune perte de données n'est requise.

La limite du nombre d'opérations de réplication synchrone SnapMirror par paire HA dépend du modèle de contrôleur.

Le tableau ci-dessous répertorie le nombre d'opérations SnapMirror synchrone autorisées par paire HA en fonction du type de plateforme et de la version ONTAP.

|===


| Plateforme | Versions antérieures à ONTAP 9.9.1 | ONTAP 9.9.1 | ONTAP 9.10.1 | ONTAP 9.11.1 à ONTAP 9.14.1 


 a| 
AFF
 a| 
80
 a| 
160
 a| 
200
 a| 
400



 a| 
ASA
 a| 
80
 a| 
160
 a| 
200
 a| 
400



 a| 
FAS
 a| 
40
 a| 
80
 a| 
80
 a| 
80



 a| 
ONTAP Select
 a| 
20
 a| 
40
 a| 
40
 a| 
40

|===


== Fonctionnalités prises en charge

Le tableau suivant présente les fonctionnalités prises en charge par SnapMirror synchrone et les versions ONTAP dans lesquelles la prise en charge est disponible.

[cols="3,1,4"]
|===


| Fonction | Version d'abord prise en charge | Informations supplémentaires 


| Antivirus sur le volume primaire de la relation SnapMirror synchrone | ONTAP 9.6 |  


| Réplication de copie Snapshot créée par les applications | ONTAP 9.7 | Si une copie Snapshot est étiquetée avec l'étiquette appropriée au moment du `snapshot create` Par ailleurs, lors de l'utilisation de l'interface de ligne de commandes ou de l'API ONTAP, SnapMirror synchrone réplique les copies Snapshot, créées par l'utilisateur ou créées avec des scripts externes, après la suspension des applications. Les copies Snapshot planifiées créées à l'aide d'une règle Snapshot ne sont pas répliquées. Pour plus d'informations sur la réplication de copies Snapshot créées par les applications, consultez l'article de la base de connaissances : link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/How_to_replicate_application_created_snapshots_with_SnapMirror_Synchronous["Réplication des copies Snapshot créées par les applications avec SnapMirror synchrone"^]. 


| Suppression automatique des clones | ONTAP 9.6 |  


| Les agrégats FabricPool avec règles de Tiering aucune, Snapshot ou Auto sont pris en charge avec la source et la destination SnapMirror synchrone. | ONTAP 9.5 | Le volume de destination d'un agrégat FabricPool ne peut pas être défini sur l'ensemble des règles de Tiering. 


| FC | ONTAP 9.5 | Sur tous les réseaux pour lesquels la latence ne dépasse pas 10 ms. 


| NVMe-FC | ONTAP 9.7 |  


| Clones de fichiers | ONTAP 9.7 |  


| FPolicy sur le volume principal de la relation SnapMirror synchrone | ONTAP 9.6 |  


| Quotas matériels et conditionnels sur le volume principal de la relation SnapMirror synchrone | ONTAP 9.6 | Les règles de quota ne sont pas répliquées vers la destination. Par conséquent, la base de données de quota n'est pas répliquée vers la destination. 


| ISCSI | ONTAP 9.5 |  


| Clones de LUN et clones d'espace de noms NVMe | ONTAP 9.7 |  


| Clones LUN sauvegardés par des copies Snapshot créées par les applications | ONTAP 9.7 |  


| Accès à des protocoles mixtes (NFS v3 et SMB) | ONTAP 9.6 |  


| Restauration NDMP/NDMP | ONTAP 9.13.1 | Le cluster source et le cluster destination doivent exécuter ONTAP 9.13.1 ou une version ultérieure pour pouvoir utiliser NDMP avec SnapMirror synchrone. Pour plus d'informations, voir xref:../tape-backup/transfer-data-ndmpcopy-task.html[Transfert de données à l'aide d'une copie ndmp]. 


| Opérations SnapMirror synchrones sans interruption (NDO) sur les plateformes AFF/ASA, uniquement. | ONTAP 9.12.1 | La prise en charge de la continuité de l'activité vous permet d'effectuer de nombreuses tâches de maintenance courantes sans planifier de temps d'indisponibilité. Les opérations prises en charge incluent le basculement et le retour, ainsi que le déplacement de volumes, à condition qu'un seul nœud survive au sein de chacun des deux clusters. 


| NFS v4.2 | ONTAP 9.10.1 |  


| NFS v4.3 | ONTAP 9.5 |  


| NFS v4.0 | ONTAP 9.6 |  


| NFS v4.1 | ONTAP 9.6 |  


| NVMe/TCP | 9.10.1 |  


| Suppression de la limitation de fréquence d'opération de métadonnées élevée | ONTAP 9.6 |  


| Sécurité des données sensibles en transit avec le chiffrement TLS 1.2 | ONTAP 9.6 |  


| Restauration de fichiers uniques et partiels | ONTAP 9.13.1 |  


| SMB 2.0 ou version ultérieure | ONTAP 9.6 |  


| SnapMirror Synchronous mirror-mirror cascade | ONTAP 9.6 | La relation à partir du volume de destination de la relation SnapMirror synchrone doit être une relation SnapMirror asynchrone. 


| Reprise d'activité de SVM | ONTAP 9.6 | * Une source SnapMirror synchrone peut également être une source de reprise d'activité SVM, par exemple une configuration « Fan-Out » avec SnapMirror synchrone comme une étape et la reprise d'activité SVM comme l'autre.

* Une source SnapMirror synchrone ne peut pas être une destination de reprise d'activité SVM, car SnapMirror synchrone ne prend pas en charge la mise en cascade d'une source de protection des données.
Vous devez relâcher la relation synchrone avant d'effectuer une resynchronisation de reprise d'activité SVM dans le cluster destination.

* Une destination SnapMirror synchrone ne peut pas être une source de reprise d'activité de SVM, car la reprise d'activité de SVM ne prend pas en charge la réplication des volumes DP.
Une resynchronisation de la source synchrone entraînerait la reprise d'activité du SVM excluant le volume DP dans le cluster de destination. 


| Restauration sur bande vers le volume source | ONTAP 9.13.1 |  


| Parité temporelle entre les volumes source et de destination pour le NAS | ONTAP 9.6 | Si vous avez effectué une mise à niveau de ONTAP 9.5 vers ONTAP 9.6, l'horodatage est uniquement répliqué pour les fichiers nouveaux et modifiés du volume source. L'horodatage des fichiers existants dans le volume source n'est pas synchronisé. 
|===


== Fonctions non prises en charge

Les fonctionnalités suivantes ne sont pas prises en charge avec les relations SnapMirror synchrones :

* Groupes de cohérence
* Systèmes DP_optimisés (DPO)
* Volumes FlexGroup
* Volumes FlexCache
* Limitation globale
* Dans une configuration « Fan-Out », seule une relation peut être une relation SnapMirror synchrone ; toutes les autres relations du volume source doivent être des relations SnapMirror asynchrones.
* Déplacement de LUN
* Configurations MetroCluster
* Accès mixte SAN/NVMe
Les LUN et les namespaces NVMe ne sont pas pris en charge sur le même volume ou SVM.
* SnapCenter
* Volumes SnapLock
* Copies Snapshot inviolables
* Sauvegarde sur bande ou restauration à l'aide de dump et SMTape sur le volume de destination
* Débit au sol (QoS min) pour les volumes source
* SnapRestore du volume
* VVol




== Modes de fonctionnement

SnapMirror synchrone dispose de deux modes de fonctionnement basés sur le type de règle SnapMirror utilisée :

* *Mode de synchronisation*
En mode synchrone, les opérations d'E/S de l'application sont envoyées en parallèle au primaire et au secondaire
systèmes de stockage netapp fas. Si l'écriture dans le stockage secondaire n'est pas terminée, pour une raison quelconque, l'application peut continuer à écrire sur le stockage primaire. Lorsque l'erreur est résolue, la technologie SnapMirror synchrone se resynchronise automatiquement sur le système de stockage secondaire et reprend la réplication du stockage primaire sur le stockage secondaire en mode synchrone.
En mode synchrone, RPO=0 et RTO sont très faibles jusqu'à ce qu'une défaillance de réplication secondaire se produise. Ainsi, les objectifs RPO et RTO deviennent indéterminés, mais équivalent au temps de résolution du problème à l'origine de la défaillance de la réplication secondaire et de la resynchronisation à réaliser.
* *Mode StrictSync*
SnapMirror synchrone peut fonctionner en mode StrictSync. Si l'écriture sur le stockage secondaire n'est pas terminée, pour une raison quelconque, les E/S de l'application échouent, ce qui permet de s'assurer que les stockages primaire et secondaire sont identiques. Les E/S de l'application vers le système primaire sont reprendre uniquement après le retour de la relation SnapMirror dans `InSync` état. En cas de panne du stockage primaire, les E/S des applications peuvent reprendre sur le système de stockage secondaire, après le basculement, sans perte de données.
En mode StrictSync, le RPO est toujours nul et le RTO très faible.




== État des relations

L'état d'une relation SnapMirror synchrone est toujours dans le `InSync` état pendant le fonctionnement normal. Si le transfert SnapMirror échoue, quelle qu'en soit la raison, la destination n'est pas en synchronisation avec la source et peut être transférée vers le système `OutofSync` état.

Pour les relations SnapMirror synchrones, le système vérifie automatiquement l'état de la relation  `InSync` ou `OutofSync`) à intervalle fixe. Si le statut de la relation est `OutofSync`, ONTAP déclenche automatiquement le processus de resynchronisation automatique pour ramener la relation à l' `InSync` état. La resynchronisation automatique n'est déclenchée que si le transfert échoue en raison de certaines opérations, telles que le basculement non planifié du stockage à la source ou à la destination, ou en cas de panne réseau. Les opérations initiées par l'utilisateur, telles que `snapmirror quiesce` et `snapmirror break` ne pas déclencher une resynchronisation automatique.

Si le statut de la relation devient `OutofSync` Dans le cas d'une relation SnapMirror synchrone en mode StrictSync, toutes les opérations d'E/S vers le volume primaire sont arrêtées. Le `OutofSync` État de la relation SnapMirror synchrone en mode synchrone n'engendre pas d'interruption des opérations d'E/S primaires et du volume primaire.

.Informations associées
http://www.netapp.com/us/media/tr-4733.pdf["Rapport technique NetApp 4733 : configuration SnapMirror synchrone et bonnes pratiques"^]
