---
permalink: data-protection/snapmirror-licensing-concept.html 
sidebar: sidebar 
keywords: snapmirror, licensing, snapvault, vault, mirror, relationship, replication, backup, back up, disaster recovery, dr 
summary: 'La licence SnapMirror prend en charge les relations de coffre-fort et de miroir ainsi que la réplication ONTAP pour les cas d"utilisation de sauvegarde et de reprise après sinistre.' 
---
= En savoir plus sur les licences ONTAP SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis ONTAP 9.3, la licence a été simplifiée pour la réplication entre les instances ONTAP. Dans les versions de ONTAP 9, la licence SnapMirror prend en charge les relations d'archivage sécurisé et en miroir. Vous pouvez utiliser une licence SnapMirror pour prendre en charge la réplication ONTAP, aussi bien pour la sauvegarde que pour la reprise après incident.

Avant la version ONTAP 9.3, une licence SnapVault distincte était nécessaire pour configurer les relations _vault_ entre les instances ONTAP, où l'instance DP pouvait conserver un nombre plus élevé de snapshots pour prendre en charge les cas d'utilisation de sauvegarde avec des durées de conservation plus longues, et une licence SnapMirror était nécessaire pour configurer les relations _mirror_ entre les instances ONTAP, où chaque instance ONTAP conservera le même nombre de snapshots (c'est-à-dire qu'une image de cluster_ pouvait utiliser des basculements de reprise d'incident). Les licences SnapMirror et SnapVault sont toujours utilisées et prises en charge pour les versions ONTAP 8.x et 9.x.

Les licences SnapVault continuent de fonctionner et sont prises en charge aussi bien pour les versions ONTAP 8.x que 9.x, mais la licence SnapMirror peut être utilisée à la place d'une licence SnapVault et peut être utilisée pour les configurations en miroir et en coffre-fort.

Pour la réplication asynchrone ONTAP, à partir de ONTAP 9.3, un moteur de réplication unifié unique est utilisé pour configurer les règles de mode de protection étendue des données (XDP), où la licence SnapMirror peut être configurée pour une règle de miroir, une règle de copie à distance ou une règle de copie miroir-coffre. Une licence SnapMirror est requise sur les clusters source et de destination. Une licence SnapVault n'est pas requise si une licence SnapMirror est déjà installée. La licence perpétuelle asynchrone SnapMirror est incluse dans la suite logicielle ONTAP One installée sur les nouveaux systèmes AFF et FAS.

Les limites de configuration de la protection des données sont déterminées à l'aide de plusieurs facteurs, notamment la version de ONTAP, la plateforme matérielle et les licences installées. Pour plus d'informations, voir https://hwu.netapp.com/["Hardware Universe"^].



== Licence synchrone SnapMirror

Depuis ONTAP 9.5, les relations SnapMirror synchrones sont prises en charge. Pour créer une relation synchrone SnapMirror, vous avez besoin des licences suivantes :

* La licence synchrone SnapMirror est requise à la fois sur le cluster source et sur le cluster destination.
+
La licence synchrone SnapMirror fait partie du link:../system-admin/manage-licenses-concept.html["Suite de licences ONTAP One"].

+
Si votre système a été acheté avant juin 2019 avec un bundle Premium ou Flash, vous pouvez télécharger une clé principale NetApp pour obtenir la licence synchrone SnapMirror requise sur le site de support NetApp : https://mysupport.netapp.com/NOW/knowledge/docs/olio/guides/master_lickey/["Clés de licence maîtresse"^].

* La licence SnapMirror est requise sur le cluster source et le cluster cible.




== Licence cloud SnapMirror

Depuis ONTAP 9.8, la licence cloud SnapMirror assure la réplication asynchrone des copies Snapshot entre des instances ONTAP et des terminaux de stockage objet. Les cibles de réplication peuvent être configurées à la fois via des magasins d'objets sur site et des services de stockage objet dans le cloud public compatibles S3 et S3. Les relations cloud SnapMirror sont prises en charge par les systèmes ONTAP vers les cibles de stockage objet préqualifiées.

SnapMirror Cloud n'est pas disponible en tant que licence autonome. Une seule licence est requise par cluster ONTAP. Outre une licence cloud SnapMirror, la licence asynchrone SnapMirror est également requise.

Pour créer une relation cloud avec SnapMirror, vous avez besoin des licences suivantes :

* Licence SnapMirror et licence cloud SnapMirror pour la réplication directe sur le terminal du magasin d'objets.
* Lors de la configuration d'un workflow de réplication à règles multiples (par exemple, disque à disque à cloud), une licence SnapMirror est requise sur toutes les instances ONTAP, tandis que la licence cloud SnapMirror est uniquement requise pour le cluster source qui réplique directement sur le terminal de stockage objet.


À partir d' ONTAP 9.9.1, vous pouvez link:cloud-backup-with-snapmirror-task.html["Utilisez System Manager pour la réplication cloud SnapMirror"] .

La liste des applications tierces cloud SnapMirror autorisées est publiée sur le site Web de NetApp.



== Licence optimisée pour Data protection

Les licences DPO (Data protection Optimized) ne sont plus vendues et DPO n'est pas pris en charge sur les plates-formes actuelles. Cependant, si vous disposez d'une licence DPO installée sur une plate-forme prise en charge, NetApp continue à fournir le support jusqu'à la fin de la disponibilité de cette plate-forme.

DPO n'est pas inclus avec le pack de licences ONTAP One et vous ne pouvez pas mettre à niveau vers le pack de licences ONTAP One si la licence DPO est installée sur un système.

Pour plus d'informations sur les plates-formes prises en charge, voir https://hwu.netapp.com/["Hardware Universe"^].
