---
permalink: data-protection/snapmirror-unified-replication-concept.html 
sidebar: sidebar 
keywords: snapmirror, unified, replication 
summary: 'La réplication unifiée SnapMirror vous permet de configurer la reprise après incident et l"archivage sur le même volume de destination. Lorsque la réplication unifiée est appropriée, elle offre des avantages en réduisant la quantité de stockage secondaire nécessaire, en limitant le nombre de transferts de base et en diminuant le trafic réseau.' 
---
= Découvrez la réplication unifiée ONTAP SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror _réplication unifiée_ permet de configurer la reprise après incident et l'archivage sur le même volume de destination. Lorsque la réplication unifiée est appropriée, elle offre des avantages en réduisant la quantité de stockage secondaire nécessaire, en limitant le nombre de transferts de base et en diminuant le trafic réseau.



== Mode d'initialisation des relations de protection unifiée des données

Comme pour SnapMirror, la protection unifiée des données effectue un transfert de base dès le premier appel que vous l'appelez. La règle SnapMirror pour la relation définit le contenu de la base et toutes les mises à jour.

Un transfert de base dans le cadre de la règle de protection des données unifiée par défaut `MirrorAndVault` effectue un snapshot du volume source, puis transfère cette copie et les blocs de données qu'elle référence au volume de destination. Tout comme l'archivage en coffre-fort, la protection unifiée des données n'inclut pas les anciens snapshots dans la configuration de base.



== Mise à jour des relations de protection unifiée des données

À chaque mise à jour de la `MirrorAndVault` règle, SnapMirror crée un snapshot du volume source et transfère ce snapshot ainsi que tous les snapshots créés depuis la dernière mise à jour, à condition qu'ils aient des étiquettes correspondant aux étiquettes définies dans les règles de la règle de snapshot. Dans les valeurs de sortie suivantes de `snapmirror policy show` la commande pour la `MirrorAndVault` règle, noter ce qui suit :

* `Create Snapshot` Est « true », ce qui signifie que `MirrorAndVault` crée un snapshot lorsque SnapMirror met à jour la relation.
* `MirrorAndVault` Possède des règles « `sm_created`", « quotidiennes » et « hebdomadaires », ce qui indique que le snapshot créé par SnapMirror et les snapshots avec des libellés correspondants sur la source sont transférés lorsque SnapMirror met à jour la relation.


[listing]
----
cluster_dst::> snapmirror policy show -policy MirrorAndVault -instance

                     Vserver: vs0
      SnapMirror Policy Name: MirrorAndVault
      SnapMirror Policy Type: mirror-vault
                Policy Owner: cluster-admin
                 Tries Limit: 8
           Transfer Priority: normal
   Ignore accesstime Enabled: false
     Transfer Restartability: always
 Network Compression Enabled: false
             Create Snapshot: true
                     Comment: A unified SnapMirror synchronous and SnapVault policy for
                              mirroring the latest file system and daily and weekly snapshots.
       Total Number of Rules: 3
                  Total Keep: 59
                       Rules: SnapMirror Label     Keep  Preserve Warn Schedule Prefix
                              ----------------     ----  -------- ---- -------- ------
                              sm_created              1  false       0 -        -
                              daily                   7  false       0 -        -
                              weekly                 52  false       0 -        -
----


== Politique unifiée sur 7ans

La règle préconfigurée `Unified7year` fonctionne exactement de la même manière que `MirrorAndVault`, sauf qu'une quatrième règle transfère les snapshots mensuels et les conserve pendant sept ans.

[listing]
----

                       Rules: SnapMirror Label     Keep  Preserve Warn Schedule Prefix
                              ----------------     ----  -------- ---- -------- ------
                              sm_created              1  false       0 -        -
                              daily                   7  false       0 -        -
                              weekly                 52  false       0 -        -
                              monthly                84  false       0 -        -
----


== Protégez-vous contre les risques de corruption

La réplication unifiée limite le contenu du transfert de base vers le snapshot créé par SnapMirror au moment de l'initialisation. À chaque mise à jour, SnapMirror crée un autre snapshot de la source et le transfère ainsi que tout nouvel instantané dont les étiquettes correspondent aux étiquettes définies dans les règles de la règle de snapshot.

Vous pouvez vous protéger contre le risque de corruption d'un instantané mis à jour en créant une copie du dernier instantané transféré sur la destination. Cette « copie locale » est conservée indépendamment des règles de conservation sur la source, de sorte que même si l'instantané initialement transféré par SnapMirror n'est plus disponible sur la source, une copie de celui-ci sera disponible sur la destination.



== À quel moment utiliser la réplication unifiée des données

Vous devez évaluer les avantages de la maintenance d'un miroir complet par rapport aux avantages offerts par la réplication unifiée : réduction de la quantité de stockage secondaire, limitation du nombre de transferts de base et diminution du trafic réseau.

Le facteur clé pour déterminer la pertinence de la réplication unifiée est le taux de changement du système de fichiers actif. Par exemple, un miroir traditionnel convient mieux à un volume contenant des snapshots horaires de journaux de transactions de base de données.
