---
permalink: data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html 
sidebar: sidebar 
keywords: snapmirror, synchronous, disaster, recovery 
summary: 'Depuis la version ONTAP 9.5, la technologie SnapMirror synchrone (SM-S) est prise en charge sur toutes les plateformes FAS et AFF disposant d"au moins 16 Go de mémoire et sur toutes les plateformes ONTAP Select. La technologie SnapMirror synchrone est une fonctionnalité sous licence par nœud qui permet la réplication synchrone des données au niveau du volume.' 
---
= Principes de base de la reprise après incident synchrone de SnapMirror
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Depuis la version ONTAP 9.5, la technologie SnapMirror synchrone (SM-S) est prise en charge sur toutes les plateformes FAS et AFF disposant d'au moins 16 Go de mémoire et sur toutes les plateformes ONTAP Select. La technologie SnapMirror synchrone est une fonctionnalité sous licence par nœud qui permet la réplication synchrone des données au niveau du volume.

Cette fonctionnalité répond aux exigences réglementaires et nationales en matière de réplication synchrone dans les secteurs financiers, de la santé et autres secteurs réglementés où aucune perte de données n'est requise.

La limite du nombre d'opérations de réplication synchrone SnapMirror par paire HA dépend du modèle de contrôleur.

Le tableau ci-dessous répertorie le nombre d'opérations SnapMirror synchrone autorisées par paire HA en fonction du type de plateforme et de la version ONTAP.

|===


| Plateforme | Versions antérieures à ONTAP 9.9.1 | ONTAP 9.9.1 | ONTAP 9.10.1 | ONTAP 9.11.1 à ONTAP 9.14.1 


 a| 
AFF
 a| 
80
 a| 
160
 a| 
200
 a| 
400



 a| 
FAS
 a| 
40
 a| 
80
 a| 
80
 a| 
80



 a| 
ONTAP Select
 a| 
20
 a| 
40
 a| 
40
 a| 
40

|===


== Fonctionnalités prises en charge

ONTAP 9.12.1 prend en charge la continuité de l'activité SnapMirror synchrone sur les plateformes AFF/ASA, uniquement. La prise en charge de la continuité de l'activité vous permet d'effectuer de nombreuses tâches de maintenance courantes sans planifier de temps d'indisponibilité. Les opérations prises en charge incluent le basculement et le retour, ainsi que le déplacement de volumes, à condition qu'un seul nœud survive au sein de chacun des deux clusters.

Les fonctionnalités suivantes sont prises en charge pour la technologie SnapMirror synchrone dans la ONTAP 9.10.1 (si tous les nœuds du cluster source et de destination exécutent ONTAP 9.10.1) :

* NFSv4.2
* NVMe/TCP


Dans ONTAP 9.5 et versions ultérieures, la technologie SnapMirror synchrone prend en charge les protocoles NFSv3, FC et iSCSI sur tous les réseaux pour lesquels la latence n'excède pas 10 ms.

SnapMirror synchrone prend en charge les volumes source et de destination sur les agrégats FabricPool avec une règle de Tiering sans, Snapshot ou Auto. Le volume de destination d'un agrégat FabricPool ne peut pas être défini sur l'ensemble des règles de Tiering.

Les fonctionnalités suivantes sont prises en charge par la technologie SnapMirror synchrone dans la ONTAP 9.7 :

* Réplication des copies Snapshot créées par les applications
Si une copie Snapshot est étiquetée avec l'étiquette appropriée au moment du `snapshot create` Par ailleurs, lors de l'utilisation de l'interface de ligne de commandes ou de l'API ONTAP, SnapMirror synchrone réplique les copies Snapshot, créées par l'utilisateur ou créées avec des scripts externes, après la suspension des applications. Les copies Snapshot planifiées créées à l'aide d'une règle Snapshot ne sont pas répliquées. Pour plus d'informations sur la réplication de copies Snapshot créées par les applications, consultez l'article de la base de connaissances : link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/How_to_replicate_application_created_snapshots_with_SnapMirror_Synchronous["Réplication des copies Snapshot créées par les applications avec SnapMirror synchrone"^].
* NVMe-FC
* Clones de LUN et clones d'espace de noms NVMe
Les clones LUN sauvegardés par les copies Snapshot créées par les applications sont également pris en charge.


Les fonctionnalités suivantes sont prises en charge pour la technologie SnapMirror synchrone dans la ONTAP 9.6 (si tous les nœuds du cluster source et de destination exécutent ONTAP 9.6) :

* REPRISE APRÈS INCIDENT DES SVM
+
** Une source SnapMirror synchrone peut également être une source SVM DR, par exemple une configuration « Fan-Out » avec SM-S comme une jambe et un SVM DR comme l'autre.
** Une source SnapMirror synchrone ne peut pas être une destination de reprise après incident SVM, car SM-S ne prend pas en charge une source DP en cascade.
Vous devez libérer la relation synchrone avant d'effectuer une resynchronisation des SVM DR dans le cluster destination.
** Une destination SnapMirror synchrone ne peut pas être une source SVM DR, car la reprise après incident du SVM ne prend pas en charge la réplication de volumes DP.
Un retournement de resynchronisation de la source synchrone entraînerait la reprise après incident du SVM à l'exclusion du volume DP dans le cluster de destination.


* NFSv4.0 et NFSv4.1
* SMB 2.0 ou version ultérieure
* Accès à partir de protocoles mixtes (NFSv3 et SMB)
* Antivirus sur le volume primaire de la relation SnapMirror synchrone
* Quotas matériels ou conditionnels sur le volume principal de la relation SnapMirror synchrone
Les règles de quota ne sont pas répliquées vers la destination. Par conséquent, la base de données de quota n'est pas répliquée vers la destination.
* FPolicy sur le volume principal de la relation SnapMirror synchrone
* SnapMirror Synchronous mirror-mirror cascade
La relation à partir du volume de destination de la relation SnapMirror synchrone doit être une relation SnapMirror asynchrone.
* Parité temporelle entre les volumes source et de destination pour le NAS
Si vous avez effectué une mise à niveau de ONTAP 9.5 vers ONTAP 9.6, l'horodatage est uniquement répliqué pour les fichiers nouveaux et modifiés du volume source. L'horodatage des fichiers existants dans le volume source n'est pas synchronisé.
* Suppression de la limitation de fréquence d'opération de métadonnées élevée
* Sécurité des données sensibles en transit avec le chiffrement TLS 1.2
* Cloner la suppression automatique


À partir de ONTAP 9.13.1, NDMP est pris en charge avec SnapMirror synchrone. Le cluster source et le cluster destination doivent exécuter ONTAP 9.13.1 ou une version ultérieure pour pouvoir utiliser NDMP avec SnapMirror synchrone. Pour plus d'informations, voir xref:../tape-backup/transfer-data-ndmpcopy-task.html[Transfert de données à l'aide d'une copie ndmp].



== Fonctions non prises en charge

Les fonctionnalités suivantes ne sont pas prises en charge avec les relations SnapMirror synchrones :

* Copies Snapshot inviolables
* Groupes de cohérence
* Configurations MetroCluster
* Déplacement de LUN
* Clone de LUN/clone de fichier
* VVol
* Accès mixte SAN/NVMe
Les LUN et les namespaces NVMe ne sont pas pris en charge sur le même volume ou SVM.
* Volumes SnapLock
* Volumes FlexGroup
* Volumes FlexCache
* SnapRestore
* Systèmes DP_optimisés (DPO)
* Sauvegarde sur bande ou restauration à l'aide de dump et SMTape sur le volume de destination
* Restauration sur bande vers le volume source
* Débit au sol (QoS min) pour les volumes source
* Dans une configuration « Fan-Out », seule une relation peut être une relation SnapMirror synchrone ; toutes les autres relations du volume source doivent être des relations SnapMirror asynchrones.
* Limitation globale




== Modes de fonctionnement

SnapMirror synchrone dispose de deux modes de fonctionnement basés sur le type de règle SnapMirror utilisée :

* *Mode de synchronisation*
En mode synchrone, les opérations d'E/S de l'application sont envoyées en parallèle au primaire et au secondaire
systèmes de stockage netapp fas. Si l'écriture dans le stockage secondaire n'est pas terminée, pour une raison quelconque, l'application peut continuer à écrire sur le stockage primaire. Lorsque l'erreur est résolue, la technologie SnapMirror synchrone se resynchronise automatiquement sur le système de stockage secondaire et reprend la réplication du stockage primaire sur le stockage secondaire en mode synchrone.
En mode synchrone, RPO=0 et RTO sont très faibles jusqu'à ce qu'une défaillance de réplication secondaire se produise. Ainsi, les objectifs RPO et RTO deviennent indéterminés, mais équivalent au temps de résolution du problème à l'origine de la défaillance de la réplication secondaire et de la resynchronisation à réaliser.
* *Mode StrictSync*
SnapMirror synchrone peut fonctionner en mode StrictSync. Si l'écriture sur le stockage secondaire n'est pas terminée, pour une raison quelconque, les E/S de l'application échouent, ce qui permet de s'assurer que les stockages primaire et secondaire sont identiques. Les E/S de l'application vers le système primaire sont reprendre uniquement après le retour de la relation SnapMirror dans `InSync` état. En cas de panne du stockage primaire, les E/S des applications peuvent reprendre sur le système de stockage secondaire, après le basculement, sans perte de données.
En mode StrictSync, le RPO est toujours nul et le RTO très faible.




== État des relations

L'état d'une relation SnapMirror synchrone est toujours dans le `InSync` état pendant le fonctionnement normal. Si le transfert SnapMirror échoue, quelle qu'en soit la raison, la destination n'est pas en synchronisation avec la source et peut être transférée vers le système `OutofSync` état.

Pour les relations SnapMirror synchrones, le système vérifie automatiquement l'état de la relation  `InSync` ou `OutofSync`) à intervalle fixe. Si le statut de la relation est `OutofSync`, ONTAP déclenche automatiquement le processus de resynchronisation automatique pour ramener la relation à l' `InSync` état. La resynchronisation automatique n'est déclenchée que si le transfert échoue en raison de certaines opérations, telles que le basculement non planifié du stockage à la source ou à la destination, ou en cas de panne réseau. Les opérations initiées par l'utilisateur, telles que `snapmirror quiesce` et `snapmirror break` ne pas déclencher une resynchronisation automatique.

Si le statut de la relation devient `OutofSync` Dans le cas d'une relation SnapMirror synchrone en mode StrictSync, toutes les opérations d'E/S vers le volume primaire sont arrêtées. Le `OutofSync` État de la relation SnapMirror synchrone en mode synchrone n'engendre pas d'interruption des opérations d'E/S primaires et du volume primaire.

.Informations associées
http://www.netapp.com/us/media/tr-4733.pdf["Rapport technique NetApp 4733 : configuration SnapMirror synchrone et bonnes pratiques"^]
