---
permalink: data-protection/update-replication-relationship-manual-task.html 
sidebar: sidebar 
keywords: update, replication, relationship, manual, snap mirror, snapmirror, synchronous 
summary: Vous devrez peut-être mettre à jour une relation de réplication manuellement si une mise à jour échoue, car le volume source a été déplacé. 
---
= Mettre à jour une relation de réplication ONTAP SnapMirror manuellement
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devrez peut-être mettre à jour une relation de réplication manuellement si une mise à jour échoue, car le volume source a été déplacé.

.Description de la tâche
SnapMirror interrompt tous les transferts depuis un volume source déplacé jusqu'à ce que vous mette à jour la relation de réplication manuellement.

Depuis ONTAP 9.5, les relations SnapMirror synchrones sont prises en charge. Bien que les volumes source et de destination soient synchronisés à tout moment dans ces relations, la vue du cluster secondaire est synchronisée avec la vue principale uniquement toutes les heures. Si vous souhaitez afficher les données à un point dans le temps à la destination, vous devez effectuer une mise à jour manuelle en exécutant `snapmirror update` la commande.

.Étape
. Mettre à jour une relation de réplication manuellement :
+
`snapmirror update -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ...`

+
[NOTE]
====
On doit exécuter cette commande depuis le SVM de destination ou le cluster destination. La commande échoue si un snapshot commun n'existe pas sur la source et la destination. Utilisez `snapmirror initialize` pour réinitialiser la relation. Pour en savoir plus, `snapmirror initialize` consultez le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["Référence de commande ONTAP"^].

====
+
L'exemple suivant met à jour la relation entre le volume source `volA` marche `svm1` et le volume de destination `volA_dst` marche `svm_backup`:

+
[listing]
----
cluster_src::> snapmirror update -source-path svm1:volA -destination-path svm_backup:volA_dst
----
+
Pour en savoir plus, `snapmirror update` consultez le link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["Référence de commande ONTAP"^].


