---
permalink: data-protection/vol-placement-criteria-svm-dest-reference.html 
sidebar: sidebar 
keywords: snapmirror, svm, replication, disaster recovery, aggregate, volume 
summary: Lors de la réplication de volumes du SVM source vers le SVM de destination, il est important de connaître les critères de sélection des agrégats. 
---
= Critères de placement des volumes sur les SVM de destination ONTAP SnapMirror
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lors de la réplication de volumes du SVM source vers le SVM de destination, il est important de connaître les critères de sélection des agrégats.

Les agrégats sont sélectionnés selon les critères suivants :

* Les volumes sont toujours placés sur des agrégats non racines.
* Les agrégats non racines sont sélectionnés en fonction de l'espace disponible et du nombre de volumes déjà hébergés sur l'agrégat.
+
Les agrégats disposant d'un espace libre supérieur et avec moins de volumes sont prioritaires. L'agrégat avec la priorité la plus élevée est sélectionné.

* Les volumes source des agrégats FabricPool sont situés sur des agrégats FabricPool de destination avec la même règle de Tiering.
* Si un volume du SVM source se trouve sur un agrégat Flash Pool, celui-ci est placé sur un agrégat Flash Pool sur le SVM de destination, si un tel agrégat existe et dispose de suffisamment d'espace libre.
* Si le `-space-guarantee` l'option du volume répliqué est définie sur `volume`, seuls les agrégats avec un espace libre supérieur à la taille du volume sont pris en compte.
* La taille du volume augmente automatiquement sur le SVM de destination pendant la réplication, en fonction de la taille du volume source.
+
Si vous souhaitez pré-réserver la taille sur le SVM de destination, vous devez redimensionner le volume. La taille du volume n'est pas réduite automatiquement sur le SVM de destination, en fonction du SVM source.



Si vous souhaitez déplacer un volume d'un agrégat à un autre, vous pouvez utiliser le `volume move` Commande sur le SVM de destination.
