---
permalink: data-protection/workloads-strictsync-sync-policies-concept.html 
sidebar: sidebar 
keywords: understand, workloads, support, strictsync, policy, strict sync, policies, snapmirror, snap mirror, cifs, vmware, eda, synchronous, fc, iscsi, nvme, nfsv3, nfsv4 
summary: 'Les règles StrictSync et Sync prennent en charge toutes les applications basées sur les LUN avec les protocoles FC, iSCSI et FC-NVMe, ainsi que les protocoles NFSv3 et NFSv4 pour les applications d"entreprise telles que les bases de données, VMware, les quotas, SMB, etc. Depuis la version ONTAP 9.6, SnapMirror synchrone peut être utilisé pour les services de fichiers d"entreprise, tels que l"EDA, les répertoires locaux et les workloads de développement logiciel.' 
---
= À propos des workloads pris en charge par les règles de synchronisation et de synchronisation StrictSync
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les règles StrictSync et Sync prennent en charge toutes les applications basées sur les LUN avec les protocoles FC, iSCSI et FC-NVMe, ainsi que les protocoles NFSv3 et NFSv4 pour les applications d'entreprise telles que les bases de données, VMware, les quotas, SMB, etc. Depuis la version ONTAP 9.6, SnapMirror synchrone peut être utilisé pour les services de fichiers d'entreprise, tels que l'EDA, les répertoires locaux et les workloads de développement logiciel.

Dans ONTAP 9.5, pour une règle de synchronisation, vous devez tenir compte de quelques aspects importants lors de la sélection des workloads NFSv3 ou NFSv4. Le nombre d'opérations de lecture ou d'écriture de données par workload n'est pas pris en compte, car la règle de synchronisation peut gérer des workloads d'E/S haute capacité de lecture ou d'écriture. Dans ONTAP 9.5, les charges de travail dont la création de fichiers, la création de répertoires, les modifications d'autorisations liées aux fichiers ou les modifications d'autorisations de répertoire sont excessives peuvent ne pas convenir (on parle alors de charges de travail hautement métadonnées). Un workload de métadonnées élevé est un exemple de workload DevOps dans lequel vous créez plusieurs fichiers de test, exécutez une automatisation et supprimez les fichiers. Il est également possible, par exemple, de créer une charge de travail parallèle qui génère plusieurs fichiers temporaires lors de la compilation. L'impact d'un taux élevé d'activité de métadonnées d'écriture est qu'il peut entraîner une rupture temporaire entre les miroirs, ce qui bloque les E/S de lecture et d'écriture du client.

Depuis la version ONTAP 9.6, ces limites sont supprimées, et SnapMirror synchrone peut être utilisé pour les workloads de services de fichiers d'entreprise incluant des environnements multiutilisateurs, tels que les répertoires locaux et les workloads de développement logiciel.

http://www.netapp.com/us/media/tr-4733.pdf["Configuration synchrone de SnapMirror et bonnes pratiques"^]
