---
permalink: release-notes/index.html 
sidebar: sidebar 
keywords: release notes, new features 
summary: Découvrez les nouvelles fonctionnalités disponibles dans ONTAP 9. 
---
= Points forts de la version ONTAP 9
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Chaque version du logiciel de gestion des données ONTAP 9 inclut de nouvelles fonctionnalités améliorées qui améliorent les fonctionnalités, la gestion, les performances et la sécurité dans ONTAP.

En plus de ces points forts, vous trouverez une couverture complète par version de toutes les nouvelles fonctionnalités et améliorations introduites dans les dernières versions d'ONTAP.

Pour plus d'informations sur la prise en charge des commutateurs et de la plateforme matérielle, les problèmes connus et les limites dans toutes les versions de ONTAP 9, ou pour connaître les fonctionnalités introduites dans les versions antérieures à ONTAP 9.9.1, reportez-vous à _link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Notes de mise à jour de ONTAP 9"^]_. Vous devez vous connecter avec votre compte NetApp ou créer un compte pour accéder aux notes de version.

Pour effectuer la mise à niveau vers la dernière version de ONTAP, reportez-vous à la section xref:../upgrade/prepare.html[Mise à niveau vers la dernière version de ONTAP] et xref:../upgrade/when-to-upgrade.html[Quand dois-je mettre à niveau ONTAP ?]



== Points forts de ONTAP 9.14.1

ONTAP 9.14.1 propose de nouvelles fonctionnalités améliorées dans les domaines d'FabricPool, de la protection contre les ransomware, d'OAuth, etc. Pour obtenir la liste complète des nouvelles fonctionnalités et améliorations, reportez-vous à la section xref:9141-reference.adoc[Nouveautés de ONTAP 9.14.1].

* xref:../volumes/determine-space-usage-volume-aggregate-concept.html[Réduction réservation WAFL]
+
ONTAP 9.14.1 augmente immédiatement de 5 % l'espace utilisable sur les systèmes FAS et Cloud Volumes ONTAP en réduisant la réserve WAFL sur les agrégats de 30 To ou plus.

* xref:../fabricpool/enable-disable-volume-cloud-write-task.html[Améliorations de FabricPool]
+
FabricPool offre un de plus en plus de xref:../fabricpool/enable-disable-aggressive-read-ahead-task.html[performances de lecture] elle permet également d'écrire directement dans le cloud, ce qui réduit les risques de manque d'espace et les coûts de stockage en déplaçant les données inactives vers un tier de stockage moins coûteux.

* link:../authentication/oauth2-deploy-ontap.html["Prise en charge d'OAuth 2.0"]
+
ONTAP prend en charge l'infrastructure OAuth 2.0, qui peut être configurée à l'aide du Gestionnaire système. Avec OAuth 2.0, vous pouvez fournir un accès sécurisé à ONTAP pour les infrastructures d'automatisation sans créer ou exposer des ID utilisateur et des mots de passe à des scripts en texte brut et des runbooks.

* link:../anti-ransomware/manage-parameters-task.html["Améliorations de la protection anti-ransomware autonome (ARP)"]
+
ARP vous accorde davantage de contrôle sur la sécurité des événements, ce qui vous permet d'ajuster les conditions qui créent des alertes et de réduire le risque de faux positifs.

* xref:../data-protection/create-delete-snapmirror-failover-test-task.html[Répétition de la reprise d'activité SnapMirror dans System Manager]
+
System Manager permet de tester facilement la reprise après incident sur un site distant et de la nettoyer après le test. Cette fonctionnalité permet des tests plus simples et plus fréquents, et une confiance accrue dans les objectifs de délai de restauration.

* xref::../s3-config/index.html[Prise en charge du verrouillage objet S3]
+
ONTAP S3 prend en charge la commande d'API de verrouillage objet, ce qui vous permet de protéger contre la suppression les données écrites sur ONTAP avec S3
À l'aide de commandes standard de l'API S3 et pour s'assurer que les données importantes sont protégées pendant la durée appropriée.

* xref:../assign-tags-cluster-task.html[Cluster] et xref:../assign-tags-volumes-task.html[volumétrie] balisage
+
Ajoutez des balises de métadonnées aux volumes et aux clusters, qui suivent et suivent le déplacement des données depuis l'environnement sur site vers le cloud, et inversement.





== Points forts de ONTAP 9.13.1

ONTAP 9.13.1 inclut de nouvelles fonctionnalités améliorées dans les domaines de la protection contre les ransomware, des groupes de cohérence, de la qualité de service, de la gestion de la capacité des locataires, etc. Pour obtenir la liste complète des nouvelles fonctionnalités et améliorations, reportez-vous à la section xref:9131-reference.adoc[Nouveautés de ONTAP 9.13.1].

* Améliorations de la protection anti-ransomware autonome (ARP) :
+
** xref:../anti-ransomware/enable-default-task.adoc[Activation automatique]
+
Avec ONTAP 9.13.1, ARP passe automatiquement du mode de formation au mode de production dès lors qu'il dispose de données d'apprentissage suffisantes, ce qui évite à un administrateur de l'activer au bout de 30 jours.

** xref:../anti-ransomware/use-cases-restrictions-concept.html#multi-admin-verification-with-volumes-protected-with-arp[Prise en charge de la vérification multiadministrateur]
+
Les commandes de désactivation du protocole ARP sont prises en charge par la vérification multiadministrateur, ce qui permet de s'assurer qu'aucun administrateur ne peut désactiver le protocole ARP pour exposer les données à d'éventuelles attaques par ransomware.

** xref:../anti-ransomware/use-cases-restrictions-concept.html[Prise en charge de FlexGroup]
+
ARP prend en charge FlexGroups à partir de ONTAP 9.13.1. ARP peut contrôler et protéger les FlexGroups couvrant plusieurs volumes et nœuds du cluster, ce qui permet de protéger même les datasets les plus volumineux avec ARP.



* xref:../consistency-groups/index.html[Contrôle des performances et de la capacité pour les groupes de cohérence dans System Manager]
+
Le contrôle des performances et de la capacité fournit des informations détaillées pour chaque groupe de cohérence. Il vous permet d'identifier et de signaler rapidement les problèmes potentiels au niveau de l'application plutôt qu'au niveau de l'objet de données.

* xref:../volumes/manage-svm-capacity.html[Gestion de la capacité des locataires]
+
Les clients et fournisseurs de services mutualisés peuvent fixer une limite de capacité sur chaque SVM, ce qui permet aux locataires d'effectuer un provisionnement en libre-service sans risque de consommation excessive de la capacité d'un locataire sur le cluster.

* xref:../performance-admin/adaptive-policy-template-task.html[Plafonds et étages de qualité de service]
+
ONTAP 9.13.1 vous permet de regrouper des objets, tels que des volumes, des LUN ou des fichiers, et d'attribuer un plafond de QoS (IOPS maximales) ou un seuil (IOPS minimales), ce qui améliore les attentes en matière de performance des applications.





== Points forts de ONTAP 9.12.1

ONTAP 9.12.1 offre de nouvelles fonctionnalités améliorées dans les domaines du renforcement de la sécurité, de la conservation, des performances, etc. Pour obtenir la liste complète des nouvelles fonctionnalités et améliorations, reportez-vous à la section xref:9121-reference.adoc[Nouveautés de ONTAP 9.12.1].

* xref:../snaplock/snapshot-lock-concept.html[Instantanés inviolables]
+
Avec la technologie SnapLock, les copies Snapshot ne peuvent pas être supprimées à la source ou à la destination.

+
Conservez davantage de points de restauration en protégeant les snapshots sur le stockage primaire et secondaire contre la suppression par des attaquants de ransomware ou des administrateurs peu scrupuleux.

* xref:../anti-ransomware/index.html[Améliorations de la protection anti-ransomware autonome (ARP)]
+
Activez immédiatement une protection anti-ransomware autonome intelligente sur le stockage secondaire, en fonction du modèle de filtrage déjà effectué pour le stockage primaire.

+
Après un basculement, identifiez instantanément les attaques par ransomware sur le stockage secondaire. Une copie Snapshot est immédiatement prise des données qui commencent à être affectées, et les administrateurs sont avertis, ce qui contribue à arrêter une attaque et à améliorer la restauration.

* xref:../nas-audit/plan-fpolicy-event-config-concept.html[FPolicy]
+
Activation en un clic de ONTAP FPolicy pour activer le blocage automatique des fichiers malveillants connus l'activation simplifiée aide à se protéger contre les attaques de ransomware classiques qui utilisent des extensions de fichiers connues communes.

* xref:../system-admin/ontap-implements-audit-logging-concept.html[Renforcement de la sécurité : consignation sécurisée]
+
Consignation à toute épreuve dans ONTAP pour s'assurer que les comptes d'administrateur compromis ne peuvent pas masquer les actions malveillantes. L'administrateur et l'historique des utilisateurs ne peuvent pas être modifiés ou supprimés sans la connaissance des systèmes.

+
Consigner et auditer toutes les actions d'administration, quelle que soit leur origine, pour garantir la collecte de toutes les actions ayant un impact sur les données. Une alerte est générée chaque fois que les journaux d'audit du système ont été modifiés, de quelque manière que ce soit, pour prévenir les administrateurs de la modification.

* xref:../authentication/setup-ssh-multifactor-authentication-task.html[Renforcement de la sécurité : authentification multifacteur étendue]
+
L'authentification multifacteur (MFA) pour la CLI (SSH) prend en charge les dispositifs physiques à jetons Yubikey, garantissant ainsi qu'un attaquant ne peut pas accéder au système ONTAP à l'aide d'informations d'identification volées ou d'un système client compromis. Cisco DUO est pris en charge pour MFA avec System Manager.

* Dualité fichier/objet (accès multiprotocole)
+
La dualité fichier/objet permet un accès en lecture et en écriture natif du protocole S3 à la même source de données qui dispose déjà d'un accès au protocole NAS. Vous pouvez accéder simultanément à votre stockage en tant que fichiers ou en tant qu'objets à partir de la même source de données, ce qui vous évite d'avoir à dupliquer des copies des données pour les utiliser avec différents protocoles (S3 ou NAS), comme pour l'analytique qui utilise des données d'objet.

* xref:../flexgroup/manage-flexgroup-rebalance-task.html[Rééquilibrage FlexGroup]
+
Si les composants FlexGroup sont déséquilibrés, le FlexGroup peut être rééquilibré et géré sans interruption à partir du
CLI, API REST et System Manager. Pour des performances optimales, la capacité utilisée des membres d'un FlexGroup doit être répartie de façon égale.

* Amélioration de la capacité de stockage
+
La réservation d'espace WAFL a été considérablement réduite, ce qui donne jusqu'à 400 Tio de capacité utilisable supplémentaire par agrégat.





== Points forts de ONTAP 9.11.1

ONTAP 9.11.1 propose de nouvelles fonctionnalités améliorées dans les domaines de la sécurité, de la conservation, des performances, etc. Pour obtenir la liste complète des nouvelles fonctionnalités et améliorations, reportez-vous à la section xref:9111-reference.adoc[Nouveautés de ONTAP 9.11.1].

* xref:../multi-admin-verify/index.html[Vérification multi-administrateurs]
+
La vérification multiadministrateur est une approche native de vérification unique sur le marché qui requiert plusieurs approbations pour les tâches administratives sensibles telles que la suppression d'un Snapshot ou d'un volume. Les approbations requises dans une implémentation MAV empêchent les attaques malveillantes et les modifications accidentelles des données.

* xref:../anti-ransomware/index.html[Améliorations de la protection anti-ransomware autonome]
+
La protection anti-ransomware autonome (ARP) utilise le machine learning pour détecter les menaces de ransomware avec une granularité accrue. Vous pouvez ainsi identifier les menaces rapidement et accélérer la restauration en cas de violation.

* xref:../flexgroup/supported-unsupported-config-concept.html#features-supported-beginning-with-ontap-9-11-1[Conformité SnapLock pour les volumes FlexGroup]
+
Sécurisez des datasets de plusieurs pétaoctets pour des charges de travail telles que l'automatisation de la conception électronique, les médias et le divertissement en protégeant les données à l'aide du verrouillage des fichiers WORM afin qu'elles ne puissent pas être modifiées ou supprimées.

* xref:../flexgroup/fast-directory-delete-asynchronous-task.html[Suppression du répertoire asynchrone]
+
Avec ONTAP 9.11.1, la suppression des fichiers a lieu en arrière-plan du système ONTAP. Vous pouvez ainsi supprimer facilement les répertoires volumineux tout en éliminant les impacts sur les performances et la latence des E/S hôtes

* xref:../s3-config/index.html[Améliorations de S3]
+
Simplifiez et étendez les fonctionnalités de gestion des données d'objet S3 avec ONTAP, ainsi que des terminaux d'API supplémentaires et la gestion des versions d'objet au niveau du compartiment. Vous pouvez ainsi stocker plusieurs versions d'un objet dans le même compartiment.

* Améliorations apportées à System Manager
+
System Manager prend en charge des fonctionnalités avancées d'optimisation des ressources de stockage et d'amélioration de la gestion des audits. Ces mises à jour incluent des capacités améliorées de gestion et de configuration des agrégats de stockage, une meilleure visibilité sur l'analytique système et la visualisation matérielle des systèmes FAS.





== Points forts de ONTAP 9.10.1

ONTAP 9.10.1 inclut de nouvelles fonctionnalités améliorées dans les domaines du renforcement de la sécurité, de l'analytique des performances, de la prise en charge du protocole NVMe et des options de sauvegarde du stockage objet. Pour obtenir la liste complète des nouvelles fonctionnalités et améliorations, reportez-vous à la section xref:9101-reference.adoc[Nouveautés de ONTAP 9.10.1].

* xref:../anti-ransomware/index.html[Protection autonome contre les ransomwares]
+
La protection autonome contre les ransomware crée automatiquement une copie Snapshot de votre volume et alerte les administrateurs en cas d'activité anormale, ce qui vous permet de détecter rapidement les attaques par ransomware et de restaurer vos données plus rapidement.

* Améliorations apportées à System Manager
+
System Manager télécharge automatiquement les mises à jour de firmware pour les disques, les tiroirs et les processeurs de service, en plus de proposer de nouvelles intégrations avec NetApp Active IQ Digital Advisor, BlueXP et la gestion des certificats. Ces améliorations simplifient l'administration et assurent la continuité de l'activité.

* xref:../concept_nas_file_system_analytics_overview.html[Améliorations de l'analyse du système de fichiers]
+
L'analytique du système de fichiers fournit des outils de télémétrie supplémentaires pour identifier les principaux fichiers, répertoires et utilisateurs de votre partage de fichiers. Vous pouvez ainsi identifier les problèmes de performances des workloads afin d'améliorer la planification des ressources et l'implémentation de la QoS.

* xref:../nvme/support-limitations.html[Prise en charge de NVMe over TCP (NVMe/TCP) pour les systèmes AFF]
+
Obtenez une haute performance et réduisez le TCO de votre SAN d'entreprise et des workloads modernes sur un système AFF lorsque vous utilisez NVMe/TCP sur votre réseau Ethernet existant.

* xref:../nvme/support-limitations.html[Prise en charge de NVMe over Fibre Channel (NVMe/FC) pour les systèmes NetApp FAS]
+
Utilisez le protocole NVMe/FC sur vos baies hybrides pour permettre une migration uniforme vers NVMe.

* xref:../s3-snapmirror/index.html[Sauvegarde native dans le cloud hybride pour le stockage objet]
+
Protégez vos données ONTAP S3 avec les cibles de stockage objet de votre choix. Utilisez la réplication SnapMirror pour sauvegarder vos données dans un stockage sur site avec StorageGRID, dans le cloud avec Amazon S3 ou dans un autre compartiment ONTAP S3 sur des systèmes NetApp AFF et FAS.

* xref:../flexcache/global-file-locking-task.html[Verrouillage global des fichiers avec FlexCache]
+
Assurez la cohérence des fichiers aux emplacements du cache lors des mises à jour des fichiers source à l'origine avec un verrouillage global des fichiers à l'aide de FlexCache. Cette amélioration permet d'activer des verrouillages exclusifs de lecture de fichiers dans une relation origine-cache pour les charges de travail qui nécessitent un verrouillage amélioré.





== Points forts de ONTAP 9.9.1

ONTAP 9.91.1 inclut de nouvelles fonctionnalités améliorées dans les domaines de l'efficacité du stockage, de l'authentification multifacteur, de la reprise d'activité, etc. Pour obtenir la liste complète des nouvelles fonctionnalités et améliorations, reportez-vous à la section xref:991-reference.adoc[Nouveautés de ONTAP 9.9.1].

* Sécurité renforcée pour la gestion des accès à distance via l'interface de ligne de commande
+
La prise en charge du hachage de mot de passe SHA512 et SSH A512 protège les informations d'identification des comptes d'administrateur contre les agents malveillants qui tentent d'accéder au système.

* link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_and_cable_the_mcc_components.html["Améliorations MetroCluster IP : prise en charge des clusters à 8 nœuds"^]
+
La nouvelle limite est deux fois plus importante que la précédente. Elle prend en charge les configurations MetroCluster et assure la disponibilité continue des données.

* xref:../smbc/index.html[Améliorations de la continuité de l'activité SnapMirror]
+
Offre davantage d'options de réplication pour la sauvegarde et la reprise d'activité pour les conteneurs de données volumineux pour workloads NAS.

* xref:../san-admin/storage-virtualization-vmware-copy-offload-concept.html[Performances SAN améliorées]
+
Délivre des performances SAN jusqu'à quatre fois supérieures pour les applications à LUN uniques, telles que les datastores VMware, afin que vous puissiez atteindre les performances élevées dans votre environnement SAN.

* xref:../task_cloud_backup_data_using_cbs.html[Nouvelle option de stockage objet pour le cloud hybride]
+
StorageGRID peut être utilisé comme destination pour NetApp Cloud Backup Service afin de simplifier et d'automatiser la sauvegarde de vos données ONTAP sur site.



.Étapes suivantes
* xref:../upgrade/prepare.html[Mise à niveau vers la dernière version de ONTAP]
* xref:../upgrade/when-to-upgrade.html[Quand dois-je mettre à niveau ONTAP ?]

