---
permalink: release-notes/whats-new-9181.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 9.18.1' 
summary: Découvrez les nouvelles fonctionnalités disponibles dans ONTAP 9.18.1. 
---
= Nouveautés d' ONTAP 9.18.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez les nouvelles fonctionnalités disponibles dans ONTAP 9.18.1.

Pour plus d'informations sur les problèmes connus, les limites et les mises en garde de mise à niveau dans les dernières versions de ONTAP 9, consultez le https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Notes de mise à jour de ONTAP 9"^]. Vous devez vous connecter avec votre compte NetApp ou créer un compte pour accéder aux notes de version.

* Découvrez les nouveautés et les améliorations https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["Fonctionnalités ONTAP MetroCluster"^].
* En savoir plus sur  https://docs.netapp.com/us-en/ontap-afx/release-notes/whats-new-9171.html["nouvelles fonctionnalités logicielles ONTAP améliorées pour les systèmes de stockage NetApp AFX"^] .
* En savoir plus sur  https://docs.netapp.com/us-en/asa-r2/release-notes/whats-new-9171.html["nouvelles fonctionnalités logicielles ONTAP améliorées pour les systèmes de stockage NetApp ASA r2"^] .
* En savoir plus sur  https://docs.netapp.com/us-en/ontap-systems/whats-new.html["prise en charge nouvelle et améliorée des systèmes AFF, ASA et FAS et des commutateurs pris en charge"^] .
* En savoir plus sur les mises à jour du https://docs.netapp.com/us-en/ontap-automation/whats_new.html["L'API REST DE ONTAP"^].


Pour effectuer une mise à niveau vers la dernière version de ONTAP, reportez-vous à link:../upgrade/create-upgrade-plan.html["Préparez la mise à niveau de ONTAP"]la section .



== Protection des données

[cols="30%,70%"]
|===
| Mise à jour | Description 


 a| 
xref:../data-protection/cloud-backup-with-snapmirror-task.html[SnapMirror cloud : prise en charge pour MetroCluster FlexGroup volumes]
 a| 
SnapMirror cloud prend en charge les opérations de sauvegarde et de restauration pour les volumes FlexGroup dans les configurations MetroCluster.

|===


== Mise en réseau

[cols="30%,70%"]
|===
| Mise à jour | Description 


 a| 
xref:../networking/ipsec-prepare.html[Déchargement matériel IPsec, prise en charge d'IPv6]
 a| 
La prise en charge du déchargement matériel IPsec est étendue à IPv6.



 a| 
xref:../networking/configure_network_security_using_federal_information_processing_standards_fips.html[Algorithmes PQC d'OpenSSL]
 a| 
ONTAP prend en charge les algorithmes cryptographiques post-quantiques pour SSL. Ces algorithmes offrent une protection supplémentaire contre d'éventuelles futures attaques informatiques quantiques et sont disponibles lorsque le mode SSL FIPS est désactivé.



 a| 
xref:../networking/configure-backend-encryption.html[chiffrement du réseau du cluster dorsal ONTAP]
 a| 
Vous pouvez activer le chiffrement TLS pour les données en transit sur le réseau du cluster backend ONTAP .



 a| 
xref:../high-availability/ha-pair-encryption.html[ONTAP HA chiffrement du réseau de trafic]
 a| 
Vous pouvez activer le chiffrement du trafic entre les nœuds des paires à haute disponibilité (HA).

|===


== SAN

[cols="30%,70%"]
|===
| Mise à jour | Description 


 a| 
xref:../san-admin/nvme-copy-offload.html[Déchargement de copie NVMe]
 a| 
La fonction de déchargement de copie NVMe permet à un hôte NVMe de décharger les opérations de copie de son processeur vers le processeur du contrôleur de stockage ONTAP . L'hôte peut copier des données d'un espace de noms NVMe à un autre tout en réservant ses ressources CPU pour les charges de travail applicatives.

|===


== Stockage objet S3

[cols="30%,70%"]
|===
| Mise à jour | Description 


 a| 
xref:../s3-snapshots/list-restore-s3-snapshot.html[Prise en charge de la restauration d'instantanés S3 à un point précis dans le temps]
 a| 
Le compartiment de snapshots S3 est désormais accessible nativement avec l'interface de ligne de commande ONTAP. De plus, vous pouvez restaurer un objet unique, un ensemble d'objets ou un compartiment entier sur un client S3 à partir d'un snapshot S3.



 a| 
xref:../s3-multiprotocol/create-nas-bucket-task.html[Prise en charge de la création de compartiments NAS sur les volumes FlexCache]
 a| 
Vous pouvez créer des compartiments NAS sur les volumes FlexCache, et les applications peuvent accéder aux données sur les volumes FlexCache avec le protocole S3 lorsque tous les nœuds du cluster utilisent ONTAP 9.18.1 ou une version ultérieure. Pour plus de détails sur l’activation de l’accès S3 aux volumes NAS FlexCache, consultez link:../flexcache/enable-flexcache-duality.html["Activer l'accès S3 aux volumes NAS FlexCache"].

|===


== Sécurité

[cols="30%,70%"]
|===
| Mise à jour | Description 


 a| 
xref:../anti-ransomware/use-cases-restrictions-concept.html#supported-configurations[Prise en charge des volumes FlexGroup pour ARP/AI]
 a| 
Les volumes NetApp FlexGroup prennent en charge ARP/AI, offrant une détection et une protection avancées contre les ransomwares basées sur l'apprentissage automatique.  Dans ONTAP 9.17.1 et versions antérieures, seule la première génération d'ARP était disponible pour les volumes FlexGroup .  À partir d' ONTAP 9.18.1, les volumes FlexGroup ont la même valeur que les volumes FlexVol sur les plateformes ONTAP sur site (AFF et FAS) et sur les déploiements ONTAP virtuels (y compris Cloud Volumes ONTAP et ONTAP Select).  Par conséquent, ARP/AI devient la technologie ARP par défaut pour les volumes FlexVol et FlexGroup .



 a| 
xref:../anti-ransomware/index.html#enablement-options-for-arp[ARP/AI est activé par défaut pour les nouveaux volumes sur les systèmes pris en charge]
 a| 
Lorsque vous créez un nouveau cluster ou mettez à niveau votre cluster vers la version 9.18.1, ARP/AI est automatiquement activé par défaut sur tous les nouveaux volumes pour AFF A series, AFF C series, ASA, et https://docs.netapp.com/us-en/asa-r2/secure-data/enable-anti-ransomware-protection.html["ASA r2"] systèmes après un délai de grâce de 12 heures. Pendant ce délai de grâce, vous pouvez refuser l’activation par défaut.

|===


== Améliorations de la gestion des ressources de stockage

[cols="30%,70%"]
|===
| Mise à jour | Description 


 a| 
xref:../performance-admin/adaptive-qos-policy-groups-task.html[Prise en charge des groupes de stratégies QoS imbriqués à deux niveaux sur les SVM et les volumes]
 a| 
Vous pouvez attribuer une politique QoS à une SVM et aux volumes situés sous cette SVM simultanément.



 a| 
xref:../flexcache/create-volume-task.html[Créer des volumes SVM FlexCache à partir de volumes d'origine dans une relation SVM-DR]
 a| 
Vous pouvez créer des volumes SVM FlexCache à partir de volumes d'origine qui font partie d'une relation SVM-DR.



 a| 
xref:../volumes/commands-display-space-usage-reference.html[Commandes permettant d'afficher les informations d'utilisation de l'espace]
 a| 
Dans ONTAP 9.18.1 et versions ultérieures, la  `storage aggregate show-space` commande modifie la façon dont la capacité logique référencée et la capacité logique non référencée sont rapportées. La capacité logique référencée comptabilise les blocs référencés dans tous les objets et les blocs non référencés dans les objets fragmentés. La capacité logique non référencée comptabilise uniquement les blocs non référencés dans les objets ayant dépassé le seuil de saturation et pouvant être supprimés ou défragmentés.

Par exemple, lorsque vous utilisez le seuil de remplissage agrégé par défaut de 40 % pour ONTAP S3 et StorageGRID, 60 % des blocs d’un objet doivent être non référencés avant que les blocs ne soient signalés comme capacité non référencée.

Dans les versions antérieures à ONTAP 9.18.1, la capacité logique référencée indique les blocs référencés dans tous les objets (complets et fragmentés). La capacité logique non référencée indique les blocs non référencés dans tous les objets.

|===