---
permalink: release-notes/whats-new-9191.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 9.19.1' 
summary: Découvrez les nouvelles fonctionnalités disponibles dans ONTAP 9.19.1. 
---
= Nouveautés d'ONTAP 9.19.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez les nouvelles fonctionnalités disponibles dans ONTAP 9.19.1.

Pour plus d'informations sur les problèmes connus, les limites et les mises en garde de mise à niveau dans les dernières versions de ONTAP 9, consultez le https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Notes de mise à jour de ONTAP 9"^]. Vous devez vous connecter avec votre compte NetApp ou créer un compte pour accéder aux notes de version.

* Découvrez les nouveautés et les améliorations https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["Fonctionnalités ONTAP MetroCluster"^].
* En savoir plus sur  https://docs.netapp.com/us-en/ontap-afx/release-notes/whats-new-9171.html["nouvelles fonctionnalités logicielles ONTAP améliorées pour les systèmes de stockage NetApp AFX"^] .
* En savoir plus sur  https://docs.netapp.com/us-en/asa-r2/release-notes/whats-new-9171.html["nouvelles fonctionnalités logicielles ONTAP améliorées pour les systèmes de stockage NetApp ASA r2"^] .
* En savoir plus sur  https://docs.netapp.com/us-en/ontap-systems/whats-new.html["prise en charge nouvelle et améliorée des systèmes AFF, ASA et FAS et des commutateurs pris en charge"^] .
* En savoir plus sur les mises à jour du https://docs.netapp.com/us-en/ontap-automation/whats_new.html["L'API REST DE ONTAP"^].


Pour effectuer une mise à niveau vers la dernière version de ONTAP, reportez-vous à link:../upgrade/create-upgrade-plan.html["Préparez la mise à niveau de ONTAP"]la section .



[[data-protection]]
== Protection des données

[cols="30%,70%"]
|===
| Mise à jour | Description 


 a| 
xref:../snapmirror-active-sync/interoperability-reference.html[SnapMirror active sync prend en charge le basculement transparent des applications pour AIX]
 a| 
SnapMirror active sync pour les architectures symétriques actives/actives prend en charge le basculement transparent avec un RPO nul pour AIX sur des clusters à 2 nœuds.



 a| 
xref:../data-protection/cloud-backup-with-snapmirror-task.html#restore-from-the-cloud[SnapMirror les limites de prise en charge du cloud sont augmentées à 100 compartiments S3]
 a| 
SnapMirror cloud augmente à 100 le nombre de compartiments S3 pris en charge.



 a| 
xref:../snaplock/snapshot-lock-concept.html[SnapMirror synchrone prend en charge le verrouillage inviolable des snapshots]
 a| 
Vous pouvez utiliser le verrouillage d'instantané inviolable avec la synchronisation SnapMirror .



 a| 
xref:../data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html[SnapMirror synchronous prend en charge la réplication des instantanés planifiés vers le volume de destination]
 a| 
Vous pouvez répliquer les instantanés planifiés sur le volume de destination avec SnapMirror synchrone.



 a| 
xref:../snapmirror-active-sync/protect-nas-task.html[SnapMirror prise en charge de la synchronisation active pour NAS]
 a| 
SnapMirror active sync prend en charge les charges de travail NAS au niveau SVM en utilisant NFS et SMB sur les clusters AFF (2 nœuds uniquement) ou  https://docs.netapp.com/us-en/ontap-afx/release-notes/whats-new-9191.html["AFX"] clusters (4 nœuds uniquement), avec un accès en lecture-écriture uniquement sur le primaire.

|===


[[nas]]
== NAS

[cols="30%,70%"]
|===
| Mise à jour | Description 


 a| 
xref:../flexcache/index.html[Amélioration des performances du NAS]
 a| 
ONTAP 9.19.1 alloue davantage de ressources CPU au traitement des requêtes de listage des petits répertoires NAS. Cette amélioration bénéficie aux clients ayant des centaines à des milliers de clients listant simultanément le même petit répertoire NAS, d'une taille de 2 Mo ou moins (environ 25 000 fichiers).

Cette amélioration réduit le recours à des solutions de contournement, comme l'utilisation de volumes FlexCache locaux, pour gérer un grand nombre de clients effectuant des listes de répertoires. Pour un nombre de clients plus faible, les performances ne seront pas affectées. Cette amélioration des performances est automatique et ne nécessite aucune configuration.

|===


[[networking]]
== Mise en réseau

[cols="30%,70%"]
|===
| Mise à jour | Description 


 a| 
Gérer les versions NFS prises en charge par le SVM
 a| 
La prise en charge de NFSv4.2 est gérée indépendamment des paramètres NFSv4.1, ce qui permet à chaque SVM d'activer ou de désactiver les fonctionnalités NFSv4.2 selon les besoins. Par défaut, NFSv4.2 est activé lors de la création d'un nouveau service NFS, sauf s'il est explicitement désactivé par l'administrateur.

* xref:../nfs-admin/enable-disable-nfs-task.html[Activer ou désactiver NFSv4.2 pour les SVM ONTAP]
* https://docs.netapp.com/us-en/ontap/task_nas_enable_linux_nfs.html["Activer le stockage NAS pour les serveurs Linux à l'aide de NFS avec ONTAP System Manager"]




 a| 
xref:../concepts/path-failover-concept.html#nas-path-failover[Amélioration du basculement LIF]
 a| 
La stratégie de groupe de basculement définie par le système ONTAP étend dynamiquement les cibles de basculement des LIF de données NAS afin d'inclure potentiellement tous les ports disponibles dans le domaine de diffusion sur n'importe quel nœud disponible du cluster. Vous pouvez appliquer la stratégie définie par le système à n'importe quel groupe de basculement. Avant ONTAP 9.19.1, les LIF dotées de cette stratégie ne pouvaient basculer que vers un seul autre nœud du cluster ; si ce nœud était hors quorum, le basculement ne s'effectuait pas, même si d'autres nœuds étaient disponibles.



 a| 
link:../networking/improve-tcp-wan-performance.html["Améliorations des performances TCP"]
 a| 
ONTAP améliore les performances de transfert de données TCP sur les liaisons WAN sujettes aux pertes et à une latence élevée en intégrant deux fonctions de récupération des pertes, PRR et RACK, dans la pile TCP d'ONTAP. PRR convient à tous les réseaux et est activé par défaut. RACK convient aux réseaux congestionnés avec des débits d'environ 25 Gigabits/seconde et est désactivé par défaut.

|===


[[san]]
== SAN

[cols="30%,70%"]
|===
| Mise à jour | Description 


 a| 
xref:../san-config/configure-fc-nvme-hosts-ha-pairs-reference.html[Prise en charge des configurations FC à connexion directe]
 a| 
Il n'est pas nécessaire de recourir à des commutateurs FC pour connecter des hôtes FC et FC-NVMe au stockage ONTAP. Les hôtes peuvent se connecter directement aux ports d'adaptateur FC sur les systèmes AFF, ASA et FAS. Cette connexion directe est particulièrement utile sur les sites distants et dans les environnements hybrides où la simplicité est primordiale.



 a| 
xref:../san-admin/multipath-automatic-lif-failover-support.html[Prise en charge du multipathing actif-actif sur les systèmes AFF]
 a| 
Les systèmes AFF prennent en charge le multipathing actif-actif dans les environnements SAN. Dans les configurations actives-actives, tous les chemins au sein de la paire haute disponibilité qui possède le LUN ou l’espace de noms sont actifs-optimisés, de sorte qu’en cas de basculement du stockage, l’hôte n’a pas besoin d’attendre la transition ALUA ou ANA des chemins de basculement pour reprendre les E/S. Cela réduit le temps de basculement, permettant aux clients SAN d’exécuter des charges de travail critiques sur les systèmes AFF avec la même résilience des chemins sans interruption et le même équilibrage de charge qui étaient auparavant disponibles uniquement sur les systèmes ASA.



 a| 
xref:../san-admin/multipath-automatic-lif-failover-support.html[Prise en charge améliorée du basculement automatique des SAN LIF]
 a| 
Le basculement automatique des LIF est pris en charge sur les systèmes AFF et ASA pour les LIF de protocole iSCSI dans les configurations multipath actives-actives et actives-actives-scsi uniquement, ainsi que pour les LIF de protocole NVMe/TCP dans les configurations multipath actives-actives.



 a| 
link:https://docs.netapp.com/us-en/ontap-fli/get-started/learn-about-data-migration.html["Prise en charge de l'importation de LUN externes pour le protocole iSCSI"^]
 a| 
L'importation de LUN étrangères (FLI) prend en charge le protocole iSCSI pour la connectivité du backend.

|===


[[s3-object-storage]]
== Stockage objet S3

[cols="30%,70%"]
|===
| Mise à jour | Description 


 a| 
xref:../s3-config/create-modify-bucket-policy-task.html[Prise en charge par ONTAP S3 des écritures et suppressions conditionnelles avec application]
 a| 
Vous pouvez utiliser des conditions pour imposer des écritures conditionnelles lors du chargement d'objets et des suppressions conditionnelles lors de la suppression d'objets. Les écritures et suppressions conditionnelles offrent un moyen d'empêcher l'écrasement ou la suppression non intentionnelle d'objets.



 a| 
xref:../s3-config/regenerate-access-keys.html[Clés ONTAP S3]
 a| 
Pour maintenir l'accès des utilisateurs aux ressources S3 si la clé d'accès d'origine expire, les administrateurs du cluster ONTAP peuvent générer une deuxième clé d'accès pour chaque utilisateur S3.

|===


[[security]]
== Sécurité

[cols="30%,70%"]
|===
| Mise à jour | Description 


 a| 
Les caractéristiques de charge de travail ARP ont été supprimées de l’interface utilisateur de System Manager.
 a| 
Le Gestionnaire système n'affiche plus les caractéristiques de charge de travail de la protection autonome contre les ransomwares (ARP), notamment les statistiques de base et de pic d'activité. Ces informations ont été supprimées car les pics d'activité étaient fréquemment interprétés à tort comme une véritable attaque de ransomware ou comme nécessitant un réglage manuel.

Le comportement et la détection ARP restent inchangés, seule la présentation de ces informations dans System Manager est affectée. Les statistiques de surtension restent disponibles via l’interface de ligne de commande ONTAP et l’API REST ONTAP pour une analyse avancée.



 a| 
xref:../networking/configure-tls-offload.html[Configuration de déchargement TLS]
 a| 
Vous pouvez configurer le déchargement TLS pour améliorer les performances après l'établissement de la liaison TLS en exploitant les ressources des cartes Ethernet compatibles. Cette fonctionnalité décharge le chiffrement et le déchiffrement, réduisant ainsi la charge du processeur et améliorant les performances.



 a| 
xref:../nfs-admin/enable-nfs-over-tls-task.html[Activez NFS sur TLS pour chiffrer le trafic NFS en transit]
 a| 
Vous pouvez activer NFS sur TLS avec TLS 1.3 pour chiffrer le trafic NFS en transit sur les SVM compatibles NFS. Cette amélioration contribue à protéger les données NFS contre l'interception ou la falsification sur les réseaux non sécurisés. Cette version prend également en charge l'authentification TLS mutuelle optionnelle par LIF et les contrôles de règles d'export afin de refuser l'accès TCP non TLS aux clients concernés.



 a| 
xref:../anti-ransomware/use-cases-restrictions-concept.html#snapmirror[Prise en charge de la protection autonome contre les ransomwares pour SnapMirror synchrone et SnapMirror active sync]
 a| 
ARP/AI protège les volumes primaires dans les relations SnapMirror synchrones (NAS et SAN) sur les systèmes FAS, AFF et  https://docs.netapp.com/us-en/ontap-afx/release-notes/whats-new-9191.html["AFX"] , ainsi que dans les relations SnapMirror active sync SAN sur les systèmes AFF et  https://docs.netapp.com/us-en/asa-r2/release-notes/whats-new-9191.html["ASA r2"] . La détection s’effectue sur le primaire actif en lecture-écriture, où les instantanés ARP sont créés (les instantanés ne sont pas répliqués).

Les clusters mis à niveau vers ONTAP 9.19.1, dont l’activation par défaut d’ARP avait été supprimée en raison de relations de réplication synchrone, verront cette activation automatiquement rétablie. Un avertissement avant la mise à jour informe les administrateurs et leur offre la possibilité de la désactiver.



 a| 
xref:../authentication-access-control/webauthn-mfa-overview.html[WebAuthn Amélioration du domaine de la partie de confiance]
 a| 
ONTAP 9.19.1 introduit un nouveau paramètre `-rp-domains` dans la commande des paramètres globaux WebAuthn, qui permet aux administrateurs de restreindre explicitement l'ensemble des domaines de Relying Party (RP) autorisés acceptés lors de l'authentification multifactorielle WebAuthn (FIDO2) dans System Manager.

|===


[[storage-resource-management-enhancements]]
== Améliorations de la gestion des ressources de stockage

[cols="30%,70%"]
|===
| Mise à jour | Description 


 a| 
xref:../concepts/capacity-measurements.html[Rapports améliorés sur l'espace volumétrique]
 a| 
Vous pouvez utiliser la commande  `volume show-space` pour afficher des détails sur l’utilisation de l’espace au sein d’un volume. À partir de ONTAP 9.19.1, le répertoire utilisé pour le rapport d’espace est inclus dans le résultat de la commande.



 a| 
xref:../performance-admin/guarantee-throughput-qos-task.html[Prise en charge de la modification des paramètres par défaut qui contrôlent les augmentations automatiques du plafond de débit QoS]
 a| 
Vous pouvez modifier les paramètres par défaut qui déterminent comment les groupes de stratégies QoS augmentent automatiquement le plafond de débit QoS en réponse à des besoins ponctuels de performances accrues. Ces paramètres ne sont pas modifiables dans ONTAP 9.18.1 et les versions antérieures.

|===


[[system-manager]]
== System Manager

[cols="30%,70%"]
|===
| Mise à jour | Description 


 a| 
xref:../concept-svm-admin-dashboard-sm.html[Surveillez et gérez le SVM à l'aide du nouveau tableau de bord ONTAP System Manager]
 a| 
Un nouveau tableau de bord dédié permet aux administrateurs de SVM de surveiller et de gérer leurs propres SVM. Ceci est particulièrement utile dans un environnement ONTAP mutualisé, où l'administrateur du cluster peut fournir un tableau de bord SVM à chaque locataire.

|===


[[upgrade]]
== Mise à niveau

[cols="30%,70%"]
|===
| Mise à jour | Description 


 a| 
xref:../upgrade/automated-pre-checks.html[Amélioration des rapports pour les vérifications préalables automatisées des mises à niveau]
 a| 
Lors de l'exécution des vérifications automatisées préalables à la mise à niveau, les erreurs et les avertissements sont affichés séparément afin de vous aider à identifier facilement les problèmes qui doivent être résolus avant la mise à niveau.

|===