---
permalink: release-notes/whats-new-9171.html 
sidebar: sidebar 
keywords: 'what"s new, release notes, 9.17.1' 
summary: Découvrez les nouvelles fonctionnalités disponibles dans ONTAP 9.17.1. 
---
= Quoi de neuf dans ONTAP 9.17.1
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Découvrez les nouvelles fonctionnalités disponibles dans ONTAP 9.17.1.

Pour plus d'informations sur les problèmes connus, les limites et les mises en garde de mise à niveau dans les dernières versions de ONTAP 9, consultez le https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["Notes de mise à jour de ONTAP 9"^]. Vous devez vous connecter avec votre compte NetApp ou créer un compte pour accéder aux notes de version.

* Découvrez les nouveautés et les améliorations https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["Fonctionnalités ONTAP MetroCluster"^].
* En savoir plus sur  https://docs.netapp.com/us-en/ontap-afx/release-notes/whats-new-9171.html["nouvelles fonctionnalités logicielles ONTAP améliorées pour les systèmes de stockage NetApp AFX"^] .
* En savoir plus sur  https://docs.netapp.com/us-en/asa-r2/release-notes/whats-new-9171.html["nouvelles fonctionnalités logicielles ONTAP améliorées pour les systèmes de stockage NetApp ASA r2"^] .
* En savoir plus sur  https://docs.netapp.com/us-en/ontap-systems/whats-new.html["prise en charge nouvelle et améliorée des systèmes AFF, ASA et FAS et des commutateurs pris en charge"^] .
* En savoir plus sur les mises à jour du https://docs.netapp.com/us-en/ontap-automation/whats_new.html["L'API REST DE ONTAP"^].


Pour effectuer une mise à niveau vers la dernière version de ONTAP, reportez-vous à link:../upgrade/create-upgrade-plan.html["Préparez la mise à niveau de ONTAP"]la section .



== Protection des données

[cols="30%,70%"]
|===
| Mise à jour | Description 


 a| 
xref:../nvme/support-limitations.html#features[Prise en charge de la synchronisation active SnapMirror pour l'accès hôte via NVMe]
 a| 
SnapMirror Active Sync prend désormais en charge l'accès NVMe pour les charges de travail VMware avec accès hôte NVMe/TCP et NVMe/FC pour les clusters ONTAP à deux nœuds. La prise en charge de NVMe/TCP pour les charges de travail VMware dépend de la correction des bugs VMware.



 a| 
xref:../snapmirror-active-sync/index.html[Prise en charge d' ONTAP Cloud Mediator avec la synchronisation active SnapMirror]
 a| 
ONTAP Cloud Mediator a été introduit dans ONTAP 9.17.1 et prend en charge les relations de synchronisation active SnapMirror . Ce médiateur cloud, comme ONTAP Mediator, agit comme témoin de quorum pour les relations de synchronisation active SnapMirror , garantissant un basculement transparent tout en réduisant la complexité opérationnelle liée à la maintenance et à la gestion d'un site tiers.

|===


== Stockage objet S3

[cols="30%,70%"]
|===
| Mise à jour | Description 


 a| 
xref:../s3-multiprotocol/index.html[Prise en charge de l'action CopyObject dans les compartiments NAS ONTAP S3]
 a| 
L'action CopyObject est prise en charge dans le bucket NAS ONTAP S3.



 a| 
xref:../s3-multiprotocol/create-nas-bucket-task.html[Prise en charge de la liaison d'un bucket NAS S3 à un chemin de jonction]
 a| 
Lors de la création d'un bucket NAS S3 avec l'interface de ligne de commande ONTAP , vous pouvez choisir de lier le bucket au volume plutôt qu'au chemin de jonction. Lors de la liaison au volume, le chemin de jonction est automatiquement mis à jour si celui-ci change, par exemple lors du démontage ou du montage d'un volume.



 a| 
xref:../s3-multiprotocol/index.html#object-multipart-upload[Prise en charge multiprotocole S3 pour le balisage et les métadonnées]
 a| 
Les paires clé/valeur de marquage et de métadonnées utilisateur sont prises en charge par l'action CreateMultipartUpload dans les environnements multiprotocoles (S3 et NAS).

|===


== Sécurité

[cols="30%,70%"]
|===
| Mise à jour | Description 


 a| 
xref:../anti-ransomware/index.html[Prise en charge supplémentaire de l'hyperviseur]
 a| 
À partir d'ONTAP 9.17.1P5, la protection autonome contre les ransomwares prend en charge les hyperviseurs Hyper-V, KVM et OpenStack.



 a| 
xref:../anti-ransomware/index.html[Mises à jour instantanées de la protection autonome contre les ransomwares]
 a| 
ONTAP introduit plusieurs mises à jour concernant les instantanés ARP.



 a| 
xref:../system-admin/use-hsts-task.html[Prise en charge de HTTP Strict Transport Security (HSTS)]
 a| 
ONTAP prend en charge HTTP Strict Transport Security pour les services Web, permettant l'application d'une communication HTTPS sécurisée entre le navigateur d'un utilisateur et ONTAP.



 a| 
xref:../networking/ipsec-prepare.html[Déchargement matériel IPsec avec groupes d'agrégation de liens]
 a| 
ONTAP prend en charge le déchargement matériel IPsec pour les groupes d'agrégation de liens, étendant la prise en charge du déchargement matériel introduite dans la version 9.16.1.



 a| 
xref:../networking/ipsec-prepare.html[Prise en charge des clés pré-partagées post-quantiques IPsec]
 a| 
ONTAP prend en charge les clés pré-partagées post-quantiques pour IPsec afin de se protéger contre d'éventuelles futures attaques informatiques quantiques.



 a| 
xref:../encryption-at-rest/manage-keys-barbican-task.html[Prise en charge du gestionnaire de clés OpenStack Barbican]
 a| 
ONTAP prend en charge le gestionnaire de clés Barbican d'OpenStack pour les clés NetApp Volume Encryption (NVE).



 a| 
xref:../authentication/configure-jit-elevation-task.html[Prise en charge de l'élévation des privilèges juste à temps (JIT)]
 a| 
ONTAP prend en charge l'élévation des privilèges JIT pour le contrôle d'accès basé sur les rôles (RBAC). Les utilisateurs peuvent demander une élévation temporaire vers un rôle configuré, leur permettant ainsi d'accéder à des commandes privilégiées à la demande. Les administrateurs de cluster peuvent configurer qui peut accéder à l'élévation des privilèges JIT, ainsi que le moment et la durée de l'accès.



 a| 
xref:../system-admin/configure-saml-authentication-task.html[Prise en charge d'Entra IdP et de la prise en charge du groupe IdP pour l'authentification SAML]
 a| 
ONTAP prend en charge Microsoft Entra comme fournisseur d'identité SAML. De plus, les informations de groupe fournies par le fournisseur d'identité peuvent être mappées aux rôles ONTAP .



 a| 
xref:../system-admin/audit-manage-cross-cluster-requests.html[Audit des demandes inter-clusters]
 a| 
Vous pouvez configurer et exécuter des opérations d'audit sur le cluster source initial et le cluster de destination (en cours d'exécution). Dans les versions précédentes, seul le cluster recevant la requête du client effectuait l'audit. Grâce à cette fonctionnalité, un cluster appairé qui répond à une requête inter-clusters enregistre également l'activité. Ces opérations d'audit peuvent être activées et étendues à toute requête SET ou GET initiée dans ONTAP.



 a| 
xref:../anti-ransomware/index.html[Prise en charge du SAN avec protection autonome contre les ransomwares]
 a| 
ARP prend en charge les volumes SAN avec détection des anomalies basée sur le chiffrement, introduit de nouvelles commandes pour des statistiques d'entropie détaillées et unifie la messagerie de protection contre les ransomwares dans System Manager, auparavant axée sur le NAS. Des seuils de détection configurables et une conservation des snapshots plus déterministe offrent une plus grande flexibilité pour diverses charges de travail.

|===


== Améliorations de la gestion des ressources de stockage

[cols="30%,70%"]
|===
| Mise à jour | Description 


 a| 
xref:../task_nas_file_system_analytics_enable.html[FSA activé par défaut pour les nouveaux volumes]
 a| 
Les volumes créés sur des SVM nouvellement créées sur des clusters ONTAP alloués aux protocoles NAS ont l'analyse du système de fichiers (FSA) activée par défaut. L'analyse du système de fichiers (FSA) est automatiquement activée dès la création d'un volume, offrant des capacités d'analyse immédiates sans configuration supplémentaire.



 a| 
xref:../flexgroup/fast-directory-delete-asynchronous-task.html[Prise en charge améliorée de l'affichage de la progression de la suppression directe sur les volumes FlexGroup]
 a| 
La commande CLI ONTAP  `volume file async-delete show` a été amélioré pour inclure les tâches de suppression asynchrones émises par les clients.

|===