---
permalink: fabricpool/assign-new-tag-volume-creation-task.html 
sidebar: sidebar 
keywords: assigning, new tag, volume creation 
summary: 'Vous pouvez créer une nouvelle balise d"objet lorsque vous souhaitez affecter une ou plusieurs balises à de nouveaux objets qui sont placés à un niveau à partir d"un nouveau volume que vous créez.' 
---
= Attribuez une nouvelle balise lors de la création du volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer une nouvelle balise d'objet lorsque vous souhaitez affecter une ou plusieurs balises à de nouveaux objets qui sont placés à un niveau à partir d'un nouveau volume que vous créez. Les balises permettent de classer et de trier les objets de hiérarchisation pour plus de facilité la gestion des données. À partir de ONTAP 9.8, vous pouvez utiliser System Manager pour créer des balises d'objet.

Vous pouvez définir des balises uniquement sur les volumes FabricPool reliés à StorageGRID. Ces balises sont conservées lors du déplacement de volume.

* Un maximum de 4 balises par volume est autorisé
* Dans l'interface de ligne de commandes, chaque balise d'objet doit être une paire clé-valeur séparée par un signe égal (`""`)
* Dans l'interface de ligne de commandes, plusieurs balises doivent être séparées par une virgule (`""`)
* Chaque valeur de balise peut contenir un maximum de 127 caractères
* Chaque touche de balise doit commencer par un caractère alphabétique ou un trait de soulignement.
+
Les touches ne doivent contenir que des caractères alphanumériques et des traits de soulignement, et le nombre maximum de caractères autorisé est de 127.





== Procédure

Vous pouvez attribuer des balises d'objet à l'aide de ONTAP System Manager ou de l'interface de ligne de commandes de ONTAP.

[role="tabbed-block"]
====
.System Manager
--
. Accédez à *stockage > niveaux*.
. Localisez un niveau de stockage contenant les volumes à marquer.
. Cliquez sur l'onglet *volumes*.
. Localisez le volume que vous souhaitez marquer et dans la colonne *balises d'objet*, sélectionnez *cliquez pour entrer des balises*.
. Entrez une clé et une valeur.
. Cliquez sur *appliquer*.


--
.CLI
--
. Utilisez le `volume create` commande avec `-tiering-object-tags` option permettant de créer un nouveau volume avec les balises spécifiées. Vous pouvez spécifier plusieurs balises dans des paires séparées par des virgules :
+
[listing]
----
volume create [ -vserver <vserver name> ] -volume <volume_name> -tiering-object-tags <key1=value1> [
    ,<key2=value2>,<key3=value3>,<key4=value4> ]
----
+
L'exemple suivant illustre la création d'un volume nommé fp_Volume 1 avec trois balises d'objet.

+
[listing]
----
vol create -volume fp_volume1 -vserver vs0 -tiering-object-tags project=fabricpool,type=abc,content=data
----


--
====