---
permalink: fabricpool/benefits-storage-tiers-concept.html 
sidebar: sidebar 
keywords: benefits, storage, tiers, using, fabricpool 
summary: 'La configuration d"un agrégat pour utiliser FabricPool permet d"utiliser des niveaux de stockage. Vous pouvez équilibrer efficacement les performances et le coût de votre système de stockage, surveiller et optimiser l"utilisation de l"espace, et effectuer le déplacement des données basé sur des règles entre les tiers de stockage.' 
---
= Avantages des niveaux de stockage à l'aide de FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La configuration d'un agrégat pour utiliser FabricPool permet d'utiliser des niveaux de stockage. Vous pouvez équilibrer efficacement les performances et le coût de votre système de stockage, surveiller et optimiser l'utilisation de l'espace, et effectuer le déplacement des données basé sur des règles entre les tiers de stockage.

* Vous pouvez optimiser les performances de stockage et réduire les coûts de stockage en stockant les données dans un niveau basé sur la fréquence d'accès aux données.
+
** Les données fréquemment utilisées (« actives ») sont stockées dans le _Tier de performance_.
+
Le niveau de performance utilise un stockage primaire haute performance, comme un agrégat 100 % Flash (100 % SSD) du système de stockage.

** Les données rarement utilisées (« inactives ») sont stockées dans le _Cloud Tier_, également appelé _Capacity Tier_.
+
Le Tier cloud utilise un magasin d'objets moins coûteux et ne requiert pas de hautes performances.



* Vous avez la possibilité de spécifier le niveau dans lequel les données doivent être stockées.
+
Vous pouvez spécifier l'une des options de règles de Tiering prises en charge au niveau du volume. Avec ces options, vous pouvez déplacer efficacement les données entre les tiers quand elles sont actives ou inactives.

+
link:tiering-policies-concept.html#types-of-fabricpool-tiering-policies["Types de règles de Tiering FabricPool"]

* Vous pouvez choisir l'un des magasins d'objets pris en charge à utiliser comme Tier cloud pour FabricPool.
* Vous pouvez surveiller l'utilisation de l'espace dans un agrégat compatible FabricPool.
* Vous pouvez connaître la quantité de données inactives d'un volume grâce au reporting des données inactives.
* Vous pouvez réduire l'empreinte sur site du système de stockage.
+
Nous économisons de l'espace physique lorsque vous utilisez un magasin d'objets basé dans le cloud pour le Tier cloud.


