---
permalink: fabricpool/enable-disable-volume-cloud-write-task.html 
sidebar: sidebar 
keywords: creating, volume, fabricpool, cloud write, enable, disable 
summary: 'Depuis ONTAP 9.14.1, vous pouvez activer et désactiver le mode d"écriture cloud sur un volume nouveau ou existant d"un FabricPool afin que les clients NFS puissent écrire des données directement sur le cloud.' 
---
= Activez et désactivez les volumes pour écrire directement dans le cloud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À partir de ONTAP 9.14.1, vous pouvez activer et désactiver le mode d'écriture dans le cloud sur un volume nouveau ou existant d'un FabricPool, afin que les clients NFS puissent écrire des données directement dans le cloud sans attendre les analyses de Tiering. Les clients SMB écrivent toujours dans le Tier de performance dans un volume cloud compatible avec l'écriture. Le mode d'écriture dans le cloud est désactivé par défaut.

Le mode d'écriture cloud s'avère utile pour les migrations, par exemple lorsqu'un grand volume de données est transféré vers un cluster que le cluster ne peut prendre en charge sur le niveau local. Sans le mode d'écriture dans le cloud, lors d'une migration, de petites quantités de données sont transférées, puis hiérarchisées, puis transférées et de nouveau hiérarchisées jusqu'à la fin de la migration. Avec le mode d'écriture dans le cloud, ce type de gestion n'est plus nécessaire, car les données ne sont jamais transférées vers le Tier local.

.Avant de commencer
* Vous devez être administrateur de cluster ou SVM.
* Vous devez avoir le niveau de privilège avancé.
* Le volume doit être de type lecture-écriture.
* Le volume doit disposer de la règle de hiérarchisation TOTALE.




== Activez l'écriture cloud lors de la création du volume

.Étapes
. Définissez le niveau de privilège sur avancé :
+
[source, cli]
----
set -privilege advanced
----
. Créer un volume et activer le mode d'écriture cloud :
+
[source, cli]
----
volume create -volume <volume name> -is-cloud-write-enabled <true|false> -aggregate <local tier name>
----
+
L'exemple suivant illustre la création d'un volume nommé vol1 avec l'écriture cloud activée sur le Tier local FabricPool (aggr1) :

+
[listing]
----
volume create -volume vol1 -is-cloud-write-enabled true -aggregate aggr1
----




== Activez l'écriture cloud sur un volume existant

.Étapes
. Définissez le niveau de privilège sur avancé :
+
[source, cli]
----
set -privilege advanced
----
. Modifier un volume pour activer le mode d'écriture cloud :
+
[source, cli]
----
volume modify -volume <volume name> -is-cloud-write-enabled <true|false> -aggregate <local tier name>
----
+
L'exemple suivant modifie un volume nommé vol1 avec l'écriture cloud activée sur le niveau local FabricPool (aggr1) :

+
[listing]
----
volume modify -volume vol1 -is-cloud-write-enabled true -aggregate aggr1
----




== Désactiver l'écriture cloud sur un volume

.Étapes
. Définissez le niveau de privilège sur avancé :
+
[source, cli]
----
set -privilege advanced
----
. Désactiver le mode d'écriture cloud :
+
[source, cli]
----
volume modify -volume <volume name> -is-cloud-write-enabled <true|false> -aggregate <aggregate name>
----
+
L'exemple suivant illustre la création d'un volume nommé vol1 avec l'écriture dans le cloud activée :

+
[listing]
----
volume modify -volume vol1 -is-cloud-write-enabled false -aggregate aggr1
----

