---
permalink: fabricpool/index.html 
sidebar: sidebar 
keywords: deciding, use, managing, storage tiers, fabricpool 
summary: 'Vous pouvez utiliser FabricPool pour procéder au Tiering automatique des données, en fonction de la fréquence d"accès aux données.' 
---
= Présentation de la gestion des niveaux FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser FabricPool pour procéder au Tiering automatique des données, en fonction de la fréquence d'accès aux données.

FabricPool est une solution de stockage hybride qui utilise un agrégat 100 % Flash (100 % SSD) comme Tier de performance et un magasin d'objets comme Tier cloud. L'utilisation d'un FabricPool vous permet de réduire les coûts de stockage sans compromettre les performances, l'efficacité ni la protection.

Le Tier cloud peut se trouver sous NetApp StorageGRID ou ONTAP S3 (à partir de ONTAP 9.8), ou l'un de ces fournisseurs :

* Cloud Alibaba
* Amazon S3
* Google Cloud
* Cloud IBM
* Stockage Microsoft Azure Blob Storage




== Vidéo sur l'utilisation des données de niveau et des coûts réduits

video::Vs1-WMvj9fI[youtube,width=848,height=480]
.Informations associées
Voir aussi https://["NetApp Cloud Tiering"^] documentation :
