---
permalink: fabricpool/install-ca-certificate-ontap-s3-task.html 
sidebar: sidebar 
keywords: installing, ca certificate, ontap s3 
summary: 'Sauf si vous prévoyez de désactiver la vérification du certificat pour ONTAP S3, vous devez installer un certificat d"autorité de certification ONTAP S3 sur le cluster afin que ONTAP puisse s"authentifier auprès d"ONTAP S3 en tant que magasin d"objets pour FabricPool.' 
---
= Installez un certificat d'autorité de certification si vous utilisez ONTAP S3
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'utilisation de certificats CA crée une relation de confiance entre les applications client et le serveur de magasin d'objets ONTAP S3. Un certificat d'autorité de certification doit être installé sur ONTAP avant de l'utiliser comme magasin d'objets accessible aux clients distants.

Sauf si vous prévoyez de désactiver la vérification du certificat pour ONTAP S3, vous devez installer un certificat d'autorité de certification ONTAP S3 sur le cluster afin que ONTAP puisse s'authentifier auprès d'ONTAP S3 en tant que magasin d'objets pour FabricPool.

Bien que ONTAP puisse générer des certificats auto-signés, il est recommandé d'utiliser des certificats signés d'une autorité de certification tierce.

.Étapes
. Obtenir le certificat de l'autorité de certification du système ONTAP S3
. Utilisez le `security certificate install` commande avec `-type` `server-ca` Paramètre permettant d'installer le certificat d'autorité de certification ONTAP S3 sur le cluster.
+
Le nom de domaine complet que vous entrez doit correspondre au nom commun personnalisé du certificat de l'autorité de certification ONTAP S3.





== Mettre à jour un certificat expiré

Pour mettre à jour un certificat expiré, il est recommandé d'utiliser une autorité de certification approuvée pour générer le nouveau certificat de serveur. Par ailleurs, assurez-vous que le certificat est mis à jour simultanément sur le serveur ONTAP S3 et sur le cluster ONTAP afin de limiter au maximum le temps d'indisponibilité.

.Informations associées
link:../s3-config/index.html["Configuration de S3"]
