---
permalink: fabricpool/install-ca-certificate-storagegrid-task.html 
sidebar: sidebar 
keywords: installing, ca certificate, storagegrid 
summary: 'Sauf si vous prévoyez de désactiver la vérification du certificat pour StorageGRID, vous devez installer un certificat d"autorité de certification StorageGRID sur le cluster de manière à ce que ONTAP puisse s"authentifier auprès de StorageGRID comme magasin d"objets pour FabricPool.' 
---
= Installez un certificat d'autorité de certification sur un cluster ONTAP pour StorageGRID
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'utilisation de certificats CA crée une relation de confiance entre les applications clientes et StorageGRID.

Sauf si vous prévoyez de désactiver la vérification du certificat pour StorageGRID, vous devez installer un certificat d'autorité de certification StorageGRID sur le cluster de manière à ce que ONTAP puisse s'authentifier auprès de StorageGRID comme magasin d'objets pour FabricPool.

Bien que StorageGRID puisse générer des certificats auto-signés, il est recommandé d'utiliser des certificats signés d'une autorité de certification tierce.

.Description de la tâche
Bien que l'installation et l'utilisation de certificats d'autorité de certification (CA) soient des pratiques recommandées, à partir de ONTAP 9.4, l'installation de certificats d'autorité de certification n'est pas requise pour StorageGRID.

.Étapes
. Contactez votre administrateur StorageGRID pour obtenir le https://docs.netapp.com/us-en/storagegrid-118/admin/configuring-storagegrid-certificates-for-fabricpool.html["Certificat CA du système StorageGRID"^].
. Utilisez le `security certificate install` commande avec `-type` `server-ca` Paramètre permettant d'installer le certificat d'autorité de certification StorageGRID sur le cluster.
+
Le nom de domaine complet (FQDN) que vous saisissez doit correspondre au nom commun personnalisé du certificat de l'autorité de certification StorageGRID.





== Mettre à jour un certificat expiré

Pour mettre à jour un certificat expiré, il est recommandé d'utiliser une autorité de certification approuvée pour générer le nouveau certificat de serveur. Par ailleurs, vous devez vous assurer que le certificat est mis à jour simultanément sur le serveur StorageGRID et sur le cluster ONTAP afin de limiter au maximum le temps d'interruption.

.Informations associées
* https://docs.netapp.com/us-en/storagegrid-family/["Ressources StorageGRID"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-install.html["installation du certificat de sécurité"^]

