---
permalink: fabricpool/monitor-space-utilization-task.html 
sidebar: sidebar 
keywords: monitoring, space, utilization, fabricpool 
summary: 'Vous devez connaître la quantité de données stockées dans les tiers de performance et de cloud pour FabricPool. Ces informations vous permettent de déterminer si vous devez modifier la règle de Tiering d"un volume, d"augmenter la limite d"utilisation sous licence d"FabricPool ou d"augmenter l"espace de stockage du Tier cloud.' 
---
= Surveiller l'utilisation de l'espace pour FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez connaître la quantité de données stockées dans les tiers de performance et de cloud pour FabricPool. Ces informations vous permettent de déterminer si vous devez modifier la règle de Tiering d'un volume, d'augmenter la limite d'utilisation sous licence d'FabricPool ou d'augmenter l'espace de stockage du Tier cloud.

.Étapes
. Contrôlez l'utilisation de l'espace pour les agrégats compatibles FabricPool à l'aide de l'une des commandes suivantes pour afficher les informations :
+
|===


| Si vous voulez afficher... | Ensuite, utilisez cette commande : 


 a| 
Taille utilisée du Tier cloud dans un agrégat
 a| 
`storage aggregate show` avec le `-instance` paramètre



 a| 
Détails de l'utilisation de l'espace au sein d'un agrégat, y compris la capacité référencée du magasin d'objets
 a| 
`storage aggregate show-space` avec le `-instance` paramètre



 a| 
Utilisation de l'espace des magasins d'objets connectés aux agrégats, y compris l'espace de licence utilisé
 a| 
`storage aggregate object-store show-space`



 a| 
Liste des volumes d'un agrégat et de leurs données et métadonnées sans leur empreinte
 a| 
`volume show-footprint`

|===
+
En plus d'utiliser les commandes de l'interface de ligne de commandes, vous pouvez utiliser Active IQ Unified Manager (anciennement OnCommand Unified Manager) avec FabricPool Advisor, qui est pris en charge sur les clusters ONTAP 9.4 et versions ultérieures, ou System Manager pour contrôler l'utilisation de l'espace.

+
L'exemple suivant montre des moyens d'afficher l'utilisation de l'espace et les informations associées pour FabricPool :

+
[listing]
----
cluster1::> storage aggregate show-space -instance

                          Aggregate: MyFabricPool
                                                                   ...
                                               Aggregate Display Name: MyFabricPool
                                                                   ...
                          Total Object Store Logical Referenced Capacity: -
                          Object Store Logical Referenced Capacity Percentage: -
                                                                   ...
                                                       Object Store Size: -
                          Object Store Space Saved by Storage Efficiency: -
                          Object Store Space Saved by Storage Efficiency Percentage: -
                                                 Total Logical Used Size: -
                                                 Logical Used Percentage: -
                                           Logical Unreferenced Capacity: -
                                         Logical Unreferenced Percentage: -

----
+
[listing]
----
cluster1::> storage aggregate show -instance

                           Aggregate: MyFabricPool
                           ...
                           Composite: true
                           Capacity Tier Used Size:
                           ...
----
+
[listing]
----
cluster1::> volume show-footprint

Vserver : vs1
Volume : rootvol

Feature                          Used       Used%
-------------------------------- ---------- -----
Volume Footprint                 KB          %
Volume Guarantee                 MB          %
Flexible Volume Metadata         KB          %
Delayed Frees                    KB          %
Total Footprint                  MB          %

Vserver : vs1
Volume : vol

Feature                          Used       Used%
-------------------------------- ---------- -----
Volume Footprint                 KB          %
Footprint in Performance Tier    KB          %
Footprint in Amazon01            KB          %
Flexible Volume Metadata         MB          %
Delayed Frees                    KB          %
Total Footprint                  MB          %
...
----
. Procédez de l'une des manières suivantes :
+
|===


| Les fonctions que vous recherchez... | Alors... 


 a| 
Modification de la règle de Tiering d'un volume
 a| 
Suivre la procédure de la section link:modify-tiering-policy-cooling-period-task.html["Gestion du Tiering du stockage en modifiant la règle de hiérarchisation ou la période de refroidissement minimale d'un volume"].



 a| 
Augmentez la limite d'utilisation de la licence FabricPool
 a| 
Contactez votre ingénieur commercial NetApp ou partenaire.

https://["Support NetApp"]



 a| 
Augmentez l'espace de stockage du Tier cloud
 a| 
Contactez le fournisseur du magasin d'objets que vous utilisez pour le Tier cloud.

|===

