---
permalink: fabricpool/promote-mirror-task.html 
sidebar: sidebar 
keywords: promoting, fabricpool, mirror 
summary: 'Vous pouvez réattribuer le miroir du magasin d"objets en tant que magasin d"objets principal en le promouvant. Lorsque le miroir du magasin d"objets devient le miroir principal, le miroir d"origine devient automatiquement le miroir.' 
---
= Promouvoir un miroir FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez réattribuer le miroir du magasin d'objets en tant que magasin d'objets principal en le promouvant. Lorsque le miroir du magasin d'objets devient le miroir principal, le miroir d'origine devient automatiquement le miroir.

.Ce dont vous avez besoin
* Le miroir FabricPool doit être synchronisé
* Le magasin d'objets doit être opérationnel


.Description de la tâche
Vous pouvez remplacer le magasin d'objets d'origine par un magasin d'objets d'un autre fournisseur cloud. Par exemple, le miroir d'origine peut être un magasin d'objets AWS, mais vous pouvez le remplacer par un magasin d'objets Azure.

.Étape
. Promouvoir un miroir de magasin d'objets à l'aide du `storage aggregate object-store modify -aggregate` commande.
+
[listing]
----
cluster1::> storage aggregate object-store modify -aggregate aggr1 -name my-store-2 -mirror-type primary
----

