---
permalink: fabricpool/replace-existing-object-store-mirror-task.html 
sidebar: sidebar 
keywords: replacing, existing, object, store, fabricpool, mirror 
summary: 'Vous pouvez utiliser la technologie FabricPool mirror pour remplacer un magasin d"objets par un autre. Le nouveau magasin d"objets n"a pas besoin d"utiliser le même fournisseur cloud que le magasin d"objets d"origine.' 
---
= Remplacer un magasin d'objets existant par un miroir ONTAP FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser la technologie FabricPool mirror pour remplacer un magasin d'objets par un autre. Le nouveau magasin d'objets n'a pas besoin d'utiliser le même fournisseur cloud que le magasin d'objets d'origine.

.Description de la tâche
Vous pouvez remplacer le magasin d'objets d'origine par un magasin d'objets qui utilise un autre fournisseur cloud. Par exemple, votre magasin d'objets d'origine peut utiliser AWS en tant que fournisseur cloud, mais vous pouvez le remplacer par un magasin d'objets qui utilise Azure comme fournisseur cloud, et inversement. Toutefois, le nouveau magasin d'objets doit conserver la même taille d'objet que l'original.

.Étapes
. Créez un miroir FabricPool en ajoutant un nouveau magasin d'objets à un FabricPool existant à l'aide de `storage aggregate object-store mirror` commande.
+
[listing]
----
cluster1::> storage aggregate object-store mirror -aggregate aggr1 -object-store-name my-AZURE-store
----
. Surveillez l'état de resynchronisation du miroir à l'aide du `storage aggregate object-store show-resync-status` commande.
+
[listing]
----
cluster1::> storage aggregate object-store show-resync-status -aggregate aggr1
----
+
[listing]
----
                                                  Complete
      Aggregate    Primary          Mirror        Percentage
      ---------    -----------      ----------    ----------
      aggr1        my-AWS-store     my-AZURE-store     40%
----
. Vérifiez que le miroir est en mode synchrone à l'aide du `storage aggregate object-store> show -fields mirror-type,is-mirror-degraded` commande.
+
[listing]
----
cluster1::> storage aggregate object-store show -fields mirror-type,is-mirror-degraded
----
+
[listing]
----
aggregate      object-store-name mirror-type     is-mirror-degraded
-------------- ----------------- ------------- ------------------
aggr1          my-AWS-store        primary           -
               my-AZURE-store      mirror          false
----
. Remplacez le magasin d'objets principal par le magasin d'objets symétriques à l'aide du `storage aggregate object-store modify` commande.
+
[listing]
----
cluster1::> storage aggregate object-store modify -aggregate aggr1 -object-store-name my-AZURE-store -mirror-type primary
----
. Affiche des détails sur le miroir FabricPool à l'aide du `storage aggregate object-store show -fields mirror-type,is-mirror-degraded` commande.
+
Cet exemple affiche les informations relatives au miroir FabricPool, y compris si le miroir est dégradé (hors synchronisation).

+
[listing]
----
cluster1::> storage aggregate object-store show -fields mirror-type, is-mirror-degraded
----
+
[listing]
----
aggregate      object-store-name mirror-type     is-mirror-degraded
-------------- ----------------- ------------- ------------------
aggr1          my-AZURE-store      primary           -
               my-AWS-store        mirror          false
----
. Déposer le rétroviseur FabricPool à l'aide de l'outil `storage aggregate object-store unmirror` commande.
+
[listing]
----
cluster1::> storage aggregate object-store unmirror -aggregate aggr1
----
. Vérifiez que FabricPool est de nouveau dans une configuration de magasin d'objets unique à l'aide du `storage aggregate object-store show -fields mirror-type,is-mirror-degraded` commande.
+
[listing]
----
cluster1::> storage aggregate object-store show -fields mirror-type,is-mirror-degraded
----
+
[listing]
----
aggregate      object-store-name mirror-type     is-mirror-degraded
-------------- ----------------- ------------- ------------------
aggr1          my-AZURE-store      primary           -
----


.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-mirror.html["agrégat de stockage miroir de magasin d'objets"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-modify.html["agrégat de stockage objet-magasin modifier"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-show-resync-status.html["agrégat de stockage objet-magasin afficher-resynchroniser-état"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-show.html["agrégat de stockage objet-magasin afficher"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-unmirror.html["stockage agrégat objet-magasin démiroir"^]

