---
permalink: fabricpool/setup-ontap-s3-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, ontap s3, cloud tier 
summary: Si vous exécutez ONTAP 9.8 ou une version ultérieure, vous pouvez configurer ONTAP S3 en tant que Tier cloud pour FabricPool. 
---
= Configurez ONTAP S3 en tant que Tier cloud ONTAP FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous exécutez ONTAP 9.8 ou une version ultérieure, vous pouvez configurer ONTAP S3 en tant que Tier cloud pour FabricPool.

.Ce dont vous avez besoin
Vous devez disposer du nom du serveur ONTAP S3 et de l'adresse IP des LIFs associées sur le cluster distant.

[NOTE]
====
Le nom du serveur est utilisé comme nom de domaine complet (FQDN) par les applications clientes. En dehors de ONTAP, confirmez que les enregistrements DNS pointent vers les LIFs de données du SVM utilisées.

====
Il faut que des LIF intercluster se trouvent sur le cluster local.

link:../s3-config/create-intercluster-lifs-remote-fabricpool-tiering-task.html["Création des LIFs intercluster pour le Tiering des FabricPool distants"]

.Description de la tâche
L'équilibrage de charge est activé pour les serveurs ONTAP S3 dans ONTAP 9.8 et versions ultérieures. Lorsque le nom d'hôte du serveur résout plusieurs adresses IP, ONTAP établit des connexions client avec toutes les adresses IP renvoyées (jusqu'à 16 adresses IP maximum). Les adresses IP sont récupérées dans une méthode de séquence périodique lors de l'établissement des connexions.

.Procédures
Vous pouvez configurer ONTAP S3 en tant que Tier cloud pour FabricPool avec ONTAP System Manager ou l'interface de ligne de commande ONTAP.

[role="tabbed-block"]
====
.System Manager
--
. Cliquez sur *stockage > tiers > Ajouter un niveau de cloud* et sélectionnez ONTAP S3 comme fournisseur de magasin d'objets.
. Complétez les informations demandées.
. Si vous souhaitez créer un miroir de nuage, cliquez sur *Ajouter en tant que miroir FabricPool*.


Un miroir FabricPool vous permet de remplacer un datastore en toute transparence et de garantir la disponibilité de vos données en cas d'incident.

--
.CLI
--
. Ajoutez des entrées pour le serveur S3 et les LIF à votre serveur DNS.
+
|===


| Option | Description 


 a| 
*Si vous utilisez un serveur DNS externe*
 a| 
Attribuez le nom du serveur S3 et les adresses IP à l'administrateur des serveurs DNS.



 a| 
*Si vous utilisez la table hôtes DNS de votre système local*
 a| 
Saisissez la commande suivante :

`dns host create -vserver svm_name -address ip_address -hostname s3_server_name`

|===
. Spécifiez les informations de configuration ONTAP S3 à l'aide du `storage aggregate object-store config create` commande avec `-provider-type` `ONTAP_S3` paramètre.
+
** Le `storage aggregate object-store config create` Échec de la commande si le système ONTAP local ne peut pas accéder au serveur ONTAP S3 avec les informations fournies.
** Vous utilisez le `-access-key` Paramètre permettant de spécifier la clé d'accès pour autoriser les requêtes vers le serveur ONTAP S3.
** Vous utilisez le `-secret-password` Paramètre pour spécifier le mot de passe (clé d'accès secrète) pour l'authentification des requêtes vers le serveur ONTAP S3.
** Si le mot de passe du serveur ONTAP S3 est modifié, vous devez immédiatement mettre à jour le mot de passe correspondant stocké dans le système ONTAP local.
+
L'accès aux données du magasin d'objets ONTAP S3 est donc possible sans interruption.

** Le `-is-certificate-validation-enabled` paramètre sur `false` désactive la vérification de certificat pour ONTAP S3. Utilisation de certificats signés (`-is-certificate-validation-enabled true`) d'une autorité de certification tierce est une pratique recommandée.


+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name myS3 -provider-type ONTAP_S3 -server myS3server
-container-name myS3container -access-key myS3key
-secret-password myS3pass
----
. Affichez et vérifiez les informations de configuration ONTAP_S3 à l'aide de `storage aggregate object-store config show` commande.
+
Le `storage aggregate object-store config modify` vous permet de modifier le `ONTAP_S3` Informations de configuration pour FabricPool.



--
====