---
permalink: fabricpool/setup-azure-blob-storage-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, azure blob storage, cloud, cloud tier 
summary: Si vous exécutez ONTAP 9.4 ou une version ultérieure, vous pouvez configurer Azure Blob Storage pour le cloud en tant que Tier cloud pour FabricPool. 
---
= Configuration du stockage Azure Blob en tant que Tier cloud ONTAP FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous exécutez ONTAP 9.4 ou une version ultérieure, vous pouvez configurer Azure Blob Storage en tant que Tier cloud pour FabricPool.

.Considérations relatives à l'utilisation du stockage Microsoft Azure Blob avec FabricPool
* Un link:https://bluexp.netapp.com/cloud-tiering["Licence de Tiering BlueXP"] est requis pour le Tiering vers Azure Blob Storage.
* Une licence FabricPool n'est pas requise si vous utilisez Azure Blob Storage avec Cloud Volumes ONTAP.
* Il est recommandé que le LIF utilisé par ONTAP pour se connecter avec le serveur d'objets Azure Blob Storage soit sur un port 10 Gbit/s.
* FabricPool ne prend pas encore en charge Azure Stack, qui est actuellement disponible dans les services Azure sur site.
* Au niveau du compte dans Microsoft Azure Blob Storage, FabricPool ne prend en charge que les tiers de stockage à chaud et froid.
+
FabricPool ne prend pas en charge le Tiering au niveau des objets blob. Il ne prend pas également en charge le Tiering vers le Tier de stockage d'archivage d'Azure.



.Description de la tâche
FabricPool ne prend pas encore en charge Azure Stack, qui est actuellement disponible dans les services Azure sur site.

.Étapes
. Spécifiez les informations de configuration du stockage Azure Blob Storage à l'aide du `storage aggregate object-store config create` commande avec `-provider-type` `Azure_Cloud` paramètre.
+
** Le `storage aggregate object-store config create` Échec de la commande si ONTAP ne peut pas accéder au stockage Azure Blob Storage avec les informations fournies.
** Vous utilisez le `-azure-account` Paramètre permettant de spécifier le compte Azure Blob Storage.
** Vous utilisez le `-azure-private-key` Paramètre pour spécifier la clé d'accès pour l'authentification des requêtes vers Azure Blob Storage.
** Si le mot de passe du stockage Azure Blob Storage est modifié, vous devez immédiatement mettre à jour le mot de passe correspondant stocké dans ONTAP.
+
ONTAP peut ainsi accéder sans interruption aux données dans le stockage Azure Blob Storage.



+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name MyAzure -provider-type Azure_Cloud
-server blob.core.windows.net -container-name myAzureContainer
-azure-account myAzureAcct -azure-private-key myAzureKey
----
. Affichez et vérifiez les informations de configuration d'Azure Blob Storage à l'aide du `storage aggregate object-store config show` commande.
+
Le `storage aggregate object-store config modify` Vous permet de modifier les informations de configuration du stockage Azure Blob pour FabricPool.


