---
permalink: fabricpool/setup-ibm-object-storage-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, ibm cloud, object storage, cloud tier 
summary: Si vous exécutez ONTAP 9.5 ou version ultérieure, vous pouvez configurer IBM Cloud Object Storage en tant que Tier cloud pour FabricPool. 
---
= Configuration d'IBM Cloud Object Storage en tant que Tier cloud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous exécutez ONTAP 9.5 ou version ultérieure, vous pouvez configurer IBM Cloud Object Storage en tant que Tier cloud pour FabricPool.

.Considérations relatives à l'utilisation du stockage objet cloud IBM avec FabricPool
* Vous aurez peut-être besoin d'une licence FabricPool.
+
Les systèmes AFF nouvellement commandés disposent d'une capacité libre de 10 To pour l'utilisation de FabricPool. Si vous avez besoin de capacité supplémentaire sur un système AFF, si vous utilisez le stockage objet cloud IBM sur un système non-AFF ou si vous effectuez une mise à niveau à partir d'un cluster existant, vous avez besoin d'un link:https://docs.netapp.com/us-en/ontap/fabricpool/install-license-aws-azure-ibm-task.html["Licence FabricPool"].

+
Si vous commandez FabricPool pour la première fois pour un cluster existant, une licence FabricPool avec 10 To de capacité libre est disponible.

* Il est recommandé que le LIF utilisé par ONTAP pour se connecter avec le serveur d'objets IBM Cloud soit sur un port 10 Gbit/s.


.Étapes
. Spécifiez les informations de configuration du stockage objet IBM Cloud à l'aide de `storage aggregate object-store config create` commande avec `-provider-type` `IBM_COS` paramètre.
+
** Le `storage aggregate object-store config create` Échec de la commande si ONTAP ne peut pas accéder au stockage objet cloud IBM avec les informations fournies.
** Vous utilisez le `-access-key` Paramètre permettant de spécifier la clé d'accès pour autoriser les requêtes vers le magasin d'objets IBM Cloud Object Storage.
** Vous utilisez le `-secret-password` Paramètre pour spécifier le mot de passe (clé d'accès secrète) pour l'authentification des requêtes vers le magasin d'objets IBM Cloud Object Storage.
** Si le mot de passe du stockage objet IBM Cloud a été modifié, vous devez immédiatement mettre à jour le mot de passe correspondant stocké dans ONTAP.
+
ONTAP peut ainsi accéder sans interruption aux données du stockage objet dans le cloud IBM.



+
[listing]
----
storage aggregate object-store config create
-object-store-name MyIBM -provider-type IBM_COS
-server s3.us-east.objectstorage.softlayer.net
-container-name my-ibm-cos-bucket -access-key DXJRXHPXHYXA9X31X3JX
----
. Affichez et vérifiez les informations de configuration du stockage objet IBM Cloud à l'aide du `storage aggregate object-store config show` commande.
+
Le `storage aggregate object-store config modify` Permet de modifier les informations de configuration du stockage objet dans le cloud IBM pour FabricPool.


