---
permalink: nfs-config/additional-information-reference.html 
sidebar: sidebar 
keywords: additional, information, nfs, configuration, networking, san protocol, root volume, protection 
summary: 'Après avoir testé l"accès client NFS avec succès, vous pouvez effectuer une configuration NFS supplémentaire ou ajouter un accès SAN. Une fois les protocoles accès terminés, vous devez protéger le volume root de la machine virtuelle de stockage (SVM).' 
---
= Où trouver des informations complémentaires
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir testé l'accès client NFS avec succès, vous pouvez effectuer une configuration NFS supplémentaire ou ajouter un accès SAN. Une fois les protocoles accès terminés, vous devez protéger le volume root de la machine virtuelle de stockage (SVM).



== Configuration NFS

Vous pouvez configurer davantage l'accès NFS à l'aide des informations et rapports techniques suivants :

* link:../nfs-admin/index.html["Gestion NFS"]
+
Décrit comment configurer et gérer l'accès aux fichiers à l'aide de NFS.

* https://www.netapp.com/pdf.html?item=/media/10720-tr-4067.pdf["Rapport technique NetApp 4067 : Guide des meilleures pratiques et de mise en œuvre de NFS"^]
+
Sert de guide opérationnel NFSv3 et NFSv4, et présente le système d'exploitation ONTAP avec un accent sur NFSv4.

* https://www.netapp.com/pdf.html?item=/media/19371-tr-4073.pdf["Rapport technique NetApp 4073 : authentification unifiée sécurisée"^]
+
Explique comment configurer ONTAP pour une utilisation avec des serveurs Kerberos version 5 (krb5) UNIX pour l'authentification du stockage NFS et Windows Server Active Directory (AD) en tant que fournisseur d'identité KDC et Lightweight Directory Access Protocol (LDAP).

* https://www.netapp.com/pdf.html?item=/media/16398-tr-3580pdf.pdf["Rapport technique NetApp 3580 : Guide des améliorations et des meilleures pratiques NFSv4 implémentation d'Data ONTAP"^]
+
Décrit les meilleures pratiques à suivre lors de l'implémentation des composants NFSv4 sur des clients AIX, Linux ou Solaris reliés à des systèmes exécutant ONTAP.





== Configuration de la mise en réseau

Vous pouvez configurer davantage les fonctions de réseau et les services de noms à l'aide des informations et rapports techniques suivants :

* link:../nfs-admin/index.html["Gestion NFS"]
+
Décrit la configuration et la gestion de la mise en réseau ONTAP.

* https://www.netapp.com/pdf.html?item=/media/16885-tr-4182pdf.pdf["Rapport technique NetApp 4182 : considérations relatives à la conception du stockage Ethernet et meilleures pratiques pour les configurations clustered Data ONTAP"^]
+
Décrit l'implémentation des configurations réseau ONTAP et fournit des scénarios de déploiement réseau communs et des recommandations sur les meilleures pratiques.

* https://www.netapp.com/pdf.html?item=/media/16328-tr-4668pdf.pdf["Rapport technique de NetApp 4668 : name Services Best Practices Guide (Guide des meilleures pratiques des services de noms)"^]
+
Explique comment configurer LDAP, NIS, DNS et la configuration de fichiers locaux à des fins d'authentification.





== Configuration du protocole SAN

Si vous souhaitez fournir ou modifier un accès SAN au nouveau SVM, vous pouvez utiliser les informations de configuration FC ou iSCSI disponibles pour plusieurs systèmes d'exploitation hôtes.



== Protection du volume racine

Après avoir configuré les protocoles sur le SVM, il faut s'assurer que son volume root est protégé :

* link:../data-protection/index.html["Protection des données"]
+
Décrit la procédure de création d'un miroir de partage de charge pour protéger le volume racine du SVM, une pratique recommandée par NetApp pour les SVM compatibles avec NAS. Décrit également la procédure de restauration rapide en cas de défaillances ou de pertes de volumes en promouvant le volume racine du SVM à partir d'un miroir de partage de charge.


