---
permalink: nfs-config/assess-physical-storage-requirements-task.html 
sidebar: sidebar 
keywords: assess, physical, storage, requirements 
summary: 'Avant de provisionner le stockage NFS pour les clients, vous devez vérifier que l"espace disponible sur un agrégat est suffisant pour le nouveau volume. Si ce n"est pas le cas, vous pouvez ajouter des disques à un agrégat existant ou créer un nouvel agrégat du type souhaité.' 
---
= Évaluer les besoins en matière de stockage physique
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de provisionner le stockage NFS pour les clients, vous devez vérifier que l'espace disponible sur un agrégat est suffisant pour le nouveau volume. Si ce n'est pas le cas, vous pouvez ajouter des disques à un agrégat existant ou créer un nouvel agrégat du type souhaité.

.Étapes
. Afficher l'espace disponible dans les agrégats existants :
+
`storage aggregate show`

+
Si un agrégat dispose d'un espace suffisant, notez son nom dans la fiche de travail.

+
[listing]
----
cluster::> storage aggregate show
Aggregate     Size Available Used% State   #Vols  Nodes  RAID Status
--------- -------- --------- ----- ------- ------ ------ -----------
aggr_0     239.0GB   11.13GB   95% online       1 node1  raid_dp,
                                                         normal
aggr_1     239.0GB   11.13GB   95% online       1 node1  raid_dp,
                                                         normal
aggr_2     239.0GB   11.13GB   95% online       1 node2  raid_dp,
                                                         normal
aggr_3     239.0GB   11.13GB   95% online       1 node2  raid_dp,
                                                         normal
aggr_4     239.0GB   238.9GB   95% online       5 node3  raid_dp,
                                                         normal
aggr_5     239.0GB   239.0GB   95% online       4 node4  raid_dp,
                                                         normal
6 entries were displayed.
----
. Si aucun agrégat n'a suffisamment d'espace, ajoutez des disques à un agrégat existant en utilisant le `storage aggregate add-disks` ou créez un nouvel agrégat à l'aide de `storage aggregate create` commande.

