---
permalink: nfs-config/associate-export-policy-flexvol-task.html 
sidebar: sidebar 
keywords: assign, export, policy, volume 
summary: Chaque volume contenu au SVM doit être associé à une export policy qui contient les export rules auxquelles les clients ont accès les données au sein du volume. 
---
= Affectation d'une export-policy à un volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Chaque volume contenu au SVM doit être associé à une export policy qui contient les export rules auxquelles les clients ont accès les données au sein du volume.

.Description de la tâche
Vous pouvez associer une export policy à un volume lors de la création du volume ou à tout moment après sa création. Vous pouvez associer une export policy au volume, bien qu'une seule policy puisse être associée à de nombreux volumes.

.Étapes
. Si une export policy n'a pas été spécifiée lors de la création du volume, affectez une export policy au volume :
+
`volume modify -vserver _vserver_name_ -volume _volume_name_ -policy _export_policy_name_`

. Vérifiez que la policy a été assignée au volume :
+
`volume show -volume _volume_name_ -fields policy`



.Exemple
Les commandes suivantes affectent l'export policy nfs_policy vers le volume vol1 sur le SVM vs1 et vérifient l'affectation :

[listing]
----
cluster::> volume modify -v1server vs1 -volume vol1 -policy nfs_policy

cluster::>volume show -volume vol -fields policy
vserver volume       policy
------- ------------ ----------------
vs1     vol1         nfs_policy
----