---
permalink: nfs-config/comparison-exports-7-mode-concept.html 
sidebar: sidebar 
keywords: comparison, exports, 7-mode ontap 
summary: Dans ONTAP, les exportations sont définies et utilisées différemment des environnements 7-mode. 
---
= Comparaison des exportations dans 7-mode et ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dans ONTAP, les exportations sont définies et utilisées différemment des environnements 7-mode.

|===


| Domaines de différence | 7-mode | ONTAP 


 a| 
Définition des exportations
 a| 
Les exportations sont définies dans le `/etc/exports` fichier.
 a| 
Les exportations sont définies par la création d'une export policy au sein d'un SVM. Un SVM peut inclure plusieurs export policy.



 a| 
Champ d'application de l'exportation
 a| 
* Les exportations s'appliquent à un chemin de fichiers ou à un qtree spécifié.
* Vous devez créer une entrée séparée dans `/etc/exports` pour chaque chemin de fichier ou qtree.
* Les exportations ne sont persistantes que si elles sont définies dans le `/etc/exports` fichier.

 a| 
* Les règles d'exportation s'appliquent à tout un volume, y compris l'ensemble des chemins de fichiers et qtrees contenu dans le volume.
* Si vous le souhaitez, des règles d'exportation peuvent être appliquées à plusieurs volumes.
* Toutes les règles d'exportation sont conservées sur l'ensemble des redémarrages du système.




 a| 
Escrime (spécification d'un accès différent pour des clients spécifiques aux mêmes ressources)
 a| 
Pour fournir à des clients spécifiques un accès différent à une seule ressource exportée, vous devez répertorier chaque client et son accès autorisé dans `/etc/exports` fichier.
 a| 
Les export-policies se composent d'un certain nombre de règles d'exportation individuelles. Chaque règle d'exportation définit des autorisations d'accès spécifiques pour une ressource et répertorie les clients disposant de ces autorisations. Pour spécifier un accès différent pour des clients spécifiques, vous devez créer une règle d'exportation pour chaque ensemble spécifique d'autorisations d'accès, répertorier les clients disposant de ces autorisations, puis ajouter les règles à la export policy.



 a| 
Changement de nom
 a| 
Lorsque vous définissez une exportation, vous pouvez choisir de modifier le nom de l'exportation par rapport au nom du chemin du fichier. Vous devez utiliser le `-actual` paramètre lors de la définition d'une telle exportation dans le `/etc/exports` fichier.
 a| 
Vous pouvez choisir de rendre le nom du volume exporté différent de celui du volume réel. Pour ce faire, il faut monter le volume avec un nom de chemin de jonction personnalisé au sein du namespace du SVM.


NOTE: Par défaut, les volumes sont montés avec leur nom de volume. Pour personnaliser le chemin de jonction d'un volume, vous devez le démonter, le renommer, puis le remonter.

|===