---
permalink: nfs-config/create-local-unix-user-task.html 
sidebar: sidebar 
keywords: create, local, unix, user 
summary: 'Vous pouvez utiliser la commande vserver services name-service unix-user create pour créer des utilisateurs UNIX locaux. Un utilisateur UNIX local est un utilisateur UNIX que vous créez sur le SVM en tant qu"option de services de noms UNIX à utiliser lors du traitement des mappages de noms.' 
---
= Créez un utilisateur UNIX local
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `vserver services name-service unix-user create` Commande permettant de créer des utilisateurs UNIX locaux. Un utilisateur UNIX local est un utilisateur UNIX que vous créez sur le SVM en tant qu'option de services de noms UNIX à utiliser lors du traitement des mappages de noms.

.Étape
. Créer un utilisateur UNIX local :
+
`vserver services name-service unix-user create -vserver _vserver_name_ -user _user_name_ -id _integer_ -primary-gid _integer_ -full-name _full_name_`

+
`-user _user_name_` spécifie le nom d'utilisateur. La longueur du nom d'utilisateur doit être inférieure ou égale à 64 caractères.

+
`-id _integer_` Spécifie l'ID utilisateur que vous attribuez.

+
`-primary-gid _integer_` Spécifie l'ID du groupe principal. L'utilisateur est ainsi ajouté au groupe principal. Après avoir créé l'utilisateur, vous pouvez l'ajouter manuellement à tout groupe supplémentaire souhaité.



.Exemple
La commande suivante crée un utilisateur UNIX local nommé johnm (nom complet « John Miller ») sur la SVM nommée vs1. L'utilisateur possède l'ID 123 et le groupe principal ID 100.

[listing]
----
node::> vserver services name-service unix-user create -vserver vs1 -user johnm -id 123
-primary-gid 100 -full-name "John Miller"
----