---
permalink: nfs-config/enable-ldap-svms-task.html 
sidebar: sidebar 
keywords: associate, ldap, client, configuration, svms 
summary: Pour activer LDAP sur un SVM, il faut utiliser la commande vserver services name-service ldap create pour associer une configuration client LDAP à la SVM. 
---
= Associer la configuration client LDAP aux SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour activer LDAP sur un SVM, vous devez utiliser `vserver services name-service ldap create` Commande permettant d'associer une configuration client LDAP à la SVM.

.Avant de commencer
* Un domaine LDAP doit déjà exister au sein du réseau et doit être accessible au cluster sur lequel le SVM est situé.
* Une configuration client LDAP doit exister sur le SVM.


.Étapes
. Activer LDAP sur le SVM :
+
`vserver services name-service ldap create -vserver _vserver_name_ -client-config _client_config_name_`

+
[NOTE]
====
À partir de ONTAP 9.2, le `vserver services name-service ldap create` Commande effectue une validation automatique de la configuration et signale un message d'erreur si ONTAP n'est pas en mesure de contacter le serveur de noms.

====
+
La commande suivante permet à LDAP sur le SVM « vs1 » et le configure pour utiliser la configuration du client LDAP « ldap1 » :

+
[listing]
----
cluster1::> vserver services name-service ldap create -vserver vs1 -client-config ldap1 -client-enabled true
----
. Valider le statut des serveurs name en utilisant la commande vserver services name-service ldap check.
+
La commande suivante valide les serveurs LDAP sur le SVM vs1.

+
[listing]
----
cluster1::> vserver services name-service ldap check -vserver vs1

| Vserver: vs1                                                |
| Client Configuration Name: c1                               |
| LDAP Status: up                                             |
| LDAP Status Details: Successfully connected to LDAP server "10.11.12.13".                                              |
----
+
La commande name service check est disponible à partir de ONTAP 9.2.


