---
permalink: nfs-config/export-policies-concept.html 
sidebar: sidebar 
keywords: secure, nfs, access, using, export, policies 
summary: 'Vous pouvez utiliser des règles d"exportation pour restreindre l"accès NFS aux volumes ou aux qtrees aux clients correspondant à des paramètres spécifiques. Lorsque vous provisionnez un nouveau stockage, vous pouvez utiliser une stratégie et des règles existantes, ajouter des règles à une stratégie existante, ou créer une nouvelle règle et de nouvelles règles. Vous pouvez également vérifier la configuration des export-policies' 
---
= En savoir plus sur la sécurisation de l'accès NFS ONTAP à l'aide de politiques d'exportation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser des règles d'exportation pour restreindre l'accès NFS aux volumes ou aux qtrees aux clients correspondant à des paramètres spécifiques. Lorsque vous provisionnez un nouveau stockage, vous pouvez utiliser une stratégie et des règles existantes, ajouter des règles à une stratégie existante, ou créer une nouvelle règle et de nouvelles règles. Vous pouvez également vérifier la configuration des export-policies

[NOTE]
====
Depuis ONTAP 9.3, vous pouvez activer la vérification de la configuration des règles d'exportation en tant que tâche d'arrière-plan qui enregistre toutes les violations de règles dans une liste de règles d'erreur. Le `vserver export-policy config-checker` Les commandes appellent le vérificateur et affichent les résultats, que vous pouvez utiliser pour vérifier votre configuration et supprimer des règles erronées de la stratégie. Les commandes ne valident que la configuration d'exportation pour les noms d'hôte, les groupes réseau et les utilisateurs anonymes.

====