---
permalink: nfs-config/index.html 
sidebar: sidebar 
keywords: NFS, configuration, overview 
summary: 'Vous pouvez utiliser les commandes CLI de ONTAP 9 pour configurer l"accès client NFS aux fichiers contenus dans un nouveau volume ou qtree dans une machine virtuelle de stockage nouvelle ou existante.' 
---
= Présentation de la configuration NFS avec l'interface de ligne de commande
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser les commandes de l'interface de ligne de commande de ONTAP 9 pour configurer l'accès des clients NFS aux fichiers contenus dans un nouveau volume ou qtree dans une nouvelle machine virtuelle de stockage (SVM) ou existante.

Suivez les procédures ci-dessous pour configurer l'accès à un volume ou à un qtree de la manière suivante :

* Vous souhaitez utiliser toute version de NFS actuellement prise en charge par ONTAP : NFS v3, NFS V4, NFS v4.1, NFSv4.2 ou NFSv4.1 avec pNFS.
* Vous souhaitez utiliser l'interface de ligne de commande et non System Manager, ni un outil de création de scripts automatisé.
+
Pour utiliser System Manager pour configurer l'accès multiprotocole NAS, reportez-vous à la section link:https://docs.netapp.com/us-en/ontap/task_nas_provision_nfs_and_smb.html["Provisionnement de stockage NAS pour Windows et Linux à l'aide des protocoles NFS et SMB"].

* Vous voulez appliquer les bonnes pratiques, pas explorer toutes les options disponibles.
+
Vous trouverez des détails sur la syntaxe des commandes dans l'aide de l'interface de ligne de commande et dans les pages de manuel ONTAP.

* Les autorisations liées au fichier UNIX seront utilisées pour sécuriser le nouveau volume.
* Vous disposez des privilèges d'administrateur de cluster et non des privilèges d'administrateur de SVM.


Pour plus d'informations sur la plage de fonctionnalités du protocole NFS ONTAP, consultez le link:../nfs-admin/index.html["Présentation de référence NFS"].



== D'autres façons de le faire dans ONTAP

|===


| Pour effectuer ces tâches avec... | Reportez-vous à... 


| System Manager redessiné (disponible avec ONTAP 9.7 et versions ultérieures) | link:../task_nas_provision_linux_nfs.html["Provisionnement du stockage NAS pour les serveurs Linux via NFS"] 


| System Manager Classic (disponible avec ONTAP 9.7 et versions antérieures) | link:https://docs.netapp.com/us-en/ontap-sm-classic/nfs-config/index.html["Présentation de la configuration NFS"^] 
|===