---
permalink: nfs-config/tls-nfs-strong-security-concept.html 
sidebar: sidebar 
keywords: use, tls, nfs, strong, security 
summary: TLS permet des communications réseau chiffrées avec une sécurité équivalente et moins complexe que Kerberos. 
---
= Présentation de l'utilisation de TLS avec NFS pour une sécurité renforcée
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead lead"]
TLS permet des communications réseau chiffrées avec une sécurité équivalente et moins complexe que Kerberos et IPsec. En tant qu'administrateur, vous pouvez activer, configurer et désactiver TLS pour une sécurité renforcée avec les connexions NFSv3 et NFSv4.x via System Manager, l'interface de ligne de commande ONTAP ou l'API REST ONTAP.


NOTE: NFS over TLS est disponible dans ONTAP 9.15.1 en tant que préversion publique. À titre de préversion, NFS over TLS n'est pas pris en charge pour les workloads de production dans ONTAP 9.15.1.

ONTAP utilise TLS 1.3 pour les connexions NFS sur TLS.



== De formation

NFS sur TLS nécessite des certificats X.509. Vous pouvez soit créer et installer un certificat de serveur signé par une autorité de certification sur le cluster ONTAP, soit installer un certificat que le service NFS utilise directement. Vos certificats doivent être conformes aux directives suivantes :

* Le nom commun (CN) de chaque certificat doit être configuré avec le nom de domaine complet (FQDN) de la LIF de données sur laquelle TLS sera activé.
* Le nom SAN (Subject alternative Name) de chaque certificat doit être configuré avec l'adresse IP de la LIF de données sur laquelle TLS sera activé. Vous pouvez également ajouter le nom de domaine complet de la LIF de données. Si l'adresse IP et le nom de domaine complet sont configurés, les clients NFS peuvent se connecter à l'aide de l'adresse IP ou du nom de domaine complet.
* Vous pouvez installer plusieurs certificats de service NFS pour la même LIF, mais un seul d'entre eux peut être utilisé à la fois dans le cadre de la configuration NFS TLS.

