---
permalink: nfs-config/verify-status-netgroup-definitions-task.html 
sidebar: sidebar 
keywords: verify, status, netgroup, definitions 
summary: Après avoir chargé netgroups dans le SVM, on peut utiliser la commande vserver services name-service netgroup status pour vérifier le statut des définitions netgroup. Vous pouvez ainsi déterminer si les définitions de groupe réseau sont cohérentes sur tous les nœuds qui suivent la SVM. 
---
= Vérifier les définitions de groupes de réseaux SVM NFS ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Après avoir chargé des netgroups dans la SVM, vous pouvez utiliser `vserver services name-service netgroup status` commande pour vérifier le statut des définitions de groupe réseau. Vous pouvez ainsi déterminer si les définitions de groupe réseau sont cohérentes sur tous les nœuds qui suivent la SVM.

.Étapes
. Définissez le niveau de privilège sur avancé :
+
`set -privilege advanced`

. Vérifiez l'état des définitions de groupe réseau :
+
`vserver services name-service netgroup status`

+
Vous pouvez afficher des informations supplémentaires dans une vue plus détaillée.

. Retour au niveau de privilège admin :
+
`set -privilege admin`



.Exemple
Une fois le niveau de privilège défini, la commande suivante affiche le statut netgroup pour tous les SVM :

[listing]
----
vs1::> set -privilege advanced

Warning: These advanced commands are potentially dangerous; use them only when
         directed to do so by technical support.
Do you wish to continue? (y or n): y

vs1::*> vserver services name-service netgroup status
Virtual
Server    Node            Load Time           Hash Value
--------- --------------- ------------------- --------------------------------
vs1
          node1           9/20/2006 16:04:53  e6cb38ec1396a280c0d2b77e3a84eda2
          node2           9/20/2006 16:06:26  e6cb38ec1396a280c0d2b77e3a84eda2
          node3           9/20/2006 16:08:08  e6cb38ec1396a280c0d2b77e3a84eda2
          node4           9/20/2006 16:11:33  e6cb38ec1396a280c0d2b77e3a84eda2
----