---
permalink: nfs-config/where-provision-storage-capacity-task.html 
sidebar: sidebar 
keywords: decide, provision, new, nfs, storage, capacity 
summary: Avant de créer un nouveau volume NFS ou qtree, vous devez décider de le placer dans une SVM nouvelle ou existante, et du volume de configuration requis par la SVM. Cette décision détermine votre flux de travail. 
---
= Choisissez où provisionner la capacité de stockage NFS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Avant de créer un nouveau volume NFS ou qtree, vous devez décider de le placer dans une SVM nouvelle ou existante, et du volume de configuration requis par la SVM. Cette décision détermine votre flux de travail.

.Choix
* Si vous souhaitez provisionner un volume ou qtree sur un nouveau SVM, ou sur un SVM existant sur lequel NFS est activé mais non configuré, suivez les étapes de « Configuration de l'accès NFS à un SVM » et de « Ajout de stockage NFS à un SVM compatible NFS ».
+
xref:../smb-config/configure-access-svm-task.adoc[Configurer l'accès NFS à un SVM]

+
xref:add-storage-capacity-nfs-enabled-svm-concept.adoc[Ajout d'un stockage NFS à un SVM compatible NFS]

+
Vous pouvez choisir de créer un nouveau SVM si l'un des cas suivants est vrai :

+
** Vous activez NFS pour la première fois sur un cluster.
** Un cluster contient des SVM existants, dans lequel vous ne souhaitez pas activer la prise en charge de NFS.
** Un cluster possède un ou plusieurs SVM compatibles NFS, et vous souhaitez un autre serveur NFS dans un espace de noms isolé (scénario de colocation). Vous devez également choisir cette option pour provisionner le stockage sur un SVM existant sur lequel NFS est activé, mais non configuré. Ce peut être le cas si vous avez créé le SVM pour l'accès SAN ou si aucun protocole n'a été activé au moment de la création de la SVM.


+
Après avoir activé NFS sur le SVM, procéder au provisionnement d'un volume ou qtree.

* Si vous souhaitez provisionner un volume ou qtree sur un SVM existant entièrement configuré pour l'accès NFS, suivez les étapes de la section « Ajout de stockage NFS à un SVM compatible NFS ».
+
xref:add-storage-capacity-nfs-enabled-svm-concept.adoc[Ajout de stockage NFS à un SVM compatible NFS]


