---
permalink: system-admin/accounts-access-sp-concept.html 
sidebar: sidebar 
keywords: account, access, sp, cluster, user, cli, node 
summary: 'Lorsque vous tentez d"accéder au processeur de service, vous êtes invité à fournir des informations d"identification. Les comptes utilisateurs du cluster créés avec le type d"application processeur de service ont accès à l"interface de ligne de commandes du processeur de service sur n"importe quel nœud du cluster. Les comptes utilisateurs du processeur de service sont gérés à partir de ONTAP et authentifiés par mot de passe. Depuis la version ONTAP 9.9.1, les comptes utilisateurs de SP doivent avoir le rôle admin.' 
---
= Accédez au processeur de service ONTAP à l'aide d'un compte utilisateur de cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous tentez d'accéder au processeur de service, vous êtes invité à fournir des informations d'identification. Comptes utilisateurs du cluster créés avec le `service-processor` Le type d'application a accès à l'interface de ligne de commandes du processeur de service sur n'importe quel nœud du cluster. Les comptes utilisateurs du processeur de service sont gérés à partir de ONTAP et authentifiés par mot de passe. Depuis ONTAP 9.9.1, les comptes utilisateurs de SP doivent avoir le `admin` rôle.

Les comptes utilisateurs permettant d'accéder au processeur de service sont gérés à partir de ONTAP au lieu de l'interface de ligne de commandes du processeur de service. Un compte utilisateur du cluster peut accéder au processeur de service s'il est créé avec le `-application` paramètre du `security login create` commande définie sur `service-processor` et le `-authmethod` paramètre défini sur `password`. Le processeur de service prend uniquement en charge l'authentification par mot de passe.

Vous devez spécifier le `-role` Paramètre lors de la création d'un compte utilisateur du processeur de service.

* Dans ONTAP 9.9.1 et versions ultérieures, vous devez spécifier `admin` pour le `-role` et toute modification d'un compte nécessite le `admin` rôle. Les autres rôles ne sont plus autorisés pour des raisons de sécurité.
+
** Si vous effectuez une mise à niveau vers ONTAP 9.9.1 ou une version ultérieure, reportez-vous à la section link:../upgrade/sp-user-accounts-change-concept.html["Modifier les comptes utilisateur pouvant accéder au Service Processor"].
** Si vous rétablir ONTAP 9.8 ou des versions antérieures, consultez link:../revert/verify-sp-user-accounts-task.html["Vérifiez les comptes utilisateurs pouvant accéder au Service Processor"].


* Dans ONTAP 9.8 et les versions antérieures, tout rôle peut accéder au processeur de service, mais `admin` est recommandé.


Par défaut, le compte d'utilisateur du cluster nommé « admin » inclut le `service-processor` Le type d'application et a accès au processeur de service.

ONTAP vous empêche de créer des comptes utilisateur avec des noms réservés au système (tels que « root » et « naroot »). Vous ne pouvez pas utiliser un nom réservé système pour accéder au cluster ou au processeur de service.

Vous pouvez afficher les comptes utilisateurs actuels du processeur de service à l'aide de `-application service-processor` paramètre du `security login show` commande.
