---
permalink: system-admin/accounts-access-sp-concept.html 
sidebar: sidebar 
keywords: account, access, sp, cluster, user, cli, node 
summary: 'Lorsque vous tentez d"accéder au SP, il vous est demandé un identifiant. Les comptes d"utilisateurs du cluster créés avec le type d"application service-processor ont accès à la CLI du SP sur n"importe quel nœud du cluster. Les comptes d"utilisateurs du SP sont gérés depuis ONTAP et authentifiés par mot de passe. À partir d"ONTAP 9.15.1, les comptes d"utilisateurs du SP peuvent, en option, utiliser l"authentification à deux facteurs avec une clé publique comme seconde méthode d"authentification. À partir d"ONTAP 9.9.1, les comptes d"utilisateurs du SP doivent avoir le rôle admin.' 
---
= Accédez au processeur de service ONTAP à l'aide d'un compte utilisateur de cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lorsque vous essayez d'accéder au SP, il vous est demandé un identifiant. Les comptes d'utilisateurs du cluster créés avec le type d'application  `service-processor` ont accès à l'interface CLI du SP sur n'importe quel nœud du cluster. Les comptes d'utilisateurs du SP sont gérés depuis ONTAP et authentifiés par mot de passe. À partir d'ONTAP 9.15.1, les comptes d'utilisateurs du SP peuvent, en option, utiliser l'authentification à deux facteurs avec une clé publique comme seconde méthode d'authentification. À partir d'ONTAP 9.9.1, les comptes d'utilisateurs du SP doivent avoir le rôle  `admin`.

Les comptes utilisateurs permettant d'accéder au SP sont gérés depuis ONTAP au lieu de l'interface de ligne de commande du SP. Un compte utilisateur de cluster peut accéder au SP s'il est créé avec le  `-application` paramètre de la  `security login create` commande défini sur  `service-processor` et le  `-authmethod` paramètre défini sur  `password`. À partir de ONTAP 9.15.1, vous pouvez configurer en option l'authentification à deux facteurs pour un compte SP en définissant la seconde méthode d'authentification sur  `publickey` avec la commande  `security login modify` puis en associant la clé publique avec la commande  `security login publickey create`.

Vous devez spécifier le `-role` Paramètre lors de la création d'un compte utilisateur du processeur de service.

* Dans ONTAP 9.9.1 et versions ultérieures, vous devez spécifier `admin` pour le `-role` et toute modification d'un compte nécessite le `admin` rôle. Les autres rôles ne sont plus autorisés pour des raisons de sécurité.
+
** Si vous effectuez une mise à niveau vers ONTAP 9.9.1 ou une version ultérieure, reportez-vous à la section link:../upgrade/sp-user-accounts-change-concept.html["Modifier les comptes utilisateur pouvant accéder au Service Processor"].
** Si vous rétablir ONTAP 9.8 ou des versions antérieures, consultez link:../revert/verify-sp-user-accounts-task.html["Vérifiez les comptes utilisateurs pouvant accéder au Service Processor"].


* Dans ONTAP 9.8 et les versions antérieures, tout rôle peut accéder au processeur de service, mais `admin` est recommandé.


Par défaut, le compte d'utilisateur du cluster nommé « admin » inclut le `service-processor` Le type d'application et a accès au processeur de service.

ONTAP vous empêche de créer des comptes utilisateur avec des noms réservés au système (tels que « root » et « naroot »). Vous ne pouvez pas utiliser un nom réservé système pour accéder au cluster ou au processeur de service.

Vous pouvez afficher les comptes utilisateurs actuels du processeur de service à l'aide de `-application service-processor` paramètre du `security login show` commande.

Apprenez-en davantage sur link:https://docs.netapp.com/us-en/ontap-cli/security-login-modify.html[`security login modify`^], link:https://docs.netapp.com/us-en/ontap-cli/security-login-publickey-create.html[`security login publickey create`^] et link:https://docs.netapp.com/us-en/ontap-cli/security-login-show.html[`security login show`^] dans la référence des commandes ONTAP.
