---
permalink: system-admin/add-nodes-cluster-concept.html 
sidebar: sidebar 
keywords: add, node, cluster, create, expand 
summary: 'Une fois le cluster créé, vous pouvez le développer en ajoutant des nœuds. Vous n"ajoutez qu"un seul nœud à la fois.' 
---
= Ajout de nœuds à un cluster ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une fois le cluster créé, vous pouvez le développer en ajoutant des nœuds. Vous n'ajoutez qu'un seul nœud à la fois.

.Avant de commencer
* Installez et configurez votre nouveau système de stockage en vérifiant les exigences matérielles, en préparant votre site et en installant et câblant les composants matériels (contrôleurs, baies de stockage et commutateurs). Consultez la documentation des systèmes matériels ONTAP pour plus de détails :
+
** link:https://docs.netapp.com/us-en/ontap-systems/aff-landing/index.html["Systèmes AFF"^]
** link:https://docs.netapp.com/us-en/ontap-systems/allsan-landing/index.html["Systèmes ASA"^]
** link:https://docs.netapp.com/us-en/ontap-systems/afx/index.html["Systèmes AFX"^]
** link:https://docs.netapp.com/us-en/ontap-systems/asa-r2/index.html["Systèmes ASA R2"^]
** link:https://docs.netapp.com/us-en/ontap-systems/fas/index.html["Systèmes FAS"^]


* Examinez les considérations relatives au câblage et à la configuration du modèle de commutateur de cluster pour les ports de cluster de votre nouveau système de stockage. Voir le link:https://docs.netapp.com/us-en/ontap-systems-switches/index.html["Documentation de commutation pour les systèmes matériels ONTAP"^]
+
.. Sélectionnez les *Cluster Switches* ou les *Shared Switches* dans la vignette *Supported switches*.
.. Sélectionnez la documentation *Install* pour votre modèle de commutateur.
.. Recherchez le sujet *Review cabling and configuration considerations* et consultez-le pour votre système de stockage.


* Si vous ajoutez des nœuds à un cluster à plusieurs nœuds, tous les nœuds existants du cluster doivent être en bon état (indiqué par `cluster show`). Pour en savoir plus, `cluster show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/cluster-show.html["Référence de commande ONTAP"^].
* Si vous ajoutez des nœuds à un cluster sans commutateur à deux nœuds, vous devez convertir le cluster sans commutateur à deux nœuds en cluster à connexion par commutateur à l'aide d'un commutateur de cluster pris en charge par NetApp.
+
[cols="1,2"]
|===
| Modèle de commutateur | Procédure de migration 


 a| 
Broadcom BES-53248
 a| 
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-bes-53248/migrate-to-2n-switched.html["Migrer vers un environnement de cluster NetApp commuté"^]



 a| 
Cisco Nexus 9336C-FX2
 a| 
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-9336c-fx2/migrate-to-2n-switched-9336-cluster.html["Migrer vers un cluster commuté à deux nœuds"^]



 a| 
Cisco Nexus 9336C-FX2 (Cluster+Stockage partagés)
 a| 
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-cisco-9336c-fx2-shared/migrate-from-switchless-cluster-dat-storage.html["Migrer depuis un cluster sans commutateur avec stockage à connexion directe"^]



 a| 
NVIDIA SN2100
 a| 
link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-nvidia-sn2100/migrate-2n-switched-sn2100-cluster.html["Migrer vers un cluster commuté à deux nœuds avec des commutateurs de cluster NVIDIA SN2100"^]

|===
* Si vous ajoutez un second nœud à un cluster à un seul nœud, le second nœud doit avoir été installé et le réseau de clusters doit avoir été configuré.
* Si la configuration automatique du processeur de service est activée sur le cluster, le sous-réseau spécifié pour le processeur de service doit disposer de ressources disponibles pour permettre au nœud de jonction d'utiliser le sous-réseau spécifié pour configurer automatiquement le processeur de service.
* Vous devez avoir collecté les informations suivantes pour le LIF de gestion des nœuds du nouveau nœud :
+
** Port
** Adresse IP
** Masque de réseau
** Passerelle par défaut




.Description de la tâche
Les nœuds doivent être numériques de manière à pouvoir former des paires haute disponibilité. Une fois que vous avez commencé à ajouter un nœud au cluster, vous devez terminer le processus. Le nœud doit faire partie du cluster avant de pouvoir ajouter un autre nœud.

.Étapes
. Mettez le nœud que vous souhaitez ajouter au cluster sous tension.
+
Le nœud démarre et l'assistant de configuration du nœud démarre sur la console.

+
[listing]
----
Welcome to node setup.

You can enter the following commands at any time:
  "help" or "?" - if you want to have a question clarified,
  "back" - if you want to change previously answered questions, and
  "exit" or "quit" - if you want to quit the setup wizard.
     Any changes you made before quitting will be saved.

To accept a default or omit a question, do not enter a value.

Enter the node management interface port [e0M]:
----
. Quittez l'assistant de configuration des nœuds : `exit`
+
L'assistant de configuration du nœud se ferme et une invite de connexion s'affiche, vous avertissant que vous n'avez pas terminé les tâches de configuration.

+
Pour en savoir plus, `exit` consultez le link:https://docs.netapp.com/us-en/ontap-cli/exit.html["Référence de commande ONTAP"^].

. Connectez-vous au compte admin à l'aide de `admin` nom d'utilisateur.
. Démarrez l'assistant de configuration du cluster :
+
[listing]
----
::> cluster setup

Welcome to the cluster setup wizard.

You can enter the following commands at any time:
 "help" or "?" - if you want to have a question clarified,
 "back" - if you want to change previously answered questions, and
 "exit" or "quit" - if you want to quit the cluster setup wizard.
 Any changes you made before quitting will be saved.

You can return to cluster setup at any time by typing "cluster setup".
To accept a default or omit a question, do not enter a value....

Use your web browser to complete cluster setup by accessing
https://<node_mgmt_or_e0M_IP_address>

Otherwise, press Enter to complete cluster setup using the
command line interface:
----
+
[NOTE]
====
Pour plus d'informations sur la configuration d'un cluster à l'aide de l'interface graphique de configuration, consultez le link:https://docs.netapp.com/us-en/ontap/task_admin_add_nodes_to_cluster.html["documentation sur la gestion des nœuds"] . Pour en savoir plus, `cluster setup` consultez le link:https://docs.netapp.com/us-en/ontap-cli/cluster-setup.html["Référence de commande ONTAP"^].

====
. Appuyez sur entrée pour effectuer cette tâche à l'aide de l'interface de ligne de commande. Lorsque vous êtes invité à créer un cluster ou à vous joindre à un cluster existant, entrez `*join*`.
+
[listing]
----
Do you want to create a new cluster or join an existing cluster? {create, join}:
join
----
+
Si la version de ONTAP exécutée sur le nouveau nœud est différente de celle exécutée sur le cluster existant, le système signale une `System checks Error: Cluster join operation cannot be performed at this time` erreur. Il s'agit du comportement attendu. Pour continuer, exécutez `cluster add-node -allow-mixed-version-join true -cluster-ips <IP address> -node-names <new_node_name>` la commande au niveau de privilège avancé à partir d'un nœud existant dans le cluster.

. Suivez les invites pour configurer le nœud et le joindre au cluster :
+
** Pour accepter la valeur par défaut d'une invite, appuyez sur entrée.
** Pour saisir votre propre valeur pour une invite, entrez la valeur, puis appuyez sur entrée.


. Répétez les étapes précédentes pour chaque nœud ajouté.


.Une fois que vous avez terminé
Une fois les nœuds ajoutés au cluster, il est conseillé d'activer le basculement du stockage pour chaque paire haute disponibilité.

.Informations associées
* link:../upgrade/concept_mixed_version_requirements.html#mixed-version-clusters-supported-for-ontap-software-upgrades["Prise en charge de clusters à version mixte pour les mises à niveau du logiciel ONTAP"]
* https://docs.netapp.com/us-en/ontap-cli/cluster-add-node.html["nœud d'ajout de cluster"^]

