---
permalink: system-admin/administrative-privilege-levels-concept.html 
sidebar: sidebar 
keywords: administrative, privilege, levels, parameters, commands, admin, advanced, diagnostic 
summary: 'Les commandes et paramètres ONTAP sont définis sur trois niveaux de privilège : admin, Advanced et diagnostic. Les niveaux de privilège reflètent les niveaux de compétence requis pour exécuter les tâches.' 
---
= Présentation des niveaux de privilège des commandes de l'interface de ligne de commandes ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les commandes et paramètres ONTAP sont définis à trois niveaux de privilèges : _admin_, _Advanced_ et _diagnostic_. Les niveaux de privilège reflètent les niveaux de compétence requis pour exécuter les tâches.

* *admin*
+
La plupart des commandes et des paramètres sont disponibles à ce niveau. Ils sont utilisés pour les tâches courantes ou de routine.

* *avancé*
+
Les commandes et les paramètres à ce niveau sont rarement utilisés, nécessitent des connaissances avancées et peuvent causer des problèmes s'ils sont utilisés de façon inappropriée.

+
Vous utilisez des commandes ou des paramètres avancés uniquement avec les conseils du personnel de support.

* *diagnostic*
+
Les paramètres et les commandes de diagnostic sont potentiellement sources de perturbation. Ils sont utilisés uniquement par le personnel de support pour diagnostiquer et corriger les problèmes.


