---
permalink: system-admin/autosupport-active-iq-digital-advisor-concept.html 
sidebar: sidebar 
keywords: autosupport, active, iq, digital, advisor, telemetry, artificial, intelligence 
summary: 'Le composant AutoSupport de ONTAP collecte les données de télémétrie et les envoie pour analyse. Le conseiller digital Active IQ analyse les données d"AutoSupport et fournit un support proactif et une optimisation. Avec l"intelligence artificielle, Active IQ peut identifier les problèmes potentiels et vous aider à les résoudre avant qu"ils n"affectent votre activité.' 
---
= Utilisez AutoSupport et Active IQ Digital Advisor
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le composant AutoSupport de ONTAP collecte les données de télémétrie et les envoie pour analyse. Le conseiller digital Active IQ analyse les données d'AutoSupport et fournit un support proactif et une optimisation. Avec l'intelligence artificielle, Active IQ peut identifier les problèmes potentiels et vous aider à les résoudre avant qu'ils n'affectent votre activité.

Active IQ vous permet d'optimiser votre infrastructure de données dans l'ensemble de votre cloud hybride grâce à un portail cloud et à une application mobile qui offrent des analyses prédictives et un support proactif. Les informations et les recommandations basées sur les données de Active IQ sont accessibles à tous les clients NetApp qui possèdent un contrat SupportEdge actif (les fonctionnalités varient selon le produit et le niveau de support).

Voici quelques avantages que vous pouvez faire avec Active IQ :

* Planification des mises à niveau. Active IQ identifie les problèmes qui peuvent être résolus dans votre environnement en effectuant une mise à niveau vers la plus récente version d'ONTAP et le composant Upgrade Advisor vous aide à planifier une mise à niveau réussie.
* Voir le bien-être du système. Votre tableau de bord Active IQ signale tout problème éventuel et vous aide à le corriger. Surveillez la capacité du système pour vous assurer que votre espace de stockage est insuffisant. Consultez les dossiers de demande de support de votre système.
* Gestion des performances. Active IQ affiche les performances du système sur une période plus longue que ce que vous pouvez voir dans System Manager. Identifiez les problèmes de configuration et de système qui ont un impact sur les performances.
* Optimisez l'efficacité. Affichez les mesures de l'efficacité du stockage et identifiez des moyens de stocker plus de données dans moins d'espace.
* Voir l'inventaire et la configuration. Active IQ affiche des informations complètes sur l'inventaire et la configuration logicielle et matérielle. Voyez quand les contrats de service arrivent à expiration et renouvelez-les pour vous assurer que vous restez pris en charge.


https://docs.netapp.com/us-en/active-iq/["Documentation NetApp : conseiller digital Active IQ"]

https://aiq.netapp.com/custom-dashboard/search["Lancez Active IQ"]

https://www.netapp.com/us/services/support-edge.aspx["Services SupportEdge"]
