---
permalink: system-admin/autosupport-creates-sends-event-messages-concept.html 
sidebar: sidebar 
keywords: autosupport, event, triggered, messages, ems, data, example 
summary: AutoSupport crée des messages AutoSupport déclenchés par les événements lorsque le système EMS traite un événement déclencheur. Un message AutoSupport déclenché par un événement alerte les destinataires des problèmes qui requièrent une action corrective et ne contient que des informations pertinentes pour le problème. Vous pouvez personnaliser le contenu à inclure et qui reçoit les messages. 
---
= Comment AutoSupport crée et envoie des messages déclenchés par des événements
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport crée des messages AutoSupport déclenchés par les événements lorsque le système EMS traite un événement déclencheur. Un message AutoSupport déclenché par un événement alerte les destinataires des problèmes qui requièrent une action corrective et ne contient que des informations pertinentes pour le problème. Vous pouvez personnaliser le contenu à inclure et qui reçoit les messages.

AutoSupport utilise le processus suivant pour créer et envoyer des messages AutoSupport déclenchés par les événements :

. Lorsque l'EMS traite un événement déclencheur, EMS envoie une requête à AutoSupport.
+
Un événement déclencheur est un événement EMS avec une destination AutoSupport et un nom commençant par un `callhome.` préfixe.

. AutoSupport crée un message AutoSupport déclenché par un événement.
+
AutoSupport collecte des informations de base et de dépannage des sous-systèmes associés au déclencheur afin de créer un message contenant uniquement les informations pertinentes pour l'événement de déclenchement.

+
Un ensemble de sous-systèmes par défaut est associé à chaque déclencheur. Cependant, vous pouvez choisir d'associer des sous-systèmes supplémentaires à un déclencheur en utilisant le `system node autosupport trigger modify` commande.

. AutoSupport envoie le message AutoSupport déclenché par l'événement aux destinataires définis par le `system node autosupport modify` commande avec `-to`, `-noteto`, `-partner-address`, et `-support` paramètres.
+
Vous pouvez activer et désactiver la transmission de messages AutoSupport pour des déclencheurs spécifiques à l'aide de la `system node autosupport trigger modify` commande avec `-to` et `-noteto` paramètres.



Le `storage shelf PSU failed` L'événement EMS déclenche un message contenant des données de base provenant des fichiers obligatoires, journaux, stockage, RAID, HA, Sous-systèmes de plate-forme et de mise en réseau et données de dépannage des sous-systèmes obligatoire, fichiers journaux et stockage.

Vous souhaitez inclure des données à propos de NFS dans tout message AutoSupport envoyé en réponse à une future `storage shelf PSU failed` événement. Vous entrez la commande suivante pour activer les données de dépannage de NFS pour le `callhome.shlf.ps.fault` événement :

[listing]
----

        cluster1::\>
        system node autosupport trigger modify -node node1 -autosupport-message shlf.ps.fault -troubleshooting-additional nfs
----
Notez que le `callhome.` le préfixe est supprimé du `callhome.shlf.ps.fault` événement lorsque vous utilisez le `system node autosupport trigger` Commandes ou lorsqu'elles sont référencées par des événements AutoSupport et EMS dans l'interface de ligne de commande.
