---
permalink: system-admin/cluster-management-server-concept.html 
sidebar: sidebar 
keywords: cluster, management, server, adminsvm, svm, single, entity 
summary: 'Le serveur de gestion de cluster, également appelé « admin SVM », est une implémentation SVM (Storage Virtual machine) spécialisée qui présente le cluster comme une seule entité gérable. Outre les services faisant office de domaine d"administration de niveau le plus élevé, le serveur de gestion du cluster possède des ressources qui n"appartiennent pas de façon logique à un SVM de données.' 
---
= Qu'est-ce que le serveur de gestion du cluster
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le serveur de gestion de cluster, également appelé __admin__SVM, est une implémentation SVM spécialisée qui présente le cluster comme une seule entité gérable. Outre les services faisant office de domaine d'administration de niveau le plus élevé, le serveur de gestion du cluster possède des ressources qui n'appartiennent pas de façon logique à un SVM de données.

Le serveur de gestion du cluster est toujours disponible sur le cluster. Vous pouvez accéder au serveur de gestion du cluster par le biais de la console ou du LIF de gestion du cluster.

En cas de défaillance de son port réseau local, la LIF de gestion du cluster bascule automatiquement vers un autre nœud du cluster. En fonction des caractéristiques de connectivité du protocole de gestion que vous utilisez, vous risquez de remarquer ou non le basculement. Si vous utilisez un protocole sans connexion (par exemple, SNMP) ou que vous disposez d'une connexion limitée (par exemple, HTTP), il est peu probable que vous remarquiez le basculement. Cependant, si vous utilisez une connexion à long terme (par exemple, SSH), vous devrez vous reconnecter au serveur de gestion du cluster après le basculement.

Lorsque vous créez un cluster, toutes les caractéristiques de la LIF de gestion du cluster sont configurées, y compris son adresse IP, son masque de réseau, sa passerelle et son port.

Contrairement à un SVM de données ou à un SVM de nœuds, un serveur de gestion du cluster ne possède pas de volume root ni de volumes utilisateur hôte (bien qu'il puisse héberger les volumes du système). En outre, un serveur de gestion du cluster ne peut avoir que des LIFs du type cluster management.

Si vous exécutez le `vserver show` commande, le serveur de gestion du cluster apparaît dans la liste de sortie de cette commande.
