---
permalink: system-admin/commands-manage-feature-licenses-reference.html 
sidebar: sidebar 
keywords: command, manage, license, command, cluster, system, feature, usage, usage 
summary: 'Vous utilisez les commandes de licence système pour gérer les licences de fonctionnalités du cluster. Vous utilisez les commandes d"utilisation des fonctions du système pour surveiller l"utilisation des fonctions.' 
---
= Commandes de gestion des licences
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous utilisez le `system license` commandes permettant de gérer les licences des fonctions pour le cluster. Vous utilisez le `system feature-usage` commandes permettant de contrôler l'utilisation des fonctions.

[cols="2,4"]
|===
| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Ajoutez une ou plusieurs licences
 a| 
`system license add`

.Exemples
L'exemple suivant ajoute une liste de licences avec les clés AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA et BBBBBBBBBBBBBBBBBBBBBBBBBBBBBB au cluster :

[]
====
Cluster1::> licence système add -code-licence AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB

====
L'exemple suivant installe les licences à partir du nœud local "/mroot/etc/lic_file" :

[]
====
cluster 1::> licence système add -use-license-file true

====


 a| 
Affiche des informations sur les licences installées, par exemple :

* Nom et description du package de licences
* Type de licence (`site`, `license`, ou `demo`)
* Date d'expiration, le cas échéant
* Les clusters ou nœuds pour lesquels une licence est accordée par un pack
* Indique si la licence a été installée avant Data ONTAP 8.2 (`legacy`)
* ID client

 a| 
`system license show`

[NOTE]
====
Certaines informations s'affichent uniquement lorsque vous utilisez le `–instance` paramètre.

====


 a| 
Afficher tous les packages qui requièrent des licences et leur état actuel de licence, y compris les éléments suivants :

* Nom du package
* La méthode sous licence
* La date d'expiration, le cas échéant

 a| 
`system license show-status`

.Exemple
L'exemple suivant affiche le statut de licence du cluster :

[]
====
cluster 1::> licence système show-status
Licence d'état Portée État détaillé
--------- ------------------ --------- -----------------------
partiellement installé
          CIFS nœud Licence manquante sur : node2-Cluster1.
          SnapRestore nœud Licence manquante sur : node2-Cluster1.
valide
          FCP nœud -
          FabricPool Cluster sur lequel le système utilise 1 To et peut utiliser jusqu'à 25 To.
non installé
          NFS - -
          ISCSI - -
          SnapMirror - -
          FlexClone - -
          SnapVault - -
          SnapLock - -
          SnapManager Suite - -
          SnapProtectApps - -
          V_StorageAttach - -
          Insight_Balance - -
          OCShift - -
          TPM - -
          VE - -
          DP_optimisé - -
sans objet
          Des offres - -
          Sélectionnez - -
20 entrées ont été affichées.

====


 a| 
Supprimez la licence d'un pack du cluster ou d'un nœud dont vous avez spécifié le numéro de série
 a| 
`system license delete`

.Exemples
L'exemple suivant illustre la suppression d'une licence nommée CIFS et du numéro de série 1-81-0000000000000000000123456 du cluster :

[]
====
Cluster 1::> licence système delete -numéro de série 1-81-0000000000000000000123456 -package CIFS

====
L'exemple suivant supprime du cluster toutes les licences du pack de licences installées pour le numéro de série 123456789 :

[]
====
Cluster1::> licence système delete { -numéro-série 123456789 -licence-installée "Core Bundle" }

====


 a| 
Afficher ou supprimer les licences expirées ou inutilisées
 a| 
`system license clean-up`

.Exemples
L'exemple suivant simule et affiche les licences qui peuvent être nettoyées :

[]
====
cluster-1::> nettoyage de la licence système -expiré -inutilisé

Les licences suivantes ont été supprimées en toute sécurité :

Numéro de série : 1-80-000011
Propriétaire: Cdancluster-1
Package Raison
--------------------------- ------------------------------------------------------------
CIFS La licence a expiré

Numéro de série : 4067154888
Propriétaire: Aucun
Package Raison
--------------------------- ------------------------------------------------------------
Des offres La licence a expiré

Numéro de série : 1-81-0000000000000004067154999
Propriétaire: Aucun
Package Raison
--------------------------- ------------------------------------------------------------
ISCSI Licence non utilisée par n'importe quel nœud du cluster
Les licences suivantes ont expiré ou sont inutilisées, mais ne peuvent pas être supprimées en toute sécurité :

Numéro de série : 4067154778
Propriétaire: Node1
Package Raison
--------------------------- ------------------------------------------------------------
Des offres La fonction serait altérée lors de la dépose

Numéro de série : 4067154779
Propriétaire: Node2
Package Raison
--------------------------- ------------------------------------------------------------
Des offres Licence générée par le système

====


 a| 
Affiche un récapitulatif de l'utilisation des fonctionnalités dans le cluster par nœud
 a| 
`system feature-usage show-summary`



 a| 
Affiche l'état d'utilisation de la fonction dans le cluster par nœud et par semaine
 a| 
`system feature-usage show-history`



 a| 
Affiche l'état du risque de droit de licence pour chaque package de licences
 a| 
`system license entitlement-risk show`

[NOTE]
====
Certaines informations s'affichent uniquement lorsque vous utilisez le `-detail` et `-instance` paramètres.

====
|===
.Informations associées
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Commandes de ONTAP 9"^]

https://kb.netapp.com/onprem/ontap/os/ONTAP_9.10.1_and_later_licensing_overview["Article de la base de connaissances : présentation des licences ONTAP 9.10.1 et versions ultérieures"^]

https://docs.netapp.com/us-en/ontap/task_admin_enable_new_features.html["Utilisez System Manager pour installer un fichier de licence NetApp"^]
