---
permalink: system-admin/commands-manage-sp-from-ontap-reference.html 
sidebar: sidebar 
keywords: command, manage, sp, ontap, network, configuration, firmware, image, ssh 
summary: 'ONTAP fournit des commandes de gestion du processeur de service, y compris la configuration réseau du processeur de service, l"image du firmware du processeur de service, l"accès SSH au processeur de service et l"administration générale du processeur de service.' 
---
= Commandes de gestion du processeur de service à partir de ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP fournit des commandes de gestion du processeur de service, y compris la configuration réseau du processeur de service, l'image du firmware du processeur de service, l'accès SSH au processeur de service et l'administration générale du processeur de service.



== Commandes permettant de gérer la configuration réseau du processeur de service

|===
| Les fonctions que vous recherchez... | Exécuter cette commande ONTAP... 


 a| 
Activez la configuration réseau automatique du processeur de service pour que ce dernier utilise la famille d'adresse IPv4 ou IPv6 du sous-réseau spécifié
 a| 
`system service-processor network auto-configuration enable`



 a| 
Désactivez la configuration réseau automatique du processeur de service pour la famille d'adresses IPv4 ou IPv6 du sous-réseau spécifié pour le processeur de service
 a| 
`system service-processor network auto-configuration disable`



 a| 
Affiche la configuration réseau automatique du processeur de service
 a| 
`system service-processor network auto-configuration show`



 a| 
Configurez manuellement le réseau du processeur de service d'un nœud, y compris les éléments suivants :

* La famille d'adresses IP (IPv4 ou IPv6)
* Indique si l'interface réseau de la famille d'adresses IP spécifiée doit être activée
* Si vous utilisez IPv4, que vous utilisiez la configuration réseau depuis le serveur DHCP ou l'adresse réseau que vous spécifiez
* Adresse IP publique du processeur de service
* Le masque de réseau du processeur de service (si vous utilisez IPv4)
* Longueur du préfixe réseau du masque de sous-réseau pour le processeur de service (en cas d'utilisation d'IPv6)
* Adresse IP de la passerelle pour le processeur de service

 a| 
`system service-processor network modify`



 a| 
Affichage de la configuration réseau du processeur de service, y compris les éléments suivants :

* La famille d'adresses configurée (IPv4 ou IPv6) et si elle est activée ou non
* Type de périphérique de gestion à distance
* État actuel du processeur de service et état de la liaison
* Configuration du réseau, comme l'adresse IP, l'adresse MAC, le masque de réseau, la longueur du préfixe du masque de sous-réseau, l'adresse IP attribuée par le routeur, l'adresse IP locale de liaison et l'adresse IP de la passerelle
* Heure à laquelle le processeur de service a été mis à jour pour la dernière fois
* Nom du sous-réseau utilisé pour la configuration automatique du processeur de service
* Indique si l'adresse IP attribuée par le routeur IPv6 est activée
* État de configuration du réseau du processeur de service
* Raison de l'échec de configuration réseau du processeur de service

 a| 
`system service-processor network show`

L'affichage des détails complets du réseau du processeur de service nécessite le `-instance` paramètre.



 a| 
Modifiez la configuration du service API du processeur de service, notamment :

* Modification du port utilisé par le service d'API du processeur de service
* Activation ou désactivation du service API du processeur de service

 a| 
`system service-processor api-service modify`

(niveau de privilège avancé)



 a| 
Affiche la configuration du service API du processeur de service
 a| 
`system service-processor api-service show`

(niveau de privilège avancé)



 a| 
Renouvelez les certificats SSL et SSH utilisés par le service API SP pour les communications internes
 a| 
* Pour ONTAP 9.5 ou version ultérieure : `system service-processor api-service renew-internal-certificates`
* Pour ONTAP 9.4 ou version antérieure : `system service-processor api-service renew-certificates`
+
(niveau de privilège avancé)



|===


== Commandes permettant de gérer l'image du firmware du processeur de service

|===
| Les fonctions que vous recherchez... | Exécuter cette commande ONTAP... 


 a| 
Afficher les détails de l'image du firmware du processeur de service actuellement installée, y compris les éléments suivants :

* Type de périphérique de gestion à distance
* Image (principale ou de sauvegarde) à partir de laquelle le processeur de service démarre, son état et la version du firmware
* Indique si la mise à jour automatique du micrologiciel est activée et que l'état de la dernière mise à jour est activé

 a| 
`system service-processor image show`

Le `-is-current` Paramètre indique l'image (principale ou de sauvegarde) à partir de laquelle le processeur de service est actuellement démarré, pas si la version du firmware installée est la plus récente.



 a| 
Activez ou désactivez la mise à jour automatique du firmware du processeur de service
 a| 
`system service-processor image modify`

Par défaut, le firmware du processeur de service est automatiquement mis à jour avec la mise à jour du ONTAP ou lorsqu'une nouvelle version du firmware du processeur de service est téléchargée manuellement. La désactivation de la mise à jour automatique n'est pas recommandée, car cela peut entraîner des combinaisons sous-optimales ou non qualifiées entre l'image ONTAP et l'image du firmware du processeur de service.



 a| 
Téléchargez manuellement une image du firmware du processeur de service sur un nœud
 a| 
`system node image get`

[NOTE]
====
Avant d'exécuter le `system node image` commandes, vous devez définir le niveau de privilège sur avancé (`set -privilege advanced`), saisissez *y* lorsque vous êtes invité à continuer.

====
L'image du firmware du processeur de service est fournie avec ONTAP. Vous n'avez pas besoin de télécharger manuellement le firmware du processeur de service, sauf si vous souhaitez utiliser une version du firmware du processeur de service différente de celle fournie avec ONTAP.



 a| 
Affichez le statut de la dernière mise à jour du firmware du processeur de service déclenchée par ONTAP, y compris les informations suivantes :

* Heure de début et de fin de la dernière mise à jour du firmware du processeur de service
* Indique si une mise à jour est en cours et le pourcentage terminé

 a| 
`system service-processor image update-progress show`

|===


== Commandes permettant de gérer l'accès SSH au processeur de service

|===
| Les fonctions que vous recherchez... | Exécuter cette commande ONTAP... 


 a| 
Accordez au SP un accès uniquement aux adresses IP spécifiées
 a| 
`system service-processor ssh add-allowed-addresses`



 a| 
Bloc les adresses IP spécifiées pour l'accès au processeur de service
 a| 
`system service-processor ssh remove-allowed-addresses`



 a| 
Affiche les adresses IP pouvant accéder au processeur de service
 a| 
`system service-processor ssh show`

|===


== Commandes d'administration générale du processeur de service

|===
| Les fonctions que vous recherchez... | Exécuter cette commande ONTAP... 


 a| 
Affichage des informations générales sur le processeur de service, notamment :

* Type de périphérique de gestion à distance
* État actuel du processeur de service
* Indique si le réseau du processeur de service est configuré ou non
* Informations sur le réseau, telles que l'adresse IP publique et l'adresse MAC
* Version du firmware du processeur de service et version de l'interface IPMI (Intelligent Platform Management interface)
* Indique si la mise à jour automatique du firmware du processeur de service est activée

 a| 
`system service-processor show` L'affichage des informations complètes du processeur de service nécessite le `-instance` paramètre.



 a| 
Redémarre le processeur de service sur un nœud
 a| 
`system service-processor reboot-sp`



 a| 
Générez et envoyez un message AutoSupport qui inclut les fichiers journaux du processeur de service collectés à partir d'un nœud spécifié
 a| 
`system node autosupport invoke-splog`



 a| 
Affiche la carte d'allocation des fichiers journaux du processeur de service collectés dans le cluster, y compris les numéros de séquence des fichiers journaux du processeur de service qui résident dans chaque nœud de collecte
 a| 
`system service-processor log show-allocations`

|===
.Informations associées
link:../concepts/manual-pages.html["Référence de commande ONTAP"]
