---
permalink: system-admin/commands-manage-mount-points-nodes-reference.html 
sidebar: sidebar 
keywords: command, manage, mount, point, nodes, spi, web, service, root, volume, root 
summary: 'Le service web spi crée automatiquement un point de montage d"un nœud vers le volume racine d"un autre nœud lors d"une demande d"accès aux fichiers journaux ou aux fichiers core du nœud. Même si vous n"avez pas besoin de gérer manuellement les points de montage, vous pouvez le faire à l"aide des commandes system node root-mount.' 
---
= Commandes permettant de gérer les points de montage sur les nœuds
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le `spi` le service web crée automatiquement un point de montage d'un nœud vers le volume racine d'un autre nœud lors d'une demande d'accès aux fichiers journaux ou fichiers « core » du nœud. Bien que vous n'ayez pas besoin de gérer manuellement les points de montage, vous pouvez le faire en utilisant le `system node root-mount` commandes.

|===
| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Créer manuellement un point de montage d'un nœud vers le volume racine d'un autre nœud
 a| 
`system node root-mount create` Un seul point de montage peut exister d'un nœud à un autre.



 a| 
Affiche les points de montage existants sur les nœuds du cluster, y compris le moment où un point de montage a été créé et son état actuel
 a| 
`system node root-mount show`



 a| 
Supprimez un point de montage d'un nœud vers le volume racine d'un autre nœud et force les connexions vers le point de montage à fermer
 a| 
`system node root-mount delete`

|===
.Informations associées
link:../concepts/manual-pages.html["Référence de commande ONTAP"]
