---
permalink: system-admin/commands-monitor-health-system-reference.html 
sidebar: sidebar 
keywords: command, monitor, health, system, display, status, cli, software, version, switches, alert 
summary: 'Vous pouvez utiliser les commandes de l"intégrité du système pour afficher des informations relatives à l"état de santé des ressources système, répondre aux alertes et configurer les alertes futures. L"utilisation des commandes de l"interface de ligne de commandes vous permet d"afficher des informations détaillées sur la configuration de la surveillance de l"état. Les pages de manuels des commandes contiennent plus d"informations.' 
---
= Commandes permettant de contrôler l'état de santé de votre système
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser `system health` les commandes pour afficher des informations relatives à l'état des ressources système, répondre aux alertes et configurer les futures alertes. L'utilisation des commandes de l'interface de ligne de commandes vous permet d'afficher des informations détaillées sur la configuration de la surveillance de l'état. Pour en savoir plus, `system health` consultez le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+health["Référence de commande ONTAP"^].



== Affiche l'état de l'état de santé du système

|===
| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Affiche l'état de santé du système, qui reflète l'état global des moniteurs d'intégrité individuels
 a| 
`system health status show`



 a| 
Affiche l'état d'intégrité des sous-systèmes pour lesquels la surveillance de l'état est disponible
 a| 
`system health subsystem show`

|===


== Affiche l'état de la connectivité du nœud

|===
| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Affiche des informations détaillées sur la connectivité du nœud au tiroir de stockage, notamment les informations relatives aux ports, la vitesse du port HBA, le débit d'E/S et le taux d'opérations d'E/S par seconde
 a| 
`storage shelf show -connectivity`

Utilisez le `-instance` paramètre pour afficher des informations détaillées sur chaque tiroir.



 a| 
Affiche des informations sur les disques et les LUN de baie, y compris l'espace utilisable, les numéros de tiroir et de compartiment, ainsi que le nom de nœud propriétaire
 a| 
`storage disk show`

Utilisez le `-instance` paramètre pour afficher des informations détaillées sur chaque lecteur.



 a| 
Affiche des informations détaillées sur les ports des tiroirs de stockage, notamment le type de port, la vitesse et l'état
 a| 
`storage port show`

Utilisez le `-instance` paramètre pour afficher des informations détaillées sur chaque adaptateur.

|===


== Gérer la détection des commutateurs de cluster, de stockage et de réseau de gestion

[cols="3*"]
|===
| Les fonctions que vous recherchez... | Utilisez cette commande. (ONTAP 9.8 et versions ultérieures) | Utilisez cette commande. (ONTAP 9.7 et versions antérieures) 


 a| 
Afficher les commutateurs surveillés par le bloc d'instruments
 a| 
`system switch ethernet show`
 a| 
`system cluster-switch show`



 a| 
Afficher les commutateurs actuellement surveillés par le cluster, notamment les commutateurs que vous avez supprimés (indiqués dans la colonne raison de la sortie de la commande) et les informations de configuration dont vous avez besoin pour accéder au réseau au cluster et aux commutateurs du réseau de gestion.

Cette commande est disponible au niveau de privilège avancé.
 a| 
`system switch ethernet show-all`
 a| 
`system cluster-switch show-all`



 a| 
Configurer la détection d'un commutateur non découvert
 a| 
`system switch ethernet create`
 a| 
`system cluster-switch create`



 a| 
Modifier les informations relatives à un commutateur que le cluster surveille (par exemple, nom de périphérique, adresse IP, version SNMP et chaîne de communauté)
 a| 
`system switch ethernet modify`
 a| 
`system cluster-switch modify`



 a| 
Désactiver la surveillance d'un commutateur
 a| 
`system switch ethernet modify -disable-monitoring`
 a| 
`system cluster-switch modify -disable-monitoring`



 a| 
Désactiver la détection et la surveillance d'un commutateur et supprimer les informations de configuration du commutateur
 a| 
`system switch ethernet delete`
 a| 
`system cluster-switch delete`



 a| 
Supprimez définitivement les informations de configuration du commutateur stockées dans la base de données (ce qui permet de réactiver la détection automatique du commutateur)
 a| 
`system switch ethernet delete -force`
 a| 
`system cluster-switch delete -force`



 a| 
Activez la journalisation automatique pour envoyer des messages AutoSupport.
 a| 
`system switch ethernet log`
 a| 
`system cluster-switch log`

|===


== Répondez aux alertes générées

|===
| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Affiche des informations sur les alertes générées, telles que la ressource et le nœud où l'alerte a été déclenchée, ainsi que la gravité et la cause probable de l'alerte
 a| 
`system health alert show`



 a| 
Affiche des informations sur chaque alerte générée
 a| 
`system health alert show -instance`



 a| 
Indique que quelqu'un travaille sur une alerte
 a| 
`system health alert modify`



 a| 
Accuser réception d'une alerte
 a| 
`system health alert modify -acknowledge`



 a| 
Supprimez une alerte ultérieure afin qu'elle n'affecte pas l'état de santé d'un sous-système
 a| 
`system health alert modify -suppress`



 a| 
Supprimez une alerte qui n'a pas été automatiquement effacée
 a| 
`system health alert delete`



 a| 
Affiche des informations sur les messages AutoSupport qui déclenchent les alertes la semaine dernière, par exemple pour déterminer si une alerte a déclenché un message AutoSupport
 a| 
`system health autosupport trigger history show`

|===


== Configurez les alertes futures

|===
| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Activez ou désactivez la règle qui contrôle si un état de ressource spécifique génère une alerte spécifique
 a| 
`system health policy definition modify`

|===


== Affiche des informations sur la configuration de la surveillance de l'état

|===
| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Affiche des informations relatives aux contrôles d'état, telles que leurs nœuds, leurs noms, leurs sous-systèmes et leur état
 a| 
`system health config show`

[NOTE]
====
Utilisez le `-instance` paramètre pour afficher des informations détaillées sur chaque contrôle de l'état.

====


 a| 
Affiche des informations sur les alertes qu'un contrôle de l'état peut générer
 a| 
`system health alert definition show`

[NOTE]
====
Utilisez le `-instance` paramètre pour afficher des informations détaillées sur chaque définition d'alerte.

====


 a| 
Affiche des informations sur les règles de contrôle de l'état, qui déterminent l'heure à laquelle les alertes sont émises
 a| 
`system health policy definition show`

[NOTE]
====
Utilisez le `-instance` paramètre pour afficher des informations détaillées sur chaque règle. Utilisez d'autres paramètres pour filtrer la liste des alertes, par exemple en fonction de l'état (activé ou non), du contrôle de l'état, de l'alerte, etc.

====
|===
Pour en savoir plus sur les commandes décrites dans cette procédurelink:https://docs.netapp.com/us-en/ontap-cli/["Référence de commande ONTAP"^], reportez-vous à la .
