---
permalink: system-admin/commands-manage-audit-settings-reference.html 
sidebar: sidebar 
keywords: command, manage, audit, settings, management, activity 
summary: 'Vous utilisez les commandes d"audit de sécurité pour gérer les activités de gestion consignées dans le fichier audit.log. Les commandes de transfert de journaux de cluster permettent de gérer les destinations vers lesquelles le journal d"audit est transmis.' 
---
= Commandes permettant de gérer les paramètres d'audit des activités de gestion
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous utilisez le `security audit` commandes permettant de gérer les activités de gestion consignées dans le système `audit.log` fichier. Vous utilisez le `cluster log-forwarding` commandes permettant de gérer les destinations de transfert du journal d'audit vers.

|===
| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Spécifiez que les demandes GET depuis l'interface de ligne de commande ONTAP ou les API doivent être enregistrées dans le journal d'audit (l' `audit.log` file), en plus des demandes de jeu par défaut
 a| 
`security audit modify`



 a| 
Affiche les paramètres du journal d'audit
 a| 
`security audit show`



 a| 
Affiche les entrées d'audit fusionnées à partir de plusieurs nœuds du cluster
 a| 
`security audit log show`



 a| 
Spécifiez une destination de transfert pour le journal d'audit et les mesures de sécurité pour sa transmission
 a| 
`cluster log-forwarding create`



 a| 
Modifier une destination pour le journal d'audit
 a| 
`cluster log-forwarding modify`



 a| 
Supprime une destination pour le journal d'audit
 a| 
`cluster log-forwarding delete`



 a| 
Affiche les destinations configurées pour le journal d'audit
 a| 
`cluster log-forwarding show`

|===
.Informations associées
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["Commandes de ONTAP 9"^]
