---
permalink: system-admin/commands-manage-node-remotely-reference.html 
sidebar: sidebar 
keywords: command, manage, node, remotely, sp, cli, cluster 
summary: 'Vous pouvez gérer un nœud à distance en accédant à son processeur de service et en exécutant des commandes de l"interface de ligne de commandes du processeur de service afin d"effectuer des tâches de gestion des nœuds. Dans le cas de plusieurs tâches courantes de gestion des nœuds à distance, vous pouvez également utiliser les commandes ONTAP d"un autre nœud du cluster. Certaines commandes du processeur de service sont spécifiques à la plateforme et peuvent ne pas être disponibles sur votre plateforme.' 
---
= Commandes ONTAP pour la gestion à distance des nœuds
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez gérer un nœud à distance en accédant à son processeur de service et en exécutant des commandes de l'interface de ligne de commandes du processeur de service afin d'effectuer des tâches de gestion des nœuds. Dans le cas de plusieurs tâches courantes de gestion des nœuds à distance, vous pouvez également utiliser les commandes ONTAP d'un autre nœud du cluster. Certaines commandes du processeur de service sont spécifiques à la plateforme et peuvent ne pas être disponibles sur votre plateforme.

|===
| Les fonctions que vous recherchez... | Utilisez cette commande du processeur de service... | Utilisez cette commande BMC... | Ou cette commande ONTAP ... 


 a| 
Affiche les commandes ou sous-commandes du processeur de service disponibles d'une commande SP spécifiée
 a| 
`help` [`command`]
 a| 
 a| 



 a| 
Affiche le niveau de privilège actuel pour l'interface de ligne de commandes du processeur de service
 a| 
`priv show`
 a| 
 a| 



 a| 
Définissez le niveau de privilège pour accéder au mode spécifié pour l'interface de ligne de commandes du processeur de service
 a| 
`priv set` {`admin` | `advanced` | `diag`}
 a| 
 a| 



 a| 
Afficher la date et l'heure du système
 a| 
`date`
 a| 
 a| 
`date`



 a| 
Affiche les événements consignés par le processeur de service
 a| 
`events` {`all` | `info` | `newest` `number` | `oldest number` | `search keyword`}
 a| 
 a| 



 a| 
Affiche l'état du processeur de service et les informations de configuration réseau
 a| 
`sp status` [`-v` | `-d`]

Le `-v` Option affiche les statistiques du processeur de service sous forme détaillée. Le `-d` Option ajoute le journal de débogage du processeur de service à l'affichage.
 a| 
`bmc status` [`-v` | `-d`]

Le `-v` Option affiche les statistiques du processeur de service sous forme détaillée. Le `-d` Option ajoute le journal de débogage du processeur de service à l'affichage.
 a| 
`system service-processor show`



 a| 
Affiche la durée de mise en service du processeur de service et le nombre moyen de tâches de la file d'attente d'exécution au cours des 1, 5 et 15 dernières minutes
 a| 
`sp uptime`
 a| 
`bmc uptime`
 a| 



 a| 
Affiche les journaux de la console du système
 a| 
`system log`
 a| 
 a| 



 a| 
Affiche les archives du journal du processeur de service ou les fichiers d'une archive
 a| 
`sp log history show` [`-archive` {`latest` |{`all` | `archive-name`}] [`-dump` {`all` | `file-name`}]
 a| 
`bmc log history show` [`-archive` {`latest` |{`all` | `archive-name`}] [`-dump` {`all` | `file-name`}]
 a| 



 a| 
Affiche l'état de mise sous tension du contrôleur d'un nœud
 a| 
`system power status`
 a| 
 a| 
`system node power show`



 a| 
Afficher les informations sur la batterie
 a| 
`system battery show`
 a| 
 a| 



 a| 
Affiche les informations ACP ou l'état des capteurs du module d'extension
 a| 
`system acp` [`show` | `sensors show`]
 a| 
 a| 



 a| 
Répertorier toutes les unités remplaçables sur site et leurs ID
 a| 
`system fru list`
 a| 
 a| 



 a| 
Affiche les informations produit pour l'unité remplaçable sur site spécifiée
 a| 
`system fru show` `fru_id`
 a| 
 a| 



 a| 
Affiche le journal d'historique des données FRU
 a| 
`system fru log show` (niveau de privilège avancé)
 a| 
 a| 



 a| 
Affiche le statut des capteurs environnementaux, y compris leurs États et leurs valeurs actuelles
 a| 
`system sensors` ou `system sensors show`
 a| 
 a| 
`system node environment sensors show`



 a| 
Affiche l'état et les détails du capteur spécifié
 a| 
`system sensors get` `sensor_name`

Vous pouvez obtenir `sensor_name` à l'aide du `system sensors` ou le `system sensors show` commande.
 a| 
 a| 



 a| 
Affiche les informations de version du firmware du processeur de service
 a| 
`version`
 a| 
 a| 
`system service-processor image show`



 a| 
Affiche l'historique des commandes du processeur de service
 a| 
`sp log audit` (niveau de privilège avancé)
 a| 
`bmc log audit`
 a| 



 a| 
Affiche les informations de débogage du processeur de service
 a| 
`sp log debug` (niveau de privilège avancé)
 a| 
`bmc log debug` (niveau de privilège avancé)
 a| 



 a| 
Affiche le fichier des messages du processeur de service
 a| 
`sp log messages` (niveau de privilège avancé)
 a| 
`bmc log messages` (niveau de privilège avancé)
 a| 



 a| 
Affiche les paramètres de collecte d'analyses système lors d'un événement de réinitialisation de la surveillance, affiche les informations d'analyse système recueillies lors d'un événement de réinitialisation de la surveillance ou efface les informations d'analyse système recueillies
 a| 
`system forensics` [`show` | `log dump` | `log clear`]
 a| 
 a| 



 a| 
Connectez-vous à la console du système
 a| 
`system console`
 a| 
 a| 
`system node run-console`



 a| 
Vous devez appuyer sur Ctrl-D pour quitter la session de console du système.



 a| 
Mise sous tension ou hors tension du nœud, ou réalisation d'une mise hors/sous tension (mise hors tension, puis remise sous tension)
 a| 
`system power` `on`
 a| 
 a| 
`system node power on` (niveau de privilège avancé)



 a| 
`system power` `off`
 a| 
 a| 



 a| 
`system power` `cycle`
 a| 
 a| 



 a| 
L'alimentation de veille reste allumée pour maintenir le processeur de service en fonctionnement sans interruption. Pendant la mise hors/sous tension, une brève pause se produit avant de remettre l'alimentation en marche.

[NOTE]
====
À l'aide de ces commandes, la mise hors/sous tension du nœud peut provoquer un arrêt incorrect du nœud (également appelé _shutdown_) et ne remplace pas un arrêt normal à l'aide de ONTAP `system node halt` commande.

====


 a| 
Créer un « core dump » et réinitialiser le nœud
 a| 
`system core` [`-f`]

Le `-f` option force la création d'un « core dump » et la réinitialisation du nœud.
 a| 
 a| 
`system node coredump trigger`

(niveau de privilège avancé)



 a| 
Ces commandes ont le même effet que d'appuyer sur le bouton non masquable Interrupt (NMI) d'un nœud, provoquant un arrêt non planifié du nœud et forçant un vidage des fichiers core lors de l'arrêt du nœud. Ces commandes sont utiles lorsque ONTAP sur le nœud est arrêté ou ne répond pas aux commandes telles que `system node shutdown`. Les fichiers core dump générés sont affichés dans la sortie du `system node coredump show` commande. Le processeur de service reste opérationnel tant que l'alimentation en entrée du nœud n'est pas interrompue.



 a| 
Redémarrez le nœud à l'aide d'une image du micrologiciel du BIOS (primaire, de sauvegarde ou de courant) spécifiée en option pour effectuer une restauration suite à des problèmes tels qu'une image corrompue du périphérique d'amorçage du nœud
 a| 
`system reset` {`primary` | `backup` | `current`}
 a| 
 a| 
`system node reset` avec le `-firmware` {`primary` | `backup` | `current`} paramètre (niveau de privilège avancé)

`system node reset`



 a| 
[NOTE]
====
Cette opération provoque un arrêt non planifié du nœud.

====
Si aucune image du micrologiciel du BIOS n'est spécifiée, l'image actuelle est utilisée pour le redémarrage. Le processeur de service reste opérationnel tant que l'alimentation en entrée du nœud n'est pas interrompue.



 a| 
Affiche l'état de la mise à jour automatique du firmware des batteries ou active ou désactive la mise à jour automatique du firmware des batteries lors du prochain démarrage du SP
 a| 
`system battery auto_update` [`status` | `enable` | `disable`]

(niveau de privilège avancé)
 a| 
 a| 



 a| 
Comparez l'image actuelle du micrologiciel de la batterie à une image de micrologiciel spécifiée
 a| 
`system battery verify` [`image_URL`]

(niveau de privilège avancé)

Si `image_URL` n'est pas spécifié, l'image du micrologiciel de la batterie par défaut est utilisée pour la comparaison.
 a| 
 a| 



 a| 
Mettez à jour le micrologiciel de la batterie à partir de l'image à l'emplacement spécifié
 a| 
`system battery flash` `image_URL`

(niveau de privilège avancé)

Vous utilisez cette commande si le processus de mise à niveau automatique du micrologiciel de la batterie a échoué pour une raison quelconque.
 a| 
 a| 



 a| 
Mettez à jour le firmware du processeur de service en utilisant l'image à l'emplacement spécifié
 a| 
`sp update` `image_URL image_URL` il ne doit pas dépasser 200 caractères.
 a| 
`bmc update` `image_URL image_URL` il ne doit pas dépasser 200 caractères.
 a| 
`system service-processor image update`



 a| 
Redémarre le processeur de service
 a| 
`sp reboot`
 a| 
 a| 
`system service-processor reboot-sp`



 a| 
Effacez le contenu Flash de la mémoire NVRAM
 a| 
`system nvram flash clear` (niveau de privilège avancé)

Cette commande ne peut pas être démarrée lorsque le contrôleur est hors tension (`system power off`).
 a| 
 a| 



 a| 
Quittez l'interface de ligne de commandes du processeur de service
 a| 
`exit`
 a| 
 a| 

|===