---
permalink: system-admin/commands-manage-web-protocol-engine-reference.html 
sidebar: sidebar 
keywords: command, manage, web, protocol, engine, firewall, system, services 
summary: 'Vous utilisez les commandes Web des services système pour gérer le moteur de protocole Web. Vous utilisez les commandes de création de la politique de pare-feu des services système et de modification de l"interface réseau pour permettre aux demandes d"accès Web de passer par le pare-feu.' 
---
= Commandes de gestion du moteur de protocole Web
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous utilisez le `system services web` commandes permettant de gérer le moteur de protocole web. Vous utilisez le `system services firewall policy create` et `network interface modify` commandes permettant d'autoriser les demandes d'accès web à passer par le pare-feu.

|===
| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Configurer le moteur de protocole Web au niveau du cluster :

* Activez ou désactivez le moteur de protocole Web pour le cluster
* Activez ou désactivez SSLv3 pour le cluster
* Activer ou désactiver la conformité FIPS 140-2 pour des services web sécurisés (HTTPS)

 a| 
`system services web modify`



 a| 
Afficher la configuration du moteur de protocole Web au niveau du cluster, déterminer si les protocoles Web sont fonctionnels dans tout le cluster et indiquer si la conformité FIPS 140-2 est activée et en ligne
 a| 
`system services web show`



 a| 
Afficher la configuration du moteur de protocole Web au niveau du nœud et l'activité de gestion du service Web pour les nœuds du cluster
 a| 
`system services web node show`



 a| 
Créez une politique de pare-feu ou ajoutez un service de protocole HTTP ou HTTPS à une politique de pare-feu existante pour permettre aux demandes d'accès Web de passer par le pare-feu
 a| 
`system services firewall policy create`

Réglage du `-service` paramètre à `http` ou `https` permet aux demandes d'accès web de passer par le pare-feu.



 a| 
Associer une politique de pare-feu à une LIF
 a| 
`network interface modify`

Vous pouvez utiliser le `-firewall-policy` Paramètre pour modifier la politique de pare-feu d'une LIF.

|===
.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html["modification de l'interface réseau"^]

