---
permalink: system-admin/commands-manage-autosupport-reference.html 
sidebar: sidebar 
keywords: command, manage, autosupport, node, message, send, resend, cancel, configure, display, information 
summary: 'Les commandes AutoSupport du nœud système permettent de modifier ou d"afficher la configuration AutoSupport, d"afficher les informations relatives aux messages AutoSupport précédents et d"envoyer, de renvoyer ou d"annuler un message AutoSupport.' 
---
= Commandes de gestion de AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous utilisez le `system node autosupport` Commandes permettant de modifier ou d'afficher la configuration AutoSupport, d'afficher des informations sur les messages AutoSupport précédents et d'envoyer, de renvoyer ou d'annuler un message AutoSupport.



== Configurez AutoSupport

|===
| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Contrôlez si des messages AutoSupport sont envoyés
 a| 
`system node autosupport modify` avec le `-state` paramètre



 a| 
Contrôlez si les messages AutoSupport sont envoyés au support technique
 a| 
`system node autosupport modify` avec le `-support` paramètre



 a| 
Configurer AutoSupport ou modifier la configuration de AutoSupport
 a| 
`system node autosupport modify`



 a| 
Activez et désactivez les messages AutoSupport à votre organisation de support interne pour les événements de déclenchement individuels. Vous pouvez également spécifier des rapports de sous-système supplémentaires à inclure dans les messages envoyés en réponse aux événements de déclenchement individuels
 a| 
`system node autosupport trigger modify`

|===


== Affiche des informations sur la configuration AutoSupport

|===
| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Afficher la configuration AutoSupport
 a| 
`system node autosupport show` avec le `-node` paramètre



 a| 
Afficher un récapitulatif de toutes les adresses et URL qui reçoivent des messages AutoSupport
 a| 
`system node autosupport destinations show`



 a| 
Affichez les messages AutoSupport envoyés à votre organisation de support interne pour des événements déclencheurs individuels
 a| 
`system node autosupport trigger show`



 a| 
Affichage de l'état de la configuration AutoSupport ainsi que de la livraison vers différentes destinations
 a| 
`system node autosupport check show`



 a| 
Affiche l'état détaillé de la configuration AutoSupport ainsi que la livraison à différentes destinations
 a| 
`system node autosupport check show-details`

|===


== Affiche les informations relatives aux messages AutoSupport précédents

|===
| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Affiche des informations sur un ou plusieurs des 50 messages AutoSupport les plus récents
 a| 
`system node autosupport history show`



 a| 
Affiche des informations sur les messages AutoSupport récents générés pour télécharger les fichiers core dump ou archive des performances vers le site de support technique ou un URI spécifié
 a| 
`system node autosupport history show-upload-details`



 a| 
Affichez les informations des messages AutoSupport, y compris le nom et la taille de chaque fichier collecté pour le message, ainsi que toute erreur
 a| 
`system node autosupport manifest show`

|===


== Envoyer, renvoyer ou annuler des messages AutoSupport

|===
| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Retransmettez un message AutoSupport stocké localement, identifié par son numéro de séquence AutoSupport


NOTE: Si vous retransmettez un message AutoSupport et que le support a déjà reçu ce message, le système de support ne crée pas de dossier en double. Si, par contre, le support ne recevait pas ce message, le système AutoSupport analysera le message et créera un dossier, si nécessaire.
 a| 
`system node autosupport history retransmit`



 a| 
Générer et envoyer un message AutoSupport, par exemple, à des fins de test
 a| 
`system node autosupport invoke`


NOTE: Utilisez le `-force` Paramètre permettant d'envoyer un message même si AutoSupport est désactivé. Utilisez le `-uri` paramètre pour envoyer le message à la destination que vous spécifiez au lieu de la destination configurée.



 a| 
Annuler un message AutoSupport
 a| 
`system node autosupport history cancel`

|===
.Informations associées
link:../concepts/manual-pages.html["Référence de commande ONTAP"]
