---
permalink: system-admin/control-system-health-alerts-concept.html 
sidebar: sidebar 
keywords: system, health, alert, customization, monitor, enable, disable 
summary: 'Vous pouvez contrôler les alertes qu"un contrôle de l"état génère en activant et en désactivant les politiques d"intégrité du système qui définissent lorsque les alertes sont déclenchées. Cela vous permet de personnaliser le système de surveillance de l"état de santé pour votre environnement particulier.' 
---
= Personnalisation des alertes d'intégrité du système
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez contrôler les alertes qu'un contrôle de l'état génère en activant et en désactivant les politiques d'intégrité du système qui définissent lorsque les alertes sont déclenchées. Cela vous permet de personnaliser le système de surveillance de l'état de santé pour votre environnement particulier.

Pour connaître le nom d'une règle, vous pouvez afficher des informations détaillées sur une alerte générée ou afficher les définitions de règles pour un contrôle de l'état, un nœud ou un ID d'alerte spécifique.

La désactivation des politiques de santé est différente de la suppression des alertes. Lorsque vous supprimez une alerte, elle n'a pas d'impact sur l'état de santé du sous-système, mais l'alerte peut toujours se produire.

Si vous désactivez une règle, la condition ou l'état défini dans son expression de règle de gestion ne déclenche plus d'alerte.

.Exemple d'alerte que vous souhaitez désactiver
Par exemple, supposons qu'une alerte ne vous soit pas utile. Vous utilisez le `system health alert show –instance` Commande pour obtenir l'ID de la règle pour l'alerte. Vous utilisez l'ID de la police dans le `system health policy definition show` commande pour afficher les informations relatives à la règle. Après avoir vérifié l'expression de règle et d'autres informations sur la stratégie, vous décidez de la désactiver. Vous utilisez le `system health policy definition modify` commande pour désactiver la règle.
