---
permalink: system-admin/create-motd-task.html 
sidebar: sidebar 
keywords: create, motd, cli, user, clustershell, ssh, session, cluster, access, message, day 
summary: 'Vous pouvez créer un message du jour (MOTD) pour communiquer des informations aux utilisateurs authentifiés de CLI. Le mot MOTD s"affiche dans une session de console (pour l"accès au cluster uniquement) ou dans une session SSH (pour l"accès au cluster ou SVM) après l"authentification d"un utilisateur, mais avant l"affichage de l"invite clustershell.' 
---
= Créer un MOTD
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer un message du jour (MOTD) pour communiquer des informations aux utilisateurs authentifiés de CLI. Le mot MOTD s'affiche dans une session de console (pour l'accès au cluster uniquement) ou dans une session SSH (pour l'accès au cluster ou SVM) après l'authentification d'un utilisateur, mais avant l'affichage de l'invite clustershell.

.Étapes
. Utilisez le `security login motd modify` Commande pour créer un MOTD pour le cluster ou le SVM :
+
|===
| Les fonctions que vous recherchez... | Alors... 


 a| 
Spécifiez un message à une seule ligne
 a| 
Utilisez le `-message` «[.code]``text``" paramètre pour spécifier le texte.



 a| 
Inclure les nouvelles lignes (également appelée fin de lignes)
 a| 
Utiliser la commande sans `-message` ou `-uri` Paramètre pour lancer le mode interactif pour modifier le MOTD.



 a| 
Téléchargez le contenu à partir d'un emplacement pour le MOTD
 a| 
Utilisez le `-uri` Paramètre pour spécifier l'emplacement FTP ou HTTP du contenu.

|===
+
La taille maximale d'un MOTD est de 2,048 octets, y compris les nouvelles lignes.

+
Le `security login motd modify` La page man décrit les séquences d'échappement que vous pouvez utiliser pour permettre au MOTD d'afficher du contenu généré dynamiquement.

+
Un MOTD créé à l'aide du `-uri` paramètre statique. Elle n'est pas mise à jour automatiquement pour refléter les modifications ultérieures du contenu source.

+
Un MOTD créé pour le cluster est également affiché pour toutes les connexions de SVM par défaut, ainsi qu'un MOTD de niveau SVM que vous pouvez créer séparément pour un SVM donné. Réglage du `-is-cluster-message-enabled` paramètre à `false` Pour un SVM, il n'est pas possible de visualiser la MOTD niveau du cluster pour ce SVM.

. Vérifiez que le MOTD a été créé en l'affichant avec le `security login motd show` commande.
+
Spécification du `-message` paramètre avec une chaîne vide (`""`) Affiche les MOTDS qui ne sont pas configurés ou n'ont pas de contenu.

+
Voir la https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr-980/security%5F%5Flogin%5F%5Fmotd%5F%5Fmodify.html["code de connexion de sécurité motd modifier"] Page de manuel de commande pour une liste de paramètres à utiliser pour permettre au MOTD d'afficher le contenu généré dynamiquement. Assurez-vous de consulter la page de manuel spécifique à votre version de ONTAP.



.Exemples de création de MOTDS
L'exemple suivant utilise le mode non interactif pour créer un MOTD pour le cluster « cluster1 » :

[listing]
----
cluster1::> security login motd modify -message "Greetings!"
----
L'exemple suivant utilise le mode interactif pour créer un MOTD pour le SVM "`svm1'"qui utilise les séquences d'échappement pour afficher le contenu généré dynamiquement :

[listing]
----
cluster1::> security login motd modify -vserver svm1

Enter the message of the day for Vserver "svm1".
Max size: 2048. Enter a blank line to terminate input. Press Ctrl-C to abort.
0        1         2         3         4         5         6         7         8
12345678901234567890123456789012345678901234567890123456789012345678901234567890
Welcome to the \n SVM.  Your user ID is '\N'. Your last successful login was \L.
----
L'exemple suivant affiche les MOTDS qui ont été créés :

[listing]
----
cluster1::> security login motd show
Vserver: cluster1
Is the Cluster MOTD Displayed?: true
Message
-----------------------------------------------------------------------------
Greetings!

Vserver: svm1
Is the Cluster MOTD Displayed?: true
Message
-----------------------------------------------------------------------------
Welcome to the \n SVM.  Your user ID is '\N'. Your last successful login was \L.

2 entries were displayed.
----