---
permalink: system-admin/create-banner-task.html 
sidebar: sidebar 
keywords: create, banner, svm, access, cluster, ssh, session 
summary: 'Vous pouvez créer une bannière pour afficher un message à quelqu"un qui tente d"accéder au cluster ou à un SVM. La bannière s"affiche dans une session de console (pour l"accès au cluster uniquement) ou dans une session SSH (pour l"accès au cluster ou SVM) avant qu"un utilisateur soit invité à s"authentifier.' 
---
= Créez une bannière
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez créer une bannière pour afficher un message à quelqu'un qui tente d'accéder au cluster ou à un SVM. La bannière s'affiche dans une session de console (pour l'accès au cluster uniquement) ou dans une session SSH (pour l'accès au cluster ou SVM) avant qu'un utilisateur soit invité à s'authentifier.

.Étapes
. Utilisez le `security login banner modify` Commande pour créer une bannière pour le cluster ou le SVM :
+
|===
| Les fonctions que vous recherchez... | Alors... 


 a| 
Spécifiez un message à une seule ligne
 a| 
Utilisez le `-message` «[.code]``text``" paramètre pour spécifier le texte.



 a| 
Inclure les nouvelles lignes (également appelées fin de lignes) dans le message
 a| 
Utiliser la commande sans `-message` ou `-uri` paramètre pour lancer le mode interactif d'édition de la bannière.



 a| 
Téléchargez le contenu depuis un emplacement pour l'utiliser pour la bannière
 a| 
Utilisez le `-uri` Paramètre pour spécifier l'emplacement FTP ou HTTP du contenu.

|===
+
La taille maximale d'une bannière est de 2,048 octets, y compris les newlines.

+
Bannière créée à l'aide du `-uri` paramètre statique. Elle n'est pas mise à jour automatiquement pour refléter les modifications ultérieures du contenu source.

+
La bannière créée pour le cluster est également affichée pour tous les SVM qui ne disposent pas de bannière existante. Toute bannière créée pour un SVM remplace la bannière de niveau cluster pour ce SVM. Spécification du `-message` paramètre avec un tiret dans les guillemets doubles (`"-"`) Pour la SVM réinitialise le SVM pour l'utilisation de la bannière cluster.

. Vérifiez que la bannière a été créée en l'affichant avec le `security login banner show` commande.
+
Spécification du `-message` paramètre avec une chaîne vide (`""`) affiche des bannières qui n'ont pas de contenu.

+
Spécification du `-message` paramètre avec `"-"` Affiche tous les SVM (admin ou data) ne disposant pas de bannière configurée.



L'exemple suivant utilise le mode non interactif pour créer une bannière pour le cluster « cluster1 » :

[listing]
----
cluster1::> security login banner modify -message "Authorized users only!"

cluster1::>
----
L'exemple suivant utilise le mode interactif pour créer une bannière pour le SVM "`svm1'":

[listing]
----
cluster1::> security login banner modify -vserver svm1

Enter the message of the day for Vserver "svm1".
Max size: 2048. Enter a blank line to terminate input. Press Ctrl-C to abort.
0        1         2         3         4         5         6         7         8
12345678901234567890123456789012345678901234567890123456789012345678901234567890
The svm1 SVM is reserved for authorized users only!


cluster1::>
----
L'exemple suivant montre les bannières créées :

[listing]
----
cluster1::> security login banner show
Vserver: cluster1
Message
-----------------------------------------------------------------------------
Authorized users only!

Vserver: svm1
Message
-----------------------------------------------------------------------------
The svm1 SVM is reserved for authorized users only!

2 entries were displayed.

cluster1::>
----
xref:manage-banner-reference.adoc[Gestion de la bannière]
