---
permalink: system-admin/different-shells-cli-commands-concept-cluster-admin.html 
sidebar: sidebar 
keywords: diag, secd, different, shells, cli, commands, cluster, administrators, clustershell, nodeshell, systemshell 
summary: Le cluster possède trois shells différents pour les commandes CLI, le clustershell, le nodeshell et le systemshell. Les coques sont à des fins différentes, et elles ont chacune un jeu de commandes différent. 
---
= À propos des différents shells pour la présentation des commandes CLI (administrateurs de cluster uniquement)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le cluster a trois shells différents pour les commandes CLI, le _clustershell_, le _nodeshell_ et le _systemshell_. Les coques sont à des fins différentes, et elles ont chacune un jeu de commandes différent.

* Le clustershell est le shell natif qui démarre automatiquement lorsque vous vous connectez au cluster.
+
Il fournit toutes les commandes dont vous avez besoin pour configurer et gérer le cluster. L'aide CLI clustershell (déclenchée par `?` à l'invite clustershell) affiche les commandes clustershell disponibles. Le `man _command_name_` commande dans le clustershell affiche la page man pour la commande clustershell spécifiée.

* Le nodeshell est un shell spécial pour les commandes qui prennent effet uniquement au niveau du nœud.
+
Le nodeshell est accessible via le `system node run` commande.

+
Aide de l'interface de ligne de commande du nodeshell (déclenchée par `?` ou `help` à l'invite nodeshell) affiche les commandes disponibles du nodeshell. Le `man _command_name_` la commande dans le nodeshell affiche la page man pour la commande nodeshell spécifiée.

+
De nombreuses commandes et options de nodeshell couramment utilisées sont regroupées ou alitées dans le clustershell et peuvent également être exécutées à partir du clustershell.

* Le systemshell est un shell de bas niveau qui est utilisé uniquement pour le diagnostic et la résolution de problèmes.
+
Le systemshell et le compte "diag" associé sont destinés à des fins de diagnostic de bas niveau. Leur accès requiert le niveau de privilège de diagnostic et est réservé uniquement au support technique pour effectuer les tâches de dépannage.


