---
permalink: system-admin/different-shells-cli-commands-concept-cluster-admin.html 
sidebar: sidebar 
keywords: diag, secd, different, shells, cli, commands, cluster, administrators, clustershell, nodeshell, systemshell, display, list, help 
summary: Le cluster possède trois shells différents pour les commandes CLI, le clustershell, le nodeshell et le systemshell. Les coques sont à des fins différentes, et elles ont chacune un jeu de commandes différent. 
---
= En savoir plus sur les différents shells ONTAP pour les commandes CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le cluster a trois shells différents pour les commandes CLI, le _clustershell_, le _nodeshell_ et le _systemshell_. Les coques sont à des fins différentes, et elles ont chacune un jeu de commandes différent.

* Le clustershell est le shell natif qui démarre automatiquement lorsque vous vous connectez au cluster.
+
Il fournit toutes les commandes dont vous avez besoin pour configurer et gérer le cluster. L'aide de l'interface de ligne de commande du cluster shell (déclenchée par `?` à l'invite du cluster shell) affiche les commandes clustershell disponibles. La `man _command_name_` commande du cluster shell affiche la page man de la commande clustershell spécifiée. Pour en savoir plus, `man _command_name_` consultez le link:https://docs.netapp.com/us-en/ontap-cli/man.html["Référence de commande ONTAP"^].

* Le nodeshell est un shell spécial pour les commandes qui prennent effet uniquement au niveau du nœud.
+
Le nodeshell est accessible via la `system node run` commande. Pour en savoir plus, `system node run` consultez le link:https://docs.netapp.com/us-en/ontap-cli/system-node-run.html["Référence de commande ONTAP"^].

+
Aide de l'interface de ligne de commande du nodeshell (déclenchée par `?` ou `help` à l'invite nodeshell) affiche les commandes disponibles du nodeshell. Le `man _command_name_` la commande dans le nodeshell affiche la page man pour la commande nodeshell spécifiée.

+
De nombreuses commandes et options de nodeshell couramment utilisées sont regroupées ou alitées dans le clustershell et peuvent également être exécutées à partir du clustershell.

* Le systemshell est un shell de bas niveau qui est utilisé uniquement pour le diagnostic et la résolution de problèmes.
+
Le systemshell et le compte "diag" associé sont destinés à des fins de diagnostic de bas niveau. Leur accès requiert le niveau de privilège de diagnostic et est réservé uniquement au support technique pour effectuer les tâches de dépannage.



Pour en savoir plus sur les commandes décrites dans cette procédurelink:https://docs.netapp.com/us-en/ontap-cli/["Référence de commande ONTAP"^], reportez-vous à la .



== Accès aux commandes et options du nodeshell dans le clustershell

Les commandes et options de Nodeshell sont accessibles via le nodeshell:

`system node run –node _nodename_`

De nombreuses commandes et options de nodeshell couramment utilisées sont regroupées ou alitées dans le clustershell et peuvent également être exécutées à partir du clustershell.

Les options Nodeshell prises en charge dans le clustershell sont accessibles à l'aide du `vserver options clustershell` commande. Pour voir ces options, vous pouvez effectuer l'une des opérations suivantes :

* Interroger la CLI clustershell avec `vserver options -vserver _nodename_or_clustername_ -option-name ?`
* Pour en savoir plus, `vserver options` consultez le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+options["Référence de commande ONTAP"^].


Si vous saisissez une commande ou une option nodeshell ou hérité dans le clustershell et que la commande ou l'option a une commande clustershell équivalente, ONTAP vous informe de la commande clustershell à utiliser.

Si vous entrez une commande ou une option de nodeshell ou hérité qui n'est pas prise en charge dans le clustershell, ONTAP vous informe de l'état « non pris en charge » pour la commande ou l'option.



== Affiche les commandes nodeshell disponibles

Vous pouvez obtenir la liste des commandes du nodeshell disponibles en utilisant l'aide de la CLI du nodeshell.

.Étapes
. Pour accéder au nodeshell, entrez la commande suivante à l'invite du système du clustershell :
+
`*system node run -node {_nodename_|local}*`

+
`local` est le nœud que vous utilisez pour accéder au cluster.

+
[NOTE]
====
Le `system node run` la commande a une commande alias, `run`.

====
. Entrez la commande suivante dans le nodeshell pour voir la liste des commandes disponibles du nodeshell :
+
`*[_commandname_] help*`

+
 `_commandname_` est le nom de la commande dont vous souhaitez afficher la disponibilité. Si vous n'incluez pas `_commandname_`, La CLI affiche toutes les commandes du nodeshell disponibles.

+
Vous entrez `exit` Ou tapez Ctrl-d pour revenir à la CLI clustershell.



.Exemple d'affichage des commandes de nodeshell disponibles
L'exemple suivant accède au nodeshell d'un nœud nommé node2 et affiche les informations relatives à la commande nodeshell `environment`:

[listing]
----
cluster1::> system node run -node node2
Type 'exit' or 'Ctrl-D' to return to the CLI

node2> environment help
Usage: environment status |
     [status] [shelf [<adapter>[.<shelf-number>]]] |
     [status] [shelf_log] |
     [status] [shelf_stats] |
     [status] [shelf_power_status] |
     [status] [chassis [all | list-sensors | Temperature | PSU 1 |
     PSU 2 | Voltage | SYS FAN | NVRAM6-temperature-3 | NVRAM6-battery-3]]
----