---
permalink: system-admin/enable-telnet-rsh-access-cluster-task.html 
sidebar: sidebar 
keywords: enable, telnet, rsh, access, cluster, mgmt, management, service, policy 
summary: 'En tant que pratique de sécurité, Telnet et RSH sont désactivés par défaut. Pour permettre au cluster d"accepter les demandes Telnet ou RSH, vous devez activer le service dans la stratégie de service de gestion par défaut.' 
---
= Activer l'accès Telnet ou RSH au cluster
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
En tant que pratique de sécurité, Telnet et RSH sont désactivés par défaut. Pour permettre au cluster d'accepter les demandes Telnet ou RSH, vous devez activer le service dans la stratégie de service de gestion par défaut.

.Description de la tâche
* RSH n'est pas un protocole sécurisé.
+
Vous devez envisager d'utiliser SSH pour accéder au cluster. SSH fournit un shell distant sécurisé et une session réseau interactive.

* ONTAP prend en charge un maximum de 50 sessions RSH simultanées par nœud.
+
Si la LIF de cluster management réside sur le nœud, il partage cette limite avec la LIF de node management.

+
Si le taux de connexions entrantes est supérieur à 10 par seconde, le service est temporairement désactivé pendant 60 secondes.

* Les commandes RSH nécessitent des privilèges avancés.


.Étapes
. Vérifiez que le protocole de sécurité RSH ou Telnet est activé :
+
`security protocol show`

+
.. Si le protocole de sécurité RSH ou Telnet est activé, passez à l'étape suivante.
.. Si le protocole de sécurité RSH ou Telnet n'est pas activé, utilisez la commande suivante pour l'activer :
+
`security protocol modify -application <rsh/telnet> -enabled true`



. Vérifier que le `management-rsh-server` service ou `management-telnet-server` existe sur les LIFs de management :
+
`network interface show -services management-rsh-server`

+
ou

+
`network interface show -services management-telnet-server`

+
.. Si le `management-rsh-server` service ou `management-telnet-server` existe, passez à l'étape suivante.
.. Si le `management-rsh-server` service ou `management-telnet-server` n'existe pas, utilisez la commande suivante pour l'ajouter :
+
`network interface service-policy add-service -vserver cluster1 -policy default-management -service management-rsh-server`

+
`network interface service-policy add-service -vserver cluster1 -policy default-management -service management-telnet-server`




