---
permalink: system-admin/free-space-node-root-volume-task.html 
sidebar: sidebar 
keywords: free, space, node, root, volume, full, delete, file, core, dump 
summary: 'Un message d"avertissement s"affiche lorsque le volume racine d"un nœud est plein ou presque plein. Le nœud ne peut pas fonctionner correctement lorsque son volume racine est plein. Vous pouvez libérer de l"espace sur le volume racine d"un nœud en supprimant les fichiers core dump, les fichiers de trace des paquets et les copies Snapshot du volume racine.' 
---
= Libérer de l'espace sur le volume racine d'un nœud
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un message d'avertissement s'affiche lorsque le volume racine d'un nœud est saturé ou presque plein. Le nœud ne peut pas fonctionner correctement lorsque son volume racine est plein. Vous pouvez libérer de l'espace sur le volume racine d'un nœud en supprimant les fichiers « core dump », les fichiers de trace des paquets et les copies Snapshot de volume racine.

.Étapes
. Afficher les fichiers « core dump » du nœud et leurs noms en utilisant la `system node coredump show` commande.
. Supprimez les fichiers core dump indésirables du nœud à l'aide de la `system node coredump delete` commande.
. Accès au nodeshell :
+
`*system node run -node _nodename_*`

+
`_nodename_` est le nom du nœud dont vous souhaitez libérer l'espace du volume racine.

. Passez au niveau de privilège avancé du nodeshell à partir du nodeshell :
+
`*priv set advanced*`

. Afficher et supprimer les fichiers de trace des paquets du nœud via le nodeshell :
+
.. Afficher tous les fichiers dans le volume root du nœud :
+
`*ls /etc*`

.. Si des fichiers de trace de paquets sont enregistrés (`*.trc`) sont dans le volume racine du nœud, supprimez-les individuellement :
+
`*rm /etc/log/packet_traces/_file_name.trc_*`



. Identifiez et supprimez les copies Snapshot du volume racine du nœud via le nodeshell :
+
.. Identifiez le nom du volume root :
+
`*vol status*`

+
Le volume racine est indiqué par le mot « root » dans la colonne « Options » du `vol status` sortie de la commande.

+
Dans l'exemple suivant, le volume root est `vol0`:

+
[listing]
----
node1*> vol status

         Volume State           Status            Options
           vol0 online          raid_dp, flex     root, nvfail=on
                                64-bit
----
.. Afficher les copies Snapshot du volume racine :
+
`*snap list root_vol_name*`

.. Supprimez les copies Snapshot de volume racine non souhaitées :
+
`*snap delete root_vol_namesnapshot_name*`



. Quittez le nodeshell et retournez au clustershell :
+
`*exit*`


