---
permalink: system-admin/health-monitors-concept.html 
sidebar: sidebar 
keywords: available, cluster, health, monitors, errors, detect, events, alerts, delete 
summary: 'Plusieurs moniteurs d"état permettent de surveiller différentes parties d"un cluster. Les contrôles d"état vous aident à corriger des erreurs au sein des systèmes ONTAP en détectant des événements, en vous envoyant des alertes et en supprimant les événements tels qu"ils sont clairs.' 
---
= En savoir plus sur les moniteurs d'état de cluster ONTAP disponibles
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Plusieurs moniteurs d'état permettent de surveiller différentes parties d'un cluster. Les contrôles d'état vous aident à corriger des erreurs au sein des systèmes ONTAP en détectant des événements, en vous envoyant des alertes et en supprimant les événements tels qu'ils sont clairs.

|===
| Nom du contrôle de l'état (identifiant) | Nom du sous-système (identifiant) | Objectif 


 a| 
Commutateur Ethernet
 a| 
Commutateur (commutateur - état)
 a| 
Le moniteur d'état des commutateurs Ethernet ONTAP (CSHM) surveille l'état des commutateurs du cluster et du réseau de stockage tout en collectant les journaux à des fins d'analyse. Par défaut, le CSHM interroge chaque commutateur via SNMPv2c toutes les 5 minutes pour mettre à jour les tables de ressources avec des informations sur la prise en charge, l'état de surveillance, les capteurs de température, l'utilisation du CPU, les configurations et connexions d'interface, la redondance des commutateurs de cluster et les opérations relatives aux ventilateurs et aux blocs d'alimentation. De plus, si elle est configurée, CSHM collecte les journaux via SSH/SCP toutes les heures, qui sont envoyés via AutoSupport pour une analyse plus approfondie. Sur demande, CSHM peut également effectuer une collecte de journaux de support technique plus détaillée à l'aide de SSH/SCP.

Voir link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-cshm/config-overview.html["Contrôle de l'état des commutateurs"^] pour plus de détails.



 a| 
Structure MetroCluster
 a| 
Commutateur
 a| 
Surveille la topologie de la configuration MetroCluster back-end de la structure et détecte les erreurs de configuration, comme le câblage et la segmentation incorrects ou les défaillances ISL.



 a| 
État de santé du MetroCluster
 a| 
Interconnexion, RAID et stockage
 a| 
Surveille les adaptateurs FC-VI, les adaptateurs d'initiateurs FC, les agrégats et disques situés derrière le côté gauche et les ports d'intercluster



 a| 
Connectivité nœud(nœud-Connect)
 a| 
Continuité de l'activité CIFS
 a| 
Surveille les connexions SMB afin de garantir la continuité de l'activité aux applications Hyper-V.



 a| 
Stockage (SAS-Connect)
 a| 
Surveille les tiroirs, les disques et les adaptateurs au niveau du nœud pour s'assurer que les chemins et les connexions sont appropriés.



 a| 
Système
 a| 
sans objet
 a| 
Rassemble les informations d'autres moniteurs de santé.



 a| 
Connectivité système (system-Connect)
 a| 
Stockage (SAS-Connect)
 a| 
Surveille les tiroirs au niveau du cluster pour détecter les chemins appropriés vers deux nœuds en cluster haute disponibilité.

|===