---
permalink: system-admin/install-ca-signed-client-certificate-kmip-server-task.html 
sidebar: sidebar 
keywords: install, ca, signed, client, certificate, kmip, server, key, management, interoperability, protocol, server 
summary: 'Les types client et server-ca spécifient que le certificat est utilisé pour l"authentification mutuelle du cluster et d"un gestionnaire de clés externe, tel qu"un serveur KMIP.' 
---
= Installer un certificat client signé par une autorité de certification pour le serveur KMIP dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les types client et server-ca spécifient que le certificat est utilisé pour l'authentification mutuelle du cluster et d'un gestionnaire de clés externe, tel qu'un serveur KMIP.

.Description de la tâche
Installez un certificat pour authentifier un serveur KMIP en tant que serveur SSL auprès du cluster.

.Étapes
. Utilisez la  `security certificate install`commande avec le  `-type server-ca`paramètre pour installer un certificat pour le serveur KMIP.
. Lorsque vous y êtes invité, entrez le certificat, puis appuyez sur entrée.
+
ONTAP vous rappelle de conserver une copie du certificat à des fins de référence ultérieure.

+
[listing]
----
cluster1::> security certificate install -type server-ca -vserver cluster1

Please enter Certificate: Press <Enter> when done
-----BEGIN CERTIFICATE-----
<certificate_value>
-----END CERTIFICATE-----


You should keep a copy of the CA-signed digital certificate for future reference.

cluster1::>
----


.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-install.html["installation du certificat de sécurité"^]

