---
permalink: system-admin/install-ca-signed-client-certificate-kmip-server-task.html 
sidebar: sidebar 
keywords: install, ca, signed, client, certificate, kmip, server, key, management, interoperability, protocol, server 
summary: 'Le sous-type de certificat du protocole KMIP (Key Management Interoperability Protocol) (paramètre -subtype kmip-cert), ainsi que les types client et serveur-ca, spécifie que le certificat est utilisé pour authentifier mutuellement le cluster et un gestionnaire de clés externe, comme un serveur KMIP.' 
---
= Installez un certificat client signé par une autorité de certification pour le serveur KMIP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le sous-type de certificat du protocole KMIP (Key Management Interoperability Protocol) (paramètre -subtype kmip-cert), ainsi que les types client et serveur-ca, spécifie que le certificat est utilisé pour authentifier mutuellement le cluster et un gestionnaire de clés externe, comme un serveur KMIP.

.Description de la tâche
Installez un certificat KMIP pour authentifier un serveur KMIP en tant que serveur SSL sur le cluster.

.Étapes
. Utilisez le `security certificate install` commande avec `-type server-ca` et `-subtype kmip-cert` Paramètres pour installer un certificat KMIP pour le serveur KMIP.
. Lorsque vous y êtes invité, entrez le certificat, puis appuyez sur entrée.
+
ONTAP vous rappelle de conserver une copie du certificat à des fins de référence ultérieure.

+
[listing]
----
cluster1::> security certificate install -type server-ca -subtype kmip-cert
-vserver cluster1

Please enter Certificate: Press <Enter> when done
-----BEGIN CERTIFICATE-----
MIICPDCCAaUCEDyRMcsf9tAbDpq40ES/Er4wDQYJKoZIhvcNAQEFBQAwXzELMAkG
2JhucwNhkcV8sEVAbkSdjbCxlnRhLQ2pRdKkkirWmnWXbj9T/UWZYB2oK0z5XqcJ
2HUw19JlYD1n1khVdWk/kfVIC0dpImmClr7JyDiGSnoscxlIaU5rfGW/D/xwzoiQ
...
-----END CERTIFICATE-----


You should keep a copy of the CA-signed digital certificate for future reference.

cluster1::>
----

