---
permalink: system-admin/keyboard-shortcuts-edit-cli-commands-reference.html 
sidebar: sidebar 
keywords: keyboard, shortcuts, edit, cli, commands, unix, tcsh, shell, emacs, editor, active 
summary: 'La commande à l"invite de commande en cours est la commande active. L"utilisation des raccourcis clavier vous permet de modifier rapidement la commande active. Ces raccourcis clavier sont similaires à ceux du shell tcsh UNIX et de l"éditeur Emacs.' 
---
= Raccourcis clavier pour la modification des commandes CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La commande à l'invite de commande en cours est la commande active. L'utilisation des raccourcis clavier vous permet de modifier rapidement la commande active. Ces raccourcis clavier sont similaires à ceux du shell tcsh UNIX et de l'éditeur Emacs.

Le tableau suivant répertorie les raccourcis clavier permettant de modifier les commandes de l'interface de ligne de commande. « Ctrl- » indique que vous maintenez la touche Ctrl enfoncée tout en tapant le caractère spécifié après. « Échap- » indique que vous appuyez sur la touche Échap et relâchez-la, puis saisissez le caractère spécifié après.

|===
| Les fonctions que vous recherchez... | Utilisez le raccourci clavier suivant... 


 a| 
Déplacez le curseur d'un caractère vers l'arrière
 a| 
Ctrl-B



 a| 
Flèche vers l'arrière



 a| 
Déplacez le curseur d'un caractère vers l'avant
 a| 
Ctrl-F



 a| 
Flèche vers l'avant



 a| 
Déplacez le curseur d'un mot vers l'arrière
 a| 
ESC-B



 a| 
Déplacez le curseur d'un mot vers l'avant
 a| 
ESC-F



 a| 
Déplacez le curseur au début de la ligne
 a| 
Ctrl-A



 a| 
Déplacez le curseur jusqu'à la fin de la ligne
 a| 
Ctrl-E



 a| 
Supprimez le contenu de la ligne de commande du début de la ligne jusqu'au curseur et enregistrez-le dans le tampon de coupe. La mémoire tampon de coupure agit comme une mémoire temporaire, similaire à ce que l'on appelle un _presse-papiers_ dans certains programmes.
 a| 
Ctrl-U



 a| 
Supprimez le contenu de la ligne de commande du curseur jusqu'à la fin de la ligne et enregistrez-le dans le tampon de découpe
 a| 
Ctrl-K



 a| 
Supprimez le contenu de la ligne de commande du curseur jusqu'à la fin du mot suivant et enregistrez-le dans le tampon de découpe
 a| 
ESC-D



 a| 
Supprimez le mot devant le curseur et enregistrez-le dans le tampon de coupe
 a| 
Ctrl-W



 a| 
Ank le contenu du tampon de coupe, et le pousser dans la ligne de commande au niveau du curseur
 a| 
Ctrl + y



 a| 
Supprimer le caractère avant le curseur
 a| 
Ctrl-H



 a| 
Retour arrière



 a| 
Supprimez le caractère où se trouve le curseur
 a| 
Ctrl-D.



 a| 
Effacez la ligne
 a| 
Ctrl-C



 a| 
Effacez l'écran
 a| 
Ctrl-L



 a| 
Remplacez le contenu actuel de la ligne de commande par l'entrée précédente de la liste d'historique.

À chaque répétition du raccourci clavier, le curseur historique se déplace vers l'entrée précédente.
 a| 
Ctrl-P



 a| 
ESC-P



 a| 
Flèche vers le haut



 a| 
Remplacez le contenu actuel de la ligne de commande par l'entrée suivante de la liste de l'historique. À chaque répétition du raccourci clavier, le curseur historique se déplace vers l'entrée suivante.
 a| 
Ctrl-N



 a| 
ESC-N



 a| 
Flèche vers le bas



 a| 
Développer une commande partiellement saisie ou répertorier une entrée valide à partir de la position d'édition actuelle
 a| 
Onglet



 a| 
Ctrl-I



 a| 
Afficher l'aide contextuelle
 a| 
?



 a| 
Échapper à la cartographie spéciale de la marque de question ("»?`") character. For instance, to enter a question mark into a command's argument, press Esc and then the "`?» caractère.
 a| 
ESC- ?



 a| 
Démarrez la sortie TTY
 a| 
Ctrl-Q



 a| 
Arrêter la sortie TTY
 a| 
Ctrl-S

|===