---
permalink: system-admin/license-types-licensed-method-concept.html 
sidebar: sidebar 
keywords: license, types, method, cluster, manage, install, add, nlf 
summary: La compréhension des types de licence et la méthode sous licence vous aident à gérer les licences dans un cluster. 
---
= Types de licence et méthode sous licence
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
La compréhension des types de licence et la méthode sous licence vous aident à gérer les licences dans un cluster.



== Types de licence

Un pack peut disposer d'un ou plusieurs des types de licence suivants installés dans le cluster. Le `system license show` commande affiche le ou les types de licence installés pour un package.

* Licence standard (`license`)
+
Une licence standard est une licence verrouillée par un nœud. Il est émis pour un nœud avec un numéro de série système spécifique (également appelé _numéro de série du contrôleur_). Une licence standard n'est valide que pour le nœud qui possède le numéro de série correspondant.

+
L'installation d'une licence standard verrouillée par un nœud donne droit à la fonctionnalité sous licence d'un nœud. Pour que le cluster utilise la fonctionnalité sous licence, au moins un nœud doit être sous licence pour cette fonctionnalité. Il se peut qu'il soit hors conformité pour utiliser la fonctionnalité sous licence sur un nœud qui ne dispose pas d'un droit pour la fonctionnalité.

* Licence de site (`site`)
+
Une licence de site n'est pas liée à un numéro de série de système spécifique. Lorsque vous installez une licence de site, tous les nœuds du cluster ont droit à la fonctionnalité sous licence. Le `system license show` la commande affiche les licences du site sous le numéro de série du cluster.

+
Si votre cluster dispose d'une licence de site et que vous supprimez un nœud du cluster, le nœud ne dispose pas de la licence de site et il n'est plus autorisé à utiliser la fonctionnalité sous licence. Si vous ajoutez un noeud à un cluster qui possède une licence de site, le noeud a automatiquement droit à la fonctionnalité accordée par la licence de site.

* Licence d'évaluation (`demo`)
+
Une licence d'évaluation est une licence temporaire qui expire après une certaine période (indiquée par le `system license show` commande). Il vous permet d'essayer certaines fonctionnalités logicielles sans avoir à acheter un droit. Il s'agit d'une licence à l'échelle du cluster, qui n'est pas liée à un numéro de série spécifique d'un nœud.

+
Si votre cluster dispose d'une licence d'évaluation pour un package et que vous supprimez un nœud du cluster, celui-ci ne supporte pas la licence d'évaluation.





== Méthode sous licence

Il est possible d'installer une licence au niveau du cluster ( `site` ou `demo` type) et une licence verrouillée par nœud ( `license` type) pour un package. Par conséquent, un package installé peut avoir plusieurs types de licence au sein du cluster. Cependant, pour le cluster, il n'y a qu'une seule méthode _licensed_ pour un package. Le `licensed method` champ du `system license status show` commande affiche le droit utilisé pour le pack. La commande détermine la méthode sous licence comme suit :

* Si un pack ne comporte qu'un seul type de licence installé dans le cluster, le type de licence installé est la méthode sous licence.
* Si aucune licence n'est installée dans le pack, la méthode sous licence est `none`.
* Si plusieurs types de licence sont installés sur un package, la méthode sous licence est déterminée dans l'ordre de priorité suivant du type de licence :-`site`, `license`, et `demo`.
+
Par exemple :

+
** Si vous disposez d'une licence de site, d'une licence standard et d'une licence d'évaluation pour un package, la méthode sous licence pour le package du cluster est `site`.
** Si vous disposez d'une licence standard et d'une licence d'évaluation pour un package, la méthode sous licence pour le package du cluster est `license`.
** Si vous ne disposez que d'une licence d'évaluation pour un package, la méthode sous licence pour le package du cluster est `demo`.



