---
permalink: concepts/licensing-concept.html 
sidebar: sidebar 
keywords: licensing, ONTAP, enable features 
summary: 'Une licence est un enregistrement d"un ou plusieurs droits logiciels. Depuis mai 2023, tous les systèmes AFF (A-Series et C-Series) et FAS sont vendus avec la suite logicielle ONTAP One ou la suite logicielle de base ONTAP.' 
---
= Présentation des licences ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une licence est un enregistrement d'un ou plusieurs droits logiciels. À partir de ONTAP 9.10.1, toutes les licences sont livrées sous forme de fichier de licence NetApp (NLF), qui est un fichier unique qui active plusieurs fonctionnalités.  À partir de mai 2023, tous les systèmes AFF (A-Series et C-Series) et FAS sont vendus avec la suite logicielle ONTAP One ou la suite logicielle de base ONTAP, chacun étant livré sous forme de NLF unique, en remplacement des bundles NLF distincts introduits initialement dans ONTAP 9.10.1.



== Licences incluses avec ONTAP One

ONTAP One contient toutes les fonctionnalités sous licence disponibles. Le tableau ci-dessous répertorie les contenus des anciens bundles de base, de protection des données, de sécurité et de conformité, de cloud hybride et de chiffrement. Le chiffrement n'est pas disponible dans les pays soumis à des restrictions.

|===


| Ancien nom de bundle | Clés ONTAP One incluses 


.5+| Bundle principal | FlexClone 


| SnapRestore 


| NFS, SMB, S3 


| FC et iSCSI 


| NVME-of 


.3+| Bundle de sécurité et de conformité | Protection autonome contre les ransomwares 


| MTKM 


| SnapLock 


.3+| Bundle de protection des données | SnapMirror (réplication asynchrone, synchrone, continuité de l'activité) 


| SnapCenter 


| S3 SnapMirror pour les cibles NetApp 


.2+| Bundle de cloud hybride | Cloud SnapMirror 


| SnapMirror S3 pour les cibles non-NetApp 


.3+| Pack de chiffrement | NetApp Volume Encryption 


| Module de plate-forme sécurisée 


| Chiffrement des données au repos 
|===


== Licences non incluses avec ONTAP One

ONTAP One n'inclut pas les services fournis dans le cloud de NetApp, notamment :

* Tiering BlueXP
* Cloud Insights
* Sauvegarde BlueXP
* Gouvernance




== ONTAP One pour les systèmes existants

Si vos systèmes existants sont actuellement pris en charge par NetApp, mais n'ont pas été mis à niveau vers ONTAP One, les licences existantes sur ces systèmes sont toujours valides et continuent de fonctionner comme prévu. Par exemple, si la licence SnapMirror est déjà installée sur les systèmes existants, il n'est pas nécessaire de passer à ONTAP One pour obtenir une nouvelle licence SnapMirror. Toutefois, si aucune licence SnapMirror n'est installée sur un système existant, la seule façon d'obtenir cette licence est de passer à ONTAP One moyennant des frais supplémentaires.

À partir de juin 2023, les systèmes ONTAP utilisant des clés de LICENCE à 28 caractères peuvent demander une mise à niveau vers le pack de compatibilité ONTAP One ou ONTAP base.



== Licences incluses avec ONTAP base

ONTAP base est une suite logicielle en option qui constitue une alternative à ONTAP One pour les systèmes ONTAP. C'est pour des utilisations spécifiques où les technologies de protection des données telles que SnapMirror et SnapCenter, ainsi que les fonctionnalités de sécurité telles que les ransomwares autonomes, ne sont pas requises, comme les systèmes non-production pour des environnements de test ou de développement dédiés. Des licences supplémentaires ne peuvent pas être ajoutées à ONTAP base. Si vous souhaitez disposer de licences supplémentaires, telles que SnapMirror, vous devez effectuer une mise à niveau vers ONTAP One.

|===


| Ancien nom de bundle | Clés ONTAP One incluses 


.5+| Bundle principal | FlexClone 


| SnapRestore 


| NFS, SMB, S3 


| FC et iSCSI 


| NVME-of 


.3+| Pack de chiffrement | NetApp Volume Encryption 


| Module de plate-forme sécurisée 


| Chiffrement des données au repos 
|===


== Autres méthodes de livraison de licence

Dans ONTAP 8.2 à ONTAP 9.9.1, les clés de licence sont livrées sous forme de chaînes de 28 caractères, et une clé par fonctionnalité ONTAP est disponible.
