---
permalink: system-admin/log-files-sent-autosupport-messages-concept.html 
sidebar: sidebar 
keywords: log, files, autosupport, message, technical, support, staff 
summary: 'Les messages AutoSupport peuvent contenir plusieurs fichiers journaux clés qui permettent au personnel du support technique de revoir l"activité récente du système.' 
---
= Fichiers journaux envoyés dans les messages AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les messages AutoSupport peuvent contenir plusieurs fichiers journaux clés qui permettent au personnel du support technique de revoir l'activité récente du système.

Tous les types de messages AutoSupport peuvent inclure les fichiers journaux suivants lorsque le sous-système fichiers journaux est activé :

|===
| Fichier journal | Quantité de données incluses dans le fichier 


 a| 
* Fichiers journaux à partir du `/mroot/etc/log/mlog/` répertoire
* Le fichier journal DES MESSAGES

 a| 
Seules les nouvelles lignes ajoutées aux journaux depuis le dernier message AutoSupport jusqu'à un maximum spécifié. Cela permet de s'assurer que les messages AutoSupport disposent de données uniques et pertinentes, sans chevauchement.

(Les fichiers journaux des partenaires font exception. Pour les partenaires, le nombre maximal de données autorisé est inclus.)



 a| 
* Fichiers journaux à partir du `/mroot/etc/log/shelflog/` répertoire
* Fichiers journaux à partir du `/mroot/etc/log/acp/` répertoire
* Données de journal du système de gestion des événements (EMS)

 a| 
Les lignes de données les plus récentes jusqu'à un maximum spécifié.

|===
Le contenu des messages AutoSupport peut changer de version d'ONTAP.
