---
permalink: system-admin/manage-access-web-services-concept.html 
sidebar: sidebar 
keywords: 'manage, access, web, service, http, https, cluster, administrator, web, protocol, engine, ssl, role, api, ontapi, disco, supdiag, sysmgr, fw, bmc, docs, "docs_api", fud, ontapmsg, portal, rest, saml, backup, back up, security, csrf' 
summary: 'Un service Web est une application que les utilisateurs peuvent accéder via HTTP ou HTTPS. L"administrateur du cluster peut configurer le moteur de protocole Web, configurer SSL, activer un service Web et permettre aux utilisateurs d"un rôle d"accéder à un service Web.' 
---
= Gérer l'accès aux services Web
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Un service Web est une application que les utilisateurs peuvent accéder via HTTP ou HTTPS. L'administrateur du cluster peut configurer le moteur de protocole Web, configurer SSL, activer un service Web et permettre aux utilisateurs d'un rôle d'accéder à un service Web.

Depuis ONTAP 9.6, les services Web suivants sont pris en charge :

* Infrastructure du processeur de service (`spi`)
+
Ce service met à disposition les fichiers log, core dump et MIB des nœuds pour l'accès HTTP ou HTTPS via la LIF de cluster management ou une LIF de node-management. Le paramètre par défaut est `enabled`.

+
Lors d'une demande d'accès aux fichiers journaux ou aux fichiers « core dump » d'un nœud, la `spi` le service web crée automatiquement un point de montage d'un nœud vers le volume racine d'un autre nœud où les fichiers résident. Il n'est pas nécessaire de créer manuellement le point de montage. `

* Les API ONTAP (`ontapi`)
+
Ce service vous permet d'exécuter des API ONTAP pour exécuter des fonctions administratives avec un programme distant. Le paramètre par défaut est `enabled`.

+
Ce service peut être requis pour certains outils de gestion externes. Par exemple, si vous utilisez System Manager, vous devez laisser ce service activé.

* Détection Data ONTAP (`disco`)
+
Ce service permet aux applications de gestion externes de découvrir le cluster sur le réseau. Le paramètre par défaut est `enabled`.

* Diagnostics du support (`supdiag`)
+
Ce service contrôle l'accès à un environnement privilégié sur le système afin d'aider à l'analyse et à la résolution des problèmes. Le paramètre par défaut est `disabled`. Vous ne devez activer ce service que si vous y êtes invité par le support technique.

* System Manager (`sysmgr`)
+
Ce service contrôle la disponibilité de System Manager, qui est inclus avec ONTAP. Le paramètre par défaut est `enabled`. Ce service est pris en charge uniquement sur le cluster.

* Mise à jour du contrôleur BMC (Baseboard Management Controller) du micrologiciel (`FW_BMC`)
+
Ce service vous permet de télécharger les fichiers du micrologiciel BMC. Le paramètre par défaut est `enabled`.

* Documentation ONTAP (`docs`)
+
Ce service fournit un accès à la documentation ONTAP. Le paramètre par défaut est `enabled`.

* API RESTful ONTAP (`docs_api`)
+
Ce service permet d'accéder à la documentation de l'API RESTful ONTAP. Le paramètre par défaut est `enabled`.

* Téléchargement de fichiers (`fud`)
+
Ce service permet le téléchargement et le téléchargement de fichiers. Le paramètre par défaut est `enabled`.

* Messagerie ONTAP (`ontapmsg`)
+
Ce service prend en charge une interface de publication et d'abonnement qui vous permet de vous abonner à des événements. Le paramètre par défaut est `enabled`.

* Portail ONTAP (`portal`)
+
Ce service implémente la passerelle dans un serveur virtuel. Le paramètre par défaut est `enabled`.

* Interface ONTAP RESTful (`rest`)
+
Ce service prend en charge une interface RESTful qui permet de gérer à distance tous les éléments de l'infrastructure du cluster. Le paramètre par défaut est `enabled`.

* Prise en charge des fournisseurs de services SAML (`saml`)
+
Ce service fournit des ressources pour prendre en charge le fournisseur de services SAML. Le paramètre par défaut est `enabled`.

* Fournisseur de services SAML (`saml-sp`)
+
Ce service offre des services tels que les métadonnées SP et le service client d'assertion au fournisseur de services. Le paramètre par défaut est `enabled`.



Depuis ONTAP 9.7, les services supplémentaires suivants sont pris en charge :

* Fichiers de sauvegarde de configuration (`backups`)
+
Ce service vous permet de télécharger les fichiers de sauvegarde de configuration. Le paramètre par défaut est `enabled`.

* Sécurité ONTAP (`security`)
+
Ce service prend en charge la gestion des jetons CSRF pour une authentification améliorée. Le paramètre par défaut est `enabled`.


