---
permalink: system-admin/manage-jobs-schedules.html 
sidebar: sidebar 
keywords: job, categories, server, cluster, affiliated, private, commands, managing, show jobs, job schedule, stop a job, delete a job, pause a job, display private jobs, modify, cron, interval, delete, interval schedule, manage jobs and schedule, manage jobs, manage schedule 
summary: 'Les travaux sont placés dans une file d"attente de travaux et exécutés en arrière-plan lorsque des ressources sont disponibles. Si une tâche consomme trop de ressources de cluster, vous pouvez l"arrêter ou le mettre en pause jusqu"à ce que la demande sur le cluster soit moins élevée. Vous pouvez également surveiller et redémarrer les travaux.' 
---
= Gestion des tâches ONTAP et des planifications de tâches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les travaux sont placés dans une file d'attente de travaux et exécutés en arrière-plan lorsque des ressources sont disponibles. Si une tâche consomme trop de ressources de cluster, vous pouvez l'arrêter ou le mettre en pause jusqu'à ce que la demande sur le cluster soit moins élevée. Vous pouvez également surveiller et redémarrer les travaux.



== Catégories de travail

Il existe trois catégories de travaux que vous pouvez gérer : affilié au serveur, affilié au cluster et privé.

Un travail peut se trouver dans l'une des catégories suivantes :

* *Travaux affiliés au serveur*
+
Ces travaux sont mis en file d'attente par l'infrastructure de gestion vers un nœud spécifique à exécuter.

* *Emplois affiliés à un groupe*
+
Ces travaux sont mis en file d'attente par l'infrastructure de gestion vers n'importe quel nœud du cluster à exécuter.

* *Emplois privés*
+
Ces jobs sont spécifiques à un nœud et n'utilisent pas la base de données répliquée (RDB) ou tout autre mécanisme du cluster. Les commandes qui gèrent les travaux privés nécessitent un niveau de privilège avancé ou supérieur.





== Commandes de gestion des travaux

Lorsque vous entrez une commande qui appelle un travail, généralement, la commande vous informe que le travail a été mis en file d'attente, puis revient à l'invite de commande CLI. Toutefois, certaines commandes indiquent plutôt la progression du travail et ne reviennent pas à l'invite de commande CLI tant que le travail n'a pas été terminé. Dans ce cas, vous pouvez appuyer sur Ctrl-C pour déplacer le travail en arrière-plan.

|===
| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Affiche des informations sur tous les travaux
 a| 
`job show`



 a| 
Affiche des informations sur les travaux par nœud
 a| 
`job show bynode`



 a| 
Affiche des informations sur les travaux affiliés à un cluster
 a| 
`job show-cluster`



 a| 
Affiche des informations sur les tâches terminées
 a| 
`job show-completed`



 a| 
Affiche des informations sur l'historique des travaux
 a| 
`job history show`

Jusqu'à 25,000 enregistrements de tâche sont stockés pour chaque nœud du cluster. Par conséquent, toute tentative d'affichage de l'historique complet du travail peut prendre beaucoup de temps. Pour éviter les temps d'attente potentiellement longs, il est conseillé d'afficher les tâches par nœud, machine virtuelle de stockage ou ID d'enregistrement.



 a| 
Affiche la liste des travaux privés
 a| 
`job private show` (niveau de privilège avancé)



 a| 
Affiche des informations sur les travaux privés terminés
 a| 
`job private show-completed` (niveau de privilège avancé)



 a| 
Affiche des informations sur l'état d'initialisation des gestionnaires de travaux
 a| 
`job initstate show` (niveau de privilège avancé)



 a| 
Surveiller la progression d'une tâche
 a| 
`job watch-progress`



 a| 
Surveiller la progression d'un travail privé
 a| 
`job private watch-progress` (niveau de privilège avancé)



 a| 
Interrompre un travail
 a| 
`job pause`



 a| 
Interrompre un travail privé
 a| 
`job private pause` (niveau de privilège avancé)



 a| 
Reprendre un travail en pause
 a| 
`job resume`



 a| 
Reprendre un travail privé en pause
 a| 
`job private resume` (niveau de privilège avancé)



 a| 
Arrêter un travail
 a| 
`job stop`



 a| 
Arrêter un travail privé
 a| 
`job private stop` (niveau de privilège avancé)



 a| 
Supprimer un travail
 a| 
`job delete`



 a| 
Supprimer un travail privé
 a| 
`job private delete` (niveau de privilège avancé)



 a| 
Dissociez un travail affilié à un cluster avec un nœud non disponible qui le possède, de sorte qu'un autre nœud puisse prendre possession de ce travail
 a| 
`job unclaim` (niveau de privilège avancé)

|===
[NOTE]
====
Vous pouvez utiliser le `event log show` commande permettant de déterminer le résultat d'un travail terminé.

====
.Informations associées
link:../concepts/manual-pages.html["Référence de commande ONTAP"]



== Commandes de gestion des planifications de travaux

De nombreuses tâches (par exemple, les snapshots de volume) peuvent être configurées pour s'exécuter selon des plannings spécifiés.les planifications qui s'exécutent à des moments spécifiques sont appelées _cron_ schedules (similaire aux planifications UNIX `cron`). Les horaires exécutés à intervalles sont appelés _interval_ planifications. Vous utilisez les `job schedule` commandes pour gérer les planifications de travaux.

Les planifications de tâches ne s'adaptent pas aux modifications manuelles apportées à la date et à l'heure du cluster. Ces travaux sont planifiés pour s'exécuter en fonction de l'heure actuelle du cluster au moment de la création du travail ou de l'exécution du travail le plus récent. Par conséquent, si vous modifiez manuellement la date ou l'heure du cluster, vous devez utiliser le `job show` et `job history show` commandes permettant de vérifier que tous les travaux planifiés sont mis en file d'attente et terminés en fonction de vos besoins.

Si le cluster fait partie d'une configuration MetroCluster, la planification de tâches sur les deux clusters doit être identique. Par conséquent, si vous créez, modifiez ou supprimez un Job planning, vous devez effectuer la même opération sur le cluster distant.

|===
| Les fonctions que vous recherchez... | Utilisez cette commande... 


 a| 
Affiche des informations sur tous les horaires
 a| 
`job schedule show`



 a| 
Affiche la liste des travaux par planning
 a| 
`job schedule show-jobs`



 a| 
Affiche des informations sur les planifications cron
 a| 
`job schedule cron show`



 a| 
Affiche des informations sur les plannings d'intervalles
 a| 
`job schedule interval show`



 a| 
Créez une planification cron
 a| 
`job schedule cron create`

À partir de ONTAP 9.10.1, vous pouvez inclure le SVM pour votre planification de tâches.



 a| 
Créer un planning d'intervalles
 a| 
`job schedule interval create`

Vous devez spécifier au moins un des paramètres suivants : `-days`, `-hours`, `-minutes`, ou `-seconds`.



 a| 
Modifier une planification cron
 a| 
`job schedule cron modify`



 a| 
Modifier un planning d'intervalles
 a| 
`job schedule interval modify`



 a| 
Supprimer un planning
 a| 
`job schedule delete`



 a| 
Supprimez une planification cron
 a| 
`job schedule cron delete`



 a| 
Supprimer un planning d'intervalles
 a| 
`job schedule interval delete`

|===
.Informations associées
link:../concepts/manual-pages.html["Référence de commande ONTAP"]
