---
permalink: system-admin/manage-banner-reference.html 
sidebar: sidebar 
keywords: manage, banner, svm, cluster, configure 
summary: Vous pouvez gérer la bannière au niveau du cluster ou de la SVM. La bannière configurée pour le cluster est également utilisée pour tous les SVM qui ne possèdent pas de message de bannière défini. Une bannière créée par la suite pour un SVM remplace la bannière de cluster pour ce SVM. 
---
= Gestion de la bannière
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez gérer la bannière au niveau du cluster ou de la SVM. La bannière configurée pour le cluster est également utilisée pour tous les SVM qui ne possèdent pas de message de bannière défini. Une bannière créée par la suite pour un SVM remplace la bannière de cluster pour ce SVM.

.Choix
* Gérez la bannière au niveau du cluster :
+
|===
| Les fonctions que vous recherchez... | Alors... 


 a| 
Créez une bannière à afficher pour toutes les sessions de connexion de l'interface de ligne de commande
 a| 
Définissez une bannière au niveau du cluster :

`*security login banner modify -vserver _cluster_name_ { [-message "text"] | [_-uri ftp_or_http_addr_] }*`



 a| 
Supprimer la bannière pour toutes les connexions (cluster et SVM)
 a| 
Définissez la bannière sur une chaîne vide (`""`) :

`*security login banner modify -vserver * -message ""*`



 a| 
Remplacer une bannière créée par un administrateur du SVM
 a| 
Modifier le message de la bannière SVM :

`*security login banner modify -vserver _svm_name_ { [-message "_text_"] | [-uri _ftp_or_http_addr_] }*`

|===
* Gestion de la bannière au niveau du SVM :
+
Spécification `-vserver _svm_name_` N'est pas requis dans le contexte SVM.

+
|===
| Les fonctions que vous recherchez... | Alors... 


 a| 
Remplacer la bannière fournie par l'administrateur du cluster avec une autre bannière pour le SVM
 a| 
Créer une bannière pour le SVM :

`*security login banner modify -vserver _svm_name_ { [-message "text"] | [-uri ftp_or_http_addr] }*`



 a| 
Supprime la bannière fournie par l'administrateur du cluster afin qu'aucune bannière ne s'affiche pour la SVM
 a| 
Définir la bannière SVM sur une chaîne vide pour le SVM :

`*security login banner modify -vserver _svm_name_ -message ""*`



 a| 
Utilisez la bannière cluster lorsque le SVM utilise actuellement une bannière de niveau SVM
 a| 
Définissez la bannière SVM sur `"-"`:

`*security login banner modify -vserver _svm_name_ -message "-"*`

|===

