---
permalink: system-admin/methods-specifying-queries-concept.html 
sidebar: sidebar 
keywords: method, use, query, operator, interface, management, unix, patterns, wildcards, command, parameter, argument 
summary: 'L"interface de gestion prend en charge les requêtes, les modèles de style UNIX et les caractères génériques pour vous permettre de faire correspondre plusieurs valeurs dans les arguments de paramètres de commande.' 
---
= Méthodes d'utilisation des opérateurs de requête
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
L'interface de gestion prend en charge les requêtes, les modèles de style UNIX et les caractères génériques pour vous permettre de faire correspondre plusieurs valeurs dans les arguments de paramètres de commande.

Le tableau suivant décrit les opérateurs de requête pris en charge :

[cols="10,90"]
|===
| Opérateur | Description 


 a| 
*
 a| 
Caractère générique correspondant à toutes les entrées.

Par exemple, la commande `volume show -volume \*tmp*` affiche la liste de tous les volumes dont le nom inclut la chaîne `tmp`.



 a| 
!
 a| 
PAS opérateur.

Indique une valeur qui ne doit pas être comparée ; par exemple, `*!vs0*` indique de ne pas correspondre à la valeur `vs0`.



 a| 
|
 a| 
OU opérateur.

Sépare deux valeurs à comparer, par exemple `*vs0 | vs2*` correspond soit à vs0, soit à vs2. Vous pouvez spécifier plusieurs instructions OU ; par exemple, `a | b* | \*c*` correspond à l'entrée `a`, toute entrée commençant par `b`, et toute entrée qui inclut `c`.



 a| 
..
 a| 
Opérateur de gamme.

Par exemple : `*5..10*` correspond à n'importe quelle valeur de `5` à `10`, inclus.



 a| 
<
 a| 
Moins que l'opérateur.

Par exemple : `*<20*` correspond à toute valeur inférieure à `20`.



 a| 
>
 a| 
Opérateur supérieur à.

Par exemple : `*>5*` correspond à toute valeur supérieure à `5`.



 a| 
\<=
 a| 
Inférieur ou égal à l'opérateur.

Par exemple : `*<=5*` correspond à toute valeur inférieure ou égale à `5`.



 a| 
>=
 a| 
Supérieur à ou égal à l'opérateur.

Par exemple : `*>=5*` correspond à toute valeur supérieure ou égale à `5`.



 a| 
{`query`}
 a| 
Requête étendue.

Une requête étendue doit être spécifiée comme premier argument après le nom de la commande, avant tout autre paramètre.

Par exemple, la commande `volume modify {-volume \*tmp*} -state offline` définit hors ligne tous les volumes dont le nom inclut la chaîne `tmp`.

|===
Si vous souhaitez analyser les caractères de requête en tant que littérales, vous devez inclure ces caractères dans des guillemets doubles (par exemple, « »{caret}', «».`", "`*`", or "`$») pour les bons résultats à retourner.

Vous pouvez utiliser plusieurs opérateurs de requête dans une seule ligne de commande. Par exemple, la commande `volume show -size >1GB -percent-used <50 -vserver !vs1` Affiche tous les volumes dont la taille est supérieure à 1 Go, inférieurs à 50 % utilisés et non sur la machine virtuelle de stockage (SVM) nommée « vs1 ».
