---
permalink: system-admin/methods-navigating-cli-command-directories-concept.html 
sidebar: sidebar 
keywords: method, navigating, cli, command, directories, hierarchy, path, structure 
summary: 'Les commandes de l"interface de ligne de commande sont organisées en hiérarchie par répertoires de commandes. Vous pouvez exécuter des commandes dans la hiérarchie en entrant le chemin de commande complet ou en parcourant la structure du répertoire.' 
---
= Navigation dans les répertoires de commandes de l'interface de ligne de commande ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les commandes de l'interface de ligne de commande sont organisées en hiérarchie par répertoires de commandes. Vous pouvez exécuter des commandes dans la hiérarchie en entrant le chemin de commande complet ou en parcourant la structure du répertoire.

Lorsque vous utilisez l'interface de ligne de commande, vous pouvez accéder à un répertoire de commandes en saisissant le nom du répertoire à l'invite, puis en appuyant sur entrée. Le nom du répertoire est alors inclus dans le texte d'invite pour indiquer que vous interagissez avec le répertoire de commande approprié. Pour aller plus loin dans la hiérarchie de commandes, entrez le nom d'un sous-répertoire de commandes, puis appuyez sur entrée. Le nom du sous-répertoire est alors inclus dans le texte d'invite et le contexte passe à ce sous-répertoire.

Vous pouvez naviguer dans plusieurs répertoires de commandes en entrant la commande entière. Par exemple, vous pouvez afficher des informations sur les disques en entrant dans le `storage disk show` commande à l'invite. Vous pouvez également exécuter la commande en parcourant un seul répertoire de commandes à la fois, comme illustré dans l'exemple suivant :

[listing]
----
cluster1::> storage
cluster1::storage> disk
cluster1::storage disk> show
----
Pour en savoir plus, `storage disk show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-show.html["Référence de commande ONTAP"^].

Vous pouvez abréger les commandes en n'entrant que le nombre minimal de lettres dans une commande qui rend la commande unique au répertoire courant. Par exemple, pour abréger la commande dans l'exemple précédent, vous pouvez entrer `st d sh`. Vous pouvez également utiliser la touche Tab pour développer des commandes abrégées et afficher les paramètres d'une commande, y compris les valeurs des paramètres par défaut.

Vous pouvez utiliser le `top` commande pour accéder au niveau supérieur de la hiérarchie de commandes et au `up` commande ou `..` commande permettant d'atteindre un niveau dans la hiérarchie de commandes.

[NOTE]
====
Les commandes et les options de commande précédées d'un astérisque (*) dans l'interface de ligne de commande ne peuvent être exécutées qu'au niveau de privilège avancé ou supérieur.

====
.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/top.html["haut"^]
* link:https://docs.netapp.com/us-en/ontap-cli/up.html["haut"^]

