---
permalink: system-admin/receive-system-health-alerts-automatic-task.html 
sidebar: sidebar 
keywords: receive, system, health, alert, automatically, system, show, command, ems, event, management, monito 
summary: 'Vous pouvez afficher manuellement les alertes d"état du système en utilisant la commande System Health Alert show. Vous devez toutefois vous abonner à des messages EMS pour recevoir automatiquement des notifications lorsqu"un contrôle de l"état génère une alerte.' 
---
= Recevez automatiquement les alertes d'intégrité du système ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez consulter manuellement les alertes d'intégrité du système à l'aide de la `system health alert show` commande. Vous devez toutefois vous abonner à des messages EMS pour recevoir automatiquement des notifications lorsqu'un contrôle de l'état génère une alerte. Pour en savoir plus, `system health alert show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/system-health-alert-show.html["Référence de commande ONTAP"^].

.Description de la tâche
La procédure suivante vous indique comment configurer les notifications pour tous les messages hm.Alert.déclenché et pour tous les messages hm.Alert.effacé.

Tous les messages hm.Alert.déclenché et tous les messages hm.Alert.décoché comprennent une interruption SNMP. Les noms des traps SNMP sont `HealthMonitorAlertRaised` et `HealthMonitorAlertCleared`. Pour plus d'informations sur les interruptions SNMP, consultez le _Network Management Guide_.

.Étapes
. Utilisez le `event destination create` Commande pour définir la destination à laquelle vous souhaitez envoyer les messages EMS.
+
[listing]
----
cluster1::> event destination create -name health_alerts -mail admin@example.com
----
+
Pour en savoir plus, `event destination create` consultez le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=event+destination+create["Référence de commande ONTAP"^].

. Utilisez le `event route add-destinations` commande permettant d'acheminer le `hm.alert.raised` message et le `hm.alert.cleared` message vers une destination.
+
[listing]
----
cluster1::> event route add-destinations -messagename hm.alert* -destinations health_alerts
----
+
Pour en savoir plus, `event route add-destinations` consultez le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=event+route+add-destinations["Référence de commande ONTAP"^].



.Informations associées
* link:../networking/networking_reference.html["Gestion du réseau"]

