---
permalink: system-admin/rules-node-root-volumes-aggregates-concept.html 
sidebar: sidebar 
keywords: node, governing, root, volume, aggregate, riles, special, directories 
summary: 'Le volume racine d"un nœud contient des répertoires et des fichiers spéciaux pour ce nœud. L"agrégat root contient le volume root. Quelques règles régissent le volume racine d"un nœud et son agrégat racine.' 
---
= Présentation des règles qui régissent les volumes racine des nœuds et les agrégats racine
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Le volume racine d'un nœud contient des répertoires et des fichiers spéciaux pour ce nœud. L'agrégat root contient le volume root. Quelques règles régissent le volume racine d'un nœud et l'agrégat racine.

Le volume racine d'un nœud est un volume FlexVol installé en usine ou par le logiciel d'installation. Il est réservé aux fichiers système, aux fichiers journaux et aux fichiers core. Le nom du répertoire est `/mroot`, qui n'est accessible que via le systemshell par le support technique. La taille minimale du volume racine d'un nœud dépend du modèle de plateforme.

* Les règles suivantes régissent le volume racine du nœud :
+
** À moins d'en recevoir l'instruction du support technique, ne modifiez pas la configuration ou le contenu du volume racine.
** Ne stockez pas les données utilisateur sur le volume racine.
+
Le stockage des données utilisateur dans le volume racine augmente le temps de rétablissement du stockage entre les nœuds d'une paire haute disponibilité.

** Vous pouvez déplacer le volume root vers un autre agrégat.
+
xref:relocate-root-volumes-new-aggregates-task.adoc[Transfert des volumes racines vers de nouveaux agrégats]



* L'agrégat root est dédié uniquement au volume root du nœud.
+
ONTAP vous empêche de créer d'autres volumes dans l'agrégat racine.



https://hwu.netapp.com["NetApp Hardware Universe"^]
