---
permalink: system-admin/sp-bmc-network-interface--firmware-updates-concept.html 
sidebar: sidebar 
keywords: sp, bmc, network, interface, firmware, update 
summary: 'Une mise à jour du firmware du processeur de service déclenchée par ONTAP avec le processeur de service qui exécute les versions 1.5, 2.5, 3.1 ou ultérieures prend en charge l"utilisation d"un mécanisme de transfert de fichiers IP sur l"interface réseau du processeur de service.' 
---
= Lorsque le SP/BMC utilise l'interface réseau pour les mises à jour du micrologiciel
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Une mise à jour du firmware du processeur de service déclenchée par ONTAP avec le processeur de service qui exécute les versions 1.5, 2.5, 3.1 ou ultérieures prend en charge l'utilisation d'un mécanisme de transfert de fichiers IP sur l'interface réseau du processeur de service.

[NOTE]
====
Cette rubrique s'applique à la fois au processeur de service et au contrôleur BMC.

====
La mise à jour du firmware du processeur de service sur l'interface réseau est plus rapide qu'une mise à jour via l'interface série. Il réduit la fenêtre de maintenance pendant laquelle le firmware du processeur de service est mis à jour, et le fonctionnement de la ONTAP ne génère aucune interruption. Des versions du processeur de service qui prennent en charge cette fonctionnalité sont incluses avec ONTAP. Ils sont également disponibles sur le site de support NetApp et peuvent être installés sur les contrôleurs qui exécutent une version compatible de ONTAP.

Lorsque vous exécutez SP version 1.5, 2.5, 3.1 ou ultérieure, les comportements de mise à niveau du micrologiciel suivants s'appliquent :

* Une mise à jour du firmware du processeur de service qui est _automatiquement_ déclenchée par ONTAP par défaut par l'utilisation de l'interface réseau pour la mise à jour. Toutefois, le processeur de service passe à l'utilisation de l'interface série pour la mise à jour du firmware si l'une des conditions suivantes se produit :
+
** L'interface réseau du processeur de service n'est pas configurée ou n'est pas disponible.
** Le transfert de fichier IP échoue.
** Le service API du processeur de service est désactivé.




Quelle que soit la version du processeur de service que vous exécutez, une mise à jour du firmware du processeur de service déclenchée par l'interface de ligne de commandes du processeur de service utilise toujours l'interface réseau du processeur de service pour la mise à jour.

https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics["Téléchargements NetApp : firmware système et diagnostics"]
