---
permalink: system-admin/sp-cli-system-console-sessions-concept.html 
sidebar: sidebar 
keywords: relationship, sp, cli, console, system, sessions, shell, environment, login, authentication 
summary: 'Vous pouvez ouvrir une session de l"interface de ligne de commandes du processeur de service afin de gérer un nœud à distance et d"ouvrir une session de console distincte du processeur de service pour accéder à la console du nœud. La session de la console du processeur de service met en miroir les valeurs de sortie affichées dans une session de console système simultanée. Le processeur de service et la console du système disposent d"environnements shell indépendants avec une authentification de connexion indépendante.' 
---
= Relations entre l'interface de ligne de commandes du processeur de service, la console du processeur de service et les sessions de console système
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez ouvrir une session de l'interface de ligne de commandes du processeur de service afin de gérer un nœud à distance et d'ouvrir une session de console distincte du processeur de service pour accéder à la console du nœud. La session de la console du processeur de service met en miroir les valeurs de sortie affichées dans une session de console système simultanée. Le processeur de service et la console du système disposent d'environnements shell indépendants avec une authentification de connexion indépendante.

La présentation de la façon dont les sessions de l'interface de ligne de commandes du processeur de service, de la console du processeur de service et de la console système sont associées permet de gérer un nœud à distance. Voici une description de la relation entre les sessions :

* Un seul administrateur peut se connecter à la session de l'interface de ligne de commandes du processeur de service à la fois. Toutefois, le processeur de service vous permet d'ouvrir simultanément une session de l'interface de ligne de commandes du processeur de service et une autre session de console du processeur de service.
+
L'interface de ligne de commandes du processeur de service est indiquée avec l'invite du processeur de service (`SP>`). Dans une session de l'interface de ligne de commandes du processeur de service, vous pouvez utiliser ce dernier `system console` Commande pour lancer une session de console du processeur de service. En même temps, vous pouvez démarrer une session de l'interface de ligne de commandes du processeur de service distincte via SSH. Si vous appuyez sur Ctrl-D pour quitter la session de console du processeur de service, vous revenez automatiquement à la session de l'interface de ligne de commandes du processeur de service. Si une session de l'interface de ligne de commandes du processeur de service existe déjà, un message vous demande si vous souhaitez mettre fin à la session de l'interface de ligne de commandes du processeur de service existante. Si vous saisissez « y », la session de l'interface de ligne de commandes du processeur de service existante est interrompue, ce qui vous permet de revenir de la console du processeur de service à l'interface de ligne de commandes du processeur de service. Cette action est enregistrée dans le journal des événements du processeur de service.

+
Dans une session de l'interface de ligne de commandes ONTAP connectée via SSH, vous pouvez basculer sur la console système d'un nœud en exécutant ONTAP `system node run-console` commande provenant d'un autre nœud.

* Pour des raisons de sécurité, la session de l'interface de ligne de commandes du processeur de service et la session de console du système ont une authentification de connexion indépendante.
+
Lorsque vous lancez une session de console du processeur de service à partir de l'interface de ligne de commandes du processeur de service (en utilisant le processeur de service) `system console` commande), vous êtes invité à fournir les informations d'identification de la console du système. Lorsque vous accédez à l'interface de ligne de commandes du processeur de service à partir d'une session de console système (en appuyant sur Ctrl-G), vous êtes invité à fournir les informations d'identification de l'interface de ligne de commandes du processeur de service.

* La session de console du processeur de service et la session de console du système ont des environnements de shell indépendants.
+
La session de la console du processeur de service met en miroir les valeurs de sortie affichées dans une session de console simultanée du système. Cependant, la session de console simultanée du système ne met pas en miroir la session de console du processeur de service.

+
La session de la console du processeur de service ne met pas en miroir les valeurs de sortie des sessions SSH simultanées.


