---
permalink: system-admin/system-health-monitoring-concept.html 
sidebar: sidebar 
keywords: monitor, health, system, cluster, conditions, alert, fault, risk, degraded, status, active 
summary: 'Cette fonction surveille de manière proactive certaines conditions critiques du cluster et déclenche des alertes en cas de défaillance ou de risque. Si des alertes sont actives, l"état de l"état du système signale un état dégradé pour le cluster. Les alertes incluent les informations dont vous avez besoin pour répondre à la dégradation de l"état du système.' 
---
= Surveillez l'état de santé de votre système
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cette fonction surveille de manière proactive certaines conditions critiques du cluster et déclenche des alertes en cas de défaillance ou de risque. Si des alertes sont actives, l'état de l'état du système signale un état dégradé pour le cluster. Les alertes incluent les informations dont vous avez besoin pour répondre à la dégradation de l'état du système.

Si l'état est dégradé, vous pouvez afficher des détails sur le problème, y compris la cause probable et les actions de récupération recommandées. Une fois le problème résolu, l'état de l'état du système revient automatiquement à OK.

L'état de l'état du système reflète plusieurs moniteurs d'état distincts. Un état dégradé au sein d'un moniteur d'état entraîne un état dégradé pour l'état global du système.

Pour plus de détails sur la prise en charge des commutateurs de cluster par ONTAP pour le contrôle de l'état du système dans votre cluster, reportez-vous au _Hardware Universe_.

https://["Commutateurs pris en charge dans le Hardware Universe"^]

Pour plus d'informations sur les causes des messages AutoSupport du moniteur d'intégrité des commutateurs de cluster (CSHM) et sur les actions nécessaires pour résoudre ces alertes, consultez l'article de la base de connaissances.

https://["Message AutoSupport : processus de surveillance de l'état CSHM"]
