---
permalink: system-admin/troubleshoot-autosupport-https-task.html 
sidebar: sidebar 
keywords: troubleshoot, autosupport, message, delivery, http, https, check, settings, resolve, problem 
summary: 'Si le système n"envoie pas le message AutoSupport attendu et que vous utilisez HTTPS, vous pouvez vérifier un certain nombre de paramètres pour résoudre le problème.' 
---
= Dépannage de la transmission des messages ONTAP AutoSupport via HTTPS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si le système n'envoie pas le message AutoSupport attendu et que vous utilisez HTTPS ou que la fonction de mise à jour automatique ne fonctionne pas, vous pouvez vérifier un certain nombre de paramètres pour résoudre le problème.

.Avant de commencer
Vous devez avoir confirmé la connectivité réseau de base et la recherche DNS :

* Votre LIF de node-management doit être active et administrative.
* Vous devez pouvoir envoyer une requête ping à un hôte opérationnel sur le même sous-réseau à partir de la LIF de gestion du cluster (il ne s'agit pas d'une LIF sur un des nœuds).
* Vous devez pouvoir envoyer des requêtes ping à un hôte opérationnel en dehors du sous-réseau à partir de la LIF de gestion du cluster.
* Vous devez pouvoir ping un hôte opérationnel hors du sous-réseau depuis la LIF de gestion du cluster utilisant le nom de l'hôte (pas l'adresse IP).


.Description de la tâche
Ces étapes sont destinées aux cas où vous avez déterminé que AutoSupport peut générer le message, mais ne peut pas le transmettre via HTTPS.

Si vous rencontrez des erreurs ou si vous ne parvenez pas à effectuer une étape de cette procédure, déterminez et traitez le problème avant de passer à l'étape suivante.

.Étapes
. Afficher l'état détaillé du sous-système AutoSupport :
+
`system node autosupport check show-details`

+
Cela inclut la vérification de la connectivité aux destinations AutoSupport via l'envoi de messages de test et la liste des erreurs possibles dans les paramètres de configuration de AutoSupport.

. Vérifier l'état du LIF node management :
+
[source, cli]
----
network interface show -home-node local -role node-mgmt -fields vserver,lif,status-oper,status-admin,address,role
----
+
Les `status-oper` champs et `status-admin` doivent renvoyer `up`. Pour en savoir plus, `up` consultez le link:https://docs.netapp.com/us-en/ontap-cli/up.html["Référence de commande ONTAP"^].

. Enregistrer le nom du SVM, le nom de la LIF et l'adresse IP de la LIF pour une utilisation ultérieure.
. Assurez-vous que le DNS est activé et configuré correctement :
+
[source, cli]
----
vserver services name-service dns show
----
. Corriger toute erreur renvoyée par le message AutoSupport :
+
[source, cli]
----
system node autosupport history show -node * -fields node,seq-num,destination,last-update,status,error
----
+
Pour obtenir de l'aide sur le dépannage des erreurs renvoyées, reportez-vous au link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/ONTAP_AutoSupport_(Transport_HTTPS_and_HTTP)_Resolution_Guide["Guide de résolution ONTAP AutoSupport (transport HTTPS et HTTP)"^].

. Vérifiez que le cluster peut accéder aux serveurs dont il a besoin et à Internet :
+
.. `network traceroute -lif node-management_LIF -destination DNS server`
.. `network traceroute -lif node_management_LIF -destination support.netapp.com`
+
[NOTE]
====
L'adresse `support.netapp.com` elle-même ne répond pas à la commande ping/traceroute, mais l'information par saut est utile.

====
.. `system node autosupport show -fields proxy-url`
.. `network traceroute -node node_management_LIF -destination proxy_url`


+
Si l'une de ces routes ne fonctionne pas, essayez la même route à partir d'un hôte fonctionnel sur le même sous-réseau que le cluster, à l'aide `traceroute` de l'utilitaire ou de `tracert` la plupart des clients réseau tiers. Vous pouvez ensuite déterminer si le problème se situe au niveau de votre configuration réseau ou de votre configuration de cluster. Pour en savoir plus, `network traceroute` consultez le link:https://docs.netapp.com/us-en/ontap-cli/network-traceroute.html["Référence de commande ONTAP"^].

. Si vous utilisez HTTPS pour votre protocole de transport AutoSupport, assurez-vous que le trafic HTTPS peut quitter le réseau :
+
.. Configurez un client web sur le même sous-réseau que la LIF de gestion du cluster.
+
Assurez-vous que tous les paramètres de configuration sont les mêmes que pour la configuration AutoSupport, y compris en utilisant le même serveur proxy, le même nom d'utilisateur, le même mot de passe et le même port.

.. L'accès `+https://support.netapp.com+` avec le client web.
+
L'accès doit être réussi. Si ce n'est pas le cas, assurez-vous que tous les pare-feu sont correctement configurés pour autoriser le trafic HTTPS et DNS et que le serveur proxy est configuré correctement. Pour plus d'informations sur la configuration de la résolution statique des noms pour support.netapp.com, consultez l'article de la base de connaissances https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_would_a_HOST_entry_be_added_in_ONTAP_for_support.netapp.com%3F["Comment ajouter une entrée D'HÔTE dans ONTAP pour support.netapp.com?"^]



. À partir de ONTAP 9.10.1, si vous activez les mises à jour automatiques, assurez-vous que vous disposez d'une connectivité HTTPS aux URL supplémentaires suivantes :
+
** \https://support-sg-emea.netapp.com
** \https://support-sg-naeast.netapp.com
** \https://support-sg-nawest.netapp.com



