---
permalink: system-admin/view-default-certificates-tls-based-applications-task.html 
sidebar: sidebar 
keywords: view, default, certificates, tls, applications, transport 
summary: 'ONTAP fournit un ensemble par défaut de certificats racine approuvés pour les applications ONTAP utilisant Transport Layer Security (TLS).' 
---
= Afficher les certificats par défaut pour les applications basées sur TLS dans ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP fournit un ensemble par défaut de certificats racine approuvés pour les applications ONTAP utilisant Transport Layer Security (TLS).

.Avant de commencer
Les certificats par défaut sont installés uniquement sur le SVM d'administration lors de sa création ou lors d'une mise à niveau.

.Description de la tâche
Les applications actuelles qui agissent en tant que client et qui nécessitent une validation de certificat sont AutoSupport, EMS, LDAP, Audit Logging, FabricPool, Et KMIP.

Lorsque les certificats expirent, un message EMS est appelé pour demander à l'utilisateur de supprimer les certificats. Les certificats par défaut ne peuvent être supprimés qu'au niveau de privilège avancé.

[NOTE]
====
La suppression des certificats par défaut peut entraîner l'absence de fonctionnement de certaines applications ONTAP (par exemple, AutoSupport et Audit Logging).

====
.Étape
. Vous pouvez afficher les certificats par défaut qui sont installés sur le SVM d'admin en utilisant la commande Security Certificate show :
+
`*security certificate show -vserver –type server-ca*`

+
[listing]
----
cluster1::> security certificate show

Vserver    Serial Number   Certificate Name                          Type
---------- --------------- ----------------------------------------- ---------
vs0        4F4E4D7B         www.example.com                            server
    Certificate Authority:  www.example.com
          Expiration Date: Thu Feb 28 16:08:28 2013
----
+
Pour en savoir plus, `security certificate show` consultez le link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-show.html?q=show["Référence de commande ONTAP"^].


