---
permalink: system-admin/when-where-autosupport-messages-sent-concept.html 
sidebar: sidebar 
keywords: active, iq, digital advisor, active iq, autosupport, messages, email, manual, scheduled, event, triggered 
summary: AutoSupport envoie des messages à différents destinataires, en fonction du type de message. Apprendre quand et où AutoSupport envoie des messages peut vous aider à comprendre les messages que vous recevez par e-mail ou que vous consultez sur le site Web de Digital Advisor. 
---
= Quand et où les messages AutoSupport sont envoyés
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AutoSupport envoie des messages à différents destinataires, en fonction du type de message. Apprendre quand et où AutoSupport envoie des messages peut vous aider à comprendre les messages que vous recevez par e-mail ou que vous consultez sur le site Web de Digital Advisor.

Sauf indication contraire, les paramètres dans les tableaux suivants sont des paramètres de l' `system node autosupport modify` commande.



== Messages déclenchés par des événements

Lorsque des événements se produisent sur le système qui nécessitent une action corrective, AutoSupport envoie automatiquement un message déclenché par un événement.

|===
| Lorsque le message est envoyé | Où le message est envoyé 


 a| 
AutoSupport répond à un événement de déclenchement dans l'EMS
 a| 
Adresses spécifiées dans `-to` et `-noteto`. (Seuls les événements critiques affectant le service sont envoyés.)

Adresses spécifiées dans `-partner-address`

Support technique, si `-support` est défini sur `enable`

|===


== Messages programmés

AutoSupport envoie automatiquement plusieurs messages selon un calendrier normal.

|===
| Lorsque le message est envoyé | Où le message est envoyé 


 a| 
Quotidien (par défaut, envoyé entre 12 h 00 et 1 h 00 en tant que message de journal)
 a| 
Adresses spécifiées dans `-partner-address`

Support technique, si `-support` est défini sur `enable`



 a| 
Quotidien (par défaut, envoyé entre 12 h 00 et 1 h 00 comme un message de performance), si le `-perf` le paramètre est défini sur `true`
 a| 
Adresses spécifiées dans -adresse-partenaire»

Support technique, si `-support` est défini sur `enable`



 a| 
Hebdomadaire (par défaut, envoyé le dimanche entre 12 h 00 et 1 h 00)
 a| 
Adresses spécifiées dans `-partner-address`

Support technique, si `-support` est défini sur `enable`

|===


== Messages déclenchés manuellement

Vous pouvez lancer ou renvoyer manuellement un message AutoSupport.

|===
| Lorsque le message est envoyé | Où le message est envoyé 


 a| 
Vous lancez manuellement un message à l'aide de `system node autosupport invoke` commande
 a| 
Si un URI est spécifié à l'aide de `-uri` paramètre dans le `system node autosupport invoke` Commande, le message est envoyé à cet URI.

Si `-uri` est omis, le message est envoyé aux adresses spécifiées dans `-to` et `-partner-address`. Le message est également envoyé au support technique si `-support` est défini sur `enable`.



 a| 
Vous lancez manuellement un message à l'aide de `system node autosupport invoke-core-upload` commande
 a| 
Si un URI est spécifié à l'aide de `-uri` paramètre dans le `system node autosupport invoke-core-upload` Commande, le message est envoyé à cet URI, et le fichier core dump est chargé sur l'URI.

Si `-uri` est omis dans le `system node autosupport invoke-core-upload` commande, le message est envoyé au support technique et le fichier « core dump » est chargé sur le site du support technique.

Cela est nécessaire dans les deux cas `-support` est défini sur `enable` et `-transport` est défini sur `https` ou `http`.

En raison de la grande taille des fichiers core dump, le message n'est pas envoyé aux adresses spécifiées dans l' `-to` et `-partner-addresses` paramètres.



 a| 
Vous lancez manuellement un message à l'aide de `system node autosupport invoke-performance-archive` commande
 a| 
Si un URI est spécifié à l'aide de `-uri` paramètre dans le `system node autosupport invoke-performance-archive` Commande, le message est envoyé à cet URI, et le fichier d'archive de performances est chargé dans l'URI.

Si `-uri` est omis dans le `system node autosupport invoke-performance-archive`, le message est envoyé au support technique et le fichier d'archive de performances est chargé sur le site de support technique.

Cela est nécessaire dans les deux cas `-support` est défini sur `enable` et `-transport` est défini sur `https` ou `http`.

En raison de la taille importante des fichiers d'archivage de performances, le message n'est pas envoyé aux adresses spécifiées dans l' `-to` et `-partner-addresses` paramètres.



 a| 
Vous renvoyez manuellement un message précédent à l'aide de `system node autosupport history retransmit` commande
 a| 
Uniquement à l'URI que vous spécifiez dans le `-uri` paramètre du `system node autosupport history retransmit` commande

|===


== Messages déclenchés par le support technique

Le support technique peut demander des messages à AutoSupport avec la fonction AutoSupport OnDemand.

|===
| Lorsque le message est envoyé | Où le message est envoyé 


 a| 
Quand AutoSupport obtient les instructions de livraison pour générer de nouveaux messages AutoSupport
 a| 
Adresses spécifiées dans `-partner-address`

Support technique, si `-support` est défini sur `enable` et `-transport` est défini sur `https`



 a| 
Quand AutoSupport obtient des instructions de livraison pour renvoyer les messages AutoSupport précédents
 a| 
Support technique, si `-support` est défini sur `enable` et `-transport` est défini sur `https`



 a| 
Quand AutoSupport obtient des instructions de livraison pour générer de nouveaux messages AutoSupport qui chargent des fichiers core dump ou d'archivage des performances
 a| 
Support technique, si `-support` est défini sur `enable` et `-transport` est défini sur `https`. Le fichier « core dump » ou d'archivage des performances est téléchargé sur le site du support technique.

|===