---
permalink: authentication/change-login-password-task.html 
sidebar: sidebar 
keywords: reset password, administrator, security login password 
summary: Vous devez modifier votre mot de passe initial immédiatement après la première connexion au système. 
---
= Modifier le mot de passe d'un administrateur ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez modifier votre mot de passe initial immédiatement après la première connexion au système. Si vous êtes un administrateur de SVM, vous pouvez utiliser `security login password` commande permettant de modifier votre propre mot de passe. Si vous êtes administrateur de cluster, vous pouvez utiliser `security login password` pour modifier le mot de passe d'un administrateur.

.Description de la tâche
Le nouveau mot de passe doit respecter les règles suivantes :

* Il ne peut pas contenir le nom d'utilisateur
* Elle doit comporter au moins huit caractères
* Il doit contenir au moins une lettre et un chiffre
* Il ne peut pas être le même que les six derniers mots de passe



NOTE: Vous pouvez utiliser `security login role config modify` la commande pour modifier les règles relatives aux mots de passe pour les comptes associés à un rôle donné.

.Avant de commencer
* Vous devez être un administrateur de cluster ou de SVM pour modifier votre propre mot de passe.
* Vous devez être un administrateur de cluster pour modifier le mot de passe d'un autre administrateur.


.Étape
. Modifier un mot de passe d'administrateur : `security login password -vserver _svm_name_ -username _user_name_`
+
La commande suivante permet de modifier le mot de passe de l'administrateur `admin1` Pour la SVM``vs1.example.com``. Vous êtes invité à saisir le mot de passe actuel, puis à saisir de nouveau le nouveau mot de passe.

+
[listing]
----
vs1.example.com::>security login password -vserver engData -username admin1
Please enter your current password:
Please enter a new password:
Please enter it again:
----


.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/security-login-role-config-modify.html["modification de la configuration du rôle de connexion de sécurité"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-login-password.html["mot de passe de connexion de sécurité"^]

