---
permalink: authentication/configure-ldap-server-access-task.html 
sidebar: sidebar 
keywords: configure, ldap, server access 
summary: 'Vous devez configurer l"accès des serveurs LDAP à une SVM avant que les comptes LDAP ne puissent accéder à la SVM. Vous pouvez utiliser la commande vserver services name-service ldap client create pour créer une configuration client LDAP sur la SVM. Vous pouvez ensuite utiliser la commande vserver services name-service ldap create pour associer la configuration client LDAP à la SVM.' 
---
= Configurez l'accès au serveur LDAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous devez configurer l'accès des serveurs LDAP à une SVM avant que les comptes LDAP ne puissent accéder à la SVM. Vous pouvez utiliser le `vserver services name-service ldap client create` Commande permettant de créer une configuration client LDAP sur le SVM. Vous pouvez ensuite utiliser le `vserver services name-service ldap create` Commande permettant d'associer la configuration client LDAP à la SVM.

.Ce dont vous avez besoin
* Vous devez avoir installé un link:install-ca-signed-server-digital-certificate-task.html["Certificat numérique de serveur signé CA"] Sur le SVM.
* Pour effectuer cette tâche, vous devez être un administrateur de cluster ou de SVM.


.Description de la tâche
La plupart des serveurs LDAP peuvent utiliser les schémas par défaut fournis par ONTAP :

* MS-AD-BIS (schéma préféré pour la plupart des serveurs AD Windows 2012 et versions ultérieures)
* AD-IDMU (serveurs AD Windows 2008, Windows 2012 et versions ultérieures)
* AD-SFU (serveurs AD Windows 2003 et versions antérieures)
* RFC-2307 (SERVEURS LDAP UNIX)


Il est préférable d'utiliser les schémas par défaut à moins qu'il n'y ait une obligation de faire autrement. Si c'est le cas, vous pouvez créer votre propre schéma en copiant un schéma par défaut et en modifiant la copie. Pour plus d'informations, reportez-vous aux documents suivants.

* link:../nfs-config/index.html["Configuration NFS"]
* https://["Rapport technique NetApp 4835 : comment configurer LDAP dans ONTAP"^]


.Étapes
. Créer une configuration client LDAP sur un SVM : `vserver services name-service ldap client create -vserver SVM_name -client-config client_configuration -servers LDAP_server_IPs -schema schema -use-start-tls true|false`
+
[NOTE]
====
Le démarrage de TLS est pris en charge uniquement pour l'accès aux SVM de données. Il n'est pas pris en charge pour l'accès aux SVM d'administration.

====
+
Pour connaître la syntaxe complète de la commande, reportez-vous au link:config-worksheets-reference.html["feuille de calcul"].

+
La commande suivante crée une configuration client LDAP nommée `corp` Sur le SVM``engData``. Le client établit des liaisons anonymes avec les adresses IP sur les serveurs LDAP `172.160.0.100` et `172.16.0.101`. Le client utilise le `RFC-2307` Schéma pour effectuer des requêtes LDAP. La communication entre le client et le serveur est cryptée à l'aide de Start TLS.

+
[listing]
----
cluster1::>vserver services name-service ldap client create
-vserver engData -client-config corp -servers 172.16.0.100,172.16.0.101 -schema RFC-2307 -use-start-tls true
----
+
[NOTE]
====
À partir de ONTAP 9.2, le champ `-ldap-servers` remplace le champ `-servers`. Ce nouveau champ peut prendre un nom d'hôte ou une adresse IP pour le serveur LDAP.

====
. Associer la configuration client LDAP au SVM : `vserver services name-service ldap create -vserver SVM_name -client-config client_configuration -client-enabled true|false`
+
Pour connaître la syntaxe complète de la commande, reportez-vous au link:config-worksheets-reference.html["feuille de calcul"].

+
La commande suivante associe la configuration du client LDAP `corp` Avec la SVM``engData``, Et active le client LDAP sur la SVM.

+
[listing]
----
cluster1::>vserver services name-service ldap create -vserver engData -client-config corp -client-enabled true
----
+
[NOTE]
====
Avec ONTAP 9.2, le `vserver services name-service ldap create` Commande effectue une validation automatique de la configuration et signale un message d'erreur si ONTAP n'est pas en mesure de contacter le serveur de noms.

====
. Valider le statut des serveurs name en utilisant la commande vserver services name-service ldap check.
+
La commande suivante valide les serveurs LDAP sur le SVM vs 0.

+
[listing]
----
cluster1::> vserver services name-service ldap check -vserver vs0

| Vserver: vs0                                                |
| Client Configuration Name: c1                               |
| LDAP Status: up                                             |
| LDAP Status Details: Successfully connected to LDAP server "10.11.12.13".                                              |
----
+
La commande name service check est disponible à partir de ONTAP 9.2.


