---
permalink: authentication/configure-local-account-mfa-totp-task.html 
sidebar: sidebar 
keywords: enable, ssh, multifactor authentication, mfa, hardware authentication device 
summary: 'Pour bénéficier d"une sécurité accrue des comptes via l"authentification multifacteur (MFA) avec un mot de passe à usage unique (TOTP), vous devez configurer votre compte utilisateur local pour l"utilisation du TOTP.' 
---
= Configurez les comptes utilisateur ONTAP locaux pour MFA avec TOTP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
À partir de la version ONTAP 9.13.1, les comptes utilisateur peuvent être configurés avec l'authentification multifacteur (MFA) avec un mot de passe à usage unique (TOTP).

.Avant de commencer
* L'administrateur du stockage doit link:setup-ssh-multifactor-authentication-task.html#enable-mfa-with-totp["Activez MFA avec TOTP"] comme deuxième méthode d'authentification pour votre compte utilisateur.
* La méthode d'authentification de votre compte utilisateur principal doit être un mot de passe utilisateur ou une clé SSH publique.
* Vous devez configurer votre application TOTP pour qu'elle fonctionne avec votre smartphone et créer votre clé secrète TOTP.
+
Microsoft Authenticator, Google Authenticator, Authy et tout autre authentificateur compatible TOTP sont pris en charge.



.Étapes
. Connectez-vous à votre compte utilisateur avec votre méthode d'authentification actuelle.
+
Votre méthode d'authentification actuelle doit être un mot de passe utilisateur ou une clé publique SSH.

. Créez la configuration TOTP sur votre compte :
+
[source, cli]
----
security login totp create -vserver "<svm_name>" -username "<account_username >"
----
. Vérifiez que la configuration TOTP est activée sur votre compte :
+
[source, cli]
----
security login totp show -vserver "<svm_name>" -username "<account_username>"
----

