---
permalink: authentication/create-svm-computer-account-domain-task.html 
sidebar: sidebar 
keywords: create, svm, computer, account, domain, cifs server 
summary: 'Si vous n"avez pas configuré de serveur SMB pour un SVM de données, vous pouvez utiliser la commande vserver active-Directory create pour créer un compte ordinateur pour le SVM sur le domaine.' 
---
= Créer un compte SVM Computer sur le domaine
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Si vous n'avez pas configuré de serveur SMB pour un SVM de données, vous pouvez utiliser le `vserver active-directory create` Commande pour créer un compte ordinateur pour le SVM sur le domaine.

Pour effectuer cette tâche, vous devez être un administrateur de cluster ou de SVM.

Une fois que vous avez saisi le `vserver active-directory create` Vous êtes invité à fournir les informations d'identification d'un compte utilisateur AD avec suffisamment de privilèges pour ajouter des ordinateurs à l'unité organisationnelle spécifiée dans le domaine. Le mot de passe du compte ne peut pas être vide.

.Étape
. Créer un compte ordinateur pour un SVM sur le domaine AD :
+
`vserver active-directory create -vserver _SVM_name_ -account-name _NetBIOS_account_name_ -domain _domain_ -ou _organizational_unit_`

+
Pour connaître la syntaxe complète de la commande, reportez-vous au link:config-worksheets-reference.html["feuille de calcul"].

+
La commande suivante crée un compte ordinateur nommé `ADSERVER1` sur le domaine `example.com` Pour la SVM `engData`. Une fois la commande saisie, vous êtes invité à saisir les informations d'identification du compte utilisateur AD.

+
[listing]
----
cluster1::>vserver active-directory create -vserver engData -account-name ADSERVER1 -domain example.com

In order to create an Active Directory machine account, you must supply the name and password of a Windows account with sufficient privileges to add computers to the "CN=Computers" container within the "example.com" domain.

Enter the user name: Administrator

Enter the password:
----

