---
permalink: authentication/create-svm-user-accounts-task.html 
sidebar: sidebar 
keywords: create, login accounts 
summary: 'Vous pouvez activer les comptes d"administrateur des clusters et des SVM locaux ou distants. Un compte local est un compte dans lequel les informations de compte, la clé publique ou le certificat de sécurité résident sur le système de stockage. Les informations de compte AD sont stockées sur un contrôleur de domaine. Les comptes LDAP et NIS résident sur des serveurs LDAP et NIS.' 
---
= Présentation de la création de comptes de connexion
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez activer les comptes d'administrateur des clusters et des SVM locaux ou distants. Un compte local est un compte dans lequel les informations de compte, la clé publique ou le certificat de sécurité résident sur le système de stockage. Les informations de compte AD sont stockées sur un contrôleur de domaine. Les comptes LDAP et NIS résident sur des serveurs LDAP et NIS.



== Administrateurs Cluster et SVM

Un _cluster Administrator_ accède au SVM d'admin pour le cluster. La SVM d'admin et un administrateur du cluster avec le nom réservé `admin` sont automatiquement créées lorsque le cluster est configuré.

Un administrateur de cluster avec la valeur par défaut `admin` le rôle peut administrer l'ensemble du cluster et ses ressources. L'administrateur du cluster peut créer d'autres administrateurs de cluster disposant de différents rôles selon les besoins.

Un _administrateur SVM_ accède à un SVM de données. L'administrateur du cluster crée des SVM de données et des administrateurs SVM si nécessaire.

Les administrateurs du SVM sont affectés à `vsadmin` rôle par défaut. L'administrateur du cluster peut attribuer différents rôles aux administrateurs du SVM si nécessaire.



=== Respecter les conventions de nom

Les noms génériques suivants ne peuvent pas être utilisés pour les comptes d'administrateur du cluster distant et du SVM :

* « adm »
* « bac »
* « cli »
* « démon »
* « ftp »
* « jeux »
* « arrêter »
* « lp »
* « courrier »
* « homme »
* « naroot »
* « NetApp »
* « actualités »
* « personne »
* « opérateur »
* « racine »
* « arrêt »
* « sshd »
* « sync »
* « sys »
* « uuucp »
* « www »




== Rôles fusionnés

Si vous activez plusieurs comptes distants pour le même utilisateur, l'utilisateur est affecté à l'Union de tous les rôles spécifiés pour les comptes. C'est-à-dire, si un compte LDAP ou NIS est affecté à `vsadmin` Et le compte de groupe AD pour le même utilisateur est affecté à `vsadmin-volume` Rôle, l'utilisateur AD se connecte avec les fonctions plus inclusives `vsadmin` capacités. Les rôles sont définis comme _fusionnés_.
