---
permalink: authentication/enable-ssl-certificate-accounts-task.html 
sidebar: sidebar 
keywords: enable, ssl certificate, accounts, security login create 
summary: 'Vous pouvez utiliser la commande Security login create pour permettre aux comptes d"administrateur d"accéder à un SVM admin ou données avec un certificat SSL.' 
---
= Activez les comptes de certificat SSL
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `security login create` Commande pour permettre aux comptes d'administrateur d'accéder à un SVM d'administration ou de données avec un certificat SSL.

.Description de la tâche
* Vous devez installer un certificat numérique de serveur signé par une autorité de certification pour que le compte puisse accéder à la SVM.
+
xref:install-server-certificate-cluster-svm-ssl-server-task.adoc[Génération et installation d'un certificat de serveur signé par une autorité de certification]

+
Vous pouvez effectuer cette tâche avant ou après avoir activé l'accès au compte.

* Si vous n'êtes pas certain du rôle de contrôle d'accès que vous souhaitez attribuer au compte de connexion, vous pouvez ajouter le rôle ultérieurement avec le `security login modify` commande.
+
xref:modify-role-assigned-administrator-task.adoc[Modification du rôle attribué à un administrateur]




NOTE: Pour les comptes d'administrateur de cluster, l'authentification par certificat est prise en charge avec `http`, `ontapi`, et `rest` en termes de latence. Pour les comptes d'administrateur SVM, l'authentification par certificat est prise en charge uniquement avec `ontapi` et `rest` en termes de latence.

.Étape
. Activer les comptes d'administrateur local pour accéder à un SVM à l'aide d'un certificat SSL :
+
`security login create -vserver SVM_name -user-or-group-name user_or_group_name -application application -authmethod authentication_method -role role -comment comment`

+
Pour en savoir plus sur les commandes décrites dans cette procédurelink:https://docs.netapp.com/us-en/ontap-cli/["Référence de commande ONTAP"^], reportez-vous à la .

+
La commande suivante active le compte d'administrateur du SVM `svmadmin2` avec la valeur par défaut `vsadmin` Rôle d'accès à la SVM``engData2`` Utilisation d'un certificat numérique SSL.

+
[listing]
----
cluster1::>security login create -vserver engData2 -user-or-group-name svmadmin2 -application ontapi -authmethod cert
----


.Une fois que vous avez terminé
Si vous n'avez pas installé de certificat numérique serveur signé par une autorité de certification, vous devez le faire avant que le compte puisse accéder à la SVM.

xref:install-server-certificate-cluster-svm-ssl-server-task.adoc[Génération et installation d'un certificat de serveur signé par une autorité de certification]
