---
permalink: authentication/grant-access-active-directory-users-groups-task.html 
sidebar: sidebar 
keywords: enable, active directory, account access 
summary: 'Vous pouvez utiliser la commande Security login create pour activer les comptes utilisateur ou groupe Active Directory (AD) pour accéder à un SVM admin ou data. Tout utilisateur du groupe AD peut accéder à la SVM avec le rôle attribué au groupe.' 
---
= Activez l'accès au compte Active Directory
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `security login create` Commande pour permettre aux utilisateurs ou groupes Active Directory (AD) d'accéder à un SVM d'administration ou de données. Tout utilisateur du groupe AD peut accéder à la SVM avec le rôle attribué au groupe.

.Ce dont vous avez besoin
* L'heure du cluster doit être synchronisée sur dans les cinq minutes qui suivent l'heure sur le contrôleur de domaine AD.
* Vous devez être un administrateur de cluster pour effectuer cette tâche.


.Description de la tâche
* Vous devez configurer l'accès du contrôleur AD domain au cluster ou au SVM avant que le compte ne puisse accéder au SVM.
+
xref:enable-ad-users-groups-access-cluster-svm-task.adoc[Configuration de l'accès au contrôleur de domaine Active Directory]

+
Vous pouvez effectuer cette tâche avant ou après avoir activé l'accès au compte.

* Vous pouvez utiliser ONTAP 9.11.1 depuis link:../nfs-admin/ldap-fast-bind-nsswitch-authentication-task.html["LDAP Fast bind pour l'authentification nsswitch"] S'il est pris en charge par le serveur LDAP AD.
* Si vous n'êtes pas certain du rôle de contrôle d'accès que vous souhaitez attribuer au compte de connexion, vous pouvez utiliser le `security login modify` commande permettant d'ajouter le rôle ultérieurement.
+
xref:modify-role-assigned-administrator-task.adoc[Modification du rôle attribué à un administrateur]



[NOTE]
====
L'accès au compte du groupe D'ANNONCES est pris en charge uniquement avec le `SSH` et `ontapi` en termes de latence.

====
.Étape
. Activer les comptes d'utilisateur ou d'administrateur de groupe AD pour accéder à un SVM :
+
`security login create -vserver SVM_name -user-or-group-name user_or_group_name -application application -authmethod domain -role role -comment comment [-is-ldap-fastbind true]`

+
Pour connaître la syntaxe complète de la commande, reportez-vous au link:config-worksheets-reference.html["feuille de calcul"].

+
link:config-worksheets-reference.html["Création ou modification de comptes de connexion"]

+
La commande suivante active le compte d'administrateur du cluster AD `DOMAIN1\guest1` avec le prédéfini `backup` Rôle d'accès à la SVM d'admin``engCluster``.

+
[listing]
----
cluster1::>security login create -vserver engCluster -user-or-group-name DOMAIN1\guest1 -application ssh -authmethod domain -role backup
----
+
La commande suivante active les comptes administrateur du SVM dans le compte AD group `DOMAIN1\adgroup` avec le prédéfini `vsadmin-volume` Rôle d'accès à la SVM``engData``.

+
[listing]
----
cluster1::>security login create -vserver engData -user-or-group-name DOMAIN1\adgroup -application ssh -authmethod domain -role vsadmin-volume
----


.Une fois que vous avez terminé
Si vous n'avez pas configuré l'accès au contrôleur AD domain au cluster ou au SVM, vous devez le faire avant que le compte puisse accéder au SVM.

xref:enable-ad-users-groups-access-cluster-svm-task.adoc[Configuration de l'accès au contrôleur de domaine Active Directory]
