---
permalink: authentication/grant-access-active-directory-users-groups-task.html 
sidebar: sidebar 
keywords: enable, active directory, account access 
summary: 'Vous pouvez utiliser la commande Security login create pour activer les comptes utilisateur ou groupe Active Directory (AD) pour accéder à un SVM admin ou data. Tout utilisateur du groupe AD peut accéder à la SVM avec le rôle attribué au groupe.' 
---
= Activez l'accès au compte ONTAP Active Directory
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser `security login create` la commande pour permettre aux comptes d'utilisateur ou de groupe Active Directory d'accéder à un SVM d'administrateur ou de données. Tout utilisateur du groupe AD peut accéder à la SVM avec le rôle attribué au groupe. Pour en savoir plus, `security login create` consultez le link:https://docs.netapp.com/us-en/ontap-cli/security-login-create.html["Référence de commande ONTAP"^].

.Description de la tâche
* Vous devez configurer l'accès du contrôleur AD domain au cluster ou au SVM avant que le compte ne puisse accéder au SVM.
+
xref:enable-ad-users-groups-access-cluster-svm-task.adoc[Configuration de l'accès au contrôleur de domaine Active Directory]

+
Vous pouvez effectuer cette tâche avant ou après avoir activé l'accès au compte.

* À partir de ONTAP 9.13.1, vous pouvez utiliser une clé publique SSH comme méthode d'authentification principale ou secondaire avec un mot de passe utilisateur AD.
+
Si vous choisissez d'utiliser une clé publique SSH comme authentification principale, aucune authentification AD n'a lieu.

* A partir de ONTAP 9.11.1, vous pouvez utiliser link:../nfs-admin/ldap-fast-bind-nsswitch-authentication-task.html["Utiliser la liaison rapide LDAP pour l'authentification nsswitch pour les SVM NFS ONTAP"] si le serveur LDAP AD le prend en charge.
* Si vous n'êtes pas sûr du rôle de contrôle d'accès que vous souhaitez attribuer au compte de connexion, vous pouvez utiliser `security login modify` la commande pour ajouter le rôle ultérieurement. Pour en savoir plus, `security login modify` consultez le link:https://docs.netapp.com/us-en/ontap-cli/security-login-modify.html["Référence de commande ONTAP"^].
+
xref:modify-role-assigned-administrator-task.adoc[Modification du rôle attribué à un administrateur]




NOTE: L'accès au compte du groupe D'ANNONCES est pris en charge uniquement avec le `SSH`, `ontapi`, et `rest` en termes de latence. Les groupes AD ne sont pas pris en charge avec l'authentification de clé publique SSH, qui est couramment utilisée pour l'authentification multifacteur.

.Avant de commencer
* L'heure du cluster doit être synchronisée sur dans les cinq minutes qui suivent l'heure sur le contrôleur de domaine AD.
* Vous devez être un administrateur de cluster pour effectuer cette tâche.


.Étape
. Activer les comptes d'utilisateur ou d'administrateur de groupe AD pour accéder à un SVM :
+
*Pour les utilisateurs AD :*

+
[cols="1,1,1,4"]
|===
| Version ONTAP | Authentification principale | Authentification secondaire | Commande 


| 9.13.1 et versions ultérieures | Clé publique | Aucune  a| 
[listing]
----
security login create -vserver <svm_name> -user-or-group-name <user_name> -application ssh -authentication-method publickey -role <role>
----


| 9.13.1 et versions ultérieures | Domaine | Clé publique  a| 
*Pour un nouvel utilisateur*

[listing]
----
security login create -vserver <svm_name> -user-or-group-name <user_name> -application ssh -authentication-method domain -second-authentication-method publickey -role <role>
----
*Pour un utilisateur existant*

[listing]
----
security login modify -vserver <svm_name> -user-or-group-name <user_name> -application ssh -authentication-method domain -second-authentication-method publickey -role <role>
----


| 9.0 et versions ultérieures | Domaine | Aucune  a| 
[listing]
----
security login create -vserver <svm_name> -user-or-group-name <user_name> -application <application> -authentication-method domain -role <role> -comment <comment> [-is-ldap-fastbind true]
----
|===
+
*Pour les groupes AD :*

+
[cols="1,1,1,4"]
|===
| Version ONTAP | Authentification principale | Authentification secondaire | Commande 


| 9.0 et versions ultérieures | Domaine | Aucune  a| 
[listing]
----
security login create -vserver <svm_name> -user-or-group-name <user_name> -application <application> -authentication-method domain -role <role> -comment <comment> [-is-ldap-fastbind true]
----
|===


.Une fois que vous avez terminé
Si vous n'avez pas configuré l'accès au contrôleur AD domain au cluster ou au SVM, vous devez le faire avant que le compte puisse accéder au SVM.

xref:enable-ad-users-groups-access-cluster-svm-task.adoc[Configuration de l'accès au contrôleur de domaine Active Directory]
