---
permalink: authentication/index.html 
sidebar: sidebar 
keywords: decide, overview, administrator, authentication, rbac, role-based, access, control 
summary: 'Vous pouvez activer des comptes de connexion pour les administrateurs du cluster ONTAP et des serveurs virtuels de stockage. Vous pouvez également utiliser le contrôle d"accès basé sur des rôles pour définir les fonctionnalités des administrateurs.' 
---
= Authentification de l'administrateur et présentation du RBAC avec l'interface de ligne de commande
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez activer des comptes de connexion pour les administrateurs du cluster ONTAP et des serveurs virtuels de stockage. Vous pouvez également utiliser le contrôle d'accès basé sur des rôles pour définir les fonctionnalités des administrateurs.

Vous activez les comptes de connexion et le RBAC de l'une des manières suivantes :

* Vous souhaitez utiliser l'interface de ligne de commandes ONTAP et non System Manager, ni un outil de création de scripts automatisé.
* Vous voulez appliquer les bonnes pratiques, pas explorer toutes les options disponibles.
* Vous n'utilisez pas SNMP pour collecter des informations relatives au cluster.

