---
permalink: authentication/lock-unlock-user-account-task.html 
sidebar: sidebar 
keywords: lock, unlock, administrator account 
summary: Vous pouvez utiliser la commande de verrouillage de connexion de sécurité pour verrouiller un compte administrateur et la commande de déverrouillage de connexion de sécurité pour déverrouiller le compte. 
---
= Verrouiller et déverrouiller un compte d'administrateur ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vous pouvez utiliser le `security login lock` commande permettant de verrouiller un compte d'administrateur, et le `security login unlock` commande pour déverrouiller le compte.

.Avant de commencer
Pour effectuer ces tâches, vous devez être un administrateur de cluster.

.Étapes
. Verrouiller un compte administrateur :
+
`security login lock -vserver SVM_name -username user_name`

+
La commande suivante verrouille le compte administrateur `admin1` Pour la SVM ``vs1.example.com``:

+
[listing]
----
cluster1::>security login lock -vserver engData -username admin1
----
+
Pour en savoir plus, `security login lock` consultez le link:https://docs.netapp.com/us-en/ontap-cli/security-login-lock.html["Référence de commande ONTAP"^].

. Déverrouiller un compte administrateur :
+
`security login unlock -vserver SVM_name -username user_name`

+
La commande suivante déverrouille le compte administrateur `admin1` Pour la SVM ``vs1.example.com``:

+
[listing]
----
cluster1::>security login unlock -vserver engData -username admin1
----
+
Pour en savoir plus, `security login unlock` consultez le link:https://docs.netapp.com/us-en/ontap-cli/security-login-unlock.html["Référence de commande ONTAP"^].



Pour en savoir plus, `security login` consultez le link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+login["Référence de commande ONTAP"^].
