---
permalink: authentication/manage-public-key-authentication-concept.html 
sidebar: sidebar 
keywords: associate, public key, administrator account 
summary: 'Pour l"authentification de clé publique SSH, vous devez associer la clé publique à un compte d"administrateur avant que le compte puisse accéder à la SVM. Vous pouvez utiliser la commande de sécurité login publickey create pour associer une clé à un compte administrateur.' 
---
= Associer une clé publique à un compte d'administrateur
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pour l'authentification de clé publique SSH, vous devez associer la clé publique à un compte d'administrateur avant que le compte puisse accéder à la SVM. Vous pouvez utiliser le `security login publickey create` commande permettant d'associer une clé à un compte d'administrateur.

.Avant de commencer
* Vous devez avoir généré la clé SSH.
* Pour effectuer cette tâche, vous devez être un administrateur de cluster ou de SVM.


.Description de la tâche
Si vous authentifiez un compte via SSH avec un mot de passe et une clé publique SSH, le compte est authentifié d'abord par la clé publique.

.Étape
. Associer une clé publique à un compte d'administrateur :
+
`security login publickey create -vserver _SVM_name_ -username _user_name_ -index _index_ -publickey _certificate_ -comment _comment_`

+
Pour connaître la syntaxe complète de la commande, reportez-vous au link:config-worksheets-reference.html["feuille de calcul"].

+
link:config-worksheets-reference.html["Association d'une clé publique à un compte d'utilisateur"]

+
La commande suivante associe une clé publique au compte d'administrateur du SVM `svmadmin1` Pour la SVM ``engData1``. La clé publique est affectée à l'index numéro 5.

+
[listing]
----
cluster1::>security login publickey create -vserver engData1 -username svmadmin1 -index 5 -publickey
"ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAIEAspH64CYbUsDQCdW22JnK6J
/vU9upnKzd2zAk9C1f7YaWRUAFNs2Qe5lUmQ3ldi8AD0Vfbr5T6HZPCixNAIza
FciDy7hgnmdj9eNGedGr/JNrftQbLD1hZybX+72DpQB0tYWBhe6eDJ1oPLob
ZBGfMlPXh8VjeU44i7W4+s0hG0E=tsmith@publickey.example.com"
----

