---
sidebar: sidebar 
permalink: authentication/oauth2-external-roles.html 
keywords: oauth 2.0, oauth2, external roles, external role mapping 
summary: 'Un rôle externe est défini dans un fournisseur d"identification configuré pour une utilisation par ONTAP. Vous pouvez créer et gérer les relations de mappage entre ces rôles externes et les rôles ONTAP à l"aide de l"interface de ligne de commandes ONTAP.' 
---
= Mappage de rôles externes
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Un rôle externe est défini dans un fournisseur d'identification configuré pour une utilisation par ONTAP. Vous pouvez créer et gérer des relations de mappage entre ces rôles externes et les rôles ONTAP à l'aide de l'interface de ligne de commandes ONTAP.


NOTE: Vous pouvez également configurer la fonction de mappage de rôles externes à l'aide de l'API REST ONTAP. Pour en savoir plus, consultez le https://docs.netapp.com/us-en/ontap-automation/["Documentation sur l'automatisation ONTAP"^].



== Rôles externes dans un jeton d'accès

Voici un fragment d'un jeton d'accès JSON contenant deux rôles externes.

[listing]
----
  ...
  "appidacr": "1",
  "family_name": "User",
  "name": "Test User 1",
  "oid": "4c2215c7-6d52-40a7-ce71-096fa41379ba",
  "roles": [
    "Global Administrator",
    "Application Administrator"
  ],
  "ver": "1.0",
  ...
----


== Configuration

Vous pouvez utiliser l'interface de ligne de commande ONTAP pour administrer la fonction de mappage de rôle externe.



=== Création

Vous pouvez définir une configuration de mappage de rôles à l'aide de la `security login external-role-mapping create` commande. Vous devez être au niveau de privilège ONTAP *admin* pour exécuter cette commande ainsi que les options associées. Pour en savoir plus, `security login external-role-mapping create` consultez le link:https://docs.netapp.com/us-en/ontap-cli/security-login-external-role-mapping-create.html["Référence de commande ONTAP"^].

.Paramètres
Les paramètres utilisés pour créer un mappage de groupe sont décrits ci-dessous.

[cols="30,70"]
|===
| Paramètre | Description 


| `external-role` | Nom du rôle défini au niveau du fournisseur d'identité externe. 


| `provider` | Nom du fournisseur d'identité. Il doit s'agir de l'identifiant du système. 


| `ontap-role` | Indique le rôle ONTAP existant vers lequel le rôle externe est mappé. 
|===
.Exemple
[listing]
----
security login external-role-mapping create -external-role "Global Administrator" -provider entra -ontap-role admin
----


=== Autres opérations de l'interface de ligne de commande

La commande prend en charge plusieurs opérations supplémentaires, notamment :

* Afficher
* Modifier
* Supprimer


.Informations associées
* link:https://docs.netapp.com/us-en/ontap-cli/["Référence de commande ONTAP"^]

