---
permalink: authentication/predefined-roles-cluster-administrators-concept.html 
sidebar: sidebar 
keywords: predefined roles, cluster administrators 
summary: Les rôles prédéfinis des administrateurs du cluster doivent répondre à la plupart des besoins. Vous pouvez créer des rôles personnalisés selon vos besoins. Par défaut un administrateur de cluster se voit attribuer le rôle admin prédéfini. 
---
= Rôles prédéfinis pour les administrateurs du cluster ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Les rôles prédéfinis des administrateurs du cluster doivent répondre à la plupart des besoins. Vous pouvez créer des rôles personnalisés selon vos besoins. Par défaut un administrateur de cluster se voit attribuer le paramétrage prédéfini `admin` rôle.

Le tableau suivant répertorie les rôles prédéfinis pour les administrateurs du cluster :

|===


| Ce rôle... | Dispose de ce niveau d'accès... | Aux commandes ou répertoires de commandes suivants 


 a| 
admin
 a| 
tous
 a| 
Tous les répertoires de commandes (`DEFAULT`)



 a| 
admin-no-fsa (disponible à partir de ONTAP 9.12.1)
 a| 
Lecture/écriture
 a| 
* Tous les répertoires de commandes (`DEFAULT`)
* `security login rest-role`
* `security login role`




 a| 
Lecture seule
 a| 
* `security login rest-role create`
* `security login rest-role delete`
* `security login rest-role modify`
* `security login rest-role show`
* `security login role create`
* `security login role create`
* `security login role delete`
* `security login role modify`
* `security login role show`
* `volume activity-tracking`
* `volume analytics`




 a| 
Aucune
 a| 
`volume file show-disk-usage`



 a| 
AutoSupport
 a| 
tous
 a| 
* `set`
* `system node autosupport`




 a| 
Aucune
 a| 
Tous les autres répertoires de commandes (`DEFAULT`)



 a| 
sauvegarde
 a| 
tous
 a| 
`vserver services ndmp`



 a| 
lecture seule
 a| 
`volume`



 a| 
Aucune
 a| 
Tous les autres répertoires de commandes (`DEFAULT`)



 a| 
lecture seule
 a| 
tous
 a| 
* `security login password`
+
Pour la gestion du mot de passe local et des informations clés du compte utilisateur

* `set`




 a| 
* À partir de ONTAP 9.8, lecture seule
* Avant ONTAP 9.8, aucune

 a| 
`security`



 a| 
lecture seule
 a| 
Tous les autres répertoires de commandes (`DEFAULT`)



 a| 
SnapLock
 a| 
tous
 a| 
* `set`
* `volume create`
* `volume modify`
* `volume move`
* `volume show`




 a| 
Aucune
 a| 
* `volume move governor`
* `volume move recommend`




 a| 
Aucune
 a| 
Tous les autres répertoires de commandes (`DEFAULT`)



 a| 
Aucune
 a| 
Aucune
 a| 
Tous les répertoires de commandes (`DEFAULT`)

|===

NOTE: Le `autosupport` le rôle est affecté au prédéfini `autosupport` Compte, utilisé par AutoSupport OnDemand. ONTAP vous empêche de modifier ou de supprimer le `autosupport` compte. ONTAP vous empêche également d'attribuer le `autosupport` rôle vers d'autres comptes utilisateur.
